{
  "abstract": [
    {
      "text": "An abstract base class for interface templates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPTemplate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPTemplate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPTemplate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CPTemplate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CPTemplate",
              "type": "codeVoice"
            },
            {
              "text": " is an abstract base class for defining CarPlay user interface templates. It provides the common functionality present in all templates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t use this class directly, or create your own subclasses. Instead, you must use one of the prebuilt templates, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPActionSheetTemplate": {
      "abstract": [
        {
          "text": "A template that displays a modal action sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPActionSheetTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPActionSheetTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPActionSheetTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPActionSheetTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpactionsheettemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPAlertTemplate": {
      "abstract": [
        {
          "text": "A template that displays a modal alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPAlertTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPAlertTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPAlertTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPAlertTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpalerttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding": {
      "abstract": [
        {
          "text": "The methods that templates use to provide buttons for the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPBarButtonProviding"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPBarButtonProviding"
        }
      ],
      "role": "symbol",
      "title": "CPBarButtonProviding",
      "type": "topic",
      "url": "/documentation/carplay/cpbarbuttonproviding"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPContactTemplate": {
      "abstract": [
        {
          "text": "A template that displays information about a person or a business.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPContactTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPContactTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPContactTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPContactTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpcontacttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate": {
      "abstract": [
        {
          "text": "A template that displays and manages a grid of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPGridTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPGridTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPGridTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpgridtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate": {
      "abstract": [
        {
          "text": "A template that provides information for a point of interest, food order, parking location, or charging location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPInformationTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPInformationTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPInformationTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpinformationtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate": {
      "abstract": [
        {
          "text": "A template that displays and manages a list of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPListTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPListTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cplisttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate": {
      "abstract": [
        {
          "text": "A shared system template that displays Now Playing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate": {
      "abstract": [
        {
          "text": "A template that displays a map with selectable points of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPPointOfInterestTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPPointOfInterestTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cppointofinteresttemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate": {
      "abstract": [
        {
          "text": "A template that provides the ability to search for a destination and see a list of search results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSearchTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSearchTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPSearchTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpsearchtemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate": {
      "abstract": [
        {
          "text": "A container template that displays and manages other templates, presenting them as tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTabBarTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTabBarTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPTabBarTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cptabbartemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate": {
      "abstract": [
        {
          "text": "An abstract base class for interface templates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/showsTabBadge": {
      "abstract": [
        {
          "text": "An indicator you use to call attention to the tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsTabBadge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/showsTabBadge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsTabBadge"
        }
      ],
      "role": "symbol",
      "title": "showsTabBadge",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate/showstabbadge"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabImage": {
      "abstract": [
        {
          "text": "An image that represents the content of the tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabImage"
        }
      ],
      "role": "symbol",
      "title": "tabImage",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate/tabimage"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabSystemItem": {
      "abstract": [
        {
          "text": "A system object that provides a title and image for common tab content, such as contacts or favorites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabSystemItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarItem",
          "text": "UITabBarItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITabBarSystemItem",
          "text": "SystemItem"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabSystemItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabSystemItem"
        }
      ],
      "role": "symbol",
      "title": "tabSystemItem",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate/tabsystemitem"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabTitle": {
      "abstract": [
        {
          "text": "A short title that describes the content of the tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabTitle"
        }
      ],
      "role": "symbol",
      "title": "tabTitle",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate/tabtitle"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/userInfo": {
      "abstract": [
        {
          "text": "Any custom data or object that you want to associate with the template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/userInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInfo"
        }
      ],
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/carplay/cptemplate/userinfo"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate": {
      "abstract": [
        {
          "text": "A template that displays a voice control indicator during audio input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPVoiceControlTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPVoiceControlTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPVoiceControlTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpvoicecontroltemplate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPActionSheetTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPAlertTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPContactTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-Purpose-Templates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate",
        "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding"
      ],
      "title": "General Purpose Templates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Template-Information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/userInfo"
      ],
      "title": "Accessing Template Information"
    },
    {
      "anchor": "Accessing-Tab-Information",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabTitle",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabImage",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabSystemItem",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/showsTabBadge"
      ],
      "title": "Accessing Tab Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPTemplate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Template-Information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/userInfo"
              ],
              "title": "Accessing Template Information"
            },
            {
              "anchor": "Accessing-Tab-Information",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabTitle",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabImage",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/tabSystemItem",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplate/showsTabBadge"
              ],
              "title": "Accessing Tab Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPActionSheetTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPAlertTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPContactTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPInformationTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPPointOfInterestTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPSearchTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPVoiceControlTemplate"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-Purpose-Templates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPListTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPGridTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPTabBarTemplate",
                "doc://com.apple.carplay/documentation/CarPlay/CPBarButtonProviding"
              ],
              "title": "General Purpose Templates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabImage/title",
          "value": "tabImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAlertTemplate/title",
          "value": "CPAlertTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAlertTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAlertTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPAlertTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPAlertTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPContactTemplate/title",
          "value": "CPContactTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPContactTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPContactTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPContactTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPContactTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/title",
          "value": "CPSearchTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSearchTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSearchTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1showsTabBadge/title",
          "value": "showsTabBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1showsTabBadge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsTabBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabSystemItem/title",
          "value": "tabSystemItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabSystemItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPGridTemplate/title",
          "value": "CPGridTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPGridTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPGridTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPGridTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPGridTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPActionSheetTemplate/title",
          "value": "CPActionSheetTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPActionSheetTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPActionSheetTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPActionSheetTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPActionSheetTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/title",
          "value": "CPBarButtonProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPBarButtonProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPBarButtonProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/title",
          "value": "CPInformationTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPInformationTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPInformationTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/title",
          "value": "CPNowPlayingTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabTitle/title",
          "value": "tabTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1tabTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tabTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTabBarTemplate/title",
          "value": "CPTabBarTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTabBarTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTabBarTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTabBarTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTabBarTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1userInfo/title",
          "value": "userInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate~1userInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/title",
          "value": "CPPointOfInterestTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPPointOfInterestTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPointOfInterestTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/title",
          "value": "CPVoiceControlTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPVoiceControlTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPVoiceControlTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPVoiceControlTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplate/title",
          "value": "CPListTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPListTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPListTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/title",
          "value": "CPTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cptemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cptemplate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
