{
  "abstract": [
    {
      "text": "The methods for responding to the life cycle events of your app’s scene.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPTemplateApplicationSceneDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CPTemplateApplicationSceneDelegate"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CPTemplateApplicationSceneDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "CPTemplateApplicationSceneDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UISceneDelegate",
              "text": "UISceneDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This protocol defines methods that CarPlay calls when the scene connects and disconnects, as well as methods for responding to certain user actions. Use your implementation to provide the appropriate behavior for when these events occur. For example, creating and setting your root template when CarPlay launches your app and connects its scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create instances of your scene delegate directly. Instead, you specify the name of the class as part of the CarPlay scene configuration you add to your ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file—see the example below—or that you return from your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "  method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>CPTemplateApplicationSceneSessionRoleApplication</key>",
            "<array> ",
            "    <dict>",
            "        <key>UISceneClassName</key>",
            "        <string>CPTemplateApplicationScene</string>",
            "        <key>UISceneConfigurationName</key>",
            "        <string>MyCarPlaySceneConfiguration</string>",
            "        <!-- Specify the name of your scene delegate class. --> ",
            "        <key>UISceneDelegateClassName</key>",
            "        <string>MyCarPlaySceneDelegate</string> ",
            "    </dict>",
            "</array>"
          ],
          "syntax": "plist",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration": {
      "abstract": [
        {
          "text": "An object that provides vehicle properties and configuration for the CarPlay environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSessionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSessionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPSessionConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpsessionconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene": {
      "abstract": [
        {
          "text": "A CarPlay scene that controls your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationScene"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationScene"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationScene",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscene"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate": {
      "abstract": [
        {
          "text": "The methods for responding to the life cycle events of your app’s scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationSceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationSceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationSceneDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/contentStyleDidChange(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentStyleDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceStyle",
          "text": "UIUserInterfaceStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/contentStyleDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentStyleDidChange:"
        }
      ],
      "role": "symbol",
      "title": "contentStyleDidChange(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/contentstyledidchange(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a CarPlay scene to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didConnectInterfaceController:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didConnect:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didconnect:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a CarPlay scene to your navigation app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPWindow",
          "text": "CPWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didConnectInterfaceController:toWindow:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didConnect:to:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didconnect:to:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnect:from:)": {
      "abstract": [
        {
          "text": "Tells the delegate when CarPlay removes a scene from your navigation app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDisconnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPWindow",
          "text": "CPWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnect:from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didDisconnectInterfaceController:fromWindow:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didDisconnect:from:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:diddisconnect:from:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnectInterfaceController:)": {
      "abstract": [
        {
          "text": "Tells the delegate when CarPlay removes a scene from the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDisconnectInterfaceController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnectInterfaceController:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didDisconnectInterfaceController:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didDisconnectInterfaceController:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:diddisconnectinterfacecontroller:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-5rf2h": {
      "abstract": [
        {
          "text": "Tells the delegate when the user selects a maneuver while the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPManeuver",
          "text": "CPManeuver"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-5rf2h",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didSelectManeuver:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didselect:)-5rf2h"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-7bie0": {
      "abstract": [
        {
          "text": "Tells the delegate when the user selects a navigation alert while the app is in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPNavigationAlert",
          "text": "CPNavigationAlert"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-7bie0",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didSelectNavigationAlert:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didselect:)-7bie0"
    },
    "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay": {
      "abstract": [
        {
          "text": "Use scenes to present your app’s content on the vehicle’s built-in screen.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay",
      "kind": "article",
      "role": "article",
      "title": "Displaying Content in CarPlay",
      "type": "topic",
      "url": "/documentation/carplay/displaying-content-in-carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements": {
      "abstract": [
        {
          "text": "Configure your CarPlay-enabled app with the entitlements it requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
      "kind": "article",
      "role": "article",
      "title": "Requesting CarPlay Entitlements",
      "type": "topic",
      "url": "/documentation/carplay/requesting-carplay-entitlements"
    },
    "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios": {
      "abstract": [
        {
          "text": "Make your CarPlay-enabled apps compatible with older system versions, such as iOS 13 and earlier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
      "kind": "article",
      "role": "article",
      "title": "Supporting Previous Versions of iOS",
      "type": "topic",
      "url": "/documentation/carplay/supporting-previous-versions-of-ios"
    },
    "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator": {
      "abstract": [
        {
          "text": "Configure Simulator to run and debug your CarPlay-enabled app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
      "kind": "article",
      "role": "article",
      "title": "Using the CarPlay Simulator",
      "type": "topic",
      "url": "/documentation/carplay/using-the-carplay-simulator"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)": {
      "abstract": [
        {
          "text": "Retrieves the configuration data for UIKit to use when creating a new scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "optional"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "application"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configurationForConnecting"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "connectingSceneSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneConnectionOptions",
          "text": "ConnectionOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneConfiguration",
          "text": "UISceneConfiguration"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "application(_:configurationForConnecting:options:)",
      "type": "topic",
      "url": "/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate": {
      "abstract": [
        {
          "text": "The core methods you use to respond to life-cycle events occurring within a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISceneDelegate",
      "type": "topic",
      "url": "/documentation/UIKit/UISceneDelegate"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Integration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
        "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay",
        "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
        "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
        "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration"
      ],
      "title": "CarPlay Integration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-the-Scene-Life-Cycle",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnectInterfaceController:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnect:from:)"
      ],
      "title": "Responding to the Scene Life Cycle"
    },
    {
      "anchor": "Responding-to-User-Actions",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-5rf2h",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-7bie0"
      ],
      "title": "Responding to User Actions"
    },
    {
      "anchor": "Instance-Methods",
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/contentStyleDidChange(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CPTemplateApplicationSceneDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-the-Scene-Life-Cycle",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnectInterfaceController:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didDisconnect:from:)"
              ],
              "title": "Responding to the Scene Life Cycle"
            },
            {
              "anchor": "Responding-to-User-Actions",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-5rf2h",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didSelect:)-7bie0"
              ],
              "title": "Responding to User Actions"
            },
            {
              "anchor": "Instance-Methods",
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/contentStyleDidChange(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Integration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
                "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay",
                "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
                "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
                "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration"
              ],
              "title": "CarPlay Integration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CPTemplateApplicationSceneDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UISceneDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UISceneDelegate",
                    "text": "UISceneDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didSelect:)-7bie0/title",
          "value": "templateApplicationScene:didSelectNavigationAlert:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didSelect:)-7bie0/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didSelectNavigationAlert:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/title",
          "value": "CPTemplateApplicationSceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UISceneDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:)/title",
          "value": "templateApplicationScene:didConnectInterfaceController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didConnectInterfaceController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didSelect:)-5rf2h/title",
          "value": "templateApplicationScene:didSelectManeuver:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didSelect:)-5rf2h/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didSelectManeuver:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1contentStyleDidChange(_:)/title",
          "value": "contentStyleDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1contentStyleDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentStyleDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/title",
          "value": "application:configurationForConnectingSceneSession:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneConfiguration",
              "text": "UISceneConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "identifier",
              "text": "application:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIApplication",
              "text": "UIApplication"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "application"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationForConnectingSceneSession:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneSession",
              "text": "UISceneSession"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "connectingSceneSession"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneConnectionOptions",
              "text": "UISceneConnectionOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didDisconnectInterfaceController:)/title",
          "value": "templateApplicationScene:didDisconnectInterfaceController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didDisconnectInterfaceController:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didDisconnectInterfaceController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:to:)/title",
          "value": "templateApplicationScene:didConnectInterfaceController:toWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didConnectInterfaceController:toWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/title",
          "value": "CPTemplateApplicationScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didDisconnect:from:)/title",
          "value": "templateApplicationScene:didDisconnectInterfaceController:fromWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didDisconnect:from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didDisconnectInterfaceController:fromWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/title",
          "value": "CPSessionConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSessionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSessionConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cptemplateapplicationscenedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cptemplateapplicationscenedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
