{
  "abstract": [
    {
      "text": "Use scenes to present your app’s content on the vehicle’s built-in screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/displaying-content-in-carplay"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Displaying Content in CarPlay"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A scene manages your CarPlay-enabled app’s user interface, including the window that CarPlay displays on the vehicle’s screen. Navigation apps are the only app category that have access to this window, and use it to draw their map content. All other categories of apps use only the scene’s interface controller to manage their user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "As CarPlay manages your app’s scene, you provide a scene delegate — an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol — that the system notifies about scene life cycle events. CarPlay creates your app’s scene and scene delegate when the user launches your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-CarPlay-Scene",
          "level": 3,
          "text": "Add a CarPlay Scene",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To add a CarPlay scene, provide its configuration in the scene manifest of your Xcode project’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file. Specify your scene delegate’s class name as the value of the ",
              "type": "text"
            },
            {
              "code": "UISceneDelegateClassName",
              "type": "codeVoice"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>UIApplicationSceneManifest</key>",
            "<dict>",
            "    <key>UIApplicationSupportsMultipleScenes</key>",
            "    <true/>",
            "    <key>UISceneConfigurations</key>",
            "    <dict>",
            "        <key>CPTemplateApplicationSceneSessionRoleApplication</key>",
            "        <array> ",
            "            <dict>",
            "                <key>UISceneClassName</key>",
            "                <string>CPTemplateApplicationScene</string>",
            "                <key>UISceneConfigurationName</key>",
            "                <string>MyCarPlaySceneConfiguration</string>",
            "                <key>UISceneDelegateClassName</key>",
            "                <string>MyCarPlaySceneDelegate</string> ",
            "            </dict>",
            "        </array>",
            "    </dict>",
            "</dict>     "
          ],
          "syntax": "plist",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In your scene delegate, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and use the interface controller that it provides to set your root template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func templateApplicationScene(_ templateApplicationScene: CPTemplateApplicationScene, ",
                    "    didConnect interfaceController: CPInterfaceController) {",
                    "    ",
                    "    // Store a reference to the interface controller so ",
                    "    // you can add and remove templates as the user ",
                    "    // interacts with your app.",
                    "    self.interfaceController = interfaceController",
                    "    ",
                    "    // Create a template and set it as the root.",
                    "    let rootTemplate = self.makeRootTemplate()",
                    "    interfaceController.setRootTemplate(rootTemplate, animated: true, ",
                    "        completion: nil)",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene ",
                    "   didConnectInterfaceController:(CPInterfaceController *)interfaceController {",
                    "    ",
                    "    // Store a reference to the interface controller so ",
                    "    // you can add and remove templates as the user ",
                    "    // interacts with your app.",
                    "    self.interfaceController = interfaceController;",
                    "    ",
                    "    // Create a template and set it as the root.",
                    "    CPTemplate *rootTemplate = [self makeRootTemplate];",
                    "    [self.interfaceController setRootTemplate:rootTemplate ",
                    "                                     animated:YES",
                    "                                   completion:NULL];",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Obj-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "If your app specifies the navigation entitlement, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead because it provides a reference to your app’s window that CarPlay manages. Create an instance of your map-drawing view controller and set it as the window’s root view controller. Make sure that you set your interface controller’s root template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func templateApplicationScene(_ templateApplicationScene: CPTemplateApplicationScene, ",
                    "    didConnect interfaceController: CPInterfaceController, to window: CPWindow) {",
                    "    ",
                    "    // Retain references to the interface controller and window for",
                    "    // the entire duration of the CarPlay session.",
                    "    self.interfaceController = interfaceController",
                    "    self.carWindow = window",
                    "    ",
                    "    // Assign the window's root view controller to the view controller",
                    "    // that draws your map content.",
                    "    window.rootViewController = MapRenderingViewController()",
                    "    ",
                    "    // Create a map template and set it as the root.",
                    "    let mapTemplate = self.makeMapTemplate()",
                    "    interfaceController.setRootTemplate(mapTemplate, animated: true, ",
                    "        completion: nil)",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)templateApplicationScene:(CPTemplateApplicationScene *)templateApplicationScene ",
                    "   didConnectInterfaceController:(CPInterfaceController *)interfaceController ",
                    "                        toWindow:(CPWindow *)window {",
                    "    ",
                    "    // Retain references to the interface controller and window for",
                    "    // the entire duration of the CarPlay session.",
                    "    self.interfaceController = interfaceController;",
                    "    self.carWindow = window;",
                    "    ",
                    "    // Assign the window's root view controller to the view controller",
                    "    // that draws your map content.",
                    "    window.rootViewController = [[MapRenderingViewController alloc] init];",
                    "    ",
                    "    // Create a map template and set it as the root.",
                    "    CPMapTemplate *mapTemplate = [self makeMapTemplate];",
                    "    [interfaceController setRootTemplate:mapTemplate ",
                    "                                animated:YES",
                    "                              completion:NULL];",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Obj-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use the window’s root view controller to draw only map content. Don’t render alerts, overlays, or any other user interface elements. Use only the templates that the framework provides to create your app’s CarPlay user interface.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Add-a-CarPlay-Dashboard-Scene",
          "level": 3,
          "text": "Add a CarPlay Dashboard Scene",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Navigation apps can add an additional scene entry to their scene manifest to enable their maps, upcoming maneuvers, and shortcut buttons to appear in the CarPlay Dashboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Add the following key to the ",
              "type": "text"
            },
            {
              "code": "UIApplicationSceneManifest",
              "type": "codeVoice"
            },
            {
              "text": " dictionary in your Xcode project’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file to specify that your app supports the CarPlay Dashboard:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>UIApplicationSceneManifest</key>",
            "<dict>",
            "    <key>CPSupportsDashboardNavigationScene</key>",
            "    <true/>",
            "</dict>"
          ],
          "syntax": "plist",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In the same file, add the CarPlay Dashboard scene configuration to the ",
              "type": "text"
            },
            {
              "code": "UISceneConfigurations",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. Provide your dashboard scene delegate’s class name as the value of the ",
              "type": "text"
            },
            {
              "code": "UISceneDelegateClassName",
              "type": "codeVoice"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>CPTemplateApplicationDashboardSceneSessionRoleApplication</key>",
            "<array> ",
            "    <dict>",
            "        <key>UISceneClassName</key>",
            "        <string>CPTemplateApplicationDashboardScene</string>",
            "        <key>UISceneConfigurationName</key>",
            "        <string>MyCarPlayDashboardSceneConfiguration</string>",
            "        <key>UISceneDelegateClassName</key>",
            "        <string>MyCarPlayDashboardSceneDelegate</string> ",
            "    </dict>",
            "</array>"
          ],
          "syntax": "plist",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The names of the dashboard scene’s session role and scene class are different from the standard CarPlay scene. If the CarPlay Dashboard doesn’t display your navigation app, make sure that you’re using the correct names.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In your dashboard scene delegate, implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate/templateApplicationDashboardScene(_:didConnect:to:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Use the window that the method provides to render your map content. Set the dashboard controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPDashboardController/shortcutButtons",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to an array of buttons — up to a maximum of two — that the CarPlay Dashboard displays when your app isn’t actively navigating.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func templateApplicationDashboardScene(_ templateApplicationDashboardScene: CPTemplateApplicationDashboardScene,",
                    "    didConnect dashboardController: CPDashboardController, to window: UIWindow) {",
                    "    ",
                    "    // Retain references to the dashboard controller and window for",
                    "    // the entire duration of the CarPlay Dashboard session.",
                    "    self.dashboardController = dashboardController",
                    "    self.dashboardWindow = window",
                    "    ",
                    "    // Assign the window's root view controller to the view controller",
                    "    // that draws your map content.",
                    "    window.rootViewController = MapRenderingViewController()",
                    "    ",
                    "    // Create your shortcut buttons and add them to the dashboard.",
                    "    dashboardController.shortcutButtons = makeShortcutButtons()",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "-(void)templateApplicationDashboardScene:(CPTemplateApplicationDashboardScene*)templateApplicationDashboardScene",
                    "           didConnectDashboardController:(CPDashboardController *)dashboardController ",
                    "                                toWindow:(UIWindow *)window {",
                    "    ",
                    "    // Retain references to the dashboard controller and window for",
                    "    // the entire duration of the CarPlay Dashboard session.",
                    "    self.dashboardController = dashboardController;",
                    "    self.dashboardWindow = window;",
                    "    ",
                    "    // Assign the window's root view controller to the view controller",
                    "    // that draws your map content.",
                    "    window.rootViewController = [[MapRenderingViewController alloc] init];",
                    "    ",
                    "    // Create your shortcut buttons and add them to the dashboard.",
                    "    dashboardController.shortcutButtons = [self makeShortcutButtons];",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Obj-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPDashboardController/shortcutButtons": {
      "abstract": [
        {
          "text": "An array of shortcut buttons to display on the CarPlay Dashboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shortcutButtons"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPDashboardButton",
          "text": "CPDashboardButton"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPDashboardController/shortcutButtons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shortcutButtons"
        }
      ],
      "role": "symbol",
      "title": "shortcutButtons",
      "type": "topic",
      "url": "/documentation/carplay/cpdashboardcontroller/shortcutbuttons"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration": {
      "abstract": [
        {
          "text": "An object that provides vehicle properties and configuration for the CarPlay environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPSessionConfiguration"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPSessionConfiguration"
        }
      ],
      "role": "symbol",
      "title": "CPSessionConfiguration",
      "type": "topic",
      "url": "/documentation/carplay/cpsessionconfiguration"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate/templateApplicationDashboardScene(_:didConnect:to:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a CarPlay Dashboard scene to your navigation app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationDashboardScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationDashboardScene",
          "text": "CPTemplateApplicationDashboardScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPDashboardController",
          "text": "CPDashboardController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationDashboardSceneDelegate/templateApplicationDashboardScene(_:didConnect:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationDashboardScene:didConnectDashboardController:toWindow:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationDashboardScene(_:didConnect:to:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationdashboardscenedelegate/templateapplicationdashboardscene(_:didconnect:to:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene": {
      "abstract": [
        {
          "text": "A CarPlay scene that controls your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationScene"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationScene"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationScene",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscene"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate": {
      "abstract": [
        {
          "text": "The methods for responding to the life cycle events of your app’s scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationSceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTemplateApplicationSceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPTemplateApplicationSceneDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a CarPlay scene to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didConnectInterfaceController:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didConnect:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didconnect:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a CarPlay scene to your navigation app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "templateApplicationScene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPTemplateApplicationScene",
          "text": "CPTemplateApplicationScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didConnect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPInterfaceController",
          "text": "CPInterfaceController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPWindow",
          "text": "CPWindow"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate/templateApplicationScene(_:didConnect:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "templateApplicationScene:didConnectInterfaceController:toWindow:"
        }
      ],
      "role": "symbol",
      "title": "templateApplicationScene(_:didConnect:to:)",
      "type": "topic",
      "url": "/documentation/carplay/cptemplateapplicationscenedelegate/templateapplicationscene(_:didconnect:to:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements": {
      "abstract": [
        {
          "text": "Configure your CarPlay-enabled app with the entitlements it requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
      "kind": "article",
      "role": "article",
      "title": "Requesting CarPlay Entitlements",
      "type": "topic",
      "url": "/documentation/carplay/requesting-carplay-entitlements"
    },
    "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios": {
      "abstract": [
        {
          "text": "Make your CarPlay-enabled apps compatible with older system versions, such as iOS 13 and earlier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
      "kind": "article",
      "role": "article",
      "title": "Supporting Previous Versions of iOS",
      "type": "topic",
      "url": "/documentation/carplay/supporting-previous-versions-of-ios"
    },
    "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator": {
      "abstract": [
        {
          "text": "Configure Simulator to run and debug your CarPlay-enabled app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
      "kind": "article",
      "role": "article",
      "title": "Using the CarPlay Simulator",
      "type": "topic",
      "url": "/documentation/carplay/using-the-carplay-simulator"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "CarPlay-Integration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
        "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
        "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
        "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate",
        "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration"
      ],
      "title": "CarPlay Integration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "CarPlay-Integration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/requesting-carplay-entitlements",
                "doc://com.apple.carplay/documentation/CarPlay/supporting-previous-versions-of-ios",
                "doc://com.apple.carplay/documentation/CarPlay/using-the-carplay-simulator",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationScene",
                "doc://com.apple.carplay/documentation/CarPlay/CPTemplateApplicationSceneDelegate",
                "doc://com.apple.carplay/documentation/CarPlay/CPSessionConfiguration"
              ],
              "title": "CarPlay Integration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/title",
          "value": "CPTemplateApplicationSceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationSceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/title",
          "value": "CPTemplateApplicationScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTemplateApplicationScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:to:)/title",
          "value": "templateApplicationScene:didConnectInterfaceController:toWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didConnectInterfaceController:toWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:)/title",
          "value": "templateApplicationScene:didConnectInterfaceController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationSceneDelegate~1templateApplicationScene(_:didConnect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationScene:didConnectInterfaceController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPDashboardController~1shortcutButtons/title",
          "value": "shortcutButtons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPDashboardController~1shortcutButtons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shortcutButtons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardSceneDelegate~1templateApplicationDashboardScene(_:didConnect:to:)/title",
          "value": "templateApplicationDashboardScene:didConnectDashboardController:toWindow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTemplateApplicationDashboardSceneDelegate~1templateApplicationDashboardScene(_:didConnect:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "templateApplicationDashboardScene:didConnectDashboardController:toWindow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/title",
          "value": "CPSessionConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSessionConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPSessionConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPSessionConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/displaying-content-in-carplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/displaying-content-in-carplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
