{
  "abstract": [
    {
      "text": "Configure your music app to work with CarPlay by displaying a custom UI.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/integrating-carplay-with-your-music-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Integrating CarPlay with Your Music App"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "CarPlay Music is a sample music app that demonstrates how to display a custom UI from a CarPlay–enabled vehicle. CarPlay Music integrates with the CarPlay framework by implementing the  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPNowPlayingTemplate",
              "isActive": true,
              "overridingTitle": "CPNowPlayingTemplate",
              "overridingTitleInlineContent": [
                {
                  "code": "CPNowPlayingTemplate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPListTemplate",
              "isActive": true,
              "overridingTitle": "CPListTemplate",
              "overridingTitleInlineContent": [
                {
                  "code": "CPListTemplate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ". This sample’s iOS app component provides a logging interface to help you understand the life cycle of a CarPlay app, as well as a music controller.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-Sample-Code-Project",
          "level": 3,
          "text": "Configure the Sample Code Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To configure the sample code project, perform the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Complete the steps in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CarPlay/requesting-carplay-entitlements",
                      "isActive": true,
                      "overridingTitle": "Requesting CarPlay Entitlements",
                      "overridingTitleInlineContent": [
                        {
                          "text": "Requesting CarPlay Entitlements",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " to request the CarPlay audio entitlement and configure the Xcode project.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a key and developer token for the ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/musickit",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " service. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AppleMusicAPI/generating-developer-tokens",
                      "isActive": true,
                      "overridingTitle": "Getting Keys and Creating Tokens",
                      "overridingTitleInlineContent": [
                        {
                          "text": "Getting Keys and Creating Tokens",
                          "type": "text"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update the ",
                      "type": "text"
                    },
                    {
                      "code": "developerToken",
                      "type": "codeVoice"
                    },
                    {
                      "text": " variable in the ",
                      "type": "text"
                    },
                    {
                      "code": "AppleMusicAPIController.swift",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file to use the developer token you create.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Handle-Communication-with-CarPlay",
          "level": 3,
          "text": "Handle Communication with CarPlay",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The app is responsible for adding and removing the root view controller of the CarPlay window in response to connections and disconnections.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows an example implementation of setting a root template:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var tabTemplates = [CPTemplate]()",
            "",
            "if let playlists = MediaPlayerUtilities.searchForPlaylistsInLocalLibrary(withPredicate: nil) {",
            "    ",
            "    let listItems = playlists.compactMap { (playlist) -> CPListItem? in",
            "        let listItem = CPListItem(text: playlist.name, detailText: \"\")",
            "        listItem.handler = { playlistItem, completion in",
            "            AppleMusicAPIController.playWithItems(items: playlist.items.compactMap({ (item) -> String? in",
            "                return item.playbackStoreID",
            "            }))",
            "            completion()",
            "        }",
            "        return listItem",
            "    }",
            "    ",
            "    var playlistTemplate: CPListTemplate!",
            "    ",
            "    if #available(iOS 15.0, *) {",
            "        let configuration = CPAssistantCellConfiguration(",
            "                            position: .top,",
            "                            visibility: .always,",
            "                            assistantAction: .playMedia)",
            "        playlistTemplate = CPListTemplate(",
            "                            title: \"Playlists\",",
            "                            sections: [CPListSection(items: listItems)],",
            "                            assistantCellConfiguration: configuration)",
            "                        ",
            "    } else {",
            "        playlistTemplate = CPListTemplate(",
            "                            title: \"Playlists\",",
            "                            sections: [CPListSection(items: listItems)])",
            "                        ",
            "    }",
            "    ",
            "    playlistTemplate.tabImage = UIImage(systemName: \"list.star\")",
            "    ",
            "    tabTemplates.append(playlistTemplate)",
            "}",
            "",
            "tabTemplates.append(genresTemplate())",
            "tabTemplates.append(settingsTemplate())",
            "",
            "self.carplayInterfaceController!.delegate = self",
            "self.carplayInterfaceController!.setRootTemplate(CPTabBarTemplate(templates: tabTemplates), animated: true, completion: nil)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Prepare-for-App-Selection",
          "level": 3,
          "text": "Prepare for App Selection",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Like other Music apps, CarPlay Music is eligible to participate in App Selection to improve its interactions with Siri. This allows the system to automatically select the app for playing music on the device. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
              "isActive": true,
              "overridingTitle": "Improving Siri Media Interaction and App Selection",
              "overridingTitleInlineContent": [
                {
                  "code": "Improving Siri Media Interaction and App Selection",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code demonstrates how to declare an app as eligible for App Selection:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let context = INMediaUserContext()",
            "context.numberOfLibraryItems = MPMediaQuery.songs().items?.count",
            "AppleMusicAPIController.sharedController.prepareForRequests { (success) in",
            "    if success {",
            "        context.subscriptionStatus = .subscribed",
            "    } else {",
            "        context.subscriptionStatus = .notSubscribed",
            "    }",
            "    context.becomeCurrent()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Listen-for-Changes-with-the-Music-Player",
          "level": 3,
          "text": "Listen for Changes with the Music Player",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A good way to ensure an app UI updates automatically in response to changes is to listen for changes in the Now Playing item, as well as in the playing state. CarPlay Music uses the ",
              "type": "text"
            },
            {
              "code": "applicationMusicPlayer",
              "type": "codeVoice"
            },
            {
              "text": ", so it subscribes to the ",
              "type": "text"
            },
            {
              "code": "MPMusicPlayerControllerPlaybackStateDidChange",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "MPMusicPlayerControllerNowPlayingItemDidChange",
              "type": "codeVoice"
            },
            {
              "text": " notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "self.playbackObserver = NotificationCenter.default.addObserver(",
            "    forName: .MPMusicPlayerControllerPlaybackStateDidChange,",
            "    object: nil,",
            "    queue: .main) {",
            "    notification in",
            "    MemoryLogger.shared.appendEvent(",
            "        \"MPMusicPlayerControllerPlaybackStateDidChange: \\(MPMusicPlayerController.applicationQueuePlayer.playbackState)\")",
            "}",
            "",
            "self.nowPlayingItemObserver = NotificationCenter.default.addObserver(",
            "    forName: .MPMusicPlayerControllerNowPlayingItemDidChange,",
            "    object: nil,",
            "    queue: .main) {",
            "    notification in",
            "    MemoryLogger.shared.appendEvent(\"MPMusicPlayerControllerNowPlayingItemDidChange\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate": {
      "abstract": [
        {
          "text": "A shared system template that displays Now Playing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPNowPlayingTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpnowplayingtemplate"
    },
    "doc://com.apple.documentation/documentation/AppleMusicAPI/generating-developer-tokens": {
      "abstract": [
        {
          "text": "Generate a developer token needed to make requests to Apple Music API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppleMusicAPI/generating-developer-tokens",
      "kind": "article",
      "role": "article",
      "title": "Generating Developer Tokens",
      "type": "topic",
      "url": "/documentation/AppleMusicAPI/generating-developer-tokens"
    },
    "doc://com.apple.documentation/documentation/CarPlay/CPListTemplate": {
      "abstract": [
        {
          "text": "A template that displays and manages a list of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPListTemplate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPListTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CPListTemplate",
      "type": "topic",
      "url": "/documentation/CarPlay/CPListTemplate"
    },
    "doc://com.apple.documentation/documentation/CarPlay/CPNowPlayingTemplate": {
      "abstract": [
        {
          "text": "A shared system template that displays Now Playing information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPNowPlayingTemplate"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CarPlay/CPNowPlayingTemplate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CPNowPlayingTemplate",
      "type": "topic",
      "url": "/documentation/CarPlay/CPNowPlayingTemplate"
    },
    "doc://com.apple.documentation/documentation/CarPlay/requesting-carplay-entitlements": {
      "abstract": [
        {
          "text": "Configure your CarPlay-enabled app with the entitlements it requires.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CarPlay/requesting-carplay-entitlements",
      "kind": "article",
      "role": "article",
      "title": "Requesting CarPlay Entitlements",
      "type": "topic",
      "url": "/documentation/CarPlay/requesting-carplay-entitlements"
    },
    "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection": {
      "abstract": [
        {
          "text": "Fine-tune voice controls and improve Siri Suggestions by sharing app capabilities, customized names, and listening habits with the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SiriKit/improving-siri-media-interactions-and-app-selection",
      "kind": "article",
      "role": "article",
      "title": "Improving Siri Media Interactions and App Selection",
      "type": "topic",
      "url": "/documentation/SiriKit/improving-siri-media-interactions-and-app-selection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "f5c58cac38e6/IntegratingCarPlayWithYourMusicApp.zip": {
      "checksum": "f5c58cac38e60ac244586a26dded3573b6f1a2da3b2e11003ec5543c90680ae93f37e50718d6bbd0b054f8669c3e2617dfda2eb024052f8cf7cb98439014f1c5",
      "identifier": "f5c58cac38e6/IntegratingCarPlayWithYourMusicApp.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/f5c58cac38e6/IntegratingCarPlayWithYourMusicApp.zip"
    },
    "https://developer.apple.com/musickit": {
      "identifier": "https://developer.apple.com/musickit",
      "title": "MusicKit",
      "titleInlineContent": [
        {
          "text": "MusicKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/musickit"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "f5c58cac38e6/IntegratingCarPlayWithYourMusicApp.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate"
      ],
      "title": "Audio"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPNowPlayingTemplate"
              ],
              "title": "Audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CarPlay~1CPListTemplate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPListTemplate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTemplate",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CarPlay~1CPNowPlayingTemplate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPTemplate",
              "text": "CPTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/title",
          "value": "CPNowPlayingTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPNowPlayingTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPNowPlayingTemplate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/integrating-carplay-with-your-music-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/integrating-carplay-with-your-music-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
