{
  "abstract": [
    {
      "text": "Creates a custom rotor with the specified rotor type and item search delegate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSAccessibilityCustomRotor(im)initWithRotorType:itemSearchDelegate:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "rotorType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
        "text": "NSAccessibilityCustomRotor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
        "text": "RotorType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "itemSearchDelegate"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
        "text": "NSAccessibilityCustomRotorItemSearchDelegate"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithRotorType:itemSearchDelegate:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(rotorType:itemSearchDelegate:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "rotorType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
              "text": "NSAccessibilityCustomRotor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
              "text": "RotorType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "itemSearchDelegate"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor": {
      "abstract": [
        {
          "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotor"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotor",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content that the rotor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RotorType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RotorType"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotor.RotorType",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/rotortype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)": {
      "abstract": [
        {
          "text": "Creates a custom rotor with the specified label and item search delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLabel:itemSearchDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(label:itemSearchDelegate:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/init(label:itemsearchdelegate:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)": {
      "abstract": [
        {
          "text": "Creates a custom rotor with the specified rotor type and item search delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rotorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAccessibilityCustomRotor",
          "text": "NSAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
          "text": "RotorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(rotorType:itemSearchDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithRotorType:itemSearchDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(rotorType:itemSearchDelegate:)",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotor/init(rotortype:itemsearchdelegate:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate": {
      "abstract": [
        {
          "text": "A delegate for a custom rotor that finds the next item result after performing a search with the specified search parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotorItemSearchDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAccessibilityCustomRotorItemSearchDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSAccessibilityCustomRotorItemSearchDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nsaccessibilitycustomrotoritemsearchdelegate"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Rotor",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)"
      ],
      "title": "Creating a Rotor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithRotorType:itemSearchDelegate:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRotorType:itemSearchDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Rotor",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/init(label:itemSearchDelegate:)"
              ],
              "title": "Creating a Rotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithRotorType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSAccessibilityCustomRotor/RotorType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSAccessibilityCustomRotorType",
                    "text": "NSAccessibilityCustomRotorType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "rotorType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "itemSearchDelegate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)NSAccessibilityCustomRotorItemSearchDelegate",
                    "text": "id<NSAccessibilityCustomRotorItemSearchDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "itemSearchDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/title",
          "value": "NSAccessibilityCustomRotorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1RotorType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(rotorType:itemSearchDelegate:)/title",
          "value": "initWithRotorType:itemSearchDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(rotorType:itemSearchDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithRotorType:itemSearchDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/title",
          "value": "NSAccessibilityCustomRotorItemSearchDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotorItemSearchDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotorItemSearchDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/title",
          "value": "NSAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(label:itemSearchDelegate:)/title",
          "value": "initWithLabel:itemSearchDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSAccessibilityCustomRotor~1init(label:itemSearchDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLabel:itemSearchDelegate:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotor/init(rotortype:itemsearchdelegate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsaccessibilitycustomrotor/init(rotortype:itemsearchdelegate:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
