{
  "abstract": [
    {
      "text": "An error that indicates the action’s executable failed to load due to linking issues.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11AMErrorCodeLeV15actionLinkErrorSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "actionLinkError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC11AMErrorCodeLeV",
        "text": "AMError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AMErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "actionLinkError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "actionLinkError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC11AMErrorCodeLeV",
              "text": "AMError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AMErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionApplicationResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionapplicationresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is the wrong version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationVersionResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionApplicationVersionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionapplicationversionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s binary is not compatible with the current processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionArchitectureMismatchError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionArchitectureMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionarchitecturemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an exception while running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExceptionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionExceptionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionexceptionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an error while running (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExecutionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionExecutionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionexecutionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError": {
      "abstract": [
        {
          "text": "An error that indicates the action doesn’t meet the Gatekeeper security policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFailedGatekeeperError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionFailedGatekeeperError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionfailedgatekeepererror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a file required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFileResourceError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionFileResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionfileresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError": {
      "abstract": [
        {
          "text": "An error that indicates Automator is unable to initialize an action (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInitializationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionInitializationError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actioninitializationerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load due to linking issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLinkError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/actionLinkError",
      "kind": "symbol",
      "role": "symbol",
      "title": "actionLinkError",
      "type": "topic",
      "url": "/documentation/automator/amerror/actionlinkerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError": {
      "abstract": [
        {
          "text": "An error that indicates the user cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError",
      "kind": "symbol",
      "role": "symbol",
      "title": "userCanceledError",
      "type": "topic",
      "url": "/documentation/automator/amerror/usercancelederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError": {
      "abstract": [
        {
          "text": "An error that indicates one of the actions of the workflow couldn’t be loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowActionsNotLoadedError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowActionsNotLoadedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowactionsnotloadederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is newer than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerActionVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNewerActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowneweractionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document that was saved with a newer version of Automator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNewerVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflownewerversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError": {
      "abstract": [
        {
          "text": "An error that indicates there are no enabled actions in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNoEnabledActionsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowNoEnabledActionsError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflownoenabledactionserror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is older than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowOlderActionVersionError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowOlderActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowolderactionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document whose property list couldn’t be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowPropertyListInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11AMErrorCodeLeV",
          "text": "AMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "workflowPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/workflowpropertylistinvaliderror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/workflowActionsNotLoadedError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNewerVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowNoEnabledActionsError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowOlderActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/workflowPropertyListInvalidError",
        "doc://com.apple.automator/documentation/Automator/AMError/userCanceledError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionApplicationVersionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionArchitectureMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionExceptionError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionExecutionError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionFailedGatekeeperError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionFileResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/actionInitializationError"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amerror/actionlinkerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
