{
  "abstract": [
    {
      "text": "Automator error codes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.automator/documentation/Automator",
        "doc://com.apple.automator/documentation/Automator/AMError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.automator/documentation/Automator/AMError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AMErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Automator"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AMError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " code numbers in the Automator error domain (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). You’ll obtain these error codes from the instances of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " returned, for example, by certain methods of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For related information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.automator/documentation/Automator": {
      "abstract": [
        {
          "text": "Develop actions that the Automator app can load and run. View, edit, and run Automator workflows in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator",
      "kind": "symbol",
      "role": "collection",
      "title": "Automator",
      "type": "topic",
      "url": "/documentation/automator"
    },
    "doc://com.apple.automator/documentation/Automator/AMActionErrorKey": {
      "abstract": [
        {
          "text": "A key to retrieve the action that caused an error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionErrorKey"
        }
      ],
      "role": "symbol",
      "title": "AMActionErrorKey",
      "type": "topic",
      "url": "/documentation/automator/amactionerrorkey"
    },
    "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies the Automator error domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMAutomatorErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "AMAutomatorErrorDomain",
      "type": "topic",
      "url": "/documentation/automator/amautomatorerrordomain"
    },
    "doc://com.apple.automator/documentation/Automator/AMError": {
      "abstract": [
        {
          "text": "An Automator error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMError"
        }
      ],
      "role": "symbol",
      "title": "AMError",
      "type": "topic",
      "url": "/documentation/automator/amerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code": {
      "abstract": [
        {
          "text": "Automator error codes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code",
      "type": "topic",
      "url": "/documentation/automator/amerror/code"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionApplicationResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionApplicationResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionapplicationresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an app required by the action is the wrong version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionApplicationVersionResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionApplicationVersionResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionApplicationVersionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionapplicationversionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s binary is not compatible with the current processor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionArchitectureMismatchError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionArchitectureMismatchError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionArchitectureMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionarchitecturemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an exception while running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExceptionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionExceptionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionExceptionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionexceptionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError": {
      "abstract": [
        {
          "text": "An error that indicates an action encounters an error while running (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionExecutionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionExecutionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionExecutionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionexecutionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError": {
      "abstract": [
        {
          "text": "An error that indicates the action doesn’t meet the Gatekeeper security policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFailedGatekeeperError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionFailedGatekeeperError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionFailedGatekeeperError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionfailedgatekeepererror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a file required by the action is not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionFileResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionFileResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionFileResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionfileresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError": {
      "abstract": [
        {
          "text": "An error that indicates Automator is unable to initialize an action (reason unknown).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInitializationError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionInitializationError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionInitializationError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actioninitializationerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError": {
      "abstract": [
        {
          "text": "An error that indicates the action requires input data to run, but none was supplied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionInsufficientDataError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionInsufficientDataError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionInsufficientDataError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actioninsufficientdataerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been deprecated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionIsDeprecatedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionIsDeprecatedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionIsDeprecatedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionisdeprecatederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError": {
      "abstract": [
        {
          "text": "An error that indicates a license required by the action was not found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLicenseResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLicenseResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLicenseResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionlicenseresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load due to linking issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLinkError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLinkError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLinkError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionlinkerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable failed to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionLoadError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionLoadError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionLoadError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionloaderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError": {
      "abstract": [
        {
          "text": "An error that indicates the action has been identified as malware by XProtect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionMalwareError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionMalwareError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionMalwareError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionmalwareerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError": {
      "abstract": [
        {
          "text": "An error that indicates the action’s executable is of a type that is not loadable in the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionNotLoadableError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionNotLoadableError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionNotLoadableError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionnotloadableerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates the property list for an action is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionPropertyListInvalidError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionPropertyListInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionPropertyListInvalidError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionpropertylistinvaliderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionQuarantineError": {
      "abstract": [
        {
          "text": "An error that indicates action has been quarantined by XProtect, the antimalware system on the Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionQuarantineError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionQuarantineError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionQuarantineError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionQuarantineError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionquarantineerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRequiredActionResourceError": {
      "abstract": [
        {
          "text": "An error that indicates an action required by the action is not loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionRequiredActionResourceError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRequiredActionResourceError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionRequiredActionResourceError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionRequiredActionResourceError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionrequiredactionresourceerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRuntimeMismatchError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt was made to load an action that is not compiled in a way that is compatible with the current app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionRuntimeMismatchError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRuntimeMismatchError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionRuntimeMismatchError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionRuntimeMismatchError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionruntimemismatcherror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError": {
      "abstract": [
        {
          "text": "An error that indicates developer signature for this action is corrupted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionSignatureCorruptError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionSignatureCorruptError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionSignatureCorruptError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionsignaturecorrupterror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionThirdPartyActionsNotAllowedError": {
      "abstract": [
        {
          "text": "An error that indicates the action is a third party action, and loading it has not been allowed by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionThirdPartyActionsNotAllowedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionThirdPartyActionsNotAllowedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionThirdPartyActionsNotAllowedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionThirdPartyActionsNotAllowedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionthirdpartyactionsnotallowederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXPCError": {
      "abstract": [
        {
          "text": "An error that indicates the remote process running the action has crashed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionXPCError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXPCError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionXPCError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionXPCError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionxpcerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXProtectError": {
      "abstract": [
        {
          "text": "An error that indicates XProtect is unable to successfully analyze the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionXProtectError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXProtectError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMActionXProtectError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.actionXProtectError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/actionxprotecterror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionFailedError": {
      "abstract": [
        {
          "text": "An error that occurs when, for example, the converter encounters an error converting data from one type to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionFailedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionFailedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMConversionFailedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.conversionFailedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/conversionfailederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNoDataError": {
      "abstract": [
        {
          "text": "An error that occurs when the converter determines that the conversion, though possible, would produce a nil result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionNoDataError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNoDataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMConversionNoDataError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.conversionNoDataError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/conversionnodataerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNotPossibleError": {
      "abstract": [
        {
          "text": "An error that occurs when the converter determines that it is unable to convert from one data type to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "conversionNotPossibleError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNotPossibleError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMConversionNotPossibleError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.conversionNotPossibleError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/conversionnotpossibleerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/init(rawvalue:)"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/noSuchActionError": {
      "abstract": [
        {
          "text": "An error that indicates the action could not be located on the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuchActionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/noSuchActionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMNoSuchActionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.noSuchActionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/nosuchactionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/userCanceledError": {
      "abstract": [
        {
          "text": "An error that indicates the user cancelled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userCanceledError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/userCanceledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMUserCanceledError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.userCanceledError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/usercancelederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError": {
      "abstract": [
        {
          "text": "An error that indicates one of the actions of the workflow couldn’t be loaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowActionsNotLoadedError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowActionsNotLoadedError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowActionsNotLoadedError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowactionsnotloadederror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is newer than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerActionVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNewerActionVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNewerActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowneweractionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document that was saved with a newer version of Automator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNewerVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNewerVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNewerVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflownewerversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError": {
      "abstract": [
        {
          "text": "An error that indicates there are no enabled actions in the workflow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowNoEnabledActionsError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowNoEnabledActionsError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowNoEnabledActionsError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflownoenabledactionserror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError": {
      "abstract": [
        {
          "text": "An error that indicates an action in a workflow is older than the installed action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowOlderActionVersionError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowOlderActionVersionError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowOlderActionVersionError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowolderactionversionerror"
    },
    "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError": {
      "abstract": [
        {
          "text": "An error that indicates an attempt to open a workflow document whose property list couldn’t be read.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "workflowPropertyListInvalidError"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowPropertyListInvalidError"
        }
      ],
      "role": "symbol",
      "title": "AMError.Code.workflowPropertyListInvalidError",
      "type": "topic",
      "url": "/documentation/automator/amerror/code/workflowpropertylistinvaliderror"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflow": {
      "abstract": [
        {
          "text": "An object that lets you use an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflow"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflow",
      "type": "topic",
      "url": "/documentation/automator/amworkflow"
    },
    "doc://com.apple.automator/documentation/Automator/AMWorkflowController": {
      "abstract": [
        {
          "text": "An object that lets you manage an Automator workflow in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "identifier": "doc://com.apple.automator/documentation/Automator/AMWorkflowController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AMWorkflowController"
        }
      ],
      "role": "symbol",
      "title": "AMWorkflowController",
      "type": "topic",
      "url": "/documentation/automator/amworkflowcontroller"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
        "doc://com.apple.automator/documentation/Automator/AMActionErrorKey",
        "doc://com.apple.automator/documentation/Automator/AMError"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Workflow-Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError"
      ],
      "title": "Workflow Errors"
    },
    {
      "anchor": "Workflow-Runtime-Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/userCanceledError"
      ],
      "title": "Workflow Runtime Errors"
    },
    {
      "anchor": "Action-Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionPropertyListInvalidError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionQuarantineError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRequiredActionResourceError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRuntimeMismatchError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionThirdPartyActionsNotAllowedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXPCError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXProtectError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/noSuchActionError"
      ],
      "title": "Action Errors"
    },
    {
      "anchor": "Data-Conversion-Errors",
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionFailedError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNoDataError",
        "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNotPossibleError"
      ],
      "title": "Data Conversion Errors"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.automator/documentation/Automator/AMError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.automator/documentation/Automator"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Workflow-Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowActionsNotLoadedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerActionVersionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNewerVersionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowNoEnabledActionsError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowOlderActionVersionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/workflowPropertyListInvalidError"
              ],
              "title": "Workflow Errors"
            },
            {
              "anchor": "Workflow-Runtime-Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/userCanceledError"
              ],
              "title": "Workflow Runtime Errors"
            },
            {
              "anchor": "Action-Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionApplicationVersionResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionArchitectureMismatchError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExceptionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionExecutionError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFailedGatekeeperError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionFileResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInitializationError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionInsufficientDataError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionIsDeprecatedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLicenseResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLinkError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionLoadError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionMalwareError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionNotLoadableError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionPropertyListInvalidError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionQuarantineError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRequiredActionResourceError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionRuntimeMismatchError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionSignatureCorruptError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionThirdPartyActionsNotAllowedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXPCError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/actionXProtectError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/noSuchActionError"
              ],
              "title": "Action Errors"
            },
            {
              "anchor": "Data-Conversion-Errors",
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionFailedError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNoDataError",
                "doc://com.apple.automator/documentation/Automator/AMError/Code/conversionNotPossibleError"
              ],
              "title": "Data Conversion Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.automator/documentation/Automator/AMAutomatorErrorDomain",
                "doc://com.apple.automator/documentation/Automator/AMActionErrorKey"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AMErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionNotLoadableError/title",
          "value": "AMActionNotLoadableError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionNotLoadableError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionNotLoadableError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1noSuchActionError/title",
          "value": "AMNoSuchActionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1noSuchActionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMNoSuchActionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFileResourceError/title",
          "value": "AMActionFileResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFileResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionFileResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInitializationError/title",
          "value": "AMActionInitializationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInitializationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionInitializationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/title",
          "value": "AMActionErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMActionErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLoadError/title",
          "value": "AMActionLoadError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLoadError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLoadError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/title",
          "value": "AMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionNoDataError/title",
          "value": "AMConversionNoDataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionNoDataError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMConversionNoDataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionIsDeprecatedError/title",
          "value": "AMActionIsDeprecatedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionIsDeprecatedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionIsDeprecatedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInsufficientDataError/title",
          "value": "AMActionInsufficientDataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionInsufficientDataError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionInsufficientDataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLinkError/title",
          "value": "AMActionLinkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLinkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLinkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionArchitectureMismatchError/title",
          "value": "AMActionArchitectureMismatchError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionArchitectureMismatchError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionArchitectureMismatchError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationResourceError/title",
          "value": "AMActionApplicationResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionApplicationResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerActionVersionError/title",
          "value": "AMWorkflowNewerActionVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerActionVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNewerActionVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowOlderActionVersionError/title",
          "value": "AMWorkflowOlderActionVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowOlderActionVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowOlderActionVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionMalwareError/title",
          "value": "AMActionMalwareError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionMalwareError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionMalwareError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionSignatureCorruptError/title",
          "value": "AMActionSignatureCorruptError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionSignatureCorruptError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionSignatureCorruptError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionNotPossibleError/title",
          "value": "AMConversionNotPossibleError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionNotPossibleError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMConversionNotPossibleError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionThirdPartyActionsNotAllowedError/title",
          "value": "AMActionThirdPartyActionsNotAllowedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionThirdPartyActionsNotAllowedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionThirdPartyActionsNotAllowedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExecutionError/title",
          "value": "AMActionExecutionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExecutionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionExecutionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionXPCError/title",
          "value": "AMActionXPCError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionXPCError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionXPCError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1userCanceledError/title",
          "value": "AMUserCanceledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1userCanceledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMUserCanceledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionFailedError/title",
          "value": "AMConversionFailedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1conversionFailedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMConversionFailedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionRuntimeMismatchError/title",
          "value": "AMActionRuntimeMismatchError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionRuntimeMismatchError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionRuntimeMismatchError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/title",
          "value": "AMWorkflowController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflowController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFailedGatekeeperError/title",
          "value": "AMActionFailedGatekeeperError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionFailedGatekeeperError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionFailedGatekeeperError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionQuarantineError/title",
          "value": "AMActionQuarantineError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionQuarantineError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionQuarantineError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLicenseResourceError/title",
          "value": "AMActionLicenseResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionLicenseResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionLicenseResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/title",
          "value": "AMWorkflow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMWorkflow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowPropertyListInvalidError/title",
          "value": "AMWorkflowPropertyListInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowPropertyListInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowPropertyListInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/title",
          "value": "AMAutomatorErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMAutomatorErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMAutomatorErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionXProtectError/title",
          "value": "AMActionXProtectError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionXProtectError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionXProtectError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationVersionResourceError/title",
          "value": "AMActionApplicationVersionResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionApplicationVersionResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionApplicationVersionResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowActionsNotLoadedError/title",
          "value": "AMWorkflowActionsNotLoadedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowActionsNotLoadedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowActionsNotLoadedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNoEnabledActionsError/title",
          "value": "AMWorkflowNoEnabledActionsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNoEnabledActionsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNoEnabledActionsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerVersionError/title",
          "value": "AMWorkflowNewerVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1workflowNewerVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMWorkflowNewerVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionRequiredActionResourceError/title",
          "value": "AMActionRequiredActionResourceError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionRequiredActionResourceError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionRequiredActionResourceError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExceptionError/title",
          "value": "AMActionExceptionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionExceptionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionExceptionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionPropertyListInvalidError/title",
          "value": "AMActionPropertyListInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.automator~1documentation~1Automator~1AMError~1Code~1actionPropertyListInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AMActionPropertyListInvalidError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/automator/amerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/automator/amerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
