{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationShouldRequestHealthAuthorization(_:)"},"variants":[{"paths":["/documentation/uikit/uiapplicationdelegate/applicationshouldrequesthealthauthorization(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiapplicationdelegate/applicationshouldrequesthealthauthorization(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"metadata":{"externalID":"c:objc(pl)UIApplicationDelegate(im)applicationShouldRequestHealthAuthorization:","role":"symbol","platforms":[{"beta":false,"introducedAt":"9.0","deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"introducedAt":"9.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationShouldRequestHealthAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","title":"applicationShouldRequestHealthAuthorization(_:)","navigatorTitle":[{"text":"applicationShouldRequestHealthAuthorization:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationShouldRequestHealthAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIApplication","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"application","content":[{"inlineContent":[{"text":"Your singleton app object.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Discussion","anchor":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"In your implementation of this method, call the "},{"identifier":"doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614153-handleauthorizationforextension","isActive":true,"type":"reference"},{"type":"text","text":" method of the "},{"identifier":"doc://com.apple.documentation/documentation/HealthKit/HKHealthStore","isActive":true,"type":"reference"},{"type":"text","text":" object."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Tells the delegate when your app should ask the user for access to his or her HealthKit data.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/HealthKit/HKHealthStore":{"identifier":"doc://com.apple.documentation/documentation/HealthKit/HKHealthStore","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HKHealthStore"}],"type":"topic","role":"symbol","url":"/documentation/HealthKit/HKHealthStore","kind":"symbol","title":"HKHealthStore","abstract":[{"type":"text","text":"The access point for all data managed by HealthKit."}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationShouldRequestHealthAuthorization(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationShouldRequestHealthAuthorization(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationShouldRequestHealthAuthorization"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"applicationShouldRequestHealthAuthorization:","kind":"identifier"}],"type":"topic","role":"symbol","url":"/documentation/uikit/uiapplicationdelegate/applicationshouldrequesthealthauthorization(_:)","kind":"symbol","title":"applicationShouldRequestHealthAuthorization(_:)","abstract":[{"type":"text","text":"Tells the delegate when your app should ask the user for access to his or her HealthKit data."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614153-handleauthorizationforextension":{"identifier":"doc://com.apple.documentation/documentation/healthkit/hkhealthstore/1614153-handleauthorizationforextension","fragments":[{"kind":"text","text":"func "},{"kind":"identifier","text":"handleAuthorizationForExtension"},{"kind":"text","text":"("},{"kind":"identifier","text":"completion"},{"kind":"text","text":": (Bool, (any Error)?) -> Void)"}],"type":"topic","role":"symbol","url":"/documentation/healthkit/hkhealthstore/1614153-handleauthorizationforextension","kind":"symbol","title":"handleAuthorizationForExtension(completion:)","abstract":[{"type":"text","text":"Requests permission to save and read the data types specified by an extension."}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"introducedAt":"9.0","name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"9.0","name":"iPadOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false},{"deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"applicationShouldRequestHealthAuthorization:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationShouldRequestHealthAuthorization:"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applicationShouldRequestHealthAuthorization:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"application","content":[{"type":"paragraph","inlineContent":[{"text":"Your singleton app object.","type":"text"}]}]}]}},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HKHealthStore","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1HealthKit~1HKHealthStore/fragments"},{"op":"replace","value":"applicationShouldRequestHealthAuthorization:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationShouldRequestHealthAuthorization(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"applicationShouldRequestHealthAuthorization:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationShouldRequestHealthAuthorization(_:)/fragments"},{"op":"replace","value":"UIApplicationDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplicationDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplicationDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle"},{"op":"replace","value":"UIApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplication"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"op":"replace","value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"op":"replace","value":"handleAuthorizationForExtensionWithCompletion:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1healthkit~1hkhealthstore~11614153-handleauthorizationforextension/title"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}