{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that the app is about to enter the foreground."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationWillEnterForeground","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"parameters":[{"name":"application","content":[{"type":"paragraph","inlineContent":[{"text":"Your singleton app object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"If you’re using scenes (see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/scenes"},{"type":"text","text":"), UIKit will not call this method. Use "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)"},{"type":"text","text":" instead to prepare your app to enter the foreground. UIKit posts a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification"},{"type":"text","text":" regardless of whether your app uses "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/scenes"},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","name":"Important","style":"important"},{"type":"paragraph","inlineContent":[{"text":"In iOS 4.0 and later, UIKit calls this method as part of the transition from the background to the active state. You can use this method to undo many of the changes you made to your app upon entering the background. The call to this method is invariably followed by a call to the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","isActive":true},{"text":" method, which then moves the app from the inactive to the active state.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"UIKit also posts a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification"},{"type":"text","text":" shortly before calling this method to give interested objects a chance to respond to the transition."}]}],"kind":"content"}],"seeAlsoSections":[{"anchor":"Responding-to-app-life-cycle-events","title":"Responding to app life-cycle events","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"introducedAt":"4.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"4.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false}],"navigatorTitle":[{"text":"applicationWillEnterForeground:","kind":"identifier"}],"externalID":"c:objc(pl)UIApplicationDelegate(im)applicationWillEnterForeground:","title":"applicationWillEnterForeground(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationWillEnterForeground","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"role":"symbol","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiapplicationdelegate/applicationwillenterforeground(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiapplicationdelegate/applicationwillenterforeground(_:)"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app is about to become inactive."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationwillresignactive(_:)","navigatorTitle":[{"kind":"identifier","text":"applicationWillResignActive:"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationWillResignActive","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","title":"applicationWillResignActive(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app has become active."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationdidbecomeactive(_:)","navigatorTitle":[{"text":"applicationDidBecomeActive:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationDidBecomeActive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","title":"applicationDidBecomeActive(_:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)","kind":"symbol","navigatorTitle":[{"text":"sceneWillEnterForeground:","kind":"identifier"}],"type":"topic","title":"sceneWillEnterForeground(_:)","url":"/documentation/uikit/uiscenedelegate/scenewillenterforeground(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sceneWillEnterForeground","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScene","text":"UIScene","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the scene is about to begin running in the foreground and become visible to the user."}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"applicationDidEnterBackground:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationDidEnterBackground","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uiapplicationdelegate/applicationdidenterbackground(_:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","title":"applicationDidEnterBackground(_:)","abstract":[{"text":"Tells the delegate that the app is now in the background.","type":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app is no longer active and loses focus."}],"url":"/documentation/uikit/uiapplication/willresignactivenotification","navigatorTitle":[{"text":"UIApplicationWillResignActiveNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willResignActiveNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification","title":"willResignActiveNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app enters the background."}],"url":"/documentation/uikit/uiapplication/didenterbackgroundnotification","navigatorTitle":[{"text":"UIApplicationDidEnterBackgroundNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterBackgroundNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","title":"didEnterBackgroundNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification":{"abstract":[{"type":"text","text":"A notification that posts shortly before an app leaves the background state on its way to becoming the active app."}],"url":"/documentation/uikit/uiapplication/willenterforegroundnotification","navigatorTitle":[{"text":"UIApplicationWillEnterForegroundNotification","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willEnterForegroundNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","title":"willEnterForegroundNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)":{"abstract":[{"type":"text","text":"Tells the delegate when the app is about to terminate."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationwillterminate(_:)","navigatorTitle":[{"kind":"identifier","text":"applicationWillTerminate:"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applicationWillTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","title":"applicationWillTerminate(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app is about to terminate."}],"url":"/documentation/uikit/uiapplication/willterminatenotification","navigatorTitle":[{"kind":"identifier","text":"UIApplicationWillTerminateNotification"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"willTerminateNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification","title":"willTerminateNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification":{"abstract":[{"type":"text","text":"A notification that posts when the app becomes active."}],"url":"/documentation/uikit/uiapplication/didbecomeactivenotification","navigatorTitle":[{"kind":"identifier","text":"UIApplicationDidBecomeActiveNotification"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didBecomeActiveNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","title":"didBecomeActiveNotification"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/scenes":{"abstract":[{"type":"text","text":"Manage multiple instances of your app’s UI simultaneously, and direct resources to the appropriate instance of your UI."}],"type":"topic","url":"/documentation/uikit/scenes","title":"Scenes","kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/scenes","role":"collectionGroup"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)":{"abstract":[{"type":"text","text":"Tells the delegate that the app is about to enter the foreground."}],"navigatorTitle":[{"kind":"identifier","text":"applicationWillEnterForeground:"}],"type":"topic","url":"/documentation/uikit/uiapplicationdelegate/applicationwillenterforeground(_:)","title":"applicationWillEnterForeground(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationWillEnterForeground"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"4.0","beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"introducedAt":"4.0","beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false},{"name":"tvOS","beta":false,"unavailable":false,"deprecated":false},{"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"applicationWillEnterForeground:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationWillEnterForeground:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Responding to app life-cycle events","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillResignActive(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidEnterBackground(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillTerminate(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/didBecomeActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didEnterBackgroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willEnterForegroundNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willResignActiveNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/willTerminateNotification"],"anchor":"Responding-to-app-life-cycle-events"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"applicationWillEnterForeground:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Your singleton app object."}],"type":"paragraph"}],"name":"application"}]},"path":"/primaryContentSections/1","op":"replace"},{"value":"UIApplication","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"value":[{"kind":"identifier","text":"UIApplication"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"value":"applicationWillResignActive:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillResignActive(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationWillResignActive:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillResignActive(_:)/fragments"},{"value":"applicationDidBecomeActive:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationDidBecomeActive:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/fragments"},{"value":"UIApplicationDelegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title"},{"value":[{"kind":"identifier","text":"UIApplicationDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle","value":[{"text":"UIApplicationDelegate","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneWillEnterForeground(_:)/title","value":"sceneWillEnterForeground:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneWillEnterForeground(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sceneWillEnterForeground:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/title","value":"applicationDidEnterBackground:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidEnterBackground(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"applicationDidEnterBackground:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willResignActiveNotification/title","value":"UIApplicationWillResignActiveNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willResignActiveNotification/fragments","value":[{"text":"UIApplicationWillResignActiveNotification","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didEnterBackgroundNotification/title","value":"UIApplicationDidEnterBackgroundNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didEnterBackgroundNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationDidEnterBackgroundNotification"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willEnterForegroundNotification/title","value":"UIApplicationWillEnterForegroundNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willEnterForegroundNotification/fragments","value":[{"text":"UIApplicationWillEnterForegroundNotification","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillTerminate(_:)/title","value":"applicationWillTerminate:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillTerminate(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationWillTerminate:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willTerminateNotification/title","value":"UIApplicationWillTerminateNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willTerminateNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationWillTerminateNotification"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didBecomeActiveNotification/title","value":"UIApplicationDidBecomeActiveNotification"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didBecomeActiveNotification/fragments","value":[{"kind":"identifier","text":"UIApplicationDidBecomeActiveNotification"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/title","value":"applicationWillEnterForeground:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"applicationWillEnterForeground:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}