{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRegister","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"notificationSettings","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIUserNotificationSettings","preciseIdentifier":"c:objc(cs)UIUserNotificationSettings","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"application","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The app object that registered the user notification settings."}]}]},{"name":"notificationSettings","content":[{"type":"paragraph","inlineContent":[{"text":"The user’s specified notification settings for your app. The settings in this object may be different than the ones you originally requested.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"inlineContent":[{"text":"Apps that use local or remote notifications to alert the user to new information must register the types of notifications they want to use by calling the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)"},{"text":" method of the app object. The system compares your app’s request with the user’s preferences to determine the types of local and remote notifications allowed, and returns the results to your app by calling this method. Check the contents of the ","type":"text"},{"type":"codeVoice","code":"notificationSettings"},{"text":" parameter whenever this method is called.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Because the user can change notification settings in the Settings app at any time, call the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings"},{"type":"text","text":" method before your app performs work to prepare a notification for presentation."}],"type":"paragraph"},{"inlineContent":[{"text":"The first time you register your app’s preferred notification types, the system asks the user whether your app should be allowed to deliver notifications and stores the user’s response. The system does not prompt the user on subsequent calls to the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)","isActive":true,"type":"reference"},{"text":" method, but the user can always change notification preferences using Settings.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"A user’s notification settings control only whether the system ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"displays"}]},{"text":" local or remote notifications onscreen. Regardless of the notification settings, local and remote notifications are delivered to your app at the appropriate times.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Called to tell the delegate the types of local and remote notifications that can be used to get the user’s attention."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiapplicationdelegate/application(_:didregister:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiapplicationdelegate/application(_:didregister:)"]}],"sections":[],"metadata":{"modules":[{"name":"UIKit"}],"symbolKind":"method","role":"symbol","title":"application(_:didRegister:)","platforms":[{"introducedAt":"8.0","name":"iOS","deprecated":false,"message":"Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]","deprecatedAt":"10.0","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","introducedAt":"8.0","message":"Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]","beta":false,"deprecatedAt":"10.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","message":"Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:]","beta":false,"deprecatedAt":"13.1","unavailable":false}],"navigatorTitle":[{"text":"application:didRegisterUserNotificationSettings:","kind":"identifier"}],"externalID":"c:objc(pl)UIApplicationDelegate(im)application:didRegisterUserNotificationSettings:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRegister","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIUserNotificationSettings","preciseIdentifier":"c:objc(cs)UIUserNotificationSettings","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"deprecationSummary":[{"inlineContent":[{"text":"Use ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)"},{"text":" instead.","type":"text"}],"type":"paragraph"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)"],"anchor":"Deprecated","title":"Deprecated","generated":true}],"references":{"doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UNAuthorizationOptions","text":"UNAuthorizationOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)","abstract":[{"text":"Requests a person’s authorization to allow local and remote notifications for your app.","type":"text"}],"url":"/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)","role":"symbol","title":"requestAuthorization(options:completionHandler:)","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:handleOpenURL:"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleOpen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleopen:)","abstract":[{"type":"text","text":"Asks the delegate to open a resource identified by URL."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","title":"application(_:handleOpen:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceApplication"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:open:sourceapplication:annotation:)","title":"application(_:open:sourceApplication:annotation:)","navigatorTitle":[{"kind":"identifier","text":"application:openURL:sourceApplication:annotation:"}],"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","abstract":[{"text":"Asks the delegate to open a resource identified by a URL.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:handle:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INIntent","preciseIdentifier":"c:objc(cs)INIntent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"INIntentResponse","preciseIdentifier":"c:objc(cs)INIntentResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"deprecated":true,"title":"application(_:handle:completionHandler:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Asks the delegate to handle the specified SiriKit intent directly."}],"navigatorTitle":[{"kind":"identifier","text":"application:handleIntent:completionHandler:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:forremotenotification:withresponseinfo:completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:"}],"deprecated":true,"type":"topic","title":"application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handleActionWithIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withResponseInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Called when your app has been activated by the user selecting an action from a remote notification.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)":{"navigatorTitle":[{"kind":"identifier","text":"registerUserNotificationSettings:"}],"url":"/documentation/uikit/uiapplication/registerusernotificationsettings(_:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)","title":"registerUserNotificationSettings(_:)","type":"topic","deprecated":true,"abstract":[{"text":"Registers your preferred options for notifying the user.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerUserNotificationSettings","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIUserNotificationSettings","kind":"typeIdentifier","text":"UIUserNotificationSettings"},{"kind":"text","text":")"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"}],"role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handleActionWithIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","abstract":[{"type":"text","text":"Tells the app delegate to perform the custom action specified by a remote notification."}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:forremotenotification:completionhandler:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)":{"abstract":[{"text":"Tells the delegate when the frame of the status bar has changed.","type":"text"}],"title":"application(_:didChangeStatusBarFrame:)","type":"topic","url":"/documentation/uikit/uiapplicationdelegate/application(_:didchangestatusbarframe:)","navigatorTitle":[{"kind":"identifier","text":"application:didChangeStatusBarFrame:"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeStatusBarFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)":{"abstract":[{"type":"text","text":"Called to tell the delegate the types of local and remote notifications that can be used to get the user’s attention."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegister"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIUserNotificationSettings","kind":"typeIdentifier","text":"UIUserNotificationSettings"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)","kind":"symbol","type":"topic","title":"application(_:didRegister:)","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:didRegisterUserNotificationSettings:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didregister:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings":{"role":"symbol","title":"currentUserNotificationSettings","abstract":[{"text":"Returns the user notification settings for the app.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"currentUserNotificationSettings"}],"deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentUserNotificationSettings"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIUserNotificationSettings","preciseIdentifier":"c:objc(cs)UIUserNotificationSettings"},{"kind":"text","text":"?"}],"url":"/documentation/uikit/uiapplication/currentusernotificationsettings","kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:didchangestatusbarorientation:)","navigatorTitle":[{"kind":"identifier","text":"application:didChangeStatusBarOrientation:"}],"deprecated":true,"type":"topic","title":"application(_:didChangeStatusBarOrientation:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeStatusBarOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientation","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the interface orientation of the status bar has changed."}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)":{"navigatorTitle":[{"text":"application:willChangeStatusBarOrientation:duration:","kind":"identifier"}],"abstract":[{"text":"Tells the delegate when the interface orientation of the status bar is about to change.","type":"text"}],"kind":"symbol","title":"application(_:willChangeStatusBarOrientation:duration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willChangeStatusBarOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","type":"topic","url":"/documentation/uikit/uiapplicationdelegate/application(_:willchangestatusbarorientation:duration:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSaveApplicationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"deprecated":true,"type":"topic","abstract":[{"text":"Asks the delegate whether to preserve the app’s state.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)","navigatorTitle":[{"kind":"identifier","text":"application:shouldSaveApplicationState:"}],"role":"symbol","title":"application(_:shouldSaveApplicationState:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:shouldsaveapplicationstate:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceiveremotenotification:)","abstract":[{"type":"text","text":"Called when your app has received a remote notification."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","deprecated":true,"type":"topic","title":"application(_:didReceiveRemoteNotification:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)":{"title":"application(_:performFetchWithCompletionHandler:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","abstract":[{"text":"Tells the app that it can begin a fetch operation if it has data to download.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:performfetchwithcompletionhandler:)","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:performFetchWithCompletionHandler:"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"performFetchWithCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","abstract":[{"text":"Sent to the delegate when a running app receives a local notification.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":")"}],"type":"topic","title":"application(_:didReceive:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceive:)","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveLocalNotification:"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings":{"abstract":[{"type":"text","text":"The types of notifications that can be displayed to the user by your app."}],"deprecated":true,"role":"symbol","url":"/documentation/uikit/uiusernotificationsettings","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIUserNotificationSettings","kind":"identifier"}],"navigatorTitle":[{"text":"UIUserNotificationSettings","kind":"identifier"}],"title":"UIUserNotificationSettings"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)":{"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","title":"application(_:handleActionWithIdentifier:for:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when your app has been activated because user selected a custom action from the alert panel of a local notification."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleActionWithIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:for:completionhandler:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)":{"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","title":"application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when your app has been activated by the user selecting an action from a local notification."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleActionWithIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withResponseInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:for:withresponseinfo:completionhandler:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:willChangeStatusBarFrame:"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChangeStatusBarFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:willchangestatusbarframe:)","abstract":[{"type":"text","text":"Tells the delegate when the frame of the status bar is about to change."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","title":"application(_:willChangeStatusBarFrame:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"deprecatedAt":"10.0","name":"iOS","beta":false,"deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"deprecatedAt":"10.0","name":"iPadOS","beta":false,"deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"deprecatedAt":"13.1","name":"Mac Catalyst","beta":false,"deprecated":false,"introducedAt":"13.1"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"application:didRegisterUserNotificationSettings:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didRegisterUserNotificationSettings:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)"],"anchor":"Deprecated","generated":true,"title":"Deprecated"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","text":"UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterUserNotificationSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIUserNotificationSettings","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings","preciseIdentifier":"c:objc(cs)UIUserNotificationSettings"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"notificationSettings"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"application","content":[{"inlineContent":[{"type":"text","text":"The app object that registered the user notification settings."}],"type":"paragraph"}]},{"name":"notificationSettings","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s specified notification settings for your app. The settings in this object may be different than the ones you originally requested."}]}]}]},"path":"/primaryContentSections/1"},{"op":"replace","value":[{"inlineContent":[{"text":"Use ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/UserNotifications/UNUserNotificationCenter/requestAuthorization(options:completionHandler:)","isActive":true},{"text":" instead.","type":"text"}],"type":"paragraph"}],"path":"/deprecationSummary"},{"op":"replace","value":"requestAuthorizationWithOptions:completionHandler:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/title"},{"op":"replace","value":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requestAuthorizationWithOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@UNAuthorizationOptions","text":"UNAuthorizationOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"granted"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNUserNotificationCenter~1requestAuthorization(options:completionHandler:)/fragments"},{"op":"replace","value":"application:handleOpenURL:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleOpen:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleOpenURL:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleOpen:)/fragments"},{"op":"replace","value":"application:openURL:sourceApplication:annotation:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:sourceApplication:annotation:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:openURL:sourceApplication:annotation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:sourceApplication:annotation:)/fragments"},{"op":"replace","value":"application:handleIntent:completionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handle:completionHandler:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleIntent:completionHandler:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handle:completionHandler:)/fragments"},{"op":"replace","value":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)/fragments"},{"op":"replace","value":"registerUserNotificationSettings:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerUserNotificationSettings:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/fragments"},{"op":"replace","value":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/fragments"},{"op":"replace","value":"application:didChangeStatusBarFrame:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarFrame:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didChangeStatusBarFrame:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarFrame:)/fragments"},{"op":"replace","value":"application:didRegisterUserNotificationSettings:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegister:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterUserNotificationSettings:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegister:)/fragments"},{"op":"replace","value":"currentUserNotificationSettings","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/title"},{"op":"replace","value":[{"text":"currentUserNotificationSettings","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/fragments"},{"op":"replace","value":"application:didChangeStatusBarOrientation:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarOrientation:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didChangeStatusBarOrientation:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarOrientation:)/fragments"},{"op":"replace","value":"application:willChangeStatusBarOrientation:duration:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarOrientation:duration:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:willChangeStatusBarOrientation:duration:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarOrientation:duration:)/fragments"},{"op":"replace","value":"application:shouldSaveApplicationState:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:shouldSaveApplicationState:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/fragments"},{"op":"replace","value":"application:didReceiveRemoteNotification:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/fragments"},{"op":"replace","value":"application:performFetchWithCompletionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:performFetchWithCompletionHandler:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:performFetchWithCompletionHandler:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:performFetchWithCompletionHandler:)/fragments"},{"op":"replace","value":"application:didReceiveLocalNotification:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceive:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveLocalNotification:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceive:)/fragments"},{"op":"replace","value":"UIUserNotificationSettings","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/title"},{"op":"replace","value":[{"text":"UIUserNotificationSettings","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIUserNotificationSettings"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/navigatorTitle"},{"op":"replace","value":"UIApplicationDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title"},{"op":"replace","value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments"},{"op":"replace","value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle"},{"op":"replace","value":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/fragments"},{"op":"replace","value":"UIApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplication"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"op":"replace","value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"op":"replace","value":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)/fragments"},{"op":"replace","value":"application:willChangeStatusBarFrame:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarFrame:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:willChangeStatusBarFrame:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarFrame:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}