{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiapplicationdelegate/application(_:didregisterforremotenotificationswithdevicetoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiapplicationdelegate/application(_:didregisterforremotenotificationswithdevicetoken:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"kind":"text","text":" "},{"text":"deviceToken","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The app object that initiated the remote-notification registration process.","type":"text"}]}],"name":"application"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A globally unique token that identifies this device to APNs. Send this token to the server that you use to generate remote notifications. Your server must pass this token unmodified back to APNs when sending those remote notifications."}]},{"type":"paragraph","inlineContent":[{"text":"APNs device tokens are of variable length. Do not hard-code their size.","type":"text"}]}],"name":"deviceToken"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"UIKit calls this method after it successfully registers your app with APNs.  In your implementation of this method, send the contents of the ","type":"text"},{"code":"deviceToken","type":"codeVoice"},{"text":" parameter to the server that you use to generate remote notifications. Never cache the device token locally on the user’s device. Device tokens can change periodically, so caching the value risks sending an invalid token to your server. If the device token hasn’t changed, registering with APNs and returning the token happens quickly.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Typically, this method is called only after you call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications()"},{"text":" method of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication"},{"text":", but UIKit might call it in other rare circumstances. For example, UIKit calls the method when the user launches an app after having restored a device from data that is not the device’s backup data. In this exceptional case, the app won’t know the new device’s token until the user launches it.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didRegisterForRemoteNotificationsWithDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(pl)UIApplicationDelegate(im)application:didRegisterForRemoteNotificationsWithDeviceToken:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","platforms":[{"name":"iOS","introducedAt":"3.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"3.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)"},"kind":"symbol","identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that the app successfully registered with Apple Push Notification service (APNs)."}],"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications()"]},{"title":"Handling remote notification registration","generated":true,"anchor":"Handling-remote-notification-registration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)"]}],"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceiveremotenotification:)","abstract":[{"type":"text","text":"Called when your app has received a remote notification."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","deprecated":true,"type":"topic","title":"application(_:didReceiveRemoteNotification:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterForRemoteNotificationsWithDeviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","role":"symbol","title":"application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","abstract":[{"text":"Tells the delegate that the app successfully registered with Apple Push Notification service (APNs).","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegisterForRemoteNotificationsWithDeviceToken:)","navigatorTitle":[{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didregisterforremotenotificationswithdevicetoken:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:didFailToRegisterForRemoteNotificationsWithError:"}],"title":"application(_:didFailToRegisterForRemoteNotificationsWithError:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:didfailtoregisterforremotenotificationswitherror:)","abstract":[{"text":"Tells the delegate when Apple Push Notification service cannot successfully complete the registration process.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterForRemoteNotificationsWithError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]},"doc://com.externally.resolved.symbol/s:10Foundation4DataV":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:10Foundation4DataV","kind":"symbol","fragments":[{"text":"struct ","kind":"text"},{"text":"Data","kind":"identifier"}],"abstract":[{"text":"A byte buffer in memory.","type":"text"}],"type":"topic","url":"/documentation/foundation/data","title":"Data"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSData":{"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSData","kind":"identifier"}],"title":"NSData","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","type":"topic","url":"/documentation/foundation/nsdata","kind":"symbol","abstract":[{"text":"A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications()":{"role":"symbol","abstract":[{"text":"Registers to receive remote notifications through Apple Push Notification service.","type":"text"}],"navigatorTitle":[{"text":"registerForRemoteNotifications","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerForRemoteNotifications"},{"text":"()","kind":"text"}],"type":"topic","title":"registerForRemoteNotifications()","url":"/documentation/uikit/uiapplication/registerforremotenotifications()","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"fetchCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@E@UIBackgroundFetchResult","text":"UIBackgroundFetchResult","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceiveremotenotification:fetchcompletionhandler:)","title":"application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","navigatorTitle":[{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)","abstract":[{"type":"text","text":"Tells the app that a remote notification arrived that indicates there is data to be fetched."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"introducedAt":"3.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"3.0","name":"iPadOS","unavailable":false},{"unavailable":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"introducedAt":"1.0","name":"visionOS","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterForRemoteNotificationsWithDeviceToken:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications()"]},{"title":"Handling remote notification registration","generated":true,"anchor":"Handling-remote-notification-registration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didFailToRegisterForRemoteNotificationsWithError:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:fetchCompletionHandler:)"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterForRemoteNotificationsWithDeviceToken:"},{"kind":"text","text":"("},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceToken"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":{"parameters":[{"name":"application","content":[{"inlineContent":[{"type":"text","text":"The app object that initiated the remote-notification registration process."}],"type":"paragraph"}]},{"name":"deviceToken","content":[{"inlineContent":[{"type":"text","text":"A globally unique token that identifies this device to APNs. Send this token to the server that you use to generate remote notifications. Your server must pass this token unmodified back to APNs when sending those remote notifications."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"APNs device tokens are of variable length. Do not hard-code their size."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"op":"replace","value":"UIApplicationDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title"},{"op":"replace","value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplicationDelegate"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle"},{"op":"replace","value":"UIApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplication"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"op":"replace","value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"op":"replace","value":"application:didReceiveRemoteNotification:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didReceiveRemoteNotification:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/fragments"},{"op":"replace","value":"application:didRegisterForRemoteNotificationsWithDeviceToken:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didRegisterForRemoteNotificationsWithDeviceToken:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegisterForRemoteNotificationsWithDeviceToken:)/fragments"},{"op":"replace","value":"application:didFailToRegisterForRemoteNotificationsWithError:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFailToRegisterForRemoteNotificationsWithError:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didFailToRegisterForRemoteNotificationsWithError:)/fragments"},{"op":"replace","value":[{"type":"text","text":"A static byte buffer in memory."}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSData/abstract"},{"op":"replace","value":"registerForRemoteNotifications","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"registerForRemoteNotifications","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications()/fragments"},{"op":"replace","value":"application:didReceiveRemoteNotification:fetchCompletionHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didReceiveRemoteNotification:fetchCompletionHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:fetchCompletionHandler:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}