{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uiapplicationdelegate/applicationprotecteddatadidbecomeavailable(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiapplicationdelegate/applicationprotecteddatadidbecomeavailable(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"Responding to environment changes","anchor":"Responding-to-environment-changes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataWillBecomeUnavailable(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidReceiveMemoryWarning(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationSignificantTimeChange(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didReceiveMemoryWarningNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/significantTimeChangeNotification"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataDidBecomeAvailable(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"4.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"4.0"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable:"}],"externalID":"c:objc(pl)UIApplicationDelegate(im)applicationProtectedDataDidBecomeAvailable:","role":"symbol","title":"applicationProtectedDataDidBecomeAvailable(_:)","symbolKind":"method"},"abstract":[{"text":"Tells the delegate that protected files are available now.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applicationProtectedDataDidBecomeAvailable","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"application","content":[{"inlineContent":[{"text":"Your singleton app object.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"mentions","mentions":["doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files"]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"On a device that uses content protection, protected files are stored in an encrypted form and made available only at certain times, usually when the device is unlocked. This notification lets your app know that the device is now unlocked and that you may access certain types of protected files again.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIApplicationProtectedDataDidBecomeAvailable"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectedDataDidBecomeAvailableNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"title":"protectedDataDidBecomeAvailableNotification","abstract":[{"type":"text","text":"A notification that posts when the protected files become available for your code to access."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification","url":"/documentation/uikit/uiapplication/protecteddatadidbecomeavailablenotification"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataWillBecomeUnavailable(_:)":{"navigatorTitle":[{"kind":"identifier","text":"applicationProtectedDataWillBecomeUnavailable:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationProtectedDataWillBecomeUnavailable"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataWillBecomeUnavailable(_:)","title":"applicationProtectedDataWillBecomeUnavailable(_:)","abstract":[{"text":"Tells the delegate that the protected files are about to become unavailable.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiapplicationdelegate/applicationprotecteddatawillbecomeunavailable(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationSignificantTimeChange(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applicationSignificantTimeChange:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationSignificantTimeChange"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"title":"applicationSignificantTimeChange(_:)","abstract":[{"type":"text","text":"Tells the delegate when there is a significant change in the time."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationSignificantTimeChange(_:)","url":"/documentation/uikit/uiapplicationdelegate/applicationsignificanttimechange(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/didReceiveMemoryWarningNotification":{"url":"/documentation/uikit/uiapplication/didreceivememorywarningnotification","abstract":[{"type":"text","text":"A notification that posts when the app receives a warning from the operating system about low memory availability."}],"navigatorTitle":[{"kind":"identifier","text":"UIApplicationDidReceiveMemoryWarningNotification"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/didReceiveMemoryWarningNotification","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveMemoryWarningNotification","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"title":"didReceiveMemoryWarningNotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/significantTimeChangeNotification":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIApplicationSignificantTimeChangeNotification"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"significantTimeChangeNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"title":"significantTimeChangeNotification","abstract":[{"type":"text","text":"A notification that posts when there’s a significant change in time."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/significantTimeChangeNotification","url":"/documentation/uikit/uiapplication/significanttimechangenotification"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidReceiveMemoryWarning(_:)":{"url":"/documentation/uikit/uiapplicationdelegate/applicationdidreceivememorywarning(_:)","abstract":[{"type":"text","text":"Tells the delegate when the app receives a memory warning from the system."}],"role":"symbol","title":"applicationDidReceiveMemoryWarning(_:)","kind":"symbol","navigatorTitle":[{"text":"applicationDidReceiveMemoryWarning:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidReceiveMemoryWarning(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"applicationDidReceiveMemoryWarning","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIApplicationProtectedDataWillBecomeUnavailable"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectedDataWillBecomeUnavailableNotification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"title":"protectedDataWillBecomeUnavailableNotification","abstract":[{"type":"text","text":"A notification that posts shortly before protected files are locked down and become inaccessible."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification","url":"/documentation/uikit/uiapplication/protecteddatawillbecomeunavailablenotification"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataDidBecomeAvailable(_:)":{"navigatorTitle":[{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataDidBecomeAvailable(_:)","title":"applicationProtectedDataDidBecomeAvailable(_:)","abstract":[{"text":"Tells the delegate that protected files are available now.","type":"text"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiapplicationdelegate/applicationprotecteddatadidbecomeavailable(_:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files":{"url":"/documentation/uikit/encrypting-your-app-s-files","type":"topic","abstract":[{"type":"text","text":"Protect the user’s data in iOS by encrypting it on disk."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files","kind":"article","role":"article","title":"Encrypting Your App’s Files"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"4.0","deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"4.0","deprecated":false},{"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"applicationProtectedDataDidBecomeAvailable:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"anchor":"Responding-to-environment-changes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationProtectedDataWillBecomeUnavailable(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidReceiveMemoryWarning(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationSignificantTimeChange(_:)","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataDidBecomeAvailableNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/protectedDataWillBecomeUnavailableNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/didReceiveMemoryWarningNotification","doc://com.apple.uikit/documentation/UIKit/UIApplication/significantTimeChangeNotification"],"title":"Responding to environment changes"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"applicationProtectedDataDidBecomeAvailable:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication"},{"text":" *) ","kind":"text"},{"text":"application","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"application","content":[{"inlineContent":[{"text":"Your singleton app object.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"value":"UIApplicationProtectedDataDidBecomeAvailable","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataDidBecomeAvailableNotification/title"},{"value":[{"kind":"identifier","text":"UIApplicationProtectedDataDidBecomeAvailable"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataDidBecomeAvailableNotification/fragments"},{"value":"applicationProtectedDataWillBecomeUnavailable:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationProtectedDataWillBecomeUnavailable(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationProtectedDataWillBecomeUnavailable:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationProtectedDataWillBecomeUnavailable(_:)/fragments"},{"value":"applicationSignificantTimeChange:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationSignificantTimeChange(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"applicationSignificantTimeChange:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationSignificantTimeChange(_:)/fragments"},{"value":"UIApplicationDidReceiveMemoryWarningNotification","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didReceiveMemoryWarningNotification/title"},{"value":[{"text":"UIApplicationDidReceiveMemoryWarningNotification","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didReceiveMemoryWarningNotification/fragments"},{"value":"UIApplicationSignificantTimeChangeNotification","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1significantTimeChangeNotification/title"},{"value":[{"kind":"identifier","text":"UIApplicationSignificantTimeChangeNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1significantTimeChangeNotification/fragments"},{"value":"applicationDidReceiveMemoryWarning:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidReceiveMemoryWarning(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationDidReceiveMemoryWarning:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidReceiveMemoryWarning(_:)/fragments"},{"value":"UIApplicationProtectedDataWillBecomeUnavailable","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataWillBecomeUnavailableNotification/title"},{"value":[{"kind":"identifier","text":"UIApplicationProtectedDataWillBecomeUnavailable"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1protectedDataWillBecomeUnavailableNotification/fragments"},{"value":"UIApplication","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"value":[{"text":"UIApplication","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"value":"applicationProtectedDataDidBecomeAvailable:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationProtectedDataDidBecomeAvailable(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applicationProtectedDataDidBecomeAvailable:"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationProtectedDataDidBecomeAvailable(_:)/fragments"},{"value":"UIApplicationDelegate","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title"},{"value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments"},{"value":[{"kind":"identifier","text":"UIApplicationDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}