{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"UIKit"}],"externalID":"s:So21UIApplicationDelegateP5UIKitE4mainyyFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}],"title":"main()","symbolKind":"method","role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"extendedModule":"UIKit","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"abstract":[{"type":"text","text":"Provides the top-level entry point for the app."}],"variants":[{"paths":["/documentation/uikit/uiapplicationdelegate/main()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/main()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","isActive":true},{"type":"text","text":" provides an implementation of the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/main()","isActive":true},{"type":"text","text":" method so that it can serve as the main entry point for a UIKit app. The system calls the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/main()","isActive":true},{"type":"text","text":" method to launch your app; you never call it yourself. You can have exactly one entry point in your app, which you mark with the "},{"type":"codeVoice","code":"@main"},{"type":"text","text":" attribute."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/main()":{"url":"/documentation/uikit/uiapplicationdelegate/main()","abstract":[{"type":"text","text":"Provides the top-level entry point for the app."}],"kind":"symbol","type":"topic","title":"main()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/main()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UIApplicationDelegate","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title","op":"replace"},{"value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments","op":"replace"},{"value":[{"text":"UIApplicationDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}