{
  "abstract": [
    {
      "text": "No error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.classkit/documentation/ClassKit",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLSErrorCode@CLSErrorCodeNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "ClassKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLSErrorCodeNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLSError.Code.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.classkit/documentation/ClassKit": {
      "abstract": [
        {
          "text": "Enable teachers to assign activities from your app’s content and to view student progress.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ClassKit",
      "type": "topic",
      "url": "/documentation/classkit"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError": {
      "abstract": [
        {
          "text": "Errors issued by ClassKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSError"
        }
      ],
      "role": "symbol",
      "title": "CLSError",
      "type": "topic",
      "url": "/documentation/classkit/clserror"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code": {
      "abstract": [
        {
          "text": "Error codes that ClassKit issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/authorizationDenied": {
      "abstract": [
        {
          "text": "The app isn’t authorized to perform the requested operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationDenied"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/authorizationDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeAuthorizationDenied"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.authorizationDenied",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/authorizationdenied"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/classKitUnavailable": {
      "abstract": [
        {
          "text": "ClassKit isn’t available on this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classKitUnavailable"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/classKitUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeClassKitUnavailable"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.classKitUnavailable",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/classkitunavailable"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/databaseInaccessible": {
      "abstract": [
        {
          "text": "ClassKit isn’t accessible because the device is locked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "databaseInaccessible"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/databaseInaccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeDatabaseInaccessible"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.databaseInaccessible",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/databaseinaccessible"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidAccountCredentials": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAccountCredentials"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidAccountCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeInvalidAccountCredentials"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.invalidAccountCredentials",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/invalidaccountcredentials"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidArgument": {
      "abstract": [
        {
          "text": "An invalid argument was provided to the API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.invalidArgument",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/invalidargument"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidCreate": {
      "abstract": [
        {
          "text": "An attempt to save a new object that already exists in the data store failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidCreate"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidCreate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeInvalidCreate"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.invalidCreate",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/invalidcreate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidModification": {
      "abstract": [
        {
          "text": "An attempt to modify a read-only object failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidModification"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidModification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeInvalidModification"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.invalidModification",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/invalidmodification"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidUpdate": {
      "abstract": [
        {
          "text": "ClassKit failed to save an updated object in the data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidUpdate"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeInvalidUpdate"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.invalidUpdate",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/invalidupdate"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/limits": {
      "abstract": [
        {
          "text": "A limit has been exceeded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limits"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/limits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeLimits"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.limits",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/limits"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/none": {
      "abstract": [
        {
          "text": "No error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodeNone"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.none",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/none"
    },
    "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/partialFailure": {
      "abstract": [
        {
          "text": "ClassKit encountered more than one error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialFailure"
        }
      ],
      "identifier": "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/partialFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLSErrorCodePartialFailure"
        }
      ],
      "role": "symbol",
      "title": "CLSError.Code.partialFailure",
      "type": "topic",
      "url": "/documentation/classkit/clserror/code/partialfailure"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/authorizationDenied",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/classKitUnavailable",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/databaseInaccessible",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidAccountCredentials",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidArgument",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidCreate",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidModification",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidUpdate",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/limits",
        "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/partialFailure"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLSErrorCodeNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.classkit/documentation/ClassKit",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/authorizationDenied",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/classKitUnavailable",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/databaseInaccessible",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidAccountCredentials",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidArgument",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidCreate",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidModification",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/invalidUpdate",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/limits",
                "doc://com.apple.classkit/documentation/ClassKit/CLSError/Code/partialFailure"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLSErrorCodeNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1none/title",
          "value": "CLSErrorCodeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidAccountCredentials/title",
          "value": "CLSErrorCodeInvalidAccountCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidAccountCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeInvalidAccountCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1partialFailure/title",
          "value": "CLSErrorCodePartialFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1partialFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodePartialFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1databaseInaccessible/title",
          "value": "CLSErrorCodeDatabaseInaccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1databaseInaccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeDatabaseInaccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1classKitUnavailable/title",
          "value": "CLSErrorCodeClassKitUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1classKitUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeClassKitUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidCreate/title",
          "value": "CLSErrorCodeInvalidCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidCreate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeInvalidCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1limits/title",
          "value": "CLSErrorCodeLimits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1limits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeLimits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidUpdate/title",
          "value": "CLSErrorCodeInvalidUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeInvalidUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidModification/title",
          "value": "CLSErrorCodeInvalidModification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidModification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeInvalidModification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1authorizationDenied/title",
          "value": "CLSErrorCodeAuthorizationDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1authorizationDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeAuthorizationDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidArgument/title",
          "value": "CLSErrorCodeInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code~1invalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCodeInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/title",
          "value": "CLSErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.classkit~1documentation~1ClassKit~1CLSError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLSErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/classkit/clserror/code/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/classkit/clserror/code/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
