{
  "abstract": [
    {
      "text": "Informs the delegate that the pop-up list is about to be displayed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillPopUp(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSComboBoxDelegate(im)comboBoxWillPopUp:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "comboBoxWillPopUp"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation12NotificationV",
        "text": "Notification"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "comboBoxWillPopUp:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "comboBoxWillPopUp(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "comboBoxWillPopUp"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "notification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12NotificationV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation12NotificationV",
              "text": "Notification"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A notification named ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBox/willPopUpNotification",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "notification"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBox/willPopUpNotification": {
      "abstract": [
        {
          "text": "Posted whenever the pop-up list of the ",
          "type": "text"
        },
        {
          "code": "NSComboBox",
          "type": "codeVoice"
        },
        {
          "text": " is going to be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willPopUpNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBox/willPopUpNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSComboBoxWillPopUpNotification"
        }
      ],
      "role": "symbol",
      "title": "willPopUpNotification",
      "type": "topic",
      "url": "/documentation/appkit/nscombobox/willpopupnotification"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods implemented by delegates of combo box objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSComboBoxDelegate"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSComboBoxDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSComboBoxDelegate",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxdelegate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionDidChange(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the pop-up list selection has finished changing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBoxSelectionDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comboBoxSelectionDidChange:"
        }
      ],
      "role": "symbol",
      "title": "comboBoxSelectionDidChange(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxdelegate/comboboxselectiondidchange(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionIsChanging(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the pop-up list selection is changing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBoxSelectionIsChanging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionIsChanging(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comboBoxSelectionIsChanging:"
        }
      ],
      "role": "symbol",
      "title": "comboBoxSelectionIsChanging(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxdelegate/comboboxselectionischanging(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillDismiss(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the pop-up list is about to be dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBoxWillDismiss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillDismiss(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comboBoxWillDismiss:"
        }
      ],
      "role": "symbol",
      "title": "comboBoxWillDismiss(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxdelegate/comboboxwilldismiss(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillPopUp(_:)": {
      "abstract": [
        {
          "text": "Informs the delegate that the pop-up list is about to be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comboBoxWillPopUp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillPopUp(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comboBoxWillPopUp:"
        }
      ],
      "role": "symbol",
      "title": "comboBoxWillPopUp(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nscomboboxdelegate/comboboxwillpopup(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification": {
      "abstract": [
        {
          "text": "An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNotification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation12NotificationV": {
      "abstract": [
        {
          "text": "A container for information broadcast through a notification center to all registered observers. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation12NotificationV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Notification",
      "type": "topic",
      "url": "/documentation/foundation/notification"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manipulating-the-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionDidChange(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionIsChanging(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillDismiss(_:)"
      ],
      "title": "Manipulating the selection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "comboBoxWillPopUp:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comboBoxWillPopUp:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Manipulating-the-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionDidChange(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxSelectionIsChanging(_:)",
                "doc://com.apple.appkit/documentation/AppKit/NSComboBoxDelegate/comboBoxWillDismiss(_:)"
              ],
              "title": "Manipulating the selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "comboBoxWillPopUp:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSNotification",
                    "text": "NSNotification"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "notification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A notification named ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSComboBox/willPopUpNotification",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "notification"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/title",
          "value": "NSComboBoxDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBoxDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBoxDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract",
          "value": [
            {
              "text": "A container for information broadcast through a notification center to all registered observers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox~1willPopUpNotification/title",
          "value": "NSComboBoxWillPopUpNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBox~1willPopUpNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSComboBoxWillPopUpNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxSelectionIsChanging(_:)/title",
          "value": "comboBoxSelectionIsChanging:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxSelectionIsChanging(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comboBoxSelectionIsChanging:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxSelectionDidChange(_:)/title",
          "value": "comboBoxSelectionDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxSelectionDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comboBoxSelectionDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxWillDismiss(_:)/title",
          "value": "comboBoxWillDismiss:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxWillDismiss(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comboBoxWillDismiss:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxWillPopUp(_:)/title",
          "value": "comboBoxWillPopUp:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSComboBoxDelegate~1comboBoxWillPopUp(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comboBoxWillPopUp:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscomboboxdelegate/comboboxwillpopup(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscomboboxdelegate/comboboxwillpopup(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
