{"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/withConfiguration(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/applyingSymbolConfiguration(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/withHorizontallyFlippedOrientation()","doc://com.apple.uikit/documentation/UIKit/UIImage/withRenderingMode(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/withAlignmentRectInsets(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:)","doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:resizingMode:)","doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithoutBaseline()","doc://com.apple.uikit/documentation/UIKit/UIImage/withBaselineOffset(fromBottom:)","doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class"],"title":"Changing the image attributes","anchor":"Changing-the-image-attributes"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageFlippedForRightToLeftLayoutDirection()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/uikit/uiimage/imageflippedforrighttoleftlayoutdirection()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiimage/imageflippedforrighttoleftlayoutdirection()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageFlippedForRightToLeftLayoutDirection","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","text":"UIImage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The current image, prepared to flip horizontally if it’s in a right-to-left layout.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method to specify an image that should flip in a right-to-left layout. Note that most images do not need to flip in a right-to-left layout."}]},{"type":"paragraph","inlineContent":[{"text":"This method returns the current ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","type":"reference"},{"text":" object with the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection","type":"reference"},{"text":" property set to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":"; it does ","type":"text"},{"inlineContent":[{"type":"text","text":"not"}],"type":"emphasis"},{"text":" return a flipped image. When the returned image is displayed in a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView","type":"reference"},{"text":" object in a right-to-left layout direction (whether the layout direction is set by the system language, or because the image view’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute","type":"reference"},{"text":" property is set to ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft","type":"reference"},{"text":"), the image appears flipped. When the returned image is displayed in a left-to-right context, it appears unflipped.","type":"text"}]}],"kind":"content"}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"platforms":[{"beta":false,"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"iPadOS"},{"beta":false,"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"beta":false,"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"tvOS"},{"beta":false,"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS"},{"beta":false,"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"watchOS"}],"symbolKind":"method","externalID":"c:objc(cs)UIImage(im)imageFlippedForRightToLeftLayoutDirection","title":"imageFlippedForRightToLeftLayoutDirection()"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"abstract":[{"text":"Returns a new version of the current image that flips horizontally when it’s in a right-to-left layout.","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resizableImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCapInsets","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:)","abstract":[{"text":"Returns a new version of the image with the specified cap insets.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"resizableImageWithCapInsets:","kind":"identifier"}],"title":"resizableImage(withCapInsets:)","url":"/documentation/uikit/uiimage/resizableimage(withcapinsets:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forceRightToLeft","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft","abstract":[{"text":"A view that’s always displayed using a right-to-left layout.","type":"text"}],"url":"/documentation/uikit/uisemanticcontentattribute/forcerighttoleft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UISemanticContentAttributeForceRightToLeft"}],"role":"symbol","title":"UISemanticContentAttribute.forceRightToLeft"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withRenderingMode(_:)":{"navigatorTitle":[{"text":"imageWithRenderingMode:","kind":"identifier"}],"url":"/documentation/uikit/uiimage/withrenderingmode(_:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withRenderingMode(_:)","abstract":[{"text":"Returns a new version of the image that uses the specified rendering mode.","type":"text"}],"title":"withRenderingMode(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withRenderingMode","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"RenderingMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageRenderingMode"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withBaselineOffset(fromBottom:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withBaselineOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withBaselineOffset(fromBottom:)","abstract":[{"type":"text","text":"Creates a new image with a baseline at the specified offset from the bottom of the image."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithBaselineOffsetFromBottom:"}],"title":"withBaselineOffset(fromBottom:)","url":"/documentation/uikit/uiimage/withbaselineoffset(frombottom:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"flipsForRightToLeftLayoutDirection"}],"title":"flipsForRightToLeftLayoutDirection","url":"/documentation/uikit/uiimage/flipsforrighttoleftlayoutdirection","abstract":[{"type":"text","text":"A Boolean value that indicates whether the image flips in a right-to-left layout."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsForRightToLeftLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.uikit/documentation/UIKit/UIImageView":{"role":"symbol","url":"/documentation/uikit/uiimageview","navigatorTitle":[{"kind":"identifier","text":"UIImageView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImageView"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImageView","abstract":[{"text":"A view that displays a single image or a sequence of animated images in your interface.","type":"text"}],"kind":"symbol","title":"UIImageView","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withConfiguration(_:)":{"abstract":[{"text":"Returns a new version of the current image, replacing the current configuration attributes with the specified attributes.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/uikit/uiimage/withconfiguration(_:)","navigatorTitle":[{"text":"imageWithConfiguration:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withConfiguration(_:)","type":"topic","title":"withConfiguration(_:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"A configuration object that contains the traits that the system uses when selecting the current image variant.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class","role":"symbol","url":"/documentation/uikit/uiimage/configuration-swift.class","kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","title":"UIImage.Configuration"},"doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithoutBaseline()":{"type":"topic","abstract":[{"text":"Creates a copy of the current image object without any baseline information.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithoutBaseline()","kind":"symbol","url":"/documentation/uikit/uiimage/imagewithoutbaseline()","title":"imageWithoutBaseline()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageWithoutBaseline"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithoutBaseline"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class":{"kind":"symbol","role":"symbol","title":"UIImage.SymbolConfiguration","navigatorTitle":[{"text":"SymbolConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SymbolConfiguration","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.class","abstract":[{"type":"text","text":"An object that contains the specific font, size, style, and weight attributes to apply to a symbol image."}],"type":"topic"},"doc://com.apple.documentation/documentation/swift/true":{"abstract":[{"text":"A true value.","type":"text"}],"role":"symbol","url":"/documentation/swift/true","identifier":"doc://com.apple.documentation/documentation/swift/true","type":"topic","title":"true","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withAlignmentRectInsets(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withAlignmentRectInsets","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withAlignmentRectInsets(_:)","abstract":[{"text":"Returns a new version of the image that uses the specified alignment insets.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"imageWithAlignmentRectInsets:","kind":"identifier"}],"title":"withAlignmentRectInsets(_:)","url":"/documentation/uikit/uiimage/withalignmentrectinsets(_:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/imageFlippedForRightToLeftLayoutDirection()":{"title":"imageFlippedForRightToLeftLayoutDirection()","navigatorTitle":[{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"}],"role":"symbol","abstract":[{"type":"text","text":"Returns a new version of the current image that flips horizontally when it’s in a right-to-left layout."}],"kind":"symbol","url":"/documentation/uikit/uiimage/imageflippedforrighttoleftlayoutdirection()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageFlippedForRightToLeftLayoutDirection()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:resizingMode:)":{"type":"topic","abstract":[{"text":"Returns a new version of the image with the specified cap insets and options.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:resizingMode:)","kind":"symbol","url":"/documentation/uikit/uiimage/resizableimage(withcapinsets:resizingmode:)","title":"resizableImage(withCapInsets:resizingMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizableImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCapInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resizingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ResizingMode","preciseIdentifier":"c:@E@UIImageResizingMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resizableImageWithCapInsets:resizingMode:"}]},"doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute":{"abstract":[{"text":"A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.","type":"text"}],"title":"semanticContentAttribute","url":"/documentation/uikit/uiview/semanticcontentattribute","navigatorTitle":[{"text":"semanticContentAttribute","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView/semanticContentAttribute","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"semanticContentAttribute","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UISemanticContentAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@E@UISemanticContentAttribute"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/applyingSymbolConfiguration(_:)":{"navigatorTitle":[{"kind":"identifier","text":"imageByApplyingSymbolConfiguration:"}],"url":"/documentation/uikit/uiimage/applyingsymbolconfiguration(_:)","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/applyingSymbolConfiguration(_:)","abstract":[{"type":"text","text":"Returns a new version of the current image, applying the specified configuration attributes on top of the current attributes."}],"title":"applyingSymbolConfiguration(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"applyingSymbolConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageSymbolConfiguration","text":"SymbolConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/withHorizontallyFlippedOrientation()":{"type":"topic","abstract":[{"text":"Returns a new version of the image that’s a mirror of the original image.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withHorizontallyFlippedOrientation()","kind":"symbol","url":"/documentation/uikit/uiimage/withhorizontallyflippedorientation()","title":"withHorizontallyFlippedOrientation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withHorizontallyFlippedOrientation"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithHorizontallyFlippedOrientation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"9.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"9.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"introducedAt":"9.0","beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false},{"deprecated":false,"introducedAt":"2.0","beta":false,"name":"watchOS","unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"imageFlippedForRightToLeftLayoutDirection"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageFlippedForRightToLeftLayoutDirection","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/withConfiguration(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/applyingSymbolConfiguration(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/withHorizontallyFlippedOrientation()","doc://com.apple.uikit/documentation/UIKit/UIImage/withRenderingMode(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/withAlignmentRectInsets(_:)","doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:)","doc://com.apple.uikit/documentation/UIKit/UIImage/resizableImage(withCapInsets:resizingMode:)","doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithoutBaseline()","doc://com.apple.uikit/documentation/UIKit/UIImage/withBaselineOffset(fromBottom:)","doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class","doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class"],"title":"Changing the image attributes","anchor":"Changing-the-image-attributes"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]}},{"op":"replace","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The current image, prepared to flip horizontally if it’s in a right-to-left layout."}]}],"kind":"content"},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizableImage(withCapInsets:)/title","value":"resizableImageWithCapInsets:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizableImage(withCapInsets:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"resizableImageWithCapInsets:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/title","value":"UISemanticContentAttributeForceRightToLeft"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/fragments","value":[{"text":"UISemanticContentAttributeForceRightToLeft","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withRenderingMode(_:)/title","value":"imageWithRenderingMode:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withRenderingMode(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithRenderingMode:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withBaselineOffset(fromBottom:)/title","value":"imageWithBaselineOffsetFromBottom:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withBaselineOffset(fromBottom:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageWithBaselineOffsetFromBottom:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1flipsForRightToLeftLayoutDirection/title","value":"flipsForRightToLeftLayoutDirection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1flipsForRightToLeftLayoutDirection/fragments","value":[{"text":"flipsForRightToLeftLayoutDirection","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/title","value":"UIImageView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/fragments","value":[{"kind":"identifier","text":"UIImageView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/navigatorTitle","value":[{"text":"UIImageView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withConfiguration(_:)/title","value":"imageWithConfiguration:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withConfiguration(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithConfiguration:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/title","value":"UIImageConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/fragments","value":[{"text":"UIImageConfiguration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/navigatorTitle","value":[{"kind":"identifier","text":"UIImageConfiguration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageWithoutBaseline()/title","value":"imageWithoutBaseline"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageWithoutBaseline()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithoutBaseline"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/title","value":"UIImageSymbolConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/fragments","value":[{"kind":"identifier","text":"UIImageSymbolConfiguration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/navigatorTitle","value":[{"kind":"identifier","text":"UIImageSymbolConfiguration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withAlignmentRectInsets(_:)/title","value":"imageWithAlignmentRectInsets:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withAlignmentRectInsets(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageWithAlignmentRectInsets:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageFlippedForRightToLeftLayoutDirection()/title","value":"imageFlippedForRightToLeftLayoutDirection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageFlippedForRightToLeftLayoutDirection()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageFlippedForRightToLeftLayoutDirection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizableImage(withCapInsets:resizingMode:)/title","value":"resizableImageWithCapInsets:resizingMode:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizableImage(withCapInsets:resizingMode:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resizableImageWithCapInsets:resizingMode:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1semanticContentAttribute/title","value":"semanticContentAttribute"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1semanticContentAttribute/fragments","value":[{"kind":"identifier","text":"semanticContentAttribute"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1applyingSymbolConfiguration(_:)/title","value":"imageByApplyingSymbolConfiguration:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1applyingSymbolConfiguration(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageByApplyingSymbolConfiguration:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withHorizontallyFlippedOrientation()/title","value":"imageWithHorizontallyFlippedOrientation"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withHorizontallyFlippedOrientation()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithHorizontallyFlippedOrientation"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}