{"sections":[],"metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Orientation","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false},{"name":"watchOS","unavailable":false,"beta":false,"introducedAt":"2.0","deprecated":false}],"navigatorTitle":[{"text":"Orientation","kind":"identifier"}],"externalID":"c:@E@UIImageOrientation","extendedModule":"UIKit","title":"UIImage.Orientation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimage/orientation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimage/orientation"]}],"abstract":[{"text":"Constants that specify the intended display orientation for an image.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Orientation"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"Orientation values are commonly found in image metadata, and specifying image orientation correctly can be important both for displaying the image and for certain kinds of image processing."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage"},{"type":"text","text":" class automatically handles the transform necessary to present an image in the correct display orientation according to its orientation metadata, so an image object’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation"},{"type":"text","text":" property simply indicates which transform was applied."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For example, an iOS device camera always encodes pixel data in the camera sensor’s native landscape orientation, along with metadata indicating the camera orientation. When UIImage loads a photo shot in portrait orientation, it automatically applies a 90° rotation before displaying the image data, and the image’s "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation"},{"type":"text","text":" value of "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right"},{"type":"text","text":" indicates that this rotation has been applied."}],"type":"paragraph"},{"inlineContent":[{"identifier":"media-2948302","type":"image"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Some frameworks describe image orientation using the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation"},{"text":" type (or the raw TIFF/Exif numeric values that type defines symbols for). However, the underlying numeric values of that type are incompatible with ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"},{"text":". For conversion help, see the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation"},{"text":" overview.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation","doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection","doc://com.apple.uikit/documentation/UIKit/UIImage/resizingMode-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/ResizingMode-swift.enum","doc://com.apple.uikit/documentation/UIKit/UIImage/duration","doc://com.apple.uikit/documentation/UIKit/UIImage/capInsets","doc://com.apple.uikit/documentation/UIKit/UIImage/alignmentRectInsets","doc://com.apple.uikit/documentation/UIKit/UIImage/isSymbolImage"],"generated":true,"anchor":"Accessing-image-attributes","title":"Accessing image attributes"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation"},"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"],"anchor":"Image-orientations","title":"Image orientations"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"flipsForRightToLeftLayoutDirection"}],"title":"flipsForRightToLeftLayoutDirection","url":"/documentation/uikit/uiimage/flipsforrighttoleftlayoutdirection","abstract":[{"type":"text","text":"A Boolean value that indicates whether the image flips in a right-to-left layout."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipsForRightToLeftLayoutDirection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/duration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"type":"topic","title":"duration","url":"/documentation/uikit/uiimage/duration","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/duration","navigatorTitle":[{"text":"duration","kind":"identifier"}],"abstract":[{"type":"text","text":"The time interval for displaying an animated image."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored":{"title":"UIImage.Orientation.leftMirrored","abstract":[{"type":"text","text":"The image has been rotated 90° clockwise and flipped horizontally from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationLeftMirrored"}],"url":"/documentation/uikit/uiimage/orientation/leftmirrored","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right":{"title":"UIImage.Orientation.right","abstract":[{"type":"text","text":"The image has been rotated 90° clockwise from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationRight"}],"url":"/documentation/uikit/uiimage/orientation/right","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImageOrientation","text":"Orientation","kind":"typeIdentifier"}],"type":"topic","title":"imageOrientation","url":"/documentation/uikit/uiimage/imageorientation","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation","navigatorTitle":[{"text":"imageOrientation","kind":"identifier"}],"abstract":[{"text":"The orientation of the receiver’s image.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up":{"title":"UIImage.Orientation.up","abstract":[{"text":"The original pixel data matches the image’s intended display orientation.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"up","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationUp","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/up","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/capInsets":{"role":"symbol","url":"/documentation/uikit/uiimage/capinsets","abstract":[{"type":"text","text":"The end-cap insets."}],"type":"topic","title":"capInsets","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"capInsets"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEdgeInsets","preciseIdentifier":"c:@S@UIEdgeInsets"}],"navigatorTitle":[{"kind":"identifier","text":"capInsets"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/capInsets","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left":{"title":"UIImage.Orientation.left","abstract":[{"type":"text","text":"The image has been rotated 90° counterclockwise from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationLeft"}],"url":"/documentation/uikit/uiimage/orientation/left","kind":"symbol"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/alignmentRectInsets":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alignmentRectInsets","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIEdgeInsets","kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets"}],"type":"topic","title":"alignmentRectInsets","url":"/documentation/uikit/uiimage/alignmentrectinsets","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/alignmentRectInsets","navigatorTitle":[{"text":"alignmentRectInsets","kind":"identifier"}],"abstract":[{"text":"The alignment metadata for positioning the image during layout.","type":"text"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the intended display orientation for an image."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Orientation"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation","title":"UIImage.Orientation","navigatorTitle":[{"kind":"identifier","text":"Orientation"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiimage/orientation"},"doc://com.apple.uikit/documentation/UIKit/UIImage/isSymbolImage":{"title":"isSymbolImage","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/isSymbolImage","abstract":[{"type":"text","text":"A Boolean value that indicates whether the image is a symbol."}],"type":"topic","navigatorTitle":[{"text":"symbolImage","kind":"identifier"}],"url":"/documentation/uikit/uiimage/issymbolimage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSymbolImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored":{"title":"UIImage.Orientation.upMirrored","abstract":[{"type":"text","text":"The image has been horizontally flipped from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationUpMirrored"}],"url":"/documentation/uikit/uiimage/orientation/upmirrored","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored":{"title":"UIImage.Orientation.rightMirrored","abstract":[{"text":"The image has been rotated 90° counterclockwise and flipped horizontally from the orientation of its original pixel data.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightMirrored","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationRightMirrored","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/rightmirrored","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored":{"title":"UIImage.Orientation.downMirrored","abstract":[{"type":"text","text":"The image has been vertically flipped from the orientation of its original pixel data."}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"downMirrored"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageOrientationDownMirrored"}],"url":"/documentation/uikit/uiimage/orientation/downmirrored","kind":"symbol"},"media-2948302":{"variants":[{"traits":["1x","light"],"url":"https://docs-assets.developer.apple.com/published/5f85393673d69bff25539fb1abf634d9/media-2948302.png"},{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/a4de8a358cbf9a76800cc595fceb8892/media-2948302@2x.png"}],"alt":"UIImage rotates an image with right orientation for correct display","identifier":"media-2948302","type":"image"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/init(rawValue:)","url":"/documentation/uikit/uiimage/orientation/init(rawvalue:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/ResizingMode-swift.enum":{"role":"symbol","abstract":[{"type":"text","text":"Constants that specify the possible resizing modes for an image."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResizingMode"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/ResizingMode-swift.enum","title":"UIImage.ResizingMode","navigatorTitle":[{"kind":"identifier","text":"ResizingMode"}],"type":"topic","kind":"symbol","url":"/documentation/uikit/uiimage/resizingmode-swift.enum"},"doc://com.apple.uikit/documentation/UIKit/UIImage/resizingMode-swift.property":{"title":"resizingMode","type":"topic","navigatorTitle":[{"text":"resizingMode","kind":"identifier"}],"abstract":[{"text":"The resizing mode of the image.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/resizingMode-swift.property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resizingMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":".","kind":"text"},{"text":"ResizingMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageResizingMode"}],"kind":"symbol","url":"/documentation/uikit/uiimage/resizingmode-swift.property"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down":{"title":"UIImage.Orientation.down","abstract":[{"text":"The image has been rotated 180° from the orientation of its original pixel data.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"down","kind":"identifier"}],"navigatorTitle":[{"text":"UIImageOrientationDown","kind":"identifier"}],"url":"/documentation/uikit/uiimage/orientation/down","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation":{"abstract":[{"type":"text","text":"A value describing the intended display orientation for an image."}],"title":"CGImagePropertyOrientation","role":"symbol","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImagePropertyOrientation"}],"url":"/documentation/ImageIO/CGImagePropertyOrientation","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration","op":"replace"},{"path":"/metadata/title","value":"UIImageOrientation","op":"replace"},{"path":"/metadata/symbolKind","value":"enum","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIImageOrientation"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"UIImageOrientation"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Image orientations","anchor":"Image-orientations","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/up","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/down","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/left","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/right","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/upMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/downMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/leftMirrored","doc://com.apple.uikit/documentation/UIKit/UIImage/Orientation/rightMirrored"]}],"op":"replace"},{"path":"/relationshipsSections","value":null,"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.documentation/documentation/ImageIO/CGImagePropertyOrientation"],"anchor":"Related-Documentation","title":"Related Documentation"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/imageOrientation","doc://com.apple.uikit/documentation/UIKit/UIImage/flipsForRightToLeftLayoutDirection","doc://com.apple.uikit/documentation/UIKit/UIImage/resizingMode-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/ResizingMode-swift.enum","doc://com.apple.uikit/documentation/UIKit/UIImage/duration","doc://com.apple.uikit/documentation/UIKit/UIImage/capInsets","doc://com.apple.uikit/documentation/UIKit/UIImage/alignmentRectInsets","doc://com.apple.uikit/documentation/UIKit/UIImage/isSymbolImage"],"generated":true,"anchor":"Accessing-image-attributes","title":"Accessing image attributes"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIImageOrientation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"flipsForRightToLeftLayoutDirection","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1flipsForRightToLeftLayoutDirection/title","op":"replace"},{"value":[{"kind":"identifier","text":"flipsForRightToLeftLayoutDirection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1flipsForRightToLeftLayoutDirection/fragments","op":"replace"},{"value":"duration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1duration/title","op":"replace"},{"value":[{"kind":"identifier","text":"duration"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1duration/fragments","op":"replace"},{"value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace"},{"value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace"},{"value":"UIImageOrientationLeftMirrored","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/title","op":"replace"},{"value":[{"text":"UIImageOrientationLeftMirrored","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1leftMirrored/fragments","op":"replace"},{"value":"UIImageOrientationRight","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageOrientationRight"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1right/fragments","op":"replace"},{"value":"imageOrientation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageOrientation/title","op":"replace"},{"value":[{"kind":"identifier","text":"imageOrientation"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageOrientation/fragments","op":"replace"},{"value":"UIImageOrientationUp","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/title","op":"replace"},{"value":[{"text":"UIImageOrientationUp","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1up/fragments","op":"replace"},{"value":"capInsets","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1capInsets/title","op":"replace"},{"value":[{"kind":"identifier","text":"capInsets"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1capInsets/fragments","op":"replace"},{"value":"UIImageOrientationLeft","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/title","op":"replace"},{"value":[{"text":"UIImageOrientationLeft","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1left/fragments","op":"replace"},{"value":"alignmentRectInsets","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1alignmentRectInsets/title","op":"replace"},{"value":[{"kind":"identifier","text":"alignmentRectInsets"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1alignmentRectInsets/fragments","op":"replace"},{"value":"UIImageOrientation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/title","op":"replace"},{"value":[{"text":"UIImageOrientation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageOrientation"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation/navigatorTitle","op":"replace"},{"value":"symbolImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1isSymbolImage/title","op":"replace"},{"value":[{"kind":"identifier","text":"symbolImage"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1isSymbolImage/fragments","op":"replace"},{"value":"UIImageOrientationUpMirrored","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageOrientationUpMirrored"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1upMirrored/fragments","op":"replace"},{"value":"UIImageOrientationRightMirrored","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/title","op":"replace"},{"value":[{"text":"UIImageOrientationRightMirrored","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1rightMirrored/fragments","op":"replace"},{"value":"UIImageOrientationDownMirrored","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/title","op":"replace"},{"value":[{"text":"UIImageOrientationDownMirrored","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1downMirrored/fragments","op":"replace"},{"value":"UIImageResizingMode","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1ResizingMode-swift.enum/title","op":"replace"},{"value":[{"text":"UIImageResizingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1ResizingMode-swift.enum/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageResizingMode"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1ResizingMode-swift.enum/navigatorTitle","op":"replace"},{"value":"resizingMode","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizingMode-swift.property/title","op":"replace"},{"value":[{"kind":"identifier","text":"resizingMode"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1resizingMode-swift.property/fragments","op":"replace"},{"value":"UIImageOrientationDown","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/title","op":"replace"},{"value":[{"text":"UIImageOrientationDown","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Orientation~1down/fragments","op":"replace"},{"value":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImagePropertyOrientation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t","text":"uint32_t"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1ImageIO~1CGImagePropertyOrientation/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}