{"abstract":[{"type":"text","text":"The standard image for indicating the removal of content."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIImage/remove","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","seeAlsoSections":[{"title":"Getting standard system images","generated":true,"anchor":"Getting-standard-system-images","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/add","doc://com.apple.uikit/documentation/UIKit/UIImage/actions","doc://com.apple.uikit/documentation/UIKit/UIImage/checkmark","doc://com.apple.uikit/documentation/UIKit/UIImage/strokedCheckmark"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimage/remove"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimage/remove"]}],"metadata":{"extendedModule":"UIKit","title":"remove","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"removeImage"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"13.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"13.1"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"6.0","name":"watchOS"}],"externalID":"c:objc(cs)UIImage(cpy)removeImage"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIImage/add":{"abstract":[{"type":"text","text":"The standard image for indicating the addition of content."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/add","url":"/documentation/uikit/uiimage/add","title":"add","navigatorTitle":[{"kind":"identifier","text":"addImage"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"add"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/actions":{"abstract":[{"type":"text","text":"The standard image for indicating user-initiated actions."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/actions","url":"/documentation/uikit/uiimage/actions","title":"actions","navigatorTitle":[{"kind":"identifier","text":"actionsImage"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"actions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/checkmark":{"abstract":[{"type":"text","text":"The standard image for a checkmark on a filled-circle background."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/checkmark","url":"/documentation/uikit/uiimage/checkmark","title":"checkmark","navigatorTitle":[{"kind":"identifier","text":"checkmarkImage"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/strokedCheckmark":{"abstract":[{"type":"text","text":"The standard image for a checkmark on a tinted circle with a white-stroked border."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/strokedCheckmark","url":"/documentation/uikit/uiimage/strokedcheckmark","title":"strokedCheckmark","navigatorTitle":[{"kind":"identifier","text":"strokedCheckmarkImage"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"strokedCheckmark"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/remove":{"abstract":[{"type":"text","text":"The standard image for indicating the removal of content."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/remove","url":"/documentation/uikit/uiimage/remove","title":"remove","navigatorTitle":[{"kind":"identifier","text":"removeImage"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"6.0","name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Property","op":"replace","path":"/metadata/roleHeading"},{"value":"removeImage","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"removeImage"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Getting standard system images","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/add","doc://com.apple.uikit/documentation/UIKit/UIImage/actions","doc://com.apple.uikit/documentation/UIKit/UIImage/checkmark","doc://com.apple.uikit/documentation/UIKit/UIImage/strokedCheckmark"],"anchor":"Getting-standard-system-images"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"addImage","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1add/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1add/fragments","value":[{"text":"addImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"text":"UIImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"text":"UIImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1actions/title","value":"actionsImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1actions/fragments","value":[{"text":"actionsImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1checkmark/title","value":"checkmarkImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1checkmark/fragments","value":[{"kind":"identifier","text":"checkmarkImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1strokedCheckmark/title","value":"strokedCheckmarkImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1strokedCheckmark/fragments","value":[{"text":"strokedCheckmarkImage","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1remove/title","value":"removeImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1remove/fragments","value":[{"kind":"identifier","text":"removeImage"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}