{"topicSections":[{"title":"Rendering modes","anchor":"Rendering-modes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/automatic","doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysTemplate"]},{"title":"Initializers","anchor":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/init(rawValue:)"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RenderingMode","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"The rendering mode controls how UIKit uses color information to display an image. See "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances","isActive":true},{"type":"text","text":" for creating tintable images with template mode."}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/uikit/uiimage/renderingmode-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiimage/renderingmode-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"symbolKind":"enum","externalID":"c:@E@UIImageRenderingMode","title":"UIImage.RenderingMode","platforms":[{"name":"iOS","introducedAt":"7.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"7.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false}],"extendedModule":"UIKit","navigatorTitle":[{"kind":"identifier","text":"RenderingMode"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderingMode"}],"roleHeading":"Enumeration"},"abstract":[{"type":"text","text":"Constants that specify the possible rendering modes for an image."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"seeAlsoSections":[{"title":"Getting rendering information","anchor":"Getting-rendering-information","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/renderingMode-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/imageRendererFormat"],"generated":true}],"references":{"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/renderingMode-swift.property":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/renderingMode-swift.property","type":"topic","title":"renderingMode","url":"/documentation/uikit/uiimage/renderingmode-swift.property","kind":"symbol","navigatorTitle":[{"text":"renderingMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"renderingMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"text":"RenderingMode","preciseIdentifier":"c:@E@UIImageRenderingMode","kind":"typeIdentifier"}],"abstract":[{"text":"A setting that determines how the app renders an image.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/imageRendererFormat":{"title":"imageRendererFormat","navigatorTitle":[{"text":"imageRendererFormat","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"/documentation/uikit/uiimage/imagerendererformat","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/imageRendererFormat","abstract":[{"text":"The preferred image renderer format for the image.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageRendererFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIGraphicsImageRendererFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum":{"role":"symbol","title":"UIImage.RenderingMode","url":"/documentation/uikit/uiimage/renderingmode-swift.enum","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Constants that specify the possible rendering modes for an image."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderingMode"}],"navigatorTitle":[{"kind":"identifier","text":"RenderingMode"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/automatic":{"role":"symbol","title":"UIImage.RenderingMode.automatic","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/automatic","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Draw the image using the context’s default rendering mode."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageRenderingModeAutomatic"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/automatic"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/init(rawValue:)":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"init(rawValue:)","role":"symbol","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/init(rawvalue:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal":{"navigatorTitle":[{"kind":"identifier","text":"UIImageRenderingModeAlwaysOriginal"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysOriginal"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Always draw the original image, without treating it as a template."}],"role":"symbol","title":"UIImage.RenderingMode.alwaysOriginal","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/alwaysoriginal"},"doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances":{"role":"article","url":"/documentation/uikit/providing-images-for-different-appearances","type":"topic","abstract":[{"text":"Supply image resources appropriate for light and dark appearances and for high-contrast environments.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances","kind":"article","title":"Providing images for different appearances"},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysTemplate":{"role":"symbol","title":"UIImage.RenderingMode.alwaysTemplate","url":"/documentation/uikit/uiimage/renderingmode-swift.enum/alwaystemplate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Always draw the image as a template image, ignoring its color information."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysTemplate"}],"navigatorTitle":[{"kind":"identifier","text":"UIImageRenderingModeAlwaysTemplate"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysTemplate"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"iOS","introducedAt":"7.0","unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"7.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration","path":"/metadata/roleHeading"},{"op":"replace","value":"UIImageRenderingMode","path":"/metadata/title"},{"op":"replace","value":"enum","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"UIImageRenderingMode","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIImageRenderingMode"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/automatic","doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysOriginal","doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum/alwaysTemplate"],"title":"Rendering modes","anchor":"Rendering-modes"}],"path":"/topicSections"},{"op":"replace","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/renderingMode-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/imageRendererFormat"],"generated":true,"anchor":"Getting-rendering-information","title":"Getting rendering information"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImageRenderingMode","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1renderingMode-swift.property/title","op":"replace","value":"renderingMode"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1renderingMode-swift.property/fragments","op":"replace","value":[{"text":"renderingMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageRendererFormat/title","op":"replace","value":"imageRendererFormat"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1imageRendererFormat/fragments","op":"replace","value":[{"text":"imageRendererFormat","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/title","op":"replace","value":"UIImageRenderingMode"},{"value":[{"kind":"identifier","text":"UIImageRenderingMode"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageRenderingMode"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/navigatorTitle","op":"replace"},{"value":"UIImageRenderingModeAutomatic","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1automatic/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIImageRenderingModeAutomatic"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1automatic/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"text":"UIImage","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/title","value":"UIImageRenderingModeAlwaysOriginal","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysOriginal/fragments","value":[{"kind":"identifier","text":"UIImageRenderingModeAlwaysOriginal"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysTemplate/title","value":"UIImageRenderingModeAlwaysTemplate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum~1alwaysTemplate/fragments","value":[{"text":"UIImageRenderingModeAlwaysTemplate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}