{"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIImage/scale","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Getting the image size and scale","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/size"],"anchor":"Getting-the-image-size-and-scale"}],"metadata":{"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"4.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"4.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS","beta":false}],"externalID":"c:objc(cs)UIImage(py)scale","navigatorTitle":[{"kind":"identifier","text":"scale"}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","title":"scale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimage/scale"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimage/scale"]}],"abstract":[{"text":"The scale factor of the image.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If you load an image from a file whose name includes the "},{"code":"@2x","type":"codeVoice"},{"type":"text","text":" modifier, the scale is set to "},{"code":"2.0","type":"codeVoice"},{"type":"text","text":". You can also specify an explicit scale factor when initializing an image from a Core Graphics image. All other images are assumed to have a scale factor of "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"If you multiply the logical size of the image (stored in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/size"},{"type":"text","text":" property) by the value in this property, you get the dimensions of the image in pixels."}],"type":"paragraph"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/scale":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/scale","kind":"symbol","navigatorTitle":[{"text":"scale","kind":"identifier"}],"title":"scale","role":"symbol","abstract":[{"type":"text","text":"The scale factor of the image."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"type":"topic","url":"/documentation/uikit/uiimage/scale"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/UIImage/size":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/size","url":"/documentation/uikit/uiimage/size","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"type":"topic","role":"symbol","title":"size","abstract":[{"text":"The logical dimensions, in points, for the image.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"4.0"},{"beta":false,"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"4.0"},{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"scale"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"scale"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Getting the image size and scale","anchor":"Getting-the-image-size-and-scale","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/size"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1scale/title","op":"replace","value":"scale"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1scale/fragments","op":"replace","value":[{"kind":"identifier","text":"scale"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace","value":"UIImage"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace","value":[{"kind":"identifier","text":"UIImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1size/title","op":"replace","value":"size"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1size/fragments","op":"replace","value":[{"kind":"identifier","text":"size"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}