{"seeAlsoSections":[{"generated":true,"title":"Getting the image configuration","anchor":"Getting-the-image-configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/configuration-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/symbolConfiguration-swift.property"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:objc(cs)UIImage(py)traitCollection","roleHeading":"Instance Property","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"traitCollection"}],"platforms":[{"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier","text":"UITraitCollection"}],"role":"symbol","title":"traitCollection","symbolKind":"property"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIImage/traitCollection","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@NSCopying","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"traitCollection","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"kind":"symbol","abstract":[{"text":"The trait collection that describes the current variant of the image.","type":"text"}],"variants":[{"paths":["/documentation/uikit/uiimage/traitcollection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiimage/traitcollection"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIImage/symbolConfiguration-swift.property":{"type":"topic","abstract":[{"type":"text","text":"The configuration details for a symbol image."}],"title":"symbolConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbolConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)UIImageSymbolConfiguration","kind":"typeIdentifier","text":"SymbolConfiguration"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/symbolConfiguration-swift.property","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiimage/symbolconfiguration-swift.property","navigatorTitle":[{"kind":"identifier","text":"symbolConfiguration"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITraitCollection":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UITraitCollection","kind":"identifier"}],"title":"UITraitCollection","url":"/documentation/uikit/uitraitcollection","abstract":[{"text":"A collection of data that represents the environment for an individual element in your app’s user interface.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitCollection","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/configuration-swift.property":{"type":"topic","abstract":[{"type":"text","text":"The configuration details for the image."}],"title":"configuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)UIImageConfiguration","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/configuration-swift.property","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiimage/configuration-swift.property","navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/traitCollection":{"type":"topic","abstract":[{"type":"text","text":"The trait collection that describes the current variant of the image."}],"title":"traitCollection","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"traitCollection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITraitCollection","kind":"typeIdentifier","text":"UITraitCollection"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/traitCollection","kind":"symbol","role":"symbol","url":"/documentation/uikit/uiimage/traitcollection","navigatorTitle":[{"kind":"identifier","text":"traitCollection"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"traitCollection","path":"/metadata/title","op":"replace"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"traitCollection","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/configuration-swift.property","doc://com.apple.uikit/documentation/UIKit/UIImage/symbolConfiguration-swift.property"],"generated":true,"anchor":"Getting-the-image-configuration","title":"Getting the image configuration"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITraitCollection","text":"UITraitCollection","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitCollection"},{"text":" * ","kind":"text"},{"text":"traitCollection","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1symbolConfiguration-swift.property/title","value":"symbolConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1symbolConfiguration-swift.property/fragments","value":[{"kind":"identifier","text":"symbolConfiguration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/title","value":"UITraitCollection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/fragments","value":[{"text":"UITraitCollection","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/navigatorTitle","value":[{"text":"UITraitCollection","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","value":"UIImage"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","value":[{"kind":"identifier","text":"UIImage"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1configuration-swift.property/title","value":"configuration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1configuration-swift.property/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1traitCollection/title","value":"traitCollection"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1traitCollection/fragments","value":[{"text":"traitCollection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}