{"abstract":[{"text":"Returns a new version of the image with a tint color that uses the specified rendering mode.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iPadOS"},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"6.0","name":"watchOS","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTintColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"renderingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageRenderingMode","text":"RenderingMode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"externalID":"c:objc(cs)UIImage(im)imageWithTintColor:renderingMode:","navigatorTitle":[{"kind":"identifier","text":"imageWithTintColor:renderingMode:"}],"title":"withTintColor(_:renderingMode:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:)"],"generated":true,"anchor":"Tinting-the-image","title":"Tinting the image"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiimage/withtintcolor(_:renderingmode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiimage/withtintcolor(_:renderingmode:)"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:renderingMode:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withTintColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"renderingMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":".","kind":"text"},{"text":"RenderingMode","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum","preciseIdentifier":"c:@E@UIImageRenderingMode"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage"}]}],"kind":"declarations"},{"parameters":[{"name":"color","content":[{"inlineContent":[{"text":"The tint color to apply to the image.","type":"text"}],"type":"paragraph"}]},{"name":"renderingMode","content":[{"inlineContent":[{"text":"The rendering mode to assign to the returned image.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new version of the image that incorporates the specified tint color.","type":"text"}]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"For bitmap images, this method draws the background tint color followed by the image contents using the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgblendmode/destinationin"},{"type":"text","text":" mode. For symbol images, this method returns an image that always uses the specified tint color."}],"type":"paragraph"}]}],"references":{"doc://com.apple.documentation/documentation/coregraphics/cgblendmode/destinationin":{"type":"topic","url":"/documentation/coregraphics/cgblendmode/destinationin","kind":"symbol","fragments":[{"text":"case ","kind":"text"},{"text":"destinationIn","kind":"identifier"}],"title":"CGBlendMode.destinationIn","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgblendmode/destinationin","role":"symbol","abstract":[{"text":"`R = D*Sa`","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum":{"role":"symbol","title":"UIImage.RenderingMode","url":"/documentation/uikit/uiimage/renderingmode-swift.enum","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Constants that specify the possible rendering modes for an image."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RenderingMode"}],"navigatorTitle":[{"kind":"identifier","text":"RenderingMode"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:)":{"type":"topic","url":"/documentation/uikit/uiimage/withtintcolor(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"withTintColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"title":"withTintColor(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithTintColor:"}],"abstract":[{"text":"Returns a new version of the current image with the specified tint color.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor":{"type":"topic","role":"symbol","title":"UIColor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIColor","kind":"identifier"}],"navigatorTitle":[{"text":"UIColor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/uikit/uicolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:renderingMode:)":{"type":"topic","url":"/documentation/uikit/uiimage/withtintcolor(_:renderingmode:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withTintColor","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"renderingMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"RenderingMode","preciseIdentifier":"c:@E@UIImageRenderingMode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}],"title":"withTintColor(_:renderingMode:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:renderingMode:)","role":"symbol","navigatorTitle":[{"text":"imageWithTintColor:renderingMode:","kind":"identifier"}],"abstract":[{"text":"Returns a new version of the image with a tint color that uses the specified rendering mode.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"introducedAt":"1.0","unavailable":false,"name":"visionOS"},{"beta":false,"deprecated":false,"introducedAt":"6.0","unavailable":false,"name":"watchOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"imageWithTintColor:renderingMode:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"imageWithTintColor:renderingMode:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIImage"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"anchor":"Tinting-the-image","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIImage/withTintColor(_:)"],"title":"Tinting the image","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage"},{"text":" *) ","kind":"text"},{"text":"imageWithTintColor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"renderingMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImageRenderingMode","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage/RenderingMode-swift.enum","preciseIdentifier":"c:@E@UIImageRenderingMode"},{"text":") ","kind":"text"},{"text":"renderingMode","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"parameters":[{"name":"color","content":[{"inlineContent":[{"text":"The tint color to apply to the image.","type":"text"}],"type":"paragraph"}]},{"name":"renderingMode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The rendering mode to assign to the returned image."}]}]}],"kind":"parameters"},"path":"/primaryContentSections/1"},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A new version of the image that incorporates the specified tint color.","type":"text"}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"op":"replace","value":"kCGBlendModeDestinationIn","path":"/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgblendmode~1destinationin/title"},{"op":"replace","value":"UIImageRenderingMode","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIImageRenderingMode"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/fragments"},{"op":"replace","value":[{"text":"UIImageRenderingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1RenderingMode-swift.enum/navigatorTitle"},{"op":"replace","value":"imageWithTintColor:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withTintColor(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageWithTintColor:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withTintColor(_:)/fragments"},{"op":"replace","value":"UIColor","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title"},{"op":"replace","value":[{"text":"UIColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIColor"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle"},{"op":"replace","value":"UIImage","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments"},{"op":"replace","value":[{"text":"UIImage","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle"},{"op":"replace","value":"imageWithTintColor:renderingMode:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withTintColor(_:renderingMode:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageWithTintColor:renderingMode:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1withTintColor(_:renderingMode:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}