{
  "abstract": [
    {
      "text": "Returns a constraint that defines one item’s attribute as less than or equal to another.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSLayoutAnchor(im)constraintLessThanOrEqualToAnchor:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "constraint"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "lessThanOrEqualTo"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
        "text": "NSLayoutAnchor"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "AnchorType"
      },
      {
        "kind": "text",
        "text": ">) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
        "text": "NSLayoutConstraint"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "constraintLessThanOrEqualToAnchor:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "constraint(lessThanOrEqualTo:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "constraint"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "lessThanOrEqualTo"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "anchor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
              "text": "NSLayoutAnchor"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "AnchorType"
            },
            {
              "kind": "text",
              "text": ">) -> "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
              "text": "NSLayoutConstraint"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A layout anchor from an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object. You must use a subclass of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " that matches the current anchor. For example, if you call this method on an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object, this parameter must be another ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "anchor"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that defines the attribute represented by this layout anchor as less than or equal to the attribute represented by the ",
              "type": "text"
            },
            {
              "code": "anchor",
              "type": "codeVoice"
            },
            {
              "text": " parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method defines the relationship ",
              "type": "text"
            },
            {
              "code": "first attribute <= second attribute",
              "type": "codeVoice"
            },
            {
              "text": ". Where ",
              "type": "text"
            },
            {
              "code": "first attribute",
              "type": "codeVoice"
            },
            {
              "text": " is the layout attribute represented by the anchor receiving this method call, and ",
              "type": "text"
            },
            {
              "code": "second attribute",
              "type": "codeVoice"
            },
            {
              "text": " is the layout attribute represented by the ",
              "type": "text"
            },
            {
              "code": "anchor",
              "type": "codeVoice"
            },
            {
              "text": " parameter. All values are measured in points; however, these values can be interpreted in different ways, depending on the type of layout anchor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For leading or trailing anchors, the values increase as you move in the current language’s reading direction. For English, values increase as you move to the right.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For left and right anchors, the values increase as you move to the right.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects, the values increase as you move down.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects, the values increase as the items increase in size.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The constraints produced by the following two examples are identical.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// Creating a constraint using NSLayoutConstraint",
                    "NSLayoutConstraint(item: subview,",
                    "                   attribute: .Leading,",
                    "                   relatedBy: .LessThanOrEqual,",
                    "                   toItem: view,",
                    "                   attribute: .LeadingMargin,",
                    "                   multiplier: 1.0,",
                    "                   constant: 0.0).isActive = true",
                    " ",
                    "// Creating the same constraint using constraintLessThanOrEqualToAnchor:",
                    "let margins = view.layoutMarginsGuide",
                    "subview.leadingAnchor.constraintLessThanOrEqualToAnchor(margins.leadingAnchor).isActive = true"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// Creating a constraint using NSLayoutConstraint",
                    "[NSLayoutConstraint",
                    " constraintWithItem:subview",
                    " attribute:NSLayoutAttributeLeading",
                    " relatedBy:NSLayoutRelationLessThanOrEqual",
                    " toItem:self.view",
                    " attribute:NSLayoutAttributeLeadingMargin",
                    " multiplier:1.0",
                    " constant:0.0].active = YES;",
                    " ",
                    "// Creating the same constraint using constraintLessThanOrEqualToAnchor:",
                    "NSLayoutGuide *margin = self.view.layoutMarginsGuide;",
                    "[subview.leadingAnchor constraintLessThanOrEqualToAnchor:margin.leadingAnchor].active = YES;"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as equal to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "equalTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintEqualToAnchor:"
        }
      ],
      "role": "symbol",
      "title": "constraint(equalTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(equalto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:constant:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as equal to another item’s attribute plus a constant offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "equalTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "constant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:constant:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintEqualToAnchor:constant:"
        }
      ],
      "role": "symbol",
      "title": "constraint(equalTo:constant:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(equalto:constant:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as greater than or equal to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "greaterThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintGreaterThanOrEqualToAnchor:"
        }
      ],
      "role": "symbol",
      "title": "constraint(greaterThanOrEqualTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(greaterthanorequalto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:constant:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as greater than or equal to another item’s attribute plus a constant offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "greaterThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "constant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:constant:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintGreaterThanOrEqualToAnchor:constant:"
        }
      ],
      "role": "symbol",
      "title": "constraint(greaterThanOrEqualTo:constant:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(greaterthanorequalto:constant:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as less than or equal to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lessThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintLessThanOrEqualToAnchor:"
        }
      ],
      "role": "symbol",
      "title": "constraint(lessThanOrEqualTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(lessthanorequalto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:constant:)": {
      "abstract": [
        {
          "text": "Returns a constraint that defines one item’s attribute as less than or equal to another item’s attribute plus a constant offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "constraint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "lessThanOrEqualTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutAnchor",
          "text": "NSLayoutAnchor"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "AnchorType"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "constant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:constant:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "constraintLessThanOrEqualToAnchor:constant:"
        }
      ],
      "role": "symbol",
      "title": "constraint(lessThanOrEqualTo:constant:)",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutanchor/constraint(lessthanorequalto:constant:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutconstraint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension": {
      "abstract": [
        {
          "text": "A factory class for creating size-based layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutDimension"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutDimension",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutdimension"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide": {
      "abstract": [
        {
          "text": "A rectangular area that can interact with Auto Layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutGuide"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutGuide",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutguide"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating horizontal layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutXAxisAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutXAxisAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutxaxisanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor": {
      "abstract": [
        {
          "text": "A factory class for creating vertical layout constraint objects using a fluent API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutYAxisAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutYAxisAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutYAxisAnchor",
      "type": "topic",
      "url": "/documentation/appkit/nslayoutyaxisanchor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/appkit/nsview"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Building-constraints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:constant:)",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:constant:)",
        "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:constant:)"
      ],
      "title": "Building constraints"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "constraintLessThanOrEqualToAnchor:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintLessThanOrEqualToAnchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Building-constraints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(equalTo:constant:)",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:)",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(greaterThanOrEqualTo:constant:)",
                "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor/constraint(lessThanOrEqualTo:constant:)"
              ],
              "title": "Building constraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
                    "text": "NSLayoutConstraint"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "constraintLessThanOrEqualToAnchor:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSLayoutAnchor",
                    "text": "NSLayoutAnchor<id>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "anchor"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A layout anchor from an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutGuide",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object. You must use a subclass of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutAnchor",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " that matches the current anchor. For example, if you call this method on an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object, this parameter must be another ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutXAxisAnchor",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "anchor"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSLayoutConstraint",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object that defines the attribute represented by this layout anchor as less than or equal to the attribute represented by the ",
                    "type": "text"
                  },
                  {
                    "code": "anchor",
                    "type": "codeVoice"
                  },
                  {
                    "text": " parameter.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/title",
          "value": "NSLayoutYAxisAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutYAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutYAxisAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutYAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(greaterThanOrEqualTo:)/title",
          "value": "constraintGreaterThanOrEqualToAnchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(greaterThanOrEqualTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintGreaterThanOrEqualToAnchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(greaterThanOrEqualTo:constant:)/title",
          "value": "constraintGreaterThanOrEqualToAnchor:constant:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(greaterThanOrEqualTo:constant:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintGreaterThanOrEqualToAnchor:constant:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title",
          "value": "NSView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(equalTo:)/title",
          "value": "constraintEqualToAnchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(equalTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintEqualToAnchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutXAxisAnchor/title",
          "value": "NSLayoutXAxisAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutXAxisAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutXAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutXAxisAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutXAxisAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(equalTo:constant:)/title",
          "value": "constraintEqualToAnchor:constant:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(equalTo:constant:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintEqualToAnchor:constant:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/title",
          "value": "NSLayoutDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutDimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(lessThanOrEqualTo:constant:)/title",
          "value": "constraintLessThanOrEqualToAnchor:constant:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(lessThanOrEqualTo:constant:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintLessThanOrEqualToAnchor:constant:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(lessThanOrEqualTo:)/title",
          "value": "constraintLessThanOrEqualToAnchor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor~1constraint(lessThanOrEqualTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "constraintLessThanOrEqualToAnchor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/title",
          "value": "NSLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutGuide/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor/title",
          "value": "NSLayoutAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSLayoutAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nslayoutanchor/constraint(lessthanorequalto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nslayoutanchor/constraint(lessthanorequalto:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
