{
  "abstract": [
    {
      "text": "An Apple Pay button useful for renting items such as cars or scooters.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/rent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPaymentButtonType@PKPaymentButtonTypeRent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rent"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentButtonTypeRent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPaymentButtonType.rent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This button looks like:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3667468",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType": {
      "abstract": [
        {
          "text": "The Apple Pay button types you can display to initiate Apple Pay transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentButtonType"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonType"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/addMoney": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for adding money to a card, account, or payment system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addMoney"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/addMoney",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeAddMoney"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.addMoney",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/addmoney"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/book": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for booking trips, flights, or other experiences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "book"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/book",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeBook"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.book",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/book"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/buy": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for product purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buy"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/buy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeBuy"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.buy",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/buy"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/checkout": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for purchase experiences that include other payment buttons that start with “Check out”.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkout"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/checkout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeCheckout"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.checkout",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/checkout"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/continue": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for general purchases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`continue`"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/continue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeContinue"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.continue",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/continue"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/contribute": {
      "abstract": [
        {
          "text": "An Apple Pay button useful to help people contribute money to projects, causes, organizations, and other entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contribute"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/contribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeContribute"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.contribute",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/contribute"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/donate": {
      "abstract": [
        {
          "text": "An Apple Pay button used by approved nonprofit organization that lets people make donations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "donate"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/donate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeDonate"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.donate",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/donate"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/inStore": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for paying bills or invoices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inStore"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/inStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeInStore"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.inStore",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/instore"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/order": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for placing orders for such as like meals or flowers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "order"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/order",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeOrder"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.order",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/order"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/plain": {
      "abstract": [
        {
          "text": "An Apple Pay button with the Apple Pay logo only, useful when an additional call to action isn’t needed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plain"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/plain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypePlain"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.plain",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/plain"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/reload": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for adding money to a card, account, or payment system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reload"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/reload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeReload"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.reload",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/reload"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/rent": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for renting items such as cars or scooters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rent"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/rent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeRent"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.rent",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/rent"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/setUp": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for prompting the user to set up a card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setUp"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/setUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeSetUp"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.setUp",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/setup"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/subscribe": {
      "abstract": [
        {
          "text": "An Apple Pay button useful for purchasing a subscription such as a gym membership or meal-kit delivery service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subscribe"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/subscribe",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeSubscribe"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.subscribe",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/subscribe"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/support": {
      "abstract": [
        {
          "text": "An Apple Pay button useful supporting people give money to projects, causes, organizations, and other entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "support"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/support",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeSupport"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.support",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/support"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/tip": {
      "abstract": [
        {
          "text": "An Apple Pay button useful useful for letting people tip for goods or services.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tip"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/tip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentButtonTypeTip"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentButtonType.tip",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymentbuttontype/tip"
    },
    "https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/",
      "title": "Human Interface Guidelines > Apple Pay > Buttons and Marks",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Apple Pay > Buttons and Marks",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/"
    },
    "media-3667468": {
      "alt": "A button with the text “Rent with” and the Apple Pay logo.",
      "identifier": "media-3667468",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/76031f404448d513815d6f552533b812/media-3667468@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Payment-button-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/plain",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/buy",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/addMoney",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/book",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/checkout",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/continue",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/contribute",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/donate",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/inStore",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/order",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/reload",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/setUp",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/subscribe",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/support",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/tip"
      ],
      "title": "Payment button types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentButtonTypeRent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeRent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Payment-button-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/plain",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/buy",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/addMoney",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/book",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/checkout",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/continue",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/contribute",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/donate",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/inStore",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/order",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/reload",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/setUp",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/subscribe",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/support",
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentButtonType/tip"
              ],
              "title": "Payment button types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKPaymentButtonTypeRent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1order/title",
          "value": "PKPaymentButtonTypeOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1order/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1inStore/title",
          "value": "PKPaymentButtonTypeInStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1inStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeInStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1book/title",
          "value": "PKPaymentButtonTypeBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1book/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1donate/title",
          "value": "PKPaymentButtonTypeDonate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1donate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeDonate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1plain/title",
          "value": "PKPaymentButtonTypePlain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1plain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypePlain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1contribute/title",
          "value": "PKPaymentButtonTypeContribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1contribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeContribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1rent/title",
          "value": "PKPaymentButtonTypeRent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1rent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeRent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1subscribe/title",
          "value": "PKPaymentButtonTypeSubscribe"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1subscribe/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeSubscribe"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1checkout/title",
          "value": "PKPaymentButtonTypeCheckout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1checkout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeCheckout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1addMoney/title",
          "value": "PKPaymentButtonTypeAddMoney"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1addMoney/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeAddMoney"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType/title",
          "value": "PKPaymentButtonType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1setUp/title",
          "value": "PKPaymentButtonTypeSetUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1setUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeSetUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1buy/title",
          "value": "PKPaymentButtonTypeBuy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1buy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeBuy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1support/title",
          "value": "PKPaymentButtonTypeSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1support/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1reload/title",
          "value": "PKPaymentButtonTypeReload"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1reload/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeReload"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1continue/title",
          "value": "PKPaymentButtonTypeContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1continue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1tip/title",
          "value": "PKPaymentButtonTypeTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentButtonType~1tip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentButtonTypeTip"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymentbuttontype/rent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymentbuttontype/rent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
