{
  "abstract": [
    {
      "text": "The ranges of characters to highlight in the subtitle string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mapkit/documentation/MapKit",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitleHighlightRanges"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MKLocalSearchCompletion(py)subtitleHighlightRanges",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "subtitleHighlightRanges"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSValue",
        "text": "NSValue"
      },
      {
        "kind": "text",
        "text": "]"
      }
    ],
    "modules": [
      {
        "name": "MapKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "subtitleHighlightRanges"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "subtitleHighlightRanges"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "subtitleHighlightRanges"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSValue",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSValue",
              "text": "NSValue"
            },
            {
              "kind": "text",
              "text": "] { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property contains an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each of which contains an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsrange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type defining a range of characters in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " string. Use this property to identify the ranges of characters in the subtitle string that you want to highlight. Highlighting the matching text of a search completion is optional, but it’s a best practice for providing helpful information to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsrange": {
      "abstract": [
        {
          "text": "A structure used to describe a portion of a series, such as characters in a string or objects in an array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsrange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRange",
      "type": "topic",
      "url": "/documentation/foundation/nsrange"
    },
    "doc://com.apple.documentation/documentation/foundation/nsvalue": {
      "abstract": [
        {
          "text": "A simple container for a single C or Objective-C data item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSValue"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSValue",
      "type": "topic",
      "url": "/documentation/foundation/nsvalue"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mapkit/documentation/MapKit": {
      "abstract": [
        {
          "text": "Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit",
      "kind": "symbol",
      "role": "collection",
      "title": "MapKit",
      "type": "topic",
      "url": "/documentation/mapkit"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion": {
      "abstract": [
        {
          "text": "A fully formed string that completes a partial string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompletion"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MKLocalSearchCompletion"
        }
      ],
      "role": "symbol",
      "title": "MKLocalSearchCompletion",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitle": {
      "abstract": [
        {
          "text": "The subtitle (if any) associated with the point of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion/subtitle"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitleHighlightRanges": {
      "abstract": [
        {
          "text": "The ranges of characters to highlight in the subtitle string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleHighlightRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitleHighlightRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtitleHighlightRanges"
        }
      ],
      "role": "symbol",
      "title": "subtitleHighlightRanges",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion/subtitlehighlightranges"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/title": {
      "abstract": [
        {
          "text": "The title string associated with the point of interest.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion/title"
    },
    "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/titleHighlightRanges": {
      "abstract": [
        {
          "text": "The ranges of characters to highlight in the title string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleHighlightRanges"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/titleHighlightRanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleHighlightRanges"
        }
      ],
      "role": "symbol",
      "title": "titleHighlightRanges",
      "type": "topic",
      "url": "/documentation/mapkit/mklocalsearchcompletion/titlehighlightranges"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSValue": {
      "abstract": [
        {
          "text": "A simple container for a single C or Objective-C data item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSValue"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSValue",
      "type": "topic",
      "url": "/documentation/foundation/nsvalue"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-search-completions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/title",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitle",
        "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/titleHighlightRanges"
      ],
      "title": "Getting the search completions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "subtitleHighlightRanges"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitleHighlightRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mapkit/documentation/MapKit",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-search-completions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/title",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/subtitle",
                "doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion/titleHighlightRanges"
              ],
              "title": "Getting the search completions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSValue *>"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "subtitleHighlightRanges"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1subtitle/title",
          "value": "subtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1subtitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/title",
          "value": "MKLocalSearchCompletion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MKLocalSearchCompletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1subtitleHighlightRanges/title",
          "value": "subtitleHighlightRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1subtitleHighlightRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtitleHighlightRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1titleHighlightRanges/title",
          "value": "titleHighlightRanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1titleHighlightRanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleHighlightRanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompletion/subtitlehighlightranges"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mapkit/mklocalsearchcompletion/subtitlehighlightranges"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
