{
  "abstract": [
    {
      "text": "Failed to open a connection to the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ICReturnConnectionErrorCode@ICReturnConnectionFailedToOpen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failedToOpen"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ICReturnConnectionFailedToOpen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ICReturnConnectionError.Code.failedToOpen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failedToOpen"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError": {
      "abstract": [
        {
          "text": "A connection error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly": {
      "abstract": [
        {
          "text": "Device closed session without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedSessionSuddenly"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionClosedSessionSuddenly"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.closedSessionSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/closedsessionsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited": {
      "abstract": [
        {
          "text": "Device driver exited without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "driverExited"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionDriverExited"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.driverExited",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/driverexited"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed": {
      "abstract": [
        {
          "text": "Device reports eject has failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectFailed"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionEjectFailed"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.ejectFailed",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/ejectfailed"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly": {
      "abstract": [
        {
          "text": "Device ejected without request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ejectedSuddenly"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionEjectedSuddenly"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.ejectedSuddenly",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/ejectedsuddenly"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen": {
      "abstract": [
        {
          "text": "Failed to open a connection to the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpen"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionFailedToOpen"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.failedToOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopen"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice": {
      "abstract": [
        {
          "text": "Failed to open the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failedToOpenDevice"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionFailedToOpenDevice"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.failedToOpenDevice",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopendevice"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen": {
      "abstract": [
        {
          "text": "Device reports session is already open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionAlreadyOpen"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnConnectionSessionAlreadyOpen"
        }
      ],
      "role": "symbol",
      "title": "ICReturnConnectionError.Code.sessionAlreadyOpen",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnconnectionerror/code/sessionalreadyopen"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen"
      ],
      "title": "Error Cases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ICReturnConnectionFailedToOpen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionFailedToOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/closedSessionSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/driverExited",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectedSuddenly",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/ejectFailed",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/failedToOpenDevice",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnConnectionError/Code/sessionAlreadyOpen"
              ],
              "title": "Error Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ICReturnConnectionFailedToOpen"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectedSuddenly/title",
          "value": "ICReturnConnectionEjectedSuddenly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectedSuddenly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionEjectedSuddenly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpen/title",
          "value": "ICReturnConnectionFailedToOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionFailedToOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1closedSessionSuddenly/title",
          "value": "ICReturnConnectionClosedSessionSuddenly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1closedSessionSuddenly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionClosedSessionSuddenly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectFailed/title",
          "value": "ICReturnConnectionEjectFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1ejectFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionEjectFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpenDevice/title",
          "value": "ICReturnConnectionFailedToOpenDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1failedToOpenDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionFailedToOpenDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1sessionAlreadyOpen/title",
          "value": "ICReturnConnectionSessionAlreadyOpen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1sessionAlreadyOpen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionSessionAlreadyOpen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/title",
          "value": "ICReturnConnectionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1driverExited/title",
          "value": "ICReturnConnectionDriverExited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnConnectionError~1Code~1driverExited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnConnectionDriverExited"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnconnectionerror/code/failedtoopen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
