{
  "abstract": [
    {
      "text": "The range of dates during which someone took the pictures.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/dateCreated"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSearchForPhotosIntent(py)dateCreated",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "dateCreated"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
        "text": "INDateComponentsRange"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "dateCreated"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSearchForPhotosIntent is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INSearchForPhotosIntent is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INSearchForPhotosIntent is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INSearchForPhotosIntent is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INSearchForPhotosIntent is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "dateCreated"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@NSCopying"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "dateCreated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
              "text": "INDateComponentsRange"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this property to limit the scope of the search to photos taken within the specified dates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange": {
      "abstract": [
        {
          "text": "A span of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "role": "symbol",
      "title": "INDateComponentsRange",
      "type": "topic",
      "url": "/documentation/intents/indatecomponentsrange"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions": {
      "abstract": [
        {
          "text": "Constants indicating attributes of a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "role": "symbol",
      "title": "INPhotoAttributeOptions",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent": {
      "abstract": [
        {
          "text": "A request for the list of photos that match the specified criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchForPhotosIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchForPhotosIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchForPhotosIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/albumName": {
      "abstract": [
        {
          "text": "The name of the album that contains the photos.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "albumName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/albumName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "albumName"
        }
      ],
      "role": "symbol",
      "title": "albumName",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent/albumname"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/dateCreated": {
      "abstract": [
        {
          "text": "The range of dates during which someone took the pictures.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/dateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateCreated"
        }
      ],
      "role": "symbol",
      "title": "dateCreated",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent/datecreated"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/excludedAttributes": {
      "abstract": [
        {
          "text": "The attributes that must not be present in the photos.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludedAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/excludedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "excludedAttributes"
        }
      ],
      "role": "symbol",
      "title": "excludedAttributes",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent/excludedattributes"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/includedAttributes": {
      "abstract": [
        {
          "text": "The attributes that must be present in the photos.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includedAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/includedAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includedAttributes"
        }
      ],
      "role": "symbol",
      "title": "includedAttributes",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent/includedattributes"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/locationCreated": {
      "abstract": [
        {
          "text": "The location where someone took the photos.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CLPlacemark",
          "text": "CLPlacemark"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/locationCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationCreated"
        }
      ],
      "role": "symbol",
      "title": "locationCreated",
      "type": "topic",
      "url": "/documentation/intents/insearchforphotosintent/locationcreated"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Search-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/locationCreated",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/albumName",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/includedAttributes",
        "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/excludedAttributes",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
      ],
      "title": "Getting the Search Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "dateCreated"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Search-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/locationCreated",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/albumName",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/includedAttributes",
                "doc://com.apple.sirikit/documentation/Intents/INSearchForPhotosIntent/excludedAttributes",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
              ],
              "title": "Getting the Search Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
                    "text": "INDateComponentsRange"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "dateCreated"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "atomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
                    "text": "INDateComponentsRange"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "dateCreated"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1excludedAttributes/title",
          "value": "excludedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1excludedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "excludedAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/title",
          "value": "INPhotoAttributeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent/title",
          "value": "INSearchForPhotosIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForPhotosIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchForPhotosIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1dateCreated/title",
          "value": "dateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1dateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/title",
          "value": "INDateComponentsRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1albumName/title",
          "value": "albumName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1albumName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "albumName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1locationCreated/title",
          "value": "locationCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1locationCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "locationCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1includedAttributes/title",
          "value": "includedAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchForPhotosIntent~1includedAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includedAttributes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchforphotosintent/datecreated"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchforphotosintent/datecreated"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
