{
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSFileName"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "FSKit",
    "externalID": "s:So10FSFileNameC5FSKitE7cStringABSRys4Int8VG_tcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "cString"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SR",
        "text": "UnsafeBufferPointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5CChara",
        "text": "CChar"
      },
      {
        "kind": "text",
        "text": ">)"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(cString:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "cString"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SR",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SR",
              "text": "UnsafeBufferPointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5CChara",
              "text": "CChar"
            },
            {
              "kind": "text",
              "text": ">)"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSFileName": {
      "abstract": [
        {
          "text": "The name of a file, expressed as a data buffer.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSFileName"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSFileName"
        }
      ],
      "role": "symbol",
      "title": "FSFileName",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bytes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(bytes:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(bytes:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SR",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5CChara",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(cString:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(cString:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(cstring:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(data:)": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence data object.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:"
        }
      ],
      "role": "symbol",
      "title": "init(data:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(data:)"
    },
    "doc://FSKit/documentation/FSKit/FSFileName/init(string:)": {
      "abstract": [
        {
          "text": "Creates a filename by copying a character sequence from a string instance.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSFileName/init(string:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:"
        }
      ],
      "role": "symbol",
      "title": "init(string:)",
      "type": "topic",
      "url": "/documentation/fskit/fsfilename/init(string:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SR": {
      "abstract": [
        {
          "text": "A nonowning collection interface to a buffer of elements stored contiguously in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeBufferPointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SR",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeBufferPointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeBufferPointer"
    },
    "doc://com.externally.resolved.symbol/s:s5CChara": {
      "abstract": [
        {
          "text": "The C ‘char’ type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CChar"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Int8V",
          "text": "Int8"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5CChara",
      "kind": "symbol",
      "role": "symbol",
      "title": "CChar",
      "type": "topic",
      "url": "/documentation/Swift/CChar"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-filename",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSFileName/init(bytes:)",
        "doc://FSKit/documentation/FSKit/FSFileName/init(data:)",
        "doc://FSKit/documentation/FSKit/FSFileName/init(string:)"
      ],
      "title": "Creating a filename"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(data:)/title",
          "value": "initWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(string:)/title",
          "value": "initWithString:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName~1init(string:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithString:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/title",
          "value": "FSFileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSFileName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSFileName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsfilename/init(cstring:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
