{
  "abstract": [
    {
      "text": "The split view interface uses the classic split view style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISplitViewControllerStyle@UISplitViewControllerStyleUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISplitViewControllerStyleUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "UISplitViewController.Style.doubleColumn",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISplitViewController.Style.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A split view controller with this style represents a classic split view controller created using any other approach than ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/init(style:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You cannot create a split view controller with a style of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/unspecified",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using this initializer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Split view controllers with this style don’t support any column-style APIs, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/setViewController(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController": {
      "abstract": [
        {
          "text": "A container view controller that implements a hierarchical interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the number of columns the split view interface displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.Style",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/style-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/doubleColumn": {
      "abstract": [
        {
          "text": "The split view interface displays two columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleColumn"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/doubleColumn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerStyleDoubleColumn"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.Style.doubleColumn",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/style-swift.enum/doublecolumn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/tripleColumn": {
      "abstract": [
        {
          "text": "The split view interface displays three columns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tripleColumn"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/tripleColumn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerStyleTripleColumn"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.Style.tripleColumn",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/style-swift.enum/triplecolumn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/unspecified": {
      "abstract": [
        {
          "text": "The split view interface uses the classic split view style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerStyleUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController.Style.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/style-swift.enum/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/init(style:)": {
      "abstract": [
        {
          "text": "Creates a split view controller with the specified column style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerStyle",
          "text": "Style"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/init(style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(style:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/init(style:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/setViewController(_:for:)": {
      "abstract": [
        {
          "text": "Presents the provided view controller in the specified column of the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerColumn",
          "text": "Column"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/setViewController(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setViewController:forColumn:"
        }
      ],
      "role": "symbol",
      "title": "setViewController(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/setviewcontroller(_:for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/doubleColumn",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/tripleColumn"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISplitViewControllerStyleUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyleUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/doubleColumn",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/Style-swift.enum/tripleColumn"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISplitViewControllerStyleUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum/title",
          "value": "UISplitViewControllerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1init(style:)/title",
          "value": "initWithStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1init(style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1unspecified/title",
          "value": "UISplitViewControllerStyleUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyleUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1tripleColumn/title",
          "value": "UISplitViewControllerStyleTripleColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1tripleColumn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyleTripleColumn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1setViewController(_:for:)/title",
          "value": "setViewController:forColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1setViewController(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setViewController:forColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/title",
          "value": "UISplitViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1doubleColumn/title",
          "value": "UISplitViewControllerStyleDoubleColumn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1Style-swift.enum~1doubleColumn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerStyleDoubleColumn"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontroller/style-swift.enum/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontroller/style-swift.enum/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
