{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@IntentsUIVersionNumber",
    "fragments": [
      {
        "kind": "identifier",
        "text": "IntentsUIVersionNumber"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "IntentsUIVersionNumber"
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "IntentsUIVersionNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:d",
              "text": "double"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "IntentsUIVersionNumber"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext": {
      "abstract": [
        {
          "text": "Constants indicating where your view controller appears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIHostedViewContext"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIHostedViewContext"
        }
      ],
      "role": "symbol",
      "title": "INUIHostedViewContext",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewcontext"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IntentsUIVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "IntentsUIVersionNumber",
      "type": "topic",
      "url": "/documentation/intentsui/intentsuiversionnumber"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IntentsUIVersionString"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "IntentsUIVersionString",
      "type": "topic",
      "url": "/documentation/intentsui/intentsuiversionstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext",
        "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString"
      ],
      "title": "Getting Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/title",
          "value": "INUIHostedViewContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/intentsuiversionnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
