{
  "abstract": [
    {
      "text": "Methods for presenting custom content in the Siri and Maps interfaces.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INUIHostedViewControlling",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INUIHostedViewControlling"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUIHostedViewControlling"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INUIHostedViewControlling"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INUIHostedViewControlling"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol defines methods for presenting a custom interface from Siri or Maps. You adopt this protocol in a view controller, which you then deliver in an Intents UI app extension as part of your iOS app. When displaying information to the user, Siri and Maps incorporate your view controller’s content into the default interface. In iOS 11 and later, SiriKit gives you the option to replace some or all of the default interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An Intents UI app extension works in tandem with a corresponding Intents app extension. The Intents app extension handles the intent and provides a response that includes data from your app. The view controller in your Intents UI app extension receives that data in the form of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and uses it to configure its view. Using the methods of this protocol, you can replace some or all of the default Siri or Maps interface or you can augment the default interface with a custom view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each Intents UI app extension must contain only one view controller, but that view controller may provide a custom interface for multiple intents. Use the ",
              "type": "text"
            },
            {
              "code": "IntentsSupported",
              "type": "codeVoice"
            },
            {
              "text": " key in the extension’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file to specify which intent classes the view controller supports. During the configuration phase, use the class of the intent to configure the contents of your view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on how to create an Intents UI extension, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/SiriKit/creating-an-intents-ui-extension",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Replace-Some-or-All-of-the-Default-Interface",
          "level": 3,
          "text": "Replace Some or All of the Default Interface",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Prior to displaying an interface, SiriKit determines which pieces of data that it wants to display from the intent and your response and packages them into ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. For each parameter (or grouped set of parameters), SiriKit creates an instance of your view controller and calls its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Use that method to configure the custom interface that you want displayed by Siri and Maps. If you don’t provide a custom view, SiriKit displays a default view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Before calling the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method with parameters, SiriKit calls it once with no parameters so that you can configure your interface all at once or provide an extra custom view.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Each view controller object may display parameters other than the ones that SiriKit provided. For example, if SiriKit asks you to display the pickup date for a ride, you could display the pickup date, drop-off date, and the pickup location in your custom view. When executing the handler block of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INParameter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects for all of the parameters that you displayed. SiriKit doesn’t ask you to configure the same parameter twice.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Augment-the-Default-Interface-with-a-Single-View",
          "level": 3,
          "text": "Augment the Default Interface with a Single View",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to keep the default Siri or Maps interface and augment it with a custom view, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. When you implement only that method, SiriKit doesn’t replace any of the default interfaces. Instead, it inserts your view controller’s view into the default interface. You might augment the default interface when you want to take a more minimal approach to your customizations. For example, you might use it solely to add branding information to the default interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When augmenting the default interface, configure the contents of your view however you want. You can add subviews, embed child view controllers, and install layout constraints to display and manage your content. However, don’t add gesture recognizers or views that involve user interactions to your view hierarchy. The system actively prevents the delivery of touch events to your view controller while it’s onscreen. If you need to update your views dynamically, use a timer to trigger programmatic updates.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To avoid the duplication of some types of content, implement the properties of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol in your view controller. The properties define elements of the default interface that SiriKit can hide. For example, a ride booking app that provides its own map might implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding/displaysMap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and return true to cause SiriKit to hide the default map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If your view controller implements the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method, SiriKit doesn’t call the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INIntentSetImageKeyPath"
        }
      ],
      "role": "symbol",
      "title": "INIntentSetImageKeyPath",
      "type": "topic",
      "url": "/documentation/intents/inintentsetimagekeypath"
    },
    "doc://com.apple.sirikit/documentation/Intents/INInteraction": {
      "abstract": [
        {
          "text": "An interaction between the user and your app involving an intent object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INInteraction"
        }
      ],
      "role": "symbol",
      "title": "INInteraction",
      "type": "topic",
      "url": "/documentation/intents/ininteraction"
    },
    "doc://com.apple.sirikit/documentation/Intents/INParameter": {
      "abstract": [
        {
          "text": "A parameter of an interaction object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INParameter"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INParameter"
        }
      ],
      "role": "symbol",
      "title": "INParameter",
      "type": "topic",
      "url": "/documentation/intents/inparameter"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext": {
      "abstract": [
        {
          "text": "Constants indicating where your view controller appears.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIHostedViewContext"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIHostedViewContext"
        }
      ],
      "role": "symbol",
      "title": "INUIHostedViewContext",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewcontext"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling": {
      "abstract": [
        {
          "text": "Methods for presenting custom content in the Siri and Maps interfaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIHostedViewControlling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIHostedViewControlling"
        }
      ],
      "role": "symbol",
      "title": "INUIHostedViewControlling",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewcontrolling"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)": {
      "abstract": [
        {
          "text": "Configures your view controller’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INInteraction",
          "text": "INInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INUIHostedViewContext",
          "text": "INUIHostedViewContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configureWithInteraction:context:completion:"
        }
      ],
      "role": "symbol",
      "title": "configure(with:context:completion:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewcontrolling/configure(with:context:completion:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configureView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INParameter",
          "text": "INParameter"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INInteraction",
          "text": "INInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "interactiveBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INUIInteractiveBehavior",
          "text": "INUIInteractiveBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INUIHostedViewContext",
          "text": "INUIHostedViewContext"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INParameter",
          "text": "INParameter"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configureViewForParameters:ofInteraction:interactiveBehavior:context:completion:"
        }
      ],
      "role": "symbol",
      "title": "configureView(for:of:interactiveBehavior:context:completion:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewcontrolling/configureview(for:of:interactivebehavior:context:completion:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding": {
      "abstract": [
        {
          "text": "Methods for hiding portions of the default interfaces that Siri provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIHostedViewSiriProviding"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIHostedViewSiriProviding"
        }
      ],
      "role": "symbol",
      "title": "INUIHostedViewSiriProviding",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewsiriproviding"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding/displaysMap": {
      "abstract": [
        {
          "text": "A Boolean indicating whether your view controller replaces any default map interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaysMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding/displaysMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaysMap"
        }
      ],
      "role": "symbol",
      "title": "displaysMap",
      "type": "topic",
      "url": "/documentation/intentsui/inuihostedviewsiriproviding/displaysmap"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior": {
      "abstract": [
        {
          "text": "Constants indicating how users are able to interact with your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehavior"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIInteractiveBehavior"
        }
      ],
      "role": "symbol",
      "title": "INUIInteractiveBehavior",
      "type": "topic",
      "url": "/documentation/intentsui/inuiinteractivebehavior"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IntentsUIVersionNumber"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "IntentsUIVersionNumber",
      "type": "topic",
      "url": "/documentation/intentsui/intentsuiversionnumber"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IntentsUIVersionString"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString",
      "kind": "symbol",
      "role": "symbol",
      "title": "IntentsUIVersionString",
      "type": "topic",
      "url": "/documentation/intentsui/intentsuiversionstring"
    },
    "doc://com.apple.sirikit/documentation/SiriKit/creating-an-intents-ui-extension": {
      "abstract": [
        {
          "text": "Create an Intents UI app extension to customize the interfaces displayed by Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/SiriKit/creating-an-intents-ui-extension",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Creating an Intents UI Extension",
      "type": "topic",
      "url": "/documentation/sirikit/creating-an-intents-ui-extension"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-UI-for-Siri-and-Maps",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/SiriKit/creating-an-intents-ui-extension",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding",
        "doc://com.apple.sirikit/documentation/Intents/INParameter",
        "doc://com.apple.sirikit/documentation/Intents/INIntentSetImageKeyPath"
      ],
      "title": "Custom UI for Siri and Maps"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-View-Controller",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)"
      ],
      "title": "Configuring the View Controller"
    },
    {
      "anchor": "Getting-Information",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext"
      ],
      "title": "Getting Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUIHostedViewControlling"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewControlling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewControlling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-View-Controller",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configureView(for:of:interactiveBehavior:context:completion:)",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIInteractiveBehavior",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewControlling/configure(with:context:completion:)"
              ],
              "title": "Configuring the View Controller"
            },
            {
              "anchor": "Getting-Information",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewContext",
                "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionString",
                "doc://com.apple.sirikit/documentation/IntentsUI/IntentsUIVersionNumber"
              ],
              "title": "Getting Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-UI-for-Siri-and-Maps",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIHostedViewSiriProviding",
                "doc://com.apple.sirikit/documentation/Intents/INParameter"
              ],
              "title": "Custom UI for Siri and Maps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INUIHostedViewControlling"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling~1configure(with:context:completion:)/title",
          "value": "configureWithInteraction:context:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling~1configure(with:context:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "configureWithInteraction:context:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling/title",
          "value": "INUIHostedViewControlling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewControlling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewControlling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewSiriProviding~1displaysMap/title",
          "value": "displaysMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewSiriProviding~1displaysMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displaysMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/title",
          "value": "INInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling~1configureView(for:of:interactiveBehavior:context:completion:)/title",
          "value": "configureViewForParameters:ofInteraction:interactiveBehavior:context:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewControlling~1configureView(for:of:interactiveBehavior:context:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "configureViewForParameters:ofInteraction:interactiveBehavior:context:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/title",
          "value": "INUIInteractiveBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIInteractiveBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIInteractiveBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewSiriProviding/title",
          "value": "INUIHostedViewSiriProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewSiriProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewSiriProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewSiriProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewSiriProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/title",
          "value": "INParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INParameter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/title",
          "value": "INUIHostedViewContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIHostedViewContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIHostedViewContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuihostedviewcontrolling"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuihostedviewcontrolling"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
