{
  "abstract": [
    {
      "text": "The protocol an object implements to receive notifications from the view controller that edits or removes a shortcut in Siri.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/IntentsUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INUIEditVoiceShortcutViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "INUIEditVoiceShortcutViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "IntentsUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INUIEditVoiceShortcutViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "INUIEditVoiceShortcutViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI": {
      "abstract": [
        {
          "text": "Customize content in the interface for Siri and Maps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI",
      "kind": "symbol",
      "role": "collection",
      "title": "IntentsUI",
      "type": "topic",
      "url": "/documentation/intentsui"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController/delegate": {
      "abstract": [
        {
          "text": "The object that retrieves notifications from the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)INUIEditVoiceShortcutViewControllerDelegate",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontroller/delegate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to receive notifications from the view controller that edits or removes a shortcut in Siri.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INUIEditVoiceShortcutViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "INUIEditVoiceShortcutViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user deleted the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didDeleteVoiceShortcutWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:diddeletevoiceshortcutwithidentifier:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user updated the shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INVoiceShortcut",
          "text": "INVoiceShortcut"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewController(_:didUpdate:error:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontroller(_:didupdate:error:)"
    },
    "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewControllerDidCancel(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate the user canceled the edit-or-remove-shortcut process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewControllerDidCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INUIEditVoiceShortcutViewController",
          "text": "INUIEditVoiceShortcutViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewControllerDidCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "editVoiceShortcutViewControllerDidCancel:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "editVoiceShortcutViewControllerDidCancel(_:)",
      "type": "topic",
      "url": "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate/editvoiceshortcutviewcontrollerdidcancel(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-View-Controller-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController/delegate"
      ],
      "title": "Handling View Controller Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-Shortcut-Changes",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)",
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
      ],
      "title": "Handling Shortcut Changes"
    },
    {
      "anchor": "Handling-View-Controller-Events",
      "identifiers": [
        "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewControllerDidCancel(_:)"
      ],
      "title": "Handling View Controller Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INUIEditVoiceShortcutViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/IntentsUI"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-Shortcut-Changes",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didUpdate:error:)",
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)"
              ],
              "title": "Handling Shortcut Changes"
            },
            {
              "anchor": "Handling-View-Controller-Events",
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewControllerDelegate/editVoiceShortcutViewControllerDidCancel(_:)"
              ],
              "title": "Handling View Controller Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-View-Controller-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/IntentsUI/INUIEditVoiceShortcutViewController/delegate"
              ],
              "title": "Handling View Controller Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "INUIEditVoiceShortcutViewControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/title",
          "value": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didDeleteVoiceShortcutWithIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didDeleteVoiceShortcutWithIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewControllerDidCancel(_:)/title",
          "value": "editVoiceShortcutViewControllerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewControllerDidCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewControllerDidCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/title",
          "value": "INUIEditVoiceShortcutViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INUIEditVoiceShortcutViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/title",
          "value": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1IntentsUI~1INUIEditVoiceShortcutViewControllerDelegate~1editVoiceShortcutViewController(_:didUpdate:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "editVoiceShortcutViewController:didUpdateVoiceShortcut:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intentsui/inuieditvoiceshortcutviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
