{
  "abstract": [
    {
      "text": "The number of items in the series.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample/count"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)HKSeriesSample(py)count",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "count"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "count"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "count"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "count"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can access the items in the series using the corresponding query. For example, to access route data, use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample": {
      "abstract": [
        {
          "text": "An abstract base class that defines samples that contain a series of items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKSeriesSample"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKSeriesSample"
        }
      ],
      "role": "symbol",
      "title": "HKSeriesSample",
      "type": "topic",
      "url": "/documentation/healthkit/hkseriessample"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample/count": {
      "abstract": [
        {
          "text": "The number of items in the series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "role": "symbol",
      "title": "count",
      "type": "topic",
      "url": "/documentation/healthkit/hkseriessample/count"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery": {
      "abstract": [
        {
          "text": "A query to access the location data stored in a workout route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKWorkoutRouteQuery",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKWorkoutRouteQuery"
        }
      ],
      "role": "symbol",
      "title": "HKWorkoutRouteQuery",
      "type": "topic",
      "url": "/documentation/healthkit/hkworkoutroutequery"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKSeriesSample"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "count"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/title",
          "value": "HKSeriesSample"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKSeriesSample"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/title",
          "value": "HKWorkoutRouteQuery"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKWorkoutRouteQuery/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKWorkoutRouteQuery"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample~1count/title",
          "value": "count"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKSeriesSample~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "count"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkseriessample/count"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkseriessample/count"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
