{
  "abstract": [
    {
      "text": "An object that contains an amount of money that the data detection system matches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.datadetection/documentation/DataDetection"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)DDMatchMoneyAmount",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DDMatchMoneyAmount"
      }
    ],
    "modules": [
      {
        "name": "DataDetection"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DDMatchMoneyAmount"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "DDMatchMoneyAmount"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DDMatchMoneyAmount"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The DataDetection framework returns a match for an amount of money in a ",
              "type": "text"
            },
            {
              "code": "DDMatchMoneyAmount",
              "type": "codeVoice"
            },
            {
              "text": " object, which contains an amount of money and an ISO currency code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.datadetection/documentation/DataDetection": {
      "abstract": [
        {
          "text": "Access and utilize common types of data that the data detection system matches.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection",
      "kind": "symbol",
      "role": "collection",
      "title": "DataDetection",
      "type": "topic",
      "url": "/documentation/datadetection"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatch": {
      "abstract": [
        {
          "text": "A base class for common types of data that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatch"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatch"
        }
      ],
      "role": "symbol",
      "title": "DDMatch",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatch"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent": {
      "abstract": [
        {
          "text": "An object that represents a calendar date or date range that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchCalendarEvent"
        }
      ],
      "role": "symbol",
      "title": "DDMatchCalendarEvent",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchcalendarevent"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchEmailAddress": {
      "abstract": [
        {
          "text": "An object that contains an email address that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchEmailAddress"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchEmailAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchEmailAddress"
        }
      ],
      "role": "symbol",
      "title": "DDMatchEmailAddress",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchemailaddress"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchFlightNumber": {
      "abstract": [
        {
          "text": "An object that contains a flight number that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchFlightNumber"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchFlightNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchFlightNumber"
        }
      ],
      "role": "symbol",
      "title": "DDMatchFlightNumber",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchflightnumber"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchLink": {
      "abstract": [
        {
          "text": "An object that contains a web link that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchLink"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchLink"
        }
      ],
      "role": "symbol",
      "title": "DDMatchLink",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchlink"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount": {
      "abstract": [
        {
          "text": "An object that contains an amount of money that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchMoneyAmount"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchMoneyAmount"
        }
      ],
      "role": "symbol",
      "title": "DDMatchMoneyAmount",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchmoneyamount"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/amount": {
      "abstract": [
        {
          "text": "A number that represents an amount of money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/amount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "amount"
        }
      ],
      "role": "symbol",
      "title": "amount",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchmoneyamount/amount"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/currency": {
      "abstract": [
        {
          "text": "A string that contains an ISO currency code, which the data detection system identifies from the matched string and user preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/currency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currency"
        }
      ],
      "role": "symbol",
      "title": "currency",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchmoneyamount/currency"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPhoneNumber": {
      "abstract": [
        {
          "text": "An object that contains a phone number that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchPhoneNumber"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPhoneNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchPhoneNumber"
        }
      ],
      "role": "symbol",
      "title": "DDMatchPhoneNumber",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchphonenumber"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPostalAddress": {
      "abstract": [
        {
          "text": "An object that contains a postal address that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPostalAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchPostalAddress"
        }
      ],
      "role": "symbol",
      "title": "DDMatchPostalAddress",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchpostaladdress"
    },
    "doc://com.apple.datadetection/documentation/DataDetection/DDMatchShipmentTrackingNumber": {
      "abstract": [
        {
          "text": "An object that contains parcel tracking information that the data detection system matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DDMatchShipmentTrackingNumber"
        }
      ],
      "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatchShipmentTrackingNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DDMatchShipmentTrackingNumber"
        }
      ],
      "role": "symbol",
      "title": "DDMatchShipmentTrackingNumber",
      "type": "topic",
      "url": "/documentation/datadetection/ddmatchshipmenttrackingnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatch"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matched-data-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchEmailAddress",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchFlightNumber",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchLink",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPhoneNumber",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPostalAddress",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchShipmentTrackingNumber"
      ],
      "title": "Matched data types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-money-information",
      "identifiers": [
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/amount",
        "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/currency"
      ],
      "title": "Getting money information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "DDMatchMoneyAmount"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchMoneyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchMoneyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.datadetection/documentation/DataDetection"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-money-information",
              "identifiers": [
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/amount",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchMoneyAmount/currency"
              ],
              "title": "Getting money information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatch"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matched-data-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchCalendarEvent",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchEmailAddress",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchFlightNumber",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchLink",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPhoneNumber",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchPostalAddress",
                "doc://com.apple.datadetection/documentation/DataDetection/DDMatchShipmentTrackingNumber"
              ],
              "title": "Matched data types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "DDMatchMoneyAmount"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.datadetection/documentation/DataDetection/DDMatch",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)DDMatch",
                    "text": "DDMatch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount~1amount/title",
          "value": "amount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount~1amount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "amount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatch/title",
          "value": "DDMatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchLink/title",
          "value": "DDMatchLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount~1currency/title",
          "value": "currency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount~1currency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPostalAddress/title",
          "value": "DDMatchPostalAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPostalAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPostalAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchPostalAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount/title",
          "value": "DDMatchMoneyAmount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchMoneyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchMoneyAmount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchMoneyAmount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchFlightNumber/title",
          "value": "DDMatchFlightNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchFlightNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchFlightNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchFlightNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPhoneNumber/title",
          "value": "DDMatchPhoneNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPhoneNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchPhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchPhoneNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchPhoneNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/title",
          "value": "DDMatchCalendarEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchCalendarEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchCalendarEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchEmailAddress/title",
          "value": "DDMatchEmailAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchEmailAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchEmailAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchEmailAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchShipmentTrackingNumber/title",
          "value": "DDMatchShipmentTrackingNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchShipmentTrackingNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchShipmentTrackingNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.datadetection~1documentation~1DataDetection~1DDMatchShipmentTrackingNumber/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "DDMatchShipmentTrackingNumber"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/datadetection/ddmatchmoneyamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/datadetection/ddmatchmoneyamount"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
