{
  "abstract": [
    {
      "text": "Creates a task that updates the model at the URL with the training data, and calls the progress handlers during and after the update.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:progressHandlers:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MLUpdateTask(cm)updateTaskForModelAtURL:trainingData:progressHandlers:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "forModelAt"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "trainingData"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MLBatchProvider",
        "text": "MLBatchProvider"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "progressHandlers"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
        "text": "MLUpdateProgressHandlers"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(forModelAt:trainingData:progressHandlers:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "forModelAt"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "modelURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "trainingData"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MLBatchProvider",
              "text": "MLBatchProvider"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "progressHandlers"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
              "text": "MLUpdateProgressHandlers"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The location in the file system of a model file (",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "ModelName",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "code": ".mlmodelc",
                  "type": "codeVoice"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "modelURL"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The update data for the model, contained in a batch provider.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "trainingData"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The closures the task calls during the update process.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "progressHandlers"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider": {
      "abstract": [
        {
          "text": "An interface that represents a collection of feature providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLBatchProvider"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLBatchProvider"
        }
      ],
      "role": "symbol",
      "title": "MLBatchProvider",
      "type": "topic",
      "url": "/documentation/coreml/mlbatchprovider"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration": {
      "abstract": [
        {
          "text": "The settings for creating or updating a machine learning model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLModelConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLModelConfiguration"
        }
      ],
      "role": "symbol",
      "title": "MLModelConfiguration",
      "type": "topic",
      "url": "/documentation/coreml/mlmodelconfiguration"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateContext": {
      "abstract": [
        {
          "text": "The context an update task provides to your app’s completion and update progress handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateContext"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateContext"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateContext",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatecontext"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers": {
      "abstract": [
        {
          "text": "A collection of closures an update task uses to notify your app of its progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateProgressHandlers"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateProgressHandlers"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateProgressHandlers",
      "type": "topic",
      "url": "/documentation/coreml/mlupdateprogresshandlers"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask": {
      "abstract": [
        {
          "text": "A task that updates a model with additional training data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLUpdateTask"
        }
      ],
      "role": "symbol",
      "title": "MLUpdateTask",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a task that updates the model at the URL with the training data, and calls the completion handler when the update completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateContext",
          "text": "MLUpdateContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTaskForModelAtURL:trainingData:completionHandler:error:"
        }
      ],
      "role": "symbol",
      "title": "init(forModelAt:trainingData:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:completionhandler:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a task that updates the model at the URL with the training data and configuration, and calls the completion handler when the update completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateContext",
          "text": "MLUpdateContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTaskForModelAtURL:trainingData:configuration:completionHandler:error:"
        }
      ],
      "role": "symbol",
      "title": "init(forModelAt:trainingData:configuration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:configuration:completionhandler:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)": {
      "abstract": [
        {
          "text": "Creates a task that updates the model at the URL with the training data and configuration, and calls the progress handlers during and after the update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "progressHandlers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
          "text": "MLUpdateProgressHandlers"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
        }
      ],
      "role": "symbol",
      "title": "init(forModelAt:trainingData:configuration:progressHandlers:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:configuration:progresshandlers:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:progressHandlers:)": {
      "abstract": [
        {
          "text": "Creates a task that updates the model at the URL with the training data, and calls the progress handlers during and after the update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "progressHandlers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
          "text": "MLUpdateProgressHandlers"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:progressHandlers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
        }
      ],
      "role": "symbol",
      "title": "init(forModelAt:trainingData:progressHandlers:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:progresshandlers:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateContext",
          "text": "MLUpdateContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(forModelAtURL:trainingData:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelaturl:trainingdata:completionhandler:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:completionHandler:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateContext",
          "text": "MLUpdateContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(forModelAtURL:trainingData:configuration:completionHandler:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelaturl:trainingdata:configuration:completionhandler:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:progressHandlers:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLModelConfiguration",
          "text": "MLModelConfiguration"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "progressHandlers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
          "text": "MLUpdateProgressHandlers"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:progressHandlers:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(forModelAtURL:trainingData:configuration:progressHandlers:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelaturl:trainingdata:configuration:progresshandlers:)"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:progressHandlers:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forModelAtURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "trainingData"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MLBatchProvider",
          "text": "MLBatchProvider"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "progressHandlers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
          "text": "MLUpdateProgressHandlers"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:progressHandlers:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(forModelAtURL:trainingData:progressHandlers:)",
      "type": "topic",
      "url": "/documentation/coreml/mlupdatetask/init(formodelaturl:trainingdata:progresshandlers:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSURL": {
      "abstract": [
        {
          "text": "An object representing the location of a resource that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURL",
      "type": "topic",
      "url": "/documentation/foundation/nsurl"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Update-Task",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:completionHandler:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:completionHandler:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:completionHandler:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:progressHandlers:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:completionHandler:)",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAtURL:trainingData:configuration:progressHandlers:)",
        "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider",
        "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateContext",
        "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers"
      ],
      "title": "Creating an Update Task"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-Update-Task",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:completionHandler:)",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:completionHandler:)",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateTask/init(forModelAt:trainingData:configuration:progressHandlers:)",
                "doc://com.apple.coreml/documentation/CoreML/MLBatchProvider",
                "doc://com.apple.coreml/documentation/CoreML/MLModelConfiguration",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateContext",
                "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers"
              ],
              "title": "Creating an Update Task"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "updateTaskForModelAtURL:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSURL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "modelURL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "trainingData:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)MLBatchProvider",
                    "text": "id<MLBatchProvider>"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "trainingData"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "progressHandlers:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coreml/documentation/CoreML/MLUpdateProgressHandlers",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MLUpdateProgressHandlers",
                    "text": "MLUpdateProgressHandlers"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "progressHandlers"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The location in the file system of a model file (",
                        "type": "text"
                      },
                      {
                        "inlineContent": [
                          {
                            "text": "ModelName",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      },
                      {
                        "code": ".mlmodelc",
                        "type": "codeVoice"
                      },
                      {
                        "text": ").",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "modelURL"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The update data for the model, contained in a batch provider.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "trainingData"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The closures the task calls during the update process.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "progressHandlers"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On output, a pointer to an error object that describes why the method failed, or ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if no error occurred. If you are not interested in the error information, pass ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " for this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "error"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/title",
          "value": "MLUpdateProgressHandlers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateProgressHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateProgressHandlers/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateProgressHandlers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:completionHandler:)/title",
          "value": "updateTaskForModelAtURL:trainingData:completionHandler:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:completionHandler:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/title",
          "value": "MLModelConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLModelConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLModelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/title",
          "value": "MLBatchProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLBatchProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLBatchProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/title",
          "value": "MLUpdateTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:progressHandlers:)/title",
          "value": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:progressHandlers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:progressHandlers:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:completionHandler:)/title",
          "value": "updateTaskForModelAtURL:trainingData:configuration:completionHandler:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:configuration:completionHandler:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSURL/abstract",
          "value": [
            {
              "text": "An object that represents the location of a resource, such as an item on a remote server or the path to a local file. ",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateContext/title",
          "value": "MLUpdateContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLUpdateContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:progressHandlers:)/title",
          "value": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLUpdateTask~1init(forModelAt:trainingData:configuration:progressHandlers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "updateTaskForModelAtURL:trainingData:configuration:progressHandlers:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:progresshandlers:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlupdatetask/init(formodelat:trainingdata:progresshandlers:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
