{
  "abstract": [
    {
      "text": "Writes file system metadata from a buffer to a cache, prior to flushing it to the resource.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://FSKit/documentation/FSKit",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/delayedMetadataWriteFrom:startingAt:length:error:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)FSBlockDeviceResource(im)delayedMetadataWriteFrom:startingAt:length:error:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "delayedMetadataWriteFrom:startingAt:length:error:"
      }
    ],
    "modules": [
      {
        "name": "FSKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "delayedMetadataWriteFrom:startingAt:length:error:"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "delayedMetadataWriteFrom:startingAt:length:error:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "delayedMetadataWriteFrom:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "buffer"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "startingAt:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@off_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@off_t",
              "text": "off_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "offset"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "length:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@size_t",
              "text": "size_t"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "length"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "error:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSError",
              "text": "NSError"
            },
            {
              "kind": "text",
              "text": " * *) "
            },
            {
              "kind": "internalParam",
              "text": "error"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A buffer to provide the data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "buffer"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The offset into the resource from which to start writing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "offset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The number of bytes to writing.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "length"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On return, any error encountered while writing data, or ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if no error occurred.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "error"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Boolean value indicating whether the metadata write succeeded.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method provides access to the Kernel Buffer Cache, which is the primary system cache for file system metadata.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Unlike equivalent kernel APIs, this method doesn’t hold any kernel-level claim to the underlying buffers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method is equivalent to ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataWriteFrom:startingAt:length:error:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", except that it writes data to the resource’s buffer cache instead of writing to disk immediately.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To ensure writing data to disk, the client must flush the metadata by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataFlush()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/asynchronousMetadataFlush()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Delayed writes offer two significant advantages:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Delayed writes are more performant, since the file system can avoid waiting for the actual write, reducing I/O latency.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When writing to a specific range repeatedly, delayed writes allow the file system to flush data to the disk only when necessary. This reduces disk usage by eliminating unnecessary writes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For the write to succeed, requests must conform to any transfer requirements of the underlying resource.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Disk drives typically require sector (",
              "type": "text"
            },
            {
              "code": "physicalBlockSize",
              "type": "codeVoice"
            },
            {
              "text": ") addressed operations of one or more sector-aligned offsets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This method doesn’t support partial writing of metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://FSKit/documentation/FSKit": {
      "abstract": [
        {
          "text": "Implement a file system that runs in user space.",
          "type": "text"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit",
      "kind": "symbol",
      "role": "collection",
      "title": "FSKit",
      "type": "topic",
      "url": "/documentation/fskit"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource": {
      "abstract": [
        {
          "text": "A resource that represents a block storage disk partition.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FSBlockDeviceResource"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FSBlockDeviceResource"
        }
      ],
      "role": "symbol",
      "title": "FSBlockDeviceResource",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/asynchronousMetadataFlush()": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asynchronousMetadataFlush"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/asynchronousMetadataFlush()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "asynchronousMetadataFlushWithError:"
        }
      ],
      "role": "symbol",
      "title": "asynchronousMetadataFlush()",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/asynchronousmetadataflush()"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/delayedMetadataWriteFrom:startingAt:length:error:": {
      "abstract": [
        {
          "text": "Writes file system metadata from a buffer to a cache, prior to flushing it to the resource.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "delayedMetadataWriteFrom:startingAt:length:error:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/delayedMetadataWriteFrom:startingAt:length:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delayedMetadataWriteFrom:startingAt:length:error:"
        }
      ],
      "role": "symbol",
      "title": "delayedMetadataWriteFrom:startingAt:length:error:",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/delayedmetadatawritefrom:startingat:length:error:"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataClear(_:withDelayedWrites:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataClear"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSMetadataRange",
          "text": "FSMetadataRange"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withDelayedWrites"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataClear(_:withDelayedWrites:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataClear:withDelayedWrites:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataClear(_:withDelayedWrites:)",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/metadataclear(_:withdelayedwrites:)"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataFlush()": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFlush"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataFlush()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataFlushWithError:"
        }
      ],
      "role": "symbol",
      "title": "metadataFlush()",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/metadataflush()"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataPurge(_:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataPurge"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FSMetadataRange",
          "text": "FSMetadataRange"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataPurge(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataPurge:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataPurge(_:)",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/metadatapurge(_:)"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataReadInto:startingAt:length:error:": {
      "abstract": [
        {
          "text": "Synchronously reads file system metadata from the resource into a buffer.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "metadataReadInto:startingAt:length:error:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataReadInto:startingAt:length:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataReadInto:startingAt:length:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataReadInto:startingAt:length:error:",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/metadatareadinto:startingat:length:error:"
    },
    "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataWriteFrom:startingAt:length:error:": {
      "abstract": [
        {
          "text": "Synchronously writes file system metadata from a buffer to the resource.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "metadataWriteFrom:startingAt:length:error:"
        }
      ],
      "identifier": "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataWriteFrom:startingAt:length:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataWriteFrom:startingAt:length:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataWriteFrom:startingAt:length:error:",
      "type": "topic",
      "url": "/documentation/fskit/fsblockdeviceresource/metadatawritefrom:startingat:length:error:"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:@T@off_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@off_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "off_t",
      "type": "topic",
      "url": "/documentation/kernel/off_t"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-and-writing-data-with-kernel-buffer-cache",
      "generated": true,
      "identifiers": [
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataReadInto:startingAt:length:error:",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataWriteFrom:startingAt:length:error:",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataFlush()",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/asynchronousMetadataFlush()",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataClear(_:withDelayedWrites:)",
        "doc://FSKit/documentation/FSKit/FSBlockDeviceResource/metadataPurge(_:)"
      ],
      "title": "Reading and writing data with kernel buffer cache"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource/title",
          "value": "FSBlockDeviceResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockDeviceResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FSBlockDeviceResource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataFlush()/title",
          "value": "metadataFlushWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataFlush()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "metadataFlushWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataClear(_:withDelayedWrites:)/title",
          "value": "metadataClear:withDelayedWrites:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataClear(_:withDelayedWrites:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "metadataClear:withDelayedWrites:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataPurge(_:)/title",
          "value": "metadataPurge:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1metadataPurge(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "metadataPurge:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1asynchronousMetadataFlush()/title",
          "value": "asynchronousMetadataFlushWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1FSKit~1documentation~1FSKit~1FSBlockDeviceResource~1asynchronousMetadataFlush()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "asynchronousMetadataFlushWithError:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/fskit/fsblockdeviceresource/delayedmetadatawritefrom:startingat:length:error:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
