{
  "abstract": [
    {
      "text": "Creates a new eraser item with the specified width.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.pencilkit/documentation/PencilKit",
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:width:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PencilKit",
    "externalID": "s:So22PKToolPickerEraserItemC9PencilKitE4type5widthAbC12PKEraserToolV0C4TypeO_14CoreFoundation7CGFloatVtcfc",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9PencilKit12PKEraserToolV",
        "text": "PKEraserTool"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9PencilKit12PKEraserToolV10EraserTypeO",
        "text": "EraserType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "width"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "PencilKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(type:width:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9PencilKit12PKEraserToolV",
              "text": "PKEraserTool"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct/EraserType-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9PencilKit12PKEraserToolV10EraserTypeO",
              "text": "EraserType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "width"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit": {
      "abstract": [
        {
          "text": "Capture touch and Apple Pencil input as a drawing, and display that content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PencilKit",
      "type": "topic",
      "url": "/documentation/pencilkit"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct": {
      "abstract": [
        {
          "text": "A tool for erasing previously drawn content in a canvas view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKEraserTool"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKEraserTool"
        }
      ],
      "role": "symbol",
      "title": "PKEraserTool",
      "type": "topic",
      "url": "/documentation/pencilkit/pkerasertool-swift.struct"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct/EraserType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the behavior of the eraser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EraserType"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKEraserTool-swift.struct/EraserType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EraserType"
        }
      ],
      "role": "symbol",
      "title": "PKEraserTool.EraserType",
      "type": "topic",
      "url": "/documentation/pencilkit/pkerasertool-swift.struct/erasertype-swift.enum"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem": {
      "abstract": [
        {
          "text": "An item that represents an eraser tool in the tool picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKToolPickerEraserItem"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKToolPickerEraserItem"
        }
      ],
      "role": "symbol",
      "title": "PKToolPickerEraserItem",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickereraseritem"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:)": {
      "abstract": [
        {
          "text": "Creates a new eraser item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit12PKEraserToolV",
          "text": "PKEraserTool"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit12PKEraserToolV10EraserTypeO",
          "text": "EraserType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(type:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickereraseritem/init(type:)"
    },
    "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:width:)": {
      "abstract": [
        {
          "text": "Creates a new eraser item with the specified width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit12PKEraserToolV",
          "text": "PKEraserTool"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9PencilKit12PKEraserToolV10EraserTypeO",
          "text": "EraserType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:width:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(type:width:)",
      "type": "topic",
      "url": "/documentation/pencilkit/pktoolpickereraseritem/init(type:width:)"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-eraser-item",
      "generated": true,
      "identifiers": [
        "doc://com.apple.pencilkit/documentation/PencilKit/PKToolPickerEraserItem/init(type:)"
      ],
      "title": "Creating an eraser item"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/title",
          "value": "PKToolPickerEraserItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerEraserItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.pencilkit~1documentation~1PencilKit~1PKToolPickerEraserItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKToolPickerEraserItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/pencilkit/pktoolpickereraseritem/init(type:width:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
