{
  "abstract": [
    {
      "text": "SHA-1 160-bit.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use SHA-2 for integrity protection instead",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEVPNIKEv2IntegrityAlgorithm@NEVPNIKEv2IntegrityAlgorithmSHA160",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SHA160"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "message": "Use SHA-2 for integrity protection instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "8.0",
        "message": "Use SHA-2 for integrity protection instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.0",
        "introducedAt": "13.1",
        "message": "Use SHA-2 for integrity protection instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.11",
        "message": "Use SHA-2 for integrity protection instead",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use SHA-2 for integrity protection instead",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEVPNIKEv2IntegrityAlgorithm.SHA160"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SHA160"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithm"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160": {
      "abstract": [
        {
          "text": "SHA-1 160-bit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA160"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA160",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha160"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256": {
      "abstract": [
        {
          "text": "SHA-2 256-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA256"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA256"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA256",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha256"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384": {
      "abstract": [
        {
          "text": "SHA-2 384-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA384"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA384"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA384",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha384"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512": {
      "abstract": [
        {
          "text": "SHA-2 512-bit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA512"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA512"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA512",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha512"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96": {
      "abstract": [
        {
          "text": "SHA-1 96-bit.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SHA96"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEVPNIKEv2IntegrityAlgorithmSHA96"
        }
      ],
      "role": "symbol",
      "title": "NEVPNIKEv2IntegrityAlgorithm.SHA96",
      "type": "topic",
      "url": "/documentation/networkextension/nevpnikev2integrityalgorithm/sha96"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Integrity-algorithms",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512"
      ],
      "title": "Integrity algorithms"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "17.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA160"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Integrity-algorithms",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA96",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA256",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA384",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEVPNIKEv2IntegrityAlgorithm/SHA512"
              ],
              "title": "Integrity algorithms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use SHA-2 for integrity protection instead",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA160/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA96/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA96"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA96/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA96"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA384/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA384"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA384/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA384"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA512/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA512"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA512/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA512"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA256/title",
          "value": "NEVPNIKEv2IntegrityAlgorithmSHA256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm~1SHA256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithmSHA256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/title",
          "value": "NEVPNIKEv2IntegrityAlgorithm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEVPNIKEv2IntegrityAlgorithm/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEVPNIKEv2IntegrityAlgorithm"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2integrityalgorithm/sha160"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nevpnikev2integrityalgorithm/sha160"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
