{
  "abstract": [
    {
      "text": "An error indicating that the current device doesn’t support the use of session objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotSupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WCErrorCode@WCErrorCodeSessionNotSupported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sessionNotSupported"
      }
    ],
    "modules": [
      {
        "name": "Watch Connectivity"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WCErrorCodeSessionNotSupported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WCError.Code.sessionNotSupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sessionNotSupported"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity": {
      "abstract": [
        {
          "text": "Implement two-way communication between an iOS app and its paired watchOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
      "kind": "symbol",
      "role": "collection",
      "title": "Watch Connectivity",
      "type": "topic",
      "url": "/documentation/watchconnectivity"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError": {
      "abstract": [
        {
          "text": "A structure that contains Watch Connectivity error information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WCError"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCError"
        }
      ],
      "role": "symbol",
      "title": "WCError",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code": {
      "abstract": [
        {
          "text": "Constants for errors during a session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deliveryFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t deliver the payload.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deliveryFailed"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deliveryFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeDeliveryFailed"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.deliveryFailed",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/deliveryfailed"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deviceNotPaired": {
      "abstract": [
        {
          "text": "An error indicating that the current device doesn’t have a paired counterpart.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceNotPaired"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deviceNotPaired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeDeviceNotPaired"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.deviceNotPaired",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/devicenotpaired"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/fileAccessDenied": {
      "abstract": [
        {
          "text": "An error indicating that the system can’t transfer a file because it is inaccessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileAccessDenied"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/fileAccessDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeFileAccessDenied"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.fileAccessDenied",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/fileaccessdenied"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/genericError": {
      "abstract": [
        {
          "text": "An error that occurs when there is an unknown problem.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericError"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/genericError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeGenericError"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.genericError",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/genericerror"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/insufficientSpace": {
      "abstract": [
        {
          "text": "An error indicating that there isn’t enough space on the receiving side to store the data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientSpace"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/insufficientSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeInsufficientSpace"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.insufficientSpace",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/insufficientspace"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/invalidParameter": {
      "abstract": [
        {
          "text": "An error indicating that a parameter is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidParameter"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/invalidParameter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeInvalidParameter"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.invalidParameter",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/invalidparameter"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyFailed": {
      "abstract": [
        {
          "text": "An error that occurs when the system can’t return the reply.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReplyFailed"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeMessageReplyFailed"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.messageReplyFailed",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/messagereplyfailed"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyTimedOut": {
      "abstract": [
        {
          "text": "An error that occurs when the counterpart app doesn’t return a reply in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageReplyTimedOut"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyTimedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeMessageReplyTimedOut"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.messageReplyTimedOut",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/messagereplytimedout"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/notReachable": {
      "abstract": [
        {
          "text": "An error indicating that the counterpart app isn’t reachable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notReachable"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/notReachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeNotReachable"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.notReachable",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/notreachable"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadTooLarge": {
      "abstract": [
        {
          "text": "An error indicating an attempt to send an item that exceeds the maximum size limit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payloadTooLarge"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodePayloadTooLarge"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.payloadTooLarge",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/payloadtoolarge"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadUnsupportedTypes": {
      "abstract": [
        {
          "text": "An error indicating that a dictionary contains nonproperty list types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "payloadUnsupportedTypes"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadUnsupportedTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodePayloadUnsupportedTypes"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.payloadUnsupportedTypes",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/payloadunsupportedtypes"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionInactive": {
      "abstract": [
        {
          "text": "An error indicating that the session is inactive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionInactive"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionInactive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeSessionInactive"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.sessionInactive",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/sessioninactive"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionMissingDelegate": {
      "abstract": [
        {
          "text": "An error indicating that the WatchKit extension doesn’t have a valid extension delegate to process events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionMissingDelegate"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionMissingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeSessionMissingDelegate"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.sessionMissingDelegate",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/sessionmissingdelegate"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotActivated": {
      "abstract": [
        {
          "text": "An error indicating that the other device doesn’t have an active session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotActivated"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeSessionNotActivated"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.sessionNotActivated",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/sessionnotactivated"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotSupported": {
      "abstract": [
        {
          "text": "An error indicating that the current device doesn’t support the use of session objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessionNotSupported"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeSessionNotSupported"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.sessionNotSupported",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/sessionnotsupported"
    },
    "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/watchAppNotInstalled": {
      "abstract": [
        {
          "text": "An error indicating that the Watch app isn’t an installed app on the user’s Apple Watch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "watchAppNotInstalled"
        }
      ],
      "identifier": "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/watchAppNotInstalled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WCErrorCodeWatchAppNotInstalled"
        }
      ],
      "role": "symbol",
      "title": "WCError.Code.watchAppNotInstalled",
      "type": "topic",
      "url": "/documentation/watchconnectivity/wcerror/code/watchappnotinstalled"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/genericError",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionMissingDelegate",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotActivated",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deviceNotPaired",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/watchAppNotInstalled",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/notReachable",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/invalidParameter",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadTooLarge",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadUnsupportedTypes",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyFailed",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyTimedOut",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/fileAccessDenied",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deliveryFailed",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/insufficientSpace",
        "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionInactive"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WCErrorCodeSessionNotSupported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeSessionNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/genericError",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionMissingDelegate",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionNotActivated",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deviceNotPaired",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/watchAppNotInstalled",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/notReachable",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/invalidParameter",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadTooLarge",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/payloadUnsupportedTypes",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyFailed",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/messageReplyTimedOut",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/fileAccessDenied",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/deliveryFailed",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/insufficientSpace",
                "doc://com.apple.watchconnectivity/documentation/WatchConnectivity/WCError/Code/sessionInactive"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WCErrorCodeSessionNotSupported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionInactive/title",
          "value": "WCErrorCodeSessionInactive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionInactive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeSessionInactive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1deviceNotPaired/title",
          "value": "WCErrorCodeDeviceNotPaired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1deviceNotPaired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeDeviceNotPaired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1payloadTooLarge/title",
          "value": "WCErrorCodePayloadTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1payloadTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodePayloadTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1genericError/title",
          "value": "WCErrorCodeGenericError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1genericError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeGenericError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1watchAppNotInstalled/title",
          "value": "WCErrorCodeWatchAppNotInstalled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1watchAppNotInstalled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeWatchAppNotInstalled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1fileAccessDenied/title",
          "value": "WCErrorCodeFileAccessDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1fileAccessDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeFileAccessDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1notReachable/title",
          "value": "WCErrorCodeNotReachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1notReachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeNotReachable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionNotActivated/title",
          "value": "WCErrorCodeSessionNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionNotActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeSessionNotActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1invalidParameter/title",
          "value": "WCErrorCodeInvalidParameter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1invalidParameter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeInvalidParameter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1messageReplyTimedOut/title",
          "value": "WCErrorCodeMessageReplyTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1messageReplyTimedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeMessageReplyTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/title",
          "value": "WCErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1deliveryFailed/title",
          "value": "WCErrorCodeDeliveryFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1deliveryFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeDeliveryFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1payloadUnsupportedTypes/title",
          "value": "WCErrorCodePayloadUnsupportedTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1payloadUnsupportedTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodePayloadUnsupportedTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1messageReplyFailed/title",
          "value": "WCErrorCodeMessageReplyFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1messageReplyFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeMessageReplyFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionMissingDelegate/title",
          "value": "WCErrorCodeSessionMissingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionMissingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeSessionMissingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionNotSupported/title",
          "value": "WCErrorCodeSessionNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1sessionNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeSessionNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1insufficientSpace/title",
          "value": "WCErrorCodeInsufficientSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchconnectivity~1documentation~1WatchConnectivity~1WCError~1Code~1insufficientSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WCErrorCodeInsufficientSpace"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchconnectivity/wcerror/code/sessionnotsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchconnectivity/wcerror/code/sessionnotsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
