{
  "abstract": [
    {
      "text": "When the tracking mode for the control is set to use a momentary accelerator, returns a value for the selected segment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSSegmentedControl(py)doubleValueForSelectedSegment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "doubleValueForSelectedSegment"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "doubleValueForSelectedSegment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10.3",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "doubleValueForSelectedSegment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "doubleValueForSelectedSegment"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of the selected segment interpreted as a double-precision floating-point number.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is intended for use with controls whose tracking mode is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". An assertion will occur if this method is called for other types of segmented controls.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl": {
      "abstract": [
        {
          "text": "Display one or more buttons in a single horizontal group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentedControl"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator": {
      "abstract": [
        {
          "text": "On pressure-sensitive systems, when the user force clicks a segment, a momentary accelerator segmented control sends repeating actions as pressure changes occur. The control stops sending actions when the user releases pressure. A document-based app, for example, might implement a momentary accelerator segmented control in order to allow a user to adjust the speed of paging by using variable pressure. In this example, actions are sent to the app to indicate when pressure on the control has changed. The app then determines the amount of pressure currently applied, and adjusts navigation speed accordingly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentaryAccelerator"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSegmentSwitchTrackingMomentaryAccelerator"
        }
      ],
      "role": "symbol",
      "title": "NSSegmentedControl.SwitchTracking.momentaryAccelerator",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/switchtracking/momentaryaccelerator"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment": {
      "abstract": [
        {
          "text": "When the tracking mode for the control is set to use a momentary accelerator, returns a value for the selected segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "doubleValueForSelectedSegment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "doubleValueForSelectedSegment"
        }
      ],
      "role": "symbol",
      "title": "doubleValueForSelectedSegment",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/doublevalueforselectedsegment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexOfSelectedItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfSelectedItem"
        }
      ],
      "role": "symbol",
      "title": "indexOfSelectedItem",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/indexofselecteditem"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the specified segment is selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelected"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forSegment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isSelectedForSegment:"
        }
      ],
      "role": "symbol",
      "title": "isSelected(forSegment:)",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/isselected(forsegment:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)": {
      "abstract": [
        {
          "text": "Selects the segment with the specified tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectSegment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectSegmentWithTag:"
        }
      ],
      "role": "symbol",
      "title": "selectSegment(withTag:)",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/selectsegment(withtag:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment": {
      "abstract": [
        {
          "text": "The index of the selected segment of the control, or ",
          "type": "text"
        },
        {
          "code": "-1",
          "type": "codeVoice"
        },
        {
          "text": " if no segment is selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedSegment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedSegment"
        }
      ],
      "role": "symbol",
      "title": "selectedSegment",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/selectedsegment"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor": {
      "abstract": [
        {
          "text": "The color of the selected segment’s bezel, in appearances that support it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedSegmentBezelColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColor",
          "text": "NSColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedSegmentBezelColor"
        }
      ],
      "role": "symbol",
      "title": "selectedSegmentBezelColor",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/selectedsegmentbezelcolor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)": {
      "abstract": [
        {
          "text": "Sets the selection state of the specified segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSelected"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forSegment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSelected:forSegment:"
        }
      ],
      "role": "symbol",
      "title": "setSelected(_:forSegment:)",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/setselected(_:forsegment:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode": {
      "abstract": [
        {
          "text": "The type of tracking behavior the control exhibits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSSegmentedControl",
          "text": "NSSegmentedControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSSegmentSwitchTracking",
          "text": "SwitchTracking"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackingMode"
        }
      ],
      "role": "symbol",
      "title": "trackingMode",
      "type": "topic",
      "url": "/documentation/appkit/nssegmentedcontrol/trackingmode"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-the-Selected-Segment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)",
        "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor"
      ],
      "title": "Managing the Selected Segment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10.3",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "doubleValueForSelectedSegment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleValueForSelectedSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/SwitchTracking/momentaryAccelerator",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/trackingMode"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Managing-the-Selected-Segment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)",
                "doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor"
              ],
              "title": "Managing the Selected Segment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "doubleValueForSelectedSegment"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1doubleValueForSelectedSegment/title",
          "value": "doubleValueForSelectedSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1doubleValueForSelectedSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "doubleValueForSelectedSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegment/title",
          "value": "selectedSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setSelected(_:forSegment:)/title",
          "value": "setSelected:forSegment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setSelected(_:forSegment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setSelected:forSegment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentaryAccelerator/title",
          "value": "NSSegmentSwitchTrackingMomentaryAccelerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1SwitchTracking~1momentaryAccelerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentSwitchTrackingMomentaryAccelerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1indexOfSelectedItem/title",
          "value": "indexOfSelectedItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1indexOfSelectedItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexOfSelectedItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectSegment(withTag:)/title",
          "value": "selectSegmentWithTag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectSegment(withTag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectSegmentWithTag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSelected(forSegment:)/title",
          "value": "isSelectedForSegment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSelected(forSegment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isSelectedForSegment:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title",
          "value": "NSSegmentedControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/title",
          "value": "trackingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1trackingMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegmentBezelColor/title",
          "value": "selectedSegmentBezelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegmentBezelColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedSegmentBezelColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nssegmentedcontrol/doublevalueforselectedsegment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nssegmentedcontrol/doublevalueforselectedsegment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
