{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:objc(cs)NSSegmentedControl(im)imageScalingForSegment:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageScaling","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@NSImageScaling","text":"NSImageScaling","kind":"typeIdentifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"imageScaling(forSegment:)","navigatorTitle":[{"text":"imageScalingForSegment:","kind":"identifier"}],"modules":[{"name":"AppKit"}],"platforms":[{"name":"macOS","unavailable":false,"introducedAt":"10.5","deprecated":false,"beta":false}],"role":"symbol"},"seeAlsoSections":[{"title":"Configuring a Segment Image","anchor":"Configuring-a-Segment-Image","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImage(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/image(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImageScaling(_:forSegment:)"],"generated":true}],"kind":"symbol","sections":[],"abstract":[{"text":"Returns the scaling mode used to display the specified segment’s image.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/imageScaling(forSegment:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageScaling","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"segment","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling","preciseIdentifier":"c:@E@NSImageScaling","text":"NSImageScaling","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The index of the segment whose enabled state you want to get. This method raises an exception (","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1413262-rangeexception"},{"text":") if the index is out of bounds.","type":"text"}]}],"name":"segment"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"One of the image scaling constants. For a list of possible values, see "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling","type":"reference"},{"type":"text","text":". The default value is "},{"isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown","type":"reference"},{"type":"text","text":"."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nssegmentedcontrol/imagescaling(forsegment:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nssegmentedcontrol/imagescaling(forsegment:)"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown":{"kind":"symbol","url":"/documentation/appkit/nsimagescaling/scaleproportionallydown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSImageScaleProportionallyDown"}],"abstract":[{"text":"If it is too large for the destination, scale the image down while preserving the aspect ratio.","type":"text"}],"title":"NSImageScaling.scaleProportionallyDown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleProportionallyDown"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown","type":"topic"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl":{"url":"/documentation/appkit/nssegmentedcontrol","kind":"symbol","navigatorTitle":[{"text":"NSSegmentedControl","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSSegmentedControl","abstract":[{"text":"Display one or more buttons in a single horizontal group.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSegmentedControl","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSImageScaling":{"navigatorTitle":[{"kind":"identifier","text":"NSImageScaling"}],"title":"NSImageScaling","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSImageScaling"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling","abstract":[{"type":"text","text":"Constants that specify a cell’s image scaling behavior."}],"role":"symbol","url":"/documentation/appkit/nsimagescaling","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/imageScaling(forSegment:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/imageScaling(forSegment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageScaling"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageScaling","text":"NSImageScaling"}],"type":"topic","abstract":[{"type":"text","text":"Returns the scaling mode used to display the specified segment’s image."}],"url":"/documentation/appkit/nssegmentedcontrol/imagescaling(forsegment:)","title":"imageScaling(forSegment:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageScalingForSegment:"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImage(_:forSegment:)":{"url":"/documentation/appkit/nssegmentedcontrol/setimage(_:forsegment:)","kind":"symbol","title":"setImage(_:forSegment:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImage(_:forSegment:)","type":"topic","navigatorTitle":[{"text":"setImage:forSegment:","kind":"identifier"}],"abstract":[{"text":"Sets the image for the specified segment.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setImage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage","text":"NSImage"},{"kind":"text","text":"?, "},{"text":"forSegment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/image(forSegment:)":{"kind":"symbol","navigatorTitle":[{"text":"imageForSegment:","kind":"identifier"}],"role":"symbol","title":"image(forSegment:)","abstract":[{"text":"Returns the image associated with the specified segment.","type":"text"}],"url":"/documentation/appkit/nssegmentedcontrol/image(forsegment:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"NSImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSImage"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/image(forSegment:)"},"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1413262-rangeexception":{"identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1413262-rangeexception","fragments":[{"text":"static let ","kind":"text"},{"text":"rangeException","kind":"identifier"},{"text":": NSExceptionName","kind":"text"}],"type":"topic","abstract":[{"text":"Name of an exception that occurs when attempting to access outside the bounds of some data, such as beyond the end of a string.","type":"text"}],"url":"/documentation/foundation/nsexceptionname/1413262-rangeexception","title":"rangeException","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImageScaling(_:forSegment:)":{"url":"/documentation/appkit/nssegmentedcontrol/setimagescaling(_:forsegment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setImageScaling"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSImageScaling","text":"NSImageScaling"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setImageScaling(_:forSegment:)","kind":"symbol","abstract":[{"text":"Sets the scaling mode used to display the specified segment’s image.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImageScaling(_:forSegment:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setImageScaling:forSegment:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.5","deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"imageScalingForSegment:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageScalingForSegment:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"op":"replace"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImage(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/image(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setImageScaling(_:forSegment:)"],"anchor":"Configuring-a-Segment-Image","title":"Configuring a Segment Image"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling","preciseIdentifier":"c:@E@NSImageScaling","text":"NSImageScaling","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imageScalingForSegment:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"segment","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"segment","content":[{"inlineContent":[{"type":"text","text":"The index of the segment whose enabled state you want to get. This method raises an exception ("},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsexceptionname/1413262-rangeexception"},{"type":"text","text":") if the index is out of bounds."}],"type":"paragraph"}]}]}},{"value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"One of the image scaling constants. For a list of possible values, see "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling"},{"type":"text","text":". The default value is "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSImageScaling/scaleProportionallyDown"},{"type":"text","text":"."}]}],"kind":"content"},"op":"replace","path":"/primaryContentSections/2"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyDown/title","value":"NSImageScaleProportionallyDown"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling~1scaleProportionallyDown/fragments","value":[{"text":"NSImageScaleProportionallyDown","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title","value":"NSSegmentedControl"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments","value":[{"text":"NSSegmentedControl","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle","value":[{"kind":"identifier","text":"NSSegmentedControl"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/title","value":"NSImageScaling"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/fragments","value":[{"text":"NSImageScaling","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/navigatorTitle","value":[{"kind":"identifier","text":"NSImageScaling"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1imageScaling(forSegment:)/title","value":"imageScalingForSegment:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1imageScaling(forSegment:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageScalingForSegment:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setImage(_:forSegment:)/title","value":"setImage:forSegment:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setImage(_:forSegment:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setImage:forSegment:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1image(forSegment:)/title","value":"imageForSegment:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1image(forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageForSegment:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsexceptionname~11413262-rangeexception/title","value":"NSRangeException"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setImageScaling(_:forSegment:)/title","value":"setImageScaling:forSegment:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setImageScaling(_:forSegment:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setImageScaling:forSegment:","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}