{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment"],"generated":true,"anchor":"Managing-the-Selected-Segment","title":"Managing the Selected Segment"}],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)NSSegmentedControl(py)indexOfSelectedItem","platforms":[{"unavailable":false,"deprecated":false,"name":"macOS","introducedAt":"10.4","beta":false}],"title":"indexOfSelectedItem","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"indexOfSelectedItem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"indexOfSelectedItem","kind":"identifier"}]},"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfSelectedItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nssegmentedcontrol/indexofselecteditem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nssegmentedcontrol/indexofselecteditem"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexOfSelectedItem"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"abstract":[],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/indexOfSelectedItem","navigatorTitle":[{"kind":"identifier","text":"indexOfSelectedItem"}],"title":"indexOfSelectedItem","url":"/documentation/appkit/nssegmentedcontrol/indexofselecteditem","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment":{"role":"symbol","url":"/documentation/appkit/nssegmentedcontrol/selectedsegment","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment","title":"selectedSegment","abstract":[{"text":"The index of the selected segment of the control, or ","type":"text"},{"code":"-1","type":"codeVoice"},{"text":" if no segment is selected.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"selectedSegment","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedSegment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl":{"url":"/documentation/appkit/nssegmentedcontrol","kind":"symbol","navigatorTitle":[{"text":"NSSegmentedControl","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSSegmentedControl","abstract":[{"text":"Display one or more buttons in a single horizontal group.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSegmentedControl","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment":{"url":"/documentation/appkit/nssegmentedcontrol/doublevalueforselectedsegment","role":"symbol","kind":"symbol","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment","navigatorTitle":[{"kind":"identifier","text":"doubleValueForSelectedSegment"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"doubleValueForSelectedSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"doubleValueForSelectedSegment","abstract":[{"text":"When the tracking mode for the control is set to use a momentary accelerator, returns a value for the selected segment.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor","kind":"symbol","navigatorTitle":[{"text":"selectedSegmentBezelColor","kind":"identifier"}],"role":"symbol","type":"topic","title":"selectedSegmentBezelColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedSegmentBezelColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSColor","preciseIdentifier":"c:objc(cs)NSColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The color of the selected segment’s bezel, in appearances that support it.","type":"text"}],"url":"/documentation/appkit/nssegmentedcontrol/selectedsegmentbezelcolor"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setSelected:forSegment:"}],"role":"symbol","type":"topic","title":"setSelected(_:forSegment:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the selection state of the specified segment."}],"url":"/documentation/appkit/nssegmentedcontrol/setselected(_:forsegment:)"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)":{"url":"/documentation/appkit/nssegmentedcontrol/selectsegment(withtag:)","kind":"symbol","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)","abstract":[{"text":"Selects the segment with the specified tag.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"selectSegmentWithTag:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectSegment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"selectSegment(withTag:)"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)":{"url":"/documentation/appkit/nssegmentedcontrol/isselected(forsegment:)","type":"topic","title":"isSelected(forSegment:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isSelectedForSegment:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSegment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Returns a Boolean value indicating whether the specified segment is selected.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"unavailable":false,"introducedAt":"10.4","deprecated":false,"name":"macOS"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"indexOfSelectedItem"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"indexOfSelectedItem"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegment","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectSegment(withTag:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setSelected(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSelected(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/selectedSegmentBezelColor","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/doubleValueForSelectedSegment"],"title":"Managing the Selected Segment","generated":true,"anchor":"Managing-the-Selected-Segment"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"indexOfSelectedItem","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"indexOfSelectedItem","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1indexOfSelectedItem/title"},{"value":[{"text":"indexOfSelectedItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1indexOfSelectedItem/fragments"},{"value":"selectedSegment","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegment/title"},{"value":[{"text":"selectedSegment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegment/fragments"},{"value":"NSSegmentedControl","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title"},{"value":[{"text":"NSSegmentedControl","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments"},{"value":[{"kind":"identifier","text":"NSSegmentedControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle"},{"value":"doubleValueForSelectedSegment","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1doubleValueForSelectedSegment/title"},{"value":[{"text":"doubleValueForSelectedSegment","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1doubleValueForSelectedSegment/fragments"},{"value":"selectedSegmentBezelColor","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegmentBezelColor/title"},{"value":[{"kind":"identifier","text":"selectedSegmentBezelColor"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectedSegmentBezelColor/fragments"},{"value":"setSelected:forSegment:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setSelected(_:forSegment:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setSelected:forSegment:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setSelected(_:forSegment:)/fragments"},{"value":"selectSegmentWithTag:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectSegment(withTag:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectSegmentWithTag:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1selectSegment(withTag:)/fragments"},{"value":"isSelectedForSegment:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSelected(forSegment:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isSelectedForSegment:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSelected(forSegment:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}