{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A Boolean value that indicates whether spring loading is enabled for the control.","type":"text"}],"sections":[],"seeAlsoSections":[{"title":"Configuring a Segment Menu","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)"],"anchor":"Configuring-a-Segment-Menu"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSpringLoaded"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The value of this property is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if spring loading is enabled for the control, and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":" if it is not. The default is ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"On pressure-sensitive systems, such as systems with the Force Touch trackpad, spring loading is a feature that allows a user to activate a segment in a segmented control by dragging selected items over it and force clicking—pressing harder—without dropping the selected items. The user can then continue dragging the items, possibly to perform additional actions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A practical example of this feature can be found in the Calendar app. A selected calendar event can be dragged over the day, week, month, or year segments in the toolbar. Force clicking on a segment switches the calendar view without releasing the selected calendar event. The calendar event can then be dropped at the desired location in the new calendar view."}]},{"type":"paragraph","inlineContent":[{"text":"When spring loading is enabled on a segmented control and a user drags something over a segment, the segment highlights to indicate that it responds to force clicking. In this situation, if the user presses harder, additional highlighting occurs to indicate that the segment was activated.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"On systems that don’t support pressure sensitivity, simply hovering over the segment for a short period of time is sufficient to activate the segment.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["/documentation/appkit/nssegmentedcontrol/isspringloaded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nssegmentedcontrol/isspringloaded"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"metadata":{"platforms":[{"introducedAt":"10.10.3","deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"title":"isSpringLoaded","navigatorTitle":[{"text":"springLoaded","kind":"identifier"}],"externalID":"c:objc(cs)NSSegmentedControl(py)springLoaded","modules":[{"name":"AppKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpringLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded","navigatorTitle":[{"text":"springLoaded","kind":"identifier"}],"title":"isSpringLoaded","abstract":[{"text":"A Boolean value that indicates whether spring loading is enabled for the control.","type":"text"}],"kind":"symbol","url":"/documentation/appkit/nssegmentedcontrol/isspringloaded","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpringLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl":{"url":"/documentation/appkit/nssegmentedcontrol","kind":"symbol","navigatorTitle":[{"text":"NSSegmentedControl","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSSegmentedControl","abstract":[{"text":"Display one or more buttons in a single horizontal group.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSegmentedControl","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","title":"setMenu(_:forSegment:)","abstract":[{"text":"Sets the menu for the specified segment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"setMenu:forSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/setmenu(_:forsegment:)","role":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setShowsMenuIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","title":"setShowsMenuIndicator(_:forSegment:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"setShowsMenuIndicator:forSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/setshowsmenuindicator(_:forsegment:)","role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","title":"menu(forSegment:)","abstract":[{"text":"Returns the menu for the specified segment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"menuForSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/menu(forsegment:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsMenuIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)","title":"showsMenuIndicator(forSegment:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"showsMenuIndicatorForSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/showsmenuindicator(forsegment:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"introducedAt":"10.10.3","name":"macOS","unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"springLoaded","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"springLoaded","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"op":"replace","path":"/hierarchy"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)"],"anchor":"Configuring-a-Segment-Menu","title":"Configuring a Segment Menu","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isSpringLoaded"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"springLoaded"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"springLoaded","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSpringLoaded/title"},{"value":[{"text":"springLoaded","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSpringLoaded/fragments"},{"value":"NSSegmentedControl","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title"},{"value":[{"kind":"identifier","text":"NSSegmentedControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments"},{"value":[{"text":"NSSegmentedControl","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle"},{"value":"setMenu:forSegment:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setMenu(_:forSegment:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMenu:forSegment:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setMenu(_:forSegment:)/fragments"},{"value":"setShowsMenuIndicator:forSegment:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setShowsMenuIndicator(_:forSegment:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setShowsMenuIndicator:forSegment:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setShowsMenuIndicator(_:forSegment:)/fragments"},{"value":"menuForSegment:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1menu(forSegment:)/title"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1menu(forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"menuForSegment:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1showsMenuIndicator(forSegment:)/title","value":"showsMenuIndicatorForSegment:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1showsMenuIndicator(forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showsMenuIndicatorForSegment:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}