{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsMenuIndicator"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"segment","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"metadata":{"platforms":[{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"10.13","unavailable":false}],"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"role":"symbol","externalID":"c:objc(cs)NSSegmentedControl(im)showsMenuIndicatorForSegment:","title":"showsMenuIndicator(forSegment:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showsMenuIndicator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSegment"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"showsMenuIndicatorForSegment:","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nssegmentedcontrol/showsmenuindicator(forsegment:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nssegmentedcontrol/showsmenuindicator(forsegment:)"]}],"seeAlsoSections":[{"generated":true,"title":"Configuring a Segment Menu","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded"],"anchor":"Configuring-a-Segment-Menu"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl":{"url":"/documentation/appkit/nssegmentedcontrol","kind":"symbol","navigatorTitle":[{"text":"NSSegmentedControl","kind":"identifier"}],"role":"symbol","type":"topic","title":"NSSegmentedControl","abstract":[{"text":"Display one or more buttons in a single horizontal group.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSSegmentedControl","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded":{"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded","navigatorTitle":[{"text":"springLoaded","kind":"identifier"}],"title":"isSpringLoaded","abstract":[{"text":"A Boolean value that indicates whether spring loading is enabled for the control.","type":"text"}],"kind":"symbol","url":"/documentation/appkit/nssegmentedcontrol/isspringloaded","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSpringLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showsMenuIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/showsMenuIndicator(forSegment:)","title":"showsMenuIndicator(forSegment:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"showsMenuIndicatorForSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/showsmenuindicator(forsegment:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:Si":{"abstract":[{"type":"text","text":"A signed integer value type."}],"url":"/documentation/Swift/Int","kind":"symbol","role":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","type":"topic","fragments":[{"text":"@frozen","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}]},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"menu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","title":"menu(forSegment:)","abstract":[{"text":"Returns the menu for the specified segment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"menuForSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/menu(forsegment:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMenu","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSMenu","preciseIdentifier":"c:objc(cs)NSMenu","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","title":"setMenu(_:forSegment:)","abstract":[{"text":"Sets the menu for the specified segment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"setMenu:forSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/setmenu(_:forsegment:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setShowsMenuIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forSegment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","title":"setShowsMenuIndicator(_:forSegment:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"setShowsMenuIndicator:forSegment:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nssegmentedcontrol/setshowsmenuindicator(_:forsegment:)","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"fragments":[{"kind":"text","text":"typealias "},{"kind":"identifier","text":"NSInteger"}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes an integer."}],"title":"NSInteger"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.13","name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"showsMenuIndicatorForSegment:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"showsMenuIndicatorForSegment:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Configuring a Segment Menu","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setMenu(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/menu(forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/setShowsMenuIndicator(_:forSegment:)","doc://com.apple.appkit/documentation/AppKit/NSSegmentedControl/isSpringLoaded"],"anchor":"Configuring-a-Segment-Menu"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"showsMenuIndicatorForSegment:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"segment","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/title","value":"NSSegmentedControl","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/fragments","value":[{"kind":"identifier","text":"NSSegmentedControl"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl/navigatorTitle","value":[{"kind":"identifier","text":"NSSegmentedControl"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSpringLoaded/title","value":"springLoaded","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1isSpringLoaded/fragments","value":[{"kind":"identifier","text":"springLoaded"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1showsMenuIndicator(forSegment:)/title","value":"showsMenuIndicatorForSegment:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1showsMenuIndicator(forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showsMenuIndicatorForSegment:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1menu(forSegment:)/title","value":"menuForSegment:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1menu(forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"menuForSegment:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setMenu(_:forSegment:)/title","value":"setMenu:forSegment:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setMenu(_:forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMenu:forSegment:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setShowsMenuIndicator(_:forSegment:)/title","value":"setShowsMenuIndicator:forSegment:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSegmentedControl~1setShowsMenuIndicator(_:forSegment:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setShowsMenuIndicator:forSegment:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}