{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
        "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t/reserved-3n62l"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@es_event_close_t@Ua@FI@reserved",
    "fragments": [
      {
        "kind": "identifier",
        "text": "reserved"
      }
    ],
    "modules": [
      {
        "name": "Endpoint Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "reserved"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "reserved"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@uint8_t",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@uint8_t",
              "text": "uint8_t"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reserved"
            },
            {
              "kind": "text",
              "text": "["
            },
            {
              "kind": "number",
              "text": "64"
            },
            {
              "kind": "text",
              "text": "];"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity": {
      "abstract": [
        {
          "text": "Develop system extensions that enhance user security.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity",
      "kind": "symbol",
      "role": "collection",
      "title": "Endpoint Security",
      "type": "topic",
      "url": "/documentation/endpointsecurity"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t": {
      "abstract": [
        {
          "text": "A type for an event that indicates the closing of a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "es_event_close_t"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "es_event_close_t"
        }
      ],
      "role": "symbol",
      "title": "es_event_close_t",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_close_t"
    },
    "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t/reserved-3n62l": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "reserved"
        }
      ],
      "identifier": "doc://com.apple.endpointsecurity/documentation/EndpointSecurity/es_event_close_t/reserved-3n62l",
      "kind": "symbol",
      "role": "symbol",
      "title": "reserved",
      "type": "topic",
      "url": "/documentation/endpointsecurity/es_event_close_t/reserved-3n62l"
    },
    "doc://com.externally.resolved.symbol/c:@T@uint8_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@uint8_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "uint8_t",
      "type": "topic",
      "url": "/documentation/kernel/uint8_t"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/title",
          "value": "es_event_close_t"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_close_t"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.endpointsecurity~1documentation~1EndpointSecurity~1es_event_close_t/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "es_event_close_t"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/endpointsecurity/es_event_close_t/reserved-3n62l"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
