{
  "abstract": [
    {
      "text": "The number of times a render pass calls any vertex shader.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@MTLCounterResultStatistic@FI@vertexInvocations",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vertexInvocations"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt64V",
        "text": "UInt64"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vertexInvocations"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "vertexInvocations"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vertexInvocations"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt64V",
              "text": "UInt64"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic": {
      "abstract": [
        {
          "text": "The data structure for storing the data you resolve from a statistic counter set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLCounterResultStatistic"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLCounterResultStatistic"
        }
      ],
      "role": "symbol",
      "title": "MTLCounterResultStatistic",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations": {
      "abstract": [
        {
          "text": "The number of primitives a render pass sends to the clip stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipperInvocations"
        }
      ],
      "role": "symbol",
      "title": "clipperInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/clipperinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut": {
      "abstract": [
        {
          "text": "The number of primitives the clip stage produces during a render pass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clipperPrimitivesOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clipperPrimitivesOut"
        }
      ],
      "role": "symbol",
      "title": "clipperPrimitivesOut",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/clipperprimitivesout"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations": {
      "abstract": [
        {
          "text": "The number of times a pass calls any compute kernel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "computeKernelInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "computeKernelInvocations"
        }
      ],
      "role": "symbol",
      "title": "computeKernelInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/computekernelinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations": {
      "abstract": [
        {
          "text": "The number of times a render pass calls fragment shaders.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fragmentInvocations"
        }
      ],
      "role": "symbol",
      "title": "fragmentInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/fragmentinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed": {
      "abstract": [
        {
          "text": "The number of fragments a render pass sends to the visibility and blend stages because they pass the scissor, depth, and stencil tests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fragmentsPassed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fragmentsPassed"
        }
      ],
      "role": "symbol",
      "title": "fragmentsPassed",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/fragmentspassed"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations": {
      "abstract": [
        {
          "text": "The number of vertices a render pass sends to a post-tessellation vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postTessellationVertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "postTessellationVertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "postTessellationVertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/posttessellationvertexinvocations"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches": {
      "abstract": [
        {
          "text": "The number of tessellation patches a render pass sends to the tessellation stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tessellationInputPatches"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tessellationInputPatches"
        }
      ],
      "role": "symbol",
      "title": "tessellationInputPatches",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/tessellationinputpatches"
    },
    "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations": {
      "abstract": [
        {
          "text": "The number of times a render pass calls any vertex shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexInvocations"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt64V",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/vertexInvocations",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexInvocations"
        }
      ],
      "role": "symbol",
      "title": "vertexInvocations",
      "type": "topic",
      "url": "/documentation/metal/mtlcounterresultstatistic/vertexinvocations"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt64V": {
      "abstract": [
        {
          "text": "A 64-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt64",
      "type": "topic",
      "url": "/documentation/Swift/UInt64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Statistics-Values",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
        "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations"
      ],
      "title": "Statistics Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vertexInvocations"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Statistics-Values",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/tessellationInputPatches",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/postTessellationVertexInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/clipperPrimitivesOut",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentInvocations",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/fragmentsPassed",
                "doc://com.apple.metal/documentation/Metal/MTLCounterResultStatistic/computeKernelInvocations"
              ],
              "title": "Statistics Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "vertexInvocations"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1vertexInvocations/title",
          "value": "vertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1vertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentInvocations/title",
          "value": "fragmentInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fragmentInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/title",
          "value": "MTLCounterResultStatistic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLCounterResultStatistic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1computeKernelInvocations/title",
          "value": "computeKernelInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1computeKernelInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "computeKernelInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1tessellationInputPatches/title",
          "value": "tessellationInputPatches"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1tessellationInputPatches/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tessellationInputPatches"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperInvocations/title",
          "value": "clipperInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipperInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperPrimitivesOut/title",
          "value": "clipperPrimitivesOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1clipperPrimitivesOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clipperPrimitivesOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1postTessellationVertexInvocations/title",
          "value": "postTessellationVertexInvocations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1postTessellationVertexInvocations/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "postTessellationVertexInvocations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentsPassed/title",
          "value": "fragmentsPassed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLCounterResultStatistic~1fragmentsPassed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fragmentsPassed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlcounterresultstatistic/vertexinvocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlcounterresultstatistic/vertexinvocations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
