{
  "abstract": [
    {
      "text": "The default background style the system chooses.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/default"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SWAttributionViewBackgroundStyle@SWAttributionViewBackgroundStyleDefault",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "`default`"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SWAttributionViewBackgroundStyleDefault"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SWAttributionView.BackgroundStyle.default"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "`default`"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView": {
      "abstract": [
        {
          "text": "A view that displays the sender who shares a highlight and provides related actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionView"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum": {
      "abstract": [
        {
          "text": "The background styling of the attribution view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.BackgroundStyle",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/color": {
      "abstract": [
        {
          "text": "A non-material background color for the view’s contents, best when placed over monochrome backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewBackgroundStyleColor"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.BackgroundStyle.color",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum/color"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/default": {
      "abstract": [
        {
          "text": "The default background style the system chooses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewBackgroundStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.BackgroundStyle.default",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum/default"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/material": {
      "abstract": [
        {
          "text": "A material background blur for the view’s contents, best when placed over multicolored backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "material"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/material",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWAttributionViewBackgroundStyleMaterial"
        }
      ],
      "role": "symbol",
      "title": "SWAttributionView.BackgroundStyle.material",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum/material"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Background-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/color",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/material"
      ],
      "title": "Background styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SWAttributionViewBackgroundStyleDefault"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Background-styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/color",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWAttributionView/BackgroundStyle-swift.enum/material"
              ],
              "title": "Background styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SWAttributionViewBackgroundStyleDefault"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1default/title",
          "value": "SWAttributionViewBackgroundStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum/title",
          "value": "SWAttributionViewBackgroundStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1material/title",
          "value": "SWAttributionViewBackgroundStyleMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1material/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyleMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1color/title",
          "value": "SWAttributionViewBackgroundStyleColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView~1BackgroundStyle-swift.enum~1color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionViewBackgroundStyleColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/title",
          "value": "SWAttributionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWAttributionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWAttributionView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swattributionview/backgroundstyle-swift.enum/default"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
