{
  "abstract": [
    {
      "text": "The option you choose to allow the model to use all compute units available, including the neural engine.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreml/documentation/CoreML",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/all"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLComputeUnits@MLComputeUnitsAll",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "all"
      }
    ],
    "modules": [
      {
        "name": "Core ML"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLComputeUnitsAll"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLComputeUnits.all"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "all"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreml/documentation/CoreML": {
      "abstract": [
        {
          "text": "Integrate machine learning models into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML",
      "kind": "symbol",
      "role": "collection",
      "title": "Core ML",
      "type": "topic",
      "url": "/documentation/coreml"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits": {
      "abstract": [
        {
          "text": "The set of processing-unit configurations the model can use to make predictions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLComputeUnits"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeUnits"
        }
      ],
      "role": "symbol",
      "title": "MLComputeUnits",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputeunits"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/all": {
      "abstract": [
        {
          "text": "The option you choose to allow the model to use all compute units available, including the neural engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "all"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/all",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeUnitsAll"
        }
      ],
      "role": "symbol",
      "title": "MLComputeUnits.all",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputeunits/all"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndGPU": {
      "abstract": [
        {
          "text": "The option you choose to allow the model to use both the CPU and GPU, but not the neural engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuAndGPU"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndGPU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeUnitsCPUAndGPU"
        }
      ],
      "role": "symbol",
      "title": "MLComputeUnits.cpuAndGPU",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputeunits/cpuandgpu"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndNeuralEngine": {
      "abstract": [
        {
          "text": "The option you choose to allow the model to use both the CPU and neural engine, but not the GPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuAndNeuralEngine"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndNeuralEngine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeUnitsCPUAndNeuralEngine"
        }
      ],
      "role": "symbol",
      "title": "MLComputeUnits.cpuAndNeuralEngine",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputeunits/cpuandneuralengine"
    },
    "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuOnly": {
      "abstract": [
        {
          "text": "The option you choose to limit the model to only use the CPU.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cpuOnly"
        }
      ],
      "identifier": "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLComputeUnitsCPUOnly"
        }
      ],
      "role": "symbol",
      "title": "MLComputeUnits.cpuOnly",
      "type": "topic",
      "url": "/documentation/coreml/mlcomputeunits/cpuonly"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Processing-Unit-Configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuOnly",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndGPU",
        "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndNeuralEngine"
      ],
      "title": "Processing Unit Configurations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLComputeUnitsAll"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnitsAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreml/documentation/CoreML",
                "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Processing-Unit-Configurations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuOnly",
                "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndGPU",
                "doc://com.apple.coreml/documentation/CoreML/MLComputeUnits/cpuAndNeuralEngine"
              ],
              "title": "Processing Unit Configurations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLComputeUnitsAll"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuAndNeuralEngine/title",
          "value": "MLComputeUnitsCPUAndNeuralEngine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuAndNeuralEngine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnitsCPUAndNeuralEngine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuOnly/title",
          "value": "MLComputeUnitsCPUOnly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnitsCPUOnly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits/title",
          "value": "MLComputeUnits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1all/title",
          "value": "MLComputeUnitsAll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1all/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnitsAll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuAndGPU/title",
          "value": "MLComputeUnitsCPUAndGPU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreml~1documentation~1CoreML~1MLComputeUnits~1cpuAndGPU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLComputeUnitsCPUAndGPU"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreml/mlcomputeunits/all"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreml/mlcomputeunits/all"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
