{
  "abstract": [
    {
      "text": "An event that indicates a window’s contents are visible again.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSEventSubtype@NSEventSubtypeWindowExposed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "windowExposed"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEventSubtypeWindowExposed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSEvent.EventSubtype.windowExposed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "windowExposed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent": {
      "abstract": [
        {
          "text": "An object that contains information about an input action, such as a mouse click or a key press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEvent"
        }
      ],
      "role": "symbol",
      "title": "NSEvent",
      "type": "topic",
      "url": "/documentation/appkit/nsevent"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype": {
      "abstract": [
        {
          "text": "Subtypes for various types of events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EventSubtype"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated": {
      "abstract": [
        {
          "text": "An app-activation event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationActivated"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeApplicationActivated"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.applicationActivated",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/applicationactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated": {
      "abstract": [
        {
          "text": "An app-deactivation event occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDeactivated"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeApplicationDeactivated"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.applicationDeactivated",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/applicationdeactivated"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged": {
      "abstract": [
        {
          "text": "An event that indicates a window changed screens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenChanged"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeScreenChanged"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.screenChanged",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/screenchanged"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed": {
      "abstract": [
        {
          "text": "An event that indicates a window’s contents are visible again.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowExposed"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowExposed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeWindowExposed"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.windowExposed",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/windowexposed"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved": {
      "abstract": [
        {
          "text": "An event that indicates a window moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowMoved"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEventSubtypeWindowMoved"
        }
      ],
      "role": "symbol",
      "title": "NSEvent.EventSubtype.windowMoved",
      "type": "topic",
      "url": "/documentation/appkit/nsevent/eventsubtype/windowmoved"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-AppKit-Event-Subtypes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
        "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved"
      ],
      "title": "Getting AppKit Event Subtypes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEventSubtypeWindowExposed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeWindowExposed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-AppKit-Event-Subtypes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationActivated",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/applicationDeactivated",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/screenChanged",
                "doc://com.apple.appkit/documentation/AppKit/NSEvent/EventSubtype/windowMoved"
              ],
              "title": "Getting AppKit Event Subtypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSEventSubtypeWindowExposed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowExposed/title",
          "value": "NSEventSubtypeWindowExposed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowExposed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeWindowExposed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/title",
          "value": "NSEventSubtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/title",
          "value": "NSEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationActivated/title",
          "value": "NSEventSubtypeApplicationActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeApplicationActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowMoved/title",
          "value": "NSEventSubtypeWindowMoved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1windowMoved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeWindowMoved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationDeactivated/title",
          "value": "NSEventSubtypeApplicationDeactivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1applicationDeactivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeApplicationDeactivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1screenChanged/title",
          "value": "NSEventSubtypeScreenChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSEvent~1EventSubtype~1screenChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEventSubtypeScreenChanged"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsevent/eventsubtype/windowexposed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsevent/eventsubtype/windowexposed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
