{
  "abstract": [
    {
      "text": "An optional Core Image filter object that provides the transition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.quartzcore/documentation/QuartzCore",
        "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/filter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CATransition(py)filter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "filter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Animation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "filter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "filter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "filter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If specified, the filter must support both ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputimagekey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputtargetimagekey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " input keys, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/kcioutputimagekey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " output key.  The filter may optionally support the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputextentkey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " input key, which is set to a rectangle describing the region in which the transition should run. If ",
              "type": "text"
            },
            {
              "code": "filter",
              "type": "codeVoice"
            },
            {
              "text": " does not support the required input and output keys the behavior is undefined.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Defaults to ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". When a transition filter is specified the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties are ignored.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that contains the transitioning layer must have its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/layerUsesCoreImageFilters",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows how you can transition between the two states of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " named ",
              "type": "text"
            },
            {
              "code": "transitioningLayer",
              "type": "codeVoice"
            },
            {
              "text": ". When the layer is first created, its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is set to red and its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer/string",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property is set to ",
              "type": "text"
            },
            {
              "code": "Red",
              "type": "codeVoice"
            },
            {
              "text": ". When the ",
              "type": "text"
            },
            {
              "code": "runTransition()",
              "type": "codeVoice"
            },
            {
              "text": " function is called, a new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object is created and added to ",
              "type": "text"
            },
            {
              "code": "transitioningLayer",
              "type": "codeVoice"
            },
            {
              "text": ", and the state of the layer is changed so that its background color is blue and its rendered text reads ",
              "type": "text"
            },
            {
              "code": "Blue",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The end result is that the transition animates from the red state to the blue state using a ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CICopyMachineTransition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " transition.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func viewDidLoad() {",
            "    super.viewDidLoad()",
            "    ",
            "    view.layerUsesCoreImageFilters = true",
            "    ",
            "    view.layer = CALayer()",
            "    ",
            "    transitioningLayer.frame = CGRect(x: 10, y: 10,",
            "                                      width: 320, height: 160)",
            "    ",
            "    view.layer!.addSublayer(transitioningLayer)",
            "    ",
            "    // Initial \"red\" state",
            "    transitioningLayer.backgroundColor = NSColor.red.cgColor",
            "    transitioningLayer.string = \"Red\"",
            "}",
            "     ",
            "func runTransition() {",
            "    let transition = CATransition()",
            "    transition.duration = 2",
            "    ",
            "    transition.filter = CIFilter(name: \"CICopyMachineTransition\")",
            "    transitioningLayer.add(transition,",
            "                           forKey: \"transition\")",
            "    ",
            "    // Transition to \"blue\" state",
            "    transitioningLayer.backgroundColor = NSColor.blue.cgColor",
            "    transitioningLayer.string = \"Blue\"",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is not supported on layers in iOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/AppKit/NSView"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSView/layerUsesCoreImageFilters": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view’s layer uses Core Image filters and needs in-process rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layerUsesCoreImageFilters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/layerUsesCoreImageFilters",
      "kind": "symbol",
      "role": "symbol",
      "title": "layerUsesCoreImageFilters",
      "type": "topic",
      "url": "/documentation/AppKit/NSView/layerUsesCoreImageFilters"
    },
    "doc://com.apple.documentation/documentation/coreimage/kciinputextentkey": {
      "abstract": [
        {
          "text": "A key for a  object that specifies a rectangle that defines the extent of the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCIInputExtentKey"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputextentkey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCIInputExtentKey",
      "type": "topic",
      "url": "/documentation/coreimage/kciinputextentkey"
    },
    "doc://com.apple.documentation/documentation/coreimage/kciinputimagekey": {
      "abstract": [
        {
          "text": "A key for the  object to use as an input image. For filters that also use a background image, this key refers to the foreground image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCIInputImageKey"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputimagekey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCIInputImageKey",
      "type": "topic",
      "url": "/documentation/coreimage/kciinputimagekey"
    },
    "doc://com.apple.documentation/documentation/coreimage/kciinputtargetimagekey": {
      "abstract": [
        {
          "text": "A key for a  object that is the target image for a transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCIInputTargetImageKey"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/kciinputtargetimagekey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCIInputTargetImageKey",
      "type": "topic",
      "url": "/documentation/coreimage/kciinputtargetimagekey"
    },
    "doc://com.apple.documentation/documentation/coreimage/kcioutputimagekey": {
      "abstract": [
        {
          "text": "A key for the  object produced by a filter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCIOutputImageKey"
        },
        {
          "kind": "text",
          "text": ": String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coreimage/kcioutputimagekey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCIOutputImageKey",
      "type": "topic",
      "url": "/documentation/coreimage/kcioutputimagekey"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore": {
      "abstract": [
        {
          "text": "Render, compose, and animate visual elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Animation",
      "type": "topic",
      "url": "/documentation/quartzcore"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor": {
      "abstract": [
        {
          "text": "The background color of the receiver. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGColorRef",
          "text": "CGColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CALayer/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/quartzcore/calayer/backgroundcolor"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer": {
      "abstract": [
        {
          "text": "A layer that provides simple text layout and rendering of plain or attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATextLayer"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATextLayer"
        }
      ],
      "role": "symbol",
      "title": "CATextLayer",
      "type": "topic",
      "url": "/documentation/quartzcore/catextlayer"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer/string": {
      "abstract": [
        {
          "text": "The text to be rendered by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATextLayer/string",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "string"
        }
      ],
      "role": "symbol",
      "title": "string",
      "type": "topic",
      "url": "/documentation/quartzcore/catextlayer/string"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition": {
      "abstract": [
        {
          "text": "An object that provides an animated transition between a layer’s states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CATransition"
        }
      ],
      "role": "symbol",
      "title": "CATransition",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/filter": {
      "abstract": [
        {
          "text": "An optional Core Image filter object that provides the transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/filter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filter"
        }
      ],
      "role": "symbol",
      "title": "filter",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition/filter"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype": {
      "abstract": [
        {
          "text": "Specifies an optional subtype that indicates the direction for the predefined motion-based transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtype"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionSubtype",
          "text": "CATransitionSubtype"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/subtype",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subtype"
        }
      ],
      "role": "symbol",
      "title": "subtype",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition/subtype"
    },
    "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type": {
      "abstract": [
        {
          "text": "Specifies the predefined transition type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CATransitionType",
          "text": "CATransitionType"
        }
      ],
      "identifier": "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/quartzcore/catransition/type"
    },
    "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CICopyMachineTransition": {
      "identifier": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CICopyMachineTransition",
      "title": "CICopyMachineTransition",
      "titleInlineContent": [
        {
          "text": "CICopyMachineTransition",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html#//apple_ref/doc/filter/ci/CICopyMachineTransition"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "filter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.quartzcore/documentation/QuartzCore",
                "doc://com.apple.quartzcore/documentation/QuartzCore/CATransition"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "filter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView~1layerUsesCoreImageFilters/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "layerUsesCoreImageFilters"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CALayer~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1filter/title",
          "value": "filter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1filter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "filter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/title",
          "value": "CATransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1subtype/title",
          "value": "subtype"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATransition~1subtype/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subtype"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/title",
          "value": "CATextLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CATextLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer~1string/title",
          "value": "string"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.quartzcore~1documentation~1QuartzCore~1CATextLayer~1string/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "string"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/quartzcore/catransition/filter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/quartzcore/catransition/filter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
