{
  "abstract": [
    {
      "text": "An identifier for an event parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corehaptics/documentation/CoreHaptics",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreHaptics",
    "externalID": "c:@T@CHHapticEventParameterID",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ParameterID"
      }
    ],
    "modules": [
      {
        "name": "Core Haptics"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ParameterID"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CHHapticEvent.ParameterID"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ParameterID"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/representing-haptic-patterns-in-ahap-files"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Specify event parameters when creating a haptic or audio event. The combination of parameters determines the event’s character.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corehaptics/documentation/CoreHaptics": {
      "abstract": [
        {
          "text": "Compose and play haptic patterns to customize your iOS app’s haptic feedback.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Haptics",
      "type": "topic",
      "url": "/documentation/corehaptics"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent": {
      "abstract": [
        {
          "text": "An object that describes a single haptic or audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CHHapticEvent"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEvent"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEvent",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID": {
      "abstract": [
        {
          "text": "An identifier for an event parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ParameterID"
        }
      ],
      "role": "symbol",
      "title": "CHHapticEvent.ParameterID",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/attackTime": {
      "abstract": [
        {
          "text": "The time at which a haptic pattern’s intensity begins increasing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/attackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDAttackTime"
        }
      ],
      "role": "symbol",
      "title": "attackTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/attacktime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioBrightness": {
      "abstract": [
        {
          "text": "The high-frequency content of an audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioBrightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioBrightness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDAudioBrightness"
        }
      ],
      "role": "symbol",
      "title": "audioBrightness",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/audiobrightness"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPan": {
      "abstract": [
        {
          "text": "The stereo panning of an audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioPan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDAudioPan"
        }
      ],
      "role": "symbol",
      "title": "audioPan",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/audiopan"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPitch": {
      "abstract": [
        {
          "text": "The pitch of an audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioPitch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDAudioPitch"
        }
      ],
      "role": "symbol",
      "title": "audioPitch",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/audiopitch"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioVolume": {
      "abstract": [
        {
          "text": "The volume of an audio event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDAudioVolume"
        }
      ],
      "role": "symbol",
      "title": "audioVolume",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/audiovolume"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/decayTime": {
      "abstract": [
        {
          "text": "The time at which a haptic pattern’s intensity begins decreasing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/decayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDDecayTime"
        }
      ],
      "role": "symbol",
      "title": "decayTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/decaytime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticIntensity": {
      "abstract": [
        {
          "text": "The strength of a haptic event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hapticIntensity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticIntensity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDHapticIntensity"
        }
      ],
      "role": "symbol",
      "title": "hapticIntensity",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/hapticintensity"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticSharpness": {
      "abstract": [
        {
          "text": "The feel of a haptic event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hapticSharpness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticSharpness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDHapticSharpness"
        }
      ],
      "role": "symbol",
      "title": "hapticSharpness",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/hapticsharpness"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates the identifier of a haptic event parameter with the specified string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/init(rawvalue:)"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/releaseTime": {
      "abstract": [
        {
          "text": "The time at which to begin fading the haptic pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/releaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "releaseTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/releasetime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/sustained": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to sustain a haptic event for its specified duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sustained"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEvent",
          "text": "CHHapticEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CHHapticEventParameterID",
          "text": "ParameterID"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/sustained",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CHHapticEventParameterIDSustained"
        }
      ],
      "role": "symbol",
      "title": "sustained",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/parameterid/sustained"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration": {
      "abstract": [
        {
          "text": "The duration of the haptic event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/duration"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/eventParameters": {
      "abstract": [
        {
          "text": "An array of event parameters, possibly empty.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eventParameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CHHapticEventParameter",
          "text": "CHHapticEventParameter"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/eventParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventParameters"
        }
      ],
      "role": "symbol",
      "title": "eventParameters",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/eventparameters"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime": {
      "abstract": [
        {
          "text": "The start time of the event, relative to other events in the same pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relativeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "relativeTime"
        }
      ],
      "role": "symbol",
      "title": "relativeTime",
      "type": "topic",
      "url": "/documentation/corehaptics/chhapticevent/relativetime"
    },
    "doc://com.apple.corehaptics/documentation/CoreHaptics/representing-haptic-patterns-in-ahap-files": {
      "abstract": [
        {
          "text": "Understand the Apple Haptic and Audio Pattern (AHAP) file format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corehaptics/documentation/CoreHaptics/representing-haptic-patterns-in-ahap-files",
      "kind": "article",
      "role": "article",
      "title": "Representing haptic patterns in AHAP files",
      "type": "topic",
      "url": "/documentation/corehaptics/representing-haptic-patterns-in-ahap-files"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Haptic-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/eventParameters",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration"
      ],
      "title": "Configuring Haptic Events"
    }
  ],
  "topicSections": [
    {
      "anchor": "Haptic-Event-Parameter-IDs",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticIntensity",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticSharpness",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/attackTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/decayTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/releaseTime",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/sustained"
      ],
      "title": "Haptic Event Parameter IDs"
    },
    {
      "anchor": "Audio-Event-Parameter-IDs",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioVolume",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPan",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPitch",
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioBrightness"
      ],
      "title": "Audio Event Parameter IDs"
    },
    {
      "anchor": "Swift-Initializers",
      "identifiers": [
        "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/init(rawValue:)"
      ],
      "title": "Swift Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CHHapticEventParameterID"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corehaptics/documentation/CoreHaptics"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Haptic-Event-Parameter-IDs",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticIntensity",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/hapticSharpness",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/attackTime",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/decayTime",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/releaseTime",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/sustained"
              ],
              "title": "Haptic Event Parameter IDs"
            },
            {
              "anchor": "Audio-Event-Parameter-IDs",
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioVolume",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPan",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioPitch",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/ParameterID/audioBrightness"
              ],
              "title": "Audio Event Parameter IDs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Haptic-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/eventParameters",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/relativeTime",
                "doc://com.apple.corehaptics/documentation/CoreHaptics/CHHapticEvent/duration"
              ],
              "title": "Configuring Haptic Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CHHapticEventParameterID"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioVolume/title",
          "value": "CHHapticEventParameterIDAudioVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDAudioVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1releaseTime/title",
          "value": "CHHapticEventParameterIDReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1releaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1hapticSharpness/title",
          "value": "CHHapticEventParameterIDHapticSharpness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1hapticSharpness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDHapticSharpness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1decayTime/title",
          "value": "CHHapticEventParameterIDDecayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1decayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDDecayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioBrightness/title",
          "value": "CHHapticEventParameterIDAudioBrightness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioBrightness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDAudioBrightness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1relativeTime/title",
          "value": "relativeTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1relativeTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "relativeTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1attackTime/title",
          "value": "CHHapticEventParameterIDAttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1attackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDAttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/title",
          "value": "CHHapticEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioPitch/title",
          "value": "CHHapticEventParameterIDAudioPitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioPitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDAudioPitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1hapticIntensity/title",
          "value": "CHHapticEventParameterIDHapticIntensity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1hapticIntensity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDHapticIntensity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1eventParameters/title",
          "value": "eventParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1eventParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "eventParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1sustained/title",
          "value": "CHHapticEventParameterIDSustained"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1sustained/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDSustained"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioPan/title",
          "value": "CHHapticEventParameterIDAudioPan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID~1audioPan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterIDAudioPan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID/title",
          "value": "CHHapticEventParameterID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corehaptics~1documentation~1CoreHaptics~1CHHapticEvent~1ParameterID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CHHapticEventParameterID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corehaptics/chhapticevent/parameterid"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corehaptics/chhapticevent/parameterid"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
