{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"WatchKit"}],"externalID":"c:objc(cs)WKInterfaceGroup(im)setBackgroundColor:","title":"setBackgroundColor(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackgroundColor","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false}],"navigatorTitle":[{"text":"setBackgroundColor:","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"Changes the background color for the group container."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup"]]},"primaryContentSections":[{"declarations":[{"platforms":["watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"color"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The solid background color to be displayed behind all items in the group. Specify "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" to remove the custom color you previously set using this method."}]}],"name":"color"}]},{"content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"If you do not specify a custom background color or if you set the custom color to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":", the group uses the color assigned to the group object in your storyboard file. The default background color is clear.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you set a custom background image for the group, the image is displayed on top of the background color. If the image contains any transparency, the background color shows through the transparent portions of the image."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Changes to the background color of a group are animatable."}]}],"kind":"content"}],"identifier":{"url":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundColor(_:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969"]},{"title":"Setting the Group’s Content","anchor":"Setting-the-Groups-Content","generated":true,"identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImage(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageData(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageNamed(_:)"]}],"sections":[],"kind":"symbol","variants":[{"paths":["/documentation/watchkit/wkinterfacegroup/setbackgroundcolor(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/watchkit/wkinterfacegroup/setbackgroundcolor(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImage(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"type":"topic","title":"setBackgroundImage(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImage:"}],"url":"/documentation/watchkit/wkinterfacegroup/setbackgroundimage(_:)","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImage(_:)","abstract":[{"text":"Changes the background image of the group container to the specified image.","type":"text"}]},"https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969":{"title":"App Programming Guide for watchOS","url":"https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969","titleInlineContent":[{"type":"text","text":"App Programming Guide for watchOS"}],"type":"link","identifier":"https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup":{"role":"symbol","url":"/documentation/watchkit/wkinterfacegroup","type":"topic","kind":"symbol","title":"WKInterfaceGroup","abstract":[{"text":"A container for one or more interface objects.","type":"text"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WKInterfaceGroup","kind":"identifier"}],"navigatorTitle":[{"text":"WKInterfaceGroup","kind":"identifier"}]},"doc://com.apple.watchkit/documentation/WatchKit":{"kind":"symbol","abstract":[{"type":"text","text":"Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions."}],"role":"collection","type":"topic","identifier":"doc://com.apple.watchkit/documentation/WatchKit","title":"WatchKit","url":"/documentation/watchkit"},"doc://com.externally.resolved.symbol/c:objc(cs)UIColor":{"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIColor","abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/UIKit/UIColor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIColor"}],"title":"UIColor","role":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundColor(_:)":{"url":"/documentation/watchkit/wkinterfacegroup/setbackgroundcolor(_:)","navigatorTitle":[{"kind":"identifier","text":"setBackgroundColor:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundColor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?)"}],"role":"symbol","identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundColor(_:)","title":"setBackgroundColor(_:)","abstract":[{"type":"text","text":"Changes the background color for the group container."}],"type":"topic","kind":"symbol"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageData(_:)":{"abstract":[{"text":"Changes the background image of the group container to the image in the specified data object.","type":"text"}],"title":"setBackgroundImageData(_:)","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImageData:"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageData(_:)","kind":"symbol","url":"/documentation/watchkit/wkinterfacegroup/setbackgroundimagedata(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImageData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","abstract":[{"type":"text","text":""}],"role":"overview","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies"},"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageNamed(_:)":{"abstract":[{"text":"Changes the background image of the group container to the image in the specified resource file.","type":"text"}],"title":"setBackgroundImageNamed(_:)","navigatorTitle":[{"kind":"identifier","text":"setBackgroundImageNamed:"}],"identifier":"doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageNamed(_:)","kind":"symbol","url":"/documentation/watchkit/wkinterfacegroup/setbackgroundimagenamed(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackgroundImageNamed"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"introducedAt":"2.0","name":"watchOS","deprecated":false,"unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"setBackgroundColor:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundColor:","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.watchkit/documentation/WatchKit","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["https://developer.apple.com/library/archive/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html#//apple_ref/doc/uid/TP40014969"]},{"anchor":"Setting-the-Groups-Content","title":"Setting the Group’s Content","identifiers":["doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImage(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageData(_:)","doc://com.apple.watchkit/documentation/WatchKit/WKInterfaceGroup/setBackgroundImageNamed(_:)"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["watchOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"color","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The solid background color to be displayed behind all items in the group. Specify "},{"code":"nil","type":"codeVoice"},{"text":" to remove the custom color you previously set using this method.","type":"text"}]}]}]}},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImage(_:)/title","value":"setBackgroundImage:","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImage(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImage:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup/title","value":"WKInterfaceGroup","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup/fragments","value":[{"kind":"identifier","text":"WKInterfaceGroup"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup/navigatorTitle","value":[{"text":"WKInterfaceGroup","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIColor/fragments","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIColor","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundColor(_:)/title","value":"setBackgroundColor:","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundColor(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundColor:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImageData(_:)/title","value":"setBackgroundImageData:","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImageData(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBackgroundImageData:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImageNamed(_:)/title","value":"setBackgroundImageNamed:","op":"replace"},{"path":"/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKInterfaceGroup~1setBackgroundImageNamed(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackgroundImageNamed:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}