{
  "abstract": [
    {
      "text": "The value of the minutes portion of the SMPTE time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mMinutes"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@SMPTETime@FI@mMinutes",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mMinutes"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int16V",
        "text": "Int16"
      }
    ],
    "modules": [
      {
        "name": "Core Audio Types"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mMinutes"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "2.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "10.0",
        "name": "macOS"
      },
      {
        "beta": false,
        "introducedAt": "9.0",
        "name": "tvOS"
      },
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "visionOS"
      },
      {
        "beta": false,
        "introducedAt": "3.0",
        "name": "watchOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "mMinutes"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mMinutes"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int16V",
              "text": "Int16"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes": {
      "abstract": [
        {
          "text": "Use specialized data types to interact with audio streams, complex buffers, and audiovisual timestamps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Audio Types",
      "type": "topic",
      "url": "/documentation/coreaudiotypes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime": {
      "abstract": [
        {
          "text": "A structure that defines an SMPTE time value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SMPTETime"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SMPTETime"
        }
      ],
      "role": "symbol",
      "title": "SMPTETime",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mCounter": {
      "abstract": [
        {
          "text": "The total number of messages received. It takes 8 messages to carry a full SMPTE time code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mCounter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mCounter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mCounter"
        }
      ],
      "role": "symbol",
      "title": "mCounter",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mcounter"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFlags": {
      "abstract": [
        {
          "text": "A set of flags that indicate the SMPTE state (see ",
          "type": "text"
        },
        {
          "code": "SMPTE Time Flags",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SMPTETimeFlags",
          "text": "SMPTETimeFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFlags"
        }
      ],
      "role": "symbol",
      "title": "mFlags",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mflags"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFrames": {
      "abstract": [
        {
          "text": "The value of the frames portion of the SMPTE time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mFrames"
        }
      ],
      "role": "symbol",
      "title": "mFrames",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mframes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mHours": {
      "abstract": [
        {
          "text": "The value of the hours portion of the SMPTE time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mHours"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mHours",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mHours"
        }
      ],
      "role": "symbol",
      "title": "mHours",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mhours"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mMinutes": {
      "abstract": [
        {
          "text": "The value of the minutes portion of the SMPTE time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mMinutes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mMinutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mMinutes"
        }
      ],
      "role": "symbol",
      "title": "mMinutes",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mminutes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSeconds": {
      "abstract": [
        {
          "text": "The value of the seconds portion of the SMPTE time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSeconds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSeconds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSeconds"
        }
      ],
      "role": "symbol",
      "title": "mSeconds",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mseconds"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframeDivisor": {
      "abstract": [
        {
          "text": "The number of subframes per video frame (typically 80).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSubframeDivisor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframeDivisor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSubframeDivisor"
        }
      ],
      "role": "symbol",
      "title": "mSubframeDivisor",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/msubframedivisor"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframes": {
      "abstract": [
        {
          "text": "A subframe offset to the HH:MM:SS:FF time. You can use this field to position a time marker somewhere within the time span represented by a video frame, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mSubframes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mSubframes"
        }
      ],
      "role": "symbol",
      "title": "mSubframes",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/msubframes"
    },
    "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mType": {
      "abstract": [
        {
          "text": "A SMPTE time type constant indicating the kind of SMPTE time used (see ",
          "type": "text"
        },
        {
          "code": "SMPTE Timecode Types",
          "type": "codeVoice"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SMPTETimeType",
          "text": "SMPTETimeType"
        }
      ],
      "identifier": "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mType"
        }
      ],
      "role": "symbol",
      "title": "mType",
      "type": "topic",
      "url": "/documentation/coreaudiotypes/smptetime/mtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int16V": {
      "abstract": [
        {
          "text": "A 16-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int16",
      "type": "topic",
      "url": "/documentation/Swift/Int16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mCounter",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFlags",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFrames",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mHours",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSeconds",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframeDivisor",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframes",
        "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mType"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mMinutes"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mCounter",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFlags",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mFrames",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mHours",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSeconds",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframeDivisor",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mSubframes",
                "doc://com.apple.coreaudiotypes/documentation/CoreAudioTypes/SMPTETime/mType"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@SInt16",
                    "text": "SInt16"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "mMinutes"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSubframeDivisor/title",
          "value": "mSubframeDivisor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSubframeDivisor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSubframeDivisor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mFrames/title",
          "value": "mFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/title",
          "value": "SMPTETime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SMPTETime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mMinutes/title",
          "value": "mMinutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mMinutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mMinutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSubframes/title",
          "value": "mSubframes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSubframes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSubframes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mCounter/title",
          "value": "mCounter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mCounter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mCounter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mFlags/title",
          "value": "mFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mHours/title",
          "value": "mHours"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mHours/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mHours"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSeconds/title",
          "value": "mSeconds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mSeconds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mSeconds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mType/title",
          "value": "mType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiotypes~1documentation~1CoreAudioTypes~1SMPTETime~1mType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiotypes/smptetime/mminutes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiotypes/smptetime/mminutes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
