{
  "abstract": [
    {
      "text": "The Transport Layer Security (TLS) version to use during a TLS authentication handshake.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NEHotspotEAPSettings(py)preferredTLSVersion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "preferredTLSVersion"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NEHotspotEAPSettings",
        "text": "NEHotspotEAPSettings"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NEHotspotConfigurationEAPTLSVersion",
        "text": "TLSVersion"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "preferredTLSVersion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "preferredTLSVersion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "preferredTLSVersion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NEHotspotEAPSettings",
              "text": "NEHotspotEAPSettings"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NEHotspotConfigurationEAPTLSVersion",
              "text": "TLSVersion"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Optional. For possible values see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default value is Version 1.2.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings": {
      "abstract": [
        {
          "text": "Extensible Authentication Protocol settings for configuring WPA and WPA2 enterprise Wi-Fi networks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotEAPSettings"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType": {
      "abstract": [
        {
          "text": "The EAP types that may be specified in ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EAPType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EAPType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.EAPType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/eaptype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion": {
      "abstract": [
        {
          "text": "The EAPTLS Version identifiers that may be specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TLSVersion"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/tlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum": {
      "abstract": [
        {
          "text": "The TTLS Inner Authentication Types that may be specified by ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TTLSInnerAuthenticationType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TTLSInnerAuthenticationType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotEAPSettings.TTLSInnerAuthenticationType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.enum"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/isTLSClientCertificateRequired": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether a network requires two-factor authentication or allows zero-factor authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTLSClientCertificateRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/isTLSClientCertificateRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tlsClientCertificateRequired"
        }
      ],
      "role": "symbol",
      "title": "isTLSClientCertificateRequired",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/istlsclientcertificaterequired"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/outerIdentity": {
      "abstract": [
        {
          "text": "The identity string to be used in the EAP-Identity/Response packet during outer EAP authentication.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outerIdentity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/outerIdentity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outerIdentity"
        }
      ],
      "role": "symbol",
      "title": "outerIdentity",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/outeridentity"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/password": {
      "abstract": [
        {
          "text": "The password component of the IEEE 802.1X authentication credential.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "password"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/password",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "password"
        }
      ],
      "role": "symbol",
      "title": "password",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/password"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion": {
      "abstract": [
        {
          "text": "The Transport Layer Security (TLS) version to use during a TLS authentication handshake.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTLSVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEHotspotEAPSettings",
          "text": "NEHotspotEAPSettings"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEHotspotConfigurationEAPTLSVersion",
          "text": "TLSVersion"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/preferredTLSVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTLSVersion"
        }
      ],
      "role": "symbol",
      "title": "preferredTLSVersion",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/preferredtlsversion"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes": {
      "abstract": [
        {
          "text": "An array of supported EAP types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedEAPTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedEAPTypes"
        }
      ],
      "role": "symbol",
      "title": "supportedEAPTypes",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/supportedeaptypes"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/trustedServerNames": {
      "abstract": [
        {
          "text": "An array of server certificate common name strings used to verify a server’s certificate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trustedServerNames"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/trustedServerNames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trustedServerNames"
        }
      ],
      "role": "symbol",
      "title": "trustedServerNames",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/trustedservernames"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/ttlsInnerAuthenticationType-swift.property": {
      "abstract": [
        {
          "text": "The inner-layer authentication protocol used by a TTLS module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ttlsInnerAuthenticationType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NEHotspotEAPSettings",
          "text": "NEHotspotEAPSettings"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NEHotspotConfigurationTTLSInnerAuthenticationType",
          "text": "TTLSInnerAuthenticationType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/ttlsInnerAuthenticationType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ttlsInnerAuthenticationType"
        }
      ],
      "role": "symbol",
      "title": "ttlsInnerAuthenticationType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/ttlsinnerauthenticationtype-swift.property"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/username": {
      "abstract": [
        {
          "text": "The user name string for EAP authentication, encoded as UTF-8.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "username"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/username",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "username"
        }
      ],
      "role": "symbol",
      "title": "username",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspoteapsettings/username"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-EAP-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/isTLSClientCertificateRequired",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/trustedServerNames",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/username",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/password",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/outerIdentity",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/ttlsInnerAuthenticationType-swift.property",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum"
      ],
      "title": "Accessing EAP properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "preferredTLSVersion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-EAP-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/isTLSClientCertificateRequired",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/trustedServerNames",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/supportedEAPTypes",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/EAPType",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/username",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/password",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/outerIdentity",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/ttlsInnerAuthenticationType-swift.property",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TTLSInnerAuthenticationType-swift.enum"
              ],
              "title": "Accessing EAP properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotEAPSettings/TLSVersion",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NEHotspotConfigurationEAPTLSVersion",
                    "text": "NEHotspotConfigurationEAPTLSVersion"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "preferredTLSVersion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1password/title",
          "value": "password"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1password/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "password"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1preferredTLSVersion/title",
          "value": "preferredTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1preferredTLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1username/title",
          "value": "username"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1username/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "username"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/title",
          "value": "NEHotspotEAPSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotEAPSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/title",
          "value": "NEHotspotConfigurationEAPTLSVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TLSVersion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPTLSVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1outerIdentity/title",
          "value": "outerIdentity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1outerIdentity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outerIdentity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1ttlsInnerAuthenticationType-swift.property/title",
          "value": "ttlsInnerAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1ttlsInnerAuthenticationType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ttlsInnerAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1trustedServerNames/title",
          "value": "trustedServerNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1trustedServerNames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trustedServerNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1supportedEAPTypes/title",
          "value": "supportedEAPTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1supportedEAPTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedEAPTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/title",
          "value": "NEHotspotConfigurationEAPType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1EAPType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationEAPType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1isTLSClientCertificateRequired/title",
          "value": "tlsClientCertificateRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1isTLSClientCertificateRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tlsClientCertificateRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/title",
          "value": "NEHotspotConfigurationTTLSInnerAuthenticationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationTTLSInnerAuthenticationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotEAPSettings~1TTLSInnerAuthenticationType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotConfigurationTTLSInnerAuthenticationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/preferredtlsversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspoteapsettings/preferredtlsversion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
