{
  "abstract": [
    {
      "text": "Creates a new calendar view decoration with a filled circle image, using the color and size that you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICalendarViewDecoration/decorationWithColor:size:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICalendarViewDecoration(cm)decorationWithColor:size:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "decorationWithColor:size:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "decorationWithColor:size:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "decorationWithColor:size:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "decorationWithColor:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIColor",
              "text": "UIColor"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "color"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "size:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UICalendarViewDecorationSize",
              "text": "UICalendarViewDecorationSize"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "size"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A color for the decoration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "color"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A relative size for the decoration.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "size"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A calendar view decoration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The color defaults to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if you don’t specify it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The size defaults to .",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize/medium",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if you don’t specify it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration": {
      "abstract": [
        {
          "text": "A view that a calendar view displays for a specific date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Decoration"
        }
      ],
      "role": "symbol",
      "title": "UICalendarView.Decoration",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview/decoration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration/init()": {
      "abstract": [
        {
          "text": "Creates a default calendar view decoration with a filled circle image, using the system fill color and medium size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview/decoration/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize": {
      "abstract": [
        {
          "text": "Constants that indicate the relative size of a decoration in a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DecorationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DecorationSize"
        }
      ],
      "role": "symbol",
      "title": "UICalendarView.DecorationSize",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview/decorationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize/medium": {
      "abstract": [
        {
          "text": "A medium relative decoration size in a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/DecorationSize/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarViewDecorationSizeMedium"
        }
      ],
      "role": "symbol",
      "title": "UICalendarView.DecorationSize.medium",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview/decorationsize/medium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarViewDecoration/decorationWithColor:size:": {
      "abstract": [
        {
          "text": "Creates a new calendar view decoration with a filled circle image, using the color and size that you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "decorationWithColor:size:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarViewDecoration/decorationWithColor:size:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decorationWithColor:size:"
        }
      ],
      "role": "symbol",
      "title": "decorationWithColor:size:",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarviewdecoration/decorationwithcolor:size:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill": {
      "abstract": [
        {
          "text": "An overlay fill color for thin and small shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemFillColor"
        }
      ],
      "role": "symbol",
      "title": "systemFill",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/systemfill"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Default-Decoration-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICalendarView/Decoration/init()"
      ],
      "title": "Creating a Default Decoration View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1DecorationSize~1medium/title",
          "value": "UICalendarViewDecorationSizeMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1DecorationSize~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarViewDecorationSizeMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemFill/title",
          "value": "systemFillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemFillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1DecorationSize/title",
          "value": "UICalendarViewDecorationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1DecorationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarViewDecorationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1DecorationSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarViewDecorationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1Decoration~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1Decoration~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1Decoration/title",
          "value": "UICalendarViewDecoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1Decoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarViewDecoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1Decoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarViewDecoration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicalendarviewdecoration/decorationwithcolor:size:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
