{
  "abstract": [
    {
      "text": "The state from a previous AR session to attempt to resume with this session configuration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.arkit/documentation/ARKit",
        "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/initialWorldMap"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ARPositionalTrackingConfiguration(py)initialWorldMap",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "initialWorldMap"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ARWorldMap",
        "text": "ARWorldMap"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "ARKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initialWorldMap"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "initialWorldMap"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "initialWorldMap"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldMap",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ARWorldMap",
              "text": "ARWorldMap"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldMap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " encapsulates the state of a running ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This state includes ARKit’s awareness of the physical space the user moves the device in (which ARKit uses to determine the device’s position and orientation), as well as any ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects added to the session (which can represent detected real-world features or virtual content placed by your app). After you use  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/getCurrentWorldMap(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to save a session’s world map, you can assign it to a configuration’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/run(_:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to start another session with the same spatial awareness and anchors.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By saving world maps and using them to start new sessions, your app can add new AR capabilities:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Multiuser AR experiences.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Create a shared frame of reference by sending archived ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldMap",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects to a nearby user’s device. With two devices tracking the same world map, you can build a networked experience where both users can see and interact with the same virtual content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Persistent AR experiences.",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    },
                    {
                      "text": " Save a world map when your app becomes inactive, then restore it the next time your app launches in the same physical environment. You can use  anchors from the resumed world map to place the same virtual content at the same positions from the saved session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you run a session with an initial world map, the session starts in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") tracking state while ARKit attempts to reconcile the recorded world map with the current environment. If successful, the tracking state becomes ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " after a short time, indicating that the current world coordinate system and anchors match those from the recorded world map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If ARKit cannot reconcile the recorded world map with the current environment (for example, if the device is in an entirely different place from where the world map was recorded), the session remains in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state indefinitely.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.arkit/documentation/ARKit": {
      "abstract": [
        {
          "text": "Integrate hardware sensing features to produce augmented reality apps and games.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ARKit",
      "type": "topic",
      "url": "/documentation/arkit"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARAnchor": {
      "abstract": [
        {
          "text": "An object that specifies the position and orientation of an item in the physical environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARAnchor"
        }
      ],
      "role": "symbol",
      "title": "ARAnchor",
      "type": "topic",
      "url": "/documentation/arkit/aranchor"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing": {
      "abstract": [
        {
          "text": "The AR session is attempting to resume after an interruption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "relocalizing"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/Reason/relocalizing",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.Reason.relocalizing",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/reason/relocalizing"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)": {
      "abstract": [
        {
          "text": "Tracking is available, but the quality of results is questionable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARCamera",
          "text": "ARCamera"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8ARCameraC5ARKitE13TrackingStateO",
          "text": "TrackingState"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8ARCameraC5ARKitE13TrackingStateO6ReasonO",
          "text": "Reason"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/limited(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.limited(_:)",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/limited(_:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal": {
      "abstract": [
        {
          "text": "Camera position tracking is providing optimal results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARCamera/TrackingState-swift.enum/normal",
      "kind": "symbol",
      "role": "symbol",
      "title": "ARCamera.TrackingState.normal",
      "type": "topic",
      "url": "/documentation/arkit/arcamera/trackingstate-swift.enum/normal"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration": {
      "abstract": [
        {
          "text": "A configuration that tracks only the device’s position in 3D space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARPositionalTrackingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARPositionalTrackingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "ARPositionalTrackingConfiguration",
      "type": "topic",
      "url": "/documentation/arkit/arpositionaltrackingconfiguration"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/init()": {
      "abstract": [
        {
          "text": "Creates a new positional tracking configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/arkit/arpositionaltrackingconfiguration/init()"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/initialWorldMap": {
      "abstract": [
        {
          "text": "The state from a previous AR session to attempt to resume with this session configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialWorldMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARWorldMap",
          "text": "ARWorldMap"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/initialWorldMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialWorldMap"
        }
      ],
      "role": "symbol",
      "title": "initialWorldMap",
      "type": "topic",
      "url": "/documentation/arkit/arpositionaltrackingconfiguration/initialworldmap"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/new": {
      "abstract": [
        {
          "text": "Creates a new positional tracking configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/new",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "role": "symbol",
      "title": "new",
      "type": "topic",
      "url": "/documentation/arkit/arpositionaltrackingconfiguration/new"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession": {
      "abstract": [
        {
          "text": "The object that manages the major tasks associated with every AR experience, such as motion tracking, camera passthrough, and image analysis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARSession"
        }
      ],
      "role": "symbol",
      "title": "ARSession",
      "type": "topic",
      "url": "/documentation/arkit/arsession"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession/getCurrentWorldMap(completionHandler:)": {
      "abstract": [
        {
          "text": "Returns an object encapsulating the world-tracking session’s space-mapping state and set of anchors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getCurrentWorldMap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARWorldMap",
          "text": "ARWorldMap"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/getCurrentWorldMap(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getCurrentWorldMapWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "getCurrentWorldMap(completionHandler:)",
      "type": "topic",
      "url": "/documentation/arkit/arsession/getcurrentworldmap(completionhandler:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARSession/run(_:options:)": {
      "abstract": [
        {
          "text": "Starts AR processing for the session with the specified configuration and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "run"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARConfiguration",
          "text": "ARConfiguration"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARSession",
          "text": "ARSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ARSessionRunOptions",
          "text": "RunOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARSession/run(_:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runWithConfiguration:options:"
        }
      ],
      "role": "symbol",
      "title": "run(_:options:)",
      "type": "topic",
      "url": "/documentation/arkit/arsession/run(_:options:)"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARWorldMap": {
      "abstract": [
        {
          "text": "The state in a world-tracking AR session during which a device maps the user’s position in physical space and proximity to anchor objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ARWorldMap"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ARWorldMap"
        }
      ],
      "role": "symbol",
      "title": "ARWorldMap",
      "type": "topic",
      "url": "/documentation/arkit/arworldmap"
    },
    "doc://com.apple.arkit/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap": {
      "abstract": [
        {
          "text": "The state from a previous AR session to attempt to resume with this session configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialWorldMap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ARWorldMap",
          "text": "ARWorldMap"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldTrackingConfiguration/initialWorldMap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialWorldMap"
        }
      ],
      "role": "symbol",
      "title": "initialWorldMap",
      "type": "topic",
      "url": "/documentation/arkit/arworldtrackingconfiguration/initialworldmap"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/init()"
      ],
      "title": "Creating a Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initialWorldMap"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.arkit/documentation/ARKit",
                "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/init()",
                "doc://com.apple.arkit/documentation/ARKit/ARPositionalTrackingConfiguration/new"
              ],
              "title": "Creating a Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.arkit/documentation/ARKit/ARWorldMap",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ARWorldMap",
                    "text": "ARWorldMap"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "initialWorldMap"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARWorldTrackingConfiguration~1initialWorldMap/title",
          "value": "initialWorldMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARWorldTrackingConfiguration~1initialWorldMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1run(_:options:)/title",
          "value": "runWithConfiguration:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1run(_:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runWithConfiguration:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration/title",
          "value": "ARPositionalTrackingConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPositionalTrackingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARPositionalTrackingConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/title",
          "value": "ARSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1getCurrentWorldMap(completionHandler:)/title",
          "value": "getCurrentWorldMapWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARSession~1getCurrentWorldMap(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "getCurrentWorldMapWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration~1initialWorldMap/title",
          "value": "initialWorldMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARPositionalTrackingConfiguration~1initialWorldMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARWorldMap/title",
          "value": "ARWorldMap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARWorldMap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARWorldMap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARWorldMap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/title",
          "value": "ARAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.arkit~1documentation~1ARKit~1ARAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ARAnchor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/arkit/arpositionaltrackingconfiguration/initialworldmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/arkit/arpositionaltrackingconfiguration/initialworldmap"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
