{
  "abstract": [
    {
      "text": "Activation request options to further customize the request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/options"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit31UISceneSessionActivationRequestV7optionsSo0bdE7OptionsCSgvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIScene",
        "text": "UIScene"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
        "text": "ActivationRequestOptions"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "options"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIScene",
              "text": "UIScene"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
              "text": "ActivationRequestOptions"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene": {
      "abstract": [
        {
          "text": "An object that represents one instance of your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "role": "symbol",
      "title": "UIScene",
      "type": "topic",
      "url": "/documentation/uikit/uiscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating the session associated with a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiscene/activationrequestoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct": {
      "abstract": [
        {
          "text": "A collection of properties that you use to request activation of a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneSessionActivationRequest"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneSessionActivationRequest"
        }
      ],
      "role": "symbol",
      "title": "UISceneSessionActivationRequest",
      "type": "topic",
      "url": "/documentation/uikit/uiscenesessionactivationrequest-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/options": {
      "abstract": [
        {
          "text": "Activation request options to further customize the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
          "text": "ActivationRequestOptions"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/options",
      "kind": "symbol",
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/uikit/uiscenesessionactivationrequest-swift.struct/options"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/role": {
      "abstract": [
        {
          "text": "The role to request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "role"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UISceneSessionRole",
          "text": "Role"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/role",
      "kind": "symbol",
      "role": "symbol",
      "title": "role",
      "type": "topic",
      "url": "/documentation/uikit/uiscenesessionactivationrequest-swift.struct/role"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/session": {
      "abstract": [
        {
          "text": "The specific scene session to activate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/session",
      "kind": "symbol",
      "role": "symbol",
      "title": "session",
      "type": "topic",
      "url": "/documentation/uikit/uiscenesessionactivationrequest-swift.struct/session"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/userActivity": {
      "abstract": [
        {
          "text": "A user activity to send to the newly activated scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/userActivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "userActivity",
      "type": "topic",
      "url": "/documentation/uikit/uiscenesessionactivationrequest-swift.struct/useractivity"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions": {
      "abstract": [
        {
          "text": "An object that contains information you want the system to use when activating a new window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActivationRequestOptions"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.ActivationRequestOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/activationrequestoptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/ActivationRequestOptions"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Managing-request-details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/role",
        "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/session",
        "doc://com.apple.uikit/documentation/UIKit/UISceneSessionActivationRequest-swift.struct/userActivity"
      ],
      "title": "Managing request details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/title",
          "value": "UIWindowSceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/title",
          "value": "UIScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/title",
          "value": "UISceneActivationRequestOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationRequestOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneActivationRequestOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscenesessionactivationrequest-swift.struct/options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
