{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corewlan/documentation/CoreWLAN",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CWErr@kCWUnsupportedCapabilitiesErr",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cwUnsupportedCapabilitiesErr"
      }
    ],
    "modules": [
      {
        "name": "Core WLAN"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCWUnsupportedCapabilitiesErr"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CWErr.cwUnsupportedCapabilitiesErr"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cwUnsupportedCapabilitiesErr"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Access point cannot support all requested capabilities.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corewlan/documentation/CoreWLAN": {
      "abstract": [
        {
          "text": "Query AirPort interfaces and choose wireless networks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN",
      "kind": "symbol",
      "role": "collection",
      "title": "Core WLAN",
      "type": "topic",
      "url": "/documentation/corewlan"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwAssociationDeniedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAssociationDeniedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwAssociationDeniedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwassociationdeniederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwAuthenticationAlgorithmUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAuthenticationAlgorithmUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwAuthenticationAlgorithmUnsupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwauthenticationalgorithmunsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwChallengeFailureErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWChallengeFailureErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwChallengeFailureErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwchallengefailureerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwCipherSuiteRejectedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWCipherSuiteRejectedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwCipherSuiteRejectedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwciphersuiterejectederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidAKMPErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidAKMPErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidAKMPErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidakmperr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidAuthenticationSequenceNumberErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidAuthenticationSequenceNumberErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidAuthenticationSequenceNumberErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidauthenticationsequencenumbererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidFormatErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidFormatErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidFormatErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidformaterr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidGroupCipherErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidGroupCipherErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidGroupCipherErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidgroupciphererr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwInvalidInformationElementErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWInvalidInformationElementErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwInvalidInformationElementErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwinvalidinformationelementerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwUnsupportedCapabilitiesErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwUnsupportedCapabilitiesErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWUnsupportedCapabilitiesErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwUnsupportedCapabilitiesErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwunsupportedcapabilitieserr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwapFullErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWAPFullErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwapFullErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwapfullerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwdsssofdmUnsupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWDSSSOFDMUnsupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwdsssofdmUnsupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwdsssofdmunsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cweapolErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWEAPOLErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cweapolErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cweapolerr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwhtFeaturesNotSupportedErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWHTFeaturesNotSupportedErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwhtFeaturesNotSupportedErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwhtfeaturesnotsupportederr"
    },
    "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cwipcFailureErr"
        }
      ],
      "identifier": "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCWIPCFailureErr"
        }
      ],
      "role": "symbol",
      "title": "CWErr.cwipcFailureErr",
      "type": "topic",
      "url": "/documentation/corewlan/cwerr/cwipcfailureerr"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
        "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCWUnsupportedCapabilitiesErr"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnsupportedCapabilitiesErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corewlan/documentation/CoreWLAN",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwapFullErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAssociationDeniedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwAuthenticationAlgorithmUnsupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwChallengeFailureErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwCipherSuiteRejectedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwdsssofdmUnsupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cweapolErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwhtFeaturesNotSupportedErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwipcFailureErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAKMPErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidAuthenticationSequenceNumberErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidFormatErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidGroupCipherErr",
                "doc://com.apple.corewlan/documentation/CoreWLAN/CWErr/cwInvalidInformationElementErr"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCWUnsupportedCapabilitiesErr"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidInformationElementErr/title",
          "value": "kCWInvalidInformationElementErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidInformationElementErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidInformationElementErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwErr/title",
          "value": "kCWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/title",
          "value": "CWErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CWErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwChallengeFailureErr/title",
          "value": "kCWChallengeFailureErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwChallengeFailureErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWChallengeFailureErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedCapabilitiesErr/title",
          "value": "kCWUnsupportedCapabilitiesErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwUnsupportedCapabilitiesErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWUnsupportedCapabilitiesErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwhtFeaturesNotSupportedErr/title",
          "value": "kCWHTFeaturesNotSupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwhtFeaturesNotSupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWHTFeaturesNotSupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwapFullErr/title",
          "value": "kCWAPFullErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwapFullErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAPFullErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAuthenticationAlgorithmUnsupportedErr/title",
          "value": "kCWAuthenticationAlgorithmUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAuthenticationAlgorithmUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAuthenticationAlgorithmUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwCipherSuiteRejectedErr/title",
          "value": "kCWCipherSuiteRejectedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwCipherSuiteRejectedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWCipherSuiteRejectedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwdsssofdmUnsupportedErr/title",
          "value": "kCWDSSSOFDMUnsupportedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwdsssofdmUnsupportedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWDSSSOFDMUnsupportedErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAKMPErr/title",
          "value": "kCWInvalidAKMPErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAKMPErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidAKMPErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidGroupCipherErr/title",
          "value": "kCWInvalidGroupCipherErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidGroupCipherErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidGroupCipherErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAuthenticationSequenceNumberErr/title",
          "value": "kCWInvalidAuthenticationSequenceNumberErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidAuthenticationSequenceNumberErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidAuthenticationSequenceNumberErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwipcFailureErr/title",
          "value": "kCWIPCFailureErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwipcFailureErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWIPCFailureErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidFormatErr/title",
          "value": "kCWInvalidFormatErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwInvalidFormatErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWInvalidFormatErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cweapolErr/title",
          "value": "kCWEAPOLErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cweapolErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWEAPOLErr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAssociationDeniedErr/title",
          "value": "kCWAssociationDeniedErr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corewlan~1documentation~1CoreWLAN~1CWErr~1cwAssociationDeniedErr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCWAssociationDeniedErr"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corewlan/cwerr/cwunsupportedcapabilitieserr"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corewlan/cwerr/cwunsupportedcapabilitieserr"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
