{
  "abstract": [
    {
      "text": "The distances from the screen’s edges at which content isn’t obscured.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSScreen(py)safeAreaInsets",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "safeAreaInsets"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@NSEdgeInsets",
        "text": "NSEdgeInsets"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "safeAreaInsets"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "safeAreaInsets"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "safeAreaInsets"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@NSEdgeInsets",
              "text": "NSEdgeInsets"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The safe area reflects the unobscured portion of the screen. On some Macs, the insets reflect the portion of the screen covered by the camera housing. If your app offers a custom full-screen experience, apply the specified insets to the screen’s frame rectangle to obtain the area within which it is safe to display your content. Content in the safe area is guaranteed to be unobscured.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app uses the system’s full-screen experience, you don’t need to account for the safe area in your window. When you call your window’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to enter full-screen mode, the system automatically positions the window’s contents within the safe area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen": {
      "abstract": [
        {
          "text": "An object that describes the attributes of a computer’s monitor or screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "role": "symbol",
      "title": "NSScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc": {
      "abstract": [
        {
          "text": "The unobscured portion of the top-left corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliaryTopLeftArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopLeftArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytopleftarea-uglc"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n": {
      "abstract": [
        {
          "text": "The unobscured portion of the top-right corner of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auxiliaryTopRightArea"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n",
      "kind": "symbol",
      "role": "symbol",
      "title": "auxiliaryTopRightArea",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/auxiliarytoprightarea-gr2n"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets": {
      "abstract": [
        {
          "text": "The distances from the screen’s edges at which content isn’t obscured.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safeAreaInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSEdgeInsets",
          "text": "NSEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/safeAreaInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "safeAreaInsets"
        }
      ],
      "role": "symbol",
      "title": "safeAreaInsets",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/safeareainsets"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame": {
      "abstract": [
        {
          "text": "The current location and dimensions of the visible screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visibleFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "visibleFrame"
        }
      ],
      "role": "symbol",
      "title": "visibleFrame",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/visibleframe"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)": {
      "abstract": [
        {
          "text": "Takes the window into or out of fullscreen mode,",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleFullScreen"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWindow/toggleFullScreen(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toggleFullScreen:"
        }
      ],
      "role": "symbol",
      "title": "toggleFullScreen(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nswindow/togglefullscreen(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets": {
      "abstract": [
        {
          "text": "A description of the distance between the edges of two rectangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSEdgeInsets"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEdgeInsets",
      "type": "topic",
      "url": "/documentation/foundation/nsedgeinsets"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Visible-Portion-of-the-Screen",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopLeftArea-uglc",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/auxiliaryTopRightArea-gr2n"
      ],
      "title": "Getting the Visible Portion of the Screen"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "safeAreaInsets"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "safeAreaInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSScreen"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Visible-Portion-of-the-Screen",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSScreen/visibleFrame"
              ],
              "title": "Getting the Visible Portion of the Screen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@NSEdgeInsets",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@NSEdgeInsets",
                    "text": "NSEdgeInsets"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "safeAreaInsets"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1visibleFrame/title",
          "value": "visibleFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1visibleFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "visibleFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1safeAreaInsets/title",
          "value": "safeAreaInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1safeAreaInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "safeAreaInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/title",
          "value": "toggleFullScreen:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWindow~1toggleFullScreen(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toggleFullScreen:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/title",
          "value": "NSScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscreen/safeareainsets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsscreen/safeareainsets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
