{
  "abstract": [
    {
      "text": "Returns the scaling factor from user space to device space on the screen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSScreen(im)userSpaceScaleFactor",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "userSpaceScaleFactor"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "userSpaceScaleFactor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.7",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "userSpaceScaleFactor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "userSpaceScaleFactor"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The scaling factor, measured in pixels per point, where a point is always equal to 1/72 of an inch. For example, a scaling factor of ",
              "type": "text"
            },
            {
              "code": "2.0",
              "type": "codeVoice"
            },
            {
              "text": " indicates the display has a resolution 2 pixels per point or 144 pixels per inch.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey": {
      "abstract": [
        {
          "text": "These constants are the keys for device description dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeviceDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeviceDescriptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nsdevicedescriptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDisplayGamut"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDisplayGamut"
        }
      ],
      "role": "symbol",
      "title": "NSDisplayGamut",
      "type": "topic",
      "url": "/documentation/appkit/nsdisplaygamut"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen": {
      "abstract": [
        {
          "text": "An object that describes the attributes of a computer’s monitor or screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSScreen"
        }
      ],
      "role": "symbol",
      "title": "NSScreen",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor": {
      "abstract": [
        {
          "text": "The backing store pixel scale factor for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backingScaleFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backingScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "backingScaleFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/backingscalefactor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the color space of the screen is capable of representing the specified display gamut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canRepresent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSDisplayGamut",
          "text": "NSDisplayGamut"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canRepresentDisplayGamut:"
        }
      ],
      "role": "symbol",
      "title": "canRepresent(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/canrepresent(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace": {
      "abstract": [
        {
          "text": "The color space of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSColorSpace",
          "text": "NSColorSpace"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorSpace"
        }
      ],
      "role": "symbol",
      "title": "colorSpace",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/colorspace"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)": {
      "abstract": [
        {
          "text": "Converts the rectangle to the device pixel aligned coordinates system of a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "convertRectToBacking"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "convertRectToBacking:"
        }
      ],
      "role": "symbol",
      "title": "convertRectToBacking(_:)",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/convertrecttobacking(_:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth": {
      "abstract": [
        {
          "text": "The current bit depth and colorspace information of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "depth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowDepth",
          "text": "Depth"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "depth"
        }
      ],
      "role": "symbol",
      "title": "depth",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/depth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription": {
      "abstract": [
        {
          "text": "The device dictionary for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceDescription"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSDeviceDescriptionKey",
          "text": "NSDeviceDescriptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceDescription"
        }
      ],
      "role": "symbol",
      "title": "deviceDescription",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/devicedescription"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame": {
      "abstract": [
        {
          "text": "The dimensions and location of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frame"
        }
      ],
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/frame"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName": {
      "abstract": [
        {
          "text": "The localized name of the display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedName"
        }
      ],
      "role": "symbol",
      "title": "localizedName",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/localizedname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether each screen can have its own set of spaces.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screensHaveSeparateSpaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screensHaveSeparateSpaces"
        }
      ],
      "role": "symbol",
      "title": "screensHaveSeparateSpaces",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/screenshaveseparatespaces"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths": {
      "abstract": [
        {
          "text": "A zero-terminated array of the window depths supported by the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedWindowDepths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSWindow",
          "text": "NSWindow"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWindowDepth",
          "text": "Depth"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedWindowDepths"
        }
      ],
      "role": "symbol",
      "title": "supportedWindowDepths",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/supportedwindowdepths"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor": {
      "abstract": [
        {
          "text": "Returns the scaling factor from user space to device space on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSScreen/userSpaceScaleFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userSpaceScaleFactor"
        }
      ],
      "role": "symbol",
      "title": "userSpaceScaleFactor",
      "type": "topic",
      "url": "/documentation/appkit/nsscreen/userspacescalefactor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/convertRectToBacking(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/backingScaleFactor"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Getting-Screen-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/depth",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/frame",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/supportedWindowDepths",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/deviceDescription",
        "doc://com.apple.appkit/documentation/AppKit/NSDeviceDescriptionKey",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/colorSpace",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/localizedName",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/canRepresent(_:)",
        "doc://com.apple.appkit/documentation/AppKit/NSDisplayGamut",
        "doc://com.apple.appkit/documentation/AppKit/NSScreen/screensHaveSeparateSpaces"
      ],
      "title": "Getting Screen Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpace/title",
          "value": "colorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1colorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "colorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/title",
          "value": "NSDisplayGamut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDisplayGamut/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDisplayGamut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screensHaveSeparateSpaces/title",
          "value": "screensHaveSeparateSpaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1screensHaveSeparateSpaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screensHaveSeparateSpaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingScaleFactor/title",
          "value": "backingScaleFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1backingScaleFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backingScaleFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deviceDescription/title",
          "value": "deviceDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1deviceDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1supportedWindowDepths/title",
          "value": "supportedWindowDepths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1supportedWindowDepths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedWindowDepths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1canRepresent(_:)/title",
          "value": "canRepresentDisplayGamut:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1canRepresent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canRepresentDisplayGamut:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectToBacking(_:)/title",
          "value": "convertRectToBacking:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1convertRectToBacking(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "convertRectToBacking:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/title",
          "value": "NSScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1depth/title",
          "value": "depth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1depth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "depth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1localizedName/title",
          "value": "localizedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1localizedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1frame/title",
          "value": "frame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSScreen~1frame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/title",
          "value": "NSDeviceDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSDeviceDescriptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeviceDescriptionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsscreen/userspacescalefactor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
