{
  "abstract": [
    {
      "text": "The notification the system sends when a different user becomes current.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Manually mapping profiles is deprecated. To opt-in to the system’s automatic user-data management, add the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to your target, with a value of ",
          "type": "text"
        },
        {
          "code": "runs-as-current-user-with-user-independent-keychain",
          "type": "codeVoice"
        },
        {
          "text": ". For more information, see ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifierDidChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "TVServices",
    "externalID": "c:@TVUserManagerCurrentUserIdentifierDidChangeNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentUserIdentifierDidChangeNotification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNotification",
        "text": "NSNotification"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSNotificationName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "16.0",
        "introducedAt": "13.0",
        "message": "User Management capability get-current-user is no longer supported. Use the capability runs-as-current-user-with-user-independent-keychain, with it there is no need to be notified of user changes.",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "currentUserIdentifierDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentUserIdentifierDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNotification",
              "text": "NSNotification"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The object of the notification is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". The notification doesn’t add any keys to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/1409222-userinfo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " dictionary.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management": {
      "abstract": [
        {
          "text": "The entitlement for distinguishing between multiple user accounts on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management",
      "kind": "symbol",
      "role": "symbol",
      "title": "User Management Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.user-management"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/1409222-userinfo": {
      "abstract": [
        {
          "text": "The user information dictionary associated with the notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userInfo"
        },
        {
          "kind": "text",
          "text": ": [AnyHashable : Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/1409222-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInfo",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/1409222-userinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVAppProfileDescriptor": {
      "abstract": [
        {
          "text": "A model object that you use to represent an app-specific profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVAppProfileDescriptor"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVAppProfileDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVAppProfileDescriptor"
        }
      ],
      "role": "symbol",
      "title": "TVAppProfileDescriptor",
      "type": "topic",
      "url": "/documentation/tvservices/tvappprofiledescriptor"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserIdentifier": {
      "abstract": [
        {
          "text": "A unique string for differentiating between accounts on Apple TV.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVUserIdentifier"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVUserIdentifier"
        }
      ],
      "role": "symbol",
      "title": "TVUserIdentifier",
      "type": "topic",
      "url": "/documentation/tvservices/tvuseridentifier"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager": {
      "abstract": [
        {
          "text": "An object that indicates how to store preferences for multiple people on a shared device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "role": "symbol",
      "title": "TVUserManager",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier representing the currently active Apple TV user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentUserIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVUserIdentifier",
          "text": "TVUserIdentifier"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentUserIdentifier"
        }
      ],
      "role": "symbol",
      "title": "currentUserIdentifier",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/currentuseridentifier"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifierDidChangeNotification": {
      "abstract": [
        {
          "text": "The notification the system sends when a different user becomes current.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentUserIdentifierDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifierDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "currentUserIdentifierDidChangeNotification",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/currentuseridentifierdidchangenotification"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)": {
      "abstract": [
        {
          "text": "Presents a user-to-profile configuration panel, which lets the user specify their preferred profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentProfilePreferencePanel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "currentSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVUserIdentifier",
          "text": "TVUserIdentifier"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVAppProfileDescriptor",
          "text": "TVAppProfileDescriptor"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "availableProfiles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVAppProfileDescriptor",
          "text": "TVAppProfileDescriptor"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVUserIdentifier",
          "text": "TVUserIdentifier"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVAppProfileDescriptor",
          "text": "TVAppProfileDescriptor"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentProfilePreferencePanelWithCurrentSettings:availableProfiles:completion:"
        }
      ],
      "role": "symbol",
      "title": "presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/presentprofilepreferencepanel(currentsettings:availableprofiles:completion:)"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferenceForCurrentUser(to:completion:)": {
      "abstract": [
        {
          "text": "Prompts the user to save the specified profile as the preferred profile for the current user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldStorePreferenceForCurrentUser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)TVAppProfileDescriptor",
          "text": "TVAppProfileDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferenceForCurrentUser(to:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldStorePreferenceForCurrentUserToProfile:completion:"
        }
      ],
      "role": "symbol",
      "title": "shouldStorePreferenceForCurrentUser(to:completion:)",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/shouldstorepreferenceforcurrentuser(to:completion:)"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/userIdentifiersForCurrentProfile": {
      "abstract": [
        {
          "text": "An array of system user identifiers that you associated with the current app-specific profile.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIdentifiersForCurrentProfile"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@TVUserIdentifier",
          "text": "TVUserIdentifier"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/userIdentifiersForCurrentProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userIdentifiersForCurrentProfile"
        }
      ],
      "role": "symbol",
      "title": "userIdentifiersForCurrentProfile",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/useridentifiersforcurrentprofile"
    },
    "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles": {
      "abstract": [
        {
          "text": "Adapt the content of your app for the current viewer by using an entitlement and simplifying sign-in flows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
      "kind": "article",
      "role": "sampleCode",
      "title": "Mapping Apple TV users to app profiles",
      "type": "topic",
      "url": "/documentation/tvservices/mapping-apple-tv-users-to-app-profiles"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification": {
      "abstract": [
        {
          "text": "An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNotification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-symbols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifier",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferenceForCurrentUser(to:completion:)",
        "doc://com.apple.tvservices/documentation/TVServices/TVAppProfileDescriptor",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserIdentifier",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/userIdentifiersForCurrentProfile"
      ],
      "title": "Deprecated symbols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "16.0",
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-symbols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/currentUserIdentifier",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferenceForCurrentUser(to:completion:)",
                "doc://com.apple.tvservices/documentation/TVServices/TVAppProfileDescriptor",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserIdentifier",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/userIdentifiersForCurrentProfile"
              ],
              "title": "Deprecated symbols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSNotificationName",
                    "text": "NSNotificationName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Manually mapping profiles is deprecated. To opt-in to the system’s automatic user-data management, add the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to your target, with a value of ",
                  "type": "text"
                },
                {
                  "code": "runs-as-current-user-with-user-independent-keychain",
                  "type": "codeVoice"
                },
                {
                  "text": ". For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.tvservices/documentation/TVServices/mapping-apple-tv-users-to-app-profiles",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1currentUserIdentifierDidChangeNotification/title",
          "value": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1currentUserIdentifierDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManagerCurrentUserIdentifierDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract",
          "value": [
            {
              "text": "A container for information broadcast through a notification center to all registered observers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)/title",
          "value": "presentProfilePreferencePanelWithCurrentSettings:availableProfiles:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1presentProfilePreferencePanel(currentSettings:availableProfiles:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentProfilePreferencePanelWithCurrentSettings:availableProfiles:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/title",
          "value": "TVUserManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1userIdentifiersForCurrentProfile/title",
          "value": "userIdentifiersForCurrentProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1userIdentifiersForCurrentProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userIdentifiersForCurrentProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1currentUserIdentifier/title",
          "value": "currentUserIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1currentUserIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentUserIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1shouldStorePreferenceForCurrentUser(to:completion:)/title",
          "value": "shouldStorePreferenceForCurrentUserToProfile:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1shouldStorePreferenceForCurrentUser(to:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldStorePreferenceForCurrentUserToProfile:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserIdentifier/title",
          "value": "TVUserIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVAppProfileDescriptor/title",
          "value": "TVAppProfileDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVAppProfileDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVAppProfileDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVAppProfileDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVAppProfileDescriptor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvusermanager/currentuseridentifierdidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvusermanager/currentuseridentifierdidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
