{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether your app needs to retain a selected profile.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvservices/documentation/TVServices",
        "doc://com.apple.tvservices/documentation/TVServices/TVUserManager"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferencesForCurrentUser"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVUserManager(py)shouldStorePreferencesForCurrentUser",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "shouldStorePreferencesForCurrentUser"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "TV Services"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "shouldStorePreferencesForCurrentUser"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "shouldStorePreferencesForCurrentUser"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldStorePreferencesForCurrentUser"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To create a ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " object, add the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " to your app or app extension, and select the Runs as Current User, Only When User-Independent Keychain is Available option.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Some apps rely on profiles to maintain separate information for each person who uses a shared device, such as a video content app that retains which shows they watch. To avoid interrupting people with a profile picker each time they launch your app, you can save the current user’s selection on a shared device. After someone selects a profile, use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferencesForCurrentUser",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine whether to retain the profile selection or to prompt each time your app launches. This property might be ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if people share a device, but don’t configure multiple users on that device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the property’s value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", display the profile picker to determine which profile to use for the current session, but don’t save the selected profile. If the value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and there isn’t a saved profile in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", display the profile picker and save the selected profile for future use. If the value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and there’s already a saved profile, skip the prompt and use the saved profile.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When your app runs in tvOS 15 or earlier, where ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferencesForCurrentUser",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " isn’t available, display the profile picker at the beginning of each session.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management": {
      "abstract": [
        {
          "text": "The entitlement for distinguishing between multiple user accounts on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Entitlements/com.apple.developer.user-management",
      "kind": "symbol",
      "role": "symbol",
      "title": "User Management Entitlement",
      "type": "topic",
      "url": "/documentation/BundleResources/Entitlements/com.apple.developer.user-management"
    },
    "doc://com.apple.documentation/documentation/foundation/userdefaults": {
      "abstract": [
        {
          "text": "An interface to the user’s defaults database, where you store key-value pairs persistently across launches of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "UserDefaults"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/userdefaults",
      "kind": "symbol",
      "role": "symbol",
      "title": "UserDefaults",
      "type": "topic",
      "url": "/documentation/foundation/userdefaults"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvservices/documentation/TVServices": {
      "abstract": [
        {
          "text": "Display content and descriptions, provide channel guides, and support multiple users on Apple TV.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices",
      "kind": "symbol",
      "role": "collection",
      "title": "TV Services",
      "type": "topic",
      "url": "/documentation/tvservices"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager": {
      "abstract": [
        {
          "text": "An object that indicates how to store preferences for multiple people on a shared device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVUserManager"
        }
      ],
      "role": "symbol",
      "title": "TVUserManager",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager"
    },
    "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferencesForCurrentUser": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether your app needs to retain a selected profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldStorePreferencesForCurrentUser"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.tvservices/documentation/TVServices/TVUserManager/shouldStorePreferencesForCurrentUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldStorePreferencesForCurrentUser"
        }
      ],
      "role": "symbol",
      "title": "shouldStorePreferencesForCurrentUser",
      "type": "topic",
      "url": "/documentation/tvservices/tvusermanager/shouldstorepreferencesforcurrentuser"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "shouldStorePreferencesForCurrentUser"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldStorePreferencesForCurrentUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.tvservices/documentation/TVServices",
                "doc://com.apple.tvservices/documentation/TVServices/TVUserManager"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shouldStorePreferencesForCurrentUser"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1shouldStorePreferencesForCurrentUser/title",
          "value": "shouldStorePreferencesForCurrentUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager~1shouldStorePreferencesForCurrentUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldStorePreferencesForCurrentUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1userdefaults/title",
          "value": "NSUserDefaults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/title",
          "value": "TVUserManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvservices~1documentation~1TVServices~1TVUserManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVUserManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvservices/tvusermanager/shouldstorepreferencesforcurrentuser"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/tvservices/tvusermanager/shouldstorepreferencesforcurrentuser"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
