{
  "abstract": [
    {
      "text": "An unknown type of call.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/unknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INCallRecordType@INCallRecordTypeUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknown"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INCallRecordTypeUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INCallRecordType.unknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType": {
      "abstract": [
        {
          "text": "Constants describing the type of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/inProgress": {
      "abstract": [
        {
          "text": "A received call that is currently in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.inProgress",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/latest": {
      "abstract": [
        {
          "text": "The most recent call involving the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "latest"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/latest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeLatest"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.latest",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/latest"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/missed": {
      "abstract": [
        {
          "text": "A received call that the user did not answer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missed"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/missed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeMissed"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.missed",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/missed"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/onHold": {
      "abstract": [
        {
          "text": "A received call that the user has put on hold.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "onHold"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/onHold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeOnHold"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.onHold",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/onhold"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/outgoing": {
      "abstract": [
        {
          "text": "A call initiated by the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outgoing"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/outgoing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeOutgoing"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.outgoing",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/outgoing"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/received": {
      "abstract": [
        {
          "text": "A received call that the user answered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "received"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/received",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeReceived"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.received",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/received"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/ringing": {
      "abstract": [
        {
          "text": "An incoming call that is currently causing the user’s phone to ring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ringing"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/ringing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeRinging"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.ringing",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/ringing"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/unknown": {
      "abstract": [
        {
          "text": "An unknown type of call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeUnknown"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.unknown",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/unknown"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/voicemail": {
      "abstract": [
        {
          "text": "A voicemail left from a missed call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voicemail"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/voicemail",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordTypeVoicemail"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType.voicemail",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype/voicemail"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/outgoing",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/missed",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/received",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/latest",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/voicemail",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/onHold",
        "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/ringing"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INCallRecordTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/outgoing",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/missed",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/received",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/latest",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/voicemail",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/onHold",
                "doc://com.apple.sirikit/documentation/Intents/INCallRecordType/ringing"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INCallRecordTypeUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1received/title",
          "value": "INCallRecordTypeReceived"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1received/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeReceived"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1unknown/title",
          "value": "INCallRecordTypeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1outgoing/title",
          "value": "INCallRecordTypeOutgoing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1outgoing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeOutgoing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1inProgress/title",
          "value": "INCallRecordTypeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeInProgress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1voicemail/title",
          "value": "INCallRecordTypeVoicemail"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1voicemail/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeVoicemail"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1ringing/title",
          "value": "INCallRecordTypeRinging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1ringing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeRinging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/title",
          "value": "INCallRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1onHold/title",
          "value": "INCallRecordTypeOnHold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1onHold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeOnHold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1latest/title",
          "value": "INCallRecordTypeLatest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1latest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeLatest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1missed/title",
          "value": "INCallRecordTypeMissed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType~1missed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordTypeMissed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/incallrecordtype/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/incallrecordtype/unknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
