{
  "abstract": [
    {
      "text": "Adds a symbol effect to the bar button item with the specified options and animation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIBarButtonItem(im)addSymbolEffect:options:animated:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "addSymbolEffect:options:animated:"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "addSymbolEffect:options:animated:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "addSymbolEffect:options:animated:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "addSymbolEffect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolEffect",
              "text": "NSSymbolEffect"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "symbolEffect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "options:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSSymbolEffectOptions",
              "text": "NSSymbolEffectOptions"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "animated:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "animated"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The symbol effect to add.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "symbolEffect"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options for the symbol effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Boolean value that indicates whether to animate the addition of a scale, appear, or disappear effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "animated"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with default options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with the specified options and default animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether symbol effects animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSymbolAnimationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolAnimationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSymbolAnimationEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/issymbolanimationenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffects",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffects"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffectswithoptions:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffectswithoptions:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage:withcontenttransition:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage:withcontenttransition:options:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect": {
      "abstract": [
        {
          "text": "An abstract base class for effects that you can apply to a symbol-based image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolEffect"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolEffect"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions": {
      "abstract": [
        {
          "text": "Options that configure how effects apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "@interface"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSObject",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSSymbolEffectOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSymbolEffectOptions",
      "type": "topic",
      "url": "/documentation/Symbols/NSSymbolEffectOptions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/title",
          "value": "symbolAnimationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolAnimationEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/addsymboleffect:options:animated:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
