{"variants":[{"paths":["/documentation/uikit/uibarbuttonitem/backbuttonbackgroundimage(for:barmetrics:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uibarbuttonitem/backbuttonbackgroundimage(for:barmetrics:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Customizing-the-Back-button","title":"Customizing the Back button","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundImage(_:for:barMetrics:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonTitlePositionAdjustment(for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonTitlePositionAdjustment(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundVerticalPositionAdjustment(for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundVerticalPositionAdjustment(_:for:)"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundImage(for:barMetrics:)"},"abstract":[{"text":"Returns the back button background image for a specified control state and bar metrics.","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backButtonBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"backButtonBackgroundImageForState:barMetrics:","kind":"identifier"}],"modules":[{"name":"UIKit"}],"title":"backButtonBackgroundImage(for:barMetrics:)","roleHeading":"Instance Method","platforms":[{"introducedAt":"5.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"5.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false,"beta":false}],"role":"symbol","externalID":"c:objc(cs)UIBarButtonItem(im)backButtonBackgroundImageForState:barMetrics:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backButtonBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","preciseIdentifier":"c:objc(cs)UIControl","text":"UIControl","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","preciseIdentifier":"c:@E@UIControlState","text":"State","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"state","content":[{"type":"paragraph","inlineContent":[{"text":"A control state.","type":"text"}]}]},{"name":"barMetrics","content":[{"type":"paragraph","inlineContent":[{"text":"Bar metrics.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The back button background image for "},{"code":"state","type":"codeVoice"},{"type":"text","text":" and "},{"code":"barMetrics","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"},{"content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"This modifier applies only to navigation bar back buttons and is ignored by other buttons."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIControl":{"navigatorTitle":[{"text":"UIControl","kind":"identifier"}],"title":"UIControl","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIControl","kind":"identifier"}],"abstract":[{"type":"text","text":"The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions."}],"url":"/documentation/uikit/uicontrol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIBarButtonItem"}],"abstract":[{"type":"text","text":"A specialized button for placement on a toolbar, navigation bar, or shortcuts bar."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem","role":"symbol","url":"/documentation/uikit/uibarbuttonitem","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIBarButtonItem"}],"type":"topic","title":"UIBarButtonItem"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundVerticalPositionAdjustment(for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backButtonBackgroundVerticalPositionAdjustment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","role":"symbol","title":"backButtonBackgroundVerticalPositionAdjustment(for:)","abstract":[{"type":"text","text":"Returns the back button vertical position offset for specified bar metrics."}],"type":"topic","url":"/documentation/uikit/uibarbuttonitem/backbuttonbackgroundverticalpositionadjustment(for:)","navigatorTitle":[{"text":"backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundVerticalPositionAdjustment(for:)"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundImage(for:barMetrics:)":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundImage(for:barMetrics:)","title":"backButtonBackgroundImage(for:barMetrics:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"backButtonBackgroundImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIControl","preciseIdentifier":"c:objc(cs)UIControl"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"State","preciseIdentifier":"c:@E@UIControlState"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barMetrics"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"backButtonBackgroundImageForState:barMetrics:"}],"type":"topic","url":"/documentation/uikit/uibarbuttonitem/backbuttonbackgroundimage(for:barmetrics:)","abstract":[{"text":"Returns the back button background image for a specified control state and bar metrics.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonTitlePositionAdjustment(_:for:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBackButtonTitlePositionAdjustment"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@UIOffset","kind":"typeIdentifier","text":"UIOffset"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"UIBarMetrics","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"setBackButtonTitlePositionAdjustment(_:for:)","abstract":[{"type":"text","text":"Sets the back button title offset for specified bar metrics."}],"type":"topic","url":"/documentation/uikit/uibarbuttonitem/setbackbuttontitlepositionadjustment(_:for:)","navigatorTitle":[{"text":"setBackButtonTitlePositionAdjustment:forBarMetrics:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonTitlePositionAdjustment(_:for:)"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundImage(_:for:barMetrics:)":{"navigatorTitle":[{"text":"setBackButtonBackgroundImage:forState:barMetrics:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Sets the back button background image for a specified control state and bar metrics.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackButtonBackgroundImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIControl","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIControl"},{"text":".","kind":"text"},{"text":"State","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIControlState"},{"text":", ","kind":"text"},{"text":"barMetrics","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarMetrics","text":"UIBarMetrics"},{"kind":"text","text":")"}],"title":"setBackButtonBackgroundImage(_:for:barMetrics:)","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundImage(_:for:barMetrics:)","url":"/documentation/uikit/uibarbuttonitem/setbackbuttonbackgroundimage(_:for:barmetrics:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics":{"navigatorTitle":[{"text":"UIBarMetrics","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIBarMetrics","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uibarmetrics","title":"UIBarMetrics","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Constants to specify metrics to use for appearance."}]},"doc://com.apple.uikit/documentation/UIKit/UIImage":{"kind":"symbol","role":"symbol","title":"UIImage","navigatorTitle":[{"text":"UIImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIImage","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","url":"/documentation/uikit/uiimage","abstract":[{"type":"text","text":"An object that manages image data in your app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonTitlePositionAdjustment(for:)":{"abstract":[{"text":"Returns the back button title offset for specified bar metrics.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonTitlePositionAdjustment(for:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backButtonTitlePositionAdjustment","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@UIOffset","kind":"typeIdentifier","text":"UIOffset"}],"title":"backButtonTitlePositionAdjustment(for:)","navigatorTitle":[{"text":"backButtonTitlePositionAdjustmentForBarMetrics:","kind":"identifier"}],"url":"/documentation/uikit/uibarbuttonitem/backbuttontitlepositionadjustment(for:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundVerticalPositionAdjustment(_:for:)":{"abstract":[{"text":"Sets the back button vertical position offset for specified bar metrics.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundVerticalPositionAdjustment(_:for:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setBackButtonBackgroundVerticalPositionAdjustment","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarMetrics","kind":"typeIdentifier","text":"UIBarMetrics"},{"kind":"text","text":")"}],"title":"setBackButtonBackgroundVerticalPositionAdjustment(_:for:)","navigatorTitle":[{"text":"setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:","kind":"identifier"}],"url":"/documentation/uikit/uibarbuttonitem/setbackbuttonbackgroundverticalpositionadjustment(_:for:)","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"State"}],"title":"UIControl.State","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"State"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","role":"symbol","type":"topic","url":"/documentation/uikit/uicontrol/state-swift.struct","abstract":[{"type":"text","text":"Constants describing the state of a control."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"introducedAt":"5.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"5.0","name":"iPadOS","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"backButtonBackgroundImageForState:barMetrics:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backButtonBackgroundImageForState:barMetrics:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Customizing the Back button","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundImage(_:for:barMetrics:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonTitlePositionAdjustment(for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonTitlePositionAdjustment(_:for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/backButtonBackgroundVerticalPositionAdjustment(for:)","doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setBackButtonBackgroundVerticalPositionAdjustment(_:for:)"],"generated":true,"anchor":"Customizing-the-Back-button"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"backButtonBackgroundImageForState:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIControlState","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIControl/State-swift.struct","preciseIdentifier":"c:@E@UIControlState"},{"text":") ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barMetrics:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIBarMetrics","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIBarMetrics","preciseIdentifier":"c:@E@UIBarMetrics"},{"text":") ","kind":"text"},{"text":"barMetrics","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"A control state."}],"type":"paragraph"}],"name":"state"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bar metrics."}]}],"name":"barMetrics"}],"kind":"parameters"}},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The back button background image for "},{"code":"state","type":"codeVoice"},{"type":"text","text":" and "},{"code":"barMetrics","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title","op":"replace","value":"UIControl"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments","op":"replace","value":[{"text":"UIControl","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIControl"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title","op":"replace","value":"UIBarButtonItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments","op":"replace","value":[{"kind":"identifier","text":"UIBarButtonItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIBarButtonItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonBackgroundVerticalPositionAdjustment(for:)/title","op":"replace","value":"backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonBackgroundVerticalPositionAdjustment(for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonBackgroundImage(for:barMetrics:)/title","op":"replace","value":"backButtonBackgroundImageForState:barMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonBackgroundImage(for:barMetrics:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"backButtonBackgroundImageForState:barMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonTitlePositionAdjustment(_:for:)/title","op":"replace","value":"setBackButtonTitlePositionAdjustment:forBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonTitlePositionAdjustment(_:for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBackButtonTitlePositionAdjustment:forBarMetrics:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonBackgroundImage(_:for:barMetrics:)/title","op":"replace","value":"setBackButtonBackgroundImage:forState:barMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonBackgroundImage(_:for:barMetrics:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBackButtonBackgroundImage:forState:barMetrics:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/title","op":"replace","value":"UIBarMetrics"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/fragments","op":"replace","value":[{"text":"UIBarMetrics","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarMetrics/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIBarMetrics"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title","op":"replace","value":"UIImage"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments","op":"replace","value":[{"kind":"identifier","text":"UIImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIImage"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonTitlePositionAdjustment(for:)/title","op":"replace","value":"backButtonTitlePositionAdjustmentForBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1backButtonTitlePositionAdjustment(for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"backButtonTitlePositionAdjustmentForBarMetrics:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonBackgroundVerticalPositionAdjustment(_:for:)/title","op":"replace","value":"setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1setBackButtonBackgroundVerticalPositionAdjustment(_:for:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setBackButtonBackgroundVerticalPositionAdjustment:forBarMetrics:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/title","op":"replace","value":"UIControlState"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/fragments","op":"replace","value":[{"text":"UIControlState","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1State-swift.struct/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIControlState"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}