{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether symbol effects animate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIBarButtonItem(py)symbolAnimationEnabled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isSymbolAnimationEnabled"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "symbolAnimationEnabled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "isSymbolAnimationEnabled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isSymbolAnimationEnabled"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0": {
      "abstract": [
        {
          "text": "Adds an indefinite symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-3iew0"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e": {
      "abstract": [
        {
          "text": "Adds a discrete, indefinite symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-6jx3e"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr": {
      "abstract": [
        {
          "text": "Adds a discrete symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-9dytr"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with default options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with the specified options and default animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:": {
      "abstract": [
        {
          "text": "Adds a symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addSymbolEffect:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "addSymbolEffect:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether symbol effects animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSymbolAnimationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolAnimationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSymbolAnimationEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/issymbolanimationenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffects",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffects"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeAllSymbolEffects(options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffects(options:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffectswithoptions:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffectsWithOptions:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeAllSymbolEffectsWithOptions:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffectswithoptions:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-214pl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete, indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-7m567"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-8zc4d"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:options:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeSymbolEffectOfType:options:animated:"
        }
      ],
      "role": "symbol",
      "title": "removeSymbolEffectOfType:options:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffectoftype:options:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols29ContentTransitionSymbolEffectP",
          "text": "ContentTransitionSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setSymbolImage(_:contentTransition:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage(_:contenttransition:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage:withcontenttransition:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSymbolImage:withContentTransition:options:"
        }
      ],
      "role": "symbol",
      "title": "setSymbolImage:withContentTransition:options:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage:withcontenttransition:options:"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "symbolAnimationEnabled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolAnimationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-symbol-effects",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect:options:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage:withContentTransition:options:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffectOfType:options:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffectsWithOptions:animated:"
              ],
              "title": "Configuring symbol effects"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "getter"
                  },
                  {
                    "kind": "text",
                    "text": "="
                  },
                  {
                    "kind": "identifier",
                    "text": "isSymbolAnimationEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "symbolAnimationEnabled"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/title",
          "value": "symbolAnimationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolAnimationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/issymbolanimationenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/issymbolanimationenabled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
