{
  "abstract": [
    {
      "text": "Sets a symbol image using the specified content-transition effect and options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "s:So15UIBarButtonItemC5UIKitE14setSymbolImage_17contentTransition7optionsySo7UIImageC_x7Symbols0F13EffectOptionsVtAI07ContentifM0RzAI0fM0RzlF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setSymbolImage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIImage",
        "text": "UIImage"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "contentTransition"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "keyword",
        "text": "some"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols29ContentTransitionSymbolEffectP",
        "text": "ContentTransitionSymbolEffect"
      },
      {
        "kind": "text",
        "text": " & "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols12SymbolEffectP",
        "text": "SymbolEffect"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "options"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
        "text": "SymbolEffectOptions"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setSymbolImage(_:contentTransition:options:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setSymbolImage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "image"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIImage",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "contentTransition"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "some"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols29ContentTransitionSymbolEffectP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols29ContentTransitionSymbolEffectP",
              "text": "ContentTransitionSymbolEffect"
            },
            {
              "kind": "text",
              "text": " & "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols12SymbolEffectP",
              "text": "SymbolEffect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
              "text": "SymbolEffectOptions"
            },
            {
              "kind": "text",
              "text": " = .default)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The symbol image to set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "image"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The content transition to use when setting the symbol image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "contentTransition"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options to use when setting the symbol image.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0": {
      "abstract": [
        {
          "text": "Adds an indefinite symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-3iew0"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e": {
      "abstract": [
        {
          "text": "Adds a discrete, indefinite symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-6jx3e"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr": {
      "abstract": [
        {
          "text": "Adds a discrete symbol effect to the bar button item with the specified options and animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr",
      "kind": "symbol",
      "role": "symbol",
      "title": "addSymbolEffect(_:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/addsymboleffect(_:options:animated:)-9dytr"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether symbol effects animate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSymbolAnimationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolAnimationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSymbolAnimationEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/issymbolanimationenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)": {
      "abstract": [
        {
          "text": "Removes all symbol effects from the bar button item, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAllSymbolEffects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeAllSymbolEffects(options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removeallsymboleffects(options:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-214pl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete, indefinite effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols22IndefiniteSymbolEffectP",
          "text": "IndefiniteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-7m567"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d": {
      "abstract": [
        {
          "text": "Removes the symbol effect that matches the specified discrete effect type, using the specified options and animation setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeSymbolEffect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols20DiscreteSymbolEffectP",
          "text": "DiscreteSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d",
      "kind": "symbol",
      "role": "symbol",
      "title": "removeSymbolEffect(ofType:options:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/removesymboleffect(oftype:options:animated:)-8zc4d"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)": {
      "abstract": [
        {
          "text": "Sets a symbol image using the specified content-transition effect and options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setSymbolImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentTransition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols29ContentTransitionSymbolEffectP",
          "text": "ContentTransitionSymbolEffect"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols12SymbolEffectP",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Symbols19SymbolEffectOptionsV",
          "text": "SymbolEffectOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/setSymbolImage(_:contentTransition:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setSymbolImage(_:contentTransition:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/setsymbolimage(_:contenttransition:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP": {
      "abstract": [
        {
          "text": "A presentation effect that you apply to a symbol-based image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolEffect"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols12SymbolEffectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/SymbolEffect"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV": {
      "abstract": [
        {
          "text": "Options that configure how effects apply to symbol-based images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolEffectOptions"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols19SymbolEffectOptionsV",
      "kind": "symbol",
      "role": "symbol",
      "title": "SymbolEffectOptions",
      "type": "topic",
      "url": "/documentation/Symbols/SymbolEffectOptions"
    },
    "doc://com.externally.resolved.symbol/s:7Symbols29ContentTransitionSymbolEffectP": {
      "abstract": [
        {
          "text": "An effect that animates between symbols or different configurations of the same symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentTransitionSymbolEffect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Symbols29ContentTransitionSymbolEffectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ContentTransitionSymbolEffect",
      "type": "topic",
      "url": "/documentation/Symbols/ContentTransitionSymbolEffect"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-symbol-effects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/isSymbolAnimationEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-3iew0",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-6jx3e",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/addSymbolEffect(_:options:animated:)-9dytr",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-214pl",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-7m567",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeSymbolEffect(ofType:options:animated:)-8zc4d",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/removeAllSymbolEffects(options:animated:)"
      ],
      "title": "Configuring symbol effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/title",
          "value": "symbolAnimationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1isSymbolAnimationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolAnimationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/setsymbolimage(_:contenttransition:options:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
