{
  "abstract": [
    {
      "text": "Constants that define system-supplied images for bar button items.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "UIKit",
    "externalID": "c:@E@UIBarButtonSystemItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "SystemItem"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SystemItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIBarButtonItem.SystemItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SystemItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem": {
      "abstract": [
        {
          "text": "Constants that define system-supplied images for bar button items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action": {
      "abstract": [
        {
          "text": "The system action button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "action"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemAction"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.action",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/action"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add": {
      "abstract": [
        {
          "text": "The system plus button containing an icon of a plus sign.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemAdd"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.add",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/add"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks": {
      "abstract": [
        {
          "text": "The system bookmarks button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bookmarks"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemBookmarks"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.bookmarks",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/bookmarks"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera": {
      "abstract": [
        {
          "text": "The system camera button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "camera"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCamera"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.camera",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/camera"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel": {
      "abstract": [
        {
          "text": "The system Cancel button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCancel"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.cancel",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/cancel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/close": {
      "abstract": [
        {
          "text": "The system close button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "close"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/close",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemClose"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.close",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/close"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose": {
      "abstract": [
        {
          "text": "The system compose button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemCompose"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.compose",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/compose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done": {
      "abstract": [
        {
          "text": "The system Done button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "done"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemDone"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.done",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/done"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit": {
      "abstract": [
        {
          "text": "The system Edit button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edit"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemEdit"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.edit",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/edit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fastForward": {
      "abstract": [
        {
          "text": "The system fast forward button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fastForward"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fastForward",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemFastForward"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.fastForward",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/fastforward"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace": {
      "abstract": [
        {
          "text": "Blank space to add between other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemFixedSpace"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.fixedSpace",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/fixedspace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace": {
      "abstract": [
        {
          "text": "Blank space to add between other items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flexibleSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemFlexibleSpace"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.flexibleSpace",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/flexiblespace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize": {
      "abstract": [
        {
          "text": "The system organize button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "organize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemOrganize"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.organize",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/organize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pageCurl": {
      "abstract": [
        {
          "text": "The system page curl button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCurl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pageCurl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemPageCurl"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.pageCurl",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/pagecurl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pause": {
      "abstract": [
        {
          "text": "The system pause button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pause",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemPause"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.pause",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/pause"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/play": {
      "abstract": [
        {
          "text": "The system play button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/play",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemPlay"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.play",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/play"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/redo": {
      "abstract": [
        {
          "text": "The system redo button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "redo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/redo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemRedo"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.redo",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/redo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh": {
      "abstract": [
        {
          "text": "The system refresh button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refresh"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemRefresh"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.refresh",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/refresh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply": {
      "abstract": [
        {
          "text": "The system reply button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reply"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemReply"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.reply",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/reply"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/rewind": {
      "abstract": [
        {
          "text": "The system rewind button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rewind"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/rewind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemRewind"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.rewind",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/rewind"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save": {
      "abstract": [
        {
          "text": "The system Save button, localized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemSave"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.save",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/save"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search": {
      "abstract": [
        {
          "text": "The system search button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemSearch"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.search",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop": {
      "abstract": [
        {
          "text": "The system stop button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stop"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemStop"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.stop",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/stop"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/trash": {
      "abstract": [
        {
          "text": "The system trash button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trash"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/trash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemTrash"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.trash",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/trash"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/undo": {
      "abstract": [
        {
          "text": "The system undo button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/undo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemUndo"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.undo",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/undo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/writingTools": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writingTools"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/writingTools",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonSystemItemWritingTools"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem.SystemItem.writingTools",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/systemitem/writingtools"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(barButtonSystemItem:target:action:)": {
      "abstract": [
        {
          "text": "Creates an item using the specified system item, target, and action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "barButtonSystemItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarButtonSystemItem",
          "text": "SystemItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(barButtonSystemItem:target:action:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:target:action:"
        }
      ],
      "role": "symbol",
      "title": "init(barButtonSystemItem:target:action:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/init(barbuttonsystemitem:target:action:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(systemItem:primaryAction:menu:)": {
      "abstract": [
        {
          "text": "Creates an item using the specified system item, primary action, and context menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "systemItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarButtonSystemItem",
          "text": "SystemItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "menu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(systemItem:primaryAction:menu:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(systemItem:primaryAction:menu:)",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/init(systemitem:primaryaction:menu:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:menu:": {
      "abstract": [
        {
          "text": "Creates an item using the specified system item and context menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:menu:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:menu:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:menu:"
        }
      ],
      "role": "symbol",
      "title": "initWithBarButtonSystemItem:menu:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/initwithbarbuttonsystemitem:menu:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:": {
      "abstract": [
        {
          "text": "Creates an item using the specified system item and primary action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:primaryAction:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:primaryAction:"
        }
      ],
      "role": "symbol",
      "title": "initWithBarButtonSystemItem:primaryAction:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/initwithbarbuttonsystemitem:primaryaction:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:menu:": {
      "abstract": [
        {
          "text": "Creates an item using the specified system item, primary action, and context menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:primaryAction:menu:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:menu:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBarButtonSystemItem:primaryAction:menu:"
        }
      ],
      "role": "symbol",
      "title": "initWithBarButtonSystemItem:primaryAction:menu:",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/initwithbarbuttonsystemitem:primaryaction:menu:"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-system-items",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(systemItem:primaryAction:menu:)",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(barButtonSystemItem:target:action:)"
      ],
      "title": "Creating system items"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/trash",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/play",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pause",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/rewind",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fastForward",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/undo",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/redo",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pageCurl",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/close"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/writingTools"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIBarButtonSystemItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/done",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/cancel",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/edit",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/save",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/add",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/flexibleSpace",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fixedSpace",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/compose",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/reply",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/action",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/organize",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/bookmarks",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/search",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/refresh",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/stop",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/camera",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/trash",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/play",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pause",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/rewind",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/fastForward",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/undo",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/redo",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/pageCurl",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/close"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/SystemItem/writingTools"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-system-items",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:menu:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:primaryAction:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/initWithBarButtonSystemItem:menu:",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/init(barButtonSystemItem:target:action:)"
              ],
              "title": "Creating system items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIBarButtonSystemItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1action/title",
          "value": "UIBarButtonSystemItemAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1action/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1search/title",
          "value": "UIBarButtonSystemItemSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1done/title",
          "value": "UIBarButtonSystemItemDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1done/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/title",
          "value": "UIBarButtonSystemItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1init(barButtonSystemItem:target:action:)/title",
          "value": "initWithBarButtonSystemItem:target:action:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1init(barButtonSystemItem:target:action:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBarButtonSystemItem:target:action:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1add/title",
          "value": "UIBarButtonSystemItemAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1organize/title",
          "value": "UIBarButtonSystemItemOrganize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1organize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemOrganize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1cancel/title",
          "value": "UIBarButtonSystemItemCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1edit/title",
          "value": "UIBarButtonSystemItemEdit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1edit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemEdit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1reply/title",
          "value": "UIBarButtonSystemItemReply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1reply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemReply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1close/title",
          "value": "UIBarButtonSystemItemClose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1close/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemClose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1stop/title",
          "value": "UIBarButtonSystemItemStop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1stop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemStop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1camera/title",
          "value": "UIBarButtonSystemItemCamera"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1camera/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCamera"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1refresh/title",
          "value": "UIBarButtonSystemItemRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1refresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fixedSpace/title",
          "value": "UIBarButtonSystemItemFixedSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fixedSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemFixedSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1undo/title",
          "value": "UIBarButtonSystemItemUndo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1undo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemUndo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1save/title",
          "value": "UIBarButtonSystemItemSave"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1save/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemSave"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1writingTools/title",
          "value": "UIBarButtonSystemItemWritingTools"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1writingTools/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemWritingTools"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1play/title",
          "value": "UIBarButtonSystemItemPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1play/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1bookmarks/title",
          "value": "UIBarButtonSystemItemBookmarks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1bookmarks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemBookmarks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1redo/title",
          "value": "UIBarButtonSystemItemRedo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1redo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemRedo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1pause/title",
          "value": "UIBarButtonSystemItemPause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1pause/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemPause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1flexibleSpace/title",
          "value": "UIBarButtonSystemItemFlexibleSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1flexibleSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemFlexibleSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1compose/title",
          "value": "UIBarButtonSystemItemCompose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1compose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemCompose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fastForward/title",
          "value": "UIBarButtonSystemItemFastForward"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1fastForward/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemFastForward"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1trash/title",
          "value": "UIBarButtonSystemItemTrash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1trash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemTrash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1pageCurl/title",
          "value": "UIBarButtonSystemItemPageCurl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1pageCurl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemPageCurl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1rewind/title",
          "value": "UIBarButtonSystemItemRewind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1SystemItem~1rewind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonSystemItemRewind"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/systemitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibarbuttonitem/systemitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
