{
  "abstract": [
    {
      "text": "The minimum region entirely enclosing the mesh’s vertex positions, expressed in the model coordinate system of the mesh.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/boundingBox"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLMesh(py)boundingBox",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "boundingBox"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
        "text": "MDLAxisAlignedBoundingBox"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "boundingBox"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "boundingBox"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "boundingBox"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
              "text": "MDLAxisAlignedBoundingBox"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property’s value is valid only if the mesh contains vertex data for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attribute. If the mesh does not contain position information, this property’s value is a bounding box whose ",
              "type": "text"
            },
            {
              "code": "maxBounds",
              "type": "codeVoice"
            },
            {
              "text": " coordinate is greater than its ",
              "type": "text"
            },
            {
              "code": "minBounds",
              "type": "codeVoice"
            },
            {
              "text": " coordinate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Reading this property for the first time processes the mesh’s vertex data to calculate and cache a bounding box. Reading this property thereafter returns the cached value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox": {
      "abstract": [
        {
          "text": "The minimal volume containing an object, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLAxisAlignedBoundingBox"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLAxisAlignedBoundingBox"
        }
      ],
      "role": "symbol",
      "title": "MDLAxisAlignedBoundingBox",
      "type": "topic",
      "url": "/documentation/modelio/mdlaxisalignedboundingbox"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:)": {
      "abstract": [
        {
          "text": "Adds a vertex attribute to the mesh and creates a new, empty corresponding vertex buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAttributeWithName:format:"
        }
      ],
      "role": "symbol",
      "title": "addAttribute(withName:format:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/addattribute(withname:format:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAttributeWithName:format:type:data:stride:"
        }
      ],
      "role": "symbol",
      "title": "addAttribute(withName:format:type:data:stride:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/addattribute(withname:format:type:data:stride:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:time:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:time:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addAttributeWithName:format:type:data:stride:time:"
        }
      ],
      "role": "symbol",
      "title": "addAttribute(withName:format:type:data:stride:time:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/addattribute(withname:format:type:data:stride:time:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addUnwrappedTextureCoordinates(forAttributeNamed:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addUnwrappedTextureCoordinates"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAttributeNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addUnwrappedTextureCoordinates(forAttributeNamed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addUnwrappedTextureCoordinatesForAttributeNamed:"
        }
      ],
      "role": "symbol",
      "title": "addUnwrappedTextureCoordinates(forAttributeNamed:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/addunwrappedtexturecoordinates(forattributenamed:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/allocator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allocator"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBufferAllocator",
          "text": "MDLMeshBufferAllocator"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/allocator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allocator"
        }
      ],
      "role": "symbol",
      "title": "allocator",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/allocator"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/boundingBox": {
      "abstract": [
        {
          "text": "The minimum region entirely enclosing the mesh’s vertex positions, expressed in the model coordinate system of the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
          "text": "MDLAxisAlignedBoundingBox"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/boundingBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundingBox"
        }
      ],
      "role": "symbol",
      "title": "boundingBox",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/boundingbox"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/removeAttributeNamed(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeAttributeNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/removeAttributeNamed(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeAttributeNamed:"
        }
      ],
      "role": "symbol",
      "title": "removeAttributeNamed(_:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/removeattributenamed(_:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/replaceAttributeNamed(_:with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAttributeNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexAttributeData",
          "text": "MDLVertexAttributeData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/replaceAttributeNamed(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceAttributeNamed:withData:"
        }
      ],
      "role": "symbol",
      "title": "replaceAttributeNamed(_:with:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/replaceattributenamed(_:with:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/submeshes": {
      "abstract": [
        {
          "text": "The array of submeshes to be used in rendering the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "submeshes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableArray",
          "text": "NSMutableArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/submeshes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "submeshes"
        }
      ],
      "role": "symbol",
      "title": "submeshes",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/submeshes"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/updateAttributeNamed(_:with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateAttributeNamed"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexAttributeData",
          "text": "MDLVertexAttributeData"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/updateAttributeNamed(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateAttributeNamed:withData:"
        }
      ],
      "role": "symbol",
      "title": "updateAttributeNamed(_:with:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/updateattributenamed(_:with:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:)": {
      "abstract": [
        {
          "text": "Returns the vertex data for the specified attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexAttributeData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAttributeNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexAttributeData",
          "text": "MDLVertexAttributeData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexAttributeDataForAttributeNamed:"
        }
      ],
      "role": "symbol",
      "title": "vertexAttributeData(forAttributeNamed:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexattributedata(forattributenamed:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:as:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexAttributeData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAttributeNamed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "as"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MDLVertexFormat",
          "text": "MDLVertexFormat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexAttributeData",
          "text": "MDLVertexAttributeData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:as:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexAttributeDataForAttributeNamed:asFormat:"
        }
      ],
      "role": "symbol",
      "title": "vertexAttributeData(forAttributeNamed:as:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexattributedata(forattributenamed:as:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers": {
      "abstract": [
        {
          "text": "The array of buffers that provide vertex data for the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexBuffers"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MDLMeshBuffer",
          "text": "MDLMeshBuffer"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexBuffers"
        }
      ],
      "role": "symbol",
      "title": "vertexBuffers",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexbuffers"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexCount": {
      "abstract": [
        {
          "text": "The number of vertices in the mesh.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexCount"
        }
      ],
      "role": "symbol",
      "title": "vertexCount",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexcount"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor": {
      "abstract": [
        {
          "text": "A description of the format and layout of the mesh’s vertex buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vertexDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MDLVertexDescriptor",
          "text": "MDLVertexDescriptor"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vertexDescriptor"
        }
      ],
      "role": "symbol",
      "title": "vertexDescriptor",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/vertexdescriptor"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)": {
      "abstract": [
        {
          "text": "Returns the minimum region entirely enclosing the object’s contents at the specified time sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundingBox"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "atTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
          "text": "MDLAxisAlignedBoundingBox"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLObject/boundingBox(atTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundingBoxAtTime:"
        }
      ],
      "role": "symbol",
      "title": "boundingBox(atTime:)",
      "type": "topic",
      "url": "/documentation/modelio/mdlobject/boundingbox(attime:)"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition": {
      "abstract": [
        {
          "text": "The attribute data describes vertex positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLVertexAttributePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLVertexAttributePosition"
        }
      ],
      "role": "symbol",
      "title": "MDLVertexAttributePosition",
      "type": "topic",
      "url": "/documentation/modelio/mdlvertexattributeposition"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Vertex-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/submeshes",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexCount",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/allocator",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:time:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/removeAttributeNamed(_:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/replaceAttributeNamed(_:with:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/updateAttributeNamed(_:with:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addUnwrappedTextureCoordinates(forAttributeNamed:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:)",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:as:)"
      ],
      "title": "Working with Vertex Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "boundingBox"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.modelio/documentation/ModelIO",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Vertex-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/submeshes",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexBuffers",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexCount",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexDescriptor",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/allocator",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addAttribute(withName:format:type:data:stride:time:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/removeAttributeNamed(_:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/replaceAttributeNamed(_:with:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/updateAttributeNamed(_:with:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/addUnwrappedTextureCoordinates(forAttributeNamed:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:)",
                "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/vertexAttributeData(forAttributeNamed:as:)"
              ],
              "title": "Working with Vertex Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLAxisAlignedBoundingBox",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@MDLAxisAlignedBoundingBox",
                    "text": "MDLAxisAlignedBoundingBox"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "boundingBox"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1boundingBox/title",
          "value": "boundingBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1boundingBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:)/title",
          "value": "addAttributeWithName:format:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAttributeWithName:format:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1submeshes/title",
          "value": "submeshes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1submeshes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "submeshes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexAttributeData(forAttributeNamed:as:)/title",
          "value": "vertexAttributeDataForAttributeNamed:asFormat:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexAttributeData(forAttributeNamed:as:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "vertexAttributeDataForAttributeNamed:asFormat:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:type:data:stride:time:)/title",
          "value": "addAttributeWithName:format:type:data:stride:time:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:type:data:stride:time:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAttributeWithName:format:type:data:stride:time:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1replaceAttributeNamed(_:with:)/title",
          "value": "replaceAttributeNamed:withData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1replaceAttributeNamed(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceAttributeNamed:withData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1removeAttributeNamed(_:)/title",
          "value": "removeAttributeNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1removeAttributeNamed(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeAttributeNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/title",
          "value": "MDLAxisAlignedBoundingBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAxisAlignedBoundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLAxisAlignedBoundingBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLAxisAlignedBoundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/title",
          "value": "boundingBoxAtTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLObject~1boundingBox(atTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "boundingBoxAtTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addUnwrappedTextureCoordinates(forAttributeNamed:)/title",
          "value": "addUnwrappedTextureCoordinatesForAttributeNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addUnwrappedTextureCoordinates(forAttributeNamed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addUnwrappedTextureCoordinatesForAttributeNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexDescriptor/title",
          "value": "vertexDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/title",
          "value": "vertexBuffers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexBuffers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexBuffers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexCount/title",
          "value": "vertexCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vertexCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/title",
          "value": "MDLVertexAttributePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLVertexAttributePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLVertexAttributePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:type:data:stride:)/title",
          "value": "addAttributeWithName:format:type:data:stride:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1addAttribute(withName:format:type:data:stride:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addAttributeWithName:format:type:data:stride:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexAttributeData(forAttributeNamed:)/title",
          "value": "vertexAttributeDataForAttributeNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1vertexAttributeData(forAttributeNamed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "vertexAttributeDataForAttributeNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1allocator/title",
          "value": "allocator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1allocator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allocator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1updateAttributeNamed(_:with:)/title",
          "value": "updateAttributeNamed:withData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh~1updateAttributeNamed(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateAttributeNamed:withData:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmesh/boundingbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/modelio/mdlmesh/boundingbox"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
