{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.modelio/documentation/ModelIO",
        "doc://com.apple.modelio/documentation/ModelIO/MDLMesh"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/meshWithSCNGeometry:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MDLMesh(cm)meshWithSCNGeometry:",
    "fragments": [
      {
        "kind": "text",
        "text": "+ "
      },
      {
        "kind": "identifier",
        "text": "meshWithSCNGeometry:"
      }
    ],
    "modules": [
      {
        "name": "Model I/O"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "meshWithSCNGeometry:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "meshWithSCNGeometry:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "meshWithSCNGeometry:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SCNGeometry",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNGeometry",
              "text": "SCNGeometry"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "scnGeometry"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.modelio/documentation/ModelIO": {
      "abstract": [
        {
          "text": "Import, export, and manipulate 3D models using a common infrastructure that integrates MetalKit, GLKit, and SceneKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO",
      "kind": "symbol",
      "role": "collection",
      "title": "Model I/O",
      "type": "topic",
      "url": "/documentation/modelio"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh": {
      "abstract": [
        {
          "text": "A container for vertex buffer data to be used in rendering a 3D object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MDLMesh"
        }
      ],
      "role": "symbol",
      "title": "MDLMesh",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh"
    },
    "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/meshWithSCNGeometry:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "meshWithSCNGeometry:"
        }
      ],
      "identifier": "doc://com.apple.modelio/documentation/ModelIO/MDLMesh/meshWithSCNGeometry:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "meshWithSCNGeometry:"
        }
      ],
      "role": "symbol",
      "title": "meshWithSCNGeometry:",
      "type": "topic",
      "url": "/documentation/modelio/mdlmesh/meshwithscngeometry:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)SCNGeometry": {
      "abstract": [
        {
          "text": "A three-dimensional shape (also called a model or mesh) that can be displayed in a scene, with attached materials that define its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNGeometry"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)SCNGeometry",
      "kind": "symbol",
      "role": "symbol",
      "title": "SCNGeometry",
      "type": "topic",
      "url": "/documentation/SceneKit/SCNGeometry"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/title",
          "value": "MDLMesh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.modelio~1documentation~1ModelIO~1MDLMesh/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MDLMesh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)SCNGeometry/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "SCNGeometry"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/modelio/mdlmesh/meshwithscngeometry:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
