{
  "abstract": [
    {
      "text": "The server is unable to provide a token because the internet isn’t available.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.AdServices/documentation/AdServices",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AAAttributionErrorCode@AAAttributionErrorCodeNetworkError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "networkError"
      }
    ],
    "modules": [
      {
        "name": "AdServices"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AAAttributionErrorCodeNetworkError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.3",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.1",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AAAttributionError.Code.networkError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "networkError"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To receive an attribution token, you must have unimpeded internet access. Make sure",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you’re not using a simulator when generating a token.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.AdServices/documentation/AdServices": {
      "abstract": [
        {
          "text": "Attribute app-download campaigns that originate from the App Store, Apple News, or",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Stocks on iOS devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices",
      "kind": "symbol",
      "role": "collection",
      "title": "AdServices",
      "type": "topic",
      "url": "/documentation/adservices"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code": {
      "abstract": [
        {
          "text": "The error code that the parent class issues.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an internal error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "internalError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodeInternalError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.internalError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/internalerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because the internet isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkError"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/networkError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodeNetworkError"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.networkError",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/networkerror"
    },
    "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported": {
      "abstract": [
        {
          "text": "The server is unable to provide a token because of an unsupported operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "platformNotSupported"
        }
      ],
      "identifier": "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AAAttributionErrorCodePlatformNotSupported"
        }
      ],
      "role": "symbol",
      "title": "AAAttributionError.Code.platformNotSupported",
      "type": "topic",
      "url": "/documentation/adservices/aaattributionerror/code/platformnotsupported"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-the-cause-of-an-error",
      "generated": true,
      "identifiers": [
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
        "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported"
      ],
      "title": "Determining the cause of an error"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.3",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.1",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AAAttributionErrorCodeNetworkError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodeNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.AdServices/documentation/AdServices",
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-the-cause-of-an-error",
              "generated": true,
              "identifiers": [
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/internalError",
                "doc://com.apple.AdServices/documentation/AdServices/AAAttributionError/Code/platformNotSupported"
              ],
              "title": "Determining the cause of an error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AAAttributionErrorCodeNetworkError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1platformNotSupported/title",
          "value": "AAAttributionErrorCodePlatformNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1platformNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodePlatformNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1networkError/title",
          "value": "AAAttributionErrorCodeNetworkError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1networkError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodeNetworkError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/title",
          "value": "AAAttributionErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1internalError/title",
          "value": "AAAttributionErrorCodeInternalError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.AdServices~1documentation~1AdServices~1AAAttributionError~1Code~1internalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AAAttributionErrorCodeInternalError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/adservices/aaattributionerror/code/networkerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/adservices/aaattributionerror/code/networkerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
