{
  "abstract": [
    {
      "text": "Capture additional data including depth and metadata, and synchronize capture from multiple outputs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Additional data capture"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData": {
      "abstract": [
        {
          "text": "Information about the camera characteristics used to capture images and depth data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCameraCalibrationData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCameraCalibrationData"
        }
      ],
      "role": "symbol",
      "title": "AVCameraCalibrationData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcameracalibrationdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDataOutputSynchronizer": {
      "abstract": [
        {
          "text": "An object that coordinates time-matched delivery of data from multiple capture outputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDataOutputSynchronizer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDataOutputSynchronizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDataOutputSynchronizer"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDataOutputSynchronizer",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedataoutputsynchronizer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput": {
      "abstract": [
        {
          "text": "A capture output that records scene depth information on compatible camera devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDepthDataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDepthDataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDepthDataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedepthdataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput": {
      "abstract": [
        {
          "text": "A capture input for providing timed metadata to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMetadataInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemetadatainput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput": {
      "abstract": [
        {
          "text": "A capture output for processing timed metadata produced by a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMetadataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemetadataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedData": {
      "abstract": [
        {
          "text": "The abstract superclass for media samples collected using synchronized capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedData"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSynchronizedData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesynchronizeddata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDataCollection": {
      "abstract": [
        {
          "text": "A set of data samples collected simultaneously from multiple capture outputs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedDataCollection"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDataCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedDataCollection"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSynchronizedDataCollection",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesynchronizeddatacollection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDepthData": {
      "abstract": [
        {
          "text": "A container for scene depth information collected using synchronized capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedDepthData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDepthData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedDepthData"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSynchronizedDepthData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesynchronizeddepthdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedMetadataObjectData": {
      "abstract": [
        {
          "text": "A container for metadata objects collected using synchronized capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedMetadataObjectData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedMetadataObjectData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedMetadataObjectData"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSynchronizedMetadataObjectData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesynchronizedmetadataobjectdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedSampleBufferData": {
      "abstract": [
        {
          "text": "A container for video or audio samples collected using synchronized capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedSampleBufferData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedSampleBufferData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSynchronizedSampleBufferData"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSynchronizedSampleBufferData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesynchronizedsamplebufferdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData": {
      "abstract": [
        {
          "text": "A container for per-pixel distance or disparity information captured by compatible camera devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDepthData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDepthData"
        }
      ],
      "role": "symbol",
      "title": "AVDepthData",
      "type": "topic",
      "url": "/documentation/avfoundation/avdepthdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject": {
      "abstract": [
        {
          "text": "The abstract superclass for objects provided by a metadata capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture": {
      "abstract": [
        {
          "text": "Capture audio and video directly to media files, or capture streams of media for direct access to media sample buffers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio and video capture",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-and-video-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream": {
      "abstract": [
        {
          "text": "Render a capture stream with rose-colored filtering and depth effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
      "kind": "article",
      "role": "sampleCode",
      "title": "AVCamFilter: Applying Filters to a Capture Stream",
      "type": "topic",
      "url": "/documentation/avfoundation/avcamfilter-applying-filters-to-a-capture-stream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup": {
      "abstract": [
        {
          "text": "Configure built-in cameras and microphones, and external capture devices, for media capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capture setup",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-setup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera": {
      "abstract": [
        {
          "text": "Access the LiDAR camera on supporting devices to capture precise depth data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing depth using the LiDAR camera",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-depth-using-the-lidar-camera"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth": {
      "abstract": [
        {
          "text": "Get a depth map with a photo to create effects like the system camera’s Portrait mode (on compatible devices).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
      "kind": "article",
      "role": "article",
      "title": "Capturing Photos with Depth",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-photos-with-depth"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually": {
      "abstract": [
        {
          "text": "Generate a depth image and attach it to your own image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
      "kind": "article",
      "role": "article",
      "title": "Creating Auxiliary Depth Data Manually",
      "type": "topic",
      "url": "/documentation/avfoundation/creating-auxiliary-depth-data-manually"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data": {
      "abstract": [
        {
          "text": "Apply your own background to a live capture feed streamed from the front-facing TrueDepth camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Enhancing Live Video by Leveraging TrueDepth Camera Data",
      "type": "topic",
      "url": "/documentation/avfoundation/enhancing-live-video-by-leveraging-truedepth-camera-data"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types": {
      "abstract": [
        {
          "text": "Inspect the supported metadata object types that the framework supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Types",
      "type": "topic",
      "url": "/documentation/avfoundation/metadata-types"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture": {
      "abstract": [
        {
          "text": "Capture high-quality still images, Live Photos, and supporting photo data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Photo capture",
      "type": "topic",
      "url": "/documentation/avfoundation/photo-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-depth-data-from-the-truedepth-camera": {
      "abstract": [
        {
          "text": "Visualize depth data in 2D and 3D from the TrueDepth camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-depth-data-from-the-truedepth-camera",
      "kind": "article",
      "role": "sampleCode",
      "title": "Streaming Depth Data from the TrueDepth Camera",
      "type": "topic",
      "url": "/documentation/avfoundation/streaming-depth-data-from-the-truedepth-camera"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
        "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture"
      ],
      "title": "Capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Depth-data-capture",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
        "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
        "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-depth-data-from-the-truedepth-camera",
        "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData"
      ],
      "title": "Depth data capture"
    },
    {
      "anchor": "Metadata-capture",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
        "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types"
      ],
      "title": "Metadata capture"
    },
    {
      "anchor": "Synchronized-capture",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDataOutputSynchronizer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDataCollection",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedSampleBufferData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedMetadataObjectData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDepthData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedData"
      ],
      "title": "Synchronized capture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Depth-data-capture",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
                "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
                "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-depth-data-from-the-truedepth-camera",
                "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData"
              ],
              "title": "Depth data capture"
            },
            {
              "anchor": "Metadata-capture",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
                "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types"
              ],
              "title": "Metadata capture"
            },
            {
              "anchor": "Synchronized-capture",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDataOutputSynchronizer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDataCollection",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedSampleBufferData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedMetadataObjectData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedDepthData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSynchronizedData"
              ],
              "title": "Synchronized capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
                "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-and-video-capture"
              ],
              "title": "Capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDepthData/title",
          "value": "AVCaptureSynchronizedDepthData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDepthData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDepthData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/title",
          "value": "AVMetadataObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/title",
          "value": "AVDepthData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/title",
          "value": "AVCaptureMetadataInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedMetadataObjectData/title",
          "value": "AVCaptureSynchronizedMetadataObjectData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedMetadataObjectData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedMetadataObjectData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedMetadataObjectData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedMetadataObjectData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDataCollection/title",
          "value": "AVCaptureSynchronizedDataCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDataCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedDataCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedDataCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedDataCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/title",
          "value": "AVCaptureDepthDataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDepthDataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDepthDataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/title",
          "value": "AVCameraCalibrationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCameraCalibrationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCameraCalibrationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedSampleBufferData/title",
          "value": "AVCaptureSynchronizedSampleBufferData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedSampleBufferData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedSampleBufferData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedSampleBufferData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedSampleBufferData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDataOutputSynchronizer/title",
          "value": "AVCaptureDataOutputSynchronizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDataOutputSynchronizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDataOutputSynchronizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDataOutputSynchronizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDataOutputSynchronizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedData/title",
          "value": "AVCaptureSynchronizedData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSynchronizedData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSynchronizedData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/title",
          "value": "AVCaptureMetadataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/additional-data-capture"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/additional-data-capture"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
