{
  "abstract": [
    {
      "text": "Define how to mix the audio levels from multiple audio tracks over an asset’s duration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio mixing"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMix": {
      "abstract": [
        {
          "text": "An object that manages the input parameters for mixing audio tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMix"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMix"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMix",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiomix"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMixInputParameters": {
      "abstract": [
        {
          "text": "An object that represents the parameters that you apply when adding an audio track to a mix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioMixInputParameters"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMixInputParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioMixInputParameters"
        }
      ],
      "role": "symbol",
      "title": "AVAudioMixInputParameters",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiomixinputparameters"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMix": {
      "abstract": [
        {
          "text": "An object that manages the input parameters for mixing audio tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableAudioMix"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableAudioMix"
        }
      ],
      "role": "symbol",
      "title": "AVMutableAudioMix",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutableaudiomix"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMixInputParameters": {
      "abstract": [
        {
          "text": "The parameters you use when adding an audio track to a mix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableAudioMixInputParameters"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMixInputParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableAudioMixInputParameters"
        }
      ],
      "role": "symbol",
      "title": "AVMutableAudioMixInputParameters",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutableaudiomixinputparameters"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets": {
      "abstract": [
        {
          "text": "Combine tracks and segments of tracks from multiple assets into a composite asset that you can play or process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite assets",
      "type": "topic",
      "url": "/documentation/avfoundation/composite-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies": {
      "abstract": [
        {
          "text": "Access the contents of a QuickTime movie file, and perform sample-level edits of its media tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuickTime movies",
      "type": "topic",
      "url": "/documentation/avfoundation/quicktime-movies"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects": {
      "abstract": [
        {
          "text": "Define standard video transition effects, synchronize layer animations with media timing, and create custom video compositors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video effects",
      "type": "topic",
      "url": "/documentation/avfoundation/video-effects"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Mixing",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMix",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMix",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMixInputParameters",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMixInputParameters"
      ],
      "title": "Mixing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Mixing",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMix",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMix",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioMixInputParameters",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAudioMixInputParameters"
              ],
              "title": "Mixing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects"
              ],
              "title": "Editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMix/title",
          "value": "AVMutableAudioMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAudioMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAudioMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMixInputParameters/title",
          "value": "AVMutableAudioMixInputParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMixInputParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAudioMixInputParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAudioMixInputParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAudioMixInputParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMix/title",
          "value": "AVAudioMix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMix/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMixInputParameters/title",
          "value": "AVAudioMixInputParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMixInputParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixInputParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAudioMixInputParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioMixInputParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/audio-mixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/audio-mixing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
