{
  "abstract": [
    {
      "text": "Play, record, and process audio; configure your app’s system audio behavior.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-playback-recording-and-processing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Audio playback, recording, and processing"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience": {
      "abstract": [
        {
          "text": "A protocol that defines types of spatial audio experiences that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfoundation/avaudiosessionspatialexperience"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis": {
      "abstract": [
        {
          "text": "Configure voices to speak strings of text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech synthesis",
      "type": "topic",
      "url": "/documentation/avfoundation/speech-synthesis"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioApplication": {
      "abstract": [
        {
          "text": "An object that manages one or more audio sessions that belong to an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioApplication"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioApplication",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioApplication",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioApplication"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer": {
      "abstract": [
        {
          "text": "An object that plays audio data from a file or buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioPlayer",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioPlayer"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRecorder": {
      "abstract": [
        {
          "text": "An object that records audio data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRecorder"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRecorder",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioRecorder",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioRecorder"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRoutingArbiter": {
      "abstract": [
        {
          "text": "An object for configuring macOS apps to participate in AirPods Automatic Switching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioRoutingArbiter"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRoutingArbiter",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioRoutingArbiter",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioRoutingArbiter"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioSession"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVMIDIPlayer": {
      "abstract": [
        {
          "text": "An object that plays MIDI data through a system sound module.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIPlayer"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVMIDIPlayer",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMIDIPlayer",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVMIDIPlayer"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/audio-engine": {
      "abstract": [
        {
          "text": "Perform advanced real-time and offline audio processing, implement 3D spatialization, and work with MIDI and samplers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/audio-engine",
      "kind": "article",
      "role": "article",
      "title": "Audio Engine",
      "type": "topic",
      "url": "/documentation/AVFAudio/audio-engine"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to interruptions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions",
      "kind": "article",
      "role": "article",
      "title": "Handling audio interruptions",
      "type": "topic",
      "url": "/documentation/AVFAudio/handling-audio-interruptions"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/responding-to-audio-route-changes": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to route changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/responding-to-audio-route-changes",
      "kind": "article",
      "role": "article",
      "title": "Responding to audio route changes",
      "type": "topic",
      "url": "/documentation/AVFAudio/responding-to-audio-route-changes"
    },
    "doc://com.apple.documentation/documentation/avfaudio/capturing_stereo_audio_from_built-in_microphones": {
      "abstract": [
        {
          "text": "Configure an iOS device’s built-in microphones to add stereo-recording capabilities to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/avfaudio/capturing_stereo_audio_from_built-in_microphones",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing stereo audio from built-in microphones",
      "type": "topic",
      "url": "/documentation/avfaudio/capturing_stereo_audio_from_built-in_microphones"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis"
      ],
      "title": "Audio"
    }
  ],
  "topicSections": [
    {
      "anchor": "System-audio",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions",
        "doc://com.apple.documentation/documentation/AVFAudio/responding-to-audio-route-changes",
        "doc://com.apple.documentation/documentation/avfaudio/capturing_stereo_audio_from_built-in_microphones",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioApplication",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRoutingArbiter"
      ],
      "title": "System audio"
    },
    {
      "anchor": "Basic-playback-and-recording",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRecorder",
        "doc://com.apple.documentation/documentation/AVFAudio/AVMIDIPlayer"
      ],
      "title": "Basic playback and recording"
    },
    {
      "anchor": "Advanced-audio-processing",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/audio-engine"
      ],
      "title": "Advanced audio processing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "System-audio",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/handling-audio-interruptions",
                "doc://com.apple.documentation/documentation/AVFAudio/responding-to-audio-route-changes",
                "doc://com.apple.documentation/documentation/avfaudio/capturing_stereo_audio_from_built-in_microphones",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioSession",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioApplication",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRoutingArbiter"
              ],
              "title": "System audio"
            },
            {
              "anchor": "Basic-playback-and-recording",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioPlayer",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioRecorder",
                "doc://com.apple.documentation/documentation/AVFAudio/AVMIDIPlayer"
              ],
              "title": "Basic playback and recording"
            },
            {
              "anchor": "Advanced-audio-processing",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/audio-engine"
              ],
              "title": "Advanced audio processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/speech-synthesis"
              ],
              "title": "Audio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVMIDIPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMIDIPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioPlayer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioPlayer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioApplication/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioApplication"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioRecorder/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioRecorder"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioRoutingArbiter/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioRoutingArbiter"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/audio-playback-recording-and-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/audio-playback-recording-and-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
