{
  "abstract": [
    {
      "text": "Configure audio processing settings using standard key and value constants.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "title": "Audio settings"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-bit-rate-strategy-values": {
      "abstract": [
        {
          "text": "The constants that represent the possible bit rate strategy values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-bit-rate-strategy-values",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Bit Rate Strategy Values",
      "type": "topic",
      "url": "/documentation/avfoundation/encoder-bit-rate-strategy-values"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-settings": {
      "abstract": [
        {
          "text": "The constants that define the audio encoder settings for the audio recorder class.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/encoder-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to all audio formats that the audio player and recorder classes support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/format-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/linear-pcm-format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to linear PCM audio formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/linear-pcm-format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Linear PCM Format Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/linear-pcm-format-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities": {
      "abstract": [
        {
          "text": "Identify the types of content and file formats that AVFoundation supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media types and utilities",
      "type": "topic",
      "url": "/documentation/avfoundation/media-types-and-utilities"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/sample-rate-conversion-settings": {
      "abstract": [
        {
          "text": "The constants that define sample rate converter audio quality settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/sample-rate-conversion-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample Rate Conversion Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/sample-rate-conversion-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/time-pitch-algorithm-settings": {
      "abstract": [
        {
          "text": "The constants that define the values for the time pitch algorithms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/time-pitch-algorithm-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Time Pitch Algorithm Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/time-pitch-algorithm-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings": {
      "abstract": [
        {
          "text": "Configure video processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video settings",
      "type": "topic",
      "url": "/documentation/avfoundation/video-settings"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout": {
      "abstract": [
        {
          "text": "An object that describes the roles of a set of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioChannelLayout"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat": {
      "abstract": [
        {
          "text": "An object that describes the representation of an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioFormat",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioFormat"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioQuality": {
      "abstract": [
        {
          "text": "The values that specify the sample rate audio quality for encoding and conversion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioQuality"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioQuality",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioQuality",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioQuality"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVChannelLayoutKey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings"
      ],
      "title": "Common"
    }
  ],
  "topicSections": [
    {
      "anchor": "Formats",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
        "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/linear-pcm-format-settings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings"
      ],
      "title": "Formats"
    },
    {
      "anchor": "Settings",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/sample-rate-conversion-settings",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioQuality",
        "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-settings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/time-pitch-algorithm-settings"
      ],
      "title": "Settings"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-bit-rate-strategy-values",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Formats",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
                "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/linear-pcm-format-settings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings"
              ],
              "title": "Formats"
            },
            {
              "anchor": "Settings",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/sample-rate-conversion-settings",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioQuality",
                "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-settings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/time-pitch-algorithm-settings"
              ],
              "title": "Settings"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-bit-rate-strategy-values",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioFormat/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioChannelLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioQuality/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioQuality"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVChannelLayoutKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/audio-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/audio-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
