{
  "abstract": [
    {
      "text": "A preset to export a 1080p High Definition format suitable for playing on Apple devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVAssetExportPresetAppleM4V1080pHD",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVAssetExportPresetAppleM4V1080pHD"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAssetExportPresetAppleM4V1080pHD"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVAssetExportPresetAppleM4V1080pHD"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V1080pHD"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD": {
      "abstract": [
        {
          "text": "A preset to export a 1080p High Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V1080pHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V1080pHD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V1080pHD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v1080phd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD": {
      "abstract": [
        {
          "text": "A preset to export a 480p Standard Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V480pSD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V480pSD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V480pSD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v480psd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD": {
      "abstract": [
        {
          "text": "A preset to export a 720p High Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V720pHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V720pHD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V720pHD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v720phd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VAppleTV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VAppleTV"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VAppleTV",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vappletv"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple devices when it streams over a cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VCellular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VCellular"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VCellular",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vcellular"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple devices it streams over a WiFi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VWiFi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VWiFi"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VWiFi",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vwifi"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on an iPod.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4ViPod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4ViPod"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4ViPod",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vipod"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "M4V-Presets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi"
      ],
      "title": "M4V Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAssetExportPresetAppleM4V1080pHD"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V1080pHD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "M4V-Presets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi"
              ],
              "title": "M4V Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAssetExportPresetAppleM4V1080pHD"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VAppleTV/title",
          "value": "AVAssetExportPresetAppleM4VAppleTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VAppleTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VAppleTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V1080pHD/title",
          "value": "AVAssetExportPresetAppleM4V1080pHD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V1080pHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V1080pHD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VWiFi/title",
          "value": "AVAssetExportPresetAppleM4VWiFi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VWiFi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VWiFi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VCellular/title",
          "value": "AVAssetExportPresetAppleM4VCellular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VCellular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VCellular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4ViPod/title",
          "value": "AVAssetExportPresetAppleM4ViPod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4ViPod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4ViPod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V480pSD/title",
          "value": "AVAssetExportPresetAppleM4V480pSD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V480pSD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V480pSD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V720pHD/title",
          "value": "AVAssetExportPresetAppleM4V720pHD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V720pHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V720pHD"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avassetexportpresetapplem4v1080phd"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avassetexportpresetapplem4v1080phd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
