{"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status"],"title":"Accessing the Status","anchor":"Accessing-the-Status"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avasyncproperty"]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAsyncProperty"}],"title":"AVAsyncProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAsyncProperty"}],"symbolKind":"class","modules":[{"name":"AVFoundation"}],"externalID":"s:12AVFoundation15AVAsyncPropertyC","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"12.0","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"15.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false}],"roleHeading":"Class"},"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading","doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty","doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty"],"title":"Property loading","generated":true,"anchor":"Property-loading"}],"relationshipsSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"text":"An asynchronous property that constrains its type and value.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAsyncProperty","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Root","kind":"genericParameter"},{"text":", ","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":">","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"mentions":["doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously"],"kind":"mentions"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"text":"This class subclasses ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty","type":"reference"},{"text":" to provide a type constraint on the property value.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty"},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"type":"topic","title":"Sendable","url":"/documentation/Swift/Sendable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously":{"type":"topic","abstract":[{"type":"text","text":"Build responsive apps by using language-level concurrency features to efficiently load media data."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously","role":"article","kind":"article","title":"Loading media data asynchronously","url":"/documentation/avfoundation/loading-media-data-asynchronously"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading":{"url":"/documentation/avfoundation/avasynchronouskeyvalueloading","title":"AVAsynchronousKeyValueLoading","abstract":[{"text":"A protocol that defines the interface to load media data asynchronously.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAsynchronousKeyValueLoading"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAsynchronousKeyValueLoading"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAnyAsyncProperty","kind":"identifier"}],"role":"symbol","url":"/documentation/avfoundation/avanyasyncproperty","abstract":[{"text":"A base class for asynchronous properties.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AVAnyAsyncProperty","kind":"identifier"}],"title":"AVAnyAsyncProperty"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty":{"url":"/documentation/avfoundation/avasyncproperty","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAsyncProperty","kind":"identifier"}],"type":"topic","title":"AVAsyncProperty","abstract":[{"type":"text","text":"An asynchronous property that constrains its type and value."}],"navigatorTitle":[{"text":"AVAsyncProperty","kind":"identifier"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty":{"kind":"symbol","title":"AVPartialAsyncProperty","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPartialAsyncProperty"}],"navigatorTitle":[{"kind":"identifier","text":"AVPartialAsyncProperty"}],"abstract":[{"type":"text","text":"An asynchronous property that constrains its type."}],"url":"/documentation/avfoundation/avpartialasyncproperty"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status":{"role":"symbol","url":"/documentation/avfoundation/avasyncproperty/status","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty/Status","abstract":[{"text":"Loaded status values for asynchronous properties.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"title":"AVAsyncProperty.Status","navigatorTitle":[{"kind":"identifier","text":"Status"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"AVAsynchronousKeyValueLoading","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVAsynchronousKeyValueLoading"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/fragments"},{"op":"replace","value":[{"text":"AVAsynchronousKeyValueLoading","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}