{"relationshipsSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"abstract":[{"type":"text","text":"An object that reads composited video frames from one or more tracks of an asset."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:objc(cs)AVAssetReaderVideoCompositionOutput","symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"title":"AVAssetReaderVideoCompositionOutput","platforms":[{"introducedAt":"4.1","deprecated":false,"beta":false,"unavailable":false,"name":"iOS"},{"introducedAt":"4.1","deprecated":false,"beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"10.7","deprecated":false,"beta":false,"unavailable":false,"name":"macOS"},{"introducedAt":"9.0","deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"modules":[{"name":"AVFoundation"}]},"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/init(videoTracks:videoSettings:)"],"anchor":"Creating-a-Video-Composition-Output","title":"Creating a Video Composition Output"},{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoComposition","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/customVideoCompositor"],"anchor":"Configuring-Video-Settings","title":"Configuring Video Settings"},{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoTracks","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoSettings"],"anchor":"Inspecting-an-Output","title":"Inspecting an Output"}],"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor"],"anchor":"Media-reading","title":"Media reading"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAssetReaderVideoCompositionOutput"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avassetreadervideocompositionoutput"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avassetreadervideocompositionoutput"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput":{"url":"/documentation/avfoundation/avassetreadertrackoutput","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput","abstract":[{"text":"An object that reads media data from a single track of an asset.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AVAssetReaderTrackOutput","kind":"identifier"}],"title":"AVAssetReaderTrackOutput","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderTrackOutput","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoSettings":{"abstract":[{"type":"text","text":"The video settings that the output uses."}],"kind":"symbol","title":"videoSettings","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoSettings","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoSettings"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"url":"/documentation/avfoundation/avassetreadervideocompositionoutput/videosettings","navigatorTitle":[{"kind":"identifier","text":"videoSettings"}]},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoTracks":{"abstract":[{"type":"text","text":"The tracks from which the output reads the composited video."}],"kind":"symbol","title":"videoTracks","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoTracks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoTracks"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AVAssetTrack","kind":"typeIdentifier","text":"AVAssetTrack"},{"kind":"text","text":"]"}],"url":"/documentation/avfoundation/avassetreadervideocompositionoutput/videotracks","navigatorTitle":[{"kind":"identifier","text":"videoTracks"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoComposition":{"abstract":[{"text":"The video composition to use for the output.","type":"text"}],"role":"symbol","title":"videoComposition","navigatorTitle":[{"text":"videoComposition","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"videoComposition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVVideoComposition","preciseIdentifier":"c:objc(cs)AVVideoComposition","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoComposition","kind":"symbol","type":"topic","url":"/documentation/avfoundation/avassetreadervideocompositionoutput/videocomposition"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput":{"title":"AVAssetReaderOutput","type":"topic","url":"/documentation/avfoundation/avassetreaderoutput","abstract":[{"text":"An abstract class that defines the interface to read media samples from an asset reader.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AVAssetReaderOutput","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput","navigatorTitle":[{"text":"AVAssetReaderOutput","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/customVideoCompositor":{"title":"customVideoCompositor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customVideoCompositor","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"AVVideoCompositing","preciseIdentifier":"c:objc(pl)AVVideoCompositing","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"abstract":[{"text":"A custom video compositor for the output.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/customVideoCompositor","type":"topic","role":"symbol","url":"/documentation/avfoundation/avassetreadervideocompositionoutput/customvideocompositor","navigatorTitle":[{"text":"customVideoCompositor","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor":{"url":"/documentation/avfoundation/avassetreaderoutputmetadataadaptor","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor","abstract":[{"text":"An object that creates timed metadata group objects for an asset track.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AVAssetReaderOutputMetadataAdaptor","kind":"identifier"}],"title":"AVAssetReaderOutputMetadataAdaptor","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderOutputMetadataAdaptor","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput":{"title":"AVAssetReaderSampleReferenceOutput","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput","kind":"symbol","url":"/documentation/avfoundation/avassetreadersamplereferenceoutput","navigatorTitle":[{"text":"AVAssetReaderSampleReferenceOutput","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that reads sample references from an asset track."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderSampleReferenceOutput","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:":{"abstract":[{"type":"text","text":"Returns a new object that reads composited video from the specified video tracks."}],"kind":"symbol","title":"assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:"}],"url":"/documentation/avfoundation/avassetreadervideocompositionoutput/assetreadervideocompositionoutputwithvideotracks:videosettings:","navigatorTitle":[{"kind":"identifier","text":"assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput","title":"AVAssetReaderAudioMixOutput","role":"symbol","abstract":[{"text":"An object that reads audio samples that result from mixing audio from one or more tracks.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVAssetReaderAudioMixOutput"}],"url":"/documentation/avfoundation/avassetreaderaudiomixoutput","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAssetReaderAudioMixOutput"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files":{"title":"Reading multiview 3D video files","type":"topic","role":"sampleCode","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files","kind":"article","url":"/documentation/avfoundation/reading-multiview-3d-video-files","abstract":[{"type":"text","text":"Render single images for the left eye and right eye from a multiview High Efficiency Video Coding format file by reading individual video frames."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/init(videoTracks:videoSettings:)":{"abstract":[{"type":"text","text":"Creates an object that reads composited video frames from the specified video tracks."}],"kind":"symbol","title":"init(videoTracks:videoSettings:)","type":"topic","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/init(videoTracks:videoSettings:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoTracks"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)AVAssetTrack","kind":"typeIdentifier","text":"AVAssetTrack"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"videoSettings"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"url":"/documentation/avfoundation/avassetreadervideocompositionoutput/init(videotracks:videosettings:)","navigatorTitle":[{"kind":"identifier","text":"initWithVideoTracks:videoSettings:"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAssetReader"}],"title":"AVAssetReader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAssetReader"}],"abstract":[{"type":"text","text":"An object that reads media data from an asset."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader","type":"topic","kind":"symbol","url":"/documentation/avfoundation/avassetreader"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput":{"type":"topic","url":"/documentation/avfoundation/avassetreadervideocompositionoutput","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"navigatorTitle":[{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"role":"symbol","title":"AVAssetReaderVideoCompositionOutput","kind":"symbol","abstract":[{"text":"An object that reads composited video frames from one or more tracks of an asset.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"introducedAt":"4.1","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"introducedAt":"4.1","beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS"},{"introducedAt":"13.1","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"10.7","beta":false,"unavailable":false,"deprecated":false,"name":"macOS"},{"introducedAt":"9.0","beta":false,"unavailable":false,"deprecated":false,"name":"tvOS"},{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"AVAssetReaderVideoCompositionOutput","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReaderVideoCompositionOutput"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"path":"/hierarchy","op":"replace"},{"value":[{"title":"Creating a Video Composition Output","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/assetReaderVideoCompositionOutputWithVideoTracks:videoSettings:","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/init(videoTracks:videoSettings:)"],"anchor":"Creating-a-Video-Composition-Output"},{"anchor":"Configuring-Video-Settings","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoComposition","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/customVideoCompositor"],"title":"Configuring Video Settings"},{"anchor":"Inspecting-an-Output","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoTracks","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput/videoSettings"],"title":"Inspecting an Output"}],"path":"/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput"],"title":"Inherits From","kind":"relationships"}],"path":"/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor"],"title":"Media reading","anchor":"Media-reading","generated":true}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput","text":"AVAssetReaderOutput","preciseIdentifier":"c:objc(cs)AVAssetReaderOutput","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"value":"AVAssetReaderTrackOutput","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/title"},{"value":[{"text":"AVAssetReaderTrackOutput","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/fragments"},{"value":[{"kind":"identifier","text":"AVAssetReaderTrackOutput"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/navigatorTitle"},{"value":"videoSettings","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoSettings/title"},{"value":[{"text":"videoSettings","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoSettings/fragments"},{"value":"videoTracks","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoTracks/title"},{"value":[{"text":"videoTracks","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoTracks/fragments"},{"value":"videoComposition","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoComposition/title"},{"value":[{"text":"videoComposition","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1videoComposition/fragments"},{"value":"AVAssetReaderOutput","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/title","op":"replace"},{"value":[{"text":"AVAssetReaderOutput","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReaderOutput"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/navigatorTitle","op":"replace"},{"value":"customVideoCompositor","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1customVideoCompositor/title","op":"replace"},{"value":[{"kind":"identifier","text":"customVideoCompositor"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1customVideoCompositor/fragments","op":"replace"},{"value":"AVAssetReaderOutputMetadataAdaptor","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/title","op":"replace"},{"value":[{"text":"AVAssetReaderOutputMetadataAdaptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReaderOutputMetadataAdaptor"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/navigatorTitle","op":"replace"},{"value":"AVAssetReaderSampleReferenceOutput","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReaderSampleReferenceOutput"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReaderSampleReferenceOutput"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/navigatorTitle","op":"replace"},{"value":"AVAssetReaderAudioMixOutput","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/title","op":"replace"},{"value":[{"text":"AVAssetReaderAudioMixOutput","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/fragments","op":"replace"},{"value":[{"text":"AVAssetReaderAudioMixOutput","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/navigatorTitle","op":"replace"},{"value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace"},{"value":"initWithVideoTracks:videoSettings:","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1init(videoTracks:videoSettings:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVideoTracks:videoSettings:"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput~1init(videoTracks:videoSettings:)/fragments","op":"replace"},{"value":"AVAssetReader","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVAssetReader"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/fragments","op":"replace"},{"value":[{"text":"AVAssetReader","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/navigatorTitle","op":"replace"},{"value":"AVAssetReaderVideoCompositionOutput","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/title","op":"replace"},{"value":[{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/fragments","op":"replace"},{"value":[{"text":"AVAssetReaderVideoCompositionOutput","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}