{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/avasset-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " doesn’t support using its synchronous property accessors that can block the calling thread. Instead, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading/load(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to load ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values asynchronously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset": {
      "abstract": [
        {
          "text": "An object that models timed audiovisual media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "role": "symbol",
      "title": "AVAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/allMediaSelections": {
      "abstract": [
        {
          "text": "The array of available media selections for this asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allMediaSelections"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelection",
          "text": "AVMediaSelection"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/allMediaSelections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allMediaSelections"
        }
      ],
      "role": "symbol",
      "title": "allMediaSelections",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/allmediaselections"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableChapterLocales": {
      "abstract": [
        {
          "text": "The locales of the asset’s chapter metadata.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableChapterLocales"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableChapterLocales",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableChapterLocales"
        }
      ],
      "role": "symbol",
      "title": "availableChapterLocales",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/availablechapterlocales"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions": {
      "abstract": [
        {
          "text": "An array of media characteristics for which a media selection option is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
        }
      ],
      "role": "symbol",
      "title": "availableMediaCharacteristicsWithMediaSelectionOptions",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/availablemediacharacteristicswithmediaselectionoptions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMetadataFormats": {
      "abstract": [
        {
          "text": "The metadata formats this asset contains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableMetadataFormats"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataFormat",
          "text": "AVMetadataFormat"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMetadataFormats",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableMetadataFormats"
        }
      ],
      "role": "symbol",
      "title": "availableMetadataFormats",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/availablemetadataformats"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/canContainFragments": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can extend the asset by fragments.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canContainFragments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/canContainFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canContainFragments"
        }
      ],
      "role": "symbol",
      "title": "canContainFragments",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/cancontainfragments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(bestMatchingPreferredLanguages:)": {
      "abstract": [
        {
          "text": "Returns an array of chapters with a locale that best matches the list of preferred languages.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chapterMetadataGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bestMatchingPreferredLanguages"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVTimedMetadataGroup",
          "text": "AVTimedMetadataGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(bestMatchingPreferredLanguages:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chapterMetadataGroupsBestMatchingPreferredLanguages:"
        }
      ],
      "role": "symbol",
      "title": "chapterMetadataGroups(bestMatchingPreferredLanguages:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/chaptermetadatagroups(bestmatchingpreferredlanguages:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)": {
      "abstract": [
        {
          "text": "Returns an array of chapters that contain the specified title locale and common keys.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chapterMetadataGroups"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTitleLocale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation6LocaleV",
          "text": "Locale"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "containingItemsWithCommonKeys"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataKey",
          "text": "AVMetadataKey"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVTimedMetadataGroup",
          "text": "AVTimedMetadataGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:"
        }
      ],
      "role": "symbol",
      "title": "chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/chaptermetadatagroups(withtitlelocale:containingitemswithcommonkeys:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/commonMetadata": {
      "abstract": [
        {
          "text": "The metadata items an asset contains for common metadata identifiers that provide a value.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonMetadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/commonMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commonMetadata"
        }
      ],
      "role": "symbol",
      "title": "commonMetadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/commonmetadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/containsFragments": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether at least one movie fragment extends the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsFragments"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/containsFragments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsFragments"
        }
      ],
      "role": "symbol",
      "title": "containsFragments",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/containsfragments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/creationDate": {
      "abstract": [
        {
          "text": "A metadata item that indicates the asset’s creation date.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creationDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/creationDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creationDate"
        }
      ],
      "role": "symbol",
      "title": "creationDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/creationdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/duration": {
      "abstract": [
        {
          "text": "A time value that indicates the asset’s duration.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/duration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/hasProtectedContent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset contains protected content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasProtectedContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/hasProtectedContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasProtectedContent"
        }
      ],
      "role": "symbol",
      "title": "hasProtectedContent",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/hasprotectedcontent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithAirPlayVideo": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset is compatible with AirPlay Video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCompatibleWithAirPlayVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithAirPlayVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compatibleWithAirPlayVideo"
        }
      ],
      "role": "symbol",
      "title": "isCompatibleWithAirPlayVideo",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/iscompatiblewithairplayvideo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithSavedPhotosAlbum": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can write the asset to the Saved Photos album.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCompatibleWithSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithSavedPhotosAlbum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compatibleWithSavedPhotosAlbum"
        }
      ],
      "role": "symbol",
      "title": "isCompatibleWithSavedPhotosAlbum",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/iscompatiblewithsavedphotosalbum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isComposable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can use the asset as a segment of a composition track.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isComposable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isComposable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "composable"
        }
      ],
      "role": "symbol",
      "title": "isComposable",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/iscomposable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isExportable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can export this asset using an export session.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isExportable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isExportable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exportable"
        }
      ],
      "role": "symbol",
      "title": "isExportable",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/isexportable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isPlayable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset has playable content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlayable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isPlayable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playable"
        }
      ],
      "role": "symbol",
      "title": "isPlayable",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/isplayable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isReadable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can extract the asset’s media data using an asset reader.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReadable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isReadable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readable"
        }
      ],
      "role": "symbol",
      "title": "isReadable",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/isreadable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/lyrics": {
      "abstract": [
        {
          "text": "The lyrics of the asset in a language suitable for the current locale.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lyrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/lyrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lyrics"
        }
      ],
      "role": "symbol",
      "title": "lyrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/lyrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)": {
      "abstract": [
        {
          "text": "Returns a media selection group that contains one or more options with the specified media characteristic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSelectionGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelectionGroup",
          "text": "AVMediaSelectionGroup"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaSelectionGroupForMediaCharacteristic:"
        }
      ],
      "role": "symbol",
      "title": "mediaSelectionGroup(forMediaCharacteristic:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/mediaselectiongroup(formediacharacteristic:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata": {
      "abstract": [
        {
          "text": "An array of metadata items for all metadata identifiers for which a value is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/metadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata(forFormat:)": {
      "abstract": [
        {
          "text": "Returns an array of metadata items from the container with the specified format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataFormat",
          "text": "AVMetadataFormat"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata(forFormat:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForFormat:"
        }
      ],
      "role": "symbol",
      "title": "metadata(forFormat:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/metadata(forformat:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/minimumTimeOffsetFromLive": {
      "abstract": [
        {
          "text": "A time value that indicates how closely playback follows the latest live stream content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumTimeOffsetFromLive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/minimumTimeOffsetFromLive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumTimeOffsetFromLive"
        }
      ],
      "role": "symbol",
      "title": "minimumTimeOffsetFromLive",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/minimumtimeoffsetfromlive"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/naturalSize": {
      "abstract": [
        {
          "text": "The encoded or authored size of the visual portion of the asset.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/naturalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "naturalSize"
        }
      ],
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/naturalsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/overallDurationHint": {
      "abstract": [
        {
          "text": "The total duration of fragments that currently exist, or may exist in the future.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overallDurationHint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/overallDurationHint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overallDurationHint"
        }
      ],
      "role": "symbol",
      "title": "overallDurationHint",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/overalldurationhint"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredDisplayCriteria": {
      "abstract": [
        {
          "text": "The asset’s display mode preference for optimal playback of its content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredDisplayCriteria"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVDisplayCriteria",
          "text": "AVDisplayCriteria"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredDisplayCriteria",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredDisplayCriteria"
        }
      ],
      "role": "symbol",
      "title": "preferredDisplayCriteria",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/preferreddisplaycriteria"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredMediaSelection": {
      "abstract": [
        {
          "text": "The default media selections for this asset’s media selection groups.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredMediaSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelection",
          "text": "AVMediaSelection"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredMediaSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredMediaSelection"
        }
      ],
      "role": "symbol",
      "title": "preferredMediaSelection",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/preferredmediaselection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredRate": {
      "abstract": [
        {
          "text": "The asset’s rate preference for playing its media.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredRate"
        }
      ],
      "role": "symbol",
      "title": "preferredRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/preferredrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredTransform": {
      "abstract": [
        {
          "text": "The asset’s transform preference to apply to its visual content during presentation or processing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTransform"
        }
      ],
      "role": "symbol",
      "title": "preferredTransform",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/preferredtransform"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredVolume": {
      "abstract": [
        {
          "text": "The asset’s volume preference for playing its audible media.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredVolume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredVolume"
        }
      ],
      "role": "symbol",
      "title": "preferredVolume",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/preferredvolume"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/providesPreciseDurationAndTiming": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset provides precise duration and timing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "providesPreciseDurationAndTiming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/providesPreciseDurationAndTiming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "providesPreciseDurationAndTiming"
        }
      ],
      "role": "symbol",
      "title": "providesPreciseDurationAndTiming",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/providesprecisedurationandtiming"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/track(withTrackID:)": {
      "abstract": [
        {
          "text": "Returns a track that contains the specified identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "track"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTrackID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/track(withTrackID:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackWithTrackID:"
        }
      ],
      "role": "symbol",
      "title": "track(withTrackID:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/track(withtrackid:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/trackGroups": {
      "abstract": [
        {
          "text": "The track groups an asset contains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trackGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrackGroup",
          "text": "AVAssetTrackGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/trackGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trackGroups"
        }
      ],
      "role": "symbol",
      "title": "trackGroups",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/trackgroups"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks": {
      "abstract": [
        {
          "text": "The tracks an asset contains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tracks"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tracks"
        }
      ],
      "role": "symbol",
      "title": "tracks",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/tracks"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaCharacteristic:)": {
      "abstract": [
        {
          "text": "Returns an array of asset tracks matching the specified media characteristic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tracks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaCharacteristic:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tracksWithMediaCharacteristic:"
        }
      ],
      "role": "symbol",
      "title": "tracks(withMediaCharacteristic:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/tracks(withmediacharacteristic:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaType:)": {
      "abstract": [
        {
          "text": "Returns tracks that contain media of a specified type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tracks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withMediaType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tracksWithMediaType:"
        }
      ],
      "role": "symbol",
      "title": "tracks(withMediaType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/tracks(withmediatype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/unusedTrackID()": {
      "abstract": [
        {
          "text": "Returns an identifier that no other tracks in the asset use.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unusedTrackID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMPersistentTrackID",
          "text": "CMPersistentTrackID"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/unusedTrackID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unusedTrackID"
        }
      ],
      "role": "symbol",
      "title": "unusedTrackID()",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/unusedtrackid()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty": {
      "abstract": [
        {
          "text": "An asynchronous property that constrains its type and value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsyncProperty"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsyncProperty"
        }
      ],
      "role": "symbol",
      "title": "AVAsyncProperty",
      "type": "topic",
      "url": "/documentation/avfoundation/avasyncproperty"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading/load(_:)": {
      "abstract": [
        {
          "text": "Loads a property asynchronously and returns the value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">) "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading/load(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronouskeyvalueloading/load(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Accessing-Duration-and-Timing",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/duration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/providesPreciseDurationAndTiming",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/minimumTimeOffsetFromLive"
      ],
      "title": "Accessing Duration and Timing"
    },
    {
      "anchor": "Accessing-Tracks",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/track(withTrackID:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaType:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaCharacteristic:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/unusedTrackID()"
      ],
      "title": "Accessing Tracks"
    },
    {
      "anchor": "Accessing-Track-Groups",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/trackGroups"
      ],
      "title": "Accessing Track Groups"
    },
    {
      "anchor": "Accessing-Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/commonMetadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMetadataFormats",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata(forFormat:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/creationDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/lyrics"
      ],
      "title": "Accessing Metadata"
    },
    {
      "anchor": "Accessing-Suitability",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isPlayable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isExportable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isReadable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isComposable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithAirPlayVideo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithSavedPhotosAlbum"
      ],
      "title": "Accessing Suitability"
    },
    {
      "abstract": [
        {
          "text": "Prefer loading access preferences asynchronously using the properties in Loading Asset Preferences.",
          "type": "text"
        }
      ],
      "anchor": "Accessing-Asset-Preferences",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredRate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredVolume",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredTransform",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredDisplayCriteria",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredMediaSelection"
      ],
      "title": "Accessing Asset Preferences"
    },
    {
      "anchor": "Accessing-Media-Selections",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/allMediaSelections",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)"
      ],
      "title": "Accessing Media Selections"
    },
    {
      "anchor": "Accessing-Chapter-Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableChapterLocales",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(bestMatchingPreferredLanguages:)"
      ],
      "title": "Accessing Chapter Metadata"
    },
    {
      "anchor": "Accessing-Content-Protections",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/hasProtectedContent"
      ],
      "title": "Accessing Content Protections"
    },
    {
      "anchor": "Accessing-Fragment-Support",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/canContainFragments",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/containsFragments",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/overallDurationHint"
      ],
      "title": "Accessing Fragment Support"
    },
    {
      "anchor": "Inspecting-Visual-Attributes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/naturalSize"
      ],
      "title": "Inspecting Visual Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Duration-and-Timing",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/duration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/providesPreciseDurationAndTiming",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/minimumTimeOffsetFromLive"
              ],
              "title": "Accessing Duration and Timing"
            },
            {
              "anchor": "Accessing-Tracks",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/track(withTrackID:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaType:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/tracks(withMediaCharacteristic:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/unusedTrackID()"
              ],
              "title": "Accessing Tracks"
            },
            {
              "anchor": "Accessing-Track-Groups",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/trackGroups"
              ],
              "title": "Accessing Track Groups"
            },
            {
              "anchor": "Accessing-Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/commonMetadata",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMetadataFormats",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/metadata(forFormat:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/creationDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/lyrics"
              ],
              "title": "Accessing Metadata"
            },
            {
              "anchor": "Accessing-Suitability",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isPlayable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isExportable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isReadable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isComposable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithAirPlayVideo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/isCompatibleWithSavedPhotosAlbum"
              ],
              "title": "Accessing Suitability"
            },
            {
              "abstract": [
                {
                  "text": "Prefer loading access preferences asynchronously using the properties in Loading Asset Preferences.",
                  "type": "text"
                }
              ],
              "anchor": "Accessing-Asset-Preferences",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredRate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredVolume",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredTransform",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredDisplayCriteria",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/preferredMediaSelection"
              ],
              "title": "Accessing Asset Preferences"
            },
            {
              "anchor": "Accessing-Media-Selections",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/allMediaSelections",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)"
              ],
              "title": "Accessing Media Selections"
            },
            {
              "anchor": "Accessing-Chapter-Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableChapterLocales",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/chapterMetadataGroups(bestMatchingPreferredLanguages:)"
              ],
              "title": "Accessing Chapter Metadata"
            },
            {
              "anchor": "Accessing-Content-Protections",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/hasProtectedContent"
              ],
              "title": "Accessing Content Protections"
            },
            {
              "anchor": "Accessing-Fragment-Support",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/canContainFragments",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/containsFragments",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/overallDurationHint"
              ],
              "title": "Accessing Fragment Support"
            },
            {
              "anchor": "Inspecting-Visual-Attributes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/naturalSize"
              ],
              "title": "Inspecting Visual Attributes"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1lyrics/title",
          "value": "lyrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1lyrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lyrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1track(withTrackID:)/title",
          "value": "trackWithTrackID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1track(withTrackID:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "trackWithTrackID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1mediaSelectionGroup(forMediaCharacteristic:)/title",
          "value": "mediaSelectionGroupForMediaCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1mediaSelectionGroup(forMediaCharacteristic:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mediaSelectionGroupForMediaCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredVolume/title",
          "value": "preferredVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredVolume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1metadata(forFormat:)/title",
          "value": "metadataForFormat:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1metadata(forFormat:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "metadataForFormat:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1unusedTrackID()/title",
          "value": "unusedTrackID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1unusedTrackID()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unusedTrackID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1commonMetadata/title",
          "value": "commonMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1commonMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "commonMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks/title",
          "value": "tracks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tracks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1allMediaSelections/title",
          "value": "allMediaSelections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1allMediaSelections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allMediaSelections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1naturalSize/title",
          "value": "naturalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1naturalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "naturalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks(withMediaCharacteristic:)/title",
          "value": "tracksWithMediaCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks(withMediaCharacteristic:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tracksWithMediaCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1containsFragments/title",
          "value": "containsFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1containsFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "containsFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMediaCharacteristicsWithMediaSelectionOptions/title",
          "value": "availableMediaCharacteristicsWithMediaSelectionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMediaCharacteristicsWithMediaSelectionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)/title",
          "value": "chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1chapterMetadataGroups(withTitleLocale:containingItemsWithCommonKeys:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "chapterMetadataGroupsWithTitleLocale:containingItemsWithCommonKeys:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isReadable/title",
          "value": "readable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isReadable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isPlayable/title",
          "value": "playable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isPlayable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1chapterMetadataGroups(bestMatchingPreferredLanguages:)/title",
          "value": "chapterMetadataGroupsBestMatchingPreferredLanguages:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1chapterMetadataGroups(bestMatchingPreferredLanguages:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "chapterMetadataGroupsBestMatchingPreferredLanguages:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1creationDate/title",
          "value": "creationDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1creationDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "creationDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isExportable/title",
          "value": "exportable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isExportable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exportable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1hasProtectedContent/title",
          "value": "hasProtectedContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1hasProtectedContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasProtectedContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isCompatibleWithSavedPhotosAlbum/title",
          "value": "compatibleWithSavedPhotosAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isCompatibleWithSavedPhotosAlbum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compatibleWithSavedPhotosAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1overallDurationHint/title",
          "value": "overallDurationHint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1overallDurationHint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overallDurationHint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableChapterLocales/title",
          "value": "availableChapterLocales"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableChapterLocales/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableChapterLocales"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1minimumTimeOffsetFromLive/title",
          "value": "minimumTimeOffsetFromLive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1minimumTimeOffsetFromLive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumTimeOffsetFromLive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredMediaSelection/title",
          "value": "preferredMediaSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredMediaSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredMediaSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredRate/title",
          "value": "preferredRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1providesPreciseDurationAndTiming/title",
          "value": "providesPreciseDurationAndTiming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1providesPreciseDurationAndTiming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "providesPreciseDurationAndTiming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isComposable/title",
          "value": "composable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isComposable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "composable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1trackGroups/title",
          "value": "trackGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1trackGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trackGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1canContainFragments/title",
          "value": "canContainFragments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1canContainFragments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canContainFragments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredTransform/title",
          "value": "preferredTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks(withMediaType:)/title",
          "value": "tracksWithMediaType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1tracks(withMediaType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tracksWithMediaType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isCompatibleWithAirPlayVideo/title",
          "value": "compatibleWithAirPlayVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1isCompatibleWithAirPlayVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compatibleWithAirPlayVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/title",
          "value": "AVAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredDisplayCriteria/title",
          "value": "preferredDisplayCriteria"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1preferredDisplayCriteria/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredDisplayCriteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMetadataFormats/title",
          "value": "availableMetadataFormats"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMetadataFormats/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableMetadataFormats"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avasset-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avasset-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
