{
  "abstract": [
    {
      "text": "An object that provides media input from a capture device to a capture session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureDeviceInput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCaptureDeviceInput"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureDeviceInput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCaptureDeviceInput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class is a concrete subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you use to connect a capture device to a capture session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput": {
      "abstract": [
        {
          "text": "An object that provides media input from a capture device to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDeviceInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/device": {
      "abstract": [
        {
          "text": "A capture device associated with this input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/device",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "device"
        }
      ],
      "role": "symbol",
      "title": "device",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/device"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/deviceInputWithDevice:error:": {
      "abstract": [
        {
          "text": "Returns a new input for the specified capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "deviceInputWithDevice:error:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/deviceInputWithDevice:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceInputWithDevice:error:"
        }
      ],
      "role": "symbol",
      "title": "deviceInputWithDevice:error:",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/deviceinputwithdevice:error:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/init(device:)": {
      "abstract": [
        {
          "text": "Creates an input for the specified capture device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "device"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/init(device:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDevice:error:"
        }
      ],
      "role": "symbol",
      "title": "init(device:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/init(device:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isMultichannelAudioModeSupported(_:)": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the input supports the specified multichannel audio mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMultichannelAudioModeSupported"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureMultichannelAudioMode",
          "text": "AVCaptureMultichannelAudioMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isMultichannelAudioModeSupported(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isMultichannelAudioModeSupported:"
        }
      ],
      "role": "symbol",
      "title": "isMultichannelAudioModeSupported(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/ismultichannelaudiomodesupported(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalEnabled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWindNoiseRemovalEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windNoiseRemovalEnabled"
        }
      ],
      "role": "symbol",
      "title": "isWindNoiseRemovalEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/iswindnoiseremovalenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalSupported": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isWindNoiseRemovalSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windNoiseRemovalSupported"
        }
      ],
      "role": "symbol",
      "title": "isWindNoiseRemovalSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/iswindnoiseremovalsupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/multichannelAudioMode": {
      "abstract": [
        {
          "text": "The multichannel audio mode to apply when recording audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multichannelAudioMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureMultichannelAudioMode",
          "text": "AVCaptureMultichannelAudioMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/multichannelAudioMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multichannelAudioMode"
        }
      ],
      "role": "symbol",
      "title": "multichannelAudioMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/multichannelaudiomode"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/ports(for:sourceDeviceType:sourceDevicePosition:)": {
      "abstract": [
        {
          "text": "Retrieves a virtual device’s constituent device ports for use in a multi-camera session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ports"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "sourceDeviceType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureDeviceType",
          "text": "DeviceType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "sourceDevicePosition"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
          "text": "Position"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureInput",
          "text": "AVCaptureInput"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureInputPort",
          "text": "Port"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/ports(for:sourceDeviceType:sourceDevicePosition:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portsWithMediaType:sourceDeviceType:sourceDevicePosition:"
        }
      ],
      "role": "symbol",
      "title": "ports(for:sourceDeviceType:sourceDevicePosition:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/ports(for:sourcedevicetype:sourcedeviceposition:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/unifiedAutoExposureDefaultsEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the input enables unified auto-exposure defaults.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unifiedAutoExposureDefaultsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/unifiedAutoExposureDefaultsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unifiedAutoExposureDefaultsEnabled"
        }
      ],
      "role": "symbol",
      "title": "unifiedAutoExposureDefaultsEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/unifiedautoexposuredefaultsenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/videoMinFrameDurationOverride": {
      "abstract": [
        {
          "text": "A time value that acts as a modifier to a capture device’s active video minimum frame duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoMinFrameDurationOverride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/videoMinFrameDurationOverride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoMinFrameDurationOverride"
        }
      ],
      "role": "symbol",
      "title": "videoMinFrameDurationOverride",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput/videominframedurationoverride"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput": {
      "abstract": [
        {
          "text": "An abstract superclass for objects that provide input data to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMultichannelAudioMode": {
      "abstract": [
        {
          "text": "Constants that indicate the modes of multichannel audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMultichannelAudioMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMultichannelAudioMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMultichannelAudioMode"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMultichannelAudioMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemultichannelaudiomode"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice": {
      "abstract": [
        {
          "text": "A class that represents a physical iOS device that’s nearby and can provide access to its cameras and microphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontinuitydevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice": {
      "abstract": [
        {
          "text": "Represents a physical external storage device that stores media assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession": {
      "abstract": [
        {
          "text": "Informs your app when the external storage devices connect to and disconnect from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDeviceDiscoverySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevicediscoverysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device": {
      "abstract": [
        {
          "text": "Select the front or back camera, or use advanced features like the TrueDepth camera or dual camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Capture Device",
      "type": "topic",
      "url": "/documentation/avfoundation/choosing-a-capture-device"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session": {
      "abstract": [
        {
          "text": "Configure input devices, output media, preview views, and basic settings before capturing photos or video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Capture Session",
      "type": "topic",
      "url": "/documentation/avfoundation/setting-up-a-capture-session"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capture-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
      ],
      "title": "Capture devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-input",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/init(device:)"
      ],
      "title": "Creating an input"
    },
    {
      "anchor": "Configuring-video-properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/unifiedAutoExposureDefaultsEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/videoMinFrameDurationOverride"
      ],
      "title": "Configuring video properties"
    },
    {
      "anchor": "Configuring-audio-properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isMultichannelAudioModeSupported(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/multichannelAudioMode",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMultichannelAudioMode"
      ],
      "title": "Configuring audio properties"
    },
    {
      "anchor": "Accessing-the-Device",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/device",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/ports(for:sourceDeviceType:sourceDevicePosition:)"
      ],
      "title": "Accessing the Device"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalSupported"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureDeviceInput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-input",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/deviceInputWithDevice:error:",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/init(device:)"
              ],
              "title": "Creating an input"
            },
            {
              "anchor": "Configuring-video-properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/unifiedAutoExposureDefaultsEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/videoMinFrameDurationOverride"
              ],
              "title": "Configuring video properties"
            },
            {
              "anchor": "Configuring-audio-properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isMultichannelAudioModeSupported(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/multichannelAudioMode",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMultichannelAudioMode"
              ],
              "title": "Configuring audio properties"
            },
            {
              "anchor": "Accessing-the-Device",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/device",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/ports(for:sourceDeviceType:sourceDevicePosition:)"
              ],
              "title": "Accessing the Device"
            },
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput/isWindNoiseRemovalSupported"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capture-devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
              ],
              "title": "Capture devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptureDeviceInput"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureInput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCaptureInput",
                    "text": "AVCaptureInput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1videoMinFrameDurationOverride/title",
          "value": "videoMinFrameDurationOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1videoMinFrameDurationOverride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoMinFrameDurationOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1ports(for:sourceDeviceType:sourceDevicePosition:)/title",
          "value": "portsWithMediaType:sourceDeviceType:sourceDevicePosition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1ports(for:sourceDeviceType:sourceDevicePosition:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "portsWithMediaType:sourceDeviceType:sourceDevicePosition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1device/title",
          "value": "device"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1device/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/title",
          "value": "AVContinuityDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/title",
          "value": "AVCaptureInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/title",
          "value": "AVExternalStorageDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1multichannelAudioMode/title",
          "value": "multichannelAudioMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1multichannelAudioMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "multichannelAudioMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isMultichannelAudioModeSupported(_:)/title",
          "value": "isMultichannelAudioModeSupported:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isMultichannelAudioModeSupported(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isMultichannelAudioModeSupported:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/title",
          "value": "AVCaptureDeviceInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMultichannelAudioMode/title",
          "value": "AVCaptureMultichannelAudioMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMultichannelAudioMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMultichannelAudioMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMultichannelAudioMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMultichannelAudioMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1unifiedAutoExposureDefaultsEnabled/title",
          "value": "unifiedAutoExposureDefaultsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1unifiedAutoExposureDefaultsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unifiedAutoExposureDefaultsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isWindNoiseRemovalEnabled/title",
          "value": "windNoiseRemovalEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isWindNoiseRemovalEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windNoiseRemovalEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isWindNoiseRemovalSupported/title",
          "value": "windNoiseRemovalSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1isWindNoiseRemovalSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windNoiseRemovalSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1init(device:)/title",
          "value": "initWithDevice:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput~1init(device:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDevice:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/title",
          "value": "AVExternalStorageDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturedeviceinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturedeviceinput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
