{
  "abstract": [
    {
      "text": "A control for selecting from a set of mutually exclusive values by index.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureIndexPicker",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCaptureIndexPicker"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureIndexPicker"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCaptureIndexPicker"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureIndexPicker"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Index pickers are appropriate for controls that provide an indexed container of values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl": {
      "abstract": [
        {
          "text": "An abstract base class for controls that interact with the camera system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureControl"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureControl"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureControl",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturecontrol"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker": {
      "abstract": [
        {
          "text": "A control for selecting from a set of mutually exclusive values by index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureIndexPicker"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureIndexPicker"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureIndexPicker",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/accessibilityIdentifier": {
      "abstract": [
        {
          "text": "A string identifier for this control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/accessibilityIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityIdentifier"
        }
      ],
      "role": "symbol",
      "title": "accessibilityIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/accessibilityidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:localizedIndexTitles:)": {
      "abstract": [
        {
          "text": "Creates an object to select an index from a set of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "symbolName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedIndexTitles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:localizedIndexTitles:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedTitle:symbolName:localizedIndexTitles:"
        }
      ],
      "role": "symbol",
      "title": "init(_:symbolName:localizedIndexTitles:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/init(_:symbolname:localizedindextitles:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:)": {
      "abstract": [
        {
          "text": "Creates a control to pick a value from the specified number of indexes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "symbolName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfIndexes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedTitle:symbolName:numberOfIndexes:"
        }
      ],
      "role": "symbol",
      "title": "init(_:symbolName:numberOfIndexes:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/init(_:symbolname:numberofindexes:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:localizedTitleTransform:)": {
      "abstract": [
        {
          "text": "Creates a control to pick a value from the specified number of indices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "symbolName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "numberOfIndexes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedTitleTransform"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:localizedTitleTransform:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedTitle:symbolName:numberOfIndexes:localizedTitleTransform:"
        }
      ],
      "role": "symbol",
      "title": "init(_:symbolName:numberOfIndexes:localizedTitleTransform:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/init(_:symbolname:numberofindexes:localizedtitletransform:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedIndexTitles": {
      "abstract": [
        {
          "text": "The titles to present for each index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedIndexTitles"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedIndexTitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedIndexTitles"
        }
      ],
      "role": "symbol",
      "title": "localizedIndexTitles",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/localizedindextitles"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedTitle": {
      "abstract": [
        {
          "text": "A localized title that describes the control’s action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedTitle"
        }
      ],
      "role": "symbol",
      "title": "localizedTitle",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/localizedtitle"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/numberOfIndexes": {
      "abstract": [
        {
          "text": "The number of index values the control provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfIndexes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/numberOfIndexes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfIndexes"
        }
      ],
      "role": "symbol",
      "title": "numberOfIndexes",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/numberofindexes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/selectedIndex": {
      "abstract": [
        {
          "text": "The currently selected index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/selectedIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedIndex"
        }
      ],
      "role": "symbol",
      "title": "selectedIndex",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/selectedindex"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue(_:action:)": {
      "abstract": [
        {
          "text": "Sets the action to perform on the specified dispatch queue when the control’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setActionQueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)OS_dispatch_queue",
          "text": "DispatchQueue"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ())"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue(_:action:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setActionQueue(_:action:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/setactionqueue(_:action:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue:action:": {
      "abstract": [
        {
          "text": "Sets the action to perform on the specified dispatch queue when the control’s value changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setActionQueue:action:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue:action:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setActionQueue:action:"
        }
      ],
      "role": "symbol",
      "title": "setActionQueue:action:",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/setactionqueue:action:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/symbolName": {
      "abstract": [
        {
          "text": "The name of the SF Symbol that represents this control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/symbolName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "symbolName"
        }
      ],
      "role": "symbol",
      "title": "symbolName",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureindexpicker/symbolname"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider": {
      "abstract": [
        {
          "text": "A slider control that selects a value from a bounded range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSlider"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSlider"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSlider",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureslider"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider": {
      "abstract": [
        {
          "text": "A control that adjusts the exposure bias of a capture device within the system-recommended range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSystemExposureBiasSlider"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSystemExposureBiasSlider"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSystemExposureBiasSlider",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesystemexposurebiasslider"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider": {
      "abstract": [
        {
          "text": "A control that adjusts the video zoom factor of a capture device within the system-recommended range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSystemZoomSlider"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSystemZoomSlider"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSystemZoomSlider",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesystemzoomslider"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control": {
      "abstract": [
        {
          "text": "Provide direct access to your camera app’s features to help people quickly capture the perfect shot.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control",
      "kind": "article",
      "role": "article",
      "title": "Enhancing your app experience with the Camera Control",
      "type": "topic",
      "url": "/documentation/avfoundation/enhancing-your-app-experience-with-the-camera-control"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capture-controls",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider"
      ],
      "title": "Capture controls"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-index-picker",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:localizedTitleTransform:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:localizedIndexTitles:)"
      ],
      "title": "Creating an index picker"
    },
    {
      "anchor": "Handling-interaction",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue(_:action:)"
      ],
      "title": "Handling interaction"
    },
    {
      "anchor": "Accessing-the-control-value",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/selectedIndex",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/numberOfIndexes"
      ],
      "title": "Accessing the control value"
    },
    {
      "anchor": "Setting-an-accessibility-identifier",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/accessibilityIdentifier"
      ],
      "title": "Setting an accessibility identifier"
    },
    {
      "anchor": "Inspecting-presentation-attributes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/symbolName",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedTitle",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedIndexTitles"
      ],
      "title": "Inspecting presentation attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureIndexPicker"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureIndexPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureIndexPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-index-picker",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:numberOfIndexes:localizedTitleTransform:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/init(_:symbolName:localizedIndexTitles:)"
              ],
              "title": "Creating an index picker"
            },
            {
              "anchor": "Handling-interaction",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/setActionQueue:action:"
              ],
              "title": "Handling interaction"
            },
            {
              "anchor": "Accessing-the-control-value",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/selectedIndex",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/numberOfIndexes"
              ],
              "title": "Accessing the control value"
            },
            {
              "anchor": "Setting-an-accessibility-identifier",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/accessibilityIdentifier"
              ],
              "title": "Setting an accessibility identifier"
            },
            {
              "anchor": "Inspecting-presentation-attributes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/symbolName",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedTitle",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker/localizedIndexTitles"
              ],
              "title": "Inspecting presentation attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capture-controls",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider"
              ],
              "title": "Capture controls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptureIndexPicker"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCaptureControl",
                    "text": "AVCaptureControl"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/title",
          "value": "AVCaptureSystemZoomSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemZoomSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemZoomSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:localizedIndexTitles:)/title",
          "value": "initWithLocalizedTitle:symbolName:localizedIndexTitles:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:localizedIndexTitles:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedTitle:symbolName:localizedIndexTitles:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1localizedTitle/title",
          "value": "localizedTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1localizedTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1localizedIndexTitles/title",
          "value": "localizedIndexTitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1localizedIndexTitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedIndexTitles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/title",
          "value": "AVCaptureIndexPicker"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureIndexPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureIndexPicker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1numberOfIndexes/title",
          "value": "numberOfIndexes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1numberOfIndexes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfIndexes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1symbolName/title",
          "value": "symbolName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1symbolName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "symbolName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1selectedIndex/title",
          "value": "selectedIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1selectedIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/title",
          "value": "AVCaptureControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:numberOfIndexes:localizedTitleTransform:)/title",
          "value": "initWithLocalizedTitle:symbolName:numberOfIndexes:localizedTitleTransform:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:numberOfIndexes:localizedTitleTransform:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedTitle:symbolName:numberOfIndexes:localizedTitleTransform:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:numberOfIndexes:)/title",
          "value": "initWithLocalizedTitle:symbolName:numberOfIndexes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1init(_:symbolName:numberOfIndexes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedTitle:symbolName:numberOfIndexes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/title",
          "value": "AVCaptureSystemExposureBiasSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemExposureBiasSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemExposureBiasSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1accessibilityIdentifier/title",
          "value": "accessibilityIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker~1accessibilityIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/title",
          "value": "AVCaptureSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureindexpicker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureindexpicker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
