{
  "abstract": [
    {
      "text": "A capture output that records audio and saves the recorded audio to a file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptureAudioFileOutput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCaptureAudioFileOutput"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureAudioFileOutput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCaptureAudioFileOutput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureAudioFileOutput"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "AVCaptureAudioFileOutput",
              "type": "codeVoice"
            },
            {
              "text": " implements the complete file recording interface declared by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for writing media data to audio files. In addition, you can configure options specific to the audio file formats, including writing metadata collections to each file and specifying audio encoding options. ",
              "type": "text"
            },
            {
              "code": "AVCaptureAudioFileOutput",
              "type": "codeVoice"
            },
            {
              "text": " does not, however, support ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput/startRecording(to:recordingDelegate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "—use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/startRecording(to:outputFileType:recordingDelegate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput": {
      "abstract": [
        {
          "text": "A capture output that records audio and saves the recorded audio to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureAudioFileOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureAudioFileOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureAudioFileOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/audioSettings": {
      "abstract": [
        {
          "text": "The settings used to decode or re-encode audio before it is output by the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/audioSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audioSettings"
        }
      ],
      "role": "symbol",
      "title": "audioSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/audiosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/availableOutputFileTypes()": {
      "abstract": [
        {
          "text": "Returns an array containing UTIs identifying the file types ",
          "type": "text"
        },
        {
          "code": "AVCaptureAudioFileOutput",
          "type": "codeVoice"
        },
        {
          "text": " can write.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableOutputFileTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/availableOutputFileTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableOutputFileTypes"
        }
      ],
      "role": "symbol",
      "title": "availableOutputFileTypes()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/availableoutputfiletypes()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/init()": {
      "abstract": [
        {
          "text": "Creates a new audio file output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/init()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/metadata": {
      "abstract": [
        {
          "text": "A collection of metadata to be written to the receiver’s output files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/metadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadata"
        }
      ],
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/metadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/new": {
      "abstract": [
        {
          "text": "Creates a new audio file output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/new",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "new"
        }
      ],
      "role": "symbol",
      "title": "new",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/new"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/startRecording(to:outputFileType:recordingDelegate:)": {
      "abstract": [
        {
          "text": "Tells the receiver to start recording to a new file of the specified format, and specifies a delegate that will be notified when recording is finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "outputFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recordingDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCaptureFileOutputRecordingDelegate",
          "text": "AVCaptureFileOutputRecordingDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/startRecording(to:outputFileType:recordingDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startRecordingToOutputFileURL:outputFileType:recordingDelegate:"
        }
      ],
      "role": "symbol",
      "title": "startRecording(to:outputFileType:recordingDelegate:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureaudiofileoutput/startrecording(to:outputfiletype:recordingdelegate:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput": {
      "abstract": [
        {
          "text": "The abstract superclass for capture outputs that can record captured data to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureFileOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturefileoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput/startRecording(to:recordingDelegate:)": {
      "abstract": [
        {
          "text": "Starts recording media to the specified output URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startRecording"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recordingDelegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCaptureFileOutputRecordingDelegate",
          "text": "AVCaptureFileOutputRecordingDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput/startRecording(to:recordingDelegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startRecordingToOutputFileURL:recordingDelegate:"
        }
      ],
      "role": "symbol",
      "title": "startRecording(to:recordingDelegate:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturefileoutput/startrecording(to:recordingdelegate:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputDelegate": {
      "abstract": [
        {
          "text": "Methods for monitoring or controlling the output of a media file capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutputDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutputDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureFileOutputDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturefileoutputdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputRecordingDelegate": {
      "abstract": [
        {
          "text": "Methods for responding to events that occur while recording captured media to a file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutputRecordingDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputRecordingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureFileOutputRecordingDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureFileOutputRecordingDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturefileoutputrecordingdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput": {
      "abstract": [
        {
          "text": "A capture output that records video and audio to a QuickTime movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMovieFileOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMovieFileOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMovieFileOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemoviefileoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats": {
      "abstract": [
        {
          "text": "Change the default format for capturing movie files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats",
      "kind": "article",
      "role": "article",
      "title": "Recording movies in alternative formats",
      "type": "topic",
      "url": "/documentation/avfoundation/recording-movies-in-alternative-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputDelegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputRecordingDelegate"
      ],
      "title": "File capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Discovering-Supported-Types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/availableOutputFileTypes()"
      ],
      "title": "Discovering Supported Types"
    },
    {
      "anchor": "Starting-a-Recording",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/startRecording(to:outputFileType:recordingDelegate:)"
      ],
      "title": "Starting a Recording"
    },
    {
      "anchor": "Configuring-Output",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/audioSettings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/metadata"
      ],
      "title": "Configuring Output"
    },
    {
      "anchor": "Creating-Output",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/init()"
      ],
      "title": "Creating Output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureAudioFileOutput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Discovering-Supported-Types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/availableOutputFileTypes()"
              ],
              "title": "Discovering Supported Types"
            },
            {
              "anchor": "Starting-a-Recording",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/startRecording(to:outputFileType:recordingDelegate:)"
              ],
              "title": "Starting a Recording"
            },
            {
              "anchor": "Configuring-Output",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/audioSettings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/metadata"
              ],
              "title": "Configuring Output"
            },
            {
              "anchor": "Creating-Output",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/init()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAudioFileOutput/new"
              ],
              "title": "Creating Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputDelegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutputRecordingDelegate"
              ],
              "title": "File capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptureAudioFileOutput"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureFileOutput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCaptureFileOutput",
                    "text": "AVCaptureFileOutput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1availableOutputFileTypes()/title",
          "value": "availableOutputFileTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1availableOutputFileTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "availableOutputFileTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputDelegate/title",
          "value": "AVCaptureFileOutputDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutputDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1metadata/title",
          "value": "metadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1audioSettings/title",
          "value": "audioSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1audioSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "audioSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1startRecording(to:outputFileType:recordingDelegate:)/title",
          "value": "startRecordingToOutputFileURL:outputFileType:recordingDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput~1startRecording(to:outputFileType:recordingDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startRecordingToOutputFileURL:outputFileType:recordingDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput/title",
          "value": "AVCaptureAudioFileOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAudioFileOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAudioFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutput/title",
          "value": "AVCaptureFileOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputRecordingDelegate/title",
          "value": "AVCaptureFileOutputRecordingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputRecordingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutputRecordingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutputRecordingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureFileOutputRecordingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutput~1startRecording(to:recordingDelegate:)/title",
          "value": "startRecordingToOutputFileURL:recordingDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureFileOutput~1startRecording(to:recordingDelegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startRecordingToOutputFileURL:recordingDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/title",
          "value": "AVCaptureMovieFileOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMovieFileOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMovieFileOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptureaudiofileoutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptureaudiofileoutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
