{
  "abstract": [
    {
      "text": "A specification of the features and settings to use for a photo capture request that captures multiple images with varied settings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCapturePhotoBracketSettings",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCapturePhotoBracketSettings"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCapturePhotoBracketSettings"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCapturePhotoBracketSettings"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCapturePhotoBracketSettings"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To take a bracketed capture, you create and configure an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects to describe the individual captures in the bracket, and then pass it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To request a bracketed capture, follow these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create an array of ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " objects describing the number of images to capture in the bracket and the variations on capture settings between them.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a bracketed photo settings object with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:processedFormat:bracketedSettings:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " initializer, passing the array of bracketed still image settings, along with the processed format (such as JPEG) or RAW format to capture images in.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure other settings to share across all images in the bracket, such as the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/isLensStabilizationEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property and certain inherited properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Bracketed capture supports only the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/isHighResolutionPhotoEnabled",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/previewPhotoFormat",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " settings defined by the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " superclass. Bracketed capture does not support flash, auto stabilization, or Live Photos—attempting to set any of the corresponding properties raises an exception.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Initiate capture by passing the bracketed photo settings object to your photo output’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method, along with a delegate object to receive messages about the progress and results of the capture.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 4,
          "type": "orderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Capturing a multiple-image bracket may require allocation of additional resources. See the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/setPreparedPhotoSettingsArray(_:completionHandler:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The photo output calls your delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " methods many times corresponding to the number of captures in the bracket. Each call provides the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object indicating which capture in the bracket the captured image corresponds to.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "start": 5,
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code example illustrates capturing a bracket of three RAW images with varying exposure value settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Listing 1. Capturing a Multi-Exposure Bracket",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func captureRAWAutoExposureBracket() {",
                    "    guard myCapturePhotoOutput.maxBracketedCapturePhotoCount >= 3 else { return }",
                    "    ",
                    "    // Specify a 3-shot bracket, where exposure compensation varies between each shot.",
                    "    let makeSettings = AVCaptureAutoExposureBracketedStillImageSettings.autoExposureSettingsWithExposureTargetBias",
                    "    let bracketedStillImageSettings = [-2, 0, 2].map { makeSettings(Float($0))! }",
                    "    let rawFormat = myCapturePhotoOutput.availableRawPhotoCVPixelFormatTypes.first!.unsignedIntValue as OSType",
                    "    ",
                    "    let settings = AVCapturePhotoBracketSettings(format: nil, rawPixelFormatType: rawFormat, bracketedSettings: bracketedStillImageSettings)",
                    "    settings.lensStabilizationEnabled = myCapturePhotoOutput.lensStabilizationDuringBracketedCaptureSupported",
                    "    ",
                    "    myCapturePhotoOutput.capturePhotoWithSettings(settings, delegate: self)",
                    "    // Three RAW photos will be delivered.",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)captureRAWAutoExposureBracket {",
                    "    if ( myCapturePhotoOutput.maxBracketedCapturePhotoCount < 3 ) { return; }",
                    " ",
                    "    // Specify a 3-shot bracket, where exposure compensation varies between each shot.",
                    "    NSArray *bracketedStillImageSettings = @[ [AVCaptureAutoExposureBracketedStillImageSettings autoExposureSettingsWithExposureTargetBias:-2.],",
                    "                              [AVCaptureAutoExposureBracketedStillImageSettings autoExposureSettingsWithExposureTargetBias:0.],",
                    "                              [AVCaptureAutoExposureBracketedStillImageSettings autoExposureSettingsWithExposureTargetBias:2.] ];",
                    "     OSType rawFormat = [[myCapturePhotoOutput.availableRawPhotoCVPixelFormatTypes firstObject] intValue];",
                    " ",
                    "    AVCapturePhotoBracketSettings *settings = [[AVCapturePhotoBracketSettings alloc] initWithFormat:nil rawPixelFormatType:rawFormat bracketedSettings:bracketedStillImageSettings];",
                    "    settings.lensStabilizationEnabled = myCapturePhotoOutput.isLensStabilizationDuringBracketedCaptureSupported;",
                    " ",
                    "    [myCapturePhotoOutput capturePhotoWithSettings:settings delegate:self];",
                    "    // Three RAW photos will be delivered to the delegate.",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAutoExposureBracketedStillImageSettings": {
      "abstract": [
        {
          "text": "A configuration for defining bracketed photo captures in terms of bias relative to automatic exposure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureAutoExposureBracketedStillImageSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAutoExposureBracketedStillImageSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureAutoExposureBracketedStillImageSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureAutoExposureBracketedStillImageSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureautoexposurebracketedstillimagesettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings": {
      "abstract": [
        {
          "text": "The abstract superclass for bracketed photo capture settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureBracketedStillImageSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureBracketedStillImageSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureBracketedStillImageSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturebracketedstillimagesettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureManualExposureBracketedStillImageSettings": {
      "abstract": [
        {
          "text": "A configuration for defining bracketed photo captures in terms of specific exposure and ISO values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureManualExposureBracketedStillImageSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureManualExposureBracketedStillImageSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureManualExposureBracketedStillImageSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureManualExposureBracketedStillImageSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemanualexposurebracketedstillimagesettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings": {
      "abstract": [
        {
          "text": "A specification of the features and settings to use for a photo capture request that captures multiple images with varied settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoBracketSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoBracketSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoBracketSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotobracketsettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/bracketedSettings": {
      "abstract": [
        {
          "text": "An array describing the number of and settings for images to produce in a bracketed capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bracketedSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/bracketedSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bracketedSettings"
        }
      ],
      "role": "symbol",
      "title": "bracketedSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotobracketsettings/bracketedsettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:processedFormat:bracketedSettings:)": {
      "abstract": [
        {
          "text": "Creates a photo settings object for the specified bracket of captures, in the specified formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawPixelFormatType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "processedFormat"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "bracketedSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:processedFormat:bracketedSettings:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoBracketSettingsWithRawPixelFormatType:processedFormat:bracketedSettings:"
        }
      ],
      "role": "symbol",
      "title": "init(rawPixelFormatType:processedFormat:bracketedSettings:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotobracketsettings/init(rawpixelformattype:processedformat:bracketedsettings:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)": {
      "abstract": [
        {
          "text": "Creates a photo settings object for capture in both RAW format and a processed format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawPixelFormatType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rawFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "processedFormat"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "processedFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "bracketedSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoBracketSettingsWithRawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:"
        }
      ],
      "role": "symbol",
      "title": "init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotobracketsettings/init(rawpixelformattype:rawfiletype:processedformat:processedfiletype:bracketedsettings:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/isLensStabilizationEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to stabilize the lens for the duration of the bracketed capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLensStabilizationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/isLensStabilizationEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lensStabilizationEnabled"
        }
      ],
      "role": "symbol",
      "title": "isLensStabilizationEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotobracketsettings/islensstabilizationenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate a captured image in a processed format (such as JPEG).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "previewPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "resolvedSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureResolvedPhotoSettings",
          "text": "AVCaptureResolvedPhotoSettings"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bracketSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessingphoto:previewphoto:resolvedsettings:bracketsettings:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate a captured image in RAW format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingRawPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "previewPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "resolvedSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureResolvedPhotoSettings",
          "text": "AVCaptureResolvedPhotoSettings"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "bracketSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureBracketedStillImageSettings",
          "text": "AVCaptureBracketedStillImageSettings"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingRawPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessingrawphoto:previewphoto:resolvedsettings:bracketsettings:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput": {
      "abstract": [
        {
          "text": "A capture output for still image, Live Photos, and other photography workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)": {
      "abstract": [
        {
          "text": "Initiates a photo capture using the specified settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capturePhoto"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoSettings",
          "text": "AVCapturePhotoSettings"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCapturePhotoCaptureDelegate",
          "text": "AVCapturePhotoCaptureDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capturePhotoWithSettings:delegate:"
        }
      ],
      "role": "symbol",
      "title": "capturePhoto(with:delegate:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturephoto(with:delegate:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/setPreparedPhotoSettingsArray(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the photo capture output to prepare resources for future capture requests with the specified settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPreparedPhotoSettingsArray"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoSettings",
          "text": "AVCapturePhotoSettings"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/setPreparedPhotoSettingsArray(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPreparedPhotoSettingsArray:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "setPreparedPhotoSettingsArray(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/setpreparedphotosettingsarray(_:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings": {
      "abstract": [
        {
          "text": "A specification of the features and settings to use for a single photo capture request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/isHighResolutionPhotoEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether to capture still images at the highest resolution supported by the active device and format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHighResolutionPhotoEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/isHighResolutionPhotoEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highResolutionPhotoEnabled"
        }
      ],
      "role": "symbol",
      "title": "isHighResolutionPhotoEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotosettings/ishighresolutionphotoenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/previewPhotoFormat": {
      "abstract": [
        {
          "text": "A dictionary describing the format for delivery of preview-sized images alongside the main photo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewPhotoFormat"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/previewPhotoFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewPhotoFormat"
        }
      ],
      "role": "symbol",
      "title": "previewPhotoFormat",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotosettings/previewphotoformat"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings": {
      "abstract": [
        {
          "text": "A description of the features and settings in use for an in-progress or complete photo capture request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureResolvedPhotoSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureResolvedPhotoSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptureresolvedphotosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence": {
      "abstract": [
        {
          "text": "Capture several photos at once, varying parameters like exposure duration or light sensitivity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence",
      "kind": "article",
      "role": "article",
      "title": "Capturing a Bracketed Photo Sequence",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-a-bracketed-photo-sequence"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photo-settings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
      ],
      "title": "Photo settings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Bracket-Settings-Object",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:processedFormat:bracketedSettings:)"
      ],
      "title": "Creating a Bracket Settings Object"
    },
    {
      "anchor": "Working-with-Bracketed-Settings",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/bracketedSettings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/isLensStabilizationEnabled"
      ],
      "title": "Working with Bracketed Settings"
    },
    {
      "anchor": "Bracketed-Settings-Types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAutoExposureBracketedStillImageSettings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureManualExposureBracketedStillImageSettings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings"
      ],
      "title": "Bracketed Settings Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCapturePhotoBracketSettings"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoBracketSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoBracketSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Bracket-Settings-Object",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/init(rawPixelFormatType:processedFormat:bracketedSettings:)"
              ],
              "title": "Creating a Bracket Settings Object"
            },
            {
              "anchor": "Working-with-Bracketed-Settings",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/bracketedSettings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoBracketSettings/isLensStabilizationEnabled"
              ],
              "title": "Working with Bracketed Settings"
            },
            {
              "anchor": "Bracketed-Settings-Types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureAutoExposureBracketedStillImageSettings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureManualExposureBracketedStillImageSettings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureBracketedStillImageSettings"
              ],
              "title": "Bracketed Settings Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Photo-settings",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureResolvedPhotoSettings"
              ],
              "title": "Photo settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCapturePhotoBracketSettings"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVCapturePhotoSettings",
                    "text": "AVCapturePhotoSettings"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)/title",
          "value": "captureOutput:didFinishProcessingRawPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingRawPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingRawPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/title",
          "value": "capturePhotoWithSettings:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "capturePhotoWithSettings:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/title",
          "value": "AVCaptureResolvedPhotoSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureResolvedPhotoSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureResolvedPhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1previewPhotoFormat/title",
          "value": "previewPhotoFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1previewPhotoFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewPhotoFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/title",
          "value": "AVCapturePhotoSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/title",
          "value": "AVCaptureBracketedStillImageSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureBracketedStillImageSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings/title",
          "value": "AVCapturePhotoBracketSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoBracketSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoBracketSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/title",
          "value": "AVCapturePhotoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1bracketedSettings/title",
          "value": "bracketedSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1bracketedSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bracketedSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1isHighResolutionPhotoEnabled/title",
          "value": "highResolutionPhotoEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1isHighResolutionPhotoEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highResolutionPhotoEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1setPreparedPhotoSettingsArray(_:completionHandler:)/title",
          "value": "setPreparedPhotoSettingsArray:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1setPreparedPhotoSettingsArray(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPreparedPhotoSettingsArray:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureManualExposureBracketedStillImageSettings/title",
          "value": "AVCaptureManualExposureBracketedStillImageSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureManualExposureBracketedStillImageSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureManualExposureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureManualExposureBracketedStillImageSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureManualExposureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1isLensStabilizationEnabled/title",
          "value": "lensStabilizationEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1isLensStabilizationEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lensStabilizationEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)/title",
          "value": "photoBracketSettingsWithRawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1init(rawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "photoBracketSettingsWithRawPixelFormatType:rawFileType:processedFormat:processedFileType:bracketedSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1init(rawPixelFormatType:processedFormat:bracketedSettings:)/title",
          "value": "photoBracketSettingsWithRawPixelFormatType:processedFormat:bracketedSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoBracketSettings~1init(rawPixelFormatType:processedFormat:bracketedSettings:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "photoBracketSettingsWithRawPixelFormatType:processedFormat:bracketedSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAutoExposureBracketedStillImageSettings/title",
          "value": "AVCaptureAutoExposureBracketedStillImageSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAutoExposureBracketedStillImageSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAutoExposureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureAutoExposureBracketedStillImageSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureAutoExposureBracketedStillImageSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)/title",
          "value": "captureOutput:didFinishProcessingPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:previewPhoto:resolvedSettings:bracketSettings:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingPhotoSampleBuffer:previewPhotoSampleBuffer:resolvedSettings:bracketSettings:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotobracketsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotobracketsettings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
