{
  "abstract": [
    {
      "text": "A protocol that defines the methods to implement to customize the packaging of photo data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVCapturePhotoFileDataRepresentationCustomizer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCapturePhotoFileDataRepresentationCustomizer"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCapturePhotoFileDataRepresentationCustomizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVCapturePhotoFileDataRepresentationCustomizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCapturePhotoFileDataRepresentationCustomizer"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AVCapturePhoto is a wrapper representing a photo in a file container. To flatten the photo to an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to write to file, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more complex flattening operations such as replacing or stripping metadata, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(with:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and provide a delegate for customized replacement or stripping behavior. This delegate’s methods are called synchronously before the flattening process begins.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto": {
      "abstract": [
        {
          "text": "A container for image data from a photo capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhoto",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/cgImageRepresentation()": {
      "abstract": [
        {
          "text": "Extracts and returns the captured photo’s primary image as a Core Graphics image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgImageRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/cgImageRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGImageRepresentation"
        }
      ],
      "role": "symbol",
      "title": "cgImageRepresentation()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/cgimagerepresentation()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()": {
      "abstract": [
        {
          "text": "Generates and returns a flat data representation of the photo and its attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        }
      ],
      "role": "symbol",
      "title": "fileDataRepresentation()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/filedatarepresentation()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(with:)": {
      "abstract": [
        {
          "text": "Gets a customized representation of the photo data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCapturePhotoFileDataRepresentationCustomizer",
          "text": "AVCapturePhotoFileDataRepresentationCustomizer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileDataRepresentationWithCustomizer:"
        }
      ],
      "role": "symbol",
      "title": "fileDataRepresentation(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/filedatarepresentation(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)": {
      "abstract": [
        {
          "text": "Generates and returns a flat data representation of the photo using the specified replacements for some or all of its attachments.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withReplacementMetadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "replacementEmbeddedThumbnailPhotoFormat"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "replacementEmbeddedThumbnailPixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "replacementDepthData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVDepthData",
          "text": "AVDepthData"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileDataRepresentationWithReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:"
        }
      ],
      "role": "symbol",
      "title": "fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/filedatarepresentation(withreplacementmetadata:replacementembeddedthumbnailphotoformat:replacementembeddedthumbnailpixelbuffer:replacementdepthdata:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/previewCGImageRepresentation()": {
      "abstract": [
        {
          "text": "Extracts and returns the captured photo’s preview image as a Core Graphics image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewCGImageRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/previewCGImageRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewCGImageRepresentation"
        }
      ],
      "role": "symbol",
      "title": "previewCGImageRepresentation()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/previewcgimagerepresentation()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to customize the packaging of photo data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoFileDataRepresentationCustomizer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoFileDataRepresentationCustomizer"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoFileDataRepresentationCustomizer",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)": {
      "abstract": [
        {
          "text": "Replaces the compression settings the system uses when writing Apple ProRAW data to a Linear DNG file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementAppleProRAWCompressionSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "maximumBitDepth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementAppleProRAWCompressionSettingsForPhoto:defaultSettings:maximumBitDepth:"
        }
      ],
      "role": "symbol",
      "title": "replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementappleprorawcompressionsettings(for:defaultsettings:maximumbitdepth:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementDepthData(for:)": {
      "abstract": [
        {
          "text": "A callback in which you can provide replacement depth data or strip existing depth data from the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementDepthData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVDepthData",
          "text": "AVDepthData"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementDepthData(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementDepthDataForPhoto:"
        }
      ],
      "role": "symbol",
      "title": "replacementDepthData(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementdepthdata(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)": {
      "abstract": [
        {
          "text": "A callback in which you can provide a replacement embedded thumbnail image with compression settings, or strip the existing embedded thumbnail image from the flattened file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementEmbeddedThumbnailPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPhotoFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDictionary",
          "text": "NSDictionary"
        },
        {
          "kind": "text",
          "text": "?>, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementEmbeddedThumbnailPixelBufferWithPhotoFormat:forPhoto:"
        }
      ],
      "role": "symbol",
      "title": "replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementembeddedthumbnailpixelbuffer(withphotoformat:for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementMetadata(for:)": {
      "abstract": [
        {
          "text": "A callback in which you can provide replacement metadata or direct ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " to strip existing metadata from the flattened file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementMetadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementMetadata(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementMetadataForPhoto:"
        }
      ],
      "role": "symbol",
      "title": "replacementMetadata(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementmetadata(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementPortraitEffectsMatte(for:)": {
      "abstract": [
        {
          "text": "A callback in which you can provide a replacement portrait effects matte, or strip the existing portrait effects matte from the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementPortraitEffectsMatte"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPortraitEffectsMatte",
          "text": "AVPortraitEffectsMatte"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementPortraitEffectsMatte(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementPortraitEffectsMatteForPhoto:"
        }
      ],
      "role": "symbol",
      "title": "replacementPortraitEffectsMatte(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementportraiteffectsmatte(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementSemanticSegmentationMatte(ofType:for:)": {
      "abstract": [
        {
          "text": "Replaces or removes the semantic segmentation matte of the specified type from the flattened file data representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacementSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
          "text": "AVSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVSemanticSegmentationMatteType",
          "text": "MatteType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSemanticSegmentationMatte",
          "text": "AVSemanticSegmentationMatte"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementSemanticSegmentationMatte(ofType:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacementSemanticSegmentationMatteOfType:forPhoto:"
        }
      ],
      "role": "symbol",
      "title": "replacementSemanticSegmentationMatte(ofType:for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer/replacementsemanticsegmentationmatte(oftype:for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats": {
      "abstract": [
        {
          "text": "Support professional photography workflows by enabling minimally processed image capture in your camera app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats",
      "kind": "article",
      "role": "article",
      "title": "Capturing Photos in RAW and Apple ProRAW Formats",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-photos-in-raw-and-apple-proraw-formats"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdata": {
      "abstract": [
        {
          "text": "A static byte buffer that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSData"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdata",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSData",
      "type": "topic",
      "url": "/documentation/foundation/nsdata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Packaging-Data-for-File-Output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/cgImageRepresentation()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/previewCGImageRepresentation()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)"
      ],
      "title": "Packaging Data for File Output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Replacing-or-Removing-Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementMetadata(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementDepthData(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementPortraitEffectsMatte(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementSemanticSegmentationMatte(ofType:for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)"
      ],
      "title": "Replacing or Removing Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCapturePhotoFileDataRepresentationCustomizer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoFileDataRepresentationCustomizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoFileDataRepresentationCustomizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Replacing-or-Removing-Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementMetadata(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementDepthData(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementPortraitEffectsMatte(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementSemanticSegmentationMatte(ofType:for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoFileDataRepresentationCustomizer/replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)"
              ],
              "title": "Replacing or Removing Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Packaging-Data-for-File-Output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/cgImageRepresentation()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/previewCGImageRepresentation()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)"
              ],
              "title": "Packaging Data for File Output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCapturePhotoFileDataRepresentationCustomizer"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdata/abstract",
          "value": [
            {
              "text": "A static byte buffer in memory.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1previewCGImageRepresentation()/title",
          "value": "previewCGImageRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1previewCGImageRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewCGImageRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/title",
          "value": "AVCapturePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementMetadata(for:)/title",
          "value": "replacementMetadataForPhoto:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementMetadata(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementMetadataForPhoto:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation()/title",
          "value": "fileDataRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fileDataRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation(with:)/title",
          "value": "fileDataRepresentationWithCustomizer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fileDataRepresentationWithCustomizer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementSemanticSegmentationMatte(ofType:for:)/title",
          "value": "replacementSemanticSegmentationMatteOfType:forPhoto:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementSemanticSegmentationMatte(ofType:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementSemanticSegmentationMatteOfType:forPhoto:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementPortraitEffectsMatte(for:)/title",
          "value": "replacementPortraitEffectsMatteForPhoto:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementPortraitEffectsMatte(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementPortraitEffectsMatteForPhoto:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)/title",
          "value": "replacementAppleProRAWCompressionSettingsForPhoto:defaultSettings:maximumBitDepth:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementAppleProRAWCompressionSettings(for:defaultSettings:maximumBitDepth:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementAppleProRAWCompressionSettingsForPhoto:defaultSettings:maximumBitDepth:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)/title",
          "value": "replacementEmbeddedThumbnailPixelBufferWithPhotoFormat:forPhoto:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementEmbeddedThumbnailPixelBuffer(withPhotoFormat:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementEmbeddedThumbnailPixelBufferWithPhotoFormat:forPhoto:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1cgImageRepresentation()/title",
          "value": "CGImageRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1cgImageRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "CGImageRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)/title",
          "value": "fileDataRepresentationWithReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation(withReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fileDataRepresentationWithReplacementMetadata:replacementEmbeddedThumbnailPhotoFormat:replacementEmbeddedThumbnailPixelBuffer:replacementDepthData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer/title",
          "value": "AVCapturePhotoFileDataRepresentationCustomizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoFileDataRepresentationCustomizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoFileDataRepresentationCustomizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementDepthData(for:)/title",
          "value": "replacementDepthDataForPhoto:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoFileDataRepresentationCustomizer~1replacementDepthData(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacementDepthDataForPhoto:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturephotofiledatarepresentationcustomizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
