{
  "abstract": [
    {
      "text": "Constants that indicate the type of reaction that an effect can perform.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AVCaptureReactionType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCaptureReactionType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptureReactionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVCaptureReactionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/endTime": {
      "abstract": [
        {
          "text": "The presentation time of the first frame following the end of a reaction effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/endTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endTime"
        }
      ],
      "role": "symbol",
      "title": "endTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactioneffectstate/endtime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/reactionType": {
      "abstract": [
        {
          "text": "The type of reaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reactionType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/reactionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reactionType"
        }
      ],
      "role": "symbol",
      "title": "reactionType",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactioneffectstate/reactiontype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/startTime": {
      "abstract": [
        {
          "text": "The presentation time of the first frame where the system renders the effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/startTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startTime"
        }
      ],
      "role": "symbol",
      "title": "startTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactioneffectstate/starttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of reaction that an effect can perform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionType"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureReactionType",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons": {
      "abstract": [
        {
          "text": "A reaction that displays balloons rising through the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balloons"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeBalloons"
        }
      ],
      "role": "symbol",
      "title": "balloons",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/balloons"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti": {
      "abstract": [
        {
          "text": "A reaction that displays festive spots of color falling through the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "confetti"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeConfetti"
        }
      ],
      "role": "symbol",
      "title": "confetti",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/confetti"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks": {
      "abstract": [
        {
          "text": "A reaction that displays fireworks bursting in the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fireworks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeFireworks"
        }
      ],
      "role": "symbol",
      "title": "fireworks",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/fireworks"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart": {
      "abstract": [
        {
          "text": "A reaction that displays one or more heart symbols.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeHeart"
        }
      ],
      "role": "symbol",
      "title": "heart",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/heart"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a reaction type with a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers": {
      "abstract": [
        {
          "text": "A reaction that displays a bright laser show projecting into the scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lasers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeLasers"
        }
      ],
      "role": "symbol",
      "title": "lasers",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/lasers"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain": {
      "abstract": [
        {
          "text": "A reaction that displays a dark and stormy night.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeRain"
        }
      ],
      "role": "symbol",
      "title": "rain",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/rain"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/systemImageName": {
      "abstract": [
        {
          "text": "Returns the name of a system image that displays the recommended iconography for a specified reaction type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemImageName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/systemImageName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionSystemImageNameForType"
        }
      ],
      "role": "symbol",
      "title": "systemImageName",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/systemimagename"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown": {
      "abstract": [
        {
          "text": "A reaction that displays a thumbs-down symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbsDown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeThumbsDown"
        }
      ],
      "role": "symbol",
      "title": "thumbsDown",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/thumbsdown"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp": {
      "abstract": [
        {
          "text": "A reaction that displays a thumbs-up symbol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thumbsUp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureReactionType",
          "text": "AVCaptureReactionType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureReactionTypeThumbsUp"
        }
      ],
      "role": "symbol",
      "title": "thumbsUp",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturereactiontype/thumbsup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-effect-state",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/reactionType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/startTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/endTime"
      ],
      "title": "Configuring the effect state"
    }
  ],
  "topicSections": [
    {
      "anchor": "Reaction-types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown"
      ],
      "title": "Reaction types"
    },
    {
      "anchor": "Accessing-the-system-image-name",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/systemImageName"
      ],
      "title": "Accessing the system image name"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptureReactionType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Reaction-types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/balloons",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/confetti",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/fireworks",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/heart",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/lasers",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/rain",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsUp",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/thumbsDown"
              ],
              "title": "Reaction types"
            },
            {
              "anchor": "Accessing-the-system-image-name",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionType/systemImageName"
              ],
              "title": "Accessing the system image name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-effect-state",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/reactionType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/startTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureReactionEffectState/endTime"
              ],
              "title": "Configuring the effect state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptureReactionType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1balloons/title",
          "value": "AVCaptureReactionTypeBalloons"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1balloons/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeBalloons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsDown/title",
          "value": "AVCaptureReactionTypeThumbsDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeThumbsDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1confetti/title",
          "value": "AVCaptureReactionTypeConfetti"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1confetti/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeConfetti"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/title",
          "value": "AVCaptureReactionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1fireworks/title",
          "value": "AVCaptureReactionTypeFireworks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1fireworks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeFireworks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsUp/title",
          "value": "AVCaptureReactionTypeThumbsUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1thumbsUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeThumbsUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1rain/title",
          "value": "AVCaptureReactionTypeRain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1rain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeRain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1reactionType/title",
          "value": "reactionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1reactionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reactionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1systemImageName/title",
          "value": "AVCaptureReactionSystemImageNameForType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1systemImageName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionSystemImageNameForType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1lasers/title",
          "value": "AVCaptureReactionTypeLasers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1lasers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeLasers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1heart/title",
          "value": "AVCaptureReactionTypeHeart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionType~1heart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureReactionTypeHeart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1startTime/title",
          "value": "startTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1startTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1endTime/title",
          "value": "endTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureReactionEffectState~1endTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "endTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcapturereactiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcapturereactiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
