{"seeAlsoSections":[{"title":"Photo capture","anchor":"Photo-capture","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/capturing-consistent-color-images","doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos","doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats","doc://com.apple.documentation/documentation/AppKit/supporting-continuity-camera-in-your-mac-app","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeferredPhotoProxy","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinatorDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An object that monitors changes to a photo output’s capture readiness.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCapturePhotoOutputReadinessCoordinator","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"text":"Use this object to coordinate user interface updates on the main queue with a ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput","isActive":true},{"text":" that runs on a background queue. Adopt the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinatorDelegate","isActive":true},{"text":" protocol in your app and set its implementation as the coordinator’s delegate object to receive callbacks as the associated photo output’s ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property","isActive":true},{"text":" state changes.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can track additional capture requests with this object by calling its "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/startTrackingCaptureRequest(using:)","isActive":true,"type":"reference"},{"type":"text","text":" method. You can use it to synchronously update shutter button availability and appearance and on the main thread while calling the photo output’s "},{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)","isActive":true,"type":"reference"},{"type":"text","text":" method asynchronously on a background queue."}],"type":"paragraph"}],"kind":"content"}],"topicSections":[{"title":"Creating a coordinator","anchor":"Creating-a-coordinator","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/init(photoOutput:)"]},{"title":"Setting the delegate object","anchor":"Setting-the-delegate-object","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/delegate"]},{"title":"Performing tracking requests","anchor":"Performing-tracking-requests","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/startTrackingCaptureRequest(using:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/stopTrackingCaptureRequest(using:)"]},{"title":"Determining readiness for capture","anchor":"Determining-readiness-for-capture","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/captureReadiness"]}],"variants":[{"paths":["/documentation/avfoundation/avcapturephotooutputreadinesscoordinator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturephotooutputreadinesscoordinator"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"AVCapturePhotoOutputReadinessCoordinator","kind":"identifier"}],"modules":[{"name":"AVFoundation"}],"externalID":"c:objc(cs)AVCapturePhotoOutputReadinessCoordinator","platforms":[{"name":"iOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"17.0","name":"tvOS","deprecated":false,"unavailable":false,"beta":false}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCapturePhotoOutputReadinessCoordinator","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","title":"AVCapturePhotoOutputReadinessCoordinator"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"sections":[],"references":{"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-consistent-color-images":{"url":"/documentation/avfoundation/capturing-consistent-color-images","kind":"article","type":"topic","abstract":[{"text":"Add the power of a photography studio and lighting rig to your app with the new Constant Color API.","type":"text"}],"role":"sampleCode","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-consistent-color-images","title":"Capturing consistent color images"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator":{"url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator","abstract":[{"type":"text","text":"An object that monitors changes to a photo output’s capture readiness."}],"title":"AVCapturePhotoOutputReadinessCoordinator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"}],"navigatorTitle":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos":{"kind":"article","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos","type":"topic","url":"/documentation/avfoundation/capturing-still-and-live-photos","abstract":[{"type":"text","text":"Configure and capture single or multiple still images, Live Photos, and other forms of photography."}],"role":"collectionGroup","title":"Capturing Still and Live Photos"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"url":"/documentation/objectivec/nsobject","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/startTrackingCaptureRequest(using:)":{"title":"startTrackingCaptureRequest(using:)","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/startTrackingCaptureRequest(using:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startTrackingCaptureRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCapturePhotoSettings","text":"AVCapturePhotoSettings"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"startTrackingCaptureRequestUsingPhotoSettings:"}],"type":"topic","abstract":[{"type":"text","text":"Tracks a capture request that uses the specified photo settings."}],"role":"symbol","url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator/starttrackingcapturerequest(using:)"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCapturePhoto"}],"navigatorTitle":[{"kind":"identifier","text":"AVCapturePhoto"}],"title":"AVCapturePhoto","url":"/documentation/avfoundation/avcapturephoto","abstract":[{"text":"A container for image data from a photo capture output.","type":"text"}],"type":"topic"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/init(photoOutput:)":{"abstract":[{"text":"Creates an object that helps coordinate user interface changes with a photo output that runs on a background queue.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/init(photoOutput:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"photoOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":")"}],"url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator/init(photooutput:)","title":"init(photoOutput:)","navigatorTitle":[{"text":"initWithPhotoOutput:","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureStillImageOutput","kind":"identifier"}],"navigatorTitle":[{"text":"AVCaptureStillImageOutput","kind":"identifier"}],"deprecated":true,"abstract":[{"type":"text","text":"A capture output for capturing still photos."}],"type":"topic","title":"AVCaptureStillImageOutput","url":"/documentation/avfoundation/avcapturestillimageoutput","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/captureReadiness":{"navigatorTitle":[{"text":"captureReadiness","kind":"identifier"}],"url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator/capturereadiness","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/captureReadiness","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureReadiness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"CaptureReadiness","preciseIdentifier":"c:@E@AVCapturePhotoOutputCaptureReadiness","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"A value that indicates whether the coordinator’s photo output is ready to respond to new capture requests in a timely manner.","type":"text"}],"title":"captureReadiness","role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/stopTrackingCaptureRequest(using:)":{"title":"stopTrackingCaptureRequest(using:)","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/stopTrackingCaptureRequest(using:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopTrackingCaptureRequest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"stopTrackingCaptureRequestUsingPhotoSettingsUniqueID:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Stop tracking the capture request represented by the specified photo setting’s unique identifier."}],"role":"symbol","url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator/stoptrackingcapturerequest(using:)"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate","type":"topic","abstract":[{"text":"Methods for monitoring progress and receiving results from a photo capture output.","type":"text"}],"role":"symbol","url":"/documentation/avfoundation/avcapturephotocapturedelegate","title":"AVCapturePhotoCaptureDelegate","navigatorTitle":[{"text":"AVCapturePhotoCaptureDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCapturePhotoCaptureDelegate","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.apple.documentation/documentation/AppKit/supporting-continuity-camera-in-your-mac-app":{"url":"/documentation/AppKit/supporting-continuity-camera-in-your-mac-app","abstract":[{"type":"text","text":"Incorporate scanned documents and pictures from a user’s iPhone, iPad, or iPod touch into your Mac app using Continuity Camera."}],"title":"Supporting Continuity Camera in Your Mac App","type":"topic","kind":"article","role":"article","identifier":"doc://com.apple.documentation/documentation/AppKit/supporting-continuity-camera-in-your-mac-app"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCapturePhotoOutput","kind":"identifier"}],"navigatorTitle":[{"text":"AVCapturePhotoOutput","kind":"identifier"}],"abstract":[{"type":"text","text":"A capture output for still image, Live Photos, and other photography workflows."}],"type":"topic","title":"AVCapturePhotoOutput","url":"/documentation/avfoundation/avcapturephotooutput","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"captureReadiness"}],"abstract":[{"text":"A value that specifies whether the photo output is ready to respond to new capture requests in a timely manner.","type":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/captureReadiness-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureReadiness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutput","preciseIdentifier":"c:objc(cs)AVCapturePhotoOutput"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"CaptureReadiness","preciseIdentifier":"c:@E@AVCapturePhotoOutputCaptureReadiness"}],"type":"topic","url":"/documentation/avfoundation/avcapturephotooutput/capturereadiness-swift.property","kind":"symbol","title":"captureReadiness"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeferredPhotoProxy":{"url":"/documentation/avfoundation/avcapturedeferredphotoproxy","abstract":[{"type":"text","text":"A lightly-processed photo with data that the system may use to process and fetch a higher-resolution asset at a later time."}],"title":"AVCaptureDeferredPhotoProxy","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeferredPhotoProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureDeferredPhotoProxy"}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureDeferredPhotoProxy"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/delegate":{"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"AVCapturePhotoOutputReadinessCoordinatorDelegate","preciseIdentifier":"c:objc(pl)AVCapturePhotoOutputReadinessCoordinatorDelegate"},{"text":")?","kind":"text"}],"url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinator/delegate","type":"topic","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/delegate","title":"delegate","abstract":[{"type":"text","text":"The coordinator’s delegate object."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinatorDelegate":{"url":"/documentation/avfoundation/avcapturephotooutputreadinesscoordinatordelegate","abstract":[{"type":"text","text":"A delegate protocol to receive updates about a photo output’s capture readiness."}],"title":"AVCapturePhotoOutputReadinessCoordinatorDelegate","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinatorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinatorDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinatorDelegate"}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)":{"navigatorTitle":[{"text":"capturePhotoWithSettings:delegate:","kind":"identifier"}],"title":"capturePhoto(with:delegate:)","abstract":[{"text":"Initiates a photo capture using the specified settings.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"capturePhoto","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCapturePhotoSettings","preciseIdentifier":"c:objc(cs)AVCapturePhotoSettings","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"AVCapturePhotoCaptureDelegate","preciseIdentifier":"c:objc(pl)AVCapturePhotoCaptureDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"/documentation/avfoundation/avcapturephotooutput/capturephoto(with:delegate:)","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats":{"url":"/documentation/avfoundation/capturing-photos-in-raw-and-apple-proraw-formats","kind":"article","type":"topic","abstract":[{"text":"Support professional photography workflows by enabling minimally processed image capture in your camera app.","type":"text"}],"role":"article","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats","title":"Capturing Photos in RAW and Apple ProRAW Formats"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"name":"iOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"14.0","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","introducedAt":"17.0","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"op":"replace","path":"/metadata/title","value":"AVCapturePhotoOutputReadinessCoordinator"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Creating a coordinator","anchor":"Creating-a-coordinator","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/init(photoOutput:)"]},{"title":"Setting the delegate object","anchor":"Setting-the-delegate-object","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/delegate"]},{"title":"Performing tracking requests","anchor":"Performing-tracking-requests","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/startTrackingCaptureRequest(using:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/stopTrackingCaptureRequest(using:)"]},{"title":"Determining readiness for capture","anchor":"Determining-readiness-for-capture","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinator/captureReadiness"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Photo capture","generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/capturing-consistent-color-images","doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos","doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-in-raw-and-apple-proraw-formats","doc://com.apple.documentation/documentation/AppKit/supporting-continuity-camera-in-your-mac-app","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeferredPhotoProxy","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutputReadinessCoordinatorDelegate","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureStillImageOutput"],"anchor":"Photo-capture"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]}},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator/title","value":"AVCapturePhotoOutputReadinessCoordinator","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator/fragments","value":[{"text":"AVCapturePhotoOutputReadinessCoordinator","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator/navigatorTitle","value":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinator"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1startTrackingCaptureRequest(using:)/title","value":"startTrackingCaptureRequestUsingPhotoSettings:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1startTrackingCaptureRequest(using:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"startTrackingCaptureRequestUsingPhotoSettings:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/title","value":"AVCapturePhoto","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/fragments","value":[{"kind":"identifier","text":"AVCapturePhoto"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/navigatorTitle","value":[{"kind":"identifier","text":"AVCapturePhoto"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1init(photoOutput:)/title","value":"initWithPhotoOutput:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1init(photoOutput:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPhotoOutput:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/title","value":"AVCaptureStillImageOutput","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/fragments","value":[{"text":"AVCaptureStillImageOutput","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureStillImageOutput/navigatorTitle","value":[{"text":"AVCaptureStillImageOutput","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1captureReadiness/title","value":"captureReadiness","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1captureReadiness/fragments","value":[{"kind":"identifier","text":"captureReadiness"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1stopTrackingCaptureRequest(using:)/title","value":"stopTrackingCaptureRequestUsingPhotoSettingsUniqueID:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1stopTrackingCaptureRequest(using:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"stopTrackingCaptureRequestUsingPhotoSettingsUniqueID:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate/title","value":"AVCapturePhotoCaptureDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate/fragments","value":[{"text":"AVCapturePhotoCaptureDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate/navigatorTitle","value":[{"text":"AVCapturePhotoCaptureDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/title","value":"AVCapturePhotoOutput","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/fragments","value":[{"text":"AVCapturePhotoOutput","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/navigatorTitle","value":[{"kind":"identifier","text":"AVCapturePhotoOutput"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1captureReadiness-swift.property/title","value":"captureReadiness","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1captureReadiness-swift.property/fragments","value":[{"text":"captureReadiness","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeferredPhotoProxy/title","value":"AVCaptureDeferredPhotoProxy","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeferredPhotoProxy/fragments","value":[{"kind":"identifier","text":"AVCaptureDeferredPhotoProxy"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeferredPhotoProxy/navigatorTitle","value":[{"text":"AVCaptureDeferredPhotoProxy","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1delegate/title","value":"delegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinator~1delegate/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinatorDelegate/title","value":"AVCapturePhotoOutputReadinessCoordinatorDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinatorDelegate/fragments","value":[{"kind":"identifier","text":"AVCapturePhotoOutputReadinessCoordinatorDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutputReadinessCoordinatorDelegate/navigatorTitle","value":[{"text":"AVCapturePhotoOutputReadinessCoordinatorDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/title","value":"capturePhotoWithSettings:delegate:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"capturePhotoWithSettings:delegate:"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}