{
  "abstract": [
    {
      "text": "An object that represents the region in which the system presents a caption.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCaptionRegion",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCaptionRegion"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCaptionRegion"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCaptionRegion"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The framework defines four regions, and doesn’t support configuring region settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension": {
      "abstract": [
        {
          "text": "A structure that defines a caption dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionDimension"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionDimension"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionDimension",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptiondimension"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimensionMake": {
      "abstract": [
        {
          "text": "Creates a caption dimension with a value and unit type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVCaptionDimensionMake"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimensionMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptionDimensionMake",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptiondimensionmake"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPoint": {
      "abstract": [
        {
          "text": "A structure that defines the origin point for a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionPoint"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionPoint"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionPoint",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionpoint"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPointMake": {
      "abstract": [
        {
          "text": "Creates a caption point with the specified x and y positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVCaptionPointMake"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPointMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptionPointMake",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionpointmake"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion": {
      "abstract": [
        {
          "text": "An object that represents the region in which the system presents a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionRegion"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the alignment of lines in a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayAlignment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayAlignment"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.DisplayAlignment",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/Scroll-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the scrolling effects the system applies to a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Scroll"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/Scroll-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Scroll"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.Scroll",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/scroll-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/WritingMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the writing mode for a region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WritingMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/WritingMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WritingMode"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionRegion.WritingMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/writingmode-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTBottom": {
      "abstract": [
        {
          "text": "The bottom region for iTT format captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleITTBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleITTBottomRegion"
        }
      ],
      "role": "symbol",
      "title": "appleITTBottom",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/appleittbottom"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTLeft": {
      "abstract": [
        {
          "text": "The left region for iTT format captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleITTLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleITTLeftRegion"
        }
      ],
      "role": "symbol",
      "title": "appleITTLeft",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/appleittleft"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTRight": {
      "abstract": [
        {
          "text": "The right region for iTT format captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleITTRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleITTRightRegion"
        }
      ],
      "role": "symbol",
      "title": "appleITTRight",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/appleittright"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTTop": {
      "abstract": [
        {
          "text": "The top region for iTT format captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleITTTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appleITTTopRegion"
        }
      ],
      "role": "symbol",
      "title": "appleITTTop",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/appleitttop"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/displayAlignment-swift.property": {
      "abstract": [
        {
          "text": "The alignment of lines for the region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionRegionDisplayAlignment",
          "text": "DisplayAlignment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/displayAlignment-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayAlignment"
        }
      ],
      "role": "symbol",
      "title": "displayAlignment",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/displayalignment-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/encode(with:)": {
      "abstract": [
        {
          "text": "Encodes the region using the specified encoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/encode(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "encodeWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "encode(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/encode(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/identifier": {
      "abstract": [
        {
          "text": "A string that identifies the region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/identifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/isEqual(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether an object equals another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEqual"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/isEqual(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isEqual:"
        }
      ],
      "role": "symbol",
      "title": "isEqual(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/isequal(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/mutableCopy(with:)": {
      "abstract": [
        {
          "text": "Creates a mutable copy of a caption region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mutableCopy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC6NSZoneV",
          "text": "NSZone"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/mutableCopy(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mutableCopyWithZone:"
        }
      ],
      "role": "symbol",
      "title": "mutableCopy(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/mutablecopy(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/origin": {
      "abstract": [
        {
          "text": "The region’s top-left position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVCaptionPoint",
          "text": "AVCaptionPoint"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/origin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "origin"
        }
      ],
      "role": "symbol",
      "title": "origin",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/origin"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/scroll-swift.property": {
      "abstract": [
        {
          "text": "The scroll mode of the region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scroll"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionRegionScroll",
          "text": "Scroll"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/scroll-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scroll"
        }
      ],
      "role": "symbol",
      "title": "scroll",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/scroll-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/size": {
      "abstract": [
        {
          "text": "The height and width of the region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@AVCaptionSize",
          "text": "AVCaptionSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/size"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/subRipTextBottom": {
      "abstract": [
        {
          "text": "The bottom caption region for SubRip Text (SRT) format captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subRipTextBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/subRipTextBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subRipTextBottomRegion"
        }
      ],
      "role": "symbol",
      "title": "subRipTextBottom",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/subriptextbottom"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/writingMode-swift.property": {
      "abstract": [
        {
          "text": "The block and inline progression direction of the region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptionRegion",
          "text": "AVCaptionRegion"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptionRegionWritingMode",
          "text": "WritingMode"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/writingMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writingMode"
        }
      ],
      "role": "symbol",
      "title": "writingMode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionregion/writingmode-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize": {
      "abstract": [
        {
          "text": "A structure that defines the height and width of a caption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptionSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptionSize"
        }
      ],
      "role": "symbol",
      "title": "AVCaptionSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSizeMake": {
      "abstract": [
        {
          "text": "Creates a caption size with the specified width and height.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVCaptionSizeMake"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSizeMake",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVCaptionSizeMake",
      "type": "topic",
      "url": "/documentation/avfoundation/avcaptionsizemake"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion": {
      "abstract": [
        {
          "text": "A mutable caption region subclass that you use to create new caption regions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCaptionRegion"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCaptionRegion"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCaptionRegion",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecaptionregion"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Regions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion"
      ],
      "title": "Regions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Defined-Regions",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTTop",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTBottom",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTLeft",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTRight",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/subRipTextBottom"
      ],
      "title": "Accessing Defined Regions"
    },
    {
      "anchor": "Identifying-a-Region",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/identifier"
      ],
      "title": "Identifying a Region"
    },
    {
      "anchor": "Accessing-Dimensions",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension"
      ],
      "title": "Accessing Dimensions"
    },
    {
      "anchor": "Accessing-the-Location",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/origin",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPoint"
      ],
      "title": "Accessing the Location"
    },
    {
      "anchor": "Accessing-the-Size",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/size",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize"
      ],
      "title": "Accessing the Size"
    },
    {
      "anchor": "Accessing-the-Display-Alignment",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/displayAlignment-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum"
      ],
      "title": "Accessing the Display Alignment"
    },
    {
      "anchor": "Accessing-the-Scroll-Mode",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/scroll-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/Scroll-swift.enum"
      ],
      "title": "Accessing the Scroll Mode"
    },
    {
      "anchor": "Accessing-the-Writing-Mode",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/writingMode-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/WritingMode-swift.enum"
      ],
      "title": "Accessing the Writing Mode"
    },
    {
      "anchor": "Processing-Regions",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/mutableCopy(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/encode(with:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/isEqual(_:)"
      ],
      "title": "Processing Regions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCaptionRegion"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Defined-Regions",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTTop",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTBottom",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTLeft",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/appleITTRight",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/subRipTextBottom"
              ],
              "title": "Accessing Defined Regions"
            },
            {
              "anchor": "Identifying-a-Region",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/identifier"
              ],
              "title": "Identifying a Region"
            },
            {
              "anchor": "Accessing-Dimensions",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimension",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionDimensionMake"
              ],
              "title": "Accessing Dimensions"
            },
            {
              "anchor": "Accessing-the-Location",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/origin",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPoint",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionPointMake"
              ],
              "title": "Accessing the Location"
            },
            {
              "anchor": "Accessing-the-Size",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/size",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSize",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionSizeMake"
              ],
              "title": "Accessing the Size"
            },
            {
              "anchor": "Accessing-the-Display-Alignment",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/displayAlignment-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/DisplayAlignment-swift.enum"
              ],
              "title": "Accessing the Display Alignment"
            },
            {
              "anchor": "Accessing-the-Scroll-Mode",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/scroll-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/Scroll-swift.enum"
              ],
              "title": "Accessing the Scroll Mode"
            },
            {
              "anchor": "Accessing-the-Writing-Mode",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/writingMode-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/WritingMode-swift.enum"
              ],
              "title": "Accessing the Writing Mode"
            },
            {
              "anchor": "Processing-Regions",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/mutableCopy(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/encode(with:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptionRegion/isEqual(_:)"
              ],
              "title": "Processing Regions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Regions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCaptionRegion"
              ],
              "title": "Regions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCaptionRegion"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTRight/title",
          "value": "appleITTRightRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleITTRightRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1displayAlignment-swift.property/title",
          "value": "displayAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1displayAlignment-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1mutableCopy(with:)/title",
          "value": "mutableCopyWithZone:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1mutableCopy(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mutableCopyWithZone:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1scroll-swift.property/title",
          "value": "scroll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1scroll-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scroll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1Scroll-swift.enum/title",
          "value": "AVCaptionRegionScroll"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1Scroll-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionScroll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1Scroll-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionScroll"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1WritingMode-swift.enum/title",
          "value": "AVCaptionRegionWritingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1WritingMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionWritingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1WritingMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionWritingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1subRipTextBottom/title",
          "value": "subRipTextBottomRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1subRipTextBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subRipTextBottomRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1writingMode-swift.property/title",
          "value": "writingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1writingMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "writingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/title",
          "value": "AVCaptionRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1encode(with:)/title",
          "value": "encodeWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1encode(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "encodeWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1isEqual(_:)/title",
          "value": "isEqual:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1isEqual(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "isEqual:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaptionRegion/title",
          "value": "AVMutableCaptionRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaptionRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCaptionRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCaptionRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTLeft/title",
          "value": "appleITTLeftRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleITTLeftRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionPoint/title",
          "value": "AVCaptionPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTBottom/title",
          "value": "appleITTBottomRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleITTBottomRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/title",
          "value": "AVCaptionDimension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionDimension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionDimension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1origin/title",
          "value": "origin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1origin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "origin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/title",
          "value": "AVCaptionRegionDisplayAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1DisplayAlignment-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionRegionDisplayAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/title",
          "value": "AVCaptionSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptionSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTTop/title",
          "value": "appleITTTopRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptionRegion~1appleITTTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appleITTTopRegion"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcaptionregion"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcaptionregion"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
