{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"seeAlsoSections":[{"title":"Capture controls","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker"],"anchor":"Capture-controls","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}]}],"kind":"declarations"},{"mentions":["doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control"],"kind":"mentions"},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"This control defines its range by querying the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/systemRecommendedExposureBiasRange"},{"text":" property of the device’s active format. If a device’s ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activeFormat"},{"text":" value changes, the slider updates its range with the new format’s system-recommended value.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this control, add it to the capture session by calling the session’s "},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/addControl(_:)","isActive":true},{"type":"text","text":" method."}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}],"role":"symbol","platforms":[{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"15.0","unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false,"name":"tvOS"}],"modules":[{"name":"AVFoundation"}],"symbolKind":"class","roleHeading":"Class","title":"AVCaptureSystemExposureBiasSlider","navigatorTitle":[{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}],"externalID":"c:objc(cs)AVCaptureSystemExposureBiasSlider"},"topicSections":[{"title":"Creating an exposure bias slider","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:action:)"],"anchor":"Creating-an-exposure-bias-slider"}],"variants":[{"paths":["/documentation/avfoundation/avcapturesystemexposurebiasslider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avcapturesystemexposurebiasslider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A control that adjusts the exposure bias of a capture device within the system-recommended range."}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:action:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithDevice:action:","kind":"identifier"}],"type":"topic","title":"init(device:action:)","url":"/documentation/avfoundation/avcapturesystemexposurebiasslider/init(device:action:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:action:)","role":"symbol","kind":"symbol","abstract":[{"text":"Creates a slider to control the exposure bias of the specified capture device with an action to respond to exposure bias changes.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureIndexPicker"}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureIndexPicker"}],"abstract":[{"text":"A control for selecting from a set of mutually exclusive values by index.","type":"text"}],"type":"topic","title":"AVCaptureIndexPicker","url":"/documentation/avfoundation/avcaptureindexpicker","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AVCaptureSystemExposureBiasSlider","kind":"identifier"}],"type":"topic","title":"AVCaptureSystemExposureBiasSlider","url":"/documentation/avfoundation/avcapturesystemexposurebiasslider","abstract":[{"text":"A control that adjusts the exposure bias of a capture device within the system-recommended range.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureSystemExposureBiasSlider","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activeFormat":{"abstract":[{"type":"text","text":"The capture format in use by the device."}],"title":"activeFormat","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/activeFormat","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:objc(cs)AVCaptureDeviceFormat","kind":"typeIdentifier","text":"Format"}],"url":"/documentation/avfoundation/avcapturedevice/activeformat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activeFormat"}]},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider":{"abstract":[{"text":"A slider control that selects a value from a bounded range.","type":"text"}],"title":"AVCaptureSlider","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVCaptureSlider"}],"url":"/documentation/avfoundation/avcaptureslider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVCaptureSlider"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider","role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider":{"url":"/documentation/avfoundation/avcapturesystemzoomslider","title":"AVCaptureSystemZoomSlider","kind":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AVCaptureSystemZoomSlider","kind":"identifier"}],"navigatorTitle":[{"text":"AVCaptureSystemZoomSlider","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A control that adjusts the video zoom factor of a capture device within the system-recommended range.","type":"text"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:)":{"navigatorTitle":[{"text":"initWithDevice:","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"device","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:)","title":"init(device:)","url":"/documentation/avfoundation/avcapturesystemexposurebiasslider/init(device:)","abstract":[{"type":"text","text":"Creates a slider to control the exposure bias of the specified capture device."}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AVCaptureControl","kind":"identifier"}],"type":"topic","title":"AVCaptureControl","url":"/documentation/avfoundation/avcapturecontrol","abstract":[{"text":"An abstract base class for controls that interact with the camera system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureControl","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/addControl(_:)":{"kind":"symbol","url":"/documentation/avfoundation/avcapturesession/addcontrol(_:)","title":"addControl(_:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSession/addControl(_:)","abstract":[{"type":"text","text":"Adds a control to a capture session."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addControl"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureControl","text":"AVCaptureControl"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addControl:"}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/systemRecommendedExposureBiasRange":{"kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/format/systemrecommendedexposurebiasrange","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/systemRecommendedExposureBiasRange","title":"systemRecommendedExposureBiasRange","abstract":[{"text":"The system’s recommended exposure bias range for this device format.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemRecommendedExposureBiasRange"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SN","kind":"typeIdentifier","text":"ClosedRange"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":">?"}],"type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control":{"title":"Enhancing your app experience with the Camera Control","kind":"article","url":"/documentation/avfoundation/enhancing-your-app-experience-with-the-camera-control","abstract":[{"type":"text","text":"Provide direct access to your camera app’s features to help people quickly capture the perfect shot."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control","type":"topic","role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"iOS"},{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"iPadOS"},{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"Mac Catalyst"},{"deprecated":false,"beta":false,"introducedAt":"15.0","unavailable":false,"name":"macOS"},{"deprecated":false,"beta":false,"introducedAt":"18.0","unavailable":false,"name":"tvOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"AVCaptureSystemExposureBiasSlider","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"op":"replace","path":"/hierarchy"},{"value":[{"title":"Creating an exposure bias slider","anchor":"Creating-an-exposure-bias-slider","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider/init(device:action:)"]}],"op":"replace","path":"/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl"]}],"op":"replace","path":"/relationshipsSections"},{"value":[{"title":"Capture controls","generated":true,"anchor":"Capture-controls","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-your-app-experience-with-the-camera-control","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemZoomSlider","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSlider","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureIndexPicker"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureSystemExposureBiasSlider","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AVCaptureControl","preciseIdentifier":"c:objc(cs)AVCaptureControl","kind":"typeIdentifier","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureControl"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"value":"initWithDevice:action:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider~1init(device:action:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDevice:action:"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider~1init(device:action:)/fragments"},{"value":"AVCaptureIndexPicker","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/title"},{"value":[{"text":"AVCaptureIndexPicker","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/fragments"},{"value":[{"text":"AVCaptureIndexPicker","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureIndexPicker/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"AVCaptureSystemExposureBiasSlider","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/title"},{"value":[{"text":"AVCaptureSystemExposureBiasSlider","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/fragments"},{"value":[{"kind":"identifier","text":"AVCaptureSystemExposureBiasSlider"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/navigatorTitle"},{"value":"activeFormat","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activeFormat/title"},{"value":[{"text":"activeFormat","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1activeFormat/fragments"},{"value":"AVCaptureSlider","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/title"},{"value":[{"kind":"identifier","text":"AVCaptureSlider"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/fragments"},{"value":[{"text":"AVCaptureSlider","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSlider/navigatorTitle"},{"value":"AVCaptureSystemZoomSlider","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/title"},{"value":[{"text":"AVCaptureSystemZoomSlider","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/fragments"},{"value":[{"text":"AVCaptureSystemZoomSlider","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemZoomSlider/navigatorTitle"},{"value":"initWithDevice:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider~1init(device:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDevice:"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider~1init(device:)/fragments"},{"value":"AVCaptureControl","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/title"},{"value":[{"kind":"identifier","text":"AVCaptureControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/fragments"},{"value":[{"text":"AVCaptureControl","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureControl/navigatorTitle"},{"value":"addControl:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSession~1addControl(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addControl:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSession~1addControl(_:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}