{
  "abstract": [
    {
      "text": "An object that creates and tracks decryption keys for media data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVContentKeySession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVContentKeySession"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContentKeySession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVContentKeySession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey": {
      "abstract": [
        {
          "text": "An object that represents the content key decryptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKey"
        }
      ],
      "role": "symbol",
      "title": "AVContentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient": {
      "abstract": [
        {
          "text": "A protocol for requiring decryption keys for media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRecipient"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRecipient"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRecipient",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrecipient"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a content decryption key request issued from a content key session object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRequest"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a response to a content decryption key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyResponse"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyResponse"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyResponse",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyresponse"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession": {
      "abstract": [
        {
          "text": "An object that creates and tracks decryption keys for media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/addContentKeyRecipient(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified recipient should have access to the decryption keys loaded with the session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addContentKeyRecipient"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContentKeyRecipient",
          "text": "AVContentKeyRecipient"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/addContentKeyRecipient(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addContentKeyRecipient:"
        }
      ],
      "role": "symbol",
      "title": "addContentKeyRecipient(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/addcontentkeyrecipient(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentKeyRecipients": {
      "abstract": [
        {
          "text": "An array of content key recipients.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeyRecipients"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContentKeyRecipient",
          "text": "AVContentKeyRecipient"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentKeyRecipients",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeyRecipients"
        }
      ],
      "role": "symbol",
      "title": "contentKeyRecipients",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/contentkeyrecipients"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentProtectionSessionIdentifier": {
      "abstract": [
        {
          "text": "The identifier for the current content protection session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProtectionSessionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentProtectionSessionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentProtectionSessionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "contentProtectionSessionIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/contentprotectionsessionidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegate": {
      "abstract": [
        {
          "text": "The content key session’s delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContentKeySessionDelegate",
          "text": "AVContentKeySessionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/delegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegateQueue": {
      "abstract": [
        {
          "text": "The dispatch queue the session uses to invoke delegate callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegateQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegateQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegateQueue"
        }
      ],
      "role": "symbol",
      "title": "delegateQueue",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/delegatequeue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/expire()": {
      "abstract": [
        {
          "text": "Tells the delegate that the session expired as the result of normal, intentional processes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expire"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/expire()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expire"
        }
      ],
      "role": "symbol",
      "title": "expire()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/expire()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:)": {
      "abstract": [
        {
          "text": "Creates a content key session to manage a collection of content decryption keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keySystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeySystem",
          "text": "AVContentKeySystem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySessionWithKeySystem:"
        }
      ],
      "role": "symbol",
      "title": "init(keySystem:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/init(keysystem:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:storageDirectoryAt:)": {
      "abstract": [
        {
          "text": "Creates a content key session to manage a collection of content decryption keys; points to a directory that stores abnormal session termination reports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "keySystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeySystem",
          "text": "AVContentKeySystem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "storageDirectoryAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:storageDirectoryAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySessionWithKeySystem:storageDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "init(keySystem:storageDirectoryAt:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/init(keysystem:storagedirectoryat:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidateAllPersistableContentKeys(forApp:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Invalidates all of an app’s persistable content keys and creates a secure server playback context (SPC) to verify the outcome of an invalidation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateAllPersistableContentKeys"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forApp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeySessionServerPlaybackContextOption",
          "text": "AVContentKeySessionServerPlaybackContextOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidateAllPersistableContentKeys(forApp:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateAllPersistableContentKeysForApp:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "invalidateAllPersistableContentKeys(forApp:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/invalidateallpersistablecontentkeys(forapp:options:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidatePersistableContentKey(_:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Invalidates the persistable content key and creates a secure server playback context (SPC) to verify the outcome of an invalidation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidatePersistableContentKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeySessionServerPlaybackContextOption",
          "text": "AVContentKeySessionServerPlaybackContextOption"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidatePersistableContentKey(_:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidatePersistableContentKey:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "invalidatePersistableContentKey(_:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/invalidatepersistablecontentkey(_:options:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/keySystem": {
      "abstract": [
        {
          "text": "The type of key system used to retrieve keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keySystem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVContentKeySystem",
          "text": "AVContentKeySystem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/keySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keySystem"
        }
      ],
      "role": "symbol",
      "title": "keySystem",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/keysystem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)": {
      "abstract": [
        {
          "text": "Creates a secure server playback context that the client sends to the key server to get an expiration date for the given persistable content key data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeSecureTokenForExpirationDate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofPersistableContentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeSecureTokenForExpirationDateOfPersistableContentKey:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/makesecuretokenforexpirationdate(ofpersistablecontentkey:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)": {
      "abstract": [
        {
          "text": "Returns the expired session reports for content key sessions created with the specified app identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pendingExpiredSessionReports"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAppIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "storageDirectoryAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pendingExpiredSessionReportsWithAppIdentifier:storageDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/pendingexpiredsessionreports(withappidentifier:storagedirectoryat:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/processContentKeyRequest(withIdentifier:initializationData:options:)": {
      "abstract": [
        {
          "text": "Tells the delegate to start loading the content decryption key with the specified identifier and initialization data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processContentKeyRequest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "initializationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/processContentKeyRequest(withIdentifier:initializationData:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processContentKeyRequestWithIdentifier:initializationData:options:"
        }
      ],
      "role": "symbol",
      "title": "processContentKeyRequest(withIdentifier:initializationData:options:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/processcontentkeyrequest(withidentifier:initializationdata:options:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removeContentKeyRecipient(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate to remove the specified recipient.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeContentKeyRecipient"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContentKeyRecipient",
          "text": "AVContentKeyRecipient"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removeContentKeyRecipient(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeContentKeyRecipient:"
        }
      ],
      "role": "symbol",
      "title": "removeContentKeyRecipient(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/removecontentkeyrecipient(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)": {
      "abstract": [
        {
          "text": "Removes expired session reports from storage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removePendingExpiredSessionReports"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "withAppIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "storageDirectoryAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removePendingExpiredSessionReports:withAppIdentifier:storageDirectoryAtURL:"
        }
      ],
      "role": "symbol",
      "title": "removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/removependingexpiredsessionreports(_:withappidentifier:storagedirectoryat:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/renewExpiringResponseData(for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that previously provided response data for a content key request is about to expire.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renewExpiringResponseData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/renewExpiringResponseData(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renewExpiringResponseDataForContentKeyRequest:"
        }
      ],
      "role": "symbol",
      "title": "renewExpiringResponseData(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/renewexpiringresponsedata(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/setDelegate(_:queue:)": {
      "abstract": [
        {
          "text": "Sets the session’s delegate object and the dispatch queue on which to call the delegate’s methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDelegate"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVContentKeySessionDelegate",
          "text": "AVContentKeySessionDelegate"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/setDelegate(_:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDelegate:queue:"
        }
      ],
      "role": "symbol",
      "title": "setDelegate(_:queue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/setdelegate(_:queue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/storageURL": {
      "abstract": [
        {
          "text": "A URL that points to a writable storage directory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "storageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/storageURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "storageURL"
        }
      ],
      "role": "symbol",
      "title": "storageURL",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession/storageurl"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate": {
      "abstract": [
        {
          "text": "A protocol that handles content key requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySessionDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionServerPlaybackContextOption": {
      "abstract": [
        {
          "text": "Options for specifying additional information for generating server playback context (SPC).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySessionServerPlaybackContextOption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionServerPlaybackContextOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySessionServerPlaybackContextOption"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySessionServerPlaybackContextOption",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessionserverplaybackcontextoption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySpecifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySpecifier"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySpecifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyspecifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySystem": {
      "abstract": [
        {
          "text": "A key-delivery method for a content key session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySystem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySystem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySystem"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySystem",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysystem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus": {
      "abstract": [
        {
          "text": "Constants that specify whether sufficient protection exists to display the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalContentProtectionStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalContentProtectionStatus"
        }
      ],
      "role": "symbol",
      "title": "AVExternalContentProtectionStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalcontentprotectionstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a persistable content decryption key request issued from a content key session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPersistableContentKeyRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPersistableContentKeyRequest"
        }
      ],
      "role": "symbol",
      "title": "AVPersistableContentKeyRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avpersistablecontentkeyrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)": {
      "abstract": [
        {
          "text": "Attaches a content key to a sample buffer for the purpose of content decryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferAttachContentKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKey",
          "text": "AVContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferAttachContentKey"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferAttachContentKey(_:_:_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferattachcontentkey(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "FairPlay-Streaming",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)"
      ],
      "title": "FairPlay Streaming"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Session",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:storageDirectoryAt:)"
      ],
      "title": "Creating a Session"
    },
    {
      "anchor": "Inspecting-the-Session",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/keySystem",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySystem",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/storageURL"
      ],
      "title": "Inspecting the Session"
    },
    {
      "anchor": "Managing-the-Delegate-Object",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/setDelegate(_:queue:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegateQueue"
      ],
      "title": "Managing the Delegate Object"
    },
    {
      "anchor": "Managing-Content-Key-Recipients",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentKeyRecipients",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/addContentKeyRecipient(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removeContentKeyRecipient(_:)"
      ],
      "title": "Managing Content Key Recipients"
    },
    {
      "anchor": "Processing-Requests",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/processContentKeyRequest(withIdentifier:initializationData:options:)"
      ],
      "title": "Processing Requests"
    },
    {
      "anchor": "Managing-Expiration",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/expire()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/renewExpiringResponseData(for:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentProtectionSessionIdentifier"
      ],
      "title": "Managing Expiration"
    },
    {
      "anchor": "Invalidating-Content-Keys",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidatePersistableContentKey(_:options:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidateAllPersistableContentKeys(forApp:options:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionServerPlaybackContextOption"
      ],
      "title": "Invalidating Content Keys"
    },
    {
      "anchor": "Handling-Expired-Session-Reports",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)"
      ],
      "title": "Handling Expired Session Reports"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContentKeySession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Session",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/init(keySystem:storageDirectoryAt:)"
              ],
              "title": "Creating a Session"
            },
            {
              "anchor": "Inspecting-the-Session",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/keySystem",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySystem",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/storageURL"
              ],
              "title": "Inspecting the Session"
            },
            {
              "anchor": "Managing-the-Delegate-Object",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/setDelegate(_:queue:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/delegateQueue"
              ],
              "title": "Managing the Delegate Object"
            },
            {
              "anchor": "Managing-Content-Key-Recipients",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentKeyRecipients",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/addContentKeyRecipient(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removeContentKeyRecipient(_:)"
              ],
              "title": "Managing Content Key Recipients"
            },
            {
              "anchor": "Processing-Requests",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/processContentKeyRequest(withIdentifier:initializationData:options:)"
              ],
              "title": "Processing Requests"
            },
            {
              "anchor": "Managing-Expiration",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/expire()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/renewExpiringResponseData(for:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/contentProtectionSessionIdentifier"
              ],
              "title": "Managing Expiration"
            },
            {
              "anchor": "Invalidating-Content-Keys",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidatePersistableContentKey(_:options:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/invalidateAllPersistableContentKeys(forApp:options:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionServerPlaybackContextOption"
              ],
              "title": "Invalidating Content Keys"
            },
            {
              "anchor": "Handling-Expired-Session-Reports",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession/removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)"
              ],
              "title": "Handling Expired Session Reports"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "FairPlay-Streaming",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)"
              ],
              "title": "FairPlay Streaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVContentKeySession"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1storageURL/title",
          "value": "storageURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1storageURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "storageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/title",
          "value": "AVContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1delegateQueue/title",
          "value": "delegateQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1delegateQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegateQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1invalidatePersistableContentKey(_:options:completionHandler:)/title",
          "value": "invalidatePersistableContentKey:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1invalidatePersistableContentKey(_:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidatePersistableContentKey:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/title",
          "value": "AVContentKeySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1contentKeyRecipients/title",
          "value": "contentKeyRecipients"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1contentKeyRecipients/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentKeyRecipients"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/title",
          "value": "AVContentKeySpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1renewExpiringResponseData(for:)/title",
          "value": "renewExpiringResponseDataForContentKeyRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1renewExpiringResponseData(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "renewExpiringResponseDataForContentKeyRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/title",
          "value": "AVPersistableContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPersistableContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPersistableContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAttachContentKey(_:_:_:)/title",
          "value": "AVSampleBufferAttachContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAttachContentKey(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferAttachContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1setDelegate(_:queue:)/title",
          "value": "setDelegate:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1setDelegate(_:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDelegate:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/title",
          "value": "AVContentKeyResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)/title",
          "value": "makeSecureTokenForExpirationDateOfPersistableContentKey:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1makeSecureTokenForExpirationDate(ofPersistableContentKey:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeSecureTokenForExpirationDateOfPersistableContentKey:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1addContentKeyRecipient(_:)/title",
          "value": "addContentKeyRecipient:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1addContentKeyRecipient(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addContentKeyRecipient:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionServerPlaybackContextOption/title",
          "value": "AVContentKeySessionServerPlaybackContextOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionServerPlaybackContextOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionServerPlaybackContextOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionServerPlaybackContextOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionServerPlaybackContextOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1keySystem/title",
          "value": "keySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1keySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1expire()/title",
          "value": "expire"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1expire()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "expire"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)/title",
          "value": "removePendingExpiredSessionReports:withAppIdentifier:storageDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1removePendingExpiredSessionReports(_:withAppIdentifier:storageDirectoryAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "removePendingExpiredSessionReports:withAppIdentifier:storageDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1contentProtectionSessionIdentifier/title",
          "value": "contentProtectionSessionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1contentProtectionSessionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentProtectionSessionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/title",
          "value": "AVContentKeySessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/title",
          "value": "AVContentKeyRecipient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySystem/title",
          "value": "AVContentKeySystem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySystem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySystem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySystem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1init(keySystem:storageDirectoryAt:)/title",
          "value": "contentKeySessionWithKeySystem:storageDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1init(keySystem:storageDirectoryAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contentKeySessionWithKeySystem:storageDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1removeContentKeyRecipient(_:)/title",
          "value": "removeContentKeyRecipient:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1removeContentKeyRecipient(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeContentKeyRecipient:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1init(keySystem:)/title",
          "value": "contentKeySessionWithKeySystem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1init(keySystem:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "contentKeySessionWithKeySystem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)/title",
          "value": "pendingExpiredSessionReportsWithAppIdentifier:storageDirectoryAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1pendingExpiredSessionReports(withAppIdentifier:storageDirectoryAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "pendingExpiredSessionReportsWithAppIdentifier:storageDirectoryAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/title",
          "value": "AVExternalContentProtectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalContentProtectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalContentProtectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/title",
          "value": "AVContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1processContentKeyRequest(withIdentifier:initializationData:options:)/title",
          "value": "processContentKeyRequestWithIdentifier:initializationData:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1processContentKeyRequest(withIdentifier:initializationData:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processContentKeyRequestWithIdentifier:initializationData:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1invalidateAllPersistableContentKeys(forApp:options:completionHandler:)/title",
          "value": "invalidateAllPersistableContentKeysForApp:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession~1invalidateAllPersistableContentKeys(forApp:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateAllPersistableContentKeysForApp:options:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeysession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeysession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
