{
  "abstract": [
    {
      "text": "A track in a composition that presents media of a uniform type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVCompositionTrack",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVCompositionTrack"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVCompositionTrack"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVCompositionTrack"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This object provides an immutable composition track. The framework also provides a mutable subclass, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack": {
      "abstract": [
        {
          "text": "An object that models a track of media that an asset contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading": {
      "abstract": [
        {
          "text": "A protocol that defines the interface to load media data asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "role": "symbol",
      "title": "AVAsynchronousKeyValueLoading",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronouskeyvalueloading"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVComposition": {
      "abstract": [
        {
          "text": "An object that combines and arranges media from multiple assets into a single composite asset that you can play or process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVComposition"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVComposition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVComposition"
        }
      ],
      "role": "symbol",
      "title": "AVComposition",
      "type": "topic",
      "url": "/documentation/avfoundation/avcomposition"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack": {
      "abstract": [
        {
          "text": "A track in a composition that presents media of a uniform type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrack"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/associatedTracks(ofType:)": {
      "abstract": [
        {
          "text": "Returns an array of associated tracks that have the specified association type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "associatedTracks"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVTrackAssociationType",
          "text": "AssociationType"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/associatedTracks(ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "associatedTracksOfType:"
        }
      ],
      "role": "symbol",
      "title": "associatedTracks(ofType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/associatedtracks(oftype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableMetadataFormats": {
      "abstract": [
        {
          "text": "An array of metadata formats available for the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableMetadataFormats"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataFormat",
          "text": "AVMetadataFormat"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableMetadataFormats",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableMetadataFormats",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/availablemetadataformats"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableTrackAssociationTypes": {
      "abstract": [
        {
          "text": "An array of association types that the track uses to associate with other tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableTrackAssociationTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVTrackAssociationType",
          "text": "AssociationType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableTrackAssociationTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "availableTrackAssociationTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/availabletrackassociationtypes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/canProvideSampleCursors": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track can provide instances of sample cursors to traverse its media samples and discover information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canProvideSampleCursors"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/canProvideSampleCursors",
      "kind": "symbol",
      "role": "symbol",
      "title": "canProvideSampleCursors",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/canprovidesamplecursors"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/commonMetadata": {
      "abstract": [
        {
          "text": "An array of metadata items for all common metadata keys that have a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commonMetadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/commonMetadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "commonMetadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/commonmetadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/estimatedDataRate": {
      "abstract": [
        {
          "text": "The estimated data rate, in bits per second, of the media that the track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "estimatedDataRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/estimatedDataRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "estimatedDataRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/estimateddatarate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/extendedLanguageTag": {
      "abstract": [
        {
          "text": "The language tag of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendedLanguageTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/extendedLanguageTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "extendedLanguageTag",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/extendedlanguagetag"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements": {
      "abstract": [
        {
          "text": "The replacement format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescriptionReplacements"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrackFormatDescriptionReplacement",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "formatDescriptionReplacements"
        }
      ],
      "role": "symbol",
      "title": "formatDescriptionReplacements",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/formatdescriptionreplacements"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions": {
      "abstract": [
        {
          "text": "The format descriptions of the media samples that a track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "formatDescriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "formatDescriptions",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/formatdescriptions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasAudioSampleDependencies": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track has sample dependencies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasAudioSampleDependencies"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasAudioSampleDependencies",
      "kind": "symbol",
      "role": "symbol",
      "title": "hasAudioSampleDependencies",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/hasaudiosampledependencies"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasMediaCharacteristic(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the track references media with the specified media characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasMediaCharacteristic(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasMediaCharacteristic:"
        }
      ],
      "role": "symbol",
      "title": "hasMediaCharacteristic(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/hasmediacharacteristic(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isDecodable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track is decodable in the current environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDecodable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isDecodable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isDecodable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/isdecodable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track’s container enables it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/isenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isPlayable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the track is playable in the current environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlayable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isPlayable",
      "kind": "symbol",
      "role": "symbol",
      "title": "isPlayable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/isplayable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isSelfContained": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether this track references sample data only within its container file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSelfContained"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isSelfContained",
      "kind": "symbol",
      "role": "symbol",
      "title": "isSelfContained",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/isselfcontained"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/languageCode": {
      "abstract": [
        {
          "text": "The language code of the track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "languageCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/languageCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "languageCode",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/languagecode"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata": {
      "abstract": [
        {
          "text": "An array of metadata items for all metadata identifiers that have a value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/metadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata(forFormat:)": {
      "abstract": [
        {
          "text": "Returns metadata items that a track contains for the specified format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadata"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFormat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataFormat",
          "text": "AVMetadataFormat"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataItem",
          "text": "AVMetadataItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata(forFormat:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForFormat:"
        }
      ],
      "role": "symbol",
      "title": "metadata(forFormat:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/metadata(forformat:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/minFrameDuration": {
      "abstract": [
        {
          "text": "The minimum duration of the track’s frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minFrameDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/minFrameDuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "minFrameDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/minframeduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize": {
      "abstract": [
        {
          "text": "The natural dimensions of the media data that the track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "naturalSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/naturalsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalTimeScale": {
      "abstract": [
        {
          "text": "The natural time scale of the media that a track references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "naturalTimeScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimeScale",
          "text": "CMTimeScale"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalTimeScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "naturalTimeScale",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/naturaltimescale"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/nominalFrameRate": {
      "abstract": [
        {
          "text": "The frame rate of the track, in frames per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nominalFrameRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/nominalFrameRate",
      "kind": "symbol",
      "role": "symbol",
      "title": "nominalFrameRate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/nominalframerate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform": {
      "abstract": [
        {
          "text": "The track’s transform preference to apply to its visual content during presentation or processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredTransform",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/preferredtransform"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredVolume": {
      "abstract": [
        {
          "text": "The track’s volume preference for playing its audible media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredVolume"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredVolume",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredVolume",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/preferredvolume"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/requiresFrameReordering": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether samples in the track may have different presentation and decode timestamps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFrameReordering"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/requiresFrameReordering",
      "kind": "symbol",
      "role": "symbol",
      "title": "requiresFrameReordering",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/requiresframereordering"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/samplePresentationTime(forTrackTime:)": {
      "abstract": [
        {
          "text": "Maps the specified track time through the appropriate time mapping and returns the resulting sample presentation time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplePresentationTime"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTrackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/samplePresentationTime(forTrackTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplePresentationTimeForTrackTime:"
        }
      ],
      "role": "symbol",
      "title": "samplePresentationTime(forTrackTime:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/samplepresentationtime(fortracktime:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segment(forTrackTime:)": {
      "abstract": [
        {
          "text": "Returns a segment whose target time range contains, or is closest to, the specified track time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTrackTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrackSegment",
          "text": "AVCompositionTrackSegment"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segment(forTrackTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segmentForTrackTime:"
        }
      ],
      "role": "symbol",
      "title": "segment(forTrackTime:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/segment(fortracktime:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segments": {
      "abstract": [
        {
          "text": "The time mappings from the track’s media samples to its timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrackSegment",
          "text": "AVCompositionTrackSegment"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segments"
        }
      ],
      "role": "symbol",
      "title": "segments",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/segments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/timeRange": {
      "abstract": [
        {
          "text": "The time range of the track within the overall timeline of the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTimeRange",
          "text": "CMTimeRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/timeRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "timeRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/timerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/totalSampleDataLength": {
      "abstract": [
        {
          "text": "The total number of bytes of sample data the track requires.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSampleDataLength"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/totalSampleDataLength",
      "kind": "symbol",
      "role": "symbol",
      "title": "totalSampleDataLength",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrack/totalsampledatalength"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement": {
      "abstract": [
        {
          "text": "An object that represents a format description and its replacement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrackFormatDescriptionReplacement"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrackFormatDescriptionReplacement",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontrackformatdescriptionreplacement"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackSegment": {
      "abstract": [
        {
          "text": "A track segment that maps a time from the source media track to the composition track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCompositionTrackSegment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCompositionTrackSegment"
        }
      ],
      "role": "symbol",
      "title": "AVCompositionTrackSegment",
      "type": "topic",
      "url": "/documentation/avfoundation/avcompositiontracksegment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack": {
      "abstract": [
        {
          "text": "A mutable track in a composition that you use to insert, remove, and scale track segments without affecting their low-level representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableCompositionTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableCompositionTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMutableCompositionTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecompositiontrack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compositions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVComposition",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackSegment"
      ],
      "title": "Compositions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Track-Information",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isPlayable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isDecodable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/isSelfContained",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/totalSampleDataLength",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasMediaCharacteristic(_:)"
      ],
      "title": "Accessing Track Information"
    },
    {
      "anchor": "Accessing-Temporal-Information",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/timeRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalTimeScale",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/estimatedDataRate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/samplePresentationTime(forTrackTime:)"
      ],
      "title": "Accessing Temporal Information"
    },
    {
      "anchor": "Accessing-Language-Support",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/languageCode",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/extendedLanguageTag"
      ],
      "title": "Accessing Language Support"
    },
    {
      "anchor": "Managing-Format-Descriptions",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptions",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement"
      ],
      "title": "Managing Format Descriptions"
    },
    {
      "anchor": "Accessing-Visual-Characteristics",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/naturalSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredTransform"
      ],
      "title": "Accessing Visual Characteristics"
    },
    {
      "anchor": "Accessing-Audible-Characteristics",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/preferredVolume",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasAudioSampleDependencies"
      ],
      "title": "Accessing Audible Characteristics"
    },
    {
      "anchor": "Accessing-Frame-Based-Characteristics",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/nominalFrameRate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/minFrameDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/requiresFrameReordering"
      ],
      "title": "Accessing Frame-Based Characteristics"
    },
    {
      "anchor": "Accessing-Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/commonMetadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableMetadataFormats",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata(forFormat:)"
      ],
      "title": "Accessing Metadata"
    },
    {
      "anchor": "Accessing-Track-Segments",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segments",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segment(forTrackTime:)"
      ],
      "title": "Accessing Track Segments"
    },
    {
      "anchor": "Accessing-Track-Associations",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/availableTrackAssociationTypes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/associatedTracks(ofType:)"
      ],
      "title": "Accessing Track Associations"
    },
    {
      "anchor": "Determining-Sample-Cursor-Support",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/canProvideSampleCursors"
      ],
      "title": "Determining Sample Cursor Support"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Track-Information",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/hasMediaCharacteristic(_:)"
              ],
              "title": "Accessing Track Information"
            },
            {
              "anchor": "Accessing-Temporal-Information",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/samplePresentationTime(forTrackTime:)"
              ],
              "title": "Accessing Temporal Information"
            },
            {
              "anchor": "Managing-Format-Descriptions",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/formatDescriptionReplacements",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackFormatDescriptionReplacement"
              ],
              "title": "Managing Format Descriptions"
            },
            {
              "anchor": "Accessing-Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/metadata(forFormat:)"
              ],
              "title": "Accessing Metadata"
            },
            {
              "anchor": "Accessing-Track-Segments",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segments",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/segment(forTrackTime:)"
              ],
              "title": "Accessing Track Segments"
            },
            {
              "anchor": "Accessing-Track-Associations",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrack/associatedTracks(ofType:)"
              ],
              "title": "Accessing Track Associations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableCompositionTrack"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compositions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVComposition",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCompositionTrackSegment"
              ],
              "title": "Compositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVCompositionTrack"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVAssetTrack",
                    "text": "AVAssetTrack"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1associatedTracks(ofType:)/title",
          "value": "associatedTracksOfType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1associatedTracks(ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "associatedTracksOfType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVComposition/title",
          "value": "AVComposition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVComposition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVComposition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVComposition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1samplePresentationTime(forTrackTime:)/title",
          "value": "samplePresentationTimeForTrackTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1samplePresentationTime(forTrackTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "samplePresentationTimeForTrackTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackSegment/title",
          "value": "AVCompositionTrackSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1hasMediaCharacteristic(_:)/title",
          "value": "hasMediaCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1hasMediaCharacteristic(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hasMediaCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/title",
          "value": "AVAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/title",
          "value": "AVMutableCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableCompositionTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1segment(forTrackTime:)/title",
          "value": "segmentForTrackTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1segment(forTrackTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "segmentForTrackTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/title",
          "value": "AVCompositionTrackFormatDescriptionReplacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackFormatDescriptionReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrackFormatDescriptionReplacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrackFormatDescriptionReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1formatDescriptionReplacements/title",
          "value": "formatDescriptionReplacements"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1formatDescriptionReplacements/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "formatDescriptionReplacements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/title",
          "value": "AVCompositionTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCompositionTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1segments/title",
          "value": "segments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1segments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "segments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1metadata(forFormat:)/title",
          "value": "metadataForFormat:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCompositionTrack~1metadata(forFormat:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "metadataForFormat:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/title",
          "value": "AVAsynchronousKeyValueLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcompositiontrack"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcompositiontrack"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
