{
  "abstract": [
    {
      "text": "A value representing the status of a content authorization request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVContentAuthorizationStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVContentAuthorizationStatus"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContentAuthorizationStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVContentAuthorizationStatus"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Even if authorization is completed by the user, there is no guarantee that the content will then be authorized. You should re-check whether the content is authorized before proceeding.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus": {
      "abstract": [
        {
          "text": "A value representing the status of a content authorization request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed because another asset is currently attempting authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationBusy"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.busy",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/busy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled": {
      "abstract": [
        {
          "text": "The last call to request content authorization was cancelled by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationCancelled"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.cancelled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/cancelled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed": {
      "abstract": [
        {
          "text": "The last completed call to request content authorization completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completed"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationCompleted"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.completed",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/completed"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed because there was no known mechanism by which to attempt authorization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailable"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationNotAvailable"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.notAvailable",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/notavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible": {
      "abstract": [
        {
          "text": "The last call to request content authorization couldn’t be completed in a non-recoverable way.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notPossible"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationNotPossible"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.notPossible",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/notpossible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut": {
      "abstract": [
        {
          "text": "The last call to request content authorization was cancelled because the timeout interval was reached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timedOut"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationTimedOut"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.timedOut",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/timedout"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown": {
      "abstract": [
        {
          "text": "The content authorization content request hasn’t completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentAuthorizationUnknown"
        }
      ],
      "role": "symbol",
      "title": "AVContentAuthorizationStatus.unknown",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentauthorizationstatus/unknown"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()": {
      "abstract": [
        {
          "text": "Cancels the currently outstanding content authorization request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelContentAuthorizationRequest"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelContentAuthorizationRequest"
        }
      ],
      "role": "symbol",
      "title": "cancelContentAuthorizationRequest()",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/cancelcontentauthorizationrequest()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus": {
      "abstract": [
        {
          "text": "The status of the most recent content authorization request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentAuthorizationRequestStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVContentAuthorizationStatus",
          "text": "AVContentAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentAuthorizationRequestStatus"
        }
      ],
      "role": "symbol",
      "title": "contentAuthorizationRequestStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/contentauthorizationrequeststatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the application can be used to play the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isApplicationAuthorizedForPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationAuthorizedForPlayback"
        }
      ],
      "role": "symbol",
      "title": "isApplicationAuthorizedForPlayback",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/isapplicationauthorizedforplayback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether authorization is required to play the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAuthorizationRequiredForPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationRequiredForPlayback"
        }
      ],
      "role": "symbol",
      "title": "isAuthorizationRequiredForPlayback",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/isauthorizationrequiredforplayback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the content has been authorized by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isContentAuthorizedForPlayback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentAuthorizedForPlayback"
        }
      ],
      "role": "symbol",
      "title": "isContentAuthorizedForPlayback",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/iscontentauthorizedforplayback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)": {
      "abstract": [
        {
          "text": "Presents the user the opportunity to authorize the content for playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestContentAuthorizationAsynchronously"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTimeoutInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/requestcontentauthorizationasynchronously(withtimeoutinterval:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-Playback-Authorization-in-macOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"
      ],
      "title": "Managing Playback Authorization in macOS"
    }
  ],
  "topicSections": [
    {
      "anchor": "Content-Authorization-Statuses",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible"
      ],
      "title": "Content Authorization Statuses"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContentAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Content-Authorization-Statuses",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/unknown",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/completed",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/cancelled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/timedOut",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/busy",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notAvailable",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentAuthorizationStatus/notPossible"
              ],
              "title": "Content Authorization Statuses"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-Playback-Authorization-in-macOS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isContentAuthorizedForPlayback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isAuthorizationRequiredForPlayback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/isApplicationAuthorizedForPlayback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/contentAuthorizationRequestStatus",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/cancelContentAuthorizationRequest()"
              ],
              "title": "Managing Playback Authorization in macOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVContentAuthorizationStatus"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/title",
          "value": "applicationAuthorizedForPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isApplicationAuthorizedForPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationAuthorizedForPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1completed/title",
          "value": "AVContentAuthorizationCompleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1completed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationCompleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/title",
          "value": "requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1requestContentAuthorizationAsynchronously(withTimeoutInterval:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestContentAuthorizationAsynchronouslyWithTimeoutInterval:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/title",
          "value": "AVContentAuthorizationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/title",
          "value": "contentAuthorizationRequestStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1contentAuthorizationRequestStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentAuthorizationRequestStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/title",
          "value": "AVContentAuthorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/title",
          "value": "contentAuthorizedForPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isContentAuthorizedForPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentAuthorizedForPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notPossible/title",
          "value": "AVContentAuthorizationNotPossible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notPossible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationNotPossible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1timedOut/title",
          "value": "AVContentAuthorizationTimedOut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1timedOut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationTimedOut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notAvailable/title",
          "value": "AVContentAuthorizationNotAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1notAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationNotAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1cancelled/title",
          "value": "AVContentAuthorizationCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/title",
          "value": "authorizationRequiredForPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1isAuthorizationRequiredForPlayback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationRequiredForPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/title",
          "value": "cancelContentAuthorizationRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1cancelContentAuthorizationRequest()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelContentAuthorizationRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1busy/title",
          "value": "AVContentAuthorizationBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentAuthorizationStatus~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentAuthorizationBusy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcontentauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcontentauthorizationstatus"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
