{
  "abstract": [
    {
      "text": "An object that encapsulates information about a content decryption key request issued from a content key session object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVContentKeyRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVContentKeyRequest"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVContentKeyRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVContentKeyRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey": {
      "abstract": [
        {
          "text": "An object that represents the content key decryptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKey"
        }
      ],
      "role": "symbol",
      "title": "AVContentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a content decryption key request issued from a content key session object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRequest"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason": {
      "abstract": [
        {
          "text": "The reason for asking the client to retry a content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RetryReason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RetryReason"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequest.RetryReason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/retryreason"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/Status-swift.enum": {
      "abstract": [
        {
          "text": "The status for a content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/Status-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Status"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequest.Status",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/status-swift.enum"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/canProvidePersistableContentKey": {
      "abstract": [
        {
          "text": "The content key request used to create a persistable content key or respond to a previous request with a persistable content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canProvidePersistableContentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/canProvidePersistableContentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canProvidePersistableContentKey"
        }
      ],
      "role": "symbol",
      "title": "canProvidePersistableContentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/canprovidepersistablecontentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKey": {
      "abstract": [
        {
          "text": "The generated content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKey",
          "text": "AVContentKey"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKey"
        }
      ],
      "role": "symbol",
      "title": "contentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/contentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKeySpecifier": {
      "abstract": [
        {
          "text": "The requested content key specifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentKeySpecifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeySpecifier",
          "text": "AVContentKeySpecifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKeySpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentKeySpecifier"
        }
      ],
      "role": "symbol",
      "title": "contentKeySpecifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/contentkeyspecifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/error": {
      "abstract": [
        {
          "text": "The error description for a failed key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/error"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/identifier": {
      "abstract": [
        {
          "text": "The identifier for the content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/identifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/initializationData": {
      "abstract": [
        {
          "text": "The data used to obtain a key response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initializationData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/initializationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initializationData"
        }
      ],
      "role": "symbol",
      "title": "initializationData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/initializationdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)": {
      "abstract": [
        {
          "text": "Obtains encrypted key request data for a specific combination of app and content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeStreamingContentKeyRequestData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forApp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "makeStreamingContentKeyRequestDataForApp:contentIdentifier:options:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/makestreamingcontentkeyrequestdata(forapp:contentidentifier:options:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/options": {
      "abstract": [
        {
          "text": "A dictionary of options used to initialize key loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/options",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "options"
        }
      ],
      "role": "symbol",
      "title": "options",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/options"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponse(_:)": {
      "abstract": [
        {
          "text": "Sends the specified content key response to the receiver for processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processContentKeyResponse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyResponse",
          "text": "AVContentKeyResponse"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponse(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processContentKeyResponse:"
        }
      ],
      "role": "symbol",
      "title": "processContentKeyResponse(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/processcontentkeyresponse(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponseError(_:)": {
      "abstract": [
        {
          "text": "Tells the receiver that the app was unable to obtain a content key response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processContentKeyResponseError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponseError(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "processContentKeyResponseError:"
        }
      ],
      "role": "symbol",
      "title": "processContentKeyResponseError(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/processcontentkeyresponseerror(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/renewsExpiringResponseData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the content key request renews previously provided response data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "renewsExpiringResponseData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/renewsExpiringResponseData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "renewsExpiringResponseData"
        }
      ],
      "role": "symbol",
      "title": "renewsExpiringResponseData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/renewsexpiringresponsedata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()": {
      "abstract": [
        {
          "text": "Tells the receiver that the app requires a persistable content key request object for processing.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "respondByRequestingPersistableContentKeyRequest"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "respondByRequestingPersistableContentKeyRequest"
        }
      ],
      "role": "symbol",
      "title": "respondByRequestingPersistableContentKeyRequest()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/respondbyrequestingpersistablecontentkeyrequest()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequestAndReturnError()": {
      "abstract": [
        {
          "text": "Tells the receiver that the app requires a persistable content key request object for processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "respondByRequestingPersistableContentKeyRequestAndReturnError"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequestAndReturnError()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "respondByRequestingPersistableContentKeyRequestAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "respondByRequestingPersistableContentKeyRequestAndReturnError()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/respondbyrequestingpersistablecontentkeyrequestandreturnerror()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/status-swift.property": {
      "abstract": [
        {
          "text": "The current state of the content key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKeyRequest",
          "text": "AVContentKeyRequest"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVContentKeyRequestStatus",
          "text": "Status"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/status-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequest/status-swift.property"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestProtocolVersionsKey": {
      "abstract": [
        {
          "text": "A key that specifies the versions of the content protection protocol supported by the application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRequestProtocolVersionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestProtocolVersionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRequestProtocolVersionsKey"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequestProtocolVersionsKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequestprotocolversionskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestRequiresValidationDataInSecureTokenKey": {
      "abstract": [
        {
          "text": "A key that requires the secure token to have extended validation data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestRequiresValidationDataInSecureTokenKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRequestRequiresValidationDataInSecureTokenKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrequestrequiresvalidationdatainsecuretokenkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a response to a content decryption key request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyResponse"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyResponse"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyResponse",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyresponse"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession": {
      "abstract": [
        {
          "text": "An object that creates and tracks decryption keys for media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySession"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate": {
      "abstract": [
        {
          "text": "A protocol that handles content key requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySessionDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySessionDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeysessiondelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier": {
      "abstract": [
        {
          "text": "An object that uniquely identifies a content key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeySpecifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeySpecifier"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeySpecifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyspecifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus": {
      "abstract": [
        {
          "text": "Constants that specify whether sufficient protection exists to display the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalContentProtectionStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalContentProtectionStatus"
        }
      ],
      "role": "symbol",
      "title": "AVExternalContentProtectionStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalcontentprotectionstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest": {
      "abstract": [
        {
          "text": "An object that encapsulates information about a persistable content decryption key request issued from a content key session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPersistableContentKeyRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPersistableContentKeyRequest"
        }
      ],
      "role": "symbol",
      "title": "AVPersistableContentKeyRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avpersistablecontentkeyrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)": {
      "abstract": [
        {
          "text": "Attaches a content key to a sample buffer for the purpose of content decryption.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferAttachContentKey"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVContentKey",
          "text": "AVContentKey"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation14NSErrorPointera",
          "text": "NSErrorPointer"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferAttachContentKey"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferAttachContentKey(_:_:_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferattachcontentkey(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "FairPlay-Streaming",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)"
      ],
      "title": "FairPlay Streaming"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Content-Key-Request-Data",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestProtocolVersionsKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
      ],
      "title": "Getting Content Key Request Data"
    },
    {
      "anchor": "Responding-to-the-Content-Key-Request",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponse(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponseError(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()"
      ],
      "title": "Responding to the Content Key Request"
    },
    {
      "anchor": "Getting-Content-Key-Request-Properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/identifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/canProvidePersistableContentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/error",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/initializationData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/renewsExpiringResponseData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/status-swift.property",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/Status-swift.enum"
      ],
      "title": "Getting Content Key Request Properties"
    },
    {
      "anchor": "Inspecting-a-Request",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKeySpecifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/options",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason"
      ],
      "title": "Inspecting a Request"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequestAndReturnError()"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Content-Key-Request-Data",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestProtocolVersionsKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
              ],
              "title": "Getting Content Key Request Data"
            },
            {
              "anchor": "Responding-to-the-Content-Key-Request",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponse(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/processContentKeyResponseError(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequest()"
              ],
              "title": "Responding to the Content Key Request"
            },
            {
              "anchor": "Getting-Content-Key-Request-Properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/identifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/canProvidePersistableContentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/error",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/initializationData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/renewsExpiringResponseData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/status-swift.property",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/Status-swift.enum"
              ],
              "title": "Getting Content Key Request Properties"
            },
            {
              "anchor": "Inspecting-a-Request",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/contentKeySpecifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/options",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/RetryReason"
              ],
              "title": "Inspecting a Request"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRequest/respondByRequestingPersistableContentKeyRequestAndReturnError()"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "FairPlay-Streaming",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySession",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySessionDelegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeySpecifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPersistableContentKeyRequest",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyResponse",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalContentProtectionStatus",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAttachContentKey(_:_:_:)"
              ],
              "title": "FairPlay Streaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVContentKeyRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)/title",
          "value": "makeStreamingContentKeyRequestDataForApp:contentIdentifier:options:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1makeStreamingContentKeyRequestData(forApp:contentIdentifier:options:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "makeStreamingContentKeyRequestDataForApp:contentIdentifier:options:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1Status-swift.enum/title",
          "value": "AVContentKeyRequestStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1Status-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1Status-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1canProvidePersistableContentKey/title",
          "value": "canProvidePersistableContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1canProvidePersistableContentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canProvidePersistableContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1respondByRequestingPersistableContentKeyRequest()/title",
          "value": "respondByRequestingPersistableContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1respondByRequestingPersistableContentKeyRequest()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "respondByRequestingPersistableContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1contentKeySpecifier/title",
          "value": "contentKeySpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1contentKeySpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentKeySpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAttachContentKey(_:_:_:)/title",
          "value": "AVSampleBufferAttachContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAttachContentKey(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferAttachContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/title",
          "value": "AVExternalContentProtectionStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalContentProtectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalContentProtectionStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalContentProtectionStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1error/title",
          "value": "error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/title",
          "value": "AVContentKeySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1processContentKeyResponseError(_:)/title",
          "value": "processContentKeyResponseError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1processContentKeyResponseError(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processContentKeyResponseError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequestRequiresValidationDataInSecureTokenKey/title",
          "value": "AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequestRequiresValidationDataInSecureTokenKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestRequiresValidationDataInSecureTokenKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1contentKey/title",
          "value": "contentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1contentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1status-swift.property/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1status-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1respondByRequestingPersistableContentKeyRequestAndReturnError()/title",
          "value": "respondByRequestingPersistableContentKeyRequestAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1respondByRequestingPersistableContentKeyRequestAndReturnError()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "respondByRequestingPersistableContentKeyRequestAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/title",
          "value": "AVContentKeyResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1options/title",
          "value": "options"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1options/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/title",
          "value": "AVContentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/title",
          "value": "AVContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1processContentKeyResponse(_:)/title",
          "value": "processContentKeyResponse:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1processContentKeyResponse(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "processContentKeyResponse:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/title",
          "value": "AVContentKeySessionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySessionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySessionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/title",
          "value": "AVContentKeySpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeySpecifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeySpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1renewsExpiringResponseData/title",
          "value": "renewsExpiringResponseData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1renewsExpiringResponseData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "renewsExpiringResponseData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1initializationData/title",
          "value": "initializationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1initializationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initializationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/title",
          "value": "AVPersistableContentKeyRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPersistableContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPersistableContentKeyRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPersistableContentKeyRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequestProtocolVersionsKey/title",
          "value": "AVContentKeyRequestProtocolVersionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequestProtocolVersionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestProtocolVersionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/title",
          "value": "AVContentKeyRequestRetryReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestRetryReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRequest~1RetryReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRequestRetryReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeyrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avcontentkeyrequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
