{
  "abstract": [
    {
      "text": "A command that indicates to play at a specific rate and time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVDelegatingPlaybackCoordinatorPlayCommand",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVDelegatingPlaybackCoordinatorPlayCommand"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorBufferingCommand": {
      "abstract": [
        {
          "text": "A command that indicates to start buffering data in preparation for playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorBufferingCommand"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorBufferingCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorBufferingCommand"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinatorBufferingCommand",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorbufferingcommand"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPauseCommand": {
      "abstract": [
        {
          "text": "A command that indicates to pause playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPauseCommand"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPauseCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPauseCommand"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinatorPauseCommand",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorpausecommand"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand": {
      "abstract": [
        {
          "text": "A command that indicates to play at a specific rate and time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinatorPlayCommand",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/hostClockTime": {
      "abstract": [
        {
          "text": "A host clock time to use to begin playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hostClockTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/hostClockTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hostClockTime"
        }
      ],
      "role": "symbol",
      "title": "hostClockTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand/hostclocktime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/itemTime": {
      "abstract": [
        {
          "text": "A time in the item timeline to use to begin playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/itemTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemTime"
        }
      ],
      "role": "symbol",
      "title": "itemTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand/itemtime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/rate": {
      "abstract": [
        {
          "text": "A rate to use when starting playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/rate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rate"
        }
      ],
      "role": "symbol",
      "title": "rate",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand/rate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand": {
      "abstract": [
        {
          "text": "An abstract superclass for playback commands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaybackcontrolcommand"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorSeekCommand": {
      "abstract": [
        {
          "text": "A command that indicates to seek to a new time in the item timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorSeekCommand"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorSeekCommand",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinatorSeekCommand"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinatorSeekCommand",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinatorseekcommand"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playback-Commands",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPauseCommand",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorSeekCommand",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorBufferingCommand"
      ],
      "title": "Playback Commands"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-Command-Details",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/rate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/itemTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/hostClockTime"
      ],
      "title": "Accessing Command Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVDelegatingPlaybackCoordinatorPlayCommand"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-Command-Details",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/rate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/itemTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlayCommand/hostClockTime"
              ],
              "title": "Accessing Command Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Playback-Commands",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPauseCommand",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorSeekCommand",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorBufferingCommand"
              ],
              "title": "Playback Commands"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVDelegatingPlaybackCoordinatorPlaybackControlCommand",
                    "text": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorSeekCommand/title",
          "value": "AVDelegatingPlaybackCoordinatorSeekCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorSeekCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorSeekCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorSeekCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorSeekCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPauseCommand/title",
          "value": "AVDelegatingPlaybackCoordinatorPauseCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPauseCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPauseCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPauseCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPauseCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1hostClockTime/title",
          "value": "hostClockTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1hostClockTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hostClockTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand/title",
          "value": "AVDelegatingPlaybackCoordinatorPlayCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlayCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1rate/title",
          "value": "rate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1rate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorBufferingCommand/title",
          "value": "AVDelegatingPlaybackCoordinatorBufferingCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorBufferingCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorBufferingCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorBufferingCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorBufferingCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlaybackControlCommand/title",
          "value": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlaybackControlCommand/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlaybackControlCommand/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinatorPlaybackControlCommand"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1itemTime/title",
          "value": "itemTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinatorPlayCommand~1itemTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemTime"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avdelegatingplaybackcoordinatorplaycommand"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
