{
  "abstract": [
    {
      "text": "An object that expresses an inclusive range of supported exposure bias values, in EV units.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVExposureBiasRange",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVExposureBiasRange"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVExposureBiasRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVExposureBiasRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVExposureBiasRange"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines its range using this type.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxExposureDuration": {
      "abstract": [
        {
          "text": "A time value that indicates the maximum supported exposure duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxExposureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxExposureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxExposureDuration"
        }
      ],
      "role": "symbol",
      "title": "maxExposureDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/maxexposureduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxISO": {
      "abstract": [
        {
          "text": "A floating-point number that indicates the maximum supported exposure ISO value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxISO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxISO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxISO"
        }
      ],
      "role": "symbol",
      "title": "maxISO",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/maxiso"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minExposureDuration": {
      "abstract": [
        {
          "text": "A time value that indicates the minimum supported exposure duration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minExposureDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minExposureDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minExposureDuration"
        }
      ],
      "role": "symbol",
      "title": "minExposureDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/minexposureduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minISO": {
      "abstract": [
        {
          "text": "A floating-point number that indicates the minimum supported exposure ISO value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minISO"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minISO",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minISO"
        }
      ],
      "role": "symbol",
      "title": "minISO",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/miniso"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedExposureBiasRange": {
      "abstract": [
        {
          "text": "The system’s recommended exposure bias range for this device format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "systemRecommendedExposureBiasRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedExposureBiasRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemRecommendedExposureBiasRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceformat/systemrecommendedexposurebiasrange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider": {
      "abstract": [
        {
          "text": "A control that adjusts the exposure bias of a capture device within the system-recommended range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureSystemExposureBiasSlider"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureSystemExposureBiasSlider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureSystemExposureBiasSlider"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureSystemExposureBiasSlider",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturesystemexposurebiasslider"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange": {
      "abstract": [
        {
          "text": "An object that expresses an inclusive range of supported exposure bias values, in EV units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVExposureBiasRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVExposureBiasRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avexposurebiasrange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/containsExposureBias:": {
      "abstract": [
        {
          "text": "Determines whether the range contains the specified exposure bias.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "containsExposureBias:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/containsExposureBias:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsExposureBias:"
        }
      ],
      "role": "symbol",
      "title": "containsExposureBias:",
      "type": "topic",
      "url": "/documentation/avfoundation/avexposurebiasrange/containsexposurebias:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/maxExposureBias": {
      "abstract": [
        {
          "text": "The maximum exposure bias in EV units that this range supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "maxExposureBias"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/maxExposureBias",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxExposureBias",
      "type": "topic",
      "url": "/documentation/avfoundation/avexposurebiasrange/maxexposurebias"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/minExposureBias": {
      "abstract": [
        {
          "text": "The minimum exposure bias in EV units that this range supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "minExposureBias"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/minExposureBias",
      "kind": "symbol",
      "role": "symbol",
      "title": "minExposureBias",
      "type": "topic",
      "url": "/documentation/avfoundation/avexposurebiasrange/minexposurebias"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Exposure-Support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedExposureBiasRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minISO",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxISO",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/minExposureDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/maxExposureDuration"
      ],
      "title": "Determining Exposure Support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-exposure-bias-range",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/minExposureBias",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/maxExposureBias",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExposureBiasRange/containsExposureBias:"
      ],
      "title": "Inspecting the exposure bias range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1minISO/title",
          "value": "minISO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1minISO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minISO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1maxExposureDuration/title",
          "value": "maxExposureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1maxExposureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxExposureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1minExposureDuration/title",
          "value": "minExposureDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1minExposureDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minExposureDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1maxISO/title",
          "value": "maxISO"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1maxISO/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxISO"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/title",
          "value": "AVCaptureSystemExposureBiasSlider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemExposureBiasSlider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureSystemExposureBiasSlider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureSystemExposureBiasSlider"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avexposurebiasrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
