{
  "abstract": [
    {
      "text": "Represents a physical external storage device that stores media assets.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVExternalStorageDevice",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVExternalStorageDevice"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVExternalStorageDevice"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVExternalStorageDevice"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each storage device instance corresponds to a physical external storage device where the system can media assets. You can access all of the currently available external storage devices with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession/externalStorageDevices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput": {
      "abstract": [
        {
          "text": "An object that provides media input from a capture device to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDeviceInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice": {
      "abstract": [
        {
          "text": "A class that represents a physical iOS device that’s nearby and can provide access to its cameras and microphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontinuitydevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice": {
      "abstract": [
        {
          "text": "Represents a physical external storage device that stores media assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/authorizationStatus": {
      "abstract": [
        {
          "text": "Your app’s authorization status for the external storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAuthorizationStatus",
          "text": "AVAuthorizationStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/authorizationStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationStatus"
        }
      ],
      "role": "symbol",
      "title": "authorizationStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/authorizationstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/displayName": {
      "abstract": [
        {
          "text": "The name of an external storage device that’s appropriate for a user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/displayName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayName"
        }
      ],
      "role": "symbol",
      "title": "displayName",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/displayname"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/freeSize": {
      "abstract": [
        {
          "text": "The amount of free storage space, in bytes, that’s available on the external storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/freeSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "freeSize"
        }
      ],
      "role": "symbol",
      "title": "freeSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/freesize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isConnected": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system has a connection to the external storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isConnected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isConnected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "connected"
        }
      ],
      "role": "symbol",
      "title": "isConnected",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/isconnected"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isNotRecommendedForCaptureUse": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the external storage device is suitable for camera capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNotRecommendedForCaptureUse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isNotRecommendedForCaptureUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "notRecommendedForCaptureUse"
        }
      ],
      "role": "symbol",
      "title": "isNotRecommendedForCaptureUse",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/isnotrecommendedforcaptureuse"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/nextAvailableURLs(withPathExtensions:)": {
      "abstract": [
        {
          "text": "Generates an array of security scoped URLs that are compliant for digital camera formats, where each element has a different path extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nextAvailableURLs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPathExtensions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/nextAvailableURLs(withPathExtensions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nextAvailableURLsWithPathExtensions:error:"
        }
      ],
      "role": "symbol",
      "title": "nextAvailableURLs(withPathExtensions:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/nextavailableurls(withpathextensions:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/requestAccess(completionHandler:)": {
      "abstract": [
        {
          "text": "Requests access to an external storage device on behalf of your app, which can present a dialog to a person on their device’s display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAccess"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/requestAccess(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestAccessWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestAccess(completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/requestaccess(completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/totalSize": {
      "abstract": [
        {
          "text": "The total amount of storage space, in bytes, that’s available on the external storage device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "totalSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/totalSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "totalSize"
        }
      ],
      "role": "symbol",
      "title": "totalSize",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/totalsize"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/uuid": {
      "abstract": [
        {
          "text": "The external storage device’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uuid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/uuid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "uuid"
        }
      ],
      "role": "symbol",
      "title": "uuid",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice/uuid"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession": {
      "abstract": [
        {
          "text": "Informs your app when the external storage devices connect to and disconnect from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDeviceDiscoverySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevicediscoverysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession/externalStorageDevices": {
      "abstract": [
        {
          "text": "An array of external storage devices the session updates as individual devices connect or disconnect from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "externalStorageDevices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVExternalStorageDevice",
          "text": "AVExternalStorageDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession/externalStorageDevices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "externalStorageDevices"
        }
      ],
      "role": "symbol",
      "title": "externalStorageDevices",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevicediscoverysession/externalstoragedevices"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device": {
      "abstract": [
        {
          "text": "Select the front or back camera, or use advanced features like the TrueDepth camera or dual camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
      "kind": "article",
      "role": "article",
      "title": "Choosing a Capture Device",
      "type": "topic",
      "url": "/documentation/avfoundation/choosing-a-capture-device"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capture-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
      ],
      "title": "Capture devices"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-permission-to-generate-URLs",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/authorizationStatus"
      ],
      "title": "Checking permission to generate URLs"
    },
    {
      "anchor": "Requesting-permission-to-generate-URLs",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/requestAccess(completionHandler:)"
      ],
      "title": "Requesting permission to generate URLs"
    },
    {
      "anchor": "Generating-URLs-for-image-assets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/nextAvailableURLs(withPathExtensions:)"
      ],
      "title": "Generating URLs for image assets"
    },
    {
      "anchor": "Inspecting-a-storage-device",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isConnected",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/displayName",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/uuid",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/freeSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/totalSize",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isNotRecommendedForCaptureUse"
      ],
      "title": "Inspecting a storage device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVExternalStorageDevice"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-permission-to-generate-URLs",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/authorizationStatus"
              ],
              "title": "Checking permission to generate URLs"
            },
            {
              "anchor": "Requesting-permission-to-generate-URLs",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/requestAccess(completionHandler:)"
              ],
              "title": "Requesting permission to generate URLs"
            },
            {
              "anchor": "Generating-URLs-for-image-assets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/nextAvailableURLs(withPathExtensions:)"
              ],
              "title": "Generating URLs for image assets"
            },
            {
              "anchor": "Inspecting-a-storage-device",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isConnected",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/displayName",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/uuid",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/freeSize",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/totalSize",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice/isNotRecommendedForCaptureUse"
              ],
              "title": "Inspecting a storage device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capture-devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
              ],
              "title": "Capture devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVExternalStorageDevice"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1authorizationStatus/title",
          "value": "authorizationStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1authorizationStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/title",
          "value": "AVExternalStorageDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/title",
          "value": "AVContinuityDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1isNotRecommendedForCaptureUse/title",
          "value": "notRecommendedForCaptureUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1isNotRecommendedForCaptureUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "notRecommendedForCaptureUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1freeSize/title",
          "value": "freeSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1freeSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "freeSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/title",
          "value": "AVCaptureDeviceInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1totalSize/title",
          "value": "totalSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1totalSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "totalSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1requestAccess(completionHandler:)/title",
          "value": "requestAccessWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1requestAccess(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "requestAccessWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession~1externalStorageDevices/title",
          "value": "externalStorageDevices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession~1externalStorageDevices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "externalStorageDevices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1displayName/title",
          "value": "displayName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1displayName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1nextAvailableURLs(withPathExtensions:)/title",
          "value": "nextAvailableURLsWithPathExtensions:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1nextAvailableURLs(withPathExtensions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "nextAvailableURLsWithPathExtensions:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1uuid/title",
          "value": "uuid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1uuid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "uuid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1isConnected/title",
          "value": "connected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice~1isConnected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "connected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/title",
          "value": "AVExternalStorageDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avexternalstoragedevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avexternalstoragedevice"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
