{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAILABLE_MAC_OS_X_VERSION_TBD_AND_LATER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAILABLE_MAC_OS_X_VERSION_TBD_AND_LATER"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAILABLE_MAC_OS_X_VERSION_TBD_AND_LATER",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAILABLE_MAC_OS_X_VERSION_TBD_AND_LATER",
      "type": "topic",
      "url": "/documentation/avfoundation/available_mac_os_x_version_tbd_and_later"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_AUDIO_PROCESSING_TAP_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVF_AUDIO_PROCESSING_TAP_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_AUDIO_PROCESSING_TAP_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVF_AUDIO_PROCESSING_TAP_AVAILABLE",
      "type": "topic",
      "url": "/documentation/avfoundation/avf_audio_processing_tap_available"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
        }
      ],
      "role": "symbol",
      "title": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER",
      "type": "topic",
      "url": "/documentation/avfoundation/avf_deploying_to_2022_releases_and_later"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2024_RELEASES_AND_LATER": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVF_DEPLOYING_TO_2024_RELEASES_AND_LATER"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2024_RELEASES_AND_LATER",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVF_DEPLOYING_TO_2024_RELEASES_AND_LATER",
      "type": "topic",
      "url": "/documentation/avfoundation/avf_deploying_to_2024_releases_and_later"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPRECATED_FOR_SWIFT_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVF_DEPRECATED_FOR_SWIFT_ONLY"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPRECATED_FOR_SWIFT_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVF_DEPRECATED_FOR_SWIFT_ONLY",
      "type": "topic",
      "url": "/documentation/avfoundation/avf_deprecated_for_swift_only"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVF_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVF_EXPORT",
      "type": "topic",
      "url": "/documentation/avfoundation/avf_export"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMETRICS_H": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMETRICS_H"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMETRICS_H",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMETRICS_H",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrics_h"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AV_INIT_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AV_INIT_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AV_INIT_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "AV_INIT_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/avfoundation/av_init_unavailable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AV_RENDERED_CAPTION_IMAGE_H": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AV_RENDERED_CAPTION_IMAGE_H"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AV_RENDERED_CAPTION_IMAGE_H",
      "kind": "symbol",
      "role": "symbol",
      "title": "AV_RENDERED_CAPTION_IMAGE_H",
      "type": "topic",
      "url": "/documentation/avfoundation/av_rendered_caption_image_h"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAILABLE_MAC_OS_X_VERSION_TBD_AND_LATER",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_AUDIO_PROCESSING_TAP_AVAILABLE",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPLOYING_TO_2024_RELEASES_AND_LATER",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_EXPORT",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AV_INIT_UNAVAILABLE",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVF_DEPRECATED_FOR_SWIFT_ONLY",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMETRICS_H",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AV_RENDERED_CAPTION_IMAGE_H"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER/title",
          "value": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVF_DEPLOYING_TO_2022_RELEASES_AND_LATER"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avf_deploying_to_2022_releases_and_later"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avf_deploying_to_2022_releases_and_later"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
