{
  "abstract": [
    {
      "text": "The uniform type identifiers for various file formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AVFileType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVFileType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVFileType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVFileType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats"
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType": {
      "abstract": [
        {
          "text": "The uniform type identifiers for various file formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileType"
        }
      ],
      "role": "symbol",
      "title": "AVFileType",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/AHAP": {
      "abstract": [
        {
          "text": "The UTI for the Apple Haptics Audio Pattern file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AHAP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/AHAP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAHAP"
        }
      ],
      "role": "symbol",
      "title": "AHAP",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/ahap"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/SCC": {
      "abstract": [
        {
          "text": "The UTI for the Scenarist closed-caption file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/SCC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeSCC"
        }
      ],
      "role": "symbol",
      "title": "SCC",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/scc"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/ac3": {
      "abstract": [
        {
          "text": "The UTI for the AC3 audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ac3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/ac3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAC3"
        }
      ],
      "role": "symbol",
      "title": "ac3",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/ac3"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aifc": {
      "abstract": [
        {
          "text": "The UTI for the AIFC audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aifc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aifc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAIFC"
        }
      ],
      "role": "symbol",
      "title": "aifc",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/aifc"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aiff": {
      "abstract": [
        {
          "text": "The UTI for the AIFF audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "aiff"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aiff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAIFF"
        }
      ],
      "role": "symbol",
      "title": "aiff",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/aiff"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/amr": {
      "abstract": [
        {
          "text": "The UTI for the adaptive multirate audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "amr"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/amr",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAMR"
        }
      ],
      "role": "symbol",
      "title": "amr",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/amr"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/appleiTT": {
      "abstract": [
        {
          "text": "The UTI for the Apple iTT caption file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleiTT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/appleiTT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAppleiTT"
        }
      ],
      "role": "symbol",
      "title": "appleiTT",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/appleitt"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/au": {
      "abstract": [
        {
          "text": "The UTI for the Sun/NeXT audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "au"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/au",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeSunAU"
        }
      ],
      "role": "symbol",
      "title": "au",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/au"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/avci": {
      "abstract": [
        {
          "text": "The UTI for the high-efficiency image file format that contains H.264 compressed images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "avci"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/avci",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAVCI"
        }
      ],
      "role": "symbol",
      "title": "avci",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/avci"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/caf": {
      "abstract": [
        {
          "text": "The UTI for the Core Audio Format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/caf",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeCoreAudioFormat"
        }
      ],
      "role": "symbol",
      "title": "caf",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/caf"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/dng": {
      "abstract": [
        {
          "text": "The UTI for the Adobe Digital Negative file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dng"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/dng",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeDNG"
        }
      ],
      "role": "symbol",
      "title": "dng",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/dng"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/eac3": {
      "abstract": [
        {
          "text": "The UTI for the enhanced AC3 audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "eac3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/eac3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeEnhancedAC3"
        }
      ],
      "role": "symbol",
      "title": "eac3",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/eac3"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heic": {
      "abstract": [
        {
          "text": "The UTI for the high-efficiency image file format that contains HEVC compressed images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeHEIC"
        }
      ],
      "role": "symbol",
      "title": "heic",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/heic"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heif": {
      "abstract": [
        {
          "text": "The UTI for the high-efficiency image file format that contains compressed images from any codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeHEIF"
        }
      ],
      "role": "symbol",
      "title": "heif",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/heif"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(_:)": {
      "abstract": [
        {
          "text": "Creates a file type with a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/init(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a file type from its raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/jpg": {
      "abstract": [
        {
          "text": "The UTI for the JPEG (JFIF) format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jpg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/jpg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeJPEG"
        }
      ],
      "role": "symbol",
      "title": "jpg",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/jpg"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4a": {
      "abstract": [
        {
          "text": "The UTI for the Apple m4a audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m4a"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4a",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAppleM4A"
        }
      ],
      "role": "symbol",
      "title": "m4a",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/m4a"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v": {
      "abstract": [
        {
          "text": "The UTI for the iTunes video file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m4v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAppleM4V"
        }
      ],
      "role": "symbol",
      "title": "m4v",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/m4v"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP": {
      "abstract": [
        {
          "text": "The UTI for the 3GPP file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mobile3GPP"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileType3GPP"
        }
      ],
      "role": "symbol",
      "title": "mobile3GPP",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mobile3gpp"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP2": {
      "abstract": [
        {
          "text": "The UTI for the 3GPP2 file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mobile3GPP2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileType3GPP2"
        }
      ],
      "role": "symbol",
      "title": "mobile3GPP2",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mobile3gpp2"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov": {
      "abstract": [
        {
          "text": "The UTI for the QuickTime movie file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mov"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeQuickTimeMovie"
        }
      ],
      "role": "symbol",
      "title": "mov",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mov"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp3": {
      "abstract": [
        {
          "text": "The UTI for the MPEG Audio Layer III file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mp3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeMPEGLayer3"
        }
      ],
      "role": "symbol",
      "title": "mp3",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mp3"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp4": {
      "abstract": [
        {
          "text": "The UTI for the MPEG-4 file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mp4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeMPEG4"
        }
      ],
      "role": "symbol",
      "title": "mp4",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mp4"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/tif": {
      "abstract": [
        {
          "text": "The UTI for the tagged image file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/tif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeTIFF"
        }
      ],
      "role": "symbol",
      "title": "tif",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/tif"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/wav": {
      "abstract": [
        {
          "text": "The UTI for the WAVE audio file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wav"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/wav",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeWAVE"
        }
      ],
      "role": "symbol",
      "title": "wav",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/wav"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileTypeProfile": {
      "abstract": [
        {
          "text": "File type profiles for streaming formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFileTypeProfile"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileTypeProfile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeProfile"
        }
      ],
      "role": "symbol",
      "title": "AVFileTypeProfile",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletypeprofile"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats": {
      "abstract": [
        {
          "text": "Convert an existing movie file to a different format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats",
      "kind": "article",
      "role": "article",
      "title": "Exporting video to alternative formats",
      "type": "topic",
      "url": "/documentation/avfoundation/exporting-video-to-alternative-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "File-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileTypeProfile"
      ],
      "title": "File types"
    }
  ],
  "topicSections": [
    {
      "anchor": "File-Types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/ac3",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aifc",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aiff",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/AHAP",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/amr",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/appleiTT",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/au",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/avci",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/caf",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/dng",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/eac3",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heic",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heif",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/jpg",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4a",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP2",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp3",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp4",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/SCC",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/tif",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/wav"
      ],
      "title": "File Types"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVFileType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "File-Types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/ac3",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aifc",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/aiff",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/AHAP",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/amr",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/appleiTT",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/au",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/avci",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/caf",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/dng",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/eac3",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heic",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/heif",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/jpg",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4a",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mobile3GPP2",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp3",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mp4",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/SCC",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/tif",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/wav"
              ],
              "title": "File Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "File-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileTypeProfile"
              ],
              "title": "File types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVFileType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mobile3GPP/title",
          "value": "AVFileType3GPP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mobile3GPP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType3GPP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1au/title",
          "value": "AVFileTypeSunAU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1au/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeSunAU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1aiff/title",
          "value": "AVFileTypeAIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1aiff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/title",
          "value": "AVFileType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mov/title",
          "value": "AVFileTypeQuickTimeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mov/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeQuickTimeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4v/title",
          "value": "AVFileTypeAppleM4V"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAppleM4V"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mp3/title",
          "value": "AVFileTypeMPEGLayer3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mp3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeMPEGLayer3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1amr/title",
          "value": "AVFileTypeAMR"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1amr/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAMR"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1SCC/title",
          "value": "AVFileTypeSCC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1SCC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeSCC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1tif/title",
          "value": "AVFileTypeTIFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1tif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeTIFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileTypeProfile/title",
          "value": "AVFileTypeProfile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileTypeProfile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileTypeProfile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeProfile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1heic/title",
          "value": "AVFileTypeHEIC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1heic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeHEIC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1wav/title",
          "value": "AVFileTypeWAVE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1wav/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeWAVE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1caf/title",
          "value": "AVFileTypeCoreAudioFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1caf/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeCoreAudioFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1dng/title",
          "value": "AVFileTypeDNG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1dng/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeDNG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1aifc/title",
          "value": "AVFileTypeAIFC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1aifc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAIFC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1avci/title",
          "value": "AVFileTypeAVCI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1avci/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAVCI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1AHAP/title",
          "value": "AVFileTypeAHAP"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1AHAP/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAHAP"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1ac3/title",
          "value": "AVFileTypeAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1ac3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1eac3/title",
          "value": "AVFileTypeEnhancedAC3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1eac3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeEnhancedAC3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mp4/title",
          "value": "AVFileTypeMPEG4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mp4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeMPEG4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mobile3GPP2/title",
          "value": "AVFileType3GPP2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mobile3GPP2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileType3GPP2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1jpg/title",
          "value": "AVFileTypeJPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1jpg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeJPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4a/title",
          "value": "AVFileTypeAppleM4A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4a/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAppleM4A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1appleiTT/title",
          "value": "AVFileTypeAppleiTT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1appleiTT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAppleiTT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1heif/title",
          "value": "AVFileTypeHEIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1heif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeHEIF"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avfiletype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avfiletype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
