{
  "abstract": [
    {
      "text": "A type for objects that publish metric events to the event stream.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AVMetricEventStreamPublisher",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVMetricEventStreamPublisher"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetricEventStreamPublisher"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AVMetricEventStreamPublisher"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information from different publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMergedMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmergedmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent": {
      "abstract": [
        {
          "text": "An object that represents a metric event when an error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricErrorEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricerrorevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent": {
      "abstract": [
        {
          "text": "A base class that represents a metric event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream": {
      "abstract": [
        {
          "text": "An object that allows clients to add publishers and then subscribe to specific metric event classes from those publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStream"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStream",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher": {
      "abstract": [
        {
          "text": "A type for objects that publish metric events to the event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEventStreamPublisher",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreampublisher"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/allMetrics()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allMetrics"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
          "text": "AVMetrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetricEvent",
          "text": "AVMetricEvent"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/allMetrics()",
      "kind": "symbol",
      "role": "symbol",
      "title": "allMetrics()",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreampublisher/allmetrics()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/metrics(forType:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "externalParam",
          "text": "forType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": ".Type) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation9AVMetricsV",
          "text": "AVMetrics"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "MetricEvent"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/metrics(forType:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "metrics(forType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreampublisher/metrics(fortype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber": {
      "abstract": [
        {
          "text": "A type for objects that receive metric events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamSubscriber"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStreamSubscriber",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreamsubscriber"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics": {
      "abstract": [
        {
          "text": "An object that provides metrics related to video playback quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVVideoPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoperformancemetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types": {
      "abstract": [],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metric event types",
      "type": "topic",
      "url": "/documentation/avfoundation/metric-event-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types"
      ],
      "title": "Metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-metrics",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/allMetrics()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher/metrics(forType:)"
      ],
      "title": "Getting the metrics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetricEventStreamPublisher"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types"
              ],
              "title": "Metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetricEventStreamPublisher"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/title",
          "value": "AVMetricErrorEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/title",
          "value": "AVVideoPerformanceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/title",
          "value": "AVMetricEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title",
          "value": "AVPlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/title",
          "value": "AVMetricEventStreamPublisher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetriceventstreampublisher"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetriceventstreampublisher"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
