{
  "abstract": [
    {
      "text": "Asynchronous properties for metadata items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/avmetadataitem-async-properties"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "AVMetadataItem"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty": {
      "abstract": [
        {
          "text": "An asynchronous property that constrains its type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPartialAsyncProperty"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPartialAsyncProperty"
        }
      ],
      "role": "symbol",
      "title": "AVPartialAsyncProperty",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dataValue": {
      "abstract": [
        {
          "text": "The value of the metadata item as a data value.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dataValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dataValue",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/datavalue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dateValue": {
      "abstract": [
        {
          "text": "The value of the metadata item as a date.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dateValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "dateValue",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/datevalue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/extraAttributes": {
      "abstract": [
        {
          "text": "A dictionary of additional attributes for the item.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraAttributes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataExtraAttributeKey",
          "text": "AVMetadataExtraAttributeKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/extraAttributes",
      "kind": "symbol",
      "role": "symbol",
      "title": "extraAttributes",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/extraattributes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/numberValue": {
      "abstract": [
        {
          "text": "The value of the metadata item as a number.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/numberValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberValue",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/numbervalue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/stringValue": {
      "abstract": [
        {
          "text": "The value of the metadata item as a string.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/stringValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "stringValue",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/stringvalue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/value": {
      "abstract": [
        {
          "text": "The value of the metadata item.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVMetadataItem",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        },
        {
          "kind": "text",
          "text": ")?>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/value",
      "kind": "symbol",
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/value"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avasset-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avasset-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avassettrack-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for asset tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avassettrack-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avcomposition-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for compositions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avcomposition-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVComposition",
      "type": "topic",
      "url": "/documentation/avfoundation/avcomposition-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedasset-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for fragmented assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedasset-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVFragmentedAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedasset-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedmovie-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for fragmented movies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedmovie-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVFragmentedMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovie-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avmovie-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for movies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avmovie-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablecomposition-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for mutable compositions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablecomposition-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVMutableComposition",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablecomposition-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablemovie-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for mutable movies.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablemovie-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVMutableMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablemovie-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-async-properties": {
      "abstract": [
        {
          "text": "Asynchronous properties for URL assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-async-properties",
      "kind": "article",
      "role": "collectionGroup",
      "title": "AVURLAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset-async-properties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/avasset-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avassettrack-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedasset-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avcomposition-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablecomposition-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avmovie-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablemovie-async-properties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedmovie-async-properties"
      ],
      "title": "Loading Properties"
    }
  ],
  "topicSections": [
    {
      "anchor": "Loading-Values",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/value",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/extraAttributes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/stringValue",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/numberValue",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dateValue",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/dataValue"
      ],
      "title": "Loading Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/avasset-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avassettrack-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedasset-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avcomposition-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablecomposition-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avmovie-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avmutablemovie-async-properties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avfragmentedmovie-async-properties"
              ],
              "title": "Loading Properties"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataitem-async-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataitem-async-properties"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
