{
  "abstract": [
    {
      "text": "An event that represents a media resource request.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMetricMediaResourceRequestEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVMetricMediaResourceRequestEvent"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetricMediaResourceRequestEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVMetricMediaResourceRequestEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming content key resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricContentKeyRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricContentKeyRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricContentKeyRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriccontentkeyrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent": {
      "abstract": [
        {
          "text": "A base class that represents a metric event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming media segment resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricHLSMediaSegmentRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricHLSMediaSegmentRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricHLSMediaSegmentRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrichlsmediasegmentrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming playlist resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricHLSPlaylistRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricHLSPlaylistRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricHLSPlaylistRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrichlsplaylistrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a media resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricMediaResourceRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricMediaResourceRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricMediaResourceRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/byteRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byteRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/byteRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "byteRange"
        }
      ],
      "role": "symbol",
      "title": "byteRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/byterange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/errorEvent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorEvent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetricErrorEvent",
          "text": "AVMetricErrorEvent"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/errorEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errorEvent"
        }
      ],
      "role": "symbol",
      "title": "errorEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/errorevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/networkTransactionMetrics": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkTransactionMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSURLSessionTaskMetrics",
          "text": "URLSessionTaskMetrics"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/networkTransactionMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkTransactionMetrics"
        }
      ],
      "role": "symbol",
      "title": "networkTransactionMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/networktransactionmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestEndTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestEndTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestEndTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestEndTime"
        }
      ],
      "role": "symbol",
      "title": "requestEndTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/requestendtime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestStartTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestStartTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestStartTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestStartTime"
        }
      ],
      "role": "symbol",
      "title": "requestStartTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/requeststarttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseEndTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responseEndTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseEndTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responseEndTime"
        }
      ],
      "role": "symbol",
      "title": "responseEndTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/responseendtime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseStartTime": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responseStartTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseStartTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responseStartTime"
        }
      ],
      "role": "symbol",
      "title": "responseStartTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/responsestarttime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/serverAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/serverAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverAddress"
        }
      ],
      "role": "symbol",
      "title": "serverAddress",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/serveraddress"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/url": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "url"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/url"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/wasReadFromCache": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wasReadFromCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/wasReadFromCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readFromCache"
        }
      ],
      "role": "symbol",
      "title": "wasReadFromCache",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent/wasreadfromcache"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent": {
      "abstract": [
        {
          "text": "An event that represents when the player completes a variant switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemVariantSwitchEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemvariantswitchevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent": {
      "abstract": [
        {
          "text": "An event that represents when the player attempts a variant switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchStartEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchStartEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemVariantSwitchStartEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemvariantswitchstartevent"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "HTTP-Live-Streaming",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent"
      ],
      "title": "HTTP Live Streaming"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-the-event",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/byteRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/errorEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/networkTransactionMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestEndTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestStartTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseEndTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseStartTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/serverAddress",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/url",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/wasReadFromCache"
      ],
      "title": "Inspecting the event"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetricMediaResourceRequestEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Inspecting-the-event",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/byteRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/errorEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/networkTransactionMetrics",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestEndTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/requestStartTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseEndTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/responseStartTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/serverAddress",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/url",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent/wasReadFromCache"
              ],
              "title": "Inspecting the event"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "HTTP-Live-Streaming",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent"
              ],
              "title": "HTTP Live Streaming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetricMediaResourceRequestEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVMetricEvent",
                    "text": "AVMetricEvent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/title",
          "value": "AVMetricPlayerItemVariantSwitchStartEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchStartEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchStartEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1responseStartTime/title",
          "value": "responseStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1responseStartTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responseStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/title",
          "value": "AVMetricMediaResourceRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/title",
          "value": "AVMetricHLSMediaSegmentRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSMediaSegmentRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSMediaSegmentRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/title",
          "value": "AVMetricHLSPlaylistRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSPlaylistRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSPlaylistRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/title",
          "value": "AVMetricPlayerItemVariantSwitchEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1wasReadFromCache/title",
          "value": "readFromCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1wasReadFromCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readFromCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1networkTransactionMetrics/title",
          "value": "networkTransactionMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1networkTransactionMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkTransactionMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1requestStartTime/title",
          "value": "requestStartTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1requestStartTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestStartTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1requestEndTime/title",
          "value": "requestEndTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1requestEndTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requestEndTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1url/title",
          "value": "url"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "url"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1serverAddress/title",
          "value": "serverAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1serverAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1responseEndTime/title",
          "value": "responseEndTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1responseEndTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responseEndTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/title",
          "value": "AVMetricContentKeyRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricContentKeyRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricContentKeyRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1errorEvent/title",
          "value": "errorEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1errorEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/title",
          "value": "AVMetricEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1byteRange/title",
          "value": "byteRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent~1byteRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "byteRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetricmediaresourcerequestevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetricmediaresourcerequestevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
