{
  "abstract": [
    {
      "text": "The abstract superclass for objects provided by a metadata capture output.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMetadataObject",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVMetadataObject"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetadataObject"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVMetadataObject"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "AVMetadataObject",
              "type": "codeVoice"
            },
            {
              "text": " class is an abstract class that defines the basic properties associated with a piece of metadata. These attributes reflect information either about the metadata itself or the media from which the metadata originated. Subclasses are responsible for providing appropriate values for each of the relevant properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You shouldn’t subclass ",
              "type": "text"
            },
            {
              "code": "AVMetadataObject",
              "type": "codeVoice"
            },
            {
              "text": " directly. Instead, you use one of the defined subclasses provided by the AVFoundation framework. Similarly, you don’t create instances of this class yourself but use an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to retrieve them from the captured data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput": {
      "abstract": [
        {
          "text": "A capture input for providing timed metadata to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMetadataInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemetadatainput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput": {
      "abstract": [
        {
          "text": "A capture output for processing timed metadata produced by a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureMetadataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureMetadataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturemetadataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataBodyObject": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface for a metadata body object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataBodyObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataBodyObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataBodyObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataBodyObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatabodyobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFaceObject": {
      "abstract": [
        {
          "text": "Face information detected by a metadata capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataFaceObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFaceObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataFaceObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataFaceObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatafaceobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataMachineReadableCodeObject": {
      "abstract": [
        {
          "text": "Barcode information detected by a metadata capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataMachineReadableCodeObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataMachineReadableCodeObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataMachineReadableCodeObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataMachineReadableCodeObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatamachinereadablecodeobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject": {
      "abstract": [
        {
          "text": "The abstract superclass for objects provided by a metadata capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType": {
      "abstract": [
        {
          "text": "Constants that identify metadata object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ObjectType"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataObject.ObjectType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/objecttype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/bounds": {
      "abstract": [
        {
          "text": "The bounding rectangle associated with the metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/bounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounds"
        }
      ],
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/bounds"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/duration": {
      "abstract": [
        {
          "text": "The duration of the media associated with this metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/duration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "duration"
        }
      ],
      "role": "symbol",
      "title": "duration",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/duration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/time": {
      "abstract": [
        {
          "text": "The media time value associated with the metadata object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "time"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/time",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "time"
        }
      ],
      "role": "symbol",
      "title": "time",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/time"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/type": {
      "abstract": [
        {
          "text": "The type of metadata that this object provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMetadataObject",
          "text": "AVMetadataObject"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMetadataObjectType",
          "text": "ObjectType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataobject/type"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataSalientObject": {
      "abstract": [
        {
          "text": "An object representing a single salient area in a picture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataSalientObject"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataSalientObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataSalientObject"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataSalientObject",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatasalientobject"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types": {
      "abstract": [
        {
          "text": "Inspect the supported metadata object types that the framework supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metadata Types",
      "type": "topic",
      "url": "/documentation/avfoundation/metadata-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataBodyObject",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFaceObject",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataMachineReadableCodeObject",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataSalientObject"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metadata-capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types"
      ],
      "title": "Metadata capture"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Type-of-Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/type",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType"
      ],
      "title": "Getting the Type of Metadata"
    },
    {
      "anchor": "Getting-the-Media-Related-Attributes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/time",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/duration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/bounds"
      ],
      "title": "Getting the Media-Related Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMetadataObject"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Type-of-Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/type",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/ObjectType"
              ],
              "title": "Getting the Type of Metadata"
            },
            {
              "anchor": "Getting-the-Media-Related-Attributes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/time",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/duration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataObject/bounds"
              ],
              "title": "Getting the Media-Related Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataBodyObject",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFaceObject",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataMachineReadableCodeObject",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataSalientObject"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metadata-capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataInput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMetadataOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/metadata-types"
              ],
              "title": "Metadata capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMetadataObject"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/title",
          "value": "AVMetadataObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFaceObject/title",
          "value": "AVMetadataFaceObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFaceObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataFaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFaceObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataFaceObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataBodyObject/title",
          "value": "AVMetadataBodyObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataBodyObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataBodyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataBodyObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataBodyObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataMachineReadableCodeObject/title",
          "value": "AVMetadataMachineReadableCodeObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataMachineReadableCodeObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataMachineReadableCodeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataMachineReadableCodeObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataMachineReadableCodeObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1time/title",
          "value": "time"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1time/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "time"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/title",
          "value": "AVMetadataObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1ObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/title",
          "value": "AVCaptureMetadataInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1duration/title",
          "value": "duration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1duration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "duration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/title",
          "value": "AVCaptureMetadataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMetadataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1bounds/title",
          "value": "bounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataObject~1bounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataSalientObject/title",
          "value": "AVMetadataSalientObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataSalientObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataSalientObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataSalientObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataSalientObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetadataobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmetadataobject"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
