{
  "abstract": [
    {
      "text": "An object that allows clients to add publishers and then subscribe to specific metric event classes from those publishers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVMetricEventStream",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVMetricEventStream"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMetricEventStream"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVMetricEventStream"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMetricEventStream"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Publishers are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " types that adopt ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The protocol allows clients to receive metric events with a subscriber delegate which adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent": {
      "abstract": [
        {
          "text": "An object that represents a metric event when an error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricErrorEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricerrorevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent": {
      "abstract": [
        {
          "text": "A base class that represents a metric event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream": {
      "abstract": [
        {
          "text": "An object that allows clients to add publishers and then subscribe to specific metric event classes from those publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStream"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStream",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/addPublisher:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "addPublisher:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/addPublisher:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPublisher:"
        }
      ],
      "role": "symbol",
      "title": "addPublisher:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/addpublisher:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/eventStream": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "eventStream"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/eventStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "eventStream"
        }
      ],
      "role": "symbol",
      "title": "eventStream",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/eventstream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/setSubscriber:queue:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setSubscriber:queue:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/setSubscriber:queue:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setSubscriber:queue:"
        }
      ],
      "role": "symbol",
      "title": "setSubscriber:queue:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/setsubscriber:queue:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToAllMetricEvents": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "subscribeToAllMetricEvents"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToAllMetricEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeToAllMetricEvents"
        }
      ],
      "role": "symbol",
      "title": "subscribeToAllMetricEvents",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/subscribetoallmetricevents"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvent:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "subscribeToMetricEvent:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvent:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeToMetricEvent:"
        }
      ],
      "role": "symbol",
      "title": "subscribeToMetricEvent:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/subscribetometricevent:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvents:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "subscribeToMetricEvents:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvents:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subscribeToMetricEvents:"
        }
      ],
      "role": "symbol",
      "title": "subscribeToMetricEvents:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream/subscribetometricevents:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher": {
      "abstract": [
        {
          "text": "A type for objects that publish metric events to the event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEventStreamPublisher",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreampublisher"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber": {
      "abstract": [
        {
          "text": "A type for objects that receive metric events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamSubscriber"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStreamSubscriber",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreamsubscriber"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics": {
      "abstract": [
        {
          "text": "An object that provides metrics related to video playback quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVVideoPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoperformancemetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types": {
      "abstract": [],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Metric event types",
      "type": "topic",
      "url": "/documentation/avfoundation/metric-event-types"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types"
      ],
      "title": "Metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-event-stream",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/eventStream"
      ],
      "title": "Getting the event stream"
    },
    {
      "anchor": "Adding-a-publisher",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/addPublisher:"
      ],
      "title": "Adding a publisher"
    },
    {
      "anchor": "Subscribing-to-events",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToAllMetricEvents",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvent:",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/subscribeToMetricEvents:"
      ],
      "title": "Subscribing to events"
    },
    {
      "anchor": "Setting-a-subscriber",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream/setSubscriber:queue:"
      ],
      "title": "Setting a subscriber"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/title",
          "value": "AVMetricErrorEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/title",
          "value": "AVMetricEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/title",
          "value": "AVMetricEventStreamPublisher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/title",
          "value": "AVVideoPerformanceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmetriceventstream"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
