{
  "abstract": [
    {
      "text": "A structure that defines media data characteristics.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AVMediaCharacteristic",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVMediaCharacteristic"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVMediaCharacteristic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVMediaCharacteristic"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristic"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "QuickTime Movie and MPEG-4 video files may contain tracks that provide tagged media characteristics to indicate a purpose, trait, or feature of the track’s media. For example, an audio track that mixes original program content with additional narrative descriptions of visual action may have the media characteristic ",
              "type": "text"
            },
            {
              "code": "public.accessibility.describes-video",
              "type": "codeVoice"
            },
            {
              "text": " to distinguish it from other audio tracks stored in the same file that don’t contain additional narrative.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You inspect the tagged media characteristics of a track as shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "NSArray *userDataItems = [myAVAssetTrack metadataForFormat:AVMetadataFormatQuickTimeUserData];",
            "NSArray *trackTaggedMediaCharacteristics = [AVMetadataItem metadataItemsFromArray: userDataItems",
            "        withKey: AVMetadataQuickTimeUserDataKeyTaggedCharacteristic",
            "        keySpace: AVMetadataKeySpaceQuickTimeUserData];",
            "for (AVMetadataItem *metadataItem in trackTaggedMediaCharacteristics) {",
            "     NSString *thisTrackMediaCharacteristic = [metadataItem stringValue];",
            "}"
          ],
          "syntax": "objc",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "You write tagged media characteristics to files of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " by using an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You indicate tagged characteristics for a track by setting metadata on its associated asset writer input as shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "AVMutableMetadataItem *myTaggedMediaCharacteristic = [[AVMutableMetadataItem alloc] init];",
            "[myTaggedMediaCharacteristic setKey:AVMetadataQuickTimeUserDataKeyTaggedCharacteristic];",
            "[myTaggedMediaCharacteristic setKeySpace:AVMetadataKeySpaceQuickTimeUserData];",
            "[myTaggedMediaCharacteristic setValue:aMeaningfulCharacteristicAsNSString];",
            "[myMutableArrayOfMetadata addObject:myTaggedMediaCharacteristic];",
            "[myAssetWriterInput setMetadata:myMutableArrayOfMetadata];"
          ],
          "syntax": "objc",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter": {
      "abstract": [
        {
          "text": "An object that writes media data to a container file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriter"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriter"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriter",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v": {
      "abstract": [
        {
          "text": "The UTI for the iTunes video file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "m4v"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/m4v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeAppleM4V"
        }
      ],
      "role": "symbol",
      "title": "m4v",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/m4v"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov": {
      "abstract": [
        {
          "text": "The UTI for the QuickTime movie file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mov"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFileType/mov",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFileTypeQuickTimeMovie"
        }
      ],
      "role": "symbol",
      "title": "mov",
      "type": "topic",
      "url": "/documentation/avfoundation/avfiletype/mov"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic": {
      "abstract": [
        {
          "text": "A structure that defines media data characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristic"
        }
      ],
      "role": "symbol",
      "title": "AVMediaCharacteristic",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes audible content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicAudible"
        }
      ],
      "role": "symbol",
      "title": "audible",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/audible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/carriesVideoStereoMetadata": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that the stereoscopic video track carries additional information related to the stereoscopic video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carriesVideoStereoMetadata"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/carriesVideoStereoMetadata",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicCarriesVideoStereoMetadata"
        }
      ],
      "role": "symbol",
      "title": "carriesVideoStereoMetadata",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/carriesvideostereometadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsAlphaChannel": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track contains an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsAlphaChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsAlphaChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicContainsAlphaChannel"
        }
      ],
      "role": "symbol",
      "title": "containsAlphaChannel",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/containsalphachannel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsHDRVideo": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track contains HDR video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsHDRVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsHDRVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicContainsHDRVideo"
        }
      ],
      "role": "symbol",
      "title": "containsHDRVideo",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/containshdrvideo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsOnlyForcedSubtitles": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option presents only forced subtitles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsOnlyForcedSubtitles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsOnlyForcedSubtitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicContainsOnlyForcedSubtitles"
        }
      ],
      "role": "symbol",
      "title": "containsOnlyForcedSubtitles",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/containsonlyforcedsubtitles"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsStereoMultiviewVideo": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track contains stereoscopic video captured in a multiview compression format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containsStereoMultiviewVideo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsStereoMultiviewVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicContainsStereoMultiviewVideo"
        }
      ],
      "role": "symbol",
      "title": "containsStereoMultiviewVideo",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/containsstereomultiviewvideo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesMusicAndSoundForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes legible content in the language of its specified locale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "describesMusicAndSoundForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesMusicAndSoundForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "describesMusicAndSoundForAccessibility",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/describesmusicandsoundforaccessibility"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesVideoForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates the media includes audible content that describes the visual portion of the presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "describesVideoForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesVideoForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicDescribesVideoForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "describesVideoForAccessibility",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/describesvideoforaccessibility"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/dubbedTranslation": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option contains audio language or dialect translation of the original content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dubbedTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/dubbedTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicDubbedTranslation"
        }
      ],
      "role": "symbol",
      "title": "dubbedTranslation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/dubbedtranslation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/easyToRead": {
      "abstract": [
        {
          "text": "A media characteristic that indicates a track or media selection option provides legible content that’s edited for easy reading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "easyToRead"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/easyToRead",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicEasyToRead"
        }
      ],
      "role": "symbol",
      "title": "easyToRead",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/easytoread"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/enhancesSpeechIntelligibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates a track or media selection option includes audio processed to enhance the intelligibility of speech.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enhancesSpeechIntelligibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/enhancesSpeechIntelligibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicEnhancesSpeechIntelligibility"
        }
      ],
      "role": "symbol",
      "title": "enhancesSpeechIntelligibility",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/enhancesspeechintelligibility"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/frameBased": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes frame-based content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frameBased"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/frameBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicFrameBased"
        }
      ],
      "role": "symbol",
      "title": "frameBased",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/framebased"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/indicatesHorizontalFieldOfView": {
      "abstract": [
        {
          "text": "A media characteristic that indicates the video track carries information related to the horizontal field of view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatesHorizontalFieldOfView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/indicatesHorizontalFieldOfView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicIndicatesHorizontalFieldOfView"
        }
      ],
      "role": "symbol",
      "title": "indicatesHorizontalFieldOfView",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/indicateshorizontalfieldofview"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(_:)": {
      "abstract": [
        {
          "text": "Creates a media characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/init(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a media characteristic with a string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isAuxiliaryContent": {
      "abstract": [
        {
          "text": "A media characteristic that indicates a track or media selection option includes content its author indicates is auxiliary to the asset’s presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAuxiliaryContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isAuxiliaryContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicIsAuxiliaryContent"
        }
      ],
      "role": "symbol",
      "title": "isAuxiliaryContent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/isauxiliarycontent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isMainProgramContent": {
      "abstract": [
        {
          "text": "A media characteristic that indicates a track or media selection option includes content its author indicates is essential to the asset’s presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isMainProgramContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isMainProgramContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicIsMainProgramContent"
        }
      ],
      "role": "symbol",
      "title": "isMainProgramContent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/ismainprogramcontent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isOriginalContent": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option contains original content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOriginalContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isOriginalContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicIsOriginalContent"
        }
      ],
      "role": "symbol",
      "title": "isOriginalContent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/isoriginalcontent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/languageTranslation": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option contains a language or dialect translation of the original content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "languageTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/languageTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicLanguageTranslation"
        }
      ],
      "role": "symbol",
      "title": "languageTranslation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/languagetranslation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes legible content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicLegible"
        }
      ],
      "role": "symbol",
      "title": "legible",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/legible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/tactileMinimal": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes haptic content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tactileMinimal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/tactileMinimal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicTactileMinimal"
        }
      ],
      "role": "symbol",
      "title": "tactileMinimal",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/tactileminimal"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/transcribesSpokenDialogForAccessibility": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a media selection option includes legible content that transcribes spoken dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transcribesSpokenDialogForAccessibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/transcribesSpokenDialogForAccessibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicTranscribesSpokenDialogForAccessibility"
        }
      ],
      "role": "symbol",
      "title": "transcribesSpokenDialogForAccessibility",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/transcribesspokendialogforaccessibility"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/usesWideGamutColorSpace": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track uses a wide-gamut color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesWideGamutColorSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/usesWideGamutColorSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicUsesWideGamutColorSpace"
        }
      ],
      "role": "symbol",
      "title": "usesWideGamutColorSpace",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/useswidegamutcolorspace"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes visual content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicVisual"
        }
      ],
      "role": "symbol",
      "title": "visual",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/visual"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/voiceOverTranslation": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option contains a language translation and verbal interpretation of spoken dialog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOverTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/voiceOverTranslation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicVoiceOverTranslation"
        }
      ],
      "role": "symbol",
      "title": "voiceOverTranslation",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/voiceovertranslation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType": {
      "abstract": [
        {
          "text": "An identifier for various media types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaType"
        }
      ],
      "role": "symbol",
      "title": "AVMediaType",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediatype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType"
      ],
      "title": "Media types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Visual",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsAlphaChannel",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsHDRVideo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/frameBased",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/usesWideGamutColorSpace",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsStereoMultiviewVideo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/carriesVideoStereoMetadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/indicatesHorizontalFieldOfView"
      ],
      "title": "Visual"
    },
    {
      "anchor": "Audible",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/dubbedTranslation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/voiceOverTranslation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/enhancesSpeechIntelligibility",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesMusicAndSoundForAccessibility",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/tactileMinimal"
      ],
      "title": "Audible"
    },
    {
      "anchor": "Legible",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/easyToRead",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesVideoForAccessibility",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsOnlyForcedSubtitles",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/languageTranslation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/transcribesSpokenDialogForAccessibility"
      ],
      "title": "Legible"
    },
    {
      "anchor": "Content",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isOriginalContent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isMainProgramContent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isAuxiliaryContent"
      ],
      "title": "Content"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMediaCharacteristic"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Visual",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsAlphaChannel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsHDRVideo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/frameBased",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/usesWideGamutColorSpace",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsStereoMultiviewVideo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/carriesVideoStereoMetadata",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/indicatesHorizontalFieldOfView"
              ],
              "title": "Visual"
            },
            {
              "anchor": "Audible",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/dubbedTranslation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/voiceOverTranslation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/enhancesSpeechIntelligibility",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesMusicAndSoundForAccessibility",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/tactileMinimal"
              ],
              "title": "Audible"
            },
            {
              "anchor": "Legible",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/easyToRead",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/describesVideoForAccessibility",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/containsOnlyForcedSubtitles",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/languageTranslation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/transcribesSpokenDialogForAccessibility"
              ],
              "title": "Legible"
            },
            {
              "anchor": "Content",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isOriginalContent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isMainProgramContent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/isAuxiliaryContent"
              ],
              "title": "Content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaType"
              ],
              "title": "Media types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMediaCharacteristic"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1voiceOverTranslation/title",
          "value": "AVMediaCharacteristicVoiceOverTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1voiceOverTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicVoiceOverTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsAlphaChannel/title",
          "value": "AVMediaCharacteristicContainsAlphaChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsAlphaChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicContainsAlphaChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1describesMusicAndSoundForAccessibility/title",
          "value": "AVMediaCharacteristicDescribesMusicAndSoundForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1describesMusicAndSoundForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicDescribesMusicAndSoundForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1describesVideoForAccessibility/title",
          "value": "AVMediaCharacteristicDescribesVideoForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1describesVideoForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicDescribesVideoForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/title",
          "value": "AVMediaType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic/title",
          "value": "AVMediaCharacteristic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1legible/title",
          "value": "AVMediaCharacteristicLegible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1legible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicLegible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsStereoMultiviewVideo/title",
          "value": "AVMediaCharacteristicContainsStereoMultiviewVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsStereoMultiviewVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicContainsStereoMultiviewVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsHDRVideo/title",
          "value": "AVMediaCharacteristicContainsHDRVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsHDRVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicContainsHDRVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1transcribesSpokenDialogForAccessibility/title",
          "value": "AVMediaCharacteristicTranscribesSpokenDialogForAccessibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1transcribesSpokenDialogForAccessibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicTranscribesSpokenDialogForAccessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1dubbedTranslation/title",
          "value": "AVMediaCharacteristicDubbedTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1dubbedTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicDubbedTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsOnlyForcedSubtitles/title",
          "value": "AVMediaCharacteristicContainsOnlyForcedSubtitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1containsOnlyForcedSubtitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicContainsOnlyForcedSubtitles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1tactileMinimal/title",
          "value": "AVMediaCharacteristicTactileMinimal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1tactileMinimal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicTactileMinimal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isAuxiliaryContent/title",
          "value": "AVMediaCharacteristicIsAuxiliaryContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isAuxiliaryContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicIsAuxiliaryContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1usesWideGamutColorSpace/title",
          "value": "AVMediaCharacteristicUsesWideGamutColorSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1usesWideGamutColorSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicUsesWideGamutColorSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1carriesVideoStereoMetadata/title",
          "value": "AVMediaCharacteristicCarriesVideoStereoMetadata"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1carriesVideoStereoMetadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicCarriesVideoStereoMetadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/title",
          "value": "AVAssetWriter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1indicatesHorizontalFieldOfView/title",
          "value": "AVMediaCharacteristicIndicatesHorizontalFieldOfView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1indicatesHorizontalFieldOfView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicIndicatesHorizontalFieldOfView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mov/title",
          "value": "AVFileTypeQuickTimeMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1mov/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeQuickTimeMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1languageTranslation/title",
          "value": "AVMediaCharacteristicLanguageTranslation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1languageTranslation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicLanguageTranslation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isMainProgramContent/title",
          "value": "AVMediaCharacteristicIsMainProgramContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isMainProgramContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicIsMainProgramContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1frameBased/title",
          "value": "AVMediaCharacteristicFrameBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1frameBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicFrameBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1enhancesSpeechIntelligibility/title",
          "value": "AVMediaCharacteristicEnhancesSpeechIntelligibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1enhancesSpeechIntelligibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicEnhancesSpeechIntelligibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isOriginalContent/title",
          "value": "AVMediaCharacteristicIsOriginalContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1isOriginalContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicIsOriginalContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4v/title",
          "value": "AVFileTypeAppleM4V"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFileType~1m4v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFileTypeAppleM4V"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1easyToRead/title",
          "value": "AVMediaCharacteristicEasyToRead"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1easyToRead/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicEasyToRead"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1audible/title",
          "value": "AVMediaCharacteristicAudible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1audible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicAudible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1visual/title",
          "value": "AVMediaCharacteristicVisual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1visual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicVisual"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avmediacharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avmediacharacteristic"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
