{
  "abstract": [
    {
      "text": "A structure that defines a pixel aspect ratio for a rendering context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@AVPixelAspectRatio",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPixelAspectRatio"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPixelAspectRatio"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVPixelAspectRatio"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPixelAspectRatio"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVEdgeWidths": {
      "abstract": [
        {
          "text": "A structure that defines edge processing region widths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEdgeWidths"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVEdgeWidths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVEdgeWidths"
        }
      ],
      "role": "symbol",
      "title": "AVEdgeWidths",
      "type": "topic",
      "url": "/documentation/avfoundation/avedgewidths"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio": {
      "abstract": [
        {
          "text": "A structure that defines a pixel aspect ratio for a rendering context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPixelAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPixelAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "AVPixelAspectRatio",
      "type": "topic",
      "url": "/documentation/avfoundation/avpixelaspectratio"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/horizontalSpacing": {
      "abstract": [
        {
          "text": "The pixel aspect ratio’s horizontal spacing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontalSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/horizontalSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "horizontalSpacing"
        }
      ],
      "role": "symbol",
      "title": "horizontalSpacing",
      "type": "topic",
      "url": "/documentation/avfoundation/avpixelaspectratio/horizontalspacing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init()": {
      "abstract": [
        {
          "text": "Creates an empty pixel aspect ratio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/avfoundation/avpixelaspectratio/init()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init(horizontalSpacing:verticalSpacing:)": {
      "abstract": [
        {
          "text": "Creates a pixel aspect ratio with horizontal and vertical spacing values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "horizontalSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "verticalSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init(horizontalSpacing:verticalSpacing:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(horizontalSpacing:verticalSpacing:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avpixelaspectratio/init(horizontalspacing:verticalspacing:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/verticalSpacing": {
      "abstract": [
        {
          "text": "The pixel aspect ratio’s vertical spacing value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/verticalSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "verticalSpacing"
        }
      ],
      "role": "symbol",
      "title": "verticalSpacing",
      "type": "topic",
      "url": "/documentation/avfoundation/avpixelaspectratio/verticalspacing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/edgeWidths": {
      "abstract": [
        {
          "text": "The width of the edge processing region on the left, top, right, and bottom edges, in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "edgeWidths"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVEdgeWidths",
          "text": "AVEdgeWidths"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/edgeWidths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "edgeWidths"
        }
      ],
      "role": "symbol",
      "title": "edgeWidths",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocompositionrendercontext/edgewidths"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/pixelAspectRatio": {
      "abstract": [
        {
          "text": "The pixel aspect ratio for rendered frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelAspectRatio"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVPixelAspectRatio",
          "text": "AVPixelAspectRatio"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/pixelAspectRatio",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelAspectRatio"
        }
      ],
      "role": "symbol",
      "title": "pixelAspectRatio",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocompositionrendercontext/pixelaspectratio"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Pixel-and-Edge-Width-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/edgeWidths",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVEdgeWidths",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/pixelAspectRatio"
      ],
      "title": "Getting Pixel and Edge Width Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Spacing",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/horizontalSpacing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/verticalSpacing"
      ],
      "title": "Spacing"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/init(horizontalSpacing:verticalSpacing:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Spacing",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/horizontalSpacing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPixelAspectRatio/verticalSpacing"
              ],
              "title": "Spacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Pixel-and-Edge-Width-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/edgeWidths",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVEdgeWidths",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCompositionRenderContext/pixelAspectRatio"
              ],
              "title": "Getting Pixel and Edge Width Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPixelAspectRatio"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio/title",
          "value": "AVPixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPixelAspectRatio"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio~1verticalSpacing/title",
          "value": "verticalSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio~1verticalSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "verticalSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio~1horizontalSpacing/title",
          "value": "horizontalSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPixelAspectRatio~1horizontalSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "horizontalSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1edgeWidths/title",
          "value": "edgeWidths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1edgeWidths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "edgeWidths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVEdgeWidths/title",
          "value": "AVEdgeWidths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVEdgeWidths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEdgeWidths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVEdgeWidths/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVEdgeWidths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1pixelAspectRatio/title",
          "value": "pixelAspectRatio"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCompositionRenderContext~1pixelAspectRatio/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelAspectRatio"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avpixelaspectratio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avpixelaspectratio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
