{"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avplayeritemerrorlogevent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avplayeritemerrorlogevent"]}],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"A single item in a player item’s error log."}],"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/date","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/uri","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/serverAddress","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/playbackSessionID","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorStatusCode","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorDomain","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorComment","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/allHTTPResponseHeaderFields"],"title":"Getting Information About the Event","anchor":"Getting-Information-About-the-Event"}],"metadata":{"platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"4.3","unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"4.3","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false},{"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.7","unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"9.0","unavailable":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"1.0"}],"modules":[{"name":"AVFoundation"}],"navigatorTitle":[{"text":"AVPlayerItemErrorLogEvent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItemErrorLogEvent","kind":"identifier"}],"symbolKind":"class","role":"symbol","title":"AVPlayerItemErrorLogEvent","externalID":"c:objc(cs)AVPlayerItemErrorLogEvent","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog"],"title":"Accessing Logging Information","anchor":"Accessing-Logging-Information","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This object provides properties for accessing the data fields of each log event. Each event is a single entry in an ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem","type":"reference"},{"text":" object’s error log.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"These properties aren’t observable. For more information about key-value observing, see "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift"},{"type":"text","text":"."}]}]}],"sections":[],"references":{"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/date":{"role":"symbol","navigatorTitle":[{"text":"date","kind":"identifier"}],"title":"date","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/date","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/date","type":"topic","abstract":[{"type":"text","text":"The date and time when the error occurred."}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"type":"topic","title":"Sendable","url":"/documentation/Swift/Sendable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()":{"url":"/documentation/avfoundation/avplayeritem/accesslog()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessLog","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AVPlayerItemAccessLog","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"kind":"text","text":"?"}],"title":"accessLog()","abstract":[{"text":"Returns an object that represents a snapshot of the network access log.","type":"text"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","role":"symbol","navigatorTitle":[{"text":"errorLog","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns an object that represents a snapshot of the error log."}],"url":"/documentation/avfoundation/avplayeritem/errorlog()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorLog","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItemErrorLog","text":"AVPlayerItemErrorLog","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorLog()","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog":{"url":"/documentation/avfoundation/avplayeritemerrorlog","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"title":"AVPlayerItemErrorLog","abstract":[{"type":"text","text":"The error log associated with a player item."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"url":"/documentation/objectivec/nsobject","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/uri":{"role":"symbol","navigatorTitle":[{"text":"URI","kind":"identifier"}],"title":"uri","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/uri","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uri","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/uri","type":"topic","abstract":[{"type":"text","text":"The URI of the playback item that had an error."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem":{"url":"/documentation/avfoundation/avplayeritem","title":"AVPlayerItem","abstract":[{"text":"An object that models the timing and presentation state of an asset during playback.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVPlayerItem","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItem","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog":{"url":"/documentation/avfoundation/avplayeritemaccesslog","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"title":"AVPlayerItemAccessLog","abstract":[{"type":"text","text":"An object used to retrieve the access log associated with a player item."}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent":{"abstract":[{"type":"text","text":"A single entry in a player item’s access log."}],"title":"AVPlayerItemAccessLogEvent","kind":"symbol","url":"/documentation/avfoundation/avplayeritemaccesslogevent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLogEvent"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemAccessLogEvent"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorComment":{"role":"symbol","navigatorTitle":[{"text":"errorComment","kind":"identifier"}],"title":"errorComment","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorComment","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorComment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/errorcomment","type":"topic","abstract":[{"type":"text","text":"A description of the error encountered."}]},"doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift":{"identifier":"doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift","kind":"article","abstract":[{"type":"text","text":"Notify objects about changes to the properties of other objects."}],"type":"topic","role":"article","url":"/documentation/Swift/using-key-value-observing-in-swift","title":"Using Key-Value Observing in Swift"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent":{"url":"/documentation/avfoundation/avplayeritemerrorlogevent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"title":"AVPlayerItemErrorLogEvent","abstract":[{"type":"text","text":"A single item in a player item’s error log."}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/serverAddress":{"role":"symbol","navigatorTitle":[{"text":"serverAddress","kind":"identifier"}],"title":"serverAddress","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/serverAddress","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/serveraddress","type":"topic","abstract":[{"type":"text","text":"The IP address of the server that was the source of the error."}]},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorStatusCode":{"role":"symbol","navigatorTitle":[{"text":"errorStatusCode","kind":"identifier"}],"title":"errorStatusCode","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorStatusCode","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorStatusCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/errorstatuscode","type":"topic","abstract":[{"type":"text","text":"A unique error code identifier."}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"title":"NSCopying","type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"url":"/documentation/foundation/nscopying","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/allHTTPResponseHeaderFields":{"role":"symbol","navigatorTitle":[{"text":"allHTTPResponseHeaderFields","kind":"identifier"}],"title":"allHTTPResponseHeaderFields","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/allHTTPResponseHeaderFields","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allHTTPResponseHeaderFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/allhttpresponseheaderfields","type":"topic","abstract":[{"type":"text","text":"The HTTP header fields the server returns."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/playbackSessionID":{"role":"symbol","navigatorTitle":[{"text":"playbackSessionID","kind":"identifier"}],"title":"playbackSessionID","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/playbackSessionID","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackSessionID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/playbacksessionid","type":"topic","abstract":[{"type":"text","text":"A GUID that identifies the playback session that had an error."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorDomain":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"errorDomain"}],"title":"errorDomain","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorDomain","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avplayeritemerrorlogevent/errordomain","type":"topic","abstract":[{"type":"text","text":"The domain of the error."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"4.3","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"4.3","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.7"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Class","op":"replace","path":"/metadata/roleHeading"},{"value":"AVPlayerItemErrorLogEvent","op":"replace","path":"/metadata/title"},{"value":"class","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"op":"replace","path":"/hierarchy"},{"value":[{"anchor":"Getting-Information-About-the-Event","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/date","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/uri","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/serverAddress","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/playbackSessionID","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorStatusCode","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorDomain","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/errorComment","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent/allHTTPResponseHeaderFields"],"title":"Getting Information About the Event"}],"op":"replace","path":"/topicSections"},{"value":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace","path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog"],"anchor":"Accessing-Logging-Information","title":"Accessing Logging Information"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItemErrorLogEvent","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1date/title","value":"date","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1date/fragments","value":[{"text":"date","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/title","value":"accessLog","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/fragments","value":[{"text":"- ","kind":"text"},{"text":"accessLog","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/title","value":"errorLog","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorLog"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/title","value":"AVPlayerItemErrorLog","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/fragments","value":[{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/navigatorTitle","value":[{"text":"AVPlayerItemErrorLog","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"URI","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1uri/title"},{"op":"replace","value":[{"text":"URI","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1uri/fragments"},{"op":"replace","value":"AVPlayerItem","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title"},{"op":"replace","value":[{"text":"AVPlayerItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments"},{"op":"replace","value":[{"text":"AVPlayerItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle"},{"op":"replace","value":"AVPlayerItemAccessLog","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/title"},{"op":"replace","value":[{"text":"AVPlayerItemAccessLog","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/navigatorTitle"},{"op":"replace","value":"AVPlayerItemAccessLogEvent","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/title"},{"op":"replace","value":[{"text":"AVPlayerItemAccessLogEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/fragments"},{"op":"replace","value":[{"text":"AVPlayerItemAccessLogEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/navigatorTitle"},{"op":"replace","value":"errorComment","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorComment/title"},{"op":"replace","value":[{"kind":"identifier","text":"errorComment"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorComment/fragments"},{"op":"replace","value":"AVPlayerItemErrorLogEvent","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/fragments"},{"op":"replace","value":[{"text":"AVPlayerItemErrorLogEvent","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/navigatorTitle"},{"op":"replace","value":"serverAddress","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1serverAddress/title"},{"op":"replace","value":[{"kind":"identifier","text":"serverAddress"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1serverAddress/fragments"},{"op":"replace","value":"errorStatusCode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorStatusCode/title"},{"op":"replace","value":[{"kind":"identifier","text":"errorStatusCode"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorStatusCode/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"allHTTPResponseHeaderFields","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1allHTTPResponseHeaderFields/title"},{"op":"replace","value":[{"kind":"identifier","text":"allHTTPResponseHeaderFields"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1allHTTPResponseHeaderFields/fragments"},{"op":"replace","value":"playbackSessionID","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1playbackSessionID/title"},{"op":"replace","value":[{"text":"playbackSessionID","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1playbackSessionID/fragments"},{"op":"replace","value":"errorDomain","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorDomain/title"},{"op":"replace","value":[{"kind":"identifier","text":"errorDomain"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent~1errorDomain/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}