{
  "abstract": [
    {
      "text": "A single entry in a player item’s access log.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPlayerItemAccessLogEvent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPlayerItemAccessLogEvent"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPlayerItemAccessLogEvent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVPlayerItemAccessLogEvent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This object provides named properties for accessing the data fields of each log event. Each event is a single entry in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s access log.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These properties aren’t observable. For more information about key-value observing, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()": {
      "abstract": [
        {
          "text": "Returns an object that represents a snapshot of the network access log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessLog"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerItemAccessLog",
          "text": "AVPlayerItemAccessLog"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessLog"
        }
      ],
      "role": "symbol",
      "title": "accessLog()",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/accesslog()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()": {
      "abstract": [
        {
          "text": "Returns an object that represents a snapshot of the error log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorLog"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVPlayerItemErrorLog",
          "text": "AVPlayerItemErrorLog"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errorLog"
        }
      ],
      "role": "symbol",
      "title": "errorLog()",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/errorlog()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog": {
      "abstract": [
        {
          "text": "An object used to retrieve the access log associated with a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLog"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLog"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemAccessLog",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslog"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent": {
      "abstract": [
        {
          "text": "A single entry in a player item’s access log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLogEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemAccessLogEvent"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemAccessLogEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate": {
      "abstract": [
        {
          "text": "The audio track’s average bit rate, in bits per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "averageAudioBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averageAudioBitrate"
        }
      ],
      "role": "symbol",
      "title": "averageAudioBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/averageaudiobitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate": {
      "abstract": [
        {
          "text": "The video track’s average bit rate, in bits per second.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "averageVideoBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "averageVideoBitrate"
        }
      ],
      "role": "symbol",
      "title": "averageVideoBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/averagevideobitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/downloadOverdue": {
      "abstract": [
        {
          "text": "The total number of times that downloading the segments took too long.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downloadOverdue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/downloadOverdue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "downloadOverdue"
        }
      ],
      "role": "symbol",
      "title": "downloadOverdue",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/downloadoverdue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/durationWatched": {
      "abstract": [
        {
          "text": "The accumulated duration, in seconds, of the media played.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "durationWatched"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/durationWatched",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "durationWatched"
        }
      ],
      "role": "symbol",
      "title": "durationWatched",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/durationwatched"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate": {
      "abstract": [
        {
          "text": "The average throughput, in bits per second, required to play the stream, as advertised by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedAverageBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedAverageBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedAverageBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/indicatedaveragebitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate": {
      "abstract": [
        {
          "text": "The throughput, in bits per second, required to play the stream, as advertised by the server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indicatedBitrate"
        }
      ],
      "role": "symbol",
      "title": "indicatedBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/indicatedbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/mediaRequestsWWAN": {
      "abstract": [
        {
          "text": "The number of network read requests over a WWAN.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaRequestsWWAN"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/mediaRequestsWWAN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaRequestsWWAN"
        }
      ],
      "role": "symbol",
      "title": "mediaRequestsWWAN",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/mediarequestswwan"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfBytesTransferred": {
      "abstract": [
        {
          "text": "The accumulated number of bytes transferred by the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfBytesTransferred",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfBytesTransferred"
        }
      ],
      "role": "symbol",
      "title": "numberOfBytesTransferred",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofbytestransferred"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfDroppedVideoFrames": {
      "abstract": [
        {
          "text": "The total number of dropped video frames",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfDroppedVideoFrames",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfDroppedVideoFrames"
        }
      ],
      "role": "symbol",
      "title": "numberOfDroppedVideoFrames",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofdroppedvideoframes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfMediaRequests": {
      "abstract": [
        {
          "text": "The number of media read requests from the server to this client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfMediaRequests"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfMediaRequests",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfMediaRequests"
        }
      ],
      "role": "symbol",
      "title": "numberOfMediaRequests",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofmediarequests"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfSegmentsDownloaded": {
      "abstract": [
        {
          "text": "A count of the media segments downloaded from the server to this client.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfSegmentsDownloaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfSegmentsDownloaded"
        }
      ],
      "role": "symbol",
      "title": "numberOfSegmentsDownloaded",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofsegmentsdownloaded"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfServerAddressChanges": {
      "abstract": [
        {
          "text": "A count of changes to the server address over the last uninterrupted period of playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfServerAddressChanges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfServerAddressChanges"
        }
      ],
      "role": "symbol",
      "title": "numberOfServerAddressChanges",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofserveraddresschanges"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfStalls": {
      "abstract": [
        {
          "text": "The total number of playback stalls encountered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfStalls",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfStalls"
        }
      ],
      "role": "symbol",
      "title": "numberOfStalls",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/numberofstalls"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate": {
      "abstract": [
        {
          "text": "The empirical throughput, in bits per second, across all media downloaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation": {
      "abstract": [
        {
          "text": "The standard deviation of the observed segment download bit rates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedBitrateStandardDeviation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedBitrateStandardDeviation"
        }
      ],
      "role": "symbol",
      "title": "observedBitrateStandardDeviation",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedbitratestandarddeviation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate": {
      "abstract": [
        {
          "text": "The maximum observed segment download bit rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedMaxBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedMaxBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedMaxBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedmaxbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate": {
      "abstract": [
        {
          "text": "The minimum observed segment download bit rate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "observedMinBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "observedMinBitrate"
        }
      ],
      "role": "symbol",
      "title": "observedMinBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/observedminbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackSessionID": {
      "abstract": [
        {
          "text": "A GUID that identifies the playback session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackSessionID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackSessionID"
        }
      ],
      "role": "symbol",
      "title": "playbackSessionID",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/playbacksessionid"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartDate": {
      "abstract": [
        {
          "text": "The date and time at which playback began for this event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartDate"
        }
      ],
      "role": "symbol",
      "title": "playbackStartDate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/playbackstartdate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartOffset": {
      "abstract": [
        {
          "text": "The offset, in seconds, in the playlist where the last uninterrupted period of playback began.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackStartOffset"
        }
      ],
      "role": "symbol",
      "title": "playbackStartOffset",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/playbackstartoffset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackType": {
      "abstract": [
        {
          "text": "The playback type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playbackType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "playbackType"
        }
      ],
      "role": "symbol",
      "title": "playbackType",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/playbacktype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/segmentsDownloadedDuration": {
      "abstract": [
        {
          "text": "The accumulated duration, in seconds, of the media segments downloaded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/segmentsDownloadedDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segmentsDownloadedDuration"
        }
      ],
      "role": "symbol",
      "title": "segmentsDownloadedDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/segmentsdownloadedduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/serverAddress": {
      "abstract": [
        {
          "text": "The IP address of the server that was the source of the last delivered media segment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serverAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/serverAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serverAddress"
        }
      ],
      "role": "symbol",
      "title": "serverAddress",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/serveraddress"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/startupTime": {
      "abstract": [
        {
          "text": "The accumulated duration, in seconds, until the player item is ready to play.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startupTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/startupTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startupTime"
        }
      ],
      "role": "symbol",
      "title": "startupTime",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/startuptime"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate": {
      "abstract": [
        {
          "text": "The bandwidth value that causes a switch, up or down, in the item’s quality being played.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchBitrate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "switchBitrate"
        }
      ],
      "role": "symbol",
      "title": "switchBitrate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/switchbitrate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/transferDuration": {
      "abstract": [
        {
          "text": "The accumulated duration, in seconds, of active network transfer of bytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/transferDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transferDuration"
        }
      ],
      "role": "symbol",
      "title": "transferDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/transferduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/uri": {
      "abstract": [
        {
          "text": "The URI of the playback item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uri"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/uri",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URI"
        }
      ],
      "role": "symbol",
      "title": "uri",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemaccesslogevent/uri"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog": {
      "abstract": [
        {
          "text": "The error log associated with a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemErrorLog"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemErrorLog"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemErrorLog",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemerrorlog"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent": {
      "abstract": [
        {
          "text": "A single item in a player item’s error log.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemErrorLogEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemErrorLogEvent"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemErrorLogEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemerrorlogevent"
    },
    "doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift": {
      "abstract": [
        {
          "text": "Notify objects about changes to the properties of other objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/using-key-value-observing-in-swift",
      "kind": "article",
      "role": "article",
      "title": "Using Key-Value Observing in Swift",
      "type": "topic",
      "url": "/documentation/Swift/using-key-value-observing-in-swift"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Logging-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent"
      ],
      "title": "Accessing Logging Information"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-Server-Related-Log-Events",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/uri",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/serverAddress",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfServerAddressChanges",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/mediaRequestsWWAN",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/transferDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfBytesTransferred",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfMediaRequests"
      ],
      "title": "Getting Server-Related Log Events"
    },
    {
      "anchor": "Getting-Playback-Related-Log-Events",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartDate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackSessionID",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartOffset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/startupTime",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/durationWatched",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfDroppedVideoFrames",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfStalls",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfSegmentsDownloaded",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/segmentsDownloadedDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/downloadOverdue"
      ],
      "title": "Getting Playback-Related Log Events"
    },
    {
      "abstract": [
        {
          "text": "The observed properties measure actual network download performance and indicated properties measure the bit rate of the media.",
          "type": "text"
        }
      ],
      "anchor": "Getting-Bit-Rate-Log-Events",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate"
      ],
      "title": "Getting Bit Rate Log Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPlayerItemAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Server-Related-Log-Events",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/uri",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/serverAddress",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfServerAddressChanges",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/mediaRequestsWWAN",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/transferDuration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfBytesTransferred",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfMediaRequests"
              ],
              "title": "Getting Server-Related Log Events"
            },
            {
              "anchor": "Getting-Playback-Related-Log-Events",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartDate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackSessionID",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackStartOffset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/playbackType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/startupTime",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/durationWatched",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfDroppedVideoFrames",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfStalls",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/numberOfSegmentsDownloaded",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/segmentsDownloadedDuration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/downloadOverdue"
              ],
              "title": "Getting Playback-Related Log Events"
            },
            {
              "abstract": [
                {
                  "text": "The observed properties measure actual network download performance and indicated properties measure the bit rate of the media.",
                  "type": "text"
                }
              ],
              "anchor": "Getting-Bit-Rate-Log-Events",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrateStandardDeviation",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMaxBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedMinBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/switchBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/observedBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageAudioBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/averageVideoBitrate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent/indicatedAverageBitrate"
              ],
              "title": "Getting Bit Rate Log Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Logging-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent"
              ],
              "title": "Accessing Logging Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPlayerItemAccessLogEvent"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfStalls/title",
          "value": "numberOfStalls"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfStalls/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfStalls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfBytesTransferred/title",
          "value": "numberOfBytesTransferred"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfBytesTransferred/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfBytesTransferred"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1startupTime/title",
          "value": "startupTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1startupTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startupTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1segmentsDownloadedDuration/title",
          "value": "segmentsDownloadedDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1segmentsDownloadedDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "segmentsDownloadedDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/title",
          "value": "AVPlayerItemAccessLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackStartDate/title",
          "value": "playbackStartDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackStartDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfDroppedVideoFrames/title",
          "value": "numberOfDroppedVideoFrames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfDroppedVideoFrames/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfDroppedVideoFrames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageVideoBitrate/title",
          "value": "averageVideoBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageVideoBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "averageVideoBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfMediaRequests/title",
          "value": "numberOfMediaRequests"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfMediaRequests/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfMediaRequests"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrateStandardDeviation/title",
          "value": "observedBitrateStandardDeviation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrateStandardDeviation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrateStandardDeviation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfSegmentsDownloaded/title",
          "value": "numberOfSegmentsDownloaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfSegmentsDownloaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfSegmentsDownloaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackSessionID/title",
          "value": "playbackSessionID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackSessionID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackSessionID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackStartOffset/title",
          "value": "playbackStartOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackStartOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackStartOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/title",
          "value": "accessLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/title",
          "value": "AVPlayerItemAccessLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemAccessLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1switchBitrate/title",
          "value": "switchBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1switchBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "switchBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrate/title",
          "value": "observedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1uri/title",
          "value": "URI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1uri/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1downloadOverdue/title",
          "value": "downloadOverdue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1downloadOverdue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "downloadOverdue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMinBitrate/title",
          "value": "observedMinBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMinBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedMinBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/title",
          "value": "AVPlayerItemErrorLogEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemErrorLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemErrorLogEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1durationWatched/title",
          "value": "durationWatched"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1durationWatched/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "durationWatched"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackType/title",
          "value": "playbackType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1playbackType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "playbackType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedAverageBitrate/title",
          "value": "indicatedAverageBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedAverageBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedAverageBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedBitrate/title",
          "value": "indicatedBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1indicatedBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indicatedBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1serverAddress/title",
          "value": "serverAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1serverAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serverAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/title",
          "value": "errorLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "errorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1mediaRequestsWWAN/title",
          "value": "mediaRequestsWWAN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1mediaRequestsWWAN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaRequestsWWAN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1transferDuration/title",
          "value": "transferDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1transferDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transferDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/title",
          "value": "AVPlayerItemErrorLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemErrorLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageAudioBitrate/title",
          "value": "averageAudioBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1averageAudioBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "averageAudioBitrate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title",
          "value": "AVPlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfServerAddressChanges/title",
          "value": "numberOfServerAddressChanges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1numberOfServerAddressChanges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfServerAddressChanges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMaxBitrate/title",
          "value": "observedMaxBitrate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent~1observedMaxBitrate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "observedMaxBitrate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemaccesslogevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemaccesslogevent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
