{
  "abstract": [
    {
      "text": "An object that outputs video frames from a player item.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPlayerItemVideoOutput",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPlayerItemVideoOutput"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPlayerItemVideoOutput"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVPlayerItemVideoOutput"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput": {
      "abstract": [
        {
          "text": "An object that vends attributed strings for media with a legible characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemLegibleOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemLegibleOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemLegibleOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemlegibleoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput": {
      "abstract": [
        {
          "text": "An object that vends collections of metadata items that a player item’s tracks carry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemMetadataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemMetadataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemMetadataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemmetadataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput": {
      "abstract": [
        {
          "text": "An abstract class that defines the common interface to output media data from a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPullDelegate": {
      "abstract": [
        {
          "text": "Methods you can implement to respond to pixel buffer changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPullDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPullDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPullDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemOutputPullDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemoutputpulldelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to changes in the media data sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPushDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPushDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemOutputPushDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemoutputpushdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput": {
      "abstract": [
        {
          "text": "A player item output that vends media with a legible characteristic as rendered pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemRenderedLegibleOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemRenderedLegibleOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemRenderedLegibleOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemrenderedlegibleoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput": {
      "abstract": [
        {
          "text": "An object that outputs video frames from a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemVideoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemVideoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemVideoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/copyPixelBuffer(forItemTime:itemTimeForDisplay:)": {
      "abstract": [
        {
          "text": "Retrieves an image that is appropriate for display at the specified item time, and marks the image as acquired.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forItemTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemTimeForDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/copyPixelBuffer(forItemTime:itemTimeForDisplay:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyPixelBufferForItemTime:itemTimeForDisplay:"
        }
      ],
      "role": "symbol",
      "title": "copyPixelBuffer(forItemTime:itemTimeForDisplay:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/copypixelbuffer(foritemtime:itemtimefordisplay:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegate": {
      "abstract": [
        {
          "text": "The delegate for the video output object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVPlayerItemOutputPullDelegate",
          "text": "AVPlayerItemOutputPullDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/delegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegateQueue": {
      "abstract": [
        {
          "text": "The dispatch queue on which to call delegate methods.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegateQueue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegateQueue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegateQueue"
        }
      ],
      "role": "symbol",
      "title": "delegateQueue",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/delegatequeue"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/hasNewPixelBuffer(forItemTime:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether video output is available for the specified item time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasNewPixelBuffer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forItemTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/hasNewPixelBuffer(forItemTime:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasNewPixelBufferForItemTime:"
        }
      ],
      "role": "symbol",
      "title": "hasNewPixelBuffer(forItemTime:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/hasnewpixelbuffer(foritemtime:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(outputSettings:)": {
      "abstract": [
        {
          "text": "Creates a video output object initialized with the specified output settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "outputSettings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(outputSettings:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOutputSettings:"
        }
      ],
      "role": "symbol",
      "title": "init(outputSettings:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/init(outputsettings:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(pixelBufferAttributes:)": {
      "abstract": [
        {
          "text": "Creates a video output object using the specified pixel buffer attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "pixelBufferAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(pixelBufferAttributes:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithPixelBufferAttributes:"
        }
      ],
      "role": "symbol",
      "title": "init(pixelBufferAttributes:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/init(pixelbufferattributes:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/requestNotificationOfMediaDataChange(withAdvanceInterval:)": {
      "abstract": [
        {
          "text": "Tells the receiver that the video out put client is entering a quiescent state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestNotificationOfMediaDataChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withAdvanceInterval"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/requestNotificationOfMediaDataChange(withAdvanceInterval:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestNotificationOfMediaDataChangeWithAdvanceInterval:"
        }
      ],
      "role": "symbol",
      "title": "requestNotificationOfMediaDataChange(withAdvanceInterval:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/requestnotificationofmediadatachange(withadvanceinterval:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/setDelegate(_:queue:)": {
      "abstract": [
        {
          "text": "Sets the delegate and dispatch queue for the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDelegate"
        },
        {
          "kind": "text",
          "text": "((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVPlayerItemOutputPullDelegate",
          "text": "AVPlayerItemOutputPullDelegate"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "queue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/setDelegate(_:queue:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDelegate:queue:"
        }
      ],
      "role": "symbol",
      "title": "setDelegate(_:queue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput/setdelegate(_:queue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput": {
      "abstract": [
        {
          "text": "An object that receives video data from a player object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerVideoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerVideoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerVideoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayervideooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage": {
      "abstract": [
        {
          "text": "An object that provides a rendered pixel buffer and its position in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRenderedCaptionImage"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRenderedCaptionImage"
        }
      ],
      "role": "symbol",
      "title": "AVRenderedCaptionImage",
      "type": "topic",
      "url": "/documentation/avfoundation/avrenderedcaptionimage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification": {
      "abstract": [
        {
          "text": "An object that specifies the pixel buffer attributes and tag collections handled by a player video output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoOutputSpecification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoOutputSpecification"
        }
      ],
      "role": "symbol",
      "title": "AVVideoOutputSpecification",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideooutputspecification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset": {
      "abstract": [
        {
          "text": "Creates a collection with the required tags to describe the specified video output requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateWithVideoOutputPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateWithVideoOutputPreset",
      "type": "topic",
      "url": "/documentation/avfoundation/cmtagcollectioncreatewithvideooutputpreset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset": {
      "abstract": [
        {
          "text": "Constants that indicate the type of video content to output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionVideoOutputPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionVideoOutputPreset",
      "type": "topic",
      "url": "/documentation/avfoundation/cmtagcollectionvideooutputpreset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate"
      ],
      "title": "Media output"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Video-Output",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(pixelBufferAttributes:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(outputSettings:)"
      ],
      "title": "Creating a Video Output"
    },
    {
      "anchor": "Configuring-the-Delegate",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/setDelegate(_:queue:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPullDelegate",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegateQueue"
      ],
      "title": "Configuring the Delegate"
    },
    {
      "anchor": "Notifying-the-Delegate-of-Changes",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/requestNotificationOfMediaDataChange(withAdvanceInterval:)"
      ],
      "title": "Notifying the Delegate of Changes"
    },
    {
      "anchor": "Getting-Pixel-Buffer-Data",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/hasNewPixelBuffer(forItemTime:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/copyPixelBuffer(forItemTime:itemTimeForDisplay:)"
      ],
      "title": "Getting Pixel Buffer Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPlayerItemVideoOutput"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Video-Output",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(pixelBufferAttributes:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/init(outputSettings:)"
              ],
              "title": "Creating a Video Output"
            },
            {
              "anchor": "Configuring-the-Delegate",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/setDelegate(_:queue:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPullDelegate",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/delegateQueue"
              ],
              "title": "Configuring the Delegate"
            },
            {
              "anchor": "Notifying-the-Delegate-of-Changes",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/requestNotificationOfMediaDataChange(withAdvanceInterval:)"
              ],
              "title": "Notifying the Delegate of Changes"
            },
            {
              "anchor": "Getting-Pixel-Buffer-Data",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/hasNewPixelBuffer(forItemTime:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput/copyPixelBuffer(forItemTime:itemTimeForDisplay:)"
              ],
              "title": "Getting Pixel Buffer Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-output",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate"
              ],
              "title": "Media output"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPlayerItemVideoOutput"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVPlayerItemOutput",
                    "text": "AVPlayerItemOutput"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/title",
          "value": "AVPlayerItemOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1setDelegate(_:queue:)/title",
          "value": "setDelegate:queue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1setDelegate(_:queue:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDelegate:queue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1init(outputSettings:)/title",
          "value": "initWithOutputSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1init(outputSettings:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOutputSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/title",
          "value": "AVPlayerItemOutputPushDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPushDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPushDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1requestNotificationOfMediaDataChange(withAdvanceInterval:)/title",
          "value": "requestNotificationOfMediaDataChangeWithAdvanceInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1requestNotificationOfMediaDataChange(withAdvanceInterval:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestNotificationOfMediaDataChangeWithAdvanceInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/title",
          "value": "AVVideoOutputSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoOutputSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoOutputSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/title",
          "value": "AVPlayerItemLegibleOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1hasNewPixelBuffer(forItemTime:)/title",
          "value": "hasNewPixelBufferForItemTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1hasNewPixelBuffer(forItemTime:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hasNewPixelBufferForItemTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1init(pixelBufferAttributes:)/title",
          "value": "initWithPixelBufferAttributes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1init(pixelBufferAttributes:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithPixelBufferAttributes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/title",
          "value": "AVPlayerItemVideoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPullDelegate/title",
          "value": "AVPlayerItemOutputPullDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPullDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPullDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPullDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPullDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/title",
          "value": "AVPlayerVideoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/title",
          "value": "AVPlayerItemMetadataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/title",
          "value": "AVPlayerItemRenderedLegibleOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemRenderedLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemRenderedLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1delegateQueue/title",
          "value": "delegateQueue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1delegateQueue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegateQueue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/title",
          "value": "AVRenderedCaptionImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRenderedCaptionImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRenderedCaptionImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1copyPixelBuffer(forItemTime:itemTimeForDisplay:)/title",
          "value": "copyPixelBufferForItemTime:itemTimeForDisplay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput~1copyPixelBuffer(forItemTime:itemTimeForDisplay:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyPixelBufferForItemTime:itemTimeForDisplay:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemvideooutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avplayeritemvideooutput"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
