{"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog","interfaceLanguage":"swift"},"sections":[],"metadata":{"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"4.3","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"4.3","beta":false,"unavailable":false},{"introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"introducedAt":"10.7","deprecated":false,"beta":false,"unavailable":false,"name":"macOS"},{"introducedAt":"9.0","deprecated":false,"beta":false,"unavailable":false,"name":"tvOS"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"visionOS"},{"introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false,"name":"watchOS"}],"externalID":"c:objc(cs)AVPlayerItemAccessLog","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"modules":[{"name":"AVFoundation"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"title":"AVPlayerItemAccessLog"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLog"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"AVPlayerItemAccessLog","type":"codeVoice"},{"text":" object accumulates key metrics about network playback and presents them as a collection of ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","type":"reference"},{"text":" instances. Each event instance collates the data that relates to each uninterrupted period of playback.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An object used to retrieve the access log associated with a player item."}],"variants":[{"paths":["/documentation/avfoundation/avplayeritemaccesslog"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avplayeritemaccesslog"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent"],"generated":true,"title":"Accessing Logging Information","anchor":"Accessing-Logging-Information"}],"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/events","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogData()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogDataStringEncoding"],"title":"Accessing Log Data","anchor":"Accessing-Log-Data"}],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","role":"symbol","navigatorTitle":[{"text":"errorLog","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns an object that represents a snapshot of the error log."}],"url":"/documentation/avfoundation/avplayeritem/errorlog()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorLog","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItemErrorLog","text":"AVPlayerItemErrorLog","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorLog()","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogDataStringEncoding":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogDataStringEncoding","role":"symbol","navigatorTitle":[{"text":"extendedLogDataStringEncoding","kind":"identifier"}],"abstract":[{"type":"text","text":"The string encoding of the extended log data."}],"url":"/documentation/avfoundation/avplayeritemaccesslog/extendedlogdatastringencoding","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendedLogDataStringEncoding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"title":"extendedLogDataStringEncoding","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/events":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/events","role":"symbol","navigatorTitle":[{"text":"events","kind":"identifier"}],"abstract":[{"type":"text","text":"A chronologically ordered array of player item access log events."}],"url":"/documentation/avfoundation/avplayeritemaccesslog/events","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"events","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLogEvent","text":"AVPlayerItemAccessLogEvent","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"events","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}],"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","title":"NSObject","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"url":"/documentation/objectivec/nsobject","type":"topic","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog":{"url":"/documentation/avfoundation/avplayeritemaccesslog","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"title":"AVPlayerItemAccessLog","abstract":[{"type":"text","text":"An object used to retrieve the access log associated with a player item."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"title":"NSCopying","type":"topic","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCopying"}],"url":"/documentation/foundation/nscopying","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent":{"url":"/documentation/avfoundation/avplayeritemerrorlogevent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"title":"AVPlayerItemErrorLogEvent","abstract":[{"type":"text","text":"A single item in a player item’s error log."}],"kind":"symbol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"type":"topic","title":"CVarArg","url":"/documentation/Swift/CVarArg","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"abstract":[{"type":"text","text":"A type with a customized textual representation."}],"type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"url":"/documentation/objectivec/nsobjectprotocol","title":"NSObjectProtocol","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"url":"/documentation/Swift/CustomDebugStringConvertible","title":"CustomDebugStringConvertible","abstract":[{"text":"A type with a customized textual representation suitable for debugging purposes.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDebugStringConvertible","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"type":"topic","title":"Sendable","url":"/documentation/Swift/Sendable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog":{"url":"/documentation/avfoundation/avplayeritemerrorlog","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"title":"AVPlayerItemErrorLog","abstract":[{"type":"text","text":"The error log associated with a player item."}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent":{"abstract":[{"type":"text","text":"A single entry in a player item’s access log."}],"title":"AVPlayerItemAccessLogEvent","kind":"symbol","url":"/documentation/avfoundation/avplayeritemaccesslogevent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVPlayerItemAccessLogEvent"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVPlayerItemAccessLogEvent"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()":{"url":"/documentation/avfoundation/avplayeritem/accesslog()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessLog"}],"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessLog","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AVPlayerItemAccessLog","preciseIdentifier":"c:objc(cs)AVPlayerItemAccessLog"},{"kind":"text","text":"?"}],"title":"accessLog()","abstract":[{"text":"Returns an object that represents a snapshot of the network access log.","type":"text"}],"kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogData()":{"title":"extendedLogData()","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogData()","type":"topic","role":"symbol","url":"/documentation/avfoundation/avplayeritemaccesslog/extendedlogdata()","navigatorTitle":[{"text":"extendedLogData","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns a serialized representation of the access log in the Extended Log File Format."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendedLogData","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","deprecated":false,"introducedAt":"4.3","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"4.3","beta":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"10.7","beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"introducedAt":"9.0","beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"watchOS","deprecated":false}]},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"AVPlayerItemAccessLog","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVPlayerItemAccessLog"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Accessing-Log-Data","title":"Accessing Log Data","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/events","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogData()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLog/extendedLogDataStringEncoding"]}],"path":"/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To"}],"path":"/relationshipsSections","op":"replace"},{"value":[{"generated":true,"anchor":"Accessing-Logging-Information","title":"Accessing Logging Information","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/accessLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemAccessLogEvent","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/errorLog()","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLog","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemErrorLogEvent"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVPlayerItemAccessLog","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/title","value":"errorLog"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1errorLog()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"errorLog"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1extendedLogDataStringEncoding/title","value":"extendedLogDataStringEncoding"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1extendedLogDataStringEncoding/fragments","value":[{"kind":"identifier","text":"extendedLogDataStringEncoding"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1events/title","value":"events"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1events/fragments","value":[{"text":"events","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/title","value":"AVPlayerItemAccessLog"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/fragments","value":[{"text":"AVPlayerItemAccessLog","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog/navigatorTitle","value":[{"text":"AVPlayerItemAccessLog","kind":"identifier"}]},{"value":"AVPlayerItemErrorLogEvent","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/title"},{"value":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/fragments"},{"value":[{"kind":"identifier","text":"AVPlayerItemErrorLogEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLogEvent/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"value":"AVPlayerItemErrorLog","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/title"},{"value":[{"text":"AVPlayerItemErrorLog","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/fragments"},{"value":[{"kind":"identifier","text":"AVPlayerItemErrorLog"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemErrorLog/navigatorTitle"},{"value":"AVPlayerItemAccessLogEvent","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/title"},{"value":[{"text":"AVPlayerItemAccessLogEvent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/fragments"},{"value":[{"kind":"identifier","text":"AVPlayerItemAccessLogEvent"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLogEvent/navigatorTitle"},{"value":"accessLog","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"accessLog","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1accessLog()/fragments"},{"value":"extendedLogData","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1extendedLogData()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"extendedLogData"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemAccessLog~1extendedLogData()/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}