{
  "abstract": [
    {
      "text": "An auxiliary image used to separate foreground from background with high resolution.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVPortraitEffectsMatte",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVPortraitEffectsMatte"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVPortraitEffectsMatte"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVPortraitEffectsMatte"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPortraitEffectsMatte"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before iOS 11, the iPhone camera software used depth maps to render a shallow depth of field (the ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "bokeh",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " effect) into still images taken in Portrait Mode before discarding the maps. Because the effect was part of the photo, you couldn’t access the maps separately, as metadata, for photos taken by devices running iOS 10 or earlier.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Starting in iOS 11, apps accessing the photo library can use images containing embedded auxiliary depth maps to render creative depth effects, such as forced perspective, or image projection from 2D to 3D space. These depth maps are low-resolution compared to the full-resolution RGB image. As such, the depth effects you can render are limited by the resolution and accuracy of the maps. Fine detail, such as hair, is challenging to preserve faithfully at the resolution of these depth maps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Starting in iOS 12, the portrait effects matte helps achieve this fine-grain level of detail.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3030223",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Camera type",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "RGB image resolution",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Depth map resolution",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Portrait effects matte resolution",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Rear dual camera",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "4032 x 3024",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "768 x 576",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "2016 x 1512",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "TrueDepth camera",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "3088 x 2320",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "640 x 480",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "1544 x 1160",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "Using the auxiliary matte image, you can improve the quality of rendered portrait effects, such as Natural Light, Studio Light, Contour Light, Stage Light, and Stage Light Mono.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike the depth map, the portrait effects matte isn’t intended to faithfully preserve all gradations of depth in the scene. It’s a depth-guided, people-focused segmentation mask generated from a proprietary Apple neural network trained to detect people. It separates an individual in the foreground from whatever is in the background, with greater detail and clarity than with the depth map alone. It achieves this clarity in part because the matte image has higher resolution than the depth map.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about capturing the portrait effects matte, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To learn how to extract a portrait effects matte from photos previously captured in portrait mode on a device running iOS 12, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte": {
      "abstract": [
        {
          "text": "An auxiliary image used to separate foreground from background with high resolution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPortraitEffectsMatte"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPortraitEffectsMatte"
        }
      ],
      "role": "symbol",
      "title": "AVPortraitEffectsMatte",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/applyingExifOrientation(_:)": {
      "abstract": [
        {
          "text": "Returns a derivative portrait effects matte after applying the specified EXIF orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applyingExifOrientation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGImagePropertyOrientation",
          "text": "CGImagePropertyOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/applyingExifOrientation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteByApplyingExifOrientation:"
        }
      ],
      "role": "symbol",
      "title": "applyingExifOrientation(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/applyingexiforientation(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/dictionaryRepresentation(forAuxiliaryDataType:)": {
      "abstract": [
        {
          "text": "A dictionary of primitive map information used for writing an image file with a portrait effects matte.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dictionaryRepresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAuxiliaryDataType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "?>?) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/dictionaryRepresentation(forAuxiliaryDataType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dictionaryRepresentationForAuxiliaryDataType:"
        }
      ],
      "role": "symbol",
      "title": "dictionaryRepresentation(forAuxiliaryDataType:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/dictionaryrepresentation(forauxiliarydatatype:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/init(fromDictionaryRepresentation:)": {
      "abstract": [
        {
          "text": "Initializes a portrait effects matte instance from auxiliary image information in an image file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromDictionaryRepresentation"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/init(fromDictionaryRepresentation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteFromDictionaryRepresentation:error:"
        }
      ],
      "role": "symbol",
      "title": "init(fromDictionaryRepresentation:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/init(fromdictionaryrepresentation:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/mattingImage": {
      "abstract": [
        {
          "text": "The portrait effects matte’s internal image, formatted as a pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mattingImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/mattingImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mattingImage"
        }
      ],
      "role": "symbol",
      "title": "mattingImage",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/mattingimage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/pixelFormatType": {
      "abstract": [
        {
          "text": "The pixel format type of this portrait effects matte’s internal image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelFormatType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSType",
          "text": "OSType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/pixelFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelFormatType"
        }
      ],
      "role": "symbol",
      "title": "pixelFormatType",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/pixelformattype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/replacingPortraitEffectsMatte(with:)": {
      "abstract": [
        {
          "text": "Returns a portrait effects matte by wrapping the replacement pixel buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacingPortraitEffectsMatte"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/replacingPortraitEffectsMatte(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "portraitEffectsMatteByReplacingPortraitEffectsMatteWithPixelBuffer:error:"
        }
      ],
      "role": "symbol",
      "title": "replacingPortraitEffectsMatte(with:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avportraiteffectsmatte/replacingportraiteffectsmatte(with:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte": {
      "abstract": [
        {
          "text": "An object that wraps a matting image for a particular semantic segmentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSemanticSegmentationMatte"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSemanticSegmentationMatte"
        }
      ],
      "role": "symbol",
      "title": "AVSemanticSegmentationMatte",
      "type": "topic",
      "url": "/documentation/avfoundation/avsemanticsegmentationmatte"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte": {
      "abstract": [
        {
          "text": "Prepare your app to capture a portrait effects matte when taking photos.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte",
      "kind": "article",
      "role": "article",
      "title": "Configuring Camera Capture to Collect a Portrait Effects Matte",
      "type": "topic",
      "url": "/documentation/avfoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo": {
      "abstract": [
        {
          "text": "Check for portrait effects matte metadata in existing images.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo",
      "kind": "article",
      "role": "article",
      "title": "Extracting Portrait Effects Matte Image Data from a Photo",
      "type": "topic",
      "url": "/documentation/avfoundation/extracting-portrait-effects-matte-image-data-from-a-photo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "media-3030223": {
      "alt": "Zoomed in photo showing the fine detail in a portrait effects matte image",
      "identifier": "media-3030223",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c69e91511a8754659f6683c83569e86d/media-3030223@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Matte-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte"
      ],
      "title": "Matte data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Portrait-Effects-Matte",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/init(fromDictionaryRepresentation:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/applyingExifOrientation(_:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/replacingPortraitEffectsMatte(with:)"
      ],
      "title": "Creating a Portrait Effects Matte"
    },
    {
      "anchor": "Examining-a-Portrait-Effects-Matte",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/mattingImage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/pixelFormatType",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/dictionaryRepresentation(forAuxiliaryDataType:)"
      ],
      "title": "Examining a Portrait Effects Matte"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVPortraitEffectsMatte"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Portrait-Effects-Matte",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/configuring-camera-capture-to-collect-a-portrait-effects-matte",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/init(fromDictionaryRepresentation:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/applyingExifOrientation(_:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/replacingPortraitEffectsMatte(with:)"
              ],
              "title": "Creating a Portrait Effects Matte"
            },
            {
              "anchor": "Examining-a-Portrait-Effects-Matte",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/extracting-portrait-effects-matte-image-data-from-a-photo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/mattingImage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/pixelFormatType",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPortraitEffectsMatte/dictionaryRepresentation(forAuxiliaryDataType:)"
              ],
              "title": "Examining a Portrait Effects Matte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Matte-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSemanticSegmentationMatte"
              ],
              "title": "Matte data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVPortraitEffectsMatte"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1dictionaryRepresentation(forAuxiliaryDataType:)/title",
          "value": "dictionaryRepresentationForAuxiliaryDataType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1dictionaryRepresentation(forAuxiliaryDataType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dictionaryRepresentationForAuxiliaryDataType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte/title",
          "value": "AVPortraitEffectsMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPortraitEffectsMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1applyingExifOrientation(_:)/title",
          "value": "portraitEffectsMatteByApplyingExifOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1applyingExifOrientation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "portraitEffectsMatteByApplyingExifOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1init(fromDictionaryRepresentation:)/title",
          "value": "portraitEffectsMatteFromDictionaryRepresentation:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1init(fromDictionaryRepresentation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "portraitEffectsMatteFromDictionaryRepresentation:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1mattingImage/title",
          "value": "mattingImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1mattingImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mattingImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/title",
          "value": "AVSemanticSegmentationMatte"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSemanticSegmentationMatte/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSemanticSegmentationMatte"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1pixelFormatType/title",
          "value": "pixelFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1pixelFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1replacingPortraitEffectsMatte(with:)/title",
          "value": "portraitEffectsMatteByReplacingPortraitEffectsMatteWithPixelBuffer:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPortraitEffectsMatte~1replacingPortraitEffectsMatte(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "portraitEffectsMatteByReplacingPortraitEffectsMatteWithPixelBuffer:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avportraiteffectsmatte"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avportraiteffectsmatte"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
