{
  "abstract": [
    {
      "text": "A notification the system posts when changes occur to its detected routes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVRouteDetectorMultipleRoutesDetectedDidChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "NSNotificationName"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/detectsCustomRoutes": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether route detection includes custom routes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectsCustomRoutes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/detectsCustomRoutes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectsCustomRoutes"
        }
      ],
      "role": "symbol",
      "title": "detectsCustomRoutes",
      "type": "topic",
      "url": "/documentation/avfoundation/avroutedetector/detectscustomroutes"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/isRouteDetectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether route detection is in an enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRouteDetectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/isRouteDetectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "routeDetectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isRouteDetectionEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avroutedetector/isroutedetectionenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/multipleRoutesDetected": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the object detects more than one playback route.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleRoutesDetected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/multipleRoutesDetected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "multipleRoutesDetected"
        }
      ],
      "role": "symbol",
      "title": "multipleRoutesDetected",
      "type": "topic",
      "url": "/documentation/avfoundation/avroutedetector/multipleroutesdetected"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetectorMultipleRoutesDetectedDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when changes occur to its detected routes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetectorMultipleRoutesDetectedDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVRouteDetectorMultipleRoutesDetectedDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avroutedetectormultipleroutesdetecteddidchangenotification"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2915761-avroutedetectormultipleroutesdet": {
      "abstract": [
        {
          "text": "A notification the system posts when changes occur to its detected routes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "AVRouteDetectorMultipleRoutesDetectedDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2915761-avroutedetectormultipleroutesdet",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVRouteDetectorMultipleRoutesDetectedDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/2915761-avroutedetectormultipleroutesdet"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Detecting-Routes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/detectsCustomRoutes",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/isRouteDetectionEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVRouteDetector/multipleRoutesDetected",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/2915761-avroutedetectormultipleroutesdet"
      ],
      "title": "Detecting Routes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1multipleRoutesDetected/title",
          "value": "multipleRoutesDetected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1multipleRoutesDetected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "multipleRoutesDetected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1detectsCustomRoutes/title",
          "value": "detectsCustomRoutes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1detectsCustomRoutes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "detectsCustomRoutes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1isRouteDetectionEnabled/title",
          "value": "routeDetectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRouteDetector~1isRouteDetectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "routeDetectionEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avroutedetectormultipleroutesdetecteddidchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
