{
  "abstract": [
    {
      "text": "A structure that describes the attributes of media samples to consider when resynchronizing a decoder.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@AVSampleCursorSyncInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVSampleCursorSyncInfo"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSampleCursorSyncInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVSampleCursorSyncInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor": {
      "abstract": [
        {
          "text": "An object that provides information about the media sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursor",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo": {
      "abstract": [
        {
          "text": "A structure that describes the independent decodability of audio samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorAudioDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursoraudiodependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about a chunk of media samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo": {
      "abstract": [
        {
          "text": "A value for describing dependencies between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursordependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange": {
      "abstract": [
        {
          "text": "A structure that indicates the offset and length of storage for a media sample or its chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo": {
      "abstract": [
        {
          "text": "A structure that describes the attributes of media samples to consider when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init()": {
      "abstract": [
        {
          "text": "Creates a sample cursor sync information structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo/init()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init(sampleIsFullSync:sampleIsPartialSync:sampleIsDroppable:)": {
      "abstract": [
        {
          "text": "Creates a sample cursor sync information structure with media sample information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sampleIsFullSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleIsPartialSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sampleIsDroppable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init(sampleIsFullSync:sampleIsPartialSync:sampleIsDroppable:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(sampleIsFullSync:sampleIsPartialSync:sampleIsDroppable:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo/init(sampleisfullsync:sampleispartialsync:sampleisdroppable:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsDroppable": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a sample is droppable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleIsDroppable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsDroppable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleIsDroppable"
        }
      ],
      "role": "symbol",
      "title": "sampleIsDroppable",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo/sampleisdroppable"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsFullSync": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a sample is a full sync sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleIsFullSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsFullSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleIsFullSync"
        }
      ],
      "role": "symbol",
      "title": "sampleIsFullSync",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo/sampleisfullsync"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsPartialSync": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a sample is a partial sync sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sampleIsPartialSync"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsPartialSync",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sampleIsPartialSync"
        }
      ],
      "role": "symbol",
      "title": "sampleIsPartialSync",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo/sampleispartialsync"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-cursors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
      ],
      "title": "Sample cursors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sync-Information",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsFullSync",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsPartialSync",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsDroppable"
      ],
      "title": "Sync Information"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/init(sampleIsFullSync:sampleIsPartialSync:sampleIsDroppable:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSampleCursorSyncInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sync-Information",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsFullSync",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsPartialSync",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo/sampleIsDroppable"
              ],
              "title": "Sync Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-cursors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
              ],
              "title": "Sample cursors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVSampleCursorSyncInfo"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/title",
          "value": "AVSampleCursorStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/title",
          "value": "AVSampleCursorChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/title",
          "value": "AVSampleCursorSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/title",
          "value": "AVSampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/title",
          "value": "AVSampleCursorAudioDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/title",
          "value": "AVSampleCursorDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsDroppable/title",
          "value": "sampleIsDroppable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsDroppable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleIsDroppable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsPartialSync/title",
          "value": "sampleIsPartialSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsPartialSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleIsPartialSync"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsFullSync/title",
          "value": "sampleIsFullSync"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo~1sampleIsFullSync/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sampleIsFullSync"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursorsyncinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursorsyncinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
