{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/avsamplebufferdisplaylayer-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRenderingStatus": {
      "abstract": [
        {
          "text": "The statuses for sample buffer rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVQueuedSampleBufferRenderingStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRenderingStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVQueuedSampleBufferRenderingStatus"
        }
      ],
      "role": "symbol",
      "title": "AVQueuedSampleBufferRenderingStatus",
      "type": "topic",
      "url": "/documentation/avfoundation/avqueuedsamplebufferrenderingstatus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer": {
      "abstract": [
        {
          "text": "An object that displays compressed or uncompressed video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayer"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferDisplayLayer",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/enqueue(_:)": {
      "abstract": [
        {
          "text": "Sends a sample buffer for display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enqueue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMSampleBufferRef",
          "text": "CMSampleBuffer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/enqueue(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enqueueSampleBuffer:"
        }
      ],
      "role": "symbol",
      "title": "enqueue(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/enqueue(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/error": {
      "abstract": [
        {
          "text": "The error that caused the failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/error"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flush()": {
      "abstract": [
        {
          "text": "Instructs the layer to discard any enqueued sample buffers that are pending.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flush"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flush()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flush"
        }
      ],
      "role": "symbol",
      "title": "flush()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/flush()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flushAndRemoveImage()": {
      "abstract": [
        {
          "text": "Instructs the layer to discard pending enqueued sample buffers and remove any currently displayed image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flushAndRemoveImage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flushAndRemoveImage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flushAndRemoveImage"
        }
      ],
      "role": "symbol",
      "title": "flushAndRemoveImage()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/flushandremoveimage()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/hasSufficientMediaDataForReliablePlaybackStart": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the enqueued media data meets the renderer’s preroll level.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasSufficientMediaDataForReliablePlaybackStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/hasSufficientMediaDataForReliablePlaybackStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasSufficientMediaDataForReliablePlaybackStart"
        }
      ],
      "role": "symbol",
      "title": "hasSufficientMediaDataForReliablePlaybackStart",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/hassufficientmediadataforreliableplaybackstart"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/isReadyForMoreMediaData": {
      "abstract": [
        {
          "text": "A Boolean value that indicates the readiness of the layer to accept more sample buffers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isReadyForMoreMediaData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/isReadyForMoreMediaData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readyForMoreMediaData"
        }
      ],
      "role": "symbol",
      "title": "isReadyForMoreMediaData",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/isreadyformoremediadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requestMediaDataWhenReady(on:using:)": {
      "abstract": [
        {
          "text": "Instructs the target to invoke a client-supplied block repeatedly, at its convenience, in order to gather sample buffers for display.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestMediaDataWhenReady"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "on"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@dispatch_queue_t",
          "text": "dispatch_queue_t"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requestMediaDataWhenReady(on:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestMediaDataWhenReadyOnQueue:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "requestMediaDataWhenReady(on:using:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/requestmediadatawhenready(on:using:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requiresFlushToResumeDecoding": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the layer needs to flush its state to continue decoding frames.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresFlushToResumeDecoding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requiresFlushToResumeDecoding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresFlushToResumeDecoding"
        }
      ],
      "role": "symbol",
      "title": "requiresFlushToResumeDecoding",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/requiresflushtoresumedecoding"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/status": {
      "abstract": [
        {
          "text": "The ability of the display layer to be used for enqueuing sample buffers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "status"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVQueuedSampleBufferRenderingStatus",
          "text": "AVQueuedSampleBufferRenderingStatus"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/status",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "status"
        }
      ],
      "role": "symbol",
      "title": "status",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/status"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/stopRequestingMediaData()": {
      "abstract": [
        {
          "text": "Cancels any current media data request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopRequestingMediaData"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/stopRequestingMediaData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopRequestingMediaData"
        }
      ],
      "role": "symbol",
      "title": "stopRequestingMediaData()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/stoprequestingmediadata()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/timebase": {
      "abstract": [
        {
          "text": "The renderer’s timebase, which determines how the layer interprets time stamps.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timebase"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMTimebaseRef",
          "text": "CMTimebase"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/timebase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timebase"
        }
      ],
      "role": "symbol",
      "title": "timebase",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer/timebase"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback": {
      "abstract": [
        {
          "text": "Create custom controllers to play and synchronize the timing of sample buffer streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample buffer playback",
      "type": "topic",
      "url": "/documentation/avfoundation/sample-buffer-playback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initiating-Media-Data-Requests",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requestMediaDataWhenReady(on:using:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/isReadyForMoreMediaData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requiresFlushToResumeDecoding",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/stopRequestingMediaData()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/hasSufficientMediaDataForReliablePlaybackStart"
      ],
      "title": "Initiating Media Data Requests"
    },
    {
      "anchor": "Flushing-Sample-Buffers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flush()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flushAndRemoveImage()"
      ],
      "title": "Flushing Sample Buffers"
    },
    {
      "anchor": "Configuring-the-Timebase",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/timebase"
      ],
      "title": "Configuring the Timebase"
    },
    {
      "anchor": "Enqueuing-the-Sample-Buffer",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/enqueue(_:)"
      ],
      "title": "Enqueuing the Sample Buffer"
    },
    {
      "anchor": "Getting-Display-Layer-Settings",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/status",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRenderingStatus"
      ],
      "title": "Getting Display Layer Settings"
    },
    {
      "anchor": "Handling-Errors",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/error"
      ],
      "title": "Handling Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initiating-Media-Data-Requests",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requestMediaDataWhenReady(on:using:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/isReadyForMoreMediaData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/requiresFlushToResumeDecoding",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/stopRequestingMediaData()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/hasSufficientMediaDataForReliablePlaybackStart"
              ],
              "title": "Initiating Media Data Requests"
            },
            {
              "anchor": "Flushing-Sample-Buffers",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flush()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/flushAndRemoveImage()"
              ],
              "title": "Flushing Sample Buffers"
            },
            {
              "anchor": "Configuring-the-Timebase",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/timebase"
              ],
              "title": "Configuring the Timebase"
            },
            {
              "anchor": "Enqueuing-the-Sample-Buffer",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/enqueue(_:)"
              ],
              "title": "Enqueuing the Sample Buffer"
            },
            {
              "anchor": "Getting-Display-Layer-Settings",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/status",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRenderingStatus"
              ],
              "title": "Getting Display Layer Settings"
            },
            {
              "anchor": "Handling-Errors",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer/error"
              ],
              "title": "Handling Errors"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRenderingStatus/title",
          "value": "AVQueuedSampleBufferRenderingStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRenderingStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVQueuedSampleBufferRenderingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRenderingStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVQueuedSampleBufferRenderingStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1isReadyForMoreMediaData/title",
          "value": "readyForMoreMediaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1isReadyForMoreMediaData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "readyForMoreMediaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1requestMediaDataWhenReady(on:using:)/title",
          "value": "requestMediaDataWhenReadyOnQueue:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1requestMediaDataWhenReady(on:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestMediaDataWhenReadyOnQueue:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1timebase/title",
          "value": "timebase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1timebase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timebase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1enqueue(_:)/title",
          "value": "enqueueSampleBuffer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1enqueue(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enqueueSampleBuffer:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1status/title",
          "value": "status"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1status/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1flushAndRemoveImage()/title",
          "value": "flushAndRemoveImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1flushAndRemoveImage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flushAndRemoveImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1flush()/title",
          "value": "flush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1flush()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "flush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1error/title",
          "value": "error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1hasSufficientMediaDataForReliablePlaybackStart/title",
          "value": "hasSufficientMediaDataForReliablePlaybackStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1hasSufficientMediaDataForReliablePlaybackStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasSufficientMediaDataForReliablePlaybackStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1requiresFlushToResumeDecoding/title",
          "value": "requiresFlushToResumeDecoding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1requiresFlushToResumeDecoding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresFlushToResumeDecoding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1stopRequestingMediaData()/title",
          "value": "stopRequestingMediaData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer~1stopRequestingMediaData()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopRequestingMediaData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/title",
          "value": "AVSampleBufferDisplayLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferDisplayLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferDisplayLayer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avsamplebufferdisplaylayer-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avsamplebufferdisplaylayer-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
