{
  "abstract": [
    {
      "text": "An object that provides information about the media sample at the cursor’s current position.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVSampleCursor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVSampleCursor"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVSampleCursor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVSampleCursor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You position a sample cursor at a specific media sample in a sequence of samples contained in a higher-level object, like an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can move it to a new position in that sequence either backwards or forwards, either in decode order or in presentation order. You can also request moving it according to a count of samples or a delta in time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use a sample cursor to get information about the media sample such as its duration, timestamps, dependency information, and so on. You can also use them to synchronously to perform I/O in order to load media data of one or more media samples into memory.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack": {
      "abstract": [
        {
          "text": "An object that models a track of media that an asset contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor": {
      "abstract": [
        {
          "text": "An object that provides information about the media sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursor",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/comparePositionInDecodeOrder(withPositionOf:)": {
      "abstract": [
        {
          "text": "Compares the relative positions of two sample cursors and returns their relative positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "comparePositionInDecodeOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withPositionOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSampleCursor",
          "text": "AVSampleCursor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSComparisonResult",
          "text": "ComparisonResult"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/comparePositionInDecodeOrder(withPositionOf:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "comparePositionInDecodeOrderWithPositionOfCursor:"
        }
      ],
      "role": "symbol",
      "title": "comparePositionInDecodeOrder(withPositionOf:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/comparepositionindecodeorder(withpositionof:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()": {
      "abstract": [
        {
          "text": "Returns the format description of the sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyCurrentSampleFormatDescription"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMFormatDescriptionRef",
          "text": "CMFormatDescription"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "copyCurrentSampleFormatDescription"
        }
      ],
      "role": "symbol",
      "title": "copyCurrentSampleFormatDescription()",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/copycurrentsampleformatdescription()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about the chunk of samples to which the current sample belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorChunkInfo",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "currentChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange": {
      "abstract": [
        {
          "text": "The sample range in the storage container to load together with the current sample as a chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkStorageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorStorageRange",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkStorageRange"
        }
      ],
      "role": "symbol",
      "title": "currentChunkStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL": {
      "abstract": [
        {
          "text": "The URL of the storage container of the current sample and other samples to load in the same operation as a chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentChunkStorageURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentChunkStorageURL"
        }
      ],
      "role": "symbol",
      "title": "currentChunkStorageURL",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentchunkstorageurl"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo": {
      "abstract": [
        {
          "text": "The independent decodability information for the audio sample.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleAudioDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorAudioDependencyInfo",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleAudioDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleAudioDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleaudiodependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments": {
      "abstract": [
        {
          "text": "A dictionary of dependency-related sample buffer attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDependencyAttachments"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDependencyAttachments"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDependencyAttachments",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampledependencyattachments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo": {
      "abstract": [
        {
          "text": "The dependency information that describes relationships between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDependencyInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorDependencyInfo",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampledependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration": {
      "abstract": [
        {
          "text": "The decode duration of the sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleDuration"
        }
      ],
      "role": "symbol",
      "title": "currentSampleDuration",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleduration"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk": {
      "abstract": [
        {
          "text": "The index of the current sample within the chunk to which it belongs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleIndexInChunk"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleIndexInChunk"
        }
      ],
      "role": "symbol",
      "title": "currentSampleIndexInChunk",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsampleindexinchunk"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange": {
      "abstract": [
        {
          "text": "The offset and length of the current sample in the current chunk storage URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleStorageRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorStorageRange",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleStorageRange"
        }
      ],
      "role": "symbol",
      "title": "currentSampleStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsamplestoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo": {
      "abstract": [
        {
          "text": "The synchronization information for the current sample for consideration when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentSampleSyncInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@AVSampleCursorSyncInfo",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentSampleSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "currentSampleSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/currentsamplesyncinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/decodeTimeStamp": {
      "abstract": [
        {
          "text": "The decode timestamp of the sample at the current position of the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decodeTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/decodeTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decodeTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "decodeTimeStamp",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/decodetimestamp"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)": {
      "abstract": [
        {
          "text": "Determines whether a sample earlier in decode order can have a presentation timestamp later than that of the specified sample cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "laterThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSampleCursor",
          "text": "AVSampleCursor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplesWithEarlierDecodeTimeStampsMayHaveLaterPresentationTimeStampsThanCursor:"
        }
      ],
      "role": "symbol",
      "title": "maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/maysampleswithearlierdecodetimestampshavepresentationtimestamps(laterthan:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)": {
      "abstract": [
        {
          "text": "Determines whether a sample later in decode order can have a presentation timestamp earlier than that of the specified sample cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "earlierThan"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVSampleCursor",
          "text": "AVSampleCursor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplesWithLaterDecodeTimeStampsMayHaveEarlierPresentationTimeStampsThanCursor:"
        }
      ],
      "role": "symbol",
      "title": "maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/maysampleswithlaterdecodetimestampshavepresentationtimestamps(earlierthan:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/presentationTimeStamp": {
      "abstract": [
        {
          "text": "The presentation timestamp of the sample at the current position of the cursor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationTimeStamp"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/presentationTimeStamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationTimeStamp"
        }
      ],
      "role": "symbol",
      "title": "presentationTimeStamp",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/presentationtimestamp"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/samplesRequiredForDecoderRefresh": {
      "abstract": [
        {
          "text": "The number of samples prior to the current sample, in decode order, the decoder requires to achieve a coherent output at the current decode time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "samplesRequiredForDecoderRefresh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/samplesRequiredForDecoderRefresh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "samplesRequiredForDecoderRefresh"
        }
      ],
      "role": "symbol",
      "title": "samplesRequiredForDecoderRefresh",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/samplesrequiredfordecoderrefresh"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byDecodeTime:wasPinned:)": {
      "abstract": [
        {
          "text": "Moves the cursor by a given delta time on the decode timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "step"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byDecodeTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "wasPinned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byDecodeTime:wasPinned:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepByDecodeTime:wasPinned:"
        }
      ],
      "role": "symbol",
      "title": "step(byDecodeTime:wasPinned:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/step(bydecodetime:waspinned:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byPresentationTime:wasPinned:)": {
      "abstract": [
        {
          "text": "Moves the cursor by a given delta time on the presentation timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "step"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byPresentationTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "wasPinned"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byPresentationTime:wasPinned:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepByPresentationTime:wasPinned:"
        }
      ],
      "role": "symbol",
      "title": "step(byPresentationTime:wasPinned:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/step(bypresentationtime:waspinned:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInDecodeOrder(byCount:)": {
      "abstract": [
        {
          "text": "Moves the cursor a given number of samples in decode order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stepInDecodeOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInDecodeOrder(byCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepInDecodeOrderByCount:"
        }
      ],
      "role": "symbol",
      "title": "stepInDecodeOrder(byCount:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/stepindecodeorder(bycount:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInPresentationOrder(byCount:)": {
      "abstract": [
        {
          "text": "Moves the cursor a given number of samples in presentation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stepInPresentationOrder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInPresentationOrder(byCount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stepInPresentationOrderByCount:"
        }
      ],
      "role": "symbol",
      "title": "stepInPresentationOrder(byCount:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor/stepinpresentationorder(bycount:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo": {
      "abstract": [
        {
          "text": "A structure that describes the independent decodability of audio samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorAudioDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursoraudiodependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about a chunk of media samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo": {
      "abstract": [
        {
          "text": "A value for describing dependencies between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursordependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange": {
      "abstract": [
        {
          "text": "A structure that indicates the offset and length of storage for a media sample or its chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo": {
      "abstract": [
        {
          "text": "A structure that describes the attributes of media samples to consider when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Sample-cursors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
      ],
      "title": "Sample cursors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Navigating-Samples",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byDecodeTime:wasPinned:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byPresentationTime:wasPinned:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInDecodeOrder(byCount:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInPresentationOrder(byCount:)"
      ],
      "title": "Navigating Samples"
    },
    {
      "anchor": "Getting-Timestamps",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/decodeTimeStamp",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/presentationTimeStamp"
      ],
      "title": "Getting Timestamps"
    },
    {
      "anchor": "Getting-Sample-Information",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments"
      ],
      "title": "Getting Sample Information"
    },
    {
      "anchor": "Accessing-Samples",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/samplesRequiredForDecoderRefresh"
      ],
      "title": "Accessing Samples"
    },
    {
      "anchor": "Comparing-Sample-Cursors",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/comparePositionInDecodeOrder(withPositionOf:)"
      ],
      "title": "Comparing Sample Cursors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVSampleCursor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Navigating-Samples",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byDecodeTime:wasPinned:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/step(byPresentationTime:wasPinned:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInDecodeOrder(byCount:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/stepInPresentationOrder(byCount:)"
              ],
              "title": "Navigating Samples"
            },
            {
              "anchor": "Getting-Timestamps",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/decodeTimeStamp",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/presentationTimeStamp"
              ],
              "title": "Getting Timestamps"
            },
            {
              "anchor": "Getting-Sample-Information",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentChunkStorageURL",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDuration",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleIndexInChunk",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/copyCurrentSampleFormatDescription()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleAudioDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/currentSampleDependencyAttachments"
              ],
              "title": "Getting Sample Information"
            },
            {
              "anchor": "Accessing-Samples",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/samplesRequiredForDecoderRefresh"
              ],
              "title": "Accessing Samples"
            },
            {
              "anchor": "Comparing-Sample-Cursors",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor/comparePositionInDecodeOrder(withPositionOf:)"
              ],
              "title": "Comparing Sample Cursors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Sample-cursors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
              ],
              "title": "Sample cursors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVSampleCursor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkInfo/title",
          "value": "currentChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/title",
          "value": "AVSampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1presentationTimeStamp/title",
          "value": "presentationTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1presentationTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/title",
          "value": "AVSampleCursorStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1stepInDecodeOrder(byCount:)/title",
          "value": "stepInDecodeOrderByCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1stepInDecodeOrder(byCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stepInDecodeOrderByCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1copyCurrentSampleFormatDescription()/title",
          "value": "copyCurrentSampleFormatDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1copyCurrentSampleFormatDescription()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "copyCurrentSampleFormatDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1step(byPresentationTime:wasPinned:)/title",
          "value": "stepByPresentationTime:wasPinned:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1step(byPresentationTime:wasPinned:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stepByPresentationTime:wasPinned:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1samplesRequiredForDecoderRefresh/title",
          "value": "samplesRequiredForDecoderRefresh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1samplesRequiredForDecoderRefresh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "samplesRequiredForDecoderRefresh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleStorageRange/title",
          "value": "currentSampleStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1step(byDecodeTime:wasPinned:)/title",
          "value": "stepByDecodeTime:wasPinned:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1step(byDecodeTime:wasPinned:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stepByDecodeTime:wasPinned:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageURL/title",
          "value": "currentChunkStorageURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkStorageURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/title",
          "value": "AVSampleCursorAudioDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageRange/title",
          "value": "currentChunkStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentChunkStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentChunkStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/title",
          "value": "AVSampleCursorChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1comparePositionInDecodeOrder(withPositionOf:)/title",
          "value": "comparePositionInDecodeOrderWithPositionOfCursor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1comparePositionInDecodeOrder(withPositionOf:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "comparePositionInDecodeOrderWithPositionOfCursor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/title",
          "value": "AVSampleCursorDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyAttachments/title",
          "value": "currentSampleDependencyAttachments"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyAttachments/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDependencyAttachments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyInfo/title",
          "value": "currentSampleDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1decodeTimeStamp/title",
          "value": "decodeTimeStamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1decodeTimeStamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "decodeTimeStamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)/title",
          "value": "samplesWithLaterDecodeTimeStampsMayHaveEarlierPresentationTimeStampsThanCursor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1maySamplesWithLaterDecodeTimeStampsHavePresentationTimeStamps(earlierThan:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "samplesWithLaterDecodeTimeStampsMayHaveEarlierPresentationTimeStampsThanCursor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleSyncInfo/title",
          "value": "currentSampleSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)/title",
          "value": "samplesWithEarlierDecodeTimeStampsMayHaveLaterPresentationTimeStampsThanCursor:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1maySamplesWithEarlierDecodeTimeStampsHavePresentationTimeStamps(laterThan:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "samplesWithEarlierDecodeTimeStampsMayHaveLaterPresentationTimeStampsThanCursor:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/title",
          "value": "AVSampleCursorSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDuration/title",
          "value": "currentSampleDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/title",
          "value": "AVAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1stepInPresentationOrder(byCount:)/title",
          "value": "stepInPresentationOrderByCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1stepInPresentationOrder(byCount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stepInPresentationOrderByCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleAudioDependencyInfo/title",
          "value": "currentSampleAudioDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleAudioDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleIndexInChunk/title",
          "value": "currentSampleIndexInChunk"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor~1currentSampleIndexInChunk/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentSampleIndexInChunk"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avsamplecursor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
