{
  "abstract": [
    {
      "text": "Specify options to configure the initialization of a media asset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-initialization-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Initialization Options"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset": {
      "abstract": [
        {
          "text": "An asset that represents media at a local or remote URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "role": "symbol",
      "title": "AVURLAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:": {
      "abstract": [
        {
          "text": "Returns an asset that models the media resource found at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "URLAssetWithURL:options:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLAssetWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "URLAssetWithURL:options:",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/urlassetwithurl:options:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)": {
      "abstract": [
        {
          "text": "Creates an asset that models the media at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/init(url:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)": {
      "abstract": [
        {
          "text": "Creates an asset that models the media resource at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "init(url:options:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/init(url:options:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system can make network requests on behalf of the asset when connected to a cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsCellularAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsCellularAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsCellularAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowscellularaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system allows network requests on behalf of this asset to use the constrained interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsConstrainedNetworkAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowsconstrainednetworkaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system allows network requests on behalf of this asset to use the expensive interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsExpensiveNetworkAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowsexpensivenetworkaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey": {
      "abstract": [
        {
          "text": "The HTTP cookies that a URL asset may send with HTTP requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPCookiesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPCookiesKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetHTTPCookiesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassethttpcookieskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey": {
      "abstract": [
        {
          "text": "A key that specifies the user agent of requests that an asset makes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPUserAgentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPUserAgentKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetHTTPUserAgentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassethttpuseragentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey": {
      "abstract": [
        {
          "text": "A key that specifies the MIME type to use to identify the format of a media resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetOverrideMIMETypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetOverrideMIMETypeKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetOverrideMIMETypeKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetoverridemimetypekey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset should provide accurate duration and precise random access by time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetPreferPreciseDurationAndTimingKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetpreferprecisedurationandtimingkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey": {
      "abstract": [
        {
          "text": "Specifies a UUID to set as the session identifier for HTTP requests that the asset makes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetPrimarySessionIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetPrimarySessionIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetPrimarySessionIdentifierKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetprimarysessionidentifierkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey": {
      "abstract": [
        {
          "text": "A value that represents the restrictions used by the asset when resolving references to external media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetReferenceRestrictionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetReferenceRestrictionsKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetReferenceRestrictionsKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetreferencerestrictionskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system parses and resolves alias data references in the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetShouldSupportAliasDataReferencesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetshouldsupportaliasdatareferenceskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey": {
      "abstract": [
        {
          "text": "A value that specifies the attribution of the URLs that this asset requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetURLRequestAttributionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetURLRequestAttributionKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetURLRequestAttributionKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasseturlrequestattributionkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Asset",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)"
      ],
      "title": "Creating an Asset"
    }
  ],
  "topicSections": [
    {
      "anchor": "Options",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Options",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-Asset",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:"
              ],
              "title": "Creating an Asset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsExpensiveNetworkAccessKey/title",
          "value": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsExpensiveNetworkAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPreferPreciseDurationAndTimingKey/title",
          "value": "AVURLAssetPreferPreciseDurationAndTimingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPreferPreciseDurationAndTimingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsConstrainedNetworkAccessKey/title",
          "value": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsConstrainedNetworkAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetOverrideMIMETypeKey/title",
          "value": "AVURLAssetOverrideMIMETypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetOverrideMIMETypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetOverrideMIMETypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetReferenceRestrictionsKey/title",
          "value": "AVURLAssetReferenceRestrictionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetReferenceRestrictionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetReferenceRestrictionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1init(url:options:)/title",
          "value": "initWithURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1init(url:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPrimarySessionIdentifierKey/title",
          "value": "AVURLAssetPrimarySessionIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPrimarySessionIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetPrimarySessionIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsCellularAccessKey/title",
          "value": "AVURLAssetAllowsCellularAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsCellularAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsCellularAccessKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/title",
          "value": "AVURLAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetURLRequestAttributionKey/title",
          "value": "AVURLAssetURLRequestAttributionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetURLRequestAttributionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetURLRequestAttributionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPUserAgentKey/title",
          "value": "AVURLAssetHTTPUserAgentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPUserAgentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetHTTPUserAgentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPCookiesKey/title",
          "value": "AVURLAssetHTTPCookiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPCookiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetHTTPCookiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetShouldSupportAliasDataReferencesKey/title",
          "value": "AVURLAssetShouldSupportAliasDataReferencesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetShouldSupportAliasDataReferencesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avurlasset-initialization-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avurlasset-initialization-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
