{
  "abstract": [
    {
      "text": "An asset that represents media at a local or remote URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVURLAsset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVURLAsset"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVURLAsset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVURLAsset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class is a concrete subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When you create an asset as shown below, the system creates and returns an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// A local or remote asset URL.",
            "guard let url: URL = Bundle.main.url(forResource: \"Image\",",
            "                                     withExtension: \"png\") else { return }",
            "let asset = AVAsset(url: url)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In many cases, this is an appropriate way to create asset instances, but you can also directly instantiate an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when you need more fine-grained control over its initialization. The initializer for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " accepts an options dictionary, which you use to customize the asset’s initialization for your particular purpose. For example, if you’re creating an asset for an HLS stream, you may want to prevent it from retrieving its media when it connects over a cellular network. You can do this by providing the initialization option and value as shown below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let url: URL = // A remote asset URL.",
            "let options = [AVURLAssetAllowsCellularAccessKey: false]",
            "let asset = AVURLAsset(url: url, options: options)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset": {
      "abstract": [
        {
          "text": "An object that models timed audiovisual media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "role": "symbol",
      "title": "AVAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack": {
      "abstract": [
        {
          "text": "An object that models a track of media that an asset contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup": {
      "abstract": [
        {
          "text": "A group of related tracks in an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroup"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroup"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrackGroup",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment": {
      "abstract": [
        {
          "text": "An object that represents a time range segment of an asset track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrackSegment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackSegment"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrackSegment",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettracksegment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading": {
      "abstract": [
        {
          "text": "A protocol that defines the interface to load media data asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "role": "symbol",
      "title": "AVAsynchronousKeyValueLoading",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronouskeyvalueloading"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient": {
      "abstract": [
        {
          "text": "A protocol for requiring decryption keys for media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContentKeyRecipient"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContentKeyRecipient"
        }
      ],
      "role": "symbol",
      "title": "AVContentKeyRecipient",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontentkeyrecipient"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset": {
      "abstract": [
        {
          "text": "An asset with a duration that the system can extend without modifying its existing media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedAsset"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaExtensionProperties": {
      "abstract": [
        {
          "text": "An object that describes a Media Extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaExtensionProperties"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaExtensionProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaExtensionProperties"
        }
      ],
      "role": "symbol",
      "title": "AVMediaExtensionProperties",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediaextensionproperties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/tracks-44ptx": {
      "abstract": [
        {
          "text": "The tracks an asset contains.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVURLAsset",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tracks"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "]>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/tracks-44ptx",
      "kind": "symbol",
      "role": "symbol",
      "title": "tracks",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/tracks-44ptx"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/variants": {
      "abstract": [
        {
          "text": "An array of variants that an asset contains.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Root",
            "type": "codeVoice"
          },
          {
            "text": " inherits ",
            "type": "text"
          },
          {
            "code": "AVURLAsset",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variants"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation15AVAsyncPropertyC",
          "text": "AVAsyncProperty"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Root"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "]>"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/variants",
      "kind": "symbol",
      "role": "symbol",
      "title": "variants",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty/variants"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset": {
      "abstract": [
        {
          "text": "An asset that represents media at a local or remote URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "role": "symbol",
      "title": "AVURLAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:": {
      "abstract": [
        {
          "text": "Returns an asset that models the media resource found at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "URLAssetWithURL:options:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URLAssetWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "URLAssetWithURL:options:",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/urlassetwithurl:options:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/assetCache": {
      "abstract": [
        {
          "text": "The asset’s associated asset cache, if it exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetCache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetCache",
          "text": "AVAssetCache"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/assetCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "assetCache"
        }
      ],
      "role": "symbol",
      "title": "assetCache",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/assetcache"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualMIMETypes()": {
      "abstract": [
        {
          "text": "Returns an array of the MIME types the asset supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audiovisualMIMETypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualMIMETypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audiovisualMIMETypes"
        }
      ],
      "role": "symbol",
      "title": "audiovisualMIMETypes()",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/audiovisualmimetypes()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualTypes()": {
      "abstract": [
        {
          "text": "Returns an array of the file types the asset supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audiovisualTypes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVFileType",
          "text": "AVFileType"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "audiovisualTypes"
        }
      ],
      "role": "symbol",
      "title": "audiovisualTypes()",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/audiovisualtypes()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/compatibleTrack(for:)": {
      "abstract": [
        {
          "text": "Returns an asset track from which you can insert any time range into a given composition track.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compatibleTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrack",
          "text": "AVCompositionTrack"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/compatibleTrack(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compatibleTrackForCompositionTrack:"
        }
      ],
      "role": "symbol",
      "title": "compatibleTrack(for:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/compatibletrack(for:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/findCompatibleTrack(for:completionHandler:)": {
      "abstract": [
        {
          "text": "Loads an asset track from which you can insert any time range into the composition track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findCompatibleTrack"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCompositionTrack",
          "text": "AVCompositionTrack"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetTrack",
          "text": "AVAssetTrack"
        },
        {
          "kind": "text",
          "text": "?, (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/findCompatibleTrack(for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findCompatibleTrackForCompositionTrack:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "findCompatibleTrack(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/findcompatibletrack(for:completionhandler:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/httpSessionIdentifier": {
      "abstract": [
        {
          "text": "A session identifier that the asset sends in HTTP requests that it makes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "httpSessionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/httpSessionIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "httpSessionIdentifier"
        }
      ],
      "role": "symbol",
      "title": "httpSessionIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/httpsessionidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)": {
      "abstract": [
        {
          "text": "Creates an asset that models the media at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/init(url:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)": {
      "abstract": [
        {
          "text": "Creates an asset that models the media resource at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "init(url:options:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/init(url:options:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/isPlayableExtendedMIMEType(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the asset is playable with the specified codecs and container type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPlayableExtendedMIMEType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/isPlayableExtendedMIMEType(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isPlayableExtendedMIMEType:"
        }
      ],
      "role": "symbol",
      "title": "isPlayableExtendedMIMEType(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/isplayableextendedmimetype(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mayRequireContentKeysForMediaDataProcessing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether you can add this asset as a content key recipient to a content key session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mayRequireContentKeysForMediaDataProcessing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mayRequireContentKeysForMediaDataProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mayRequireContentKeysForMediaDataProcessing"
        }
      ],
      "role": "symbol",
      "title": "mayRequireContentKeysForMediaDataProcessing",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/mayrequirecontentkeysformediadataprocessing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties": {
      "abstract": [
        {
          "text": "The properties of the media extension format reader that decodes the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaExtensionProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaExtensionProperties",
          "text": "AVMediaExtensionProperties"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaExtensionProperties"
        }
      ],
      "role": "symbol",
      "title": "mediaExtensionProperties",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/mediaextensionproperties"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/resourceLoader": {
      "abstract": [
        {
          "text": "The resource loader for the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resourceLoader"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetResourceLoader",
          "text": "AVAssetResourceLoader"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/resourceLoader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resourceLoader"
        }
      ],
      "role": "symbol",
      "title": "resourceLoader",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/resourceloader"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/url": {
      "abstract": [
        {
          "text": "A URL to the asset’s media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/url",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "role": "symbol",
      "title": "url",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/url"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/variants": {
      "abstract": [
        {
          "text": "An array of variants that an asset contains.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "variants"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAssetVariant",
          "text": "AVAssetVariant"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/variants",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "variants"
        }
      ],
      "role": "symbol",
      "title": "variants",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset/variants"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-initialization-options": {
      "abstract": [
        {
          "text": "Specify options to configure the initialization of a media asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-initialization-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Initialization Options",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset-initialization-options"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to create an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderReading"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderReading",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderreading"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to retrieve data from an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderWriting"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderWriting",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderwriting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assets",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup"
      ],
      "title": "Assets"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-Asset",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-initialization-options"
      ],
      "title": "Creating an Asset"
    },
    {
      "anchor": "Loading-Tracks",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/tracks-44ptx",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/findCompatibleTrack(for:completionHandler:)"
      ],
      "title": "Loading Tracks"
    },
    {
      "anchor": "Loading-Variants",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty/variants"
      ],
      "title": "Loading Variants"
    },
    {
      "anchor": "Determining-Supported-Media-Types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualTypes()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualMIMETypes()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/isPlayableExtendedMIMEType(_:)"
      ],
      "title": "Determining Supported Media Types"
    },
    {
      "anchor": "Assisting-with-Resource-Loading",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/resourceLoader",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mayRequireContentKeysForMediaDataProcessing"
      ],
      "title": "Assisting with Resource Loading"
    },
    {
      "anchor": "Working-with-Offline-Assets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/assetCache"
      ],
      "title": "Working with Offline Assets"
    },
    {
      "anchor": "Accessing-the-Media-URL",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/url"
      ],
      "title": "Accessing the Media URL"
    },
    {
      "anchor": "Accessing-Asset-Variants",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/variants"
      ],
      "title": "Accessing Asset Variants"
    },
    {
      "anchor": "Accessing-Compatible-Tracks",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/compatibleTrack(for:)"
      ],
      "title": "Accessing Compatible Tracks"
    },
    {
      "anchor": "Accessing-the-Session-Identifier",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/httpSessionIdentifier"
      ],
      "title": "Accessing the Session Identifier"
    },
    {
      "anchor": "Accessing-Media-Extension-Properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaExtensionProperties"
      ],
      "title": "Accessing Media Extension Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVURLAsset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-Asset",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/init(url:options:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/URLAssetWithURL:options:",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avurlasset-initialization-options"
              ],
              "title": "Creating an Asset"
            },
            {
              "anchor": "Loading-Tracks",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/findCompatibleTrack(for:completionHandler:)"
              ],
              "title": "Loading Tracks"
            },
            {
              "anchor": "Determining-Supported-Media-Types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualTypes()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/audiovisualMIMETypes()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/isPlayableExtendedMIMEType(_:)"
              ],
              "title": "Determining Supported Media Types"
            },
            {
              "anchor": "Assisting-with-Resource-Loading",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/resourceLoader",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mayRequireContentKeysForMediaDataProcessing"
              ],
              "title": "Assisting with Resource Loading"
            },
            {
              "anchor": "Working-with-Offline-Assets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/assetCache"
              ],
              "title": "Working with Offline Assets"
            },
            {
              "anchor": "Accessing-the-Media-URL",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/url"
              ],
              "title": "Accessing the Media URL"
            },
            {
              "anchor": "Accessing-Asset-Variants",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/variants"
              ],
              "title": "Accessing Asset Variants"
            },
            {
              "anchor": "Accessing-Compatible-Tracks",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/compatibleTrack(for:)"
              ],
              "title": "Accessing Compatible Tracks"
            },
            {
              "anchor": "Accessing-the-Session-Identifier",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/httpSessionIdentifier"
              ],
              "title": "Accessing the Session Identifier"
            },
            {
              "anchor": "Accessing-Media-Extension-Properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset/mediaExtensionProperties",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaExtensionProperties"
              ],
              "title": "Accessing Media Extension Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContentKeyRecipient",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderReading",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSItemProviderWriting"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assets",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup"
              ],
              "title": "Assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVURLAsset"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)AVAsset",
                    "text": "AVAsset"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1url/title",
          "value": "URL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1url/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "URL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1audiovisualMIMETypes()/title",
          "value": "audiovisualMIMETypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1audiovisualMIMETypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "audiovisualMIMETypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/title",
          "value": "AVAssetTrackSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1mediaExtensionProperties/title",
          "value": "mediaExtensionProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1mediaExtensionProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mediaExtensionProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaExtensionProperties/title",
          "value": "AVMediaExtensionProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaExtensionProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaExtensionProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaExtensionProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaExtensionProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1compatibleTrack(for:)/title",
          "value": "compatibleTrackForCompositionTrack:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1compatibleTrack(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "compatibleTrackForCompositionTrack:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/title",
          "value": "AVAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/title",
          "value": "AVFragmentedAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1httpSessionIdentifier/title",
          "value": "httpSessionIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1httpSessionIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "httpSessionIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/title",
          "value": "AVAsynchronousKeyValueLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/title",
          "value": "AVURLAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1assetCache/title",
          "value": "assetCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1assetCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "assetCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1mayRequireContentKeysForMediaDataProcessing/title",
          "value": "mayRequireContentKeysForMediaDataProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1mayRequireContentKeysForMediaDataProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mayRequireContentKeysForMediaDataProcessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/title",
          "value": "AVAssetTrackGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1init(url:options:)/title",
          "value": "initWithURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1init(url:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1variants/title",
          "value": "variants"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1variants/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "variants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1isPlayableExtendedMIMEType(_:)/title",
          "value": "isPlayableExtendedMIMEType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1isPlayableExtendedMIMEType(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "isPlayableExtendedMIMEType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1audiovisualTypes()/title",
          "value": "audiovisualTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1audiovisualTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "audiovisualTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/title",
          "value": "AVAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1resourceLoader/title",
          "value": "resourceLoader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1resourceLoader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resourceLoader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/title",
          "value": "AVContentKeyRecipient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContentKeyRecipient/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContentKeyRecipient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1findCompatibleTrack(for:completionHandler:)/title",
          "value": "findCompatibleTrackForCompositionTrack:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset~1findCompatibleTrack(for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findCompatibleTrackForCompositionTrack:completionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avurlasset"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avurlasset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
