{
  "abstract": [
    {
      "text": "A value that represents the restrictions used by the asset when resolving references to external media data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVURLAssetReferenceRestrictionsKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVURLAssetReferenceRestrictionsKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVURLAssetReferenceRestrictionsKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVURLAssetReferenceRestrictionsKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVURLAssetReferenceRestrictionsKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The corresponding value is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that wraps an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enum value, or the logical combination of multiple enum values, that indicate the restrictions the asset uses when resolving references to external media data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some assets can contain references to media data stored outside the asset’s container file, for example in another file. Use this key to specify the policy to use when the asset encounters these references. If an asset contains one or more references to a type forbidden by the reference restriction, loading of asset properties fails, and you can’t use this asset with other AVFoundation objects, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession": {
      "abstract": [
        {
          "text": "An object that exports assets in a format that you specify using an export preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportSession",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions": {
      "abstract": [
        {
          "text": "Restrictions to use when resolving references to external media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReferenceRestrictions"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReferenceRestrictions",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreferencerestrictions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system can make network requests on behalf of the asset when connected to a cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsCellularAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsCellularAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsCellularAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowscellularaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system allows network requests on behalf of this asset to use the constrained interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsConstrainedNetworkAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowsconstrainednetworkaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system allows network requests on behalf of this asset to use the expensive interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetAllowsExpensiveNetworkAccessKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetallowsexpensivenetworkaccesskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey": {
      "abstract": [
        {
          "text": "The HTTP cookies that a URL asset may send with HTTP requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPCookiesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPCookiesKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetHTTPCookiesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassethttpcookieskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey": {
      "abstract": [
        {
          "text": "A key that specifies the user agent of requests that an asset makes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPUserAgentKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetHTTPUserAgentKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetHTTPUserAgentKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassethttpuseragentkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey": {
      "abstract": [
        {
          "text": "A key that specifies the MIME type to use to identify the format of a media resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetOverrideMIMETypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetOverrideMIMETypeKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetOverrideMIMETypeKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetoverridemimetypekey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the asset should provide accurate duration and precise random access by time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetPreferPreciseDurationAndTimingKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetpreferprecisedurationandtimingkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey": {
      "abstract": [
        {
          "text": "Specifies a UUID to set as the session identifier for HTTP requests that the asset makes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetPrimarySessionIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetPrimarySessionIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetPrimarySessionIdentifierKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetprimarysessionidentifierkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey": {
      "abstract": [
        {
          "text": "A value that represents the restrictions used by the asset when resolving references to external media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetReferenceRestrictionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetReferenceRestrictionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetReferenceRestrictionsKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetReferenceRestrictionsKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetreferencerestrictionskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system parses and resolves alias data references in the asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetShouldSupportAliasDataReferencesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlassetshouldsupportaliasdatareferenceskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey": {
      "abstract": [
        {
          "text": "A value that specifies the attribution of the URLs that this asset requests.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAssetURLRequestAttributionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAssetURLRequestAttributionKey"
        }
      ],
      "role": "symbol",
      "title": "AVURLAssetURLRequestAttributionKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasseturlrequestattributionkey"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey"
      ],
      "title": "Options"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVURLAssetReferenceRestrictionsKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetReferenceRestrictionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReferenceRestrictions"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsCellularAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsConstrainedNetworkAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetAllowsExpensiveNetworkAccessKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPCookiesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetHTTPUserAgentKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetOverrideMIMETypeKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPreferPreciseDurationAndTimingKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetPrimarySessionIdentifierKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetShouldSupportAliasDataReferencesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAssetURLRequestAttributionKey"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVURLAssetReferenceRestrictionsKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPUserAgentKey/title",
          "value": "AVURLAssetHTTPUserAgentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPUserAgentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetHTTPUserAgentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPCookiesKey/title",
          "value": "AVURLAssetHTTPCookiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetHTTPCookiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetHTTPCookiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsExpensiveNetworkAccessKey/title",
          "value": "AVURLAssetAllowsExpensiveNetworkAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsExpensiveNetworkAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsExpensiveNetworkAccessKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/title",
          "value": "AVAssetReferenceRestrictions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReferenceRestrictions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReferenceRestrictions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/title",
          "value": "AVAssetExportSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetURLRequestAttributionKey/title",
          "value": "AVURLAssetURLRequestAttributionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetURLRequestAttributionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetURLRequestAttributionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title",
          "value": "AVPlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetReferenceRestrictionsKey/title",
          "value": "AVURLAssetReferenceRestrictionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetReferenceRestrictionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetReferenceRestrictionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetOverrideMIMETypeKey/title",
          "value": "AVURLAssetOverrideMIMETypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetOverrideMIMETypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetOverrideMIMETypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsConstrainedNetworkAccessKey/title",
          "value": "AVURLAssetAllowsConstrainedNetworkAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsConstrainedNetworkAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsConstrainedNetworkAccessKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetShouldSupportAliasDataReferencesKey/title",
          "value": "AVURLAssetShouldSupportAliasDataReferencesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetShouldSupportAliasDataReferencesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetShouldSupportAliasDataReferencesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPrimarySessionIdentifierKey/title",
          "value": "AVURLAssetPrimarySessionIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPrimarySessionIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetPrimarySessionIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPreferPreciseDurationAndTimingKey/title",
          "value": "AVURLAssetPreferPreciseDurationAndTimingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetPreferPreciseDurationAndTimingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetPreferPreciseDurationAndTimingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsCellularAccessKey/title",
          "value": "AVURLAssetAllowsCellularAccessKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAssetAllowsCellularAccessKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAssetAllowsCellularAccessKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avurlassetreferencerestrictionskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avurlassetreferencerestrictionskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
