{
  "abstract": [
    {
      "text": "A main-level 3.0 profile.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main30"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVVideoProfileLevelH264Main30",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVVideoProfileLevelH264Main30"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVVideoProfileLevelH264Main30"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVVideoProfileLevelH264Main30"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main30"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline30": {
      "abstract": [
        {
          "text": "A baseline-level 3.0 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline30"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Baseline30",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264baseline30"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline31": {
      "abstract": [
        {
          "text": "A baseline-level 3.1 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline31"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline31",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline31"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Baseline31",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264baseline31"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline41": {
      "abstract": [
        {
          "text": "A baseline-level 4.1 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline41"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline41",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Baseline41"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Baseline41",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264baseline41"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264BaselineAutoLevel": {
      "abstract": [
        {
          "text": "A baseline auto level profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264BaselineAutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264BaselineAutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264BaselineAutoLevel"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264BaselineAutoLevel",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264baselineautolevel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High40": {
      "abstract": [
        {
          "text": "A high-level 4.0 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264High40"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High40",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264High40"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264High40",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264high40"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High41": {
      "abstract": [
        {
          "text": "A high-level 4.1 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264High41"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High41",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264High41"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264High41",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264high41"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264HighAutoLevel": {
      "abstract": [
        {
          "text": "A high profile auto level profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264HighAutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264HighAutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264HighAutoLevel"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264HighAutoLevel",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264highautolevel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main30": {
      "abstract": [
        {
          "text": "A main-level 3.0 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main30"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main30",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main30"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Main30",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264main30"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main31": {
      "abstract": [
        {
          "text": "A main-level 3.1 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main31"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main31",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main31"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Main31",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264main31"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main32": {
      "abstract": [
        {
          "text": "A main-level 3.2 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main32"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main32"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Main32",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264main32"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main41": {
      "abstract": [
        {
          "text": "A main-level 4.1 profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main41"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main41",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264Main41"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264Main41",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264main41"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264MainAutoLevel": {
      "abstract": [
        {
          "text": "A main profile auto level profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264MainAutoLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264MainAutoLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelH264MainAutoLevel"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelH264MainAutoLevel",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelh264mainautolevel"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelKey": {
      "abstract": [
        {
          "text": "A key to access the video profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoProfileLevelKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoProfileLevelKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoprofilelevelkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Profile-level",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High40",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High41",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main31",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main32",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main41",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline30",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline31",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline41",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264HighAutoLevel",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264MainAutoLevel",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264BaselineAutoLevel"
      ],
      "title": "Profile level"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVVideoProfileLevelH264Main30"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Profile-level",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High40",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264High41",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main31",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main32",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Main41",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline30",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline31",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264Baseline41",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264HighAutoLevel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264MainAutoLevel",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoProfileLevelH264BaselineAutoLevel"
              ],
              "title": "Profile level"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVVideoProfileLevelH264Main30"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline31/title",
          "value": "AVVideoProfileLevelH264Baseline31"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline31/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Baseline31"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelKey/title",
          "value": "AVVideoProfileLevelKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264MainAutoLevel/title",
          "value": "AVVideoProfileLevelH264MainAutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264MainAutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264MainAutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264High40/title",
          "value": "AVVideoProfileLevelH264High40"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264High40/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264High40"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main32/title",
          "value": "AVVideoProfileLevelH264Main32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline41/title",
          "value": "AVVideoProfileLevelH264Baseline41"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline41/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Baseline41"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main31/title",
          "value": "AVVideoProfileLevelH264Main31"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main31/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main31"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main41/title",
          "value": "AVVideoProfileLevelH264Main41"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main41/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main41"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264BaselineAutoLevel/title",
          "value": "AVVideoProfileLevelH264BaselineAutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264BaselineAutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264BaselineAutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main30/title",
          "value": "AVVideoProfileLevelH264Main30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Main30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Main30"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264HighAutoLevel/title",
          "value": "AVVideoProfileLevelH264HighAutoLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264HighAutoLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264HighAutoLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264High41/title",
          "value": "AVVideoProfileLevelH264High41"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264High41/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264High41"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline30/title",
          "value": "AVVideoProfileLevelH264Baseline30"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoProfileLevelH264Baseline30/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoProfileLevelH264Baseline30"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avvideoprofilelevelh264main30"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avvideoprofilelevelh264main30"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
