{
  "abstract": [
    {
      "text": "A set of constants that describe the codecs the system supports for video capture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AVVideoCodecType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVVideoCodecType"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVVideoCodecType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVVideoCodecType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVVideoCodecType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats"
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes422": {
      "abstract": [
        {
          "text": "A key to access the name of the Apple ProRes422 codec used to encode the video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecAppleProRes422"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes422",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecAppleProRes422"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecAppleProRes422",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodecappleprores422"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes4444": {
      "abstract": [
        {
          "text": "A key to access the name of the Apple ProRes4444 codec used to encode the video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecAppleProRes4444"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes4444",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecAppleProRes4444"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecAppleProRes4444",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodecappleprores4444"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecH264": {
      "abstract": [
        {
          "text": "A key to access the name of the H.264 codec for compressing video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecH264"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecH264",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecH264"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecH264",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodech264"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecHEVC": {
      "abstract": [
        {
          "text": "A key to access the name of the HEVC codec used to encode the video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecHEVC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecHEVC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecHEVC"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecHEVC",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodechevc"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecJPEG": {
      "abstract": [
        {
          "text": "A key to access the name of the JPEG codec for compressing video.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecJPEG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecJPEG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecJPEG"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecJPEG",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodecjpeg"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey": {
      "abstract": [
        {
          "text": "A key to access the name of the codec for compressing video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodeckey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType": {
      "abstract": [
        {
          "text": "A set of constants that describe the codecs the system supports for video capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecType"
        }
      ],
      "role": "symbol",
      "title": "AVVideoCodecType",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/JPEGXL": {
      "abstract": [
        {
          "text": "The JPEG XL video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JPEGXL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/JPEGXL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeJPEGXL"
        }
      ],
      "role": "symbol",
      "title": "JPEGXL",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/jpegxl"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/appleProRes4444XQ": {
      "abstract": [
        {
          "text": "The Apple ProRes 4444 XQ video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appleProRes4444XQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/appleProRes4444XQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes4444XQ"
        }
      ],
      "role": "symbol",
      "title": "appleProRes4444XQ",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/appleprores4444xq"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/h264": {
      "abstract": [
        {
          "text": "The H.264 video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "h264"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/h264",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeH264"
        }
      ],
      "role": "symbol",
      "title": "h264",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/h264"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevc": {
      "abstract": [
        {
          "text": "The HEVC video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeHEVC"
        }
      ],
      "role": "symbol",
      "title": "hevc",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/hevc"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevcWithAlpha": {
      "abstract": [
        {
          "text": "The HEVC video codec that supports an alpha channel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hevcWithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevcWithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeHEVCWithAlpha"
        }
      ],
      "role": "symbol",
      "title": "hevcWithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/hevcwithalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a codec type from its raw string value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/init(rawvalue:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/jpeg": {
      "abstract": [
        {
          "text": "The JPEG video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jpeg"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/jpeg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeJPEG"
        }
      ],
      "role": "symbol",
      "title": "jpeg",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/jpeg"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422": {
      "abstract": [
        {
          "text": "The Apple ProRes 422 video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proRes422"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes422"
        }
      ],
      "role": "symbol",
      "title": "proRes422",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/prores422"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422HQ": {
      "abstract": [
        {
          "text": "The Apple ProRes 422 HQ video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proRes422HQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422HQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes422HQ"
        }
      ],
      "role": "symbol",
      "title": "proRes422HQ",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/prores422hq"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422LT": {
      "abstract": [
        {
          "text": "The Apple ProRes 422 LT video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proRes422LT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422LT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes422LT"
        }
      ],
      "role": "symbol",
      "title": "proRes422LT",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/prores422lt"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422Proxy": {
      "abstract": [
        {
          "text": "The Apple ProRes 422 Proxy video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proRes422Proxy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422Proxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes422Proxy"
        }
      ],
      "role": "symbol",
      "title": "proRes422Proxy",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/prores422proxy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes4444": {
      "abstract": [
        {
          "text": "The Apple ProRes 4444 video codec.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proRes4444"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVVideoCodecType",
          "text": "AVVideoCodecType"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes4444",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoCodecTypeAppleProRes4444"
        }
      ],
      "role": "symbol",
      "title": "proRes4444",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocodectype/prores4444"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats": {
      "abstract": [
        {
          "text": "Change the default format for capturing movie files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats",
      "kind": "article",
      "role": "article",
      "title": "Recording movies in alternative formats",
      "type": "topic",
      "url": "/documentation/avfoundation/recording-movies-in-alternative-formats"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-codecs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey"
      ],
      "title": "Video codecs"
    }
  ],
  "topicSections": [
    {
      "anchor": "Video-codecs",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/h264",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevc",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevcWithAlpha",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/jpeg",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422LT",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422HQ",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422Proxy",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes4444",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/appleProRes4444XQ"
      ],
      "title": "Video codecs"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecH264",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecHEVC",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecJPEG",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes422",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes4444"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/JPEGXL"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Video-codecs",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/h264",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevc",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/hevcWithAlpha",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/jpeg",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422LT",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422HQ",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes422Proxy",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/proRes4444",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/appleProRes4444XQ"
              ],
              "title": "Video codecs"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecH264",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecHEVC",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecJPEG",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes422",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecAppleProRes4444"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType/JPEGXL"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Video-codecs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey"
              ],
              "title": "Video codecs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVVideoCodecType"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/title",
          "value": "AVVideoCodecType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecJPEG/title",
          "value": "AVVideoCodecJPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecJPEG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecJPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecHEVC/title",
          "value": "AVVideoCodecHEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecHEVC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecHEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422HQ/title",
          "value": "AVVideoCodecTypeAppleProRes422HQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422HQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes422HQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecAppleProRes4444/title",
          "value": "AVVideoCodecAppleProRes4444"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecAppleProRes4444/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecAppleProRes4444"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecKey/title",
          "value": "AVVideoCodecKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422Proxy/title",
          "value": "AVVideoCodecTypeAppleProRes422Proxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422Proxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes422Proxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1appleProRes4444XQ/title",
          "value": "AVVideoCodecTypeAppleProRes4444XQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1appleProRes4444XQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes4444XQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecAppleProRes422/title",
          "value": "AVVideoCodecAppleProRes422"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecAppleProRes422/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecAppleProRes422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1JPEGXL/title",
          "value": "AVVideoCodecTypeJPEGXL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1JPEGXL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeJPEGXL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422/title",
          "value": "AVVideoCodecTypeAppleProRes422"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes422"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1hevc/title",
          "value": "AVVideoCodecTypeHEVC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1hevc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeHEVC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecH264/title",
          "value": "AVVideoCodecH264"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecH264/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecH264"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes4444/title",
          "value": "AVVideoCodecTypeAppleProRes4444"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes4444/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes4444"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422LT/title",
          "value": "AVVideoCodecTypeAppleProRes422LT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1proRes422LT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeAppleProRes422LT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1hevcWithAlpha/title",
          "value": "AVVideoCodecTypeHEVCWithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1hevcWithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeHEVCWithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1jpeg/title",
          "value": "AVVideoCodecTypeJPEG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1jpeg/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeJPEG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1h264/title",
          "value": "AVVideoCodecTypeH264"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType~1h264/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoCodecTypeH264"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avvideocodectype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avvideocodectype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
