{
  "abstract": [
    {
      "text": "The transfer function for the SMPTE 2084 color space.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_ST_2084_PQ"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@AVVideoTransferFunction_SMPTE_ST_2084_PQ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoAllowWideColorKey": {
      "abstract": [
        {
          "text": "The key for a dictionary that indicates whether the client can process wide color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoAllowWideColorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoAllowWideColorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoAllowWideColorKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoAllowWideColorKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoallowwidecolorkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimariesKey": {
      "abstract": [
        {
          "text": "The key to identify color primaries in a color properties dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimariesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimariesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimariesKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimariesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimarieskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_EBU_3213": {
      "abstract": [
        {
          "text": "The color primary is in the EBU Tech. 3213 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_EBU_3213"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_EBU_3213",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_EBU_3213"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimaries_EBU_3213",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimaries_ebu_3213"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_2020": {
      "abstract": [
        {
          "text": "The color primary is in the ITU_R BT.2020 color space for ultra high definition television.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_ITU_R_2020"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_2020",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_ITU_R_2020"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimaries_ITU_R_2020",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimaries_itu_r_2020"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_709_2": {
      "abstract": [
        {
          "text": "The color primary is in the ITU_R BT.709 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimaries_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimaries_itu_r_709_2"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_P3_D65": {
      "abstract": [
        {
          "text": "The color primary uses the DCI-P3 D65 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_P3_D65"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_P3_D65",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_P3_D65"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimaries_P3_D65",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimaries_p3_d65"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_SMPTE_C": {
      "abstract": [
        {
          "text": "The color primary uses the SMPTE C color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_SMPTE_C"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_SMPTE_C",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPrimaries_SMPTE_C"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPrimaries_SMPTE_C",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorprimaries_smpte_c"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPropertiesKey": {
      "abstract": [
        {
          "text": "The key for a dictionary that contains properties specifying video color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoColorPropertiesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPropertiesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoColorPropertiesKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoColorPropertiesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideocolorpropertieskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunctionKey": {
      "abstract": [
        {
          "text": "The key to identify the transfer function in a color properties dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunctionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunctionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunctionKey"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunctionKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunctionkey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_IEC_sRGB": {
      "abstract": [
        {
          "text": "The transfer function for the IEC sRGB color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_IEC_sRGB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_IEC_sRGB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_IEC_sRGB"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_IEC_sRGB",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_iec_srgb"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_2100_HLG": {
      "abstract": [
        {
          "text": "The transfer function for the ITU_R BT.2100 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_ITU_R_2100_HLG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_2100_HLG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_ITU_R_2100_HLG"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_ITU_R_2100_HLG",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_itu_r_2100_hlg"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_709_2": {
      "abstract": [
        {
          "text": "The transfer function for the ITU_R BT.709 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_ITU_R_709_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_709_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_ITU_R_709_2"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_ITU_R_709_2",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_itu_r_709_2"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_Linear": {
      "abstract": [
        {
          "text": "The transfer function for the linear color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_Linear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_Linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_Linear"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_Linear",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_linear"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_240M_1995": {
      "abstract": [
        {
          "text": "The transfer function for the SMPTE 240M color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_SMPTE_240M_1995"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_240M_1995",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_SMPTE_240M_1995"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_SMPTE_240M_1995",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_smpte_240m_1995"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_ST_2084_PQ": {
      "abstract": [
        {
          "text": "The transfer function for the SMPTE 2084 color space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_ST_2084_PQ",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
        }
      ],
      "role": "symbol",
      "title": "AVVideoTransferFunction_SMPTE_ST_2084_PQ",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideotransferfunction_smpte_st_2084_pq"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/setting-color-properties-for-a-specific-resolution": {
      "abstract": [
        {
          "text": "Choose the proper color property keys for the desired color range.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-color-properties-for-a-specific-resolution",
      "kind": "article",
      "role": "article",
      "title": "Setting Color Properties for a Specific Resolution",
      "type": "topic",
      "url": "/documentation/avfoundation/setting-color-properties-for-a-specific-resolution"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Color-properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/setting-color-properties-for-a-specific-resolution",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoAllowWideColorKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimariesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_EBU_3213",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_2020",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_709_2",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_P3_D65",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_SMPTE_C",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPropertiesKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunctionKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_IEC_sRGB",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_2100_HLG",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_709_2",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_Linear",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_240M_1995"
      ],
      "title": "Color properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfoundation/documentation/AVFoundation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Color-properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/setting-color-properties-for-a-specific-resolution",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoAllowWideColorKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimariesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_EBU_3213",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_2020",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_ITU_R_709_2",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_P3_D65",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPrimaries_SMPTE_C",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoColorPropertiesKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunctionKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_IEC_sRGB",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_2100_HLG",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_ITU_R_709_2",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_Linear",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoTransferFunction_SMPTE_240M_1995"
              ],
              "title": "Color properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_SMPTE_ST_2084_PQ/title",
          "value": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_SMPTE_ST_2084_PQ/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_SMPTE_ST_2084_PQ"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoAllowWideColorKey/title",
          "value": "AVVideoAllowWideColorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoAllowWideColorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoAllowWideColorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunctionKey/title",
          "value": "AVVideoTransferFunctionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunctionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunctionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_EBU_3213/title",
          "value": "AVVideoColorPrimaries_EBU_3213"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_EBU_3213/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimaries_EBU_3213"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_P3_D65/title",
          "value": "AVVideoColorPrimaries_P3_D65"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_P3_D65/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimaries_P3_D65"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimariesKey/title",
          "value": "AVVideoColorPrimariesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimariesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimariesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_ITU_R_709_2/title",
          "value": "AVVideoTransferFunction_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_ITU_R_2100_HLG/title",
          "value": "AVVideoTransferFunction_ITU_R_2100_HLG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_ITU_R_2100_HLG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_ITU_R_2100_HLG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_IEC_sRGB/title",
          "value": "AVVideoTransferFunction_IEC_sRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_IEC_sRGB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_IEC_sRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_Linear/title",
          "value": "AVVideoTransferFunction_Linear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_Linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_Linear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPropertiesKey/title",
          "value": "AVVideoColorPropertiesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPropertiesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPropertiesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_ITU_R_2020/title",
          "value": "AVVideoColorPrimaries_ITU_R_2020"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_ITU_R_2020/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimaries_ITU_R_2020"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_SMPTE_C/title",
          "value": "AVVideoColorPrimaries_SMPTE_C"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_SMPTE_C/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimaries_SMPTE_C"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_ITU_R_709_2/title",
          "value": "AVVideoColorPrimaries_ITU_R_709_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoColorPrimaries_ITU_R_709_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoColorPrimaries_ITU_R_709_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_SMPTE_240M_1995/title",
          "value": "AVVideoTransferFunction_SMPTE_240M_1995"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoTransferFunction_SMPTE_240M_1995/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoTransferFunction_SMPTE_240M_1995"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avvideotransferfunction_smpte_st_2084_pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/avvideotransferfunction_smpte_st_2084_pq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
