{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/cleanAperture","doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/encodedPixels","doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/productionAperture"],"title":"Aperture Modes","anchor":"Aperture-Modes"},{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"}],"abstract":[{"text":"A value that describes how a video is scaled or cropped.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false},{"name":"watchOS","beta":false,"deprecated":false,"unavailable":false}],"navigatorTitle":[{"kind":"identifier","text":"AVVideoApertureMode"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoApertureMode"}],"role":"symbol","modules":[{"name":"AVFoundation"}],"externalID":"c:@T@AVVideoApertureMode","title":"AVVideoApertureMode","symbolKind":"struct","roleHeading":"Structure"},"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode","interfaceLanguage":"swift"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/presentationSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/preferredMaximumResolution","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoApertureMode"],"title":"Configuring Presentation","generated":true,"anchor":"Configuring-Presentation"}],"variants":[{"paths":["/documentation/avfoundation/avvideoaperturemode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfoundation/avvideoaperturemode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoApertureMode"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.externally.resolved.symbol/s:s8SendableP":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"type":"topic","title":"Sendable","url":"/documentation/Swift/Sendable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/init(rawValue:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a video aperture mode with a string."}],"type":"topic","title":"init(rawValue:)","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/init(rawValue:)","kind":"symbol","url":"/documentation/avfoundation/avvideoaperturemode/init(rawvalue:)"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/encodedPixels":{"navigatorTitle":[{"kind":"identifier","text":"AVVideoApertureModeEncodedPixels"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedPixels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVVideoApertureMode","preciseIdentifier":"c:@T@AVVideoApertureMode"}],"abstract":[{"type":"text","text":"The encoded dimensions of the image description are displayed."}],"type":"topic","title":"encodedPixels","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/encodedPixels","kind":"symbol","url":"/documentation/avfoundation/avvideoaperturemode/encodedpixels"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/productionAperture":{"navigatorTitle":[{"kind":"identifier","text":"AVVideoApertureModeProductionAperture"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"productionAperture"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@AVVideoApertureMode","kind":"typeIdentifier","text":"AVVideoApertureMode"}],"abstract":[{"type":"text","text":"The pixel aspect ratio will be applied."}],"type":"topic","title":"productionAperture","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/productionAperture","kind":"symbol","url":"/documentation/avfoundation/avvideoaperturemode/productionaperture"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoApertureMode":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoApertureMode","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoApertureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVVideoApertureMode","text":"AVVideoApertureMode"}],"url":"/documentation/avfoundation/avplayeritem/videoaperturemode","type":"topic","abstract":[{"type":"text","text":"The video aperture mode to apply during playback."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"videoApertureMode"}],"title":"videoApertureMode"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/preferredMaximumResolution":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/preferredMaximumResolution","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredMaximumResolution"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"abstract":[{"type":"text","text":"The desired maximum resolution of a video that is to be downloaded."}],"type":"topic","title":"preferredMaximumResolution","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"preferredMaximumResolution"}],"role":"symbol","url":"/documentation/avfoundation/avplayeritem/preferredmaximumresolution"},"doc://com.externally.resolved.symbol/s:SQ":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"type":"topic","title":"Equatable","url":"/documentation/Swift/Equatable","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode":{"url":"/documentation/avfoundation/avvideoaperturemode","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoApertureMode"}],"type":"topic","role":"symbol","title":"AVVideoApertureMode","abstract":[{"type":"text","text":"A value that describes how a video is scaled or cropped."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode","navigatorTitle":[{"text":"AVVideoApertureMode","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/cleanAperture":{"navigatorTitle":[{"text":"AVVideoApertureModeCleanAperture","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cleanAperture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVVideoApertureMode","preciseIdentifier":"c:@T@AVVideoApertureMode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The pixel aspect ratio and clean aperture will be applied."}],"type":"topic","title":"cleanAperture","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/cleanAperture","kind":"symbol","url":"/documentation/avfoundation/avvideoaperturemode/cleanaperture"},"doc://com.externally.resolved.symbol/s:SY":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RawRepresentable","kind":"identifier"},{"text":"<","kind":"text"},{"text":"RawValue","kind":"typeIdentifier","preciseIdentifier":"s:SY8RawValueQa"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","title":"RawRepresentable","url":"/documentation/Swift/RawRepresentable","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"Equatable","kind":"typeIdentifier","preciseIdentifier":"s:SQ"}],"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"type":"topic","title":"Hashable","url":"/documentation/Swift/Hashable","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/presentationSize":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size at which the visual portion of the item is presented by the player."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"presentationSize"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/presentationSize","title":"presentationSize","kind":"symbol","url":"/documentation/avfoundation/avplayeritem/presentationsize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"deprecated":false,"name":"visionOS","unavailable":false},{"beta":false,"deprecated":false,"name":"watchOS","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Alias","op":"replace"},{"path":"/metadata/title","value":"AVVideoApertureMode","op":"replace"},{"path":"/metadata/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"AVVideoApertureMode","kind":"identifier"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"AVVideoApertureMode"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Aperture Modes","anchor":"Aperture-Modes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/cleanAperture","doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/encodedPixels","doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoApertureMode/productionAperture"]}]},{"op":"replace","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/presentationSize","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/preferredMaximumResolution","doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/videoApertureMode"],"anchor":"Configuring-Presentation","generated":true,"title":"Configuring Presentation"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"AVVideoApertureMode"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"AVVideoApertureModeEncodedPixels","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1encodedPixels/title"},{"value":[{"kind":"identifier","text":"AVVideoApertureModeEncodedPixels"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1encodedPixels/fragments"},{"value":"AVVideoApertureModeProductionAperture","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1productionAperture/title"},{"value":[{"text":"AVVideoApertureModeProductionAperture","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1productionAperture/fragments"},{"value":"videoApertureMode","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1videoApertureMode/title"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1videoApertureMode/fragments","value":[{"kind":"identifier","text":"videoApertureMode"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1preferredMaximumResolution/title","value":"preferredMaximumResolution"},{"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1preferredMaximumResolution/fragments","value":[{"text":"preferredMaximumResolution","kind":"identifier"}]},{"value":"AVVideoApertureMode","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode/title","op":"replace"},{"value":[{"text":"AVVideoApertureMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AVVideoApertureMode"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode/navigatorTitle","op":"replace"},{"value":"AVVideoApertureModeCleanAperture","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1cleanAperture/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVVideoApertureModeCleanAperture"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoApertureMode~1cleanAperture/fragments","op":"replace"},{"value":"presentationSize","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1presentationSize/title","op":"replace"},{"value":[{"text":"presentationSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1presentationSize/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}