{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"A key to access the name of the codec for compressing video."}],"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType"],"title":"Video codecs","anchor":"Video-codecs","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoCodecKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"mentions":["doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats"],"kind":"mentions"},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The value for this key is an instance of ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nsstring","isActive":true},{"text":", equivalent to ","type":"text"},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMVideoCodecType","isActive":true},{"text":". Use this key to set the video compression format to H.264, HEVC, or JPEG, depending on the video codec types available in ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput","isActive":true},{"text":". Check available video codec types by consulting ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/availableVideoCodecTypes","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/avvideocodeckey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/avvideocodeckey"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"AVVideoCodecKey"}],"role":"symbol","title":"AVVideoCodecKey","roleHeading":"Global Variable","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoCodecKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"AVFoundation"}],"symbolKind":"var","externalID":"c:@AVVideoCodecKey","platforms":[{"introducedAt":"4.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"4.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"10.7","beta":false,"name":"macOS","deprecated":false,"unavailable":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false}]},"references":{"doc://com.externally.resolved.symbol/s:SS":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"type":"topic","title":"String","url":"/documentation/Swift/String","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/availableVideoCodecTypes":{"url":"/documentation/avfoundation/avcapturemoviefileoutput/availablevideocodectypes","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput/availableVideoCodecTypes","navigatorTitle":[{"kind":"identifier","text":"availableVideoCodecTypes"}],"abstract":[{"type":"text","text":"The video codecs types the output supports for recording movie files."}],"title":"availableVideoCodecTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"availableVideoCodecTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@T@AVVideoCodecType","kind":"typeIdentifier","text":"AVVideoCodecType"},{"kind":"text","text":"]"}],"type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVVideoCodecKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"AVVideoCodecKey","kind":"identifier"}],"abstract":[{"type":"text","text":"A key to access the name of the codec for compressing video."}],"type":"topic","title":"AVVideoCodecKey","url":"/documentation/avfoundation/avvideocodeckey","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats":{"title":"Recording movies in alternative formats","kind":"article","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/recording-movies-in-alternative-formats","url":"/documentation/avfoundation/recording-movies-in-alternative-formats","abstract":[{"text":"Change the default format for capturing movie files.","type":"text"}],"role":"article","type":"topic"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureMovieFileOutput","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureMovieFileOutput","kind":"identifier"}],"navigatorTitle":[{"text":"AVCaptureMovieFileOutput","kind":"identifier"}],"abstract":[{"type":"text","text":"A capture output that records video and audio to a QuickTime movie file."}],"type":"topic","title":"AVCaptureMovieFileOutput","url":"/documentation/avfoundation/avcapturemoviefileoutput","kind":"symbol"},"doc://com.apple.documentation/documentation/CoreMedia/CMVideoCodecType":{"identifier":"doc://com.apple.documentation/documentation/CoreMedia/CMVideoCodecType","url":"/documentation/CoreMedia/CMVideoCodecType","title":"CMVideoCodecType","abstract":[{"text":"A video codec type.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMVideoCodecType"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:@T@FourCharCode","kind":"typeIdentifier","text":"FourCharCode"}],"role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVVideoCodecType","kind":"identifier"}],"navigatorTitle":[{"text":"AVVideoCodecType","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of constants that describe the codecs the system supports for video capture."}],"type":"topic","title":"AVVideoCodecType","url":"/documentation/avfoundation/avvideocodectype","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nsstring":{"url":"/documentation/foundation/nsstring","identifier":"doc://com.apple.documentation/documentation/foundation/nsstring","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"type":"topic","title":"NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","introducedAt":"4.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"4.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false},{"unavailable":false,"name":"macOS","introducedAt":"10.7","deprecated":false,"beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false,"name":"visionOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Global Variable","path":"/metadata/roleHeading","op":"replace"},{"value":"AVVideoCodecKey","path":"/metadata/title","op":"replace"},{"value":"var","path":"/metadata/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"AVVideoCodecKey","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"path":"/seeAlsoSections","op":"replace","value":[{"title":"Video codecs","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoCodecType"],"anchor":"Video-codecs","generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVVideoCodecKey"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput~1availableVideoCodecTypes/title","op":"replace","value":"availableVideoCodecTypes"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput~1availableVideoCodecTypes/fragments","op":"replace","value":[{"text":"availableVideoCodecTypes","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecKey/title","op":"replace","value":"AVVideoCodecKey"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecKey/fragments","op":"replace","value":[{"text":"AVVideoCodecKey","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/title","op":"replace","value":"AVCaptureMovieFileOutput"},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/fragments","op":"replace","value":[{"kind":"identifier","text":"AVCaptureMovieFileOutput"}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureMovieFileOutput/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVCaptureMovieFileOutput"}]},{"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreMedia~1CMVideoCodecType/fragments","op":"replace","value":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@T@FourCharCode","kind":"typeIdentifier","text":"FourCharCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"CMVideoCodecType"},{"kind":"text","text":";"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","op":"replace","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]},{"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/title","op":"replace","value":"AVVideoCodecType"},{"op":"replace","value":[{"kind":"identifier","text":"AVVideoCodecType"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVVideoCodecType"}],"path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoCodecType/navigatorTitle"},{"op":"replace","value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}