{
  "abstract": [
    {
      "text": "An object that defines an inclusive range of zoom values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVZoomRange",
    "fragments": [
      {
        "kind": "identifier",
        "text": "AVZoomRange"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVZoomRange"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AVZoomRange"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVZoomRange"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoMaxZoomFactor": {
      "abstract": [
        {
          "text": "A maximum zoom factor the format allows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoMaxZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoMaxZoomFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoMaxZoomFactor"
        }
      ],
      "role": "symbol",
      "title": "videoMaxZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/videomaxzoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoZoomFactorUpscaleThreshold": {
      "abstract": [
        {
          "text": "A threshold at which the system upscales pixel data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoZoomFactorUpscaleThreshold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoZoomFactorUpscaleThreshold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoZoomFactorUpscaleThreshold"
        }
      ],
      "role": "symbol",
      "title": "videoZoomFactorUpscaleThreshold",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/videozoomfactorupscalethreshold"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the format supports zoom factors outside the range supported for depth delivery.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported"
        }
      ],
      "role": "symbol",
      "title": "zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/format/zoomfactorsoutsideofvideozoomrangesfordepthdeliverysupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/secondaryNativeResolutionZoomFactors": {
      "abstract": [
        {
          "text": "The zoom factors at which this device transitions to secondary native resolution modes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryNativeResolutionZoomFactors"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/secondaryNativeResolutionZoomFactors",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryNativeResolutionZoomFactors",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceformat/secondarynativeresolutionzoomfactors"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/supportedVideoZoomRangesForDepthDataDelivery": {
      "abstract": [
        {
          "text": "The zoom ranges that support the delivery of depth data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "supportedVideoZoomRangesForDepthDataDelivery"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/supportedVideoZoomRangesForDepthDataDelivery",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportedVideoZoomRangesForDepthDataDelivery",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceformat/supportedvideozoomrangesfordepthdatadelivery"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedVideoZoomRange": {
      "abstract": [
        {
          "text": "The system’s recommended zoom range for this device format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "systemRecommendedVideoZoomRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedVideoZoomRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "systemRecommendedVideoZoomRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceformat/systemrecommendedvideozoomrange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange": {
      "abstract": [
        {
          "text": "An object that defines an inclusive range of zoom values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVZoomRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVZoomRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avzoomrange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/containsZoomFactor:": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified zoom factor exists in the range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "containsZoomFactor:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/containsZoomFactor:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containsZoomFactor:"
        }
      ],
      "role": "symbol",
      "title": "containsZoomFactor:",
      "type": "topic",
      "url": "/documentation/avfoundation/avzoomrange/containszoomfactor:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/maxZoomFactor": {
      "abstract": [
        {
          "text": "The range’s maximum zoom factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "maxZoomFactor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/maxZoomFactor",
      "kind": "symbol",
      "role": "symbol",
      "title": "maxZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avzoomrange/maxzoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/minZoomFactor": {
      "abstract": [
        {
          "text": "The range’s minimum zoom factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "minZoomFactor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/minZoomFactor",
      "kind": "symbol",
      "role": "symbol",
      "title": "minZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avzoomrange/minzoomfactor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-Zoom-Capabilities",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/systemRecommendedVideoZoomRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoMaxZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/videoZoomFactorUpscaleThreshold",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/secondaryNativeResolutionZoomFactors",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceFormat/supportedVideoZoomRangesForDepthDataDelivery",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/Format/zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported"
      ],
      "title": "Determining Zoom Capabilities"
    }
  ],
  "topicSections": [
    {
      "anchor": "Inspecting-a-range",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/minZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/maxZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVZoomRange/containsZoomFactor:"
      ],
      "title": "Inspecting a range"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported/title",
          "value": "zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "zoomFactorsOutsideOfVideoZoomRangesForDepthDeliverySupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1videoMaxZoomFactor/title",
          "value": "videoMaxZoomFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1videoMaxZoomFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoMaxZoomFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1videoZoomFactorUpscaleThreshold/title",
          "value": "videoZoomFactorUpscaleThreshold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1Format~1videoZoomFactorUpscaleThreshold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoZoomFactorUpscaleThreshold"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/avzoomrange"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
