{"sections":[],"identifier":{"url":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-focus","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"Focus","role":"collectionGroup","modules":[{"name":"AVFoundation"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfoundation/documentation/AVFoundation","doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"]]},"topicSections":[{"anchor":"Configuring-Automatic-Focus","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum"],"title":"Configuring Automatic Focus"},{"anchor":"Setting-a-Focus-Point-of-Interest","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusPointOfInterestSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusPointOfInterest"],"title":"Setting a Focus Point of Interest"},{"anchor":"Monitoring-Focus-Changes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAdjustingFocus"],"title":"Monitoring Focus Changes"},{"anchor":"Setting-Focus-Manually","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isLockingFocusWithCustomLensPositionSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lensPosition","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/currentLensPosition","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setFocusModeLocked(lensPosition:completionHandler:)"],"title":"Setting Focus Manually"},{"anchor":"Inspecting-the-Focus-Distance","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minimumFocusDistance"],"title":"Inspecting the Focus Distance"}],"abstract":[{"text":"Configure the automatic focus behavior of a camera, or manually set its lens position.","type":"text"}],"kind":"article","seeAlsoSections":[{"anchor":"Configuring-Camera-Hardware","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-zoom"],"generated":true,"title":"Configuring Camera Hardware"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfoundation/capture-device-focus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfoundation/capture-device-focus"]}],"references":{"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoFocusRangeRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"AutoFocusRangeRestriction"}],"abstract":[{"type":"text","text":"Constants to specify the autofocus range of a capture device."}],"type":"topic","title":"AVCaptureDevice.AutoFocusRangeRestriction","url":"/documentation/avfoundation/avcapturedevice/autofocusrangerestriction-swift.enum","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/currentLensPosition":{"kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/currentlensposition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLensPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"type":"topic","role":"symbol","title":"currentLensPosition","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/currentLensPosition","abstract":[{"type":"text","text":"A constant that represents the current lens position."}],"navigatorTitle":[{"kind":"identifier","text":"AVCaptureLensPositionCurrent"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSmoothAutoFocusSupported"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"smoothAutoFocusSupported"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device supports smooth autofocus."}],"type":"topic","title":"isSmoothAutoFocusSupported","url":"/documentation/avfoundation/avcapturedevice/issmoothautofocussupported","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting":{"abstract":[{"text":"Configure the device flash, torch, and low light settings.","type":"text"}],"role":"collectionGroup","type":"topic","title":"Lighting","url":"/documentation/avfoundation/capture-device-lighting","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting","kind":"article"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"type":"topic","title":"Technologies","url":"/documentation/technologies","kind":"technologies"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance":{"role":"collectionGroup","kind":"article","title":"White Balance","url":"/documentation/avfoundation/capture-device-white-balance","abstract":[{"type":"text","text":"Configure the automatic white balance behavior of a camera, or manually control white balance settings."}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()":{"kind":"symbol","url":"/documentation/avfoundation/avcapturedevice/lockforconfiguration()","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()","title":"lockForConfiguration()","abstract":[{"text":"Requests exclusive access to configure device hardware properties.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lockForConfiguration","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"lockForConfiguration:"}],"role":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setFocusModeLocked(lensPosition:completionHandler:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setFocusModeLocked"},{"text":"(","kind":"text"},{"text":"lensPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@SA@CMTime","text":"CMTime","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","title":"setFocusModeLocked(lensPosition:completionHandler:)","url":"/documentation/avfoundation/avcapturedevice/setfocusmodelocked(lensposition:completionhandler:)","abstract":[{"type":"text","text":"Locks the lens position at the specified value, and sets the focus mode to a locked state."}],"type":"topic","navigatorTitle":[{"text":"setFocusModeLockedWithLensPosition:completionHandler:","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setFocusModeLocked(lensPosition:completionHandler:)"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"subjectAreaDidChangeNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A notification the system posts when a capture device detects a substantial change to the video subject area."}],"url":"/documentation/avfoundation/avcapturedevice/subjectareadidchangenotification","title":"subjectAreaDidChangeNotification","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification","navigatorTitle":[{"kind":"identifier","text":"AVCaptureDeviceSubjectAreaDidChangeNotification"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusPointOfInterest":{"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusPointOfInterest","kind":"symbol","role":"symbol","type":"topic","title":"focusPointOfInterest","abstract":[{"text":"The point of interest for focusing.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusPointOfInterest","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"focusPointOfInterest","kind":"identifier"}],"url":"/documentation/avfoundation/avcapturedevice/focuspointofinterest"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color":{"abstract":[{"text":"Manage HDR and color space settings for a device.","type":"text"}],"role":"collectionGroup","type":"topic","title":"Color","url":"/documentation/avfoundation/capture-device-color","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color","kind":"article"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lensPosition":{"abstract":[{"text":"The current focus position of the lens.","type":"text"}],"title":"lensPosition","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lensPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"url":"/documentation/avfoundation/avcapturedevice/lensposition","kind":"symbol","navigatorTitle":[{"text":"lensPosition","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lensPosition"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unlockForConfiguration"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Releases exclusive control over device hardware properties."}],"url":"/documentation/avfoundation/avcapturedevice/unlockforconfiguration()","title":"unlockForConfiguration()","role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()","navigatorTitle":[{"kind":"identifier","text":"unlockForConfiguration"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled":{"navigatorTitle":[{"text":"faceDrivenAutoFocusEnabled","kind":"identifier"}],"title":"isFaceDrivenAutoFocusEnabled","abstract":[{"text":"A Boolean value that indicates whether the device has face-driven autofocus enabled.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceDrivenAutoFocusEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/isfacedrivenautofocusenabled","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property":{"navigatorTitle":[{"text":"focusMode","kind":"identifier"}],"title":"focusMode","abstract":[{"text":"The capture device’s focus mode.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"FocusMode","preciseIdentifier":"c:@E@AVCaptureFocusMode","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/focusmode-swift.property","type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation":{"role":"collection","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation","abstract":[{"type":"text","text":"Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions."}],"type":"topic","title":"AVFoundation","url":"/documentation/avfoundation","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled":{"abstract":[{"text":"A Boolean value that indicates whether the device monitors the subject area for changes.","type":"text"}],"role":"symbol","type":"topic","title":"isSubjectAreaChangeMonitoringEnabled","url":"/documentation/avfoundation/avcapturedevice/issubjectareachangemonitoringenabled","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"subjectAreaChangeMonitoringEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSubjectAreaChangeMonitoringEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minimumFocusDistance":{"url":"/documentation/avfoundation/avcapturedevice/minimumfocusdistance","type":"topic","role":"symbol","title":"minimumFocusDistance","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minimumFocusDistance","abstract":[{"type":"text","text":"The capture device’s minimum focus distance in millimeters."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumFocusDistance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minimumFocusDistance","kind":"identifier"}]},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-zoom":{"title":"Zoom","url":"/documentation/avfoundation/capture-device-zoom","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-zoom","type":"topic","kind":"article","role":"collectionGroup","abstract":[{"type":"text","text":"Configure device zooming behavior and inspect hardware capabilities."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAutoFocusRangeRestrictionSupported"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"autoFocusRangeRestrictionSupported"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device supports focus range restrictions."}],"type":"topic","title":"isAutoFocusRangeRestrictionSupported","url":"/documentation/avfoundation/avcapturedevice/isautofocusrangerestrictionsupported","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusPointOfInterestSupported":{"title":"isFocusPointOfInterestSupported","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusPointOfInterestSupported","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFocusPointOfInterestSupported","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device supports a point of interest for focus."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"focusPointOfInterestSupported","kind":"identifier"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/isfocuspointofinterestsupported"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice":{"url":"/documentation/avfoundation/avcapturedevice","title":"AVCaptureDevice","abstract":[{"text":"An object that represents a hardware or virtual capture device like a camera or microphone.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"AVCaptureDevice","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVCaptureDevice","kind":"identifier"}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FocusMode"}],"navigatorTitle":[{"kind":"identifier","text":"FocusMode"}],"abstract":[{"type":"text","text":"Constants to specify the focus mode of a capture device."}],"type":"topic","title":"AVCaptureDevice.FocusMode","url":"/documentation/avfoundation/avcapturedevice/focusmode-swift.enum","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFocusModeSupported"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureFocusMode","kind":"typeIdentifier","text":"FocusMode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFocusModeSupported:"}],"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the device supports the specified focus mode."}],"type":"topic","title":"isFocusModeSupported(_:)","url":"/documentation/avfoundation/avcapturedevice/isfocusmodesupported(_:)","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isLockingFocusWithCustomLensPositionSupported":{"title":"isLockingFocusWithCustomLensPositionSupported","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isLockingFocusWithCustomLensPositionSupported","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLockingFocusWithCustomLensPositionSupported"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device supports locking focus to a specific lens position."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lockingFocusWithCustomLensPositionSupported"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/islockingfocuswithcustomlenspositionsupported"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup":{"type":"topic","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup","role":"collectionGroup","kind":"article","abstract":[{"type":"text","text":"Configure built-in cameras and microphones, and external capture devices, for media capture."}],"url":"/documentation/avfoundation/capture-setup","title":"Capture setup"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure":{"abstract":[{"type":"text","text":"Configure the automatic exposure behavior of a camera, or manually control its exposure settings."}],"identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure","role":"collectionGroup","url":"/documentation/avfoundation/capture-device-exposure","type":"topic","kind":"article","title":"Exposure"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSmoothAutoFocusEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"smoothAutoFocusEnabled","kind":"identifier"}],"abstract":[{"text":"A Boolean value that indicates whether smooth autofocus is in an enabled state on the device.","type":"text"}],"type":"topic","title":"isSmoothAutoFocusEnabled","url":"/documentation/avfoundation/avcapturedevice/issmoothautofocusenabled","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAdjustingFocus":{"title":"isAdjustingFocus","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAdjustingFocus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAdjustingFocus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device is currently adjusting its focus setting."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adjustingFocus"}],"role":"symbol","url":"/documentation/avfoundation/avcapturedevice/isadjustingfocus"},"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats":{"title":"Formats","url":"/documentation/avfoundation/capture-device-formats","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats","type":"topic","kind":"article","role":"collectionGroup","abstract":[{"type":"text","text":"Configure capture formats and camera frame rates."}]},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoFocusRangeRestriction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureAutoFocusRangeRestriction","kind":"typeIdentifier","text":"AutoFocusRangeRestriction"}],"navigatorTitle":[{"kind":"identifier","text":"autoFocusRangeRestriction"}],"abstract":[{"type":"text","text":"A value that controls the allowable range for automatic focusing."}],"type":"topic","title":"autoFocusRangeRestriction","url":"/documentation/avfoundation/avcapturedevice/autofocusrangerestriction-swift.property","kind":"symbol"},"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled":{"role":"symbol","identifier":"doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticallyAdjustsFaceDrivenAutoFocusEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"automaticallyAdjustsFaceDrivenAutoFocusEnabled"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the device automatically adjusts face-driven autofocus."}],"type":"topic","title":"automaticallyAdjustsFaceDrivenAutoFocusEnabled","url":"/documentation/avfoundation/avcapturedevice/automaticallyadjustsfacedrivenautofocusenabled","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"anchor":"Configuring-Automatic-Focus","title":"Configuring Automatic Focus","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusModeSupported(_:)","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusMode-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/FocusMode-swift.enum","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSmoothAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFaceDrivenAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/automaticallyAdjustsFaceDrivenAutoFocusEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAutoFocusRangeRestrictionSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/autoFocusRangeRestriction-swift.property","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/AutoFocusRangeRestriction-swift.enum"]},{"anchor":"Setting-a-Focus-Point-of-Interest","title":"Setting a Focus Point of Interest","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isFocusPointOfInterestSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/focusPointOfInterest"]},{"anchor":"Monitoring-Focus-Changes","title":"Monitoring Focus Changes","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isAdjustingFocus"]},{"anchor":"Setting-Focus-Manually","title":"Setting Focus Manually","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isLockingFocusWithCustomLensPositionSupported","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lensPosition","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/currentLensPosition","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/setFocusModeLocked(lensPosition:completionHandler:)"]},{"anchor":"Inspecting-the-Focus-Distance","title":"Inspecting the Focus Distance","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minimumFocusDistance"]}],"op":"replace","path":"/topicSections"},{"value":[{"anchor":"Configuring-Camera-Hardware","identifiers":["doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled","doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color","doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-zoom"],"title":"Configuring Camera Hardware","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":"AVCaptureAutoFocusRangeRestriction","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/title"},{"value":[{"kind":"identifier","text":"AVCaptureAutoFocusRangeRestriction"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/fragments"},{"value":[{"text":"AVCaptureAutoFocusRangeRestriction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1AutoFocusRangeRestriction-swift.enum/navigatorTitle"},{"value":"AVCaptureLensPositionCurrent","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1currentLensPosition/title"},{"value":[{"text":"AVCaptureLensPositionCurrent","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1currentLensPosition/fragments"},{"value":"smoothAutoFocusSupported","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusSupported/title"},{"value":[{"kind":"identifier","text":"smoothAutoFocusSupported"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusSupported/fragments"},{"value":"lockForConfiguration:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"lockForConfiguration:"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/fragments"},{"value":"setFocusModeLockedWithLensPosition:completionHandler:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setFocusModeLocked(lensPosition:completionHandler:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setFocusModeLockedWithLensPosition:completionHandler:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1setFocusModeLocked(lensPosition:completionHandler:)/fragments"},{"value":"AVCaptureDeviceSubjectAreaDidChangeNotification","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1subjectAreaDidChangeNotification/title"},{"value":[{"kind":"identifier","text":"AVCaptureDeviceSubjectAreaDidChangeNotification"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1subjectAreaDidChangeNotification/fragments"},{"value":"focusPointOfInterest","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusPointOfInterest/title"},{"value":[{"kind":"identifier","text":"focusPointOfInterest"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusPointOfInterest/fragments"},{"value":"lensPosition","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lensPosition/title"},{"value":[{"text":"lensPosition","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lensPosition/fragments"},{"value":"unlockForConfiguration","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"unlockForConfiguration","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/fragments"},{"value":"faceDrivenAutoFocusEnabled","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFaceDrivenAutoFocusEnabled/title"},{"value":[{"kind":"identifier","text":"faceDrivenAutoFocusEnabled"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFaceDrivenAutoFocusEnabled/fragments"},{"value":"focusMode","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusMode-swift.property/title"},{"value":[{"text":"focusMode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1focusMode-swift.property/fragments"},{"value":"subjectAreaChangeMonitoringEnabled","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSubjectAreaChangeMonitoringEnabled/title"},{"value":[{"kind":"identifier","text":"subjectAreaChangeMonitoringEnabled"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSubjectAreaChangeMonitoringEnabled/fragments"},{"value":"minimumFocusDistance","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1minimumFocusDistance/title"},{"value":[{"kind":"identifier","text":"minimumFocusDistance"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1minimumFocusDistance/fragments"},{"value":"autoFocusRangeRestrictionSupported","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoFocusRangeRestrictionSupported/title"},{"value":[{"kind":"identifier","text":"autoFocusRangeRestrictionSupported"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAutoFocusRangeRestrictionSupported/fragments"},{"value":"focusPointOfInterestSupported","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusPointOfInterestSupported/title"},{"value":[{"text":"focusPointOfInterestSupported","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusPointOfInterestSupported/fragments"},{"value":"AVCaptureDevice","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title"},{"value":[{"kind":"identifier","text":"AVCaptureDevice"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments"},{"value":[{"text":"AVCaptureDevice","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle"},{"value":"AVCaptureFocusMode","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/title"},{"value":[{"kind":"identifier","text":"AVCaptureFocusMode"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/fragments"},{"value":[{"text":"AVCaptureFocusMode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1FocusMode-swift.enum/navigatorTitle"},{"value":"isFocusModeSupported:","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusModeSupported(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isFocusModeSupported:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isFocusModeSupported(_:)/fragments"},{"value":"lockingFocusWithCustomLensPositionSupported","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isLockingFocusWithCustomLensPositionSupported/title"},{"value":[{"kind":"identifier","text":"lockingFocusWithCustomLensPositionSupported"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isLockingFocusWithCustomLensPositionSupported/fragments"},{"value":"smoothAutoFocusEnabled","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusEnabled/title"},{"value":[{"kind":"identifier","text":"smoothAutoFocusEnabled"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSmoothAutoFocusEnabled/fragments"},{"value":"adjustingFocus","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAdjustingFocus/title"},{"value":[{"text":"adjustingFocus","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isAdjustingFocus/fragments"},{"value":"autoFocusRangeRestriction","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1autoFocusRangeRestriction-swift.property/title"},{"value":[{"text":"autoFocusRangeRestriction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1autoFocusRangeRestriction-swift.property/fragments"},{"value":"automaticallyAdjustsFaceDrivenAutoFocusEnabled","op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1automaticallyAdjustsFaceDrivenAutoFocusEnabled/title"},{"value":[{"kind":"identifier","text":"automaticallyAdjustsFaceDrivenAutoFocusEnabled"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1automaticallyAdjustsFaceDrivenAutoFocusEnabled/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}