{
  "abstract": [
    {
      "text": "Capture Live Photos like those created in the system Camera app and save them to the Photos library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-and-saving-live-photos"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Capturing and Saving Live Photos"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Live Photo is a picture that includes motion and sound from the moments just before and after its capture. Your app can capture and record Live Photos using the AVFoundation capture system and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you’re not already familiar with capture sessions, input setup, and photo capture, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Enable-Live-Photo-Capture",
          "level": 3,
          "text": "Enable Live Photo Capture",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a still photo your capture session needs only a video input, but a Live Photo includes sound, so you’ll need to also connect an audio capture device to your session:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "enum CameraError: Error {",
            "    case configurationFailed",
            "    // ... additional error cases ...",
            "}",
            "",
            "func configureSession() throws {",
            "    captureSession.beginConfiguration()",
            "    ",
            "    // ... add camera input and photo output ...",
            "    ",
            "    guard let audioDevice = AVCaptureDevice.default(for: .audio),",
            "          let audioDeviceInput = try? AVCaptureDeviceInput(device: audioDevice) else {",
            "              throw CameraError.configurationFailed",
            "    }",
            "    ",
            "    if captureSession.canAddInput(audioDeviceInput) {",
            "        captureSession.addInput(audioDeviceInput)",
            "    } else {",
            "        throw CameraError.configurationFailed",
            "    }",
            "    ",
            "    // ... configure photo output and start running ...",
            "    ",
            "    captureSession.commitConfiguration()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Because you’re already using a built-in camera device for video (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), you can simply use the default audio capture device—the system automatically uses the best microphone configuration for the camera position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Capturing Live Photos requires an internal reconfiguration of the capture pipeline, which takes time and interrupts any in-progress captures. Before shooting your first Live Photo, make sure you’ve configured the pipeline appropriately by enabling Live Photo capture on your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let photoOutput = AVCapturePhotoOutput()",
            "",
            "// Attempt to add the photo output to the session.",
            "if captureSession.canAddOutput(photoOutput) {",
            "    captureSession.sessionPreset = .photo",
            "    captureSession.addOutput(photoOutput)",
            "} else {",
            "    throw CameraError.configurationFailed",
            "}",
            "",
            "// Configure the photo output's behavior.",
            "photoOutput.isHighResolutionCaptureEnabled = true",
            "photoOutput.isLivePhotoCaptureEnabled = photoOutput.isLivePhotoCaptureSupported",
            "",
            "// Start the capture session.",
            "captureSession.startRunning()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Capture-a-Live-Photo",
          "level": 3,
          "text": "Capture a Live Photo",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Once your photo output is ready for Live Photos, you can choose still image or Live Photo capture for each shot. To capture a Live Photo, create an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, choosing the format for the still image portion of the Live Photo and providing a URL for writing the movie portion of the Live Photo. Then, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to trigger capture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let photoSettings = AVCapturePhotoSettings(format: [AVVideoCodecKey: AVVideoCodecType.hevc])",
            "photoSettings.livePhotoMovieFileURL = // output url",
            "",
            "// Shoot the Live Photo, using a custom class to handle capture delegate callbacks.",
            "let captureProcessor = LivePhotoCaptureProcessor()",
            "photoOutput.capturePhoto(with: photoSettings, delegate: captureProcessor)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Handle-Live-Photo-Results",
          "level": 3,
          "text": "Handle Live Photo Results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A Live Photo appears to users in the Photos app as a single asset, but it’s actually composed of separate files: the primary still image, and a movie file containing motion and sound from the moments before and after. The capture system delivers these results separately, as soon as each becomes available.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method delivers the still image portion of the Live Photo as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. Because you’ll need to save the still image and movie files together, it’s best to extract the image file data from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and keep it until the movie file finishes recording, as shown below. (You can also use this method to indicate in your UI that the still image has been captured.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func photoOutput(_ output: AVCapturePhotoOutput,",
            "                 didFinishProcessingPhoto photo: AVCapturePhoto,",
            "                 error: Error?) {",
            "    guard error != nil else {",
            "        print(\"Error capturing Live Photo still: \\(error!)\");",
            "        return",
            "    }",
            "    ",
            "    // Get and process the captured image data.",
            "    processImage(photo.fileDataRepresentation())",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method fires later, indicating that the URL you specified when triggering the capture now contains a complete movie file. Once you have both the still image and movie portions of your Live Photo, you can save them together:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func photoOutput(_ output: AVCapturePhotoOutput,",
            "                 didFinishProcessingLivePhotoToMovieFileAt outputFileURL: URL,",
            "                 duration: CMTime,",
            "                 photoDisplayTime: CMTime,",
            "                 resolvedSettings: AVCaptureResolvedPhotoSettings,",
            "                 error: Error?) {",
            "    ",
            "    guard error != nil else {",
            "        print(\"Error capturing Live Photo movie: \\(error!)\");",
            "        return",
            "    }",
            "    ",
            "    guard let stillImageData = stillImageData else { return }",
            "    ",
            "    // Save Live Photo.",
            "    saveLivePhotoToPhotosLibrary(stillImageData: stillImageData,",
            "                                 livePhotoMovieURL: outputFileURL)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "To display Live Photos after capture, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Photos/PHLivePhoto",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/PhotosUI/PHLivePhotoView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Save-a-Live-Photo-to-the-Photos-Library",
          "level": 3,
          "text": "Save a Live Photo to the Photos Library",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Photos/PHAssetCreationRequest",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class to create a single Photos asset consisting of media from multiple files—in the case of a Live Photo, the still image and its paired video. As in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/saving-captured-photos",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you’ll need to wrap that request in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Photos/PHPhotoLibrary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " change block, and first make sure that your app has the user’s permission to access Photos.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func saveLivePhotoToPhotosLibrary(stillImageData: Data, livePhotoMovieURL: URL) {    PHPhotoLibrary.requestAuthorization { status in",
            "        guard status == .authorized else { return }",
            "        ",
            "        PHPhotoLibrary.shared().performChanges({",
            "            // Add the captured photo's file data as the main resource for the Photos asset.",
            "            let creationRequest = PHAssetCreationRequest.forAsset()",
            "            creationRequest.addResource(with: .photo, data: stillImageData, options: nil)",
            "            ",
            "            // Add the movie file URL as the Live Photo's paired video resource.",
            "            let options = PHAssetResourceCreationOptions()",
            "            options.shouldMoveFile = true",
            "            creationRequest.addResource(with: .pairedVideo, fileURL: livePhotoMovieURL, options: options)",
            "        }) { success, error in",
            "            // Handle completion.",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Photos/PHAssetResourceCreationOptions/shouldMoveFile",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " option so that iOS can transfer the movie file from your app’s sandbox to the system Photos library without an expensive data-copying operation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "anchor": "Track-Live-Photo-Progress",
          "level": 3,
          "text": "Track Live Photo Progress",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Capturing Live Photos adds two additional steps to the process shown in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/tracking-photo-capture-progress",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ": after delivery of the still photo result (step 4), the photo output notifies you of movie capture status (step 5) and delivers the movie result (step 6). (Final cleanup becomes step 7.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2961960",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the user captures a Live Photo in the system Camera app, a “Live” indicator appears for a few seconds to let the user know that video and audio are still being recorded. To provide a similar interface in your app, implement these methods in your photo capture delegate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:willBeginCaptureFor:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method tells you that capture has started: implement this method to show a recording indicator.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method tells you that a Live Photo movie is no longer recording: implement this method to hide the indicator. (Note that the movie file is not yet available at this time.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can have multiple Live Photo captures running at the same time, so it’s best to use these methods to keep track of the number of captures “in flight” and hide your indicator only when that number reaches zero:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class LivePhotoCaptureProcessor: NSObject, AVCapturePhotoCaptureDelegate {",
            "    // ... other PhotoCaptureDelegate methods and supporting properties ...",
            "    ",
            "    // A handler to call when Live Photo capture begins and ends.",
            "    var livePhotoStatusHandler: (Bool) -> () = { _ in }",
            "    ",
            "    // A property for tracking in-progress captures and updating UI accordingly.",
            "    var livePhotosInProgress = 0 {",
            "        didSet {",
            "            // Update the UI accordingly based on the value of this property",
            "        }",
            "    }",
            "    ",
            "    // Call the handler when PhotoCaptureDelegate methods indicate Live Photo capture is in progress.",
            "    func photoOutput(_ output: AVCapturePhotoOutput,",
            "                     willBeginCaptureFor resolvedSettings: AVCaptureResolvedPhotoSettings) {",
            "        let capturingLivePhoto = (resolvedSettings.livePhotoMovieDimensions.width > 0 && resolvedSettings.livePhotoMovieDimensions.height > 0)",
            "        livePhotoStatusHandler(capturingLivePhoto)",
            "    }",
            "    ",
            "    func photoOutput(_ output: AVCapturePhotoOutput,",
            "                     didFinishRecordingLivePhotoMovieForEventualFileAt outputFileURL: URL,",
            "                     resolvedSettings: AVCaptureResolvedPhotoSettings) {",
            "        livePhotoStatusHandler(false)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto": {
      "abstract": [
        {
          "text": "A container for image data from a photo capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhoto",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate the movie file URL resulting from a Live Photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingLivePhotoToMovieFileAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "photoDisplayTime"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resolvedSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureResolvedPhotoSettings",
          "text": "AVCaptureResolvedPhotoSettings"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingLivePhotoToMovieFileAtURL:duration:photoDisplayTime:resolvedSettings:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessinglivephototomoviefileat:duration:photodisplaytime:resolvedsettings:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate with the captured image and associated metadata resulting from a photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingPhoto:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingPhoto:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessingphoto:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that the movie content of a Live Photo has finished recording.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishRecordingLivePhotoMovieForEventualFileAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "resolvedSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureResolvedPhotoSettings",
          "text": "AVCaptureResolvedPhotoSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishRecordingLivePhotoMovieForEventualFileAtURL:resolvedSettings:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishrecordinglivephotomovieforeventualfileat:resolvedsettings:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:willBeginCaptureFor:)": {
      "abstract": [
        {
          "text": "Notifies the delegate that the capture output has resolved settings and will soon begin its capture process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBeginCaptureFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureResolvedPhotoSettings",
          "text": "AVCaptureResolvedPhotoSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:willBeginCaptureFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:willBeginCaptureForResolvedSettings:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:willBeginCaptureFor:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:willbegincapturefor:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput": {
      "abstract": [
        {
          "text": "A capture output for still image, Live Photos, and other photography workflows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)": {
      "abstract": [
        {
          "text": "Initiates a photo capture using the specified settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capturePhoto"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoSettings",
          "text": "AVCapturePhotoSettings"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)AVCapturePhotoCaptureDelegate",
          "text": "AVCapturePhotoCaptureDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/capturePhoto(with:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "capturePhotoWithSettings:delegate:"
        }
      ],
      "role": "symbol",
      "title": "capturePhoto(with:delegate:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/capturephoto(with:delegate:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings": {
      "abstract": [
        {
          "text": "A specification of the features and settings to use for a single photo capture request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhotoSettings"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhotoSettings"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhotoSettings",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotosettings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos": {
      "abstract": [
        {
          "text": "Configure and capture single or multiple still images, Live Photos, and other forms of photography.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capturing Still and Live Photos",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-still-and-live-photos"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture": {
      "abstract": [
        {
          "text": "Capture high-quality still images, Live Photos, and supporting photo data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Photo capture",
      "type": "topic",
      "url": "/documentation/avfoundation/photo-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/saving-captured-photos": {
      "abstract": [
        {
          "text": "Add an image and other data from a photo capture to the photo library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/saving-captured-photos",
      "kind": "article",
      "role": "article",
      "title": "Saving Captured Photos",
      "type": "topic",
      "url": "/documentation/avfoundation/saving-captured-photos"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session": {
      "abstract": [
        {
          "text": "Configure input devices, output media, preview views, and basic settings before capturing photos or video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Capture Session",
      "type": "topic",
      "url": "/documentation/avfoundation/setting-up-a-capture-session"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/tracking-photo-capture-progress": {
      "abstract": [
        {
          "text": "Monitor key events during capture to provide feedback in your camera UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/tracking-photo-capture-progress",
      "kind": "article",
      "role": "article",
      "title": "Tracking Photo Capture Progress",
      "type": "topic",
      "url": "/documentation/avfoundation/tracking-photo-capture-progress"
    },
    "doc://com.apple.documentation/documentation/Photos/PHAssetCreationRequest": {
      "abstract": [
        {
          "text": "A request to create a new Photos asset from underlying data resources, for use in a photo library change block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHAssetCreationRequest"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Photos/PHAssetCreationRequest",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHAssetCreationRequest",
      "type": "topic",
      "url": "/documentation/Photos/PHAssetCreationRequest"
    },
    "doc://com.apple.documentation/documentation/Photos/PHAssetResourceCreationOptions/shouldMoveFile": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether Photos moves or duplicates files when creating an asset resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldMoveFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Photos/PHAssetResourceCreationOptions/shouldMoveFile",
      "kind": "symbol",
      "role": "symbol",
      "title": "shouldMoveFile",
      "type": "topic",
      "url": "/documentation/Photos/PHAssetResourceCreationOptions/shouldMoveFile"
    },
    "doc://com.apple.documentation/documentation/Photos/PHLivePhoto": {
      "abstract": [
        {
          "text": "A displayable representation of a Live Photo—a picture that includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhoto"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Photos/PHLivePhoto",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHLivePhoto",
      "type": "topic",
      "url": "/documentation/Photos/PHLivePhoto"
    },
    "doc://com.apple.documentation/documentation/Photos/PHPhotoLibrary": {
      "abstract": [
        {
          "text": "An object that manages access and changes to the user’s photo library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHPhotoLibrary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Photos/PHPhotoLibrary",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHPhotoLibrary",
      "type": "topic",
      "url": "/documentation/Photos/PHPhotoLibrary"
    },
    "doc://com.apple.documentation/documentation/PhotosUI/PHLivePhotoView": {
      "abstract": [
        {
          "text": "A view that displays a Live Photo—a picture that also includes motion and sound from the moments just before and after its capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PHLivePhotoView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PhotosUI/PHLivePhotoView",
      "kind": "symbol",
      "role": "symbol",
      "title": "PHLivePhotoView",
      "type": "topic",
      "url": "/documentation/PhotosUI/PHLivePhotoView"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-2961960": {
      "alt": "Diagram of numbered Live Photo capture process steps after calling capturePhoto().",
      "identifier": "media-2961960",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c8e7cee20103d7749f60ee519fd58cc4/media-2961960.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/128c17342e87a15ff120b1259fad4824/media-2961960@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Next-Steps",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/saving-captured-photos",
        "doc://com.apple.avfoundation/documentation/AVFoundation/tracking-photo-capture-progress"
      ],
      "title": "Next Steps"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Next-Steps",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/saving-captured-photos",
                "doc://com.apple.avfoundation/documentation/AVFoundation/tracking-photo-capture-progress"
              ],
              "title": "Next Steps"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/title",
          "value": "capturePhotoWithSettings:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput~1capturePhoto(with:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "capturePhotoWithSettings:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/title",
          "value": "AVCapturePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/title",
          "value": "captureOutput:didFinishProcessingPhoto:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingPhoto:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)/title",
          "value": "captureOutput:didFinishProcessingLivePhotoToMovieFileAtURL:duration:photoDisplayTime:resolvedSettings:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingLivePhotoToMovieFileAt:duration:photoDisplayTime:resolvedSettings:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingLivePhotoToMovieFileAtURL:duration:photoDisplayTime:resolvedSettings:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)/title",
          "value": "captureOutput:didFinishRecordingLivePhotoMovieForEventualFileAtURL:resolvedSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishRecordingLivePhotoMovieForEventualFileAt:resolvedSettings:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishRecordingLivePhotoMovieForEventualFileAtURL:resolvedSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/title",
          "value": "AVCapturePhotoSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1PhotosUI~1PHLivePhotoView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHLivePhotoView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIView",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Photos~1PHAssetCreationRequest/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHAssetCreationRequest"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)PHAssetChangeRequest",
              "text": "PHAssetChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/title",
          "value": "AVCapturePhotoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhotoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Photos~1PHPhotoLibrary/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHPhotoLibrary"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Photos~1PHAssetResourceCreationOptions~1shouldMoveFile/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "assign"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "shouldMoveFile"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:willBeginCaptureFor:)/title",
          "value": "captureOutput:willBeginCaptureForResolvedSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:willBeginCaptureFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:willBeginCaptureForResolvedSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Photos~1PHLivePhoto/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "PHLivePhoto"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/capturing-and-saving-live-photos"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/capturing-and-saving-live-photos"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
