{
  "abstract": [
    {
      "text": "Get processed image data without compression to use for filtering or lossless output.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-uncompressed-image-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Capturing Uncompressed Image Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typical photography workflows save images in a compressed format such as HEIF/HEVC or JPEG. These formats use lossy compression to strike a balance between preserving noticeable details in the image and reducing its data storage requirements. However, sometimes it’s more helpful to work with uncompressed image data—for example, some image processing and analysis algorithms can be confused by the visual artifacts introduced by lossy compression.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Uncompressed image data is not to be confused with unprocessed, or RAW, image data. RAW data is minimally altered data direct from a camera’s image sensor. Uncompressed image data has been processed to create a displayable image, but hasn’t been compressed to create a small file.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS, capturing uncompressed image data requires minor changes to the basic photography workflow covered in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-Uncompressed-Format-Settings",
          "level": 3,
          "text": "Choose Uncompressed Format Settings",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To capture in an uncompressed format, create a photo settings object with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/init(format:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In the format dictionary, specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with one of the values listed in the photo output’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/availablePhotoPixelFormatTypes-6eyb",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array. The example below chooses a 32-bit BGRA pixel format, which is useful in some GPU processing workflows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Choose a 32-bit BGRA pixel format and verify the camera supports it.",
            "let pixelFormatType = kCVPixelFormatType_32BGRA",
            "guard self.photoOutput.availablePhotoPixelFormatTypes.contains(pixelFormatType) else { return }",
            "let photoSettings = AVCapturePhotoSettings(format:",
            "    [ kCVPixelBufferPixelFormatTypeKey as String : pixelFormatType ])",
            "",
            "// Shoot the photo, using a custom class to handle capture delegate callbacks.",
            "let layerOrientation = previewView.videoPreviewLayer.connection!.videoOrientation",
            "let colorSpace = self.videoCaptureDevice.activeColorSpace",
            "let captureProcessor = UncompressedCaptureProcessor(orientation: layerOrientation,",
            "                                                    colorSpace: colorSpace)",
            "self.photoOutput.capturePhoto(with: photoSettings, delegate: captureProcessor)",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Handle-Results",
          "level": 3,
          "text": "Handle Results",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As with other formats, you receive uncompressed data capture results to your delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method as an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. To access the uncompressed pixel data directly, use the photo’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/pixelBuffer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, the following code applies a Core Image filter directly to the pixel buffer and writes the filtered image to a PNG file:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class UncompressedCaptureProcessor: NSObject, AVCapturePhotoCaptureDelegate {",
            "    ",
            "    // Hold on to the separately delivered RAW and compressed photo data until capture is finished.",
            "    func photoOutput(_ output: AVCapturePhotoOutput, didFinishProcessingPhoto photo: AVCapturePhoto, error: Error?) {",
            "        guard error != nil else { print(\"Error capturing photo: \\(error!)\"); return }",
            "        ",
            "        // Create a CIImage from the pixel buffer and apply a filter",
            "        let image = CIImage(cvPixelBuffer: photo.pixelBuffer!)",
            "        let imageOrientation = self.imageOrientation(for: videoOrientation)",
            "        let filteredImage = image.oriented(imageOrientation)",
            "            .applyingFilter(\"CIPhotoEffectNoir\", parameters: [:])",
            "        ",
            "        let imageColorSpace = self.imageColorSpace(for: colorSpace)",
            "        guard let pngData = CIContext()",
            "            .pngRepresentation(of: filteredImage, format: kCIFormatBGRA8, colorSpace: imageColorSpace)",
            "            else { print(\"Error creating filtered PNG image\"); return }",
            "        self.exportToFile(pngData)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Alternatively, to get an uncompressed photo ready for writing to a file, use the photo’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to get the data formatted as a TIFF file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto": {
      "abstract": [
        {
          "text": "A container for image data from a photo capture output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCapturePhoto"
        }
      ],
      "role": "symbol",
      "title": "AVCapturePhoto",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()": {
      "abstract": [
        {
          "text": "Generates and returns a flat data representation of the photo and its attachments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/fileDataRepresentation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fileDataRepresentation"
        }
      ],
      "role": "symbol",
      "title": "fileDataRepresentation()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/filedatarepresentation()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/pixelBuffer": {
      "abstract": [
        {
          "text": "The uncompressed or RAW image sample buffer for the photo, if requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelBuffer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CVPixelBufferRef",
          "text": "CVPixelBuffer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhoto/pixelBuffer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelBuffer"
        }
      ],
      "role": "symbol",
      "title": "pixelBuffer",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephoto/pixelbuffer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)": {
      "abstract": [
        {
          "text": "Provides the delegate with the captured image and associated metadata resulting from a photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photoOutput"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhotoOutput",
          "text": "AVCapturePhotoOutput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didFinishProcessingPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCapturePhoto",
          "text": "AVCapturePhoto"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoCaptureDelegate/photoOutput(_:didFinishProcessingPhoto:error:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captureOutput:didFinishProcessingPhoto:error:"
        }
      ],
      "role": "symbol",
      "title": "photoOutput(_:didFinishProcessingPhoto:error:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotocapturedelegate/photooutput(_:didfinishprocessingphoto:error:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/availablePhotoPixelFormatTypes-6eyb": {
      "abstract": [
        {
          "text": "The pixel formats the capture output supports for photo capture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "availablePhotoPixelFormatTypes"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoOutput/availablePhotoPixelFormatTypes-6eyb",
      "kind": "symbol",
      "role": "symbol",
      "title": "availablePhotoPixelFormatTypes",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotooutput/availablephotopixelformattypes-6eyb"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/init(format:)": {
      "abstract": [
        {
          "text": "Creates a photo settings object with the specified output format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCapturePhotoSettings/init(format:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "photoSettingsWithFormat:"
        }
      ],
      "role": "symbol",
      "title": "init(format:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturephotosettings/init(format:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence": {
      "abstract": [
        {
          "text": "Capture several photos at once, varying parameters like exposure duration or light sensitivity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence",
      "kind": "article",
      "role": "article",
      "title": "Capturing a Bracketed Photo Sequence",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-a-bracketed-photo-sequence"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth": {
      "abstract": [
        {
          "text": "Get a depth map with a photo to create effects like the system camera’s Portrait mode (on compatible devices).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
      "kind": "article",
      "role": "article",
      "title": "Capturing Photos with Depth",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-photos-with-depth"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos": {
      "abstract": [
        {
          "text": "Configure and capture single or multiple still images, Live Photos, and other forms of photography.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-still-and-live-photos",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capturing Still and Live Photos",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-still-and-live-photos"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-thumbnail-and-preview-images": {
      "abstract": [
        {
          "text": "Enable delivery of reduced-size images with the main image in a photo capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-thumbnail-and-preview-images",
      "kind": "article",
      "role": "article",
      "title": "Capturing Thumbnail and Preview Images",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-thumbnail-and-preview-images"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture": {
      "abstract": [
        {
          "text": "Capture high-quality still images, Live Photos, and supporting photo data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/photo-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Photo capture",
      "type": "topic",
      "url": "/documentation/avfoundation/photo-capture"
    },
    "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey": {
      "abstract": [
        {
          "text": "A key to one or more pixel buffer format types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCVPixelBufferPixelFormatTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCVPixelBufferPixelFormatTypeKey",
      "type": "topic",
      "url": "/documentation/CoreVideo/kCVPixelBufferPixelFormatTypeKey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "More-Capture-Options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-thumbnail-and-preview-images"
      ],
      "title": "More Capture Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "More-Capture-Options",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-a-bracketed-photo-sequence",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-thumbnail-and-preview-images"
              ],
              "title": "More Capture Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CoreVideo~1kCVPixelBufferPixelFormatTypeKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFStringRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCVPixelBufferPixelFormatTypeKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation()/title",
          "value": "fileDataRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1fileDataRepresentation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fileDataRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1pixelBuffer/title",
          "value": "pixelBuffer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto~1pixelBuffer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelBuffer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/title",
          "value": "AVCapturePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhoto/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCapturePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/title",
          "value": "captureOutput:didFinishProcessingPhoto:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoCaptureDelegate~1photoOutput(_:didFinishProcessingPhoto:error:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "captureOutput:didFinishProcessingPhoto:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1init(format:)/title",
          "value": "photoSettingsWithFormat:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCapturePhotoSettings~1init(format:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "photoSettingsWithFormat:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/capturing-uncompressed-image-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/capturing-uncompressed-image-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
