{
  "abstract": [
    {
      "text": "Configure device zooming behavior and inspect hardware capabilities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-zoom"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Zoom"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/cancelVideoZoomRamp()": {
      "abstract": [
        {
          "text": "Smoothly ends a zoom transition in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelVideoZoomRamp"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/cancelVideoZoomRamp()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelVideoZoomRamp"
        }
      ],
      "role": "symbol",
      "title": "cancelVideoZoomRamp()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/cancelvideozoomramp()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/displayVideoZoomFactorMultiplier": {
      "abstract": [
        {
          "text": "A video zoom factor multiplier to use when displaying zoom information in a user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayVideoZoomFactorMultiplier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/displayVideoZoomFactorMultiplier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayVideoZoomFactorMultiplier"
        }
      ],
      "role": "symbol",
      "title": "displayVideoZoomFactorMultiplier",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/displayvideozoomfactormultiplier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/dualCameraSwitchOverVideoZoomFactor": {
      "abstract": [
        {
          "text": "The video zoom factor at which a dual camera device can automatically switch between cameras.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dualCameraSwitchOverVideoZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/dualCameraSwitchOverVideoZoomFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dualCameraSwitchOverVideoZoomFactor"
        }
      ],
      "role": "symbol",
      "title": "dualCameraSwitchOverVideoZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/dualcameraswitchovervideozoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether geometric distortion correction is enabled for this device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGeometricDistortionCorrectionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometricDistortionCorrectionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isGeometricDistortionCorrectionEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isgeometricdistortioncorrectionenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionSupported": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether this device supports geometric distortion correction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGeometricDistortionCorrectionSupported"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometricDistortionCorrectionSupported"
        }
      ],
      "role": "symbol",
      "title": "isGeometricDistortionCorrectionSupported",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isgeometricdistortioncorrectionsupported"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isRampingVideoZoom": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a zoom transition is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isRampingVideoZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isRampingVideoZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rampingVideoZoom"
        }
      ],
      "role": "symbol",
      "title": "isRampingVideoZoom",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/isrampingvideozoom"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device monitors the subject area for changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSubjectAreaChangeMonitoringEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "subjectAreaChangeMonitoringEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSubjectAreaChangeMonitoringEnabled",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/issubjectareachangemonitoringenabled"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()": {
      "abstract": [
        {
          "text": "Requests exclusive access to configure device hardware properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lockForConfiguration"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lockForConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "lockForConfiguration()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/lockforconfiguration()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableVideoZoomFactor": {
      "abstract": [
        {
          "text": "The maximum zoom factor allowed in the current capture configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAvailableVideoZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableVideoZoomFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxAvailableVideoZoomFactor"
        }
      ],
      "role": "symbol",
      "title": "maxAvailableVideoZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/maxavailablevideozoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minAvailableVideoZoomFactor": {
      "abstract": [
        {
          "text": "The minimum zoom factor allowed in the current capture configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minAvailableVideoZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minAvailableVideoZoomFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minAvailableVideoZoomFactor"
        }
      ],
      "role": "symbol",
      "title": "minAvailableVideoZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/minavailablevideozoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/ramp(toVideoZoomFactor:withRate:)": {
      "abstract": [
        {
          "text": "Begins a smooth transition from the current zoom factor to another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ramp"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toVideoZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withRate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/ramp(toVideoZoomFactor:withRate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rampToVideoZoomFactor:withRate:"
        }
      ],
      "role": "symbol",
      "title": "ramp(toVideoZoomFactor:withRate:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/ramp(tovideozoomfactor:withrate:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a capture device detects a substantial change to the video subject area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subjectAreaDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceSubjectAreaDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "subjectAreaDidChangeNotification",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/subjectareadidchangenotification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()": {
      "abstract": [
        {
          "text": "Releases exclusive control over device hardware properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlockForConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlockForConfiguration"
        }
      ],
      "role": "symbol",
      "title": "unlockForConfiguration()",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/unlockforconfiguration()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/videoZoomFactor": {
      "abstract": [
        {
          "text": "A value that controls the cropping and enlargement of images captured by the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoZoomFactor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/videoZoomFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoZoomFactor"
        }
      ],
      "role": "symbol",
      "title": "videoZoomFactor",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/videozoomfactor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/virtualDeviceSwitchOverVideoZoomFactors": {
      "abstract": [
        {
          "text": "An array of video zoom factors at or above which a virtual device, such as the dual camera, may switch to its next constituent device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "virtualDeviceSwitchOverVideoZoomFactors"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNumber",
          "text": "NSNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/virtualDeviceSwitchOverVideoZoomFactors",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "virtualDeviceSwitchOverVideoZoomFactors"
        }
      ],
      "role": "symbol",
      "title": "virtualDeviceSwitchOverVideoZoomFactors",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/virtualdeviceswitchovervideozoomfactors"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color": {
      "abstract": [
        {
          "text": "Manage HDR and color space settings for a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-color"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure": {
      "abstract": [
        {
          "text": "Configure the automatic exposure behavior of a camera, or manually control its exposure settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Exposure",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-exposure"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-focus": {
      "abstract": [
        {
          "text": "Configure the automatic focus behavior of a camera, or manually set its lens position.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-focus",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Focus",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-focus"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats": {
      "abstract": [
        {
          "text": "Configure capture formats and camera frame rates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Formats",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-formats"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting": {
      "abstract": [
        {
          "text": "Configure the device flash, torch, and low light settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Lighting",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-lighting"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance": {
      "abstract": [
        {
          "text": "Configure the automatic white balance behavior of a camera, or manually control white balance settings.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance",
      "kind": "article",
      "role": "collectionGroup",
      "title": "White Balance",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-device-white-balance"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup": {
      "abstract": [
        {
          "text": "Configure built-in cameras and microphones, and external capture devices, for media capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capture setup",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-setup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Camera-Hardware",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-focus",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color"
      ],
      "title": "Configuring Camera Hardware"
    }
  ],
  "topicSections": [
    {
      "anchor": "Adjusting-Zoom",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/videoZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/ramp(toVideoZoomFactor:withRate:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/cancelVideoZoomRamp()"
      ],
      "title": "Adjusting Zoom"
    },
    {
      "anchor": "Observing-Zoom",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isRampingVideoZoom"
      ],
      "title": "Observing Zoom"
    },
    {
      "anchor": "Inspecting-Zoom-Factors",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minAvailableVideoZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableVideoZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/virtualDeviceSwitchOverVideoZoomFactors",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/dualCameraSwitchOverVideoZoomFactor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/displayVideoZoomFactorMultiplier"
      ],
      "title": "Inspecting Zoom Factors"
    },
    {
      "anchor": "Enabling-Geometric-Distortion-Correction",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionSupported",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionEnabled"
      ],
      "title": "Enabling Geometric Distortion Correction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Adjusting-Zoom",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/videoZoomFactor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/ramp(toVideoZoomFactor:withRate:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/cancelVideoZoomRamp()"
              ],
              "title": "Adjusting Zoom"
            },
            {
              "anchor": "Observing-Zoom",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isRampingVideoZoom"
              ],
              "title": "Observing Zoom"
            },
            {
              "anchor": "Inspecting-Zoom-Factors",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/minAvailableVideoZoomFactor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/maxAvailableVideoZoomFactor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/virtualDeviceSwitchOverVideoZoomFactors",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/dualCameraSwitchOverVideoZoomFactor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/displayVideoZoomFactorMultiplier"
              ],
              "title": "Inspecting Zoom Factors"
            },
            {
              "anchor": "Enabling-Geometric-Distortion-Correction",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionSupported",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isGeometricDistortionCorrectionEnabled"
              ],
              "title": "Enabling Geometric Distortion Correction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Camera-Hardware",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/lockForConfiguration()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/unlockForConfiguration()",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/isSubjectAreaChangeMonitoringEnabled",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/subjectAreaDidChangeNotification",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-formats",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-focus",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-exposure",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-white-balance",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-lighting",
                "doc://com.apple.avfoundation/documentation/AVFoundation/capture-device-color"
              ],
              "title": "Configuring Camera Hardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isGeometricDistortionCorrectionEnabled/title",
          "value": "geometricDistortionCorrectionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isGeometricDistortionCorrectionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometricDistortionCorrectionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1minAvailableVideoZoomFactor/title",
          "value": "minAvailableVideoZoomFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1minAvailableVideoZoomFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minAvailableVideoZoomFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1virtualDeviceSwitchOverVideoZoomFactors/title",
          "value": "virtualDeviceSwitchOverVideoZoomFactors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1virtualDeviceSwitchOverVideoZoomFactors/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "virtualDeviceSwitchOverVideoZoomFactors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1cancelVideoZoomRamp()/title",
          "value": "cancelVideoZoomRamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1cancelVideoZoomRamp()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelVideoZoomRamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1ramp(toVideoZoomFactor:withRate:)/title",
          "value": "rampToVideoZoomFactor:withRate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1ramp(toVideoZoomFactor:withRate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rampToVideoZoomFactor:withRate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1displayVideoZoomFactorMultiplier/title",
          "value": "displayVideoZoomFactorMultiplier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1displayVideoZoomFactorMultiplier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "displayVideoZoomFactorMultiplier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/title",
          "value": "unlockForConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1unlockForConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlockForConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxAvailableVideoZoomFactor/title",
          "value": "maxAvailableVideoZoomFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1maxAvailableVideoZoomFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxAvailableVideoZoomFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isRampingVideoZoom/title",
          "value": "rampingVideoZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isRampingVideoZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rampingVideoZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1dualCameraSwitchOverVideoZoomFactor/title",
          "value": "dualCameraSwitchOverVideoZoomFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1dualCameraSwitchOverVideoZoomFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dualCameraSwitchOverVideoZoomFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1subjectAreaDidChangeNotification/title",
          "value": "AVCaptureDeviceSubjectAreaDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1subjectAreaDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceSubjectAreaDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/title",
          "value": "lockForConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1lockForConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lockForConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSubjectAreaChangeMonitoringEnabled/title",
          "value": "subjectAreaChangeMonitoringEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isSubjectAreaChangeMonitoringEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "subjectAreaChangeMonitoringEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1videoZoomFactor/title",
          "value": "videoZoomFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1videoZoomFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoZoomFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isGeometricDistortionCorrectionSupported/title",
          "value": "geometricDistortionCorrectionSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1isGeometricDistortionCorrectionSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometricDistortionCorrectionSupported"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/capture-device-zoom"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/capture-device-zoom"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
