{
  "abstract": [
    {
      "text": "Select the front or back camera, or use advanced features like the TrueDepth camera or dual camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/choosing-a-capture-device"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Choosing a Capture Device"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Devices offer many options for capturing photos and video, including front- and back-facing cameras, dual cameras, and the TrueDepth camera. Choosing the appropriate camera automatically or offering a user interface for camera selection is an important part of developing any app with camera features.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AVFoundation offers two main paths to selecting a camera device: the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/default(_:for:position:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Quickly-Choose-a-Default-Device",
          "level": 3,
          "text": "Quickly Choose a Default Device",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you know exactly what kind of capture devices you’re looking for, use one of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " convenience methods to select a default device. For example, the code below selects the best available back-facing camera: either the dual camera on supported devices, or the single (wide-angle) camera on single-camera devices.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let device = AVCaptureDevice.default(.builtInDualCamera,",
            "                                        for: .video, position: .back) {",
            "    return device",
            "} else if let device = AVCaptureDevice.default(.builtInWideAngleCamera,",
            "                                               for: .video, position: .back) {",
            "    return device",
            "} else {",
            "    fatalError(\"Missing expected back camera device.\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Sort-and-Filter-Devices-with-a-Discovery-Session",
          "level": 3,
          "text": "Sort and Filter Devices with a Discovery Session",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To see the entire set of devices matching certain criteria so that you can use your own logic to choose one, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. First, create a discovery session for the kinds of devices you need:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let discoverySession = AVCaptureDevice.DiscoverySession(deviceTypes:",
            "    [.builtInTrueDepthCamera, .builtInDualCamera, .builtInWideAngleCamera],",
            "    mediaType: .video, position: .unspecified)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Then, read the discovery session’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession/devices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " list to find matching devices and choose one that suits your needs. The discovery session automatically sorts its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession/devices",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " list based on the device types you asked for, so you can use the array order to find the best device with certain features. For example, because the discovery session shown above searches for depth-capable devices before the wide-angle camera and allows any device position, the first item in its devices list matching a specified position is the best depth capture device for that position (or a fallback device):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func bestDevice(in position: AVCaptureDevice.Position) -> AVCaptureDevice {",
            "    let devices = self.discoverySession.devices",
            "    guard !devices.isEmpty else { fatalError(\"Missing capture devices.\")}",
            "",
            "    return devices.first(where: { device in device.position == position })!",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice": {
      "abstract": [
        {
          "text": "An object that represents a hardware or virtual capture device like a camera or microphone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDevice"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession": {
      "abstract": [
        {
          "text": "An object that finds capture devices that match specific search criteria.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DiscoverySession"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDevice.DiscoverySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/discoverysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession/devices": {
      "abstract": [
        {
          "text": "A list of devices that match the search criteria of the discovery session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "devices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/DiscoverySession/devices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "devices"
        }
      ],
      "role": "symbol",
      "title": "devices",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/discoverysession/devices"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/default(_:for:position:)": {
      "abstract": [
        {
          "text": "Returns the default device for the specified device type, media type, and position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVCaptureDeviceType",
          "text": "DeviceType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaType",
          "text": "AVMediaType"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "position"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVCaptureDevicePosition",
          "text": "Position"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVCaptureDevice",
          "text": "AVCaptureDevice"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice/default(_:for:position:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultDeviceWithDeviceType:mediaType:position:"
        }
      ],
      "role": "symbol",
      "title": "default(_:for:position:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedevice/default(_:for:position:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput": {
      "abstract": [
        {
          "text": "An object that provides media input from a capture device to a capture session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDeviceInput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDeviceInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedeviceinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice": {
      "abstract": [
        {
          "text": "A class that represents a physical iOS device that’s nearby and can provide access to its cameras and microphones.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVContinuityDevice"
        }
      ],
      "role": "symbol",
      "title": "AVContinuityDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avcontinuitydevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice": {
      "abstract": [
        {
          "text": "Represents a physical external storage device that stores media assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDevice"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDevice",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevice"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession": {
      "abstract": [
        {
          "text": "Informs your app when the external storage devices connect to and disconnect from the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVExternalStorageDeviceDiscoverySession"
        }
      ],
      "role": "symbol",
      "title": "AVExternalStorageDeviceDiscoverySession",
      "type": "topic",
      "url": "/documentation/avfoundation/avexternalstoragedevicediscoverysession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup": {
      "abstract": [
        {
          "text": "Configure built-in cameras and microphones, and external capture devices, for media capture.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capture-setup",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Capture setup",
      "type": "topic",
      "url": "/documentation/avfoundation/capture-setup"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Capture-devices",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
      ],
      "title": "Capture devices"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Capture-devices",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDeviceInput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVContinuityDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDevice",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVExternalStorageDeviceDiscoverySession"
              ],
              "title": "Capture devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/title",
          "value": "AVCaptureDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/title",
          "value": "AVCaptureDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/title",
          "value": "AVExternalStorageDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/title",
          "value": "AVCaptureDeviceInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDeviceInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDeviceInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1default(_:for:position:)/title",
          "value": "defaultDeviceWithDeviceType:mediaType:position:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1default(_:for:position:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultDeviceWithDeviceType:mediaType:position:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession~1devices/title",
          "value": "devices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDevice~1DiscoverySession~1devices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "devices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/title",
          "value": "AVContinuityDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVContinuityDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVContinuityDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/title",
          "value": "AVExternalStorageDeviceDiscoverySession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVExternalStorageDeviceDiscoverySession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVExternalStorageDeviceDiscoverySession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/choosing-a-capture-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/choosing-a-capture-device"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
