{
  "abstract": [
    {
      "text": "Creates a collection with the required tags to describe the specified video output requirements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CMTagCollectionCreateWithVideoOutputPreset",
    "fragments": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCreateWithVideoOutputPreset"
      }
    ],
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMTagCollectionCreateWithVideoOutputPreset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.2",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.1",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CMTagCollectionCreateWithVideoOutputPreset"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@OSStatus",
              "text": "OSStatus"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CMTagCollectionCreateWithVideoOutputPreset"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFAllocatorRef",
              "text": "CFAllocatorRef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "allocator"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CMTagCollectionVideoOutputPreset",
              "text": "CMTagCollectionVideoOutputPreset"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "preset"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CMTagCollectionRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMTagCollectionRef",
              "text": "CMTagCollectionRef"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "newCollectionOut"
            },
            {
              "kind": "text",
              "text": ");"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An allocator to use to create the collection and internal data structures.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "allocator"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A preset that indicates the desired output type.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "preset"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The address of the newly created tag collection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "newCollectionOut"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput": {
      "abstract": [
        {
          "text": "An object that vends attributed strings for media with a legible characteristic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemLegibleOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemLegibleOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemLegibleOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemlegibleoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput": {
      "abstract": [
        {
          "text": "An object that vends collections of metadata items that a player item’s tracks carry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemMetadataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemMetadataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemMetadataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemmetadataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput": {
      "abstract": [
        {
          "text": "An abstract class that defines the common interface to output media data from a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate": {
      "abstract": [
        {
          "text": "A protocol that defines the methods to implement to respond to changes in the media data sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPushDelegate"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemOutputPushDelegate"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemOutputPushDelegate",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemoutputpushdelegate"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput": {
      "abstract": [
        {
          "text": "A player item output that vends media with a legible characteristic as rendered pixel buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemRenderedLegibleOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemRenderedLegibleOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemRenderedLegibleOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemrenderedlegibleoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput": {
      "abstract": [
        {
          "text": "An object that outputs video frames from a player item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItemVideoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItemVideoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItemVideoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritemvideooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput": {
      "abstract": [
        {
          "text": "An object that receives video data from a player object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerVideoOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerVideoOutput"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerVideoOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayervideooutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage": {
      "abstract": [
        {
          "text": "An object that provides a rendered pixel buffer and its position in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRenderedCaptionImage"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRenderedCaptionImage"
        }
      ],
      "role": "symbol",
      "title": "AVRenderedCaptionImage",
      "type": "topic",
      "url": "/documentation/avfoundation/avrenderedcaptionimage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification": {
      "abstract": [
        {
          "text": "An object that specifies the pixel buffer attributes and tag collections handled by a player video output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoOutputSpecification"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoOutputSpecification"
        }
      ],
      "role": "symbol",
      "title": "AVVideoOutputSpecification",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideooutputspecification"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset": {
      "abstract": [
        {
          "text": "Creates a collection with the required tags to describe the specified video output requirements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionCreateWithVideoOutputPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionCreateWithVideoOutputPreset",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionCreateWithVideoOutputPreset",
      "type": "topic",
      "url": "/documentation/avfoundation/cmtagcollectioncreatewithvideooutputpreset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset": {
      "abstract": [
        {
          "text": "Constants that indicate the type of video content to output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CMTagCollectionVideoOutputPreset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionVideoOutputPreset",
      "type": "topic",
      "url": "/documentation/avfoundation/cmtagcollectionvideooutputpreset"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef": {
      "abstract": [
        {
          "text": "A reference to a CFAllocator object. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFAllocator"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFAllocatorRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFAllocator",
      "type": "topic",
      "url": "/documentation/corefoundation/cfallocator"
    },
    "doc://com.externally.resolved.symbol/c:@T@CMTagCollectionRef": {
      "abstract": [
        {
          "text": "A reference to a tag collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typedef"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "const"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@OpaqueCMTagCollection",
          "text": "OpaqueCMTagCollection"
        },
        {
          "kind": "text",
          "text": " * "
        },
        {
          "kind": "identifier",
          "text": "CMTagCollectionRef"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CMTagCollectionRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CMTagCollectionRef",
      "type": "topic",
      "url": "/documentation/CoreMedia/CMTagCollectionRef"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-output",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerVideoOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoOutputSpecification",
        "doc://com.apple.avfoundation/documentation/AVFoundation/CMTagCollectionVideoOutputPreset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemVideoOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemLegibleOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemRenderedLegibleOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVRenderedCaptionImage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemMetadataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItemOutputPushDelegate"
      ],
      "title": "Media output"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/title",
          "value": "AVRenderedCaptionImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRenderedCaptionImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVRenderedCaptionImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRenderedCaptionImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/title",
          "value": "AVPlayerItemLegibleOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemLegibleOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/title",
          "value": "AVPlayerItemRenderedLegibleOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemRenderedLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemRenderedLegibleOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemRenderedLegibleOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFAllocatorRef/title",
          "value": "CFAllocatorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/title",
          "value": "AVPlayerItemVideoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemVideoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/title",
          "value": "AVPlayerItemOutputPushDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPushDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutputPushDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutputPushDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/title",
          "value": "AVPlayerItemOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/title",
          "value": "AVPlayerItemMetadataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItemMetadataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItemMetadataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/title",
          "value": "AVPlayerVideoOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerVideoOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerVideoOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/title",
          "value": "AVVideoOutputSpecification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoOutputSpecification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoOutputSpecification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoOutputSpecification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/cmtagcollectioncreatewithvideooutputpreset"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
