{
  "abstract": [
    {
      "text": "The constants that represent the possible bit rate strategy values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/encoder-bit-rate-strategy-values"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "title": "Encoder Bit Rate Strategy Values"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use these values with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVEncoderBitRateStrategyKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-settings"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Constant": {
      "abstract": [
        {
          "text": "A value that represents a constant bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBitRateStrategy_Constant"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Constant",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioBitRateStrategy_Constant",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioBitRateStrategy_Constant"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_LongTermAverage": {
      "abstract": [
        {
          "text": "A value that represents an average bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBitRateStrategy_LongTermAverage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_LongTermAverage",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioBitRateStrategy_LongTermAverage",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioBitRateStrategy_LongTermAverage"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Variable": {
      "abstract": [
        {
          "text": "A value that represents a variable bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBitRateStrategy_Variable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Variable",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioBitRateStrategy_Variable",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioBitRateStrategy_Variable"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_VariableConstrained": {
      "abstract": [
        {
          "text": "A value that represents a constrained variable bit rate strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioBitRateStrategy_VariableConstrained"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_VariableConstrained",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioBitRateStrategy_VariableConstrained",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioBitRateStrategy_VariableConstrained"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVEncoderBitRateStrategyKey": {
      "abstract": [
        {
          "text": "A constant that represents the bit rate strategy for the encoder to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVEncoderBitRateStrategyKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVEncoderBitRateStrategyKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVEncoderBitRateStrategyKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVEncoderBitRateStrategyKey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Strategies",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Constant",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_LongTermAverage",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_VariableConstrained",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Variable"
      ],
      "title": "Strategies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Strategies",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Constant",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_LongTermAverage",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_VariableConstrained",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioBitRateStrategy_Variable"
              ],
              "title": "Strategies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioBitRateStrategy_Constant/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioBitRateStrategy_Constant"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioBitRateStrategy_Variable/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioBitRateStrategy_Variable"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioBitRateStrategy_LongTermAverage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioBitRateStrategy_LongTermAverage"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAUDIOENGINE_HAVE_AUAUDIOUNIT/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "#define"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAUDIOENGINE_HAVE_AUAUDIOUNIT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVEncoderBitRateStrategyKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVEncoderBitRateStrategyKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioBitRateStrategy_VariableConstrained/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioBitRateStrategy_VariableConstrained"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/encoder-bit-rate-strategy-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/encoder-bit-rate-strategy-values"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
