{
  "abstract": [
    {
      "text": "Measure front-of-screen luminance by using test pattern files with a spectroradiometer or colorimeter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Evaluating an App’s Video Color Using Light-Measurement Instruments"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Evaluate the color characteristics of your AVFoundation-based app or workflow using test pattern files. Output these files to a spectroradiometer or colorimeter to measure the front-of-screen (FoS) luminance, and compare your measurements against the expected values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Measure-FoS-Luminance",
          "level": 3,
          "text": "Measure FoS Luminance",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the test files from the ",
              "type": "text"
            },
            {
              "code": "SDR_BT709_HDTV",
              "type": "codeVoice"
            },
            {
              "text": " folder (see “Color Test Patterns” on the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/av-foundation/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") with a measuring instrument such as a spectroradiometer or colorimeter to measure the FoS luminance. Take your measurements after aligning the instrument to the center of the display in a dark room to prevent stray light or glare from influencing the measurements. You may see some variation in the readings depending on your instrument’s tolerances and its calibration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the luminance ramp test pattern files in the folder ",
              "type": "text"
            },
            {
              "code": "SDR_BT709_HDTV",
              "type": "codeVoice"
            },
            {
              "text": " to measure the FoS luminance. Open the test pattern movie files in your app or the QuickTime Player app, then measure and compare the results against those shown below. If you encounter conflicting results, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color#Ensure-Accurate-Color-Application-of-Your-Apps-Video",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to make certain your app takes advantage of the color-management capabilities of macOS.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following list summarizes the FoS luminance expectations (output in nits) on macOS platforms for video files tagged as BT.709 (NCLC = 1-1-1).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "MacOS internal display",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = Reference White Nits * linearBrightnessAttenuation * (Normalized Codeword)^(1.961)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses a 1.961 gamma based on the assumption of a bright surround environment. The linear brightness attenuation varies between 0 and 1 and is dependent on the position of the display’s brightness slider. Reference white nits is the peak luminance capability of the Mac display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "External TV or monitor through HDMI interface",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = Reference White Nits * (Normalized Codeword)^(display’s EOTF gamma)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Reference white nits is the peak luminance capability of the external TV or monitor. The display’s EOTF (electro-optical transfer function) gamma is the gamma used by the TV or monitor to decode the input signal to linear light.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Pro Display XDR (P3-1600 nits) and Apple Display (P3-500 nits):",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Pro Display XDR Apple reference modes",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = Reference White Nits * linearBrightnessAttenuation * (Normalized Codeword)^(1.961)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses a 1.961 gamma based on the assumption of a bright surround environment, the same as the macOS internal displays. The linear brightness attenuation varies between 0 and 1 and is dependent on the position of the display’s brightness slider. Reference white nits is the peak SDR (standard dynamic range) luminance capability of the mode in the Pro Display XDR display, which is set to 500 nits for both of the Apple reference modes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Pro Display XDR HDR video (P3-ST 2084) reference mode",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = Reference White Nits * (Normalized Codeword)^(1.961)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Reference white nits is the peak SDR luminance capability of HDR Video (P3 - ST 2084) mode, which is set to 100 nits.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "HDTV Video (BT.709 – BT.1886), NTSC Video (BT.601 SMPTE-C), and PAL & SECAM Video (BT.601 – EBU):",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Pro Display XDR BT.1886 reference modes",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = a*(max(Normalized Codeword + b, 0))^(gamma)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "(where a and b are derived as per ",
              "type": "text"
            },
            {
              "identifier": "https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1886-0-201103-I!!PDF-E.pdf",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ")",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "a = (Lw ^ (1/gamma) - Lb ^ (1/gamma))^(gamma)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "b = Lb ^ (1/gamma) / ((Lw ^ (1/gamma) - Lb ^ (1/gamma))",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Lw = 100.0 nits",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Lb = 0.0005 nits",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "gamma = 2.4",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "Pro Display XDR custom reference mode with system gamma boost",
                    "type": "text"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "inlineContent": [
                          {
                            "text": "FoS Nits = Reference White Nits * (Normalized Codeword)^(1.961 * system-gamma-boost)",
                            "type": "text"
                          }
                        ],
                        "type": "emphasis"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Reference white nits (SDR maximum luminance) and system gamma boost (≥ 1.0) are set while creating a custom reference mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color": {
      "abstract": [
        {
          "text": "Check color reproduction for a video in your app by using test patterns, video test equipment, and light-measurement instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Evaluating an App’s Video Color",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color#Ensure-Accurate-Color-Application-of-Your-Apps-Video": {
      "abstract": [],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color#Ensure-Accurate-Color-Application-of-Your-Apps-Video",
      "kind": "section",
      "title": "Ensure Accurate Color Application of Your App’s Video",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color#Ensure-Accurate-Color-Application-of-Your-Apps-Video"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-video-test-equipment": {
      "abstract": [
        {
          "text": "Output test pattern files to a vectorscope or waveform analyzer to review the video signals.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-video-test-equipment",
      "kind": "article",
      "role": "article",
      "title": "Evaluating an App’s Video Color Using Video Test Equipment",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files": {
      "abstract": [
        {
          "text": "Check color reproduction of your app or workflow by using test pattern files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
      "kind": "article",
      "role": "article",
      "title": "Evaluating Video Using QuickTime Test Pattern Files",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-video-using-quicktime-test-pattern-files"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/av-foundation/": {
      "identifier": "https://developer.apple.com/av-foundation/",
      "title": "AVFoundation Developer Page",
      "titleInlineContent": [
        {
          "text": "AVFoundation Developer Page",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/av-foundation/"
    },
    "https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1886-0-201103-I!!PDF-E.pdf": {
      "identifier": "https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1886-0-201103-I!!PDF-E.pdf",
      "title": "Recommendation ITU-R BT.1886",
      "titleInlineContent": [
        {
          "text": "Recommendation ITU-R BT.1886",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.1886-0-201103-I!!PDF-E.pdf"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-Evaluation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
      ],
      "title": "Video Evaluation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Video-Evaluation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
                "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
              ],
              "title": "Video Evaluation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
