{
  "abstract": [
    {
      "text": "Output test pattern files to a vectorscope or waveform analyzer to review the video signals.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Evaluating an App’s Video Color Using Video Test Equipment"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "AVFoundation automatically applies color management to video during playback. Verify that the system properly color manages your video by using either of the following techniques:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Output the test pattern files to a vectorscope or waveform analyzer to analyze the video signals.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Verify the correct colorspace conversion matrices on a vectorscope, and verify the gamma, quantization errors, and range expansion or compression on a waveform monitor.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3733686",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Analyze-Your-Video-Signal-Using-a-Vectorscope",
          "level": 3,
          "text": "Analyze Your Video Signal Using a Vectorscope",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A vectorscope plots the two chroma components of a video signal and measures their color relationship. Vectorscopes often include printed boxes indicating standard colors. Ideally, a correctly reproduced color bar signal should “hit” the vectorscope boxes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Output QuickTime test patterns to a vectorscope to analyze the video signals. View the test pattern on a vectorscope and verify the correct colorspace conversion matrices and the presence of a color match.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Don’t evaluate the display outputs (Display Port or DVI) using standard vectorscope targets. The system adjusts gamma for displays, but not for video devices. Use standard vectorscope targets for video outputs (HDMI, Composite, or Component video output).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, vectorscopes contain a set of six boxes (yellow, cyan, green, magenta, red, and blue) representing 75% color bars, and another set for 100% color bars. These boxes correspond to sections C and D of the test pattern file ",
              "type": "text"
            },
            {
              "code": "QuickTime_Test_Pattern_HD.mov,",
              "type": "codeVoice"
            },
            {
              "text": " shown below:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3712975",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Consider the color correct if the representation’s color vector “hits” inside the corresponding box during testing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These boxes typically represent only HD or only SD color bars, not content converted from one standard to the other. For example, Rec. 709 (HD) 75% red is different from Rec. 601 (SD) 75% red, and a converted signal typically wouldn’t either hit HD or SD targets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To learn how to use test pattern files to confirm the proper color management of your app’s video, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files#Open-Test-Patterns-and-Verify-Color-Characteristics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Analyze-Your-Video-Signal-Using-a-Waveform-Monitor",
          "level": 3,
          "text": "Analyze Your Video Signal Using a Waveform Monitor",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A waveform monitor displays the composite of the amplitude of all lines in a given frame of video over time. Among other things, this instrument helps ensure the use of all values with no truncated (crushed) range of blacks or whites.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Output your video to a waveform analyzer and view the test pattern on a waveform monitor. Verify the gamma, quantization errors, and range expansion or compression.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following are elements of the QuickTime Test Pattern movie file to examine on a waveform monitor:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Black boxes on a black background. A test signal on the waveform monitor visible as 16 steps beginning with true black (row A in the figure above).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Gradient. A monotonically increasing gradient that includes super-whites and super-blacks. You should expect rendering processes that include full-range RGB to crush such a gradient (row B in figure above). The result on the waveform monitor should range from true-black to full-white. However, you may see clamping of the beginning and end of the repeating pattern to black or white for the extent of the range corresponding to super-white and super-black. The gradient should form a straight line on the waveform monitor’s display (otherwise it indicates a gamma conversion). Any uneven lines on the display indicate the effects of quantization.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "White boxes on a full-white background. On the waveform monitor, this portion of the test signal should be visible as 16 steps beginning from full-white (row F in the figure above).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Quantized gradient. The waveform monitor plots the area under those targets for the gamma of the signal (row E in the figure above).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color": {
      "abstract": [
        {
          "text": "Check color reproduction for a video in your app by using test patterns, video test equipment, and light-measurement instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Evaluating an App’s Video Color",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments": {
      "abstract": [
        {
          "text": "Measure front-of-screen luminance by using test pattern files with a spectroradiometer or colorimeter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments",
      "kind": "article",
      "role": "article",
      "title": "Evaluating an App’s Video Color Using Light-Measurement Instruments",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files": {
      "abstract": [
        {
          "text": "Check color reproduction of your app or workflow by using test pattern files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
      "kind": "article",
      "role": "article",
      "title": "Evaluating Video Using QuickTime Test Pattern Files",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-video-using-quicktime-test-pattern-files"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files#Open-Test-Patterns-and-Verify-Color-Characteristics": {
      "abstract": [],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files#Open-Test-Patterns-and-Verify-Color-Characteristics",
      "kind": "section",
      "title": "Open Test Patterns and Verify Color Characteristics",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-video-using-quicktime-test-pattern-files#Open-Test-Patterns-and-Verify-Color-Characteristics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3712975": {
      "alt": "A QuickTime test pattern HD movie file with color and grayscale patterns. The top of the movie contains dark levels, the middle has multi-colored bars and the bottom has white light levels.",
      "identifier": "media-3712975",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4a1c3e93f3eb149a84b1cab61fb6de7e/media-3712975@2x.png"
        }
      ]
    },
    "media-3733686": {
      "alt": "An illustration showing two test pattern analyses. At the top is an analysis using a vectorscope, and at the bottom is an analysis using a waveform analyzer.",
      "identifier": "media-3733686",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b03232728d1e34935021e9254d30cd9b/media-3733686@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Video-Evaluation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
      ],
      "title": "Video Evaluation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Video-Evaluation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-video-using-quicktime-test-pattern-files",
                "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color-using-light-measurement-instruments"
              ],
              "title": "Video Evaluation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/evaluating-an-app-s-video-color-using-video-test-equipment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
