{
  "abstract": [
    {
      "text": "Configure an export session to output media in standard sizes and formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/export-presets"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Export Presets"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the preset name constants to initialize an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1280x720": {
      "abstract": [
        {
          "text": "A preset to export a 1280 by 720 movie that contains H.264 video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset1280x720"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1280x720",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset1280x720"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPreset1280x720",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpreset1280x720"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1920x1080": {
      "abstract": [
        {
          "text": "A preset to export a 1920 by 1080 movie that contains H.264 video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset1920x1080"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1920x1080",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset1920x1080"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPreset1920x1080",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpreset1920x1080"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset3840x2160": {
      "abstract": [
        {
          "text": "A preset to export a 3840 by 2160 movie that contains H.264 video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset3840x2160"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset3840x2160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset3840x2160"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPreset3840x2160",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpreset3840x2160"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset640x480": {
      "abstract": [
        {
          "text": "A preset to export a 640 by 480 movie that contains H.264 video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset640x480"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset640x480",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset640x480"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPreset640x480",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpreset640x480"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset960x540": {
      "abstract": [
        {
          "text": "A preset to export a 960 by 540 movie that contains H.264 video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset960x540"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset960x540",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPreset960x540"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPreset960x540",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpreset960x540"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4A": {
      "abstract": [
        {
          "text": "A preset to export an audio-only MPEG 4 Audio file with appropriate iTunes gapless playback data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4A"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4A",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4A"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4A",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4a"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD": {
      "abstract": [
        {
          "text": "A preset to export a 1080p High Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V1080pHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V1080pHD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V1080pHD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v1080phd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD": {
      "abstract": [
        {
          "text": "A preset to export a 480p Standard Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V480pSD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V480pSD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V480pSD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v480psd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD": {
      "abstract": [
        {
          "text": "A preset to export a 720p High Definition format suitable for playing on Apple devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V720pHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4V720pHD"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4V720pHD",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4v720phd"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VAppleTV"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VAppleTV"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VAppleTV",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vappletv"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple devices when it streams over a cellular network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VCellular"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VCellular"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VCellular",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vcellular"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on Apple devices it streams over a WiFi network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VWiFi"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4VWiFi"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4VWiFi",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vwifi"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod": {
      "abstract": [
        {
          "text": "A preset to export a format suitable for playing on an iPod.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4ViPod"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleM4ViPod"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleM4ViPod",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetapplem4vipod"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes422LPCM": {
      "abstract": [
        {
          "text": "A preset to export a QuickTime movie with Apple ProRes 422 video and LPCM audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleProRes422LPCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes422LPCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleProRes422LPCM"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleProRes422LPCM",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetappleprores422lpcm"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes4444LPCM": {
      "abstract": [
        {
          "text": "A preset to export a QuickTime movie with Apple ProRes 4444 video and LPCM audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleProRes4444LPCM"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes4444LPCM",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetAppleProRes4444LPCM"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetAppleProRes4444LPCM",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetappleprores4444lpcm"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080": {
      "abstract": [
        {
          "text": "A preset to export a 1920 by 1080 movie that contains HEVC video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC1920x1080"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC1920x1080"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVC1920x1080",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevc1920x1080"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080WithAlpha": {
      "abstract": [
        {
          "text": "A preset to export a 1920 by 1080 movie that contains HEVC video with alpha and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC1920x1080WithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080WithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC1920x1080WithAlpha"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVC1920x1080WithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevc1920x1080withalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160": {
      "abstract": [
        {
          "text": "A preset to export a 3840 by 2160 movie that contains HEVC video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC3840x2160"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC3840x2160"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVC3840x2160",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevc3840x2160"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160WithAlpha": {
      "abstract": [
        {
          "text": "A preset to export a 3840 by 2160 movie that contains HEVC video with alpha and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC3840x2160WithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160WithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC3840x2160WithAlpha"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVC3840x2160WithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevc3840x2160withalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC7680x4320": {
      "abstract": [
        {
          "text": "A preset to export a 7680 by 4320 movie that contains HEVC video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC7680x4320"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC7680x4320",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVC7680x4320"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVC7680x4320",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevc7680x4320"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQuality": {
      "abstract": [
        {
          "text": "A preset to export the highest available video quality and HEVC video compression.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVCHighestQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVCHighestQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVCHighestQuality",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevchighestquality"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQualityWithAlpha": {
      "abstract": [
        {
          "text": "A preset to export the highest available video quality and HEVC video compression with alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVCHighestQualityWithAlpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQualityWithAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHEVCHighestQualityWithAlpha"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHEVCHighestQualityWithAlpha",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethevchighestqualitywithalpha"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHighestQuality": {
      "abstract": [
        {
          "text": "A preset to export a high-quality movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHighestQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHighestQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetHighestQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetHighestQuality",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresethighestquality"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetLowQuality": {
      "abstract": [
        {
          "text": "A preset to export a low-quality movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetLowQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetLowQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetLowQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetLowQuality",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetlowquality"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC1440x1440": {
      "abstract": [
        {
          "text": "A preset to export a 1440 by 1440 movie that contains MV-HEVC video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMVHEVC1440x1440"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC1440x1440",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMVHEVC1440x1440"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetMVHEVC1440x1440",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetmvhevc1440x1440"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC960x960": {
      "abstract": [
        {
          "text": "A preset to export a 960 by 960 movie that contains MV-HEVC video and AAC audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMVHEVC960x960"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC960x960",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMVHEVC960x960"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetMVHEVC960x960",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetmvhevc960x960"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMediumQuality": {
      "abstract": [
        {
          "text": "A preset to export a medium-quality movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMediumQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMediumQuality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetMediumQuality"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetMediumQuality",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetmediumquality"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetPassthrough": {
      "abstract": [
        {
          "text": "A preset to export the asset in its current format, unless otherwise prohibited.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetPassthrough"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetPassthrough",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportPresetPassthrough"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportPresetPassthrough",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportpresetpassthrough"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession": {
      "abstract": [
        {
          "text": "An object that exports assets in a format that you specify using an export preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportSession",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/exportSessionWithAsset:presetName:": {
      "abstract": [
        {
          "text": "Returns a new asset export session that uses the specified preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "exportSessionWithAsset:presetName:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/exportSessionWithAsset:presetName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exportSessionWithAsset:presetName:"
        }
      ],
      "role": "symbol",
      "title": "exportSessionWithAsset:presetName:",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/exportsessionwithasset:presetname:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/init(asset:presetName:)": {
      "abstract": [
        {
          "text": "Creates an export session with a preset configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "asset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAsset",
          "text": "AVAsset"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "presetName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/init(asset:presetName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAsset:presetName:"
        }
      ],
      "role": "symbol",
      "title": "init(asset:presetName:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession/init(asset:presetname:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-an-Export-Session",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/init(asset:presetName:)"
      ],
      "title": "Creating an Export Session"
    }
  ],
  "topicSections": [
    {
      "anchor": "Quality-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetLowQuality",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMediumQuality",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHighestQuality",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQuality",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQualityWithAlpha"
      ],
      "title": "Quality Presets"
    },
    {
      "anchor": "Size-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset640x480",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset960x540",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1280x720",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1920x1080",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset3840x2160"
      ],
      "title": "Size Presets"
    },
    {
      "anchor": "HEVC-Size-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080WithAlpha",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160WithAlpha",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC7680x4320"
      ],
      "title": "HEVC Size Presets"
    },
    {
      "anchor": "MV-HEVC-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC960x960",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC1440x1440"
      ],
      "title": "MV-HEVC Presets"
    },
    {
      "anchor": "M4V-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi"
      ],
      "title": "M4V Presets"
    },
    {
      "anchor": "Apple-ProRes-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes422LPCM",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes4444LPCM"
      ],
      "title": "Apple ProRes Presets"
    },
    {
      "anchor": "Passthrough-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetPassthrough"
      ],
      "title": "Passthrough Presets"
    },
    {
      "anchor": "Audio-only-Presets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4A"
      ],
      "title": "Audio-only Presets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Quality-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetLowQuality",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMediumQuality",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHighestQuality",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQuality",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVCHighestQualityWithAlpha"
              ],
              "title": "Quality Presets"
            },
            {
              "anchor": "Size-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset640x480",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset960x540",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1280x720",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset1920x1080",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPreset3840x2160"
              ],
              "title": "Size Presets"
            },
            {
              "anchor": "HEVC-Size-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC1920x1080WithAlpha",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC3840x2160WithAlpha",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetHEVC7680x4320"
              ],
              "title": "HEVC Size Presets"
            },
            {
              "anchor": "MV-HEVC-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC960x960",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetMVHEVC1440x1440"
              ],
              "title": "MV-HEVC Presets"
            },
            {
              "anchor": "M4V-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V480pSD",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V720pHD",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4V1080pHD",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4ViPod",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VAppleTV",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VCellular",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4VWiFi"
              ],
              "title": "M4V Presets"
            },
            {
              "anchor": "Apple-ProRes-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes422LPCM",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleProRes4444LPCM"
              ],
              "title": "Apple ProRes Presets"
            },
            {
              "anchor": "Passthrough-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetPassthrough"
              ],
              "title": "Passthrough Presets"
            },
            {
              "anchor": "Audio-only-Presets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportPresetAppleM4A"
              ],
              "title": "Audio-only Presets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-an-Export-Session",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/exportSessionWithAsset:presetName:",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession/init(asset:presetName:)"
              ],
              "title": "Creating an Export Session"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVCHighestQuality/title",
          "value": "AVAssetExportPresetHEVCHighestQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVCHighestQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVCHighestQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVCHighestQualityWithAlpha/title",
          "value": "AVAssetExportPresetHEVCHighestQualityWithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVCHighestQualityWithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVCHighestQualityWithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V480pSD/title",
          "value": "AVAssetExportPresetAppleM4V480pSD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V480pSD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V480pSD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V720pHD/title",
          "value": "AVAssetExportPresetAppleM4V720pHD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V720pHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V720pHD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC3840x2160WithAlpha/title",
          "value": "AVAssetExportPresetHEVC3840x2160WithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC3840x2160WithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVC3840x2160WithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V1080pHD/title",
          "value": "AVAssetExportPresetAppleM4V1080pHD"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4V1080pHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4V1080pHD"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset1920x1080/title",
          "value": "AVAssetExportPreset1920x1080"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset1920x1080/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPreset1920x1080"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/title",
          "value": "AVAssetExportSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHighestQuality/title",
          "value": "AVAssetExportPresetHighestQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHighestQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHighestQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetLowQuality/title",
          "value": "AVAssetExportPresetLowQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetLowQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetLowQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMVHEVC1440x1440/title",
          "value": "AVAssetExportPresetMVHEVC1440x1440"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMVHEVC1440x1440/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetMVHEVC1440x1440"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC7680x4320/title",
          "value": "AVAssetExportPresetHEVC7680x4320"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC7680x4320/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVC7680x4320"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4A/title",
          "value": "AVAssetExportPresetAppleM4A"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4A/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4A"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VWiFi/title",
          "value": "AVAssetExportPresetAppleM4VWiFi"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VWiFi/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VWiFi"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleProRes4444LPCM/title",
          "value": "AVAssetExportPresetAppleProRes4444LPCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleProRes4444LPCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleProRes4444LPCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1init(asset:presetName:)/title",
          "value": "initWithAsset:presetName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession~1init(asset:presetName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAsset:presetName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset640x480/title",
          "value": "AVAssetExportPreset640x480"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset640x480/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPreset640x480"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset3840x2160/title",
          "value": "AVAssetExportPreset3840x2160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset3840x2160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPreset3840x2160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleProRes422LPCM/title",
          "value": "AVAssetExportPresetAppleProRes422LPCM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleProRes422LPCM/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleProRes422LPCM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC1920x1080WithAlpha/title",
          "value": "AVAssetExportPresetHEVC1920x1080WithAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC1920x1080WithAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVC1920x1080WithAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC1920x1080/title",
          "value": "AVAssetExportPresetHEVC1920x1080"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC1920x1080/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVC1920x1080"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMediumQuality/title",
          "value": "AVAssetExportPresetMediumQuality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMediumQuality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetMediumQuality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VAppleTV/title",
          "value": "AVAssetExportPresetAppleM4VAppleTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VAppleTV/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VAppleTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset960x540/title",
          "value": "AVAssetExportPreset960x540"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset960x540/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPreset960x540"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMVHEVC960x960/title",
          "value": "AVAssetExportPresetMVHEVC960x960"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetMVHEVC960x960/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetMVHEVC960x960"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset1280x720/title",
          "value": "AVAssetExportPreset1280x720"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPreset1280x720/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPreset1280x720"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetPassthrough/title",
          "value": "AVAssetExportPresetPassthrough"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetPassthrough/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetPassthrough"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VCellular/title",
          "value": "AVAssetExportPresetAppleM4VCellular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4VCellular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4VCellular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC3840x2160/title",
          "value": "AVAssetExportPresetHEVC3840x2160"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetHEVC3840x2160/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetHEVC3840x2160"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4ViPod/title",
          "value": "AVAssetExportPresetAppleM4ViPod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportPresetAppleM4ViPod/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportPresetAppleM4ViPod"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/export-presets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/export-presets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
