{
  "abstract": [
    {
      "text": "Specify options to configure the initialization of a movie.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/initialization-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Initialization Options"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie": {
      "abstract": [
        {
          "text": "An object that represents an audiovisual container that conforms to the QuickTime movie file format or a related format like MPEG-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMovie"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMovie"
        }
      ],
      "role": "symbol",
      "title": "AVMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(data:options:)": {
      "abstract": [
        {
          "text": "Creates a movie object from a movie file’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(data:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:options:"
        }
      ],
      "role": "symbol",
      "title": "init(data:options:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie/init(data:options:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:)": {
      "abstract": [
        {
          "text": "Creates a movie that models the media at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(url:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie/init(url:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:options:)": {
      "abstract": [
        {
          "text": "Creates a movie object from a movie header stored in a QuickTime movie file of ISO base media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "init(url:options:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie/init(url:options:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithData:options:": {
      "abstract": [
        {
          "text": "Returns a new movie object from a movie file’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "movieWithData:options:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithData:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movieWithData:options:"
        }
      ],
      "role": "symbol",
      "title": "movieWithData:options:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie/moviewithdata:options:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithURL:options:": {
      "abstract": [
        {
          "text": "Returns a new movie object from a movie header stored in a QuickTime movie file of ISO base media file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "movieWithURL:options:"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithURL:options:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "movieWithURL:options:"
        }
      ],
      "role": "symbol",
      "title": "movieWithURL:options:",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie/moviewithurl:options:"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieReferenceRestrictionsKey": {
      "abstract": [
        {
          "text": "A key that specifies restrictions for a movie to use when it resolves references to external media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMovieReferenceRestrictionsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieReferenceRestrictionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMovieReferenceRestrictionsKey"
        }
      ],
      "role": "symbol",
      "title": "AVMovieReferenceRestrictionsKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmoviereferencerestrictionskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieShouldSupportAliasDataReferencesKey": {
      "abstract": [
        {
          "text": "A key that specifies a Boolean value that indicates whether the system parses and resolves alias data references in the movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMovieShouldSupportAliasDataReferencesKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieShouldSupportAliasDataReferencesKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMovieShouldSupportAliasDataReferencesKey"
        }
      ],
      "role": "symbol",
      "title": "AVMovieShouldSupportAliasDataReferencesKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovieshouldsupportaliasdatareferenceskey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies": {
      "abstract": [
        {
          "text": "Access the contents of a QuickTime movie file, and perform sample-level edits of its media tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "QuickTime movies",
      "type": "topic",
      "url": "/documentation/avfoundation/quicktime-movies"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Movie",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:options:)",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(data:options:)"
      ],
      "title": "Creating a Movie"
    }
  ],
  "topicSections": [
    {
      "anchor": "Options",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieReferenceRestrictionsKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieShouldSupportAliasDataReferencesKey"
      ],
      "title": "Options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Options",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieReferenceRestrictionsKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieShouldSupportAliasDataReferencesKey"
              ],
              "title": "Options"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Movie",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithURL:options:",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(url:options:)",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/movieWithData:options:",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie/init(data:options:)"
              ],
              "title": "Creating a Movie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/title",
          "value": "AVMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieShouldSupportAliasDataReferencesKey/title",
          "value": "AVMovieShouldSupportAliasDataReferencesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieShouldSupportAliasDataReferencesKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovieShouldSupportAliasDataReferencesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie~1init(data:options:)/title",
          "value": "initWithData:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie~1init(data:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieReferenceRestrictionsKey/title",
          "value": "AVMovieReferenceRestrictionsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieReferenceRestrictionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovieReferenceRestrictionsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie~1init(url:options:)/title",
          "value": "initWithURL:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie~1init(url:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:options:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/initialization-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/initialization-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
