{
  "abstract": [
    {
      "text": "The audio settings that apply to linear PCM audio formats.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/linear-pcm-format-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "title": "Linear PCM Format Settings"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings": {
      "abstract": [
        {
          "text": "The audio settings that apply to all audio formats that the audio player and recorder classes support.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Format Settings",
      "type": "topic",
      "url": "/documentation/avfoundation/format-settings"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout": {
      "abstract": [
        {
          "text": "An object that describes the roles of a set of audio channels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioChannelLayout"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioChannelLayout",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioChannelLayout"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat": {
      "abstract": [
        {
          "text": "An object that describes the representation of an audio format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioFormat"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioFormat",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVAudioFormat"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVChannelLayoutKey"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMBitDepthKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMBitDepthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMBitDepthKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMBitDepthKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVLinearPCMBitDepthKey"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsBigEndianKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsBigEndianKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMIsBigEndianKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVLinearPCMIsBigEndianKey"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsFloatKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsFloatKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsFloatKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMIsFloatKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVLinearPCMIsFloatKey"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleaved": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsNonInterleaved"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleaved",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMIsNonInterleaved",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVLinearPCMIsNonInterleaved"
    },
    "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "#define"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVLinearPCMIsNonInterleavedKey"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVLinearPCMIsNonInterleavedKey",
      "type": "topic",
      "url": "/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formats",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
        "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
        "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings"
      ],
      "title": "Formats"
    }
  ],
  "topicSections": [
    {
      "anchor": "Settings",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMBitDepthKey",
        "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
        "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsFloatKey",
        "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleaved"
      ],
      "title": "Settings"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Settings",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMBitDepthKey",
                "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsBigEndianKey",
                "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsFloatKey",
                "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleaved",
                "doc://com.apple.documentation/documentation/AVFAudio/AVLinearPCMIsNonInterleavedKey"
              ],
              "title": "Settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formats",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioFormat",
                "doc://com.apple.documentation/documentation/AVFAudio/AVAudioChannelLayout",
                "doc://com.apple.documentation/documentation/AVFAudio/AVChannelLayoutKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/format-settings"
              ],
              "title": "Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioFormat/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioFormat"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVAudioChannelLayout/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVAudioChannelLayout"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVLinearPCMIsNonInterleaved/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsNonInterleaved"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVLinearPCMBitDepthKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVLinearPCMBitDepthKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVChannelLayoutKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVLinearPCMIsFloatKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsFloatKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVFAudio~1AVLinearPCMIsBigEndianKey/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVLinearPCMIsBigEndianKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/linear-pcm-format-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/linear-pcm-format-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
