{
  "abstract": [
    {
      "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media assets"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty": {
      "abstract": [
        {
          "text": "A base class for asynchronous properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAnyAsyncProperty"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAnyAsyncProperty"
        }
      ],
      "role": "symbol",
      "title": "AVAnyAsyncProperty",
      "type": "topic",
      "url": "/documentation/avfoundation/avanyasyncproperty"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset": {
      "abstract": [
        {
          "text": "An object that models timed audiovisual media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsset"
        }
      ],
      "role": "symbol",
      "title": "AVAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack": {
      "abstract": [
        {
          "text": "An object that models a track of media that an asset contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup": {
      "abstract": [
        {
          "text": "A group of related tracks in an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroup"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackGroup"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrackGroup",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettrackgroup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment": {
      "abstract": [
        {
          "text": "An object that represents a time range segment of an asset track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetTrackSegment"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetTrackSegment"
        }
      ],
      "role": "symbol",
      "title": "AVAssetTrackSegment",
      "type": "topic",
      "url": "/documentation/avfoundation/avassettracksegment"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty": {
      "abstract": [
        {
          "text": "An asynchronous property that constrains its type and value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsyncProperty"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsyncProperty"
        }
      ],
      "role": "symbol",
      "title": "AVAsyncProperty",
      "type": "topic",
      "url": "/documentation/avfoundation/avasyncproperty"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading": {
      "abstract": [
        {
          "text": "A protocol that defines the interface to load media data asynchronously.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAsynchronousKeyValueLoading"
        }
      ],
      "role": "symbol",
      "title": "AVAsynchronousKeyValueLoading",
      "type": "topic",
      "url": "/documentation/avfoundation/avasynchronouskeyvalueloading"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding": {
      "abstract": [
        {
          "text": "A protocol that defines whether an asset supports fragment minding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentMinding"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentMinding"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentMinding",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentminding"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset": {
      "abstract": [
        {
          "text": "An asset with a duration that the system can extend without modifying its existing media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedAsset"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetMinder": {
      "abstract": [
        {
          "text": "An object that periodically checks whether the system adds new fragments to a fragmented asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedAssetMinder"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetMinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedAssetMinder"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedAssetMinder",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedassetminder"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetTrack": {
      "abstract": [
        {
          "text": "An object that provides the track-level interface to inspect a fragmented asset’s media tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedAssetTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedAssetTrack"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedAssetTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedassettrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataExtraAttributeKey": {
      "abstract": [
        {
          "text": "A structure that defines keys for extra metadata attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataExtraAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataExtraAttributeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataExtraAttributeKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataExtraAttributeKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataextraattributekey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFormat": {
      "abstract": [
        {
          "text": "A structure that defines metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataFormat"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataFormat"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataFormat",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataformat"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier": {
      "abstract": [
        {
          "text": "A structure that defines identifiers for metadata formats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataIdentifier"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataIdentifier",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataidentifier"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItem": {
      "abstract": [
        {
          "text": "A metadata item for an audiovisual asset or one of its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataItem"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataitem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItemFilter": {
      "abstract": [
        {
          "text": "An object that filters selected information from a metadata item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataItemFilter"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItemFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataItemFilter"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataItemFilter",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadataitemfilter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKey",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakey"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKeySpace": {
      "abstract": [
        {
          "text": "A structure that defines a metadata key space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetadataKeySpace"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKeySpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetadataKeySpace"
        }
      ],
      "role": "symbol",
      "title": "AVMetadataKeySpace",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetadatakeyspace"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMetadataItem": {
      "abstract": [
        {
          "text": "A mutable metadata item for an audiovisual asset or for one of its tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableMetadataItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMetadataItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableMetadataItem"
        }
      ],
      "role": "symbol",
      "title": "AVMutableMetadataItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablemetadataitem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty": {
      "abstract": [
        {
          "text": "An asynchronous property that constrains its type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPartialAsyncProperty"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPartialAsyncProperty"
        }
      ],
      "role": "symbol",
      "title": "AVPartialAsyncProperty",
      "type": "topic",
      "url": "/documentation/avfoundation/avpartialasyncproperty"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset": {
      "abstract": [
        {
          "text": "An asset that represents media at a local or remote URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVURLAsset"
        }
      ],
      "role": "symbol",
      "title": "AVURLAsset",
      "type": "topic",
      "url": "/documentation/avfoundation/avurlasset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously": {
      "abstract": [
        {
          "text": "Build responsive apps by using language-level concurrency features to efficiently load media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously",
      "kind": "article",
      "role": "article",
      "title": "Loading media data asynchronously",
      "type": "topic",
      "url": "/documentation/avfoundation/loading-media-data-asynchronously"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing": {
      "abstract": [
        {
          "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media reading and writing",
      "type": "topic",
      "url": "/documentation/avfoundation/media-reading-and-writing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities": {
      "abstract": [
        {
          "text": "Identify the types of content and file formats that AVFoundation supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media types and utilities",
      "type": "topic",
      "url": "/documentation/avfoundation/media-types-and-utilities"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/retrieving-media-metadata": {
      "abstract": [
        {
          "text": "Load descriptive metadata for media assets and their tracks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/retrieving-media-metadata",
      "kind": "article",
      "role": "article",
      "title": "Retrieving media metadata",
      "type": "topic",
      "url": "/documentation/avfoundation/retrieving-media-metadata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings": {
      "abstract": [
        {
          "text": "Configure video processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video settings",
      "type": "topic",
      "url": "/documentation/avfoundation/video-settings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
      ],
      "title": "Common"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Assets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup"
      ],
      "title": "Assets"
    },
    {
      "anchor": "Metadata",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/retrieving-media-metadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItem",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMetadataItem",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKeySpace",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataExtraAttributeKey",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFormat",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItemFilter"
      ],
      "title": "Metadata"
    },
    {
      "anchor": "Property-loading",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsyncProperty",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPartialAsyncProperty",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAnyAsyncProperty"
      ],
      "title": "Property loading"
    },
    {
      "anchor": "Fragmented-assets",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetMinder",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding"
      ],
      "title": "Fragmented assets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/loading-media-data-asynchronously"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Assets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVURLAsset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackSegment",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetTrackGroup"
              ],
              "title": "Assets"
            },
            {
              "anchor": "Metadata",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/retrieving-media-metadata",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItem",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMetadataItem",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataIdentifier",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataKeySpace",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataExtraAttributeKey",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataFormat",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetadataItemFilter"
              ],
              "title": "Metadata"
            },
            {
              "anchor": "Property-loading",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsynchronousKeyValueLoading"
              ],
              "title": "Property loading"
            },
            {
              "anchor": "Fragmented-assets",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAsset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedAssetMinder",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding"
              ],
              "title": "Fragmented assets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/title",
          "value": "AVAsynchronousKeyValueLoading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsynchronousKeyValueLoading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsynchronousKeyValueLoading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/title",
          "value": "AVAssetTrackSegment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackSegment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackSegment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItemFilter/title",
          "value": "AVMetadataItemFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItemFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataItemFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItemFilter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataItemFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFormat/title",
          "value": "AVMetadataFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataExtraAttributeKey/title",
          "value": "AVMetadataExtraAttributeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataExtraAttributeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataExtraAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataExtraAttributeKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataExtraAttributeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItem/title",
          "value": "AVMetadataItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/title",
          "value": "AVURLAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVURLAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVURLAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/title",
          "value": "AVFragmentedAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/title",
          "value": "AVAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetMinder/title",
          "value": "AVFragmentedAssetMinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetMinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAssetMinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetMinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAssetMinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetTrack/title",
          "value": "AVFragmentedAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMetadataItem/title",
          "value": "AVMutableMetadataItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMetadataItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMetadataItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMetadataItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMetadataItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/title",
          "value": "AVMetadataIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKeySpace/title",
          "value": "AVMetadataKeySpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKeySpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKeySpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKeySpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/title",
          "value": "AVMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/title",
          "value": "AVAssetTrackGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrackGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrackGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/title",
          "value": "AVAssetTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/title",
          "value": "AVFragmentMinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentMinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentMinding"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/media-assets"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/media-assets"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
