{
  "abstract": [
    {
      "text": "Read images from video, export to alternative formats, and perform sample-level reading and writing of media data.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/media-reading-and-writing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Media reading and writing"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession": {
      "abstract": [
        {
          "text": "An object that exports assets in a format that you specify using an export preset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetExportSession"
        }
      ],
      "role": "symbol",
      "title": "AVAssetExportSession",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetexportsession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator": {
      "abstract": [
        {
          "text": "An object that generates images from a video asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetImageGenerator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetImageGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVAssetImageGenerator",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetimagegenerator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader": {
      "abstract": [
        {
          "text": "An object that reads media data from an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReader"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReader"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReader",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreader"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput": {
      "abstract": [
        {
          "text": "An object that reads audio samples that result from mixing audio from one or more tracks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderAudioMixOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderAudioMixOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderAudioMixOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreaderaudiomixoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface to read media samples from an asset reader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreaderoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor": {
      "abstract": [
        {
          "text": "An object that creates timed metadata group objects for an asset track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderOutputMetadataAdaptor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderOutputMetadataAdaptor"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderOutputMetadataAdaptor",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreaderoutputmetadataadaptor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput": {
      "abstract": [
        {
          "text": "An object that reads sample references from an asset track.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderSampleReferenceOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderSampleReferenceOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderSampleReferenceOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreadersamplereferenceoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput": {
      "abstract": [
        {
          "text": "An object that reads media data from a single track of an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderTrackOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderTrackOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderTrackOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreadertrackoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput": {
      "abstract": [
        {
          "text": "An object that reads composited video frames from one or more tracks of an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetReaderVideoCompositionOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetReaderVideoCompositionOutput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetReaderVideoCompositionOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetreadervideocompositionoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter": {
      "abstract": [
        {
          "text": "An object that writes media data to a container file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriter"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriter"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriter",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriter"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInput": {
      "abstract": [
        {
          "text": "An object that appends media samples to a track in an asset writer’s output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriterInput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriterInput"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriterInput",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriterinput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputGroup": {
      "abstract": [
        {
          "text": "A group of inputs with tracks that are mutually exclusive to each other for playback or processing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputGroup"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputGroup"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriterInputGroup",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriterinputgroup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputMetadataAdaptor": {
      "abstract": [
        {
          "text": "An object that appends timed metadata groups to an asset writer input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputMetadataAdaptor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputMetadataAdaptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputMetadataAdaptor"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriterInputMetadataAdaptor",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriterinputmetadataadaptor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputPixelBufferAdaptor": {
      "abstract": [
        {
          "text": "An object that appends video samples to an asset writer input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputPixelBufferAdaptor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputPixelBufferAdaptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputPixelBufferAdaptor"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriterInputPixelBufferAdaptor",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriterinputpixelbufferadaptor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputTaggedPixelBufferGroupAdaptor": {
      "abstract": [
        {
          "text": "An object that appends tagged buffer groups to an asset writer input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputTaggedPixelBufferGroupAdaptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor"
        }
      ],
      "role": "symbol",
      "title": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetwriterinputtaggedpixelbuffergroupadaptor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsAssistant": {
      "abstract": [
        {
          "text": "An object that builds audio and video output settings dictionaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVOutputSettingsAssistant"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsAssistant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVOutputSettingsAssistant"
        }
      ],
      "role": "symbol",
      "title": "AVOutputSettingsAssistant",
      "type": "topic",
      "url": "/documentation/avfoundation/avoutputsettingsassistant"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings": {
      "abstract": [
        {
          "text": "Configure audio processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio settings",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/caption-authoring": {
      "abstract": [
        {
          "text": "Create captions and subtitles in industry-standard formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/caption-authoring",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Caption Authoring",
      "type": "topic",
      "url": "/documentation/avfoundation/caption-authoring"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/converting-side-by-side-3d-video-to-multiview-hevc-and-spatial-video": {
      "abstract": [
        {
          "text": "Create video content for visionOS by converting an existing 3D HEVC file to a multiview HEVC format, optionally adding spatial metadata to create a spatial video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/converting-side-by-side-3d-video-to-multiview-hevc-and-spatial-video",
      "kind": "article",
      "role": "sampleCode",
      "title": "Converting side-by-side 3D video to multiview HEVC and spatial video",
      "type": "topic",
      "url": "/documentation/avfoundation/converting-side-by-side-3d-video-to-multiview-hevc-and-spatial-video"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/creating-images-from-a-video-asset": {
      "abstract": [
        {
          "text": "Display images for specific times within the media timeline by generating images from a video’s frames.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/creating-images-from-a-video-asset",
      "kind": "article",
      "role": "article",
      "title": "Creating images from a video asset",
      "type": "topic",
      "url": "/documentation/avfoundation/creating-images-from-a-video-asset"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color": {
      "abstract": [
        {
          "text": "Check color reproduction for a video in your app by using test patterns, video test equipment, and light-measurement instruments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Evaluating an App’s Video Color",
      "type": "topic",
      "url": "/documentation/avfoundation/evaluating-an-app-s-video-color"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats": {
      "abstract": [
        {
          "text": "Convert an existing movie file to a different format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats",
      "kind": "article",
      "role": "article",
      "title": "Exporting video to alternative formats",
      "type": "topic",
      "url": "/documentation/avfoundation/exporting-video-to-alternative-formats"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets": {
      "abstract": [
        {
          "text": "Load media assets from files and streams to inspect their attributes, tracks, and embedded metadata.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media assets",
      "type": "topic",
      "url": "/documentation/avfoundation/media-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities": {
      "abstract": [
        {
          "text": "Identify the types of content and file formats that AVFoundation supports.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media types and utilities",
      "type": "topic",
      "url": "/documentation/avfoundation/media-types-and-utilities"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files": {
      "abstract": [
        {
          "text": "Render single images for the left eye and right eye from a multiview High Efficiency Video Coding format file by reading individual video frames.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files",
      "kind": "article",
      "role": "sampleCode",
      "title": "Reading multiview 3D video files",
      "type": "topic",
      "url": "/documentation/avfoundation/reading-multiview-3d-video-files"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/tagging-media-with-video-color-information": {
      "abstract": [
        {
          "text": "Inspect and set video color space information when writing and transcoding media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/tagging-media-with-video-color-information",
      "kind": "article",
      "role": "article",
      "title": "Tagging Media with Video Color Information",
      "type": "topic",
      "url": "/documentation/avfoundation/tagging-media-with-video-color-information"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings": {
      "abstract": [
        {
          "text": "Configure video processing settings using standard key and value constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video settings",
      "type": "topic",
      "url": "/documentation/avfoundation/video-settings"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/writing-fragmented-mpeg-4-files-for-http-live-streaming": {
      "abstract": [
        {
          "text": "Create an HTTP Live Streaming presentation by turning a movie file into a sequence of fragmented MPEG-4 files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/writing-fragmented-mpeg-4-files-for-http-live-streaming",
      "kind": "article",
      "role": "sampleCode",
      "title": "Writing Fragmented MPEG-4 Files for HTTP Live Streaming",
      "type": "topic",
      "url": "/documentation/avfoundation/writing-fragmented-mpeg-4-files-for-http-live-streaming"
    },
    "doc://com.apple.documentation/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata": {
      "abstract": [
        {
          "text": "Add spatial metadata to stereo photos and videos to create spatial media for viewing on Apple Vision Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata",
      "kind": "article",
      "role": "article",
      "title": "Creating spatial photos and videos with spatial metadata",
      "type": "topic",
      "url": "/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Common",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
      ],
      "title": "Common"
    }
  ],
  "topicSections": [
    {
      "anchor": "Media-export",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession"
      ],
      "title": "Media export"
    },
    {
      "anchor": "Image-generation",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/creating-images-from-a-video-asset",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"
      ],
      "title": "Image generation"
    },
    {
      "anchor": "Media-reading",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor"
      ],
      "title": "Media reading"
    },
    {
      "anchor": "Media-writing",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/writing-fragmented-mpeg-4-files-for-http-live-streaming",
        "doc://com.apple.avfoundation/documentation/AVFoundation/converting-side-by-side-3d-video-to-multiview-hevc-and-spatial-video",
        "doc://com.apple.documentation/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata",
        "doc://com.apple.avfoundation/documentation/AVFoundation/tagging-media-with-video-color-information",
        "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsAssistant",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputPixelBufferAdaptor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputTaggedPixelBufferGroupAdaptor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputMetadataAdaptor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputGroup"
      ],
      "title": "Media writing"
    },
    {
      "anchor": "Captions",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/caption-authoring"
      ],
      "title": "Captions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Media-export",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/exporting-video-to-alternative-formats",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetExportSession"
              ],
              "title": "Media export"
            },
            {
              "anchor": "Image-generation",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/creating-images-from-a-video-asset",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetImageGenerator"
              ],
              "title": "Image generation"
            },
            {
              "anchor": "Media-reading",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/reading-multiview-3d-video-files",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReader",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderTrackOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderAudioMixOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderVideoCompositionOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderSampleReferenceOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetReaderOutputMetadataAdaptor"
              ],
              "title": "Media reading"
            },
            {
              "anchor": "Media-writing",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/writing-fragmented-mpeg-4-files-for-http-live-streaming",
                "doc://com.apple.avfoundation/documentation/AVFoundation/converting-side-by-side-3d-video-to-multiview-hevc-and-spatial-video",
                "doc://com.apple.documentation/documentation/ImageIO/Creating-spatial-photos-and-videos-with-spatial-metadata",
                "doc://com.apple.avfoundation/documentation/AVFoundation/tagging-media-with-video-color-information",
                "doc://com.apple.avfoundation/documentation/AVFoundation/evaluating-an-app-s-video-color",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVOutputSettingsAssistant",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriter",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputPixelBufferAdaptor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputTaggedPixelBufferGroupAdaptor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputMetadataAdaptor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetWriterInputGroup"
              ],
              "title": "Media writing"
            },
            {
              "anchor": "Captions",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/caption-authoring"
              ],
              "title": "Captions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Common",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-types-and-utilities",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-settings",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-settings"
              ],
              "title": "Common"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/title",
          "value": "AVAssetReaderOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputMetadataAdaptor/title",
          "value": "AVAssetWriterInputMetadataAdaptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputMetadataAdaptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputMetadataAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputMetadataAdaptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputMetadataAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/title",
          "value": "AVAssetWriter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputTaggedPixelBufferGroupAdaptor/title",
          "value": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputTaggedPixelBufferGroupAdaptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputTaggedPixelBufferGroupAdaptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputTaggedPixelBufferGroupAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputPixelBufferAdaptor/title",
          "value": "AVAssetWriterInputPixelBufferAdaptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputPixelBufferAdaptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputPixelBufferAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputPixelBufferAdaptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputPixelBufferAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInput/title",
          "value": "AVAssetWriterInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/title",
          "value": "AVAssetReader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/title",
          "value": "AVAssetImageGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetImageGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetImageGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/title",
          "value": "AVAssetExportSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetExportSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetExportSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/title",
          "value": "AVAssetReaderOutputMetadataAdaptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderOutputMetadataAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderOutputMetadataAdaptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderOutputMetadataAdaptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsAssistant/title",
          "value": "AVOutputSettingsAssistant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsAssistant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsAssistant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVOutputSettingsAssistant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVOutputSettingsAssistant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/title",
          "value": "AVAssetReaderTrackOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderTrackOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderTrackOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderTrackOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/title",
          "value": "AVAssetReaderSampleReferenceOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderSampleReferenceOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderSampleReferenceOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderSampleReferenceOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputGroup/title",
          "value": "AVAssetWriterInputGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetWriterInputGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetWriterInputGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/title",
          "value": "AVAssetReaderVideoCompositionOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderVideoCompositionOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderVideoCompositionOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderVideoCompositionOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/title",
          "value": "AVAssetReaderAudioMixOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderAudioMixOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetReaderAudioMixOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetReaderAudioMixOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/media-reading-and-writing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/media-reading-and-writing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
