{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/metric-event-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Metric event types"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information from different publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMergedMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMergedMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmergedmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming content key resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricContentKeyRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricContentKeyRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricContentKeyRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriccontentkeyrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent": {
      "abstract": [
        {
          "text": "An object that represents a metric event when an error occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricErrorEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricErrorEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricerrorevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent": {
      "abstract": [
        {
          "text": "A base class that represents a metric event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream": {
      "abstract": [
        {
          "text": "An object that allows clients to add publishers and then subscribe to specific metric event classes from those publishers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStream"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStream",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher": {
      "abstract": [
        {
          "text": "A type for objects that publish metric events to the event stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamPublisher"
        }
      ],
      "role": "symbol",
      "title": "AVMetricEventStreamPublisher",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreampublisher"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber": {
      "abstract": [
        {
          "text": "A type for objects that receive metric events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVMetricEventStreamSubscriber"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVMetricEventStreamSubscriber",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetriceventstreamsubscriber"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming media segment resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricHLSMediaSegmentRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricHLSMediaSegmentRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricHLSMediaSegmentRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrichlsmediasegmentrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a live streaming playlist resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricHLSPlaylistRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricHLSPlaylistRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricHLSPlaylistRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrichlsplaylistrequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent": {
      "abstract": [
        {
          "text": "An event that represents a media resource request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricMediaResourceRequestEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricMediaResourceRequestEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricMediaResourceRequestEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricmediaresourcerequestevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemInitialLikelyToKeepUpEvent": {
      "abstract": [
        {
          "text": "An event that represents the initial state for whether playback is likely to continue without stalling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemInitialLikelyToKeepUpEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemInitialLikelyToKeepUpEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemInitialLikelyToKeepUpEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemInitialLikelyToKeepUpEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeriteminitiallikelytokeepupevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemLikelyToKeepUpEvent": {
      "abstract": [
        {
          "text": "An event that represents when playback is likely to continue without stalling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemLikelyToKeepUpEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemLikelyToKeepUpEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemLikelyToKeepUpEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemLikelyToKeepUpEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemlikelytokeepupevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent": {
      "abstract": [
        {
          "text": "An event that represents the combined metrics for the entire playback session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemPlaybackSummaryEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemPlaybackSummaryEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemPlaybackSummaryEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemplaybacksummaryevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemRateChangeEvent": {
      "abstract": [
        {
          "text": "An event that represents when the playback rate changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemRateChangeEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemRateChangeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemRateChangeEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemRateChangeEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemratechangeevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekDidCompleteEvent": {
      "abstract": [
        {
          "text": "An event that represents when the playback seek completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemSeekDidCompleteEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekDidCompleteEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemSeekDidCompleteEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemSeekDidCompleteEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemseekdidcompleteevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekEvent": {
      "abstract": [
        {
          "text": "An event that represents when a playback seek occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemSeekEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemSeekEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemSeekEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemseekevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemStallEvent": {
      "abstract": [
        {
          "text": "An event that represents when playback stalls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemStallEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemStallEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemStallEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemStallEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemstallevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent": {
      "abstract": [
        {
          "text": "An event that represents when the player completes a variant switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemVariantSwitchEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemvariantswitchevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent": {
      "abstract": [
        {
          "text": "An event that represents when the player attempts a variant switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchStartEvent"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetricPlayerItemVariantSwitchStartEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMetricPlayerItemVariantSwitchStartEvent",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetricplayeritemvariantswitchstartevent"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics": {
      "abstract": [
        {
          "text": "An asynchronous stream of metric information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avmetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics": {
      "abstract": [
        {
          "text": "An object that provides metrics related to video playback quality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVVideoPerformanceMetrics"
        }
      ],
      "role": "symbol",
      "title": "AVVideoPerformanceMetrics",
      "type": "topic",
      "url": "/documentation/avfoundation/avvideoperformancemetrics"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMergedMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent"
      ],
      "title": "Metrics"
    }
  ],
  "topicSections": [
    {
      "anchor": "HTTP-Live-Streaming",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent"
      ],
      "title": "HTTP Live Streaming"
    },
    {
      "anchor": "Buffering",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemStallEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemLikelyToKeepUpEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemInitialLikelyToKeepUpEvent"
      ],
      "title": "Buffering"
    },
    {
      "anchor": "Transport-control",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemRateChangeEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekDidCompleteEvent",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekEvent"
      ],
      "title": "Transport control"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "HTTP-Live-Streaming",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricMediaResourceRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricContentKeyRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSMediaSegmentRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricHLSPlaylistRequestEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchStartEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemVariantSwitchEvent"
              ],
              "title": "HTTP Live Streaming"
            },
            {
              "anchor": "Buffering",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemStallEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemLikelyToKeepUpEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemInitialLikelyToKeepUpEvent"
              ],
              "title": "Buffering"
            },
            {
              "anchor": "Transport-control",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemPlaybackSummaryEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemRateChangeEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekDidCompleteEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricPlayerItemSeekEvent"
              ],
              "title": "Transport control"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVVideoPerformanceMetrics",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStream",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamPublisher",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEventStreamSubscriber",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricEvent",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMetricErrorEvent"
              ],
              "title": "Metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/title",
          "value": "AVMetricPlayerItemVariantSwitchEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/title",
          "value": "AVMetricPlayerItemPlaybackSummaryEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemPlaybackSummaryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemPlaybackSummaryEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemPlaybackSummaryEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemLikelyToKeepUpEvent/title",
          "value": "AVMetricPlayerItemLikelyToKeepUpEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemLikelyToKeepUpEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemLikelyToKeepUpEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemLikelyToKeepUpEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemLikelyToKeepUpEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemInitialLikelyToKeepUpEvent/title",
          "value": "AVMetricPlayerItemInitialLikelyToKeepUpEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemInitialLikelyToKeepUpEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemInitialLikelyToKeepUpEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemInitialLikelyToKeepUpEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemInitialLikelyToKeepUpEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/title",
          "value": "AVMetricEventStreamPublisher"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEventStreamPublisher/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEventStreamPublisher"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekDidCompleteEvent/title",
          "value": "AVMetricPlayerItemSeekDidCompleteEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekDidCompleteEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemSeekDidCompleteEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekDidCompleteEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemSeekDidCompleteEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekEvent/title",
          "value": "AVMetricPlayerItemSeekEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemSeekEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemSeekEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemSeekEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/title",
          "value": "AVMetricErrorEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricErrorEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricErrorEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/title",
          "value": "AVMetricMediaResourceRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricMediaResourceRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricMediaResourceRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/title",
          "value": "AVMetricHLSMediaSegmentRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSMediaSegmentRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSMediaSegmentRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSMediaSegmentRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemStallEvent/title",
          "value": "AVMetricPlayerItemStallEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemStallEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemStallEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemStallEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemStallEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/title",
          "value": "AVMetricHLSPlaylistRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSPlaylistRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricHLSPlaylistRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricHLSPlaylistRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemRateChangeEvent/title",
          "value": "AVMetricPlayerItemRateChangeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemRateChangeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemRateChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemRateChangeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemRateChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/title",
          "value": "AVMetricContentKeyRequestEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricContentKeyRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricContentKeyRequestEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricContentKeyRequestEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/title",
          "value": "AVVideoPerformanceMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVVideoPerformanceMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVVideoPerformanceMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/title",
          "value": "AVMetricEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/title",
          "value": "AVMetricPlayerItemVariantSwitchStartEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchStartEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMetricPlayerItemVariantSwitchStartEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMetricPlayerItemVariantSwitchStartEvent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/metric-event-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/metric-event-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
