{
  "abstract": [
    {
      "text": "Download streamed content to disk to allow offline playback, and define policies to automatically remove downloaded assets.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Offline playback and storage"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAggregateAssetDownloadTask": {
      "abstract": [
        {
          "text": "A task that downloads multiple media selections for an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAggregateAssetDownloadTask"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAggregateAssetDownloadTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAggregateAssetDownloadTask"
        }
      ],
      "role": "symbol",
      "title": "AVAggregateAssetDownloadTask",
      "type": "topic",
      "url": "/documentation/avfoundation/avaggregateassetdownloadtask"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetCache": {
      "abstract": [
        {
          "text": "An object that you use to inspect locally cached media data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetCache"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetCache",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetCache"
        }
      ],
      "role": "symbol",
      "title": "AVAssetCache",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetcache"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManagementPolicy": {
      "abstract": [
        {
          "text": "An object that defines a policy to automatically manage the storage of downloaded assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetDownloadStorageManagementPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManagementPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetDownloadStorageManagementPolicy"
        }
      ],
      "role": "symbol",
      "title": "AVAssetDownloadStorageManagementPolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetdownloadstoragemanagementpolicy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManager": {
      "abstract": [
        {
          "text": "An object that manages policies to automatically purge downloaded assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetDownloadStorageManager"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetDownloadStorageManager"
        }
      ],
      "role": "symbol",
      "title": "AVAssetDownloadStorageManager",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetdownloadstoragemanager"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadTask": {
      "abstract": [
        {
          "text": "A session used to download HTTP Live Streaming assets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetDownloadTask"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadTask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetDownloadTask"
        }
      ],
      "role": "symbol",
      "title": "AVAssetDownloadTask",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetdownloadtask"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadURLSession": {
      "abstract": [
        {
          "text": "A URL session that creates and executes asset download tasks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAssetDownloadURLSession"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadURLSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAssetDownloadURLSession"
        }
      ],
      "role": "symbol",
      "title": "AVAssetDownloadURLSession",
      "type": "topic",
      "url": "/documentation/avfoundation/avassetdownloadurlsession"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAssetDownloadStorageManagementPolicy": {
      "abstract": [
        {
          "text": "A mutable object that you use to create a new storage management policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableAssetDownloadStorageManagementPolicy"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAssetDownloadStorageManagementPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableAssetDownloadStorageManagementPolicy"
        }
      ],
      "role": "symbol",
      "title": "AVMutableAssetDownloadStorageManagementPolicy",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutableassetdownloadstoragemanagementpolicy"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback": {
      "abstract": [
        {
          "text": "Create custom controllers to play and synchronize the timing of sample buffer streams.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Sample buffer playback",
      "type": "topic",
      "url": "/documentation/avfoundation/sample-buffer-playback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay": {
      "abstract": [
        {
          "text": "Stream content wirelessly to other devices using AirPlay, and handle requests involving FairPlay-protected assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Streaming and AirPlay",
      "type": "topic",
      "url": "/documentation/avfoundation/streaming-and-airplay"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/using-avfoundation-to-play-and-persist-http-live-streams": {
      "abstract": [
        {
          "text": "Play HTTP Live Streams and persist streams on disk for offline playback using AVFoundation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/using-avfoundation-to-play-and-persist-http-live-streams",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using AVFoundation to play and persist HTTP Live Streams",
      "type": "topic",
      "url": "/documentation/avfoundation/using-avfoundation-to-play-and-persist-http-live-streams"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
        "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback"
      ],
      "title": "Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Asset-downloading",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/using-avfoundation-to-play-and-persist-http-live-streams",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadURLSession",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadTask",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAggregateAssetDownloadTask"
      ],
      "title": "Asset downloading"
    },
    {
      "anchor": "Offline-storage-management",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManager",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManagementPolicy",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAssetDownloadStorageManagementPolicy"
      ],
      "title": "Offline storage management"
    },
    {
      "anchor": "Cache-monitoring",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetCache"
      ],
      "title": "Cache monitoring"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Asset-downloading",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/using-avfoundation-to-play-and-persist-http-live-streams",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadURLSession",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadTask",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAggregateAssetDownloadTask"
              ],
              "title": "Asset downloading"
            },
            {
              "anchor": "Offline-storage-management",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManager",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetDownloadStorageManagementPolicy",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableAssetDownloadStorageManagementPolicy"
              ],
              "title": "Offline storage management"
            },
            {
              "anchor": "Cache-monitoring",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVAssetCache"
              ],
              "title": "Cache monitoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
                "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback"
              ],
              "title": "Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAggregateAssetDownloadTask/title",
          "value": "AVAggregateAssetDownloadTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAggregateAssetDownloadTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAggregateAssetDownloadTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAggregateAssetDownloadTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAggregateAssetDownloadTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAssetDownloadStorageManagementPolicy/title",
          "value": "AVMutableAssetDownloadStorageManagementPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAssetDownloadStorageManagementPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAssetDownloadStorageManagementPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableAssetDownloadStorageManagementPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableAssetDownloadStorageManagementPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadTask/title",
          "value": "AVAssetDownloadTask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadTask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadTask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadTask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetCache/title",
          "value": "AVAssetCache"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetCache/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetCache/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetCache"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManagementPolicy/title",
          "value": "AVAssetDownloadStorageManagementPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManagementPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadStorageManagementPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManagementPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadStorageManagementPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManager/title",
          "value": "AVAssetDownloadStorageManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadStorageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadStorageManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadStorageManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadURLSession/title",
          "value": "AVAssetDownloadURLSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadURLSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadURLSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAssetDownloadURLSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAssetDownloadURLSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/offline-playback-and-storage"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/offline-playback-and-storage"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
