{
  "abstract": [
    {
      "text": "Access the contents of a QuickTime movie file, and perform sample-level edits of its media tracks.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/quicktime-movies"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "QuickTime movies"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding": {
      "abstract": [
        {
          "text": "A protocol that defines whether an asset supports fragment minding.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentMinding"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentMinding"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentMinding",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentminding"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovie": {
      "abstract": [
        {
          "text": "An object that represents a fragmented movie file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedMovie"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovie"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovie"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieMinder": {
      "abstract": [
        {
          "text": "An object that checks whether a fragmented movie appends additional movie fragments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieMinder"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieMinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieMinder"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedMovieMinder",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovieminder"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrack": {
      "abstract": [
        {
          "text": "An object that represents a track in a fragmented movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVFragmentedMovieTrack"
        }
      ],
      "role": "symbol",
      "title": "AVFragmentedMovieTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avfragmentedmovietrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaDataStorage": {
      "abstract": [
        {
          "text": "An object that represents the media sample data storage file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaDataStorage"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaDataStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaDataStorage"
        }
      ],
      "role": "symbol",
      "title": "AVMediaDataStorage",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediadatastorage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie": {
      "abstract": [
        {
          "text": "An object that represents an audiovisual container that conforms to the QuickTime movie file format or a related format like MPEG-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMovie"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMovie"
        }
      ],
      "role": "symbol",
      "title": "AVMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovie"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieTrack": {
      "abstract": [
        {
          "text": "A track in a movie that conforms to the QuickTime or ISO base media file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMovieTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMovieTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMovieTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmovietrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovie": {
      "abstract": [
        {
          "text": "A mutable object that represents an audiovisual container that conforms to the QuickTime movie file format or a related format like MPEG-4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableMovie"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableMovie"
        }
      ],
      "role": "symbol",
      "title": "AVMutableMovie",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablemovie"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovieTrack": {
      "abstract": [
        {
          "text": "A mutable track that conforms to the QuickTime or ISO base media file format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableMovieTrack"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovieTrack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableMovieTrack"
        }
      ],
      "role": "symbol",
      "title": "AVMutableMovieTrack",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablemovietrack"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor": {
      "abstract": [
        {
          "text": "An object that provides information about the media sample at the cursor’s current position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursor"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursor",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursor"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo": {
      "abstract": [
        {
          "text": "A structure that describes the independent decodability of audio samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorAudioDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorAudioDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursoraudiodependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo": {
      "abstract": [
        {
          "text": "A value that provides information about a chunk of media samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorChunkInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorChunkInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorchunkinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo": {
      "abstract": [
        {
          "text": "A value for describing dependencies between a media sample and other media samples in the same sample sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorDependencyInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorDependencyInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursordependencyinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange": {
      "abstract": [
        {
          "text": "A structure that indicates the offset and length of storage for a media sample or its chunk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorStorageRange"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorStorageRange",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorstoragerange"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo": {
      "abstract": [
        {
          "text": "A structure that describes the attributes of media samples to consider when resynchronizing a decoder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleCursorSyncInfo"
        }
      ],
      "role": "symbol",
      "title": "AVSampleCursorSyncInfo",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplecursorsyncinfo"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing": {
      "abstract": [
        {
          "text": "Define how to mix the audio levels from multiple audio tracks over an asset’s duration.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Audio mixing",
      "type": "topic",
      "url": "/documentation/avfoundation/audio-mixing"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets": {
      "abstract": [
        {
          "text": "Combine tracks and segments of tracks from multiple assets into a composite asset that you can play or process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Composite assets",
      "type": "topic",
      "url": "/documentation/avfoundation/composite-assets"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects": {
      "abstract": [
        {
          "text": "Define standard video transition effects, synchronize layer animations with media timing, and create custom video compositors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Video effects",
      "type": "topic",
      "url": "/documentation/avfoundation/video-effects"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Editing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
        "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
        "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing"
      ],
      "title": "Editing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Movies",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieTrack"
      ],
      "title": "Movies"
    },
    {
      "anchor": "Mutable-movies",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovie",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovieTrack"
      ],
      "title": "Mutable movies"
    },
    {
      "anchor": "Fragmented-movies",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovie",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrack",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieMinder",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding"
      ],
      "title": "Fragmented movies"
    },
    {
      "anchor": "Sample-cursors",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
      ],
      "title": "Sample cursors"
    },
    {
      "anchor": "Media-data-storage",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaDataStorage"
      ],
      "title": "Media data storage"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Movies",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovie",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMovieTrack"
              ],
              "title": "Movies"
            },
            {
              "anchor": "Mutable-movies",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovie",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMovieTrack"
              ],
              "title": "Mutable movies"
            },
            {
              "anchor": "Fragmented-movies",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovie",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieTrack",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentedMovieMinder",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVFragmentMinding"
              ],
              "title": "Fragmented movies"
            },
            {
              "anchor": "Sample-cursors",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursor",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorSyncInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorAudioDependencyInfo",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorStorageRange",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleCursorChunkInfo"
              ],
              "title": "Sample cursors"
            },
            {
              "anchor": "Media-data-storage",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaDataStorage"
              ],
              "title": "Media data storage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Editing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/composite-assets",
                "doc://com.apple.avfoundation/documentation/AVFoundation/video-effects",
                "doc://com.apple.avfoundation/documentation/AVFoundation/audio-mixing"
              ],
              "title": "Editing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovie/title",
          "value": "AVMutableMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/title",
          "value": "AVMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/title",
          "value": "AVSampleCursorChunkInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorChunkInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorChunkInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieTrack/title",
          "value": "AVMovieTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMovieTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/title",
          "value": "AVSampleCursorStorageRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorStorageRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorStorageRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovieTrack/title",
          "value": "AVMutableMovieTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovieTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMovieTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/title",
          "value": "AVFragmentMinding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentMinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentMinding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentMinding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/title",
          "value": "AVSampleCursorAudioDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorAudioDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorAudioDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieTrack/title",
          "value": "AVFragmentedMovieTrack"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieTrack/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieTrack/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovieTrack"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/title",
          "value": "AVSampleCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovie/title",
          "value": "AVFragmentedMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovie/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/title",
          "value": "AVSampleCursorDependencyInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorDependencyInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorDependencyInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieMinder/title",
          "value": "AVFragmentedMovieMinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieMinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovieMinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVFragmentedMovieMinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVFragmentedMovieMinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaDataStorage/title",
          "value": "AVMediaDataStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaDataStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaDataStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaDataStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaDataStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/title",
          "value": "AVSampleCursorSyncInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleCursorSyncInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleCursorSyncInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/quicktime-movies"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/quicktime-movies"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
