{
  "abstract": [
    {
      "text": "Create custom controllers to play and synchronize the timing of sample buffer streams.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/sample-buffer-playback"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Sample buffer playback"
  },
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRendering": {
      "abstract": [
        {
          "text": "Methods you can implement to enqueue sample buffers for presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVQueuedSampleBufferRendering"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRendering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVQueuedSampleBufferRendering"
        }
      ],
      "role": "symbol",
      "title": "AVQueuedSampleBufferRendering",
      "type": "topic",
      "url": "/documentation/avfoundation/avqueuedsamplebufferrendering"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRenderer": {
      "abstract": [
        {
          "text": "An object used to decompress audio and play compressed or uncompressed audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferAudioRenderer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferAudioRenderer"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferAudioRenderer",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferaudiorenderer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer": {
      "abstract": [
        {
          "text": "An object that displays compressed or uncompressed video frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferDisplayLayer"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferDisplayLayer",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferdisplaylayer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGenerator": {
      "abstract": [
        {
          "text": "An object that creates sample buffers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferGenerator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferGenerator"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferGenerator",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebuffergenerator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGeneratorBatch": {
      "abstract": [
        {
          "text": "An object that generates sample buffers in a batch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferGeneratorBatch"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGeneratorBatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferGeneratorBatch"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferGeneratorBatch",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebuffergeneratorbatch"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRenderSynchronizer": {
      "abstract": [
        {
          "text": "An object used to synchronize multiple queued sample buffers to a single timeline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferRenderSynchronizer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRenderSynchronizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferRenderSynchronizer"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferRenderSynchronizer",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferrendersynchronizer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRequest": {
      "abstract": [
        {
          "text": "An object that describes a sample buffer creation request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferRequest"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferRequest"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferRequest",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebufferrequest"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferVideoRenderer": {
      "abstract": [
        {
          "text": "An object that enqueues video sample buffers for rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVSampleBufferVideoRenderer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferVideoRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVSampleBufferVideoRenderer"
        }
      ],
      "role": "symbol",
      "title": "AVSampleBufferVideoRenderer",
      "type": "topic",
      "url": "/documentation/avfoundation/avsamplebuffervideorenderer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage": {
      "abstract": [
        {
          "text": "Download streamed content to disk to allow offline playback, and define policies to automatically remove downloaded assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Offline playback and storage",
      "type": "topic",
      "url": "/documentation/avfoundation/offline-playback-and-storage"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay": {
      "abstract": [
        {
          "text": "Stream content wirelessly to other devices using AirPlay, and handle requests involving FairPlay-protected assets.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Streaming and AirPlay",
      "type": "topic",
      "url": "/documentation/avfoundation/streaming-and-airplay"
    },
    "doc://com.apple.documentation/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player": {
      "abstract": [
        {
          "text": "Construct an audio player to play your custom audio data, and optionally take advantage of the advanced features of AirPlay 2.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player",
      "kind": "article",
      "role": "sampleCode",
      "title": "Playing Custom Audio with Your Own Player",
      "type": "topic",
      "url": "/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Playback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
        "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
        "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay"
      ],
      "title": "Playback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sample-buffer-generation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRequest",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGenerator",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGeneratorBatch"
      ],
      "title": "Sample buffer generation"
    },
    {
      "anchor": "Presentation",
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRendering",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRenderSynchronizer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferVideoRenderer",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRenderer"
      ],
      "title": "Presentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sample-buffer-generation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/avfaudio/audio_engine/playing_custom_audio_with_your_own_player",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRequest",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGenerator",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferGeneratorBatch"
              ],
              "title": "Sample buffer generation"
            },
            {
              "anchor": "Presentation",
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVQueuedSampleBufferRendering",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferRenderSynchronizer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferDisplayLayer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferVideoRenderer",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVSampleBufferAudioRenderer"
              ],
              "title": "Presentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Playback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
                "doc://com.apple.avfoundation/documentation/AVFoundation/offline-playback-and-storage",
                "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-and-airplay"
              ],
              "title": "Playback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGenerator/title",
          "value": "AVSampleBufferGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRendering/title",
          "value": "AVQueuedSampleBufferRendering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRendering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVQueuedSampleBufferRendering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVQueuedSampleBufferRendering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVQueuedSampleBufferRendering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGeneratorBatch/title",
          "value": "AVSampleBufferGeneratorBatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGeneratorBatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferGeneratorBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferGeneratorBatch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferGeneratorBatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRenderSynchronizer/title",
          "value": "AVSampleBufferRenderSynchronizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRenderSynchronizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferRenderSynchronizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRenderSynchronizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferRenderSynchronizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/title",
          "value": "AVSampleBufferDisplayLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferDisplayLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferDisplayLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferDisplayLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRequest/title",
          "value": "AVSampleBufferRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferVideoRenderer/title",
          "value": "AVSampleBufferVideoRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferVideoRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferVideoRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferVideoRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferVideoRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAudioRenderer/title",
          "value": "AVSampleBufferAudioRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAudioRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferAudioRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVSampleBufferAudioRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVSampleBufferAudioRenderer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/sample-buffer-playback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/sample-buffer-playback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
