{
  "abstract": [
    {
      "text": "Extend your app’s appeal to users by adding subtitles and alternative audio tracks in their native language.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/selecting-subtitles-and-alternative-audio-tracks"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Selecting Subtitles and Alternative Audio Tracks"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As a developer, you want to make your apps accessible to as broad an audience as possible. One way for you to extend your app’s reach is to make it available to users in their native language as well as to provide support for users who have have hearing impairments or other accessibility needs. AVKit and AVFoundation simplify handling these concerns by providing built-in support for presenting subtitles and closed captions, and for selecting alternative audio and video tracks. If you’re building your own custom player or would like to present your own media-selection interface, use the features provided by AVFoundation’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionGroup",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionOption",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Retrieve-the-Available-Media-Options",
          "level": 3,
          "text": "Retrieve the Available Media Options",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "AVMediaSelectionOption",
              "type": "codeVoice"
            },
            {
              "text": " models an alternative audio, video, or text track contained within the source media. Media options are used to select alternative camera angles, present audio dubbed in a user’s native language, or display subtitles and closed captions. You determine which alternative media presentations are available by asynchronously loading and calling the asset’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which returns an array of strings indicating the available media characteristics. The possible values returned are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (alternative audio tracks), ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (alternative video tracks), and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (subtitles and closed captions).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you’ve retrieved the array of available options, you call the asset’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, passing it the desired characteristic. This method returns the associated ",
              "type": "text"
            },
            {
              "code": "AVMediaSelectionGroup",
              "type": "codeVoice"
            },
            {
              "text": " object, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if no groups exist for the specified characteristic.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "AVMediaSelectionGroup",
              "type": "codeVoice"
            },
            {
              "text": " acts as a container for a collection of mutually exclusive ",
              "type": "text"
            },
            {
              "code": "AVMediaSelectionOption",
              "type": "codeVoice"
            },
            {
              "text": " objects. The following example shows how you retrieve an asset’s media-selection groups and display their available options:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "for characteristic in asset.availableMediaCharacteristicsWithMediaSelectionOptions {",
            "    print(\"\\(characteristic)\")",
            "",
            "    // Retrieve the AVMediaSelectionGroup for the specified characteristic.",
            "    if let group = asset.mediaSelectionGroup(forMediaCharacteristic: characteristic) {",
            "        // Print its options.",
            "        for option in group.options {",
            "            print(\"  Option: \\(option.displayName)\")",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The output for an asset containing audio and subtitle media options looks similar to the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "[AVMediaCharacteristicAudible]",
            "  Option: English",
            "  Option: Spanish",
            "",
            "[AVMediaCharacteristicLegible]",
            "  Option: English",
            "  Option: German",
            "  Option: Spanish",
            "  Option: French"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Select-the-Desired-Media-Option",
          "level": 3,
          "text": "Select the Desired Media Option",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After you’ve retrieved an ",
              "type": "text"
            },
            {
              "code": "AVMediaSelectionGroup",
              "type": "codeVoice"
            },
            {
              "text": " object for a particular media characteristic and identified the desired ",
              "type": "text"
            },
            {
              "code": "AVMediaSelectionOption",
              "type": "codeVoice"
            },
            {
              "text": " object, the next step is to select it. You select a media option by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/select(_:in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on the active ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For instance, to present the asset’s Spanish subtitle option, you could select it as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let group = asset.mediaSelectionGroup(forMediaCharacteristic: AVMediaCharacteristicLegible) {",
            "    let locale = Locale(identifier: \"es-ES\")",
            "    let options =",
            "        AVMediaSelectionGroup.mediaSelectionOptions(from: group.options, with: locale)",
            "    if let option = options.first {",
            "        // Select Spanish-language subtitle option",
            "        playerItem.select(option, in: group)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Selecting a media option makes it immediately available for presentation. Selecting a subtitle or closed-caption option displays the associated text within the video display provided by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerLayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Selecting an alternative audio or video option replaces the currently presented media with the new selection’s media.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " automatically selects media based on the user’s system preferences as its default behavior. To take control over when it makes media selections, disable the default behavior by setting the player’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/appliesMediaSelectionCriteriaAutomatically",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/false",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions": {
      "abstract": [
        {
          "text": "An array of media characteristics for which a media selection option is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/availableMediaCharacteristicsWithMediaSelectionOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
        }
      ],
      "role": "symbol",
      "title": "availableMediaCharacteristicsWithMediaSelectionOptions",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/availablemediacharacteristicswithmediaselectionoptions"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)": {
      "abstract": [
        {
          "text": "Returns a media selection group that contains one or more options with the specified media characteristic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediaSelectionGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelectionGroup",
          "text": "AVMediaSelectionGroup"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVAsset/mediaSelectionGroup(forMediaCharacteristic:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mediaSelectionGroupForMediaCharacteristic:"
        }
      ],
      "role": "symbol",
      "title": "mediaSelectionGroup(forMediaCharacteristic:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avasset/mediaselectiongroup(formediacharacteristic:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes audible content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/audible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicAudible"
        }
      ],
      "role": "symbol",
      "title": "audible",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/audible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes legible content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/legible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicLegible"
        }
      ],
      "role": "symbol",
      "title": "legible",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/legible"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual": {
      "abstract": [
        {
          "text": "A media characteristic that indicates that a track or media selection option includes visual content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visual"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVMediaCharacteristic",
          "text": "AVMediaCharacteristic"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaCharacteristic/visual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaCharacteristicVisual"
        }
      ],
      "role": "symbol",
      "title": "visual",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediacharacteristic/visual"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelection": {
      "abstract": [
        {
          "text": "An object that represents a complete rendition of media selection options on an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaSelection"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaSelection"
        }
      ],
      "role": "symbol",
      "title": "AVMediaSelection",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediaselection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionGroup": {
      "abstract": [
        {
          "text": "An object that represents a collection of mutually exclusive options for the presentation of media within an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaSelectionGroup"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaSelectionGroup"
        }
      ],
      "role": "symbol",
      "title": "AVMediaSelectionGroup",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediaselectiongroup"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionOption": {
      "abstract": [
        {
          "text": "An object that represents a specific option for the presentation of media within a group of options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMediaSelectionOption"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMediaSelectionOption"
        }
      ],
      "role": "symbol",
      "title": "AVMediaSelectionOption",
      "type": "topic",
      "url": "/documentation/avfoundation/avmediaselectionoption"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMediaSelection": {
      "abstract": [
        {
          "text": "A mutable object that represents a complete rendition of media selection options on an asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMutableMediaSelection"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMediaSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMutableMediaSelection"
        }
      ],
      "role": "symbol",
      "title": "AVMutableMediaSelection",
      "type": "topic",
      "url": "/documentation/avfoundation/avmutablemediaselection"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/appliesMediaSelectionCriteriaAutomatically": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the receiver should apply the current selection criteria automatically to player items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appliesMediaSelectionCriteriaAutomatically"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/appliesMediaSelectionCriteriaAutomatically",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appliesMediaSelectionCriteriaAutomatically"
        }
      ],
      "role": "symbol",
      "title": "appliesMediaSelectionCriteriaAutomatically",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer/appliesmediaselectioncriteriaautomatically"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem": {
      "abstract": [
        {
          "text": "An object that models the timing and presentation state of an asset during playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerItem"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerItem",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/select(_:in:)": {
      "abstract": [
        {
          "text": "Selects a media option in a given media selection group and deselects all other options in that group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "select"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelectionOption",
          "text": "AVMediaSelectionOption"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMediaSelectionGroup",
          "text": "AVMediaSelectionGroup"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerItem/select(_:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectMediaOption:inMediaSelectionGroup:"
        }
      ],
      "role": "symbol",
      "title": "select(_:in:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayeritem/select(_:in:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerLayer": {
      "abstract": [
        {
          "text": "An object that presents the visual contents of a player object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerLayer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerLayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerLayer"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerLayer",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerlayer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerMediaSelectionCriteria": {
      "abstract": [
        {
          "text": "An object that specifies the preferred languages and media characteristics for a player.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerMediaSelectionCriteria"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerMediaSelectionCriteria",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerMediaSelectionCriteria"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerMediaSelectionCriteria",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayermediaselectioncriteria"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.documentation/documentation/AVKit/AVPlayerView": {
      "abstract": [
        {
          "text": "A view that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerView",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerView",
      "type": "topic",
      "url": "/documentation/AVKit/AVPlayerView"
    },
    "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController": {
      "abstract": [
        {
          "text": "A view controller that displays content from a player and presents a native user interface to control playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerViewController"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVKit/AVPlayerViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVPlayerViewController",
      "type": "topic",
      "url": "/documentation/AVKit/AVPlayerViewController"
    },
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelection",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionGroup",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionOption",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMediaSelection",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerMediaSelectionCriteria"
      ],
      "title": "Media selection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelection",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionGroup",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMediaSelectionOption",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVMutableMediaSelection",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerMediaSelectionCriteria"
              ],
              "title": "Media selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelection/title",
          "value": "AVMediaSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1select(_:in:)/title",
          "value": "selectMediaOption:inMediaSelectionGroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem~1select(_:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "selectMediaOption:inMediaSelectionGroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionGroup/title",
          "value": "AVMediaSelectionGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelectionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelectionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1legible/title",
          "value": "AVMediaCharacteristicLegible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1legible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicLegible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVKit~1AVPlayerView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSView",
              "text": "NSView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1audible/title",
          "value": "AVMediaCharacteristicAudible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1audible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicAudible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMediaCharacteristicsWithMediaSelectionOptions/title",
          "value": "availableMediaCharacteristicsWithMediaSelectionOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1availableMediaCharacteristicsWithMediaSelectionOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableMediaCharacteristicsWithMediaSelectionOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1visual/title",
          "value": "AVMediaCharacteristicVisual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaCharacteristic~1visual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaCharacteristicVisual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/title",
          "value": "AVPlayerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AVKit~1AVPlayerViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AVPlayerViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerLayer/title",
          "value": "AVPlayerLayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerLayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerLayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerLayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionOption/title",
          "value": "AVMediaSelectionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelectionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMediaSelectionOption/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMediaSelectionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1appliesMediaSelectionCriteriaAutomatically/title",
          "value": "appliesMediaSelectionCriteriaAutomatically"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1appliesMediaSelectionCriteriaAutomatically/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "appliesMediaSelectionCriteriaAutomatically"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/title",
          "value": "AVPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1mediaSelectionGroup(forMediaCharacteristic:)/title",
          "value": "mediaSelectionGroupForMediaCharacteristic:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVAsset~1mediaSelectionGroup(forMediaCharacteristic:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mediaSelectionGroupForMediaCharacteristic:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMediaSelection/title",
          "value": "AVMutableMediaSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMediaSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMediaSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVMutableMediaSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMutableMediaSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerMediaSelectionCriteria/title",
          "value": "AVPlayerMediaSelectionCriteria"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerMediaSelectionCriteria/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerMediaSelectionCriteria"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerMediaSelectionCriteria/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerMediaSelectionCriteria"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/selecting-subtitles-and-alternative-audio-tracks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/selecting-subtitles-and-alternative-audio-tracks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
