{
  "abstract": [
    {
      "text": "Visualize depth data in 2D and 3D from the TrueDepth camera.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/streaming-depth-data-from-the-truedepth-camera"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "16.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Streaming Depth Data from the TrueDepth Camera"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The TrueDepth camera provides depth data in real time that allows you to determine the distance of a pixel from the front-facing camera. This sample demonstrates how to use the AVFoundation framework’s capture API to read data from the TrueDepth camera, and how to display it in an intuitive fashion onscreen.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample shows two different views: a 2D view that distinguishes depth values by mapping depth to color, and a 3D view that renders data as a point cloud.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To see this sample app in action, build and run the project in Xcode on an iOS device running iOS 11 or later. Because Xcode doesn’t have access to the TrueDepth camera, this sample will not build or run in the Xcode simulator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-Up-a-Capture-Session",
          "level": 3,
          "text": "Set Up a Capture Session",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set up an ",
              "type": "text"
            },
            {
              "code": "AVCaptureSession",
              "type": "codeVoice"
            },
            {
              "text": " on a separate thread via the session queue. Initialize this session queue before configuring the camera for capture, like so:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private let sessionQueue = DispatchQueue(label: \"session queue\", attributes: [], autoreleaseFrequency: .workItem)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "startRunning",
              "type": "codeVoice"
            },
            {
              "text": " method is a blocking call that may take time to execute. Dispatch session setup to the session queue so the main queue isn’t blocked, allowing the app’s UI to stay responsive:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "sessionQueue.async {",
            "    self.configureSession()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Setting up the camera for video capture follows many of the same steps as normal video capture. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for details on configuring streaming setup.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On top of normal setup, request depth data by declaring a separate output:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private let depthDataOutput = AVCaptureDepthDataOutput()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Explicitly add this output type to your capture session:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "session.addOutput(depthDataOutput)",
            "depthDataOutput.isFilteringEnabled = false",
            "if let connection = depthDataOutput.connection(with: .depthData) {",
            "    connection.isEnabled = true",
            "} else {",
            "    print(\"No AVCaptureConnection\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Search for the highest resolution available with floating-point depth values, and lock the configuration to the format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let depthFormats = videoDevice.activeFormat.supportedDepthDataFormats",
            "let filtered = depthFormats.filter({",
            "    CMFormatDescriptionGetMediaSubType($0.formatDescription) == kCVPixelFormatType_DepthFloat16",
            "})",
            "let selectedFormat = filtered.max(by: {",
            "    first, second in CMVideoFormatDescriptionGetDimensions(first.formatDescription).width < CMVideoFormatDescriptionGetDimensions(second.formatDescription).width",
            "})",
            "",
            "do {",
            "    try videoDevice.lockForConfiguration()",
            "    videoDevice.activeDepthDataFormat = selectedFormat",
            "    videoDevice.unlockForConfiguration()",
            "} catch {",
            "    print(\"Could not lock device for configuration: \\(error)\")",
            "    setupResult = .configurationFailed",
            "    session.commitConfiguration()",
            "    return",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Synchronize the normal RGB video data with depth data output. The first output in the ",
              "type": "text"
            },
            {
              "code": "dataOutputs",
              "type": "codeVoice"
            },
            {
              "text": " array is the master output.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "outputSynchronizer = AVCaptureDataOutputSynchronizer(dataOutputs: [videoDataOutput, depthDataOutput])",
            "outputSynchronizer!.setDelegate(self, queue: dataOutputQueue)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "CameraViewController",
              "type": "codeVoice"
            },
            {
              "text": " implementation creates and manages this session to interface with the camera. It also contains UI to toggle between the two viewing modes, 2D and 3D.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Visualize-Depth-Data-in-2D",
          "level": 3,
          "text": "Visualize Depth Data in 2D",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample uses JET color coding to distinguish depth values, ranging from red (close) to blue (far). A slider controls the blending of the color code and the actual color values. Touching a pixel displays its depth value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "DepthToJETConverter",
              "type": "codeVoice"
            },
            {
              "text": " performs the conversion. It separates the color spectrum into histogram bins, colors a Metal texture from depth values obtained in the image buffer, and renders that texture into the preview.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var cvTextureOut: CVMetalTexture?",
            "CVMetalTextureCacheCreateTextureFromImage(kCFAllocatorDefault, textureCache, pixelBuffer, nil, textureFormat, width, height, 0, &cvTextureOut)",
            "guard let cvTexture = cvTextureOut, let texture = CVMetalTextureGetTexture(cvTexture) else {",
            "    print(\"Depth converter failed to create preview texture\")",
            "    CVMetalTextureCacheFlush(textureCache, 0)",
            "    return nil",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Visualize-Depth-Data-in-3D",
          "level": 3,
          "text": "Visualize Depth Data in 3D",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample’s 3D viewer renders data as a point cloud. Control the camera with the following gestures:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pinch to zoom.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pan to move the camera around the center.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Rotate with two fingers to turn the camera angle.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Double-tap the screen to reset the initial position.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The sample implements a 3D point cloud as a ",
              "type": "text"
            },
            {
              "code": "PointCloudMetalView",
              "type": "codeVoice"
            },
            {
              "text": ". It uses a Metal vertex shader to control geometry and a Metal fragment shader to color individual vertices, keeping the depth texture and color texture separate:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CVMetalTextureCacheRef _depthTextureCache;",
            "CVMetalTextureCacheRef _colorTextureCache;"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The depth frame’s depth map provides the basis for the Metal view’s depth texture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CVPixelBufferRef depthFrame = depthData.depthDataMap;",
            "CVMetalTextureRef cvDepthTexture = nullptr;",
            "if (kCVReturnSuccess != CVMetalTextureCacheCreateTextureFromImage(kCFAllocatorDefault,",
            "                        _depthTextureCache,",
            "                        depthFrame,",
            "                        nil,",
            "                        MTLPixelFormatR16Float,",
            "                        CVPixelBufferGetWidth(depthFrame),",
            "                        CVPixelBufferGetHeight(depthFrame),",
            "                        0,",
            "                        &cvDepthTexture)) {",
            "    NSLog(@\"Failed to create depth texture\");",
            "    CVPixelBufferRelease(colorFrame);",
            "    return;",
            "}",
            "",
            "id<MTLTexture> depthTexture = CVMetalTextureGetTexture(cvDepthTexture);"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The RGB image provides the basis for the Metal view’s color texture:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "CVMetalTextureRef cvColorTexture = nullptr;",
            "if (kCVReturnSuccess != CVMetalTextureCacheCreateTextureFromImage(kCFAllocatorDefault,",
            "                        _colorTextureCache,",
            "                        colorFrame,",
            "                        nil,",
            "                        MTLPixelFormatBGRA8Unorm,",
            "                        CVPixelBufferGetWidth(colorFrame),",
            "                        CVPixelBufferGetHeight(colorFrame),",
            "                        0,",
            "                        &cvColorTexture)) {",
            "    NSLog(@\"Failed to create color texture\");",
            "    CVPixelBufferRelease(colorFrame);",
            "    return;",
            "}",
            "",
            "id<MTLTexture> colorTexture = CVMetalTextureGetTexture(cvColorTexture);"
          ],
          "syntax": "objective-c",
          "type": "codeListing"
        },
        {
          "anchor": "Track-Thermal-State",
          "level": 3,
          "text": "Track Thermal State",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Processing depth data from a live stream may cause the device to heat up. Keep tabs on the thermal state so you can alert the user if it exceeds a dangerous threshold.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@objc",
            "func thermalStateChanged(notification: NSNotification) {",
            "    if let processInfo = notification.object as? ProcessInfo {",
            "        showThermalState(state: processInfo.thermalState)",
            "    }",
            "}",
            "",
            "func showThermalState(state: ProcessInfo.ThermalState) {",
            "    DispatchQueue.main.async {",
            "        var thermalStateString = \"UNKNOWN\"",
            "        if state == .nominal {",
            "            thermalStateString = \"NOMINAL\"",
            "        } else if state == .fair {",
            "            thermalStateString = \"FAIR\"",
            "        } else if state == .serious {",
            "            thermalStateString = \"SERIOUS\"",
            "        } else if state == .critical {",
            "            thermalStateString = \"CRITICAL\"",
            "        }",
            "        ",
            "        let message = NSLocalizedString(\"Thermal state: \\(thermalStateString)\", comment: \"Alert message when thermal state has changed\")",
            "        let alertController = UIAlertController(title: \"TrueDepthStreamer\", message: message, preferredStyle: .alert)",
            "        alertController.addAction(UIAlertAction(title: NSLocalizedString(\"OK\", comment: \"Alert OK button\"), style: .cancel, handler: nil))",
            "        self.present(alertController, animated: true, completion: nil)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "1bc13e22cdde/StreamingDepthDataFromTheTrueDepthCamera.zip": {
      "checksum": "1bc13e22cddece20ed7f55164d75f9a3f1b0980366e45bd24e893d637559a7972f9458890f49272a7aafb7a4c02d3f6b3447eafbdf68e8f5b296decd87ee042a",
      "identifier": "1bc13e22cdde/StreamingDepthDataFromTheTrueDepthCamera.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/1bc13e22cdde/StreamingDepthDataFromTheTrueDepthCamera.zip"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData": {
      "abstract": [
        {
          "text": "Information about the camera characteristics used to capture images and depth data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCameraCalibrationData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCameraCalibrationData"
        }
      ],
      "role": "symbol",
      "title": "AVCameraCalibrationData",
      "type": "topic",
      "url": "/documentation/avfoundation/avcameracalibrationdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput": {
      "abstract": [
        {
          "text": "A capture output that records scene depth information on compatible camera devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVCaptureDepthDataOutput"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVCaptureDepthDataOutput"
        }
      ],
      "role": "symbol",
      "title": "AVCaptureDepthDataOutput",
      "type": "topic",
      "url": "/documentation/avfoundation/avcapturedepthdataoutput"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData": {
      "abstract": [
        {
          "text": "A container for per-pixel distance or disparity information captured by compatible camera devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDepthData"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDepthData"
        }
      ],
      "role": "symbol",
      "title": "AVDepthData",
      "type": "topic",
      "url": "/documentation/avfoundation/avdepthdata"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture": {
      "abstract": [
        {
          "text": "Capture additional data including depth and metadata, and synchronize capture from multiple outputs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/additional-data-capture",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Additional data capture",
      "type": "topic",
      "url": "/documentation/avfoundation/additional-data-capture"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream": {
      "abstract": [
        {
          "text": "Render a capture stream with rose-colored filtering and depth effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
      "kind": "article",
      "role": "sampleCode",
      "title": "AVCamFilter: Applying Filters to a Capture Stream",
      "type": "topic",
      "url": "/documentation/avfoundation/avcamfilter-applying-filters-to-a-capture-stream"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera": {
      "abstract": [
        {
          "text": "Access the LiDAR camera on supporting devices to capture precise depth data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera",
      "kind": "article",
      "role": "sampleCode",
      "title": "Capturing depth using the LiDAR camera",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-depth-using-the-lidar-camera"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth": {
      "abstract": [
        {
          "text": "Get a depth map with a photo to create effects like the system camera’s Portrait mode (on compatible devices).",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
      "kind": "article",
      "role": "article",
      "title": "Capturing Photos with Depth",
      "type": "topic",
      "url": "/documentation/avfoundation/capturing-photos-with-depth"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually": {
      "abstract": [
        {
          "text": "Generate a depth image and attach it to your own image.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
      "kind": "article",
      "role": "article",
      "title": "Creating Auxiliary Depth Data Manually",
      "type": "topic",
      "url": "/documentation/avfoundation/creating-auxiliary-depth-data-manually"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data": {
      "abstract": [
        {
          "text": "Apply your own background to a live capture feed streamed from the front-facing TrueDepth camera.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Enhancing Live Video by Leveraging TrueDepth Camera Data",
      "type": "topic",
      "url": "/documentation/avfoundation/enhancing-live-video-by-leveraging-truedepth-camera-data"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session": {
      "abstract": [
        {
          "text": "Configure input devices, output media, preview views, and basic settings before capturing photos or video.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/setting-up-a-capture-session",
      "kind": "article",
      "role": "article",
      "title": "Setting Up a Capture Session",
      "type": "topic",
      "url": "/documentation/avfoundation/setting-up-a-capture-session"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "1bc13e22cdde/StreamingDepthDataFromTheTrueDepthCamera.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Depth-data-capture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
        "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
        "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-depth-using-the-lidar-camera",
        "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
        "doc://com.apple.avfoundation/documentation/AVFoundation/enhancing-live-video-by-leveraging-truedepth-camera-data",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData"
      ],
      "title": "Depth data capture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Depth-data-capture",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/capturing-photos-with-depth",
                "doc://com.apple.avfoundation/documentation/AVFoundation/creating-auxiliary-depth-data-manually",
                "doc://com.apple.avfoundation/documentation/AVFoundation/avcamfilter-applying-filters-to-a-capture-stream",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCaptureDepthDataOutput",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDepthData",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVCameraCalibrationData"
              ],
              "title": "Depth data capture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/title",
          "value": "AVDepthData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDepthData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDepthData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/title",
          "value": "AVCameraCalibrationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCameraCalibrationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCameraCalibrationData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCameraCalibrationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/title",
          "value": "AVCaptureDepthDataOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDepthDataOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCaptureDepthDataOutput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCaptureDepthDataOutput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/streaming-depth-data-from-the-truedepth-camera"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/streaming-depth-data-from-the-truedepth-camera"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
