{
  "abstract": [
    {
      "text": "Create synchronized media experiences that enable users to watch and listen across devices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfoundation/documentation/AVFoundation",
        "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfoundation/documentation/AVFoundation/supporting-coordinated-media-playback"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "AVFoundation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Supporting Coordinated Media Playback"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Watching TV and movies, and listening to music, can be more fun when you do it with friends and family. However, getting together in person isn’t always an option. Beginning with iOS 15, tvOS 15, and macOS 12, you have the ability to create media apps that let people watch and listen together wherever they are. This capability is possible using AVFoundation and the new GroupActivities frameworks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "AVFoundation introduces a new class, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", that synchronizes the timing of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects across devices. Apps use the GroupActivities framework to connect playback coordinators using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "session_coordination.png",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app shows you how to add coordinated media playback support to your app. It provides a simple movie-playing app, where a user selects a movie from the library and plays it in a standard player user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-Sample-Code-Project",
          "level": 3,
          "text": "Configure the Sample Code Project",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You must build the sample with Xcode 13 and Swift 5.5.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You must run the sample on a physical device with iOS 15 or later.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "To experience coordinated playback, you need to install the app on two or more devices with unique Apple IDs. Start a FaceTime call between the devices, and select an item from the library on one of them. The system prompts you to play the movie locally or with the group. Select to play it with the group, and starting playback on one device starts it on the other. The system automatically propagates rate and time changes to all playback coordinators to keep group playback in sync.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-an-Activity",
          "level": 3,
          "text": "Create an Activity",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app plays movies, which it represents with a ",
              "type": "text"
            },
            {
              "code": "Movie",
              "type": "codeVoice"
            },
            {
              "text": " structure that defines essential data about an item in its library.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct Movie: Hashable, Codable {",
            "    var url: URL",
            "    var title: String",
            "    var description: String",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To make movie watching a group experience, the sample creates a structure called ",
              "type": "text"
            },
            {
              "code": "MovieWatchingActivity",
              "type": "codeVoice"
            },
            {
              "text": " that adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. This protocol defines a shareable experience in the app. The activity stores the movie to share with the group, and provides supporting metadata that the system displays when a user shares an activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// A group activity to watch a movie together.",
            "struct MovieWatchingActivity: GroupActivity {",
            "    ",
            "    // The movie to watch.",
            "    let movie: Movie",
            "    ",
            "    // Metadata that the system displays to participants.",
            "    var metadata: GroupActivityMetadata {",
            "        var metadata = GroupActivityMetadata()",
            "        metadata.type = .watchTogether",
            "        metadata.fallbackURL = movie.url",
            "        metadata.title = movie.title",
            "        return metadata",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "GroupActivity",
                  "type": "codeVoice"
                },
                {
                  "text": " extends ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/Codable",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", so any data that an activity stores must also conform to ",
                  "type": "text"
                },
                {
                  "code": "Codable",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Share-an-Activity",
          "level": 3,
          "text": "Share an Activity",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a user selects a movie, the sample determines whether it needs to play the movie for the current user only, or share it with the group. It makes this determination by calling the activity’s asynchronous ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/prepareForActivation()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which enables the system to present an interface for the user to select their preferred action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a new activity for the selected movie.",
            "let activity = MovieWatchingActivity(movie: selectedMovie)",
            "",
            "// Await the result of the preparation call.",
            "switch await activity.prepareForActivation() {",
            "    ",
            "case .activationDisabled:",
            "    // Playback coordination isn't active, or the user prefers to play the",
            "    // movie apart from the group. Enqueue the movie for local playback only.",
            "    self.enqueuedMovie = selectedMovie",
            "    ",
            "case .activationPreferred:",
            "    // The user prefers to share this activity with the group.",
            "    // The app enqueues the movie for playback when the activity starts.",
            "    do {",
            "        _ = try await activity.activate()",
            "    } catch {",
            "        print(\"Unable to activate the activity: \\(error)\")",
            "    }",
            "    ",
            "case .cancelled:",
            "    // The user cancels the operation. Do nothing.",
            "    break",
            "    ",
            "default: ()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The call returns a result that indicates the appropriate action to take. A result of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationDisabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates that group playback isn’t active, or the user selects to play the movie locally only. In this case, the app sets the movie as the ",
              "type": "text"
            },
            {
              "code": "enqueuedMovie",
              "type": "codeVoice"
            },
            {
              "text": ", which enqueues it for local playback. A result of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationPreferred",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " indicates that group playback is possible, and the user wants to start a group activity. When this occurs, the sample calls the activity’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/activate()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which starts a group session and shares the activity with the group. The sample doesn’t immediately enqueue the movie for playback, but instead waits until the group session notifies all participants of the new activity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Await-Group-Sessions",
          "level": 3,
          "text": "Await Group Sessions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the sample activates a ",
              "type": "text"
            },
            {
              "code": "MovieWatchingActivity",
              "type": "codeVoice"
            },
            {
              "text": ", the system creates a group session. It accesses the session by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/sessions()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which returns sessions for the activity as an asynchronous sequence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Await new sessions to watch movies together.",
            "for await groupSession in MovieWatchingActivity.sessions() {",
            "    // Set the app's active group session.",
            "    self.groupSession = groupSession",
            "    ",
            "    // Remove previous subscriptions.",
            "    subscriptions.removeAll()",
            "    ",
            "    // Observe changes to the session state.",
            "    groupSession.$state.sink { [weak self] state in",
            "        if case .invalidated = state {",
            "            // Set the groupSession to nil to publish",
            "            // the invalidated session state.",
            "            self?.groupSession = nil",
            "            self?.subscriptions.removeAll()",
            "        }",
            "    }.store(in: &subscriptions)",
            "    ",
            "    // Join the session to participate in playback coordination.",
            "    groupSession.join()",
            "    ",
            "    // Observe when the local user or a remote participant starts an activity.",
            "    groupSession.$activity.sink { [weak self] activity in",
            "        // Set the movie to enqueue it in the player.",
            "        self?.enqueuedMovie = activity.movie",
            "    }.store(in: &subscriptions)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the sample receives a new session, it sets it as the active group session, and then joins it, which makes the app eligible to participate in the session. Then it subscribes to the session’s activity publisher and, when it receives a new value, it enqueues the activity’s movie for playback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Prepare-for-Coordinated-Playback",
          "level": 3,
          "text": "Prepare for Coordinated Playback",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The last step the sample takes to enable group playback is to access the player’s coordinator and connect it with the group session. It does this by calling the coordinator object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/coordinateWithSession(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, which connects it with the coordinators of other participants in the session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// The group session to coordinate playback with.",
            "private var groupSession: GroupSession<MovieWatchingActivity>? {",
            "    didSet {",
            "        guard let session = groupSession else {",
            "            // Stop playback if a session terminates.",
            "            player.rate = 0",
            "            return",
            "        }",
            "        // Coordinate playback with the active session.",
            "        player.playbackCoordinator.coordinateWithSession(session)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After the sample makes this connection, the system coordinates rate and time changes across participant players. The app continues to enqueue movies in a typical way, and controls playback using the player’s standard transport methods like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/play()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/pause()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/seek(to:)-87h2r",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The coordinator intercepts these changes and communicates them to other coordinators as appropriate. Likewise, it also responds to rate and time changes from other participants and sets them on its local player.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Suspend-Participation-in-Coordinated-Playback",
          "level": 3,
          "text": "Suspend Participation in Coordinated Playback",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, the sample keeps playback in sync with the group. However, there are times when it needs to prevent local interruptions from impacting other participants. In these situations, it disconnects from the group temporarily by issuing a playback suspension. An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " automatically issues playback suspensions for common system events like network stalls and audio session interruptions. Apps can also define custom suspensions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample provides a feature that lets a viewer quickly catch up with content they miss. This action doesn’t impact the group, so the app begins a custom playback suspension. It creates an extension on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that defines a new ",
              "type": "text"
            },
            {
              "code": "whatHappened",
              "type": "codeVoice"
            },
            {
              "text": " suspension reason.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension AVCoordinatedPlaybackSuspension.Reason {",
            "    static var whatHappened = AVCoordinatedPlaybackSuspension.Reason(rawValue: \"com.example.groupwatching.suspension.what-happened\")",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When a user taps the feature’s button in the user interface, the sample calls its ",
              "type": "text"
            },
            {
              "code": "performWhatHappened()",
              "type": "codeVoice"
            },
            {
              "text": "  method. In this method, it starts the custom suspension, rewinds by 10 seconds, and then plays at double speed until playback catches up with the group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func performWhatHappened() {",
            "    ",
            "    // Rewind 10 seconds.",
            "    let rewindDuration = CMTime(value: 10, timescale: 1)",
            "    let rewindTime = player.currentTime() - rewindDuration",
            "    ",
            "    // Start a custom suspension.",
            "    let suspension = player.playbackCoordinator.beginSuspension(for: .whatHappened)",
            "    player.seek(to: rewindTime)",
            "    player.rate = 2.0",
            "    ",
            "    DispatchQueue.main.asyncAfter(deadline: .now() + rewindDuration.seconds) {",
            "        // End the suspension and resume playback with the group.",
            "        suspension.end()",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After the local device catches up with group playback, the sample ends the suspension. Although it sets the player’s rate to ",
              "type": "text"
            },
            {
              "code": "2.0",
              "type": "codeVoice"
            },
            {
              "text": " after beginning the suspension, it doesn’t have to explicitly set it back to the original rate when it ends because the coordinator sets it automatically when the player rejoins group playback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "367117687a0a/SupportingCoordinatedMediaPlayback.zip": {
      "checksum": "367117687a0ae02d7b8e006741350526a5829a4155f902163dfe067f6a95a4951b441e86e7bf2ce7546b952aa5f4b7e6d35864863a4c4d321aefbeea5d630bd4",
      "identifier": "367117687a0a/SupportingCoordinatedMediaPlayback.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/367117687a0a/SupportingCoordinatedMediaPlayback.zip"
    },
    "Destination-Video-intro.png": {
      "alt": null,
      "identifier": "Destination-Video-intro.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/648c665254129674ce04bbc64dbeeb2d/Destination-Video-intro@2x.png"
        }
      ]
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation": {
      "abstract": [
        {
          "text": "Work with audiovisual assets, control device cameras, process audio, and configure system audio interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFoundation",
      "type": "topic",
      "url": "/documentation/avfoundation"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct": {
      "abstract": [
        {
          "text": "Constants that identify playback suspension reasons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVCoordinatedPlaybackSuspension/Reason-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Reason"
        }
      ],
      "role": "symbol",
      "title": "AVCoordinatedPlaybackSuspension.Reason",
      "type": "topic",
      "url": "/documentation/avfoundation/avcoordinatedplaybacksuspension/reason-swift.struct"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinator": {
      "abstract": [
        {
          "text": "A playback coordinator subclass that coordinates the playback of custom player objects in a connected group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVDelegatingPlaybackCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVDelegatingPlaybackCoordinator",
      "type": "topic",
      "url": "/documentation/avfoundation/avdelegatingplaybackcoordinator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator": {
      "abstract": [
        {
          "text": "An object that coordinates the playback of players in a connected group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlaybackCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlaybackCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVPlaybackCoordinator",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/coordinateWithSession(_:)": {
      "abstract": [
        {
          "text": "Begins coordination of a player with a group session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinateWithSession"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15GroupActivities0A7SessionC",
          "text": "GroupSession"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator/coordinateWithSession(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "coordinateWithSession(_:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplaybackcoordinator/coordinatewithsession(_:)"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer": {
      "abstract": [
        {
          "text": "An object that provides the interface to control the player’s transport behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayer"
        }
      ],
      "role": "symbol",
      "title": "AVPlayer",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/pause()": {
      "abstract": [
        {
          "text": "Pauses playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pause"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/pause()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pause"
        }
      ],
      "role": "symbol",
      "title": "pause()",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer/pause()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/play()": {
      "abstract": [
        {
          "text": "Begins playback of the current item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "play"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/play()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "play"
        }
      ],
      "role": "symbol",
      "title": "play()",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer/play()"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/seek(to:)-87h2r": {
      "abstract": [
        {
          "text": "Requests that the player seek to a specified time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "seek"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CMTime",
          "text": "CMTime"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayer/seek(to:)-87h2r",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "seekToTime:"
        }
      ],
      "role": "symbol",
      "title": "seek(to:)",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayer/seek(to:)-87h2r"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator": {
      "abstract": [
        {
          "text": "A playback coordinator subclass that coordinates the playback of player objects in a connected group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVPlayerPlaybackCoordinator"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVPlayerPlaybackCoordinator"
        }
      ],
      "role": "symbol",
      "title": "AVPlayerPlaybackCoordinator",
      "type": "topic",
      "url": "/documentation/avfoundation/avplayerplaybackcoordinator"
    },
    "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback": {
      "abstract": [
        {
          "text": "Manage the playback of media assets and interstitial content, independent of how you present that content in your interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfoundation/documentation/AVFoundation/media-playback",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Media playback",
      "type": "topic",
      "url": "/documentation/avfoundation/media-playback"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity": {
      "abstract": [
        {
          "text": "A type that can advertise your app’s activities to other participants.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GroupActivity"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Se",
          "text": "Decodable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "GroupActivity",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivity"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/activate()": {
      "abstract": [
        {
          "text": "Begins the activity immediately and creates a session for the app when a FaceTime call is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activate"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/activate()",
      "kind": "symbol",
      "role": "symbol",
      "title": "activate()",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivity/activate()"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/prepareForActivation()": {
      "abstract": [
        {
          "text": "Returns the participant’s preferred option for how to start the activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepareForActivation"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15GroupActivities0A24ActivityActivationResultO",
          "text": "GroupActivityActivationResult"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/prepareForActivation()",
      "kind": "symbol",
      "role": "symbol",
      "title": "prepareForActivation()",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivity/prepareForActivation()"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/sessions()": {
      "abstract": [
        {
          "text": "Returns the sessions for this activity as an asynchronous sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sessions"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15GroupActivities0A8ActivityPAAE8Sessionsa",
          "text": "Sessions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivity/sessions()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sessions()",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivity/sessions()"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationDisabled": {
      "abstract": [
        {
          "text": "A result that indicates the user disabled the automatic sharing of activities, or prefers to perform the activity locally.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationDisabled"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationDisabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "GroupActivityActivationResult.activationDisabled",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivityActivationResult/activationDisabled"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationPreferred": {
      "abstract": [
        {
          "text": "A result that indicates the user wants to share the activity with the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationPreferred"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupActivityActivationResult/activationPreferred",
      "kind": "symbol",
      "role": "symbol",
      "title": "GroupActivityActivationResult.activationPreferred",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupActivityActivationResult/activationPreferred"
    },
    "doc://com.apple.documentation/documentation/GroupActivities/GroupSession": {
      "abstract": [
        {
          "text": "A session for an in-progress activity that synchronizes content among participant devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GroupSession"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "ActivityType"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "ActivityType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:15GroupActivities0A8ActivityP",
          "text": "GroupActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/GroupActivities/GroupSession",
      "kind": "symbol",
      "role": "symbol",
      "title": "GroupSession",
      "type": "topic",
      "url": "/documentation/GroupActivities/GroupSession"
    },
    "doc://com.apple.documentation/documentation/Swift/Codable": {
      "abstract": [
        {
          "text": "A type that can convert itself into and out of an external representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Codable"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Se",
          "text": "Decodable"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SE",
          "text": "Encodable"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/Codable",
      "kind": "symbol",
      "role": "symbol",
      "title": "Codable",
      "type": "topic",
      "url": "/documentation/Swift/Codable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.documentation/documentation/visionOS/destination-video": {
      "abstract": [
        {
          "text": "Leverage SwiftUI to build an immersive media experience in a multiplatform app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/visionOS/destination-video",
      "images": [
        {
          "identifier": "Destination-Video-intro.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "sampleCode",
      "title": "Destination Video",
      "type": "topic",
      "url": "/documentation/visionOS/destination-video"
    },
    "session_coordination.png": {
      "alt": "A diagram that represents two devices with a connection through a GroupSession object. Device 1 and Device 2 each contain representations of the app, AVPlayer, AVPlayerItem, and AVPlayerPlaybackCoordinator relationships. The two AVPlayerPlaybackCoordinator items have a two-way dotted-line connection between the two devices.",
      "identifier": "session_coordination.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ed4faf2bc2c9250ca5ee0a4b5e2cc862/session_coordination.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/abe59fdb46bc880a3a3dea907feb6477/session_coordination~dark@2x.png"
        }
      ]
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "367117687a0a/SupportingCoordinatedMediaPlayback.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "SharePlay",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/visionOS/destination-video",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator",
        "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinator"
      ],
      "title": "SharePlay"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "SharePlay",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlaybackCoordinator",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVPlayerPlaybackCoordinator",
                "doc://com.apple.avfoundation/documentation/AVFoundation/AVDelegatingPlaybackCoordinator"
              ],
              "title": "SharePlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1play()/title",
          "value": "play"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1play()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "play"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1pause()/title",
          "value": "pause"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1pause()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pause"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinator/title",
          "value": "AVDelegatingPlaybackCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVDelegatingPlaybackCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVDelegatingPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/title",
          "value": "AVCoordinatedPlaybackSuspensionReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVCoordinatedPlaybackSuspension~1Reason-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVCoordinatedPlaybackSuspensionReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/title",
          "value": "AVPlayer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerPlaybackCoordinator/title",
          "value": "AVPlayerPlaybackCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerPlaybackCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayerPlaybackCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlayerPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1seek(to:)-87h2r/title",
          "value": "seekToTime:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlayer~1seek(to:)-87h2r/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "seekToTime:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/title",
          "value": "AVPlaybackCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlaybackCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfoundation~1documentation~1AVFoundation~1AVPlaybackCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVPlaybackCoordinator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfoundation/supporting-coordinated-media-playback"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfoundation/supporting-coordinated-media-playback"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
