{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID/init(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So18CNDetectionGroupIDayABs5Int64Vcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int64V",
        "text": "Int64"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int64V",
              "text": "Int64"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID": {
      "abstract": [
        {
          "text": "A structure representing a unique number representing the detection to focus on if this is a group decision.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionGroupID"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionGroupID"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionGroupID",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiongroupid"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID/init(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int64V",
          "text": "Int64"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionGroupID/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiongroupid/init(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s5Int64V": {
      "abstract": [
        {
          "text": "A 64-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int64"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int64V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int64",
      "type": "topic",
      "url": "/documentation/Swift/Int64"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionGroupID/title",
          "value": "CNDetectionGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionGroupID/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionGroupID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cndetectiongroupid/init(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
