{
  "abstract": [
    {
      "text": "The user must launch your app to make the reservation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INBookRestaurantReservationIntentCode@INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureRequiringAppLaunch"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INBookRestaurantReservationIntentCode.failureRequiringAppLaunch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureRequiringAppLaunch"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this response code when you cannot handle the request directly for a reason not covered by any other response code. Do not use it for general errors or to force the user to launch your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode": {
      "abstract": [
        {
          "text": "Constants indicating the state of the response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCode"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/denied": {
      "abstract": [
        {
          "text": "The restaurant declined the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeDenied"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.denied",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/denied"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failure": {
      "abstract": [
        {
          "text": "You were unable to create the reservation object in your system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.failure",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to make the reservation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchMustVerifyCredentials": {
      "abstract": [
        {
          "text": "Your app failed to create the reservation because the user’s credentials were invalid or missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchMustVerifyCredentials",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchMustVerifyCredentials"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.failureRequiringAppLaunchMustVerifyCredentials",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/failurerequiringapplaunchmustverifycredentials"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchServiceTemporarilyUnavailable": {
      "abstract": [
        {
          "text": "Your service is temporarily unavailable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.failureRequiringAppLaunchServiceTemporarilyUnavailable",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/failurerequiringapplaunchservicetemporarilyunavailable"
    },
    "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/success": {
      "abstract": [
        {
          "text": "You successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INBookRestaurantReservationIntentCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INBookRestaurantReservationIntentCode.success",
      "type": "topic",
      "url": "/documentation/intents/inbookrestaurantreservationintentcode/success"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/denied",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchMustVerifyCredentials",
        "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchServiceTemporarilyUnavailable"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/denied",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchMustVerifyCredentials",
                "doc://com.apple.sirikit/documentation/Intents/INBookRestaurantReservationIntentCode/failureRequiringAppLaunchServiceTemporarilyUnavailable"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failure/title",
          "value": "INBookRestaurantReservationIntentCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1denied/title",
          "value": "INBookRestaurantReservationIntentCodeDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunchMustVerifyCredentials/title",
          "value": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchMustVerifyCredentials"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunchMustVerifyCredentials/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchMustVerifyCredentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode/title",
          "value": "INBookRestaurantReservationIntentCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1success/title",
          "value": "INBookRestaurantReservationIntentCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/title",
          "value": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunchServiceTemporarilyUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunchServiceTemporarilyUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunch/title",
          "value": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INBookRestaurantReservationIntentCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INBookRestaurantReservationIntentCodeFailureRequiringAppLaunch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inbookrestaurantreservationintentcode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inbookrestaurantreservationintentcode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
