{
  "abstract": [
    {
      "text": "Blend factor of zero.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLBlendFactor@MTLBlendFactorZero",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "zero"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLBlendFactorZero"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLBlendFactor.zero"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "zero"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "F(rgb) = 0",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "F(a) = 0",
              "type": "codeVoice"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor": {
      "abstract": [
        {
          "text": "The source and destination blend factors are often needed to complete specification of a blend operation. In most cases, the blend factor for both RGB values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(rgb)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") and alpha values (",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "F(a)",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ") are similar to one another, but in some cases, such as ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorSourceAlphaSaturated",
          "type": "codeVoice"
        },
        {
          "text": ", the blend factor is slightly different. Four blend factors (",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendColor",
          "type": "codeVoice"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "code": "MTLBlendFactorOneMinusBlendAlpha",
          "type": "codeVoice"
        },
        {
          "text": ") refer to a constant blend color value that is set by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method of ",
          "type": "text"
        },
        {
          "code": "MTLRenderCommandEncoder",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha": {
      "abstract": [
        {
          "text": "Blend factor of alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorBlendAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.blendAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/blendalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor": {
      "abstract": [
        {
          "text": "Blend factor of RGB values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorBlendColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.blendColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/blendcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha": {
      "abstract": [
        {
          "text": "Blend factor of destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorDestinationAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.destinationAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/destinationalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor": {
      "abstract": [
        {
          "text": "Blend factor of destination values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorDestinationColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.destinationColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/destinationcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one": {
      "abstract": [
        {
          "text": "Blend factor of one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "one"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOne"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.one",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/one"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus alpha value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusBlendAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusBlendAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusBlendAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusblendalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus RGB values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusBlendColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusBlendColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusBlendColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusblendcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusDestinationAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusDestinationAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusDestinationAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusdestinationalpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus destination values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusDestinationColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusDestinationColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusDestinationColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminusdestinationcolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha": {
      "abstract": [
        {
          "text": "Blend factor of one minus source alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSourceAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSourceAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSourceAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussourcealpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor": {
      "abstract": [
        {
          "text": "Blend factor of one minus source values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oneMinusSourceColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorOneMinusSourceColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.oneMinusSourceColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/oneminussourcecolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color": {
      "abstract": [
        {
          "text": "Blend factor of source values. This option supports dual-source blending and reads from the second color output of the fragment function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "source1Color"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSource1Color"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.source1Color",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/source1color"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha": {
      "abstract": [
        {
          "text": "Blend factor of source alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAlpha"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceAlpha"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceAlpha",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcealpha"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated": {
      "abstract": [
        {
          "text": "Blend factor of the minimum of either source alpha or one minus destination alpha.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceAlphaSaturated"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceAlphaSaturated"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceAlphaSaturated",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcealphasaturated"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor": {
      "abstract": [
        {
          "text": "Blend factor of source values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceColor"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorSourceColor"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.sourceColor",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/sourcecolor"
    },
    "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero": {
      "abstract": [
        {
          "text": "Blend factor of zero.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "zero"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/zero",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLBlendFactorZero"
        }
      ],
      "role": "symbol",
      "title": "MTLBlendFactor.zero",
      "type": "topic",
      "url": "/documentation/metal/mtlblendfactor/zero"
    },
    "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)": {
      "abstract": [
        {
          "text": "Configures each pixel component value, including alpha, for the render pipeline’s constant blend color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBlendColor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "red"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "green"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "blue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLRenderCommandEncoder/setBlendColor(red:green:blue:alpha:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBlendColorRed:green:blue:alpha:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setBlendColor(red:green:blue:alpha:)",
      "type": "topic",
      "url": "/documentation/metal/mtlrendercommandencoder/setblendcolor(red:green:blue:alpha:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
        "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLBlendFactorZero"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/one",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusSourceAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/destinationAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusDestinationAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/sourceAlphaSaturated",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendColor",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/blendAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/oneMinusBlendAlpha",
                "doc://com.apple.metal/documentation/Metal/MTLBlendFactor/source1Color"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLBlendFactorZero"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceAlpha/title",
          "value": "MTLBlendFactorOneMinusSourceAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSourceAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendAlpha/title",
          "value": "MTLBlendFactorOneMinusBlendAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusBlendAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlphaSaturated/title",
          "value": "MTLBlendFactorSourceAlphaSaturated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlphaSaturated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceAlphaSaturated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Color/title",
          "value": "MTLBlendFactorSource1Color"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1source1Color/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSource1Color"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceColor/title",
          "value": "MTLBlendFactorSourceColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1zero/title",
          "value": "MTLBlendFactorZero"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1zero/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorZero"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendColor/title",
          "value": "MTLBlendFactorOneMinusBlendColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusBlendColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusBlendColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceColor/title",
          "value": "MTLBlendFactorOneMinusSourceColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusSourceColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusSourceColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendColor/title",
          "value": "MTLBlendFactorBlendColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorBlendColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendAlpha/title",
          "value": "MTLBlendFactorBlendAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1blendAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorBlendAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationColor/title",
          "value": "MTLBlendFactorOneMinusDestinationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusDestinationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/title",
          "value": "MTLBlendFactor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationColor/title",
          "value": "MTLBlendFactorDestinationColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorDestinationColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlpha/title",
          "value": "MTLBlendFactorSourceAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1sourceAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorSourceAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationAlpha/title",
          "value": "MTLBlendFactorDestinationAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1destinationAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorDestinationAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/title",
          "value": "setBlendColorRed:green:blue:alpha:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLRenderCommandEncoder~1setBlendColor(red:green:blue:alpha:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBlendColorRed:green:blue:alpha:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationAlpha/title",
          "value": "MTLBlendFactorOneMinusDestinationAlpha"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1oneMinusDestinationAlpha/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOneMinusDestinationAlpha"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/title",
          "value": "MTLBlendFactorOne"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLBlendFactor~1one/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLBlendFactorOne"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlblendfactor/zero"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlblendfactor/zero"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
