{
  "abstract": [
    {
      "text": "Called when a frame’s scripting object for a page is available. Use the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " method instead.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)WebFrameLoadDelegate(im)webView:windowScriptObjectAvailable:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "webView:windowScriptObjectAvailable:"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "webView:windowScriptObjectAvailable:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "webView:windowScriptObjectAvailable:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "webView:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WebView",
              "text": "WebView"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "webView"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "windowScriptObjectAvailable:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.webkit/documentation/WebKit/WebScriptObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)WebScriptObject",
              "text": "WebScriptObject"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "windowScriptObject"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The web view containing the frame.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "webView"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The window object in the scripting environment.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "windowScriptObject"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method is invoked before the page is actually loaded.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s": {
      "abstract": [
        {
          "text": "Connects to a given URL by initiating an asynchronous client request.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "load"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation10URLRequestV",
          "text": "URLRequest"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadRequest:"
        }
      ],
      "role": "symbol",
      "title": "load(_:)",
      "type": "topic",
      "url": "/documentation/webkit/webframe/load(_:)-47p2s"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebFrameLoadDelegate"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebFrameLoadDelegate"
        }
      ],
      "role": "symbol",
      "title": "WebFrameLoadDelegate",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)": {
      "abstract": [
        {
          "text": "Called when the JavaScript window object in a frame is ready for loading.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "webView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebView",
          "text": "WebView"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "didClearWindowObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebScriptObject",
          "text": "WebScriptObject"
        },
        {
          "kind": "text",
          "text": "!, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebFrame",
          "text": "WebFrame"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:didClearWindowObject:forFrame:"
        }
      ],
      "role": "symbol",
      "title": "webView(_:didClearWindowObject:for:)",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview(_:didclearwindowobject:for:)"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:": {
      "abstract": [
        {
          "text": "Called when a frame’s scripting object for a page is available. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView(_:didClearWindowObject:for:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method instead.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "webView:windowScriptObjectAvailable:"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrameLoadDelegate/webView:windowScriptObjectAvailable:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "webView:windowScriptObjectAvailable:"
        }
      ],
      "role": "symbol",
      "title": "webView:windowScriptObjectAvailable:",
      "type": "topic",
      "url": "/documentation/webkit/webframeloaddelegate/webview:windowscriptobjectavailable:"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebScriptObject": {
      "abstract": [
        {
          "text": "A ",
          "type": "text"
        },
        {
          "code": "WebScriptObject",
          "type": "codeVoice"
        },
        {
          "text": " object is an Objective-C wrapper for a scripting object passed to your application from the scripting environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebScriptObject"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebScriptObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebScriptObject"
        }
      ],
      "role": "symbol",
      "title": "WebScriptObject",
      "type": "topic",
      "url": "/documentation/webkit/webscriptobject"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView": {
      "abstract": [
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " is the core view class in the WebKit framework that manages interactions between the ",
          "type": "text"
        },
        {
          "code": "WebFrame",
          "type": "codeVoice"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "code": "WebFrameView",
          "type": "codeVoice"
        },
        {
          "text": " classes. To embed web content in your application, you just create a ",
          "type": "text"
        },
        {
          "code": "WebView",
          "type": "codeVoice"
        },
        {
          "text": " object, attach it to a window, and send a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " message to its main frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WebView"
        }
      ],
      "role": "symbol",
      "title": "WebView",
      "type": "topic",
      "url": "/documentation/webkit/webview"
    },
    "doc://com.apple.webkit/documentation/WebKit/WebView/windowScriptObject": {
      "abstract": [
        {
          "text": "The receiver’s window object from the scripting environment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowScriptObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)WebScriptObject",
          "text": "WebScriptObject"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WebView/windowScriptObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windowScriptObject"
        }
      ],
      "role": "symbol",
      "title": "windowScriptObject",
      "type": "topic",
      "url": "/documentation/webkit/webview/windowscriptobject"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WebView/windowScriptObject"
      ],
      "title": "Related Documentation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1windowScriptObject/title",
          "value": "windowScriptObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView~1windowScriptObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windowScriptObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/title",
          "value": "WebFrameLoadDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebFrameLoadDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didClearWindowObject:for:)/title",
          "value": "webView:didClearWindowObject:forFrame:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrameLoadDelegate~1webView(_:didClearWindowObject:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "webView:didClearWindowObject:forFrame:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title",
          "value": "loadRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/title",
          "value": "WebScriptObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebScriptObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebScriptObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebScriptObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title",
          "value": "WebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WebView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/webframeloaddelegate/webview:windowscriptobjectavailable:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
