{
  "abstract": [
    {
      "text": "An unspecified response code.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/unspecified"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INShareFocusStatusIntentResponseCode@INShareFocusStatusIntentResponseCodeUnspecified",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unspecified"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INShareFocusStatusIntentResponseCodeUnspecified"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INShareFocusStatusIntentResponseCode.unspecified"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unspecified"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode": {
      "abstract": [
        {
          "text": "A constant that indicates your app’s ability to handle an intent to share the user’s focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "Your intent handler is unable to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user needs to launch your app to update their focus status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "An unspecified response code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INShareFocusStatusIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INShareFocusStatusIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/insharefocusstatusintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reporting-a-Problem",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failure",
        "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failureRequiringAppLaunch"
      ],
      "title": "Reporting a Problem"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INShareFocusStatusIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reporting-a-Problem",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failure",
                "doc://com.apple.sirikit/documentation/Intents/INShareFocusStatusIntentResponseCode/failureRequiringAppLaunch"
              ],
              "title": "Reporting a Problem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INShareFocusStatusIntentResponseCodeUnspecified"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INShareFocusStatusIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/title",
          "value": "INShareFocusStatusIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1unspecified/title",
          "value": "INShareFocusStatusIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1failure/title",
          "value": "INShareFocusStatusIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INShareFocusStatusIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INShareFocusStatusIntentResponseCodeFailure"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insharefocusstatusintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insharefocusstatusintentresponsecode/unspecified"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
