{
  "abstract": [
    {
      "text": "The camera isn’t accessible.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/cameraNotAccessible"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartCallCallCapabilityUnsupportedReason@INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cameraNotAccessible"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INStartCallCallCapabilityUnsupportedReason.cameraNotAccessible"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cameraNotAccessible"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason the app can’t support starting the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallCallCapabilityUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallCallCapabilityUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INStartCallCallCapabilityUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/instartcallcallcapabilityunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/cameraNotAccessible": {
      "abstract": [
        {
          "text": "The camera isn’t accessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cameraNotAccessible"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/cameraNotAccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
        }
      ],
      "role": "symbol",
      "title": "INStartCallCallCapabilityUnsupportedReason.cameraNotAccessible",
      "type": "topic",
      "url": "/documentation/intents/instartcallcallcapabilityunsupportedreason/cameranotaccessible"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/microphoneNotAccessible": {
      "abstract": [
        {
          "text": "The microphone isn’t accessible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "microphoneNotAccessible"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/microphoneNotAccessible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallCallCapabilityUnsupportedReasonMicrophoneNotAccessible"
        }
      ],
      "role": "symbol",
      "title": "INStartCallCallCapabilityUnsupportedReason.microphoneNotAccessible",
      "type": "topic",
      "url": "/documentation/intents/instartcallcallcapabilityunsupportedreason/microphonenotaccessible"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/videoCallUnsupported": {
      "abstract": [
        {
          "text": "The app doesn’t support video calls.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoCallUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/videoCallUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallCallCapabilityUnsupportedReasonVideoCallUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INStartCallCallCapabilityUnsupportedReason.videoCallUnsupported",
      "type": "topic",
      "url": "/documentation/intents/instartcallcallcapabilityunsupportedreason/videocallunsupported"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/videoCallUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/microphoneNotAccessible"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/videoCallUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallCallCapabilityUnsupportedReason/microphoneNotAccessible"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1cameraNotAccessible/title",
          "value": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1cameraNotAccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReasonCameraNotAccessible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1videoCallUnsupported/title",
          "value": "INStartCallCallCapabilityUnsupportedReasonVideoCallUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1videoCallUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReasonVideoCallUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason/title",
          "value": "INStartCallCallCapabilityUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1microphoneNotAccessible/title",
          "value": "INStartCallCallCapabilityUnsupportedReasonMicrophoneNotAccessible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallCallCapabilityUnsupportedReason~1microphoneNotAccessible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallCallCapabilityUnsupportedReasonMicrophoneNotAccessible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartcallcallcapabilityunsupportedreason/cameranotaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartcallcallcapabilityunsupportedreason/cameranotaccessible"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
