{
  "abstract": [
    {
      "text": "A dictionary of names and values to match with query items in a URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
        "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "ul:applinks.Details.Components.Query",
    "fragments": [
      {
        "kind": "text",
        "text": "object "
      },
      {
        "kind": "identifier",
        "text": "applinks.Details.Components.Query"
      }
    ],
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applinks.Details.Components.Query"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Object",
    "symbolKind": "dictionary",
    "title": "applinks.Details.Components.Query"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "items": [
        {
          "attributes": [],
          "content": [],
          "introducedVersion": "13.0.0",
          "name": "Any Key",
          "required": false,
          "type": [
            {
              "kind": "text",
              "text": "string"
            }
          ]
        }
      ],
      "kind": "properties",
      "title": "Properties"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The keys in this dictionary are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlqueryitem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " names and the values are patterns to match with the specified key’s value.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This example code shows how to use a dictionary object for pattern matching with a URL query component:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "\"?\": { \"productID\": \"12345\" }"
          ],
          "syntax": "javascript",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The above definition matches a URL query component that has a name of ",
              "type": "text"
            },
            {
              "code": "productID",
              "type": "codeVoice"
            },
            {
              "text": " and a value of ",
              "type": "text"
            },
            {
              "code": "12345",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks": {
      "abstract": [
        {
          "text": "The root object for a universal links service definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks"
        }
      ],
      "role": "symbol",
      "title": "applinks",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary": {
      "abstract": [
        {
          "text": "A list of apps and the universal links they handle for a domain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary": {
      "abstract": [
        {
          "text": "Patterns that define the universal links an app can open.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query": {
      "abstract": [
        {
          "text": "A dictionary of names and values to match with query items in a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "object "
        },
        {
          "kind": "identifier",
          "text": "applinks.Details.Components.Query"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary/Query",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applinks.Details.Components.Query"
        }
      ],
      "role": "symbol",
      "title": "applinks.Details.Components.Query",
      "type": "topic",
      "url": "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary/query"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurlqueryitem": {
      "abstract": [
        {
          "text": "An object representing a single name/value pair for an item in the query portion of a URL that bridges to ; use  when you need reference semantics or other Foundation-specific behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSURLQueryItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurlqueryitem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSURLQueryItem",
      "type": "topic",
      "url": "/documentation/foundation/nsurlqueryitem"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Object"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applinks.Details.Components.Query"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary",
                "doc://com.apple.bundleresources/documentation/BundleResources/applinks/Details-swift.dictionary/Components-swift.dictionary"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "object "
                  },
                  {
                    "kind": "identifier",
                    "text": "applinks.Details.Components.Query"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "items": [
              {
                "attributes": [],
                "content": [],
                "introducedVersion": "13.0.0",
                "name": "Any Key",
                "required": false,
                "type": [
                  {
                    "kind": "text",
                    "text": "string"
                  }
                ]
              }
            ],
            "kind": "properties",
            "title": "Properties"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/title",
          "value": "applinks.Details.Components.Query"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary~1Query/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components.Query"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/title",
          "value": "applinks.Details"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/title",
          "value": "applinks.Details.Components"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks~1Details-swift.dictionary~1Components-swift.dictionary/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks.Details.Components"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/title",
          "value": "applinks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/fragments",
          "value": [
            {
              "kind": "text",
              "text": "object "
            },
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1applinks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "applinks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurlqueryitem/abstract",
          "value": [
            {
              "text": "An object representing a single name/value pair for an item in the query portion of a URL.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary/query"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/applinks/details-swift.dictionary/components-swift.dictionary/query"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
