{
  "abstract": [
    {
      "text": "The media is playing.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.webkit/documentation/WebKit",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKMediaPlaybackState@WKMediaPlaybackStatePlaying",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "playing"
      }
    ],
    "modules": [
      {
        "name": "WebKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKMediaPlaybackStatePlaying"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.5",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.3",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKMediaPlaybackState.playing"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "playing"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.webkit/documentation/WebKit": {
      "abstract": [
        {
          "text": "Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WebKit",
      "type": "topic",
      "url": "/documentation/webkit"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState": {
      "abstract": [
        {
          "text": "An enumeration that describes whether an audio or video presentation is playing, paused, or suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackState"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none": {
      "abstract": [
        {
          "text": "There is no media to play back.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStateNone"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.none",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/none"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused": {
      "abstract": [
        {
          "text": "The media playback is paused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paused"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStatePaused"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.paused",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/paused"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing": {
      "abstract": [
        {
          "text": "The media is playing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playing"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/playing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStatePlaying"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.playing",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/playing"
    },
    "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended": {
      "abstract": [
        {
          "text": "The media is not playing, and cannot be resumed until the user revokes the suspension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "suspended"
        }
      ],
      "identifier": "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKMediaPlaybackStateSuspended"
        }
      ],
      "role": "symbol",
      "title": "WKMediaPlaybackState.suspended",
      "type": "topic",
      "url": "/documentation/webkit/wkmediaplaybackstate/suspended"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
        "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.5",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.3",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKMediaPlaybackStatePlaying"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStatePlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.webkit/documentation/WebKit",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/none",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/paused",
                "doc://com.apple.webkit/documentation/WebKit/WKMediaPlaybackState/suspended"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKMediaPlaybackStatePlaying"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/title",
          "value": "WKMediaPlaybackState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1suspended/title",
          "value": "WKMediaPlaybackStateSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1suspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStateSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1playing/title",
          "value": "WKMediaPlaybackStatePlaying"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1playing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStatePlaying"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1none/title",
          "value": "WKMediaPlaybackStateNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStateNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1paused/title",
          "value": "WKMediaPlaybackStatePaused"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WKMediaPlaybackState~1paused/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKMediaPlaybackStatePaused"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/webkit/wkmediaplaybackstate/playing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/webkit/wkmediaplaybackstate/playing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
