{
  "abstract": [
    {
      "text": "Registers a list of traits to observe and a closure to execute when one of the observed traits changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit23UITraitChangeObservableP23registerForTraitChanges_7handlerSo0bC12Registration_pSayAA0B10Definition_pXpG_yqd___So0B10CollectionCtctSo0B11EnvironmentRd__lF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "registerForTraitChanges"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "TraitEnvironment"
      },
      {
        "kind": "text",
        "text": ">(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit7UITraita",
        "text": "UITrait"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "handler"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit23UITraitChangeObservableP05TraitC7Handlera",
        "text": "TraitChangeHandler"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "TraitEnvironment"
      },
      {
        "kind": "text",
        "text": ">) -> any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
        "text": "UITraitChangeRegistration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "registerForTraitChanges(_:handler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@discardableResult"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "registerForTraitChanges"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "TraitEnvironment"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "traits"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit7UITraita",
              "text": "UITrait"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "handler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit23UITraitChangeObservableP05TraitC7Handlera",
              "text": "TraitChangeHandler"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "TraitEnvironment"
            },
            {
              "kind": "text",
              "text": ">) -> any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
              "text": "UITraitChangeRegistration"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "TraitEnvironment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UITraitEnvironment",
              "text": "UITraitEnvironment"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of traits to observe for changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "traits"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A closure that the system executes when one of the registered traits changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "handler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An opaque token you can use to stop observing trait changes by passing to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You don’t have to unregister your observations, and you can safely ignore this value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The first parameter of the closure provides access to the observed object whose traits have changed, so you don’t need to create a weak reference. When registering for changes on self, use ",
              "type": "text"
            },
            {
              "code": "self",
              "type": "codeVoice"
            },
            {
              "text": " as the name and ",
              "type": "text"
            },
            {
              "code": "Self",
              "type": "codeVoice"
            },
            {
              "text": " as the type of the first parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example registers size class traits so that the system executes the closure when a size class trait changes in the view’s trait collection:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let sizeTraits: [UITrait] = [UITraitVerticalSizeClass.self, UITraitHorizontalSizeClass.self]",
            "",
            "// Register for size class changes on self. Declare the first paramteter as `self: Self`.",
            "// Declaring self as the first parameter eliminates the need to capture self from outside the closure, and avoids strong reference cycles.",
            "registerForTraitChanges(sizeTraits) { (self: Self, previousTraitCollection: UITraitCollection) in",
            "    // Handle the trait change.",
            "}",
            "",
            "// Register for size class changes on a different view of class MyView.",
            "view.registerForTraitChanges(sizeTraits) { (view: MyView, previousTraitCollection: UITraitCollection) in",
            "    // Handle the trait change.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITrait-9423": {
      "abstract": [
        {
          "text": "A type representing a trait in a trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "role": "symbol",
      "title": "UITrait",
      "type": "topic",
      "url": "/documentation/uikit/uitrait-9423"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler": {
      "abstract": [
        {
          "text": "A closure the system executes when observed traits change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TraitChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TraitChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable.TraitChangeHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/traitchangehandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the receiving object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:action:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:action:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe and a closure to execute when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "TraitEnvironment"
        },
        {
          "kind": "text",
          "text": ">(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit23UITraitChangeObservableP05TraitC7Handlera",
          "text": "TraitChangeHandler"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "TraitEnvironment"
        },
        {
          "kind": "text",
          "text": ">) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:handler:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:handler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the specified target object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:target:action:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:target:action:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)": {
      "abstract": [
        {
          "text": "Tells the system to stop observing previously registered traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "unregisterForTraitChanges(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/unregisterfortraitchanges(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeRegistration",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeregistration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-trait-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration"
      ],
      "title": "Observing trait changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/title",
          "value": "UITraitChangeRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:handler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
