{
  "abstract": [
    {
      "text": "Registers a list of traits to observe, and calls a method on the receiving object when one of the observed traits changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit23UITraitChangeObservableP23registerForTraitChanges_6actionSo0bC12Registration_pSayAA0B10Definition_pXpG_10ObjectiveC8SelectorVtF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "registerForTraitChanges"
      },
      {
        "kind": "text",
        "text": "(["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:5UIKit7UITraita",
        "text": "UITrait"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "action"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10ObjectiveC8SelectorV",
        "text": "Selector"
      },
      {
        "kind": "text",
        "text": ") -> any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
        "text": "UITraitChangeRegistration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "registerForTraitChanges(_:action:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@discardableResult"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "registerForTraitChanges"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "traits"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:5UIKit7UITraita",
              "text": "UITrait"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "action"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10ObjectiveC8SelectorV",
              "text": "Selector"
            },
            {
              "kind": "text",
              "text": ") -> any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
              "text": "UITraitChangeRegistration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of traits to observe for changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "traits"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A selector identifying the method the system calls when one of the registered trait changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "action"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An opaque token you can use to stop observing trait changes by passing to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You don’t have to unregister your observations, and you can safely ignore this value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This is a convenience method for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when the object receiving the registration is the target of the action. For example, when you register for changes on ",
              "type": "text"
            },
            {
              "code": "self",
              "type": "codeVoice"
            },
            {
              "text": ", the ",
              "type": "text"
            },
            {
              "code": "target",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "code": "self",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example calls ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsLayout()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in response to changes to size traits:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let sizeTraits: [UITrait] = [UITraitVerticalSizeClass.self, UITraitHorizontalSizeClass.self]",
            "",
            "// Register for size class changes on self, and invalidate the layout in response to changes.",
            "registerForTraitChanges(sizeTraits, action: #selector(UIView.setNeedsLayout))"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITrait-9423": {
      "abstract": [
        {
          "text": "A type representing a trait in a trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITrait-9423",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITrait"
        }
      ],
      "role": "symbol",
      "title": "UITrait",
      "type": "topic",
      "url": "/documentation/uikit/uitrait-9423"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler": {
      "abstract": [
        {
          "text": "A closure the system executes when observed traits change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TraitChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TraitChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable.TraitChangeHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/traitchangehandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the receiving object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:action:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:action:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:action:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe and a closure to execute when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "TraitEnvironment"
        },
        {
          "kind": "text",
          "text": ">(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit23UITraitChangeObservableP05TraitC7Handlera",
          "text": "TraitChangeHandler"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "TraitEnvironment"
        },
        {
          "kind": "text",
          "text": ">) -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:handler:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:handler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)": {
      "abstract": [
        {
          "text": "Registers a list of traits to observe, and calls a method on the specified target object when one of the observed traits changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit7UITraita",
          "text": "UITrait"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "action"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "registerForTraitChanges(_:target:action:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:target:action:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)": {
      "abstract": [
        {
          "text": "Tells the system to stop observing previously registered traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForTraitChanges"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITraitChangeRegistration",
          "text": "UITraitChangeRegistration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "unregisterForTraitChanges(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94/unregisterfortraitchanges(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeRegistration"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeRegistration",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeregistration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsLayout()": {
      "abstract": [
        {
          "text": "Invalidates the current layout of the receiver and triggers a layout update during the next update cycle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsLayout"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setNeedsLayout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsLayout"
        }
      ],
      "role": "symbol",
      "title": "setNeedsLayout()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setneedslayout()"
    },
    "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Selector"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV",
      "kind": "symbol",
      "role": "symbol",
      "title": "Selector",
      "type": "topic",
      "url": "/documentation/objectivec/selector"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Observing-trait-changes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:handler:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/registerForTraitChanges(_:target:action:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/unregisterForTraitChanges(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94/TraitChangeHandler",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeRegistration"
      ],
      "title": "Observing trait changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/title",
          "value": "UITraitChangeRegistration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitChangeRegistration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitChangeRegistration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsLayout()/title",
          "value": "setNeedsLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setNeedsLayout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitraitchangeobservable-67e94/registerfortraitchanges(_:action:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
