{
  "abstract": [
    {
      "text": "Resolves the restaurant for which you are providing default values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/resolveRestaurant(for:completion:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)INGetAvailableRestaurantReservationBookingDefaultsIntentHandling(im)resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "resolveRestaurant"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
        "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completion"
      },
      {
        "kind": "text",
        "text": ": ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
        "text": "INRestaurantResolutionResult"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "resolveRestaurant(for:completion:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveRestaurant"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completion"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
              "text": "INRestaurantResolutionResult"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "resolveRestaurant"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " -> "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantResolutionResult",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
              "text": "INRestaurantResolutionResult"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "intent"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution result object whose value contains the ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": " object that you intend to use. If you located more than one restaurant that matches the provided information, create a resolution result that asks the user to choose from among the possible options.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "resolutionResult",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completion"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this method to resolve the restaurant you are providing default values for.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent": {
      "abstract": [
        {
          "text": "A request for the default values to use when fetching potential reservation options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntent",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling": {
      "abstract": [
        {
          "text": "The handler interface for providing default values to the system when pre-fetching an initial set of possible reservation times.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        }
      ],
      "role": "symbol",
      "title": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/resolveRestaurant(for:completion:)": {
      "abstract": [
        {
          "text": "Resolves the restaurant for which you are providing default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resolveRestaurant"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
          "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
          "text": "INRestaurantResolutionResult"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/resolveRestaurant(for:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
        }
      ],
      "role": "symbol",
      "title": "resolveRestaurant(for:completion:)",
      "type": "topic",
      "url": "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling/resolverestaurant(for:completion:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurant": {
      "abstract": [
        {
          "text": "A restaurant for which your app can make and manage reservations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurant"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurant"
        }
      ],
      "role": "symbol",
      "title": "INRestaurant",
      "type": "topic",
      "url": "/documentation/intents/inrestaurant"
    },
    "doc://com.apple.sirikit/documentation/Intents/INRestaurantResolutionResult": {
      "abstract": [
        {
          "text": "A resolution result for the restaurant selected by a user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INRestaurantResolutionResult"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantResolutionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INRestaurantResolutionResult"
        }
      ],
      "role": "symbol",
      "title": "INRestaurantResolutionResult",
      "type": "topic",
      "url": "/documentation/intents/inrestaurantresolutionresult"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetAvailableRestaurantReservationBookingDefaultsIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INGetAvailableRestaurantReservationBookingDefaultsIntent",
                    "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "intent"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withCompletion:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurantResolutionResult",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INRestaurantResolutionResult",
                    "text": "INRestaurantResolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "resolutionResult"
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completion"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The intent object containing details about the user’s request. Use this object to get the initial information, if any, provided by the user.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "intent"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The block to execute with the resolution. You must execute this block at some point during your implementation of this method. This block has no return value and takes the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "The object containing the details of your proposed resolution. For successful resolutions, create a resolution result object whose value contains the ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INRestaurant",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": " object that you intend to use. If you located more than one restaurant that matches the provided information, create a resolution result that asks the user to choose from among the possible options.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "resolutionResult",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completion"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantResolutionResult/title",
          "value": "INRestaurantResolutionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantResolutionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurantResolutionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurantResolutionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/title",
          "value": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetAvailableRestaurantReservationBookingDefaultsIntentHandling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1resolveRestaurant(for:completion:)/title",
          "value": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetAvailableRestaurantReservationBookingDefaultsIntentHandling~1resolveRestaurant(for:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "resolveRestaurantForGetAvailableRestaurantReservationBookingDefaults:withCompletion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/title",
          "value": "INRestaurant"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurant"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INRestaurant/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INRestaurant"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling/resolverestaurant(for:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetavailablerestaurantreservationbookingdefaultsintenthandling/resolverestaurant(for:completion:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
