{
  "abstract": [
    {
      "text": "When a sample is calculated, the time value is clamped to the range of time values found in the sequence. For example, if the last keyframe’s time value is ",
      "type": "text"
    },
    {
      "code": "0.5",
      "type": "codeVoice"
    },
    {
      "text": ", a sample at any time value from ",
      "type": "text"
    },
    {
      "code": "0.5",
      "type": "codeVoice"
    },
    {
      "text": " to ",
      "type": "text"
    },
    {
      "code": "1.0",
      "type": "codeVoice"
    },
    {
      "text": " returns the last keyframe’s value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.spritekit/documentation/SpriteKit",
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/clamp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKRepeatMode@SKRepeatModeClamp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "clamp"
      }
    ],
    "modules": [
      {
        "name": "SpriteKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKRepeatModeClamp"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKRepeatMode.clamp"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "clamp"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Given a sequence with the key values of ",
              "type": "text"
            },
            {
              "code": "[5, 1, 10]",
              "type": "codeVoice"
            },
            {
              "text": " and times of ",
              "type": "text"
            },
            {
              "code": "[0, 0.25, 0.5]",
              "type": "codeVoice"
            },
            {
              "text": ", clamp repeat mode produces a set of values that follow straight line when the sample time is greater or equal to ",
              "type": "text"
            },
            {
              "code": "0.5",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2576677",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit": {
      "abstract": [
        {
          "text": "Add high-performance 2D content with smooth animations to your app, or create a game with a high-level set of 2D game-based tools.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SpriteKit",
      "type": "topic",
      "url": "/documentation/spritekit"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode": {
      "abstract": [
        {
          "text": "The modes used to determine how the sequence repeats.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRepeatMode"
        }
      ],
      "role": "symbol",
      "title": "SKRepeatMode",
      "type": "topic",
      "url": "/documentation/spritekit/skrepeatmode"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/clamp": {
      "abstract": [
        {
          "text": "When a sample is calculated, the time value is clamped to the range of time values found in the sequence. For example, if the last keyframe’s time value is ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": ", a sample at any time value from ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " returns the last keyframe’s value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clamp"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/clamp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRepeatModeClamp"
        }
      ],
      "role": "symbol",
      "title": "SKRepeatMode.clamp",
      "type": "topic",
      "url": "/documentation/spritekit/skrepeatmode/clamp"
    },
    "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/loop": {
      "abstract": [
        {
          "text": "When a sample is calculated, the sequence loops back to the beginning of the sequence. For example, if the last keyframe’s time value is ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": ", then a sample at any time value from ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "1.0",
          "type": "codeVoice"
        },
        {
          "text": " returns the same value as the sequence did from ",
          "type": "text"
        },
        {
          "code": "0.0",
          "type": "codeVoice"
        },
        {
          "text": " to ",
          "type": "text"
        },
        {
          "code": "0.5",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loop"
        }
      ],
      "identifier": "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/loop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKRepeatModeLoop"
        }
      ],
      "role": "symbol",
      "title": "SKRepeatMode.loop",
      "type": "topic",
      "url": "/documentation/spritekit/skrepeatmode/loop"
    },
    "media-2576677": {
      "alt": "Playground graph generated by SKKeyframeSequence using clamp repeat mode",
      "identifier": "media-2576677",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4139d5fb8890f536eb4691e709c117b2/media-2576677@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/loop"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKRepeatModeClamp"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatModeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.spritekit/documentation/SpriteKit",
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.spritekit/documentation/SpriteKit/SKRepeatMode/loop"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKRepeatModeClamp"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/title",
          "value": "SKRepeatMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode~1clamp/title",
          "value": "SKRepeatModeClamp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode~1clamp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatModeClamp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode~1loop/title",
          "value": "SKRepeatModeLoop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.spritekit~1documentation~1SpriteKit~1SKRepeatMode~1loop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKRepeatModeLoop"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/spritekit/skrepeatmode/clamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/spritekit/skrepeatmode/clamp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
