{
  "abstract": [
    {
      "text": "Authenticate to the network.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.networkextension/documentation/NetworkExtension",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NEHotspotHelperCommandType@kNEHotspotHelperCommandTypeAuthenticate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "authenticate"
      }
    ],
    "modules": [
      {
        "name": "Network Extension"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kNEHotspotHelperCommandTypeAuthenticate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NEHotspotHelperCommandType.authenticate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "authenticate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension": {
      "abstract": [
        {
          "text": "Customize and extend core networking features.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension",
      "kind": "symbol",
      "role": "collection",
      "title": "Network Extension",
      "type": "topic",
      "url": "/documentation/networkextension"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NEHotspotHelperCommandType"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NEHotspotHelperCommandType"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate": {
      "abstract": [
        {
          "text": "Authenticate to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authenticate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/authenticate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeAuthenticate"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.authenticate",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/authenticate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/evaluate": {
      "abstract": [
        {
          "text": "Evaluate the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evaluate"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/evaluate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeEvaluate"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.evaluate",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/evaluate"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/filterScanList": {
      "abstract": [
        {
          "text": "Filter the Wi-Fi scan list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterScanList"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/filterScanList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeFilterScanList"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.filterScanList",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/filterscanlist"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/logoff": {
      "abstract": [
        {
          "text": "Logoff the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "logoff"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/logoff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeLogoff"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.logoff",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/logoff"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain": {
      "abstract": [
        {
          "text": "Maintain the connection to the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maintain"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeMaintain"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.maintain",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/maintain"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/none": {
      "abstract": [
        {
          "text": "Placeholder for the null command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypeNone"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.none",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/none"
    },
    "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI": {
      "abstract": [
        {
          "text": "Present user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentUI"
        }
      ],
      "identifier": "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kNEHotspotHelperCommandTypePresentUI"
        }
      ],
      "role": "symbol",
      "title": "NEHotspotHelperCommandType.presentUI",
      "type": "topic",
      "url": "/documentation/networkextension/nehotspothelpercommandtype/presentui"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Command-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/none",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/filterScanList",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/evaluate",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain",
        "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/logoff"
      ],
      "title": "Command Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kNEHotspotHelperCommandTypeAuthenticate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeAuthenticate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.networkextension/documentation/NetworkExtension",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Command-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/none",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/filterScanList",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/evaluate",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/presentUI",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/maintain",
                "doc://com.apple.networkextension/documentation/NetworkExtension/NEHotspotHelperCommandType/logoff"
              ],
              "title": "Command Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kNEHotspotHelperCommandTypeAuthenticate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1none/title",
          "value": "kNEHotspotHelperCommandTypeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1filterScanList/title",
          "value": "kNEHotspotHelperCommandTypeFilterScanList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1filterScanList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeFilterScanList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1presentUI/title",
          "value": "kNEHotspotHelperCommandTypePresentUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1presentUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypePresentUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1authenticate/title",
          "value": "kNEHotspotHelperCommandTypeAuthenticate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1authenticate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeAuthenticate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType/title",
          "value": "NEHotspotHelperCommandType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperCommandType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NEHotspotHelperCommandType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1evaluate/title",
          "value": "kNEHotspotHelperCommandTypeEvaluate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1evaluate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeEvaluate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1maintain/title",
          "value": "kNEHotspotHelperCommandTypeMaintain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1maintain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeMaintain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1logoff/title",
          "value": "kNEHotspotHelperCommandTypeLogoff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.networkextension~1documentation~1NetworkExtension~1NEHotspotHelperCommandType~1logoff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kNEHotspotHelperCommandTypeLogoff"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/networkextension/nehotspothelpercommandtype/authenticate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/networkextension/nehotspothelpercommandtype/authenticate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
