{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Screen-Time/documentation/ScreenTime",
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory",
        "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier/init(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So29STWebHistoryProfileIdentifierayABSScfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Screen Time"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Screen-Time/documentation/ScreenTime": {
      "abstract": [
        {
          "text": "Share and manage web-usage data, and observe changes made by a parent or guardian.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime",
      "kind": "symbol",
      "role": "collection",
      "title": "Screen Time",
      "type": "topic",
      "url": "/documentation/screentime"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory": {
      "abstract": [
        {
          "text": "The object you use to delete web-usage data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "STWebHistory"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier": {
      "abstract": [
        {
          "text": "An identifier representing a web history profile.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ProfileIdentifier"
        }
      ],
      "role": "symbol",
      "title": "STWebHistory.ProfileIdentifier",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory/profileidentifier"
    },
    "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier/init(_:)": {
      "abstract": [],
      "beta": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.Screen-Time/documentation/ScreenTime/STWebHistory/ProfileIdentifier/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/screentime/stwebhistory/profileidentifier/init(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/title",
          "value": "STWebHistory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/title",
          "value": "STWebHistoryProfileIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Screen-Time~1documentation~1ScreenTime~1STWebHistory~1ProfileIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "STWebHistoryProfileIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screentime/stwebhistory/profileidentifier/init(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
