{
  "abstract": [
    {
      "text": "Texture filtering for rendering the material property’s image contents at a size smaller than that of the original image.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/minificationFilter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNMaterialProperty(py)minificationFilter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "minificationFilter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCNFilterMode",
        "text": "SCNFilterMode"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "minificationFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "minificationFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "minificationFilter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNFilterMode",
              "text": "SCNFilterMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Texture filtering determines the appearance of a material property’s contents when portions of the material surface appear larger or smaller than the original texture image. For example, the texture coordinates at a point far from the camera may correspond to an area of several pixels in the texture image. SceneKit uses the minification filter to determine the color of the sampled texel at that point.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The default minification filter is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode/linear",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNWrapMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for available modes and their effects.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode": {
      "abstract": [
        {
          "text": "Texture filtering modes, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/minificationFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/magnificationFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mipFilter",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNFilterMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNFilterMode"
        }
      ],
      "role": "symbol",
      "title": "SCNFilterMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnfiltermode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode/linear": {
      "abstract": [
        {
          "text": "Texture filtering sample texels from the neighborhood of the coordinates being sampled and linearly interpolates their colors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "linear"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode/linear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNFilterModeLinear"
        }
      ],
      "role": "symbol",
      "title": "SCNFilterMode.linear",
      "type": "topic",
      "url": "/documentation/scenekit/scnfiltermode/linear"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty": {
      "abstract": [
        {
          "text": "A container for the color or texture of one of a material’s visual properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNMaterialProperty"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNMaterialProperty"
        }
      ],
      "role": "symbol",
      "title": "SCNMaterialProperty",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/borderColor": {
      "abstract": [
        {
          "text": "A color used to fill in areas of a material’s surface not covered by the material property’s image contents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "borderColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/borderColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderColor"
        }
      ],
      "role": "symbol",
      "title": "borderColor",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/bordercolor"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/contentsTransform": {
      "abstract": [
        {
          "text": "The transformation applied to the material property’s visual contents. Animatable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentsTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNMatrix4",
          "text": "SCNMatrix4"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/contentsTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentsTransform"
        }
      ],
      "role": "symbol",
      "title": "contentsTransform",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/contentstransform"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/magnificationFilter": {
      "abstract": [
        {
          "text": "Texture filtering for rendering the material property’s image contents at a size larger than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNFilterMode",
          "text": "SCNFilterMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/magnificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "magnificationFilter"
        }
      ],
      "role": "symbol",
      "title": "magnificationFilter",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/magnificationfilter"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mappingChannel": {
      "abstract": [
        {
          "text": "The source of texture coordinates for mapping the material property’s image contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mappingChannel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mappingChannel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mappingChannel"
        }
      ],
      "role": "symbol",
      "title": "mappingChannel",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/mappingchannel"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/maxAnisotropy": {
      "abstract": [
        {
          "text": "The amount of anisotropic texture filtering to be used when rendering the material property’s image contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maxAnisotropy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/maxAnisotropy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maxAnisotropy"
        }
      ],
      "role": "symbol",
      "title": "maxAnisotropy",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/maxanisotropy"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/minificationFilter": {
      "abstract": [
        {
          "text": "Texture filtering for rendering the material property’s image contents at a size smaller than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minificationFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNFilterMode",
          "text": "SCNFilterMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/minificationFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minificationFilter"
        }
      ],
      "role": "symbol",
      "title": "minificationFilter",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/minificationfilter"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mipFilter": {
      "abstract": [
        {
          "text": "Texture filtering for using mipmaps to render the material property’s image contents at a size smaller than that of the original image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mipFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNFilterMode",
          "text": "SCNFilterMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mipFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mipFilter"
        }
      ],
      "role": "symbol",
      "title": "mipFilter",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/mipfilter"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapS": {
      "abstract": [
        {
          "text": "The wrapping behavior for the S texture coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrapS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNWrapMode",
          "text": "SCNWrapMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wrapS"
        }
      ],
      "role": "symbol",
      "title": "wrapS",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/wraps"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapT": {
      "abstract": [
        {
          "text": "The wrapping behavior for the T texture coordinate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrapT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNWrapMode",
          "text": "SCNWrapMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wrapT"
        }
      ],
      "role": "symbol",
      "title": "wrapT",
      "type": "topic",
      "url": "/documentation/scenekit/scnmaterialproperty/wrapt"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNWrapMode": {
      "abstract": [
        {
          "text": "Modes to apply to texture wrapping, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapT",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapS",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNWrapMode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNWrapMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNWrapMode"
        }
      ],
      "role": "symbol",
      "title": "SCNWrapMode",
      "type": "topic",
      "url": "/documentation/scenekit/scnwrapmode"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-Texture-Mapping-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/contentsTransform",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapS",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapT",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNWrapMode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/magnificationFilter",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mipFilter",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/maxAnisotropy",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mappingChannel",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/borderColor"
      ],
      "title": "Configuring Texture Mapping Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "minificationFilter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-Texture-Mapping-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/contentsTransform",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapS",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/wrapT",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNWrapMode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/magnificationFilter",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mipFilter",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/maxAnisotropy",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/mappingChannel",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNMaterialProperty/borderColor"
              ],
              "title": "Configuring Texture Mapping Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNFilterMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SCNFilterMode",
                    "text": "SCNFilterMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "minificationFilter"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1wrapS/title",
          "value": "wrapS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1wrapS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wrapS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/title",
          "value": "SCNMaterialProperty"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNMaterialProperty"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNWrapMode/title",
          "value": "SCNWrapMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNWrapMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNWrapMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNWrapMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1minificationFilter/title",
          "value": "minificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1minificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1mipFilter/title",
          "value": "mipFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1mipFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mipFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1borderColor/title",
          "value": "borderColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1borderColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "borderColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1maxAnisotropy/title",
          "value": "maxAnisotropy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1maxAnisotropy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maxAnisotropy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1wrapT/title",
          "value": "wrapT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1wrapT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wrapT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1magnificationFilter/title",
          "value": "magnificationFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1magnificationFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "magnificationFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1mappingChannel/title",
          "value": "mappingChannel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1mappingChannel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mappingChannel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1contentsTransform/title",
          "value": "contentsTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNMaterialProperty~1contentsTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentsTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFilterMode/title",
          "value": "SCNFilterMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFilterMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFilterMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFilterMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFilterMode~1linear/title",
          "value": "SCNFilterModeLinear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNFilterMode~1linear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNFilterModeLinear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnmaterialproperty/minificationfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnmaterialproperty/minificationfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
