{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orange"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicolor/orange"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicolor/orange"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIColor/orange","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"orangeColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"platforms":[{"introducedAt":"2.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"2.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"},{"beta":false,"name":"watchOS","unavailable":false,"deprecated":false,"introducedAt":"2.0"}],"roleHeading":"Type Property","title":"orange","symbolKind":"property","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIColor(cpy)orangeColor"},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/black","doc://com.apple.uikit/documentation/UIKit/UIColor/blue","doc://com.apple.uikit/documentation/UIKit/UIColor/brown","doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","doc://com.apple.uikit/documentation/UIKit/UIColor/gray","doc://com.apple.uikit/documentation/UIKit/UIColor/green","doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","doc://com.apple.uikit/documentation/UIKit/UIColor/purple","doc://com.apple.uikit/documentation/UIKit/UIColor/red","doc://com.apple.uikit/documentation/UIKit/UIColor/white","doc://com.apple.uikit/documentation/UIKit/UIColor/yellow"],"anchor":"Fixed-colors","generated":true,"title":"Fixed colors"}],"abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.5","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIColor/green":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"green","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"greenColor","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicolor/green","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/green","title":"green"},"doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lightGray"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"/documentation/uikit/uicolor/lightgray","title":"lightGray","navigatorTitle":[{"kind":"identifier","text":"lightGrayColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","abstract":[{"type":"text","text":"A color object with a grayscale value of 2/3 and an alpha value of "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/red":{"navigatorTitle":[{"text":"redColor","kind":"identifier"}],"url":"/documentation/uikit/uicolor/red","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"red","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/red","title":"red","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/black":{"navigatorTitle":[{"kind":"identifier","text":"blackColor"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/black","abstract":[{"type":"text","text":"A color object in the sRGB color space with a grayscale value of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"black"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"/documentation/uikit/uicolor/black","title":"black","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray":{"abstract":[{"text":"A color object with a grayscale value of 1/3 and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkGray","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/darkgray","navigatorTitle":[{"text":"darkGrayColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","type":"topic","title":"darkGray","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/magenta":{"type":"topic","role":"symbol","title":"magenta","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magenta","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"magentaColor","kind":"identifier"}],"abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"url":"/documentation/uikit/uicolor/magenta","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/purple":{"abstract":[{"type":"text","text":"A color object with RGB values of "},{"code":"0.5","type":"codeVoice"},{"type":"text","text":", "},{"code":"0.0","type":"codeVoice"},{"type":"text","text":", and "},{"code":"0.5","type":"codeVoice"},{"type":"text","text":", and an alpha value of "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purple"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/purple","navigatorTitle":[{"kind":"identifier","text":"purpleColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/purple","type":"topic","title":"purple","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/gray":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"/documentation/uikit/uicolor/gray","title":"gray","navigatorTitle":[{"kind":"identifier","text":"grayColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/gray","abstract":[{"text":"A color object with a grayscale value of ","type":"text"},{"type":"codeVoice","code":"0.5"},{"text":" and an alpha value of ","type":"text"},{"type":"codeVoice","code":"1.0"},{"text":".","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/brown":{"navigatorTitle":[{"kind":"identifier","text":"brownColor"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/brown","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"/documentation/uikit/uicolor/brown","abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.6"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.4"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.2"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"title":"brown","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/cyan":{"type":"topic","role":"symbol","title":"cyan","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cyan","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"cyanColor","kind":"identifier"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/cyan","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/blue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"url":"/documentation/uikit/uicolor/blue","navigatorTitle":[{"text":"blueColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/blue","title":"blue"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/orange":{"type":"topic","role":"symbol","title":"orange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"orangeColor","kind":"identifier"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.5"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/orange","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/orange","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/yellow":{"navigatorTitle":[{"kind":"identifier","text":"yellowColor"}],"title":"yellow","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/yellow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"yellow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/yellow","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/white":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/white","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"whiteColor"}],"url":"/documentation/uikit/uicolor/white","title":"white","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"white"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"type":"text","text":"A color object with a grayscale value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor":{"type":"topic","role":"symbol","title":"UIColor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIColor","kind":"identifier"}],"navigatorTitle":[{"text":"UIColor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/uikit/uicolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"2.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0"},{"unavailable":false,"name":"watchOS","beta":false,"deprecated":false,"introducedAt":"2.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Property","op":"replace"},{"path":"/metadata/title","value":"orangeColor","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"orangeColor","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Fixed colors","anchor":"Fixed-colors","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/black","doc://com.apple.uikit/documentation/UIKit/UIColor/blue","doc://com.apple.uikit/documentation/UIKit/UIColor/brown","doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","doc://com.apple.uikit/documentation/UIKit/UIColor/gray","doc://com.apple.uikit/documentation/UIKit/UIColor/green","doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","doc://com.apple.uikit/documentation/UIKit/UIColor/purple","doc://com.apple.uikit/documentation/UIKit/UIColor/red","doc://com.apple.uikit/documentation/UIKit/UIColor/white","doc://com.apple.uikit/documentation/UIKit/UIColor/yellow"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor"},{"text":" * ","kind":"text"},{"text":"orangeColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1green/title","op":"replace","value":"greenColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1green/fragments","op":"replace","value":[{"kind":"identifier","text":"greenColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightGray/title","op":"replace","value":"lightGrayColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightGray/fragments","op":"replace","value":[{"kind":"identifier","text":"lightGrayColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1red/title","op":"replace","value":"redColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1red/fragments","op":"replace","value":[{"text":"redColor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1black/title","op":"replace","value":"blackColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1black/fragments","op":"replace","value":[{"kind":"identifier","text":"blackColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkGray/title","op":"replace","value":"darkGrayColor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkGray/fragments","op":"replace","value":[{"kind":"identifier","text":"darkGrayColor"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1magenta/title","op":"replace","value":"magentaColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1magenta/fragments","value":[{"kind":"identifier","text":"magentaColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1purple/title","value":"purpleColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1purple/fragments","value":[{"kind":"identifier","text":"purpleColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1gray/title","value":"grayColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1gray/fragments","value":[{"kind":"identifier","text":"grayColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1brown/title","value":"brownColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1brown/fragments","value":[{"text":"brownColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1cyan/title","value":"cyanColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1cyan/fragments","value":[{"text":"cyanColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1blue/title","value":"blueColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1blue/fragments","value":[{"text":"blueColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1orange/title","value":"orangeColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1orange/fragments","value":[{"text":"orangeColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1yellow/title","value":"yellowColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1yellow/fragments","value":[{"kind":"identifier","text":"yellowColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1white/title","value":"whiteColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1white/fragments","value":[{"kind":"identifier","text":"whiteColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title","value":"UIColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments","value":[{"text":"UIColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle","value":[{"kind":"identifier","text":"UIColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}