{"seeAlsoSections":[{"anchor":"Applying-the-color-to-the-drawing-environment","title":"Applying the color to the drawing environment","identifiers":["doc://com.apple.uikit/documentation/UIKit/customizing-drawings","doc://com.apple.uikit/documentation/UIKit/UIColor/setFill()","doc://com.apple.uikit/documentation/UIKit/UIColor/setStroke()"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicolor/set()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicolor/set()"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"sections":[],"metadata":{"externalID":"c:objc(cs)UIColor(im)set","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"set"},{"kind":"text","text":"()"}],"role":"symbol","platforms":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","title":"set()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"set"}]},"abstract":[{"type":"text","text":"Sets the color of subsequent stroke and fill operations to the color that the receiver represents."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"If you subclass ","type":"text"},{"code":"UIColor","type":"codeVoice"},{"text":", you must implement this method in your subclass. Your custom implementation should modify both the stroke and fill color in the current graphics context by setting them both to the color represented by the receiver.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIColor/set()"},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UIColor":{"type":"topic","role":"symbol","title":"UIColor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIColor","kind":"identifier"}],"navigatorTitle":[{"text":"UIColor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/uikit/uicolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/setStroke()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setStroke","kind":"identifier"},{"text":"()","kind":"text"}],"title":"setStroke()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/setStroke()","role":"symbol","type":"topic","url":"/documentation/uikit/uicolor/setstroke()","abstract":[{"type":"text","text":"Sets the color of subsequent stroke operations to the color that the receiver represents."}],"kind":"symbol","navigatorTitle":[{"text":"setStroke","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/set()":{"abstract":[{"type":"text","text":"Sets the color of subsequent stroke and fill operations to the color that the receiver represents."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"set","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uicolor/set()","title":"set()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/set()","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/setFill()":{"abstract":[{"type":"text","text":"Sets the color of subsequent fill operations to the color that the receiver represents."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setFill","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setFill","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uicolor/setfill()","title":"setFill()","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/setFill()","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/customizing-drawings":{"abstract":[{"type":"text","text":"Create custom colors and patterns for drawing in your app."}],"type":"topic","role":"article","url":"/documentation/uikit/customizing-drawings","title":"Customizing drawings","identifier":"doc://com.apple.uikit/documentation/UIKit/customizing-drawings","kind":"article"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"name":"iOS","introducedAt":"2.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"2.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"set","path":"/metadata/title"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"set","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/customizing-drawings","doc://com.apple.uikit/documentation/UIKit/UIColor/setFill()","doc://com.apple.uikit/documentation/UIKit/UIColor/setStroke()"],"anchor":"Applying-the-color-to-the-drawing-environment","generated":true,"title":"Applying the color to the drawing environment"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"set"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"UIColor","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title"},{"op":"replace","value":[{"text":"UIColor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIColor"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle"},{"op":"replace","value":"setStroke","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1setStroke()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setStroke","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1setStroke()/fragments"},{"op":"replace","value":"set","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1set()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"set"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1set()/fragments"},{"op":"replace","value":"setFill","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1setFill()/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFill"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1setFill()/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}