{"abstract":[{"type":"text","text":"A pink color that automatically adapts to the current trait environment."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPink","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uicolor/systempink"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicolor/systempink"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"seeAlsoSections":[{"anchor":"Adaptable-colors","title":"Adaptable colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal","doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Property","platforms":[{"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"7.0","unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"introducedAt":"9.0","unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"name":"visionOS","beta":false}],"navigatorTitle":[{"kind":"identifier","text":"systemPinkColor"}],"extendedModule":"UIKit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemPink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"systemPink","symbolKind":"property","externalID":"c:objc(cs)UIColor(cpy)systemPinkColor","modules":[{"name":"UIKit"}]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen":{"navigatorTitle":[{"text":"systemGreenColor","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","abstract":[{"type":"text","text":"A green color that automatically adapts to the current trait environment."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemGreen","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicolor/systemgreen","title":"systemGreen","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal":{"url":"/documentation/uikit/uicolor/systemteal","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"systemTeal","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"abstract":[{"text":"A teal color that automatically adapts to the current trait environment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"systemTealColor","kind":"identifier"}],"type":"topic","role":"symbol","title":"systemTeal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","type":"topic","url":"/documentation/uikit/uicolor/systembrown","title":"systemBrown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemBrownColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemBrown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"A brown color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","abstract":[{"type":"text","text":"A mint color that automatically adapts to the current trait environment."}],"title":"systemMint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemMint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"systemMintColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/systemmint","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple":{"navigatorTitle":[{"text":"systemPurpleColor","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","abstract":[{"type":"text","text":"A purple color that automatically adapts to the current trait environment."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPurple","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicolor/systempurple","title":"systemPurple","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","type":"topic","url":"/documentation/uikit/uicolor/systemred","title":"systemRed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemRedColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemRed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"text":"A red color that automatically adapts to the current trait environment.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","type":"topic","url":"/documentation/uikit/uicolor/systemcyan","title":"systemCyan","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemCyanColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemCyan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"A cyan color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","abstract":[{"type":"text","text":"An orange color that automatically adapts to the current trait environment."}],"title":"systemOrange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemOrange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"systemOrangeColor","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uicolor/systemorange","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPink","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink","type":"topic","abstract":[{"text":"A pink color that automatically adapts to the current trait environment.","type":"text"}],"url":"/documentation/uikit/uicolor/systempink","title":"systemPink","navigatorTitle":[{"text":"systemPinkColor","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","navigatorTitle":[{"text":"systemBlueColor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemBlue","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","abstract":[{"text":"A blue color that automatically adapts to the current trait environment.","type":"text"}],"title":"systemBlue","url":"/documentation/uikit/uicolor/systemblue","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"systemIndigoColor","kind":"identifier"}],"title":"systemIndigo","url":"/documentation/uikit/uicolor/systemindigo","abstract":[{"type":"text","text":"An indigo color that automatically adapts to the current trait environment."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemIndigo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemYellow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"systemYellowColor","kind":"identifier"}],"title":"systemYellow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow","type":"topic","url":"/documentation/uikit/uicolor/systemyellow","kind":"symbol","abstract":[{"type":"text","text":"A yellow color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor":{"type":"topic","role":"symbol","title":"UIColor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIColor","kind":"identifier"}],"navigatorTitle":[{"text":"UIColor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/uikit/uicolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"7.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"7.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"9.0","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Property"},{"op":"replace","path":"/metadata/title","value":"systemPinkColor"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"systemPinkColor","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Adaptable colors","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal","doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow"],"anchor":"Adaptable-colors"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"text":"systemPinkColor","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGreen/title","value":"systemGreenColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGreen/fragments","value":[{"kind":"identifier","text":"systemGreenColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemTeal/title","value":"systemTealColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemTeal/fragments","value":[{"kind":"identifier","text":"systemTealColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBrown/title","value":"systemBrownColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBrown/fragments","value":[{"text":"systemBrownColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemMint/title","value":"systemMintColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemMint/fragments","value":[{"text":"systemMintColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPurple/title","value":"systemPurpleColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPurple/fragments","value":[{"kind":"identifier","text":"systemPurpleColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemRed/title","value":"systemRedColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemRed/fragments","value":[{"text":"systemRedColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemCyan/title","value":"systemCyanColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemCyan/fragments","value":[{"kind":"identifier","text":"systemCyanColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemOrange/title","value":"systemOrangeColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemOrange/fragments","value":[{"text":"systemOrangeColor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPink/title","value":"systemPinkColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPink/fragments","value":[{"kind":"identifier","text":"systemPinkColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBlue/title","value":"systemBlueColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBlue/fragments","value":[{"kind":"identifier","text":"systemBlueColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemIndigo/title","value":"systemIndigoColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemIndigo/fragments","value":[{"kind":"identifier","text":"systemIndigoColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemYellow/title","value":"systemYellowColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemYellow/fragments","value":[{"kind":"identifier","text":"systemYellowColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title","value":"UIColor","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments","value":[{"kind":"identifier","text":"UIColor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle","value":[{"kind":"identifier","text":"UIColor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}