{
  "abstract": [
    {
      "text": "Notifications aren’t allowed.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.usernotifications/documentation/UserNotifications",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationsNotAllowed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UNErrorCode@UNErrorCodeNotificationsNotAllowed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notificationsNotAllowed"
      }
    ],
    "modules": [
      {
        "name": "User Notifications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UNErrorCodeNotificationsNotAllowed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.14",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UNError.Code.notificationsNotAllowed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notificationsNotAllowed"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This error occurs when you try to submit a notification request and your app or app extension isn’t authorized to schedule notifications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "UserNotifications-PageImage-card.png": {
      "alt": "[A notification interface displayed on the lock screen of an iOS device.]",
      "identifier": "UserNotifications-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/074de9a9213bf2905d67fae5eb46e4f8/UserNotifications-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5733742e1c084fc202b3c92df9083686/UserNotifications-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications": {
      "abstract": [
        {
          "text": "Push user-facing notifications to the user’s device from a server, or generate them locally from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications",
      "images": [
        {
          "identifier": "UserNotifications-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "User Notifications",
      "type": "topic",
      "url": "/documentation/usernotifications"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError": {
      "abstract": [
        {
          "text": "An object that represents a notification error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNError"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNError"
        }
      ],
      "role": "symbol",
      "title": "UNError",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code": {
      "abstract": [
        {
          "text": "Constants that identify notification errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentCorrupt": {
      "abstract": [
        {
          "text": "The file for an attachment is corrupt.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentCorrupt"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentCorrupt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentCorrupt"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentCorrupt",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentcorrupt"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidFileSize": {
      "abstract": [
        {
          "text": "An attachment is too large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentInvalidFileSize"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidFileSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentInvalidFileSize"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentInvalidFileSize",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentinvalidfilesize"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidURL": {
      "abstract": [
        {
          "text": "The URL for an attachment was invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentInvalidURL"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentInvalidURL"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentInvalidURL",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentinvalidurl"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentMoveIntoDataStoreFailed": {
      "abstract": [
        {
          "text": "An error occurred when trying to move an attachment to the system data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentMoveIntoDataStoreFailed"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentMoveIntoDataStoreFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentMoveIntoDataStoreFailed"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentMoveIntoDataStoreFailed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentmoveintodatastorefailed"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentNotInDataStore": {
      "abstract": [
        {
          "text": "The specified attachment isn’t in the system data store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentNotInDataStore"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentNotInDataStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentNotInDataStore"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentNotInDataStore",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentnotindatastore"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentUnrecognizedType": {
      "abstract": [
        {
          "text": "The file type of an attachment isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attachmentUnrecognizedType"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentUnrecognizedType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeAttachmentUnrecognizedType"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.attachmentUnrecognizedType",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/attachmentunrecognizedtype"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingInvalid": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProvidingInvalid"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingInvalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeContentProvidingInvalid"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.contentProvidingInvalid",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/contentprovidinginvalid"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingObjectNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentProvidingObjectNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingObjectNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeContentProvidingObjectNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.contentProvidingObjectNotAllowed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/contentprovidingobjectnotallowed"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoContent": {
      "abstract": [
        {
          "text": "The notification has no user-facing content, but should.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationInvalidNoContent"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeNotificationInvalidNoContent"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.notificationInvalidNoContent",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/notificationinvalidnocontent"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoDate": {
      "abstract": [
        {
          "text": "The notification doesn’t have an associated date, but should.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationInvalidNoDate"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeNotificationInvalidNoDate"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.notificationInvalidNoDate",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/notificationinvalidnodate"
    },
    "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationsNotAllowed": {
      "abstract": [
        {
          "text": "Notifications aren’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationsNotAllowed"
        }
      ],
      "identifier": "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationsNotAllowed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UNErrorCodeNotificationsNotAllowed"
        }
      ],
      "role": "symbol",
      "title": "UNError.Code.notificationsNotAllowed",
      "type": "topic",
      "url": "/documentation/usernotifications/unerror/code/notificationsnotallowed"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidURL",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentUnrecognizedType",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidFileSize",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentNotInDataStore",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentMoveIntoDataStoreFailed",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentCorrupt",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoDate",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoContent",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingInvalid",
        "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingObjectNotAllowed"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.14",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UNErrorCodeNotificationsNotAllowed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeNotificationsNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.usernotifications/documentation/UserNotifications",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidURL",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentUnrecognizedType",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentInvalidFileSize",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentNotInDataStore",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentMoveIntoDataStoreFailed",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/attachmentCorrupt",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoDate",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/notificationInvalidNoContent",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingInvalid",
                "doc://com.apple.usernotifications/documentation/UserNotifications/UNError/Code/contentProvidingObjectNotAllowed"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UNErrorCodeNotificationsNotAllowed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationsNotAllowed/title",
          "value": "UNErrorCodeNotificationsNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationsNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeNotificationsNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationInvalidNoContent/title",
          "value": "UNErrorCodeNotificationInvalidNoContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationInvalidNoContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeNotificationInvalidNoContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationInvalidNoDate/title",
          "value": "UNErrorCodeNotificationInvalidNoDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1notificationInvalidNoDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeNotificationInvalidNoDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1contentProvidingObjectNotAllowed/title",
          "value": "UNErrorCodeContentProvidingObjectNotAllowed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1contentProvidingObjectNotAllowed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeContentProvidingObjectNotAllowed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentUnrecognizedType/title",
          "value": "UNErrorCodeAttachmentUnrecognizedType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentUnrecognizedType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentUnrecognizedType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentInvalidURL/title",
          "value": "UNErrorCodeAttachmentInvalidURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentInvalidURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentInvalidURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/title",
          "value": "UNErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentCorrupt/title",
          "value": "UNErrorCodeAttachmentCorrupt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentCorrupt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentCorrupt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentInvalidFileSize/title",
          "value": "UNErrorCodeAttachmentInvalidFileSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentInvalidFileSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentInvalidFileSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1contentProvidingInvalid/title",
          "value": "UNErrorCodeContentProvidingInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1contentProvidingInvalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeContentProvidingInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentNotInDataStore/title",
          "value": "UNErrorCodeAttachmentNotInDataStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentNotInDataStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentNotInDataStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentMoveIntoDataStoreFailed/title",
          "value": "UNErrorCodeAttachmentMoveIntoDataStoreFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.usernotifications~1documentation~1UserNotifications~1UNError~1Code~1attachmentMoveIntoDataStoreFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UNErrorCodeAttachmentMoveIntoDataStoreFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/usernotifications/unerror/code/notificationsnotallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/usernotifications/unerror/code/notificationsnotallowed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
