{
  "abstract": [
    {
      "text": "The Y padding.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_padding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@BNNSPoolingLayerParameters@FI@y_padding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "y_padding"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "y_padding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.0",
        "name": "iOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.0",
        "name": "iPadOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.12",
        "name": "macOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "10.0",
        "name": "tvOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "7.0",
        "introducedAt": "3.0",
        "name": "watchOS",
        "renamed": "BNNSLayerParametersPooling",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "y_padding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "y_padding"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Virtual 0 values added to the left and right of each channel of the input stack.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters": {
      "abstract": [
        {
          "text": "A structure containing pooling layer parameters.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BNNSPoolingLayerParameters"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BNNSPoolingLayerParameters"
        }
      ],
      "role": "symbol",
      "title": "BNNSPoolingLayerParameters",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/activation": {
      "abstract": [
        {
          "text": "The layer activation function.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSActivation",
          "text": "BNNSActivation"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/activation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activation"
        }
      ],
      "role": "symbol",
      "title": "activation",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/activation"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/bias": {
      "abstract": [
        {
          "text": "Layer bias, one for each output channel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bias"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@BNNSLayerData",
          "text": "BNNSLayerData"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/bias",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bias"
        }
      ],
      "role": "symbol",
      "title": "bias",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/bias"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/in_channels": {
      "abstract": [
        {
          "text": "The number of input channels.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "in_channels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/in_channels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "in_channels"
        }
      ],
      "role": "symbol",
      "title": "in_channels",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/in_channels"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_height": {
      "abstract": [
        {
          "text": "The height of the convolution kernel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k_height"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_height",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k_height"
        }
      ],
      "role": "symbol",
      "title": "k_height",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/k_height"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_width": {
      "abstract": [
        {
          "text": "The width of the convolution kernel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "k_width"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_width",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "k_width"
        }
      ],
      "role": "symbol",
      "title": "k_width",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/k_width"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/out_channels": {
      "abstract": [
        {
          "text": "The number of output channels.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "out_channels"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/out_channels",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "out_channels"
        }
      ],
      "role": "symbol",
      "title": "out_channels",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/out_channels"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/pooling_function": {
      "abstract": [
        {
          "text": "The pooling function to apply to each sample.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pooling_function"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@EA@BNNSPoolingFunction",
          "text": "BNNSPoolingFunction"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/pooling_function",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pooling_function"
        }
      ],
      "role": "symbol",
      "title": "pooling_function",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/pooling_function"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_padding": {
      "abstract": [
        {
          "text": "The X padding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x_padding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_padding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "x_padding"
        }
      ],
      "role": "symbol",
      "title": "x_padding",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/x_padding"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_stride": {
      "abstract": [
        {
          "text": "The X increment in the input image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "x_stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "x_stride"
        }
      ],
      "role": "symbol",
      "title": "x_stride",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/x_stride"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_padding": {
      "abstract": [
        {
          "text": "The Y padding.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "y_padding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_padding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "y_padding"
        }
      ],
      "role": "symbol",
      "title": "y_padding",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/y_padding"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_stride": {
      "abstract": [
        {
          "text": "The Y increment in the input image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "y_stride"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_stride",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "y_stride"
        }
      ],
      "role": "symbol",
      "title": "y_stride",
      "type": "topic",
      "url": "/documentation/accelerate/bnnspoolinglayerparameters/y_stride"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@size_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "size_t",
      "type": "topic",
      "url": "/documentation/kernel/size_t"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/activation",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/bias",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/in_channels",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_height",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_width",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/out_channels",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/pooling_function",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_padding",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_stride",
        "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_stride"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "7.0",
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "y_padding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y_padding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/activation",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/bias",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/in_channels",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_height",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/k_width",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/out_channels",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/pooling_function",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_padding",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/x_stride",
                "doc://com.apple.accelerate/documentation/Accelerate/BNNSPoolingLayerParameters/y_stride"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@size_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@size_t",
                    "text": "size_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "y_padding"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1bias/title",
          "value": "bias"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1bias/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bias"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters/title",
          "value": "BNNSPoolingLayerParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingLayerParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BNNSPoolingLayerParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1x_padding/title",
          "value": "x_padding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1x_padding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "x_padding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1k_height/title",
          "value": "k_height"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1k_height/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k_height"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1y_padding/title",
          "value": "y_padding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1y_padding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y_padding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1pooling_function/title",
          "value": "pooling_function"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1pooling_function/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pooling_function"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1x_stride/title",
          "value": "x_stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1x_stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "x_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1activation/title",
          "value": "activation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1activation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1y_stride/title",
          "value": "y_stride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1y_stride/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "y_stride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1k_width/title",
          "value": "k_width"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1k_width/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "k_width"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1out_channels/title",
          "value": "out_channels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1out_channels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "out_channels"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1in_channels/title",
          "value": "in_channels"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BNNSPoolingLayerParameters~1in_channels/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "in_channels"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/bnnspoolinglayerparameters/y_padding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/bnnspoolinglayerparameters/y_padding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
