{
  "abstract": [
    {
      "text": "The numerical order of the episode, if the media item is an episode of a TV series.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episodeOrder"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ITLibMediaItemVideoInfo(py)episodeOrder",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "episodeOrder"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "episodeOrder"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "episodeOrder"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "episodeOrder"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " if the media item isn’t an episode of a TV series.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo": {
      "abstract": [
        {
          "text": "This class encapsulates the video information of a video media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemVideoInfo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemVideoInfo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemVideoInfo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episode": {
      "abstract": [
        {
          "text": "The name of the episode, if the media item is an episode of a TV series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "episode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "episode"
        }
      ],
      "role": "symbol",
      "title": "episode",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/episode"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episodeOrder": {
      "abstract": [
        {
          "text": "The numerical order of the episode, if the media item is an episode of a TV series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "episodeOrder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episodeOrder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "episodeOrder"
        }
      ],
      "role": "symbol",
      "title": "episodeOrder",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/episodeorder"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/isHD": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the video is high-definition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isHD"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/isHD",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hd"
        }
      ],
      "role": "symbol",
      "title": "isHD",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/ishd"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/season": {
      "abstract": [
        {
          "text": "The corresponding TV season, if the media item is an episode of a TV series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "season"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/season",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "season"
        }
      ],
      "role": "symbol",
      "title": "season",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/season"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/series": {
      "abstract": [
        {
          "text": "The name of the corresponding TV series, if the media item is an episode in a TV series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "series"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/series",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "series"
        }
      ],
      "role": "symbol",
      "title": "series",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/series"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/sortSeries": {
      "abstract": [
        {
          "text": "The sorting name of the corresponding TV series, if the media item is an episode in a TV series.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sortSeries"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/sortSeries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sortSeries"
        }
      ],
      "role": "symbol",
      "title": "sortSeries",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/sortseries"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoHeight": {
      "abstract": [
        {
          "text": "The height of the video in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoHeight"
        }
      ],
      "role": "symbol",
      "title": "videoHeight",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/videoheight"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoWidth": {
      "abstract": [
        {
          "text": "The width of the video in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "videoWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "videoWidth"
        }
      ],
      "role": "symbol",
      "title": "videoWidth",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemvideoinfo/videowidth"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Video-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoWidth",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoHeight",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/series",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/sortSeries",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/season",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/isHD",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episode"
      ],
      "title": "Getting Video Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "episodeOrder"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "episodeOrder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Video-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoWidth",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/videoHeight",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/series",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/sortSeries",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/season",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/isHD",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemVideoInfo/episode"
              ],
              "title": "Getting Video Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "assign"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "episodeOrder"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1videoWidth/title",
          "value": "videoWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1videoWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/title",
          "value": "ITLibMediaItemVideoInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemVideoInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemVideoInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1videoHeight/title",
          "value": "videoHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1videoHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "videoHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1season/title",
          "value": "season"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1season/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "season"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1episode/title",
          "value": "episode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1episode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "episode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1series/title",
          "value": "series"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1series/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "series"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1sortSeries/title",
          "value": "sortSeries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1sortSeries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sortSeries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1isHD/title",
          "value": "hd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1isHD/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1episodeOrder/title",
          "value": "episodeOrder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemVideoInfo~1episodeOrder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "episodeOrder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemvideoinfo/episodeorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemvideoinfo/episodeorder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
