{
  "abstract": [
    {
      "text": "A property-based merge policy that applies external changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSMergePolicy(cpy)mergeByPropertyStoreTrumpMergePolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mergeByPropertyStoreTrump"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSMergePolicy",
        "text": "NSMergePolicy"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mergeByPropertyStoreTrumpMergePolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "mergeByPropertyStoreTrump"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mergeByPropertyStoreTrump"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSMergePolicy",
              "text": "NSMergePolicy"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A policy that merges conflicts between the persistent store’s version of the object and the current in-memory version by individual property, with external changes trumping in-memory changes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy": {
      "abstract": [
        {
          "text": "A policy object that you use to resolve conflicts between the persistent store and in-memory versions of managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errorMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/error"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyObjectTrump"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeByPropertyObjectTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergeByPropertyObjectTrump",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/mergebypropertyobjecttrump"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyStoreTrump"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeByPropertyStoreTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergeByPropertyStoreTrump",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/mergebypropertystoretrump"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite": {
      "abstract": [
        {
          "text": "A merge policy that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overwrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overwriteMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "overwrite",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/overwrite"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rollbackMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "rollback",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/rollback"
    },
    "doc://com.apple.coredata/documentation/CoreData/merge-policies": {
      "abstract": [
        {
          "text": "Define standard ways to handle conflicts during a save operation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/merge-policies",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Merge Policies",
      "type": "topic",
      "url": "/documentation/coredata/merge-policies"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-Merge-Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback",
        "doc://com.apple.coredata/documentation/CoreData/merge-policies"
      ],
      "title": "Defining Merge Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-Merge-Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback",
                "doc://com.apple.coredata/documentation/CoreData/merge-policies"
              ],
              "title": "Defining Merge Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSMergePolicy",
                    "text": "NSMergePolicy"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "mergeByPropertyStoreTrumpMergePolicy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1error/title",
          "value": "errorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1overwrite/title",
          "value": "overwriteMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1overwrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overwriteMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyStoreTrump/title",
          "value": "mergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyStoreTrump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/title",
          "value": "NSMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyObjectTrump/title",
          "value": "mergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyObjectTrump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergeByPropertyObjectTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1rollback/title",
          "value": "rollbackMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1rollback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rollbackMergePolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmergepolicy/mergebypropertystoretrump"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsmergepolicy/mergebypropertystoretrump"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
