{
  "abstract": [
    {
      "text": "The calendar supports the busy event availability setting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkit/documentation/EventKit",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKCalendarEventAvailabilityMask@EKCalendarEventAvailabilityBusy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "busy"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
        "text": "EKCalendarEventAvailabilityMask"
      }
    ],
    "modules": [
      {
        "name": "EventKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKCalendarEventAvailabilityBusy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "busy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "busy"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
              "text": "EKCalendarEventAvailabilityMask"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkit/documentation/EventKit": {
      "abstract": [
        {
          "text": "Create, view, and edit calendar and reminder events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit",
      "type": "topic",
      "url": "/documentation/eventkit"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask": {
      "abstract": [
        {
          "text": "A bitmask indicating the event availability settings that the calendar can support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "role": "symbol",
      "title": "EKCalendarEventAvailabilityMask",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone": {
      "abstract": [
        {
          "text": "The calendar does not support event availability settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityNone"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "EKCalendarEventAvailabilityNone",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/ekcalendareventavailabilitynone"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy": {
      "abstract": [
        {
          "text": "The calendar supports the busy event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityBusy"
        }
      ],
      "role": "symbol",
      "title": "busy",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/busy"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free": {
      "abstract": [
        {
          "text": "The calendar supports the free event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "free"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityFree"
        }
      ],
      "role": "symbol",
      "title": "free",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/free"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative": {
      "abstract": [
        {
          "text": "The calendar supports the tentative event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tentative"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityTentative"
        }
      ],
      "role": "symbol",
      "title": "tentative",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/tentative"
    },
    "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable": {
      "abstract": [
        {
          "text": "The calendar supports the unavailable event availability setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unavailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKCalendarEventAvailabilityMask",
          "text": "EKCalendarEventAvailabilityMask"
        }
      ],
      "identifier": "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKCalendarEventAvailabilityUnavailable"
        }
      ],
      "role": "symbol",
      "title": "unavailable",
      "type": "topic",
      "url": "/documentation/eventkit/ekcalendareventavailabilitymask/unavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
        "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKCalendarEventAvailabilityBusy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkit/documentation/EventKit",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/free",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/tentative",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/unavailable",
                "doc://com.apple.eventkit/documentation/EventKit/EKCalendarEventAvailabilityMask/EKCalendarEventAvailabilityNone"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKCalendarEventAvailabilityBusy"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1unavailable/title",
          "value": "EKCalendarEventAvailabilityUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1unavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1free/title",
          "value": "EKCalendarEventAvailabilityFree"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1free/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityFree"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1tentative/title",
          "value": "EKCalendarEventAvailabilityTentative"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1tentative/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityTentative"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1busy/title",
          "value": "EKCalendarEventAvailabilityBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/title",
          "value": "EKCalendarEventAvailabilityMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkit~1documentation~1EventKit~1EKCalendarEventAvailabilityMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKCalendarEventAvailabilityMask"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkit/ekcalendareventavailabilitymask/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkit/ekcalendareventavailabilitymask/busy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
