{
  "abstract": [
    {
      "text": "Constants that represents control change event types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@E@AVMIDIControlChangeMessageType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "MessageType"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MessageType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVMIDIControlChangeEvent.MessageType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MessageType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent": {
      "abstract": [
        {
          "text": "An object that represents a MIDI control change message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeEvent"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeEvent"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that represents control change event types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageType"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_LSB": {
      "abstract": [
        {
          "text": "An event type that represents the registered parameter number LSB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPN_LSB"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_LSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeRPN_LSB"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.RPN_LSB",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/rpn_lsb"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_MSB": {
      "abstract": [
        {
          "text": "An event type that represents the registered parameter number MSB.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RPN_MSB"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_MSB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeRPN_MSB"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.RPN_MSB",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/rpn_msb"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allNotesOff": {
      "abstract": [
        {
          "text": "An event type for muting all sounding notes while maintaining the release time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allNotesOff"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allNotesOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeAllNotesOff"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.allNotesOff",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/allnotesoff"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allSoundOff": {
      "abstract": [
        {
          "text": "An event type for muting all sounding notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allSoundOff"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allSoundOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeAllSoundOff"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.allSoundOff",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/allsoundoff"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/attackTime": {
      "abstract": [
        {
          "text": "An event type for controlling the attack time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attackTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/attackTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeAttackTime"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.attackTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/attacktime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance": {
      "abstract": [
        {
          "text": "An event type for controlling the left and right channel balance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "balance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBalance"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.balance",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/balance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect": {
      "abstract": [
        {
          "text": "An event type for switching bank selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bankSelect"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBankSelect"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.bankSelect",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/bankselect"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath": {
      "abstract": [
        {
          "text": "An event type for a breath controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "breath"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBreath"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.breath",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/breath"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/brightness": {
      "abstract": [
        {
          "text": "An event type for controlling the brightness.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brightness"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/brightness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeBrightness"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.brightness",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/brightness"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/chorusLevel": {
      "abstract": [
        {
          "text": "An event type for controlling the chorus level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chorusLevel"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/chorusLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeChorusLevel"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.chorusLevel",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/choruslevel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry": {
      "abstract": [
        {
          "text": "An event type for controlling the data entry parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataEntry"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeDataEntry"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.dataEntry",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/dataentry"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/decayTime": {
      "abstract": [
        {
          "text": "An event type for controlling the decay time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "decayTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/decayTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeDecayTime"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.decayTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/decaytime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression": {
      "abstract": [
        {
          "text": "An event type that represents an expression controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expression"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeExpression"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.expression",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/expression"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/filterResonance": {
      "abstract": [
        {
          "text": "An event type for a filter resonance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "filterResonance"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/filterResonance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeFilterResonance"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.filterResonance",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/filterresonance"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot": {
      "abstract": [
        {
          "text": "An event type for sending continuous stream of values when using a foot controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "foot"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeFoot"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.foot",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/foot"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal": {
      "abstract": [
        {
          "text": "An event type for holding notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hold2Pedal"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeHold2Pedal"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.hold2Pedal",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/hold2pedal"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal": {
      "abstract": [
        {
          "text": "An event type for switching the legato pedal on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legatoPedal"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeLegatoPedal"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.legatoPedal",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/legatopedal"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel": {
      "abstract": [
        {
          "text": "An event type for modulating a vibrato effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modWheel"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeModWheel"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.modWheel",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/modwheel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOff": {
      "abstract": [
        {
          "text": "An event type for setting the device mode to polyphonic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoModeOff"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeMonoModeOff"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.monoModeOff",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/monomodeoff"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOn": {
      "abstract": [
        {
          "text": "An event type for setting the device mode to monophonic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoModeOn"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeMonoModeOn"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.monoModeOn",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/monomodeon"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOff": {
      "abstract": [
        {
          "text": "An event type for setting omni off mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "omniModeOff"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeOmniModeOff"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.omniModeOff",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/omnimodeoff"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOn": {
      "abstract": [
        {
          "text": "An event type for setting omni on mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "omniModeOn"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeOmniModeOn"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.omniModeOn",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/omnimodeon"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan": {
      "abstract": [
        {
          "text": "An event type for controlling the left and right channel pan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pan"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePan"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.pan",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/pan"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento": {
      "abstract": [
        {
          "text": "An event type for switching portamento on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portamento"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePortamento"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.portamento",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamento"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime": {
      "abstract": [
        {
          "text": "An event type for controlling the portamento rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portamentoTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypePortamentoTime"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.portamentoTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/portamentotime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/releaseTime": {
      "abstract": [
        {
          "text": "An event type for controlling the release time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "releaseTime"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/releaseTime",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeReleaseTime"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.releaseTime",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/releasetime"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/resetAllControllers": {
      "abstract": [
        {
          "text": "An event type for resetting all controllers to their default state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resetAllControllers"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/resetAllControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeResetAllControllers"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.resetAllControllers",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/resetallcontrollers"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/reverbLevel": {
      "abstract": [
        {
          "text": "An event type for controlling the reverb level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reverbLevel"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/reverbLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeReverbLevel"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.reverbLevel",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/reverblevel"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft": {
      "abstract": [
        {
          "text": "An event type for lowering the volume of the notes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soft"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSoft"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.soft",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/soft"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto": {
      "abstract": [
        {
          "text": "An event type for switching sostenuto on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sostenuto"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSostenuto"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.sostenuto",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/sostenuto"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain": {
      "abstract": [
        {
          "text": "An event type for switching a damper pedal on or off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sustain"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeSustain"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.sustain",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/sustain"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDelay": {
      "abstract": [
        {
          "text": "An event type for controlling the vibrato delay.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vibratoDelay"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDelay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeVibratoDelay"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.vibratoDelay",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/vibratodelay"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDepth": {
      "abstract": [
        {
          "text": "An event type for controlling the vibrato depth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vibratoDepth"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDepth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeVibratoDepth"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.vibratoDepth",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/vibratodepth"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoRate": {
      "abstract": [
        {
          "text": "An event type for controlling the vibrato rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vibratoRate"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoRate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeVibratoRate"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.vibratoRate",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/vibratorate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume": {
      "abstract": [
        {
          "text": "An event type for controlling the channel volume.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "volume"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVMIDIControlChangeMessageTypeVolume"
        }
      ],
      "role": "symbol",
      "title": "AVMIDIControlChangeEvent.MessageType.volume",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum/volume"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/messageType-swift.property": {
      "abstract": [
        {
          "text": "The type of control change message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVMIDIControlChangeEvent",
          "text": "AVMIDIControlChangeEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVMIDIControlChangeMessageType",
          "text": "MessageType"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/messageType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "messageType"
        }
      ],
      "role": "symbol",
      "title": "messageType",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/value": {
      "abstract": [
        {
          "text": "The value of the control change event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/value",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "value"
        }
      ],
      "role": "symbol",
      "title": "value",
      "type": "topic",
      "url": "/documentation/avfaudio/avmidicontrolchangeevent/value"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-a-Control-Change-Event",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/value",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/messageType-swift.property"
      ],
      "title": "Inspecting a Control Change Event"
    }
  ],
  "topicSections": [
    {
      "anchor": "Event-Types",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/filterResonance",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/releaseTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/attackTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/brightness",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/decayTime",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoRate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDepth",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDelay",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/reverbLevel",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/chorusLevel",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_LSB",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_MSB",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allSoundOff",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/resetAllControllers",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allNotesOff",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOff",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOn",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOn",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOff"
      ],
      "title": "Event Types"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVMIDIControlChangeMessageType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Event-Types",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/bankSelect",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/modWheel",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/breath",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/foot",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamentoTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/dataEntry",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/volume",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/balance",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/pan",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/expression",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sustain",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/portamento",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/sostenuto",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/soft",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/legatoPedal",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/hold2Pedal",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/filterResonance",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/releaseTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/attackTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/brightness",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/decayTime",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoRate",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDepth",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/vibratoDelay",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/reverbLevel",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/chorusLevel",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_LSB",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/RPN_MSB",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allSoundOff",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/resetAllControllers",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/allNotesOff",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOff",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/omniModeOn",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOn",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/MessageType-swift.enum/monoModeOff"
              ],
              "title": "Event Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-a-Control-Change-Event",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/value",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVMIDIControlChangeEvent/messageType-swift.property"
              ],
              "title": "Inspecting a Control Change Event"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVMIDIControlChangeMessageType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1messageType-swift.property/title",
          "value": "messageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1messageType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "messageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1filterResonance/title",
          "value": "AVMIDIControlChangeMessageTypeFilterResonance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1filterResonance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeFilterResonance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1hold2Pedal/title",
          "value": "AVMIDIControlChangeMessageTypeHold2Pedal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1hold2Pedal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeHold2Pedal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/title",
          "value": "AVMIDIControlChangeMessageType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoRate/title",
          "value": "AVMIDIControlChangeMessageTypeVibratoRate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoRate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeVibratoRate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1expression/title",
          "value": "AVMIDIControlChangeMessageTypeExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1expression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1allNotesOff/title",
          "value": "AVMIDIControlChangeMessageTypeAllNotesOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1allNotesOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeAllNotesOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1brightness/title",
          "value": "AVMIDIControlChangeMessageTypeBrightness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1brightness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBrightness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoDelay/title",
          "value": "AVMIDIControlChangeMessageTypeVibratoDelay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoDelay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeVibratoDelay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1omniModeOn/title",
          "value": "AVMIDIControlChangeMessageTypeOmniModeOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1omniModeOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeOmniModeOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1omniModeOff/title",
          "value": "AVMIDIControlChangeMessageTypeOmniModeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1omniModeOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeOmniModeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1RPN_LSB/title",
          "value": "AVMIDIControlChangeMessageTypeRPN_LSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1RPN_LSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeRPN_LSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sostenuto/title",
          "value": "AVMIDIControlChangeMessageTypeSostenuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sostenuto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSostenuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sustain/title",
          "value": "AVMIDIControlChangeMessageTypeSustain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1sustain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSustain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1releaseTime/title",
          "value": "AVMIDIControlChangeMessageTypeReleaseTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1releaseTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeReleaseTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1resetAllControllers/title",
          "value": "AVMIDIControlChangeMessageTypeResetAllControllers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1resetAllControllers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeResetAllControllers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1decayTime/title",
          "value": "AVMIDIControlChangeMessageTypeDecayTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1decayTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeDecayTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1dataEntry/title",
          "value": "AVMIDIControlChangeMessageTypeDataEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1dataEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeDataEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/title",
          "value": "AVMIDIControlChangeEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamentoTime/title",
          "value": "AVMIDIControlChangeMessageTypePortamentoTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamentoTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePortamentoTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1foot/title",
          "value": "AVMIDIControlChangeMessageTypeFoot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1foot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeFoot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1bankSelect/title",
          "value": "AVMIDIControlChangeMessageTypeBankSelect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1bankSelect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBankSelect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1allSoundOff/title",
          "value": "AVMIDIControlChangeMessageTypeAllSoundOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1allSoundOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeAllSoundOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1volume/title",
          "value": "AVMIDIControlChangeMessageTypeVolume"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1volume/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeVolume"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1breath/title",
          "value": "AVMIDIControlChangeMessageTypeBreath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1breath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBreath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1balance/title",
          "value": "AVMIDIControlChangeMessageTypeBalance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1balance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeBalance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1value/title",
          "value": "value"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1value/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "value"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1chorusLevel/title",
          "value": "AVMIDIControlChangeMessageTypeChorusLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1chorusLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeChorusLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1monoModeOn/title",
          "value": "AVMIDIControlChangeMessageTypeMonoModeOn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1monoModeOn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeMonoModeOn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1reverbLevel/title",
          "value": "AVMIDIControlChangeMessageTypeReverbLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1reverbLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeReverbLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoDepth/title",
          "value": "AVMIDIControlChangeMessageTypeVibratoDepth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1vibratoDepth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeVibratoDepth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1legatoPedal/title",
          "value": "AVMIDIControlChangeMessageTypeLegatoPedal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1legatoPedal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeLegatoPedal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1modWheel/title",
          "value": "AVMIDIControlChangeMessageTypeModWheel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1modWheel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeModWheel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1monoModeOff/title",
          "value": "AVMIDIControlChangeMessageTypeMonoModeOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1monoModeOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeMonoModeOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1attackTime/title",
          "value": "AVMIDIControlChangeMessageTypeAttackTime"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1attackTime/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeAttackTime"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1soft/title",
          "value": "AVMIDIControlChangeMessageTypeSoft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1soft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeSoft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1pan/title",
          "value": "AVMIDIControlChangeMessageTypePan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1pan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1RPN_MSB/title",
          "value": "AVMIDIControlChangeMessageTypeRPN_MSB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1RPN_MSB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypeRPN_MSB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamento/title",
          "value": "AVMIDIControlChangeMessageTypePortamento"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVMIDIControlChangeEvent~1MessageType-swift.enum~1portamento/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVMIDIControlChangeMessageTypePortamento"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avmidicontrolchangeevent/messagetype-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
