{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder/evenPageOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)ICScannerFunctionalUnitDocumentFeeder(py)evenPageOrientation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "evenPageOrientation"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ICEXIFOrientationType",
        "text": "ICEXIFOrientationType"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "evenPageOrientation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "evenPageOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "evenPageOrientation"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ICEXIFOrientationType",
              "text": "ICEXIFOrientationType"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType": {
      "abstract": [
        {
          "text": "The file’s orientation type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICEXIFOrientationType"
        }
      ],
      "role": "symbol",
      "title": "ICEXIFOrientationType",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icexiforientationtype"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder": {
      "abstract": [
        {
          "text": "An object that represents the document feeder unit on a scanner.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICScannerFunctionalUnitDocumentFeeder"
        }
      ],
      "role": "symbol",
      "title": "ICScannerFunctionalUnitDocumentFeeder",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder/evenPageOrientation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "evenPageOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICEXIFOrientationType",
          "text": "ICEXIFOrientationType"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder/evenPageOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "evenPageOrientation"
        }
      ],
      "role": "symbol",
      "title": "evenPageOrientation",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder/evenpageorientation"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "evenPageOrientation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "evenPageOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
                "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICScannerFunctionalUnitDocumentFeeder"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICEXIFOrientationType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@ICEXIFOrientationType",
                    "text": "ICEXIFOrientationType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "evenPageOrientation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder~1evenPageOrientation/title",
          "value": "evenPageOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder~1evenPageOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "evenPageOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/title",
          "value": "ICScannerFunctionalUnitDocumentFeeder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICScannerFunctionalUnitDocumentFeeder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICScannerFunctionalUnitDocumentFeeder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/title",
          "value": "ICEXIFOrientationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICEXIFOrientationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICEXIFOrientationType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder/evenpageorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/imagecapturecore/icscannerfunctionalunitdocumentfeeder/evenpageorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
