{
  "abstract": [
    {
      "text": "The mode allowing the selection of a single display through the presented picker.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleDisplay"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SCContentSharingPickerMode@SCContentSharingPickerModeSingleDisplay",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "singleDisplay"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
        "text": "SCContentSharingPickerMode"
      }
    ],
    "modules": [
      {
        "name": "ScreenCaptureKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SCContentSharingPickerModeSingleDisplay"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "singleDisplay"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "singleDisplay"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
              "text": "SCContentSharingPickerMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit": {
      "abstract": [
        {
          "text": "Filter and select screen content and stream it to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
      "kind": "symbol",
      "role": "collection",
      "title": "ScreenCaptureKit",
      "type": "topic",
      "url": "/documentation/screencapturekit"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode": {
      "abstract": [
        {
          "text": "Available modes for selecting streaming content from a picker presented by the operating system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "role": "symbol",
      "title": "SCContentSharingPickerMode",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleApplications": {
      "abstract": [
        {
          "text": "The mode allowing the selection of multiple applications through the presented picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleApplications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleApplications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerModeMultipleApplications"
        }
      ],
      "role": "symbol",
      "title": "multipleApplications",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode/multipleapplications"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleWindows": {
      "abstract": [
        {
          "text": "The mode allowing the selection of multiple windows through the presented picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleWindows"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleWindows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerModeMultipleWindows"
        }
      ],
      "role": "symbol",
      "title": "multipleWindows",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode/multiplewindows"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleApplication": {
      "abstract": [
        {
          "text": "The mode allowing the selection of a single application through the presented picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerModeSingleApplication"
        }
      ],
      "role": "symbol",
      "title": "singleApplication",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode/singleapplication"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleDisplay": {
      "abstract": [
        {
          "text": "The mode allowing the selection of a single display through the presented picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleDisplay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleDisplay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerModeSingleDisplay"
        }
      ],
      "role": "symbol",
      "title": "singleDisplay",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode/singledisplay"
    },
    "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleWindow": {
      "abstract": [
        {
          "text": "The mode allowing the selection of a single window through the presented picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "singleWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCContentSharingPickerMode",
          "text": "SCContentSharingPickerMode"
        }
      ],
      "identifier": "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCContentSharingPickerModeSingleWindow"
        }
      ],
      "role": "symbol",
      "title": "singleWindow",
      "type": "topic",
      "url": "/documentation/screencapturekit/sccontentsharingpickermode/singlewindow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Picker-selection-modes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleApplications",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleWindows",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleApplication",
        "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleWindow"
      ],
      "title": "Picker selection modes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.2",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SCContentSharingPickerModeSingleDisplay"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeSingleDisplay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Picker-selection-modes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleApplications",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/multipleWindows",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleApplication",
                "doc://com.apple.screencapturekit/documentation/ScreenCaptureKit/SCContentSharingPickerMode/singleWindow"
              ],
              "title": "Picker selection modes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SCContentSharingPickerModeSingleDisplay"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleWindow/title",
          "value": "SCContentSharingPickerModeSingleWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeSingleWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleApplication/title",
          "value": "SCContentSharingPickerModeSingleApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeSingleApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/title",
          "value": "SCContentSharingPickerMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1multipleApplications/title",
          "value": "SCContentSharingPickerModeMultipleApplications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1multipleApplications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeMultipleApplications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1multipleWindows/title",
          "value": "SCContentSharingPickerModeMultipleWindows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1multipleWindows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeMultipleWindows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleDisplay/title",
          "value": "SCContentSharingPickerModeSingleDisplay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.screencapturekit~1documentation~1ScreenCaptureKit~1SCContentSharingPickerMode~1singleDisplay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCContentSharingPickerModeSingleDisplay"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/screencapturekit/sccontentsharingpickermode/singledisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/screencapturekit/sccontentsharingpickermode/singledisplay"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
