{
  "abstract": [
    {
      "text": "Sets the page layout’s values to those stored in the print info object used when the page layout panel is run.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Deprecated in OS X v10.5. This method should not be invoked directly, so there is no replacement.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPageLayout(im)readPrintInfo",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "readPrintInfo"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "readPrintInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.5",
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "readPrintInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "readPrintInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Do not invoke this method directly; it is invoked automatically before the receiver is displayed.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout": {
      "abstract": [
        {
          "text": "A panel that queries the user for information such as paper type and orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPageLayout"
        }
      ],
      "role": "symbol",
      "title": "NSPageLayout",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView": {
      "abstract": [
        {
          "text": "Returns the page layout panel’s accessory view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessoryView"
        }
      ],
      "role": "symbol",
      "title": "accessoryView",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/accessoryview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo": {
      "abstract": [
        {
          "text": "The printing information object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInfo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInfo"
        }
      ],
      "role": "symbol",
      "title": "printInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/printinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo": {
      "abstract": [
        {
          "text": "Sets the page layout’s values to those stored in the print info object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "readPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/readPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "readPrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/readprintinfo"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()": {
      "abstract": [
        {
          "text": "Displays the page layout panel and begins the modal loop using the shared print info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModal"
        }
      ],
      "role": "symbol",
      "title": "runModal()",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/runmodal()"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)": {
      "abstract": [
        {
          "text": "Displays the page layout panel and begins the modal loop using the specified print info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runModal"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPrintInfo",
          "text": "NSPrintInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runModalWithPrintInfo:"
        }
      ],
      "role": "symbol",
      "title": "runModal(with:)",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/runmodal(with:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:": {
      "abstract": [
        {
          "text": "Adds a view object to the page layout panel.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAccessoryView:"
        }
      ],
      "role": "symbol",
      "title": "setAccessoryView:",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/setaccessoryview:"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo": {
      "abstract": [
        {
          "text": "Writes the page layout’s values to the print info object used when the page layout panel is run.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "writePrintInfo"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writePrintInfo"
        }
      ],
      "role": "symbol",
      "title": "writePrintInfo",
      "type": "topic",
      "url": "/documentation/appkit/nspagelayout/writeprintinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/printInfo",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal()",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/runModal(with:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/accessoryView",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/setAccessoryView:",
        "doc://com.apple.appkit/documentation/AppKit/NSPageLayout/writePrintInfo"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal(with:)/title",
          "value": "runModalWithPrintInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModalWithPrintInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/title",
          "value": "NSPageLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPageLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal()/title",
          "value": "runModal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1runModal()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runModal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1printInfo/title",
          "value": "printInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPageLayout~1printInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspagelayout/readprintinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
