{
  "abstract": [
    {
      "text": "Creates a search call history intent object with the specified search criteria.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(callType:dateCreated:recipient:callCapabilities:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "Intents",
    "externalID": "c:objc(cs)INSearchCallHistoryIntent(im)initWithCallType:dateCreated:recipient:callCapabilities:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "callType"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INCallRecordType",
        "text": "INCallRecordType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "dateCreated"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
        "text": "INDateComponentsRange"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "recipient"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)INPerson",
        "text": "INPerson"
      },
      {
        "kind": "text",
        "text": "?, "
      },
      {
        "kind": "externalParam",
        "text": "callCapabilities"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INCallCapabilityOptions",
        "text": "INCallCapabilityOptions"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithCallType:dateCreated:recipient:callCapabilities:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "Use the designated initializer instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.0",
        "introducedAt": "10.0",
        "message": "Use the designated initializer instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use the designated initializer instead",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "Use the designated initializer instead",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "4.0",
        "introducedAt": "3.2",
        "message": "Use the designated initializer instead",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(callType:dateCreated:recipient:callCapabilities:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "callType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INCallRecordType",
              "text": "INCallRecordType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "dateCreated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
              "text": "INDateComponentsRange"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "recipient"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INPerson",
              "text": "INPerson"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "callCapabilities"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INCallCapabilityOptions",
              "text": "INCallCapabilityOptions"
            },
            {
              "kind": "text",
              "text": " = [])"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "call"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "callType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INCallRecordType",
              "text": "INCallRecordType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "dateCreated"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
              "text": "INDateComponentsRange"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "recipient"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)INPerson",
              "text": "INPerson"
            },
            {
              "kind": "text",
              "text": "?, "
            },
            {
              "kind": "externalParam",
              "text": "callCapabilities"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INCallCapabilityOptions",
              "text": "INCallCapabilityOptions"
            },
            {
              "kind": "text",
              "text": " = [])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of call to search. Use this parameter to specify whether you want to search all calls or search only outgoing calls, missed calls, or received calls.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The dates associated with the call records. Use this parameter to specify the range of dates to search.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "dateCreated"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The person who received the call. Match the information in this parameter against the user’s contacts.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "recipient"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The audio-video capabilities of the call. Use this parameter to specify whether you want to search audio-only calls, video calls, or both. You can combine the constants of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " type as needed.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "callCapabilities"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Normally, you don’t create instances of this class yourself. Instead, Siri creates instances when the user asks to search their call history. However, you can use this method during testing to create intent objects in order to validate your intent handling code paths.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions": {
      "abstract": [
        {
          "text": "Constants indicating the capabilities of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallCapabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallCapabilityOptions"
        }
      ],
      "role": "symbol",
      "title": "INCallCapabilityOptions",
      "type": "topic",
      "url": "/documentation/intents/incallcapabilityoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INCallRecordType": {
      "abstract": [
        {
          "text": "Constants describing the type of the call.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INCallRecordType"
        }
      ],
      "role": "symbol",
      "title": "INCallRecordType",
      "type": "topic",
      "url": "/documentation/intents/incallrecordtype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange": {
      "abstract": [
        {
          "text": "A span of time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INDateComponentsRange"
        }
      ],
      "role": "symbol",
      "title": "INDateComponentsRange",
      "type": "topic",
      "url": "/documentation/intents/indatecomponentsrange"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPerson": {
      "abstract": [
        {
          "text": "Information about a person participating in a SiriKit interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPerson"
        }
      ],
      "role": "symbol",
      "title": "INPerson",
      "type": "topic",
      "url": "/documentation/intents/inperson"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent": {
      "abstract": [
        {
          "text": "A request to list the calls matching the specified criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchCallHistoryIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(callType:dateCreated:recipient:callCapabilities:)": {
      "abstract": [
        {
          "text": "Creates a search call history intent object with the specified search criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "callType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordType",
          "text": "INCallRecordType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "recipient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "callCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallCapabilityOptions",
          "text": "INCallCapabilityOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(callType:dateCreated:recipient:callCapabilities:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCallType:dateCreated:recipient:callCapabilities:"
        }
      ],
      "role": "symbol",
      "title": "init(callType:dateCreated:recipient:callCapabilities:)",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/init(calltype:datecreated:recipient:callcapabilities:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(dateCreated:recipient:callCapabilities:callTypes:unseen:)": {
      "abstract": [
        {
          "text": "Creates a search call history intent object with the specified search criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "recipient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INPerson",
          "text": "INPerson"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "callCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallCapabilityOptions",
          "text": "INCallCapabilityOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "callTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordTypeOptions",
          "text": "INCallRecordTypeOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "unseen"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(dateCreated:recipient:callCapabilities:callTypes:unseen:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(dateCreated:recipient:callCapabilities:callTypes:unseen:)",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/init(datecreated:recipient:callcapabilities:calltypes:unseen:)"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/initWithDateCreated:recipient:callCapabilities:callTypes:unseen:": {
      "abstract": [
        {
          "text": "Initializes the search call history intent object with the specified search criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithDateCreated:recipient:callCapabilities:callTypes:unseen:"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/initWithDateCreated:recipient:callCapabilities:callTypes:unseen:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDateCreated:recipient:callCapabilities:callTypes:unseen:"
        }
      ],
      "role": "symbol",
      "title": "initWithDateCreated:recipient:callCapabilities:callTypes:unseen:",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/initwithdatecreated:recipient:callcapabilities:calltypes:unseen:"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-the-Intent-Object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/init(dateCreated:recipient:callCapabilities:callTypes:unseen:)"
      ],
      "title": "Initializing the Intent Object"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "11.0",
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "4.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithCallType:dateCreated:recipient:callCapabilities:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCallType:dateCreated:recipient:callCapabilities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-the-Intent-Object",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/initWithDateCreated:recipient:callCapabilities:callTypes:unseen:"
              ],
              "title": "Initializing the Intent Object"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithCallType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallRecordType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INCallRecordType",
                    "text": "INCallRecordType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "dateCreated:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INDateComponentsRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
                    "text": "INDateComponentsRange"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "dateCreated"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "recipient:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INPerson",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)INPerson",
                    "text": "INPerson"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "recipient"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "callCapabilities:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@INCallCapabilityOptions",
                    "text": "INCallCapabilityOptions"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "callCapabilities"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of call to search. Use this parameter to specify whether you want to search all calls or search only outgoing calls, missed calls, or received calls.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The dates associated with the call records. Use this parameter to specify the range of dates to search.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "dateCreated"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The person who received the call. Match the information in this parameter against the user’s contacts.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "recipient"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The audio-video capabilities of the call. Use this parameter to specify whether you want to search audio-only calls, video calls, or both. You can combine the constants of the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.sirikit/documentation/Intents/INCallCapabilityOptions",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " type as needed.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "callCapabilities"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/title",
          "value": "INDateComponentsRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INDateComponentsRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INDateComponentsRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/title",
          "value": "INPerson"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPerson/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPerson"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1init(callType:dateCreated:recipient:callCapabilities:)/title",
          "value": "initWithCallType:dateCreated:recipient:callCapabilities:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1init(callType:dateCreated:recipient:callCapabilities:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCallType:dateCreated:recipient:callCapabilities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapabilityOptions/title",
          "value": "INCallCapabilityOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapabilityOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallCapabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallCapabilityOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallCapabilityOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/title",
          "value": "INSearchCallHistoryIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/title",
          "value": "INCallRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INCallRecordType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INCallRecordType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchcallhistoryintent/init(calltype:datecreated:recipient:callcapabilities:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/insearchcallhistoryintent/init(calltype:datecreated:recipient:callcapabilities:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
