{
  "abstract": [
    {
      "text": "A Boolean value that indicates whether the user has seen the call yet.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/unseen-1mohp"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)INSearchCallHistoryIntent(py)unseen",
    "fragments": [
      {
        "kind": "identifier",
        "text": "unseen"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "unseen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "unseen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "atomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "unseen"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNumber",
              "text": "NSNumber"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "unseen"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent": {
      "abstract": [
        {
          "text": "A request to list the calls matching the specified criteria.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INSearchCallHistoryIntent"
        }
      ],
      "role": "symbol",
      "title": "INSearchCallHistoryIntent",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callCapabilities": {
      "abstract": [
        {
          "text": "The audio-video capabilities of the call.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callCapabilities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallCapabilityOptions",
          "text": "INCallCapabilityOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callCapabilities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callCapabilities"
        }
      ],
      "role": "symbol",
      "title": "callCapabilities",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/callcapabilities"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callType": {
      "abstract": [
        {
          "text": "The call type.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordType",
          "text": "INCallRecordType"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callType"
        }
      ],
      "role": "symbol",
      "title": "callType",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/calltype"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callTypes": {
      "abstract": [
        {
          "text": "The types of calls to search.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INCallRecordTypeOptions",
          "text": "INCallRecordTypeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "callTypes"
        }
      ],
      "role": "symbol",
      "title": "callTypes",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/calltypes"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/dateCreated": {
      "abstract": [
        {
          "text": "The range of dates associated with the call records.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateCreated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)INDateComponentsRange",
          "text": "INDateComponentsRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/dateCreated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dateCreated"
        }
      ],
      "role": "symbol",
      "title": "dateCreated",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/datecreated"
    },
    "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/unseen-1mohp": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user has seen the call yet.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "unseen"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/unseen-1mohp",
      "kind": "symbol",
      "role": "symbol",
      "title": "unseen",
      "type": "topic",
      "url": "/documentation/intents/insearchcallhistoryintent/unseen-1mohp"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Call-History-Details",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/dateCreated",
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callTypes",
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callType",
        "doc://com.apple.sirikit/documentation/Intents/INSearchCallHistoryIntent/callCapabilities"
      ],
      "title": "Getting the Call History Details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callCapabilities/title",
          "value": "callCapabilities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callCapabilities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callCapabilities"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/title",
          "value": "INSearchCallHistoryIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INSearchCallHistoryIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1dateCreated/title",
          "value": "dateCreated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1dateCreated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dateCreated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callType/title",
          "value": "callType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callTypes/title",
          "value": "callTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INSearchCallHistoryIntent~1callTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "callTypes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/insearchcallhistoryintent/unseen-1mohp"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
