{"abstract":[{"text":"Rounds values toward -inf.","type":"text"}],"sections":[],"kind":"symbol","identifier":{"url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/floor","interfaceLanguage":"swift"},"metadata":{"role":"symbol","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}],"modules":[{"name":"Metal Performance Shaders Graph"}],"title":"MPSGraphResizeNearestRoundingMode.floor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingModeFloor"}],"externalID":"c:@E@MPSGraphResizeNearestRoundingMode@MPSGraphResizeNearestRoundingModeFloor","symbolKind":"case"},"variants":[{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/floor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/floor"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/floor":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"floor"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingModeFloor"}],"title":"MPSGraphResizeNearestRoundingMode.floor","url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/floor","abstract":[{"type":"text","text":"Rounds values toward -inf."}],"kind":"symbol","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/floor"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode":{"url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"abstract":[{"text":"The rounding mode to use when using nearest resize mode.","type":"text"}],"type":"topic","title":"MPSGraphResizeNearestRoundingMode","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode","role":"symbol"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"16.0","beta":false},{"deprecated":false,"name":"macOS","introducedAt":"13.0","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","introducedAt":"16.0","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Enumeration Case","path":"/metadata/roleHeading"},{"op":"replace","value":"MPSGraphResizeNearestRoundingModeFloor","path":"/metadata/title"},{"op":"replace","value":"case","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"MPSGraphResizeNearestRoundingModeFloor","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MPSGraphResizeNearestRoundingModeFloor","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":"MPSGraphResizeNearestRoundingModeFloor","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode~1floor/title"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingModeFloor"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode~1floor/fragments"},{"op":"replace","value":"MPSGraphResizeNearestRoundingMode","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/title"},{"op":"replace","value":[{"text":"MPSGraphResizeNearestRoundingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/fragments"},{"op":"replace","value":[{"text":"MPSGraphResizeNearestRoundingMode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}