{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","identifier":"doc://com.externally.resolved.symbol/s:Su","text":"UInt"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"modules":[{"name":"Metal Performance Shaders Graph"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"s:So33MPSGraphResizeNearestRoundingModeV8rawValueABSgSu_tcfc"},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/init(rawValue:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/init(rawvalue:)"]}],"references":{"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode":{"url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"abstract":[{"text":"The rounding mode to use when using nearest resize mode.","type":"text"}],"type":"topic","title":"MPSGraphResizeNearestRoundingMode","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode","role":"symbol"},"doc://com.externally.resolved.symbol/s:Su":{"abstract":[{"type":"text","text":"An unsigned integer value type."}],"fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UInt"}],"identifier":"doc://com.externally.resolved.symbol/s:Su","type":"topic","title":"UInt","role":"symbol","url":"/documentation/Swift/UInt","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/init(rawValue:)":{"abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","type":"topic","url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/init(rawvalue:)"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/title","value":"MPSGraphResizeNearestRoundingMode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/fragments"},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/navigatorTitle","value":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}