{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/roundtoeven"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/roundtoeven"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/roundToEven","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"MPSGraphResizeNearestRoundingModeRoundToEven","kind":"identifier"}],"externalID":"c:@E@MPSGraphResizeNearestRoundingMode@MPSGraphResizeNearestRoundingModeRoundToEven","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"roundToEven","kind":"identifier"}],"modules":[{"name":"Metal Performance Shaders Graph"}],"roleHeading":"Case","role":"symbol","platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.3","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"16.3","name":"iPadOS"},{"introducedAt":"16.3","beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"13.2","beta":false,"unavailable":false,"name":"macOS","deprecated":false},{"introducedAt":"16.3","beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"introducedAt":"1.0","beta":false,"unavailable":false,"name":"visionOS","deprecated":false}],"title":"MPSGraphResizeNearestRoundingMode.roundToEven"},"abstract":[{"text":"Rounds values to the nearest integer value, with 0.5f rounding toward the closest even value.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"roundToEven"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode"]]},"references":{"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/roundToEven":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"roundToEven","kind":"identifier"}],"navigatorTitle":[{"text":"MPSGraphResizeNearestRoundingModeRoundToEven","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode/roundtoeven","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode/roundToEven","title":"MPSGraphResizeNearestRoundingMode.roundToEven","type":"topic","abstract":[{"text":"Rounds values to the nearest integer value, with 0.5f rounding toward the closest even value.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","title":"Technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode":{"url":"/documentation/metalperformanceshadersgraph/mpsgraphresizenearestroundingmode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"navigatorTitle":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}],"abstract":[{"text":"The rounding mode to use when using nearest resize mode.","type":"text"}],"type":"topic","title":"MPSGraphResizeNearestRoundingMode","identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode","role":"symbol"},"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph":{"role":"collection","kind":"symbol","url":"/documentation/metalperformanceshadersgraph","abstract":[{"type":"text","text":"Build, compile, and execute compute graphs utilizing all the different compute devices on the platform, including GPU, CPU, and Neural Engine."}],"identifier":"doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","title":"Metal Performance Shaders Graph","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"16.3"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"16.3"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"16.3"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"13.2"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"16.3"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"MPSGraphResizeNearestRoundingModeRoundToEven"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"MPSGraphResizeNearestRoundingModeRoundToEven","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph","doc://com.apple.metalperformanceshadersgraph/documentation/MetalPerformanceShadersGraph/MPSGraphResizeNearestRoundingMode"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"MPSGraphResizeNearestRoundingModeRoundToEven","kind":"identifier"}]}]}},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode~1roundToEven/title","value":"MPSGraphResizeNearestRoundingModeRoundToEven"},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode~1roundToEven/fragments","value":[{"text":"MPSGraphResizeNearestRoundingModeRoundToEven","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/title","value":"MPSGraphResizeNearestRoundingMode"},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/fragments","value":[{"text":"MPSGraphResizeNearestRoundingMode","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.metalperformanceshadersgraph~1documentation~1MetalPerformanceShadersGraph~1MPSGraphResizeNearestRoundingMode/navigatorTitle","value":[{"kind":"identifier","text":"MPSGraphResizeNearestRoundingMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}