{
  "abstract": [
    {
      "text": "Creates an authorization mechanism.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.security/documentation/Security",
        "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@AuthorizationPluginInterface@FI@MechanismCreate",
    "fragments": [
      {
        "kind": "identifier",
        "text": "MechanismCreate"
      }
    ],
    "modules": [
      {
        "name": "Security"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MechanismCreate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "10.4",
        "name": "macOS"
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "MechanismCreate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:*FI(#*v#*$@S@__OpaqueAuthorizationEngine#*1C#*S2_)",
              "text": "int (*)(void *, struct __OpaqueAuthorizationEngine *, const char *, void **)"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MechanismCreate"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The authorization plug-in reference you assigned to the plug-in in the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inPlugin"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An opaque handle that you must pass back to the authorization engine when you call one of the engine’s callback functions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inEngine"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The mechanism ID specified in the authorization policy database is passed to the plug-in so that the plug-in can create the appropriate mechanism.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mechanismId"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, points to an authorization mechanism reference that you define. The authorization engine includes this reference when it calls your plug-in so that you can identify which instance of a mechanism to invoke, deactivate, or destroy.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "outMechanism"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A result code. Return ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (no error) if the function completes successfully and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Security Server internal error) if any error occurs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A given authorization plug-in can implement any number of authorization mechanisms, distinguished by their mechanism names in the authorization policy database.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When the authorization engine calls your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function, you should create a mechanism of the type specified by the mechanismID parameter and return an authorization mechanism reference. Subsequently, the authorization engine can call your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismInvoke",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to perform an authorization, or can direct you to deactivate or destroy the mechanism instance by calling your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDeactivate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.security/documentation/Security": {
      "abstract": [
        {
          "text": "Secure the data your app manages, and control access to your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security",
      "kind": "symbol",
      "role": "collection",
      "title": "Security",
      "type": "topic",
      "url": "/documentation/security"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate": {
      "abstract": [
        {
          "text": "Initializes the plug-in and exchanges interfaces with the authorization engine.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationPluginCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationPluginCreate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugincreate"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface": {
      "abstract": [
        {
          "text": "The interface that must be implemented by your plug-in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AuthorizationPluginInterface"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface",
      "kind": "symbol",
      "role": "symbol",
      "title": "AuthorizationPluginInterface",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate": {
      "abstract": [
        {
          "text": "Creates an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismCreate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismCreate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismCreate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismcreate"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDeactivate": {
      "abstract": [
        {
          "text": "Deactivates an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismDeactivate"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDeactivate",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismDeactivate",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismdeactivate"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy": {
      "abstract": [
        {
          "text": "Destroys an authorization mechanism.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismDestroy"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismDestroy",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismDestroy",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanismdestroy"
    },
    "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismInvoke": {
      "abstract": [
        {
          "text": "Invokes an authorization mechanism to perform an authorization operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MechanismInvoke"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/AuthorizationPluginInterface/MechanismInvoke",
      "kind": "symbol",
      "role": "symbol",
      "title": "MechanismInvoke",
      "type": "topic",
      "url": "/documentation/security/authorizationplugininterface/mechanisminvoke"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationInternal": {
      "abstract": [
        {
          "text": "An unrecognized internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationInternal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationInternal"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationInternal",
      "type": "topic",
      "url": "/documentation/security/errauthorizationinternal"
    },
    "doc://com.apple.security/documentation/Security/errAuthorizationSuccess": {
      "abstract": [
        {
          "text": "The operation completed successfully.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@OSStatus",
          "text": "OSStatus"
        }
      ],
      "identifier": "doc://com.apple.security/documentation/Security/errAuthorizationSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errAuthorizationSuccess"
        }
      ],
      "role": "symbol",
      "title": "errAuthorizationSuccess",
      "type": "topic",
      "url": "/documentation/security/errauthorizationsuccess"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/title",
          "value": "errAuthorizationSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/title",
          "value": "errAuthorizationInternal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.security~1documentation~1Security~1errAuthorizationInternal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errAuthorizationInternal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/security/authorizationplugininterface/mechanismcreate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
