{
  "abstract": [
    {
      "text": "Constants that represent possible data transfer sizes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cloudkit/documentation/CloudKit",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CloudKit",
    "externalID": "c:@E@CKOperationGroupTransferSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "TransferSize"
      }
    ],
    "modules": [
      {
        "name": "CloudKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "TransferSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CKOperationGroup.TransferSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "TransferSize"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cloudkit/documentation/CloudKit": {
      "abstract": [
        {
          "text": "Store structured app and user data in iCloud containers that all users of your app can share.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CloudKit",
      "type": "topic",
      "url": "/documentation/cloudkit"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup": {
      "abstract": [
        {
          "text": "An explicit association between two or more operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroup"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize": {
      "abstract": [
        {
          "text": "Constants that represent possible data transfer sizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TransferSize"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TransferSize"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "gigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.gigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/gigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents hundreds of gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hundredsOfGigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeHundredsOfGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.hundredsOfGigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/hundredsofgigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents hundreds of megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hundredsOfMegabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeHundredsOfMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.hundredsOfMegabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/hundredsofmegabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/init(rawvalue:)"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more kilobytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kilobytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeKilobytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.kilobytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/kilobytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents 1 or more megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "megabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.megabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/megabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents tens of gigabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensOfGigabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeTensOfGigabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.tensOfGigabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/tensofgigabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes": {
      "abstract": [
        {
          "text": "A transfer size that represents tens of megabytes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tensOfMegabytes"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeTensOfMegabytes"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.tensOfMegabytes",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/tensofmegabytes"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown": {
      "abstract": [
        {
          "text": "An unknown transfer size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CKOperationGroupTransferSizeUnknown"
        }
      ],
      "role": "symbol",
      "title": "CKOperationGroup.TransferSize.unknown",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/transfersize/unknown"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration": {
      "abstract": [
        {
          "text": "The default configuration for operations in the group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperation",
          "text": "CKOperation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultConfiguration"
        }
      ],
      "role": "symbol",
      "title": "defaultConfiguration",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/defaultconfiguration"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedReceiveSize": {
      "abstract": [
        {
          "text": "The estimated size of traffic to download from CloudKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectedReceiveSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationGroup",
          "text": "CKOperationGroup"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKOperationGroupTransferSize",
          "text": "TransferSize"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedReceiveSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectedReceiveSize"
        }
      ],
      "role": "symbol",
      "title": "expectedReceiveSize",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/expectedreceivesize"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedSendSize": {
      "abstract": [
        {
          "text": "The estimated size of traffic to upload to CloudKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expectedSendSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CKOperationGroup",
          "text": "CKOperationGroup"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CKOperationGroupTransferSize",
          "text": "TransferSize"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedSendSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "expectedSendSize"
        }
      ],
      "role": "symbol",
      "title": "expectedSendSize",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/expectedsendsize"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/name": {
      "abstract": [
        {
          "text": "The operation group’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/name"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/operationGroupID": {
      "abstract": [
        {
          "text": "The operation group’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationGroupID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/operationGroupID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "operationGroupID"
        }
      ],
      "role": "symbol",
      "title": "operationGroupID",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/operationgroupid"
    },
    "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/quantity": {
      "abstract": [
        {
          "text": "The number of operations in the operation group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quantity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/quantity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quantity"
        }
      ],
      "role": "symbol",
      "title": "quantity",
      "type": "topic",
      "url": "/documentation/cloudkit/ckoperationgroup/quantity"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-an-Operation-Group",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedReceiveSize",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedSendSize",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/name",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/operationGroupID",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/quantity"
      ],
      "title": "Configuring an Operation Group"
    }
  ],
  "topicSections": [
    {
      "anchor": "Transfer-Sizes",
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown"
      ],
      "title": "Transfer Sizes"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CKOperationGroupTransferSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.cloudkit/documentation/CloudKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Transfer-Sizes",
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/kilobytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/megabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/gigabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfMegabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/tensOfGigabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfMegabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/hundredsOfGigabytes",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/TransferSize/unknown"
              ],
              "title": "Transfer Sizes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-an-Operation-Group",
              "generated": true,
              "identifiers": [
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/defaultConfiguration",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedReceiveSize",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/expectedSendSize",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/name",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/operationGroupID",
                "doc://com.apple.cloudkit/documentation/CloudKit/CKOperationGroup/quantity"
              ],
              "title": "Configuring an Operation Group"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CKOperationGroupTransferSize"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfMegabytes/title",
          "value": "CKOperationGroupTransferSizeHundredsOfMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfMegabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeHundredsOfMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1expectedReceiveSize/title",
          "value": "expectedReceiveSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1expectedReceiveSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectedReceiveSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1operationGroupID/title",
          "value": "operationGroupID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1operationGroupID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "operationGroupID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfGigabytes/title",
          "value": "CKOperationGroupTransferSizeHundredsOfGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1hundredsOfGigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeHundredsOfGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1kilobytes/title",
          "value": "CKOperationGroupTransferSizeKilobytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1kilobytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeKilobytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1expectedSendSize/title",
          "value": "expectedSendSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1expectedSendSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "expectedSendSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1quantity/title",
          "value": "quantity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1quantity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quantity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1megabytes/title",
          "value": "CKOperationGroupTransferSizeMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1megabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1gigabytes/title",
          "value": "CKOperationGroupTransferSizeGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1gigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1unknown/title",
          "value": "CKOperationGroupTransferSizeUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1defaultConfiguration/title",
          "value": "defaultConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1defaultConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfMegabytes/title",
          "value": "CKOperationGroupTransferSizeTensOfMegabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfMegabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeTensOfMegabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/title",
          "value": "CKOperationGroupTransferSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfGigabytes/title",
          "value": "CKOperationGroupTransferSizeTensOfGigabytes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup~1TransferSize~1tensOfGigabytes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroupTransferSizeTensOfGigabytes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/title",
          "value": "CKOperationGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cloudkit~1documentation~1CloudKit~1CKOperationGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CKOperationGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cloudkit/ckoperationgroup/transfersize"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/cloudkit/ckoperationgroup/transfersize"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
