{
  "abstract": [
    {
      "text": "The streaming media service account for the session to configure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediasetup/documentation/MediaSetup",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/account"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSSetupSession(py)account",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "account"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MSServiceAccount",
        "text": "MSServiceAccount"
      }
    ],
    "modules": [
      {
        "name": "Media Setup"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "account"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "account"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "account"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MSServiceAccount",
              "text": "MSServiceAccount"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup": {
      "abstract": [
        {
          "text": "Enable users to configure HomePod speakers to stream music directly from your media service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Setup",
      "type": "topic",
      "url": "/documentation/mediasetup"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount": {
      "abstract": [
        {
          "text": "Account details for accessing a streaming media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "role": "symbol",
      "title": "MSServiceAccount",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession": {
      "abstract": [
        {
          "text": "An object that manages the transfer of configuration information between your app, the system, your media service, and HomePod speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSetupSession"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSetupSession"
        }
      ],
      "role": "symbol",
      "title": "MSSetupSession",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/account": {
      "abstract": [
        {
          "text": "The streaming media service account for the session to configure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "account"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSServiceAccount",
          "text": "MSServiceAccount"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/account",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "account"
        }
      ],
      "role": "symbol",
      "title": "account",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession/account"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/init(serviceAccount:)": {
      "abstract": [
        {
          "text": "Creates a new session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceAccount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MSServiceAccount",
          "text": "MSServiceAccount"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/init(serviceAccount:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithServiceAccount:"
        }
      ],
      "role": "symbol",
      "title": "init(serviceAccount:)",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession/init(serviceaccount:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Preparing-the-Configuration-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/init(serviceAccount:)"
      ],
      "title": "Preparing the Configuration View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "account"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "account"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediasetup/documentation/MediaSetup",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Preparing-the-Configuration-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/init(serviceAccount:)"
              ],
              "title": "Preparing the Configuration View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MSServiceAccount",
                    "text": "MSServiceAccount"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "account"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/title",
          "value": "MSServiceAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1init(serviceAccount:)/title",
          "value": "initWithServiceAccount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1init(serviceAccount:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithServiceAccount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/title",
          "value": "MSSetupSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSetupSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSetupSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1account/title",
          "value": "account"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1account/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "account"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediasetup/mssetupsession/account"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediasetup/mssetupsession/account"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
