{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/mediasetup/mssetupsession/presentationcontext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/mediasetup/mssetupsession/presentationcontext"]}],"abstract":[{"type":"text","text":"A delegate that provides media setup display information to the system."}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mediasetup/documentation/MediaSetup","doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"]]},"identifier":{"url":"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationContext","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MSAuthenticationPresentationContext","identifier":"doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext","text":"MSAuthenticationPresentationContext","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)MSSetupSession(py)presentationContext","modules":[{"name":"Media Setup"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationContext","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MSAuthenticationPresentationContext","text":"MSAuthenticationPresentationContext"},{"kind":"text","text":")?"}],"title":"presentationContext","navigatorTitle":[{"kind":"identifier","text":"presentationContext"}],"role":"symbol","platforms":[{"unavailable":false,"introducedAt":"14.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false,"beta":false}],"symbolKind":"property"},"seeAlsoSections":[{"anchor":"Presenting-the-Configuration-View","title":"Presenting the Configuration View","identifiers":["doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext","doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.apple.mediasetup/documentation/MediaSetup":{"identifier":"doc://com.apple.mediasetup/documentation/MediaSetup","type":"topic","kind":"symbol","role":"collection","title":"Media Setup","url":"/documentation/mediasetup","abstract":[{"text":"Enable users to configure HomePod speakers to stream music directly from your media service.","type":"text"}]},"doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext":{"navigatorTitle":[{"text":"MSAuthenticationPresentationContext","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MSAuthenticationPresentationContext","kind":"identifier"}],"url":"/documentation/mediasetup/msauthenticationpresentationcontext","type":"topic","title":"MSAuthenticationPresentationContext","abstract":[{"type":"text","text":"A protocol that provides media setup display information to the system."}],"kind":"symbol"},"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession":{"navigatorTitle":[{"text":"MSSetupSession","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MSSetupSession","kind":"identifier"}],"url":"/documentation/mediasetup/mssetupsession","type":"topic","title":"MSSetupSession","abstract":[{"type":"text","text":"An object that manages the transfer of configuration information between your app, the system, your media service, and HomePod speakers."}],"kind":"symbol"},"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()":{"navigatorTitle":[{"text":"startWithError:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"/documentation/mediasetup/mssetupsession/start()","type":"topic","title":"start()","abstract":[{"type":"text","text":"Initiates the service configuration process and sends the account details of the streaming media service to the user’s HomePod speakers."}],"kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","kind":"technologies","role":"overview","title":"Technologies","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}]},"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext":{"navigatorTitle":[{"text":"presentationContext","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationContext","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"MSAuthenticationPresentationContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MSAuthenticationPresentationContext"},{"text":")?","kind":"text"}],"url":"/documentation/mediasetup/mssetupsession/presentationcontext","type":"topic","title":"presentationContext","abstract":[{"type":"text","text":"A delegate that provides media setup display information to the system."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":[{"unavailable":false,"introducedAt":"14.0","name":"iOS","deprecated":false,"beta":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"14.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"14.0","unavailable":false},{"deprecated":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"value":"presentationContext","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"presentationContext"}],"path":"/metadata/fragments","op":"replace"},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mediasetup/documentation/MediaSetup","doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","value":[{"generated":true,"title":"Presenting the Configuration View","anchor":"Presenting-the-Configuration-View","identifiers":["doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext","doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<MSAuthenticationPresentationContext>","preciseIdentifier":"c:Qoobjc(pl)MSAuthenticationPresentationContext","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"presentationContext","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"op":"replace","value":"MSAuthenticationPresentationContext","path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"MSAuthenticationPresentationContext"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MSAuthenticationPresentationContext"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/navigatorTitle"},{"op":"replace","value":"MSSetupSession","path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/title"},{"op":"replace","value":[{"text":"MSSetupSession","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/fragments"},{"op":"replace","value":[{"text":"MSSetupSession","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/navigatorTitle"},{"op":"replace","value":"startWithError:","path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1start()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"startWithError:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1start()/fragments"},{"op":"replace","value":"presentationContext","path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1presentationContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"presentationContext"}],"path":"/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1presentationContext/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}