{
  "abstract": [
    {
      "text": "Initiates the service configuration process and sends the account details of the streaming media service to the user’s HomePod speakers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediasetup/documentation/MediaSetup",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSSetupSession(im)startWithError:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "start"
      },
      {
        "kind": "text",
        "text": "() "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "Media Setup"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "startWithError:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "start()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "start"
            },
            {
              "kind": "text",
              "text": "() "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup": {
      "abstract": [
        {
          "text": "Enable users to configure HomePod speakers to stream music directly from your media service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Setup",
      "type": "topic",
      "url": "/documentation/mediasetup"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext": {
      "abstract": [
        {
          "text": "A protocol that provides media setup display information to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSAuthenticationPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSAuthenticationPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "MSAuthenticationPresentationContext",
      "type": "topic",
      "url": "/documentation/mediasetup/msauthenticationpresentationcontext"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession": {
      "abstract": [
        {
          "text": "An object that manages the transfer of configuration information between your app, the system, your media service, and HomePod speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSSetupSession"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSSetupSession"
        }
      ],
      "role": "symbol",
      "title": "MSSetupSession",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext": {
      "abstract": [
        {
          "text": "A delegate that provides media setup display information to the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentationContext"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MSAuthenticationPresentationContext",
          "text": "MSAuthenticationPresentationContext"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentationContext"
        }
      ],
      "role": "symbol",
      "title": "presentationContext",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession/presentationcontext"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()": {
      "abstract": [
        {
          "text": "Initiates the service configuration process and sends the account details of the streaming media service to the user’s HomePod speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/start()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startWithError:"
        }
      ],
      "role": "symbol",
      "title": "start()",
      "type": "topic",
      "url": "/documentation/mediasetup/mssetupsession/start()"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-the-Configuration-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext"
      ],
      "title": "Presenting the Configuration View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "startWithError:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediasetup/documentation/MediaSetup",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-the-Configuration-View",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSSetupSession/presentationContext",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSAuthenticationPresentationContext"
              ],
              "title": "Presenting the Configuration View"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "startWithError:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "error"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/title",
          "value": "MSSetupSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSetupSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSSetupSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/title",
          "value": "MSAuthenticationPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSAuthenticationPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSAuthenticationPresentationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSAuthenticationPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1start()/title",
          "value": "startWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1start()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1presentationContext/title",
          "value": "presentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSSetupSession~1presentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "presentationContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediasetup/mssetupsession/start()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediasetup/mssetupsession/start()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
