{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Cache Options","anchor":"Cache-Options","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"]]},"variants":[{"paths":["/documentation/appkit/nsimage/cachemode-swift.enum/always"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nsimage/cachemode-swift.enum/always"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Always generate a cache when drawing."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"c:@E@NSImageCacheMode@NSImageCacheAlways","modules":[{"name":"AppKit"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","title":"NSImage.CacheMode.always","navigatorTitle":[{"text":"NSImageCacheAlways","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSImage":{"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage","url":"/documentation/appkit/nsimage","navigatorTitle":[{"text":"NSImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSImage","kind":"identifier"}],"type":"topic","title":"NSImage","role":"symbol","abstract":[{"text":"A high-level interface for manipulating image data.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum":{"abstract":[{"text":"Constants that specify the caching policy on a per-image basis.","type":"text"}],"type":"topic","title":"NSImage.CacheMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CacheMode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CacheMode"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default":{"abstract":[{"text":"Caching is unspecified.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NSImageCacheDefault","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","url":"/documentation/appkit/nsimage/cachemode-swift.enum/default","title":"NSImage.CacheMode.default"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize":{"url":"/documentation/appkit/nsimage/cachemode-swift.enum/bysize","title":"NSImage.CacheMode.bySize","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","abstract":[{"text":"Cache if the cache size is smaller than the original data.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bySize"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSImageCacheBySize"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never":{"url":"/documentation/appkit/nsimage/cachemode-swift.enum/never","title":"NSImage.CacheMode.never","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never","abstract":[{"text":"Never cache; always draw direct.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"never"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSImageCacheNever"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"url":"/documentation/appkit/nsimage/cachemode-swift.enum/always","identifier":"doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/always","role":"symbol","abstract":[{"text":"Always generate a cache when drawing.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSImageCacheAlways"}],"type":"topic","title":"NSImage.CacheMode.always"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"NSImageCacheAlways","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"NSImageCacheAlways"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/default","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/bySize","doc://com.apple.appkit/documentation/AppKit/NSImage/CacheMode-swift.enum/never"],"generated":true,"anchor":"Cache-Options","title":"Cache Options"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"NSImageCacheAlways"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/title","value":"NSImage","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/fragments","value":[{"kind":"identifier","text":"NSImage"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage/navigatorTitle","value":[{"text":"NSImage","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/title","value":"NSImageCacheMode","op":"replace"},{"value":[{"text":"NSImageCacheMode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/fragments"},{"value":[{"kind":"identifier","text":"NSImageCacheMode"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum/navigatorTitle"},{"value":"NSImageCacheDefault","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1default/title"},{"value":[{"text":"NSImageCacheDefault","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1default/fragments"},{"value":"NSImageCacheBySize","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1bySize/title"},{"value":[{"text":"NSImageCacheBySize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1bySize/fragments"},{"value":"NSImageCacheNever","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1never/title"},{"value":[{"text":"NSImageCacheNever","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1never/fragments"},{"value":"NSImageCacheAlways","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1always/title"},{"value":[{"text":"NSImageCacheAlways","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1CacheMode-swift.enum~1always/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}