{
  "abstract": [
    {
      "text": "A rule that prevents modification of the referenced managed objects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/noActionDeleteRule"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSDeleteRule@NSNoActionDeleteRule",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "noActionDeleteRule"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSNoActionDeleteRule"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSDeleteRule.noActionDeleteRule"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "noActionDeleteRule"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you use this delete rule, make sure you delete any referenced managed objects or nullify their inverse relationships. Otherwise, those objects will reference an object that doesn’t exist, and your persistent store will be in an inconsistent state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule": {
      "abstract": [
        {
          "text": "Constants that determine what happens when you delete a relationship’s owning managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeleteRule"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeleteRule"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteRule",
      "type": "topic",
      "url": "/documentation/coredata/nsdeleterule"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/cascadeDeleteRule": {
      "abstract": [
        {
          "text": "A rule that deletes the referenced managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cascadeDeleteRule"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/cascadeDeleteRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCascadeDeleteRule"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteRule.cascadeDeleteRule",
      "type": "topic",
      "url": "/documentation/coredata/nsdeleterule/cascadedeleterule"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/denyDeleteRule": {
      "abstract": [
        {
          "text": "A rule that prevents the deletion of the owning managed object if the relationship has references to other objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denyDeleteRule"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/denyDeleteRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDenyDeleteRule"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteRule.denyDeleteRule",
      "type": "topic",
      "url": "/documentation/coredata/nsdeleterule/denydeleterule"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/noActionDeleteRule": {
      "abstract": [
        {
          "text": "A rule that prevents modification of the referenced managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noActionDeleteRule"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/noActionDeleteRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNoActionDeleteRule"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteRule.noActionDeleteRule",
      "type": "topic",
      "url": "/documentation/coredata/nsdeleterule/noactiondeleterule"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/nullifyDeleteRule": {
      "abstract": [
        {
          "text": "A rule that nullifies the inverse relationship of the referenced managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nullifyDeleteRule"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/nullifyDeleteRule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSNullifyDeleteRule"
        }
      ],
      "role": "symbol",
      "title": "NSDeleteRule.nullifyDeleteRule",
      "type": "topic",
      "url": "/documentation/coredata/nsdeleterule/nullifydeleterule"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Delete-Rules",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/nullifyDeleteRule",
        "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/cascadeDeleteRule",
        "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/denyDeleteRule"
      ],
      "title": "Delete Rules"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSNoActionDeleteRule"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoActionDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData",
                "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Delete-Rules",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/nullifyDeleteRule",
                "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/cascadeDeleteRule",
                "doc://com.apple.coredata/documentation/CoreData/NSDeleteRule/denyDeleteRule"
              ],
              "title": "Delete Rules"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSNoActionDeleteRule"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1nullifyDeleteRule/title",
          "value": "NSNullifyDeleteRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1nullifyDeleteRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNullifyDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1denyDeleteRule/title",
          "value": "NSDenyDeleteRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1denyDeleteRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDenyDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1noActionDeleteRule/title",
          "value": "NSNoActionDeleteRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1noActionDeleteRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSNoActionDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1cascadeDeleteRule/title",
          "value": "NSCascadeDeleteRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule~1cascadeDeleteRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCascadeDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule/title",
          "value": "NSDeleteRule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeleteRule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeleteRule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeleteRule"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsdeleterule/noactiondeleterule"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsdeleterule/noactiondeleterule"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
