{
  "abstract": [
    {
      "text": "The user must launch your app to retrieve the reservation details.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failureRequiringAppLaunch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INGetReservationDetailsIntentResponseCode@INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failureRequiringAppLaunch"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INGetReservationDetailsIntentResponseCode.failureRequiringAppLaunch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failureRequiringAppLaunch"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this response code when you can’t handle the request with Siri for a reason not covered by any other response code. For example, you might use this code if the user hasn’t set up an account with your app. Don’t use it for general errors or to force the user to launch your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode": {
      "abstract": [
        {
          "text": "Constants that indicate the status of the request for reservations details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCode"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCode"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failure": {
      "abstract": [
        {
          "text": "Your app is unable to retrieve the reservation details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failure"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeFailure"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.failure",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/failure"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failureRequiringAppLaunch": {
      "abstract": [
        {
          "text": "The user must launch your app to retrieve the reservation details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failureRequiringAppLaunch"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failureRequiringAppLaunch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.failureRequiringAppLaunch",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/failurerequiringapplaunch"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/inProgress": {
      "abstract": [
        {
          "text": "Your app is processing the request for reservation details.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inProgress"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/inProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeInProgress"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.inProgress",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/inprogress"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/ready": {
      "abstract": [
        {
          "text": "Your app is ready to handle the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ready"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/ready",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeReady"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.ready",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/ready"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/success": {
      "abstract": [
        {
          "text": "Your app successfully handled the intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.success",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/success"
    },
    "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/unspecified": {
      "abstract": [
        {
          "text": "The response code is unspecified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INGetReservationDetailsIntentResponseCodeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "INGetReservationDetailsIntentResponseCode.unspecified",
      "type": "topic",
      "url": "/documentation/intents/ingetreservationdetailsintentresponsecode/unspecified"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Request-Status",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/unspecified",
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/ready",
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/inProgress",
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/success",
        "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failure"
      ],
      "title": "Request Status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Request-Status",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/unspecified",
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/ready",
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/inProgress",
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/success",
                "doc://com.apple.sirikit/documentation/Intents/INGetReservationDetailsIntentResponseCode/failure"
              ],
              "title": "Request Status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1ready/title",
          "value": "INGetReservationDetailsIntentResponseCodeReady"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1ready/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeReady"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1failureRequiringAppLaunch/title",
          "value": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1failureRequiringAppLaunch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeFailureRequiringAppLaunch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1failure/title",
          "value": "INGetReservationDetailsIntentResponseCodeFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1failure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1unspecified/title",
          "value": "INGetReservationDetailsIntentResponseCodeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode/title",
          "value": "INGetReservationDetailsIntentResponseCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1success/title",
          "value": "INGetReservationDetailsIntentResponseCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1inProgress/title",
          "value": "INGetReservationDetailsIntentResponseCodeInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INGetReservationDetailsIntentResponseCode~1inProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INGetReservationDetailsIntentResponseCodeInProgress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/ingetreservationdetailsintentresponsecode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/ingetreservationdetailsintentresponsecode/failurerequiringapplaunch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
