{
  "abstract": [
    {
      "text": "A photo taken with a flash.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPhotoAttributeOptions@INPhotoAttributeOptionFlash",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "flash"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
        "text": "INPhotoAttributeOptions"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPhotoAttributeOptionFlash"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "flash"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flash"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
              "text": "INPhotoAttributeOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions": {
      "abstract": [
        {
          "text": "Constants indicating attributes of a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "role": "symbol",
      "title": "INPhotoAttributeOptions",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF": {
      "abstract": [
        {
          "text": "A Graphics Interchange Format image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GIF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionGIF"
        }
      ],
      "role": "symbol",
      "title": "GIF",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/gif"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the bounce effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bouncePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionBouncePhoto"
        }
      ],
      "role": "symbol",
      "title": "bouncePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/bouncephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto": {
      "abstract": [
        {
          "text": "A burst-mode photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "burstPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionBurstPhoto"
        }
      ],
      "role": "symbol",
      "title": "burstPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/burstphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash": {
      "abstract": [
        {
          "text": "A photo taken with a flash.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/flash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFlash"
        }
      ],
      "role": "symbol",
      "title": "flash",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/flash"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto": {
      "abstract": [
        {
          "text": "An HDR photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hdrPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionHDRPhoto"
        }
      ],
      "role": "symbol",
      "title": "hdrPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/hdrphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto": {
      "abstract": [
        {
          "text": "A live photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "livePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLivePhoto"
        }
      ],
      "role": "symbol",
      "title": "livePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/livephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the long exxposure effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "longExposurePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLongExposurePhoto"
        }
      ],
      "role": "symbol",
      "title": "longExposurePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/longexposurephoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto": {
      "abstract": [
        {
          "text": "A live photo edited with the loop effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loopPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionLoopPhoto"
        }
      ],
      "role": "symbol",
      "title": "loopPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/loopphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto": {
      "abstract": [
        {
          "text": "A panorama photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "panoramaPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPanoramaPhoto"
        }
      ],
      "role": "symbol",
      "title": "panoramaPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/panoramaphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo": {
      "abstract": [
        {
          "text": "A still image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "photo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPhoto"
        }
      ],
      "role": "symbol",
      "title": "photo",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/photo"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto": {
      "abstract": [
        {
          "text": "A portrait photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitPhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionPortraitPhoto"
        }
      ],
      "role": "symbol",
      "title": "portraitPhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/portraitphoto"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie": {
      "abstract": [
        {
          "text": "A selfie.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selfie"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionSelfie"
        }
      ],
      "role": "symbol",
      "title": "selfie",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/selfie"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto": {
      "abstract": [
        {
          "text": "A square photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "squarePhoto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionSquarePhoto"
        }
      ],
      "role": "symbol",
      "title": "squarePhoto",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/squarephoto"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Photo",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie"
      ],
      "title": "Photo"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPhotoAttributeOptionFlash"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFlash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Photo",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/photo",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/bouncePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/burstPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/hdrPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/livePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/longExposurePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/loopPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/squarePhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/panoramaPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/portraitPhoto",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/GIF",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/selfie"
              ],
              "title": "Photo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPhotoAttributeOptionFlash"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1bouncePhoto/title",
          "value": "INPhotoAttributeOptionBouncePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1bouncePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionBouncePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1burstPhoto/title",
          "value": "INPhotoAttributeOptionBurstPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1burstPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionBurstPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1selfie/title",
          "value": "INPhotoAttributeOptionSelfie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1selfie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionSelfie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1hdrPhoto/title",
          "value": "INPhotoAttributeOptionHDRPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1hdrPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionHDRPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1flash/title",
          "value": "INPhotoAttributeOptionFlash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1flash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFlash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1loopPhoto/title",
          "value": "INPhotoAttributeOptionLoopPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1loopPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLoopPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/title",
          "value": "INPhotoAttributeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1GIF/title",
          "value": "INPhotoAttributeOptionGIF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1GIF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionGIF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1panoramaPhoto/title",
          "value": "INPhotoAttributeOptionPanoramaPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1panoramaPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPanoramaPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1livePhoto/title",
          "value": "INPhotoAttributeOptionLivePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1livePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLivePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1squarePhoto/title",
          "value": "INPhotoAttributeOptionSquarePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1squarePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionSquarePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1photo/title",
          "value": "INPhotoAttributeOptionPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1photo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1longExposurePhoto/title",
          "value": "INPhotoAttributeOptionLongExposurePhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1longExposurePhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionLongExposurePhoto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitPhoto/title",
          "value": "INPhotoAttributeOptionPortraitPhoto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1portraitPhoto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionPortraitPhoto"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions/flash"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions/flash"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
