{
  "abstract": [
    {
      "text": "A process filter.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
          "type": "text"
        },
        {
          "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INPhotoAttributeOptions@INPhotoAttributeOptionProcessFilter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "processFilter"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
        "text": "INPhotoAttributeOptions"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INPhotoAttributeOptionProcessFilter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "10.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "15.0",
        "introducedAt": "13.1",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.2",
        "message": "INPhotoAttributeOptions is deprecated. There is no replacement.",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "processFilter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "processFilter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
              "text": "INPhotoAttributeOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions": {
      "abstract": [
        {
          "text": "Constants indicating attributes of a photo.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "role": "symbol",
      "title": "INPhotoAttributeOptions",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter": {
      "abstract": [
        {
          "text": "A chrome filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "chromeFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionChromeFilter"
        }
      ],
      "role": "symbol",
      "title": "chromeFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/chromefilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter": {
      "abstract": [
        {
          "text": "A fade filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fadeFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionFadeFilter"
        }
      ],
      "role": "symbol",
      "title": "fadeFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/fadefilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter": {
      "abstract": [
        {
          "text": "An instant filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "instantFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionInstantFilter"
        }
      ],
      "role": "symbol",
      "title": "instantFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/instantfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter": {
      "abstract": [
        {
          "text": "A mono filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionMonoFilter"
        }
      ],
      "role": "symbol",
      "title": "monoFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/monofilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter": {
      "abstract": [
        {
          "text": "A noir filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noirFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionNoirFilter"
        }
      ],
      "role": "symbol",
      "title": "noirFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/noirfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter": {
      "abstract": [
        {
          "text": "A process filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "processFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/processFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionProcessFilter"
        }
      ],
      "role": "symbol",
      "title": "processFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/processfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter": {
      "abstract": [
        {
          "text": "A tonal filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tonalFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionTonalFilter"
        }
      ],
      "role": "symbol",
      "title": "tonalFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/tonalfilter"
    },
    "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter": {
      "abstract": [
        {
          "text": "A transfer filter.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transferFilter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@INPhotoAttributeOptions",
          "text": "INPhotoAttributeOptions"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INPhotoAttributeOptionTransferFilter"
        }
      ],
      "role": "symbol",
      "title": "transferFilter",
      "type": "topic",
      "url": "/documentation/intents/inphotoattributeoptions/transferfilter"
    },
    "https://developer.apple.com/support/deprecated-sirikit-intent-domains": {
      "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
      "title": "Deprecated SiriKit Intent Domains",
      "titleInlineContent": [
        {
          "text": "Deprecated SiriKit Intent Domains",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/support/deprecated-sirikit-intent-domains"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Filter",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
        "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter"
      ],
      "title": "Filter"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "15.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INPhotoAttributeOptionProcessFilter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionProcessFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Filter",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/noirFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/chromeFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/instantFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/tonalFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/transferFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/monoFilter",
                "doc://com.apple.sirikit/documentation/Intents/INPhotoAttributeOptions/fadeFilter"
              ],
              "title": "Filter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INPhotoAttributeOptionProcessFilter"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "This intent is no longer available. You may define a custom intent instead. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/support/deprecated-sirikit-intent-domains",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1transferFilter/title",
          "value": "INPhotoAttributeOptionTransferFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1transferFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionTransferFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1instantFilter/title",
          "value": "INPhotoAttributeOptionInstantFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1instantFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionInstantFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1chromeFilter/title",
          "value": "INPhotoAttributeOptionChromeFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1chromeFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionChromeFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/title",
          "value": "INPhotoAttributeOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1processFilter/title",
          "value": "INPhotoAttributeOptionProcessFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1processFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionProcessFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1tonalFilter/title",
          "value": "INPhotoAttributeOptionTonalFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1tonalFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionTonalFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1noirFilter/title",
          "value": "INPhotoAttributeOptionNoirFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1noirFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionNoirFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1monoFilter/title",
          "value": "INPhotoAttributeOptionMonoFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1monoFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionMonoFilter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1fadeFilter/title",
          "value": "INPhotoAttributeOptionFadeFilter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INPhotoAttributeOptions~1fadeFilter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INPhotoAttributeOptionFadeFilter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions/processfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/inphotoattributeoptions/processfilter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
