{
  "abstract": [
    {
      "text": "An error indicating the accessory is out of resources.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfResources"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeAccessoryOutOfResources",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessoryOutOfResources"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeAccessoryOutOfResources"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMError.Code.accessoryOutOfResources"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessoryOutOfResources"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBlocked": {
      "abstract": [
        {
          "text": "An error indicating a blocked accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryIsBlocked"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBlocked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryIsBlocked"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryIsBlocked",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryisblocked"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBusy": {
      "abstract": [
        {
          "text": "An error indicating the accessory is busy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryIsBusy"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBusy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryIsBusy"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryIsBusy",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryisbusy"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsSuspended": {
      "abstract": [
        {
          "text": "The accessory is suspended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryIsSuspended"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsSuspended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryIsSuspended"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryIsSuspended",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryissuspended"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryNotReachable": {
      "abstract": [
        {
          "text": "An error indicating the accessory is not reachable over the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryNotReachable"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryNotReachable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryNotReachable"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryNotReachable",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessorynotreachable"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfCompliance": {
      "abstract": [
        {
          "text": "An error indicating the accessory is out of compliance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryOutOfCompliance"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfCompliance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryOutOfCompliance"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryOutOfCompliance",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryoutofcompliance"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfResources": {
      "abstract": [
        {
          "text": "An error indicating the accessory is out of resources.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryOutOfResources"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfResources",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryOutOfResources"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryOutOfResources",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryoutofresources"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryPoweredOff": {
      "abstract": [
        {
          "text": "An error indicating the accessory is off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryPoweredOff"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryPoweredOff",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryPoweredOff"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryPoweredOff",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessorypoweredoff"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryResponseError": {
      "abstract": [
        {
          "text": "An error with the accessory’s response.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryResponseError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryResponseError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAccessoryResponseError"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.accessoryResponseError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/accessoryresponseerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/addAccessoryFailed": {
      "abstract": [
        {
          "text": "A failed attempt to add an accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addAccessoryFailed"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/addAccessoryFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAddAccessoryFailed"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.addAccessoryFailed",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/addaccessoryfailed"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleAccessory": {
      "abstract": [
        {
          "text": "The accessory is incompatible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleAccessory"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeIncompatibleAccessory"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.incompatibleAccessory",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/incompatibleaccessory"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessory-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBlocked",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBusy",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsSuspended",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryNotReachable",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfCompliance",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryPoweredOff",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryResponseError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/addAccessoryFailed",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleAccessory"
      ],
      "title": "Accessory errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMErrorCodeAccessoryOutOfResources"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryOutOfResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessory-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBlocked",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsBusy",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryIsSuspended",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryNotReachable",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryOutOfCompliance",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryPoweredOff",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/accessoryResponseError",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/addAccessoryFailed",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleAccessory"
              ],
              "title": "Accessory errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMErrorCodeAccessoryOutOfResources"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryOutOfResources/title",
          "value": "HMErrorCodeAccessoryOutOfResources"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryOutOfResources/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryOutOfResources"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1addAccessoryFailed/title",
          "value": "HMErrorCodeAddAccessoryFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1addAccessoryFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAddAccessoryFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1incompatibleAccessory/title",
          "value": "HMErrorCodeIncompatibleAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1incompatibleAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeIncompatibleAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryPoweredOff/title",
          "value": "HMErrorCodeAccessoryPoweredOff"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryPoweredOff/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryPoweredOff"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryResponseError/title",
          "value": "HMErrorCodeAccessoryResponseError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryResponseError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryResponseError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsBusy/title",
          "value": "HMErrorCodeAccessoryIsBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsBusy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryIsBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryOutOfCompliance/title",
          "value": "HMErrorCodeAccessoryOutOfCompliance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryOutOfCompliance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryOutOfCompliance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsBlocked/title",
          "value": "HMErrorCodeAccessoryIsBlocked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsBlocked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryIsBlocked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsSuspended/title",
          "value": "HMErrorCodeAccessoryIsSuspended"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryIsSuspended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryIsSuspended"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryNotReachable/title",
          "value": "HMErrorCodeAccessoryNotReachable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1accessoryNotReachable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAccessoryNotReachable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerror/code/accessoryoutofresources"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmerror/code/accessoryoutofresources"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
