{
  "abstract": [
    {
      "text": "An error indicating the maximum object count has been reached.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/maximumObjectLimitReached"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeMaximumObjectLimitReached",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "maximumObjectLimitReached"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeMaximumObjectLimitReached"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMError.Code.maximumObjectLimitReached"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "maximumObjectLimitReached"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/cannotActivateTriggerTooFarInFuture": {
      "abstract": [
        {
          "text": "An error indicating the trigger cannot be activated because it is set too far in the future.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cannotActivateTriggerTooFarInFuture"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/cannotActivateTriggerTooFarInFuture",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeCannotActivateTriggerTooFarInFuture"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.cannotActivateTriggerTooFarInFuture",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/cannotactivatetriggertoofarinfuture"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/dateMustBeOnSpecifiedBoundaries": {
      "abstract": [
        {
          "text": "An error indicating the date is not on the specified boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dateMustBeOnSpecifiedBoundaries"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/dateMustBeOnSpecifiedBoundaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeDateMustBeOnSpecifiedBoundaries"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.dateMustBeOnSpecifiedBoundaries",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/datemustbeonspecifiedboundaries"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/fireDateInPast": {
      "abstract": [
        {
          "text": "An attempt to activate a timer trigger with a date in the past.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fireDateInPast"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/fireDateInPast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeFireDateInPast"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.fireDateInPast",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/firedateinpast"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidMessageSize": {
      "abstract": [
        {
          "text": "An error indicating an invalid message size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidMessageSize"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidMessageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInvalidMessageSize"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.invalidMessageSize",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/invalidmessagesize"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/maximumObjectLimitReached": {
      "abstract": [
        {
          "text": "An error indicating the maximum object count has been reached.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumObjectLimitReached"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/maximumObjectLimitReached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeMaximumObjectLimitReached"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.maximumObjectLimitReached",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/maximumobjectlimitreached"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceMustBeOnSpecifiedBoundaries": {
      "abstract": [
        {
          "text": "An error indicating the recurrence rule is not on the specified boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurrenceMustBeOnSpecifiedBoundaries"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceMustBeOnSpecifiedBoundaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeRecurrenceMustBeOnSpecifiedBoundaries"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.recurrenceMustBeOnSpecifiedBoundaries",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/recurrencemustbeonspecifiedboundaries"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooLarge": {
      "abstract": [
        {
          "text": "An attempt to use a recurrence period that is too large.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurrenceTooLarge"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeRecurrenceTooLarge"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.recurrenceTooLarge",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/recurrencetoolarge"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooSmall": {
      "abstract": [
        {
          "text": "An error indicating the recurrence interval is too short.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recurrenceTooSmall"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeRecurrenceTooSmall"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.recurrenceTooSmall",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/recurrencetoosmall"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Limit-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/cannotActivateTriggerTooFarInFuture",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/dateMustBeOnSpecifiedBoundaries",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/fireDateInPast",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidMessageSize",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooLarge",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooSmall",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceMustBeOnSpecifiedBoundaries"
      ],
      "title": "Limit errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMErrorCodeMaximumObjectLimitReached"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeMaximumObjectLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Limit-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/cannotActivateTriggerTooFarInFuture",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/dateMustBeOnSpecifiedBoundaries",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/fireDateInPast",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidMessageSize",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooLarge",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceTooSmall",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/recurrenceMustBeOnSpecifiedBoundaries"
              ],
              "title": "Limit errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMErrorCodeMaximumObjectLimitReached"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1maximumObjectLimitReached/title",
          "value": "HMErrorCodeMaximumObjectLimitReached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1maximumObjectLimitReached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeMaximumObjectLimitReached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1dateMustBeOnSpecifiedBoundaries/title",
          "value": "HMErrorCodeDateMustBeOnSpecifiedBoundaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1dateMustBeOnSpecifiedBoundaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeDateMustBeOnSpecifiedBoundaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1cannotActivateTriggerTooFarInFuture/title",
          "value": "HMErrorCodeCannotActivateTriggerTooFarInFuture"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1cannotActivateTriggerTooFarInFuture/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeCannotActivateTriggerTooFarInFuture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidMessageSize/title",
          "value": "HMErrorCodeInvalidMessageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidMessageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInvalidMessageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceTooSmall/title",
          "value": "HMErrorCodeRecurrenceTooSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceTooSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeRecurrenceTooSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1fireDateInPast/title",
          "value": "HMErrorCodeFireDateInPast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1fireDateInPast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeFireDateInPast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceTooLarge/title",
          "value": "HMErrorCodeRecurrenceTooLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceTooLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeRecurrenceTooLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceMustBeOnSpecifiedBoundaries/title",
          "value": "HMErrorCodeRecurrenceMustBeOnSpecifiedBoundaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1recurrenceMustBeOnSpecifiedBoundaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeRecurrenceMustBeOnSpecifiedBoundaries"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerror/code/maximumobjectlimitreached"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmerror/code/maximumobjectlimitreached"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
