{
  "abstract": [
    {
      "text": "An error indicating the user is not signed into iCloud.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notSignedIntoiCloud"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeNotSignedIntoiCloud",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notSignedIntoiCloud"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeNotSignedIntoiCloud"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMError.Code.notSignedIntoiCloud"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notSignedIntoiCloud"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/homeAccessNotAuthorized": {
      "abstract": [
        {
          "text": "An error indicating access to the home was not authorized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "homeAccessNotAuthorized"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/homeAccessNotAuthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeHomeAccessNotAuthorized"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.homeAccessNotAuthorized",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/homeaccessnotauthorized"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/insufficientPrivileges": {
      "abstract": [
        {
          "text": "An error indicating insufficient privileges for the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPrivileges"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/insufficientPrivileges",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInsufficientPrivileges"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.insufficientPrivileges",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/insufficientprivileges"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidOrMissingAuthorizationData": {
      "abstract": [
        {
          "text": "An error indicating the authorization data is invalid or missing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidOrMissingAuthorizationData"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidOrMissingAuthorizationData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInvalidOrMissingAuthorizationData"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.invalidOrMissingAuthorizationData",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/invalidormissingauthorizationdata"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/locationForHomeDisabled": {
      "abstract": [
        {
          "text": "An error indicating the home’s location is disabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "locationForHomeDisabled"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/locationForHomeDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeLocationForHomeDisabled"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.locationForHomeDisabled",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/locationforhomedisabled"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/messageAuthenticationFailed": {
      "abstract": [
        {
          "text": "A message authentication failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "messageAuthenticationFailed"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/messageAuthenticationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeMessageAuthenticationFailed"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.messageAuthenticationFailed",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/messageauthenticationfailed"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForLocationServices": {
      "abstract": [
        {
          "text": "An error indicating location services are not authorized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorizedForLocationServices"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForLocationServices",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotAuthorizedForLocationServices"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notAuthorizedForLocationServices",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notauthorizedforlocationservices"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForMicrophoneAccess": {
      "abstract": [
        {
          "text": "An error indicating microphone access is not authorized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAuthorizedForMicrophoneAccess"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForMicrophoneAccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotAuthorizedForMicrophoneAccess"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notAuthorizedForMicrophoneAccess",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notauthorizedformicrophoneaccess"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notSignedIntoiCloud": {
      "abstract": [
        {
          "text": "An error indicating the user is not signed into iCloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSignedIntoiCloud"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notSignedIntoiCloud",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotSignedIntoiCloud"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notSignedIntoiCloud",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notsignedintoicloud"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/ownershipFailure": {
      "abstract": [
        {
          "text": "The ownership code did not match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ownershipFailure"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/ownershipFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeOwnershipFailure"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.ownershipFailure",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/ownershipfailure"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/securityFailure": {
      "abstract": [
        {
          "text": "A security failure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "securityFailure"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/securityFailure",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeSecurityFailure"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.securityFailure",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/securityfailure"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Authorization-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidOrMissingAuthorizationData",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/locationForHomeDisabled",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/homeAccessNotAuthorized",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/insufficientPrivileges",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/messageAuthenticationFailed",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForLocationServices",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForMicrophoneAccess",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/ownershipFailure",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/securityFailure"
      ],
      "title": "Authorization errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMErrorCodeNotSignedIntoiCloud"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotSignedIntoiCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Authorization-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidOrMissingAuthorizationData",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/locationForHomeDisabled",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/homeAccessNotAuthorized",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/insufficientPrivileges",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/messageAuthenticationFailed",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForLocationServices",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notAuthorizedForMicrophoneAccess",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/ownershipFailure",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/securityFailure"
              ],
              "title": "Authorization errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMErrorCodeNotSignedIntoiCloud"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1securityFailure/title",
          "value": "HMErrorCodeSecurityFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1securityFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeSecurityFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notAuthorizedForLocationServices/title",
          "value": "HMErrorCodeNotAuthorizedForLocationServices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notAuthorizedForLocationServices/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotAuthorizedForLocationServices"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidOrMissingAuthorizationData/title",
          "value": "HMErrorCodeInvalidOrMissingAuthorizationData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidOrMissingAuthorizationData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInvalidOrMissingAuthorizationData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notAuthorizedForMicrophoneAccess/title",
          "value": "HMErrorCodeNotAuthorizedForMicrophoneAccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notAuthorizedForMicrophoneAccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotAuthorizedForMicrophoneAccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1messageAuthenticationFailed/title",
          "value": "HMErrorCodeMessageAuthenticationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1messageAuthenticationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeMessageAuthenticationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1insufficientPrivileges/title",
          "value": "HMErrorCodeInsufficientPrivileges"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1insufficientPrivileges/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInsufficientPrivileges"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notSignedIntoiCloud/title",
          "value": "HMErrorCodeNotSignedIntoiCloud"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notSignedIntoiCloud/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotSignedIntoiCloud"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1locationForHomeDisabled/title",
          "value": "HMErrorCodeLocationForHomeDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1locationForHomeDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeLocationForHomeDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1ownershipFailure/title",
          "value": "HMErrorCodeOwnershipFailure"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1ownershipFailure/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeOwnershipFailure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1homeAccessNotAuthorized/title",
          "value": "HMErrorCodeHomeAccessNotAuthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1homeAccessNotAuthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeHomeAccessNotAuthorized"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerror/code/notsignedintoicloud"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmerror/code/notsignedintoicloud"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
