{
  "abstract": [
    {
      "text": "An error described in the device’s user manual.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/referToUserManual"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeReferToUserManual",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "referToUserManual"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeReferToUserManual"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.3",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.2",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMError.Code.referToUserManual"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "referToUserManual"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/alreadyExists": {
      "abstract": [
        {
          "text": "An error indicating the container already contains the object you are trying to add.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyExists"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/alreadyExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeAlreadyExists"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.alreadyExists",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/alreadyexists"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/genericError": {
      "abstract": [
        {
          "text": "An error that does not have a more specific error code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "genericError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/genericError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeGenericError"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.genericError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/genericerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleHomeHub": {
      "abstract": [
        {
          "text": "An error indicating an incompatible home hub.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incompatibleHomeHub"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11HMErrorCodeLeV",
          "text": "HMError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@HMErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleHomeHub",
      "kind": "symbol",
      "role": "symbol",
      "title": "incompatibleHomeHub",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/incompatiblehomehub"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidClass": {
      "abstract": [
        {
          "text": "An attempt to use an abstract base class in an operation instead of a concrete subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidClass"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInvalidClass"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.invalidClass",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/invalidclass"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/missingEntitlement": {
      "abstract": [
        {
          "text": "An error indicating a required entitlement is not available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.missingEntitlement",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/missingentitlement"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notFound": {
      "abstract": [
        {
          "text": "An error indicating the object was not found in the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotFound"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notFound",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notfound"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationAlreadyEnabled": {
      "abstract": [
        {
          "text": "An error indicating the notification is already enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationAlreadyEnabled"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationAlreadyEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotificationAlreadyEnabled"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notificationAlreadyEnabled",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notificationalreadyenabled"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationNotSupported": {
      "abstract": [
        {
          "text": "An attempt to register for notifications from an accessory that does not support notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notificationNotSupported"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNotificationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.notificationNotSupported",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/notificationnotsupported"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/operationNotSupported": {
      "abstract": [
        {
          "text": "An attempt to use an unsupported operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "operationNotSupported"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/operationNotSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeOperationNotSupported"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.operationNotSupported",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/operationnotsupported"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/referToUserManual": {
      "abstract": [
        {
          "text": "An error described in the device’s user manual.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referToUserManual"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/referToUserManual",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeReferToUserManual"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.referToUserManual",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/refertousermanual"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/unexpectedError": {
      "abstract": [
        {
          "text": "An unexpected error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unexpectedError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/unexpectedError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeUnexpectedError"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.unexpectedError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/unexpectederror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "General-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/alreadyExists",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/genericError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/incompatibleHomeHub",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidClass",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notFound",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationAlreadyEnabled",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationNotSupported",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/operationNotSupported",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/unexpectedError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/missingEntitlement"
      ],
      "title": "General errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.3",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMErrorCodeReferToUserManual"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeReferToUserManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "General-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/alreadyExists",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/genericError",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidClass",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notFound",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationAlreadyEnabled",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/notificationNotSupported",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/operationNotSupported",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/unexpectedError",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/missingEntitlement"
              ],
              "title": "General errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMErrorCodeReferToUserManual"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1unexpectedError/title",
          "value": "HMErrorCodeUnexpectedError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1unexpectedError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeUnexpectedError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidClass/title",
          "value": "HMErrorCodeInvalidClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInvalidClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notFound/title",
          "value": "HMErrorCodeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notificationNotSupported/title",
          "value": "HMErrorCodeNotificationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notificationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotificationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1operationNotSupported/title",
          "value": "HMErrorCodeOperationNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1operationNotSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeOperationNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1referToUserManual/title",
          "value": "HMErrorCodeReferToUserManual"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1referToUserManual/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeReferToUserManual"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1genericError/title",
          "value": "HMErrorCodeGenericError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1genericError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeGenericError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1alreadyExists/title",
          "value": "HMErrorCodeAlreadyExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1alreadyExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeAlreadyExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1missingEntitlement/title",
          "value": "HMErrorCodeMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notificationAlreadyEnabled/title",
          "value": "HMErrorCodeNotificationAlreadyEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1notificationAlreadyEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNotificationAlreadyEnabled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerror/code/refertousermanual"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmerror/code/refertousermanual"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
