{
  "abstract": [
    {
      "text": "An attempt to use a numeric value higher than the specified maximum value.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.homekit/documentation/HomeKit",
        "doc://com.apple.homekit/documentation/HomeKit/HMError",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueHigherThanMaximum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HMErrorCode@HMErrorCodeValueHigherThanMaximum",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "valueHigherThanMaximum"
      }
    ],
    "modules": [
      {
        "name": "HomeKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HMErrorCodeValueHigherThanMaximum"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HMError.Code.valueHigherThanMaximum"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "valueHigherThanMaximum"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.homekit/documentation/HomeKit": {
      "abstract": [
        {
          "text": "Configure, control, and communicate with home automation accessories.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HomeKit",
      "type": "topic",
      "url": "/documentation/homekit"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError": {
      "abstract": [
        {
          "text": "An error HomeKit returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMError"
        }
      ],
      "role": "symbol",
      "title": "HMError",
      "type": "topic",
      "url": "/documentation/homekit/hmerror"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from HomeKit APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidDataFormatSpecified": {
      "abstract": [
        {
          "text": "An error indicating an invalid data format was specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDataFormatSpecified"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidDataFormatSpecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInvalidDataFormatSpecified"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.invalidDataFormatSpecified",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/invaliddataformatspecified"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidValueType": {
      "abstract": [
        {
          "text": "An attempt to use an invalid value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidValueType"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidValueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeInvalidValueType"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.invalidValueType",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/invalidvaluetype"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameContainsProhibitedCharacters": {
      "abstract": [
        {
          "text": "An attempt to name an object with prohibited characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameContainsProhibitedCharacters"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameContainsProhibitedCharacters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNameContainsProhibitedCharacters"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.nameContainsProhibitedCharacters",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/namecontainsprohibitedcharacters"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotEndWithValidCharacters": {
      "abstract": [
        {
          "text": "An error indicating the provided name has invalid characters at the end.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameDoesNotEndWithValidCharacters"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotEndWithValidCharacters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNameDoesNotEndWithValidCharacters"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.nameDoesNotEndWithValidCharacters",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/namedoesnotendwithvalidcharacters"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotStartWithValidCharacters": {
      "abstract": [
        {
          "text": "An attempt to start the name of an object with invalid characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameDoesNotStartWithValidCharacters"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotStartWithValidCharacters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeNameDoesNotStartWithValidCharacters"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.nameDoesNotStartWithValidCharacters",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/namedoesnotstartwithvalidcharacters"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringLongerThanMaximum": {
      "abstract": [
        {
          "text": "An attempt to use a string longer than the maximum allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringLongerThanMaximum"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringLongerThanMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeStringLongerThanMaximum"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.stringLongerThanMaximum",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/stringlongerthanmaximum"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringShorterThanMinimum": {
      "abstract": [
        {
          "text": "An attempt to use a string shorter than the required minimum.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stringShorterThanMinimum"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringShorterThanMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeStringShorterThanMinimum"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.stringShorterThanMinimum",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/stringshorterthanminimum"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueHigherThanMaximum": {
      "abstract": [
        {
          "text": "An attempt to use a numeric value higher than the specified maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueHigherThanMaximum"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueHigherThanMaximum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeValueHigherThanMaximum"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.valueHigherThanMaximum",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/valuehigherthanmaximum"
    },
    "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueLowerThanMinimum": {
      "abstract": [
        {
          "text": "An attempt to use a numeric value lower than the specified minimum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueLowerThanMinimum"
        }
      ],
      "identifier": "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueLowerThanMinimum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HMErrorCodeValueLowerThanMinimum"
        }
      ],
      "role": "symbol",
      "title": "HMError.Code.valueLowerThanMinimum",
      "type": "topic",
      "url": "/documentation/homekit/hmerror/code/valuelowerthanminimum"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Value-errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidDataFormatSpecified",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidValueType",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameContainsProhibitedCharacters",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotEndWithValidCharacters",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotStartWithValidCharacters",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringLongerThanMaximum",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringShorterThanMinimum",
        "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueLowerThanMinimum"
      ],
      "title": "Value errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HMErrorCodeValueHigherThanMaximum"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeValueHigherThanMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.homekit/documentation/HomeKit",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Value-errors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidDataFormatSpecified",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/invalidValueType",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameContainsProhibitedCharacters",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotEndWithValidCharacters",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/nameDoesNotStartWithValidCharacters",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringLongerThanMaximum",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/stringShorterThanMinimum",
                "doc://com.apple.homekit/documentation/HomeKit/HMError/Code/valueLowerThanMinimum"
              ],
              "title": "Value errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HMErrorCodeValueHigherThanMaximum"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameDoesNotStartWithValidCharacters/title",
          "value": "HMErrorCodeNameDoesNotStartWithValidCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameDoesNotStartWithValidCharacters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNameDoesNotStartWithValidCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1valueLowerThanMinimum/title",
          "value": "HMErrorCodeValueLowerThanMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1valueLowerThanMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeValueLowerThanMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidValueType/title",
          "value": "HMErrorCodeInvalidValueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidValueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInvalidValueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameContainsProhibitedCharacters/title",
          "value": "HMErrorCodeNameContainsProhibitedCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameContainsProhibitedCharacters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNameContainsProhibitedCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/title",
          "value": "HMErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1stringShorterThanMinimum/title",
          "value": "HMErrorCodeStringShorterThanMinimum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1stringShorterThanMinimum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeStringShorterThanMinimum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidDataFormatSpecified/title",
          "value": "HMErrorCodeInvalidDataFormatSpecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1invalidDataFormatSpecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeInvalidDataFormatSpecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameDoesNotEndWithValidCharacters/title",
          "value": "HMErrorCodeNameDoesNotEndWithValidCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1nameDoesNotEndWithValidCharacters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeNameDoesNotEndWithValidCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1stringLongerThanMaximum/title",
          "value": "HMErrorCodeStringLongerThanMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1stringLongerThanMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeStringLongerThanMaximum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1valueHigherThanMaximum/title",
          "value": "HMErrorCodeValueHigherThanMaximum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.homekit~1documentation~1HomeKit~1HMError~1Code~1valueHigherThanMaximum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HMErrorCodeValueHigherThanMaximum"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/homekit/hmerror/code/valuehigherthanmaximum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/homekit/hmerror/code/valuehigherthanmaximum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
