{
  "abstract": [
    {
      "text": "The path to the file or folder in the app package, relative to the installer path.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileSourcePath"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.APFiles.APFileSourcePath",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "APFileSourcePath"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "typealias",
    "title": "APFileSourcePath"
  },
  "primaryContentSections": [
    {
      "details": {
        "ideTitle": "Install file source path",
        "name": "APFileSourcePath",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "string"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles": {
      "abstract": [
        {
          "text": "Describes the files or directories the app installs on the system.",
          "type": "text"
        }
      ],
      "ideTitle": "Installation files",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles",
      "kind": "symbol",
      "name": "APFiles",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFiles"
        }
      ],
      "role": "symbol",
      "title": "APFiles",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APDisplayedAsContainer": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the file or a folder icon is displayed in the Info window.",
          "type": "text"
        }
      ],
      "ideTitle": "Display with folder icon",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APDisplayedAsContainer",
      "kind": "symbol",
      "name": "APDisplayedAsContainer",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APDisplayedAsContainer"
        }
      ],
      "role": "symbol",
      "title": "APDisplayedAsContainer",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apdisplayedascontainer"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDescriptionKey": {
      "abstract": [
        {
          "text": "A short description of the file or folder that appears in the Info window.",
          "type": "text"
        }
      ],
      "ideTitle": "Install file description text",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDescriptionKey",
      "kind": "symbol",
      "name": "APFileDescriptionKey",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFileDescriptionKey"
        }
      ],
      "role": "symbol",
      "title": "APFileDescriptionKey",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apfiledescriptionkey"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDestinationPath": {
      "abstract": [
        {
          "text": "The path to use when installing the file or folder, relative to the app bundle.",
          "type": "text"
        }
      ],
      "ideTitle": "File destination path",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDestinationPath",
      "kind": "symbol",
      "name": "APFileDestinationPath",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFileDestinationPath"
        }
      ],
      "role": "symbol",
      "title": "APFileDestinationPath",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apfiledestinationpath"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileName": {
      "abstract": [
        {
          "text": "The name of the file or folder to install.",
          "type": "text"
        }
      ],
      "ideTitle": "Install file name",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileName",
      "kind": "symbol",
      "name": "APFileName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFileName"
        }
      ],
      "role": "symbol",
      "title": "APFileName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apfilename"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileSourcePath": {
      "abstract": [
        {
          "text": "The path to the file or folder in the app package, relative to the installer path.",
          "type": "text"
        }
      ],
      "ideTitle": "Install file source path",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileSourcePath",
      "kind": "symbol",
      "name": "APFileSourcePath",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APFileSourcePath"
        }
      ],
      "role": "symbol",
      "title": "APFileSourcePath",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apfilesourcepath"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APInstallAction": {
      "abstract": [
        {
          "text": "The action to take on the file or folder.",
          "type": "text"
        }
      ],
      "ideTitle": "File install action",
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APInstallAction",
      "kind": "symbol",
      "name": "APInstallAction",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "APInstallAction"
        }
      ],
      "role": "symbol",
      "title": "APInstallAction",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/apfiles/apinstallaction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Property-List-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APDisplayedAsContainer",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDescriptionKey",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDestinationPath",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APInstallAction"
      ],
      "title": "Property List Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "APFileSourcePath"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFileSourcePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Property-List-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APDisplayedAsContainer",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDescriptionKey",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileDestinationPath",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APFileName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/APFiles/APInstallAction"
              ],
              "title": "Property List Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APDisplayedAsContainer/title",
          "value": "APDisplayedAsContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APDisplayedAsContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APDisplayedAsContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileDescriptionKey/title",
          "value": "APFileDescriptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileDescriptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFileDescriptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileSourcePath/title",
          "value": "APFileSourcePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileSourcePath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFileSourcePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileName/title",
          "value": "APFileName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFileName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APInstallAction/title",
          "value": "APInstallAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APInstallAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APInstallAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/title",
          "value": "APFiles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFiles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileDestinationPath/title",
          "value": "APFileDestinationPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1APFiles~1APFileDestinationPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "APFileDestinationPath"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/apfiles/apfilesourcepath"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/apfiles/apfilesourcepath"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
