{
  "abstract": [
    {
      "text": "A button label with the text ",
      "type": "text"
    },
    {
      "inlineContent": [
        {
          "text": "Current Location",
          "type": "text"
        }
      ],
      "type": "emphasis"
    },
    {
      "text": ".",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CLLocationButtonLabel@CLLocationButtonLabelCurrentLocation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "currentLocation"
      }
    ],
    "modules": [
      {
        "name": "CoreLocationUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CLLocationButtonLabelCurrentLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CLLocationButtonLabel.currentLocation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "currentLocation"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI": {
      "abstract": [
        {
          "text": "Streamline access to users’ location data through a standard, secure UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreLocationUI",
      "type": "topic",
      "url": "/documentation/corelocationui"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel": {
      "abstract": [
        {
          "text": "Constants that specify the text of the button label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabel"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/currentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.currentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/currentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none": {
      "abstract": [
        {
          "text": "A style that doesn’t display a text label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelNone"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.none",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/none"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelSendCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.sendCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sendcurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send My Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sendMyCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelSendMyCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.sendMyCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sendmycurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Share Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelShareCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.shareCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sharecurrentlocation"
    },
    "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation": {
      "abstract": [
        {
          "text": "A button label with the text ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Share My Current Location",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shareMyCurrentLocation"
        }
      ],
      "identifier": "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CLLocationButtonLabelShareMyCurrentLocation"
        }
      ],
      "role": "symbol",
      "title": "CLLocationButtonLabel.shareMyCurrentLocation",
      "type": "topic",
      "url": "/documentation/corelocationui/cllocationbuttonlabel/sharemycurrentlocation"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-label-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
        "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation"
      ],
      "title": "Customizing label styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CLLocationButtonLabelCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-label-styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/none",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/sendMyCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareCurrentLocation",
                "doc://com.apple.CoreLocationUI/documentation/CoreLocationUI/CLLocationButtonLabel/shareMyCurrentLocation"
              ],
              "title": "Customizing label styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CLLocationButtonLabelCurrentLocation"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendCurrentLocation/title",
          "value": "CLLocationButtonLabelSendCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelSendCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareMyCurrentLocation/title",
          "value": "CLLocationButtonLabelShareMyCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareMyCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelShareMyCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareCurrentLocation/title",
          "value": "CLLocationButtonLabelShareCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1shareCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelShareCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1currentLocation/title",
          "value": "CLLocationButtonLabelCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1currentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelCurrentLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1none/title",
          "value": "CLLocationButtonLabelNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/title",
          "value": "CLLocationButtonLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendMyCurrentLocation/title",
          "value": "CLLocationButtonLabelSendMyCurrentLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.CoreLocationUI~1documentation~1CoreLocationUI~1CLLocationButtonLabel~1sendMyCurrentLocation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CLLocationButtonLabelSendMyCurrentLocation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corelocationui/cllocationbuttonlabel/currentlocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corelocationui/cllocationbuttonlabel/currentlocation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
