{
  "abstract": [
    {
      "text": "Defines an audio component by its source channels.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-channel-source"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "audio-channel-source"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "audio-channel-source",
              "type": "codeVoice"
            },
            {
              "text": " element defines an audio component for ",
              "type": "text"
            },
            {
              "code": "clip",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "asset-clip",
              "type": "codeVoice"
            },
            {
              "text": " elements in terms of source channels in the underlying assets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Audio-Channel-Attributes",
          "level": 3,
          "text": "Audio Channel Attributes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "audio-channel-source",
              "type": "codeVoice"
            },
            {
              "text": " element uses the attributes listed below to define its audio channel configuration:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "srcCh",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The audio source channels in the containing ",
                      "type": "text"
                    },
                    {
                      "code": "clip",
                      "type": "codeVoice"
                    },
                    {
                      "text": " element, such as “",
                      "type": "text"
                    },
                    {
                      "code": "1",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "2",
                      "type": "codeVoice"
                    },
                    {
                      "text": "”. Final Cut Pro sorts the channels from underlying assets by their ",
                      "type": "text"
                    },
                    {
                      "code": "srcID",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and then by their ",
                      "type": "text"
                    },
                    {
                      "code": "srcCh",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "outCh",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "An indication of how the audio source channels are assigned to the output, such as “",
                      "type": "text"
                    },
                    {
                      "code": "L",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "R",
                      "type": "codeVoice"
                    },
                    {
                      "text": "”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The next code example reconfigures the audio on the primary timeline as dual mono, while mapping the audio on the anchored item to reverse stereo. Additionally, the example mutes the last 1 second of the anchored audio. The two mono audio components on the primary timeline has roles as ",
              "type": "text"
            },
            {
              "code": "dialogue.dialogue-1",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "dialog.dialogue-2",
              "type": "codeVoice"
            },
            {
              "text": ", while the reverse stereo audio component in the anchored item has a role as ",
              "type": "text"
            },
            {
              "code": "music.music-1",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<asset-clip name=\"MyVideo\" ref=\"r2\" start=\"0s\" duration=\"5s\" audioRole=\"dialogue\">",
            "   <asset-clip name=\"MyAudio\" ref=\"r3\" lane=\"-1\" start=\"10s\" duration=\"5s\" audioRole=\"music\">",
            "      <audio-channel-source role=\"music.music-1\" srcCh=\"2, 1\">",
            "         <mute start=\"14s\" duration=\"1s\" />",
            "      </audio-channel-source>",
            "   </asset-clip>",
            "   <audio-channel-source role=\"dialogue.dialogue-1\" srcCh=\"1\" />",
            "   <audio-channel-source role=\"dialogue.dialogue-2\" srcCh=\"2\" />",
            "</asset-clip>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source": {
      "abstract": [
        {
          "text": "Defines an audio component by its role.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
      "kind": "article",
      "role": "article",
      "title": "audio-role-source",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio-role-source"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute": {
      "abstract": [
        {
          "text": "Suppresses audio output for the audio component over a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute",
      "kind": "article",
      "role": "article",
      "title": "mute",
      "type": "topic",
      "url": "/documentation/professional-video-applications/mute"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Component-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute"
      ],
      "title": "Audio Component Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Component-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute"
              ],
              "title": "Audio Component Configuration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/audio-channel-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/audio-channel-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
