{
  "abstract": [
    {
      "text": "References audio data from an ",
      "type": "text"
    },
    {
      "code": "asset",
      "type": "codeVoice"
    },
    {
      "text": " or ",
      "type": "text"
    },
    {
      "code": "effect",
      "type": "codeVoice"
    },
    {
      "text": " element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "audio"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Attributes of an ",
              "type": "text"
            },
            {
              "code": "audio",
              "type": "codeVoice"
            },
            {
              "text": " element:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "srcID",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "References the specific audio source (or track) in the asset. The default is ",
                      "type": "text"
                    },
                    {
                      "code": "1",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "role",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Assigns a role to the audio media component. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Format is ",
                      "type": "text"
                    },
                    {
                      "code": "main-role.subrole",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "srcCh",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Identifies specific audio source channels in the asset. Value is a comma-separated series of 1-based channel indices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "outCh",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Specifies output channels to send the audio. Value is a comma-separated series of channel tags: ",
                      "type": "text"
                    },
                    {
                      "code": "L",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "R",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "C",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "LFE",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "Ls",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "Rs",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "X",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For information on how to define audio components for story elements, see Audio Component Configuration for more information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip": {
      "abstract": [
        {
          "text": "References a single media asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
      "kind": "article",
      "role": "article",
      "title": "asset-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition": {
      "abstract": [
        {
          "text": "Contains one active story element followed by alternative story elements in the audition container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
      "kind": "article",
      "role": "article",
      "title": "audition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip": {
      "abstract": [
        {
          "text": "Represents a basic unit of editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
      "kind": "article",
      "role": "article",
      "title": "clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap": {
      "abstract": [
        {
          "text": "Defines a placeholder element that has no intrinsic audio or video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
      "kind": "article",
      "role": "article",
      "title": "gap",
      "type": "topic",
      "url": "/documentation/professional-video-applications/gap"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip": {
      "abstract": [
        {
          "text": "References a multicam media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
      "kind": "article",
      "role": "article",
      "title": "mc-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/mc-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip": {
      "abstract": [
        {
          "text": "References a compound clip media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
      "kind": "article",
      "role": "article",
      "title": "ref-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/ref-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence": {
      "abstract": [
        {
          "text": "A container that represents the top-level sequence for a Final Cut Pro project or compound clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence",
      "kind": "article",
      "role": "article",
      "title": "sequence",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sequence"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine": {
      "abstract": [
        {
          "text": "Contains elements ordered sequentially in time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
      "kind": "article",
      "role": "article",
      "title": "spine",
      "type": "topic",
      "url": "/documentation/professional-video-applications/spine"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip": {
      "abstract": [
        {
          "text": "Contains a clip with its contained and anchored items synchronized.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
      "kind": "article",
      "role": "article",
      "title": "sync-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sync-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video": {
      "abstract": [
        {
          "text": "References  video data from an ",
          "type": "text"
        },
        {
          "code": "asset",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "effect",
          "type": "codeVoice"
        },
        {
          "text": " element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
      "kind": "article",
      "role": "article",
      "title": "video",
      "type": "topic",
      "url": "/documentation/professional-video-applications/video"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Story-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
      ],
      "title": "Story Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Story-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
              ],
              "title": "Story Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
