{
  "abstract": [
    {
      "text": "Create a workflow extension in Xcode by using the Final Cut Pro Workflow Extension template.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/building-a-workflow-extension"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Building a Workflow Extension"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you are ready to develop a workflow extension, build it using the Xcode template that comes with the Workflow Extension SDK. The Xcode template packages the extension code in a specific manner (",
              "type": "text"
            },
            {
              "code": ".appex",
              "type": "codeVoice"
            },
            {
              "text": ") and embeds it in an app bundle. When a user installs the app containing your extension, macOS registers the workflow extension, and Final Cut Pro makes the extension available in its interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Install-the-Workflow-Extension-SDK",
          "level": 3,
          "text": "Install the Workflow Extension SDK",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Download and install the Workflow Extension SDK from ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/download/all/?q=WorkflowExtensions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Run the installer that comes with the Workflow Extension SDK. It installs the relevant frameworks and the Xcode template in the appropriate locations on your computer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-Workflow-Extension-Target-to-Your-Project",
          "level": 3,
          "text": "Add a Workflow Extension Target to Your Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You create and configure the workflow extension as a separate target alongside your app. Start by launching Xcode and opening your existing macOS app project. Then choose File > New > Target, select the Final Cut Pro Workflow Extension template from the Workflow Extension section of the macOS platform, and click Next, as shown in the following image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3562763",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Enter a product name for your extension and set other options, like your organization name. Make sure that your app project is selected in the Project menu, and that your macOS app target is selected in the Embed in Application menu. Then click Finish.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Xcode template sets up relevant build options and creates an initial set of project files for the workflow extension. A workflow extension template includes an ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file, a view controller class, and a default user interface. With this initial set of files, you can build and run the project even before you customize the workflow extension code. During the build process, Xcode inserts the extension in the proper place in your app bundle, and you get a workflow extension bundle (ending in ",
              "type": "text"
            },
            {
              "code": ".appex",
              "type": "codeVoice"
            },
            {
              "text": ") that runs in its own process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Keys-to-the-Info-Property-List-Template",
          "level": 3,
          "text": "Add Keys to the Info Property List Template",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The default ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file identifies your workflow extension and may specify some details about your extension under the ",
              "type": "text"
            },
            {
              "code": "NSExtension",
              "type": "codeVoice"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "  <key>NSExtension</key>",
            "  <dict>",
            "    <key>NSExtensionPointIdentifier</key>",
            "    <string>com.apple.FinalCut.WorkfloWExtension</string>",
            "    <key>ProExtensionPrincipalViewControllerClass</key>",
            "    <string>MyExtensionViewController</string>",
            "  </dict>"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Also, if required, you can add keys to the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file to specify the minimum size of the floating window in which Final Cut Pro displays a workflow extension view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, to limit the minimum size of the floating window to 100 x 100 pixels, add the following values to the ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file under the ",
              "type": "text"
            },
            {
              "code": "ProExtensionAttributes",
              "type": "codeVoice"
            },
            {
              "text": " key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "  <key>ProExtensionAttributes</key>",
            "  <dict>",
            "    <key>ContentViewMinimumWidth</key>",
            "    <integer>100</integer>",
            "    <key>ContentViewMinimumHeight</key>",
            "    <integer>100</integer>",
            "  </dict>"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions#Set-a-Minimum-Floating-Window-Size",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Modify-the-Workflow-Extension-Principal-Class",
          "level": 3,
          "text": "Modify the Workflow Extension Principal Class",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A workflow extension is essentially a view controller class for the view hosted in the Final Cut Pro interface. The Xcode template provides a subclass of ",
              "type": "text"
            },
            {
              "code": "NSViewController",
              "type": "codeVoice"
            },
            {
              "text": ", which is the principal class that serves as the primary view controller of the workflow extension. When Final Cut Pro  (the host app) invokes your extension, an operating system service instantiates this class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The principal class has stubs for methods you can modify to customize the workflow in your extension. You can modify this class to act as an observer for changes in the Final Cut Pro timeline or to add support for drag and drop functionality.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a user closes an extension’s floating window, the view controller invokes the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSViewController/viewWillDisappear()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of your extension’s principal class, and the view disappears from the window. Override the ",
              "type": "text"
            },
            {
              "code": "viewWillDisappear",
              "type": "codeVoice"
            },
            {
              "text": " method to remove references to objects that you no longer need or anything you need to do when the view disappears. For example, you may use this method to stop an audio session or to manage any custom objects in your extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-and-Verify-Your-Workflow-Extension",
          "level": 3,
          "text": "Enable and Verify Your Workflow Extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test your workflow extension before submitting it to the app store, you must enable it by installing the containing app in your ",
              "type": "text"
            },
            {
              "code": "/Application",
              "type": "codeVoice"
            },
            {
              "text": " folder and launching the app once from there. This step makes Final Cut Pro recognize and display your extension in its interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To verify that your extension is available in Final Cut Pro, check the extension menu to see if it appears in the list of available extensions. Each menu item contains the localized name of the extension along with the extension icon. You can also get the list of available extensions from the  Extensions item in the Window menu. Either way, when a user chooses an extension, Final Cut Pro loads it and displays its interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Final Cut Pro displays an extension menu in its toolbar only if it has available workflow extensions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Debug-Your-Workflow-Extension",
          "level": 3,
          "text": "Debug Your Workflow Extension",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Debugging your workflow extension in Xcode is similar to debugging any other process in an Xcode debugger. You can connect the Xcode debugger to a workflow extension process before or after launching a workflow extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To connect the Xcode debugger before launching an extension, you attach the debugger to the extension by its name. Choose the Attach to Process by PID or Name option from the Xcode Debug menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To attach the Xcode debugger after launching the extension:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Invoke the extension from the Final Cut Pro interface.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "From the Xcode menu, choose Debug > Attach to Process, then select the extension by name or from the list of running processes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The Xcode debugger attaches to the extension’s process, sets active breakpoints, and lets the extension execute. At this point, you can use the same Xcode debugging features that you use to debug other processes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSViewController/viewWillDisappear()": {
      "abstract": [
        {
          "text": "Called when the view controller’s view is about to be removed from the view hierarchy in the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillDisappear"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSViewController/viewWillDisappear()",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillDisappear()",
      "type": "topic",
      "url": "/documentation/AppKit/NSViewController/viewWillDisappear()"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions": {
      "abstract": [
        {
          "text": "Follow these design guidelines to provide a unique experience to workflow extension users.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions",
      "kind": "article",
      "role": "article",
      "title": "Designing Workflow Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/designing-workflow-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions#Set-a-Minimum-Floating-Window-Size": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions#Set-a-Minimum-Floating-Window-Size",
      "kind": "section",
      "title": "Set a Minimum Floating Window Size",
      "type": "topic",
      "url": "/documentation/professional-video-applications/designing-workflow-extensions#Set-a-Minimum-Floating-Window-Size"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions": {
      "abstract": [
        {
          "text": "Integrate your app’s workflow within the Final Cut Pro interface to streamline data exchange.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workflow Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/workflow-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://developer.apple.com/download/all/?q=WorkflowExtensions": {
      "identifier": "https://developer.apple.com/download/all/?q=WorkflowExtensions",
      "title": "Apple’s developer website",
      "titleInlineContent": [
        {
          "text": "Apple’s developer website",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/download/all/?q=WorkflowExtensions"
    },
    "media-3562763": {
      "alt": "Screenshot showing the Final Cut Pro Workflow Extension template location in the Xcode template window.",
      "identifier": "media-3562763",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8ffff2a50688f7a707746864efccf476/media-3562763@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8ffff2a50688f7a707746864efccf476/media-3562763~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/designing-workflow-extensions"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSViewController~1viewWillDisappear()/title",
          "value": "viewWillDisappear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSViewController~1viewWillDisappear()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "viewWillDisappear"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/building-a-workflow-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/building-a-workflow-extension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
