{
  "abstract": [
    {
      "text": "Contain keyword and smart collections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/collection-folder"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "collection-folder"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "collection-folder",
              "type": "codeVoice"
            },
            {
              "text": " element to describe a collection folder in an event. A ",
              "type": "text"
            },
            {
              "code": "collection-folder",
              "type": "codeVoice"
            },
            {
              "text": " element contains a series of ",
              "type": "text"
            },
            {
              "code": "keyword-collection",
              "type": "codeVoice"
            },
            {
              "text": " elements or ",
              "type": "text"
            },
            {
              "code": "smart-collection",
              "type": "codeVoice"
            },
            {
              "text": " elements, and can also include other ",
              "type": "text"
            },
            {
              "code": "collection-folder",
              "type": "codeVoice"
            },
            {
              "text": " elements. The following example represents a collection folder that contains a keyword collection and a smart collection:\u2028",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<collection-folder name=\"MyCollection\">",
            "   <keyword-collection name=\"MyKeyword\" />",
            "   <smart-collection name=\"Compound Clips\" match=\"all\">",
            "      <match-clip rule=\"is\" type=\"compound\" />",
            "   </smart-collection>",
            "</collection-folder>",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/describing-final-cut-pro-items-in-fcpxml": {
      "abstract": [
        {
          "text": "Describe clips, projects, and other items in FCPXML to exchange data with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/describing-final-cut-pro-items-in-fcpxml",
      "kind": "article",
      "role": "article",
      "title": "Describing Final Cut Pro Items in FCPXML",
      "type": "topic",
      "url": "/documentation/professional-video-applications/describing-final-cut-pro-items-in-fcpxml"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword-collection": {
      "abstract": [
        {
          "text": "Group clips and projects based on matching keywords.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword-collection",
      "kind": "article",
      "role": "article",
      "title": "keyword-collection",
      "type": "topic",
      "url": "/documentation/professional-video-applications/keyword-collection"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection": {
      "abstract": [
        {
          "text": "Describe smart collection filters that group clips and projects that match the criteria.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection",
      "kind": "article",
      "role": "article",
      "title": "smart-collection",
      "type": "topic",
      "url": "/documentation/professional-video-applications/smart-collection"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Clips-and-Project-Collections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/describing-final-cut-pro-items-in-fcpxml",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword-collection",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection"
      ],
      "title": "Clips and Project Collections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Clips-and-Project-Collections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/describing-final-cut-pro-items-in-fcpxml",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword-collection",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection"
              ],
              "title": "Clips and Project Collections"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/collection-folder"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/collection-folder"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
