{
  "abstract": [
    {
      "text": "Group combination of clips as a unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/compound-clip-media"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Compound Clip Media"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A compound clip media is a clip you construct out of audio or video clip components, and which you can reference as a unit. Use the ",
              "type": "text"
            },
            {
              "code": "sequence",
              "type": "codeVoice"
            },
            {
              "text": " element to describe its top-level sequence.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code example below shows a compound clip definition with two clips laid down in series inside a ",
              "type": "text"
            },
            {
              "code": "spine",
              "type": "codeVoice"
            },
            {
              "text": " element and then under a ",
              "type": "text"
            },
            {
              "code": "sequence",
              "type": "codeVoice"
            },
            {
              "text": " element:\u2028",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<resources>",
            "   <media id=\"r1\" name=\"MyCompoundClip\">",
            "      <sequence format=\"r2\">",
            "         <spine>",
            "            <asset-clip name=\"MyMovie1\" offset=\"0s\" ref=\"r3\" duration=\"10s\" audioRole=\"dialogue\" />",
            "            <asset-clip name=\"MyMovie2\" offset=\"0s\" ref=\"r4\" duration=\"20s\" audioRole=\"dialogue\" />",
            "         </spine>",
            "      </sequence>",
            "   </media>",
            "   <format id=\"r2\" name=\"FFVideoFormat1080p30\" />",
            "   <asset id=\"r3\" name=\"MyMovie1\" src=\"file:///Volumes/Media/MyMovie1.mov\" start=\"0s\" duration=\"10s\" hasVideo=\"1\" format=\"r2\" hasAudio=\"1\" audioSources=\"1\" audioChannels=\"2\" audioRate=\"48000\" />",
            "   <asset id=\"r4\" name=\"MyMovie2\" src=\"file:///Volumes/Media/MyMovie2.mov\" start=\"0s\" duration=\"20s\" hasVideo=\"1\" format=\"r2\" hasAudio=\"1\" audioSources=\"1\" audioChannels=\"2\" audioRate=\"48000\" />",
            "</resources>",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Using-Compound-Clip",
          "level": 3,
          "text": "Using Compound Clip",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use the compound clip media as a clip, add a ",
              "type": "text"
            },
            {
              "code": "ref-clip",
              "type": "codeVoice"
            },
            {
              "text": " element that references the media in the timeline. Each ",
              "type": "text"
            },
            {
              "code": "ref-clip",
              "type": "codeVoice"
            },
            {
              "text": " element uses audio and video from the compound clip media. Call out audio components from the compound clip by their roles and apply adjustments or effects. For information on configuring audio components in compound clips, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-components-in-compound-clips",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The code listing below refers to the compound clip defined in the previous code example:\u2028",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<ref-clip ref=\"r4\" name=\"MyCompoundClip\" duration=\"10s\"/>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-components-in-compound-clips": {
      "abstract": [
        {
          "text": "Manipulate audio components in compound clips based on each clip’s role.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-components-in-compound-clips",
      "kind": "article",
      "role": "article",
      "title": "Audio Components in Compound Clips",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio-components-in-compound-clips"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media": {
      "abstract": [
        {
          "text": "Describe a compound clip or a multi-camera media definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Compound-Clip-Media",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-components-in-compound-clips"
      ],
      "title": "Compound Clip Media"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Compound-Clip-Media",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-components-in-compound-clips"
              ],
              "title": "Compound Clip Media"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/compound-clip-media"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/compound-clip-media"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
