{
  "abstract": [
    {
      "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "title": "Content and Metadata Exchanges with Final Cut Pro"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Help your users exchange data between Final Cut Pro and your app, and avoid unwieldy manual processes. With FCPXML representing media, metadata, and Final Cut Pro items, your users can send data from your app to Final Cut Pro for editing, or receive rendered media (movies) and editing decisions from Final Cut Pro projects in your app for further processing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3878511",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "FCPXML is a specialized format that uses XML elements to describe the data going between your app and Final Cut Pro. With FCPXML simplifying the data exchange, app users can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send large quantities of media from an asset management tool to be edited in Final Cut Pro.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Send media clips—annotated with ratings, keywords, and metadata—and let Final Cut Pro organize the incoming media.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Receive rendered media and editing decisions for a project—including lists of media used—from Final Cut Pro for further processing, such as color grading and correction.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Receive rendered media (movies) in an app to finish and package for delivery, playout, or archiving.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Record an audio/video stream and start editing the media in Final Cut Pro while the file is still being recorded.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination": {
      "abstract": [
        {
          "text": "Receive rendered media (movies), editing descriptions for project timelines, library archives, and FCPXML for other Final Cut Pro items in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination",
      "kind": "article",
      "role": "article",
      "title": "Receiving Media and Data Through a Custom Share Destination",
      "type": "topic",
      "url": "/documentation/professional-video-applications/receiving-media-and-data-through-a-custom-share-destination"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Manage and streamline the sending of batches of media assets and timeline sequences from your app using Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Sending Data Programmatically to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-data-programmatically-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets, timeline sequences, and metadata from your app to Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Sending Media and Metadata to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-media-and-metadata-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded": {
      "abstract": [
        {
          "text": "Designate media as a growing file to make it available to users while it’s still being recorded.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded",
      "kind": "article",
      "role": "article",
      "title": "Sending media to Final Cut Pro as it’s recorded",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-media-to-final-cut-pro-as-it-s-recorded"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Add drag and drop support so your users can drag media assets and timeline sequences from your app directly into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop for Data Sent to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-to-receive-final-cut-pro-data": {
      "abstract": [
        {
          "text": "Add drag and drop support in your app to give users an intuitive way to receive clips, projects, and other items from Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-to-receive-final-cut-pro-data",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop to Receive Final Cut Pro Data",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-drag-and-drop-to-receive-final-cut-pro-data"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions": {
      "abstract": [
        {
          "text": "Integrate your app’s workflow within the Final Cut Pro interface to streamline data exchange.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Workflow Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/workflow-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "media-3878511": {
      "alt": "Illustration showing a two-way flow of data between Final Cut Pro and your app, with the Final Cut Pro icon and X M L (to indicate FCPXML) in the middle.",
      "identifier": "media-3878511",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/740b712eda51d05ae5a284cdc920225f/media-3878511@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "XML-Data-Exchange",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ],
      "title": "XML Data Exchange"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
      ],
      "title": "Data Sent from Your App to Final Cut Pro"
    },
    {
      "anchor": "Data-Received-in-Your-App-from-Final-Cut-Pro",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-to-receive-final-cut-pro-data",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination"
      ],
      "title": "Data Received in Your App from Final Cut Pro"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
              ],
              "title": "Data Sent from Your App to Final Cut Pro"
            },
            {
              "anchor": "Data-Received-in-Your-App-from-Final-Cut-Pro",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-to-receive-final-cut-pro-data",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination"
              ],
              "title": "Data Received in Your App from Final Cut Pro"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "XML-Data-Exchange",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/workflow-extensions",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
              ],
              "title": "XML Data Exchange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
