{
  "abstract": [
    {
      "text": "Define the record types, object classes, and event types that let your app interact with Final Cut Pro.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating Scripting Definitions for Custom Share Destinations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As the target application of a Final Cut Pro custom share destination, your app must respond to the Apple events that Final Cut Pro sends to get information about the kind of data your users want. (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/responding-to-apple-events-from-final-cut-pro",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".) Your app must also supply ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "scripting definitions",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " to define the Apple events along with their associated objects and record types. The tables in the following sections describe the definitions your app needs for its interactions with Final Cut Pro.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For an example of a complete scripting definition, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Review-a-Scripting-Definition-Example-Asset-Management-Suite",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Define-Record-Types",
          "level": 3,
          "text": "Define Record Types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "asset location—",
              "type": "codeVoice"
            },
            {
              "text": "Describes the location of the files associated with an object of a class asset. (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Define-Object-Classes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "folder",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "file",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The containing folder path.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "base name",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "text",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The base name for the exported output files. This name must match the asset name.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "has description",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "boolean",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Set to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the app requires FCPXML as the exported output.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "has media",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "boolean",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Set to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the app requires media as the exported output.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "code": "library location—",
              "type": "codeVoice"
            },
            {
              "text": "Describes the location of the library files associated with an asset.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "library folder",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "file",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The containing folder path.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "library base name",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "text",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The base name for the exported output files.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "has archive",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "boolean",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Set to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the application requires a library archive as the exported output.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "has library description",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "boolean",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Set to ",
                      "type": "text"
                    },
                    {
                      "code": "true",
                      "type": "codeVoice"
                    },
                    {
                      "text": " if the application requires FCPXML as the exported output.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Define-Object-Classes",
          "level": 3,
          "text": "Define Object Classes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "asset—",
              "type": "codeVoice"
            },
            {
              "text": "Represents an asset object that corresponds to the exported output from Final Cut Pro.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "id",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "text",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The unique asset identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "name",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "text",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The asset name.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "location info",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "asset location",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The location of files associated with the asset.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "library info",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "library location",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The location of the library files associated with the asset.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "metadata",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "user defined record",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The shared metadata set associated with the asset.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "data options",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "user defined record",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The options set for the asset data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The protocol between Final Cut Pro and your app through Apple events should be agnostic to your app’s object containment hierarchy. For example, the scripting definition in the Asset Management Suite Example defines an asset as a document element, but it could also define an asset as an element of a larger entity, such as a media asset database.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Your app needs only to return an object specifier with which Final Cut Pro can access a specific asset object. (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Review-a-Scripting-Definition-Example-Asset-Management-Suite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When an asset object is not a document, handling an ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event to associate files to an asset might be a bit awkward. Because Cocoa Scripting handles the ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event, you need a custom document controller to override the behavior of Cocoa when your app opens a file and when it associates a file (based on matching the URL) with either an existing asset object or with a new asset object. You may need some customization to ensure that the files handled through the ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event are properly associated to the asset object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Define-Event-Types",
          "level": 3,
          "text": "Define Event Types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "make—",
              "type": "codeVoice"
            },
            {
              "text": "Creates a new asset object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Property",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Type",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "new",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "type",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The new object’s class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "at",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "location specifier",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The location in which to insert the new object.*",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "with data",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "any",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The initial contents of the object.*",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "with",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "properties",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "record",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "A list of object properties used to initialize the new object: ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "name",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (",
                      "type": "text"
                    },
                    {
                      "code": "text",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")—The asset name. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "metadata",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (",
                      "type": "text"
                    },
                    {
                      "code": "record",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")—The metadata set associated with the asset object. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "data",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "options",
                      "type": "codeVoice"
                    },
                    {
                      "text": " (",
                      "type": "text"
                    },
                    {
                      "code": "record",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")—The option set used to create the asset data.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Final Cut Pro doesn’t use the ",
                  "type": "text"
                },
                {
                  "code": "at",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "with data",
                  "type": "codeVoice"
                },
                {
                  "text": " parameters itself, but they are inherited from the respective event definitions (or ",
                  "type": "text"
                },
                {
                  "code": "make",
                  "type": "codeVoice"
                },
                {
                  "text": " event definitions) in the standard suite. They’re included here in case your app needs to support these parameters for other clients.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Specify-an-Access-Group-for-Your-App",
          "level": 3,
          "text": "Specify an Access Group for Your App",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To enable access from a sandboxed application to the objects and events in your app, your app must specify ",
              "type": "text"
            },
            {
              "code": "com.apple.assetmanagement.import",
              "type": "codeVoice"
            },
            {
              "text": " as the access group for:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The object class for media assets",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The respective element in its container",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "code": "Create Asset",
                      "type": "codeVoice"
                    },
                    {
                      "text": " event",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ScriptableCocoaApplications/SApps_intro/SAppsIntro.html#//apple_ref/doc/uid/TP40002164",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " describes how to use classes and categories to create scriptable apps (referred to as Cocoa scripting) in the Cocoa application framework.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Review-a-Scripting-Definition-Example-Asset-Management-Suite",
          "level": 3,
          "text": "Review a Scripting Definition Example: Asset Management Suite",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An app that interacts with Final Cut Pro must support the events and object classes described in the previous tables. The following code shows a complete example of a scripting definition used by an asset-management app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!DOCTYPE dictionary SYSTEM \"file://localhost/System/Library/DTDs/sdef.dtd\">",
            " ",
            "<!--",
            " ",
            "   File: AssetManagementSuite.sdef",
            " Abstract: Asset Management suite scripting definitions",
            "     for the SimpleAssetManager sample code.",
            "  Version: 1.6",
            "",
            "    Disclaimer: IMPORTANT:  This Apple software is supplied to you by Apple Inc. (\"Apple\") in consideration of your agreement to the following terms, and your use, installation, modification or redistribution of this Apple software constitutes acceptance of these terms.  If you do not agree with these terms, please do not use, install, modify or redistribute this Apple software.",
            "    In consideration of your agreement to abide by the following terms, and subject to these terms, Apple grants you a personal, non-exclusive license, under Apple's copyrights in this original Apple software (the \"Apple Software\"), to use, reproduce, modify and redistribute the AppleSoftware, with or without modifications, in source and/or binary forms; provided that if you redistribute the Apple Software in its entirety and without modifications, you must retain this notice and the following text and disclaimers in all such redistributions of the Apple Software.",
            "    Neither the name, trademarks, service marks or logos of Apple Inc. may be used to endorse or promote products derived from the Apple Software without specific prior written permission from Apple.  Except as expressly stated in this notice, no other rights or licenses, express or implied, are granted by Apple herein, including but not limited to any patent rights that may be infringed by your derivative works or by other works in which the Apple Software may be incorporated.",
            "    The Apple Software is provided by Apple on an \"AS IS\" basis.  APPLE MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS.",
            "    IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.",
            "",
            "Copyright (C) 2011-2019 Apple Inc. All Rights Reserved.",
            " ",
            "-->",
            " ",
            " ",
            "<!-- declare the namespace for using XInclude so you can include the standard suite -->",
            "<dictionary xmlns:xi=\"http://www.w3.org/2003/XInclude\">",
            " ",
            "  <!-- use XInclude to include the standard suite -->",
            "  <xi:include href=\"file:///System/Library/ScriptingDefinitions/CocoaStandard.sdef\" xpointer=\"xpointer(/dictionary/suite)\"/>",
            " ",
            "  <!-- specific suite(s) for the application follow... -->",
            "  <suite name=\"ProVideo Asset Management\" code=\"pvam\" description=\"Scripting terminology for Pro Video Asset Management applications.\">",
            " ",
            "    <record-type name=\"asset location\" code=\"aslc\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <property name=\"folder\" code=\"asfd\" type=\"file\" description=\"Directory in which the asset files exist.\">",
            "        <cocoa key=\"folder\"/>",
            "      </property>",
            "      <property name=\"base name\" code=\"asbn\" type=\"text\" description=\"Base file name of the asset files.\">",
            "        <cocoa key=\"basename\"/>",
            "      </property>",
            "      <property name=\"has media\" code=\"ashm\" type=\"boolean\" description=\"Whether the asset has rendered media\">",
            "        <cocoa key=\"hasMedia\"/>",
            "      </property>",
            "      <property name=\"has description\" code=\"ashd\" type=\"boolean\" description=\"Whether the asset has an XML description\">",
            "        <cocoa key=\"hasDescription\"/>",
            "      </property>",
            "    </record-type>",
            " ",
            "    <!-- record type for library access -->",
            "    <record-type name=\"library location\" code=\"lblc\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <property name=\"library folder\" code=\"lbfd\" type=\"file\" description=\"Directory in which the library files exist.\">",
            "        <cocoa key=\"folder\"/>",
            "      </property>",
            "      <property name=\"library base name\" code=\"lbbn\" type=\"text\" description=\"Base file name of the library files.\">",
            "        <cocoa key=\"basename\"/>",
            "      </property>",
            "      <property name=\"has archive\" code=\"lbha\" type=\"boolean\" description=\"Whether the library has data for archive.\">",
            "        <cocoa key=\"hasArchive\"/>",
            "      </property>",
            "      <property name=\"has library description\" code=\"lbhd\" type=\"boolean\" description=\"Whether the library has an XML description.\">",
            "        <cocoa key=\"hasDescription\"/>",
            "      </property>",
            "    </record-type>",
            " ",
            "    <value-type name=\"user defined record\" code=\"usrf\">",
            "      <cocoa class=\"NSDictionary\"/>",
            "    </value-type>",
            " ",
            "    <command name=\"open\" code=\"aevtodoc\" description=\"Open a document.\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <direct-parameter description=\"The file(s) to be opened.\">",
            "        <type type=\"file\"/>",
            "        <type type=\"file\" list=\"yes\"/>",
            "      </direct-parameter>",
            "      <result description=\"The opened document(s).\">",
            "        <type type=\"document\"/>",
            "        <type type=\"document\" list=\"yes\"/>",
            "      </result>",
            "    </command>",
            " ",
            "    <command name=\"make\" code=\"corecrel\" description=\"Create a new object.\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <cocoa class=\"SAMMakeCommand\"/>",
            "      <parameter name=\"new\" code=\"kocl\" type=\"type\" description=\"The class of the new object.\">",
            "        <cocoa key=\"ObjectClass\"/>",
            "      </parameter>",
            "      <parameter name=\"at\" code=\"insh\" type=\"location specifier\" optional=\"yes\" description=\"The location at which to insert the object.\">",
            "        <cocoa key=\"Location\"/>",
            "      </parameter>",
            "      <parameter name=\"with data\" code=\"data\" type=\"any\" optional=\"yes\" description=\"The initial contents of the object.\">",
            "        <cocoa key=\"ObjectData\"/>",
            "      </parameter>",
            "      <parameter name=\"with properties\" code=\"prdt\" type=\"record\" optional=\"yes\" description=\"The initial values for properties of the object.\">",
            "        <cocoa key=\"KeyDictionary\"/>",
            "      </parameter>",
            "      <result type=\"specifier\" description=\"The new object.\"/>",
            "    </command>",
            " ",
            "    <class-extension name=\"application\" extends=\"application\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <cocoa class=\"NSApplication\"/>",
            "      <property name=\"name\" code=\"pnam\" type=\"text\" access=\"r\" description=\"The name of the application.\">",
            "        <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      </property>",
            "      <element type=\"document\">",
            "        <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      </element>",
            "    </class-extension>",
            " ",
            "    <class name=\"document\" code=\"docu\" description=\"A document.\" inherits=\"document\">",
            "      <access-group identifier=\"com.apple.proapps.assetmanagement.import\" access=\"rw\"/>",
            "      <cocoa class=\"SAMDocument\"/>",
            "      <property name=\"name\" code=\"pnam\" type=\"text\" access=\"r\" description=\"The name of the application.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "      </property>",
            "      <property name=\"id\" code=\"ID  \" type=\"text\" access=\"r\" description=\"The unique identifier of the asset\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "      </property>",
            "      <element type=\"asset\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"assets\"/>",
            "      </element>",
            "    </class>",
            " ",
            "    <class name=\"asset\" code=\"aset\" description=\"A media asset.\">",
            "      <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "      <cocoa class=\"SAMAsset\"/>",
            "      <property name=\"id\" code=\"ID  \" type=\"text\" access=\"r\" description=\"The unique identifier of the asset\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"uniqueID\"/>",
            "      </property>",
            "      <property name=\"name\" code=\"pnam\" type=\"text\" access=\"r\" description=\"Its name.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"name\"/>",
            "      </property>",
            "      <property name=\"location info\" code=\"locn\" type=\"asset location\" access=\"r\" description=\"Location information of the asset.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"locationInfo\"/>",
            "      </property>",
            "      <property name=\"library info\" code=\"lbry\" type=\"library location\" access=\"r\" description=\"Location information of the containing library in the source.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"libraryInfo\"/>",
            "      </property>",
            "      <property name=\"metadata\" code=\"meta\" type=\"user defined record\" access=\"rw\" description=\"Metadata associated to the asset.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"metadata\"/>",
            "      </property>",
            "      <property name=\"data options\" code=\"dopt\" type=\"user defined record\" access=\"rw\" description=\"Data creation options for the asset.\">",
            "        <access-group identifier=\"com.apple.assetmanagement.import\" access=\"rw\"/>",
            "        <cocoa key=\"dataOptions\"/>",
            "      </property>",
            "    </class>",
            "    <enumeration name=\"saveable file format\" code=\"savf\">",
            "      <enumerator name=\"document\" code=\"docu\" description=\"A document.\"/>",
            "    </enumeration>",
            "  </suite>",
            "</dictionary>",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Metadata Exchanges with Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Define-Object-Classes": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Define-Object-Classes",
      "kind": "section",
      "title": "Define Object Classes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-scripting-definitions-for-custom-share-destinations#Define-Object-Classes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Review-a-Scripting-Definition-Example-Asset-Management-Suite": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-scripting-definitions-for-custom-share-destinations#Review-a-Scripting-Definition-Example-Asset-Management-Suite",
      "kind": "section",
      "title": "Review a Scripting Definition Example: Asset Management Suite",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-scripting-definitions-for-custom-share-destinations#Review-a-Scripting-Definition-Example-Asset-Management-Suite"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination": {
      "abstract": [
        {
          "text": "Receive rendered media (movies), editing descriptions for project timelines, library archives, and FCPXML for other Final Cut Pro items in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination",
      "kind": "article",
      "role": "article",
      "title": "Receiving Media and Data Through a Custom Share Destination",
      "type": "topic",
      "url": "/documentation/professional-video-applications/receiving-media-and-data-through-a-custom-share-destination"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/responding-to-apple-events-from-final-cut-pro": {
      "abstract": [
        {
          "text": "Tell Final Cut Pro about the kind of data your users want to receive in your app through a custom share destination.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/responding-to-apple-events-from-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Responding to Apple Events from Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/responding-to-apple-events-from-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-conversions-with-scripting-class-extensions": {
      "abstract": [
        {
          "text": "Support conversions between the Apple event descriptor types and Foundation object classes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-conversions-with-scripting-class-extensions",
      "kind": "article",
      "role": "article",
      "title": "Supporting Conversions with Scripting Class Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-conversions-with-scripting-class-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ScriptableCocoaApplications/SApps_intro/SAppsIntro.html#//apple_ref/doc/uid/TP40002164": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ScriptableCocoaApplications/SApps_intro/SAppsIntro.html#//apple_ref/doc/uid/TP40002164",
      "title": "Cocoa Scripting Guide",
      "titleInlineContent": [
        {
          "text": "Cocoa Scripting Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ScriptableCocoaApplications/SApps_intro/SAppsIntro.html#//apple_ref/doc/uid/TP40002164"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-Apple-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/responding-to-apple-events-from-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-conversions-with-scripting-class-extensions"
      ],
      "title": "Handling Apple Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-Apple-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/responding-to-apple-events-from-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-conversions-with-scripting-class-extensions"
              ],
              "title": "Handling Apple Events"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/creating-scripting-definitions-for-custom-share-destinations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/creating-scripting-definitions-for-custom-share-destinations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
