{
  "abstract": [
    {
      "text": "Encoder attributes specify the audio and video configuration values for the output format.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-attributes-settings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Encoder Attributes Settings"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You specify the encoder attributes as the keys and values in the dictionary the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorExtensionSettings/settingsAttributes()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method returns. The available encoder attribute keys are listed below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions": {
      "abstract": [
        {
          "text": "Add custom output file formats to the Final Cut Pro workflow.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/encoder-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Encoder Extensions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/encoder-extensions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorExtensionSettings/settingsAttributes()": {
      "abstract": [
        {
          "text": "Returns a set of audio and video encoding attributes to display on the Compressor app interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "settingsAttributes"
        },
        {
          "kind": "text",
          "text": "() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/CompressorExtensionSettings/settingsAttributes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "settingsAttributes"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "settingsAttributes()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/compressorextensionsettings/settingsattributes()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey": {
      "abstract": [
        {
          "text": "Specifies whether the extension supports segmentation of the source media.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAllowsSegmentationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAllowsSegmentationKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAllowsSegmentationKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceallowssegmentationkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey": {
      "abstract": [
        {
          "text": "Specifies the audio channel layout for the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioChannelLayoutKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioChannelLayoutKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioChannelLayoutKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiochannellayoutkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey": {
      "abstract": [
        {
          "text": "Specifies whether audio is enabled in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioEnabledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioEnabledKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioEnabledKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudioenabledkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey": {
      "abstract": [
        {
          "text": "Specifies whether audio samples are in floating-point value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleFloatKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleFloatKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleFloatKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosamplefloatkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey": {
      "abstract": [
        {
          "text": "Specifies the sample rate of audio in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleRateKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleRateKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosampleratekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey": {
      "abstract": [
        {
          "text": "Specifies the number of bits per audio sample in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAudioSampleSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAudioSampleSizeKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAudioSampleSizeKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceaudiosamplesizekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey": {
      "abstract": [
        {
          "text": "Specifies whether the output file height is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoHeightKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautoheightkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey": {
      "abstract": [
        {
          "text": "Specifies whether the frame rate is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoRateKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoRateKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautoratekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey": {
      "abstract": [
        {
          "text": "Specifies whether the output file width is set to automatic in the encoder settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEAutoWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEAutoWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCEAutoWidthKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceautowidthkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey": {
      "abstract": [
        {
          "text": "Specifies the color space supported in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEColorSpaceKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEColorSpaceKey"
        }
      ],
      "role": "symbol",
      "title": "kCEColorSpaceKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcecolorspacekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEDenominatorKey": {
      "abstract": [
        {
          "text": "Specifies the denominator of a ratio-based output frame rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEDenominatorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEDenominatorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEDenominatorKey"
        }
      ],
      "role": "symbol",
      "title": "kCEDenominatorKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcedenominatorkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey": {
      "abstract": [
        {
          "text": "Specifies the output scanning method.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEFieldOrderKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEFieldOrderKey"
        }
      ],
      "role": "symbol",
      "title": "kCEFieldOrderKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcefieldorderkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey": {
      "abstract": [
        {
          "text": "Specifies the extension of the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEFileExtensionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEFileExtensionKey"
        }
      ],
      "role": "symbol",
      "title": "kCEFileExtensionKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcefileextensionkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFrameRateKey": {
      "abstract": [
        {
          "text": "Specifies the frame rate of the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEFrameRateKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFrameRateKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEFrameRateKey"
        }
      ],
      "role": "symbol",
      "title": "kCEFrameRateKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceframeratekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey": {
      "abstract": [
        {
          "text": "Specifies the height of the encoded video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEHeightKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEHeightKey"
        }
      ],
      "role": "symbol",
      "title": "kCEHeightKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kceheightkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerDurationKey": {
      "abstract": [
        {
          "text": "Specifies the duration of the chapter marker, as number of frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerDurationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerDurationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerDurationKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerDurationKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerdurationkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerFrameNumberKey": {
      "abstract": [
        {
          "text": "Specifies the output chapter marker’s start time, as a frame number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerFrameNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerFrameNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerFrameNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerFrameNumberKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerframenumberkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageFileURLKey": {
      "abstract": [
        {
          "text": "Specifies the marker’s file URL when the marker image comes from a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerImageFileURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageFileURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerImageFileURLKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerImageFileURLKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerimagefileurlkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceFrameNumberKey": {
      "abstract": [
        {
          "text": "Specifies a source file chapter marker’s start time, as a frame number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerImageSourceFrameNumberKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceFrameNumberKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerImageSourceFrameNumberKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerImageSourceFrameNumberKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerimagesourceframenumberkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceTimeKey": {
      "abstract": [
        {
          "text": "Specifies a source file chapter marker’s start time, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerImageSourceTimeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceTimeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerImageSourceTimeKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerImageSourceTimeKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerimagesourcetimekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerKindKey": {
      "abstract": [
        {
          "text": "Specifies the kind of marker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerKindKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerKindKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerKindKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerKindKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerkindkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerNameKey": {
      "abstract": [
        {
          "text": "Specifies the chapter marker name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerNameKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkernamekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerTimeKey": {
      "abstract": [
        {
          "text": "Specifies the chapter marker start time, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerTimeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerTimeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerTimeKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerTimeKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkertimekey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerURLKey": {
      "abstract": [
        {
          "text": "Specifies the chapter marker URL when the marker image comes from a file stored on the web server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEMarkerURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEMarkerURLKey"
        }
      ],
      "role": "symbol",
      "title": "kCEMarkerURLKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcemarkerurlkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCENumeratorKey": {
      "abstract": [
        {
          "text": "Specifies the numerator of a ratio-based output frame rate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCENumeratorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCENumeratorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCENumeratorKey"
        }
      ],
      "role": "symbol",
      "title": "kCENumeratorKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcenumeratorkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey": {
      "abstract": [
        {
          "text": "Specifies the aspect ratio of the output frame pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEPixelAspectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEPixelAspectKey"
        }
      ],
      "role": "symbol",
      "title": "kCEPixelAspectKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcepixelaspectkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey": {
      "abstract": [
        {
          "text": "Specifies whether video is enabled in the output file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEVideoEnabledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEVideoEnabledKey"
        }
      ],
      "role": "symbol",
      "title": "kCEVideoEnabledKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcevideoenabledkey"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey": {
      "abstract": [
        {
          "text": "Specifies the width of the encoded video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCEWidthKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCEWidthKey"
        }
      ],
      "role": "symbol",
      "title": "kCEWidthKey",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kcewidthkey"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Encoder-Attribute-Keys",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCENumeratorKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEDenominatorKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFrameRateKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerURLKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerTimeKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerNameKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerKindKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceTimeKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceFrameNumberKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageFileURLKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerFrameNumberKey",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerDurationKey"
      ],
      "title": "Encoder Attribute Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Encoder-Attribute-Keys",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAllowsSegmentationKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFileExtensionKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFieldOrderKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEColorSpaceKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioChannelLayoutKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEVideoEnabledKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioEnabledKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleFloatKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleRateKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAudioSampleSizeKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEWidthKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEHeightKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoRateKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoWidthKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEAutoHeightKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEPixelAspectKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCENumeratorKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEDenominatorKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEFrameRateKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerURLKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerTimeKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerNameKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerKindKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceTimeKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageSourceFrameNumberKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerImageFileURLKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerFrameNumberKey",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kCEMarkerDurationKey"
              ],
              "title": "Encoder Attribute Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleFloatKey/title",
          "value": "kCEAudioSampleFloatKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleFloatKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleFloatKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleRateKey/title",
          "value": "kCEAudioSampleRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioEnabledKey/title",
          "value": "kCEAudioEnabledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioEnabledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioEnabledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoWidthKey/title",
          "value": "kCEAutoWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEVideoEnabledKey/title",
          "value": "kCEVideoEnabledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEVideoEnabledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEVideoEnabledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEDenominatorKey/title",
          "value": "kCEDenominatorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEDenominatorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEDenominatorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEWidthKey/title",
          "value": "kCEWidthKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEWidthKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEWidthKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCENumeratorKey/title",
          "value": "kCENumeratorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCENumeratorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCENumeratorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerKindKey/title",
          "value": "kCEMarkerKindKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerKindKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerKindKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorExtensionSettings~1settingsAttributes()/title",
          "value": "settingsAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1CompressorExtensionSettings~1settingsAttributes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "settingsAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFieldOrderKey/title",
          "value": "kCEFieldOrderKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFieldOrderKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEFieldOrderKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFrameRateKey/title",
          "value": "kCEFrameRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFrameRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEFrameRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoHeightKey/title",
          "value": "kCEAutoHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageFileURLKey/title",
          "value": "kCEMarkerImageFileURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageFileURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerImageFileURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerURLKey/title",
          "value": "kCEMarkerURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageSourceFrameNumberKey/title",
          "value": "kCEMarkerImageSourceFrameNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageSourceFrameNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerImageSourceFrameNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioChannelLayoutKey/title",
          "value": "kCEAudioChannelLayoutKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioChannelLayoutKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioChannelLayoutKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerFrameNumberKey/title",
          "value": "kCEMarkerFrameNumberKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerFrameNumberKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerFrameNumberKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEPixelAspectKey/title",
          "value": "kCEPixelAspectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEPixelAspectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEPixelAspectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoRateKey/title",
          "value": "kCEAutoRateKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAutoRateKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAutoRateKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEHeightKey/title",
          "value": "kCEHeightKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEHeightKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEHeightKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerNameKey/title",
          "value": "kCEMarkerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleSizeKey/title",
          "value": "kCEAudioSampleSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAudioSampleSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAudioSampleSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerTimeKey/title",
          "value": "kCEMarkerTimeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerTimeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerTimeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEColorSpaceKey/title",
          "value": "kCEColorSpaceKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEColorSpaceKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEColorSpaceKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAllowsSegmentationKey/title",
          "value": "kCEAllowsSegmentationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEAllowsSegmentationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEAllowsSegmentationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFileExtensionKey/title",
          "value": "kCEFileExtensionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEFileExtensionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEFileExtensionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerDurationKey/title",
          "value": "kCEMarkerDurationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerDurationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerDurationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageSourceTimeKey/title",
          "value": "kCEMarkerImageSourceTimeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kCEMarkerImageSourceTimeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCEMarkerImageSourceTimeKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/encoder-attributes-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/encoder-attributes-settings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
