{
  "abstract": [
    {
      "text": "Represent a single event in a library.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/event"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "event"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An event may contain clips as story elements and projects, along with keyword collections and smart collections. The ",
              "type": "text"
            },
            {
              "code": "keyword-collection",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "smart-collection",
              "type": "codeVoice"
            },
            {
              "text": " elements organize clips by keywords and other matching criteria listed under the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection#Smart-Collection-Match-Elements",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "An event element has the following attributes:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "name",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Specifies name of the event.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "An event element has the following subelements:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Subelements",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "clip",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Represents a basic unit of editing.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "audition",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Contains one active story element followed by alternative story elements in the audition container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "mc-clip",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "References a multicam media.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "ref-clip",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "References a compound clip media.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "sync-clip",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Contains a clip with its contained and anchored items synchronized.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "asset-clip",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "References a single media asset.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "project",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Represents a project timeline.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "keyword-collection",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Groups clips and projects based on matching keywords.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "smart-collection",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Describes smart collection filters that group clips and projects that match the criteria.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "collection-folder",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Contains keyword and smart collections.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents": {
      "abstract": [
        {
          "text": "Describe media assets, editing decisions, metadata, and other items in FCPXML so users can send and receive data between your app and Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
      "kind": "article",
      "role": "article",
      "title": "Creating FCPXML Documents",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-fcpxml-documents"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml": {
      "abstract": [
        {
          "text": "Contain top-level elements in a document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
      "kind": "article",
      "role": "article",
      "title": "fcpxml",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-bundle-reference": {
      "abstract": [
        {
          "text": "Keep an FCPXML document and any files it references together in a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-bundle-reference",
      "kind": "article",
      "role": "article",
      "title": "FCPXML Bundle Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-bundle-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options": {
      "abstract": [
        {
          "text": "Contain options that describe how to import events and projects into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options",
      "kind": "article",
      "role": "article",
      "title": "import-options",
      "type": "topic",
      "url": "/documentation/professional-video-applications/import-options"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data": {
      "abstract": [
        {
          "text": "Import data from Final Cut Pro to your app by using FCPXML.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
      "kind": "article",
      "role": "article",
      "title": "Importing FCPXML Data",
      "type": "topic",
      "url": "/documentation/professional-video-applications/importing-fcpxml-data"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library": {
      "abstract": [
        {
          "text": "Contain events, clips, projects, and smart collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
      "kind": "article",
      "role": "article",
      "title": "library",
      "type": "topic",
      "url": "/documentation/professional-video-applications/library"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project": {
      "abstract": [
        {
          "text": "Represent a project timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
      "kind": "article",
      "role": "article",
      "title": "project",
      "type": "topic",
      "url": "/documentation/professional-video-applications/project"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources": {
      "abstract": [
        {
          "text": "Contain shared resources on which events and projects depend.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
      "kind": "article",
      "role": "article",
      "title": "resources",
      "type": "topic",
      "url": "/documentation/professional-video-applications/resources"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection#Smart-Collection-Match-Elements": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/smart-collection#Smart-Collection-Match-Elements",
      "kind": "section",
      "title": "Smart Collection Match Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/smart-collection#Smart-Collection-Match-Elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Structure-and-Root-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-bundle-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options"
      ],
      "title": "Document Structure and Root Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Structure-and-Root-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-bundle-reference",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options"
              ],
              "title": "Document Structure and Root Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/event"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/event"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
