{
  "abstract": [
    {
      "text": "Keep an FCPXML document and any files it references together in a bundle.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-bundle-reference"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "FCPXML Bundle Reference"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a user shares data from Final Cut Pro with your app, Final Cut Pro exports the required files and packages them together in a bundle. The bundle format makes it easy for an app to keep FCPXML and referenced files together. FCPXML Bundles have a ",
              "type": "text"
            },
            {
              "code": ".fcpxmld",
              "type": "codeVoice"
            },
            {
              "text": " extension.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3878510",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The simplest FCPXML bundle contains an ",
              "type": "text"
            },
            {
              "code": "Info.fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " file at the root level of the bundle. This file contains a structured description of the exported data. You use the file to retrieve information about the exported data and locate other relevant files in the bundle. The format of the ",
              "type": "text"
            },
            {
              "code": "Info.fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " file is defined in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (DTD).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app already supports ",
              "type": "text"
            },
            {
              "code": ".fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " files, add support for the new bundle format to ensure full compatibility with exports from Final Cut Pro.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "FCPXML bundle support is available for Document Type Definition (DTD) 1.10 and later.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents": {
      "abstract": [
        {
          "text": "Describe media assets, editing decisions, metadata, and other items in FCPXML so users can send and receive data between your app and Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
      "kind": "article",
      "role": "article",
      "title": "Creating FCPXML Documents",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-fcpxml-documents"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition": {
      "abstract": [
        {
          "text": "Document Type Definition (DTD) for the latest Final Cut Pro XML interchange format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition",
      "kind": "article",
      "role": "article",
      "title": "Document Type Definition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/document-type-definition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/event": {
      "abstract": [
        {
          "text": "Represent a single event in a library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/event",
      "kind": "article",
      "role": "article",
      "title": "event",
      "type": "topic",
      "url": "/documentation/professional-video-applications/event"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml": {
      "abstract": [
        {
          "text": "Contain top-level elements in a document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
      "kind": "article",
      "role": "article",
      "title": "fcpxml",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options": {
      "abstract": [
        {
          "text": "Contain options that describe how to import events and projects into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options",
      "kind": "article",
      "role": "article",
      "title": "import-options",
      "type": "topic",
      "url": "/documentation/professional-video-applications/import-options"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data": {
      "abstract": [
        {
          "text": "Import data from Final Cut Pro to your app by using FCPXML.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
      "kind": "article",
      "role": "article",
      "title": "Importing FCPXML Data",
      "type": "topic",
      "url": "/documentation/professional-video-applications/importing-fcpxml-data"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library": {
      "abstract": [
        {
          "text": "Contain events, clips, projects, and smart collections.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
      "kind": "article",
      "role": "article",
      "title": "library",
      "type": "topic",
      "url": "/documentation/professional-video-applications/library"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project": {
      "abstract": [
        {
          "text": "Represent a project timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
      "kind": "article",
      "role": "article",
      "title": "project",
      "type": "topic",
      "url": "/documentation/professional-video-applications/project"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources": {
      "abstract": [
        {
          "text": "Contain shared resources on which events and projects depend.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
      "kind": "article",
      "role": "article",
      "title": "resources",
      "type": "topic",
      "url": "/documentation/professional-video-applications/resources"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "media-3878510": {
      "alt": "Illustration that shows a data flow from a Final Cut Pro icon on the right to an X  M L bundle in the middle, and then to your app on the left. ",
      "identifier": "media-3878510",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/52910ac2d404e24d294c3ea28a3a1c7f/media-3878510@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Document-Structure-and-Root-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/event",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options"
      ],
      "title": "Document Structure and Root Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Document-Structure-and-Root-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/importing-fcpxml-data",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/resources",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/library",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/event",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/project",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options"
              ],
              "title": "Document Structure and Root Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/fcpxml-bundle-reference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/fcpxml-bundle-reference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
