{
  "abstract": [
    {
      "text": "A filter element that references an audio effect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-audio"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "filter-audio"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apply audio filters to elements that represent audible media, for example, ",
              "type": "text"
            },
            {
              "code": "audio",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "clip",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "ref-clip",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "audio-source",
              "type": "codeVoice"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "code": "audio-aux-source",
              "type": "codeVoice"
            },
            {
              "text": " elements. For multicam clips, apply the audio filters to the entire multicam clip, represented by ",
              "type": "text"
            },
            {
              "code": "mc-clip",
              "type": "codeVoice"
            },
            {
              "text": " elements.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In FCPXML 1.3 and later, the ",
                  "type": "text"
                },
                {
                  "code": "filter-audio",
                  "type": "codeVoice"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "code": "filter-video",
                  "type": "codeVoice"
                },
                {
                  "text": " elements represent audio or video filters respectively. In versions earlier than FCPXML 1.3, a single ",
                  "type": "text"
                },
                {
                  "code": "filter",
                  "type": "codeVoice"
                },
                {
                  "text": " element represented both audio and video filters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters": {
      "abstract": [
        {
          "text": "Specify values to change adjustment attributes and effects parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
      "kind": "article",
      "role": "article",
      "title": "Adjustment Attributes and Effect Parameters",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adjustment-attributes-and-effect-parameters"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements": {
      "abstract": [
        {
          "text": "Alter the audio and video output of story elements by using adjustment elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Adjustment Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adjustment-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation": {
      "abstract": [
        {
          "text": "Create animations by changing specific adjustment attributes and effect parameters over time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/professional-video-applications/animation"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption": {
      "abstract": [
        {
          "text": "Represents a closed-caption or subtitle with one or more text blocks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
      "kind": "article",
      "role": "article",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/professional-video-applications/caption"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video": {
      "abstract": [
        {
          "text": "A filter element that references a video effect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
      "kind": "article",
      "role": "article",
      "title": "filter-video",
      "type": "topic",
      "url": "/documentation/professional-video-applications/filter-video"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters": {
      "abstract": [
        {
          "text": "Designate a region to which you apply video filter by using a collection of masks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Masked Filters",
      "type": "topic",
      "url": "/documentation/professional-video-applications/masked-filters"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title": {
      "abstract": [
        {
          "text": "Represents a title with one or more text blocks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
      "kind": "article",
      "role": "collectionGroup",
      "title": "title",
      "type": "topic",
      "url": "/documentation/professional-video-applications/title"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition": {
      "abstract": [
        {
          "text": "Applies transition effects that either stand by itself (no neighboring elements), combine two neighboring elements, or apply to a single element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
      "kind": "article",
      "role": "article",
      "title": "transition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/transition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adjustment-and-Effects-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation"
      ],
      "title": "Adjustment and Effects Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adjustment-and-Effects-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation"
              ],
              "title": "Adjustment and Effects Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/filter-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/filter-audio"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
