{
  "abstract": [
    {
      "text": "Reference a video-format definition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "title": "format"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this element to reference one of the video formats listed under ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/predefined-video-formats",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " through the ",
              "type": "text"
            },
            {
              "code": "name",
              "type": "codeVoice"
            },
            {
              "text": " attribute, or use it to describe a custom video format using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Format-Element-Attributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For audio only assets, use the ",
              "type": "text"
            },
            {
              "code": "FFFrameRateUndefined",
              "type": "codeVoice"
            },
            {
              "text": " format.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When ",
              "type": "text"
            },
            {
              "code": "Format Element Attributes",
              "type": "codeVoice"
            },
            {
              "text": " exist, they override the predefined format value identified by the ",
              "type": "text"
            },
            {
              "code": "name",
              "type": "codeVoice"
            },
            {
              "text": " attribute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In FCPXML 1.6 and earlier, Final Cut Pro ignores the ",
                  "type": "text"
                },
                {
                  "code": "format",
                  "type": "codeVoice"
                },
                {
                  "text": " element attributes if you specify the name attribute.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Format-Element-Attributes",
          "level": 3,
          "text": "Format Element Attributes",
          "type": "heading"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Attribute",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Description",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "frameDuration",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The frame duration as a time value.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "fieldOrder",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The field order for interlaced (",
                      "type": "text"
                    },
                    {
                      "code": "upper first",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "lower first",
                      "type": "codeVoice"
                    },
                    {
                      "text": "), or progressive video (",
                      "type": "text"
                    },
                    {
                      "code": "progressive",
                      "type": "codeVoice"
                    },
                    {
                      "text": ").",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "width",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The video frame width, in pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "height",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The video frame height, in pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "paspH",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The relative width of a pixel when you encode video with non-square pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "paspV",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The relative height of a pixel when you encode video with non-square pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "colorSpace",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The asset’s color space. For information oh how to decribe a color space, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Describing-a-Color-Space",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "projection",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The projection type to display a project or media. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " Valid values are: ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "none",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for a traditional project or media  ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "equirectangular",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "cubic",
                      "type": "codeVoice"
                    },
                    {
                      "text": " for a 360 project or media ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "fisheye",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "back-to-back fisheye",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "code": "stereoscopic",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The type of stereoscopic mode. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " The valide values are: ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "mono",
                      "type": "codeVoice"
                    },
                    {
                      "text": "  ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "side by side",
                      "type": "codeVoice"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "over under",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "anchor": "Describing-a-Color-Space",
          "level": 3,
          "text": "Describing a Color Space",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can describe a color space in terms of its components (color primaries, transfer function, and YCbCr matrix). Color space enocdes each component as an integer value and combines it in a triplet with a hyphen (-) as the delimiter.  For example, 1-1-1 represents the standard Rec. 709 color profile, and 9-1-9 is the standard Rec. 2020 color profile in SDR with the traditional Rec. 709 transfer function. For more information on specific encoded values, see ISO/IEC 23001-8.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the color space triplets syntax to specify the ",
              "type": "text"
            },
            {
              "code": "colorSpace",
              "type": "codeVoice"
            },
            {
              "text": " attribute of the ",
              "type": "text"
            },
            {
              "code": "format",
              "type": "codeVoice"
            },
            {
              "text": " element and the ",
              "type": "text"
            },
            {
              "code": "colorSpaceOverride",
              "type": "codeVoice"
            },
            {
              "text": " attribute of the ",
              "type": "text"
            },
            {
              "code": "asset",
              "type": "codeVoice"
            },
            {
              "text": " element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When Final Cut Pro exports FCPXML, it appends the name of the color space in parentheses to the triplet representation for well-known color spaces. For example 1-1-1 (Rec. 709) or 9-1-9 (Rec. 2020). On import, Final Cut Pro only uses the triplet and ignores the name within the parentheses.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The color space of a project or a multicam sequence can be one of those listed in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset#Well-Known-Color-Space-Triplets",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You cannot represemt still image color spaces in terms of components, so the triplet syntax isn’t valid. Instead, use one of the following values for the ",
              "type": "text"
            },
            {
              "code": "colorSpaceOverride",
              "type": "codeVoice"
            },
            {
              "text": " attribute:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "sRGB IEC61966-2.1",
                      "type": "codeVoice"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "Adobe RGB (1998",
                      "type": "codeVoice"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "FCPXML 1.7 added enhanced support for project and media color space and added support for HDR library processing mode.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset": {
      "abstract": [
        {
          "text": "Define file-based media managed in a Final Cut Pro library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "asset",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset#Well-Known-Color-Space-Triplets": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset#Well-Known-Color-Space-Triplets",
      "kind": "section",
      "title": "Well-Known Color Space Triplets",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset#Well-Known-Color-Space-Triplets"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect": {
      "abstract": [
        {
          "text": "Reference visual, audio, or custom effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
      "kind": "article",
      "role": "collectionGroup",
      "title": "effect",
      "type": "topic",
      "url": "/documentation/professional-video-applications/effect"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Describing-a-Color-Space": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Describing-a-Color-Space",
      "kind": "section",
      "title": "Describing a Color Space",
      "type": "topic",
      "url": "/documentation/professional-video-applications/format#Describing-a-Color-Space"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Format-Element-Attributes": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format#Format-Element-Attributes",
      "kind": "section",
      "title": "Format Element Attributes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/format#Format-Element-Attributes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/id": {
      "abstract": [
        {
          "text": "Specifies a local identifier to use within the FCPXML document.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/id",
      "kind": "article",
      "role": "article",
      "title": "id",
      "type": "topic",
      "url": "/documentation/professional-video-applications/id"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator": {
      "abstract": [
        {
          "text": "Describe a URL-based resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
      "kind": "article",
      "role": "article",
      "title": "locator",
      "type": "topic",
      "url": "/documentation/professional-video-applications/locator"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media": {
      "abstract": [
        {
          "text": "Describe a compound clip or a multi-camera media definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/name": {
      "abstract": [
        {
          "text": "Specifies the name of the resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/name",
      "kind": "article",
      "role": "article",
      "title": "name",
      "type": "topic",
      "url": "/documentation/professional-video-applications/name"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker": {
      "abstract": [
        {
          "text": "Describe a tracked object such as a face or other moving object in a video clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
      "kind": "article",
      "role": "article",
      "title": "object-tracker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/object-tracker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/predefined-video-formats": {
      "abstract": [
        {
          "text": "Valid values for video formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/predefined-video-formats",
      "kind": "article",
      "role": "article",
      "title": "Predefined Video Formats",
      "type": "topic",
      "url": "/documentation/professional-video-applications/predefined-video-formats"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape": {
      "abstract": [
        {
          "text": "Define a shape that the object-tracker uses to match the movement of an object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape",
      "kind": "article",
      "role": "article",
      "title": "tracking-shape",
      "type": "topic",
      "url": "/documentation/professional-video-applications/tracking-shape"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shared-Resources-and-Reference-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
      ],
      "title": "Shared Resources and Reference Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Predefined-Video-Formats",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/predefined-video-formats"
      ],
      "title": "Predefined Video Formats"
    },
    {
      "anchor": "Resource-Element-Attributes",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/id",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/name"
      ],
      "title": "Resource Element Attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Predefined-Video-Formats",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/predefined-video-formats"
              ],
              "title": "Predefined Video Formats"
            },
            {
              "anchor": "Resource-Element-Attributes",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/id",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/name"
              ],
              "title": "Resource Element Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shared-Resources-and-Reference-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
              ],
              "title": "Shared Resources and Reference Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/format"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/format"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
