{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "FxPlug macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitKeyframe": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FxInitKeyframe"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitKeyframe",
      "kind": "symbol",
      "role": "symbol",
      "title": "FxInitKeyframe",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxinitkeyframe"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitLight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "FxInitLight"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitLight",
      "kind": "symbol",
      "role": "symbol",
      "title": "FxInitLight",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxinitlight"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_EXPANDED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kFxParameterFlag_EXPANDED"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_EXPANDED",
      "kind": "symbol",
      "role": "symbol",
      "title": "kFxParameterFlag_EXPANDED",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxparameterflag_expanded"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitKeyframe",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxInitLight",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxParameterFlag_EXPANDED"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/fxplug-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/fxplug-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
