{
  "abstract": [
    {
      "text": "An annotation that applies a keyword to a range of time.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "keyword"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker": {
      "abstract": [
        {
          "text": "An annotation that indicates the result of scene analysis to determine the number of people present and the shot and stabilization types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
      "kind": "article",
      "role": "article",
      "title": "analysis-marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/analysis-marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker": {
      "abstract": [
        {
          "text": "An annotation that applies to a range of time and indicates a chapter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
      "kind": "article",
      "role": "article",
      "title": "chapter-marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/chapter-marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker": {
      "abstract": [
        {
          "text": "An annotation, with an optional to-do flag, that applies a text marker to a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
      "kind": "article",
      "role": "article",
      "title": "marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note": {
      "abstract": [
        {
          "text": "Define descriptive notes that appliy to an entire element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note",
      "kind": "article",
      "role": "article",
      "title": "note",
      "type": "topic",
      "url": "/documentation/professional-video-applications/note"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating": {
      "abstract": [
        {
          "text": "A rating annotation, such as favorite or reject, that applies to a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
      "kind": "article",
      "role": "article",
      "title": "rating",
      "type": "topic",
      "url": "/documentation/professional-video-applications/rating"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Annotation-and-Note-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note"
      ],
      "title": "Annotation and Note Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Annotation-and-Note-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note"
              ],
              "title": "Annotation and Note Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/keyword"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/keyword"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
