{
  "abstract": [
    {
      "text": "Describe a URL-based resource.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "locator"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "locator",
              "type": "codeVoice"
            },
            {
              "text": " element to describe the location of data files associated with another FCPXML element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Locator-Element-Attributes",
          "level": 3,
          "text": "Locator Element Attributes",
          "type": "heading"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Specifies a local identifier that you use within the FCPXML document.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "id",
                    "type": "codeVoice"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A string that specifies the location of the resource as an absolute or relative URL. For details about the URL, see the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media-rep#Location-of-Media-Files",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " section of ",
                        "type": "text"
                      },
                      {
                        "code": "media-rep",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "code": "url",
                    "type": "codeVoice"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset": {
      "abstract": [
        {
          "text": "Define file-based media managed in a Final Cut Pro library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "asset",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect": {
      "abstract": [
        {
          "text": "Reference visual, audio, or custom effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
      "kind": "article",
      "role": "collectionGroup",
      "title": "effect",
      "type": "topic",
      "url": "/documentation/professional-video-applications/effect"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format": {
      "abstract": [
        {
          "text": "Reference a video-format definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "format",
      "type": "topic",
      "url": "/documentation/professional-video-applications/format"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media": {
      "abstract": [
        {
          "text": "Describe a compound clip or a multi-camera media definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media-rep#Location-of-Media-Files": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media-rep#Location-of-Media-Files",
      "kind": "section",
      "title": "Location of Media Files",
      "type": "topic",
      "url": "/documentation/professional-video-applications/media-rep#Location-of-Media-Files"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker": {
      "abstract": [
        {
          "text": "Describe a tracked object such as a face or other moving object in a video clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
      "kind": "article",
      "role": "article",
      "title": "object-tracker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/object-tracker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape": {
      "abstract": [
        {
          "text": "Define a shape that the object-tracker uses to match the movement of an object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape",
      "kind": "article",
      "role": "article",
      "title": "tracking-shape",
      "type": "topic",
      "url": "/documentation/professional-video-applications/tracking-shape"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shared-Resources-and-Reference-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
      ],
      "title": "Shared Resources and Reference Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shared-Resources-and-Reference-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
              ],
              "title": "Shared Resources and Reference Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/locator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/locator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
