{
  "abstract": [
    {
      "text": "Describe a tracked object such as a face or other moving object in a video clip.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/object-tracker"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "object-tracker"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Users can track moving objects in video clips to match their movement to a clip, title, logo, generator, or a still image, by using the object-tracker feature in Final Cut Pro. They can also track the shape mask of a video effect, for example a blur, highlight, or color effect, to a moving object in a video clip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The object-tracking feature records the movement of an object, for example a reference point, person, or animal, in a video clip and then applies that recorded movement data to another item, which might be a video effect, title, generator, or another video or still-image clip. The result is an animation in which the item ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "follows",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " or moves in conjunction with, the tracked object in the original clip. For example, using the object-tracking technique users can:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add a blurry circle to a person’s face to help preserve anonymity",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add a glow effect to the image of jet engines on an airplane streaking through the sky",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the names of swimmers to their moving bodies as they compete in a swim meet",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Each object-tracker element consists of one or more tracking shapes. Describe the tracking shapes by using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset": {
      "abstract": [
        {
          "text": "Define file-based media managed in a Final Cut Pro library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
      "kind": "article",
      "role": "collectionGroup",
      "title": "asset",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect": {
      "abstract": [
        {
          "text": "Reference visual, audio, or custom effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
      "kind": "article",
      "role": "collectionGroup",
      "title": "effect",
      "type": "topic",
      "url": "/documentation/professional-video-applications/effect"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format": {
      "abstract": [
        {
          "text": "Reference a video-format definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
      "kind": "article",
      "role": "collectionGroup",
      "title": "format",
      "type": "topic",
      "url": "/documentation/professional-video-applications/format"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator": {
      "abstract": [
        {
          "text": "Describe a URL-based resource.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
      "kind": "article",
      "role": "article",
      "title": "locator",
      "type": "topic",
      "url": "/documentation/professional-video-applications/locator"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media": {
      "abstract": [
        {
          "text": "Describe a compound clip or a multi-camera media definition.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
      "kind": "article",
      "role": "collectionGroup",
      "title": "media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape": {
      "abstract": [
        {
          "text": "Define a shape that the object-tracker uses to match the movement of an object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape",
      "kind": "article",
      "role": "article",
      "title": "tracking-shape",
      "type": "topic",
      "url": "/documentation/professional-video-applications/tracking-shape"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Shared-Resources-and-Reference-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
      ],
      "title": "Shared Resources and Reference Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Shared-Resources-and-Reference-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/media",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/format",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/effect",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/locator",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/tracking-shape"
              ],
              "title": "Shared Resources and Reference Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/object-tracker"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/object-tracker"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
