{
  "abstract": [
    {
      "text": "Maintain consistent rendering at all resolutions and aspect ratios by using pixel transforms.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Optimizing FxPlug plug-ins"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "FxPlug plug-ins provide users a real-time rendering experience that’s measured in frames produced per second. Plug-ins that work with large inputs can optimize their performance by rendering only a subset of pixels as determined using ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "pixel transforms",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Pixel transforms are 4x4 matrices that are created by the host app to contain ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "transformation",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " information about the media the plug-in has been applied to. Transformations include translation, rotation, scale, and foreshortening (skewing the image to make closer objects appear larger).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Understand-pixel-transforms",
          "level": 3,
          "text": "Understand pixel transforms",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The host application creates the 4x4 matrices used in pixel transforms. These matrices contain information that must be taken into account in order to render correctly and efficiently.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For example, if the host application asks your plug-in to render a small thumbnail preview, the scaling information for that request is contained in the pixel transform matrices. Likewise, when a user selects Dynamic Resolution from the viewer options in Motion, or Better Performance in Final Cut Pro, that information is also included in the pixel transform matrices. A pixel transform contains either full or partial information on how the input or output image will be distorted before being composited into the scene. Take a look at this example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3906065",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When a layer is parallel to the film-back of the virtual camera that’s recording a scene, you might see all of its pixels as shown above.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The most efficient texture for a generator to produce is one that corresponds exactly to the pixels needed in the final composition. Assuming that your plug-in supports pixel transforms, a good one to use is the one that projects from the layer’s object space to the scene’s output space. When the user rotates the layer around the y-axis and translates it back on the z-axis, it becomes shorter along its width, as shown below. Rotating the layer in this way lets your plug-in process fewer pixels, because fewer pixels are needed to render the final composition.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3906063",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "A pixel transform doesn’t contain the same information as a full transformation matrix, which also shows a layer’s position in the scene. To get complete information about the 3D environment, including camera and object transforms, use the ",
                  "type": "text"
                },
                {
                  "code": "Fx3DAPI_v4",
                  "type": "codeVoice"
                },
                {
                  "text": " object that the host application provides.****",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Support-pixel-transforms-in-your-plug-in",
          "level": 3,
          "text": "Support pixel transforms in your plug-in",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each plug-in chooses what information it needs to know about the image through pixel transforms, and lets the host know which types of transforms it will deal with. It does this by including the associated key-value pair in the dictionary it returns from its properties method. The key is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the value tells the host application what types of transformations a plug-in is capable of working with. (If your plug-in doesn’t include this key, the host application assumes that your plug-in supports scale transforms).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "This plug-in supports non-uniform scaling only.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Scale",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "This plug-in supports both non-uniform scaling and translation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_ScaleTranslate",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            },
            {
              "definition": {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "This plug-in supports any affine or full-perspective transform.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ]
              },
              "term": {
                "inlineContent": [
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Full",
                    "isActive": true,
                    "type": "reference"
                  }
                ]
              }
            }
          ],
          "type": "termList"
        },
        {
          "inlineContent": [
            {
              "text": "Your properties method can also set a Boolean on another key, ",
              "type": "text"
            },
            {
              "code": "kFxPropertyKey_PixelIndependent",
              "type": "codeVoice"
            },
            {
              "text": ". If a plug-in is pixel independent, each output pixel relies only on a single input pixel, and the location of each input pixel doesn’t matter. An example of this would be a color filter, which applies an adjustment at every pixel, regardless of position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows a typical entry in the dictionary returned by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect/properties(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func properties(_ properties: AutoreleasingUnsafeMutablePointer<NSDictionary>?) throws {",
                    "        let swiftProps = [",
                    "            kFxPropertyKey_MayRemapTime : NSNumber(booleanLiteral: false),",
                    "            kFxPropertyKey_PixelTransformSupport : NSNumber(value: kFxPixelTransform_ScaleTranslate),",
                    "            kFxPropertyKey_VariesWhenParamsAreStatic: NSNumber(booleanLiteral: false)",
                    "        ]",
                    "        let props = NSDictionary(dictionary: swiftProps)",
                    "        properties?.pointee = props",
                    "    }"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (BOOL)properties:(NSDictionary * _Nonnull * _Nullable)properties",
                    "             error:(NSError * _Nullable * _Nullable)error",
                    "{",
                    "    *properties = @{",
                    "                    kFxPropertyKey_MayRemapTime : @NO,",
                    "                    kFxPropertyKey_PixelTransformSupport :",
                    "                    [NSNumber numberWithInt:kFxPixelTransform_ScaleTranslate]",
                    "                    }; ",
                    "    return YES;",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "anchor": "Apply-pixel-transforms",
          "level": 3,
          "text": "Apply pixel transforms",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After informing the host application which types of transforms your plug-in supports, apply the appropriate pixel transforms using these steps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Ask the input image for its pixel transform or its inverse pixel transform matrices (or both). Use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class methods ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/pixelTransform",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/inversePixelTransform",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to convert coordinate systems. If you want to convert coordinates into full-sized, square pixel coordinates, use ",
                      "type": "text"
                    },
                    {
                      "code": "inversePixelTransform",
                      "type": "codeVoice"
                    },
                    {
                      "text": ". If you want to convert from full-sized, square pixel coordinates to actual image pixels, use ",
                      "type": "text"
                    },
                    {
                      "code": "pixelTransform",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the specified transformation matrices in your plug-in’s fragment shader.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Pass the current coordinate for the input texture through the inverse pixel transform. The result is a coordinate that represents the current pixel if the image were in square pixels, not transformed, at its full resolution, with the origin in the center of the image. This coordinate system is sometimes referred to as ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "document space",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Calculate for distortions, convolution kernels, and so on using the coordinate derived in the previous step. To distort pixels along a sine wave or push pixels away from a particular point in the image, work in square pixels at full resolution to get correct results for all types of footage in all viewing conditions. Likewise, to sample multiple places in the input image to produce a blur or other convolution kernel, space the samples appropriately, regardless of the pixel aspect ratio, use of fields, or viewing resolution.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Convert the values back into the space that the image’s pixels are actually in. If your plug-in is a generator, you have no input image, so skip this step. Pass the coordinates through the forward pixel transform to get the coordinate from which you sampled the input image. This space is usually referred to as ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "pixel space",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can now safely sample from the image and know that you’ll get the required result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Compare-pixel-transform-examples",
          "level": 3,
          "text": "Compare pixel transform examples",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you make proper use of pixel transforms in your rendering code, you don’t need special-case code for thumbnails or proxy resolution, and you don’t need to scale any of your parameters: your rendering will work for all of these situations. The illustrations below show common pixel transforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a user creates a square-pixel project and applies project-sized footage to the canvas (a typical case) the pixel transform is the identity matrix, as is the inverse pixel transform, as shown in the following illustration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3906064",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a user then sets the canvas viewing resolution to half-resolution, that change is reflected in the pixel transform, as shown in the following illustration:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3906062",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the user applies a filter to footage that has a pixel aspect ratio of 1.33, that change is reflected in the pixel transform, as shown in the final illustration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3906061",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/communicating-with-the-plug-in-state": {
      "abstract": [
        {
          "text": "Prepare the necessary information, such as parameter values, for your FxPlug plug-in to render.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/communicating-with-the-plug-in-state",
      "kind": "article",
      "role": "article",
      "title": "Communicating with the plug-in state",
      "type": "topic",
      "url": "/documentation/professional-video-applications/communicating-with-the-plug-in-state"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rendering-in-fxplug": {
      "abstract": [
        {
          "text": "Use Metal or other frameworks to render images with your FxPlug plug-in.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rendering-in-fxplug",
      "kind": "article",
      "role": "article",
      "title": "Rendering in FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/rendering-in-fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/working-with-tiled-images": {
      "abstract": [
        {
          "text": "Render only the necessary tiles of an image in your FxPlug plug-in to improve efficiency.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/working-with-tiled-images",
      "kind": "article",
      "role": "article",
      "title": "Working with tiled images",
      "type": "topic",
      "url": "/documentation/professional-video-applications/working-with-tiled-images"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile": {
      "abstract": [
        {
          "text": "An image tile object that is passed between an out-of-process FxPlug plug-in and a host application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageTile"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageTile"
        }
      ],
      "role": "symbol",
      "title": "FxImageTile",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagetile"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/inversePixelTransform": {
      "abstract": [
        {
          "text": "The inverse of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/pixelTransform",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inversePixelTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxMatrix44",
          "text": "FxMatrix44"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/inversePixelTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inversePixelTransform"
        }
      ],
      "role": "symbol",
      "title": "inversePixelTransform",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagetile/inversepixeltransform"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/pixelTransform": {
      "abstract": [
        {
          "text": "The transformation between pixel units and idealized, 100% scale, square pixel image units.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pixelTransform"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxMatrix44",
          "text": "FxMatrix44"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageTile/pixelTransform",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pixelTransform"
        }
      ],
      "role": "symbol",
      "title": "pixelTransform",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximagetile/pixeltransform"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect": {
      "abstract": [
        {
          "text": "The designated initializer for your plug-in for rendering only certain portions of the plug-in’s output, referred to as tiles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxTileableEffect"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxTileableEffect"
        }
      ],
      "role": "symbol",
      "title": "FxTileableEffect",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtileableeffect"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect/properties(_:)": {
      "abstract": [
        {
          "text": "Tells the host application about what the plug-in needs and supports, such as whether it renders in a gamma-corrected color space or a linear one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "properties"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SA",
          "text": "AutoreleasingUnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDictionary",
          "text": "NSDictionary"
        },
        {
          "kind": "text",
          "text": ">?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect/properties(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "properties:error:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "properties(_:)",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxtileableeffect/properties(_:)"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Full": {
      "abstract": [
        {
          "text": "Handles full perspective transformation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_Full"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Full",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_Full"
        }
      ],
      "role": "symbol",
      "title": "kFxPixelTransform_Full",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpixeltransform_full"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Scale": {
      "abstract": [
        {
          "text": "Handles only (non-uniform) scaling - this is the minimum required.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_Scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_Scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_Scale"
        }
      ],
      "role": "symbol",
      "title": "kFxPixelTransform_Scale",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpixeltransform_scale"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_ScaleTranslate": {
      "abstract": [
        {
          "text": "Handles non-uniform scaling, and arbitrary translation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_ScaleTranslate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPixelTransform_ScaleTranslate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPixelTransform_ScaleTranslate"
        }
      ],
      "role": "symbol",
      "title": "kFxPixelTransform_ScaleTranslate",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpixeltransform_scaletranslate"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport": {
      "abstract": [
        {
          "text": "A key in the ",
          "type": "text"
        },
        {
          "code": "properties",
          "type": "codeVoice"
        },
        {
          "text": " dictionary in the ",
          "type": "text"
        },
        {
          "code": "FXBaseEffect",
          "type": "codeVoice"
        },
        {
          "text": " Class that corresponds to an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " containing one of the ",
          "type": "text"
        },
        {
          "code": "FxImage",
          "type": "codeVoice"
        },
        {
          "text": " values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/kFxPropertyKey_PixelTransformSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFxPropertyKey_PixelTransformSupport"
        }
      ],
      "role": "symbol",
      "title": "kFxPropertyKey_PixelTransformSupport",
      "type": "topic",
      "url": "/documentation/professional_video_applications/kfxpropertykey_pixeltransformsupport"
    },
    "media-3906061": {
      "alt": "Matrix Example 3: Pixel aspect of 1.33 transform and inverse pixel transform matrices",
      "identifier": "media-3906061",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9847fbc42da0b9e06cf72836e6e07683/media-3906061@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/0aeeda4cf43d882ad19dd4e044437ab3/media-3906061~dark@2x.png"
        }
      ]
    },
    "media-3906062": {
      "alt": "Matrix Example 2: Half-size pixel transform and inverse pixel transform matrices",
      "identifier": "media-3906062",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bf40fa8b2318c3a5dd0d44bf1802ea1e/media-3906062@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bca14e99bd0fa877c926d32bfe016320/media-3906062~dark@2x.png"
        }
      ]
    },
    "media-3906063": {
      "alt": "The checkerboard layer rotated around the y axis",
      "identifier": "media-3906063",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cd4dbe78d94805d29396c7e145322145/media-3906063@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cd4dbe78d94805d29396c7e145322145/media-3906063~dark@2x.png"
        }
      ]
    },
    "media-3906064": {
      "alt": "Matrix Example 1: 1:1 pixel transform and inverse pixel transform matrices",
      "identifier": "media-3906064",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9233cb7be9147d0f32ea2f1b59314c0f/media-3906064@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ab4bafd9b29db5fcd86a23042d30f185/media-3906064~dark@2x.png"
        }
      ]
    },
    "media-3906065": {
      "alt": "A checkerboard layer parallel to the film-back of the virtual camera",
      "identifier": "media-3906065",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5fd4385317982b17109751724b7dee0b/media-3906065@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5fd4385317982b17109751724b7dee0b/media-3906065~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Rendering",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rendering-in-fxplug",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/communicating-with-the-plug-in-state",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/working-with-tiled-images",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect"
      ],
      "title": "Rendering"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Rendering",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rendering-in-fxplug",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/communicating-with-the-plug-in-state",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/working-with-tiled-images",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxTileableEffect"
              ],
              "title": "Rendering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_Scale/title",
          "value": "kFxPixelTransform_Scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_Scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPixelTransform_Scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_ScaleTranslate/title",
          "value": "kFxPixelTransform_ScaleTranslate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_ScaleTranslate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPixelTransform_ScaleTranslate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile~1inversePixelTransform/title",
          "value": "inversePixelTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile~1inversePixelTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inversePixelTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTileableEffect/title",
          "value": "FxTileableEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTileableEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTileableEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTileableEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxTileableEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile/title",
          "value": "FxImageTile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageTile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageTile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile~1pixelTransform/title",
          "value": "pixelTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageTile~1pixelTransform/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pixelTransform"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/title",
          "value": "kFxPropertyKey_PixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPropertyKey_PixelTransformSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPropertyKey_PixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_Full/title",
          "value": "kFxPixelTransform_Full"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1kFxPixelTransform_Full/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFxPixelTransform_Full"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTileableEffect~1properties(_:)/title",
          "value": "properties:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxTileableEffect~1properties(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "properties:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/optimizing-fxplug-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/optimizing-fxplug-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
