{
  "abstract": [
    {
      "text": "Add a plug-in to a Motion effect template to use in Final Cut Pro.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Preparing plug-ins for use in Final Cut Pro"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To make FxPlug plug-ins work in Final Cut Pro, you need to create a Final Cut Effect within Motion that rigs and/or publishes your FxPlug parameters. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/kb/PH16018",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in Motion Help and ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/kb/PH16033",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Final Cut Pro for iPad doesn’t support FxPlug 4 plug-ins.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Effects in Final Cut Pro include Generators, Transitions, and Filters. These Final Cut Pro effects are really just Motion documents, which can contain whatever you choose. This is useful because most users of Final Cut Pro want to solve specific tasks, rather than to apply particular effects with dozens of parameters. Advanced users who need more control will be able to either open your Final Cut Effect in Motion and edit it themselves, or create their own Final Cut Pro Effects within Motion for their specific task.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "In general, plug-in users don’t need control over every aspect of a plug-in to get the effect; effects that offer too many parameters to the user can be overwhelming.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "To prepare your plug-in you use Motion to create a Final Cut Effect, Generator, Transition, or Title. To do that, you’ll need to create a Motion Effect, apply your filter or generator, and publish its parameters in a rig. A rig consolidates your plug-in’s parameters, which you can then publish in your effect. This makes it easier for Final Cut Pro users to apply the effects of your plug-in to their projects. (For information about creating rigs for your plug-in, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/kb/PH16018",
              "isActive": true,
              "overridingTitle": "Rigging overview",
              "overridingTitleInlineContent": [
                {
                  "text": "Rigging overview",
                  "type": "text"
                }
              ],
              "type": "reference"
            },
            {
              "text": " in Motion Help).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-basic-Final-Cut-Pro-effect",
          "level": 3,
          "text": "Create a basic Final Cut Pro effect",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The following steps outline the workflow for creating a basic Final Cut Pro Effect in Motion. For details about any step or about using Motion, see ",
              "type": "text"
            },
            {
              "identifier": "https://help.apple.com/motion/mac/5.4.2/#/motn8d17a294",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Launch Motion and select the Final Cut Pro Effect template from the Project Browser. This creates a new Motion project with a placeholder layer called Effect Source.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Apply the Glow filter. You can do this by dragging the effect out of the filters library and onto the Effect Source placeholder. Alternatively, you can select the Effect Source placeholder layer, click Filters and choose Glow, and finally click Apply. Save your effect.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Open the filter’s Inspector. Select the newly applied Glow plug-in and open the Motion inspector to reveal the plug-in’s parameters.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Build and name a rig to connect the controls for the Radius parameter. Click the popup-menu indicator to the right of the Radius slider to see the options for the Radius parameter. Choose Add To Rig > Create New Rig > Add To New Slider. Motion creates a new Rig group in the layer list with the new layer (named Slider) selected. Change the name of the slider to Glowiness. Finally, choose Publish from the slider parameter’s option menu.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Connect the rig to the Opacity parameter. In the layer list, select the Glow filter to see its parameters in the Inspector. Parameters with a joystick icon indicate they’re controlled with a rig—notice that the Radius parameter shows this icon. Now, add another parameter to this rig. Click the pop-up menu indicator to the right of the Opacity slider and choose Add To Rig > Rig > Add To Glowiness.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the low end of parameters for the Glowiness effect. Select the rig named Glowiness in the layer list. In the inspector, you’ll see a slider that controls the parameter levels. On this slider, click the circle at the left end. Edit the levels for when Glowiness is set to zero. There are two parameters under this rig’s control: Opacity, and Radius. Set the Effect Source.Opacity and Effect Source.Radius sliders to 0. This sets the Opacity and Radius parameters to 0 when the rigged slider is set to 0.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the high end of parameters for the Glowiness effect. Now edit the right end of the rig. Begin again by clicking the circle at the right end of the Glowiness parameter. Next, set the Effect Source.Opacity and Effect Source.Radius sliders to their maximum values. You now have a rigged parameter. Drag the Glowiness parameter and verify that the underlying parameters change as well.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you apply this plug-in in Final Cut Pro, users of the effect see a single slider (called Glowiness) which they can use to control both the Radius and Opacity parameters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Publish-the-parameters-for-your-plug-in",
          "level": 3,
          "text": "Publish the parameters for your plug-in",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to give your users direct access so they can control every aspect of a parameter in your plug-in, publish each parameter in Motion directly, without a rig. Unlike rigging a parameter, publishing a parameter gives users individual control over a single parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create the Threshold parameter for direct manipulation:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Show the filter’s parameters in the inspector. In the layer list, select the Glow effect and be sure the Inspector tab is visible.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Publish the Threshold parameter. In the inspector, click the Threshold parameter’s pop- up menu, and choose Publish.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Save the effect. When you attempt to save a Final Cut Pro Effect, Transition, Generator, or Title, you’re presented with some options. In addition to a name, you can assign the effect to a category, which is where it appears in the Final Cut Pro Effect browser. You can also add it to a theme. After you have a name and category, click the Publish button.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Your effect is immediately available in Final Cut Pro.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-temporal-effects-and-project-loop-markers",
          "level": 3,
          "text": "Set temporal effects and project loop markers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If your Motion Template doesn’t create a temporal effect (a timing effect such as retiming, temporal blur, or echo/feedback), set the Project Loop End marker in the template. If you don’t include such a marker, your effects will rerender after a blade, trim, or edit in Final Cut Pro. For more about Project Loop End markers, see ",
              "type": "text"
            },
            {
              "identifier": "https://support.apple.com/kb/PH16059",
              "isActive": true,
              "type": "reference"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Deprecate-a-Motion-template",
          "level": 3,
          "text": "Deprecate a Motion template",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you update an existing plug-in, you may also need to deprecate the older version of the Motion template. A deprecated template is considered obsolete and does not appear in the effects browser in Motion, but it will still be applied in projects that previously used it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The second bit of the ",
              "type": "text"
            },
            {
              "code": "<flags>",
              "type": "codeVoice"
            },
            {
              "text": " value in the Motion XML for a template indicates whether or not the template has been deprecated. A ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " value for the second bit indicates that the template has not been deprecated; a value of ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": " indicates that it has been deprecated.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To deprecate a template, open the Motion XML document and take the current value of the ",
              "type": "text"
            },
            {
              "code": "<flags>",
              "type": "codeVoice"
            },
            {
              "text": " element (a child of the ",
              "type": "text"
            },
            {
              "code": "<template>",
              "type": "codeVoice"
            },
            {
              "text": " element) and perform a bitwise ",
              "type": "text"
            },
            {
              "code": "OR",
              "type": "codeVoice"
            },
            {
              "text": " operation with the value ",
              "type": "text"
            },
            {
              "code": "0x2",
              "type": "codeVoice"
            },
            {
              "text": ". For example, if the value of ",
              "type": "text"
            },
            {
              "code": "<flags>",
              "type": "codeVoice"
            },
            {
              "text": " was previously ",
              "type": "text"
            },
            {
              "code": "1",
              "type": "codeVoice"
            },
            {
              "text": ", it would now be ",
              "type": "text"
            },
            {
              "code": "3",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<template>",
            "    <flags>3</flags>",
            "</template>"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If a project isn’t a Designed for 4K project, then the ",
                  "type": "text"
                },
                {
                  "code": "<template>",
                  "type": "codeVoice"
                },
                {
                  "text": " element won’t exist in the XML document. To deprecate this type of project, manually add the ",
                  "type": "text"
                },
                {
                  "code": "<template>",
                  "type": "codeVoice"
                },
                {
                  "text": " element and set ",
                  "type": "text"
                },
                {
                  "code": "<flags>",
                  "type": "codeVoice"
                },
                {
                  "text": " to ",
                  "type": "text"
                },
                {
                  "code": "2",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in": {
      "abstract": [
        {
          "text": "Give users confidence in your FxPlug plug-in by enabling notarization.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in",
      "kind": "article",
      "role": "article",
      "title": "Notarizing your FxPlug plug-in",
      "type": "topic",
      "url": "/documentation/professional-video-applications/notarizing-your-fxplug-plug-in"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/testing-fxplug-plug-ins": {
      "abstract": [
        {
          "text": "Test and debug FxPlug plug-ins using a variety of methods.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/testing-fxplug-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Testing FxPlug plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/testing-fxplug-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://help.apple.com/motion/mac/5.4.2/#/motn8d17a294": {
      "identifier": "https://help.apple.com/motion/mac/5.4.2/#/motn8d17a294",
      "title": "Motion Help",
      "titleInlineContent": [
        {
          "text": "Motion Help",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/motion/mac/5.4.2/#/motn8d17a294"
    },
    "https://support.apple.com/kb/PH16018": {
      "identifier": "https://support.apple.com/kb/PH16018",
      "title": "Rigging overview",
      "titleInlineContent": [
        {
          "text": "Rigging overview",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/kb/PH16018"
    },
    "https://support.apple.com/kb/PH16033": {
      "identifier": "https://support.apple.com/kb/PH16033",
      "title": "Final Cut Pro Templates Overview",
      "titleInlineContent": [
        {
          "text": "Final Cut Pro Templates Overview",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/kb/PH16033"
    },
    "https://support.apple.com/kb/PH16059": {
      "identifier": "https://support.apple.com/kb/PH16059",
      "title": "What are template markers?",
      "titleInlineContent": [
        {
          "text": "What are template markers?",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/kb/PH16059"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-and-deployment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/testing-fxplug-plug-ins",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in"
      ],
      "title": "Testing and deployment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-and-deployment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/testing-fxplug-plug-ins",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in"
              ],
              "title": "Testing and deployment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/preparing-plug-ins-for-use-in-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/preparing-plug-ins-for-use-in-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
