{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Professional Video Applications Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Constants",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-constants"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Enumerations",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-enumerations"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Protocols",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-protocols"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin": {
      "abstract": [
        {
          "text": "These constants define the orientation of an image’s coordinate system. Images in Motion have a bottom-left origin. Images in Final Cut have a top-left origin.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxImageOrigin"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxImageOrigin"
        }
      ],
      "role": "symbol",
      "title": "FxImageOrigin",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fximageorigin"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathStyle": {
      "abstract": [
        {
          "text": "The style of the path, which is linear, bezier, or b-spline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxPathStyle"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxPathStyle"
        }
      ],
      "role": "symbol",
      "title": "FxPathStyle",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxpathstyle"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport": {
      "abstract": [
        {
          "text": "Constants that define the support for pixel transforms.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxPixelTransformSupport"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxPixelTransformSupport"
        }
      ],
      "role": "symbol",
      "title": "FxPixelTransformSupport",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxpixeltransformsupport"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathStyle",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxImageOrigin",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPathStyle",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxPixelTransformSupport"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathStyle/title",
          "value": "FxPathStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPathStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPathStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/title",
          "value": "FxImageOrigin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxImageOrigin/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxImageOrigin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/title",
          "value": "FxPixelTransformSupport"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPixelTransformSupport"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxPixelTransformSupport/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxPixelTransformSupport"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/professional-video-applications-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/professional-video-applications-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
