{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-protocols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Professional Video Applications Protocols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Constants",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-constants"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Data Types",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-data-types"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Professional Video Applications Enumerations",
      "type": "topic",
      "url": "/documentation/professional-video-applications/professional-video-applications-enumerations"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxXPCProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxXPCProtocol"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxXPCProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxXPCProtocol"
        }
      ],
      "role": "symbol",
      "title": "FxXPCProtocol",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxxpcprotocol"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIAccessing": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PROAPIAccessing"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIAccessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PROAPIAccessing"
        }
      ],
      "role": "symbol",
      "title": "PROAPIAccessing",
      "type": "topic",
      "url": "/documentation/professional_video_applications/proapiaccessing"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIObject": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PROAPIObject"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PROAPIObject"
        }
      ],
      "role": "symbol",
      "title": "PROAPIObject",
      "type": "topic",
      "url": "/documentation/professional_video_applications/proapiobject"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROPlugInRegistering": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PROPlugInRegistering"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROPlugInRegistering",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PROPlugInRegistering"
        }
      ],
      "role": "symbol",
      "title": "PROPlugInRegistering",
      "type": "topic",
      "url": "/documentation/professional_video_applications/propluginregistering"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROXPCProtocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PROXPCProtocol"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROXPCProtocol",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PROXPCProtocol"
        }
      ],
      "role": "symbol",
      "title": "PROXPCProtocol",
      "type": "topic",
      "url": "/documentation/professional_video_applications/proxpcprotocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Protocols",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxXPCProtocol",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIAccessing",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIObject",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROPlugInRegistering",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROXPCProtocol"
      ],
      "title": "Protocols"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Protocols",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxXPCProtocol",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIAccessing",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROAPIObject",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROPlugInRegistering",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/PROXPCProtocol"
              ],
              "title": "Protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-enumerations",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-constants",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/professional-video-applications-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIAccessing/title",
          "value": "PROAPIAccessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIAccessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PROAPIAccessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIAccessing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PROAPIAccessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIObject/title",
          "value": "PROAPIObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PROAPIObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROAPIObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PROAPIObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROPlugInRegistering/title",
          "value": "PROPlugInRegistering"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROPlugInRegistering/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PROPlugInRegistering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROPlugInRegistering/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PROPlugInRegistering"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxXPCProtocol/title",
          "value": "FxXPCProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxXPCProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxXPCProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxXPCProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxXPCProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROXPCProtocol/title",
          "value": "PROXPCProtocol"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROXPCProtocol/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PROXPCProtocol"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1PROXPCProtocol/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PROXPCProtocol"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/professional-video-applications-protocols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/professional-video-applications-protocols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
