{
  "abstract": [
    {
      "text": "References a compound clip media.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "ref-clip"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "ref-clip",
              "type": "codeVoice"
            },
            {
              "text": " element to describe a timeline sequence created from a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/compound-clip-media",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The edit uses the entire set of media components in the compound clip media. Specify the timing of the edit through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also use a ",
              "type": "text"
            },
            {
              "code": "ref-clip",
              "type": "codeVoice"
            },
            {
              "text": " element as an immediate child element of an ",
              "type": "text"
            },
            {
              "code": "event",
              "type": "codeVoice"
            },
            {
              "text": " element to represent a browser clip. In this case, use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to specify its format and other attributes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip": {
      "abstract": [
        {
          "text": "References a single media asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
      "kind": "article",
      "role": "article",
      "title": "asset-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio": {
      "abstract": [
        {
          "text": "References audio data from an ",
          "type": "text"
        },
        {
          "code": "asset",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "effect",
          "type": "codeVoice"
        },
        {
          "text": " element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
      "kind": "article",
      "role": "article",
      "title": "audio",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition": {
      "abstract": [
        {
          "text": "Contains one active story element followed by alternative story elements in the audition container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
      "kind": "article",
      "role": "article",
      "title": "audition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip": {
      "abstract": [
        {
          "text": "Represents a basic unit of editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
      "kind": "article",
      "role": "article",
      "title": "clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/compound-clip-media": {
      "abstract": [
        {
          "text": "Group combination of clips as a unit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/compound-clip-media",
      "kind": "article",
      "role": "article",
      "title": "Compound Clip Media",
      "type": "topic",
      "url": "/documentation/professional-video-applications/compound-clip-media"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap": {
      "abstract": [
        {
          "text": "Defines a placeholder element that has no intrinsic audio or video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
      "kind": "article",
      "role": "article",
      "title": "gap",
      "type": "topic",
      "url": "/documentation/professional-video-applications/gap"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip": {
      "abstract": [
        {
          "text": "References a multicam media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
      "kind": "article",
      "role": "article",
      "title": "mc-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/mc-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence": {
      "abstract": [
        {
          "text": "A container that represents the top-level sequence for a Final Cut Pro project or compound clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence",
      "kind": "article",
      "role": "article",
      "title": "sequence",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sequence"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine": {
      "abstract": [
        {
          "text": "Contains elements ordered sequentially in time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
      "kind": "article",
      "role": "article",
      "title": "spine",
      "type": "topic",
      "url": "/documentation/professional-video-applications/spine"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip": {
      "abstract": [
        {
          "text": "Contains a clip with its contained and anchored items synchronized.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
      "kind": "article",
      "role": "article",
      "title": "sync-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sync-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes": {
      "abstract": [
        {
          "text": "Define characteristics of a timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes",
      "kind": "article",
      "role": "article",
      "title": "Timeline Attributes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/timeline-attributes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes": {
      "abstract": [
        {
          "text": "Schedule the element and its contained or anchored items in a timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
      "kind": "article",
      "role": "article",
      "title": "Timing Attributes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/timing-attributes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video": {
      "abstract": [
        {
          "text": "References  video data from an ",
          "type": "text"
        },
        {
          "code": "asset",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "effect",
          "type": "codeVoice"
        },
        {
          "text": " element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
      "kind": "article",
      "role": "article",
      "title": "video",
      "type": "topic",
      "url": "/documentation/professional-video-applications/video"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Story-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
      ],
      "title": "Story Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Story-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
              ],
              "title": "Story Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/ref-clip"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/ref-clip"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
