{
  "abstract": [
    {
      "text": "Manage and streamline the sending of batches of media assets and timeline sequences from your app using Apple events.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Sending Data Programmatically to Final Cut Pro"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Consider using Apple events to help your users manage their workflow if they have many assets to send to Final Cut Pro and generally send all of those assets before starting their work in Final Cut Pro. With Apple event support in your app, your users need fewer clicks to send their media assets, projects, and metadata to Final Cut Pro for editing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To provide a more streamlined process, use the ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event to send an FCPXML document to Final Cut Pro and trigger the process with a button or menu item in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3878514",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-and-Save-an-FCPXML-File",
          "level": 3,
          "text": "Create and Save an FCPXML File",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before your app can use Apple events to send a file to Final Cut Pro, it must create the FCPXML document, and save it as a file with an ",
              "type": "text"
            },
            {
              "code": ".fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " extension. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Consider saving the ",
              "type": "text"
            },
            {
              "code": ".fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " file to a temporary location that your app clears periodically. Once Final Cut Pro processes the FCPXML, it no longer needs the actual ",
              "type": "text"
            },
            {
              "code": ".fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Send-an-FCPXML-File-Using-an-Apple-Event",
          "level": 3,
          "text": "Send an FCPXML File Using an Apple Event",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To communicate your app’s request, create an AppleScript that sends an ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event to Final Cut Pro. This Apple event contains a URL that points to an ",
              "type": "text"
            },
            {
              "code": ".fcpxml",
              "type": "codeVoice"
            },
            {
              "text": " file your app created, and it tells Final Cut Pro to open and process that file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following AppleScript to send an ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event containing the URL to an FCPXML file called ",
              "type": "text"
            },
            {
              "code": "MyEvents.fcpxml",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "tell application \"Final Cut Pro\"",
            "    activate",
            "    open POSIX file \"/Users/JohnDoe/Documents/UberMAM/MyEvents.fcpxml\"",
            "end tell"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following code to execute the AppleScript script created in the previous example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "// the scriptSourceToSend property contains the AppleScript source above",
                    "let script = NSAppleScript(source: scriptSourceToSend)",
                    "var errorInfo: NSDictionary? = nil",
                    "let result = script?.executeAndReturnError(&errorInfo)",
                    "if result == nil { /* handle error */ }"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "// the scriptSourceToSend property contains the AppleScript source above",
                    "NSAppleScript *script = [[NSAppleScript alloc] initWithSource:self.scriptSourceToSend];",
                    "NSDictionary *errorInfo = nil;",
                    "NSAppleEventDescriptor *result = [script executeAndReturnError:&errorInfo];",
                    "if (result == nil) { /* handle error */ }"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "AppleScript is the preferred way to send an FCPXML document to Final Cut Pro using the ",
              "type": "text"
            },
            {
              "code": "Open",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " Apple event. AppleScript lets Final Cut Pro identify the app that’s sending the request, which means Final Cut Pro can provide that information when it reports an error or prompts for user action. The result is a better experience for your users. If you prefer, however, you can use ",
              "type": "text"
            },
            {
              "code": "NSWorkspace",
              "type": "codeVoice"
            },
            {
              "text": " instead of AppleScript. (See the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/technotes/tn2050/_index.html#//apple_ref/doc/uid/DTS10003081-CH1-SUBSECTION8",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " developer documentation for details.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Specify-a-Library-for-the-FCPXML-File",
          "level": 3,
          "text": "Specify a Library for the FCPXML File",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your app sends an FCPXML file to Final Cut Pro using an Apple event, Final Cut Pro displays the Open Library dialog so your user can choose where the content should go. Users can choose an existing library (or event) or create a new one.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can also specify the location of the library as a URL by adding the ",
              "type": "text"
            },
            {
              "code": "import",
              "type": "codeVoice"
            },
            {
              "text": " option to your FCPXML document. You can even have your app prompt users for the location of the library and add that information as the ",
              "type": "text"
            },
            {
              "code": "import",
              "type": "codeVoice"
            },
            {
              "text": " option when it creates your FCPXML document. If no library exists at the location specified in the FCPXML file, Final Cut Pro creates a new one and gives it the default library name. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Once Final Cut Pro determines a library for the data, it processes the FCPXML document and populates the content according to the following rules.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "If an FCPXML document contains",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Final Cut Pro does the following",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "One or more clips or projects",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Final Cut Pro creates a new event in the specified library named with today’s date, as in 06-29-19. Final Cut Pro then imports all items into the new event by copying or linking to the source data. (If an event with the same name already exists, Final Cut Pro adds a numerical suffix to the new event name to keep names unique, as in 06-29-19 1.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Events",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Final Cut Pro puts the events into the specified library, merging events with the same name. (If items within the merged events have the same name, Final Cut Pro asks the user whether to replace the existing item with the new item or keep both. If a user keeps both, Final Cut Pro adds a numerical suffix to the new item name to keep names unique.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "A library",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Final Cut Pro merges all the content into the specified library. Any naming conflicts between new and existing items are handled using the previous rules.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Metadata Exchanges with Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents": {
      "abstract": [
        {
          "text": "Describe media assets, editing decisions, metadata, and other items in FCPXML so users can send and receive data between your app and Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
      "kind": "article",
      "role": "article",
      "title": "Creating FCPXML Documents",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-fcpxml-documents"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options": {
      "abstract": [
        {
          "text": "Contain options that describe how to import events and projects into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/import-options",
      "kind": "article",
      "role": "article",
      "title": "import-options",
      "type": "topic",
      "url": "/documentation/professional-video-applications/import-options"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets, timeline sequences, and metadata from your app to Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Sending Media and Metadata to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-media-and-metadata-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded": {
      "abstract": [
        {
          "text": "Designate media as a growing file to make it available to users while it’s still being recorded.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded",
      "kind": "article",
      "role": "article",
      "title": "Sending media to Final Cut Pro as it’s recorded",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-media-to-final-cut-pro-as-it-s-recorded"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Add drag and drop support so your users can drag media assets and timeline sequences from your app directly into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop for Data Sent to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://developer.apple.com/library/archive/technotes/tn2050/_index.html#//apple_ref/doc/uid/DTS10003081-CH1-SUBSECTION8": {
      "identifier": "https://developer.apple.com/library/archive/technotes/tn2050/_index.html#//apple_ref/doc/uid/DTS10003081-CH1-SUBSECTION8",
      "title": "NSWorkspace",
      "titleInlineContent": [
        {
          "text": "NSWorkspace",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/technotes/tn2050/_index.html#//apple_ref/doc/uid/DTS10003081-CH1-SUBSECTION8"
    },
    "media-3878514": {
      "alt": "Illustration showing movement of Final Cut Pro X M L document from your app through an Apple event to Final Cut Pro.",
      "identifier": "media-3878514",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c56ed4aab8a41002549581c27153d269/media-3878514@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
      ],
      "title": "Data Sent from Your App to Final Cut Pro"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
              ],
              "title": "Data Sent from Your App to Final Cut Pro"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/sending-data-programmatically-to-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/sending-data-programmatically-to-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
