{
  "abstract": [
    {
      "text": "Send media assets, timeline sequences, and metadata from your app to Final Cut Pro.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-and-metadata-to-final-cut-pro"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Sending Media and Metadata to Final Cut Pro"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Make content in your app available to Final Cut Pro, whether it’s a timeline sequence from an asset-management app or raw footage from video capture software. With FCPXML, your users have options for getting data from your app to Final Cut Pro for editing. Your app can send media assets as Final Cut Pro clips, events, projects, and other items. An FCPXML document can also contain markers, ratings, keywords, keyword collections, and metadata.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3878512",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Choose-How-to-Send-Data-to-Final-Cut-Pro",
          "level": 3,
          "text": "Choose How to Send Data to Final Cut Pro",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Send your users’ data to Final Cut Pro based on how much and what kind of data they have to send, how often they need to send it, and how they approach their tasks. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If your users often send small batches of individual clips to different areas of Final Cut Pro and go back and forth frequently between your app and Final Cut Pro, set up drag and drop in your app to make sending media to Final Cut Pro more intuitive. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If your users have a lot of assets to edit, and their workflow has them send everything to Final Cut Pro before starting to edit, use Apple events to help them manage that workflow more efficiently. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If your users want to send media to Final Cut Pro for editing while they’re recording it, make sure your app designates the file as a ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "growing",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " file. You can then choose how to send the growing media file to Final Cut Pro. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Create-an-FCPXML-Document",
          "level": 3,
          "text": "Create an FCPXML Document",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "No matter how your app sends content to Final Cut Pro, it must create an FCPXML document to describe your users’ data. FCPXML—an XML-based language—describes the media, metadata, and timeline sequences (rough cuts as well as more-polished sequences) in terms that Final Cut Pro understands. Using FCPXML, your app can also take advantage of Final Cut Pro features, such as keywords, and use metadata to set up content for your users to edit. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Metadata Exchanges with Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents": {
      "abstract": [
        {
          "text": "Describe media assets, editing decisions, metadata, and other items in FCPXML so users can send and receive data between your app and Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents",
      "kind": "article",
      "role": "article",
      "title": "Creating FCPXML Documents",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-fcpxml-documents"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Manage and streamline the sending of batches of media assets and timeline sequences from your app using Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Sending Data Programmatically to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-data-programmatically-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded": {
      "abstract": [
        {
          "text": "Designate media as a growing file to make it available to users while it’s still being recorded.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded",
      "kind": "article",
      "role": "article",
      "title": "Sending media to Final Cut Pro as it’s recorded",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sending-media-to-final-cut-pro-as-it-s-recorded"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro": {
      "abstract": [
        {
          "text": "Add drag and drop support so your users can drag media assets and timeline sequences from your app directly into Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop for Data Sent to Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "media-3878512": {
      "alt": "Illustration showing the types of items users can send from your ap to Final Cut Pro using F C P X M L.",
      "identifier": "media-3878512",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/84009a7f8c378e71c18a081d033c8255/media-3878512@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
      ],
      "title": "Data Sent from Your App to Final Cut Pro"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Sent-from-Your-App-to-Final-Cut-Pro",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-data-programmatically-to-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sending-media-to-final-cut-pro-as-it-s-recorded"
              ],
              "title": "Data Sent from Your App to Final Cut Pro"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/sending-media-and-metadata-to-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/sending-media-and-metadata-to-final-cut-pro"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
