{
  "abstract": [
    {
      "text": "Download and install the required software to develop FxPlug plug-ins.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/setting-up-for-fxplug-development"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting up for FxPlug development"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Developing FxPlug plug-ins requires that you have certain developer software installed on your Mac along with host applications.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Install-software",
          "level": 3,
          "text": "Install software",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Your system must have the following software installed:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://apps.apple.com/app/xcode/id497799835",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " 15 or newer",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "FxPlug 4 SDK (download from ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/download/all/?q=FxPlug",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ")",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://apps.apple.com/app/motion/id434290957",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " 5.6.4 or newer",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://apps.apple.com/app/final-cut-pro/id424389933",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " 10.6.6 or newer",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Use-plug-ins-in-host-applications",
          "level": 3,
          "text": "Use plug-ins in host applications",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Plug-ins can be used in Final Cut Pro for Mac and Motion, referred to as the host applications. Use plug-ins directly in Motion; in Final Cut Pro, however, you must wrap plug-ins in a template, as described in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Once built, macOS automatically recognizes the plug-ins and vends them to the host applications on request.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro": {
      "abstract": [
        {
          "text": "Add a plug-in to a Motion effect template to use in Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Preparing plug-ins for use in Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/preparing-plug-ins-for-use-in-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/using-out-of-process-fxplug-plug-ins": {
      "abstract": [
        {
          "text": "Register and render FxPlug plug-ins with Motion and Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/using-out-of-process-fxplug-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Using out-of-process FxPlug plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/using-out-of-process-fxplug-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://apps.apple.com/app/final-cut-pro/id424389933": {
      "identifier": "https://apps.apple.com/app/final-cut-pro/id424389933",
      "title": "Final Cut Pro",
      "titleInlineContent": [
        {
          "text": "Final Cut Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://apps.apple.com/app/final-cut-pro/id424389933"
    },
    "https://apps.apple.com/app/motion/id434290957": {
      "identifier": "https://apps.apple.com/app/motion/id434290957",
      "title": "Motion",
      "titleInlineContent": [
        {
          "text": "Motion",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://apps.apple.com/app/motion/id434290957"
    },
    "https://apps.apple.com/app/xcode/id497799835": {
      "identifier": "https://apps.apple.com/app/xcode/id497799835",
      "title": "Xcode",
      "titleInlineContent": [
        {
          "text": "Xcode",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://apps.apple.com/app/xcode/id497799835"
    },
    "https://developer.apple.com/download/all/?q=FxPlug": {
      "identifier": "https://developer.apple.com/download/all/?q=FxPlug",
      "title": "Apple’s developer website",
      "titleInlineContent": [
        {
          "text": "Apple’s developer website",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/download/all/?q=FxPlug"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/using-out-of-process-fxplug-plug-ins"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/using-out-of-process-fxplug-plug-ins"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/setting-up-for-fxplug-development"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/setting-up-for-fxplug-development"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
