{
  "abstract": [
    {
      "text": "Describe Final Cut Pro events and project data and their associated effects.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "title": "Story Elements"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Story Elements to arrange video or audio materials and titles or generators into a timeline, in the order you want them to appear when it plays on the timeline. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for additional control over their precise timing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Anchor one or more other story elements to each story element. An anchored item has a positive or negative lane index that either positions the item above or below its base element in the timeline.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For video elements, lane order also implies compositing order — items with higher lane indexes composite over elements with lower lane indexes. For audio elements, lane order doesn’t affect compositing. Items that reside inside, rather than above or below, a container are called contained items and have an implied lane index of zero.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Many story elements can contain annotations (keyword, markers, and so on) over a range of time, specified with the start and duration attributes. Add annotations  to story elements using the elements listed under Annotation and Note Elements. ",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters": {
      "abstract": [
        {
          "text": "Specify values to change adjustment attributes and effects parameters.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
      "kind": "article",
      "role": "article",
      "title": "Adjustment Attributes and Effect Parameters",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adjustment-attributes-and-effect-parameters"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements": {
      "abstract": [
        {
          "text": "Alter the audio and video output of story elements by using adjustment elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Adjustment Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/adjustment-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker": {
      "abstract": [
        {
          "text": "An annotation that indicates the result of scene analysis to determine the number of people present and the shot and stabilization types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
      "kind": "article",
      "role": "article",
      "title": "analysis-marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/analysis-marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation": {
      "abstract": [
        {
          "text": "Create animations by changing specific adjustment attributes and effect parameters over time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation",
      "type": "topic",
      "url": "/documentation/professional-video-applications/animation"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip": {
      "abstract": [
        {
          "text": "References a single media asset.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
      "kind": "article",
      "role": "article",
      "title": "asset-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/asset-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio": {
      "abstract": [
        {
          "text": "References audio data from an ",
          "type": "text"
        },
        {
          "code": "asset",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "effect",
          "type": "codeVoice"
        },
        {
          "text": " element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
      "kind": "article",
      "role": "article",
      "title": "audio",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-channel-source": {
      "abstract": [
        {
          "text": "Defines an audio component by its source channels.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-channel-source",
      "kind": "article",
      "role": "article",
      "title": "audio-channel-source",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio-channel-source"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source": {
      "abstract": [
        {
          "text": "Defines an audio component by its role.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
      "kind": "article",
      "role": "article",
      "title": "audio-role-source",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audio-role-source"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition": {
      "abstract": [
        {
          "text": "Contains one active story element followed by alternative story elements in the audition container.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
      "kind": "article",
      "role": "article",
      "title": "audition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/audition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption": {
      "abstract": [
        {
          "text": "Represents a closed-caption or subtitle with one or more text blocks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
      "kind": "article",
      "role": "article",
      "title": "caption",
      "type": "topic",
      "url": "/documentation/professional-video-applications/caption"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker": {
      "abstract": [
        {
          "text": "An annotation that applies to a range of time and indicates a chapter.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
      "kind": "article",
      "role": "article",
      "title": "chapter-marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/chapter-marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip": {
      "abstract": [
        {
          "text": "Represents a basic unit of editing.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
      "kind": "article",
      "role": "article",
      "title": "clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/conform-rate": {
      "abstract": [
        {
          "text": "Apply rate conforming to match media frame rate to timeline frame rate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/conform-rate",
      "kind": "article",
      "role": "article",
      "title": "conform-rate",
      "type": "topic",
      "url": "/documentation/professional-video-applications/conform-rate"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-audio": {
      "abstract": [
        {
          "text": "A filter element that references an audio effect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-audio",
      "kind": "article",
      "role": "article",
      "title": "filter-audio",
      "type": "topic",
      "url": "/documentation/professional-video-applications/filter-audio"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video": {
      "abstract": [
        {
          "text": "A filter element that references a video effect.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
      "kind": "article",
      "role": "article",
      "title": "filter-video",
      "type": "topic",
      "url": "/documentation/professional-video-applications/filter-video"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/frame-sampling": {
      "abstract": [
        {
          "text": "Adjust the clip’s frame rate to match the project’s frame rate.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/frame-sampling",
      "kind": "article",
      "role": "article",
      "title": "Frame Sampling",
      "type": "topic",
      "url": "/documentation/professional-video-applications/frame-sampling"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap": {
      "abstract": [
        {
          "text": "Defines a placeholder element that has no intrinsic audio or video data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
      "kind": "article",
      "role": "article",
      "title": "gap",
      "type": "topic",
      "url": "/documentation/professional-video-applications/gap"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword": {
      "abstract": [
        {
          "text": "An annotation that applies a keyword to a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword",
      "kind": "article",
      "role": "article",
      "title": "keyword",
      "type": "topic",
      "url": "/documentation/professional-video-applications/keyword"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker": {
      "abstract": [
        {
          "text": "An annotation, with an optional to-do flag, that applies a text marker to a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
      "kind": "article",
      "role": "article",
      "title": "marker",
      "type": "topic",
      "url": "/documentation/professional-video-applications/marker"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters": {
      "abstract": [
        {
          "text": "Designate a region to which you apply video filter by using a collection of masks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Masked Filters",
      "type": "topic",
      "url": "/documentation/professional-video-applications/masked-filters"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip": {
      "abstract": [
        {
          "text": "References a multicam media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
      "kind": "article",
      "role": "article",
      "title": "mc-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/mc-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute": {
      "abstract": [
        {
          "text": "Suppresses audio output for the audio component over a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute",
      "kind": "article",
      "role": "article",
      "title": "mute",
      "type": "topic",
      "url": "/documentation/professional-video-applications/mute"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note": {
      "abstract": [
        {
          "text": "Define descriptive notes that appliy to an entire element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note",
      "kind": "article",
      "role": "article",
      "title": "note",
      "type": "topic",
      "url": "/documentation/professional-video-applications/note"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating": {
      "abstract": [
        {
          "text": "A rating annotation, such as favorite or reject, that applies to a range of time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
      "kind": "article",
      "role": "article",
      "title": "rating",
      "type": "topic",
      "url": "/documentation/professional-video-applications/rating"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip": {
      "abstract": [
        {
          "text": "References a compound clip media.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
      "kind": "article",
      "role": "article",
      "title": "ref-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/ref-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/roles-attribute": {
      "abstract": [
        {
          "text": "Assign video, audio, title, and caption elements a role.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/roles-attribute",
      "kind": "article",
      "role": "article",
      "title": "Roles Attribute",
      "type": "topic",
      "url": "/documentation/professional-video-applications/roles-attribute"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence": {
      "abstract": [
        {
          "text": "A container that represents the top-level sequence for a Final Cut Pro project or compound clip.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence",
      "kind": "article",
      "role": "article",
      "title": "sequence",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sequence"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine": {
      "abstract": [
        {
          "text": "Contains elements ordered sequentially in time.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
      "kind": "article",
      "role": "article",
      "title": "spine",
      "type": "topic",
      "url": "/documentation/professional-video-applications/spine"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip": {
      "abstract": [
        {
          "text": "Contains a clip with its contained and anchored items synchronized.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
      "kind": "article",
      "role": "article",
      "title": "sync-clip",
      "type": "topic",
      "url": "/documentation/professional-video-applications/sync-clip"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes": {
      "abstract": [
        {
          "text": "Define characteristics of a timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes",
      "kind": "article",
      "role": "article",
      "title": "Timeline Attributes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/timeline-attributes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timemap": {
      "abstract": [
        {
          "text": "Adjust or retime the playback speed of an element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timemap",
      "kind": "article",
      "role": "article",
      "title": "timeMap",
      "type": "topic",
      "url": "/documentation/professional-video-applications/timemap"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes": {
      "abstract": [
        {
          "text": "Schedule the element and its contained or anchored items in a timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
      "kind": "article",
      "role": "article",
      "title": "Timing Attributes",
      "type": "topic",
      "url": "/documentation/professional-video-applications/timing-attributes"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title": {
      "abstract": [
        {
          "text": "Represents a title with one or more text blocks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
      "kind": "article",
      "role": "collectionGroup",
      "title": "title",
      "type": "topic",
      "url": "/documentation/professional-video-applications/title"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition": {
      "abstract": [
        {
          "text": "Applies transition effects that either stand by itself (no neighboring elements), combine two neighboring elements, or apply to a single element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
      "kind": "article",
      "role": "article",
      "title": "transition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/transition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video": {
      "abstract": [
        {
          "text": "References  video data from an ",
          "type": "text"
        },
        {
          "code": "asset",
          "type": "codeVoice"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "code": "effect",
          "type": "codeVoice"
        },
        {
          "text": " element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
      "kind": "article",
      "role": "article",
      "title": "video",
      "type": "topic",
      "url": "/documentation/professional-video-applications/video"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Story-Elements",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
      ],
      "title": "Story Elements"
    },
    {
      "anchor": "Timeline-Characteristics",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timemap",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/conform-rate",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/frame-sampling"
      ],
      "title": "Timeline Characteristics"
    },
    {
      "anchor": "Adjustment-and-Effects-Elements",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-audio",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation"
      ],
      "title": "Adjustment and Effects Elements"
    },
    {
      "anchor": "Audio-Component-Configuration",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-channel-source",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute"
      ],
      "title": "Audio Component Configuration"
    },
    {
      "anchor": "Annotation-and-Note-Elements",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note"
      ],
      "title": "Annotation and Note Elements"
    },
    {
      "anchor": "Media-Component-Roles",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/roles-attribute"
      ],
      "title": "Media Component Roles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Story-Elements",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/asset-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sync-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/video",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mc-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/ref-clip",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/gap",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/spine",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audition",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/sequence"
              ],
              "title": "Story Elements"
            },
            {
              "anchor": "Timeline-Characteristics",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timeline-attributes",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timing-attributes",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/timemap",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/conform-rate",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/frame-sampling"
              ],
              "title": "Timeline Characteristics"
            },
            {
              "anchor": "Adjustment-and-Effects-Elements",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-elements",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/transition",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/caption",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-audio",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/filter-video",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/masked-filters",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/adjustment-attributes-and-effect-parameters",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/animation"
              ],
              "title": "Adjustment and Effects Elements"
            },
            {
              "anchor": "Audio-Component-Configuration",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-channel-source",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/audio-role-source",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/mute"
              ],
              "title": "Audio Component Configuration"
            },
            {
              "anchor": "Annotation-and-Note-Elements",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/keyword",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/chapter-marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/analysis-marker",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/rating",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/note"
              ],
              "title": "Annotation and Note Elements"
            },
            {
              "anchor": "Media-Component-Roles",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/roles-attribute"
              ],
              "title": "Media Component Roles"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/story-elements"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/story-elements"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
