{
  "abstract": [
    {
      "text": "Add drag and drop support in your app to give users an intuitive way to receive clips, projects, and other items from Final Cut Pro.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-to-receive-final-cut-pro-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Supporting Drag and Drop to Receive Final Cut Pro Data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Drag and drop is a good choice for receiving data when your users need to transfer a relatively small number of items from Final Cut Pro to your app. If your users often go back and forth between Final Cut Pro and your app as they receive data from Final Cut Pro, supporting drag and drop in your app could streamline that workflow by letting them drag items directly from the Final Cut Pro sidebar or browser to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "If you want your users to be able to send rendered media (movies) to your app, set up a custom share destination. (See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".)",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Drag and drop operations use a ",
              "type": "text"
            },
            {
              "code": "pasteboard",
              "type": "codeVoice"
            },
            {
              "text": " as the standardized mechanism for exchanging data between apps.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3878515",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Once your user selects objects in the Final Cut Pro sidebar or browser and starts dragging them, Final Cut Pro creates a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "promise",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": "—a commitment to provide a data representation—in the dragging pasteboard. When your user drops the dragged objects into your app, your app requests the content of the promise. Final Cut Pro fulfills the request by putting the FCPXML for the dragged objects into the pasteboard. Your app retrieves the FCPXML and creates the objects in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information on versioned pasteboard types, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro#Pasteboard-Types-and-Versions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "When your users drag an object from Final Cut Pro to your app, only the metadata in the currently selected metadata view is included in the FCPXML. Users can change the metadata view in Final Cut Pro before they drag data to your app. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Receive-Pasteboard-Data",
          "level": 3,
          "text": "Receive Pasteboard Data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When receiving XML, your app can begin checking the available types on the pasteboard to request the most appropriate type; typically the highest versioned pasteboard type your app supports. Requesting a versioned pasteboard type ensures that your app continues to function as expected if a user updates to a new version of Final Cut Pro, with a newer DTD version, before updating your app. Order the pasteboard types your app supports by priority. Then you can iterate through your app’s sorted pasteboard types and select the first type available on the pasteboard. The following code snippet shows how you can do this in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let sortedPasteboardTypes = [\"com.apple.finalcutpro.xml.v1-10\", \"com.apple.finalcutpro.xml.v1-9\", \"com.apple.finalcutpro.xml\"]",
                    "    .map { NSPasteboard.PasteboardType($0) }",
                    "for pasteboardType in sortedPasteboardTypes {",
                    "    guard let availableTypes = pasteboard.types, availableTypes.contains(pasteboardType),",
                    "          let data = pasteboard.data(forType: pasteboardType) else { continue }",
                    "    do {",
                    "        let document = try XMLDocument(data: data, options: [])",
                    "        parseXMLDocument(document)",
                    "    } catch let error {",
                    "        print(error)",
                    "    }",
                    "    break",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSArray *sortedPasteboardTypes = @[@\"com.apple.finalcutpro.xml.v1-10\", @\"com.apple.finalcutpro.xml.v1-9\", @\"com.apple.finalcutpro.xml\"];",
                    "for (NSPasteboardType pasteboardType in sortedPasteboardTypes) {",
                    "    if ([pasteboard.types containsObject:pasteboardType]) {",
                    "        NSData *xmlData = [pasteboard dataForType:pasteboardType];",
                    "        NSError *error = nil;",
                    "        NSXMLDocument *xmlDoc = [[NSXMLDocument alloc] initWithData:xmlData options:NSXMLNodeOptionsNone error:&error];",
                    "        if (error != nil) {",
                    "            [self parseXMLDocument:xmlDoc];",
                    "        }",
                    "        break;",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The organization of the FCPXML document depends on what your users drag out of Final Cut Pro:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "When users drag",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The FCPXML from Final Cut Pro includes",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "One or more events from the Final Cut Pro sidebar",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The contents of the dragged events. Each event can contain multiple projects and clips; each project contains editing decisions and can include markers; and each clip can include keywords and ratings. (Information about the library that contains the events is not included.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "One or more items (projects and clips) in the Final Cut Pro browser",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The contents of the dragged projects and clips. Each project contains editing decisions, along with any markers. Each clip can include keywords and ratings. (Information about the events that contain those items is not included.)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "A single library from the Final Cut Pro sidebar",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "The contents of the entire library. The library can contain multiple events, which could contain multiple projects (with editing decisions and possibly with markers) and clips (possibly with keywords and ratings).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "In each case, metadata associated with the media assets (and in the selected metadata view) are available in the Resource section of the FCPXML document (See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents#Structure-Your-FCPXML-Document",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more details.)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You may decide to design your app so that it accepts only certain types of Final Cut Pro objects in specific areas. For example, one part of your app might accept events, while another part might accept only clips.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro": {
      "abstract": [
        {
          "text": "Send media assets and timeline sequences to Final Cut Pro for editing, and receive rendered media and editing decisions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/content-and-metadata-exchanges-with-final-cut-pro",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Content and Metadata Exchanges with Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/content-and-metadata-exchanges-with-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents#Structure-Your-FCPXML-Document": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/creating-fcpxml-documents#Structure-Your-FCPXML-Document",
      "kind": "section",
      "title": "Structure Your FCPXML Document",
      "type": "topic",
      "url": "/documentation/professional-video-applications/creating-fcpxml-documents#Structure-Your-FCPXML-Document"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination": {
      "abstract": [
        {
          "text": "Receive rendered media (movies), editing descriptions for project timelines, library archives, and FCPXML for other Final Cut Pro items in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination",
      "kind": "article",
      "role": "article",
      "title": "Receiving Media and Data Through a Custom Share Destination",
      "type": "topic",
      "url": "/documentation/professional-video-applications/receiving-media-and-data-through-a-custom-share-destination"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro#Pasteboard-Types-and-Versions": {
      "abstract": [],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro#Pasteboard-Types-and-Versions",
      "kind": "section",
      "title": "Pasteboard Types and Versions",
      "type": "topic",
      "url": "/documentation/professional-video-applications/supporting-drag-and-drop-for-data-sent-to-final-cut-pro#Pasteboard-Types-and-Versions"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac": {
      "identifier": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac",
      "title": "Intro to metadata in Final Cut Pro",
      "titleInlineContent": [
        {
          "text": "Intro to metadata in Final Cut Pro",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://support.apple.com/guide/final-cut-pro/intro-to-metadata-verc392f8885/mac"
    },
    "media-3878515": {
      "alt": "Illustration showing an F C P X M L document moving from Final Cut Pro to your app using the pasteboard. ",
      "identifier": "media-3878515",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/e2995d9f73c9fddeddf61d4464166b35/media-3878515@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Received-in-Your-App-from-Final-Cut-Pro",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination"
      ],
      "title": "Data Received in Your App from Final Cut Pro"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Received-in-Your-App-from-Final-Cut-Pro",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/receiving-media-and-data-through-a-custom-share-destination"
              ],
              "title": "Data Received in Your App from Final Cut Pro"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/supporting-drag-and-drop-to-receive-final-cut-pro-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/supporting-drag-and-drop-to-receive-final-cut-pro-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
