{
  "abstract": [
    {
      "text": "Test and debug FxPlug plug-ins using a variety of methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/testing-fxplug-plug-ins"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Testing FxPlug plug-ins"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A number of subtle rendering situations can arise during the normal use of your plug-in, and your users expect your plug-in to handle them all correctly. You can test for most rendering issues by creating a single project that tests your plug-in for a variety of common scenarios, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Previewing timeline and layer lists",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Displaying at proxy resolution",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Rendering at a lower resolution",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Handling non-square pixels and fields",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The test projects described in this article outline how to test a filter. To test a generator, simply use your own generator instead of the Checkerboard generator, and disregard applying a filter. To ensure correct results, use pixel transforms on the input and output image; see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". To test for correctness, check the results of your generator.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Set-up-a-test-project",
          "level": 3,
          "text": "Set up a test project",
          "type": "heading"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Motion, create a new project with the following custom settings: Resolution: 1920 x 1080 pixels; Field Order: None; Aspect Ratio: Square (1.0); Frame Rate: 30 fps; Duration: 10 seconds.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add three layers to your project—each containing the same generator. Click the Library tab, select the Generators category, and highlight the built-in Checkerboard generator. (If you prefer, you can test using your own FxGenerator generator instead of the built-in Checkerboard generator). Click Apply three times to add three copies of the generator to the canvas. (If you’re testing with your own generator, use that plug-in instead of the Checkerboard generator). You should now have an HD project with square pixels and three generators in the timeline.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the pixel aspect ratio for the bottom generator. In the layer list, highlight the last generator in the list, click the Inspector tab, and then click the Generator tab to see the controls. The first three parameters of every generator are width, height, and pixel aspect ratio. For the bottom generator, set the width to 1440 pixels and, from the Pixel Aspect Ratio pop-up menu, select HD (960x720, 1440x1080).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the pixel aspect ratio for the middle generator. Highlight the middle generator in the layer list, and change its width to 960 pixels and its pixel aspect ratio to Anamorphic 2:1. This changes the generator to have a pixel aspect ratio of 2, which should highlight any problems your plug-ins have with non-square pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Keep the third and final layer’s settings as they are.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Test-for-pixel-aspect-ratio-correctness",
          "level": 3,
          "text": "Test for pixel aspect ratio correctness",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Test your plug-in filter by applying it to each generator in each layer of the project. As you deactivate the top layer, the middle layer should look the same. Likewise, as you deactivate the middle layer, the bottom layer should look the same. If you find that isn’t the case, you aren’t handling non-square pixels correctly. The simplest way to do so is to use the input and output image’s pixel transforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Start by applying the same filter to each generator in your project and then turn off the top layer. The middle layer should look the same as the top layer did. This technique of toggling layer visibility is a useful way to do A/B testing, where you’re interested in seeing if something is different. The following illustration shows the expected output of the checkerboard generator.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586108",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Now turn off the middle layer. The bottom layer should look the same as the middle and top layers. All layers should look like the checkerboard in the image above, regardless of the generator’s pixel aspect ratio setting.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If any of your layers are squeezed or stretched out, as shown in the following illustration, then your plug-in isn’t handling non-square pixels correctly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586106",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Test-the-correctness-of-your-point-parameters",
          "level": 3,
          "text": "Test the correctness of your point parameters",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Another important test for your plug-in is to make sure that your point parameters are creating their effects in the correct place, and that any parameters using absolute pixels create the same look, regardless of the pixel aspect ratio.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the top layer in the checkerboard generator, adjust the Size parameter. Set the size of each checker in absolute pixels.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make the same adjustment to the Size parameter for the middle and bottom layers. Although the second layer (anamorphic) has half as many pixels across as the layer with a pixel aspect ratio of 1, the checkers should remain the same size in both layers for any given value of the parameter.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Test-for-proxy-resolution-correctness",
          "level": 3,
          "text": "Test for proxy resolution correctness",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Proxy resolution uses uniform scaling, while pixel aspect ratio uses non-uniform scaling. If you’re using pixel transforms to do your scaling and the results of your tests for pixel aspect ratio correctness are good, then testing your proxy resolution should be a simple matter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Motion, click Render and select Half as the new resolution. The resolution of the footage drops, but your effect dimensions shouldn’t change.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Render again and select Quarter to switch to quarter resolution. If your effect dimensions remain the same, then your plug-in is properly handling proxy resolution.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the checkerboard generator at full resolution.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586104",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the checkerboard generator at half resolution, but incorrectly rendering the effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586107",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following figure shows the checkerboard generator at half resolution, and correctly rendering the effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586105",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Testing-for-correct-thumbnail-previews",
          "level": 3,
          "text": "Testing for correct thumbnail previews",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you have pixel aspect ratio and proxy resolution working correctly, your plug-in is probably handling thumbnail generation properly. Check by opening the layer list and examining the previews. If the previews show any enlargement or cropping, then your plug-in isn’t handling thumbnail generation correctly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This next example is rendered incorrectly. Notice that the preview in the layer list shows checkers that are the same size as the checkers in the canvas, which is at full-resolution.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586109",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The preview should show a smaller version of the entire layer in the layer list, as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3586103",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Troubleshoot-rendering-problems",
          "level": 3,
          "text": "Troubleshoot rendering problems",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any number of things can go wrong when dealing with non-square pixels and proxy resolution. The most common problem is that some aspect of your effect grows or shrinks inappropriately when applied to non-uniformly scaled footage. Circles get stretched or compressed into ovals, or things are twice as large as they should be.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Transform the coordinates of each pixel from the output image’s pixel space into full-sized, square-pixel image coordinates, using the inverse pixel transform. Then perform your computations on those coordinates as you would normally—without scaling them. Finally, transform the computed coordinates back into the input image’s pixel space using the pixel transform to sample the input image. See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for more information on pixel transforms.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Debug-your-plug-in",
          "level": 3,
          "text": "Debug your plug-in",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To test your plug-in code in a target application, choose Project > Scheme > Edit Scheme in your Xcode project window, and then, below the Info tab for the Run action, choose Motion or Final Cut Pro as the executable.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To see all messages that the plug-in generates, launch Console, and search for the process name of your plug-in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to test your plug-in further on whether it can handle the quitting or restarting of its process, try force quitting its process through Activity Monitor or using the command ",
              "type": "text"
            },
            {
              "code": "kill -9",
              "type": "codeVoice"
            },
            {
              "text": " followed by the process ID of your plugin, which you can find in Activity Monitor. You can also write a shell script to perform a repeatable, automated test. An example of a script is listed below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "#!/bin/sh",
            "PID=0  #enter process ID here  ",
            "SLEEPSECONDS=10  #sleep time between force quitting",
            "while [ 1 -ne 0 ]",
            "do",
            "    if [[ -n $PID ]]",
            "    then",
            "        echo \"Force quitting process with ID: $PID\"",
            "        kill -9 $PID",
            "    else",
            "        echo \"No process found.\"",
            "    fi",
            "    echo \"Sleeping for $SLEEPSECONDS seconds…\"",
            "    sleep $SLEEPSECONDS",
            "done"
          ],
          "syntax": "other",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Run your script in Terminal by first using ",
              "type": "text"
            },
            {
              "code": "chmod +x yourscript.sh",
              "type": "codeVoice"
            },
            {
              "text": " to execute permissions and then ",
              "type": "text"
            },
            {
              "code": "./yourscript.sh",
              "type": "codeVoice"
            },
            {
              "text": " to run it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Force quitting your plug-in more than twice in a span of 30 seconds may cause the host to consider it unresponsive.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug": {
      "abstract": [
        {
          "text": "Create custom effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fxplug",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FxPlug",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fxplug"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in": {
      "abstract": [
        {
          "text": "Give users confidence in your FxPlug plug-in by enabling notarization.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in",
      "kind": "article",
      "role": "article",
      "title": "Notarizing your FxPlug plug-in",
      "type": "topic",
      "url": "/documentation/professional-video-applications/notarizing-your-fxplug-plug-in"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins": {
      "abstract": [
        {
          "text": "Maintain consistent rendering at all resolutions and aspect ratios by using pixel transforms.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/optimizing-fxplug-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Optimizing FxPlug plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/optimizing-fxplug-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro": {
      "abstract": [
        {
          "text": "Add a plug-in to a Motion effect template to use in Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro",
      "kind": "article",
      "role": "article",
      "title": "Preparing plug-ins for use in Final Cut Pro",
      "type": "topic",
      "url": "/documentation/professional-video-applications/preparing-plug-ins-for-use-in-final-cut-pro"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "media-3586103": {
      "alt": "Image showing the thumbnail rendered correctly.",
      "identifier": "media-3586103",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/50fad4e01f798dfcc461ccfcf8ad07fa/media-3586103@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/50fad4e01f798dfcc461ccfcf8ad07fa/media-3586103~dark@2x.png"
        }
      ]
    },
    "media-3586104": {
      "alt": "Image showing render resolution set to Full in Motion.",
      "identifier": "media-3586104",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2fcf90f468c662da8cecbd5c31a8fadd/media-3586104@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/2fcf90f468c662da8cecbd5c31a8fadd/media-3586104~dark@2x.png"
        }
      ]
    },
    "media-3586105": {
      "alt": "Image showing render resolution set to Half in Motion, with the squares in the checkerboard pattern correctly scaled.",
      "identifier": "media-3586105",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c763a8887d419e79ddecada42d128ac1/media-3586105@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c763a8887d419e79ddecada42d128ac1/media-3586105~dark@2x.png"
        }
      ]
    },
    "media-3586106": {
      "alt": "Image showing checkerboard pattern in Motion with stretched shapes that are no longer square.",
      "identifier": "media-3586106",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3c4b546d430bb0febd07da9b992930b2/media-3586106@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3c4b546d430bb0febd07da9b992930b2/media-3586106~dark@2x.png"
        }
      ]
    },
    "media-3586107": {
      "alt": "Image showing render resolution set to Half in Motion, but the squares in the checkerboard pattern are incorrectly scaled.",
      "identifier": "media-3586107",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9ff295a2b73a3e1f334f4e5da2f9958f/media-3586107@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9ff295a2b73a3e1f334f4e5da2f9958f/media-3586107~dark@2x.png"
        }
      ]
    },
    "media-3586108": {
      "alt": "Image showing a checkerboard pattern with square shapes.",
      "identifier": "media-3586108",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8d9f553eb2743cbc12668516caef213e/media-3586108@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/8d9f553eb2743cbc12668516caef213e/media-3586108~dark@2x.png"
        }
      ]
    },
    "media-3586109": {
      "alt": "Image showing the thumbnail rendered incorrectly.",
      "identifier": "media-3586109",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/48bdeefb19e993108b89229e6097aa9c/media-3586109@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/48bdeefb19e993108b89229e6097aa9c/media-3586109~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Testing-and-deployment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in"
      ],
      "title": "Testing and deployment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Testing-and-deployment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/preparing-plug-ins-for-use-in-final-cut-pro",
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/notarizing-your-fxplug-plug-in"
              ],
              "title": "Testing and deployment"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/testing-fxplug-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/testing-fxplug-plug-ins"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
