{
  "abstract": [
    {
      "text": "Describes text style for a segment of text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text-style"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "role": "collectionGroup",
    "title": "text-style"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " element to describe text styles to apply to the content of an element. Or use ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " in combination with a ",
              "type": "text"
            },
            {
              "code": "text-style-def",
              "type": "codeVoice"
            },
            {
              "text": " element to define a shared text style that multiple ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " elements reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "code": "ref",
              "type": "codeVoice"
            },
            {
              "text": " attribute to reference a text-style definition. If a text-style definition is referenced, any attributes specified in this element override the values in the text-style definition.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Refer to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for other attributes of the ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " element to specify the text style settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You use the ",
              "type": "text"
            },
            {
              "code": "text",
              "type": "codeVoice"
            },
            {
              "text": " element to create a series of text segments in a title or caption. For each segment you can apply different text styles using the ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example XML uses text-style definitions to create a text effect:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<title offset=\"0s\" ref=\"r2\" name=\"Continuous: Title with styles, including font and size.\" duration=\"10s\" start=\"0s\">",
            "   <text>",
            "      <text-style ref=\"ts1\">Title with styles, including</text-style>",
            "      <text-style ref=\"ts2\">font</text-style>",
            "      <text-style ref=\"ts1\">and</text-style>",
            "      <text-style ref=\"ts3\">size</text-style>",
            "      <text-style ref=\"ts1\">.</text-style>",
            "   </text>",
            "   <text-style-def id=\"ts1\">",
            "      <text-style font=\"Helvetica\" fontSize=\"72\" fontFace=\"Regular\" fontColor=\"1 1 1 1\" strokeColor=\"1 0 0 1\" strokeWidth=\"1\" alignment=\"center\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts2\">",
            "      <text-style font=\"Capitals\" fontSize=\"72\" fontFace=\"Regular\" fontColor=\"1 1 1 1\" bold=\"1\" strokeColor=\"1 0 0 1\" strokeWidth=\"1\" alignment=\"center\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts3\">",
            "      <text-style font=\"Helvetica\" fontSize=\"120\" fontFace=\"Regular\" fontColor=\"1 1 1 1\" strokeColor=\"1 0 0 1\" strokeWidth=\"1\" alignment=\"center\" />",
            "   </text-style-def>",
            "</title>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "3D text geometry and appearance are described with one or more ",
              "type": "text"
            },
            {
              "code": "param",
              "type": "codeVoice"
            },
            {
              "text": " elements as children of the ",
              "type": "text"
            },
            {
              "code": "text-style",
              "type": "codeVoice"
            },
            {
              "text": " element, each specifying a respective parameter.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<text-style-def id=\"ts1\">",
            "   <text-style font=\"Helvetica\" fontSize=\"63\" fontFace=\"Regular\" fontColor=\"1 0.999974 0.999991 1\" alignment=\"center\">",
            "      <param name=\"Lighting\" key=\"527\">",
            "         <param name=\"Environment\" key=\"512\">",
            "            <param name=\"Intensity\" key=\"514\" value=\"0.8\" />",
            "            <param name=\"Rotation\" key=\"516\" value=\"0 247 0 0 (Use Rotation)\" />",
            "            <param name=\"Contrast\" key=\"517\" value=\"62\" />",
            "            <param name=\"Saturation\" key=\"525\" value=\"47\" />",
            "         </param>",
            "      </param>",
            "      <param name=\"Material\" key=\"material:Basic\">",
            "         <param name=\"Layer\" key=\"layer:Finish:1 (Enamel)\">",
            "            <param name=\"Highlight Color\" key=\"127\" value=\"0.838246 0.965254 0.503887\" />",
            "         </param>",
            "         <param name=\"Layer\" key=\"layer:Substance:3 (Plastic)\">",
            "            <param name=\"Type\" key=\"4\" value=\"0 (Shiny)\" />",
            "            <param name=\"Color\" key=\"106\" value=\"0.813144 0.729297 0.994205\" />",
            "         </param>",
            "      </param>",
            "   </text-style>",
            "</text-style-def>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following example XML represents a caption in CEA-608 format:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<caption name=\"CEA-608 English caption with color and underline.\" lane=\"1\" offset=\"2225223/24000s\" duration=\"48048/24000s\" start=\"3600s\" role=\"CEA-608?captionFormat=CEA608.en-US\">",
            "   <text position=\"4 1\" display-style=\"pop-on\" alignment=\"left\">",
            "      <text-style ref=\"ts1\">CEA-608 English caption with</text-style>",
            "      <text-style ref=\"ts3\">color</text-style>",
            "      <text-style ref=\"ts1\">and</text-style>",
            "      <text-style ref=\"ts4\">underline</text-style>",
            "      <text-style ref=\"ts1\">.</text-style>",
            "   </text>",
            "   <text-style-def id=\"ts1\">",
            "      <text-style fontFace=\"Regular\" fontColor=\"1 1 1 1\" backgroundColor=\"0 0 0 1\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts3\">",
            "      <text-style fontFace=\"Regular\" fontColor=\"0 0 1 1\" backgroundColor=\"0 0 0 1\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts4\">",
            "      <text-style fontFace=\"Regular\" fontColor=\"1 1 1 1\" backgroundColor=\"0 0 0 1\" underline=\"1\" />",
            "   </text-style-def>",
            "</caption>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The following example XML represents an ITT subtitle:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<caption name=\"Belgian French subtitle with color and bold style.\" lane=\"1\" offset=\"29029/300s\" duration=\"48048/24000s\" start=\"3600s\" role=\"My ITT?captionFormat=ITT.fr-BE\">",
            "   <text placement=\"bottom\">",
            "      <text-style ref=\"ts5\">Belgian French subtitle with</text-style>",
            "      <text-style ref=\"ts6\">color</text-style>",
            "      <text-style ref=\"ts5\">and</text-style>",
            "      <text-style ref=\"ts7\">bold style</text-style>",
            "      <text-style ref=\"ts5\">.</text-style>",
            "   </text>",
            "   <text-style-def id=\"ts5\">",
            "      <text-style fontFace=\"Regular\" fontColor=\"1 1 1 1\" backgroundColor=\"0 0 0 1\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts6\">",
            "      <text-style fontFace=\"Regular\" fontColor=\"1 0.684918 0.63397 1\" backgroundColor=\"0 0 0 1\" />",
            "   </text-style-def>",
            "   <text-style-def id=\"ts7\">",
            "      <text-style fontColor=\"1 1 1 1\" bold=\"1\" backgroundColor=\"0 0 0 1\" />",
            "   </text-style-def>",
            "</caption>"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition": {
      "abstract": [
        {
          "text": "Document Type Definition (DTD) for the latest Final Cut Pro XML interchange format.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/document-type-definition",
      "kind": "article",
      "role": "article",
      "title": "Document Type Definition",
      "type": "topic",
      "url": "/documentation/professional-video-applications/document-type-definition"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference": {
      "abstract": [
        {
          "text": "Create documents that describe the data your app or workflow extension exchanges with Final Cut Pro.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/fcpxml-reference",
      "kind": "article",
      "role": "collectionGroup",
      "title": "FCPXML Reference",
      "type": "topic",
      "url": "/documentation/professional-video-applications/fcpxml-reference"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements": {
      "abstract": [
        {
          "text": "Describe Final Cut Pro events and project data and their associated effects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/story-elements",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Story Elements",
      "type": "topic",
      "url": "/documentation/professional-video-applications/story-elements"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text": {
      "abstract": [
        {
          "text": "Describes a block of text that appears in a title or caption on a timeline.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text",
      "kind": "article",
      "role": "article",
      "title": "text",
      "type": "topic",
      "url": "/documentation/professional-video-applications/text"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text-style-def": {
      "abstract": [
        {
          "text": "Defines a set of text style attributes that can be shared with (referenced by) multiple ",
          "type": "text"
        },
        {
          "code": "text-style",
          "type": "codeVoice"
        },
        {
          "text": " elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text-style-def",
      "kind": "article",
      "role": "article",
      "title": "text-style-def",
      "type": "topic",
      "url": "/documentation/professional-video-applications/text-style-def"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title": {
      "abstract": [
        {
          "text": "Represents a title with one or more text blocks.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/title",
      "kind": "article",
      "role": "collectionGroup",
      "title": "title",
      "type": "topic",
      "url": "/documentation/professional-video-applications/title"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-and-Style-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text"
      ],
      "title": "Text and Style Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Text-Style-Definition",
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text-style-def"
      ],
      "title": "Text Style Definition"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Text-Style-Definition",
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text-style-def"
              ],
              "title": "Text Style Definition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-and-Style-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/text"
              ],
              "title": "Text and Style Elements"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional-video-applications/text-style"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional-video-applications/text-style"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
