{"metadata":{"title":"textDroppableView(_:willBecomeEditableForDrop:)","symbolKind":"method","role":"symbol","externalID":"c:objc(pl)UITextDropDelegate(im)textDroppableView:willBecomeEditableForDrop:","roleHeading":"Instance Method","navigatorTitle":[{"text":"textDroppableView:willBecomeEditableForDrop:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDroppableView","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":" & ","kind":"text"},{"text":"UITextDroppable","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDroppable"},{"text":", ","kind":"text"},{"text":"willBecomeEditableForDrop","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextDropRequest","text":"UITextDropRequest","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@UITextDropEditability","text":"UITextDropEditability","kind":"typeIdentifier"}],"modules":[{"name":"UIKit"}],"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"11.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}]},"abstract":[{"type":"text","text":"Asks the delegate if a noneditable text view can accept a drop operation."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Accepting a drop activity","anchor":"Accepting-a-drop-activity","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)"],"generated":true}],"variants":[{"paths":["/documentation/uikit/uitextdropdelegate/textdroppableview(_:willbecomeeditablefordrop:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextdropdelegate/textdroppableview(_:willbecomeeditablefordrop:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDroppableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"textDroppableView","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable","preciseIdentifier":"c:objc(pl)UITextDroppable","text":"UITextDroppable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willBecomeEditableForDrop","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"drop","kind":"internalParam"},{"text":": any ","kind":"text"},{"text":"UITextDropRequest","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextDropRequest"},{"text":") -> ","kind":"text"},{"text":"UITextDropEditability","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextDropEditability"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The text view that received the drop activity.","type":"text"}],"type":"paragraph"}],"name":"textDroppableView"},{"content":[{"inlineContent":[{"type":"text","text":"The drop request."}],"type":"paragraph"}],"name":"drop"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A text drop editability style that indicates whether the text view can accept a drop operation.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"By default, a text view that is not editable can’t accept drop requests. However, you can change this behavior by returning the editability style "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/temporary"},{"type":"text","text":" or "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/yes"},{"type":"text","text":" in your implementation of this method. Not implementing this method is the same as returning the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/no"},{"type":"text","text":" style."}],"type":"paragraph"}]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropRequest":{"kind":"symbol","role":"symbol","title":"UITextDropRequest","navigatorTitle":[{"kind":"identifier","text":"UITextDropRequest"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropRequest"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropRequest","url":"/documentation/uikit/uitextdroprequest","abstract":[{"text":"The interface for specifying the attributes of a drop request for a text view.","type":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UITextDropEditability","kind":"identifier"}],"title":"UITextDropEditability","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uitextdropeditability","navigatorTitle":[{"text":"UITextDropEditability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability","abstract":[{"text":"The text-drop editability styles for noneditable text views.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/no":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"no","kind":"identifier"}],"title":"UITextDropEditability.no","kind":"symbol","url":"/documentation/uikit/uitextdropeditability/no","navigatorTitle":[{"text":"UITextDropEditabilityNo","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/no","role":"symbol","abstract":[{"type":"text","text":"A text-drop editability specifier indicating that a noneditable text view does not accept drops."}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/yes":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"yes"}],"navigatorTitle":[{"kind":"identifier","text":"UITextDropEditabilityYes"}],"kind":"symbol","abstract":[{"type":"text","text":"A text-drop editability specifier indicating that a noneditable text view does accept drops, and that the dropped text remains editable after the drop is finished."}],"title":"UITextDropEditability.yes","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/yes","url":"/documentation/uikit/uitextdropeditability/yes"},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)":{"abstract":[{"text":"Asks the delegate if a noneditable text view can accept a drop operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDroppableView"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" & "},{"preciseIdentifier":"c:objc(pl)UITextDroppable","kind":"typeIdentifier","text":"UITextDroppable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willBecomeEditableForDrop"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UITextDropRequest","kind":"typeIdentifier","text":"UITextDropRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@E@UITextDropEditability","kind":"typeIdentifier","text":"UITextDropEditability"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)","url":"/documentation/uikit/uitextdropdelegate/textdroppableview(_:willbecomeeditablefordrop:)","navigatorTitle":[{"kind":"identifier","text":"textDroppableView:willBecomeEditableForDrop:"}],"type":"topic","kind":"symbol","title":"textDroppableView(_:willBecomeEditableForDrop:)"},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/temporary":{"navigatorTitle":[{"kind":"identifier","text":"UITextDropEditabilityTemporary"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability/temporary","kind":"symbol","url":"/documentation/uikit/uitextdropeditability/temporary","abstract":[{"text":"A text-drop editability specifier indicating that a noneditable text view does accept drops but reverts to its noneditable status immediately afterward.","type":"text"}],"role":"symbol","title":"UITextDropEditability.temporary","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"temporary"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable":{"role":"symbol","type":"topic","title":"UITextDroppable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDroppable"}],"url":"/documentation/uikit/uitextdroppable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drop destination."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDroppable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable"},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)":{"type":"topic","kind":"symbol","url":"/documentation/uikit/uitextdropdelegate/textdroppableview(_:proposalfordrop:)","navigatorTitle":[{"kind":"identifier","text":"textDroppableView:proposalForDrop:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)","title":"textDroppableView(_:proposalForDrop:)","role":"symbol","abstract":[{"text":"Asks the delegate if the text view can accept a drop operation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDroppableView"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextDroppable","kind":"typeIdentifier","text":"UITextDroppable"},{"kind":"text","text":", "},{"kind":"externalParam","text":"proposalForDrop"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)UITextDropRequest","kind":"typeIdentifier","text":"UITextDropRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITextDropProposal","kind":"typeIdentifier","text":"UITextDropProposal"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextDropDelegate"}],"url":"/documentation/uikit/uitextdropdelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","title":"UITextDropDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"The interface for configuring a text view’s drop behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"11.0","beta":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"11.0"},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"13.1"},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"textDroppableView:willBecomeEditableForDrop:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"textDroppableView:willBecomeEditableForDrop:","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate"]]}},{"op":"add","path":"/topicSections","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)"],"title":"Accepting a drop activity","anchor":"Accepting-a-drop-activity"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UITextDropEditability","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextDropEditability","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"},{"text":") ","kind":"text"},{"text":"textDroppableView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView<UITextDroppable>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewobjc(pl)UITextDroppable"},{"text":" *) ","kind":"text"},{"text":"textDroppableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willBecomeEditableForDrop:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UITextDropRequest>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UITextDropRequest"},{"text":") ","kind":"text"},{"text":"drop","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The text view that received the drop activity.","type":"text"}],"type":"paragraph"}],"name":"textDroppableView"},{"content":[{"inlineContent":[{"text":"The drop request.","type":"text"}],"type":"paragraph"}],"name":"drop"}],"kind":"parameters"},"op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A text drop editability style that indicates whether the text view can accept a drop operation."}],"type":"paragraph"}]}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/title","value":"UITextDropRequest","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/fragments","value":[{"text":"UITextDropRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropRequest/navigatorTitle","value":[{"text":"UITextDropRequest","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title","value":"UITextDropEditability","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments","value":[{"kind":"identifier","text":"UITextDropEditability"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle","value":[{"text":"UITextDropEditability","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1no/title","value":"UITextDropEditabilityNo","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1no/fragments","value":[{"kind":"identifier","text":"UITextDropEditabilityNo"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1yes/title","value":"UITextDropEditabilityYes","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1yes/fragments","value":[{"kind":"identifier","text":"UITextDropEditabilityYes"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willBecomeEditableForDrop:)/title","value":"textDroppableView:willBecomeEditableForDrop:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willBecomeEditableForDrop:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"textDroppableView:willBecomeEditableForDrop:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1temporary/title","value":"UITextDropEditabilityTemporary","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability~1temporary/fragments","value":[{"kind":"identifier","text":"UITextDropEditabilityTemporary"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","value":"UIView","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","value":[{"text":"UIView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","value":[{"text":"UIView","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title","value":"UITextDroppable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments","value":[{"text":"UITextDroppable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle","value":[{"text":"UITextDroppable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:proposalForDrop:)/title","value":"textDroppableView:proposalForDrop:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:proposalForDrop:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textDroppableView:proposalForDrop:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title","value":"UITextDropDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments","value":[{"kind":"identifier","text":"UITextDropDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle","value":[{"kind":"identifier","text":"UITextDropDelegate"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}