{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@U@vU1024@FI@s",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "s"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@U@vU1024",
        "text": "vU1024"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "text": "__Unnamed_struct_s"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "s"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "s"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "s"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@U@vU1024",
              "text": "vU1024"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "kind": "typeIdentifier",
              "text": "__Unnamed_struct_s"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024": {
      "abstract": [
        {
          "text": "A union containing an array or structure of eight ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or thirty-two 32-bit integers, representing a 1024-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "role": "symbol",
      "title": "vU1024",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "s"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_s"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "s"
        }
      ],
      "role": "symbol",
      "title": "s",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/LSW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LSW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/LSW",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSW",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/lsw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/MSW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MSW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/MSW",
      "kind": "symbol",
      "role": "symbol",
      "title": "MSW",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/msw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d10": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d10"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d10",
      "kind": "symbol",
      "role": "symbol",
      "title": "d10",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d10"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d11": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d11"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d11",
      "kind": "symbol",
      "role": "symbol",
      "title": "d11",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d11"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d12": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d12"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d12",
      "kind": "symbol",
      "role": "symbol",
      "title": "d12",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d12"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d13": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d13"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d13",
      "kind": "symbol",
      "role": "symbol",
      "title": "d13",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d13"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d14": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d14"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d14",
      "kind": "symbol",
      "role": "symbol",
      "title": "d14",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d14"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d15": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d15"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d15",
      "kind": "symbol",
      "role": "symbol",
      "title": "d15",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d15"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d16": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d16",
      "kind": "symbol",
      "role": "symbol",
      "title": "d16",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d16"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d17": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d17"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d17",
      "kind": "symbol",
      "role": "symbol",
      "title": "d17",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d17"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d18": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d18"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d18",
      "kind": "symbol",
      "role": "symbol",
      "title": "d18",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d18"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d19": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d19"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d19",
      "kind": "symbol",
      "role": "symbol",
      "title": "d19",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d19"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d2",
      "kind": "symbol",
      "role": "symbol",
      "title": "d2",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d20": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d20"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d20",
      "kind": "symbol",
      "role": "symbol",
      "title": "d20",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d20"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d21": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d21"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d21",
      "kind": "symbol",
      "role": "symbol",
      "title": "d21",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d21"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d22": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d22"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d22",
      "kind": "symbol",
      "role": "symbol",
      "title": "d22",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d22"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d23": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d23"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d23",
      "kind": "symbol",
      "role": "symbol",
      "title": "d23",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d23"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d24": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d24"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d24",
      "kind": "symbol",
      "role": "symbol",
      "title": "d24",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d24"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d25": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d25"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d25",
      "kind": "symbol",
      "role": "symbol",
      "title": "d25",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d25"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d26": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d26"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d26",
      "kind": "symbol",
      "role": "symbol",
      "title": "d26",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d26"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d27": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d27"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d27",
      "kind": "symbol",
      "role": "symbol",
      "title": "d27",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d27"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d28": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d28"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d28",
      "kind": "symbol",
      "role": "symbol",
      "title": "d28",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d28"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d29": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d29"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d29",
      "kind": "symbol",
      "role": "symbol",
      "title": "d29",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d29"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d3",
      "kind": "symbol",
      "role": "symbol",
      "title": "d3",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d30": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d30"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d30",
      "kind": "symbol",
      "role": "symbol",
      "title": "d30",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d30"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d31": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d31"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d31",
      "kind": "symbol",
      "role": "symbol",
      "title": "d31",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d31"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d4",
      "kind": "symbol",
      "role": "symbol",
      "title": "d4",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d5"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d5",
      "kind": "symbol",
      "role": "symbol",
      "title": "d5",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d6"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d6",
      "kind": "symbol",
      "role": "symbol",
      "title": "d6",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d7"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d7",
      "kind": "symbol",
      "role": "symbol",
      "title": "d7",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d8",
      "kind": "symbol",
      "role": "symbol",
      "title": "d8",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d8"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d9": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d9"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d9",
      "kind": "symbol",
      "role": "symbol",
      "title": "d9",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s/d9"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "v"
        }
      ],
      "role": "symbol",
      "title": "v",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/v"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_vs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vs"
        }
      ],
      "role": "symbol",
      "title": "vs",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/LSW",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/MSW",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d10",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d11",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d12",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d13",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d14",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d15",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d16",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d17",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d18",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d19",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d2",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d20",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d21",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d22",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d23",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d24",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d25",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d26",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d27",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d28",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d29",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d3",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d30",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d31",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d4",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d5",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d6",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d7",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d8",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s/d9"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "s"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1vs/title",
          "value": "vs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1vs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/title",
          "value": "vU1024"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1s/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1v/title",
          "value": "v"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "v"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vu1024/s"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vu1024/s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
