{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@U@vU1024@FI@vs",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "vs"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@U@vU1024",
        "text": "vU1024"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "text": "__Unnamed_struct_vs"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "vs"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "vs"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "vs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@U@vU1024",
              "text": "vU1024"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "kind": "typeIdentifier",
              "text": "__Unnamed_struct_vs"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024": {
      "abstract": [
        {
          "text": "A union containing an array or structure of eight ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or thirty-two 32-bit integers, representing a 1024-bit unsigned integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vU1024"
        }
      ],
      "role": "symbol",
      "title": "vU1024",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "s"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_s"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "s"
        }
      ],
      "role": "symbol",
      "title": "s",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "v"
        }
      ],
      "role": "symbol",
      "title": "v",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/v"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vU1024",
          "text": "vU1024"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_vs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vs"
        }
      ],
      "role": "symbol",
      "title": "vs",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v1": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v1",
      "kind": "symbol",
      "role": "symbol",
      "title": "v1",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v1"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v2",
      "kind": "symbol",
      "role": "symbol",
      "title": "v2",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v3",
      "kind": "symbol",
      "role": "symbol",
      "title": "v3",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v4",
      "kind": "symbol",
      "role": "symbol",
      "title": "v4",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v5"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v5",
      "kind": "symbol",
      "role": "symbol",
      "title": "v5",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v6"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v6",
      "kind": "symbol",
      "role": "symbol",
      "title": "v6",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v7"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v7",
      "kind": "symbol",
      "role": "symbol",
      "title": "v7",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v8": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "v8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v8",
      "kind": "symbol",
      "role": "symbol",
      "title": "v8",
      "type": "topic",
      "url": "/documentation/accelerate/vu1024/vs/v8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
        "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "vs"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v1",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v2",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v3",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v4",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v5",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v6",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v7",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/vs/v8"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/v",
                "doc://com.apple.accelerate/documentation/Accelerate/vU1024/s"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "vs"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1s/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/title",
          "value": "vU1024"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vU1024"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1v/title",
          "value": "v"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "v"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1vs/title",
          "value": "vs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vU1024~1vs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vu1024/vs"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vu1024/vs"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
