{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremedia/documentation/CoreMedia",
        "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor/isoFamilyWithAppleExtensions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreMedia",
    "externalID": "c:@kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "isoFamilyWithAppleExtensions"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CMImageDescriptionFlavor",
        "text": "CMImageDescriptionFlavor"
      }
    ],
    "modules": [
      {
        "name": "Core Media"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "isoFamilyWithAppleExtensions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "isoFamilyWithAppleExtensions"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CMImageDescriptionFlavor",
              "text": "CMImageDescriptionFlavor"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremedia/documentation/CoreMedia": {
      "abstract": [
        {
          "text": "Represent time-based audio-visual assets with essential data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Media",
      "type": "topic",
      "url": "/documentation/coremedia"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor": {
      "abstract": [
        {
          "text": "Types that represent image format descriptions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMImageDescriptionFlavor"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMImageDescriptionFlavor"
        }
      ],
      "role": "symbol",
      "title": "CMImageDescriptionFlavor",
      "type": "topic",
      "url": "/documentation/coremedia/cmimagedescriptionflavor"
    },
    "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor/isoFamilyWithAppleExtensions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isoFamilyWithAppleExtensions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CMImageDescriptionFlavor",
          "text": "CMImageDescriptionFlavor"
        }
      ],
      "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor/isoFamilyWithAppleExtensions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
        }
      ],
      "role": "symbol",
      "title": "isoFamilyWithAppleExtensions",
      "type": "topic",
      "url": "/documentation/coremedia/cmimagedescriptionflavor/isofamilywithappleextensions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremedia/documentation/CoreMedia"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coremedia/documentation/CoreMedia/CMImageDescriptionFlavor",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CMImageDescriptionFlavor",
                    "text": "CMImageDescriptionFlavor"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMImageDescriptionFlavor~1isoFamilyWithAppleExtensions/title",
          "value": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMImageDescriptionFlavor~1isoFamilyWithAppleExtensions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCMImageDescriptionFlavor_ISOFamilyWithAppleExtensions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMImageDescriptionFlavor/title",
          "value": "CMImageDescriptionFlavor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMImageDescriptionFlavor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMImageDescriptionFlavor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremedia~1documentation~1CoreMedia~1CMImageDescriptionFlavor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMImageDescriptionFlavor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremedia/cmimagedescriptionflavor/isofamilywithappleextensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremedia/cmimagedescriptionflavor/isofamilywithappleextensions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
