{
  "abstract": [
    {
      "text": "The action is invalid.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.storekittest/documentation/StoreKitTest",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@SKTestErrorCode@SKTestErrorCodeInvalidAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidAction"
      }
    ],
    "modules": [
      {
        "name": "StoreKit Test"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "SKTestErrorCodeInvalidAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "SKTestError.Code.invalidAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest": {
      "abstract": [
        {
          "text": "Create and automate tests in Xcode for your app’s subscription and in-app purchase transactions, and SKAdNetwork implementations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest",
      "kind": "symbol",
      "role": "collection",
      "title": "StoreKit Test",
      "type": "topic",
      "url": "/documentation/storekittest"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError": {
      "abstract": [
        {
          "text": "Information about an error that the testing environment returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SKTestError"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestError"
        }
      ],
      "role": "symbol",
      "title": "SKTestError",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code": {
      "abstract": [
        {
          "text": "Error codes in the testing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound": {
      "abstract": [
        {
          "text": "The initializer can’t find the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.fileNotFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/filenotfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidAction": {
      "abstract": [
        {
          "text": "The action is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidAction"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeInvalidAction"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.invalidAction",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/invalidaction"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier": {
      "abstract": [
        {
          "text": "The product identifier is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidProductIdentifier"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeInvalidProductIdentifier"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.invalidProductIdentifier",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/invalidproductidentifier"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType": {
      "abstract": [
        {
          "text": "The product type is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidProductType"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeInvalidProductType"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.invalidProductType",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/invalidproducttype"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL": {
      "abstract": [
        {
          "text": "The URL is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidURL"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeInvalidURL"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.invalidURL",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/invalidurl"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound": {
      "abstract": [
        {
          "text": "The test environment didn’t find a subscription.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSubscriptionFound"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeNoSubscriptionFound"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.noSubscriptionFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/nosubscriptionfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound": {
      "abstract": [
        {
          "text": "The test environment didn’t find a transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noTransactionFound"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeNoTransactionFound"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.noTransactionFound",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/notransactionfound"
    },
    "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable": {
      "abstract": [
        {
          "text": "The service isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SKTestErrorCodeServiceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "SKTestError.Code.serviceUnavailable",
      "type": "topic",
      "url": "/documentation/storekittest/sktesterror/code/serviceunavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound",
        "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "SKTestErrorCodeInvalidAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.storekittest/documentation/StoreKitTest",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-Codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/fileNotFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductIdentifier",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidProductType",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/invalidURL",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noSubscriptionFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/noTransactionFound",
                "doc://com.apple.storekittest/documentation/StoreKitTest/SKTestError/Code/serviceUnavailable"
              ],
              "title": "Error Codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "SKTestErrorCodeInvalidAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1serviceUnavailable/title",
          "value": "SKTestErrorCodeServiceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1serviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeServiceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidAction/title",
          "value": "SKTestErrorCodeInvalidAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeInvalidAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/title",
          "value": "SKTestErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidProductType/title",
          "value": "SKTestErrorCodeInvalidProductType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidProductType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeInvalidProductType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1noTransactionFound/title",
          "value": "SKTestErrorCodeNoTransactionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1noTransactionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeNoTransactionFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1fileNotFound/title",
          "value": "SKTestErrorCodeFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidURL/title",
          "value": "SKTestErrorCodeInvalidURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeInvalidURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1noSubscriptionFound/title",
          "value": "SKTestErrorCodeNoSubscriptionFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1noSubscriptionFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeNoSubscriptionFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidProductIdentifier/title",
          "value": "SKTestErrorCodeInvalidProductIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.storekittest~1documentation~1StoreKitTest~1SKTestError~1Code~1invalidProductIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SKTestErrorCodeInvalidProductIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/storekittest/sktesterror/code/invalidaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/storekittest/sktesterror/code/invalidaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
