{"kind":"symbol","variants":[{"paths":["/documentation/webkit/webeditingdelegate/webview(_:shouldinsert:replacing:given:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/webkit/webeditingdelegate/webview(_:shouldinsert:replacing:given:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebView","preciseIdentifier":"c:objc(cs)WebView","identifier":"doc://com.apple.webkit/documentation/WebKit/WebView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"shouldInsert"},{"kind":"text","text":" "},{"kind":"internalParam","text":"node"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMNode","preciseIdentifier":"c:objc(cs)DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"replacing"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DOMRange","preciseIdentifier":"c:objc(cs)DOMRange","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"given"},{"kind":"text","text":" "},{"kind":"internalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WebViewInsertAction","preciseIdentifier":"c:@E@WebViewInsertAction","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The web view that the user is editing.","type":"text"}]}],"name":"webView"},{"content":[{"inlineContent":[{"type":"text","text":"The content to insert."}],"type":"paragraph"}],"name":"node"},{"content":[{"inlineContent":[{"type":"text","text":"The portion of the content that is replaced with "},{"type":"codeVoice","code":"node"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"range"},{"content":[{"inlineContent":[{"text":"Indicates the type of user action that initiated the insertion.","type":"text"}],"type":"paragraph"}],"name":"action"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"text":" if the user should be allowed to insert ","type":"text"},{"code":"node","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"webView","type":"codeVoice"},{"text":"; otherwise, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"text":".","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method may perform an alternate action—for example, insert a different node—and return "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}]}]}],"metadata":{"role":"symbol","externalID":"c:objc(pl)WebEditingDelegate(im)webView:shouldInsertNode:replacingDOMRange:givenAction:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WebView","kind":"typeIdentifier","text":"WebView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"shouldInsert"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)DOMNode","kind":"typeIdentifier","text":"DOMNode"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"replacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)DOMRange","kind":"typeIdentifier","text":"DOMRange"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"given"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@WebViewInsertAction","kind":"typeIdentifier","text":"WebViewInsertAction"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"method","roleHeading":"Instance Method","platforms":[{"beta":false,"unavailable":false,"deprecatedAt":"10.14","name":"macOS","introducedAt":"10.3","deprecated":false}],"modules":[{"name":"WebKit"}],"navigatorTitle":[{"kind":"identifier","text":"webView:shouldInsertNode:replacingDOMRange:givenAction:"}],"title":"webView(_:shouldInsert:replacing:given:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate"]]},"abstract":[{"text":"Returns whether the user should be allowed to insert a node in place of a range of content.","type":"text"}],"identifier":{"url":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)"],"anchor":"Related-Documentation","title":"Related Documentation"}],"references":{"doc://com.apple.webkit/documentation/WebKit/WebView":{"type":"topic","abstract":[{"type":"codeVoice","code":"WebView"},{"text":" is the core view class in the WebKit framework that manages interactions between the ","type":"text"},{"type":"codeVoice","code":"WebFrame"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"WebFrameView"},{"text":" classes. To embed web content in your application, you just create a ","type":"text"},{"type":"codeVoice","code":"WebView"},{"text":" object, attach it to a window, and send a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s","type":"reference"},{"text":" message to its main frame.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WebView"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/WebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebView"}],"role":"symbol","kind":"symbol","title":"WebView","url":"/documentation/webkit/webview","deprecated":true},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","kind":"symbol"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)":{"abstract":[{"text":"Returns whether a user should be allowed to insert text in place of a range of content.","type":"text"}],"deprecated":true,"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WebView","text":"WebView"},{"kind":"text","text":"!, "},{"text":"shouldInsertText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WebViewInsertAction","kind":"typeIdentifier","preciseIdentifier":"c:@E@WebViewInsertAction"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"title":"webView(_:shouldInsertText:replacing:given:)","kind":"symbol","url":"/documentation/webkit/webeditingdelegate/webview(_:shouldinserttext:replacing:given:)"},"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewInsertAction"}],"type":"topic","url":"/documentation/webkit/webviewinsertaction","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction","navigatorTitle":[{"kind":"identifier","text":"WebViewInsertAction"}],"role":"symbol","deprecated":true,"kind":"symbol","title":"WebViewInsertAction","abstract":[{"type":"text","text":"The type of user action that initiated a delegate message."}]},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)","kind":"symbol","navigatorTitle":[{"text":"webView:shouldInsertNode:replacingDOMRange:givenAction:","kind":"identifier"}],"deprecated":true,"url":"/documentation/webkit/webeditingdelegate/webview(_:shouldinsert:replacing:given:)","abstract":[{"type":"text","text":"Returns whether the user should be allowed to insert a node in place of a range of content."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WebView"},{"text":"!, ","kind":"text"},{"text":"shouldInsert","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WebViewInsertAction","kind":"typeIdentifier","preciseIdentifier":"c:@E@WebViewInsertAction"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"webView(_:shouldInsert:replacing:given:)","role":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","url":"/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"role":"symbol","kind":"symbol","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","kind":"symbol","navigatorTitle":[{"text":"webViewDidChange:","kind":"identifier"}],"deprecated":true,"url":"/documentation/webkit/webeditingdelegate/webviewdidchange(_:)","abstract":[{"type":"text","text":"Sent by the default notification center when the user changes content in the web view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":"!)","kind":"text"}],"title":"webViewDidChange(_:)","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s":{"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"!)"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s","title":"load(_:)","url":"/documentation/webkit/webframe/load(_:)-47p2s","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadRequest:"}],"abstract":[{"type":"text","text":"Connects to a given URL by initiating an asynchronous client request."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate":{"identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebEditingDelegate"}],"role":"symbol","type":"topic","title":"WebEditingDelegate","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"WebEditingDelegate"}],"abstract":[],"url":"/documentation/webkit/webeditingdelegate","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.documentation/documentation/swift/true":{"kind":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/true","title":"true","url":"/documentation/swift/true","type":"topic","abstract":[{"text":"A true value.","type":"text"}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/DOMRange":{"navigatorTitle":[{"kind":"identifier","text":"DOMRange"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMRange"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domrange","title":"DOMRange"},"doc://com.externally.resolved.symbol/s:Sb":{"url":"/documentation/Swift/Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","role":"symbol","abstract":[{"text":"A value type whose instances are either `true` or `false`.","type":"text"}],"type":"topic","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.apple.webkit/documentation/WebKit/DOMNode":{"url":"/documentation/webkit/domnode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOMNode","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"DOMNode","kind":"identifier"}],"deprecated":true,"title":"DOMNode","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","abstract":[]},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"introducedAt":"10.3","name":"macOS","deprecatedAt":"10.14","beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"webView:shouldInsertNode:replacingDOMRange:givenAction:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:shouldInsertNode:replacingDOMRange:givenAction:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate"]]}},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Related Documentation","anchor":"Related-Documentation","identifiers":["doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WebView","kind":"typeIdentifier","identifier":"doc://com.apple.webkit/documentation/WebKit/WebView","preciseIdentifier":"c:objc(cs)WebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldInsertNode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOMNode","kind":"typeIdentifier","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMNode","preciseIdentifier":"c:objc(cs)DOMNode"},{"text":" *) ","kind":"text"},{"text":"node","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacingDOMRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOMRange","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange","preciseIdentifier":"c:objc(cs)DOMRange"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"givenAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WebViewInsertAction","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction","preciseIdentifier":"c:@E@WebViewInsertAction"},{"kind":"text","text":") "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"platforms":["macOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The web view that the user is editing.","type":"text"}]}],"name":"webView"},{"content":[{"inlineContent":[{"text":"The content to insert.","type":"text"}],"type":"paragraph"}],"name":"node"},{"content":[{"inlineContent":[{"type":"text","text":"The portion of the content that is replaced with "},{"type":"codeVoice","code":"node"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"range"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Indicates the type of user action that initiated the insertion.","type":"text"}]}],"name":"action"}]},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true"},{"type":"text","text":" if the user should be allowed to insert "},{"code":"node","type":"codeVoice"},{"type":"text","text":" in "},{"code":"webView","type":"codeVoice"},{"type":"text","text":"; otherwise, "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false"},{"type":"text","text":"."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"value":"WebView","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title"},{"value":[{"kind":"identifier","text":"WebView"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments"},{"value":[{"kind":"identifier","text":"WebView"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle"},{"value":"webView:shouldInsertText:replacingDOMRange:givenAction:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsertText:replacing:given:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsertText:replacing:given:)/fragments"},{"value":"WebViewInsertAction","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/title"},{"value":[{"text":"WebViewInsertAction","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/fragments"},{"value":[{"kind":"identifier","text":"WebViewInsertAction"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/navigatorTitle"},{"value":"webView:shouldInsertNode:replacingDOMRange:givenAction:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsert:replacing:given:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:shouldInsertNode:replacingDOMRange:givenAction:"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsert:replacing:given:)/fragments"},{"value":"webViewDidChange:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webViewDidChange(_:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"webViewDidChange:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webViewDidChange(_:)/fragments"},{"value":"loadRequest:","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title"},{"value":[{"text":"- ","kind":"text"},{"text":"loadRequest:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments"},{"value":"WebEditingDelegate","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/title"},{"value":[{"kind":"identifier","text":"WebEditingDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/fragments"},{"value":[{"kind":"identifier","text":"WebEditingDelegate"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/navigatorTitle"},{"value":"DOMRange","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/title"},{"value":[{"text":"DOMRange","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/fragments"},{"value":[{"kind":"identifier","text":"DOMRange"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/navigatorTitle"},{"value":"DOMNode","op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/title"},{"value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/fragments"},{"value":[{"text":"DOMNode","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMNode/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}