{"sections":[],"metadata":{"title":"webView(_:shouldInsertText:replacing:given:)","symbolKind":"method","modules":[{"name":"WebKit"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","deprecatedAt":"10.14","introducedAt":"10.3"}],"externalID":"c:objc(pl)WebEditingDelegate(im)webView:shouldInsertText:replacingDOMRange:givenAction:","roleHeading":"Instance Method","navigatorTitle":[{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WebView"},{"text":"!, ","kind":"text"},{"text":"shouldInsertText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WebViewInsertAction","kind":"typeIdentifier","preciseIdentifier":"c:@E@WebViewInsertAction"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"abstract":[{"text":"Returns whether a user should be allowed to insert text in place of a range of content.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WebView","text":"WebView","kind":"typeIdentifier","identifier":"doc://com.apple.webkit/documentation/WebKit/WebView"},{"text":"!, ","kind":"text"},{"text":"shouldInsertText","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMRange","text":"DOMRange","kind":"typeIdentifier","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@WebViewInsertAction","text":"WebViewInsertAction","kind":"typeIdentifier","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The web view that the user is editing.","type":"text"}],"type":"paragraph"}],"name":"webView"},{"content":[{"inlineContent":[{"text":"The text to insert.","type":"text"}],"type":"paragraph"}],"name":"text"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The portion of the document that will be replaced with "},{"type":"codeVoice","code":"text"},{"type":"text","text":"."}]}],"name":"range"},{"content":[{"inlineContent":[{"text":"Indicates the type of user action that initiated the insertion.","type":"text"}],"type":"paragraph"}],"name":"action"}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the user should be allowed to insert "},{"type":"codeVoice","code":"text"},{"type":"text","text":" in "},{"type":"codeVoice","code":"webView"},{"type":"text","text":"; otherwise, "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method may perform an alternate action—for example, insert different text—and return "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)"],"anchor":"Related-Documentation"}],"kind":"symbol","variants":[{"paths":["/documentation/webkit/webeditingdelegate/webview(_:shouldinserttext:replacing:given:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/webkit/webeditingdelegate/webview(_:shouldinserttext:replacing:given:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.documentation/documentation/swift/true":{"kind":"symbol","identifier":"doc://com.apple.documentation/documentation/swift/true","title":"true","url":"/documentation/swift/true","type":"topic","abstract":[{"text":"A true value.","type":"text"}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)","kind":"symbol","navigatorTitle":[{"text":"webView:shouldInsertNode:replacingDOMRange:givenAction:","kind":"identifier"}],"deprecated":true,"url":"/documentation/webkit/webeditingdelegate/webview(_:shouldinsert:replacing:given:)","abstract":[{"type":"text","text":"Returns whether the user should be allowed to insert a node in place of a range of content."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WebView"},{"text":"!, ","kind":"text"},{"text":"shouldInsert","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMNode","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMNode"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WebViewInsertAction","kind":"typeIdentifier","preciseIdentifier":"c:@E@WebViewInsertAction"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"webView(_:shouldInsert:replacing:given:)","role":"symbol"},"doc://com.apple.webkit/documentation/WebKit":{"kind":"symbol","identifier":"doc://com.apple.webkit/documentation/WebKit","title":"WebKit","url":"/documentation/webkit","type":"topic","abstract":[{"text":"Integrate web content seamlessly into your app, and customize content interactions to meet your app’s needs.","type":"text"}],"role":"collection"},"doc://com.apple.documentation/documentation/swift/false":{"type":"topic","url":"/documentation/swift/false","abstract":[{"text":"A false value.","type":"text"}],"role":"symbol","kind":"symbol","title":"false","identifier":"doc://com.apple.documentation/documentation/swift/false"},"doc://com.apple.webkit/documentation/WebKit/WebView":{"type":"topic","abstract":[{"type":"codeVoice","code":"WebView"},{"text":" is the core view class in the WebKit framework that manages interactions between the ","type":"text"},{"type":"codeVoice","code":"WebFrame"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"WebFrameView"},{"text":" classes. To embed web content in your application, you just create a ","type":"text"},{"type":"codeVoice","code":"WebView"},{"text":" object, attach it to a window, and send a ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s","type":"reference"},{"text":" message to its main frame.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WebView"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/WebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebView"}],"role":"symbol","kind":"symbol","title":"WebView","url":"/documentation/webkit/webview","deprecated":true},"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s":{"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"!)"}],"identifier":"doc://com.apple.webkit/documentation/WebKit/WebFrame/load(_:)-47p2s","title":"load(_:)","url":"/documentation/webkit/webframe/load(_:)-47p2s","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadRequest:"}],"abstract":[{"type":"text","text":"Connects to a given URL by initiating an asynchronous client request."}],"role":"symbol"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)":{"abstract":[{"text":"Returns whether a user should be allowed to insert text in place of a range of content.","type":"text"}],"deprecated":true,"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsertText:replacing:given:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WebView","text":"WebView"},{"kind":"text","text":"!, "},{"text":"shouldInsertText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!, ","kind":"text"},{"text":"replacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DOMRange","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOMRange"},{"text":"!, ","kind":"text"},{"text":"given","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WebViewInsertAction","kind":"typeIdentifier","preciseIdentifier":"c:@E@WebViewInsertAction"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"title":"webView(_:shouldInsertText:replacing:given:)","kind":"symbol","url":"/documentation/webkit/webeditingdelegate/webview(_:shouldinserttext:replacing:given:)"},"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewInsertAction"}],"type":"topic","url":"/documentation/webkit/webviewinsertaction","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction","navigatorTitle":[{"kind":"identifier","text":"WebViewInsertAction"}],"role":"symbol","deprecated":true,"kind":"symbol","title":"WebViewInsertAction","abstract":[{"type":"text","text":"The type of user action that initiated a delegate message."}]},"doc://com.apple.documentation/documentation/technologies":{"kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","url":"/documentation/technologies","type":"topic","abstract":[{"text":"","type":"text"}],"role":"overview"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)":{"type":"topic","identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","kind":"symbol","navigatorTitle":[{"text":"webViewDidChange:","kind":"identifier"}],"deprecated":true,"url":"/documentation/webkit/webeditingdelegate/webviewdidchange(_:)","abstract":[{"type":"text","text":"Sent by the default notification center when the user changes content in the web view."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webViewDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation12NotificationV"},{"text":"!)","kind":"text"}],"title":"webViewDidChange(_:)","role":"symbol"},"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/s:SS","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"role":"symbol","kind":"symbol","title":"String","url":"/documentation/Swift/String"},"doc://com.apple.webkit/documentation/WebKit/DOMRange":{"navigatorTitle":[{"kind":"identifier","text":"DOMRange"}],"kind":"symbol","deprecated":true,"identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOMRange"}],"type":"topic","role":"symbol","abstract":[],"url":"/documentation/webkit/domrange","title":"DOMRange"},"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate":{"identifier":"doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebEditingDelegate"}],"role":"symbol","type":"topic","title":"WebEditingDelegate","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"WebEditingDelegate"}],"abstract":[],"url":"/documentation/webkit/webeditingdelegate","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"role":"symbol","kind":"symbol","title":"NSString","url":"/documentation/foundation/nsstring"},"doc://com.externally.resolved.symbol/s:Sb":{"url":"/documentation/Swift/Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"symbol","role":"symbol","abstract":[{"text":"A value type whose instances are either `true` or `false`.","type":"text"}],"type":"topic","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"macOS","introducedAt":"10.3","deprecated":false,"beta":false,"unavailable":false,"deprecatedAt":"10.14"}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"webView:shouldInsertText:replacingDOMRange:givenAction:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.webkit/documentation/WebKit","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webViewDidChange(_:)","doc://com.apple.webkit/documentation/WebKit/WebEditingDelegate/webView(_:shouldInsert:replacing:given:)"],"anchor":"Related-Documentation","title":"Related Documentation"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WebView","identifier":"doc://com.apple.webkit/documentation/WebKit/WebView","text":"WebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldInsertText:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"replacingDOMRange:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOMRange","identifier":"doc://com.apple.webkit/documentation/WebKit/DOMRange","text":"DOMRange","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"givenAction:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@WebViewInsertAction","identifier":"doc://com.apple.webkit/documentation/WebKit/WebViewInsertAction","text":"WebViewInsertAction","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["macOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"webView","content":[{"inlineContent":[{"type":"text","text":"The web view that the user is editing."}],"type":"paragraph"}]},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"text":"The text to insert.","type":"text"}]}]},{"name":"range","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The portion of the document that will be replaced with "},{"code":"text","type":"codeVoice"},{"type":"text","text":"."}]}]},{"name":"action","content":[{"inlineContent":[{"text":"Indicates the type of user action that initiated the insertion.","type":"text"}],"type":"paragraph"}]}]},"path":"/primaryContentSections/1"},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/true","isActive":true},{"type":"text","text":" if the user should be allowed to insert "},{"type":"codeVoice","code":"text"},{"type":"text","text":" in "},{"type":"codeVoice","code":"webView"},{"type":"text","text":"; otherwise, "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/swift/false","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},"op":"replace","path":"/primaryContentSections/2"},{"op":"replace","value":"webView:shouldInsertNode:replacingDOMRange:givenAction:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsert:replacing:given:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:shouldInsertNode:replacingDOMRange:givenAction:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsert:replacing:given:)/fragments"},{"op":"replace","value":"WebView","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/title"},{"op":"replace","value":[{"text":"WebView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/fragments"},{"op":"replace","value":[{"text":"WebView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebView/navigatorTitle"},{"op":"replace","value":"loadRequest:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadRequest:"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebFrame~1load(_:)-47p2s/fragments"},{"op":"replace","value":"webView:shouldInsertText:replacingDOMRange:givenAction:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsertText:replacing:given:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:shouldInsertText:replacingDOMRange:givenAction:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webView(_:shouldInsertText:replacing:given:)/fragments"},{"op":"replace","value":"WebViewInsertAction","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/title"},{"op":"replace","value":[{"kind":"identifier","text":"WebViewInsertAction"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"WebViewInsertAction"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebViewInsertAction/navigatorTitle"},{"op":"replace","value":"webViewDidChange:","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webViewDidChange(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webViewDidChange:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate~1webViewDidChange(_:)/fragments"},{"op":"replace","value":"DOMRange","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOMRange"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/fragments"},{"op":"replace","value":[{"text":"DOMRange","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1DOMRange/navigatorTitle"},{"op":"replace","value":"WebEditingDelegate","path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/title"},{"op":"replace","value":[{"text":"WebEditingDelegate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"WebEditingDelegate"}],"path":"/references/doc:~1~1com.apple.webkit~1documentation~1WebKit~1WebEditingDelegate/navigatorTitle"},{"op":"replace","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}