{
  "abstract": [
    {
      "text": "Payment error key that indicates errors with the contact information.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/contactFieldUserInfoKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "PassKit",
    "externalID": "c:@PKPaymentErrorContactFieldUserInfoKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "contactFieldUserInfoKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@PKPaymentErrorKey",
        "text": "PKPaymentErrorKey"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKPaymentErrorContactFieldUserInfoKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "contactFieldUserInfoKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "contactFieldUserInfoKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@PKPaymentErrorKey",
              "text": "PKPaymentErrorKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContactField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for the values to use with this key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key with the error code ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to indicate an error in the name, email address, phone number, or the shipping address as a whole.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this key with the error code ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "  to indicate an error with the billing address as a whole, or billing name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The example code in ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/qa/qa1639/_index.html#//apple_ref/doc/uid/DTS40008751-CH1-SOURCECODE2",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shows the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/contactFieldUserInfoKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " used to indicate a phone number error.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example shows an error indicating a problem with the shipping contact’s phone number.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let phoneError = NSError.init(domain: PKPaymentErrorDomain,",
            "                               code: PKPaymentError.shippingContactInvalidError.rawValue,",
            "                               userInfo: [NSLocalizedDescriptionKey:\"Phone number is invalid\",",
            "                               PKPaymentErrorKey.contactFieldUserInfoKey:PKContactField.phoneNumber])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKContactField": {
      "abstract": [
        {
          "text": "The fields that describe a contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKContactField"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKContactField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKContactField"
        }
      ],
      "role": "symbol",
      "title": "PKContactField",
      "type": "topic",
      "url": "/documentation/passkit/pkcontactfield"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code that indicates an invalid shipping address, email, phone, or name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shippingContactInvalidError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/Code/shippingContactInvalidError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentShippingContactInvalidError"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentError.Code.shippingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/code/shippingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError": {
      "abstract": [
        {
          "text": "The error code to indicate an invalid billing address or billing name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "billingContactInvalidError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC18PKPaymentErrorCodeLeV",
          "text": "PKPaymentError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@PKPaymentErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentError/billingContactInvalidError",
      "kind": "symbol",
      "role": "symbol",
      "title": "billingContactInvalidError",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterror/billingcontactinvaliderror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey": {
      "abstract": [
        {
          "text": "Additional details about an error on the Apple Pay sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPaymentErrorKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentErrorKey"
        }
      ],
      "role": "symbol",
      "title": "PKPaymentErrorKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterrorkey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/contactFieldUserInfoKey": {
      "abstract": [
        {
          "text": "Payment error key that indicates errors with the contact information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contactFieldUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentErrorKey",
          "text": "PKPaymentErrorKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/contactFieldUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentErrorContactFieldUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "contactFieldUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterrorkey/contactfielduserinfokey"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/postalAddressUserInfoKey": {
      "abstract": [
        {
          "text": "Payment error key that indicates errors with the postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddressUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@PKPaymentErrorKey",
          "text": "PKPaymentErrorKey"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/postalAddressUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPaymentErrorPostalAddressUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "postalAddressUserInfoKey",
      "type": "topic",
      "url": "/documentation/passkit/pkpaymenterrorkey/postaladdressuserinfokey"
    },
    "https://developer.apple.com/library/archive/qa/qa1639/_index.html#//apple_ref/doc/uid/DTS40008751-CH1-SOURCECODE2": {
      "identifier": "https://developer.apple.com/library/archive/qa/qa1639/_index.html#//apple_ref/doc/uid/DTS40008751-CH1-SOURCECODE2",
      "title": "Listing 1",
      "titleInlineContent": [
        {
          "text": "Listing 1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/qa/qa1639/_index.html#//apple_ref/doc/uid/DTS40008751-CH1-SOURCECODE2"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/postalAddressUserInfoKey"
      ],
      "title": "Error keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKPaymentErrorContactFieldUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorContactFieldUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey/postalAddressUserInfoKey"
              ],
              "title": "Error keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPaymentErrorKey",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@PKPaymentErrorKey",
                    "text": "PKPaymentErrorKey"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "PKPaymentErrorContactFieldUserInfoKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/title",
          "value": "PKPaymentErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingContactInvalidError/title",
          "value": "PKPaymentShippingContactInvalidError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentError~1Code~1shippingContactInvalidError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentShippingContactInvalidError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey~1postalAddressUserInfoKey/title",
          "value": "PKPaymentErrorPostalAddressUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey~1postalAddressUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorPostalAddressUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContactField/title",
          "value": "PKContactField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContactField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContactField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKContactField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKContactField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey~1contactFieldUserInfoKey/title",
          "value": "PKPaymentErrorContactFieldUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPaymentErrorKey~1contactFieldUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPaymentErrorContactFieldUserInfoKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpaymenterrorkey/contactfielduserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpaymenterrorkey/contactfielduserinfokey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
