{
  "abstract": [
    {
      "text": "Item metadata request is being serviced.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC25ICReturnMetadataErrorCodeLeV15alreadyFetchingSoAAVvpZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "alreadyFetching"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
        "text": "ICReturnMetadataError"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "ImageCaptureCore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "alreadyFetching"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "alreadyFetching"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
              "text": "ICReturnMetadataError"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
              "text": "Code"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore": {
      "abstract": [
        {
          "text": "Browse for media devices and control them programmatically from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore",
      "kind": "symbol",
      "role": "collection",
      "title": "ImageCaptureCore",
      "type": "topic",
      "url": "/documentation/imagecapturecore"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError": {
      "abstract": [
        {
          "text": "A metadata error returned from ImageCaptureCore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ICReturnMetadataError"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "ICReturnMetadataError.Code",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/code"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching": {
      "abstract": [
        {
          "text": "Item metadata request is being serviced.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyFetching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
          "text": "ICReturnMetadataError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching",
      "kind": "symbol",
      "role": "symbol",
      "title": "alreadyFetching",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/alreadyfetching"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled": {
      "abstract": [
        {
          "text": "Item metadata request has been canceled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
          "text": "ICReturnMetadataError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled",
      "kind": "symbol",
      "role": "symbol",
      "title": "canceled",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/canceled"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid": {
      "abstract": [
        {
          "text": "Item metadata request completed with invalid result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
          "text": "ICReturnMetadataError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid",
      "kind": "symbol",
      "role": "symbol",
      "title": "invalid",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/invalid"
    },
    "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable": {
      "abstract": [
        {
          "text": "Item does not have metadata available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notAvailable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC25ICReturnMetadataErrorCodeLeV",
          "text": "ICReturnMetadataError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@ICReturnMetadataErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable",
      "kind": "symbol",
      "role": "symbol",
      "title": "notAvailable",
      "type": "topic",
      "url": "/documentation/imagecapturecore/icreturnmetadataerror/notavailable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-Codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable",
        "doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code"
      ],
      "title": "Error Codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/title",
          "value": "ICReturnMetadataErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ICReturnMetadataErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/imagecapturecore/icreturnmetadataerror/alreadyfetching"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
