{"sections":[],"metadata":{"role":"symbol","modules":[{"name":"ImageCaptureCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canceled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ICReturnMetadataError","kind":"typeIdentifier","preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV"},{"text":".","kind":"text"},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode"}],"externalID":"s:SC25ICReturnMetadataErrorCodeLeV8canceledSoAAVvpZ","platforms":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false}],"roleHeading":"Type Property","title":"canceled","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/imagecapturecore/icreturnmetadataerror/canceled"]}],"identifier":{"url":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError","text":"ICReturnMetadataError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code","text":"Code"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Error-Codes","title":"Error Codes","identifiers":["doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable","doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code"],"generated":true}],"abstract":[{"text":"Item metadata request has been canceled.","type":"text"}],"references":{"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code":{"url":"/documentation/imagecapturecore/icreturnmetadataerror/code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/Code","kind":"symbol","type":"topic","role":"symbol","title":"ICReturnMetadataError.Code","abstract":[]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled":{"url":"/documentation/imagecapturecore/icreturnmetadataerror/canceled","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV","text":"ICReturnMetadataError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/canceled","kind":"symbol","type":"topic","role":"symbol","title":"canceled","abstract":[{"text":"Item metadata request has been canceled.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","kind":"technologies","role":"overview","title":"Technologies","abstract":[{"text":"","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid":{"url":"/documentation/imagecapturecore/icreturnmetadataerror/invalid","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV","text":"ICReturnMetadataError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/invalid","kind":"symbol","type":"topic","role":"symbol","title":"invalid","abstract":[{"text":"Item metadata request completed with invalid result.","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore":{"title":"ImageCaptureCore","role":"collection","kind":"symbol","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore","abstract":[{"text":"Browse for media devices and control them programmatically from your app.","type":"text"}],"type":"topic","url":"/documentation/imagecapturecore"},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable":{"url":"/documentation/imagecapturecore/icreturnmetadataerror/notavailable","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notAvailable","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV","text":"ICReturnMetadataError"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/notAvailable","kind":"symbol","type":"topic","role":"symbol","title":"notAvailable","abstract":[{"text":"Item does not have metadata available.","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching":{"url":"/documentation/imagecapturecore/icreturnmetadataerror/alreadyfetching","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyFetching","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC25ICReturnMetadataErrorCodeLeV","text":"ICReturnMetadataError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ICReturnMetadataErrorCode","text":"Code"}],"identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError/alreadyFetching","kind":"symbol","type":"topic","role":"symbol","title":"alreadyFetching","abstract":[{"text":"Item metadata request is being serviced.","type":"text"}]},"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ICReturnMetadataError"}],"abstract":[{"type":"text","text":"A metadata error returned from ImageCaptureCore."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ICReturnMetadataError"}],"kind":"symbol","type":"topic","url":"/documentation/imagecapturecore/icreturnmetadataerror","identifier":"doc://com.apple.imagecapturecore/documentation/ImageCaptureCore/ICReturnMetadataError","title":"ICReturnMetadataError"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ICReturnMetadataErrorCode","path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/title"},{"op":"replace","value":[{"kind":"identifier","text":"ICReturnMetadataErrorCode"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ICReturnMetadataErrorCode"}],"path":"/references/doc:~1~1com.apple.imagecapturecore~1documentation~1ImageCaptureCore~1ICReturnMetadataError~1Code/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}