{
  "abstract": [
    {
      "text": "The player can no longer play the audio because of an error. Use the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/error",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " property to get information about the error that occurred.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/failed"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@WKAudioFilePlayerStatus@WKAudioFilePlayerStatusFailed",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "failed"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKAudioFilePlayerStatusFailed"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "WKAudioFilePlayerStatus.failed"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "failed"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/error": {
      "abstract": [
        {
          "text": "An error that describes the cause of a failure.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "error"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayer/error"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus": {
      "abstract": [
        {
          "text": "Constants that represent the status of the player.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerStatus"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerStatus"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerStatus",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayerstatus"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/failed": {
      "abstract": [
        {
          "text": "The player can no longer play the audio because of an error. Use the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayer/error",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property to get information about the error that occurred.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "failed"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/failed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerStatusFailed"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerStatus.failed",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayerstatus/failed"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/readyToPlay": {
      "abstract": [
        {
          "text": "The player is ready to play its item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readyToPlay"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/readyToPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerStatusReadyToPlay"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerStatus.readyToPlay",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayerstatus/readytoplay"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/unknown": {
      "abstract": [
        {
          "text": "The status of the item is unknown because the player has not yet loaded the audio file for playback.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKAudioFilePlayerStatusUnknown"
        }
      ],
      "role": "symbol",
      "title": "WKAudioFilePlayerStatus.unknown",
      "type": "topic",
      "url": "/documentation/watchkit/wkaudiofileplayerstatus/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/unknown",
        "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/readyToPlay"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "6.0",
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKAudioFilePlayerStatusFailed"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatusFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/unknown",
                "doc://com.apple.watchkit/documentation/WatchKit/WKAudioFilePlayerStatus/readyToPlay"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "WKAudioFilePlayerStatusFailed"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1unknown/title",
          "value": "WKAudioFilePlayerStatusUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatusUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus/title",
          "value": "WKAudioFilePlayerStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1error/title",
          "value": "error"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayer~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "error"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1readyToPlay/title",
          "value": "WKAudioFilePlayerStatusReadyToPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1readyToPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatusReadyToPlay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1failed/title",
          "value": "WKAudioFilePlayerStatusFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKAudioFilePlayerStatus~1failed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKAudioFilePlayerStatusFailed"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wkaudiofileplayerstatus/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wkaudiofileplayerstatus/failed"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
