{
  "abstract": [
    {
      "text": "Provides an enumerated type that describes the color primaries of the project’s working gamut.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "FxPlug",
      "versions": [
        "4.0",
        "4.2.9"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorPrimaries()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)FxColorGamutAPI_v2(im)colorPrimaries",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "colorPrimaries"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@FxColorPrimaries",
        "text": "FxColorPrimaries"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "colorPrimaries"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "4.2.6",
        "name": "FxPlug"
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "colorPrimaries()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: FxPlug"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "colorPrimaries"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@FxColorPrimaries",
              "text": "FxColorPrimaries"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value that describes the project’s working gamut.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins": {
      "abstract": [
        {
          "text": "Control the appearance of your rendering by using the color gamut API.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/Professional-Video-Applications/managing-color-space-and-gamut-in-plug-ins",
      "kind": "article",
      "role": "article",
      "title": "Managing color space and gamut in plug-ins",
      "type": "topic",
      "url": "/documentation/professional-video-applications/managing-color-space-and-gamut-in-plug-ins"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2": {
      "abstract": [
        {
          "text": "A protocol that handles plug-in queries to the host for the project’s color gamut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxColorGamutAPI_v2"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxColorGamutAPI_v2"
        }
      ],
      "role": "symbol",
      "title": "FxColorGamutAPI_v2",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcolorgamutapi_v2"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromDesiredRGBToYCbCr()": {
      "abstract": [
        {
          "text": "Returns a color matrix that is appropriate for converting RGB values in the project’s working gamut into YCbCr values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorMatrixFromDesiredRGBToYCbCr"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxMatrix44",
          "text": "FxMatrix44"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromDesiredRGBToYCbCr()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorMatrixFromDesiredRGBToYCbCr"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorMatrixFromDesiredRGBToYCbCr()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcolorgamutapi_v2/colormatrixfromdesiredrgbtoycbcr()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromYCbCrToDesiredRGB()": {
      "abstract": [
        {
          "text": "Returns a color matrix that is appropriate for converting RGB values from YCbCr to an RGB value in the project’s working gamut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorMatrixFromYCbCrToDesiredRGB"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)FxMatrix44",
          "text": "FxMatrix44"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromYCbCrToDesiredRGB()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorMatrixFromYCbCrToDesiredRGB"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorMatrixFromYCbCrToDesiredRGB()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcolorgamutapi_v2/colormatrixfromycbcrtodesiredrgb()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorPrimaries()": {
      "abstract": [
        {
          "text": "Provides an enumerated type that describes the color primaries of the project’s working gamut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorPrimaries"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@FxColorPrimaries",
          "text": "FxColorPrimaries"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorPrimaries()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "colorPrimaries"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "colorPrimaries()",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcolorgamutapi_v2/colorprimaries()"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries": {
      "abstract": [
        {
          "text": "Constants used to describe a set of color primaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FxColorPrimaries"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FxColorPrimaries"
        }
      ],
      "role": "symbol",
      "title": "FxColorPrimaries",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fxcolorprimaries"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Color-Gamut-Information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromDesiredRGBToYCbCr()",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromYCbCrToDesiredRGB()"
      ],
      "title": "Getting Color Gamut Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "colorPrimaries"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Color-Gamut-Information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromDesiredRGBToYCbCr()",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorGamutAPI_v2/colorMatrixFromYCbCrToDesiredRGB()"
              ],
              "title": "Getting Color Gamut Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: FxPlug"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@FxColorPrimaries",
                    "text": "FxColorPrimaries"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "colorPrimaries"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FxColorPrimaries",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " value that describes the project’s working gamut.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2/title",
          "value": "FxColorGamutAPI_v2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxColorGamutAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxColorGamutAPI_v2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorMatrixFromDesiredRGBToYCbCr()/title",
          "value": "colorMatrixFromDesiredRGBToYCbCr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorMatrixFromDesiredRGBToYCbCr()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorMatrixFromDesiredRGBToYCbCr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorMatrixFromYCbCrToDesiredRGB()/title",
          "value": "colorMatrixFromYCbCrToDesiredRGB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorMatrixFromYCbCrToDesiredRGB()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorMatrixFromYCbCrToDesiredRGB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorPrimaries()/title",
          "value": "colorPrimaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorGamutAPI_v2~1colorPrimaries()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "colorPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorPrimaries/title",
          "value": "FxColorPrimaries"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorPrimaries/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FxColorPrimaries"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FxColorPrimaries/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FxColorPrimaries"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fxcolorgamutapi_v2/colorprimaries()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fxcolorgamutapi_v2/colorprimaries()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
