{
  "abstract": [
    {
      "text": "Returns an object representing the specified property of the receiver.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(withCode:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "ScriptingBridge",
    "externalID": "c:objc(cs)SBObject(im)propertyWithCode:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "property"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withCode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AEKeyword",
        "text": "AEKeyword"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SBObject",
        "text": "SBObject"
      }
    ],
    "modules": [
      {
        "name": "Scripting Bridge"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "propertyWithCode:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "property(withCode:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "property"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withCode"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "code"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@AEKeyword",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AEKeyword",
              "text": "AEKeyword"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SBObject",
              "text": "SBObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A four-character code that uniquely identifies a property of the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "receiver.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "code"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An object representing the receiver’s property as identified by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "code",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "SBObject",
              "type": "codeVoice"
            },
            {
              "text": " subclasses use this method to implement application-specific",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property accessor methods. You should not need to call this method directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge": {
      "abstract": [
        {
          "text": "Automate scriptable apps by sending and receiving Apple events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
      "kind": "symbol",
      "role": "collection",
      "title": "Scripting Bridge",
      "type": "topic",
      "url": "/documentation/scriptingbridge"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "SBObject",
          "type": "codeVoice"
        },
        {
          "text": " class declares methods that can be invoked on any object in a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "scriptable application. It defines methods for getting elements and",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "properties of an object, as well as setting a given object to a new value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SBObject"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SBObject"
        }
      ],
      "role": "symbol",
      "title": "SBObject",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbobject"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/elementArray(withCode:)": {
      "abstract": [
        {
          "text": "Returns an array containing every child of the receiver with the given",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "class-type code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementArray"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@DescType",
          "text": "DescType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SBElementArray",
          "text": "SBElementArray"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/elementArray(withCode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementArrayWithCode:"
        }
      ],
      "role": "symbol",
      "title": "elementArray(withCode:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbobject/elementarray(withcode:)"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(with:code:)": {
      "abstract": [
        {
          "text": "Returns an object of the designated scripting class representing the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "specified property of the receiver",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "code"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AEKeyword",
          "text": "AEKeyword"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SBObject",
          "text": "SBObject"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(with:code:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyWithClass:code:"
        }
      ],
      "role": "symbol",
      "title": "property(with:code:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbobject/property(with:code:)"
    },
    "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(withCode:)": {
      "abstract": [
        {
          "text": "Returns an object representing the specified property of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "property"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AEKeyword",
          "text": "AEKeyword"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SBObject",
          "text": "SBObject"
        }
      ],
      "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(withCode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyWithCode:"
        }
      ],
      "role": "symbol",
      "title": "property(withCode:)",
      "type": "topic",
      "url": "/documentation/scriptingbridge/sbobject/property(withcode:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@AEKeyword": {
      "abstract": [
        {
          "text": "A four-character code that uniquely identifies a descriptor in an Apple event record or an Apple event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "AEKeyword"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@AEKeyword",
      "kind": "symbol",
      "role": "symbol",
      "title": "AEKeyword",
      "type": "topic",
      "url": "/documentation/coreservices/aekeyword"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Properties-and-Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(with:code:)",
        "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/elementArray(withCode:)"
      ],
      "title": "Getting Properties and Elements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "propertyWithCode:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyWithCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Properties-and-Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/property(with:code:)",
                "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject/elementArray(withCode:)"
              ],
              "title": "Getting Properties and Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.apple.Scripting-Bridge/documentation/ScriptingBridge/SBObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SBObject",
                    "text": "SBObject"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "propertyWithCode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@AEKeyword",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AEKeyword",
                    "text": "AEKeyword"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "code"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A four-character code that uniquely identifies a property of the",
                        "type": "text"
                      },
                      {
                        "text": " ",
                        "type": "text"
                      },
                      {
                        "text": "receiver.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "code"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An object representing the receiver’s property as identified by",
                    "type": "text"
                  },
                  {
                    "text": " ",
                    "type": "text"
                  },
                  {
                    "code": "code",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1property(withCode:)/title",
          "value": "propertyWithCode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1property(withCode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyWithCode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1property(with:code:)/title",
          "value": "propertyWithClass:code:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1property(with:code:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyWithClass:code:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject/title",
          "value": "SBObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SBObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SBObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1elementArray(withCode:)/title",
          "value": "elementArrayWithCode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Scripting-Bridge~1documentation~1ScriptingBridge~1SBObject~1elementArray(withCode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "elementArrayWithCode:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scriptingbridge/sbobject/property(withcode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scriptingbridge/sbobject/property(withcode:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
