{
  "abstract": [
    {
      "text": "Creates an action that uses the specified intent.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/createDocumentAction(withIntent:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIDocumentViewControllerLaunchOptions(cm)createDocumentActionWithIntent:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "createDocumentAction"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "withIntent"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIDocument",
        "text": "UIDocument"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@UIDocumentCreationIntent",
        "text": "CreationIntent"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIAction",
        "text": "UIAction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "createDocumentActionWithIntent:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Method",
    "symbolKind": "method",
    "title": "createDocumentAction(withIntent:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "createDocumentAction"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "withIntent"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "intent"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIDocument",
              "text": "UIDocument"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/CreationIntent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIDocumentCreationIntent",
              "text": "CreationIntent"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIAction",
              "text": "UIAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An intent that defines how your app creates the document.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "intent"
        }
      ]
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to create an action that you can assign to your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/primaryAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/secondaryAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When the system triggers the action, it calls your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAction": {
      "abstract": [
        {
          "text": "A menu element that performs its action in a closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAction"
        }
      ],
      "role": "symbol",
      "title": "UIAction",
      "type": "topic",
      "url": "/documentation/uikit/uiaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/uikit/uidocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/CreationIntent": {
      "abstract": [
        {
          "text": "An app intent that creates new documents for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CreationIntent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/CreationIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CreationIntent"
        }
      ],
      "role": "symbol",
      "title": "UIDocument.CreationIntent",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/creationintent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol you implement to respond as the user interacts with the document browser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentBrowserViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentbrowserviewcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)": {
      "abstract": [
        {
          "text": "Asks the delegate to create a new document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentBrowser"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentBrowserViewController",
          "text": "UIDocumentBrowserViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didRequestDocumentCreationWithHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentBrowserViewController",
          "text": "UIDocumentBrowserViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDocumentBrowserImportMode",
          "text": "ImportMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewControllerDelegate/documentBrowser(_:didRequestDocumentCreationWithHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentBrowser:didRequestDocumentCreationWithHandler:"
        }
      ],
      "role": "symbol",
      "title": "documentBrowser(_:didRequestDocumentCreationWithHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentbrowserviewcontrollerdelegate/documentbrowser(_:didrequestdocumentcreationwithhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController": {
      "abstract": [
        {
          "text": "A view controller that manages and presents a document stored locally or in the cloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class": {
      "abstract": [
        {
          "text": "Options for customizing the document launch view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LaunchOptions"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentViewController.LaunchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/createDocumentAction(withIntent:)": {
      "abstract": [
        {
          "text": "Creates an action that uses the specified intent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createDocumentAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIntent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocument",
          "text": "UIDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIDocumentCreationIntent",
          "text": "CreationIntent"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/createDocumentAction(withIntent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createDocumentActionWithIntent:"
        }
      ],
      "role": "symbol",
      "title": "createDocumentAction(withIntent:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/createdocumentaction(withintent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/primaryAction": {
      "abstract": [
        {
          "text": "The launch scene’s primary action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/primaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryAction"
        }
      ],
      "role": "symbol",
      "title": "primaryAction",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/primaryaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/secondaryAction": {
      "abstract": [
        {
          "text": "The launch scene’s secondary action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class/secondaryAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondaryAction"
        }
      ],
      "role": "symbol",
      "title": "secondaryAction",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/secondaryaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience": {
      "abstract": [
        {
          "text": "Add unique elements to your app’s document launch scene.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-a-document-based-app-s-launch-experience",
      "kind": "article",
      "role": "article",
      "title": "Customizing a document-based app’s launch experience",
      "type": "topic",
      "url": "/documentation/uikit/customizing-a-document-based-app-s-launch-experience"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "createDocumentActionWithIntent:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "createDocumentActionWithIntent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController/LaunchOptions-swift.class"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAction",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIAction",
                    "text": "UIAction"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "createDocumentActionWithIntent:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/CreationIntent",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UIDocumentCreationIntent",
                    "text": "UIDocumentCreationIntent"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "intent"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An intent that defines how your app creates the document.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "intent"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/title",
          "value": "UIDocumentViewControllerLaunchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewControllerLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewControllerLaunchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1createDocumentAction(withIntent:)/title",
          "value": "createDocumentActionWithIntent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1createDocumentAction(withIntent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "createDocumentActionWithIntent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1CreationIntent/title",
          "value": "UIDocumentCreationIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1CreationIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentCreationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1CreationIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentCreationIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1primaryAction/title",
          "value": "primaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1primaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title",
          "value": "UIDocumentViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didRequestDocumentCreationWithHandler:)/title",
          "value": "documentBrowser:didRequestDocumentCreationWithHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate~1documentBrowser(_:didRequestDocumentCreationWithHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentBrowser:didRequestDocumentCreationWithHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title",
          "value": "UIDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/title",
          "value": "UIAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/title",
          "value": "UIDocumentBrowserViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1secondaryAction/title",
          "value": "secondaryAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController~1LaunchOptions-swift.class~1secondaryAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondaryAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/createdocumentaction(withintent:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidocumentviewcontroller/launchoptions-swift.class/createdocumentaction(withintent:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
