{
  "abstract": [
    {
      "text": "Creates and returns a document picker that can export or move the specified documents.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " or ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:asCopy:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(urls:in:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIDocumentPickerViewController(im)initWithURLs:inMode:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "urls"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "], "
      },
      {
        "kind": "externalParam",
        "text": "in"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@UIDocumentPickerMode",
        "text": "UIDocumentPickerMode"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithURLs:inMode:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.0",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(urls:in:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "urls"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "], "
            },
            {
              "kind": "externalParam",
              "text": "in"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@UIDocumentPickerMode",
              "text": "UIDocumentPickerMode"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of documents that the document picked exports or moves.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "urls"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of file-transfer operation that the document picker performs. This argument accepts only the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/exportToService",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/moveToService",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " mode.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mode"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Returns an initialized ",
              "type": "text"
            },
            {
              "code": "UIDocumentPickerViewController",
              "type": "codeVoice"
            },
            {
              "text": " object, or ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " if the object could not be successfully initialized.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 10 and earlier, this method returns the document picker view controller from the most recently used Document Provider extension. If no valid Document Provider can be found, it defaults back to iCloud Drive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 11 and later, it returns the standard browser interface. This interface is the same one used by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller for browsing and performing actions on documents that you store locally and in the cloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentBrowserViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentbrowserviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode": {
      "abstract": [
        {
          "text": "Modes that define the type of file transfer operation that the document picker uses.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentPickerMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerMode"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerMode",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickermode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/exportToService": {
      "abstract": [
        {
          "text": "The document picker exports a local file to a destination outside the app’s sandbox.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exportToService"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/exportToService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerModeExportToService"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerMode.exportToService",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickermode/exporttoservice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/moveToService": {
      "abstract": [
        {
          "text": "The document picker moves a local file outside the app’s sandbox and provides access to it as an external file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moveToService"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/moveToService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerModeMoveToService"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerMode.moveToService",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickermode/movetoservice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that provides access to documents or destinations outside your app’s sandbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentPickerViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(documentTypes:in:)": {
      "abstract": [
        {
          "text": "Creates and returns a document picker that can open or copy the specified file types.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "documentTypes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDocumentPickerMode",
          "text": "UIDocumentPickerMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(documentTypes:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDocumentTypes:inMode:"
        }
      ],
      "role": "symbol",
      "title": "init(documentTypes:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller/init(documenttypes:in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:)": {
      "abstract": [
        {
          "text": "Creates and returns a document picker that can export the types of documents you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forExporting"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForExportingURLs:"
        }
      ],
      "role": "symbol",
      "title": "init(forExporting:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller/init(forexporting:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:asCopy:)": {
      "abstract": [
        {
          "text": "Creates and returns a document picker that can export or copy the types of documents you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forExporting"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "asCopy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:asCopy:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForExportingURLs:asCopy:"
        }
      ],
      "role": "symbol",
      "title": "init(forExporting:asCopy:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller/init(forexporting:ascopy:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(url:in:)": {
      "abstract": [
        {
          "text": "Initializes and returns a document picker that can export or copy the specified document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "url"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDocumentPickerMode",
          "text": "UIDocumentPickerMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(url:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURL:inMode:"
        }
      ],
      "role": "symbol",
      "title": "init(url:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller/init(url:in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(urls:in:)": {
      "abstract": [
        {
          "text": "Creates and returns a document picker that can export or move the specified documents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "urls"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDocumentPickerMode",
          "text": "UIDocumentPickerMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(urls:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithURLs:inMode:"
        }
      ],
      "role": "symbol",
      "title": "init(urls:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentpickerviewcontroller/init(urls:in:)"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(documentTypes:in:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(url:in:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "14.0",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "1.0",
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithURLs:inMode:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURLs:inMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(documentTypes:in:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(url:in:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithURLs:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<NSURL *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "urls"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "inMode:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@UIDocumentPickerMode",
                    "text": "UIDocumentPickerMode"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of documents that the document picked exports or moves.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "urls"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of file-transfer operation that the document picker performs. This argument accepts only the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/exportToService",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerMode/moveToService",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " mode.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mode"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "Returns an initialized ",
                    "type": "text"
                  },
                  {
                    "code": "UIDocumentPickerViewController",
                    "type": "codeVoice"
                  },
                  {
                    "text": " object, or ",
                    "type": "text"
                  },
                  {
                    "code": "nil",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the object could not be successfully initialized.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentPickerViewController/init(forExporting:asCopy:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(forExporting:)/title",
          "value": "initForExportingURLs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(forExporting:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForExportingURLs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode~1moveToService/title",
          "value": "UIDocumentPickerModeMoveToService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode~1moveToService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerModeMoveToService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(urls:in:)/title",
          "value": "initWithURLs:inMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(urls:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURLs:inMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode/title",
          "value": "UIDocumentPickerMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/title",
          "value": "UIDocumentPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/title",
          "value": "UIDocumentBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(documentTypes:in:)/title",
          "value": "initWithDocumentTypes:inMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(documentTypes:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDocumentTypes:inMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(url:in:)/title",
          "value": "initWithURL:inMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(url:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithURL:inMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(forExporting:asCopy:)/title",
          "value": "initForExportingURLs:asCopy:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerViewController~1init(forExporting:asCopy:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForExportingURLs:asCopy:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode~1exportToService/title",
          "value": "UIDocumentPickerModeExportToService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentPickerMode~1exportToService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentPickerModeExportToService"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidocumentpickerviewcontroller/init(urls:in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidocumentpickerviewcontroller/init(urls:in:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
