{
  "abstract": [
    {
      "text": "An error that indicates the number is too large or unsuitable.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKIdentityError@PKIdentityErrorInvalidNonce",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "invalidNonce"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKIdentityErrorInvalidNonce"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKIdentityError.Code.invalidNonce"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "invalidNonce"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct": {
      "abstract": [
        {
          "text": "A structure that represents an identity error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityError"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code": {
      "abstract": [
        {
          "text": "Error codes for identity operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled": {
      "abstract": [
        {
          "text": "An error that indicates the user cancels the presented sheet.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorCancelled"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/cancelled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement": {
      "abstract": [
        {
          "text": "An error that indicates an element the app requests isn’t valid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidElement"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorInvalidElement"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.invalidElement",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/invalidelement"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce": {
      "abstract": [
        {
          "text": "An error that indicates the number is too large or unsuitable.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidNonce"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidNonce",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorInvalidNonce"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.invalidNonce",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/invalidnonce"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable": {
      "abstract": [
        {
          "text": "An error that indicates a network isn’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "networkUnavailable"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNetworkUnavailable"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.networkUnavailable",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/networkunavailable"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested": {
      "abstract": [
        {
          "text": "An error that indicates the elements aren’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noElementsRequested"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNoElementsRequested"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.noElementsRequested",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/noelementsrequested"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported": {
      "abstract": [
        {
          "text": "An error that indicates the request originates from a device the framework doesn’t support.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.notSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/notsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress": {
      "abstract": [
        {
          "text": "An error that indicates a request is already in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestAlreadyInProgress"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorRequestAlreadyInProgress"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.requestAlreadyInProgress",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/requestalreadyinprogress"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown": {
      "abstract": [
        {
          "text": "An error that indicates an unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKIdentityErrorUnknown"
        }
      ],
      "role": "symbol",
      "title": "PKIdentityError.Code.unknown",
      "type": "topic",
      "url": "/documentation/passkit/pkidentityerror-swift.struct/code/unknown"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
        "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKIdentityErrorInvalidNonce"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorInvalidNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/cancelled",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/invalidElement",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/notSupported",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/networkUnavailable",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/noElementsRequested",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/requestAlreadyInProgress",
                "doc://com.apple.passkit/documentation/PassKit/PKIdentityError-swift.struct/Code/unknown"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKIdentityErrorInvalidNonce"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/title",
          "value": "PKIdentityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidNonce/title",
          "value": "PKIdentityErrorInvalidNonce"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidNonce/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorInvalidNonce"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidElement/title",
          "value": "PKIdentityErrorInvalidElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1invalidElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorInvalidElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1noElementsRequested/title",
          "value": "PKIdentityErrorNoElementsRequested"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1noElementsRequested/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNoElementsRequested"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1cancelled/title",
          "value": "PKIdentityErrorCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1networkUnavailable/title",
          "value": "PKIdentityErrorNetworkUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1networkUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNetworkUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1unknown/title",
          "value": "PKIdentityErrorUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1notSupported/title",
          "value": "PKIdentityErrorNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1requestAlreadyInProgress/title",
          "value": "PKIdentityErrorRequestAlreadyInProgress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKIdentityError-swift.struct~1Code~1requestAlreadyInProgress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKIdentityErrorRequestAlreadyInProgress"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkidentityerror-swift.struct/code/invalidnonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkidentityerror-swift.struct/code/invalidnonce"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
