{
  "abstract": [
    {
      "text": "The current date selection method of the calendar view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/selectionBehavior"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICalendarView(py)selectionBehavior",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "selectionBehavior"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UICalendarSelection",
        "text": "UICalendarSelection"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "selectionBehavior"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "selectionBehavior"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "selectionBehavior"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UICalendarSelection",
              "text": "UICalendarSelection"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection": {
      "abstract": [
        {
          "text": "A base object that tracks one or more dates a user selects from a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarSelection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarSelection"
        }
      ],
      "role": "symbol",
      "title": "UICalendarSelection",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionMultiDate": {
      "abstract": [
        {
          "text": "An object that tracks multiple dates the user selects from a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarSelectionMultiDate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionMultiDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarSelectionMultiDate"
        }
      ],
      "role": "symbol",
      "title": "UICalendarSelectionMultiDate",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarselectionmultidate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionSingleDate": {
      "abstract": [
        {
          "text": "An object that tracks a date the user selects from a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarSelectionSingleDate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionSingleDate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarSelectionSingleDate"
        }
      ],
      "role": "symbol",
      "title": "UICalendarSelectionSingleDate",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarselectionsingledate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionWeekOfYear": {
      "abstract": [
        {
          "text": "An object that tracks a specific week a person selects from a calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarSelectionWeekOfYear"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionWeekOfYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarSelectionWeekOfYear"
        }
      ],
      "role": "symbol",
      "title": "UICalendarSelectionWeekOfYear",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarselectionweekofyear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView": {
      "abstract": [
        {
          "text": "A view that displays a calendar with date-specific decorations, and provides for user selection of a single date or multiple dates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarView"
        }
      ],
      "role": "symbol",
      "title": "UICalendarView",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView/selectionBehavior": {
      "abstract": [
        {
          "text": "The current date selection method of the calendar view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionBehavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICalendarSelection",
          "text": "UICalendarSelection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView/selectionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionBehavior"
        }
      ],
      "role": "symbol",
      "title": "selectionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview/selectionbehavior"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-date-selections",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionSingleDate",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionMultiDate",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionWeekOfYear",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection"
      ],
      "title": "Handling date selections"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "selectionBehavior"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UICalendarView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-date-selections",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionSingleDate",
                "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionMultiDate",
                "doc://com.apple.uikit/documentation/UIKit/UICalendarSelectionWeekOfYear",
                "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection"
              ],
              "title": "Handling date selections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "strong"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarSelection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UICalendarSelection",
                    "text": "UICalendarSelection"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "selectionBehavior"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1selectionBehavior/title",
          "value": "selectionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView~1selectionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/title",
          "value": "UICalendarView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelection/title",
          "value": "UICalendarSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionWeekOfYear/title",
          "value": "UICalendarSelectionWeekOfYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionWeekOfYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionWeekOfYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionWeekOfYear/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionWeekOfYear"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionSingleDate/title",
          "value": "UICalendarSelectionSingleDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionSingleDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionSingleDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionSingleDate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionSingleDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionMultiDate/title",
          "value": "UICalendarSelectionMultiDate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionMultiDate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionMultiDate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarSelectionMultiDate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarSelectionMultiDate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicalendarview/selectionbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicalendarview/selectionbehavior"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
