{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Errors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Link Presentation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "LinkPresentation Errors"
  },
  "references": {
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation": {
      "abstract": [
        {
          "text": "Fetch, provide, and present rich links in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
      "kind": "symbol",
      "role": "collection",
      "title": "Link Presentation",
      "type": "topic",
      "url": "/documentation/linkpresentation"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError": {
      "abstract": [
        {
          "text": "An error returned by the LinkPresentation framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "role": "symbol",
      "title": "LPError",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from LinkPresentation APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Link Presentation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "LPErrorDomain",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperrordomain"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Macros": {
      "abstract": [],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "LinkPresentation Macros",
      "type": "topic",
      "url": "/documentation/linkpresentation/macros"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Macros"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Errors",
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Errors",
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
              ],
              "title": "Errors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Macros"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/title",
          "value": "LPErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/title",
          "value": "LPErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/linkpresentation/errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/linkpresentation/errors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
