{
  "abstract": [
    {
      "text": "An error returned by the LinkPresentation framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:SC11LPErrorCodeLeV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "LPError"
      }
    ],
    "modules": [
      {
        "name": "Link Presentation"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "LPError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "LPError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "LPError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation": {
      "abstract": [
        {
          "text": "Fetch, provide, and present rich links in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
      "kind": "symbol",
      "role": "collection",
      "title": "Link Presentation",
      "type": "topic",
      "url": "/documentation/linkpresentation"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError": {
      "abstract": [
        {
          "text": "An error returned by the LinkPresentation framework.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPError"
        }
      ],
      "role": "symbol",
      "title": "LPError",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code": {
      "abstract": [
        {
          "text": "Possible error values that can be returned from LinkPresentation APIs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "LPError.Code",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/code"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorCode": {
      "abstract": [
        {
          "text": "A code for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorCode",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorCode",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/errorcode"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorDomain": {
      "abstract": [
        {
          "text": "The domain for the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorDomain",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/errordomain"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorUserInfo": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorUserInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorUserInfo",
      "kind": "symbol",
      "role": "symbol",
      "title": "errorUserInfo",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/erroruserinfo"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchCancelled": {
      "abstract": [
        {
          "text": "An error indicating that the metadata fetch was canceled by the client.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchCancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11LPErrorCodeLeV",
          "text": "LPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchCancelled",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadataFetchCancelled",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/metadatafetchcancelled"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchFailed": {
      "abstract": [
        {
          "text": "An error indicating that a metadata fetch failed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchFailed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11LPErrorCodeLeV",
          "text": "LPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchFailed",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadataFetchFailed",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/metadatafetchfailed"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchNotAllowed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchNotAllowed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11LPErrorCodeLeV",
          "text": "LPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchNotAllowed",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadataFetchNotAllowed",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/metadatafetchnotallowed"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchTimedOut": {
      "abstract": [
        {
          "text": "An error indicating that the metadata fetch took longer than allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataFetchTimedOut"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11LPErrorCodeLeV",
          "text": "LPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchTimedOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "metadataFetchTimedOut",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/metadatafetchtimedout"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/unknown": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SC11LPErrorCodeLeV",
          "text": "LPError"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@LPErrorCode",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/unknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "unknown",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperror/unknown"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain": {
      "abstract": [
        {
          "text": "The domain for Link Presentation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LPErrorDomain"
        }
      ],
      "role": "symbol",
      "title": "LPErrorDomain",
      "type": "topic",
      "url": "/documentation/linkpresentation/lperrordomain"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP": {
      "abstract": [
        {
          "text": "A specialized error that provides a domain, error code, and user-info dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "CustomNSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomNSError",
      "type": "topic",
      "url": "/documentation/foundation/customnserror"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:10Foundation13CustomNSErrorP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s5ErrorP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Errors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
      ],
      "title": "Errors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Error-details",
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorCode",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorUserInfo"
      ],
      "title": "Error details"
    },
    {
      "anchor": "Error-domain",
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/errorDomain",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPErrorDomain"
      ],
      "title": "Error domain"
    },
    {
      "anchor": "Error-codes",
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchCancelled",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchFailed",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchTimedOut",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/unknown",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/Code"
      ],
      "title": "Error codes"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LPError/metadataFetchNotAllowed"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/title",
          "value": "LPErrorDomain"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPErrorDomain/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorDomain"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/title",
          "value": "LPErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Link-Presentation~1documentation~1LinkPresentation~1LPError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LPErrorCode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/linkpresentation/lperror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
