{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Link Presentation"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "LinkPresentation Macros"
  },
  "references": {
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation": {
      "abstract": [
        {
          "text": "Fetch, provide, and present rich links in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation",
      "kind": "symbol",
      "role": "collection",
      "title": "Link Presentation",
      "type": "topic",
      "url": "/documentation/linkpresentation"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Errors": {
      "abstract": [],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Errors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "LinkPresentation Errors",
      "type": "topic",
      "url": "/documentation/linkpresentation/errors"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LP_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "LP_EXTERN",
      "type": "topic",
      "url": "/documentation/linkpresentation/lp_extern"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LP_EXTERN_C"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C",
      "kind": "symbol",
      "role": "symbol",
      "title": "LP_EXTERN_C",
      "type": "topic",
      "url": "/documentation/linkpresentation/lp_extern_c"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LP_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "LP_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/linkpresentation/lp_extern_c_begin"
    },
    "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LP_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "LP_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/linkpresentation/lp_extern_c_end"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Errors"
      ],
      "title": "Reference"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_BEGIN",
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/LP_EXTERN_C_END"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.Link-Presentation/documentation/LinkPresentation/Errors"
              ],
              "title": "Reference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/linkpresentation/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/linkpresentation/macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
