{
  "abstract": [
    {
      "text": "Creates a monogram content view with the configuration you specify.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.tvuikit/documentation/TVUIKit",
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView/initWithConfiguration:"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)TVMonogramContentView(im)initWithConfiguration:",
    "fragments": [
      {
        "kind": "text",
        "text": "- "
      },
      {
        "kind": "identifier",
        "text": "initWithConfiguration:"
      }
    ],
    "modules": [
      {
        "name": "TVUIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithConfiguration:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "initWithConfiguration:"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentConfiguration-c.class",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)TVMonogramContentConfiguration",
              "text": "TVMonogramContentConfiguration"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "configuration"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The configuration you specify to supply its styling and content.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "configuration"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit": {
      "abstract": [
        {
          "text": "Show common user interface elements from Apple TV in your native app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "TVUIKit",
      "type": "topic",
      "url": "/documentation/tvuikit"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a monogram view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "TVMonogramContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "TVMonogramContentConfiguration",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramcontentconfiguration-c.class"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView": {
      "abstract": [
        {
          "text": "A view that contains a circular image of a person or the person’s initials.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TVMonogramContentView"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TVMonogramContentView"
        }
      ],
      "role": "symbol",
      "title": "TVMonogramContentView",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramcontentview"
    },
    "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView/initWithConfiguration:": {
      "abstract": [
        {
          "text": "Creates a monogram content view with the configuration you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentView/initWithConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "initWithConfiguration:",
      "type": "topic",
      "url": "/documentation/tvuikit/tvmonogramcontentview/initwithconfiguration:"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Monogram-Content-View",
      "generated": true,
      "identifiers": [
        "doc://com.apple.tvuikit/documentation/TVUIKit/TVMonogramContentConfiguration-c.class"
      ],
      "title": "Creating a Monogram Content View"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/title",
          "value": "TVMonogramContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.tvuikit~1documentation~1TVUIKit~1TVMonogramContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "TVMonogramContentView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/tvuikit/tvmonogramcontentview/initwithconfiguration:"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
