{
  "abstract": [
    {
      "text": "An experience that bypasses system-provided audio spatialization.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "s:So14AVAudioSessionC12AVFoundationE25BypassedSpatialExperienceV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "BypassedSpatialExperience"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "BypassedSpatialExperience"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVAudioSession.BypassedSpatialExperience"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "BypassedSpatialExperience"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy": {
      "abstract": [
        {
          "text": "Constants that specify how to set the origin of audio in a head-tracked spatial experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchoringStrategy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnchoringStrategy"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.AnchoringStrategy",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/anchoringstrategy"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience that bypasses system-provided audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BypassedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BypassedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.BypassedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/bypassedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience where the sound has a size dictated by its sound stage and is head-locked relative to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FixedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FixedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.FixedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/fixedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience where the sound a size dictated by its sound stage and location dictated by its anchoring strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HeadTrackedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HeadTrackedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.HeadTrackedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/headtrackedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize": {
      "abstract": [
        {
          "text": "Constants that specify the perceived size of sounds the audio session plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.SoundStageSize",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/soundstagesize"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe": {
      "abstract": [
        {
          "text": "The spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intendedSpatialExperience"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation31AVAudioSessionSpatialExperienceP",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperience-1qwbe"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        }
      ],
      "role": "symbol",
      "title": "isNowPlayingCandidate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/isnowplayingcandidate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)": {
      "abstract": [
        {
          "text": "Sets the spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation31AVAudioSessionSpatialExperienceP",
          "text": "AVAudioSessionSpatialExperience"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setIntendedSpatialExperience(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setintendedspatialexperience(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate:error:"
        }
      ],
      "role": "symbol",
      "title": "setIsNowPlayingCandidate(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience": {
      "abstract": [
        {
          "text": "A protocol that defines types of spatial audio experiences that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAudioSessionSpatialExperience"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:12AVFoundation31AVAudioSessionSpatialExperienceP": {
      "abstract": [
        {
          "text": "A protocol that defines types of spatial audio experiences that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:12AVFoundation31AVAudioSessionSpatialExperienceP",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAudioSessionSpatialExperience"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:12AVFoundation31AVAudioSessionSpatialExperienceP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-spatial-experience-in-visionOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe",
        "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"
      ],
      "title": "Configuring the spatial experience in visionOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title",
          "value": "AVAudioSessionSoundStageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/title",
          "value": "setIsNowPlayingCandidate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIsNowPlayingCandidate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/title",
          "value": "isNowPlayingCandidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isNowPlayingCandidate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/bypassedspatialexperience"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
