{
  "abstract": [
    {
      "text": "Audio session category identifiers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@T@AVAudioSessionCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Category"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Category"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AVAudioSession.Category"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Category"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An audio session category defines a set of audio behaviors. Choose a category that most accurately describes the audio behavior you require.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Supporting-AirPlay",
          "level": 3,
          "text": "Supporting AirPlay",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The playback-only categories (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/ambient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/soloAmbient",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") support both the mirrored and nonmirrored variants of AirPlay.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The audio session category ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playAndRecord",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " supports only the mirrored variant of AirPlay, while the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/record",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/multiRoute",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " categories don’t allow routing to AirPlay.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "SharePlay and the Group Activities API only support audio sessions using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " category. Attempting to activate a session that uses an unsupported category results in an error.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct": {
      "abstract": [
        {
          "text": "Audio session category identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.Category",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/ambient": {
      "abstract": [
        {
          "text": "The category for an app in which sound playback is nonprimary — that is, your app also works with the sound turned off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ambient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/ambient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryAmbient"
        }
      ],
      "role": "symbol",
      "title": "ambient",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/ambient"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/audioProcessing": {
      "abstract": [
        {
          "text": "The category for using an audio hardware codec or signal processor while not playing or recording audio.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "audioProcessing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/audioProcessing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryAudioProcessing"
        }
      ],
      "role": "symbol",
      "title": "audioProcessing",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/audioprocessing"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the raw value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/multiRoute": {
      "abstract": [
        {
          "text": "The category for routing distinct streams of audio data to different output devices at the same time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiRoute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/multiRoute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryMultiRoute"
        }
      ],
      "role": "symbol",
      "title": "multiRoute",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/multiroute"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playAndRecord": {
      "abstract": [
        {
          "text": "The category for recording (input) and playback (output) of audio, such as for a Voice over Internet Protocol (VoIP) app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playAndRecord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playAndRecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryPlayAndRecord"
        }
      ],
      "role": "symbol",
      "title": "playAndRecord",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/playandrecord"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback": {
      "abstract": [
        {
          "text": "The category for playing recorded music or other sounds that are central to the successful use of your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryPlayback"
        }
      ],
      "role": "symbol",
      "title": "playback",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/playback"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/record": {
      "abstract": [
        {
          "text": "The category for recording audio while also silencing playback audio.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "record"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/record",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategoryRecord"
        }
      ],
      "role": "symbol",
      "title": "record",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/record"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/soloAmbient": {
      "abstract": [
        {
          "text": "The default audio session category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "soloAmbient"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/soloAmbient",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionCategorySoloAmbient"
        }
      ],
      "role": "symbol",
      "title": "soloAmbient",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.struct/soloambient"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct": {
      "abstract": [
        {
          "text": "Constants that specify optional audio behaviors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CategoryOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CategoryOptions"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.CategoryOptions",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/categoryoptions-swift.struct"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/availableCategories": {
      "abstract": [
        {
          "text": "The audio session categories available on the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableCategories"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/availableCategories",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableCategories"
        }
      ],
      "role": "symbol",
      "title": "availableCategories",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/availablecategories"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/category-swift.property": {
      "abstract": [
        {
          "text": "The current audio session category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AVAudioSessionCategory",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/category-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "category"
        }
      ],
      "role": "symbol",
      "title": "category",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/category-swift.property"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/categoryOptions-swift.property": {
      "abstract": [
        {
          "text": "The set of options associated with the current audio session category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AVAudioSession",
          "text": "AVAudioSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AVAudioSessionCategoryOptions",
          "text": "CategoryOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/categoryOptions-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "categoryOptions"
        }
      ],
      "role": "symbol",
      "title": "categoryOptions",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/categoryoptions-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Inspecting-the-category-configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/category-swift.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/availableCategories",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/categoryOptions-swift.property",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct"
      ],
      "title": "Inspecting the category configuration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Category",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/init(rawValue:)"
      ],
      "title": "Creating a Category"
    },
    {
      "anchor": "Getting-Standard-Categories",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/ambient",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/multiRoute",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playAndRecord",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/record",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/soloAmbient",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/audioProcessing"
      ],
      "title": "Getting Standard Categories"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-Standard-Categories",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/ambient",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/multiRoute",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playAndRecord",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/record",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/soloAmbient",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/audioProcessing"
              ],
              "title": "Getting Standard Categories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Inspecting-the-category-configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/category-swift.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/availableCategories",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/categoryOptions-swift.property",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct"
              ],
              "title": "Inspecting the category configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionCategory"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1category-swift.property/title",
          "value": "category"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1category-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1availableCategories/title",
          "value": "availableCategories"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1availableCategories/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableCategories"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/title",
          "value": "AVAudioSessionCategoryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/title",
          "value": "AVAudioSessionCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/title",
          "value": "AVAudioSessionCategoryPlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryPlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playAndRecord/title",
          "value": "AVAudioSessionCategoryPlayAndRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playAndRecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryPlayAndRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1audioProcessing/title",
          "value": "AVAudioSessionCategoryAudioProcessing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1audioProcessing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryAudioProcessing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1soloAmbient/title",
          "value": "AVAudioSessionCategorySoloAmbient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1soloAmbient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategorySoloAmbient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1multiRoute/title",
          "value": "AVAudioSessionCategoryMultiRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1multiRoute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryMultiRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1ambient/title",
          "value": "AVAudioSessionCategoryAmbient"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1ambient/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryAmbient"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1categoryOptions-swift.property/title",
          "value": "categoryOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1categoryOptions-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "categoryOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1record/title",
          "value": "AVAudioSessionCategoryRecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1record/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionCategoryRecord"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/category-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/category-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
