{
  "abstract": [
    {
      "text": "The spatial audio experience your app intends to provide the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AVAudioSession(py)intendedSpatialExperience",
    "fragments": [
      {
        "kind": "identifier",
        "text": "intendedSpatialExperience"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "intendedSpatialExperience"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "intendedSpatialExperience"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AVAudioSessionSpatialExperience",
              "text": "AVAudioSessionSpatialExperience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "intendedSpatialExperience"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize": {
      "abstract": [
        {
          "text": "Constants that specify the perceived size of sounds the audio session plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.SoundStageSize",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/soundstagesize"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty": {
      "abstract": [
        {
          "text": "The spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "intendedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperience-qlty"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions": {
      "abstract": [
        {
          "text": "A dictionary of options that customize the spatial experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "intendedSpatialExperienceOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperienceOptions",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperienceoptions"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        }
      ],
      "role": "symbol",
      "title": "isNowPlayingCandidate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/isnowplayingcandidate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:": {
      "abstract": [
        {
          "text": "Sets the spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience:options:error:"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience:options:error:"
        }
      ],
      "role": "symbol",
      "title": "setIntendedSpatialExperience:options:error:",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setintendedspatialexperience:options:error:"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate:error:"
        }
      ],
      "role": "symbol",
      "title": "setIsNowPlayingCandidate(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialexperience"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-spatial-experience-in-visionOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"
      ],
      "title": "Configuring the spatial experience in visionOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title",
          "value": "AVAudioSessionSoundStageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/title",
          "value": "setIsNowPlayingCandidate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIsNowPlayingCandidate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/title",
          "value": "isNowPlayingCandidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isNowPlayingCandidate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/intendedspatialexperience-qlty"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
