{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session."}],"metadata":{"role":"symbol","modules":[{"name":"AVFAudio"}],"symbolKind":"property","externalID":"c:objc(cs)AVAudioSession(py)isNowPlayingCandidate","navigatorTitle":[{"text":"isNowPlayingCandidate","kind":"identifier"}],"platforms":[{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"roleHeading":"Instance Property","extendedModule":"AVFAudio","title":"isNowPlayingCandidate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNowPlayingCandidate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNowPlayingCandidate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool","identifier":"doc://com.externally.resolved.symbol/s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"Discussion","type":"heading"},{"inlineContent":[{"text":"Only a single audio session for an app can be a Now Playing candidate. Designating multiple audio sessions for the same app as Now Playing candidates results in none of them being eligible.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avfaudio/avaudiosession/isnowplayingcandidate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avfaudio/avaudiosession/isnowplayingcandidate"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe","doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"],"anchor":"Configuring-the-spatial-experience-in-visionOS","title":"Configuring the spatial experience in visionOS"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"]]},"identifier":{"url":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate","interfaceLanguage":"swift"},"references":{"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIntendedSpatialExperience:options:error:"}],"url":"/documentation/avfaudio/avaudiosession/setintendedspatialexperience:options:error:","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setIntendedSpatialExperience:options:error:"}],"abstract":[{"type":"text","text":"Sets the spatial audio experience your app intends to provide the user."}],"title":"setIntendedSpatialExperience:options:error:","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience":{"type":"topic","abstract":[{"type":"text","text":"An experience where the sound has a size dictated by its sound stage and is head-locked relative to the user."}],"url":"/documentation/avfaudio/avaudiosession/fixedspatialexperience","title":"AVAudioSession.FixedSpatialExperience","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FixedSpatialExperience"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FixedSpatialExperience"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","title":"BOOL","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate":{"abstract":[{"text":"A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNowPlayingCandidate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/avfaudio/avaudiosession/isnowplayingcandidate","navigatorTitle":[{"text":"isNowPlayingCandidate","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate","title":"isNowPlayingCandidate","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIntendedSpatialExperience","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"AVAudioSessionSpatialExperience","kind":"typeIdentifier","preciseIdentifier":"s:12AVFoundation31AVAudioSessionSpatialExperienceP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"setIntendedSpatialExperience(_:)","url":"/documentation/avfaudio/avaudiosession/setintendedspatialexperience(_:)","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)","abstract":[{"text":"Sets the spatial audio experience your app intends to provide the user.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)":{"abstract":[{"type":"text","text":"Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIsNowPlayingCandidate"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)","title":"setIsNowPlayingCandidate(_:)","url":"/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)","navigatorTitle":[{"kind":"identifier","text":"setIsNowPlayingCandidate:error:"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnchoringStrategy"}],"role":"symbol","abstract":[{"type":"text","text":"Constants that specify how to set the origin of audio in a head-tracked spatial experience."}],"navigatorTitle":[{"kind":"identifier","text":"AnchoringStrategy"}],"title":"AVAudioSession.AnchoringStrategy","url":"/documentation/avfaudio/avaudiosession/anchoringstrategy","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AVAudioSessionSpatialExperience"}],"identifier":"doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience","title":"AVAudioSessionSpatialExperience","abstract":[{"type":"text","text":"A protocol that defines types of spatial audio experiences that the system supports."}],"kind":"symbol","url":"/documentation/AVFoundation/AVAudioSessionSpatialExperience","role":"symbol","type":"topic"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AVAudioSession","kind":"identifier"}],"url":"/documentation/avfaudio/avaudiosession","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AVAudioSession","kind":"identifier"}],"abstract":[{"text":"An object that communicates to the system how you intend to use audio in your app.","type":"text"}],"title":"AVAudioSession","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize":{"abstract":[{"text":"Constants that specify the perceived size of sounds the audio session plays.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SoundStageSize","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize","role":"symbol","navigatorTitle":[{"text":"SoundStageSize","kind":"identifier"}],"kind":"symbol","url":"/documentation/avfaudio/avaudiosession/soundstagesize","title":"AVAudioSession.SoundStageSize","type":"topic"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions","fragments":[{"text":"intendedSpatialExperienceOptions","kind":"identifier"}],"title":"intendedSpatialExperienceOptions","type":"topic","url":"/documentation/avfaudio/avaudiosession/intendedspatialexperienceoptions","role":"symbol","abstract":[{"type":"text","text":"A dictionary of options that customize the spatial experience."}],"kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio":{"url":"/documentation/avfaudio","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio","title":"AVFAudio","type":"topic","abstract":[{"text":"Play, record, and process audio; configure your app’s system audio behavior.","type":"text"}],"role":"collection"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intendedSpatialExperience","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"AVAudioSessionSpatialExperience","preciseIdentifier":"s:12AVFoundation31AVAudioSessionSpatialExperienceP","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The spatial audio experience your app intends to provide the user."}],"title":"intendedSpatialExperience","url":"/documentation/avfaudio/avaudiosession/intendedspatialexperience-1qwbe","kind":"symbol","type":"topic"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience":{"navigatorTitle":[{"text":"HeadTrackedSpatialExperience","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadTrackedSpatialExperience","kind":"identifier"}],"title":"AVAudioSession.HeadTrackedSpatialExperience","url":"/documentation/avfaudio/avaudiosession/headtrackedspatialexperience","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience","abstract":[{"text":"An experience where the sound a size dictated by its sound stage and location dictated by its anchoring strategy.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"type":"topic","abstract":[{"text":"A value type whose instances are either `true` or `false`.","type":"text"}],"url":"/documentation/Swift/Bool","title":"Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BypassedSpatialExperience","kind":"identifier"}],"navigatorTitle":[{"text":"BypassedSpatialExperience","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience","title":"AVAudioSession.BypassedSpatialExperience","abstract":[{"type":"text","text":"An experience that bypasses system-provided audio spatialization."}],"kind":"symbol","url":"/documentation/avfaudio/avaudiosession/bypassedspatialexperience","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty","fragments":[{"kind":"identifier","text":"intendedSpatialExperience"}],"url":"/documentation/avfaudio/avaudiosession/intendedspatialexperience-qlty","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The spatial audio experience your app intends to provide the user."}],"title":"intendedSpatialExperience","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"value":"isNowPlayingCandidate","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"isNowPlayingCandidate"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"]]},"op":"replace","path":"/hierarchy"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"title":"Configuring the spatial experience in visionOS","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"],"anchor":"Configuring-the-spatial-experience-in-visionOS"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNowPlayingCandidate"},{"kind":"text","text":";"}],"platforms":["visionOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"isNowPlayingCandidate","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/title"},{"op":"replace","value":[{"text":"isNowPlayingCandidate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/fragments"},{"op":"replace","value":"setIsNowPlayingCandidate:error:","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIsNowPlayingCandidate:error:"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/fragments"},{"op":"replace","value":"AVAudioSession","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVAudioSession"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"AVAudioSession"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle"},{"op":"replace","value":"AVAudioSessionSoundStageSize","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title"},{"op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionSoundStageSize"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments"},{"op":"replace","value":[{"text":"AVAudioSessionSoundStageSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}