{
  "abstract": [
    {
      "text": "Constants that indicate the reason for an audio route change.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@E@AVAudioSessionRouteChangeReason",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "RouteChangeReason"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "RouteChangeReason"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "AVAudioSession.RouteChangeReason"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "RouteChangeReason"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants appear as possible values for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionRouteChangeReasonKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in the ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason": {
      "abstract": [
        {
          "text": "Constants that indicate the reason for an audio route change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RouteChangeReason"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "RouteChangeReason"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange": {
      "abstract": [
        {
          "text": "A value that indicates that the category of the session object changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "categoryChange"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonCategoryChange"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.categoryChange",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/categorychange"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/init(rawvalue:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable": {
      "abstract": [
        {
          "text": "A value that indicates a user action, such as plugging in a headset, has made a preferred audio route available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newDeviceAvailable"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.newDeviceAvailable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/newdeviceavailable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory": {
      "abstract": [
        {
          "text": "A value that indicates that the route changed because no suitable route is now available for the specified category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noSuitableRouteForCategory"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.noSuitableRouteForCategory",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/nosuitablerouteforcategory"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable": {
      "abstract": [
        {
          "text": "A value that indicates that the previous audio output path is no longer available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oldDeviceUnavailable"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.oldDeviceUnavailable",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/olddeviceunavailable"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override": {
      "abstract": [
        {
          "text": "A value that indicates that the output route was overridden by the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "override"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonOverride"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.override",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/override"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange": {
      "abstract": [
        {
          "text": "A value that indicates that the configuration for a set of I/O ports has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeConfigurationChange"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.routeConfigurationChange",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/routeconfigurationchange"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown": {
      "abstract": [
        {
          "text": "A value that indicates the reason for the change is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonUnknown"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.unknown",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/unknown"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep": {
      "abstract": [
        {
          "text": "A value that indicates that the route changed when the device woke up from sleep.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wakeFromSleep"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonWakeFromSleep"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.RouteChangeReason.wakeFromSleep",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangereason/wakefromsleep"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when its audio route changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "routeChangeNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangenotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionRouteChangeReasonKey": {
      "abstract": [
        {
          "text": "A user info key that’s used to retrieve the route change reason.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionRouteChangeReasonKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeReasonKey"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionRouteChangeReasonKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionroutechangereasonkey"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes": {
      "abstract": [
        {
          "text": "Observe audio session notifications to ensure that your app responds appropriately to route changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/responding-to-audio-route-changes",
      "kind": "article",
      "role": "article",
      "title": "Responding to audio route changes",
      "type": "topic",
      "url": "/documentation/avfaudio/responding-to-audio-route-changes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Route-Change-Reasons",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange"
      ],
      "title": "Route Change Reasons"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionRouteChangeReason"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Route-Change-Reasons",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/unknown",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/newDeviceAvailable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/oldDeviceUnavailable",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/categoryChange",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/override",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/wakeFromSleep",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/noSuitableRouteForCategory",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteChangeReason/routeConfigurationChange"
              ],
              "title": "Route Change Reasons"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionRouteChangeReason"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1noSuitableRouteForCategory/title",
          "value": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1noSuitableRouteForCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1routeChangeNotification/title",
          "value": "AVAudioSessionRouteChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1routeChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1wakeFromSleep/title",
          "value": "AVAudioSessionRouteChangeReasonWakeFromSleep"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1wakeFromSleep/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonWakeFromSleep"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1categoryChange/title",
          "value": "AVAudioSessionRouteChangeReasonCategoryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1categoryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonCategoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1unknown/title",
          "value": "AVAudioSessionRouteChangeReasonUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1newDeviceAvailable/title",
          "value": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1newDeviceAvailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonNewDeviceAvailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1oldDeviceUnavailable/title",
          "value": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1oldDeviceUnavailable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonOldDeviceUnavailable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1override/title",
          "value": "AVAudioSessionRouteChangeReasonOverride"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1override/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonOverride"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionRouteChangeReasonKey/title",
          "value": "AVAudioSessionRouteChangeReasonKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionRouteChangeReasonKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1routeConfigurationChange/title",
          "value": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason~1routeConfigurationChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReasonRouteConfigurationChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/title",
          "value": "AVAudioSessionRouteChangeReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteChangeReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeReason"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routechangereason"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/routechangereason"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
