{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"seeAlsoSections":[{"anchor":"Configuring-standard-audio-behaviors","title":"Configuring standard audio behaviors","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:options:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:options:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setMode(_:)"],"generated":true}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCategory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"category","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"Category","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"Mode","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"RouteSharingPolicy","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"CategoryOptions","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions"},{"text":" = []) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]},{"kind":"parameters","parameters":[{"name":"category","content":[{"type":"paragraph","inlineContent":[{"text":"The category to apply to the audio session. See ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct","type":"reference"},{"text":" for supported category values.","type":"text"}]}]},{"name":"mode","content":[{"inlineContent":[{"text":"The audio session mode to apply to the audio session. For a list of values, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"policy","content":[{"inlineContent":[{"type":"text","text":"The route-sharing policy to apply to the audio session. For a list of values, see "},{"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"text":"A mask of additional options for handling audio. For a list of constants, see ","type":"text"},{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"text":"You specify options only with a default routing policy. With a long-form route-sharing policy, you can use the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback"},{"text":" category and the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/default"},{"text":", ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/moviePlayback"},{"text":", and ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/spokenAudio"},{"text":" modes.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/avfaudio/avaudiosession/setcategory(_:mode:policy:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/avfaudio/avaudiosession/setcategory(_:mode:policy:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:objc(cs)AVAudioSession(im)setCategory:mode:routeSharingPolicy:options:error:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setCategory","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVAudioSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession"},{"text":".","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode"},{"text":", ","kind":"text"},{"text":"policy","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","text":"RouteSharingPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"setCategory(_:mode:policy:options:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setCategory:mode:routeSharingPolicy:options:error:"}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false},{"name":"watchOS","introducedAt":"5.0","unavailable":false,"deprecated":false,"beta":false}],"modules":[{"name":"AVFAudio"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:policy:options:)"},"abstract":[{"text":"Sets the session category, mode, route-sharing policy, and options.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"]]},"references":{"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:)":{"type":"topic","title":"setCategory(_:)","abstract":[{"type":"text","text":"Sets the audio session’s category."}],"navigatorTitle":[{"kind":"identifier","text":"setCategory:error:"}],"role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setCategory"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","kind":"typeIdentifier","text":"Category"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"/documentation/avfaudio/avaudiosession/setcategory(_:)"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/default":{"kind":"symbol","type":"topic","url":"/documentation/avfaudio/avaudiosession/mode-swift.struct/default","navigatorTitle":[{"text":"AVAudioSessionModeDefault","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The default audio session mode."}],"title":"default","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/default"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Category"}],"kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct","url":"/documentation/avfaudio/avaudiosession/category-swift.struct","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Category"}],"abstract":[{"type":"text","text":"Audio session category identifiers."}],"title":"AVAudioSession.Category"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:options:)":{"role":"symbol","kind":"symbol","type":"topic","url":"/documentation/avfaudio/avaudiosession/setcategory(_:options:)","title":"setCategory(_:options:)","navigatorTitle":[{"kind":"identifier","text":"setCategory:withOptions:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategory"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","kind":"typeIdentifier","text":"Category"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","kind":"typeIdentifier","text":"CategoryOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Sets the audio session’s category with the specified options.","type":"text"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:options:)"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:policy:options:)":{"type":"topic","title":"setCategory(_:mode:policy:options:)","abstract":[{"text":"Sets the session category, mode, route-sharing policy, and options.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setCategory:mode:routeSharingPolicy:options:error:"}],"role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:policy:options:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategory"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","kind":"typeIdentifier","text":"Category"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","kind":"typeIdentifier","text":"RouteSharingPolicy"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","kind":"typeIdentifier","text":"CategoryOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"/documentation/avfaudio/avaudiosession/setcategory(_:mode:policy:options:)"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/spokenAudio":{"type":"topic","abstract":[{"type":"text","text":"A mode used for continuous spoken audio to pause the audio when another app plays a short audio prompt."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spokenAudio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVAudioSession","preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier"}],"kind":"symbol","url":"/documentation/avfaudio/avaudiosession/mode-swift.struct/spokenaudio","navigatorTitle":[{"text":"AVAudioSessionModeSpokenAudio","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/spokenAudio","title":"spokenAudio","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:options:)":{"type":"topic","title":"setCategory(_:mode:options:)","url":"/documentation/avfaudio/avaudiosession/setcategory(_:mode:options:)","role":"symbol","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:options:)","abstract":[{"text":"Sets the audio session’s category, mode, and options.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCategory"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionMode","text":"Mode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"CategoryOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"setCategory:mode:options:error:"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","title":"BOOL","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AVAudioSession","kind":"identifier"}],"url":"/documentation/avfaudio/avaudiosession","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AVAudioSession","kind":"identifier"}],"abstract":[{"text":"An object that communicates to the system how you intend to use audio in your app.","type":"text"}],"title":"AVAudioSession","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/moviePlayback":{"type":"topic","abstract":[{"type":"text","text":"A mode that indicates that your app is playing back movie content."}],"url":"/documentation/avfaudio/avaudiosession/mode-swift.struct/movieplayback","title":"moviePlayback","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct/moviePlayback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AVAudioSessionModeMoviePlayback"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"moviePlayback"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier","text":"Mode"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RouteSharingPolicy","kind":"identifier"}],"title":"AVAudioSession.RouteSharingPolicy","url":"/documentation/avfaudio/avaudiosession/routesharingpolicy-swift.enum","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum","type":"topic","abstract":[{"text":"Cases that indicate the possible route-sharing policies for an audio session.","type":"text"}],"navigatorTitle":[{"text":"RouteSharingPolicy","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback":{"navigatorTitle":[{"kind":"identifier","text":"AVAudioSessionCategoryPlayback"}],"title":"playback","url":"/documentation/avfaudio/avaudiosession/category-swift.struct/playback","abstract":[{"type":"text","text":"The category for playing recorded music or other sounds that are central to the successful use of your app."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"playback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioSession","text":"AVAudioSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@AVAudioSessionCategory","text":"Category"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct/playback","role":"symbol","type":"topic"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"Mode"}],"title":"AVAudioSession.Mode","url":"/documentation/avfaudio/avaudiosession/mode-swift.struct","abstract":[{"type":"text","text":"Audio session mode identifiers."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Mode"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"type":"topic","url":"/documentation/foundation/nserror","kind":"symbol","title":"NSError","abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}]},"doc://com.apple.avfaudio/documentation/AVFAudio":{"url":"/documentation/avfaudio","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio","title":"AVFAudio","type":"topic","abstract":[{"text":"Play, record, and process audio; configure your app’s system audio behavior.","type":"text"}],"role":"collection"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CategoryOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CategoryOptions"}],"role":"symbol","type":"topic","title":"AVAudioSession.CategoryOptions","url":"/documentation/avfaudio/avaudiosession/categoryoptions-swift.struct","abstract":[{"text":"Constants that specify optional audio behaviors.","type":"text"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setMode(_:)":{"abstract":[{"text":"Sets the audio session’s mode.","type":"text"}],"url":"/documentation/avfaudio/avaudiosession/setmode(_:)","navigatorTitle":[{"kind":"identifier","text":"setMode:error:"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setMode(_:)","title":"setMode(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMode"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVAudioSession","kind":"typeIdentifier","text":"AVAudioSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@AVAudioSessionMode","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.apple.documentation/documentation/foundation/nserror":{"type":"topic","role":"symbol","url":"/documentation/foundation/nserror","identifier":"doc://com.apple.documentation/documentation/foundation/nserror","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"title":"NSError","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"11.0"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1"},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false,"introducedAt":"11.0"},{"beta":false,"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0"},{"beta":false,"unavailable":false,"name":"watchOS","deprecated":false,"introducedAt":"5.0"}],"path":"/metadata/platforms"},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Method"},{"op":"replace","path":"/metadata/title","value":"setCategory:mode:routeSharingPolicy:options:error:"},{"op":"replace","path":"/metadata/symbolKind","value":"method"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCategory:mode:routeSharingPolicy:options:error:"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Configuring standard audio behaviors","anchor":"Configuring-standard-audio-behaviors","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:mode:options:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:options:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setCategory(_:)","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setMode(_:)"],"generated":true}]},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setCategory:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AVAudioSessionCategory","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct","kind":"typeIdentifier","text":"AVAudioSessionCategory"},{"kind":"text","text":") "},{"kind":"internalParam","text":"category"},{"kind":"text","text":" "},{"kind":"identifier","text":"mode:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@AVAudioSessionMode","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct","kind":"typeIdentifier","text":"AVAudioSessionMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":" "},{"kind":"identifier","text":"routeSharingPolicy:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AVAudioSessionRouteSharingPolicy","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum","kind":"typeIdentifier","text":"AVAudioSessionRouteSharingPolicy"},{"kind":"text","text":") "},{"kind":"internalParam","text":"policy"},{"kind":"text","text":" "},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct","preciseIdentifier":"c:@E@AVAudioSessionCategoryOptions","text":"AVAudioSessionCategoryOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"outError","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}]}},{"op":"replace","path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The category to apply to the audio session. See "},{"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Category-swift.struct","isActive":true},{"type":"text","text":" for supported category values."}]}],"name":"category"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The audio session mode to apply to the audio session. For a list of values, see ","type":"text"},{"type":"reference","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/Mode-swift.struct","isActive":true},{"text":".","type":"text"}]}],"name":"mode"},{"content":[{"inlineContent":[{"type":"text","text":"The route-sharing policy to apply to the audio session. For a list of values, see "},{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/RouteSharingPolicy-swift.enum","isActive":true,"type":"reference"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"policy"},{"content":[{"inlineContent":[{"text":"A mask of additional options for handling audio. For a list of constants, see ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/CategoryOptions-swift.struct"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"options"},{"content":[{"inlineContent":[{"type":"text","text":"On input, a pointer to an error object. If an error occurs, the pointer is an "},{"type":"reference","identifier":"doc://com.apple.documentation/documentation/foundation/nserror","isActive":true},{"type":"text","text":" object that describes the error. If you don’t want error information, pass in "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"outError"}],"kind":"parameters"}},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:)/title","op":"replace","value":"setCategory:error:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCategory:error:"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1default/title","op":"replace","value":"AVAudioSessionModeDefault"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1default/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionModeDefault"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/title","op":"replace","value":"AVAudioSessionCategory"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/fragments","op":"replace","value":[{"text":"AVAudioSessionCategory","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct/navigatorTitle","op":"replace","value":[{"text":"AVAudioSessionCategory","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:options:)/title","op":"replace","value":"setCategory:withOptions:error:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:options:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setCategory:withOptions:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:mode:policy:options:)/title","op":"replace","value":"setCategory:mode:routeSharingPolicy:options:error:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:mode:policy:options:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setCategory:mode:routeSharingPolicy:options:error:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1spokenAudio/title","op":"replace","value":"AVAudioSessionModeSpokenAudio"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1spokenAudio/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionModeSpokenAudio"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:mode:options:)/title","op":"replace","value":"setCategory:mode:options:error:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setCategory(_:mode:options:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCategory:mode:options:error:"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title","op":"replace","value":"AVAudioSession"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments","op":"replace","value":[{"text":"AVAudioSession","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVAudioSession"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1moviePlayback/title","op":"replace","value":"AVAudioSessionModeMoviePlayback"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct~1moviePlayback/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionModeMoviePlayback"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/title","op":"replace","value":"AVAudioSessionRouteSharingPolicy"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionRouteSharingPolicy"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1RouteSharingPolicy-swift.enum/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionRouteSharingPolicy"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/title","op":"replace","value":"AVAudioSessionCategoryPlayback"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Category-swift.struct~1playback/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionCategoryPlayback"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct/title","op":"replace","value":"AVAudioSessionMode"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct/fragments","op":"replace","value":[{"text":"AVAudioSessionMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1Mode-swift.struct/navigatorTitle","op":"replace","value":[{"text":"AVAudioSessionMode","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/title","op":"replace","value":"AVAudioSessionCategoryOptions"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/fragments","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionCategoryOptions"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1CategoryOptions-swift.struct/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AVAudioSessionCategoryOptions"}]},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setMode(_:)/title","op":"replace","value":"setMode:error:"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setMode(_:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMode:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}