{
  "abstract": [
    {
      "text": "Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:objc(cs)AVAudioSession(im)setIsNowPlayingCandidate:error:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "setIsNowPlayingCandidate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "setIsNowPlayingCandidate:error:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "setIsNowPlayingCandidate(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "setIsNowPlayingCandidate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "inValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The new state to set.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "inValue"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Only a single audio session for an app can be a Now Playing candidate. Designating multiple audio sessions for the same app as Now Playing candidates results in none of them being eligible.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy": {
      "abstract": [
        {
          "text": "Constants that specify how to set the origin of audio in a head-tracked spatial experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchoringStrategy"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnchoringStrategy"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.AnchoringStrategy",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/anchoringstrategy"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience that bypasses system-provided audio spatialization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BypassedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BypassedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.BypassedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/bypassedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience where the sound has a size dictated by its sound stage and is head-locked relative to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FixedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FixedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.FixedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/fixedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience": {
      "abstract": [
        {
          "text": "An experience where the sound a size dictated by its sound stage and location dictated by its anchoring strategy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HeadTrackedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HeadTrackedSpatialExperience"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.HeadTrackedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/headtrackedspatialexperience"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize": {
      "abstract": [
        {
          "text": "Constants that specify the perceived size of sounds the audio session plays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SoundStageSize"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession.SoundStageSize",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/soundstagesize"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe": {
      "abstract": [
        {
          "text": "The spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intendedSpatialExperience"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation31AVAudioSessionSpatialExperienceP",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperience-1qwbe"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty": {
      "abstract": [
        {
          "text": "The spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "intendedSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperience",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperience-qlty"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions": {
      "abstract": [
        {
          "text": "A dictionary of options that customize the spatial experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "intendedSpatialExperienceOptions"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "intendedSpatialExperienceOptions",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/intendedspatialexperienceoptions"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "isNowPlayingCandidate"
        }
      ],
      "role": "symbol",
      "title": "isNowPlayingCandidate",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/isnowplayingcandidate"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)": {
      "abstract": [
        {
          "text": "Sets the spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:12AVFoundation31AVAudioSessionSpatialExperienceP",
          "text": "AVAudioSessionSpatialExperience"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "setIntendedSpatialExperience(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setintendedspatialexperience(_:)"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:": {
      "abstract": [
        {
          "text": "Sets the spatial audio experience your app intends to provide the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience:options:error:"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIntendedSpatialExperience:options:error:"
        }
      ],
      "role": "symbol",
      "title": "setIntendedSpatialExperience:options:error:",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setintendedspatialexperience:options:error:"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)": {
      "abstract": [
        {
          "text": "Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setIsNowPlayingCandidate:error:"
        }
      ],
      "role": "symbol",
      "title": "setIsNowPlayingCandidate(_:)",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)"
    },
    "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience": {
      "abstract": [
        {
          "text": "A protocol that defines types of spatial audio experiences that the system supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialExperience"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
      "kind": "symbol",
      "role": "symbol",
      "title": "AVAudioSessionSpatialExperience",
      "type": "topic",
      "url": "/documentation/AVFoundation/AVAudioSessionSpatialExperience"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@BOOL": {
      "abstract": [
        {
          "text": "Type to represent a Boolean value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
      "kind": "symbol",
      "role": "symbol",
      "title": "BOOL",
      "type": "topic",
      "url": "/documentation/objectivec/bool"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-spatial-experience-in-visionOS",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience(_:)",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-1qwbe",
        "doc://com.apple.documentation/documentation/AVFoundation/AVAudioSessionSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/HeadTrackedSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/FixedSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/BypassedSpatialExperience",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/AnchoringStrategy",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate"
      ],
      "title": "Configuring the spatial experience in visionOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "setIsNowPlayingCandidate:error:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIsNowPlayingCandidate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-spatial-experience-in-visionOS",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize",
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate"
              ],
              "title": "Configuring the spatial experience in visionOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "setIsNowPlayingCandidate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@BOOL",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@BOOL",
                    "text": "BOOL"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "inValue"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "error:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "outError"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The new state to set.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "inValue"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On input, a pointer to an error object. If an error occurs, the framework sets the pointer to an ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " object that describes the error. If you don’t want error information, pass in ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "outError"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/title",
          "value": "setIsNowPlayingCandidate:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setIsNowPlayingCandidate:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title",
          "value": "AVAudioSessionSoundStageSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSoundStageSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/title",
          "value": "isNowPlayingCandidate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "isNowPlayingCandidate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
