{"topicSections":[{"anchor":"Options","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption"],"title":"Options"}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Sets the spatial audio experience your app intends to provide the user."}],"seeAlsoSections":[{"anchor":"Configuring-the-spatial-experience-in-visionOS","identifiers":["doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)"],"generated":true,"title":"Configuring the spatial experience in visionOS"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avfaudio/documentation/AVFAudio","doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setIntendedSpatialExperience:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience","preciseIdentifier":"c:@E@AVAudioSessionSpatialExperience","text":"AVAudioSessionSpatialExperience"},{"kind":"text","text":") "},{"kind":"internalParam","text":"intendedSpatialExperience"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["visionOS"]}]},{"parameters":[{"name":"intendedSpatialExperience","content":[{"type":"paragraph","inlineContent":[{"text":"The spatial audio experience to set.","type":"text"}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary of options that customize the experience.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"If an error occurs, an object that provides the details of the error.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"platforms":[{"introducedAt":"1.0","beta":false,"unavailable":false,"deprecated":false,"name":"visionOS"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"setIntendedSpatialExperience:options:error:","kind":"identifier"}],"modules":[{"name":"AVFAudio"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"setIntendedSpatialExperience:options:error:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)AVAudioSession(im)setIntendedSpatialExperience:options:error:","title":"setIntendedSpatialExperience:options:error:"},"identifier":{"url":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:","interfaceLanguage":"occ"},"variants":[{"paths":["/documentation/avfaudio/avaudiosession/setintendedspatialexperience:options:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience":{"role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperience","title":"AVAudioSessionSpatialExperience","kind":"symbol","abstract":[],"url":"/documentation/avfaudio/avaudiosessionspatialexperience","type":"topic","fragments":[{"text":"AVAudioSessionSpatialExperience","kind":"identifier"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier":{"url":"/documentation/avfaudio/avaudiosessionspatialexperienceoptionsceneidentifier","fragments":[{"kind":"identifier","text":"AVAudioSessionSpatialExperienceOptionSceneIdentifier"}],"kind":"symbol","title":"AVAudioSessionSpatialExperienceOptionSceneIdentifier","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSceneIdentifier","type":"topic","abstract":[]},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"type":"topic","url":"/documentation/foundation/nserror","kind":"symbol","title":"NSError","abstract":[{"text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperience-qlty","fragments":[{"kind":"identifier","text":"intendedSpatialExperience"}],"url":"/documentation/avfaudio/avaudiosession/intendedspatialexperience-qlty","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The spatial audio experience your app intends to provide the user."}],"title":"intendedSpatialExperience","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate":{"abstract":[{"text":"A Boolean value that indicates whether the audio session is a candidate to be the Now Playing session.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNowPlayingCandidate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/avfaudio/avaudiosession/isnowplayingcandidate","navigatorTitle":[{"text":"isNowPlayingCandidate","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/isNowPlayingCandidate","title":"isNowPlayingCandidate","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"title":"Technologies","kind":"technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies","url":"/documentation/technologies","type":"topic","role":"overview"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/intendedSpatialExperienceOptions","fragments":[{"text":"intendedSpatialExperienceOptions","kind":"identifier"}],"title":"intendedSpatialExperienceOptions","type":"topic","url":"/documentation/avfaudio/avaudiosession/intendedspatialexperienceoptions","role":"symbol","abstract":[{"type":"text","text":"A dictionary of options that customize the spatial experience."}],"kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize":{"abstract":[{"text":"Constants that specify the perceived size of sounds the audio session plays.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SoundStageSize","kind":"identifier"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/SoundStageSize","role":"symbol","navigatorTitle":[{"text":"SoundStageSize","kind":"identifier"}],"kind":"symbol","url":"/documentation/avfaudio/avaudiosession/soundstagesize","title":"AVAudioSession.SoundStageSize","type":"topic"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy":{"url":"/documentation/avfaudio/avaudiosessionspatialexperienceoptionanchoringstrategy","fragments":[{"kind":"identifier","text":"AVAudioSessionSpatialExperienceOptionAnchoringStrategy"}],"kind":"symbol","title":"AVAudioSessionSpatialExperienceOptionAnchoringStrategy","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionAnchoringStrategy","type":"topic","abstract":[]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize":{"url":"/documentation/avfaudio/avaudiosessionspatialexperienceoptionsoundstagesize","fragments":[{"kind":"identifier","text":"AVAudioSessionSpatialExperienceOptionSoundStageSize"}],"kind":"symbol","title":"AVAudioSessionSpatialExperienceOptionSoundStageSize","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOptionSoundStageSize","type":"topic","abstract":[]},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AVAudioSession","kind":"identifier"}],"url":"/documentation/avfaudio/avaudiosession","type":"topic","kind":"symbol","navigatorTitle":[{"text":"AVAudioSession","kind":"identifier"}],"abstract":[{"text":"An object that communicates to the system how you intend to use audio in your app.","type":"text"}],"title":"AVAudioSession","role":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption":{"url":"/documentation/avfaudio/avaudiosessionspatialexperienceoption","fragments":[{"kind":"identifier","text":"AVAudioSessionSpatialExperienceOption"}],"kind":"symbol","title":"AVAudioSessionSpatialExperienceOption","role":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialExperienceOption","type":"topic","abstract":[{"text":"A type definition for a spatial experience option.","type":"text"}]},"doc://com.apple.avfaudio/documentation/AVFAudio":{"url":"/documentation/avfaudio","kind":"symbol","identifier":"doc://com.apple.avfaudio/documentation/AVFAudio","title":"AVFAudio","type":"topic","abstract":[{"text":"Play, record, and process audio; configure your app’s system audio behavior.","type":"text"}],"role":"collection"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)":{"abstract":[{"type":"text","text":"Sets a Boolean value that indicates whether the audio session is a candidate to be the Now Playing session."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIsNowPlayingCandidate"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIsNowPlayingCandidate(_:)","title":"setIsNowPlayingCandidate(_:)","url":"/documentation/avfaudio/avaudiosession/setisnowplayingcandidate(_:)","navigatorTitle":[{"kind":"identifier","text":"setIsNowPlayingCandidate:error:"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:":{"identifier":"doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/setIntendedSpatialExperience:options:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIntendedSpatialExperience:options:error:"}],"url":"/documentation/avfaudio/avaudiosession/setintendedspatialexperience:options:error:","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setIntendedSpatialExperience:options:error:"}],"abstract":[{"type":"text","text":"Sets the spatial audio experience your app intends to provide the user."}],"title":"setIntendedSpatialExperience:options:error:","role":"symbol"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","title":"BOOL","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"isNowPlayingCandidate","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/title","op":"replace"},{"value":[{"text":"isNowPlayingCandidate","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1isNowPlayingCandidate/fragments","op":"replace"},{"value":"AVAudioSessionSoundStageSize","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/title","op":"replace"},{"value":[{"text":"AVAudioSessionSoundStageSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/fragments"},{"value":[{"text":"AVAudioSessionSoundStageSize","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1SoundStageSize/navigatorTitle"},{"value":"AVAudioSession","op":"replace","path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments","value":[{"text":"AVAudioSession","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle","value":[{"text":"AVAudioSession","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/title","value":"setIsNowPlayingCandidate:error:","op":"replace"},{"path":"/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1setIsNowPlayingCandidate(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setIsNowPlayingCandidate:error:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}