{
  "abstract": [
    {
      "text": "A notification the system posts when its spatial playback capabilities change.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avfaudio/documentation/AVFAudio",
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/spatialPlaybackCapabilitiesChangedNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AVFAudio",
    "externalID": "c:@AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "spatialPlaybackCapabilitiesChangedNotification"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSNotification",
        "text": "NSNotification"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSNotificationName",
        "text": "Name"
      }
    ],
    "modules": [
      {
        "name": "AVFAudio"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "spatialPlaybackCapabilitiesChangedNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "spatialPlaybackCapabilitiesChangedNotification"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSNotification",
              "text": "NSNotification"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSNotificationName",
              "text": "Name"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system posts this notification when spatial playback capabilities change due to a change in user preference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary of this notification contains the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialAudioEnabledKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key, which indicates whether spatial audio is in an enabled state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A route change may result in a change in the ability for the system to play spatial audio, so observe ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionPortDescription/isSpatialAudioEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to check if the current route supports spatialized playback.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.avfaudio/documentation/AVFAudio": {
      "abstract": [
        {
          "text": "Play, record, and process audio; configure your app’s system audio behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio",
      "kind": "symbol",
      "role": "collection",
      "title": "AVFAudio",
      "type": "topic",
      "url": "/documentation/avfaudio"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession": {
      "abstract": [
        {
          "text": "An object that communicates to the system how you intend to use audio in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSession"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSession",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when its audio route changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "routeChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/routeChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionRouteChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "routeChangeNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/routechangenotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/spatialPlaybackCapabilitiesChangedNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when its spatial playback capabilities change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatialPlaybackCapabilitiesChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSession/spatialPlaybackCapabilitiesChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "spatialPlaybackCapabilitiesChangedNotification",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosession/spatialplaybackcapabilitieschangednotification"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionPortDescription/isSpatialAudioEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the port supports spatial audio playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSpatialAudioEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionPortDescription/isSpatialAudioEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "spatialAudioEnabled"
        }
      ],
      "role": "symbol",
      "title": "isSpatialAudioEnabled",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionportdescription/isspatialaudioenabled"
    },
    "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialAudioEnabledKey": {
      "abstract": [
        {
          "text": "A user info key that you use to retrieve the state of spatial playback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialAudioEnabledKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialAudioEnabledKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVAudioSessionSpatialAudioEnabledKey"
        }
      ],
      "role": "symbol",
      "title": "AVAudioSessionSpatialAudioEnabledKey",
      "type": "topic",
      "url": "/documentation/avfaudio/avaudiosessionspatialaudioenabledkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSNotificationName": {
      "abstract": [
        {
          "text": "A structure that defines the name of a notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSNotification.Name"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification.Name",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification": {
      "abstract": [
        {
          "text": "An object containing information broadcast to registered observers that bridges to ; use  when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNotification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNotification",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "User-Info-Keys",
      "identifiers": [
        "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialAudioEnabledKey"
      ],
      "title": "User Info Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avfaudio/documentation/AVFAudio"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "User-Info-Keys",
              "identifiers": [
                "doc://com.apple.avfaudio/documentation/AVFAudio/AVAudioSessionSpatialAudioEnabledKey"
              ],
              "title": "User Info Keys"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSNotificationName",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSNotificationName",
                    "text": "NSNotificationName"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/title",
          "value": "AVAudioSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionPortDescription~1isSpatialAudioEnabled/title",
          "value": "spatialAudioEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionPortDescription~1isSpatialAudioEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "spatialAudioEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1spatialPlaybackCapabilitiesChangedNotification/title",
          "value": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1spatialPlaybackCapabilitiesChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSpatialPlaybackCapabilitiesChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSNotification/abstract",
          "value": [
            {
              "text": "A container for information broadcast through a notification center to all registered observers.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionSpatialAudioEnabledKey/title",
          "value": "AVAudioSessionSpatialAudioEnabledKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSessionSpatialAudioEnabledKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionSpatialAudioEnabledKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1routeChangeNotification/title",
          "value": "AVAudioSessionRouteChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avfaudio~1documentation~1AVFAudio~1AVAudioSession~1routeChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVAudioSessionRouteChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSNotificationName/title",
          "value": "NSNotificationName"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/spatialplaybackcapabilitieschangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avfaudio/avaudiosession/spatialplaybackcapabilitieschangednotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
