{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.matter/documentation/Matter",
        "doc://com.apple.matter/documentation/Matter/MTRError"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.matter/documentation/Matter/MTRError/Code"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTRErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "modules": [
      {
        "name": "Matter"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Code"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "MTRError.Code"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Code"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.matter/documentation/Matter": {
      "abstract": [
        {
          "text": "Communicate with and control smart home devices from a variety of manufacturers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter",
      "kind": "symbol",
      "role": "collection",
      "title": "Matter",
      "type": "topic",
      "url": "/documentation/matter"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRError"
        }
      ],
      "role": "symbol",
      "title": "MTRError",
      "type": "topic",
      "url": "/documentation/matter/mtrerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/accessDenied": {
      "abstract": [
        {
          "text": "Access to some resource was denied.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessDenied"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/accessDenied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeAccessDenied"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.accessDenied",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/accessdenied"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/bufferTooSmall": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bufferTooSmall"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/bufferTooSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeBufferTooSmall"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.bufferTooSmall",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/buffertoosmall"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/busy": {
      "abstract": [
        {
          "text": "A request was made to some entity, and that entity cannot handle the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "request right now, but might be able to at a different point in time.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "busy"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/busy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeBusy"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.busy",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/busy"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/cancelled": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeCancelled"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.cancelled",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/cancelled"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/dnssdUnauthorized": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dnssdUnauthorized"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/dnssdUnauthorized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeDNSSDUnauthorized"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.dnssdUnauthorized",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/dnssdunauthorized"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/fabricExists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fabricExists"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/fabricExists",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeFabricExists"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.fabricExists",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/fabricexists"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/generalError": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "generalError"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/generalError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeGeneralError"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.generalError",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/generalerror"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/init(rawvalue:)"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/integrityCheckFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "integrityCheckFailed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/integrityCheckFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeIntegrityCheckFailed"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.integrityCheckFailed",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/integritycheckfailed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidArgument": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidArgument"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidArgument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeInvalidArgument"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.invalidArgument",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/invalidargument"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidIntegerValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidIntegerValue"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidIntegerValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeInvalidIntegerValue"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.invalidIntegerValue",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/invalidintegervalue"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidMessageLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidMessageLength"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidMessageLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeInvalidMessageLength"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.invalidMessageLength",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/invalidmessagelength"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidState"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeInvalidState"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.invalidState",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/invalidstate"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidStringLength": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidStringLength"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidStringLength",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeInvalidStringLength"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.invalidStringLength",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/invalidstringlength"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/notFound": {
      "abstract": [
        {
          "text": "Something was requested that could not be located.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notFound"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/notFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeNotFound"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.notFound",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/notfound"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/schemaMismatch": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "schemaMismatch"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/schemaMismatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeSchemaMismatch"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.schemaMismatch",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/schemamismatch"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/timeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timeout"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/timeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeTimeout"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.timeout",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/timeout"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/tlvDecodeFailed": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tlvDecodeFailed"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/tlvDecodeFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeTLVDecodeFailed"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.tlvDecodeFailed",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/tlvdecodefailed"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/unknownSchema": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownSchema"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/unknownSchema",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeUnknownSchema"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.unknownSchema",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/unknownschema"
    },
    "doc://com.apple.matter/documentation/Matter/MTRError/Code/wrongAddressType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongAddressType"
        }
      ],
      "identifier": "doc://com.apple.matter/documentation/Matter/MTRError/Code/wrongAddressType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTRErrorCodeWrongAddressType"
        }
      ],
      "role": "symbol",
      "title": "MTRError.Code.wrongAddressType",
      "type": "topic",
      "url": "/documentation/matter/mtrerror/code/wrongaddresstype"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/bufferTooSmall",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/cancelled",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/dnssdUnauthorized",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/fabricExists",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/generalError",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/integrityCheckFailed",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidArgument",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidIntegerValue",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidMessageLength",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidState",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidStringLength",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/schemaMismatch",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/timeout",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/tlvDecodeFailed",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/unknownSchema",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/wrongAddressType",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/accessDenied",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/busy",
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/notFound"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.matter/documentation/Matter/MTRError/Code/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTRErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.matter/documentation/Matter"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/bufferTooSmall",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/cancelled",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/dnssdUnauthorized",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/fabricExists",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/generalError",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/integrityCheckFailed",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidArgument",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidIntegerValue",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidMessageLength",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidState",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/invalidStringLength",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/schemaMismatch",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/timeout",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/tlvDecodeFailed",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/unknownSchema",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/wrongAddressType",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/accessDenied",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/busy",
                "doc://com.apple.matter/documentation/Matter/MTRError/Code/notFound"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "MTRErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidMessageLength/title",
          "value": "MTRErrorCodeInvalidMessageLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidMessageLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeInvalidMessageLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/title",
          "value": "MTRErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1generalError/title",
          "value": "MTRErrorCodeGeneralError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1generalError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeGeneralError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1notFound/title",
          "value": "MTRErrorCodeNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1notFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1timeout/title",
          "value": "MTRErrorCodeTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1timeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1schemaMismatch/title",
          "value": "MTRErrorCodeSchemaMismatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1schemaMismatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeSchemaMismatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1fabricExists/title",
          "value": "MTRErrorCodeFabricExists"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1fabricExists/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeFabricExists"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1cancelled/title",
          "value": "MTRErrorCodeCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1tlvDecodeFailed/title",
          "value": "MTRErrorCodeTLVDecodeFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1tlvDecodeFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeTLVDecodeFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidArgument/title",
          "value": "MTRErrorCodeInvalidArgument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidArgument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeInvalidArgument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidIntegerValue/title",
          "value": "MTRErrorCodeInvalidIntegerValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidIntegerValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeInvalidIntegerValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1dnssdUnauthorized/title",
          "value": "MTRErrorCodeDNSSDUnauthorized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1dnssdUnauthorized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeDNSSDUnauthorized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidStringLength/title",
          "value": "MTRErrorCodeInvalidStringLength"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidStringLength/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeInvalidStringLength"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1wrongAddressType/title",
          "value": "MTRErrorCodeWrongAddressType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1wrongAddressType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeWrongAddressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1unknownSchema/title",
          "value": "MTRErrorCodeUnknownSchema"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1unknownSchema/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeUnknownSchema"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1integrityCheckFailed/title",
          "value": "MTRErrorCodeIntegrityCheckFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1integrityCheckFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeIntegrityCheckFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1busy/title",
          "value": "MTRErrorCodeBusy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1busy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeBusy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1accessDenied/title",
          "value": "MTRErrorCodeAccessDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1accessDenied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeAccessDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidState/title",
          "value": "MTRErrorCodeInvalidState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1invalidState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeInvalidState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1bufferTooSmall/title",
          "value": "MTRErrorCodeBufferTooSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.matter~1documentation~1Matter~1MTRError~1Code~1bufferTooSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTRErrorCodeBufferTooSmall"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/matter/mtrerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/matter/mtrerror/code"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
