{
  "abstract": [
    {
      "text": "Unknown error.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unknownError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKPassKitErrorCode@PKUnknownError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unknownError"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKUnknownError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKPassKitError.Code.unknownError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unknownError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKPassKitError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code": {
      "abstract": [
        {
          "text": "Errors that the PassKit framework uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Code"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidDataError": {
      "abstract": [
        {
          "text": "Invalid pass data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidDataError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidDataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInvalidDataError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code.invalidDataError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code/invaliddataerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidSignature": {
      "abstract": [
        {
          "text": "Invalid pass signature.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidSignature"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKInvalidSignature"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code.invalidSignature",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code/invalidsignature"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/notEntitledError": {
      "abstract": [
        {
          "text": "Error caused by absence of the required entitlements for the given operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEntitledError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/notEntitledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKNotEntitledError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code.notEntitledError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code/notentitlederror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unknownError": {
      "abstract": [
        {
          "text": "Unknown error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknownError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unknownError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKUnknownError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code.unknownError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code/unknownerror"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unsupportedVersionError": {
      "abstract": [
        {
          "text": "Unsupported pass version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedVersionError"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unsupportedVersionError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKUnsupportedVersionError"
        }
      ],
      "role": "symbol",
      "title": "PKPassKitError.Code.unsupportedVersionError",
      "type": "topic",
      "url": "/documentation/passkit/pkpasskiterror/code/unsupportedversionerror"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidDataError",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unsupportedVersionError",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidSignature",
        "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/notEntitledError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKUnknownError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKUnknownError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidDataError",
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/unsupportedVersionError",
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/invalidSignature",
                "doc://com.apple.passkit/documentation/PassKit/PKPassKitError/Code/notEntitledError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKUnknownError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/title",
          "value": "PKPassKitErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKPassKitErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1invalidSignature/title",
          "value": "PKInvalidSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1invalidSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInvalidSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1unsupportedVersionError/title",
          "value": "PKUnsupportedVersionError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1unsupportedVersionError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKUnsupportedVersionError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1invalidDataError/title",
          "value": "PKInvalidDataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1invalidDataError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKInvalidDataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1notEntitledError/title",
          "value": "PKNotEntitledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1notEntitledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKNotEntitledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1unknownError/title",
          "value": "PKUnknownError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKPassKitError~1Code~1unknownError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKUnknownError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkpasskiterror/code/unknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkpasskiterror/code/unknownerror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
