{
  "abstract": [
    {
      "text": "A style indicating that the title bar separator is a line.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/line"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITitlebarSeparatorStyle@UITitlebarSeparatorStyleLine",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "line"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITitlebarSeparatorStyleLine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UITitlebarSeparatorStyle.line"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "line"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle": {
      "abstract": [
        {
          "text": "Styles that determine the type of separator displayed between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system determines the type of separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/line": {
      "abstract": [
        {
          "text": "A style indicating that the title bar separator is a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "line"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/line",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyleLine"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle.line",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle/line"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/none": {
      "abstract": [
        {
          "text": "A style indicating that there’s no title bar separator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyleNone"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle.none",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/shadow": {
      "abstract": [
        {
          "text": "A style indicating that the title bar separator is a shadow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/shadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyleShadow"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle.shadow",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle/shadow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/none",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/shadow"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITitlebarSeparatorStyleLine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyleLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/none",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle/shadow"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UITitlebarSeparatorStyleLine"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1line/title",
          "value": "UITitlebarSeparatorStyleLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1line/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyleLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/title",
          "value": "UITitlebarSeparatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1automatic/title",
          "value": "UITitlebarSeparatorStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1none/title",
          "value": "UITitlebarSeparatorStyleNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyleNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1shadow/title",
          "value": "UITitlebarSeparatorStyleShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle~1shadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyleShadow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uititlebarseparatorstyle/line"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uititlebarseparatorstyle/line"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
