{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/flipHorizontal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIModalTransitionStyle@UIModalTransitionStyleFlipHorizontal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "flipHorizontal"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIModalTransitionStyleFlipHorizontal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIModalTransitionStyle.flipHorizontal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "flipHorizontal"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the view controller is presented, the current view initiates a horizontal 3D flip from right-to-left, resulting in the revealing of the new view as if it were on the back of the previous view. On dismissal, the flip occurs from left-to-right, returning to the original view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle": {
      "abstract": [
        {
          "text": "Transition styles available when presenting view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIModalTransitionStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalTransitionStyle"
        }
      ],
      "role": "symbol",
      "title": "UIModalTransitionStyle",
      "type": "topic",
      "url": "/documentation/uikit/uimodaltransitionstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coverVertical"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalTransitionStyleCoverVertical"
        }
      ],
      "role": "symbol",
      "title": "UIModalTransitionStyle.coverVertical",
      "type": "topic",
      "url": "/documentation/uikit/uimodaltransitionstyle/coververtical"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/crossDissolve": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "crossDissolve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/crossDissolve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalTransitionStyleCrossDissolve"
        }
      ],
      "role": "symbol",
      "title": "UIModalTransitionStyle.crossDissolve",
      "type": "topic",
      "url": "/documentation/uikit/uimodaltransitionstyle/crossdissolve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/flipHorizontal": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flipHorizontal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/flipHorizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalTransitionStyleFlipHorizontal"
        }
      ],
      "role": "symbol",
      "title": "UIModalTransitionStyle.flipHorizontal",
      "type": "topic",
      "url": "/documentation/uikit/uimodaltransitionstyle/fliphorizontal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/partialCurl": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "partialCurl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/partialCurl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalTransitionStylePartialCurl"
        }
      ],
      "role": "symbol",
      "title": "UIModalTransitionStyle.partialCurl",
      "type": "topic",
      "url": "/documentation/uikit/uimodaltransitionstyle/partialcurl"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical",
        "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/crossDissolve",
        "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/partialCurl"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIModalTransitionStyleFlipHorizontal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyleFlipHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/coverVertical",
                "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/crossDissolve",
                "doc://com.apple.uikit/documentation/UIKit/UIModalTransitionStyle/partialCurl"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIModalTransitionStyleFlipHorizontal"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1coverVertical/title",
          "value": "UIModalTransitionStyleCoverVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1coverVertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyleCoverVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle/title",
          "value": "UIModalTransitionStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1flipHorizontal/title",
          "value": "UIModalTransitionStyleFlipHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1flipHorizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyleFlipHorizontal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1partialCurl/title",
          "value": "UIModalTransitionStylePartialCurl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1partialCurl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStylePartialCurl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1crossDissolve/title",
          "value": "UIModalTransitionStyleCrossDissolve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalTransitionStyle~1crossDissolve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalTransitionStyleCrossDissolve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimodaltransitionstyle/fliphorizontal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimodaltransitionstyle/fliphorizontal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
