{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/authenticationservices/ascredentialidentitystore/removecredentialidentities(_:completion:)-67lcw"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/authenticationservices/ascredentialidentitystore/removecredentialidentities(_:completion:)-67lcw"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeCredentialIdentities(_:completion:)-67lcw"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Remove the given credential identities from the store.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCredentialIdentities","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"credentialIdentities","kind":"internalParam"},{"text":": [any ","kind":"text"},{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity","text":"ASCredentialIdentity","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ASCredentialIdentity"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", (any ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:s4Voida","text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]},{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCredentialIdentities"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"credentialIdentities"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"ASCredentialIdentity","preciseIdentifier":"c:objc(pl)ASCredentialIdentity","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"]}]},{"kind":"parameters","parameters":[{"name":"credentialIdentities","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of credential identities to remove."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"An optional completion handler that runs when the operation finishes."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Call this method if the credential store supports incremental updates to remove previously-added credential identities. On failure, this method calls the callback with an error with domain "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStoreErrorDomain"},{"type":"text","text":" and doesn’t remove any of the objects in "},{"code":"credentialIdentities","type":"codeVoice"},{"type":"text","text":" from the store."}],"type":"paragraph"}]}],"seeAlsoSections":[{"title":"Adding and removing credential identities","identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/saveCredentialIdentities(_:completion:)-1bbx6","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/replaceCredentialIdentities(_:completion:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeAllCredentialIdentities(_:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialIdentity"],"generated":true,"anchor":"Adding-and-removing-credential-identities"}],"sections":[],"metadata":{"role":"symbol","title":"removeCredentialIdentities(_:completion:)","symbolKind":"method","navigatorTitle":[{"text":"removeCredentialIdentityEntries:completion:","kind":"identifier"}],"platforms":[{"introducedAt":"17.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false},{"introducedAt":"17.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"introducedAt":"17.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"14.0","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"modules":[{"name":"Authentication Services"}],"externalID":"c:objc(cs)ASCredentialIdentityStore(im)removeCredentialIdentityEntries:completion:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeCredentialIdentities","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"ASCredentialIdentity","preciseIdentifier":"c:objc(pl)ASCredentialIdentity","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore"]]},"references":{"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/replaceCredentialIdentities(_:completion:)":{"title":"replaceCredentialIdentities(_:completion:)","role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/replaceCredentialIdentities(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replaceCredentialIdentities","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"ASCredentialIdentity","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ASCredentialIdentity"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"type":"topic","abstract":[{"text":"Replaces existing credential identities with new credential identities.","type":"text"}],"navigatorTitle":[{"text":"replaceCredentialIdentityEntries:completion:","kind":"identifier"}],"url":"/documentation/authenticationservices/ascredentialidentitystore/replacecredentialidentities(_:completion:)"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity":{"abstract":[{"text":"A description that uniquely identifies a particular passkey credential.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASPasskeyCredentialIdentity","kind":"identifier"}],"navigatorTitle":[{"text":"ASPasskeyCredentialIdentity","kind":"identifier"}],"title":"ASPasskeyCredentialIdentity","kind":"symbol","role":"symbol","type":"topic","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity","url":"/documentation/authenticationservices/aspasskeycredentialidentity"},"doc://com.externally.resolved.symbol/s:s5ErrorP":{"identifier":"doc://com.externally.resolved.symbol/s:s5ErrorP","abstract":[{"type":"text","text":"A type representing an error value that can be thrown."}],"role":"symbol","type":"topic","title":"Error","url":"/documentation/Swift/Error","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8SendableP","text":"Sendable"}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCredentialIdentity","kind":"identifier"}],"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity","type":"topic","abstract":[{"text":"A protocol that credential identity classes conform to that uniquely identifies credentials.","type":"text"}],"kind":"symbol","title":"ASCredentialIdentity","url":"/documentation/authenticationservices/ascredentialidentity","navigatorTitle":[{"text":"ASCredentialIdentity","kind":"identifier"}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s4Voida":{"identifier":"doc://com.externally.resolved.symbol/s:s4Voida","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"type":"topic","url":"/documentation/Swift/Void","abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeAllCredentialIdentities(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeAllCredentialIdentities","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"removeAllCredentialIdentitiesWithCompletion:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeAllCredentialIdentities(_:)","title":"removeAllCredentialIdentities(_:)","abstract":[{"text":"Removes all existing credential identities from the store.","type":"text"}],"type":"topic","url":"/documentation/authenticationservices/ascredentialidentitystore/removeallcredentialidentities(_:)","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeCredentialIdentities(_:completion:)-67lcw":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeCredentialIdentities","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"ASCredentialIdentity","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ASCredentialIdentity"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"removeCredentialIdentityEntries:completion:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeCredentialIdentities(_:completion:)-67lcw","title":"removeCredentialIdentities(_:completion:)","abstract":[{"text":"Remove the given credential identities from the store.","type":"text"}],"type":"topic","url":"/documentation/authenticationservices/ascredentialidentitystore/removecredentialidentities(_:completion:)-67lcw","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCredentialIdentityStore","kind":"identifier"}],"navigatorTitle":[{"text":"ASCredentialIdentityStore","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore","title":"ASCredentialIdentityStore","abstract":[{"text":"A container that your extension fills to provide credentials through the QuickType bar.","type":"text"}],"type":"topic","url":"/documentation/authenticationservices/ascredentialidentitystore","kind":"symbol"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialIdentity":{"type":"topic","role":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialIdentity","kind":"symbol","url":"/documentation/authenticationservices/aspasswordcredentialidentity","abstract":[{"type":"text","text":"A description that uniquely identifies a particular password credential."}],"title":"ASPasswordCredentialIdentity","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ASPasswordCredentialIdentity","kind":"identifier"}],"navigatorTitle":[{"text":"ASPasswordCredentialIdentity","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Sb":{"identifier":"doc://com.externally.resolved.symbol/s:Sb","title":"Bool","role":"symbol","url":"/documentation/Swift/Bool","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/saveCredentialIdentities(_:completion:)-1bbx6":{"role":"symbol","title":"saveCredentialIdentities(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"saveCredentialIdentities","kind":"identifier"},{"text":"([any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ASCredentialIdentity","text":"ASCredentialIdentity"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", (any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/saveCredentialIdentities(_:completion:)-1bbx6","abstract":[{"text":"Save the supplied credential identities to the store.","type":"text"}],"url":"/documentation/authenticationservices/ascredentialidentitystore/savecredentialidentities(_:completion:)-1bbx6","type":"topic","navigatorTitle":[{"text":"saveCredentialIdentityEntries:completion:","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"url":"/documentation/technologies","role":"overview","kind":"technologies","type":"topic","title":"Technologies","abstract":[{"text":"","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/technologies"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"url":"/documentation/objectivec/bool","title":"BOOL","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSError":{"role":"symbol","url":"/documentation/foundation/nserror","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","type":"topic","fragments":[{"text":"class ","kind":"text"},{"text":"NSError","kind":"identifier"}],"title":"NSError","kind":"symbol","abstract":[{"type":"text","text":"Information about an error condition including a domain, a domain-specific error code, and application-specific information."}]},"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStoreErrorDomain":{"title":"ASCredentialIdentityStoreErrorDomain","role":"symbol","kind":"symbol","identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStoreErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ASCredentialIdentityStoreErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"type":"text","text":"The domain for a credential identity store error."}],"navigatorTitle":[{"text":"ASCredentialIdentityStoreErrorDomain","kind":"identifier"}],"url":"/documentation/authenticationservices/ascredentialidentitystoreerrordomain"},"doc://com.apple.authenticationservices/documentation/AuthenticationServices":{"identifier":"doc://com.apple.authenticationservices/documentation/AuthenticationServices","abstract":[{"text":"Make it easy for users to log into apps and services.","type":"text"}],"role":"collection","type":"topic","title":"Authentication Services","url":"/documentation/authenticationservices","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"17.0","beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"introducedAt":"17.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"17.0","deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"introducedAt":"14.0","deprecated":false,"name":"macOS","unavailable":false,"beta":false},{"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"removeCredentialIdentityEntries:completion:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeCredentialIdentityEntries:completion:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.authenticationservices/documentation/AuthenticationServices","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/saveCredentialIdentities(_:completion:)-1bbx6","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/replaceCredentialIdentities(_:completion:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentityStore/removeAllCredentialIdentities(_:)","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASCredentialIdentity","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasskeyCredentialIdentity","doc://com.apple.authenticationservices/documentation/AuthenticationServices/ASPasswordCredentialIdentity"],"title":"Adding and removing credential identities","anchor":"Adding-and-removing-credential-identities","generated":true}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeCredentialIdentityEntries:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<ASCredentialIdentity>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"credentialIdentities"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"success"},{"kind":"text","text":", "},{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"error"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A list of credential identities to remove.","type":"text"}],"type":"paragraph"}],"name":"credentialIdentities"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An optional completion handler that runs when the operation finishes.","type":"text"}]}],"name":"completion"}]},"path":"/primaryContentSections/1"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1replaceCredentialIdentities(_:completion:)/title","value":"replaceCredentialIdentityEntries:completion:"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1replaceCredentialIdentities(_:completion:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"replaceCredentialIdentityEntries:completion:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/title","value":"ASPasskeyCredentialIdentity"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/fragments","value":[{"text":"ASPasskeyCredentialIdentity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasskeyCredentialIdentity/navigatorTitle","value":[{"text":"ASPasskeyCredentialIdentity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentity/title","value":"ASCredentialIdentity"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentity/fragments","value":[{"kind":"identifier","text":"ASCredentialIdentity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentity/navigatorTitle","value":[{"text":"ASCredentialIdentity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1removeAllCredentialIdentities(_:)/title","value":"removeAllCredentialIdentitiesWithCompletion:"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1removeAllCredentialIdentities(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllCredentialIdentitiesWithCompletion:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1removeCredentialIdentities(_:completion:)-67lcw/title","value":"removeCredentialIdentityEntries:completion:"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1removeCredentialIdentities(_:completion:)-67lcw/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeCredentialIdentityEntries:completion:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore/title","value":"ASCredentialIdentityStore"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore/fragments","value":[{"text":"ASCredentialIdentityStore","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore/navigatorTitle","value":[{"kind":"identifier","text":"ASCredentialIdentityStore"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialIdentity/title","value":"ASPasswordCredentialIdentity"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialIdentity/fragments","value":[{"text":"ASPasswordCredentialIdentity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASPasswordCredentialIdentity/navigatorTitle","value":[{"text":"ASPasswordCredentialIdentity","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1saveCredentialIdentities(_:completion:)-1bbx6/title","value":"saveCredentialIdentityEntries:completion:"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStore~1saveCredentialIdentities(_:completion:)-1bbx6/fragments","value":[{"text":"- ","kind":"text"},{"text":"saveCredentialIdentityEntries:completion:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStoreErrorDomain/title","value":"ASCredentialIdentityStoreErrorDomain"},{"op":"replace","path":"/references/doc:~1~1com.apple.authenticationservices~1documentation~1AuthenticationServices~1ASCredentialIdentityStoreErrorDomain/fragments","value":[{"text":"ASCredentialIdentityStoreErrorDomain","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}