{
  "abstract": [
    {
      "text": "A protocol that defines the methods an Audio Unit host calls to manage view data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)AUCustomViewPersistentData",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUCustomViewPersistentData"
      }
    ],
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUCustomViewPersistentData"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "AUCustomViewPersistentData"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that describes how to present the audio unit’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitViewConfiguration",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auaudiounitviewconfiguration"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData": {
      "abstract": [
        {
          "text": "A protocol that defines the methods an Audio Unit host calls to manage view data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "role": "symbol",
      "title": "AUCustomViewPersistentData",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aucustomviewpersistentdata"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData/customViewPersistentData": {
      "abstract": [
        {
          "text": "Called by the host application to obtain view state data from a custom Cocoa view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customViewPersistentData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSDictionary",
          "text": "NSDictionary"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData/customViewPersistentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customViewPersistentData"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "customViewPersistentData",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aucustomviewpersistentdata/customviewpersistentdata"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView": {
      "abstract": [
        {
          "text": "A view that provides a generic user interface for a Cocoa audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "role": "symbol",
      "title": "AUGenericView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView": {
      "abstract": [
        {
          "text": "A view that provides a specialized user interface for a Cocoa-based panner audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "role": "symbol",
      "title": "AUPannerView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aupannerview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController": {
      "abstract": [
        {
          "text": "The base class to extend when creating a custom user interface for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "role": "symbol",
      "title": "AUViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase": {
      "abstract": [
        {
          "text": "A type definition that indicates the the platform’s Audio Unit view controller base class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUViewControllerBase"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUViewControllerBase",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontrollerbase"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView"
      ],
      "title": "Audio Units"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-View-State",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData/customViewPersistentData"
      ],
      "title": "Accessing View State"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUCustomViewPersistentData"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-View-State",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData/customViewPersistentData"
              ],
              "title": "Accessing View State"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUCustomViewPersistentData"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/title",
          "value": "AUAudioUnitViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/title",
          "value": "AUCustomViewPersistentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/title",
          "value": "AUPannerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/title",
          "value": "AUViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/title",
          "value": "AUGenericView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData~1customViewPersistentData/title",
          "value": "customViewPersistentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData~1customViewPersistentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customViewPersistentData"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit/aucustomviewpersistentdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit/aucustomviewpersistentdata"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
