{
  "abstract": [
    {
      "text": "Flags that describe the display of a generic view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AUGenericViewDisplayFlags",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUGenericViewDisplayFlags"
      }
    ],
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUGenericViewDisplayFlags"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "AUGenericViewDisplayFlags"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags": {
      "abstract": [
        {
          "text": "Flags that describe the display of a generic view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "role": "symbol",
      "title": "AUGenericViewDisplayFlags",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/init(rawvalue:)"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the audio unit parameters of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewParametersDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewParametersDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewParametersDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewparametersdisplayflag"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the audio unit properties of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewPropertiesDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewPropertiesDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewPropertiesDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewpropertiesdisplayflag"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag": {
      "abstract": [
        {
          "text": "If set, the generic view displays the title and manufacturer of the audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewTitleDisplayFlag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AUGenericViewDisplayFlags",
          "text": "AUGenericViewDisplayFlags"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewTitleDisplayFlag"
        }
      ],
      "role": "symbol",
      "title": "viewTitleDisplayFlag",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericviewdisplayflags/viewtitledisplayflag"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Display-Flags",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag"
      ],
      "title": "Display Flags"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUGenericViewDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Display-Flags",
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewParametersDisplayFlag",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewPropertiesDisplayFlag",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericViewDisplayFlags/viewTitleDisplayFlag"
              ],
              "title": "Display Flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUGenericViewDisplayFlags"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UInt32",
                    "text": "UInt32"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewPropertiesDisplayFlag/title",
          "value": "AUViewPropertiesDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewPropertiesDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewPropertiesDisplayFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewTitleDisplayFlag/title",
          "value": "AUViewTitleDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewTitleDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewTitleDisplayFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/title",
          "value": "AUGenericViewDisplayFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericViewDisplayFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewParametersDisplayFlag/title",
          "value": "AUViewParametersDisplayFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericViewDisplayFlags~1viewParametersDisplayFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewParametersDisplayFlag"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit/augenericviewdisplayflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit/augenericviewdisplayflags"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
