{
  "abstract": [
    {
      "text": "The base class to extend when creating a custom user interface for an audio unit.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)AUViewController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AUViewController"
      }
    ],
    "modules": [
      {
        "name": "CoreAudioKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AUViewController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "AUViewController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class doesn’t add any new methods or properties to its superclass, but it does conform to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A host app can access the view controller by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/requestViewController(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Subclassing-Notes",
          "level": 3,
          "text": "Subclassing Notes",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If an audio unit provides a custom view controller, the UI Audio Unit extension must implement a subclass of ",
              "type": "text"
            },
            {
              "code": "AUViewController",
              "type": "codeVoice"
            },
            {
              "text": " and implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol inside the subclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit": {
      "abstract": [
        {
          "text": "Add user interfaces to audio units.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit",
      "kind": "symbol",
      "role": "collection",
      "title": "CoreAudioKit",
      "type": "topic",
      "url": "/documentation/coreaudiokit"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration": {
      "abstract": [
        {
          "text": "A configuration object that describes how to present the audio unit’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnitViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnitViewConfiguration",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auaudiounitviewconfiguration"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData": {
      "abstract": [
        {
          "text": "A protocol that defines the methods an Audio Unit host calls to manage view data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUCustomViewPersistentData"
        }
      ],
      "role": "symbol",
      "title": "AUCustomViewPersistentData",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aucustomviewpersistentdata"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView": {
      "abstract": [
        {
          "text": "A view that provides a generic user interface for a Cocoa audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUGenericView"
        }
      ],
      "role": "symbol",
      "title": "AUGenericView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/augenericview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView": {
      "abstract": [
        {
          "text": "A view that provides a specialized user interface for a Cocoa-based panner audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUPannerView"
        }
      ],
      "role": "symbol",
      "title": "AUPannerView",
      "type": "topic",
      "url": "/documentation/coreaudiokit/aupannerview"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController": {
      "abstract": [
        {
          "text": "The base class to extend when creating a custom user interface for an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUViewController"
        }
      ],
      "role": "symbol",
      "title": "AUViewController",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontroller"
    },
    "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase": {
      "abstract": [
        {
          "text": "A type definition that indicates the the platform’s Audio Unit view controller base class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "AUViewControllerBase"
        }
      ],
      "identifier": "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUViewControllerBase",
      "type": "topic",
      "url": "/documentation/coreaudiokit/auviewcontrollerbase"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/requestViewController(completionHandler:)": {
      "abstract": [
        {
          "text": "Requests an audio unit’s custom view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "@escaping"
        },
        {
          "kind": "text",
          "text": " ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnit/requestViewController(completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "requestViewController(completionHandler:)",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnit/requestViewController(completionHandler:)"
    },
    "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory": {
      "abstract": [
        {
          "text": "An object that creates a version 3 audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnitFactory"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AudioToolbox/AUAudioUnitFactory",
      "kind": "symbol",
      "role": "symbol",
      "title": "AUAudioUnitFactory",
      "type": "topic",
      "url": "/documentation/AudioToolbox/AUAudioUnitFactory"
    },
    "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsextensionrequesthandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSViewController": {
      "abstract": [
        {
          "text": "A controller that manages a view, typically loaded from a nib file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewController",
      "type": "topic",
      "url": "/documentation/AppKit/NSViewController"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSEditor": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditor"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSEditor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEditor",
      "type": "topic",
      "url": "/documentation/AppKit/NSEditor"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming": {
      "abstract": [
        {
          "text": "A set of methods that support the mediation of a custom segue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSeguePerforming"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSeguePerforming",
      "type": "topic",
      "url": "/documentation/AppKit/NSSeguePerforming"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding": {
      "abstract": [
        {
          "text": "Methods that responder subclasses implement to support key binding commands, such as inserting tabs and newlines, or moving the insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStandardKeyBindingResponding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStandardKeyBindingResponding",
      "type": "topic",
      "url": "/documentation/AppKit/NSStandardKeyBindingResponding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring": {
      "abstract": [
        {
          "text": "A protocol that marks classes to restore the state of your app to continue a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification": {
      "abstract": [
        {
          "text": "A set of methods used to associate a unique identifier with objects in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUserInterfaceItemIdentification"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserInterfaceItemIdentification",
      "type": "topic",
      "url": "/documentation/AppKit/NSUserInterfaceItemIdentification"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/UIKit/UIActivityItemsConfigurationProviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the [`UIAppearance`](doc://com.apple.uikit/documentation/UIKit/UIAppearance) API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearanceContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIContentContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/UIKit/UIPasteConfigurationSupporting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIStateRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitChangeObservable-67e94"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSViewController",
        "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSEditor",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSeguePerforming",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSStandardKeyBindingResponding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserActivityRestoring",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSUserInterfaceItemIdentification",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
        "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Audio-Units",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
        "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData"
      ],
      "title": "Audio Units"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AUViewController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSViewController",
                "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Audio-Units",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUViewControllerBase",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUAudioUnitViewConfiguration",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUGenericView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUPannerView",
                "doc://com.apple.coreaudiokit/documentation/CoreAudioKit/AUCustomViewPersistentData"
              ],
              "title": "Audio Units"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUViewController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIViewController",
                    "text": "UIViewController"
                  }
                ]
              },
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AUViewController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSViewController",
                    "text": "NSViewController"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/title",
          "value": "AUGenericView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUGenericView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUGenericView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1requestViewController(completionHandler:)/title",
          "value": "requestViewControllerWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit~1requestViewController(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "requestViewControllerWithCompletionHandler:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": " (^)("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "AUViewControllerBase"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "internalParam",
              "text": "viewController"
            },
            {
              "kind": "text",
              "text": ")) "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSEditor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEditor"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserInterfaceItemIdentification/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserInterfaceItemIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/title",
          "value": "AUAudioUnitViewConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUAudioUnitViewConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnitViewConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSSeguePerforming/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSeguePerforming"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/title",
          "value": "AUViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/title",
          "value": "AUCustomViewPersistentData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUCustomViewPersistentData/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUCustomViewPersistentData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIStateRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AudioToolbox~1AUAudioUnitFactory/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AUAudioUnitFactory"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSExtensionRequestHandling",
              "text": "NSExtensionRequestHandling"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/title",
          "value": "AUPannerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coreaudiokit~1documentation~1CoreAudioKit~1AUPannerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUPannerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIContentContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSStandardKeyBindingResponding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSStandardKeyBindingResponding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coreaudiokit/auviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coreaudiokit/auviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
