{
  "abstract": [
    {
      "text": "The type of object detected, such as the face, torso, cat, dog, and so on.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.cinematic/documentation/Cinematic",
        "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CNDetection(py)detectionType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "detectionType"
      }
    ],
    "modules": [
      {
        "name": "Cinematic"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "detectionType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "detectionType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CNDetectionType",
              "text": "CNDetectionType"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "detectionType"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.cinematic/documentation/Cinematic": {
      "abstract": [
        {
          "text": "Integrate playback and editing of assets captured in Cinematic mode into your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic",
      "kind": "symbol",
      "role": "collection",
      "title": "Cinematic",
      "type": "topic",
      "url": "/documentation/cinematic"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class": {
      "abstract": [
        {
          "text": "A structure that represents a detected subject, face, torso or pet at a particular time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CNDetection"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "CNDetection",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as the face, torso, cat, dog, and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "detectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetection-c.class/detectionType",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetection-c.class/detectiontype"
    },
    "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType": {
      "abstract": [
        {
          "text": "The type of object detected, such as face, torso, cat, dog and so on.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "identifier": "doc://com.apple.cinematic/documentation/Cinematic/CNDetectionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CNDetectionType"
        }
      ],
      "role": "symbol",
      "title": "CNDetectionType",
      "type": "topic",
      "url": "/documentation/cinematic/cndetectiontype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/title",
          "value": "CNDetectionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.cinematic~1documentation~1Cinematic~1CNDetectionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CNDetectionType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/cinematic/cndetection-c.class/detectiontype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
