{
  "abstract": [
    {
      "text": "Returns the (optional) informative text currently displayed in the panel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.securityinterface/documentation/SecurityInterface",
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/informativeText()"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SFCertificateTrustPanel(im)informativeText",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "informativeText"
      },
      {
        "kind": "text",
        "text": "() -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      },
      {
        "kind": "text",
        "text": "!"
      }
    ],
    "modules": [
      {
        "name": "Security Interface"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "informativeText"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "informativeText()"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "informativeText"
            },
            {
              "kind": "text",
              "text": "() -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": "!"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface": {
      "abstract": [
        {
          "text": "Provide user interface elements for security features such as authorization, access to digital certificates, and access to items in keychains.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface",
      "kind": "symbol",
      "role": "collection",
      "title": "Security Interface",
      "type": "topic",
      "url": "/documentation/securityinterface"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel": {
      "abstract": [
        {
          "text": "A panel or sheet that lets the user edit the trust settings in any of the certificates in a certificate chain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFCertificateTrustPanel"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFCertificateTrustPanel"
        }
      ],
      "role": "symbol",
      "title": "SFCertificateTrustPanel",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificatetrustpanel"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/informativeText()": {
      "abstract": [
        {
          "text": "Returns the (optional) informative text currently displayed in the panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "informativeText"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/informativeText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "informativeText"
        }
      ],
      "role": "symbol",
      "title": "informativeText()",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificatetrustpanel/informativetext()"
    },
    "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/setInformativeText(_:)": {
      "abstract": [
        {
          "text": "Sets the (optional) informative text displayed in the panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setInformativeText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/setInformativeText(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setInformativeText:"
        }
      ],
      "role": "symbol",
      "title": "setInformativeText(_:)",
      "type": "topic",
      "url": "/documentation/securityinterface/sfcertificatetrustpanel/setinformativetext(_:)"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Controlling-the-Appearance-of-a-Certificate-Trust-Panel",
      "generated": true,
      "identifiers": [
        "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/setInformativeText(_:)"
      ],
      "title": "Controlling the Appearance of a Certificate Trust Panel"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "informativeText"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "informativeText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.securityinterface/documentation/SecurityInterface",
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Controlling-the-Appearance-of-a-Certificate-Trust-Panel",
              "generated": true,
              "identifiers": [
                "doc://com.apple.securityinterface/documentation/SecurityInterface/SFCertificateTrustPanel/setInformativeText(_:)"
              ],
              "title": "Controlling the Appearance of a Certificate Trust Panel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "identifier",
                    "text": "informativeText"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/title",
          "value": "SFCertificateTrustPanel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateTrustPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFCertificateTrustPanel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel~1setInformativeText(_:)/title",
          "value": "setInformativeText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel~1setInformativeText(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setInformativeText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel~1informativeText()/title",
          "value": "informativeText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.securityinterface~1documentation~1SecurityInterface~1SFCertificateTrustPanel~1informativeText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "informativeText"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/securityinterface/sfcertificatetrustpanel/informativetext()"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/securityinterface/sfcertificatetrustpanel/informativetext()"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
