{"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating"],"title":"Customizing the Menu","anchor":"Customizing-the-Menu","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEditMenuInteraction","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDismissMenuFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animator"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"UIEditMenuInteractionAnimating","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The interaction object triggering the menu.","type":"text"}]}],"name":"interaction"},{"content":[{"inlineContent":[{"text":"The object containing the configuration details for the menu.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object you use to add animations that run alongside the dismiss transition."}]}],"name":"animator"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)"},"abstract":[{"text":"Informs the delegate when the interaction is about to dismiss the menu.","type":"text"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"willDismissMenuFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":", ","kind":"text"},{"text":"animator","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIEditMenuInteractionAnimating","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"UIKit"}],"navigatorTitle":[{"text":"editMenuInteraction:willDismissMenuForConfiguration:animator:","kind":"identifier"}],"title":"editMenuInteraction(_:willDismissMenuFor:animator:)","externalID":"c:objc(pl)UIEditMenuInteractionDelegate(im)editMenuInteraction:willDismissMenuForConfiguration:animator:","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"16.0"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS","introducedAt":"16.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"16.0","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willdismissmenufor:animator:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willdismissmenufor:animator:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating","type":"topic","url":"/documentation/uikit/uieditmenuinteractionanimating","title":"UIEditMenuInteractionAnimating","navigatorTitle":[{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}],"kind":"symbol","abstract":[{"type":"text","text":"Methods adopted by system-supplied animator objects when interacting with menus."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)":{"type":"topic","abstract":[{"text":"Informs the delegate when the interaction is about to dismiss the menu.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"editMenuInteraction:willDismissMenuForConfiguration:animator:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"willDismissMenuFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":", ","kind":"text"},{"text":"animator","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIEditMenuInteractionAnimating","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willdismissmenufor:animator:)","title":"editMenuInteraction(_:willDismissMenuFor:animator:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate","abstract":[{"type":"text","text":"The methods for customizing the menu the interaction displays."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"UIEditMenuInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate","title":"UIEditMenuInteractionDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteractionDelegate","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)":{"abstract":[{"text":"Provides the target rectangle to position the menu relative to when the interaction begins or requires an update.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"targetRectFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:targetrectfor:)","title":"editMenuInteraction(_:targetRectFor:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction":{"navigatorTitle":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"title":"UIEditMenuInteraction","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"An interaction that provides edit operations using a menu."}],"url":"/documentation/uikit/uieditmenuinteraction","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration":{"navigatorTitle":[{"text":"UIEditMenuConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"identifier"}],"title":"UIEditMenuConfiguration","abstract":[{"text":"An object containing the configuration details for the menu your app presents in response to an edit menu interaction.","type":"text"}],"url":"/documentation/uikit/uieditmenuconfiguration","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)":{"type":"topic","abstract":[{"text":"Provides the menu to use when the interaction begins or requires an update.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"editMenuInteraction:menuForConfiguration:suggestedActions:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEditMenuInteraction","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuFor"},{"kind":"text","text":": "},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"suggestedActions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIMenuElement","preciseIdentifier":"c:objc(cs)UIMenuElement","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:menufor:suggestedactions:)","title":"editMenuInteraction(_:menuFor:suggestedActions:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)":{"abstract":[{"type":"text","text":"Informs the delegate when the interaction is about to present the menu."}],"role":"symbol","navigatorTitle":[{"text":"editMenuInteraction:willPresentMenuForConfiguration:animator:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction","text":"UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresentMenuFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","text":"UIEditMenuConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animator"},{"kind":"text","text":": any "},{"text":"UIEditMenuInteractionAnimating","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willpresentmenufor:animator:)","title":"editMenuInteraction(_:willPresentMenuFor:animator:)"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"beta":false,"introducedAt":"16.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"16.0","deprecated":false,"name":"iPadOS","unavailable":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"16.0","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Method","path":"/metadata/roleHeading","op":"replace"},{"value":"editMenuInteraction:willDismissMenuForConfiguration:animator:","path":"/metadata/title","op":"replace"},{"value":"method","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"editMenuInteraction:willDismissMenuForConfiguration:animator:","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating"],"generated":true,"title":"Customizing the Menu","anchor":"Customizing-the-Menu"}]},{"path":"/primaryContentSections/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"editMenuInteraction:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":" *) ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willDismissMenuForConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration","text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animator:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<UIEditMenuInteractionAnimating>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIEditMenuInteractionAnimating"},{"text":") ","kind":"text"},{"text":"animator","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"interaction","content":[{"inlineContent":[{"text":"The interaction object triggering the menu.","type":"text"}],"type":"paragraph"}]},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The object containing the configuration details for the menu."}],"type":"paragraph"}]},{"name":"animator","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object you use to add animations that run alongside the dismiss transition."}]}]}]},"op":"replace","path":"/primaryContentSections/1"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/title","op":"replace","value":"UIEditMenuInteractionAnimating"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/fragments","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willDismissMenuFor:animator:)/title","op":"replace","value":"editMenuInteraction:willDismissMenuForConfiguration:animator:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willDismissMenuFor:animator:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:willDismissMenuForConfiguration:animator:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/title","op":"replace","value":"UIEditMenuInteractionDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/fragments","op":"replace","value":[{"text":"UIEditMenuInteractionDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteractionDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/title","op":"replace","value":"editMenuInteraction:targetRectForConfiguration:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/title","op":"replace","value":"UIEditMenuInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/fragments","op":"replace","value":[{"text":"UIEditMenuInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/navigatorTitle","op":"replace","value":[{"text":"UIEditMenuInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/title","op":"replace","value":"UIEditMenuConfiguration"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/fragments","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuConfiguration"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/navigatorTitle","op":"replace","value":[{"text":"UIEditMenuConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/title","op":"replace","value":"editMenuInteraction:menuForConfiguration:suggestedActions:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:menuForConfiguration:suggestedActions:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willPresentMenuFor:animator:)/title","op":"replace","value":"editMenuInteraction:willPresentMenuForConfiguration:animator:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willPresentMenuFor:animator:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:willPresentMenuForConfiguration:animator:"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}