{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEditMenuInteraction","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","text":"UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration","text":"UIEditMenuConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"suggestedActions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIMenuElement","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuElement","text":"UIMenuElement"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:objc(cs)UIMenu","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenu","text":"UIMenu"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The interaction object triggering the menu.","type":"text"}]}],"name":"interaction"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The object containing the configuration details for the menu.","type":"text"}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of suggested actions UIKit gathers from the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder","isActive":true},{"type":"text","text":" chain. You should include these actions in the menu you return."}]}],"name":"suggestedActions"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns a menu describing the desired menu hierarchy. To present the default system menu, return "},{"code":"nil","type":"codeVoice"},{"type":"text","text":". To avoid presenting a menu, return an empty menu."}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"UIKit calls this method when the interaction begins or requires an update to the menu’s actions when calling "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()"},{"type":"text","text":". The interaction displays the menu you provide. When not implemented, the default behavior is the same as returning a menu including the suggestedActions."}]},{"type":"paragraph","inlineContent":[{"text":"The following example returns a menu with an additional actions in a submenu.","type":"text"}]},{"type":"codeListing","code":["func editMenuInteraction(_ interaction: UIEditMenuInteraction, menuFor configuration: UIEditMenuConfiguration, suggestedActions: [UIMenuElement]) -> UIMenu {","        let indentationMenu = UIMenu(title: \"Indentation\", image: UIImage(systemName: \"list.bullet.indent\"), children: [","            UIAction(title: \"Increase\", image: UIImage(systemName: \"increase.indent\")) { (action) in","                // Increase indentation action.","                print(\"increase indent\")","            },","            UIAction(title: \"Decrease\", image: UIImage(systemName: \"decrease.indent\")) { (action) in","                // Decrease indentation action.","                print(\"decrease indent\")","            }","        ])","","        var actions = suggestedActions","        actions.append(indentationMenu)","        return UIMenu(children: actions)","    }"],"syntax":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"introducedAt":"16.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"16.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"16.0","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"method","title":"editMenuInteraction(_:menuFor:suggestedActions:)","role":"symbol","modules":[{"name":"UIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"editMenuInteraction:menuForConfiguration:suggestedActions:","kind":"identifier"}],"externalID":"c:objc(pl)UIEditMenuInteractionDelegate(im)editMenuInteraction:menuForConfiguration:suggestedActions:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"menuFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":", ","kind":"text"},{"text":"suggestedActions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIMenuElement","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIMenuElement"},{"text":"]) -> ","kind":"text"},{"text":"UIMenu","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIMenu"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"Provides the menu to use when the interaction begins or requires an update."}],"seeAlsoSections":[{"anchor":"Customizing-the-Menu","title":"Customizing the Menu","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:menufor:suggestedactions:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:menufor:suggestedactions:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate"]]},"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating","type":"topic","url":"/documentation/uikit/uieditmenuinteractionanimating","title":"UIEditMenuInteractionAnimating","navigatorTitle":[{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}],"kind":"symbol","abstract":[{"type":"text","text":"Methods adopted by system-supplied animator objects when interacting with menus."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIEditMenuInteractionAnimating"}]},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)":{"abstract":[{"text":"Provides the target rectangle to position the menu relative to when the interaction begins or requires an update.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"targetRectFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"type":"topic","url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:targetrectfor:)","title":"editMenuInteraction(_:targetRectFor:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMenu":{"abstract":[{"type":"text","text":"A container for grouping related menu elements in an app menu or contextual menu."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIMenu"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenu","type":"topic","title":"UIMenu","kind":"symbol","role":"symbol","url":"/documentation/uikit/uimenu","navigatorTitle":[{"kind":"identifier","text":"UIMenu"}]},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration":{"navigatorTitle":[{"text":"UIEditMenuConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"identifier"}],"title":"UIEditMenuConfiguration","abstract":[{"text":"An object containing the configuration details for the menu your app presents in response to an edit menu interaction.","type":"text"}],"url":"/documentation/uikit/uieditmenuconfiguration","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction":{"navigatorTitle":[{"text":"UIEditMenuInteraction","kind":"identifier"}],"title":"UIEditMenuInteraction","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"An interaction that provides edit operations using a menu."}],"url":"/documentation/uikit/uieditmenuinteraction","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMenuElement":{"title":"UIMenuElement","kind":"symbol","navigatorTitle":[{"text":"UIMenuElement","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenuElement","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMenuElement","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing a menu, action, or command."}],"url":"/documentation/uikit/uimenuelement"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)":{"abstract":[{"type":"text","text":"Informs the delegate when the interaction is about to present the menu."}],"role":"symbol","navigatorTitle":[{"text":"editMenuInteraction:willPresentMenuForConfiguration:animator:","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction","text":"UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willPresentMenuFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","text":"UIEditMenuConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animator"},{"kind":"text","text":": any "},{"text":"UIEditMenuInteractionAnimating","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willpresentmenufor:animator:)","title":"editMenuInteraction(_:willPresentMenuFor:animator:)"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate","abstract":[{"type":"text","text":"The methods for customizing the menu the interaction displays."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"UIEditMenuInteractionDelegate","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate","title":"UIEditMenuInteractionDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIEditMenuInteractionDelegate","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIResponder":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIResponder"}],"title":"UIResponder","url":"/documentation/uikit/uiresponder","abstract":[{"type":"text","text":"An abstract interface for responding to and handling events."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIResponder"}]},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)":{"type":"topic","abstract":[{"text":"Informs the delegate when the interaction is about to dismiss the menu.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"editMenuInteraction:willDismissMenuForConfiguration:animator:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIEditMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"text":", ","kind":"text"},{"text":"willDismissMenuFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEditMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration"},{"text":", ","kind":"text"},{"text":"animator","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"UIEditMenuInteractionAnimating","preciseIdentifier":"c:objc(pl)UIEditMenuInteractionAnimating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:willdismissmenufor:animator:)","title":"editMenuInteraction(_:willDismissMenuFor:animator:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadVisibleMenu","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"reloadVisibleMenu","kind":"identifier"}],"url":"/documentation/uikit/uieditmenuinteraction/reloadvisiblemenu()","abstract":[{"text":"Updates the actions an edit menu displays.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction/reloadVisibleMenu()","role":"symbol","title":"reloadVisibleMenu()"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)":{"type":"topic","abstract":[{"text":"Provides the menu to use when the interaction begins or requires an update.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"editMenuInteraction:menuForConfiguration:suggestedActions:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:menuFor:suggestedActions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"editMenuInteraction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIEditMenuInteraction","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"menuFor"},{"kind":"text","text":": "},{"text":"UIEditMenuConfiguration","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"suggestedActions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIMenuElement","preciseIdentifier":"c:objc(cs)UIMenuElement","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"UIMenu","preciseIdentifier":"c:objc(cs)UIMenu","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uieditmenuinteractiondelegate/editmenuinteraction(_:menufor:suggestedactions:)","title":"editMenuInteraction(_:menuFor:suggestedActions:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"16.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"16.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"16.0","name":"Mac Catalyst"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"editMenuInteraction:menuForConfiguration:suggestedActions:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:menuForConfiguration:suggestedActions:"}]},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"title":"Customizing the Menu","anchor":"Customizing-the-Menu","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:targetRectFor:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willPresentMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionDelegate/editMenuInteraction(_:willDismissMenuFor:animator:)","doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteractionAnimating"]}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIMenu","kind":"typeIdentifier","text":"UIMenu","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMenu"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"editMenuInteraction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuInteraction","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuInteraction","text":"UIEditMenuInteraction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interaction"},{"kind":"text","text":" "},{"kind":"identifier","text":"menuForConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEditMenuConfiguration","identifier":"doc://com.apple.uikit/documentation/UIKit/UIEditMenuConfiguration","text":"UIEditMenuConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"suggestedActions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<UIMenuElement *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"suggestedActions"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/primaryContentSections/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"interaction","content":[{"inlineContent":[{"text":"The interaction object triggering the menu.","type":"text"}],"type":"paragraph"}]},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The object containing the configuration details for the menu."}],"type":"paragraph"}]},{"name":"suggestedActions","content":[{"inlineContent":[{"type":"text","text":"The array of suggested actions UIKit gathers from the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIResponder"},{"type":"text","text":" chain. You should include these actions in the menu you return."}],"type":"paragraph"}]}]}},{"value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Returns a menu describing the desired menu hierarchy. To present the default system menu, return ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":". To avoid presenting a menu, return an empty menu.","type":"text"}]}]},"op":"replace","path":"/primaryContentSections/2"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/title","op":"replace","value":"UIEditMenuInteractionAnimating"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/fragments","op":"replace","value":[{"text":"UIEditMenuInteractionAnimating","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionAnimating/navigatorTitle","op":"replace","value":[{"text":"UIEditMenuInteractionAnimating","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/title","op":"replace","value":"editMenuInteraction:targetRectForConfiguration:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:targetRectFor:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"editMenuInteraction:targetRectForConfiguration:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/title","op":"replace","value":"UIMenu"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/fragments","op":"replace","value":[{"text":"UIMenu","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenu/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIMenu"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/title","op":"replace","value":"UIEditMenuConfiguration"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/fragments","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuConfiguration"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuConfiguration/navigatorTitle","op":"replace","value":[{"text":"UIEditMenuConfiguration","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/title","op":"replace","value":"UIEditMenuInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/fragments","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteraction"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction/navigatorTitle","op":"replace","value":[{"text":"UIEditMenuInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/title","op":"replace","value":"UIMenuElement"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/fragments","op":"replace","value":[{"text":"UIMenuElement","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuElement/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIMenuElement"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willPresentMenuFor:animator:)/title","op":"replace","value":"editMenuInteraction:willPresentMenuForConfiguration:animator:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willPresentMenuFor:animator:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"editMenuInteraction:willPresentMenuForConfiguration:animator:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/title","op":"replace","value":"UIEditMenuInteractionDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteractionDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIEditMenuInteractionDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder/title","op":"replace","value":"UIResponder"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder/fragments","op":"replace","value":[{"kind":"identifier","text":"UIResponder"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder/navigatorTitle","op":"replace","value":[{"text":"UIResponder","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willDismissMenuFor:animator:)/title","op":"replace","value":"editMenuInteraction:willDismissMenuForConfiguration:animator:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:willDismissMenuFor:animator:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:willDismissMenuForConfiguration:animator:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/title","op":"replace","value":"reloadVisibleMenu"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteraction~1reloadVisibleMenu()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reloadVisibleMenu"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/title","op":"replace","value":"editMenuInteraction:menuForConfiguration:suggestedActions:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEditMenuInteractionDelegate~1editMenuInteraction(_:menuFor:suggestedActions:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMenuInteraction:menuForConfiguration:suggestedActions:"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}