{
  "abstract": [
    {
      "text": "No font table options are specified.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/kCTFontTableOptionNoOptions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontTableOptions@kCTFontTableOptionNoOptions",
    "fragments": [
      {
        "kind": "identifier",
        "text": "kCTFontTableOptionNoOptions"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontTableOptionNoOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "symbolKind": "case",
    "title": "kCTFontTableOptionNoOptions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "kCTFontTableOptionNoOptions"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions": {
      "abstract": [
        {
          "text": "Constants that describe font table options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontTableOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontTableOptions"
        }
      ],
      "role": "symbol",
      "title": "CTFontTableOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctfonttableoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/excludeSynthetic": {
      "abstract": [
        {
          "text": "The font table excludes synthetic font data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "excludeSynthetic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontTableOptions",
          "text": "CTFontTableOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/excludeSynthetic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableOptionExcludeSynthetic"
        }
      ],
      "role": "symbol",
      "title": "excludeSynthetic",
      "type": "topic",
      "url": "/documentation/coretext/ctfonttableoptions/excludesynthetic"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/kCTFontTableOptionNoOptions": {
      "abstract": [
        {
          "text": "No font table options are specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCTFontTableOptionNoOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/kCTFontTableOptionNoOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCTFontTableOptionNoOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctfonttableoptions/kctfonttableoptionnooptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontTableOptions/excludeSynthetic"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontTableOptions/title",
          "value": "CTFontTableOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontTableOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontTableOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontTableOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontTableOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontTableOptions~1excludeSynthetic/title",
          "value": "kCTFontTableOptionExcludeSynthetic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontTableOptions~1excludeSynthetic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableOptionExcludeSynthetic"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfonttableoptions/kctfonttableoptionnooptions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
