{
  "abstract": [
    {
      "text": "Tells the delegate that the user is starting to pan the map.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)CPMapTemplateDelegate(im)mapTemplate:panBeganWithDirection:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "mapTemplate"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPMapTemplate",
        "text": "CPMapTemplate"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "panBeganWith"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPMapTemplate",
        "text": "CPMapTemplate"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CPPanDirection",
        "text": "PanDirection"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "mapTemplate:panBeganWithDirection:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "mapTemplate(_:panBeganWith:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "mapTemplate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPMapTemplate",
              "text": "CPMapTemplate"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "panBeganWith"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "direction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPMapTemplate",
              "text": "CPMapTemplate"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CPPanDirection",
              "text": "PanDirection"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current map template.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "mapTemplate"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The direction to move on the map.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "direction"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate": {
      "abstract": [
        {
          "text": "A template that displays a navigation overlay that your app draws on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection": {
      "abstract": [
        {
          "text": "The directions a user can pan (or move) a map displayed on the CarPlay screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PanDirection"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplate.PanDirection",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplate/pandirection"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate": {
      "abstract": [
        {
          "text": "The protocol an object implements to handle events from a map template.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPMapTemplateDelegate"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPMapTemplateDelegate"
        }
      ],
      "role": "symbol",
      "title": "CPMapTemplateDelegate",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture ended with the specified velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndPanGestureWithVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didEndPanGestureWithVelocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didEndPanGestureWithVelocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didendpangesturewithvelocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didUpdatePanGestureWithTranslation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "velocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:didupdatepangesturewithtranslation:velocity:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is starting to pan the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panBeganWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panBeganWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panBeganWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panBeganWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panbeganwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user stopped panning the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panEndedWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panEndedWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panEndedWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panendedwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user is panning in a certain direction on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "panWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CPPanDirection",
          "text": "PanDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplate:panWithDirection:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplate(_:panWith:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panwith:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the pan gesture has started.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidBeginPanGesture:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidBeginPanGesture(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidbeginpangesture(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is no longer visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatediddismisspanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface is visible on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateDidShowPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateDidShowPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatedidshowpanninginterface(_:)"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the panning interface will disappear from the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPMapTemplate",
          "text": "CPMapTemplate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mapTemplateWillDismissPanningInterface:"
        }
      ],
      "role": "symbol",
      "title": "mapTemplateWillDismissPanningInterface(_:)",
      "type": "topic",
      "url": "/documentation/carplay/cpmaptemplatedelegate/maptemplatewilldismisspanninginterface(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Panning-the-Map",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
        "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
      ],
      "title": "Panning the Map"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "mapTemplate:panBeganWithDirection:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panBeganWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Panning-the-Map",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidShowPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateWillDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidDismissPanningInterface(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplateDidBeginPanGesture(_:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:panEndedWith:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didEndPanGestureWithVelocity:)",
                "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplateDelegate/mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)"
              ],
              "title": "Panning the Map"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "mapTemplate:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)CPMapTemplate",
                    "text": "CPMapTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "mapTemplate"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "panBeganWithDirection:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPMapTemplate/PanDirection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CPPanDirection",
                    "text": "CPPanDirection"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "direction"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The current map template.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "mapTemplate"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The direction to move on the map.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "direction"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/title",
          "value": "CPMapTemplate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/title",
          "value": "mapTemplate:didEndPanGestureWithVelocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didEndPanGestureWithVelocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didEndPanGestureWithVelocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/title",
          "value": "mapTemplateDidBeginPanGesture:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidBeginPanGesture(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidBeginPanGesture:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/title",
          "value": "mapTemplateDidDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/title",
          "value": "mapTemplate:panBeganWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panBeganWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panBeganWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/title",
          "value": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:didUpdatePanGestureWithTranslation:velocity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:didUpdatePanGestureWithTranslation:velocity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/title",
          "value": "mapTemplate:panEndedWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panEndedWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panEndedWithDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/title",
          "value": "mapTemplateWillDismissPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateWillDismissPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateWillDismissPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/title",
          "value": "CPMapTemplateDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPMapTemplateDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/title",
          "value": "mapTemplateDidShowPanningInterface:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplateDidShowPanningInterface(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplateDidShowPanningInterface:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/title",
          "value": "CPPanDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplate~1PanDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPPanDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/title",
          "value": "mapTemplate:panWithDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPMapTemplateDelegate~1mapTemplate(_:panWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mapTemplate:panWithDirection:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panbeganwith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cpmaptemplatedelegate/maptemplate(_:panbeganwith:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
