{
  "abstract": [
    {
      "text": "An unsupported MMI codewas used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sirikit/documentation/Intents",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@INStartCallContactUnsupportedReason@INStartCallContactUnsupportedReasonUnsupportedMmiUssd",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "unsupportedMmiUssd"
      }
    ],
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "INStartCallContactUnsupportedReason.unsupportedMmiUssd"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "unsupportedMmiUssd"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sirikit/documentation/Intents": {
      "abstract": [
        {
          "text": "Empower people to customize interactions for your app on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents",
      "kind": "symbol",
      "role": "collection",
      "title": "Intents",
      "type": "topic",
      "url": "/documentation/intents"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason": {
      "abstract": [
        {
          "text": "Constants indicating the reason the app can’t support starting a call with the contact.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReason"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReason"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle": {
      "abstract": [
        {
          "text": "The handle is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidHandle"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonInvalidHandle"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.invalidHandle",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/invalidhandle"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported": {
      "abstract": [
        {
          "text": "The app doesn’t support calls with multiple contacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multipleContactsUnsupported"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.multipleContactsUnsupported",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/multiplecontactsunsupported"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial": {
      "abstract": [
        {
          "text": "No redial attempt doesn’t have an associated call history.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noCallHistoryForRedial"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noCallHistoryForRedial",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nocallhistoryforredial"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound": {
      "abstract": [
        {
          "text": "The contact wasn’t found in the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noContactFound"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoContactFound"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noContactFound",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nocontactfound"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel": {
      "abstract": [
        {
          "text": "The handle for the label wasn’t found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noHandleForLabel"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoHandleForLabel"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noHandleForLabel",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nohandleforlabel"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial": {
      "abstract": [
        {
          "text": "The redial attempt doesn’t have a usable handle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noUsableHandleForRedial"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.noUsableHandleForRedial",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/nousablehandleforredial"
    },
    "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd": {
      "abstract": [
        {
          "text": "An unsupported MMI codewas used.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedMmiUssd"
        }
      ],
      "identifier": "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/unsupportedMmiUssd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
        }
      ],
      "role": "symbol",
      "title": "INStartCallContactUnsupportedReason.unsupportedMmiUssd",
      "type": "topic",
      "url": "/documentation/intents/instartcallcontactunsupportedreason/unsupportedmmiussd"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
        "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sirikit/documentation/Intents",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noContactFound",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/multipleContactsUnsupported",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noHandleForLabel",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/invalidHandle",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noCallHistoryForRedial",
                "doc://com.apple.sirikit/documentation/Intents/INStartCallContactUnsupportedReason/noUsableHandleForRedial"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/title",
          "value": "INStartCallContactUnsupportedReason"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReason"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noContactFound/title",
          "value": "INStartCallContactUnsupportedReasonNoContactFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noContactFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoContactFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noUsableHandleForRedial/title",
          "value": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noUsableHandleForRedial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoUsableHandleForRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1multipleContactsUnsupported/title",
          "value": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1multipleContactsUnsupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonMultipleContactsUnsupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1invalidHandle/title",
          "value": "INStartCallContactUnsupportedReasonInvalidHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1invalidHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonInvalidHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noCallHistoryForRedial/title",
          "value": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noCallHistoryForRedial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoCallHistoryForRedial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1unsupportedMmiUssd/title",
          "value": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1unsupportedMmiUssd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonUnsupportedMmiUssd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noHandleForLabel/title",
          "value": "INStartCallContactUnsupportedReasonNoHandleForLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sirikit~1documentation~1Intents~1INStartCallContactUnsupportedReason~1noHandleForLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "INStartCallContactUnsupportedReasonNoHandleForLabel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/intents/instartcallcontactunsupportedreason/unsupportedmmiussd"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/intents/instartcallcontactunsupportedreason/unsupportedmmiussd"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
