{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWithOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutDimension","text":"NSLayoutDimension"}],"role":"symbol","externalID":"c:objc(cs)NSLayoutYAxisAnchor(im)anchorWithOffsetToAnchor:","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.0"},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.1"},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.0"},{"name":"visionOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"1.0"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"anchorWithOffsetToAnchor:"}],"modules":[{"name":"UIKit"}],"title":"anchorWithOffset(to:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"]]},"abstract":[{"type":"text","text":"Creates a layout dimension object from two anchors."}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/anchorWithOffset(to:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWithOffset"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":" ","kind":"text"},{"text":"otherAnchor","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSLayoutYAxisAnchor","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"text":") -> ","kind":"text"},{"text":"NSLayoutDimension","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutDimension"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The second anchor to use when creating the layout dimension."}]}],"name":"otherAnchor"}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension","type":"reference"},{"text":" object represented by the two anchors.","type":"text"}]}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Use the returned object to define constraints relative to the space between the current anchor and the object in the ","type":"text"},{"code":"otherAnchor","type":"codeVoice"},{"text":" parameter.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/nslayoutyaxisanchor/anchorwithoffset(to:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/nslayoutyaxisanchor/anchorwithoffset(to:)"]}],"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor":{"url":"/documentation/uikit/nslayoutyaxisanchor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"title":"NSLayoutYAxisAnchor","navigatorTitle":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A factory class for creating vertical layout constraint objects using a fluent API.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/anchorWithOffset(to:)":{"title":"anchorWithOffset(to:)","abstract":[{"type":"text","text":"Creates a layout dimension object from two anchors."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/anchorWithOffset(to:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"anchorWithOffset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSLayoutYAxisAnchor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutDimension","text":"NSLayoutDimension"}],"url":"/documentation/uikit/nslayoutyaxisanchor/anchorwithoffset(to:)","navigatorTitle":[{"kind":"identifier","text":"anchorWithOffsetToAnchor:"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension":{"navigatorTitle":[{"text":"NSLayoutDimension","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension","url":"/documentation/uikit/nslayoutdimension","type":"topic","title":"NSLayoutDimension","abstract":[{"type":"text","text":"A factory class for creating size-based layout constraint objects using a fluent API."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutDimension","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"iOS","introducedAt":"10.0","unavailable":false,"beta":false,"deprecated":false},{"name":"iPadOS","introducedAt":"10.0","unavailable":false,"beta":false,"deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","introducedAt":"10.0","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}]},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"anchorWithOffsetToAnchor:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWithOffsetToAnchor:"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutDimension","text":"NSLayoutDimension","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"anchorWithOffsetToAnchor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"otherAnchor","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/primaryContentSections/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The second anchor to use when creating the layout dimension."}],"type":"paragraph"}],"name":"otherAnchor"}],"kind":"parameters"}},{"path":"/primaryContentSections/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutDimension","type":"reference"},{"text":" object represented by the two anchors.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/title","op":"replace","value":"NSLayoutYAxisAnchor"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/fragments","op":"replace","value":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/navigatorTitle","op":"replace","value":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1anchorWithOffset(to:)/title","op":"replace","value":"anchorWithOffsetToAnchor:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1anchorWithOffset(to:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWithOffsetToAnchor:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutDimension/title","op":"replace","value":"NSLayoutDimension"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutDimension/fragments","op":"replace","value":[{"text":"NSLayoutDimension","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutDimension/navigatorTitle","op":"replace","value":[{"text":"NSLayoutDimension","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}