{"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"anchor":"Building-system-spacing-constraints","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(equalToSystemSpacingBelow:multiplier:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)","doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells"],"title":"Building system spacing constraints"}],"sections":[],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"constraint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"greaterThanOrEqualToSystemSpacingBelow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"multiplier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:","kind":"identifier"}],"platforms":[{"introducedAt":"11.0","beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"name":"iPadOS","introducedAt":"11.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","introducedAt":"11.0","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false,"unavailable":false}],"extendedModule":"UIKit","title":"constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)NSLayoutYAxisAnchor(im)constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/nslayoutyaxisanchor/constraint(greaterthanorequaltosystemspacingbelow:multiplier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/nslayoutyaxisanchor/constraint(greaterthanorequaltosystemspacingbelow:multiplier:)"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)","interfaceLanguage":"swift"},"abstract":[{"text":"Returns a constraint that defines the minimum distance by which the current anchor is positioned below the specified anchor.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"constraint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"greaterThanOrEqualToSystemSpacingBelow","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"anchor","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"multiplier","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"}]}]},{"parameters":[{"name":"anchor","content":[{"inlineContent":[{"text":"The anchor to use as the starting point for the constraint.","type":"text"}],"type":"paragraph"}]},{"name":"multiplier","content":[{"inlineContent":[{"text":"The multiple of the system spacing to use as the distance between the two anchors.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"An ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint","type":"reference","isActive":true},{"text":" object that imposes a minimum distance between the current anchor and the object in the ","type":"text"},{"type":"codeVoice","code":"anchor"},{"text":" parameter.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The constraint causes the current anchor to be positioned below the object in the "},{"code":"anchor","type":"codeVoice"},{"type":"text","text":" parameter. The minimum distance between the two anchors is determined by multiplying the system spacing by the value in the "},{"code":"multiplier","type":"codeVoice"},{"type":"text","text":" parameter. The value of the system spacing is determined from information available from the anchors. For example, if the anchors represent text baselines, the spacing is determined by the fonts used at those baselines."}],"type":"paragraph"}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor":{"url":"/documentation/uikit/nslayoutyaxisanchor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"title":"NSLayoutYAxisAnchor","navigatorTitle":[{"text":"NSLayoutYAxisAnchor","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A factory class for creating vertical layout constraint objects using a fluent API.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor","kind":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@CGFloat":{"abstract":[{"type":"text","text":"The basic type for all floating-point values."}],"identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat","role":"symbol","url":"/documentation/corefoundation/cgfloat","kind":"symbol","type":"topic","title":"CGFloat"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutConstraint","kind":"identifier"}],"title":"NSLayoutConstraint","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint","role":"symbol","type":"topic","url":"/documentation/uikit/nslayoutconstraint","abstract":[{"text":"The relationship between two user interface objects that must be satisfied by the constraint-based layout system.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"NSLayoutConstraint","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)":{"title":"constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)","kind":"symbol","url":"/documentation/uikit/nslayoutyaxisanchor/constraint(lessthanorequaltosystemspacingbelow:multiplier:)","navigatorTitle":[{"kind":"identifier","text":"constraintLessThanOrEqualToSystemSpacingBelowAnchor:multiplier:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"constraint","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lessThanOrEqualToSystemSpacingBelow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"multiplier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"}],"abstract":[{"text":"Returns a constraint that defines the maximum distance by which the current anchor is positioned below the specified anchor.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(equalToSystemSpacingBelow:multiplier:)":{"kind":"symbol","url":"/documentation/uikit/nslayoutyaxisanchor/constraint(equaltosystemspacingbelow:multiplier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"constraint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"equalToSystemSpacingBelow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","kind":"typeIdentifier","text":"NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"multiplier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"}],"navigatorTitle":[{"kind":"identifier","text":"constraintEqualToSystemSpacingBelowAnchor:multiplier:"}],"title":"constraint(equalToSystemSpacingBelow:multiplier:)","role":"symbol","abstract":[{"text":"Returns a constraint that defines the specific distance at which the current anchor is positioned below the specified anchor.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(equalToSystemSpacingBelow:multiplier:)"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV":{"kind":"symbol","role":"symbol","title":"CGFloat","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"CGFloat"}],"identifier":"doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV","url":"/documentation/corefoundation/cgfloat","abstract":[{"type":"text","text":"The basic type for floating-point scalar values in Core Graphics and related frameworks."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"constraint"},{"kind":"text","text":"("},{"kind":"externalParam","text":"greaterThanOrEqualToSystemSpacingBelow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","text":"NSLayoutYAxisAnchor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"multiplier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier","text":"NSLayoutConstraint"}],"role":"symbol","kind":"symbol","title":"constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)","navigatorTitle":[{"kind":"identifier","text":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:"}],"abstract":[{"type":"text","text":"Returns a constraint that defines the minimum distance by which the current anchor is positioned below the specified anchor."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)","url":"/documentation/uikit/nslayoutyaxisanchor/constraint(greaterthanorequaltosystemspacingbelow:multiplier:)"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells":{"title":"Creating self-sizing table view cells","type":"topic","role":"sampleCode","kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells","abstract":[{"type":"text","text":"Create table view cells that support Dynamic Type and use system spacing constraints to adjust the spacing surrounding text labels."}],"url":"/documentation/uikit/creating-self-sizing-table-view-cells"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"11.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"deprecated":false,"introducedAt":"11.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"11.0","name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:"}],"op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"anchor":"Building-system-spacing-constraints","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(equalToSystemSpacingBelow:multiplier:)","doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor/constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)","doc://com.apple.uikit/documentation/UIKit/creating-self-sizing-table-view-cells"],"title":"Building system spacing constraints"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSLayoutYAxisAnchor","preciseIdentifier":"c:objc(cs)NSLayoutYAxisAnchor","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutYAxisAnchor"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"anchor"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiplier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","identifier":"doc://com.externally.resolved.symbol/c:@T@CGFloat"},{"kind":"text","text":") "},{"kind":"internalParam","text":"multiplier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The anchor to use as the starting point for the constraint.","type":"text"}],"type":"paragraph"}],"name":"anchor"},{"content":[{"inlineContent":[{"type":"text","text":"The multiple of the system spacing to use as the distance between the two anchors."}],"type":"paragraph"}],"name":"multiplier"}]}},{"value":{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"text":"An ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint"},{"text":" object that imposes a minimum distance between the current anchor and the object in the ","type":"text"},{"code":"anchor","type":"codeVoice"},{"text":" parameter.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"/primaryContentSections/2","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/title","value":"NSLayoutYAxisAnchor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/fragments","value":[{"kind":"identifier","text":"NSLayoutYAxisAnchor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor/navigatorTitle","value":[{"kind":"identifier","text":"NSLayoutYAxisAnchor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/title","value":"NSLayoutConstraint"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/fragments","value":[{"kind":"identifier","text":"NSLayoutConstraint"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/navigatorTitle","value":[{"text":"NSLayoutConstraint","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)/title","value":"constraintLessThanOrEqualToSystemSpacingBelowAnchor:multiplier:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(lessThanOrEqualToSystemSpacingBelow:multiplier:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"constraintLessThanOrEqualToSystemSpacingBelowAnchor:multiplier:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(equalToSystemSpacingBelow:multiplier:)/title","value":"constraintEqualToSystemSpacingBelowAnchor:multiplier:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(equalToSystemSpacingBelow:multiplier:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"constraintEqualToSystemSpacingBelowAnchor:multiplier:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)/title","value":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutYAxisAnchor~1constraint(greaterThanOrEqualToSystemSpacingBelow:multiplier:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"constraintGreaterThanOrEqualToSystemSpacingBelowAnchor:multiplier:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}