{
  "abstract": [
    {
      "text": "A bit mask that can be combined with an ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " variable to yield only the direction portion of the format options.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionMask"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSLayoutFormatOptions@NSLayoutFormatDirectionMask",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "directionMask"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
        "text": "NSLayoutConstraint"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
        "text": "FormatOptions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSLayoutFormatDirectionMask"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "directionMask"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "directionMask"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
              "text": "NSLayoutConstraint"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
              "text": "FormatOptions"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline": {
      "abstract": [
        {
          "text": "The object’s baseline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeBaseline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLayoutAttributeBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutattribute/nslayoutattributebaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint": {
      "abstract": [
        {
          "text": "The relationship between two user interface objects that must be satisfied by the constraint-based layout system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutConstraint"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom": {
      "abstract": [
        {
          "text": "The bottom of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeBottom"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.bottom",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX": {
      "abstract": [
        {
          "text": "The center along the x-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerX"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterX"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerX",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/centerx"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY": {
      "abstract": [
        {
          "text": "The center along the y-axis of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeCenterY"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.centerY",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/centery"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading": {
      "abstract": [
        {
          "text": "The leading edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeading"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.leading",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/leading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left": {
      "abstract": [
        {
          "text": "The left side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeLeft"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.left",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right": {
      "abstract": [
        {
          "text": "The right side of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeRight"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.right",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top": {
      "abstract": [
        {
          "text": "The top of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTop"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.top",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing": {
      "abstract": [
        {
          "text": "The trailing edge of the object’s alignment rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutAttributeTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Attribute.trailing",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/attribute/trailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions": {
      "abstract": [
        {
          "text": "A bit mask that specifies both a part of an interface element to align and a direction for the alignment between two interface elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FormatOptions"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.FormatOptions",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllBottom": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/bottom",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllBottom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllBottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllBottom"
        }
      ],
      "role": "symbol",
      "title": "alignAllBottom",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallbottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterX": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerX",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllCenterX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllCenterX"
        }
      ],
      "role": "symbol",
      "title": "alignAllCenterX",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallcenterx"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterY": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/centerY",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllCenterY"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterY",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllCenterY"
        }
      ],
      "role": "symbol",
      "title": "alignAllCenterY",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallcentery"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllFirstBaseline": {
      "abstract": [
        {
          "text": "Align all specified interface elements using the first baseline of each one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllFirstBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllFirstBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllFirstBaseline"
        }
      ],
      "role": "symbol",
      "title": "alignAllFirstBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallfirstbaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLastBaseline": {
      "abstract": [
        {
          "text": "Align all specified interface elements using the last baseline of each one.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllLastBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLastBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllLastBaseline"
        }
      ],
      "role": "symbol",
      "title": "alignAllLastBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignalllastbaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeading": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/leading",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllLeading"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllLeading"
        }
      ],
      "role": "symbol",
      "title": "alignAllLeading",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallleading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeft": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/left",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllLeft"
        }
      ],
      "role": "symbol",
      "title": "alignAllLeft",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllRight": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/right",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllRight"
        }
      ],
      "role": "symbol",
      "title": "alignAllRight",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignallright"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTop": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/top",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllTop"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTop",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllTop"
        }
      ],
      "role": "symbol",
      "title": "alignAllTop",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignalltop"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTrailing": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Attribute/trailing",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignAllTrailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllTrailing"
        }
      ],
      "role": "symbol",
      "title": "alignAllTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignalltrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignmentMask": {
      "abstract": [
        {
          "text": "Bit mask that can be combined with a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " variable to yield only the alignment portion of the format options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignmentMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignmentMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignmentMask"
        }
      ],
      "role": "symbol",
      "title": "alignmentMask",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/alignmentmask"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeadingToTrailing": {
      "abstract": [
        {
          "text": "Arrange objects in order based on the normal text flow for the current user interface language. In left-to-right languages (like English), this arrangement results in the first object being placed farthest to the left, the next one to its right, and so on. In right-to-left languages (like Arabic or Hebrew), the ordering is reversed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionLeadingToTrailing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeadingToTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatDirectionLeadingToTrailing"
        }
      ],
      "role": "symbol",
      "title": "directionLeadingToTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/directionleadingtotrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeftToRight": {
      "abstract": [
        {
          "text": "Arrange objects in order from left to right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionLeftToRight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatDirectionLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "directionLeftToRight",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/directionlefttoright"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionMask": {
      "abstract": [
        {
          "text": "A bit mask that can be combined with an ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " variable to yield only the direction portion of the format options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatDirectionMask"
        }
      ],
      "role": "symbol",
      "title": "directionMask",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/directionmask"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionRightToLeft": {
      "abstract": [
        {
          "text": "Arrange objects in order from right to left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionRightToLeft"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionRightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatDirectionRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "directionRightToLeft",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/directionrighttoleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/spacingBaselineToBaseline": {
      "abstract": [
        {
          "text": "Align elements vertically according to their baseline positions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spacingBaselineToBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutConstraint",
          "text": "NSLayoutConstraint"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLayoutFormatOptions",
          "text": "FormatOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/spacingBaselineToBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatSpacingBaselineToBaseline"
        }
      ],
      "role": "symbol",
      "title": "spacingBaselineToBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/formatoptions/spacingbaselinetobaseline"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutFormatOptions/NSLayoutFormatAlignAllBaseline": {
      "abstract": [
        {
          "text": "Align all specified interface elements using ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutAttribute/NSLayoutAttributeBaseline",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " on each.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLayoutFormatAlignAllBaseline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutFormatOptions/NSLayoutFormatAlignAllBaseline",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLayoutFormatAlignAllBaseline",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutformatoptions/nslayoutformatalignallbaseline"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeft",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllRight",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTop",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllBottom",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeading",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTrailing",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterX",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterY",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLastBaseline",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllFirstBaseline",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignmentMask",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeadingToTrailing",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeftToRight",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionRightToLeft",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/spacingBaselineToBaseline"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSLayoutFormatDirectionMask"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatDirectionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeft",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllRight",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTop",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllBottom",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLeading",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllTrailing",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterX",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllCenterY",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutFormatOptions/NSLayoutFormatAlignAllBaseline",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllLastBaseline",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignAllFirstBaseline",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/alignmentMask",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeadingToTrailing",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionLeftToRight",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/FormatOptions/directionRightToLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSLayoutFormatDirectionMask"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/title",
          "value": "NSLayoutAttributeBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/title",
          "value": "NSLayoutConstraint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutConstraint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionMask/title",
          "value": "NSLayoutFormatDirectionMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatDirectionMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllRight/title",
          "value": "NSLayoutFormatAlignAllRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/title",
          "value": "NSLayoutAttributeCenterY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/title",
          "value": "NSLayoutAttributeTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/title",
          "value": "NSLayoutAttributeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllTop/title",
          "value": "NSLayoutFormatAlignAllTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllTop/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions/title",
          "value": "NSLayoutFormatOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignmentMask/title",
          "value": "NSLayoutFormatAlignmentMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignmentMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignmentMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionRightToLeft/title",
          "value": "NSLayoutFormatDirectionRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionRightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatDirectionRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllCenterY/title",
          "value": "NSLayoutFormatAlignAllCenterY"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllCenterY/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllCenterY"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/title",
          "value": "NSLayoutAttributeTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionLeftToRight/title",
          "value": "NSLayoutFormatDirectionLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionLeftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatDirectionLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLastBaseline/title",
          "value": "NSLayoutFormatAlignAllLastBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLastBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllLastBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1spacingBaselineToBaseline/title",
          "value": "NSLayoutFormatSpacingBaselineToBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1spacingBaselineToBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatSpacingBaselineToBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLeft/title",
          "value": "NSLayoutFormatAlignAllLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionLeadingToTrailing/title",
          "value": "NSLayoutFormatDirectionLeadingToTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1directionLeadingToTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatDirectionLeadingToTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/title",
          "value": "NSLayoutAttributeLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLeading/title",
          "value": "NSLayoutFormatAlignAllLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllFirstBaseline/title",
          "value": "NSLayoutFormatAlignAllFirstBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllFirstBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllFirstBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllTrailing/title",
          "value": "NSLayoutFormatAlignAllTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/title",
          "value": "NSLayoutAttributeCenterX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1centerX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeCenterX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/title",
          "value": "NSLayoutAttributeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Attribute~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutAttributeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllCenterX/title",
          "value": "NSLayoutFormatAlignAllCenterX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllCenterX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllCenterX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllBottom/title",
          "value": "NSLayoutFormatAlignAllBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1FormatOptions~1alignAllBottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutFormatAlignAllBottom"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nslayoutconstraint/formatoptions/directionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nslayoutconstraint/formatoptions/directionmask"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
