{
  "abstract": [
    {
      "text": "A point of interest, address, or other identifiable location.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.watchkit/documentation/WatchKit",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "WatchKit",
    "externalID": "c:@WKTextContentTypeLocation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "location"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@WKTextContentType",
        "text": "WKTextContentType"
      }
    ],
    "modules": [
      {
        "name": "WatchKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "WKTextContentTypeLocation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "location"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "location"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@WKTextContentType",
              "text": "WKTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.watchkit/documentation/WatchKit": {
      "abstract": [
        {
          "text": "Build watchOS apps that use features the app delegate monitors or controls, such as background tasks and extended runtime sessions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit",
      "kind": "symbol",
      "role": "collection",
      "title": "WatchKit",
      "type": "topic",
      "url": "/documentation/watchkit"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType": {
      "abstract": [
        {
          "text": "Constants that specify a text field’s semantic meaning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentType"
        }
      ],
      "role": "symbol",
      "title": "WKTextContentType",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity": {
      "abstract": [
        {
          "text": "The name of a city.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressCity"
        }
      ],
      "role": "symbol",
      "title": "addressCity",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addresscity"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState": {
      "abstract": [
        {
          "text": "The name of a city and state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCityAndState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressCityAndState"
        }
      ],
      "role": "symbol",
      "title": "addressCityAndState",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addresscityandstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState": {
      "abstract": [
        {
          "text": "The name of a state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeAddressState"
        }
      ],
      "role": "symbol",
      "title": "addressState",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/addressstate"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName": {
      "abstract": [
        {
          "text": "The name of a country or region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeCountryName"
        }
      ],
      "role": "symbol",
      "title": "countryName",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/countryname"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress": {
      "abstract": [
        {
          "text": "The full street address for a location, including the unit or suite number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullStreetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeFullStreetAddress"
        }
      ],
      "role": "symbol",
      "title": "fullStreetAddress",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/fullstreetaddress"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location": {
      "abstract": [
        {
          "text": "A point of interest, address, or other identifiable location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeLocation"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/location"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode": {
      "abstract": [
        {
          "text": "A postal code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypePostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/postalcode"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1": {
      "abstract": [
        {
          "text": "The first line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeStreetAddressLine1"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine1",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/streetaddressline1"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2": {
      "abstract": [
        {
          "text": "The second line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeStreetAddressLine2"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine2",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/streetaddressline2"
    },
    "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality": {
      "abstract": [
        {
          "text": "The sublocality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sublocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@WKTextContentType",
          "text": "WKTextContentType"
        }
      ],
      "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WKTextContentTypeSublocality"
        }
      ],
      "role": "symbol",
      "title": "sublocality",
      "type": "topic",
      "url": "/documentation/watchkit/wktextcontenttype/sublocality"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Address",
      "generated": true,
      "identifiers": [
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
        "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode"
      ],
      "title": "Address"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "WKTextContentTypeLocation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.watchkit/documentation/WatchKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Address",
              "generated": true,
              "identifiers": [
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/fullStreetAddress",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine1",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/streetAddressLine2",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCity",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/addressCityAndState",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/sublocality",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/countryName",
                "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType/postalCode"
              ],
              "title": "Address"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.watchkit/documentation/WatchKit/WKTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@WKTextContentType",
                    "text": "WKTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "WKTextContentTypeLocation"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1location/title",
          "value": "WKTextContentTypeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine1/title",
          "value": "WKTextContentTypeStreetAddressLine1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeStreetAddressLine1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/title",
          "value": "WKTextContentTypePostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypePostalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressState/title",
          "value": "WKTextContentTypeAddressState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1sublocality/title",
          "value": "WKTextContentTypeSublocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1sublocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeSublocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1fullStreetAddress/title",
          "value": "WKTextContentTypeFullStreetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1fullStreetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeFullStreetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1countryName/title",
          "value": "WKTextContentTypeCountryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1countryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeCountryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCity/title",
          "value": "WKTextContentTypeAddressCity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressCity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine2/title",
          "value": "WKTextContentTypeStreetAddressLine2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1streetAddressLine2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeStreetAddressLine2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/title",
          "value": "WKTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCityAndState/title",
          "value": "WKTextContentTypeAddressCityAndState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.watchkit~1documentation~1WatchKit~1WKTextContentType~1addressCityAndState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "WKTextContentTypeAddressCityAndState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/watchkit/wktextcontenttype/location"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/watchkit/wktextcontenttype/location"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
