{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Styles that determine the appearance of the switch."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]}],"topicSections":[{"anchor":"Styles","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic","doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox","doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding"],"title":"Styles"},{"anchor":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)"],"title":"Initializers","generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Style"}],"externalID":"c:@E@UISwitchStyle","roleHeading":"Enumeration","symbolKind":"enum","extendedModule":"UIKit","role":"symbol","title":"UISwitch.Style","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"14.0","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"14.0","beta":false,"deprecated":false},{"introducedAt":"14.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false,"name":"visionOS"}]},"variants":[{"paths":["/documentation/uikit/uiswitch/style-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiswitch/style-swift.enum"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Setting-the-display-style","identifiers":["doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst","doc://com.apple.uikit/documentation/UIKit/UISwitch/preferredStyle","doc://com.apple.uikit/documentation/UIKit/UISwitch/style-swift.property","doc://com.apple.uikit/documentation/UIKit/UISwitch/title"],"title":"Setting the display style","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISwitch"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UISwitch/style-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISwitch","kind":"typeIdentifier","text":"UISwitch"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UISwitchStyle","kind":"typeIdentifier","text":"Style"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/style-swift.property","kind":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.property","abstract":[{"type":"text","text":"The display style for the switch."}],"navigatorTitle":[{"kind":"identifier","text":"style"}],"role":"symbol","title":"style"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/preferredStyle":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISwitch","kind":"typeIdentifier","text":"UISwitch"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UISwitchStyle","kind":"typeIdentifier","text":"Style"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/preferredStyle","kind":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/preferredstyle","abstract":[{"type":"text","text":"The preferred display style for the switch."}],"navigatorTitle":[{"kind":"identifier","text":"preferredStyle"}],"role":"symbol","title":"preferredStyle"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)","kind":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum/init(rawvalue:)","abstract":[],"role":"symbol","title":"init(rawValue:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic":{"title":"UISwitch.Style.automatic","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum/automatic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"abstract":[{"type":"text","text":"A style indicating that the system chooses the appearance of the switch according to the current user interface idiom."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic","navigatorTitle":[{"text":"UISwitchStyleAutomatic","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding":{"title":"UISwitch.Style.sliding","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum/sliding","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sliding","kind":"identifier"}],"abstract":[{"type":"text","text":"A style indicating that the switch appears as an on/off slider."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding","navigatorTitle":[{"text":"UISwitchStyleSliding","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox":{"title":"UISwitch.Style.checkbox","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum/checkbox","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"}],"abstract":[{"type":"text","text":"A style indicating that the switch appears as a Mac-style checkbox."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox","navigatorTitle":[{"text":"UISwitchStyleCheckbox","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISwitch":{"abstract":[{"type":"text","text":"A control that offers a binary choice, such as on/off."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISwitch"}],"role":"symbol","url":"/documentation/uikit/uiswitch","navigatorTitle":[{"kind":"identifier","text":"UISwitch"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch","type":"topic","title":"UISwitch","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/title":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/title","kind":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/title","abstract":[{"type":"text","text":"The title displayed next to a checkbox-style switch."}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"role":"symbol","title":"title"},"doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst":{"abstract":[{"type":"text","text":"Present a switch control as a Mac-style checkbox when your app runs in the Mac user interface idiom."}],"kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst","url":"/documentation/uikit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst","title":"Displaying a checkbox in your Mac app built with Mac Catalyst","type":"topic","role":"article"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum":{"title":"UISwitch.Style","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"abstract":[{"type":"text","text":"Styles that determine the appearance of the switch."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration","op":"replace","path":"/metadata/roleHeading"},{"value":"UISwitchStyle","op":"replace","path":"/metadata/title"},{"value":"enum","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UISwitchStyle"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"kind":"identifier","text":"UISwitchStyle"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic","doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox","doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding"],"anchor":"Styles","title":"Styles"}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"anchor":"Setting-the-display-style","identifiers":["doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst","doc://com.apple.uikit/documentation/UIKit/UISwitch/preferredStyle","doc://com.apple.uikit/documentation/UIKit/UISwitch/style-swift.property","doc://com.apple.uikit/documentation/UIKit/UISwitch/title"],"title":"Setting the display style","generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISwitchStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1style-swift.property/title","op":"replace","value":"style"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1style-swift.property/fragments","op":"replace","value":[{"text":"style","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1preferredStyle/title","op":"replace","value":"preferredStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1preferredStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"preferredStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1automatic/title","op":"replace","value":"UISwitchStyleAutomatic"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1automatic/fragments","op":"replace","value":[{"text":"UISwitchStyleAutomatic","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1sliding/title","op":"replace","value":"UISwitchStyleSliding"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1sliding/fragments","op":"replace","value":[{"kind":"identifier","text":"UISwitchStyleSliding"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1checkbox/title","op":"replace","value":"UISwitchStyleCheckbox"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1checkbox/fragments","op":"replace","value":[{"kind":"identifier","text":"UISwitchStyleCheckbox"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/title","value":"UISwitch"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/fragments","value":[{"text":"UISwitch","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/navigatorTitle","value":[{"text":"UISwitch","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1title/title","value":"title"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1title/fragments","value":[{"kind":"identifier","text":"title"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/title","value":"UISwitchStyle"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/fragments","value":[{"text":"UISwitchStyle","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/navigatorTitle","value":[{"kind":"identifier","text":"UISwitchStyle"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}