{"variants":[{"paths":["/documentation/uikit/nslayoutmanager/glyphproperty/null"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/nslayoutmanager/glyphproperty/null"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The null glyph, which the layout manager ignores.","type":"text"}],"sections":[],"seeAlsoSections":[{"title":"Glyph properties","anchor":"Glyph-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"null"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutManager","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager","text":"NSLayoutManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSGlyphProperty","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty","text":"GlyphProperty"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"null","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSLayoutManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"text":".","kind":"text"},{"text":"GlyphProperty","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSGlyphProperty"}],"navigatorTitle":[{"text":"NSGlyphPropertyNull","kind":"identifier"}],"title":"null","platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"7.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"7.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1","deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0","deprecated":false}],"modules":[{"name":"UIKit"}],"role":"symbol","externalID":"c:@E@NSGlyphProperty@NSGlyphPropertyNull","symbolKind":"property","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty"]]},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null","interfaceLanguage":"swift"},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty","navigatorTitle":[{"kind":"identifier","text":"GlyphProperty"}],"title":"NSLayoutManager.GlyphProperty","abstract":[{"text":"Glyph properties.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"elastic"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutManager","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"GlyphProperty","preciseIdentifier":"c:@E@NSGlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty/elastic","navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyElastic"}],"title":"elastic","abstract":[{"type":"text","text":"A glyph with a changeable width, such as a white space character."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter":{"url":"/documentation/uikit/nslayoutmanager/glyphproperty/nonbasecharacter","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter","role":"symbol","navigatorTitle":[{"text":"NSGlyphPropertyNonBaseCharacter","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonBaseCharacter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSLayoutManager","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutManager"},{"text":".","kind":"text"},{"text":"GlyphProperty","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSGlyphProperty"}],"type":"topic","title":"nonBaseCharacter","kind":"symbol","abstract":[{"text":"A glyph that combines several properties.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSLayoutManager","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that coordinates the layout and display of text characters."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager","role":"symbol","url":"/documentation/uikit/nslayoutmanager","kind":"symbol","navigatorTitle":[{"text":"NSLayoutManager","kind":"identifier"}],"type":"topic","title":"NSLayoutManager"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"null","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier","text":"NSLayoutManager"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier","text":"GlyphProperty"}],"url":"/documentation/uikit/nslayoutmanager/glyphproperty/null","navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyNull"}],"title":"null","abstract":[{"type":"text","text":"The null glyph, which the layout manager ignores."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/null"},"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter":{"role":"symbol","url":"/documentation/uikit/nslayoutmanager/glyphproperty/controlcharacter","abstract":[{"text":"A glyph representing a control character.","type":"text"}],"type":"topic","title":"controlCharacter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"controlCharacter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutManager","kind":"typeIdentifier","text":"NSLayoutManager"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSGlyphProperty","kind":"typeIdentifier","text":"GlyphProperty"}],"navigatorTitle":[{"kind":"identifier","text":"NSGlyphPropertyControlCharacter"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"7.0","deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"7.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"13.1","deprecated":false},{"name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","unavailable":false,"beta":false,"introducedAt":"1.0","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"/metadata/title","value":"NSGlyphPropertyNull"},{"op":"replace","path":"/metadata/symbolKind","value":"case"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"NSGlyphPropertyNull","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty"]]}},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Glyph-properties","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/controlCharacter","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/elastic","doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/GlyphProperty/nonBaseCharacter"],"title":"Glyph properties"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"NSGlyphPropertyNull","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"value":"NSGlyphProperty","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/title"},{"value":[{"text":"NSGlyphProperty","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/fragments"},{"value":[{"text":"NSGlyphProperty","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty/navigatorTitle"},{"value":"NSGlyphPropertyElastic","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1elastic/title"},{"value":[{"kind":"identifier","text":"NSGlyphPropertyElastic"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1elastic/fragments"},{"value":"NSGlyphPropertyNonBaseCharacter","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1nonBaseCharacter/title"},{"value":[{"kind":"identifier","text":"NSGlyphPropertyNonBaseCharacter"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1nonBaseCharacter/fragments"},{"value":"NSLayoutManager","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title"},{"value":[{"text":"NSLayoutManager","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments"},{"value":[{"kind":"identifier","text":"NSLayoutManager"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle"},{"value":"NSGlyphPropertyNull","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1null/title"},{"value":[{"kind":"identifier","text":"NSGlyphPropertyNull"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1null/fragments"},{"value":"NSGlyphPropertyControlCharacter","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1controlCharacter/title"},{"value":[{"kind":"identifier","text":"NSGlyphPropertyControlCharacter"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1GlyphProperty~1controlCharacter/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}