{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@U@vS256@FI@s",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "s"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@U@vS256",
        "text": "vS256"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "text": "__Unnamed_struct_s"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "s"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "s"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "s"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@U@vS256",
              "text": "vS256"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "kind": "typeIdentifier",
              "text": "__Unnamed_struct_s"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256": {
      "abstract": [
        {
          "text": "A union containing an array or structure of two ",
          "type": "text"
        },
        {
          "code": "vUInt32",
          "type": "codeVoice"
        },
        {
          "text": " vectors or eight 32-bit integers, representing a 256-bit signed integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vS256"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vS256"
        }
      ],
      "role": "symbol",
      "title": "vS256",
      "type": "topic",
      "url": "/documentation/accelerate/vs256"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "s"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_s"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "s"
        }
      ],
      "role": "symbol",
      "title": "s",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/LSW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "LSW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/LSW",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSW",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/lsw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/MSW": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "MSW"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/MSW",
      "kind": "symbol",
      "role": "symbol",
      "title": "MSW",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/msw"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d2",
      "kind": "symbol",
      "role": "symbol",
      "title": "d2",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d2"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d3": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d3",
      "kind": "symbol",
      "role": "symbol",
      "title": "d3",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d3"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d4": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d4",
      "kind": "symbol",
      "role": "symbol",
      "title": "d4",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d4"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d5": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d5"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d5",
      "kind": "symbol",
      "role": "symbol",
      "title": "d5",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d5"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d6": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d6"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d6",
      "kind": "symbol",
      "role": "symbol",
      "title": "d6",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d6"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d7": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "d7"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d7",
      "kind": "symbol",
      "role": "symbol",
      "title": "d7",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/s/d7"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/v": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "v"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@vUInt32",
          "text": "vUInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/v",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "v"
        }
      ],
      "role": "symbol",
      "title": "v",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/v"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@U@vS256",
          "text": "vS256"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "text": "__Unnamed_struct_vs"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "vs"
        }
      ],
      "role": "symbol",
      "title": "vs",
      "type": "topic",
      "url": "/documentation/accelerate/vs256/vs"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256/v",
        "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.accelerate/documentation/Accelerate",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/LSW",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/MSW",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d2",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d3",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d4",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d5",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d6",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/s/d7"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/v",
                "doc://com.apple.accelerate/documentation/Accelerate/vS256/vs"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "s"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1vs/title",
          "value": "vs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1vs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/title",
          "value": "vS256"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "vS256"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1s/title",
          "value": "s"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1s/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "s"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1v/title",
          "value": "v"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1vS256~1v/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "v"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/vs256/s"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/accelerate/vs256/s"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
