{
  "abstract": [
    {
      "text": "The delegate object for the highlight center.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter/delegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SWHighlightCenter(py)delegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "delegate"
      },
      {
        "kind": "text",
        "text": ": (any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)SWHighlightCenterDelegate",
        "text": "SWHighlightCenterDelegate"
      },
      {
        "kind": "text",
        "text": ")?"
      }
    ],
    "modules": [
      {
        "name": "Shared With You"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "delegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "delegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "delegate"
            },
            {
              "kind": "text",
              "text": ": (any "
            },
            {
              "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenterDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)SWHighlightCenterDelegate",
              "text": "SWHighlightCenterDelegate"
            },
            {
              "kind": "text",
              "text": ")? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou": {
      "abstract": [
        {
          "text": "Surface shared content and collaborate in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
      "kind": "symbol",
      "role": "collection",
      "title": "Shared With You",
      "type": "topic",
      "url": "/documentation/sharedwithyou"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter": {
      "abstract": [
        {
          "text": "An object that contains a priority-ordered list of universal links to share with the current user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightCenter"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightCenter"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightCenter",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightcenter"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter/delegate": {
      "abstract": [
        {
          "text": "The delegate object for the highlight center.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)SWHighlightCenterDelegate",
          "text": "SWHighlightCenterDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightcenter/delegate"
    },
    "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenterDelegate": {
      "abstract": [
        {
          "text": "The protocol you use to notify the delegate when the list or rank order of surfaced highlights changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SWHighlightCenterDelegate"
        }
      ],
      "identifier": "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenterDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SWHighlightCenterDelegate"
        }
      ],
      "role": "symbol",
      "title": "SWHighlightCenterDelegate",
      "type": "topic",
      "url": "/documentation/sharedwithyou/swhighlightcenterdelegate"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-the-delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenterDelegate"
      ],
      "title": "Setting the delegate"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou",
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenter"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-the-delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.sharedwithyou/documentation/SharedWithYou/SWHighlightCenterDelegate"
              ],
              "title": "Setting the delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "weak"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Qoobjc(pl)SWHighlightCenterDelegate",
                    "text": "id<SWHighlightCenterDelegate>"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "delegate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenterDelegate/title",
          "value": "SWHighlightCenterDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenterDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenterDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenterDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/title",
          "value": "SWHighlightCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.sharedwithyou~1documentation~1SharedWithYou~1SWHighlightCenter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SWHighlightCenter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightcenter/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/sharedwithyou/swhighlightcenter/delegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
