{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isInterruptible","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the transition animations can be interrupted."}],"kind":"symbol","seeAlsoSections":[{"title":"Getting the transition state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/initiallyInteractive","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInteractive","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isAnimated","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isCancelled"],"anchor":"Getting-the-transition-state","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInterruptible"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInterruptible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"required":true,"externalID":"c:objc(pl)UIViewControllerTransitionCoordinatorContext(py)isInterruptible","symbolKind":"property","title":"isInterruptible","navigatorTitle":[{"kind":"identifier","text":"isInterruptible"}],"roleHeading":"Instance Property","platforms":[{"deprecated":false,"beta":false,"introducedAt":"10.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"10.0","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"10.0","name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"modules":[{"name":"UIKit"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]]},"variants":[{"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/isinterruptible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/isinterruptible"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isAnimated":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isAnimated","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isAnimated","navigatorTitle":[{"text":"animated","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the transition is explicitly animated."}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/isanimated","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isAnimated","required":true},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"abstract":[{"text":"Type to represent a Boolean value.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","url":"/documentation/objectivec/bool","kind":"symbol","type":"topic","title":"BOOL"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/initiallyInteractive":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/initiallyInteractive","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initiallyInteractive"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initiallyInteractive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the transition started as an interactive transition."}],"kind":"symbol","required":true,"type":"topic","title":"initiallyInteractive","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/initiallyinteractive"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInteractive":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInteractive","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"interactive"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInteractive","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the transition is currently interactive."}],"kind":"symbol","required":true,"type":"topic","title":"isInteractive","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/isinteractive"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isCancelled":{"kind":"symbol","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/iscancelled","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isCancelled","abstract":[{"text":"A Boolean value indicating whether an interactive transition was canceled.","type":"text"}],"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelled"}],"title":"isCancelled"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext","role":"symbol","title":"UIViewControllerTransitionCoordinatorContext","abstract":[{"type":"text","text":"A set of methods that provides information about an in-progress view controller transition."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInterruptible":{"kind":"symbol","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/isinterruptible","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInterruptible","abstract":[{"text":"A Boolean value indicating whether the transition animations can be interrupted.","type":"text"}],"type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInterruptible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isInterruptible"}],"title":"isInterruptible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"10.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"10.0"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"10.0","deprecated":false},{"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"isInterruptible"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"isInterruptible","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Getting the transition state","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/initiallyInteractive","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isInteractive","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isAnimated","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/isCancelled"],"anchor":"Getting-the-transition-state","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isInterruptible","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"animated","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isAnimated/title","op":"replace"},{"value":[{"kind":"identifier","text":"animated"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isAnimated/fragments","op":"replace"},{"value":"initiallyInteractive","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1initiallyInteractive/title","op":"replace"},{"value":[{"kind":"identifier","text":"initiallyInteractive"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1initiallyInteractive/fragments","op":"replace"},{"value":"interactive","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isInteractive/title","op":"replace"},{"value":[{"text":"interactive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isInteractive/fragments","op":"replace"},{"value":"cancelled","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isCancelled/title","op":"replace"},{"value":[{"kind":"identifier","text":"cancelled"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isCancelled/fragments","op":"replace"},{"value":"UIViewControllerTransitionCoordinatorContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/title","op":"replace"},{"value":[{"text":"UIViewControllerTransitionCoordinatorContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/navigatorTitle","value":[{"text":"UIViewControllerTransitionCoordinatorContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isInterruptible/title","value":"isInterruptible","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1isInterruptible/fragments","value":[{"text":"isInterruptible","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}