{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"viewForKey:","kind":"identifier"}],"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UIViewControllerTransitionCoordinatorContext(im)viewForKey:","title":"view(forKey:)","role":"symbol","platforms":[{"beta":false,"unavailable":false,"introducedAt":"8.0","name":"iOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"8.0","name":"iPadOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"view","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITransitionContextViewKey","kind":"typeIdentifier","preciseIdentifier":"c:@T@UITransitionContextViewKey"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/view(forkey:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/view(forkey:)"]}],"sections":[],"seeAlsoSections":[{"anchor":"Getting-the-views-and-view-controllers","title":"Getting the views and view controllers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/viewController(forKey:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView"],"generated":true}],"abstract":[{"text":"Returns the specified view involved in the transition.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/view(forKey:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey","kind":"typeIdentifier","text":"UITransitionContextViewKey","preciseIdentifier":"c:@T@UITransitionContextViewKey"},{"kind":"text","text":") -> "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The key identifying the view you want. For a list of possible keys, see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey","type":"reference"},{"text":".","type":"text"}]}],"name":"key"}]},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The view object for the specified key or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the view could not be found."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/view(forKey:)":{"abstract":[{"text":"Returns the specified view involved in the transition.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/view(forKey:)","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/view(forkey:)","title":"view(forKey:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"view"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UITransitionContextViewKey","text":"UITransitionContextViewKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"viewForKey:"}],"role":"symbol","required":true,"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView":{"kind":"symbol","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/containerview","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"text":"Returns the view in which the transition takes place.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"containerView"}],"title":"containerView","role":"symbol","type":"topic","required":true},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext","role":"symbol","title":"UIViewControllerTransitionCoordinatorContext","abstract":[{"type":"text","text":"A set of methods that provides information about an in-progress view controller transition."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/viewController(forKey:)":{"kind":"symbol","url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext/viewcontroller(forkey:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/viewController(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UITransitionContextViewControllerKey","text":"UITransitionContextViewControllerKey"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"text":"Returns the view controllers involved in the transition.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewControllerForKey:"}],"title":"viewController(forKey:)","role":"symbol","type":"topic","required":true},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey","title":"UITransitionContextViewKey","role":"symbol","navigatorTitle":[{"text":"UITransitionContextViewKey","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITransitionContextViewKey","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The keys you use to identify the views involved in a transition."}],"url":"/documentation/uikit/uitransitioncontextviewkey","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"deprecated":false,"introducedAt":"8.0","name":"iOS","beta":false},{"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"8.0","unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"introducedAt":"1.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"viewForKey:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForKey:"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"title":"Getting the views and view controllers","generated":true,"anchor":"Getting-the-views-and-view-controllers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/viewController(forKey:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext/containerView"]}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey","preciseIdentifier":"c:@T@UITransitionContextViewKey","text":"UITransitionContextViewKey","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The key identifying the view you want. For a list of possible keys, see ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITransitionContextViewKey","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"/primaryContentSections/1","op":"replace"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The view object for the specified key or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the view could not be found."}],"type":"paragraph"}]},"path":"/primaryContentSections/2"},{"value":"viewForKey:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1view(forKey:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewForKey:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1view(forKey:)/fragments","op":"replace"},{"value":"containerView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1containerView/title","op":"replace"},{"value":[{"kind":"identifier","text":"containerView"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1containerView/fragments","op":"replace"},{"value":"UIViewControllerTransitionCoordinatorContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/title","op":"replace"},{"value":[{"text":"UIViewControllerTransitionCoordinatorContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/fragments","op":"replace"},{"value":[{"text":"UIViewControllerTransitionCoordinatorContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/navigatorTitle","op":"replace"},{"value":"viewControllerForKey:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1viewController(forKey:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewControllerForKey:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext~1viewController(forKey:)/fragments","op":"replace"},{"value":"UIView","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title","op":"replace"},{"value":[{"text":"UIView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments","op":"replace"},{"value":[{"text":"UIView","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle","op":"replace"},{"value":"UITransitionContextViewKey","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITransitionContextViewKey/title","op":"replace"},{"value":[{"text":"UITransitionContextViewKey","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITransitionContextViewKey/fragments","op":"replace"},{"value":[{"text":"UITransitionContextViewKey","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITransitionContextViewKey/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}