{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uifocusupdatecontext/nextfocuseditem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uifocusupdatecontext/nextfocuseditem"]}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextFocusedItem","kind":"identifier"},{"text":": (any ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem","text":"UIFocusItem","preciseIdentifier":"c:objc(pl)UIFocusItem","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This property is set to ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if no item is receiving the focus.","type":"text"}]}]}],"seeAlsoSections":[{"anchor":"Getting-related-focus-items","title":"Getting related focus items","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem"]}],"metadata":{"title":"nextFocusedItem","externalID":"c:objc(cs)UIFocusUpdateContext(py)nextFocusedItem","navigatorTitle":[{"kind":"identifier","text":"nextFocusedItem"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextFocusedItem","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIFocusItem","text":"UIFocusItem","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"platforms":[{"beta":false,"deprecated":false,"introducedAt":"10.0","name":"iOS","unavailable":false},{"introducedAt":"10.0","beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"introducedAt":"13.1","beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"introducedAt":"10.0","beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"modules":[{"name":"UIKit"}],"role":"symbol","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedItem","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The item to be focused after the update."}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem":{"role":"symbol","abstract":[{"text":"The item that was focused before the update.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"previouslyFocusedItem"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previouslyFocusedItem","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UIFocusItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusItem"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem","title":"previouslyFocusedItem","url":"/documentation/uikit/uifocusupdatecontext/previouslyfocuseditem"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusUpdateContext","kind":"identifier"}],"role":"symbol","title":"UIFocusUpdateContext","url":"/documentation/uikit/uifocusupdatecontext","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext","navigatorTitle":[{"text":"UIFocusUpdateContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An object that provides information relevant to a specific focus update from one view to another.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIFocusItem":{"abstract":[{"text":"An object that can become focused.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusItem","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusItem","type":"topic","title":"UIFocusItem","kind":"symbol","role":"symbol","url":"/documentation/uikit/uifocusitem","navigatorTitle":[{"text":"UIFocusItem","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedItem":{"role":"symbol","abstract":[{"text":"The item to be focused after the update.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nextFocusedItem"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextFocusedItem"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusItem","text":"UIFocusItem"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedItem","title":"nextFocusedItem","url":"/documentation/uikit/uifocusupdatecontext/nextfocuseditem"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"introducedAt":"10.0","name":"iOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"10.0","name":"iPadOS","unavailable":false},{"beta":false,"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"unavailable":false,"deprecated":false,"name":"tvOS","introducedAt":"10.0","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","introducedAt":"1.0","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Property","op":"replace"},{"path":"/metadata/title","op":"replace","value":"nextFocusedItem"},{"path":"/metadata/symbolKind","op":"replace","value":"property"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"nextFocusedItem"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext"]]}},{"path":"/topicSections","op":"add","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Getting-related-focus-items","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem"],"title":"Getting related focus items"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIFocusItem","text":"id<UIFocusItem>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"nextFocusedItem","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"previouslyFocusedItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedItem/title"},{"op":"replace","value":[{"text":"previouslyFocusedItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedItem/fragments"},{"op":"replace","value":"UIFocusUpdateContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIFocusUpdateContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/fragments"},{"op":"replace","value":[{"text":"UIFocusUpdateContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/navigatorTitle"},{"op":"replace","value":"UIFocusItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIFocusItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/fragments"},{"op":"replace","value":[{"text":"UIFocusItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/navigatorTitle"},{"op":"replace","value":"nextFocusedItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1nextFocusedItem/title"},{"op":"replace","value":[{"text":"nextFocusedItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1nextFocusedItem/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}