{"sections":[],"abstract":[{"text":"The view that was focused before the focus update.","type":"text"}],"variants":[{"paths":["/documentation/uikit/uifocusupdatecontext/previouslyfocusedview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uifocusupdatecontext/previouslyfocusedview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext"]]},"kind":"symbol","seeAlsoSections":[{"generated":true,"anchor":"Locating-focus-direction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedView","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/focusHeading","doc://com.apple.uikit/documentation/UIKit/UIFocusHeading"],"title":"Locating focus direction"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"previouslyFocusedView","modules":[{"name":"UIKit"}],"externalID":"c:objc(cs)UIFocusUpdateContext(py)previouslyFocusedView","navigatorTitle":[{"kind":"identifier","text":"previouslyFocusedView"}],"platforms":[{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previouslyFocusedView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previouslyFocusedView"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"Discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If your app targets tvOS 10 and later, use "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem"},{"type":"text","text":" instead."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property returns "},{"code":"nil","type":"codeVoice"},{"text":" when no view was previously focused, such as when setting the initial focus.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedView":{"navigatorTitle":[{"text":"previouslyFocusedView","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedView","title":"previouslyFocusedView","url":"/documentation/uikit/uifocusupdatecontext/previouslyfocusedview","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"previouslyFocusedView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The view that was focused before the focus update."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/focusHeading":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"focusHeading"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/focusHeading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusHeading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIFocusHeading","text":"UIFocusHeading"}],"kind":"symbol","url":"/documentation/uikit/uifocusupdatecontext/focusheading","abstract":[{"type":"text","text":"The heading in which the focus update is occurring."}],"title":"focusHeading","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedView":{"role":"symbol","abstract":[{"text":"The view that takes the focus after the focus update.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"nextFocusedView","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nextFocusedView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedView","title":"nextFocusedView","url":"/documentation/uikit/uifocusupdatecontext/nextfocusedview"},"doc://com.apple.uikit/documentation/UIKit/UIFocusHeading":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusHeading","navigatorTitle":[{"text":"UIFocusHeading","kind":"identifier"}],"type":"topic","abstract":[{"text":"The general type of an event.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusHeading","kind":"identifier"}],"title":"UIFocusHeading","url":"/documentation/uikit/uifocusheading"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem":{"role":"symbol","abstract":[{"text":"The item that was focused before the update.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"previouslyFocusedItem"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previouslyFocusedItem","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UIFocusItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIFocusItem"},{"kind":"text","text":")?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/previouslyFocusedItem","title":"previouslyFocusedItem","url":"/documentation/uikit/uifocusupdatecontext/previouslyfocuseditem"},"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFocusUpdateContext","kind":"identifier"}],"role":"symbol","title":"UIFocusUpdateContext","url":"/documentation/uikit/uifocusupdatecontext","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext","navigatorTitle":[{"text":"UIFocusUpdateContext","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"An object that provides information relevant to a specific focus update from one view to another.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIView":{"title":"UIView","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","abstract":[{"text":"An object that manages the content for a rectangular area on the screen.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UIView","kind":"identifier"}],"url":"/documentation/uikit/uiview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"previouslyFocusedView","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"previouslyFocusedView","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Locating focus direction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/nextFocusedView","doc://com.apple.uikit/documentation/UIKit/UIFocusUpdateContext/focusHeading","doc://com.apple.uikit/documentation/UIKit/UIFocusHeading"],"anchor":"Locating-focus-direction"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIView","kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" * "},{"text":"previouslyFocusedView","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"/primaryContentSections/0"},{"value":"previouslyFocusedView","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedView/title"},{"value":[{"text":"previouslyFocusedView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedView/fragments"},{"value":"focusHeading","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1focusHeading/title"},{"value":[{"text":"focusHeading","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1focusHeading/fragments"},{"value":"nextFocusedView","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1nextFocusedView/title"},{"value":[{"text":"nextFocusedView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1nextFocusedView/fragments"},{"value":"UIFocusHeading","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHeading/title"},{"value":[{"kind":"identifier","text":"UIFocusHeading"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHeading/fragments"},{"value":[{"kind":"identifier","text":"UIFocusHeading"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusHeading/navigatorTitle"},{"value":"previouslyFocusedItem","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedItem/title"},{"value":[{"text":"previouslyFocusedItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext~1previouslyFocusedItem/fragments"},{"value":"UIFocusUpdateContext","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/title"},{"value":[{"kind":"identifier","text":"UIFocusUpdateContext"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/fragments"},{"value":[{"text":"UIFocusUpdateContext","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusUpdateContext/navigatorTitle"},{"value":"UIView","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title"},{"value":[{"text":"UIView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments"},{"value":[{"kind":"identifier","text":"UIView"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}