{
  "abstract": [
    {
      "text": "Saves an NDEF message to a writable tag.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeNDEF(_:completionHandler:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NFCNDEFTag(im)writeNDEF:completionHandler:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "writeNDEF"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NFCNDEFMessage",
        "text": "NFCNDEFMessage"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "completionHandler"
      },
      {
        "kind": "text",
        "text": ": ((any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5ErrorP",
        "text": "Error"
      },
      {
        "kind": "text",
        "text": ")?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "writeNDEF:completionHandler:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "required": true,
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "writeNDEF(_:completionHandler:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "writeNDEF"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ndefMessage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NFCNDEFMessage",
              "text": "NFCNDEFMessage"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ((any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5ErrorP",
              "text": "Error"
            },
            {
              "kind": "text",
              "text": ")?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        },
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "writeNDEF"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "ndefMessage"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NFCNDEFMessage",
              "text": "NFCNDEFMessage"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "async"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The NDEF message to write to the tag.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "ndefMessage"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The handler invoked by the reader session after completing the write request. The session calls ",
                  "type": "text"
                },
                {
                  "code": "completionHandler",
                  "type": "codeVoice"
                },
                {
                  "text": " on the dispatch queue provided when creating the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "The handler has the following parameter:",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "items": [
                {
                  "definition": {
                    "content": [
                      {
                        "inlineContent": [
                          {
                            "text": "An ",
                            "type": "text"
                          },
                          {
                            "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                            "isActive": true,
                            "type": "reference"
                          },
                          {
                            "text": " object if the write request fails. A value of ",
                            "type": "text"
                          },
                          {
                            "code": "nil",
                            "type": "codeVoice"
                          },
                          {
                            "text": " indicates that the write was successful.",
                            "type": "text"
                          }
                        ],
                        "type": "paragraph"
                      }
                    ]
                  },
                  "term": {
                    "inlineContent": [
                      {
                        "text": "error",
                        "type": "text"
                      }
                    ]
                  }
                }
              ],
              "type": "termList"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To determine whether the tag is writable, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/queryNDEFStatus(completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and check that the ",
              "type": "text"
            },
            {
              "code": "status",
              "type": "codeVoice"
            },
            {
              "text": " is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage": {
      "abstract": [
        {
          "text": "An NFC NDEF message consisting of an array of payload records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFMessage"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFMessage",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefmessage"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession": {
      "abstract": [
        {
          "text": "A reader session for detecting NFC Data Exchange Format (NDEF) tags.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFReaderSession"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFReaderSession",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefreadersession"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite": {
      "abstract": [
        {
          "text": "A status indicating that the tag supports reading and writing NDEF message data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readWrite"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFStatus/readWrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFStatusReadWrite"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFStatus.readWrite",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndefstatus/readwrite"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag": {
      "abstract": [
        {
          "text": "An interface for interacting with an NDEF tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCNDEFTag"
        }
      ],
      "role": "symbol",
      "title": "NFCNDEFTag",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/queryNDEFStatus(completionHandler:)": {
      "abstract": [
        {
          "text": "Asks the reader session for the NDEF support status of the tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryNDEFStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCNDEFStatus",
          "text": "NFCNDEFStatus"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/queryNDEFStatus(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryNDEFStatusWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "queryNDEFStatus(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag/queryndefstatus(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeLock(completionHandler:)": {
      "abstract": [
        {
          "text": "Changes the NDEF tag status to read-only, preventing future write operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeLock"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeLock(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeLockWithCompletionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "writeLock(completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag/writelock(completionhandler:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeNDEF(_:completionHandler:)": {
      "abstract": [
        {
          "text": "Saves an NDEF message to a writable tag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeNDEF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCNDEFMessage",
          "text": "NFCNDEFMessage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeNDEF(_:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeNDEF:completionHandler:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "writeNDEF(_:completionHandler:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcndeftag/writendef(_:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nserror": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSError": {
      "abstract": [
        {
          "text": "Information about an error condition including a domain, a domain-specific error code, and application-specific information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSError"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSError",
      "type": "topic",
      "url": "/documentation/foundation/nserror"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    },
    "doc://com.externally.resolved.symbol/s:s5ErrorP": {
      "abstract": [
        {
          "text": "A type representing an error value that can be thrown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8SendableP",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5ErrorP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Error",
      "type": "topic",
      "url": "/documentation/Swift/Error"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Writing-to-the-Tag",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeLock(completionHandler:)"
      ],
      "title": "Writing to the Tag"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "writeNDEF:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeNDEF:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Writing-to-the-Tag",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFTag/writeLock(completionHandler:)"
              ],
              "title": "Writing to the Tag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "writeNDEF:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFMessage",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NFCNDEFMessage",
                    "text": "NFCNDEFMessage"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "ndefMessage"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "completionHandler:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^)("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSError",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSError",
                    "text": "NSError"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": ""
                  },
                  {
                    "kind": "text",
                    "text": ")) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The NDEF message to write to the tag.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "ndefMessage"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The handler invoked by the reader session after completing the write request. The session calls ",
                        "type": "text"
                      },
                      {
                        "code": "completionHandler",
                        "type": "codeVoice"
                      },
                      {
                        "text": " on the dispatch queue provided when creating the ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCNDEFReaderSession",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "The handler has the following parameter:",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "items": [
                      {
                        "definition": {
                          "content": [
                            {
                              "inlineContent": [
                                {
                                  "text": "An ",
                                  "type": "text"
                                },
                                {
                                  "identifier": "doc://com.apple.documentation/documentation/foundation/nserror",
                                  "isActive": true,
                                  "type": "reference"
                                },
                                {
                                  "text": " object if the write request fails. A value of ",
                                  "type": "text"
                                },
                                {
                                  "code": "nil",
                                  "type": "codeVoice"
                                },
                                {
                                  "text": " indicates that the write was successful.",
                                  "type": "text"
                                }
                              ],
                              "type": "paragraph"
                            }
                          ]
                        },
                        "term": {
                          "inlineContent": [
                            {
                              "text": "error",
                              "type": "text"
                            }
                          ]
                        }
                      }
                    ],
                    "type": "termList"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1writeLock(completionHandler:)/title",
          "value": "writeLockWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1writeLock(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeLockWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readWrite/title",
          "value": "NFCNDEFStatusReadWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFStatus~1readWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFStatusReadWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/title",
          "value": "NFCNDEFMessage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFMessage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFMessage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/title",
          "value": "NFCNDEFReaderSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFReaderSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFReaderSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/title",
          "value": "NFCNDEFTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCNDEFTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1writeNDEF(_:completionHandler:)/title",
          "value": "writeNDEF:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1writeNDEF(_:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeNDEF:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1queryNDEFStatus(completionHandler:)/title",
          "value": "queryNDEFStatusWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCNDEFTag~1queryNDEFStatus(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "queryNDEFStatusWithCompletionHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcndeftag/writendef(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcndeftag/writendef(_:completionhandler:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
