{
  "abstract": [
    {
      "text": "The font you use for headings.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSFont",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSFontTextStyleHeadline",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "headline"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSFont",
        "text": "NSFont"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSFontTextStyle",
        "text": "TextStyle"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFontTextStyleHeadline"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "headline"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "headline"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSFont",
              "text": "NSFont"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSFontTextStyle",
              "text": "TextStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont": {
      "abstract": [
        {
          "text": "The representation of a font in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFont"
        }
      ],
      "role": "symbol",
      "title": "NSFont",
      "type": "topic",
      "url": "/documentation/appkit/nsfont"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle": {
      "abstract": [
        {
          "text": "Constants that specify the preferred text styles you use with fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "role": "symbol",
      "title": "NSFont.TextStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body": {
      "abstract": [
        {
          "text": "The font you use for body text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleBody"
        }
      ],
      "role": "symbol",
      "title": "body",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/body"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout": {
      "abstract": [
        {
          "text": "The font you use for callouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "callout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCallout"
        }
      ],
      "role": "symbol",
      "title": "callout",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/callout"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1": {
      "abstract": [
        {
          "text": "The font you use for standard captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCaption1"
        }
      ],
      "role": "symbol",
      "title": "caption1",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/caption1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2": {
      "abstract": [
        {
          "text": "The font you use for alternate captions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "caption2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleCaption2"
        }
      ],
      "role": "symbol",
      "title": "caption2",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/caption2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote": {
      "abstract": [
        {
          "text": "The font you use in footnotes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footnote"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleFootnote"
        }
      ],
      "role": "symbol",
      "title": "footnote",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/footnote"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline": {
      "abstract": [
        {
          "text": "The font you use for headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/headline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleHeadline"
        }
      ],
      "role": "symbol",
      "title": "headline",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/headline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle": {
      "abstract": [
        {
          "text": "The font you use for large titles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleLargeTitle"
        }
      ],
      "role": "symbol",
      "title": "largeTitle",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/largetitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline": {
      "abstract": [
        {
          "text": "The font you use for subheadings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subheadline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleSubheadline"
        }
      ],
      "role": "symbol",
      "title": "subheadline",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/subheadline"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1": {
      "abstract": [
        {
          "text": "The font you use for first-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle1"
        }
      ],
      "role": "symbol",
      "title": "title1",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2": {
      "abstract": [
        {
          "text": "The font you use for second-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle2"
        }
      ],
      "role": "symbol",
      "title": "title2",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3": {
      "abstract": [
        {
          "text": "The font you use for third-level hierarchical headings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFont",
          "text": "NSFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSFontTextStyle",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFontTextStyleTitle3"
        }
      ],
      "role": "symbol",
      "title": "title3",
      "type": "topic",
      "url": "/documentation/appkit/nsfont/textstyle/title3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
        "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFontTextStyleHeadline"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleHeadline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/body",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/callout",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption1",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/caption2",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/footnote",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/subheadline",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/largeTitle",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title1",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title2",
                "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle/title3"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSFont/TextStyle",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSFontTextStyle",
                    "text": "NSFontTextStyle"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFontTextStyleHeadline"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/title",
          "value": "NSFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1subheadline/title",
          "value": "NSFontTextStyleSubheadline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1subheadline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleSubheadline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1body/title",
          "value": "NSFontTextStyleBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1body/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/title",
          "value": "NSFontTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title2/title",
          "value": "NSFontTextStyleTitle2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1footnote/title",
          "value": "NSFontTextStyleFootnote"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1footnote/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleFootnote"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1callout/title",
          "value": "NSFontTextStyleCallout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1callout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCallout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption1/title",
          "value": "NSFontTextStyleCaption1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCaption1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1largeTitle/title",
          "value": "NSFontTextStyleLargeTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1largeTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleLargeTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title1/title",
          "value": "NSFontTextStyleTitle1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption2/title",
          "value": "NSFontTextStyleCaption2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1caption2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleCaption2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title3/title",
          "value": "NSFontTextStyleTitle3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1title3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleTitle3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1headline/title",
          "value": "NSFontTextStyleHeadline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSFont~1TextStyle~1headline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFontTextStyleHeadline"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsfont/textstyle/headline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsfont/textstyle/headline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
