{
  "abstract": [
    {
      "text": "The highest level of confidence in the heart rate data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coremotion/documentation/CoreMotion",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/highest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CMHighFrequencyHeartRateDataConfidence@CMHighFrequencyHeartRateDataConfidenceHighest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "highest"
      }
    ],
    "modules": [
      {
        "name": "Core Motion"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CMHighFrequencyHeartRateDataConfidenceHighest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "CMHighFrequencyHeartRateDataConfidence.highest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "highest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coremotion/documentation/CoreMotion": {
      "abstract": [
        {
          "text": "Process accelerometer, gyroscope, pedometer, and environment-related events.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Motion",
      "type": "topic",
      "url": "/documentation/coremotion"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence": {
      "abstract": [
        {
          "text": "The level of confidence in the accuracy of the heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidence"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidence"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateDataConfidence",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedataconfidence"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/high": {
      "abstract": [
        {
          "text": "A high level of confidence in the heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidenceHigh"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateDataConfidence.high",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/high"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/highest": {
      "abstract": [
        {
          "text": "The highest level of confidence in the heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highest"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/highest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidenceHighest"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateDataConfidence.highest",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/highest"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/low": {
      "abstract": [
        {
          "text": "A low level of confidence in the heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidenceLow"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateDataConfidence.low",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/low"
    },
    "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/medium": {
      "abstract": [
        {
          "text": "A medium level of confidence in the heart rate data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        }
      ],
      "identifier": "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CMHighFrequencyHeartRateDataConfidenceMedium"
        }
      ],
      "role": "symbol",
      "title": "CMHighFrequencyHeartRateDataConfidence.medium",
      "type": "topic",
      "url": "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/medium"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Levels-of-confidence",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/low",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/medium",
        "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/high"
      ],
      "title": "Levels of confidence"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CMHighFrequencyHeartRateDataConfidenceHighest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidenceHighest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coremotion/documentation/CoreMotion",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Levels-of-confidence",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/low",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/medium",
                "doc://com.apple.coremotion/documentation/CoreMotion/CMHighFrequencyHeartRateDataConfidence/high"
              ],
              "title": "Levels of confidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "CMHighFrequencyHeartRateDataConfidenceHighest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence/title",
          "value": "CMHighFrequencyHeartRateDataConfidence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1highest/title",
          "value": "CMHighFrequencyHeartRateDataConfidenceHighest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1highest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidenceHighest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1medium/title",
          "value": "CMHighFrequencyHeartRateDataConfidenceMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidenceMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1low/title",
          "value": "CMHighFrequencyHeartRateDataConfidenceLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidenceLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1high/title",
          "value": "CMHighFrequencyHeartRateDataConfidenceHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coremotion~1documentation~1CoreMotion~1CMHighFrequencyHeartRateDataConfidence~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CMHighFrequencyHeartRateDataConfidenceHigh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/highest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coremotion/cmhighfrequencyheartratedataconfidence/highest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
