{
  "abstract": [
    {
      "text": "A drop operation type specifying that no data should be transferred, thereby canceling the drag.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDropOperation@UIDropOperationCancel",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "cancel"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDropOperationCancel"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIDropOperation.cancel"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "cancel"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the user attempts a drop activity, the drag operation is canceled and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method isn’t called.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)": {
      "abstract": [
        {
          "text": "Tells the delegate it can request the item provider data from the session’s drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:performDrop:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:performDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation": {
      "abstract": [
        {
          "text": "Operation types that determine how a drag and drop activity resolves when the user drops a drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel": {
      "abstract": [
        {
          "text": "A drop operation type specifying that no data should be transferred, thereby canceling the drag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperationCancel"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation.cancel",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation/cancel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy": {
      "abstract": [
        {
          "text": "A drop operation type specifying that the data represented by the drag items should be copied to the destination view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperationCopy"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation.copy",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation/copy"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden": {
      "abstract": [
        {
          "text": "A drop operation type specifying that, although a move or copy operation is typically legitimate in this scenario, the drop activity isn’t allowed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forbidden"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperationForbidden"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation.forbidden",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation/forbidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move": {
      "abstract": [
        {
          "text": "A drop operation type specifying that the data represented by the drag items should be moved, not copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "move"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperationMove"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation.move",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation/move"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination": {
      "abstract": [
        {
          "text": "Adopt drop interaction APIs to selectively consume dragged content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
      "kind": "article",
      "role": "article",
      "title": "Making a view into a drop destination",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drop-destination"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drop-operation-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden",
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy",
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move"
      ],
      "title": "Drop operation types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDropOperationCancel"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drop-operation-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden",
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy",
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move"
              ],
              "title": "Drop operation types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIDropOperationCancel"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1forbidden/title",
          "value": "UIDropOperationForbidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1forbidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationForbidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/title",
          "value": "dropInteraction:performDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:performDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1copy/title",
          "value": "UIDropOperationCopy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1copy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationCopy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/title",
          "value": "UIDropOperationCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/title",
          "value": "UIDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/title",
          "value": "UIDropOperationMove"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationMove"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidropoperation/cancel"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidropoperation/cancel"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
