{"sections":[],"abstract":[{"type":"text","text":"A drop operation type specifying that the data represented by the drag items should be copied to the destination view."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uidropoperation/copy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uidropoperation/copy"]}],"seeAlsoSections":[{"anchor":"Drop-operation-types","title":"Drop operation types","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel","doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden","doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move"],"generated":true}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"}]}]},{"kind":"content","content":[{"anchor":"Discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This operation is used most often. When the user performs a drop activity, the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)"},{"type":"text","text":" delegate method is called. Your implementation of this delegate method should copy the data from the drag items to the destination view."}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropOperation"]]},"metadata":{"title":"UIDropOperation.copy","roleHeading":"Case","platforms":[{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"introducedAt":"11.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"introducedAt":"13.1","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"},{"introducedAt":"1.0","unavailable":false,"deprecated":false,"beta":false,"name":"visionOS"}],"role":"symbol","navigatorTitle":[{"text":"UIDropOperationCopy","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"UIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"}],"externalID":"c:@E@UIDropOperation@UIDropOperationCopy"},"references":{"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)":{"navigatorTitle":[{"kind":"identifier","text":"dropInteraction:performDrop:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dropInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDropInteraction","text":"UIDropInteraction"},{"kind":"text","text":", "},{"kind":"externalParam","text":"performDrop"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDropSession","text":"UIDropSession"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)","abstract":[{"type":"text","text":"Tells the delegate it can request the item provider data from the session’s drag items."}],"title":"dropInteraction(_:performDrop:)","url":"/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"}],"url":"/documentation/uikit/uidropoperation/cancel","role":"symbol","navigatorTitle":[{"text":"UIDropOperationCancel","kind":"identifier"}],"title":"UIDropOperation.cancel","abstract":[{"text":"A drop operation type specifying that no data should be transferred, thereby canceling the drag.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden":{"title":"UIDropOperation.forbidden","role":"symbol","abstract":[{"type":"text","text":"A drop operation type specifying that, although a move or copy operation is typically legitimate in this scenario, the drop activity isn’t allowed."}],"navigatorTitle":[{"kind":"identifier","text":"UIDropOperationForbidden"}],"url":"/documentation/uikit/uidropoperation/forbidden","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forbidden"}]},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy":{"url":"/documentation/uikit/uidropoperation/copy","role":"symbol","title":"UIDropOperation.copy","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/copy","navigatorTitle":[{"text":"UIDropOperationCopy","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"}],"abstract":[{"text":"A drop operation type specifying that the data represented by the drag items should be copied to the destination view.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation":{"abstract":[{"type":"text","text":"Operation types that determine how a drag and drop activity resolves when the user drops a drag item."}],"url":"/documentation/uikit/uidropoperation","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation","title":"UIDropOperation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIDropOperation"}],"navigatorTitle":[{"kind":"identifier","text":"UIDropOperation"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move":{"url":"/documentation/uikit/uidropoperation/move","role":"symbol","title":"UIDropOperation.move","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move","navigatorTitle":[{"text":"UIDropOperationMove","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"move","kind":"identifier"}],"abstract":[{"text":"A drop operation type specifying that the data represented by the drag items should be moved, not copied.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iOS"},{"unavailable":false,"introducedAt":"11.0","deprecated":false,"beta":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"1.0","deprecated":false,"beta":false,"name":"visionOS"}]},{"path":"/metadata/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"/metadata/title","op":"replace","value":"UIDropOperationCopy"},{"path":"/metadata/symbolKind","op":"replace","value":"case"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"identifier","text":"UIDropOperationCopy"}]},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIDropOperation"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Drop-operation-types","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel","doc://com.apple.uikit/documentation/UIKit/UIDropOperation/forbidden","doc://com.apple.uikit/documentation/UIKit/UIDropOperation/move"],"title":"Drop operation types"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"UIDropOperationCopy","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/title","value":"dropInteraction:performDrop:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dropInteraction:performDrop:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/title","value":"UIDropOperationCancel","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/fragments","value":[{"kind":"identifier","text":"UIDropOperationCancel"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1forbidden/title","value":"UIDropOperationForbidden","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1forbidden/fragments","value":[{"kind":"identifier","text":"UIDropOperationForbidden"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1copy/title","value":"UIDropOperationCopy","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1copy/fragments","value":[{"text":"UIDropOperationCopy","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/title","value":"UIDropOperation","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/fragments","value":[{"kind":"identifier","text":"UIDropOperation"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/navigatorTitle","value":[{"text":"UIDropOperation","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/title","value":"UIDropOperationMove"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1move/fragments","value":[{"text":"UIDropOperationMove","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}