{
  "abstract": [
    {
      "text": "Creates a new quaternion from a 4 x 4 rotation matrix.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-5vcd5"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So10simd_quatda0A0EyABSo0A10_double4x4acfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_double4x4",
        "text": "simd_double4x4"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "rotationMatrix"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x4",
              "text": "simd_double4x4"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The rotation matrix.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "rotationMatrix"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function ignores the last row and the last column of ",
              "type": "text"
            },
            {
              "code": "rotationMatrix",
              "type": "codeVoice"
            },
            {
              "text": ", and is the equivalent of passing the upper-left 3 x 3 submatrix to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-791zk",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x4": {
      "abstract": [
        {
          "text": "A matrix of four columns and four rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x4"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x4",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd": {
      "abstract": [
        {
          "text": "A double-precision quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_quatd"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_quatd"
        }
      ],
      "role": "symbol",
      "title": "simd_quatd",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init()": {
      "abstract": [
        {
          "text": "Creates a new quaternion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init()"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-5vcd5": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a 4 x 4 rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x4",
          "text": "simd_double4x4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-5vcd5",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(_:)-5vcd5"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-791zk": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a 3 x 3 rotation matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double3x3",
          "text": "simd_double3x3"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-791zk",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(_:)-791zk"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(angle:axis:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion with an action that’s a rotation about an axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "angle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "axis"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(angle:axis:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(angle:axis:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(angle:axis:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(from:to:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion with an action that’s a rotation between two vectors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(from:to:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(from:to:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(from:to:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(ix:iy:iz:r:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from four scalar values that specify the imaginary and real parts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "iy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "iz"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "r"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(ix:iy:iz:r:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(ix:iy:iz:r:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(ix:iy:iz:r:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(real:imag:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a scalar real part and a vector imaginary part.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "real"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "imag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5SIMD3V",
          "text": "SIMD3"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(real:imag:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(real:imag:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(real:imag:)"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(vector:)": {
      "abstract": [
        {
          "text": "Creates a new quaternion from a four-element vector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "vector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@simd_double4",
          "text": "simd_double4"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(vector:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(vector:)",
      "type": "topic",
      "url": "/documentation/simd/simd_quatd/init(vector:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-a-quaternion",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init()",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(vector:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(_:)-791zk",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(angle:axis:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(from:to:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(ix:iy:iz:r:)",
        "doc://com.apple.accelerate/documentation/simd/simd_quatd/init(real:imag:)"
      ],
      "title": "Initializing a quaternion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/title",
          "value": "simd_quatd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_quatd/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_quatd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/title",
          "value": "simd_double4x4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_quatd/init(_:)-5vcd5"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
