{
  "abstract": [
    {
      "text": "A factor that reduces the body’s linear velocity.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/damping"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNPhysicsBody(py)damping",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "damping"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "damping"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "damping"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "damping"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This property simulates the effect of fluid friction or air resistance on a body. A damping factor of ",
              "type": "text"
            },
            {
              "code": "0.0",
              "type": "codeVoice"
            },
            {
              "text": " specifies no loss in velocity, and a damping factor of ",
              "type": "text"
            },
            {
              "code": "1.0",
              "type": "codeVoice"
            },
            {
              "text": " prevents the body from moving. The default damping factor is ",
              "type": "text"
            },
            {
              "code": "0.1",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody": {
      "abstract": [
        {
          "text": "The physics simulation attributes attached to a scene graph node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBody",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/angularDamping": {
      "abstract": [
        {
          "text": "A factor that reduces the body’s angular velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "angularDamping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/angularDamping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "angularDamping"
        }
      ],
      "role": "symbol",
      "title": "angularDamping",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/angulardamping"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/centerOfMassOffset": {
      "abstract": [
        {
          "text": "The position of the body’s center of mass relative to its local coordinate origin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerOfMassOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/centerOfMassOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerOfMassOffset"
        }
      ],
      "role": "symbol",
      "title": "centerOfMassOffset",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/centerofmassoffset"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/charge": {
      "abstract": [
        {
          "text": "The electric charge of the body, in coulombs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/charge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "charge"
        }
      ],
      "role": "symbol",
      "title": "charge",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/charge"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/damping": {
      "abstract": [
        {
          "text": "A factor that reduces the body’s linear velocity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "damping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/damping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "damping"
        }
      ],
      "role": "symbol",
      "title": "damping",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/damping"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/friction": {
      "abstract": [
        {
          "text": "The body’s resistance to sliding motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "friction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/friction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "friction"
        }
      ],
      "role": "symbol",
      "title": "friction",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/friction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/mass": {
      "abstract": [
        {
          "text": "The mass of the body, in kilograms.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/mass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mass"
        }
      ],
      "role": "symbol",
      "title": "mass",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/mass"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/momentOfInertia": {
      "abstract": [
        {
          "text": "The body’s moment of inertia, expressed in the local coordinate system of the node that contains the body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "momentOfInertia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@SCNVector3",
          "text": "SCNVector3"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/momentOfInertia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "momentOfInertia"
        }
      ],
      "role": "symbol",
      "title": "momentOfInertia",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/momentofinertia"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/restitution": {
      "abstract": [
        {
          "text": "A factor that determines how much kinetic energy the body loses or gains in collisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restitution"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/restitution",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restitution"
        }
      ],
      "role": "symbol",
      "title": "restitution",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/restitution"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/rollingFriction": {
      "abstract": [
        {
          "text": "The body’s resistance to rolling motion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollingFriction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/rollingFriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rollingFriction"
        }
      ],
      "role": "symbol",
      "title": "rollingFriction",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/rollingfriction"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/usesDefaultMomentOfInertia": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether SceneKit automatically calculates the body’s moment of inertia or allows setting a custom value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "usesDefaultMomentOfInertia"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/usesDefaultMomentOfInertia",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "usesDefaultMomentOfInertia"
        }
      ],
      "role": "symbol",
      "title": "usesDefaultMomentOfInertia",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/usesdefaultmomentofinertia"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-a-Bodys-Physical-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/mass",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/charge",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/friction",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/rollingFriction",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/restitution",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/angularDamping",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/momentOfInertia",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/usesDefaultMomentOfInertia",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/centerOfMassOffset"
      ],
      "title": "Defining a Body’s Physical Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "damping"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "damping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-a-Bodys-Physical-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/mass",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/charge",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/friction",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/rollingFriction",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/restitution",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/angularDamping",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/momentOfInertia",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/usesDefaultMomentOfInertia",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/centerOfMassOffset"
              ],
              "title": "Defining a Body’s Physical Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "damping"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1rollingFriction/title",
          "value": "rollingFriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1rollingFriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rollingFriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1restitution/title",
          "value": "restitution"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1restitution/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restitution"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1usesDefaultMomentOfInertia/title",
          "value": "usesDefaultMomentOfInertia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1usesDefaultMomentOfInertia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "usesDefaultMomentOfInertia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1angularDamping/title",
          "value": "angularDamping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1angularDamping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "angularDamping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1momentOfInertia/title",
          "value": "momentOfInertia"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1momentOfInertia/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "momentOfInertia"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1centerOfMassOffset/title",
          "value": "centerOfMassOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1centerOfMassOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerOfMassOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1friction/title",
          "value": "friction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1friction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "friction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1damping/title",
          "value": "damping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1damping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "damping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1mass/title",
          "value": "mass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1mass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title",
          "value": "SCNPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1charge/title",
          "value": "charge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1charge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "charge"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnphysicsbody/damping"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnphysicsbody/damping"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
