{
  "abstract": [
    {
      "text": "Creates a physics body with the specified type and shape.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.scenekit/documentation/SceneKit",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/init(type:shape:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)SCNPhysicsBody(cm)bodyWithType:shape:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "convenience"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "type"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@SCNPhysicsBodyType",
        "text": "SCNPhysicsBodyType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "shape"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)SCNPhysicsShape",
        "text": "SCNPhysicsShape"
      },
      {
        "kind": "text",
        "text": "?)"
      }
    ],
    "modules": [
      {
        "name": "SceneKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "bodyWithType:shape:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(type:shape:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "convenience"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "type"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@SCNPhysicsBodyType",
              "text": "SCNPhysicsBodyType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "shape"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)SCNPhysicsShape",
              "text": "SCNPhysicsShape"
            },
            {
              "kind": "text",
              "text": "?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A constant that determines how a body responds to forces and collisions. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "type"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A physics shape defining the volume of the body for collision detection purposes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "shape"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A new physics body object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For the body to participate in collision detection or respond to forces, you must attach it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in a scene.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you pass ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": " for the shape parameter, SceneKit automatically creates a physics shape for the body when you attach it to a node, based on that node’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. To create a physics shape that’s based on the geometries of a node and its hierarchy of children, or to control the level of detail in a physics shape, create the physics shape manually using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For nodes containing custom geometry, the physics shape SceneKit automatically creates is a rough approximation of the geometry. This approximation, or ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "convex hull",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ", provides a compromise between accuracy and performance in collision detection. For the best collision detection performance, create an ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instance based on a basic geometry class (",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ").",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.scenekit/documentation/SceneKit": {
      "abstract": [
        {
          "text": "Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit",
      "kind": "symbol",
      "role": "collection",
      "title": "SceneKit",
      "type": "topic",
      "url": "/documentation/scenekit"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNBox": {
      "abstract": [
        {
          "text": "A six-sided polyhedron geometry whose faces are all rectangles, optionally with rounded edges and corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNBox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNBox"
        }
      ],
      "role": "symbol",
      "title": "SCNBox",
      "type": "topic",
      "url": "/documentation/scenekit/scnbox"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry whose ends are capped with hemispheres.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCapsule",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCapsule"
        }
      ],
      "role": "symbol",
      "title": "SCNCapsule",
      "type": "topic",
      "url": "/documentation/scenekit/scncapsule"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCone": {
      "abstract": [
        {
          "text": "A right circular cone or frustum geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCone"
        }
      ],
      "role": "symbol",
      "title": "SCNCone",
      "type": "topic",
      "url": "/documentation/scenekit/scncone"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder": {
      "abstract": [
        {
          "text": "A right circular cylinder geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNCylinder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNCylinder"
        }
      ],
      "role": "symbol",
      "title": "SCNCylinder",
      "type": "topic",
      "url": "/documentation/scenekit/scncylinder"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode": {
      "abstract": [
        {
          "text": "A structural element of a scene graph, representing a position and transform in a 3D coordinate space, to which you can attach geometry, lights, cameras, or other displayable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNNode"
        }
      ],
      "role": "symbol",
      "title": "SCNNode",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry": {
      "abstract": [
        {
          "text": "The geometry attached to the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "geometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNGeometry",
          "text": "SCNGeometry"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/geometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "geometry"
        }
      ],
      "role": "symbol",
      "title": "geometry",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/geometry"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody": {
      "abstract": [
        {
          "text": "The physics body associated with the node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicsBody"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsBody",
          "text": "SCNPhysicsBody"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNNode/physicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicsBody"
        }
      ],
      "role": "symbol",
      "title": "physicsBody",
      "type": "topic",
      "url": "/documentation/scenekit/scnnode/physicsbody"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody": {
      "abstract": [
        {
          "text": "The physics simulation attributes attached to a scene graph node.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBody"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBody",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/dynamic()": {
      "abstract": [
        {
          "text": "Creates a physics body that can be affected by forces and collisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dynamic"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/dynamic()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dynamicBody"
        }
      ],
      "role": "symbol",
      "title": "dynamic()",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/dynamic()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/init(type:shape:)": {
      "abstract": [
        {
          "text": "Creates a physics body with the specified type and shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNPhysicsBodyType",
          "text": "SCNPhysicsBodyType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsShape",
          "text": "SCNPhysicsShape"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/init(type:shape:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bodyWithType:shape:"
        }
      ],
      "role": "symbol",
      "title": "init(type:shape:)",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/init(type:shape:)"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/kinematic()": {
      "abstract": [
        {
          "text": "Creates a physics body that is unaffected by forces or collisions but that can cause collisions affecting other bodies when moved.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kinematic"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/kinematic()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kinematicBody"
        }
      ],
      "role": "symbol",
      "title": "kinematic()",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/kinematic()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/physicsShape": {
      "abstract": [
        {
          "text": "An object that defines the solid volume of the physics body for use in collision detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "physicsShape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)SCNPhysicsShape",
          "text": "SCNPhysicsShape"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/physicsShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "physicsShape"
        }
      ],
      "role": "symbol",
      "title": "physicsShape",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/physicsshape"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/static()": {
      "abstract": [
        {
          "text": "Creates a physics body that is unaffected by forces or collisions and that cannot move.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`static`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/static()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "staticBody"
        }
      ],
      "role": "symbol",
      "title": "static()",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/static()"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/type": {
      "abstract": [
        {
          "text": "A constant that determines how the physics body responds to forces and collisions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "type"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@SCNPhysicsBodyType",
          "text": "SCNPhysicsBodyType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/type",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "type"
        }
      ],
      "role": "symbol",
      "title": "type",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbody/type"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType": {
      "abstract": [
        {
          "text": "Constants that determine how a physics body interacts with forces and other bodies, used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/type",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " property and when creating a physics body.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsBodyType"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsBodyType"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsBodyType",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsbodytype"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape": {
      "abstract": [
        {
          "text": "An abstraction of a physics body’s solid volume for tuning collision detection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPhysicsShape"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPhysicsShape"
        }
      ],
      "role": "symbol",
      "title": "SCNPhysicsShape",
      "type": "topic",
      "url": "/documentation/scenekit/scnphysicsshape"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid": {
      "abstract": [
        {
          "text": "A right rectangular pyramid geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPyramid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNPyramid"
        }
      ],
      "role": "symbol",
      "title": "SCNPyramid",
      "type": "topic",
      "url": "/documentation/scenekit/scnpyramid"
    },
    "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere": {
      "abstract": [
        {
          "text": "A sphere (or ball or globe) geometry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNSphere",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SCNSphere"
        }
      ],
      "role": "symbol",
      "title": "SCNSphere",
      "type": "topic",
      "url": "/documentation/scenekit/scnsphere"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/type",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/physicsShape"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Creating-Physics-Bodies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/static()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/dynamic()",
        "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/kinematic()"
      ],
      "title": "Creating Physics Bodies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "bodyWithType:shape:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "bodyWithType:shape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.scenekit/documentation/SceneKit",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/type",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/physicsShape"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Creating-Physics-Bodies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/static()",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/dynamic()",
                "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/kinematic()"
              ],
              "title": "Creating Physics Bodies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "+ ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "bodyWithType:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@SCNPhysicsBodyType",
                    "text": "SCNPhysicsBodyType"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "type"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "shape:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsShape",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)SCNPhysicsShape",
                    "text": "SCNPhysicsShape"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "shape"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A constant that determines how a body responds to forces and collisions. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBodyType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "type"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A physics shape defining the volume of the body for collision detection purposes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "shape"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A new physics body object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBodyType/title",
          "value": "SCNPhysicsBodyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBodyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBodyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBodyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBodyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/title",
          "value": "SCNCone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCone/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/title",
          "value": "SCNCylinder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCylinder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCylinder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/title",
          "value": "SCNSphere"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNSphere/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNSphere"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsShape/title",
          "value": "SCNPhysicsShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsShape/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/title",
          "value": "SCNCapsule"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNCapsule/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNCapsule"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1static()/title",
          "value": "staticBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1static()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "staticBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/title",
          "value": "geometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1geometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/title",
          "value": "physicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode~1physicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/title",
          "value": "SCNNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/title",
          "value": "SCNBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNBox/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1init(type:shape:)/title",
          "value": "bodyWithType:shape:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1init(type:shape:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "bodyWithType:shape:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title",
          "value": "SCNPhysicsBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPhysicsBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/title",
          "value": "SCNPyramid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPyramid/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SCNPyramid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1physicsShape/title",
          "value": "physicsShape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1physicsShape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "physicsShape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1kinematic()/title",
          "value": "kinematicBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1kinematic()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "kinematicBody"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1type/title",
          "value": "type"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1type/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "type"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1dynamic()/title",
          "value": "dynamicBody"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1dynamic()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "dynamicBody"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/scenekit/scnphysicsbody/init(type:shape:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/scenekit/scnphysicsbody/init(type:shape:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
