{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setResting"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"resting"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value indicating whether to treat the body as at rest."}]}],"name":"resting"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"When a body is at rest, SceneKit assumes that the body will not move unless another body collides with it, you change the body’s position or velocity directly, or you apply a force to the body. Resting bodies don’t participate in the physics simulation, reducing the performance cost of physics calculations and ensuring that those bodies don’t move unexpectedly."}]},{"type":"paragraph","inlineContent":[{"text":"By default, SceneKit automatically determines whether to treat a body as resting (see ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/isResting","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/allowsResting","type":"reference"},{"text":"). Use this method only if you need to override this behavior. For example, you might set a body to resting if you change its position to reflect an external influence, and don’t want the physics simulation to make the body appear to settle into place after the move.","type":"text"}]}]}],"metadata":{"modules":[{"name":"SceneKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setResting","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)SCNPhysicsBody(im)setResting:","title":"setResting(_:)","platforms":[{"deprecated":false,"beta":false,"introducedAt":"12.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"12.0","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"10.14","name":"macOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"12.0","name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"5.0","name":"watchOS","unavailable":false}],"navigatorTitle":[{"text":"setResting:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/scenekit/scnphysicsbody/setresting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/scenekit/scnphysicsbody/setresting(_:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/setResting(_:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"]]},"abstract":[{"text":"Tells SceneKit whether to treat the body as currently being in motion.","type":"text"}],"seeAlsoSections":[{"generated":true,"anchor":"Defining-When-a-Body-Can-Move","title":"Defining When a Body Can Move","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/isResting","doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/allowsResting"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:Sb":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"url":"/documentation/Swift/Bool","role":"symbol","title":"Bool","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}]},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody","abstract":[{"type":"text","text":"The physics simulation attributes attached to a scene graph node."}],"url":"/documentation/scenekit/scnphysicsbody","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SCNPhysicsBody"}],"title":"SCNPhysicsBody","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SCNPhysicsBody"}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"type":"topic","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"url":"/documentation/objectivec/bool","role":"symbol","title":"BOOL"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","title":"Technologies"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/isResting":{"navigatorTitle":[{"kind":"identifier","text":"isResting"}],"role":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/isResting","abstract":[{"text":"A Boolean value that indicates whether the physics body is at rest.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isResting","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isResting","url":"/documentation/scenekit/scnphysicsbody/isresting"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/setResting(_:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setResting:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setResting","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells SceneKit whether to treat the body as currently being in motion."}],"url":"/documentation/scenekit/scnphysicsbody/setresting(_:)","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/setResting(_:)","title":"setResting(_:)"},"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/allowsResting":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowsResting"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"allowsResting","type":"topic","url":"/documentation/scenekit/scnphysicsbody/allowsresting","identifier":"doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/allowsResting","abstract":[{"text":"A Boolean value that specifies whether SceneKit can automatically mark the physics body at rest.","type":"text"}],"navigatorTitle":[{"text":"allowsResting","kind":"identifier"}],"role":"symbol"},"doc://com.apple.scenekit/documentation/SceneKit":{"type":"topic","kind":"symbol","identifier":"doc://com.apple.scenekit/documentation/SceneKit","abstract":[{"type":"text","text":"Create 3D games and add 3D content to apps using high-level scene descriptions, and easily add animations, physics simulation, particle effects, and realistic physically based rendering."}],"url":"/documentation/scenekit","role":"collection","title":"SceneKit"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"12.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"12.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.14"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"12.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"5.0"}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"setResting:","path":"/metadata/title"},{"op":"replace","value":"method","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setResting:","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.scenekit/documentation/SceneKit","doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody"]]},"path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"title":"Defining When a Body Can Move","anchor":"Defining-When-a-Body-Can-Move","identifiers":["doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/isResting","doc://com.apple.scenekit/documentation/SceneKit/SCNPhysicsBody/allowsResting"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setResting:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"resting"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"resting","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A Boolean value indicating whether to treat the body as at rest."}]}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/title","value":"SCNPhysicsBody","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/fragments","value":[{"text":"SCNPhysicsBody","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody/navigatorTitle","value":[{"text":"SCNPhysicsBody","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1isResting/title","value":"isResting","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1isResting/fragments","value":[{"text":"isResting","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1setResting(_:)/title","value":"setResting:","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1setResting(_:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setResting:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1allowsResting/title","value":"allowsResting","op":"replace"},{"path":"/references/doc:~1~1com.apple.scenekit~1documentation~1SceneKit~1SCNPhysicsBody~1allowsResting/fragments","value":[{"kind":"identifier","text":"allowsResting"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}