{
  "abstract": [
    {
      "text": "The user canceled changes made to the event.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.eventkitui/documentation/EventKitUI",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/canceled"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@EKEventEditViewAction@EKEventEditViewActionCanceled",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "canceled"
      }
    ],
    "modules": [
      {
        "name": "EventKit UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "EKEventEditViewActionCanceled"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "EKEventEditViewAction.canceled"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "canceled"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI": {
      "abstract": [
        {
          "text": "Display an interface for viewing, selecting, and editing calendar events and reminders.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI",
      "kind": "symbol",
      "role": "collection",
      "title": "EventKit UI",
      "type": "topic",
      "url": "/documentation/eventkitui"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction": {
      "abstract": [
        {
          "text": "The action taken by the user after editing an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EKEventEditViewAction"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewAction"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewAction",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/canceled": {
      "abstract": [
        {
          "text": "The user canceled changes made to the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canceled"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/canceled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewActionCanceled"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewAction.canceled",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction/canceled"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/cancelled": {
      "abstract": [
        {
          "text": "A static variable used to cancel changes made to the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@EKEventEditViewAction",
          "text": "EKEventEditViewAction"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewActionCancelled"
        }
      ],
      "role": "symbol",
      "title": "cancelled",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction/cancelled"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/deleted": {
      "abstract": [
        {
          "text": "The user deleted the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleted"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/deleted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewActionDeleted"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewAction.deleted",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction/deleted"
    },
    "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/saved": {
      "abstract": [
        {
          "text": "The user saved changes made to the event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "saved"
        }
      ],
      "identifier": "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/saved",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EKEventEditViewActionSaved"
        }
      ],
      "role": "symbol",
      "title": "EKEventEditViewAction.saved",
      "type": "topic",
      "url": "/documentation/eventkitui/ekeventeditviewaction/saved"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/saved",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/deleted",
        "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/cancelled"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "EKEventEditViewActionCanceled"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewActionCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.eventkitui/documentation/EventKitUI",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/saved",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/deleted",
                "doc://com.apple.eventkitui/documentation/EventKitUI/EKEventEditViewAction/cancelled"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "EKEventEditViewActionCanceled"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1saved/title",
          "value": "EKEventEditViewActionSaved"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1saved/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewActionSaved"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1deleted/title",
          "value": "EKEventEditViewActionDeleted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1deleted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewActionDeleted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1cancelled/title",
          "value": "EKEventEditViewActionCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewActionCancelled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1canceled/title",
          "value": "EKEventEditViewActionCanceled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction~1canceled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewActionCanceled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/title",
          "value": "EKEventEditViewAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.eventkitui~1documentation~1EventKitUI~1EKEventEditViewAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EKEventEditViewAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewaction/canceled"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/eventkitui/ekeventeditviewaction/canceled"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
