{
  "abstract": [
    {
      "text": "Runs a one-shot query that returns an asynchronous sequence of matching series samples.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/results(for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "HealthKit",
    "externalID": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV7results3forAC7ResultsVSo13HKHealthStoreC_tF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "results"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)HKHealthStore",
        "text": "HKHealthStore"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV",
        "text": "HKQuantitySeriesSampleQueryDescriptor"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV7ResultsV",
        "text": "Results"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.5",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "results(for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "results"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "healthStore"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)HKHealthStore",
              "text": "HKHealthStore"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV",
              "text": "HKQuantitySeriesSampleQueryDescriptor"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Results",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV7ResultsV",
              "text": "Results"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The access point for HealthKit data.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "healthStore"
        }
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore": {
      "abstract": [
        {
          "text": "The access point for all data managed by HealthKit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKHealthStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKHealthStore"
        }
      ],
      "role": "symbol",
      "title": "HKHealthStore",
      "type": "topic",
      "url": "/documentation/healthkit/hkhealthstore"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor": {
      "abstract": [
        {
          "text": "A query interface that reads the series data associated with quantity samples using Swift concurrency.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQueryDescriptor"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKQuantitySeriesSampleQueryDescriptor"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQueryDescriptor",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequerydescriptor"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Result": {
      "abstract": [
        {
          "text": "A set of results from a quantity series sample descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Result",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Result"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQueryDescriptor.Result",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequerydescriptor/result"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Results": {
      "abstract": [
        {
          "text": "An asynchronous sequence that emits data from the quantity series query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Results"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Results",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Results"
        }
      ],
      "role": "symbol",
      "title": "HKQuantitySeriesSampleQueryDescriptor.Results",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequerydescriptor/results"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/results(for:)": {
      "abstract": [
        {
          "text": "Runs a one-shot query that returns an asynchronous sequence of matching series samples.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "results"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)HKHealthStore",
          "text": "HKHealthStore"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV",
          "text": "HKQuantitySeriesSampleQueryDescriptor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:9HealthKit37HKQuantitySeriesSampleQueryDescriptorV7ResultsV",
          "text": "Results"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/results(for:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "results(for:)",
      "type": "topic",
      "url": "/documentation/healthkit/hkquantityseriessamplequerydescriptor/results(for:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Running-Queries",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Results",
        "doc://com.apple.healthkit/documentation/HealthKit/HKQuantitySeriesSampleQueryDescriptor/Result"
      ],
      "title": "Running Queries"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/title",
          "value": "HKHealthStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKHealthStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKHealthStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkquantityseriessamplequerydescriptor/results(for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
