{
  "abstract": [
    {
      "text": "A constant that represents the left arrow button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIPress",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPressType@UIPressTypeLeftArrow",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "leftArrow"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPressTypeLeftArrow"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UIPress.PressType.leftArrow"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "leftArrow"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress": {
      "abstract": [
        {
          "text": "An object that represents the presence or movement of a button press on the screen for a particular event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPress"
        }
      ],
      "role": "symbol",
      "title": "UIPress",
      "type": "topic",
      "url": "/documentation/uikit/uipress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType": {
      "abstract": [
        {
          "text": "Constants that represent buttons that a person can press.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PressType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PressType"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow": {
      "abstract": [
        {
          "text": "A constant that represents the down arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "downArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeDownArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.downArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/downarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow": {
      "abstract": [
        {
          "text": "A constant that represents the left arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/leftArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeLeftArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.leftArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/leftarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown": {
      "abstract": [
        {
          "text": "A constant that represents the page down button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypePageDown"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.pageDown",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/pagedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp": {
      "abstract": [
        {
          "text": "A constant that represents the page up button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageUp"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypePageUp"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.pageUp",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/pageup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow": {
      "abstract": [
        {
          "text": "A constant that represents the right arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeRightArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.rightArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/rightarrow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow": {
      "abstract": [
        {
          "text": "A constant that represents the up arrow button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "upArrow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPressTypeUpArrow"
        }
      ],
      "role": "symbol",
      "title": "UIPress.PressType.upArrow",
      "type": "topic",
      "url": "/documentation/uikit/uipress/presstype/uparrow"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
        "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp"
      ],
      "title": "Navigation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPressTypeLeftArrow"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/upArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/downArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/rightArrow",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageDown",
                "doc://com.apple.uikit/documentation/UIKit/UIPress/PressType/pageUp"
              ],
              "title": "Navigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UIPressTypeLeftArrow"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageUp/title",
          "value": "UIPressTypePageUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypePageUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/title",
          "value": "UIPress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1downArrow/title",
          "value": "UIPressTypeDownArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1downArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeDownArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1upArrow/title",
          "value": "UIPressTypeUpArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1upArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeUpArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageDown/title",
          "value": "UIPressTypePageDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1pageDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypePageDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1leftArrow/title",
          "value": "UIPressTypeLeftArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1leftArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeLeftArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1rightArrow/title",
          "value": "UIPressTypeRightArrow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType~1rightArrow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressTypeRightArrow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/title",
          "value": "UIPressType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPress~1PressType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPressType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipress/presstype/leftarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipress/presstype/leftarrow"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
