{
  "abstract": [
    {
      "text": "A phase that runs after standard event handlers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIUpdateActionPhase(cpy)afterEventDispatch",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "afterEventDispatch"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
        "text": "UIUpdateActionPhase"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "afterEventDispatch"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "afterEventDispatch"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "afterEventDispatch"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
              "text": "UIUpdateActionPhase"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This phase runs after ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " handlers run for standard events. After that point, the app doesn’t receive new user input events. However, if you request low-latency event dispatch using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", more events might dispatch in the low-latency event dispatch phase.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use this phase to perform tasks after processing all user input events for the UI update, like starting a parallel rendering thread.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEvent": {
      "abstract": [
        {
          "text": "An object that describes a single user interaction with your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEvent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEvent"
        }
      ],
      "role": "symbol",
      "title": "UIEvent",
      "type": "topic",
      "url": "/documentation/uikit/uievent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer": {
      "abstract": [
        {
          "text": "The base class for concrete gesture recognizers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase": {
      "abstract": [
        {
          "text": "An object that defines specific phases of the UI update process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateActionPhase",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after Core Animation display link callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterCADisplayLinkDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterCADisplayLinkDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterCADisplayLinkDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftercadisplaylinkdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs after a Core Animation transaction commit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "afterCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftercatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after standard event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftereventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs after a Core Animation transaction commit for a low-latency event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterLowLatencyCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterLowLatencyCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "afterLowLatencyCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterlowlatencycatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after low-latency event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterlowlatencyeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete": {
      "abstract": [
        {
          "text": "A phase that runs at the end of a UI update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterUpdateComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterUpdateComplete"
        }
      ],
      "role": "symbol",
      "title": "afterUpdateComplete",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterupdatecomplete"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled": {
      "abstract": [
        {
          "text": "A phase that runs after the scheduling of a UI update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterUpdateScheduled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterUpdateScheduled"
        }
      ],
      "role": "symbol",
      "title": "afterUpdateScheduled",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterupdatescheduled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before Core Animation display link callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeCADisplayLinkDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeCADisplayLinkDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeCADisplayLinkDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforecadisplaylinkdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs before a Core Animation transaction commit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "beforeCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforecatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before standard event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforeeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs before a Core Animation transaction commit for a low-latency event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeLowLatencyCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeLowLatencyCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "beforeLowLatencyCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforelowlatencycatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before low-latency event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforelowlatencyeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the UI update link requests dispatch of low-latency eligible events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "wantsLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdatelink/wantslowlatencyeventdispatch"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Phases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete"
      ],
      "title": "Phases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "afterEventDispatch"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Phases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete"
              ],
              "title": "Phases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "class"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
                    "text": "UIUpdateActionPhase"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "afterEventDispatch"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyEventDispatch/title",
          "value": "afterLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCADisplayLinkDispatch/title",
          "value": "beforeCADisplayLinkDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCADisplayLinkDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeCADisplayLinkDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeEventDispatch/title",
          "value": "beforeEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyCATransactionCommit/title",
          "value": "afterLowLatencyCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterLowLatencyCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyCATransactionCommit/title",
          "value": "beforeLowLatencyCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeLowLatencyCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCATransactionCommit/title",
          "value": "afterCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyEventDispatch/title",
          "value": "beforeLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCADisplayLinkDispatch/title",
          "value": "afterCADisplayLinkDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCADisplayLinkDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterCADisplayLinkDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/title",
          "value": "UIGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/title",
          "value": "UIEvent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEvent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEvent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateComplete/title",
          "value": "afterUpdateComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterUpdateComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCATransactionCommit/title",
          "value": "beforeCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/title",
          "value": "UIUpdateActionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterEventDispatch/title",
          "value": "afterEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink~1wantsLowLatencyEventDispatch/title",
          "value": "wantsLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink~1wantsLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateScheduled/title",
          "value": "afterUpdateScheduled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateScheduled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterUpdateScheduled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiupdateactionphase/aftereventdispatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiupdateactionphase/aftereventdispatch"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
