{
  "abstract": [
    {
      "text": "Use batch processes to manage large data changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/batch-processing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Batch processing"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteRequest": {
      "abstract": [
        {
          "text": "A request that deletes objects in the SQLite persistent store without loading them into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchDeleteRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchDeleteRequest"
        }
      ],
      "role": "symbol",
      "title": "NSBatchDeleteRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchdeleterequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteResult": {
      "abstract": [
        {
          "text": "An object that describes the result of a batch delete request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchDeleteResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchDeleteResult"
        }
      ],
      "role": "symbol",
      "title": "NSBatchDeleteResult",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchdeleteresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest": {
      "abstract": [
        {
          "text": "A request to insert a batch of data in a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertRequest"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertResult": {
      "abstract": [
        {
          "text": "The result that Core Data returns when executing a batch-insertion request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchInsertResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchInsertResult"
        }
      ],
      "role": "symbol",
      "title": "NSBatchInsertResult",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchinsertresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest": {
      "abstract": [
        {
          "text": "A request to Core Data to do a batch update of data in a persistent store without loading any data into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchUpdateRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchUpdateRequest"
        }
      ],
      "role": "symbol",
      "title": "NSBatchUpdateRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult": {
      "abstract": [
        {
          "text": "The result returned when executing a batch update request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchUpdateResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchUpdateResult"
        }
      ],
      "role": "symbol",
      "title": "NSBatchUpdateResult",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdateresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/conflict-resolution": {
      "abstract": [
        {
          "text": "Detect and resolve conflicts that occur when data is changed on multiple threads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conflict resolution",
      "type": "topic",
      "url": "/documentation/coredata/conflict-resolution"
    },
    "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background": {
      "abstract": [
        {
          "text": "Use Core Data in both a single-threaded and multithreaded app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Using Core Data in the background",
      "type": "topic",
      "url": "/documentation/coredata/using-core-data-in-the-background"
    },
    "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed": {
      "abstract": [
        {
          "text": "Consume data in the background, and lower memory use by batching imports and preventing duplicate records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
      "kind": "article",
      "role": "sampleCode",
      "title": "Loading and Displaying a Large Data Feed",
      "type": "topic",
      "url": "/documentation/swiftui/loading_and_displaying_a_large_data_feed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Background-tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
        "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
        "doc://com.apple.coredata/documentation/CoreData/conflict-resolution"
      ],
      "title": "Background tasks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Inserts",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertResult"
      ],
      "title": "Data Inserts"
    },
    {
      "anchor": "Data-Updates",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult"
      ],
      "title": "Data Updates"
    },
    {
      "anchor": "Data-Deletion",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteResult"
      ],
      "title": "Data Deletion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Inserts",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchInsertResult"
              ],
              "title": "Data Inserts"
            },
            {
              "anchor": "Data-Updates",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult"
              ],
              "title": "Data Updates"
            },
            {
              "anchor": "Data-Deletion",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchDeleteResult"
              ],
              "title": "Data Deletion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Background-tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
                "doc://com.apple.coredata/documentation/CoreData/conflict-resolution"
              ],
              "title": "Background tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteResult/title",
          "value": "NSBatchDeleteResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchDeleteResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchDeleteResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertResult/title",
          "value": "NSBatchInsertResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/title",
          "value": "NSBatchInsertRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchInsertRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchInsertRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteRequest/title",
          "value": "NSBatchDeleteRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchDeleteRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchDeleteRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchDeleteRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/title",
          "value": "NSBatchUpdateRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/title",
          "value": "NSBatchUpdateResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateResult"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/batch-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/batch-processing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
