{
  "abstract": [
    {
      "text": "Detect and resolve conflicts that occur when data is changed on multiple threads.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/conflict-resolution"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Conflict resolution"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSConstraintConflict": {
      "abstract": [
        {
          "text": "An encapsulation of conflicts that occur during an attempt to save a managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConstraintConflict"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSConstraintConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSConstraintConflict"
        }
      ],
      "role": "symbol",
      "title": "NSConstraintConflict",
      "type": "topic",
      "url": "/documentation/coredata/nsconstraintconflict"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict": {
      "abstract": [
        {
          "text": "An encapsulation of conflicts that occur during an attempt to save changes in a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeConflict"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeConflict"
        }
      ],
      "role": "symbol",
      "title": "NSMergeConflict",
      "type": "topic",
      "url": "/documentation/coredata/nsmergeconflict"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy": {
      "abstract": [
        {
          "text": "A policy object that you use to resolve conflicts between the persistent store and in-memory versions of managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSQueryGenerationToken": {
      "abstract": [
        {
          "text": "A token that indicates which generation of the persistent store is being accessed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSQueryGenerationToken"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSQueryGenerationToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSQueryGenerationToken"
        }
      ],
      "role": "symbol",
      "title": "NSQueryGenerationToken",
      "type": "topic",
      "url": "/documentation/coredata/nsquerygenerationtoken"
    },
    "doc://com.apple.coredata/documentation/CoreData/batch-processing": {
      "abstract": [
        {
          "text": "Use batch processes to manage large data changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/batch-processing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Batch processing",
      "type": "topic",
      "url": "/documentation/coredata/batch-processing"
    },
    "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background": {
      "abstract": [
        {
          "text": "Use Core Data in both a single-threaded and multithreaded app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Using Core Data in the background",
      "type": "topic",
      "url": "/documentation/coredata/using-core-data-in-the-background"
    },
    "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed": {
      "abstract": [
        {
          "text": "Consume data in the background, and lower memory use by batching imports and preventing duplicate records.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
      "kind": "article",
      "role": "sampleCode",
      "title": "Loading and Displaying a Large Data Feed",
      "type": "topic",
      "url": "/documentation/swiftui/loading_and_displaying_a_large_data_feed"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Background-tasks",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
        "doc://com.apple.documentation/documentation/swiftui/loading_and_displaying_a_large_data_feed",
        "doc://com.apple.coredata/documentation/CoreData/batch-processing"
      ],
      "title": "Background tasks"
    }
  ],
  "topicSections": [
    {
      "anchor": "Conflict-Management",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSConstraintConflict",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSQueryGenerationToken"
      ],
      "title": "Conflict Management"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Conflict-Management",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSConstraintConflict",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSQueryGenerationToken"
              ],
              "title": "Conflict Management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Background-tasks",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
                "doc://com.apple.coredata/documentation/CoreData/batch-processing"
              ],
              "title": "Background tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/title",
          "value": "NSMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/title",
          "value": "NSMergeConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSQueryGenerationToken/title",
          "value": "NSQueryGenerationToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSQueryGenerationToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSQueryGenerationToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSQueryGenerationToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSQueryGenerationToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSConstraintConflict/title",
          "value": "NSConstraintConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSConstraintConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConstraintConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSConstraintConflict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSConstraintConflict"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/conflict-resolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/conflict-resolution"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
