{
  "abstract": [
    {
      "text": "Describe your app’s object structure.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/core-data-model"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Data model"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In most cases, you describe your app’s data model using Xcode’s data model editor. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " represents the ",
              "type": "text"
            },
            {
              "code": ".xcdatamodeld",
              "type": "codeVoice"
            },
            {
              "text": " file in your project’s source list. This is where you define entities that you use to generate ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclasses for Core Data to manage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The entities you create are ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instances. Entities’ properties are subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", namely ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for attributes, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRelationshipDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for relationships, and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for fetched properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The various attribute types are enumerated in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription": {
      "abstract": [
        {
          "text": "A description of a single attribute belonging to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAttributeDescription"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsattributedescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAttributeType": {
      "abstract": [
        {
          "text": "The types of attribute that Core Data supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAttributeType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAttributeType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAttributeType"
        }
      ],
      "role": "symbol",
      "title": "NSAttributeType",
      "type": "topic",
      "url": "/documentation/coredata/nsattributetype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCompositeAttributeDescription": {
      "abstract": [
        {
          "text": "A description of an attribute that derives its value by composing other attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompositeAttributeDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCompositeAttributeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCompositeAttributeDescription"
        }
      ],
      "role": "symbol",
      "title": "NSCompositeAttributeDescription",
      "type": "topic",
      "url": "/documentation/coredata/nscompositeattributedescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDerivedAttributeDescription": {
      "abstract": [
        {
          "text": "A description of an attribute that derives its value by performing a calculation on a related attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDerivedAttributeDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDerivedAttributeDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDerivedAttributeDescription"
        }
      ],
      "role": "symbol",
      "title": "NSDerivedAttributeDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsderivedattributedescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription": {
      "abstract": [
        {
          "text": "A description of a Core Data entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityDescription"
        }
      ],
      "role": "symbol",
      "title": "NSEntityDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsentitydescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription": {
      "abstract": [
        {
          "text": "A description object used to define which properties are fetched from Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchedPropertyDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchedPropertyDescription"
        }
      ],
      "role": "symbol",
      "title": "NSFetchedPropertyDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchedpropertydescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObject": {
      "abstract": [
        {
          "text": "The base class that all Core Data model objects inherit from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObject",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobject"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel": {
      "abstract": [
        {
          "text": "A programmatic representation of the ",
          "type": "text"
        },
        {
          "code": ".xcdatamodeld",
          "type": "codeVoice"
        },
        {
          "text": " file describing your objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectModel"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectModel",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription": {
      "abstract": [
        {
          "text": "A description of a single property belonging to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPropertyDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPropertyDescription"
        }
      ],
      "role": "symbol",
      "title": "NSPropertyDescription",
      "type": "topic",
      "url": "/documentation/coredata/nspropertydescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRelationshipDescription": {
      "abstract": [
        {
          "text": "A description of a relationship between two entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRelationshipDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRelationshipDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRelationshipDescription"
        }
      ],
      "role": "symbol",
      "title": "NSRelationshipDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsrelationshipdescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/modeling-data": {
      "abstract": [
        {
          "text": "Configure the data model file to contain your app’s object graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/modeling-data",
      "kind": "article",
      "role": "article",
      "title": "Modeling data",
      "type": "topic",
      "url": "/documentation/coredata/modeling-data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-modeling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/modeling-data"
      ],
      "title": "Data modeling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Objects-and-entities",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription"
      ],
      "title": "Objects and entities"
    },
    {
      "anchor": "Standard-attributes",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
        "doc://com.apple.coredata/documentation/CoreData/NSAttributeType",
        "doc://com.apple.coredata/documentation/CoreData/NSRelationshipDescription"
      ],
      "title": "Standard attributes"
    },
    {
      "anchor": "Computed-attributes",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCompositeAttributeDescription",
        "doc://com.apple.coredata/documentation/CoreData/NSDerivedAttributeDescription"
      ],
      "title": "Computed attributes"
    },
    {
      "anchor": "Fetched-properties",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription"
      ],
      "title": "Fetched properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Objects-and-entities",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityDescription"
              ],
              "title": "Objects and entities"
            },
            {
              "anchor": "Standard-attributes",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeDescription",
                "doc://com.apple.coredata/documentation/CoreData/NSAttributeType",
                "doc://com.apple.coredata/documentation/CoreData/NSRelationshipDescription"
              ],
              "title": "Standard attributes"
            },
            {
              "anchor": "Computed-attributes",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCompositeAttributeDescription",
                "doc://com.apple.coredata/documentation/CoreData/NSDerivedAttributeDescription"
              ],
              "title": "Computed attributes"
            },
            {
              "anchor": "Fetched-properties",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription"
              ],
              "title": "Fetched properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-modeling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/modeling-data"
              ],
              "title": "Data modeling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/title",
          "value": "NSManagedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCompositeAttributeDescription/title",
          "value": "NSCompositeAttributeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCompositeAttributeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositeAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCompositeAttributeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCompositeAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/title",
          "value": "NSFetchedPropertyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDerivedAttributeDescription/title",
          "value": "NSDerivedAttributeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDerivedAttributeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDerivedAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDerivedAttributeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDerivedAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/title",
          "value": "NSPropertyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRelationshipDescription/title",
          "value": "NSRelationshipDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRelationshipDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRelationshipDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRelationshipDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRelationshipDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/title",
          "value": "NSAttributeDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/title",
          "value": "NSAttributeType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAttributeType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAttributeType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/title",
          "value": "NSEntityDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/title",
          "value": "NSManagedObjectModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectModel"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/core-data-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/core-data-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
