{
  "abstract": [
    {
      "text": "Define your app’s object structure with a data model file.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating a Core Data model"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The first step in working with Core Data is to create a data model file to define the structure of your app’s objects, including their object types, properties, and relationships.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can add a Core Data model file to your Xcode project when you create the project, or you can add it to an existing project.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-Core-Data-to-a-New-Xcode-Project",
          "level": 3,
          "text": "Add Core Data to a New Xcode Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the dialog for creating a new project, select the Use Core Data checkbox, and click Next.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3039511",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The resulting project includes an ",
              "type": "text"
            },
            {
              "code": ".xcdatamodeld",
              "type": "codeVoice"
            },
            {
              "text": " file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3080773",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-a-Core-Data-Model-to-an-Existing-Project",
          "level": 3,
          "text": "Add a Core Data Model to an Existing Project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Choose File > New > File and select the iOS platform tab. Scroll down to the Core Data section, select Data Model, and click Next.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3039513",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Name your model file, select its group and targets, and click Create.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3122943",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode adds an ",
              "type": "text"
            },
            {
              "code": ".xcdatamodeld",
              "type": "codeVoice"
            },
            {
              "text": " file with the specified name to your project.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3080772",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/configuring-attributes": {
      "abstract": [
        {
          "text": "Describe the properties that compose an entity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
      "kind": "article",
      "role": "article",
      "title": "Configuring Attributes",
      "type": "topic",
      "url": "/documentation/coredata/configuring-attributes"
    },
    "doc://com.apple.coredata/documentation/CoreData/configuring-relationships": {
      "abstract": [
        {
          "text": "Specify how entities relate and how change propagates between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
      "kind": "article",
      "role": "article",
      "title": "Configuring Relationships",
      "type": "topic",
      "url": "/documentation/coredata/configuring-relationships"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/generating-code": {
      "abstract": [
        {
          "text": "Automatically or manually generate managed object subclasses from entities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/generating-code",
      "kind": "article",
      "role": "article",
      "title": "Generating code",
      "type": "topic",
      "url": "/documentation/coredata/generating-code"
    },
    "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data": {
      "abstract": [
        {
          "text": "Create, store, and present records for a variety of data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Handling Different Data Types in Core Data",
      "type": "topic",
      "url": "/documentation/coredata/handling-different-data-types-in-core-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores": {
      "abstract": [
        {
          "text": "Organize data in two different stores and implement a link between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores",
      "kind": "article",
      "role": "sampleCode",
      "title": "Linking Data Between Two Core Data Stores",
      "type": "topic",
      "url": "/documentation/coredata/linking-data-between-two-core-data-stores"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack": {
      "abstract": [
        {
          "text": "Set up the classes that manage and persist your app’s objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
      "kind": "article",
      "role": "article",
      "title": "Setting up a Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-a-core-data-stack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3039511": {
      "alt": "Screenshot showing the Use Core Data checkbox in the options for creating a new Xcode project. The checkbox appears after the language dropdown, and before the checkboxes for including Unit Tests and UI Tests.",
      "identifier": "media-3039511",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/19ae17fc660e455d5244f4d43eedb41a/media-3039511@2x.png"
        }
      ]
    },
    "media-3039513": {
      "alt": "Screenshot showing the Data Model template in the Core Data section of the file template chooser.",
      "identifier": "media-3039513",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9e07aa8d17ce31890e3262cb2434d297/media-3039513@2x.png"
        }
      ]
    },
    "media-3080772": {
      "alt": "Screenshot of Xcode showing the new model file selected in the project navigator.",
      "identifier": "media-3080772",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a7a34ec891b4f73305a50e61a313cd9f/media-3080772@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4145bfec7e280343248e494142522ab6/media-3080772~dark@2x.png"
        }
      ]
    },
    "media-3080773": {
      "alt": "Screenshot showing the .xcdatamodeld file highlighted in the project navigator.",
      "identifier": "media-3080773",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bbbb08e2398531cf02bc029b3aa047e3/media-3080773@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4090109362085d269530783f5b93fedf/media-3080773~dark@2x.png"
        }
      ]
    },
    "media-3122943": {
      "alt": "Screenshot showing the dialog for saving a data model file. The filename is selected and immediately editable.",
      "identifier": "media-3122943",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/d04d51680b0977d684f13964ef908766/media-3122943@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a40f24dc2819dce5e87328732af1f2f9/media-3122943~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
        "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
        "doc://com.apple.coredata/documentation/CoreData/generating-code"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
        "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
                "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
                "doc://com.apple.coredata/documentation/CoreData/generating-code"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
                "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/creating-a-core-data-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/creating-a-core-data-model"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
