{
  "abstract": [
    {
      "text": "Design a CloudKit-compatible data model and initialize your CloudKit schema.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model-for-cloudkit"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating a Core Data Model for CloudKit"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To pass records between a Core Data store and a CloudKit database, they both require a shared understanding of the data structure. You define this in the Core Data model and then use that to generate a CloudKit schema.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3230504",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-Data-Model",
          "level": 3,
          "text": "Create a Data Model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use Xcode’s Core Data model editor to define your app’s entities and their attributes, or construct your model in code. For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the articles under ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/modeling-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "CloudKit doesn’t support all the features of a Core Data model. As you design your model, be aware of the following limitations and make sure you create a compatible data model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Core Data model element",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "CloudKit schema limitation",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Entities",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Unique constraints aren’t supported.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Attributes",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "code": "Undefined",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject/objectID",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " attribute types aren’t supported.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Relationships",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "All relationships must be optional. Due to operation size limitations, CloudKit may not save relationship changes atomically. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " All relationships must have an inverse, in case the records synchronize out of order. ",
                      "type": "text"
                    },
                    {
                      "identifier": "spacer",
                      "type": "image"
                    },
                    {
                      "text": " CloudKit doesn’t support the Deny deletion rule.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "inlineContent": [
                        {
                          "text": "Configurations",
                          "type": "text"
                        }
                      ],
                      "type": "strong"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "Entities in a configuration must not have relationships to entities in another configuration.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about how Core Data translates managed objects to CloudKit records, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/reading-cloudkit-records-for-core-data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Initialize-Your-CloudKit-Schema-During-Development",
          "level": 3,
          "text": "Initialize Your CloudKit Schema During Development",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "After creating your Core Data model, inform CloudKit about the types of records it contains by initializing a development schema. This is a draft schema that you can rewrite as often as necessary during development. You can’t delete a record type or modify any existing attributes after you promote a development schema to production.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the persistent container to initialize the development schema, which you can do during app launch or from within one or more integration tests. To exclude schema initialization from your production builds, use the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let container = NSPersistentCloudKitContainer(name: \"Earthquakes\")",
            "",
            "// Only initialize the schema when building the app with the ",
            "// Debug build configuration.        ",
            "#if DEBUG",
            "do {",
            "    // Use the container to initialize the development schema.",
            "    try container.initializeCloudKitSchema(options: [])",
            "} catch {",
            "    // Handle any errors.",
            "}",
            "#endif"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "After initializing the schema, the console contains an entry similar to the following:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<NSCloudKitMirroringDelegate: 0x7f9699d29a90>: Successfully set up CloudKit ",
            "    integration for store"
          ],
          "syntax": null,
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "While initializing the schema, Core Data creates a temporary instance of each distinct record type in each of the container’s stores that mirror to a CloudKit database and uploads them to the iCloud servers. After completing the upload, the schema is visible in the CloudKit dashboard and Core Data removes the temporary records.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about configuring a CloudKit persistent container, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Reset-the-Environment",
          "level": 3,
          "text": "Reset the Environment",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As you change the model during development, periodically visit the CloudKit dashboard to reset the development environment and delete the existing development schema, before initializing a new one. For more information about resetting the development environment, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EditingSchemesUsingCloudKitDashboard/EditingSchemesUsingCloudKitDashboard.html#//apple_ref/doc/uid/TP40014987-CH5",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Promote-the-Schema-to-Production",
          "level": 3,
          "text": "Promote the Schema to Production",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re happy with your data model, have a fully tested app, and are ready to submit it to the App Store, it’s time to promote your schema from development to production.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "After you promote your schema to production, the record types and their fields are immutable and exist for all time. You can add new record types, and additional fields to existing record types, but you can’t modify or delete existing record types.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Initialize your schema one last time, then promote it from the CloudKit dashboard. For more information about promoting a schema from development to production, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/DeployingYourCloudKitApp/DeployingYourCloudKitApp.html#//apple_ref/doc/uid/TP40014987-CH10",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Update-the-Production-Schema",
          "level": 3,
          "text": "Update the Production Schema",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Plan carefully for how your app handles forward compatibility and major changes to the data model, because you can’t rename or delete CloudKit record types and fields in production. Consider these strategies:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Migrate users to a completely new store, using ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to associate the new store with a new container.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Incrementally add new fields to existing record types. If you adopt this approach, older versions of your app have access to every record a user creates, but not every field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Version your entities by including a ",
                      "type": "text"
                    },
                    {
                      "code": "version",
                      "type": "codeVoice"
                    },
                    {
                      "text": " attribute from the outset, and use a fetch request to select only those records that are compatible with the current version of the app. If you adopt this approach, older versions of your app won’t fetch records that a user creates with a more recent version, effectively hiding them on that device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For example, consider a ",
              "type": "text"
            },
            {
              "code": "Post",
              "type": "codeVoice"
            },
            {
              "text": " entity with a ",
              "type": "text"
            },
            {
              "code": "version",
              "type": "codeVoice"
            },
            {
              "text": " attribute that stores the version of the app that creates the record. You can use a predicate to fetch only the records that are compatible with the current version of the app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// The current version of the app's data model.",
            "let maxCompatibleVersion = 3",
            "",
            "let context = NSManagedObjectContext(",
            "    concurrencyType: .privateQueueConcurrencyType",
            ")",
            "",
            "context.performAndWait {",
            "    let fetchRequest = NSFetchRequest<NSManagedObject>(entityName: \"Post\")",
            "    ",
            "    // Create a predicate that matches against the version attribute.",
            "    fetchRequest.predicate = NSPredicate(",
            "        format: \"version <= %d\",",
            "        argumentArray: [maxCompatibleVersion]",
            "    )",
            "    ",
            "    // Fetch all posts with a version less than or equal to maxCompatibleVersion.",
            "    let results = context.fetch(fetchRequest)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Along with these choices, consider your timelines for supporting multiple versions of your app, and for migrating users to newer app versions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For tips on migrating records to a new schema, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/DesigningforCloudKit/DesigningforCloudKit.html#//apple_ref/doc/uid/TP40012094-CH9",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For more information about Core Data model migration, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". For heavyweight migrations, see the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreDataVersioning/Articles/Introduction.html#//apple_ref/doc/uid/TP40004399-CH1",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " guide.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObject/objectID": {
      "abstract": [
        {
          "text": "The object ID of the managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject/objectID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectID"
        }
      ],
      "role": "symbol",
      "title": "objectID",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobject/objectid"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions": {
      "abstract": [
        {
          "text": "An object that customizes how a store description aligns with a CloudKit database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerOptions"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainerOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainerOptions"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainerOptions",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontaineroptions"
    },
    "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model": {
      "abstract": [
        {
          "text": "Define your app’s object structure with a data model file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/creating-a-core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically": {
      "abstract": [
        {
          "text": "Enable lightweight migrations to keep your data model and the underlying data in a consistent state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
      "kind": "article",
      "role": "article",
      "title": "Migrating your data model automatically",
      "type": "topic",
      "url": "/documentation/coredata/migrating-your-data-model-automatically"
    },
    "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit": {
      "abstract": [
        {
          "text": "Back user interfaces with a local replica of a CloudKit private database.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/mirroring-a-core-data-store-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Mirroring a Core Data store with CloudKit",
      "type": "topic",
      "url": "/documentation/coredata/mirroring-a-core-data-store-with-cloudkit"
    },
    "doc://com.apple.coredata/documentation/CoreData/modeling-data": {
      "abstract": [
        {
          "text": "Configure the data model file to contain your app’s object graph.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/modeling-data",
      "kind": "article",
      "role": "article",
      "title": "Modeling data",
      "type": "topic",
      "url": "/documentation/coredata/modeling-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/reading-cloudkit-records-for-core-data": {
      "abstract": [
        {
          "text": "Access CloudKit records created from Core Data managed objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/reading-cloudkit-records-for-core-data",
      "kind": "article",
      "role": "article",
      "title": "Reading CloudKit Records for Core Data",
      "type": "topic",
      "url": "/documentation/coredata/reading-cloudkit-records-for-core-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit": {
      "abstract": [
        {
          "text": "Set up the classes and capabilities that sync your store to CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Setting Up Core Data with CloudKit",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-core-data-with-cloudkit"
    },
    "doc://com.apple.coredata/documentation/CoreData/syncing-a-core-data-store-with-cloudkit": {
      "abstract": [
        {
          "text": "Synchronize objects between devices, and handle store changes in the user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/syncing-a-core-data-store-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Syncing a Core Data Store with CloudKit",
      "type": "topic",
      "url": "/documentation/coredata/syncing-a-core-data-store-with-cloudkit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreDataVersioning/Articles/Introduction.html#//apple_ref/doc/uid/TP40004399-CH1": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreDataVersioning/Articles/Introduction.html#//apple_ref/doc/uid/TP40004399-CH1",
      "title": "Core Data Model Versioning and Data Migration",
      "titleInlineContent": [
        {
          "text": "Core Data Model Versioning and Data Migration",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreDataVersioning/Articles/Introduction.html#//apple_ref/doc/uid/TP40004399-CH1"
    },
    "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/DeployingYourCloudKitApp/DeployingYourCloudKitApp.html#//apple_ref/doc/uid/TP40014987-CH10": {
      "identifier": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/DeployingYourCloudKitApp/DeployingYourCloudKitApp.html#//apple_ref/doc/uid/TP40014987-CH10",
      "title": "Deploying the Schema",
      "titleInlineContent": [
        {
          "text": "Deploying the Schema",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/DeployingYourCloudKitApp/DeployingYourCloudKitApp.html#//apple_ref/doc/uid/TP40014987-CH10"
    },
    "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EditingSchemesUsingCloudKitDashboard/EditingSchemesUsingCloudKitDashboard.html#//apple_ref/doc/uid/TP40014987-CH5": {
      "identifier": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EditingSchemesUsingCloudKitDashboard/EditingSchemesUsingCloudKitDashboard.html#//apple_ref/doc/uid/TP40014987-CH5",
      "title": "Using CloudKit Dashboard to Manage Databases",
      "titleInlineContent": [
        {
          "text": "Using CloudKit Dashboard to Manage Databases",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitQuickStart/EditingSchemesUsingCloudKitDashboard/EditingSchemesUsingCloudKitDashboard.html#//apple_ref/doc/uid/TP40014987-CH5"
    },
    "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/DesigningforCloudKit/DesigningforCloudKit.html#//apple_ref/doc/uid/TP40012094-CH9": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/DesigningforCloudKit/DesigningforCloudKit.html#//apple_ref/doc/uid/TP40012094-CH9",
      "title": "Designing for CloudKit",
      "titleInlineContent": [
        {
          "text": "Designing for CloudKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Conceptual/iCloudDesignGuide/DesigningforCloudKit/DesigningforCloudKit.html#//apple_ref/doc/uid/TP40012094-CH9"
    },
    "media-3230504": {
      "alt": "Flow diagram showing that your app’s Core Data model generates a CloudKit schema.",
      "identifier": "media-3230504",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/81e8f1f9f7ae3eee6d4ead6744ae33d7/media-3230504@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a7bd843541aaafa2956f7878529ffb5b/media-3230504~dark@2x.png"
        }
      ]
    },
    "spacer": {
      "alt": null,
      "identifier": "spacer",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67dc4b07a8d84366d4cc0e812eb40b4a/spacer.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-CloudKit-Mirroring",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
        "doc://com.apple.coredata/documentation/CoreData/syncing-a-core-data-store-with-cloudkit",
        "doc://com.apple.coredata/documentation/CoreData/reading-cloudkit-records-for-core-data"
      ],
      "title": "Configuring CloudKit Mirroring"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-CloudKit-Mirroring",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
                "doc://com.apple.coredata/documentation/CoreData/syncing-a-core-data-store-with-cloudkit",
                "doc://com.apple.coredata/documentation/CoreData/reading-cloudkit-records-for-core-data"
              ],
              "title": "Configuring CloudKit Mirroring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/title",
          "value": "NSPersistentCloudKitContainerOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainerOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainerOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject~1objectID/title",
          "value": "objectID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject~1objectID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "objectID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/creating-a-core-data-model-for-cloudkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/creating-a-core-data-model-for-cloudkit"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
