{
  "abstract": [
    {
      "text": "Organize data in two different stores and implement a link between them.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/linking-data-between-two-core-data-stores"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "11.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Linking Data Between Two Core Data Stores"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Sometimes your app needs to work with multiple Core Data stores. For example, if you need to label data in a read-only store, you must write the labeling result to a different store. If you need to synchronize part of a large data set to iCloud, your app can organize the data in two stores to mirror one to CloudKit and keep the other on the local device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app shows how to manage and link data from two different stores with one Core Data stack. The app organizes the records of books and user feedback on the books into two separate stores. It connects two entities from the stores with a fetched property, which enables the app to access a book’s feedback directly. When users add or remove a feedback record and save the change, the app updates the fetched property by refreshing the book object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-Data-Model",
          "level": 3,
          "text": "Configure the Data Model",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app creates a ",
              "type": "text"
            },
            {
              "code": "Book",
              "type": "codeVoice"
            },
            {
              "text": " entity and a ",
              "type": "text"
            },
            {
              "code": "Feedback",
              "type": "codeVoice"
            },
            {
              "text": " entity in the Core Data model, and then creates one ",
              "type": "text"
            },
            {
              "code": "Configuration",
              "type": "codeVoice"
            },
            {
              "text": " for each store, named ",
              "type": "text"
            },
            {
              "code": "Book",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "Feedback",
              "type": "codeVoice"
            },
            {
              "text": " as well, to contain the store’s entity.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To link the entities, the sample app adds a fetched property, ",
              "type": "text"
            },
            {
              "code": "feedbackList",
              "type": "codeVoice"
            },
            {
              "text": ", in the ",
              "type": "text"
            },
            {
              "code": "Book",
              "type": "codeVoice"
            },
            {
              "text": " entity, which is displayed in the entity’s Fetched Properties section in Xcode. The fetched property’s target is set to the ",
              "type": "text"
            },
            {
              "code": "Feedback",
              "type": "codeVoice"
            },
            {
              "text": " entity and its predicate is ",
              "type": "text"
            },
            {
              "code": "bookUUID == $FETCH_SOURCE.uuid",
              "type": "codeVoice"
            },
            {
              "text": ", where ",
              "type": "text"
            },
            {
              "code": "bookUUID",
              "type": "codeVoice"
            },
            {
              "text": " is a key path of the target and ",
              "type": "text"
            },
            {
              "code": "$FETCH_SOURCE",
              "type": "codeVoice"
            },
            {
              "text": " will be replaced with the source of the fetched property, which is the ",
              "type": "text"
            },
            {
              "code": "Book",
              "type": "codeVoice"
            },
            {
              "text": " object in this sample. With this setup, when the app refreshes a ",
              "type": "text"
            },
            {
              "code": "Book",
              "type": "codeVoice"
            },
            {
              "text": " object and accesses its ",
              "type": "text"
            },
            {
              "code": "feedbackList",
              "type": "codeVoice"
            },
            {
              "text": " property, Core Data executes an ",
              "type": "text"
            },
            {
              "code": "NSFetchRequest",
              "type": "codeVoice"
            },
            {
              "text": " with the predicate on the ",
              "type": "text"
            },
            {
              "code": "Feedback",
              "type": "codeVoice"
            },
            {
              "text": " entity, and returns the result to the property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-Up-the-Core-Data-Stack",
          "level": 3,
          "text": "Set Up the Core Data Stack",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The sample app creates one ",
              "type": "text"
            },
            {
              "code": "NSPersistentStoreDescription",
              "type": "codeVoice"
            },
            {
              "text": " object for each store with the store’s URL and model configuration, then uses ",
              "type": "text"
            },
            {
              "code": "NSPersistentContainer",
              "type": "codeVoice"
            },
            {
              "text": " to load the stores.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let container = NSPersistentContainer(name: \"CoreDataFetchedProperty\")",
            "let defaultDirectoryURL = NSPersistentContainer.defaultDirectoryURL()",
            "",
            "let bookStoreURL = defaultDirectoryURL.appendingPathComponent(\"Books.sqlite\")",
            "let bookStoreDescription = NSPersistentStoreDescription(url: bookStoreURL)",
            "bookStoreDescription.configuration = \"Book\"",
            "",
            "let feedbackStoreURL = defaultDirectoryURL.appendingPathComponent(\"Feedback.sqlite\")",
            "let feedbackStoreDescription = NSPersistentStoreDescription(url: feedbackStoreURL)",
            "feedbackStoreDescription.configuration = \"Feedback\"",
            "",
            "container.persistentStoreDescriptions = [bookStoreDescription, feedbackStoreDescription]",
            "container.loadPersistentStores(completionHandler: { (_, error) in",
            "    guard let error = error as NSError? else { return }",
            "    fatalError(\"###\\(#function): Failed to load persistent stores:\\(error)\")",
            "})"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "With this setup, when the app fetches or changes data, Core Data automatically routes the request to the right store based on where the entities are.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Implement-the-Fetched-Property",
          "level": 3,
          "text": "Implement the Fetched Property",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Xcode currently doesn’t generate code for fetched properties, so the sample app adds the following extension to provide the accessor for ",
              "type": "text"
            },
            {
              "code": "feedbackList",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "extension Book {",
            "    var feedbackList: [Feedback]? { // The accessor of the feedbackList property.",
            "        return value(forKey: \"feedbackList\") as? [Feedback]",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "With the ",
              "type": "text"
            },
            {
              "code": "feedbackList",
              "type": "codeVoice"
            },
            {
              "text": " accessor, the app can access the fetched property directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "guard let feedback = book.feedbackList?[indexPath.row] else { return cell }",
            "let rating = Int(feedback.rating)",
            "let comment = feedback.comment ?? \"\""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike a relationship, a fetched property can’t be used in a predicate for ",
              "type": "text"
            },
            {
              "code": "NSFetchRequest",
              "type": "codeVoice"
            },
            {
              "text": ". It isn’t automatically updated when the managed context is saved either. When the sample app saves changes on the ",
              "type": "text"
            },
            {
              "code": "Feedback",
              "type": "codeVoice"
            },
            {
              "text": " entity, the app must refresh the ",
              "type": "text"
            },
            {
              "code": "book",
              "type": "codeVoice"
            },
            {
              "text": " object to update the ",
              "type": "text"
            },
            {
              "code": "book.feedbackList",
              "type": "codeVoice"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "context.refresh(book, mergeChanges: true)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "c9a68b653b7d/LinkingDataBetweenTwoCoreDataStores.zip": {
      "checksum": "c9a68b653b7d0e4c6d03abfba15a4c0f5a04fedb52fb5f1ad0eab0a6b91da6a6ed8ce7082d02b1d740eae6d69c7bc567a287b2da467720dc34fc8bb10094f725",
      "identifier": "c9a68b653b7d/LinkingDataBetweenTwoCoreDataStores.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/c9a68b653b7d/LinkingDataBetweenTwoCoreDataStores.zip"
    },
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model": {
      "abstract": [
        {
          "text": "Define your app’s object structure with a data model file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/creating-a-core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data": {
      "abstract": [
        {
          "text": "Create, store, and present records for a variety of data types.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data",
      "kind": "article",
      "role": "sampleCode",
      "title": "Handling Different Data Types in Core Data",
      "type": "topic",
      "url": "/documentation/coredata/handling-different-data-types-in-core-data"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack": {
      "abstract": [
        {
          "text": "Set up the classes that manage and persist your app’s objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
      "kind": "article",
      "role": "article",
      "title": "Setting up a Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-a-core-data-stack"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "c9a68b653b7d/LinkingDataBetweenTwoCoreDataStores.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
        "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
                "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
                "doc://com.apple.coredata/documentation/CoreData/handling-different-data-types-in-core-data"
              ],
              "title": "Essentials"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/linking-data-between-two-core-data-stores"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/linking-data-between-two-core-data-stores"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
