{
  "abstract": [
    {
      "text": "Migrate elaborate data models with changes that go beyond the capabilities of both lightweight and staged migrations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/manual-migrations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Manual migrations"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies how to map an entity from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMapping",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymapping"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType": {
      "abstract": [
        {
          "text": "The types for mapping an entity between a source model and a destination model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy": {
      "abstract": [
        {
          "text": "A policy instance that customizes the migration process for an entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMigrationPolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMappingModel": {
      "abstract": [
        {
          "text": "A model instance that specifies how to map a model from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "role": "symbol",
      "title": "NSMappingModel",
      "type": "topic",
      "url": "/documentation/coredata/nsmappingmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager": {
      "abstract": [
        {
          "text": "A migration manager instance that performs a migration of data from one persistent store to another using a given mapping model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationManager",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationmanager"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies in a model how to map from a property in a source entity to a property in a destination entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "role": "symbol",
      "title": "NSPropertyMapping",
      "type": "topic",
      "url": "/documentation/coredata/nspropertymapping"
    },
    "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically": {
      "abstract": [
        {
          "text": "Enable lightweight migrations to keep your data model and the underlying data in a consistent state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
      "kind": "article",
      "role": "article",
      "title": "Migrating your data model automatically",
      "type": "topic",
      "url": "/documentation/coredata/migrating-your-data-model-automatically"
    },
    "doc://com.apple.coredata/documentation/CoreData/staged-migrations": {
      "abstract": [
        {
          "text": "Migrate complex data models containing changes that are incompatible with lightweight migrations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/staged-migrations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Staged migrations",
      "type": "topic",
      "url": "/documentation/coredata/staged-migrations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-model-migration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
        "doc://com.apple.coredata/documentation/CoreData/staged-migrations"
      ],
      "title": "Data model migration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Entity-Mapping",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
        "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
      ],
      "title": "Entity Mapping"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Entity-Mapping",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
                "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
              ],
              "title": "Entity Mapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-model-migration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/migrating-your-data-model-automatically",
                "doc://com.apple.coredata/documentation/CoreData/staged-migrations"
              ],
              "title": "Data model migration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/title",
          "value": "NSEntityMigrationPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/title",
          "value": "NSEntityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/title",
          "value": "NSMappingModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/title",
          "value": "NSEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/title",
          "value": "NSPropertyMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/title",
          "value": "NSMigrationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/manual-migrations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/manual-migrations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
