{
  "abstract": [
    {
      "text": "Define standard ways to handle conflicts during a save operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/merge-policies"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Merge Policies"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "NSErrorMergePolicy",
              "type": "codeVoice"
            },
            {
              "text": " is the default policy. It is the only policy that requires action to correct any conflicts. The other policies make a save go through silently by making changes that follow rules specific to that policy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSErrorMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nserrormergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyObjectTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertyobjecttrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyStoreTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertystoretrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy": {
      "abstract": [
        {
          "text": "A policy object that you use to resolve conflicts between the persistent store and in-memory versions of managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "error"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "errorMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "error",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/error"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyObjectTrump"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeByPropertyObjectTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergeByPropertyObjectTrump",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/mergebypropertyobjecttrump"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyStoreTrump"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeByPropertyStoreTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergeByPropertyStoreTrump",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/mergebypropertystoretrump"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite": {
      "abstract": [
        {
          "text": "A merge policy that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overwrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overwriteMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "overwrite",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/overwrite"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollback"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMergePolicy",
          "text": "NSMergePolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rollbackMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "rollback",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicy/rollback"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType": {
      "abstract": [
        {
          "text": "Constants that define merge policy types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSOverwriteMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsoverwritemergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSRollbackMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsrollbackmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/conflict-resolution": {
      "abstract": [
        {
          "text": "Detect and resolve conflicts that occur when data is changed on multiple threads.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/conflict-resolution",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Conflict resolution",
      "type": "topic",
      "url": "/documentation/coredata/conflict-resolution"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-Merge-Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback"
      ],
      "title": "Defining Merge Policies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Policies",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType"
      ],
      "title": "Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Policies",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-Merge-Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/error",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyStoreTrump",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/mergeByPropertyObjectTrump",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/overwrite",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicy/rollback"
              ],
              "title": "Defining Merge Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyObjectTrump/title",
          "value": "mergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyObjectTrump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergeByPropertyObjectTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1overwrite/title",
          "value": "overwriteMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1overwrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overwriteMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/title",
          "value": "NSOverwriteMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOverwriteMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1error/title",
          "value": "errorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1error/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "errorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/title",
          "value": "NSMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1rollback/title",
          "value": "rollbackMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1rollback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rollbackMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyStoreTrump/title",
          "value": "mergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicy~1mergeByPropertyStoreTrump/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/title",
          "value": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/title",
          "value": "NSMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/title",
          "value": "NSErrorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/title",
          "value": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyObjectTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/title",
          "value": "NSRollbackMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRollbackMergePolicy"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/merge-policies"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/merge-policies"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
