{
  "abstract": [
    {
      "text": "The options keys that configure the migration behavior of a persistent store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/migration-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Migration options"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIgnorePersistentStoreVersioningOption": {
      "abstract": [
        {
          "text": "Key to ignore the built-in versioning provided by Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIgnorePersistentStoreVersioningOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIgnorePersistentStoreVersioningOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIgnorePersistentStoreVersioningOption"
        }
      ],
      "role": "symbol",
      "title": "NSIgnorePersistentStoreVersioningOption",
      "type": "topic",
      "url": "/documentation/coredata/nsignorepersistentstoreversioningoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInferMappingModelAutomaticallyOption": {
      "abstract": [
        {
          "text": "Key to attempt to create the mapping model automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInferMappingModelAutomaticallyOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInferMappingModelAutomaticallyOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInferMappingModelAutomaticallyOption"
        }
      ],
      "role": "symbol",
      "title": "NSInferMappingModelAutomaticallyOption",
      "type": "topic",
      "url": "/documentation/coredata/nsinfermappingmodelautomaticallyoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigratePersistentStoresAutomaticallyOption": {
      "abstract": [
        {
          "text": "Key to automatically attempt to migrate versioned stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigratePersistentStoresAutomaticallyOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigratePersistentStoresAutomaticallyOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigratePersistentStoresAutomaticallyOption"
        }
      ],
      "role": "symbol",
      "title": "NSMigratePersistentStoresAutomaticallyOption",
      "type": "topic",
      "url": "/documentation/coredata/nsmigratepersistentstoresautomaticallyoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)": {
      "abstract": [
        {
          "text": "Creates a persistent store coordinator with the specified managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "managedObjectModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithManagedObjectModel:"
        }
      ],
      "role": "symbol",
      "title": "init(managedObjectModel:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/init(managedobjectmodel:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/store-options": {
      "abstract": [
        {
          "text": "The options keys that configure the behavior and characteristics of a persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/store-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Store options",
      "type": "topic",
      "url": "/documentation/coredata/store-options"
    },
    "doc://com.apple.coredata/documentation/CoreData/store-versions": {
      "abstract": [
        {
          "text": "The metadata keys you use when comparing store versions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/store-versions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Store versions",
      "type": "topic",
      "url": "/documentation/coredata/store-versions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-persistent-store-coordinator",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
        "doc://com.apple.coredata/documentation/CoreData/store-options",
        "doc://com.apple.coredata/documentation/CoreData/store-versions"
      ],
      "title": "Creating a persistent store coordinator"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSIgnorePersistentStoreVersioningOption",
        "doc://com.apple.coredata/documentation/CoreData/NSMigratePersistentStoresAutomaticallyOption",
        "doc://com.apple.coredata/documentation/CoreData/NSInferMappingModelAutomaticallyOption"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSIgnorePersistentStoreVersioningOption",
                "doc://com.apple.coredata/documentation/CoreData/NSMigratePersistentStoresAutomaticallyOption",
                "doc://com.apple.coredata/documentation/CoreData/NSInferMappingModelAutomaticallyOption"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-persistent-store-coordinator",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
                "doc://com.apple.coredata/documentation/CoreData/store-options",
                "doc://com.apple.coredata/documentation/CoreData/store-versions"
              ],
              "title": "Creating a persistent store coordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigratePersistentStoresAutomaticallyOption/title",
          "value": "NSMigratePersistentStoresAutomaticallyOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigratePersistentStoresAutomaticallyOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigratePersistentStoresAutomaticallyOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1init(managedObjectModel:)/title",
          "value": "initWithManagedObjectModel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1init(managedObjectModel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithManagedObjectModel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInferMappingModelAutomaticallyOption/title",
          "value": "NSInferMappingModelAutomaticallyOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInferMappingModelAutomaticallyOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInferMappingModelAutomaticallyOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIgnorePersistentStoreVersioningOption/title",
          "value": "NSIgnorePersistentStoreVersioningOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIgnorePersistentStoreVersioningOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIgnorePersistentStoreVersioningOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/migration-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/migration-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
