{
  "abstract": [
    {
      "text": "Configure the data model file to contain your app’s object graph.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/modeling-data"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Modeling data"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A data model holds information about your application’s objects and the graph of how objects relate to each other. You provide this information in your project’s ",
              "type": "text"
            },
            {
              "code": ".xcdatamodeld",
              "type": "codeVoice"
            },
            {
              "text": " file package. To add a data model to your project, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This screenshot shows the data model for an app that displays a feed of earthquake data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3839155",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Model your data by describing your objects as entities, adding their properties as attributes and relationships, and finally generating respective ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " subclasses to inherit change tracking and life cycle management.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObject": {
      "abstract": [
        {
          "text": "The base class that all Core Data model objects inherit from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObject"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObject",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobject"
    },
    "doc://com.apple.coredata/documentation/CoreData/configuring-attributes": {
      "abstract": [
        {
          "text": "Describe the properties that compose an entity.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
      "kind": "article",
      "role": "article",
      "title": "Configuring Attributes",
      "type": "topic",
      "url": "/documentation/coredata/configuring-attributes"
    },
    "doc://com.apple.coredata/documentation/CoreData/configuring-entities": {
      "abstract": [
        {
          "text": "Model your app’s objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/configuring-entities",
      "kind": "article",
      "role": "article",
      "title": "Configuring Entities",
      "type": "topic",
      "url": "/documentation/coredata/configuring-entities"
    },
    "doc://com.apple.coredata/documentation/CoreData/configuring-relationships": {
      "abstract": [
        {
          "text": "Specify how entities relate and how change propagates between them.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
      "kind": "article",
      "role": "article",
      "title": "Configuring Relationships",
      "type": "topic",
      "url": "/documentation/coredata/configuring-relationships"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-model": {
      "abstract": [
        {
          "text": "Describe your app’s object structure.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-model",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model": {
      "abstract": [
        {
          "text": "Define your app’s object structure with a data model file.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/creating-a-core-data-model",
      "kind": "article",
      "role": "article",
      "title": "Creating a Core Data model",
      "type": "topic",
      "url": "/documentation/coredata/creating-a-core-data-model"
    },
    "doc://com.apple.coredata/documentation/CoreData/generating-code": {
      "abstract": [
        {
          "text": "Automatically or manually generate managed object subclasses from entities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/generating-code",
      "kind": "article",
      "role": "article",
      "title": "Generating code",
      "type": "topic",
      "url": "/documentation/coredata/generating-code"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "media-3839155": {
      "alt": "A screenshot showing an .xcdatamodeld file containing a Quake entity with code, magnitude, place, and time attributes.",
      "identifier": "media-3839155",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/bc1708f16eb80039f62429b9fb1c8fe8/media-3839155@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/88461a56c86faddb54691debd1771d62/media-3839155~dark@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-modeling",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/core-data-model"
      ],
      "title": "Data modeling"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-a-Core-Data-Model",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/configuring-entities",
        "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
        "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
        "doc://com.apple.coredata/documentation/CoreData/generating-code"
      ],
      "title": "Configuring a Core Data Model"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-a-Core-Data-Model",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/configuring-entities",
                "doc://com.apple.coredata/documentation/CoreData/configuring-attributes",
                "doc://com.apple.coredata/documentation/CoreData/configuring-relationships",
                "doc://com.apple.coredata/documentation/CoreData/generating-code"
              ],
              "title": "Configuring a Core Data Model"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-modeling",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/core-data-model"
              ],
              "title": "Data modeling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/title",
          "value": "NSManagedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObject/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/modeling-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/modeling-data"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
