{
  "abstract": [
    {
      "text": "The keys you use to retrieve values from a notification’s user info dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/notification-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Notification keys"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey": {
      "abstract": [
        {
          "text": "Key for the array of stores that were added.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAddedPersistentStoresKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAddedPersistentStoresKey"
        }
      ],
      "role": "symbol",
      "title": "NSAddedPersistentStoresKey",
      "type": "topic",
      "url": "/documentation/coredata/nsaddedpersistentstoreskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict": {
      "abstract": [
        {
          "text": "An encapsulation of conflicts that occur during an attempt to save changes in a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeConflict"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeConflict"
        }
      ],
      "role": "symbol",
      "title": "NSMergeConflict",
      "type": "topic",
      "url": "/documentation/coredata/nsmergeconflict"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreConnectionPoolMaxSizeKey": {
      "abstract": [
        {
          "text": "The maximum connection pool size to use on a store that supports concurrent request handling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreConnectionPoolMaxSizeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreConnectionPoolMaxSizeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreConnectionPoolMaxSizeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreConnectionPoolMaxSizeKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreconnectionpoolmaxsizekey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreSaveConflictsErrorKey": {
      "abstract": [
        {
          "text": "The key for the array of merge conflict objects (instances of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeConflict",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ").",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreSaveConflictsErrorKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreSaveConflictsErrorKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreSaveConflictsErrorKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreSaveConflictsErrorKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoresaveconflictserrorkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousTransitionTypeKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontypekey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey": {
      "abstract": [
        {
          "text": "Key for the array of stores that were removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRemovedPersistentStoresKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRemovedPersistentStoresKey"
        }
      ],
      "role": "symbol",
      "title": "NSRemovedPersistentStoresKey",
      "type": "topic",
      "url": "/documentation/coredata/nsremovedpersistentstoreskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSUUIDChangedPersistentStoresKey": {
      "abstract": [
        {
          "text": "Key for an array containing the old and new stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUUIDChangedPersistentStoresKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSUUIDChangedPersistentStoresKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUUIDChangedPersistentStoresKey"
        }
      ],
      "role": "symbol",
      "title": "NSUUIDChangedPersistentStoresKey",
      "type": "topic",
      "url": "/documentation/coredata/nsuuidchangedpersistentstoreskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468800-nspersistentstorecoordinatorstor": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator changes its registered stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresWillChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468800-nspersistentstorecoordinatorstor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresWillChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1468800-nspersistentstorecoordinatorstor"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468876-nspersistentstorecoordinatorwill": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator removes a store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorWillRemoveStore"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468876-nspersistentstorecoordinatorwill",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorWillRemoveStore",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1468876-nspersistentstorecoordinatorwill"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468925-nspersistentstorecoordinatorstor": {
      "abstract": [
        {
          "text": "A notification that the coordinator posts after its registered stores change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468925-nspersistentstorecoordinatorstor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1468925-nspersistentstorecoordinatorstor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-changes-of-the-coordinators-registered-stores",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468800-nspersistentstorecoordinatorstor",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468925-nspersistentstorecoordinatorstor",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468876-nspersistentstorecoordinatorwill"
      ],
      "title": "Responding to changes of the coordinator’s registered stores"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey",
        "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey",
        "doc://com.apple.coredata/documentation/CoreData/NSUUIDChangedPersistentStoresKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreConnectionPoolMaxSizeKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreSaveConflictsErrorKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey",
                "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey",
                "doc://com.apple.coredata/documentation/CoreData/NSUUIDChangedPersistentStoresKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreConnectionPoolMaxSizeKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreSaveConflictsErrorKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-changes-of-the-coordinators-registered-stores",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468800-nspersistentstorecoordinatorstor",
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468925-nspersistentstorecoordinatorstor",
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468876-nspersistentstorecoordinatorwill"
              ],
              "title": "Responding to changes of the coordinator’s registered stores"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAddedPersistentStoresKey/title",
          "value": "NSAddedPersistentStoresKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAddedPersistentStoresKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAddedPersistentStoresKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/title",
          "value": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRemovedPersistentStoresKey/title",
          "value": "NSRemovedPersistentStoresKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRemovedPersistentStoresKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemovedPersistentStoresKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreConnectionPoolMaxSizeKey/title",
          "value": "NSPersistentStoreConnectionPoolMaxSizeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreConnectionPoolMaxSizeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreConnectionPoolMaxSizeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreSaveConflictsErrorKey/title",
          "value": "NSPersistentStoreSaveConflictsErrorKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreSaveConflictsErrorKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreSaveConflictsErrorKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/title",
          "value": "NSMergeConflict"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeConflict/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeConflict"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUUIDChangedPersistentStoresKey/title",
          "value": "NSUUIDChangedPersistentStoresKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUUIDChangedPersistentStoresKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUUIDChangedPersistentStoresKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/notification-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/notification-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
