{
  "abstract": [
    {
      "text": "A request to Core Data to do a batch update of data in a persistent store without loading any data into memory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSBatchUpdateRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSBatchUpdateRequest"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSBatchUpdateRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSBatchUpdateRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest": {
      "abstract": [
        {
          "text": "A request to Core Data to do a batch update of data in a persistent store without loading any data into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchUpdateRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchUpdateRequest"
        }
      ],
      "role": "symbol",
      "title": "NSBatchUpdateRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/batchUpdateRequestWithEntityName:": {
      "abstract": [
        {
          "text": "Creates a batch-update request for a named managed entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "batchUpdateRequestWithEntityName:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/batchUpdateRequestWithEntityName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "batchUpdateRequestWithEntityName:"
        }
      ],
      "role": "symbol",
      "title": "batchUpdateRequestWithEntityName:",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/batchupdaterequestwithentityname:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entity": {
      "abstract": [
        {
          "text": "The managed entity to update data for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entity"
        }
      ],
      "role": "symbol",
      "title": "entity",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/entity"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entityName": {
      "abstract": [
        {
          "text": "The name of the managed entity to update data for.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entityName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entityName"
        }
      ],
      "role": "symbol",
      "title": "entityName",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/entityname"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/includesSubentities": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to update subentities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includesSubentities"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/includesSubentities",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includesSubentities"
        }
      ],
      "role": "symbol",
      "title": "includesSubentities",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/includessubentities"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entity:)": {
      "abstract": [
        {
          "text": "Creates a batch-update request for a managed entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entity:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntity:"
        }
      ],
      "role": "symbol",
      "title": "init(entity:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/init(entity:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entityName:)": {
      "abstract": [
        {
          "text": "Creates a batch-update request for a named managed entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "entityName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entityName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithEntityName:"
        }
      ],
      "role": "symbol",
      "title": "init(entityName:)",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/init(entityname:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/predicate": {
      "abstract": [
        {
          "text": "A predicate that identifies the objects to update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/predicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicate"
        }
      ],
      "role": "symbol",
      "title": "predicate",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/predicate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/propertiesToUpdate": {
      "abstract": [
        {
          "text": "A dictionary of property description pairs that describe the updates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertiesToUpdate"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/propertiesToUpdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertiesToUpdate"
        }
      ],
      "role": "symbol",
      "title": "propertiesToUpdate",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/propertiestoupdate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/resultType": {
      "abstract": [
        {
          "text": "The type of result that Core Data returns from the request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBatchUpdateRequestResultType",
          "text": "NSBatchUpdateRequestResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/resultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultType"
        }
      ],
      "role": "symbol",
      "title": "resultType",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdaterequest/resulttype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult": {
      "abstract": [
        {
          "text": "The result returned when executing a batch update request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBatchUpdateResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBatchUpdateResult"
        }
      ],
      "role": "symbol",
      "title": "NSBatchUpdateResult",
      "type": "topic",
      "url": "/documentation/coredata/nsbatchupdateresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest": {
      "abstract": [
        {
          "text": "Criteria used to retrieve data from or save data to a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorerequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Data-Updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult"
      ],
      "title": "Data Updates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Request",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entity:)",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entityName:)"
      ],
      "title": "Creating a Request"
    },
    {
      "anchor": "Configuring-a-Request",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entity",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entityName",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/includesSubentities",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/predicate",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/propertiesToUpdate",
        "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/resultType"
      ],
      "title": "Configuring a Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSBatchUpdateRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Request",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entity:)",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/init(entityName:)",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/batchUpdateRequestWithEntityName:"
              ],
              "title": "Creating a Request"
            },
            {
              "anchor": "Configuring-a-Request",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entity",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/entityName",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/includesSubentities",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/predicate",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/propertiesToUpdate",
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateRequest/resultType"
              ],
              "title": "Configuring a Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Data-Updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSBatchUpdateResult"
              ],
              "title": "Data Updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSBatchUpdateRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPersistentStoreRequest",
                    "text": "NSPersistentStoreRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1init(entityName:)/title",
          "value": "initWithEntityName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1init(entityName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntityName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/title",
          "value": "NSBatchUpdateRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/title",
          "value": "NSPersistentStoreRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1init(entity:)/title",
          "value": "initWithEntity:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1init(entity:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithEntity:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1entity/title",
          "value": "entity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1entity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1propertiesToUpdate/title",
          "value": "propertiesToUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1propertiesToUpdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "propertiesToUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1resultType/title",
          "value": "resultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1resultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/title",
          "value": "NSBatchUpdateResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBatchUpdateResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1predicate/title",
          "value": "predicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1predicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1entityName/title",
          "value": "entityName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1entityName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entityName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1includesSubentities/title",
          "value": "includesSubentities"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBatchUpdateRequest~1includesSubentities/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includesSubentities"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsbatchupdaterequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsbatchupdaterequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
