{
  "abstract": [
    {
      "text": "The Core Data version number released with macOS 10.6.3.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_3"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@NSCoreDataVersionNumber10_6_3",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCoreDataVersionNumber10_6_3"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCoreDataVersionNumber10_6_3"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSCoreDataVersionNumber10_6_3"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_6_3"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber": {
      "abstract": [
        {
          "text": "The version of Core Data available in the current process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.10.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_10",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_10"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_2": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.10.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10_2"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_10_2",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_10_2"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.10.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_10_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_10_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_10_3"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.11.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_11"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_11"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_11",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_11"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.11.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_11_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_11_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_11_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_11_3"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.4.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_4"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_4"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_4",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_4"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.4.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_4_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_4_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_4_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_4_3"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.5.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_5"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_5"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_5",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_5"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.5.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_5_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_5_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_5_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_5_3"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.6.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_6",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_6"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_2": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.6.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6_2"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_6_2",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_6_2"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.6.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_6_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_6_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_6_3"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.7.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_7",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_7"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_2": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.7.2.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7_2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7_2"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_7_2",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_7_2"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_3": {
      "abstract": [
        {
          "text": "The Core Data version number released with macOS 10.7.3.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7_3"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataVersionNumber10_7_3"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataVersionNumber10_7_3",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataversionnumber10_7_3"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Core-Data-Versions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_2",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_3",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11_3",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4_3",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5_3",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_2",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_2",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_3"
      ],
      "title": "Core Data Versions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCoreDataVersionNumber10_6_3"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_6_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Core-Data-Versions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_2",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_10_3",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_11_3",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_4_3",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_5_3",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_6_2",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_2",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataVersionNumber10_7_3"
              ],
              "title": "Core Data Versions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCoreDataVersionNumber10_6_3"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_4/title",
          "value": "NSCoreDataVersionNumber10_4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6_3/title",
          "value": "NSCoreDataVersionNumber10_6_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_6_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10_3/title",
          "value": "NSCoreDataVersionNumber10_10_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_10_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10/title",
          "value": "NSCoreDataVersionNumber10_10"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_10"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7/title",
          "value": "NSCoreDataVersionNumber10_7"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_7"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_4_3/title",
          "value": "NSCoreDataVersionNumber10_4_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_4_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_4_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_11_3/title",
          "value": "NSCoreDataVersionNumber10_11_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_11_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_11_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber/title",
          "value": "NSCoreDataVersionNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10_2/title",
          "value": "NSCoreDataVersionNumber10_10_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_10_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_10_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_5/title",
          "value": "NSCoreDataVersionNumber10_5"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_5/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_5"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7_3/title",
          "value": "NSCoreDataVersionNumber10_7_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_7_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6_2/title",
          "value": "NSCoreDataVersionNumber10_6_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_6_2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_11/title",
          "value": "NSCoreDataVersionNumber10_11"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_11/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_11"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6/title",
          "value": "NSCoreDataVersionNumber10_6"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_6/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_6"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_5_3/title",
          "value": "NSCoreDataVersionNumber10_5_3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_5_3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_5_3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7_2/title",
          "value": "NSCoreDataVersionNumber10_7_2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataVersionNumber10_7_2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataVersionNumber10_7_2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nscoredataversionnumber10_6_3"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nscoredataversionnumber10_6_3"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
