{
  "abstract": [
    {
      "text": "A set of methods that enable integration with Core Spotlight.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCoreDataCoreSpotlightDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCoreDataCoreSpotlightDelegate"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCoreDataCoreSpotlightDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSCoreDataCoreSpotlightDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Core Spotlight integration is only available for persistent stores that have a store type of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore/StoreType/sqlite",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and which use persistent history tracking. For more information, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate": {
      "abstract": [
        {
          "text": "A set of methods that enable integration with Core Spotlight.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightDelegate"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataCoreSpotlightDelegate",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)": {
      "abstract": [
        {
          "text": "Returns the searchable attributes for the specified managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributeSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableItemAttributeSet",
          "text": "CSSearchableItemAttributeSet"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributeSetForObject:"
        }
      ],
      "role": "symbol",
      "title": "attributeSet(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/attributeset(for:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)": {
      "abstract": [
        {
          "text": "Deletes all searchable items from the configured index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteSpotlightIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteSpotlightIndexWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "deleteSpotlightIndex(completionHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/deletespotlightindex(completionhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/domainIdentifier()": {
      "abstract": [
        {
          "text": "Returns the domain identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "domainIdentifier"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/domainIdentifier()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "domainIdentifier"
        }
      ],
      "role": "symbol",
      "title": "domainIdentifier()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/domainidentifier()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexDidUpdateNotification": {
      "abstract": [
        {
          "text": "The notification the delegate posts after Spotlight updates the index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexDidUpdateNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexDidUpdateNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "indexDidUpdateNotification",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/indexdidupdatenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexName()": {
      "abstract": [
        {
          "text": "Returns the index’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "indexName"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexName()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexName"
        }
      ],
      "role": "symbol",
      "title": "indexName()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/indexname()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:coordinator:)": {
      "abstract": [
        {
          "text": "Creates a Core Spotlight delegate with the specified store description and coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forStoreWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreDescription",
          "text": "NSPersistentStoreDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "coordinator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreCoordinator",
          "text": "NSPersistentStoreCoordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:coordinator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForStoreWithDescription:coordinator:"
        }
      ],
      "role": "symbol",
      "title": "init(forStoreWith:coordinator:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/init(forstorewith:coordinator:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:model:)": {
      "abstract": [
        {
          "text": "Creates a Core Spotlight delegate with the specified store description and managed object model.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forStoreWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreDescription",
          "text": "NSPersistentStoreDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "model"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:model:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForStoreWithDescription:model:"
        }
      ],
      "role": "symbol",
      "title": "init(forStoreWith:model:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/init(forstorewith:model:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/isIndexingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether Core Data is currently updating the Core Spotlight index with the persistent store’s entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isIndexingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/isIndexingEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexingEnabled"
        }
      ],
      "role": "symbol",
      "title": "isIndexingEnabled",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/isindexingenabled"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)": {
      "abstract": [
        {
          "text": "Reindexes all searchable items and clears any local state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchableIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableIndex",
          "text": "CSSearchableIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reindexAllSearchableItemsWithAcknowledgementHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchableIndex:reindexAllSearchableItemsWithAcknowledgementHandler:"
        }
      ],
      "role": "symbol",
      "title": "searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/searchableindex(_:reindexallsearchableitemswithacknowledgementhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)": {
      "abstract": [
        {
          "text": "Reindexes the searchable items for the specified identifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchableIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CSSearchableIndex",
          "text": "CSSearchableIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reindexSearchableItemsWithIdentifiers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "acknowledgementHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchableIndex:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:"
        }
      ],
      "role": "symbol",
      "title": "searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/searchableindex(_:reindexsearchableitemswithidentifiers:acknowledgementhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()": {
      "abstract": [
        {
          "text": "Starts the indexing of the store’s entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startSpotlightIndexing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startSpotlightIndexing"
        }
      ],
      "role": "symbol",
      "title": "startSpotlightIndexing()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/startspotlightindexing()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()": {
      "abstract": [
        {
          "text": "Stops the indexing of the store’s entities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopSpotlightIndexing"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopSpotlightIndexing"
        }
      ],
      "role": "symbol",
      "title": "stopSpotlightIndexing()",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegate/stopspotlightindexing()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightdelegateindexdidupdatenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightExporter": {
      "abstract": [
        {
          "text": "The key you use to specify your Core Spotlight delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightExporter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightExporter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataCoreSpotlightExporter"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataCoreSpotlightExporter",
      "type": "topic",
      "url": "/documentation/coredata/nscoredatacorespotlightexporter"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore/StoreType/sqlite": {
      "abstract": [
        {
          "text": "A store that reads from and writes to a persistent SQLite database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sqlite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So17NSPersistentStoreC8CoreDataE0B4TypeV",
          "text": "StoreType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore/StoreType/sqlite",
      "kind": "symbol",
      "role": "symbol",
      "title": "sqlite",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstore/storetype/sqlite"
    },
    "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes": {
      "abstract": [
        {
          "text": "Filter store transactions for changes relevant to the current view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Consuming relevant store changes",
      "type": "topic",
      "url": "/documentation/coredata/consuming-relevant-store-changes"
    },
    "doc://com.apple.coredata/documentation/CoreData/showcase-app-data-in-spotlight": {
      "abstract": [
        {
          "text": "Index app data so users can find it by using Spotlight search.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/showcase-app-data-in-spotlight",
      "kind": "article",
      "role": "sampleCode",
      "title": "Showcase App Data in Spotlight",
      "type": "topic",
      "url": "/documentation/coredata/showcase-app-data-in-spotlight"
    },
    "doc://com.apple.coredata/documentation/CoreData/spotlight-record-keys": {
      "abstract": [
        {
          "text": "The keys for the values that exist in Spotlight’s external record files.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/spotlight-record-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Spotlight record keys",
      "type": "topic",
      "url": "/documentation/coredata/spotlight-record-keys"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Integrating-with-Spotlight",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightExporter",
        "doc://com.apple.coredata/documentation/CoreData/spotlight-record-keys",
        "doc://com.apple.coredata/documentation/CoreData/showcase-app-data-in-spotlight"
      ],
      "title": "Integrating with Spotlight"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Core-Spotlight-Delegate",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:coordinator:)",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:model:)"
      ],
      "title": "Creating a Core Spotlight Delegate"
    },
    {
      "anchor": "Configuring-the-Index",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/isIndexingEnabled",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/domainIdentifier()",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexName()"
      ],
      "title": "Configuring the Index"
    },
    {
      "anchor": "Managing-the-Index",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()"
      ],
      "title": "Managing the Index"
    },
    {
      "anchor": "Updating-the-Index",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexDidUpdateNotification",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)",
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)"
      ],
      "title": "Updating the Index"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCoreDataCoreSpotlightDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Core-Spotlight-Delegate",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:coordinator:)",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/init(forStoreWith:model:)"
              ],
              "title": "Creating a Core Spotlight Delegate"
            },
            {
              "anchor": "Configuring-the-Index",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/isIndexingEnabled",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/domainIdentifier()",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/indexName()"
              ],
              "title": "Configuring the Index"
            },
            {
              "anchor": "Managing-the-Index",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/attributeSet(for:)",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/deleteSpotlightIndex(completionHandler:)",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/startSpotlightIndexing()",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/stopSpotlightIndexing()"
              ],
              "title": "Managing the Index"
            },
            {
              "anchor": "Updating-the-Index",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)",
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegate/searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)"
              ],
              "title": "Updating the Index"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Integrating-with-Spotlight",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataCoreSpotlightExporter",
                "doc://com.apple.coredata/documentation/CoreData/spotlight-record-keys",
                "doc://com.apple.coredata/documentation/CoreData/showcase-app-data-in-spotlight"
              ],
              "title": "Integrating with Spotlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCoreDataCoreSpotlightDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1isIndexingEnabled/title",
          "value": "indexingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1isIndexingEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "indexingEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/title",
          "value": "NSCoreDataCoreSpotlightDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1init(forStoreWith:coordinator:)/title",
          "value": "initForStoreWithDescription:coordinator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1init(forStoreWith:coordinator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForStoreWithDescription:coordinator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightExporter/title",
          "value": "NSCoreDataCoreSpotlightExporter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightExporter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataCoreSpotlightExporter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)/title",
          "value": "searchableIndex:reindexAllSearchableItemsWithAcknowledgementHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1searchableIndex(_:reindexAllSearchableItemsWithAcknowledgementHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchableIndex:reindexAllSearchableItemsWithAcknowledgementHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1deleteSpotlightIndex(completionHandler:)/title",
          "value": "deleteSpotlightIndexWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1deleteSpotlightIndex(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deleteSpotlightIndexWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1init(forStoreWith:model:)/title",
          "value": "initForStoreWithDescription:model:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1init(forStoreWith:model:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForStoreWithDescription:model:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1indexName()/title",
          "value": "indexName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1indexName()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1attributeSet(for:)/title",
          "value": "attributeSetForObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1attributeSet(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "attributeSetForObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1domainIdentifier()/title",
          "value": "domainIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1domainIdentifier()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "domainIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1startSpotlightIndexing()/title",
          "value": "startSpotlightIndexing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1startSpotlightIndexing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startSpotlightIndexing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1stopSpotlightIndexing()/title",
          "value": "stopSpotlightIndexing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1stopSpotlightIndexing()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopSpotlightIndexing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)/title",
          "value": "searchableIndex:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataCoreSpotlightDelegate~1searchableIndex(_:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchableIndex:reindexSearchableItemsWithIdentifiers:acknowledgementHandler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nscoredatacorespotlightdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nscoredatacorespotlightdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
