{
  "abstract": [
    {
      "text": "The types for mapping an entity between a source model and a destination model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSEntityMappingType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSEntityMappingType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEntityMappingType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSEntityMappingType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies how to map an entity from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMapping",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymapping"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType": {
      "abstract": [
        {
          "text": "The types for mapping an entity between a source model and a destination model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/addEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies that this is a new entity in the destination model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/addEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAddEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.addEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/addentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/copyEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies that source instances are migrated as-is.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/copyEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCopyEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.copyEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/copyentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/customEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies a custom mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/customEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCustomEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.customEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/customentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/init(rawvalue:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/removeEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies that this entity is not present in the destination model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/removeEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRemoveEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.removeEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/removeentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/transformEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies that entity exists in source and destination and is mapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transformEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/transformEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTransformEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.transformEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/transformentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/undefinedEntityMappingType": {
      "abstract": [
        {
          "text": "Specifies that the developer handles destination instance creation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undefinedEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/undefinedEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUndefinedEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType.undefinedEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype/undefinedentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy": {
      "abstract": [
        {
          "text": "A policy instance that customizes the migration process for an entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMigrationPolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMappingModel": {
      "abstract": [
        {
          "text": "A model instance that specifies how to map a model from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "role": "symbol",
      "title": "NSMappingModel",
      "type": "topic",
      "url": "/documentation/coredata/nsmappingmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager": {
      "abstract": [
        {
          "text": "A migration manager instance that performs a migration of data from one persistent store to another using a given mapping model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationManager",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationmanager"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies in a model how to map from a property in a source entity to a property in a destination entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "role": "symbol",
      "title": "NSPropertyMapping",
      "type": "topic",
      "url": "/documentation/coredata/nspropertymapping"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Entity-Mapping",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
        "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
      ],
      "title": "Entity Mapping"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/addEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/copyEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/customEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/removeEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/transformEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/undefinedEntityMappingType"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/addEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/copyEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/customEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/removeEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/transformEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType/undefinedEntityMappingType"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Entity-Mapping",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
                "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
              ],
              "title": "Entity Mapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSEntityMappingType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/title",
          "value": "NSMappingModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1addEntityMappingType/title",
          "value": "NSAddEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1addEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAddEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1customEntityMappingType/title",
          "value": "NSCustomEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1customEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCustomEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1transformEntityMappingType/title",
          "value": "NSTransformEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1transformEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTransformEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/title",
          "value": "NSMigrationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/title",
          "value": "NSPropertyMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/title",
          "value": "NSEntityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1removeEntityMappingType/title",
          "value": "NSRemoveEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1removeEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemoveEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/title",
          "value": "NSEntityMigrationPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1copyEntityMappingType/title",
          "value": "NSCopyEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1copyEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCopyEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/title",
          "value": "NSEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1undefinedEntityMappingType/title",
          "value": "NSUndefinedEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType~1undefinedEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUndefinedEntityMappingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsentitymappingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsentitymappingtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
