{
  "abstract": [
    {
      "text": "A policy instance that customizes the migration process for an entity mapping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSEntityMigrationPolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSEntityMigrationPolicy"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSEntityMigrationPolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSEntityMigrationPolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You set the policy for an entity mapping by passing the name of the migration policy class as the argument to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping/entityMigrationPolicyClassName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Typically, you specify the name in the Xcode mapping model editor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies how to map an entity from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMapping"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMapping",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymapping"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping/entityMigrationPolicyClassName": {
      "abstract": [
        {
          "text": "The class name of the migration policy for the entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "entityMigrationPolicyClassName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping/entityMigrationPolicyClassName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "entityMigrationPolicyClassName"
        }
      ],
      "role": "symbol",
      "title": "entityMigrationPolicyClassName",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymapping/entitymigrationpolicyclassname"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType": {
      "abstract": [
        {
          "text": "The types for mapping an entity between a source model and a destination model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMappingType"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMappingType",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymappingtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy": {
      "abstract": [
        {
          "text": "A policy instance that customizes the migration process for an entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicy"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMigrationPolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/begin(_:with:)": {
      "abstract": [
        {
          "text": "Sets up state information before the start of a given entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "begin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/begin(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginEntityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "begin(_:with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/begin(_:with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createDestinationInstances(forSource:in:manager:)": {
      "abstract": [
        {
          "text": "Creates the destination instance(s) for a given source instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createDestinationInstances"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forSource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createDestinationInstances(forSource:in:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createDestinationInstancesForSourceInstance:entityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "createDestinationInstances(forSource:in:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/createdestinationinstances(forsource:in:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createRelationships(forDestination:in:manager:)": {
      "abstract": [
        {
          "text": "Constructs the relationships between the newly-created destination instances.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "createRelationships"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forDestination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createRelationships(forDestination:in:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "createRelationshipsForDestinationInstance:entityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "createRelationships(forDestination:in:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/createrelationships(fordestination:in:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/end(_:manager:)": {
      "abstract": [
        {
          "text": "Performs cleanup at the end of the migration, from any phase of the mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/end(_:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endEntityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "end(_:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/end(_:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endInstanceCreation(forMapping:manager:)": {
      "abstract": [
        {
          "text": "Indicates the end of the instance creation stage for the specified entity mapping, and the precursor to the next migration stage.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endInstanceCreation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMapping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endInstanceCreation(forMapping:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endInstanceCreationForEntityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "endInstanceCreation(forMapping:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/endinstancecreation(formapping:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endRelationshipCreation(forMapping:manager:)": {
      "abstract": [
        {
          "text": "Indicates the end of the relationship creation stage for the specified entity mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endRelationshipCreation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMapping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endRelationshipCreation(forMapping:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endRelationshipCreationForEntityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "endRelationshipCreation(forMapping:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/endrelationshipcreation(formapping:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/performCustomValidation(forMapping:manager:)": {
      "abstract": [
        {
          "text": "Provides the option to perform custom validation on migrated objects during the validation stage of the entity migration policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performCustomValidation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forMapping"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityMapping",
          "text": "NSEntityMapping"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "manager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMigrationManager",
          "text": "NSMigrationManager"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/performCustomValidation(forMapping:manager:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performCustomValidationForEntityMapping:manager:error:"
        }
      ],
      "role": "symbol",
      "title": "performCustomValidation(forMapping:manager:)",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicy/performcustomvalidation(formapping:manager:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMappingModel": {
      "abstract": [
        {
          "text": "A model instance that specifies how to map a model from a source to a destination managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMappingModel"
        }
      ],
      "role": "symbol",
      "title": "NSMappingModel",
      "type": "topic",
      "url": "/documentation/coredata/nsmappingmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationDestinationObjectKey": {
      "abstract": [
        {
          "text": "Key for the destination object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationDestinationObjectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationDestinationObjectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationDestinationObjectKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationDestinationObjectKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationdestinationobjectkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityMappingKey": {
      "abstract": [
        {
          "text": "Key for the entity mapping object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationEntityMappingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityMappingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationEntityMappingKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationEntityMappingKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationentitymappingkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityPolicyKey": {
      "abstract": [
        {
          "text": "Key for the entity migration policy object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationEntityPolicyKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityPolicyKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationEntityPolicyKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationEntityPolicyKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationentitypolicykey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager": {
      "abstract": [
        {
          "text": "A migration manager instance that performs a migration of data from one persistent store to another using a given mapping model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationManager"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationManager",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationmanager"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationManagerKey": {
      "abstract": [
        {
          "text": "Key for the migration manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationManagerKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationManagerKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationManagerKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationManagerKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationmanagerkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationPropertyMappingKey": {
      "abstract": [
        {
          "text": "Key for the property mapping object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationPropertyMappingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationPropertyMappingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationPropertyMappingKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationPropertyMappingKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationpropertymappingkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationSourceObjectKey": {
      "abstract": [
        {
          "text": "Key for the source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationSourceObjectKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationSourceObjectKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationSourceObjectKey"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationSourceObjectKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationsourceobjectkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping": {
      "abstract": [
        {
          "text": "A mapping instance that specifies in a model how to map from a property in a source entity to a property in a destination entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPropertyMapping"
        }
      ],
      "role": "symbol",
      "title": "NSPropertyMapping",
      "type": "topic",
      "url": "/documentation/coredata/nspropertymapping"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Entity-Mapping",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
        "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
        "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
      ],
      "title": "Entity Mapping"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-Stages-of-the-Mapping-Life-Cycle",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/begin(_:with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createDestinationInstances(forSource:in:manager:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endInstanceCreation(forMapping:manager:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createRelationships(forDestination:in:manager:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endRelationshipCreation(forMapping:manager:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/performCustomValidation(forMapping:manager:)",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/end(_:manager:)"
      ],
      "title": "Customizing Stages of the Mapping Life Cycle"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationManagerKey",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationSourceObjectKey",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationDestinationObjectKey",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityMappingKey",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationPropertyMappingKey",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityPolicyKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSEntityMigrationPolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-Stages-of-the-Mapping-Life-Cycle",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/begin(_:with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createDestinationInstances(forSource:in:manager:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endInstanceCreation(forMapping:manager:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/createRelationships(forDestination:in:manager:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/endRelationshipCreation(forMapping:manager:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/performCustomValidation(forMapping:manager:)",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicy/end(_:manager:)"
              ],
              "title": "Customizing Stages of the Mapping Life Cycle"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationManagerKey",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationSourceObjectKey",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationDestinationObjectKey",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityMappingKey",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationPropertyMappingKey",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationEntityPolicyKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Entity-Mapping",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationManager",
                "doc://com.apple.coredata/documentation/CoreData/NSMappingModel",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMapping",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMappingType",
                "doc://com.apple.coredata/documentation/CoreData/NSPropertyMapping"
              ],
              "title": "Entity Mapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSEntityMigrationPolicy"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1endInstanceCreation(forMapping:manager:)/title",
          "value": "endInstanceCreationForEntityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1endInstanceCreation(forMapping:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endInstanceCreationForEntityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1endRelationshipCreation(forMapping:manager:)/title",
          "value": "endRelationshipCreationForEntityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1endRelationshipCreation(forMapping:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endRelationshipCreationForEntityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1begin(_:with:)/title",
          "value": "beginEntityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1begin(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginEntityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/title",
          "value": "NSPropertyMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1performCustomValidation(forMapping:manager:)/title",
          "value": "performCustomValidationForEntityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1performCustomValidation(forMapping:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performCustomValidationForEntityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/title",
          "value": "NSEntityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1createRelationships(forDestination:in:manager:)/title",
          "value": "createRelationshipsForDestinationInstance:entityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1createRelationships(forDestination:in:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createRelationshipsForDestinationInstance:entityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/title",
          "value": "NSEntityMigrationPolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationSourceObjectKey/title",
          "value": "NSMigrationSourceObjectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationSourceObjectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationSourceObjectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/title",
          "value": "NSEntityMappingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMappingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMappingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationEntityPolicyKey/title",
          "value": "NSMigrationEntityPolicyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationEntityPolicyKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationEntityPolicyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationPropertyMappingKey/title",
          "value": "NSMigrationPropertyMappingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationPropertyMappingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationPropertyMappingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationDestinationObjectKey/title",
          "value": "NSMigrationDestinationObjectKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationDestinationObjectKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationDestinationObjectKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1end(_:manager:)/title",
          "value": "endEntityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1end(_:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endEntityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/title",
          "value": "NSMigrationManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1createDestinationInstances(forSource:in:manager:)/title",
          "value": "createDestinationInstancesForSourceInstance:entityMapping:manager:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicy~1createDestinationInstances(forSource:in:manager:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "createDestinationInstancesForSourceInstance:entityMapping:manager:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/title",
          "value": "NSMappingModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMappingModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMappingModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping~1entityMigrationPolicyClassName/title",
          "value": "entityMigrationPolicyClassName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMapping~1entityMigrationPolicyClassName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "entityMigrationPolicyClassName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManagerKey/title",
          "value": "NSMigrationManagerKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationManagerKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationManagerKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationEntityMappingKey/title",
          "value": "NSMigrationEntityMappingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationEntityMappingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationEntityMappingKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsentitymigrationpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsentitymigrationpolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
