{
  "abstract": [
    {
      "text": "The default merge policy for all managed object contexts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSErrorMergePolicy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSErrorMergePolicy"
      },
      {
        "kind": "text",
        "text": ": AnyObject"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSErrorMergePolicy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSErrorMergePolicy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicy"
            },
            {
              "kind": "text",
              "text": ": AnyObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If a save fails because of conflicting objects, you can find the IDs of those objects in error’s ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys to extract the object IDs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSErrorMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nserrormergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were inserted into the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinsertedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyObjectTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertyobjecttrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyStoreTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertystoretrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType": {
      "abstract": [
        {
          "text": "Constants that define merge policy types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSOverwriteMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsoverwritemergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSRollbackMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsrollbackmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSUpdatedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsupdatedobjectskey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType"
      ],
      "title": "Policies"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSErrorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "id"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSErrorMergePolicy"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/title",
          "value": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/title",
          "value": "NSRollbackMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRollbackMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/title",
          "value": "NSInsertedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/title",
          "value": "NSOverwriteMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOverwriteMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/title",
          "value": "NSErrorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/title",
          "value": "NSUpdatedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdatedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/title",
          "value": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyObjectTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/title",
          "value": "NSMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nserrormergepolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nserrormergepolicy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
