{
  "abstract": [
    {
      "text": "Option to specify the file format of a Spotlight external records.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Spotlight integration is deprecated. Use CoreSpotlight integration instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSExternalRecordsFileFormatOption",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSExternalRecordsFileFormatOption"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSExternalRecordsFileFormatOption"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.13",
        "introducedAt": "10.6",
        "message": "Spotlight integration is deprecated. Use CoreSpotlight integration instead.",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSExternalRecordsFileFormatOption"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSExternalRecordsFileFormatOption"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For possible values, see ",
              "type": "text"
            },
            {
              "code": "Format Options for Spotlight External Record Files",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption": {
      "abstract": [
        {
          "text": "Option indicating the file extension to use for Spotlight external record files.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordExtensionOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordExtensionOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordExtensionOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordextensionoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption": {
      "abstract": [
        {
          "text": "Option indicating the directory where Spotlight external record files should be written to.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordsDirectoryOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordsDirectoryOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordsDirectoryOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordsdirectoryoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption": {
      "abstract": [
        {
          "text": "Option to specify the file format of a Spotlight external records.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordsFileFormatOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordsFileFormatOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordsFileFormatOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordsfileformatoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing a boolean that indicates whether the receiver should erase the local store file and rebuild it from the iCloud data in Mobile Documents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRebuildFromUbiquitousContentOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorerebuildfromubiquitouscontentoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing a boolean that indicates whether the receiver should remove all associated ubiquity metadata from a persistent store. You typically use this option during migration or copying to disassociate a persistent store file from an iCloud account.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRemoveUbiquitousMetadataOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreremoveubiquitousmetadataoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey": {
      "abstract": [
        {
          "text": "The a string specifying the iCloud container identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContainerIdentifierKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontaineridentifierkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey": {
      "abstract": [
        {
          "text": "Option to specify that a persistent store has a given name in ubiquity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentNameKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContentNameKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontentnamekey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey": {
      "abstract": [
        {
          "text": "Option to specify the log path to use for ubiquitous content logs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentURLKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContentURLKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontenturlkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption": {
      "abstract": [
        {
          "text": "The corresponding value is an optionally specified string which will be mixed in to Core Data’s identifier for each iCloud peer. The value must be an alphanumeric string without any special characters, whitespace or punctuation. The primary use for this option is to allow multiple applications on the same peer (device) to share a Core Data store integrated with iCloud. Each application will require its own store file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousPeerTokenOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousPeerTokenOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousPeerTokenOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouspeertokenoption"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.13",
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSExternalRecordsFileFormatOption"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordsFileFormatOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSExternalRecordsFileFormatOption"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Spotlight integration is deprecated. Use CoreSpotlight integration instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsFileFormatOption/title",
          "value": "NSExternalRecordsFileFormatOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsFileFormatOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordsFileFormatOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentURLKey/title",
          "value": "NSPersistentStoreUbiquitousContentURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContentURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRemoveUbiquitousMetadataOption/title",
          "value": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRemoveUbiquitousMetadataOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentNameKey/title",
          "value": "NSPersistentStoreUbiquitousContentNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContentNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRebuildFromUbiquitousContentOption/title",
          "value": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRebuildFromUbiquitousContentOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordExtensionOption/title",
          "value": "NSExternalRecordExtensionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordExtensionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordExtensionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousPeerTokenOption/title",
          "value": "NSPersistentStoreUbiquitousPeerTokenOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousPeerTokenOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousPeerTokenOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContainerIdentifierKey/title",
          "value": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContainerIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsDirectoryOption/title",
          "value": "NSExternalRecordsDirectoryOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsDirectoryOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordsDirectoryOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsexternalrecordsfileformatoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsexternalrecordsfileformatoption"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
