{
  "abstract": [
    {
      "text": "A description object used to define which properties are fetched from Core Data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSFetchedPropertyDescription",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSFetchedPropertyDescription"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSFetchedPropertyDescription"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSFetchedPropertyDescription"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An example might be a iTunes playlist, if expressed as a property of a containing object. Songs don’t belong to a particular playlist, especially in the case that they’re on a remote server. The playlist may remain even after the songs have been deleted, or the remote server has become inaccessible. Note, however, that unlike a playlist a fetched property is static—it does not dynamically update itself as objects in the destination entity change.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The effect of a fetched property is similar to executing a fetch request yourself and placing the results in a transient attribute, although with the framework managing the details. In particular, a fetched property is not fetched until it is requested, and the results are then cached until the object is turned into a fault. You use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refresh(_:mergeChanges:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (",
              "type": "text"
            },
            {
              "code": "NSManagedObjectContext",
              "type": "codeVoice"
            },
            {
              "text": ") to manually refresh the properties—this causes the fetch request associated with this property to be executed again when the object fault is next fired.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Unlike other relationships, which are all sets, fetched properties are represented by an ordered ",
              "type": "text"
            },
            {
              "code": "NSArray",
              "type": "codeVoice"
            },
            {
              "text": " object just as if you executed the fetch request yourself. The fetch request associated with the property can have a sort ordering. The value for a fetched property of a managed object does not support ",
              "type": "text"
            },
            {
              "code": "mutableArrayValueForKey:",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Fetch-Request-Variables",
          "level": 3,
          "text": "Fetch Request Variables",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Fetch requests set on an fetched property have 2 special variable bindings you can use: ",
              "type": "text"
            },
            {
              "code": "$FETCH_SOURCE",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "$FETCHED_PROPERTY",
              "type": "codeVoice"
            },
            {
              "text": ". The source refers to the specific managed object that has this property; the property refers to the ",
              "type": "text"
            },
            {
              "code": "NSFetchedPropertyDescription",
              "type": "codeVoice"
            },
            {
              "text": " object itself (which may have a user info associated with it that you want to use).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Editing-Fetched-Property-Descriptions",
          "level": 3,
          "text": "Editing Fetched Property Descriptions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Fetched Property descriptions are editable until they are used by an object graph manager. This allows you to create or modify them dynamically. However, once a description is used (when the managed object model to which it belongs is associated with a persistent store coordinator), it ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "must not",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " (indeed cannot) be changed. This is enforced at runtime: any attempt to mutate a model or any of its subjects after the model is associated with a persistent store coordinator causes an exception to be thrown. If you need to modify a model that is in use, create a copy, modify the copy, and then discard the objects with the old model.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription": {
      "abstract": [
        {
          "text": "An object that describes an expression to include with a fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExpressionDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExpressionDescription"
        }
      ],
      "role": "symbol",
      "title": "NSExpressionDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsexpressiondescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/affectedStores": {
      "abstract": [
        {
          "text": "An array of persistent stores specified for the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "affectedStores"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/affectedStores",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "affectedStores"
        }
      ],
      "role": "symbol",
      "title": "affectedStores",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/affectedstores"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchBatchSize": {
      "abstract": [
        {
          "text": "The batch size of the objects specified in the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchBatchSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchBatchSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchBatchSize"
        }
      ],
      "role": "symbol",
      "title": "fetchBatchSize",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/fetchbatchsize"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchLimit": {
      "abstract": [
        {
          "text": "The fetch limit of the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchLimit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchLimit"
        }
      ],
      "role": "symbol",
      "title": "fetchLimit",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/fetchlimit"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchOffset": {
      "abstract": [
        {
          "text": "The fetch offset of the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchOffset"
        }
      ],
      "role": "symbol",
      "title": "fetchOffset",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/fetchoffset"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/predicate": {
      "abstract": [
        {
          "text": "The predicate of the fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "predicate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPredicate",
          "text": "NSPredicate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/predicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "predicate"
        }
      ],
      "role": "symbol",
      "title": "predicate",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequest/predicate"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestExpression": {
      "abstract": [
        {
          "text": "An expression that evaluates the result of a fetch request on a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchRequestExpression"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestExpression",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchRequestExpression"
        }
      ],
      "role": "symbol",
      "title": "NSFetchRequestExpression",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchrequestexpression"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription": {
      "abstract": [
        {
          "text": "A description object used to define which properties are fetched from Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFetchedPropertyDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSFetchedPropertyDescription"
        }
      ],
      "role": "symbol",
      "title": "NSFetchedPropertyDescription",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchedpropertydescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription/fetchRequest": {
      "abstract": [
        {
          "text": "The fetch request of the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
          "text": "NSFetchRequestResult"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription/fetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchRequest"
        }
      ],
      "role": "symbol",
      "title": "fetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nsfetchedpropertydescription/fetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refresh(_:mergeChanges:)": {
      "abstract": [
        {
          "text": "Updates the persistent properties of a managed object to use the latest values from the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "refresh"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "mergeChanges"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/refresh(_:mergeChanges:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "refreshObject:mergeChanges:"
        }
      ],
      "role": "symbol",
      "title": "refresh(_:mergeChanges:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/refresh(_:mergechanges:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription": {
      "abstract": [
        {
          "text": "A description of a single property belonging to an entity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPropertyDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPropertyDescription"
        }
      ],
      "role": "symbol",
      "title": "NSPropertyDescription",
      "type": "topic",
      "url": "/documentation/coredata/nspropertydescription"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-Fetch-Constraints",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/predicate",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchLimit",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchOffset",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchBatchSize",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/affectedStores",
        "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestExpression",
        "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription"
      ],
      "title": "Specifying Fetch Constraints"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-and-setting-the-fetch-request",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription/fetchRequest"
      ],
      "title": "Getting and setting the fetch request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSFetchedPropertyDescription"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-and-setting-the-fetch-request",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSFetchedPropertyDescription/fetchRequest"
              ],
              "title": "Getting and setting the fetch request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-Fetch-Constraints",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/predicate",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchLimit",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchOffset",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/fetchBatchSize",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequest/affectedStores",
                "doc://com.apple.coredata/documentation/CoreData/NSFetchRequestExpression",
                "doc://com.apple.coredata/documentation/CoreData/NSExpressionDescription"
              ],
              "title": "Specifying Fetch Constraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSFetchedPropertyDescription"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPropertyDescription",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPropertyDescription",
                    "text": "NSPropertyDescription"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1refresh(_:mergeChanges:)/title",
          "value": "refreshObject:mergeChanges:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1refresh(_:mergeChanges:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "refreshObject:mergeChanges:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestExpression/title",
          "value": "NSFetchRequestExpression"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestExpression/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequestExpression/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchRequestExpression"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchOffset/title",
          "value": "fetchOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchBatchSize/title",
          "value": "fetchBatchSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchBatchSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchBatchSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchLimit/title",
          "value": "fetchLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1fetchLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1affectedStores/title",
          "value": "affectedStores"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1affectedStores/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "affectedStores"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1predicate/title",
          "value": "predicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchRequest~1predicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "predicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/title",
          "value": "NSExpressionDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExpressionDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExpressionDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExpressionDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription~1fetchRequest/title",
          "value": "fetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription~1fetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/title",
          "value": "NSFetchedPropertyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSFetchedPropertyDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSFetchedPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/title",
          "value": "NSPropertyDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPropertyDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPropertyDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsfetchedpropertydescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsfetchedpropertydescription"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
