{
  "abstract": [
    {
      "text": "An abstract superclass defining the API through which Core Data communicates with a store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSIncrementalStore",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSIncrementalStore"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSIncrementalStore"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSIncrementalStore"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSIncrementalStore"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use this interface to create persistent stores that load and save data incrementally, allowing for the management of large and/or shared datasets.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Subclassing-Notes",
          "level": 3,
          "text": "Subclassing Notes",
          "type": "heading"
        },
        {
          "anchor": "Methods-to-Override",
          "level": 4,
          "text": "Methods to Override",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a subclass of ",
              "type": "text"
            },
            {
              "code": "NSIncrementalStore",
              "type": "codeVoice"
            },
            {
              "text": ", you ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "must",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " override the following methods to provide behavior appropriate for your store:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/loadMetadata()",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/execute(_:with:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValuesForObject(with:with:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValue(forRelationship:forObjectWith:with:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/obtainPermanentIDs(for:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can also optionally override the following methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/identifierForNewStore(at:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidRegisterObjects(with:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidUnregisterObjects(with:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "There is no need to override the methods that you must otherwise override for a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Methods-that-Should-Not-Be-Overridden",
          "level": 4,
          "text": "Methods that Should Not Be Overridden",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a subclass of ",
              "type": "text"
            },
            {
              "code": "NSIncrementalStore",
              "type": "codeVoice"
            },
            {
              "text": ", you should not override the following methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newObjectID(for:referenceObject:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/referenceObject(for:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAtomicStore": {
      "abstract": [
        {
          "text": "An abstract superclass that you subclass to create a Core Data atomic store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAtomicStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAtomicStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAtomicStore"
        }
      ],
      "role": "symbol",
      "title": "NSAtomicStore",
      "type": "topic",
      "url": "/documentation/coredata/nsatomicstore"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAtomicStoreCacheNode": {
      "abstract": [
        {
          "text": "A concrete class that you use to represent basic nodes in a Core Data atomic store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAtomicStoreCacheNode"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAtomicStoreCacheNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAtomicStoreCacheNode"
        }
      ],
      "role": "symbol",
      "title": "NSAtomicStoreCacheNode",
      "type": "topic",
      "url": "/documentation/coredata/nsatomicstorecachenode"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore": {
      "abstract": [
        {
          "text": "An abstract superclass defining the API through which Core Data communicates with a store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIncrementalStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIncrementalStore"
        }
      ],
      "role": "symbol",
      "title": "NSIncrementalStore",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/execute(_:with:)": {
      "abstract": [
        {
          "text": "Returns a value as appropriate for the given request, or nil if the request cannot be completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "execute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreRequest",
          "text": "NSPersistentStoreRequest"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/execute(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "executeRequest:withContext:error:"
        }
      ],
      "role": "symbol",
      "title": "execute(_:with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/execute(_:with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/identifierForNewStore(at:)": {
      "abstract": [
        {
          "text": "Returns the identifier for the store at a given URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierForNewStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/identifierForNewStore(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifierForNewStoreAtURL:"
        }
      ],
      "role": "symbol",
      "title": "identifierForNewStore(at:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/identifierfornewstore(at:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/loadMetadata()": {
      "abstract": [
        {
          "text": "Loads the metadata for the store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadMetadata"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/loadMetadata()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadMetadata:"
        }
      ],
      "role": "symbol",
      "title": "loadMetadata()",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/loadmetadata()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidRegisterObjects(with:)": {
      "abstract": [
        {
          "text": "Indicates that objects identified by a given array of object IDs are in use in a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedObjectContextDidRegisterObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidRegisterObjects(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectContextDidRegisterObjectsWithIDs:"
        }
      ],
      "role": "symbol",
      "title": "managedObjectContextDidRegisterObjects(with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/managedobjectcontextdidregisterobjects(with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidUnregisterObjects(with:)": {
      "abstract": [
        {
          "text": "Indicates that objects identified by a given array of object IDs are no longer being used by a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedObjectContextDidUnregisterObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidUnregisterObjects(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectContextDidUnregisterObjectsWithIDs:"
        }
      ],
      "role": "symbol",
      "title": "managedObjectContextDidUnregisterObjects(with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/managedobjectcontextdidunregisterobjects(with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newObjectID(for:referenceObject:)": {
      "abstract": [
        {
          "text": "Returns a new object ID that uses given data as the key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newObjectID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEntityDescription",
          "text": "NSEntityDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "referenceObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newObjectID(for:referenceObject:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newObjectIDForEntity:referenceObject:"
        }
      ],
      "role": "symbol",
      "title": "newObjectID(for:referenceObject:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/newobjectid(for:referenceobject:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValue(forRelationship:forObjectWith:with:)": {
      "abstract": [
        {
          "text": "Returns the relationship for the given relationship of the object with a given object ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forRelationship"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSRelationshipDescription",
          "text": "NSRelationshipDescription"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forObjectWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValue(forRelationship:forObjectWith:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newValueForRelationship:forObjectWithID:withContext:error:"
        }
      ],
      "role": "symbol",
      "title": "newValue(forRelationship:forObjectWith:with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/newvalue(forrelationship:forobjectwith:with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValuesForObject(with:with:)": {
      "abstract": [
        {
          "text": "Returns an incremental store node encapsulating the persistent external values of the object with a given object ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newValuesForObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSIncrementalStoreNode",
          "text": "NSIncrementalStoreNode"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValuesForObject(with:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newValuesForObjectWithID:withContext:error:"
        }
      ],
      "role": "symbol",
      "title": "newValuesForObject(with:with:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/newvaluesforobject(with:with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/obtainPermanentIDs(for:)": {
      "abstract": [
        {
          "text": "Returns an array containing the object IDs for a given array of newly-inserted objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "obtainPermanentIDs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObject",
          "text": "NSManagedObject"
        },
        {
          "kind": "text",
          "text": "]) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/obtainPermanentIDs(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "obtainPermanentIDsForObjects:error:"
        }
      ],
      "role": "symbol",
      "title": "obtainPermanentIDs(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/obtainpermanentids(for:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/referenceObject(for:)": {
      "abstract": [
        {
          "text": "Returns the reference data used to construct a given object ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectID",
          "text": "NSManagedObjectID"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/referenceObject(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referenceObjectForObjectID:"
        }
      ],
      "role": "symbol",
      "title": "referenceObject(for:)",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstore/referenceobject(for:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStoreNode": {
      "abstract": [
        {
          "text": "A concrete class used to represent basic nodes in a Core Data incremental store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSIncrementalStoreNode"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStoreNode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSIncrementalStoreNode"
        }
      ],
      "role": "symbol",
      "title": "NSIncrementalStoreNode",
      "type": "topic",
      "url": "/documentation/coredata/nsincrementalstorenode"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore": {
      "abstract": [
        {
          "text": "The abstract base class for all Core Data persistent stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStore"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStore",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstore"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreAsynchronousResult": {
      "abstract": [
        {
          "text": "A concrete class used to represent the results of an asynchronous request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreAsynchronousResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreAsynchronousResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreAsynchronousResult"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreAsynchronousResult",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreasynchronousresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription": {
      "abstract": [
        {
          "text": "A description object used to create and load a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDescription"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDescription"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreDescription",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoredescription"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest": {
      "abstract": [
        {
          "text": "Criteria used to retrieve data from or save data to a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorerequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreResult": {
      "abstract": [
        {
          "text": "The abstract base class for results returned from a persistent store coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreResult"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreResult",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSaveChangesRequest": {
      "abstract": [
        {
          "text": "An encapsulation of a collection of changes to be made by an object store in response to a save operation on a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSaveChangesRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSaveChangesRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSaveChangesRequest"
        }
      ],
      "role": "symbol",
      "title": "NSSaveChangesRequest",
      "type": "topic",
      "url": "/documentation/coredata/nssavechangesrequest"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Store-Coordination",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreResult",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreAsynchronousResult",
        "doc://com.apple.coredata/documentation/CoreData/NSSaveChangesRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSAtomicStore",
        "doc://com.apple.coredata/documentation/CoreData/NSAtomicStoreCacheNode",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStoreNode"
      ],
      "title": "Store Coordination"
    }
  ],
  "topicSections": [
    {
      "anchor": "Manipulating-Managed-Objects",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/execute(_:with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValuesForObject(with:with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValue(forRelationship:forObjectWith:with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/obtainPermanentIDs(for:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newObjectID(for:referenceObject:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/referenceObject(for:)"
      ],
      "title": "Manipulating Managed Objects"
    },
    {
      "anchor": "Responding-to-Context-Changes",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidRegisterObjects(with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidUnregisterObjects(with:)"
      ],
      "title": "Responding to Context Changes"
    },
    {
      "anchor": "Accessing-Metadata",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/identifierForNewStore(at:)",
        "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/loadMetadata()"
      ],
      "title": "Accessing Metadata"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSIncrementalStore"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Manipulating-Managed-Objects",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/execute(_:with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValuesForObject(with:with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newValue(forRelationship:forObjectWith:with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/obtainPermanentIDs(for:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/newObjectID(for:referenceObject:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/referenceObject(for:)"
              ],
              "title": "Manipulating Managed Objects"
            },
            {
              "anchor": "Responding-to-Context-Changes",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidRegisterObjects(with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/managedObjectContextDidUnregisterObjects(with:)"
              ],
              "title": "Responding to Context Changes"
            },
            {
              "anchor": "Accessing-Metadata",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/identifierForNewStore(at:)",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStore/loadMetadata()"
              ],
              "title": "Accessing Metadata"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Store-Coordination",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDescription",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreResult",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreAsynchronousResult",
                "doc://com.apple.coredata/documentation/CoreData/NSSaveChangesRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSAtomicStore",
                "doc://com.apple.coredata/documentation/CoreData/NSAtomicStoreCacheNode",
                "doc://com.apple.coredata/documentation/CoreData/NSIncrementalStoreNode"
              ],
              "title": "Store Coordination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSIncrementalStore"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStore",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPersistentStore",
                    "text": "NSPersistentStore"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/title",
          "value": "NSPersistentStoreDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreDescription/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreResult/title",
          "value": "NSPersistentStoreResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1managedObjectContextDidRegisterObjects(with:)/title",
          "value": "managedObjectContextDidRegisterObjectsWithIDs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1managedObjectContextDidRegisterObjects(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "managedObjectContextDidRegisterObjectsWithIDs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1identifierForNewStore(at:)/title",
          "value": "identifierForNewStoreAtURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1identifierForNewStore(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "identifierForNewStoreAtURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newValuesForObject(with:with:)/title",
          "value": "newValuesForObjectWithID:withContext:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newValuesForObject(with:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newValuesForObjectWithID:withContext:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStore/title",
          "value": "NSAtomicStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAtomicStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAtomicStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1loadMetadata()/title",
          "value": "loadMetadata:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1loadMetadata()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadMetadata:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/title",
          "value": "NSPersistentStoreRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1managedObjectContextDidUnregisterObjects(with:)/title",
          "value": "managedObjectContextDidUnregisterObjectsWithIDs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1managedObjectContextDidUnregisterObjects(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "managedObjectContextDidUnregisterObjectsWithIDs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1obtainPermanentIDs(for:)/title",
          "value": "obtainPermanentIDsForObjects:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1obtainPermanentIDs(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "obtainPermanentIDsForObjects:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStoreCacheNode/title",
          "value": "NSAtomicStoreCacheNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStoreCacheNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAtomicStoreCacheNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAtomicStoreCacheNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAtomicStoreCacheNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore/title",
          "value": "NSIncrementalStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1execute(_:with:)/title",
          "value": "executeRequest:withContext:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1execute(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "executeRequest:withContext:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSaveChangesRequest/title",
          "value": "NSSaveChangesRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSaveChangesRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveChangesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSaveChangesRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSaveChangesRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreAsynchronousResult/title",
          "value": "NSPersistentStoreAsynchronousResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreAsynchronousResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreAsynchronousResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreAsynchronousResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreAsynchronousResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStoreNode/title",
          "value": "NSIncrementalStoreNode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStoreNode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStoreNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStoreNode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSIncrementalStoreNode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1referenceObject(for:)/title",
          "value": "referenceObjectForObjectID:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1referenceObject(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "referenceObjectForObjectID:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newObjectID(for:referenceObject:)/title",
          "value": "newObjectIDForEntity:referenceObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newObjectID(for:referenceObject:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newObjectIDForEntity:referenceObject:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newValue(forRelationship:forObjectWith:with:)/title",
          "value": "newValueForRelationship:forObjectWithID:withContext:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSIncrementalStore~1newValue(forRelationship:forObjectWith:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newValueForRelationship:forObjectWithID:withContext:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStore/title",
          "value": "NSPersistentStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStore/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsincrementalstore"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsincrementalstore"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
