{
  "abstract": [
    {
      "text": "A key for the set of objects that were inserted into the context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSInsertedObjectsKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSInsertedObjectsKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSInsertedObjectsKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.4",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSInsertedObjectsKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSInsertedObjectsKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were marked for deletion during the previous event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDeletedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDeletedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSDeletedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsdeletedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were inserted into the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInsertedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInsertedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInsertedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinsertedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey": {
      "abstract": [
        {
          "text": "A key that specifies that all objects in the context have been invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInvalidatedAllObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvalidatedAllObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInvalidatedAllObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinvalidatedallobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were invalidated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInvalidatedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInvalidatedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSInvalidatedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsinvalidatedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey": {
      "abstract": [
        {
          "text": "Keys to access details in user info dictionaries of managed object context notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NotificationKey"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext.NotificationKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/notificationkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a context makes changes to its registered objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didChangeObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didchangeobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes merging changes from another notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMergeChangesObjectIDsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didMergeChangesObjectIDsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didmergechangesobjectidsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes saving changes to its managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSaveObjectIDsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didSaveObjectIDsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didsaveobjectidsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts after a context completes a save.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didSaveObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "didSaveObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/didsaveobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a context writes pending changes to disk.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willSaveObjectsNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV4Namea",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "willSaveObjectsNotification",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/willsaveobjectsnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were refreshed but were not dirtied in the scope of this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRefreshedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRefreshedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSRefreshedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsrefreshedobjectskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey": {
      "abstract": [
        {
          "text": "A key for the set of objects that were updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUpdatedObjectsKey"
        }
      ],
      "role": "symbol",
      "title": "NSUpdatedObjectsKey",
      "type": "topic",
      "url": "/documentation/coredata/nsupdatedobjectskey"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave": {
      "abstract": [
        {
          "text": "A notification that posts after a context finishes writing unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextDidSave"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextDidSave",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave": {
      "abstract": [
        {
          "text": "A notification that posts before a context writes unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextWillSave"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextWillSave",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid": {
      "abstract": [
        {
          "text": "A notification that posts when there are changes to context’s registered managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextObjectsDidChange"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagedObjectContextObjectsDidChange",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didChangeObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506884-nsmanagedobjectcontextobjectsdid",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506380-nsmanagedobjectcontextdidsave",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/willSaveObjectsNotification",
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1506816-nsmanagedobjectcontextwillsave",
        "doc://com.apple.coredata/documentation/CoreData/NSUpdatedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSDeletedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSRefreshedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSInvalidatedAllObjectsKey",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didMergeChangesObjectIDsNotification",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/didSaveObjectIDsNotification",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/NotificationKey"
      ],
      "title": "Managing notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.4",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSInsertedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSInsertedObjectsKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/title",
          "value": "NSInsertedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInsertedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInsertedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedObjectsKey/title",
          "value": "NSInvalidatedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvalidatedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedAllObjectsKey/title",
          "value": "NSInvalidatedAllObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInvalidatedAllObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInvalidatedAllObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeletedObjectsKey/title",
          "value": "NSDeletedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSDeletedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDeletedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/title",
          "value": "NSUpdatedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSUpdatedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUpdatedObjectsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRefreshedObjectsKey/title",
          "value": "NSRefreshedObjectsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRefreshedObjectsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRefreshedObjectsKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsinsertedobjectskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsinsertedobjectskey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
