{
  "abstract": [
    {
      "text": "Constant used to reference the query generation token.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextQueryGenerationKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSManagedObjectContextQueryGenerationKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSManagedObjectContextQueryGenerationKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSManagedObjectContextQueryGenerationKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSManagedObjectContextQueryGenerationKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSManagedObjectContextQueryGenerationKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/automaticallyMergesChangesFromParent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the context automatically merges changes saved to its persistent store coordinator or parent context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyMergesChangesFromParent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/automaticallyMergesChangesFromParent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyMergesChangesFromParent"
        }
      ],
      "role": "symbol",
      "title": "automaticallyMergesChangesFromParent",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/automaticallymergeschangesfromparent"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/concurrencyType-swift.property": {
      "abstract": [
        {
          "text": "The concurrency type for the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "concurrencyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSManagedObjectContextConcurrencyType",
          "text": "NSManagedObjectContextConcurrencyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/concurrencyType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "concurrencyType"
        }
      ],
      "role": "symbol",
      "title": "concurrencyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/concurrencytype-swift.property"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromContextDidSave:)": {
      "abstract": [
        {
          "text": "Merges the changes specified in a given notification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromContextDidSave"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation12NotificationV",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromContextDidSave:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeChangesFromContextDidSaveNotification:"
        }
      ],
      "role": "symbol",
      "title": "mergeChanges(fromContextDidSave:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/mergechanges(fromcontextdidsave:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromRemoteContextSave:into:)": {
      "abstract": [
        {
          "text": "Handles changes from other processes or from a serialized state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeChanges"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromRemoteContextSave"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "into"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromRemoteContextSave:into:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergeChangesFromRemoteContextSave:intoContexts:"
        }
      ],
      "role": "symbol",
      "title": "mergeChanges(fromRemoteContextSave:into:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/mergechanges(fromremotecontextsave:into:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergePolicy": {
      "abstract": [
        {
          "text": "The merge policy of the context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergePolicy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mergePolicy"
        }
      ],
      "role": "symbol",
      "title": "mergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/mergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/queryGenerationToken": {
      "abstract": [
        {
          "text": "Returns the token associated with the query generation currently in use by this context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "queryGenerationToken"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSQueryGenerationToken",
          "text": "NSQueryGenerationToken"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/queryGenerationToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "queryGenerationToken"
        }
      ],
      "role": "symbol",
      "title": "queryGenerationToken",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/querygenerationtoken"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/setQueryGenerationFrom(_:)": {
      "abstract": [
        {
          "text": "Sets the query generation this context should use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setQueryGenerationFrom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSQueryGenerationToken",
          "text": "NSQueryGenerationToken"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/setQueryGenerationFrom(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setQueryGenerationFromToken:error:"
        }
      ],
      "role": "symbol",
      "title": "setQueryGenerationFrom(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/setquerygenerationfrom(_:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/transactionAuthor": {
      "abstract": [
        {
          "text": "The author for the context that is used as an identifier in persistent history transactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transactionAuthor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/transactionAuthor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "transactionAuthor"
        }
      ],
      "role": "symbol",
      "title": "transactionAuthor",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext/transactionauthor"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextQueryGenerationKey": {
      "abstract": [
        {
          "text": "Constant used to reference the query generation token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextQueryGenerationKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextQueryGenerationKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextQueryGenerationKey"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContextQueryGenerationKey",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontextquerygenerationkey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-concurrency",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromRemoteContextSave:into:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/automaticallyMergesChangesFromParent",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/concurrencyType-swift.property",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/queryGenerationToken",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/transactionAuthor",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromContextDidSave:)",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/setQueryGenerationFrom(_:)"
      ],
      "title": "Managing concurrency"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSManagedObjectContextQueryGenerationKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContextQueryGenerationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-concurrency",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromRemoteContextSave:into:)",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/automaticallyMergesChangesFromParent",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/concurrencyType-swift.property",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/queryGenerationToken",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/transactionAuthor",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/mergeChanges(fromContextDidSave:)",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext/setQueryGenerationFrom(_:)"
              ],
              "title": "Managing concurrency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSManagedObjectContextQueryGenerationKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1queryGenerationToken/title",
          "value": "queryGenerationToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1queryGenerationToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "queryGenerationToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergePolicy/title",
          "value": "mergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContextQueryGenerationKey/title",
          "value": "NSManagedObjectContextQueryGenerationKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContextQueryGenerationKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContextQueryGenerationKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1setQueryGenerationFrom(_:)/title",
          "value": "setQueryGenerationFromToken:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1setQueryGenerationFrom(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setQueryGenerationFromToken:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergeChanges(fromContextDidSave:)/title",
          "value": "mergeChangesFromContextDidSaveNotification:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergeChanges(fromContextDidSave:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "mergeChangesFromContextDidSaveNotification:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1concurrencyType-swift.property/title",
          "value": "concurrencyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1concurrencyType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "concurrencyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1transactionAuthor/title",
          "value": "transactionAuthor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1transactionAuthor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "transactionAuthor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergeChanges(fromRemoteContextSave:into:)/title",
          "value": "mergeChangesFromRemoteContextSave:intoContexts:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1mergeChanges(fromRemoteContextSave:into:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "mergeChangesFromRemoteContextSave:intoContexts:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1automaticallyMergesChangesFromParent/title",
          "value": "automaticallyMergesChangesFromParent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext~1automaticallyMergesChangesFromParent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyMergesChangesFromParent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmanagedobjectcontextquerygenerationkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsmanagedobjectcontextquerygenerationkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
