{
  "abstract": [
    {
      "text": "Constants that define merge policy types.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSMergePolicyType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSMergePolicyType"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSMergePolicyType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSMergePolicyType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSErrorMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nserrormergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyObjectTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertyobjecttrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSMergeByPropertyStoreTrumpMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsmergebypropertystoretrumpmergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType": {
      "abstract": [
        {
          "text": "Constants that define merge policy types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/errorMergePolicyType": {
      "abstract": [
        {
          "text": "The default merge policy for all managed object contexts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "errorMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/errorMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSErrorMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType.errorMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/errormergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/init(rawvalue:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyObjectTrumpMergePolicyType": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies in-memory changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyObjectTrumpMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyObjectTrumpMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyObjectTrumpMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType.mergeByPropertyObjectTrumpMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/mergebypropertyobjecttrumpmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyStoreTrumpMergePolicyType": {
      "abstract": [
        {
          "text": "A property-based merge policy that applies external changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mergeByPropertyStoreTrumpMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyStoreTrumpMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMergeByPropertyStoreTrumpMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType.mergeByPropertyStoreTrumpMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/mergebypropertystoretrumpmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/overwriteMergePolicyType": {
      "abstract": [
        {
          "text": "A merge policy type that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overwriteMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/overwriteMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType.overwriteMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/overwritemergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/rollbackMergePolicyType": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rollbackMergePolicyType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/rollbackMergePolicyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicyType"
        }
      ],
      "role": "symbol",
      "title": "NSMergePolicyType.rollbackMergePolicyType",
      "type": "topic",
      "url": "/documentation/coredata/nsmergepolicytype/rollbackmergepolicytype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that overwrites the entire stored object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSOverwriteMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSOverwriteMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsoverwritemergepolicy"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy": {
      "abstract": [
        {
          "text": "A merge policy that discards unsaved changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        },
        {
          "kind": "text",
          "text": ": AnyObject"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRollbackMergePolicy"
        }
      ],
      "role": "symbol",
      "title": "NSRollbackMergePolicy",
      "type": "topic",
      "url": "/documentation/coredata/nsrollbackmergepolicy"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Policies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
        "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy"
      ],
      "title": "Policies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Policies",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/errorMergePolicyType",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyStoreTrumpMergePolicyType",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyObjectTrumpMergePolicyType",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/overwriteMergePolicyType",
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/rollbackMergePolicyType"
      ],
      "title": "Policies"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Policies",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/errorMergePolicyType",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyStoreTrumpMergePolicyType",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/mergeByPropertyObjectTrumpMergePolicyType",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/overwriteMergePolicyType",
                "doc://com.apple.coredata/documentation/CoreData/NSMergePolicyType/rollbackMergePolicyType"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Policies",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSErrorMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyStoreTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSMergeByPropertyObjectTrumpMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSOverwriteMergePolicy",
                "doc://com.apple.coredata/documentation/CoreData/NSRollbackMergePolicy"
              ],
              "title": "Policies"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSMergePolicyType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/title",
          "value": "NSMergeByPropertyObjectTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyObjectTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyObjectTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/title",
          "value": "NSRollbackMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRollbackMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRollbackMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/title",
          "value": "NSMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1mergeByPropertyStoreTrumpMergePolicyType/title",
          "value": "NSMergeByPropertyStoreTrumpMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1mergeByPropertyStoreTrumpMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyStoreTrumpMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/title",
          "value": "NSErrorMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSErrorMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/title",
          "value": "NSMergeByPropertyStoreTrumpMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergeByPropertyStoreTrumpMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyStoreTrumpMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1mergeByPropertyObjectTrumpMergePolicyType/title",
          "value": "NSMergeByPropertyObjectTrumpMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1mergeByPropertyObjectTrumpMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMergeByPropertyObjectTrumpMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1overwriteMergePolicyType/title",
          "value": "NSOverwriteMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1overwriteMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOverwriteMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1errorMergePolicyType/title",
          "value": "NSErrorMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1errorMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSErrorMergePolicyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/title",
          "value": "NSOverwriteMergePolicy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSOverwriteMergePolicy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSOverwriteMergePolicy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1rollbackMergePolicyType/title",
          "value": "NSRollbackMergePolicyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMergePolicyType~1rollbackMergePolicyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRollbackMergePolicyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsmergepolicytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsmergepolicytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
