{
  "abstract": [
    {
      "text": "A container that encapsulates the Core Data stack in your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPersistentContainer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPersistentContainer"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPersistentContainer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSPersistentContainer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPersistentContainer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
        "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack-manually",
        "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
        "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "NSPersistentContainer simplifies the creation and management of the Core Data stack by handling the creation of the managed object model (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), persistent store coordinator (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "), and the managed object context (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext": {
      "abstract": [
        {
          "text": "An object space to manipulate and track changes to managed objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContext"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContext",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontext"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel": {
      "abstract": [
        {
          "text": "A programmatic representation of the ",
          "type": "text"
        },
        {
          "code": ".xcdatamodeld",
          "type": "codeVoice"
        },
        {
          "text": " file describing your objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectModel"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectModel",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer": {
      "abstract": [
        {
          "text": "A container that encapsulates the Core Data stack in your app, and mirrors select persistent stores to a CloudKit private database.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentCloudKitContainer"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentCloudKitContainer",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcloudkitcontainer"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer": {
      "abstract": [
        {
          "text": "A container that encapsulates the Core Data stack in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentContainer"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentContainer"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentContainer",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL()": {
      "abstract": [
        {
          "text": "Returns the location of the directory that contains the persistent stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultDirectoryURL"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultDirectoryURL"
        }
      ],
      "role": "symbol",
      "title": "defaultDirectoryURL()",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/defaultdirectoryurl()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL-swift.type.property": {
      "abstract": [
        {
          "text": "The location of the directory that contains the persistent stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultDirectoryURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL-swift.type.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultDirectoryURL",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/defaultdirectoryurl-swift.type.property"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:)": {
      "abstract": [
        {
          "text": "Creates a container with the specified name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:"
        }
      ],
      "role": "symbol",
      "title": "init(name:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/init(name:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:managedObjectModel:)": {
      "abstract": [
        {
          "text": "Create a container with the specified name and managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "managedObjectModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:managedObjectModel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:managedObjectModel:"
        }
      ],
      "role": "symbol",
      "title": "init(name:managedObjectModel:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/init(name:managedobjectmodel:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/loadPersistentStores(completionHandler:)": {
      "abstract": [
        {
          "text": "Loads the persistent stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadPersistentStores"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreDescription",
          "text": "NSPersistentStoreDescription"
        },
        {
          "kind": "text",
          "text": ", (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/loadPersistentStores(completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadPersistentStoresWithCompletionHandler:"
        }
      ],
      "role": "symbol",
      "title": "loadPersistentStores(completionHandler:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/loadpersistentstores(completionhandler:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/managedObjectModel": {
      "abstract": [
        {
          "text": "The container’s managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedObjectModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/managedObjectModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectModel"
        }
      ],
      "role": "symbol",
      "title": "managedObjectModel",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/managedobjectmodel"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/name": {
      "abstract": [
        {
          "text": "The container’s name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/name"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/newBackgroundContext()": {
      "abstract": [
        {
          "text": "Returns a new managed object context that executes on a private queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newBackgroundContext"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/newBackgroundContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "newBackgroundContext"
        }
      ],
      "role": "symbol",
      "title": "newBackgroundContext()",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/newbackgroundcontext()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-25nok": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performBackgroundTask"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ">(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "rethrows"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "T"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-25nok",
      "kind": "symbol",
      "role": "symbol",
      "title": "performBackgroundTask(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/performbackgroundtask(_:)-25nok"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-39sch": {
      "abstract": [
        {
          "text": "Executes a closure on a private queue using an ephemeral managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performBackgroundTask"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-39sch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performBackgroundTask:"
        }
      ],
      "role": "symbol",
      "title": "performBackgroundTask(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/performbackgroundtask(_:)-39sch"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:": {
      "abstract": [
        {
          "text": "Initializes a new persistent container using the provided name for the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "persistentContainerWithName:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentContainerWithName:"
        }
      ],
      "role": "symbol",
      "title": "persistentContainerWithName:",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/persistentcontainerwithname:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:managedObjectModel:": {
      "abstract": [
        {
          "text": "Initializes a new persistent container using the provided name and managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "persistentContainerWithName:managedObjectModel:"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:managedObjectModel:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentContainerWithName:managedObjectModel:"
        }
      ],
      "role": "symbol",
      "title": "persistentContainerWithName:managedObjectModel:",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/persistentcontainerwithname:managedobjectmodel:"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreCoordinator": {
      "abstract": [
        {
          "text": "The container’s persistent store coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreCoordinator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreCoordinator",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/persistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreDescriptions": {
      "abstract": [
        {
          "text": "The descriptions of the container’s persistent stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreDescriptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStoreDescription",
          "text": "NSPersistentStoreDescription"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreDescriptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreDescriptions"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreDescriptions",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/persistentstoredescriptions"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/viewContext": {
      "abstract": [
        {
          "text": "The main queue’s managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/viewContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewContext"
        }
      ],
      "role": "symbol",
      "title": "viewContext",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentcontainer/viewcontext"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack": {
      "abstract": [
        {
          "text": "Set up the classes that manage and persist your app’s objects.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack",
      "kind": "article",
      "role": "article",
      "title": "Setting up a Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-a-core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack-manually": {
      "abstract": [
        {
          "text": "Create the individual components that Core Data requires manually, to support earlier versions of Apple operating systems.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-a-core-data-stack-manually",
      "kind": "article",
      "role": "article",
      "title": "Setting up a Core Data stack manually",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-a-core-data-stack-manually"
    },
    "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit": {
      "abstract": [
        {
          "text": "Set up the classes and capabilities that sync your store to CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/setting-up-core-data-with-cloudkit",
      "kind": "article",
      "role": "article",
      "title": "Setting Up Core Data with CloudKit",
      "type": "topic",
      "url": "/documentation/coredata/setting-up-core-data-with-cloudkit"
    },
    "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background": {
      "abstract": [
        {
          "text": "Use Core Data in both a single-threaded and multithreaded app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/using-core-data-in-the-background",
      "kind": "article",
      "role": "article",
      "title": "Using Core Data in the background",
      "type": "topic",
      "url": "/documentation/coredata/using-core-data-in-the-background"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-a-Container",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:managedObjectModel:)"
      ],
      "title": "Creating a Container"
    },
    {
      "anchor": "Getting-the-Containers-Configuration",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/managedObjectModel",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/name",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreCoordinator"
      ],
      "title": "Getting the Container’s Configuration"
    },
    {
      "anchor": "Accessing-the-Default-Directory",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL-swift.type.property",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL()"
      ],
      "title": "Accessing the Default Directory"
    },
    {
      "anchor": "Managing-Persistent-Stores",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreDescriptions",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/loadPersistentStores(completionHandler:)"
      ],
      "title": "Managing Persistent Stores"
    },
    {
      "anchor": "Acquiring-Contexts",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/newBackgroundContext()",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/viewContext"
      ],
      "title": "Acquiring Contexts"
    },
    {
      "anchor": "Performing-Background-Tasks",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-39sch",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-25nok"
      ],
      "title": "Performing Background Tasks"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPersistentContainer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Container",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/init(name:managedObjectModel:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentContainerWithName:managedObjectModel:"
              ],
              "title": "Creating a Container"
            },
            {
              "anchor": "Getting-the-Containers-Configuration",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/managedObjectModel",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/name",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreCoordinator"
              ],
              "title": "Getting the Container’s Configuration"
            },
            {
              "anchor": "Accessing-the-Default-Directory",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/defaultDirectoryURL()"
              ],
              "title": "Accessing the Default Directory"
            },
            {
              "anchor": "Managing-Persistent-Stores",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/persistentStoreDescriptions",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/loadPersistentStores(completionHandler:)"
              ],
              "title": "Managing Persistent Stores"
            },
            {
              "anchor": "Acquiring-Contexts",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/newBackgroundContext()",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/viewContext"
              ],
              "title": "Acquiring Contexts"
            },
            {
              "anchor": "Performing-Background-Tasks",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentContainer/performBackgroundTask(_:)-39sch"
              ],
              "title": "Performing Background Tasks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentCloudKitContainer"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPersistentContainer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1persistentStoreDescriptions/title",
          "value": "persistentStoreDescriptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1persistentStoreDescriptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistentStoreDescriptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1init(name:managedObjectModel:)/title",
          "value": "initWithName:managedObjectModel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1init(name:managedObjectModel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:managedObjectModel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1init(name:)/title",
          "value": "initWithName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1init(name:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/title",
          "value": "NSManagedObjectModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1viewContext/title",
          "value": "viewContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1viewContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "viewContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1loadPersistentStores(completionHandler:)/title",
          "value": "loadPersistentStoresWithCompletionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1loadPersistentStores(completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadPersistentStoresWithCompletionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer/title",
          "value": "NSPersistentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1newBackgroundContext()/title",
          "value": "newBackgroundContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1newBackgroundContext()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "newBackgroundContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1performBackgroundTask(_:)-39sch/title",
          "value": "performBackgroundTask:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1performBackgroundTask(_:)-39sch/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performBackgroundTask:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1persistentStoreCoordinator/title",
          "value": "persistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1persistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/title",
          "value": "NSPersistentCloudKitContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentCloudKitContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentCloudKitContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1defaultDirectoryURL()/title",
          "value": "defaultDirectoryURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1defaultDirectoryURL()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultDirectoryURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/title",
          "value": "NSManagedObjectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1managedObjectModel/title",
          "value": "managedObjectModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentContainer~1managedObjectModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "managedObjectModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentcontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentcontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
