{
  "abstract": [
    {
      "text": "A request to fetch or purge persistent history.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSPersistentHistoryChangeRequest",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPersistentHistoryChangeRequest"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPersistentHistoryChangeRequest"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSPersistentHistoryChangeRequest"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes"
      ]
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest": {
      "abstract": [
        {
          "text": "A request to fetch or purge persistent history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryChangeRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-5kghb": {
      "abstract": [
        {
          "text": "Purges history older than that defined by a given token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "before"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentHistoryToken",
          "text": "NSPersistentHistoryToken"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-5kghb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteHistoryBeforeToken:"
        }
      ],
      "role": "symbol",
      "title": "deleteHistory(before:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/deletehistory(before:)-5kghb"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-7t2th": {
      "abstract": [
        {
          "text": "Purges history older than a given date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "before"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-7t2th",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteHistoryBeforeDate:"
        }
      ],
      "role": "symbol",
      "title": "deleteHistory(before:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/deletehistory(before:)-7t2th"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-9l06p": {
      "abstract": [
        {
          "text": "Purges history older than a given transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deleteHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "before"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentHistoryTransaction",
          "text": "NSPersistentHistoryTransaction"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-9l06p",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deleteHistoryBeforeTransaction:"
        }
      ],
      "role": "symbol",
      "title": "deleteHistory(before:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/deletehistory(before:)-9l06p"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-3rmfm": {
      "abstract": [
        {
          "text": "Retrieves the request history after a given token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "after"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentHistoryToken",
          "text": "NSPersistentHistoryToken"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-3rmfm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchHistoryAfterToken:"
        }
      ],
      "role": "symbol",
      "title": "fetchHistory(after:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/fetchhistory(after:)-3rmfm"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-9cuj5": {
      "abstract": [
        {
          "text": "Retrieves history since a given transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "after"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentHistoryTransaction",
          "text": "NSPersistentHistoryTransaction"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-9cuj5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchHistoryAfterTransaction:"
        }
      ],
      "role": "symbol",
      "title": "fetchHistory(after:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/fetchhistory(after:)-9cuj5"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-qi5b": {
      "abstract": [
        {
          "text": "Retrieves history since a given date.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "after"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-qi5b",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchHistoryAfterDate:"
        }
      ],
      "role": "symbol",
      "title": "fetchHistory(after:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/fetchhistory(after:)-qi5b"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(withFetch:)": {
      "abstract": [
        {
          "text": "Retrieves history based on a fetch request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchHistory"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withFetch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
          "text": "NSFetchRequestResult"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(withFetch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchHistoryWithFetchRequest:"
        }
      ],
      "role": "symbol",
      "title": "fetchHistory(withFetch:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/fetchhistory(withfetch:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchRequest": {
      "abstract": [
        {
          "text": "The specified fetch request, when retrieving history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fetchRequest"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSFetchRequest",
          "text": "NSFetchRequest"
        },
        {
          "kind": "text",
          "text": "<any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSFetchRequestResult",
          "text": "NSFetchRequestResult"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fetchRequest"
        }
      ],
      "role": "symbol",
      "title": "fetchRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/fetchrequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/resultType": {
      "abstract": [
        {
          "text": "The type of result that this request returns.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSPersistentHistoryResultType",
          "text": "NSPersistentHistoryResultType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/resultType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultType"
        }
      ],
      "role": "symbol",
      "title": "resultType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/resulttype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/token": {
      "abstract": [
        {
          "text": "The specified token, when retrieving history defined by a token.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "token"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentHistoryToken",
          "text": "NSPersistentHistoryToken"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/token",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "token"
        }
      ],
      "role": "symbol",
      "title": "token",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest/token"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult": {
      "abstract": [
        {
          "text": "The result of a request to fetch persistent history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResult"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResult",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest": {
      "abstract": [
        {
          "text": "Criteria used to retrieve data from or save data to a persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRequest"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorerequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes": {
      "abstract": [
        {
          "text": "Filter store transactions for changes relevant to the current view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Consuming relevant store changes",
      "type": "topic",
      "url": "/documentation/coredata/consuming-relevant-store-changes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Requesting-History",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult"
      ],
      "title": "Requesting History"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-Request",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/resultType"
      ],
      "title": "Configuring the Request"
    },
    {
      "anchor": "Getting-the-Token",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/token"
      ],
      "title": "Getting the Token"
    },
    {
      "anchor": "Fetching-History",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-qi5b",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-3rmfm",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-9cuj5",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(withFetch:)"
      ],
      "title": "Fetching History"
    },
    {
      "anchor": "Purging-History",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-7t2th",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-5kghb",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-9l06p"
      ],
      "title": "Purging History"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPersistentHistoryChangeRequest"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-Request",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/resultType"
              ],
              "title": "Configuring the Request"
            },
            {
              "anchor": "Getting-the-Token",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/token"
              ],
              "title": "Getting the Token"
            },
            {
              "anchor": "Fetching-History",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-qi5b",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-3rmfm",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(after:)-9cuj5",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/fetchHistory(withFetch:)"
              ],
              "title": "Fetching History"
            },
            {
              "anchor": "Purging-History",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-7t2th",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-5kghb",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest/deleteHistory(before:)-9l06p"
              ],
              "title": "Purging History"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Requesting-History",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult"
              ],
              "title": "Requesting History"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPersistentHistoryChangeRequest"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRequest",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSPersistentStoreRequest",
                    "text": "NSPersistentStoreRequest"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(withFetch:)/title",
          "value": "fetchHistoryWithFetchRequest:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(withFetch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchHistoryWithFetchRequest:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-9l06p/title",
          "value": "deleteHistoryBeforeTransaction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-9l06p/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deleteHistoryBeforeTransaction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-9cuj5/title",
          "value": "fetchHistoryAfterTransaction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-9cuj5/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchHistoryAfterTransaction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-qi5b/title",
          "value": "fetchHistoryAfterDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-qi5b/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchHistoryAfterDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/title",
          "value": "NSPersistentHistoryResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/title",
          "value": "NSPersistentHistoryChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchRequest/title",
          "value": "fetchRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fetchRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1token/title",
          "value": "token"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1token/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "token"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/title",
          "value": "NSPersistentStoreRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-5kghb/title",
          "value": "deleteHistoryBeforeToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-5kghb/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deleteHistoryBeforeToken:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-7t2th/title",
          "value": "deleteHistoryBeforeDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1deleteHistory(before:)-7t2th/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "deleteHistoryBeforeDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1resultType/title",
          "value": "resultType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1resultType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-3rmfm/title",
          "value": "fetchHistoryAfterToken:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest~1fetchHistory(after:)-3rmfm/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "fetchHistoryAfterToken:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistenthistorychangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistenthistorychangerequest"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
