{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/nspersistentstorecoordinator-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated Symbols"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSBinaryExternalRecordType": {
      "abstract": [
        {
          "text": "Specifies a binary file format",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBinaryExternalRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSBinaryExternalRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSBinaryExternalRecordType"
        }
      ],
      "role": "symbol",
      "title": "NSBinaryExternalRecordType",
      "type": "topic",
      "url": "/documentation/coredata/nsbinaryexternalrecordtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/addPersistentStore(ofType:configurationName:at:options:)": {
      "abstract": [
        {
          "text": "Adds a specific type of persistent store at the provided location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configurationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/addPersistentStore(ofType:configurationName:at:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPersistentStoreWithType:configuration:URL:options:error:"
        }
      ],
      "role": "symbol",
      "title": "addPersistentStore(ofType:configurationName:at:options:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/addpersistentstore(oftype:configurationname:at:options:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/destroyPersistentStore(at:ofType:options:)": {
      "abstract": [
        {
          "text": "Deletes a specific type of persistent store at the provided location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destroyPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/destroyPersistentStore(at:ofType:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destroyPersistentStoreAtURL:withType:options:error:"
        }
      ],
      "role": "symbol",
      "title": "destroyPersistentStore(at:ofType:options:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/destroypersistentstore(at:oftype:options:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/elementsDerived(fromExternalRecordAt:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing the parsed elements derived from the Spotlight external record file that is specified by the given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementsDerived"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "fromExternalRecordAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/elementsDerived(fromExternalRecordAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "elementsDerivedFromExternalRecordURL:"
        }
      ],
      "role": "symbol",
      "title": "elementsDerived(fromExternalRecordAt:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/elementsderived(fromexternalrecordat:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)": {
      "abstract": [
        {
          "text": "Creates and populates a store with the external records found at a given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "importStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "fromExternalRecordsDirectoryAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "importStoreWithIdentifier:fromExternalRecordsDirectory:toURL:options:withType:error:"
        }
      ],
      "role": "symbol",
      "title": "importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/importstore(withidentifier:fromexternalrecordsdirectoryat:to:options:oftype:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/lock()": {
      "abstract": [
        {
          "text": "Attempts to acquire a lock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lock"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/lock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lock"
        }
      ],
      "role": "symbol",
      "title": "lock()",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/lock()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:)": {
      "abstract": [
        {
          "text": "Returns a dictionary containing the metadata stored in the persistent store at a given URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForPersistentStoreOfType:URL:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataForPersistentStore(ofType:at:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/metadataforpersistentstore(oftype:at:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:options:)": {
      "abstract": [
        {
          "text": "Returns the metadata of a specific type of persistent store at the provided location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForPersistentStoreOfType:URL:options:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataForPersistentStore(ofType:at:options:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/metadataforpersistentstore(oftype:at:options:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(with:)": {
      "abstract": [
        {
          "text": "Returns a dictionary that contains the metadata stored in the persistent store at the specified location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataForPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataForPersistentStoreWithURL:error:"
        }
      ],
      "role": "symbol",
      "title": "metadataForPersistentStore(with:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/metadataforpersistentstore(with:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/migratePersistentStore(_:to:options:withType:)": {
      "abstract": [
        {
          "text": "Changes the location and, if necessary, the store type of the specified persistent store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "migratePersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "withType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPersistentStore",
          "text": "NSPersistentStore"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/migratePersistentStore(_:to:options:withType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "migratePersistentStore:toURL:options:withType:error:"
        }
      ],
      "role": "symbol",
      "title": "migratePersistentStore(_:to:options:withType:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/migratepersistentstore(_:to:options:withtype:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/perform(_:)-7jqb": {
      "abstract": [
        {
          "text": "Executes the provided closure asynchronously on the coordinator’s queue.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perform"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/perform(_:)-7jqb",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performBlock:"
        }
      ],
      "role": "symbol",
      "title": "perform(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/perform(_:)-7jqb"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/performAndWait(_:)-d3kq": {
      "abstract": [
        {
          "text": "Executes the provided closure on the coordinator’s queue and waits for it to finish.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performAndWait"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/performAndWait(_:)-d3kq",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performBlockAndWait:"
        }
      ],
      "role": "symbol",
      "title": "performAndWait(_:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/performandwait(_:)-d3kq"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/registerStoreClass(_:forStoreType:)": {
      "abstract": [
        {
          "text": "Registers a persistent store subclass using the specified store type identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerStoreClass"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forStoreType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/registerStoreClass(_:forStoreType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerStoreClass:forStoreType:"
        }
      ],
      "role": "symbol",
      "title": "registerStoreClass(_:forStoreType:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/registerstoreclass(_:forstoretype:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/removeUbiquitousContentAndPersistentStore(at:options:)": {
      "abstract": [
        {
          "text": "Deletes all ubiquitous content for all peers for the persistent store at a given URL and also delete the local store file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeUbiquitousContentAndPersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/removeUbiquitousContentAndPersistentStore(at:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeUbiquitousContentAndPersistentStoreAtURL:options:error:"
        }
      ],
      "role": "symbol",
      "title": "removeUbiquitousContentAndPersistentStore(at:options:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/removeubiquitouscontentandpersistentstore(at:options:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)": {
      "abstract": [
        {
          "text": "Replaces one persistent store with another.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replacePersistentStore"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destinationOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "withPersistentStoreFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replacePersistentStoreAtURL:destinationOptions:withPersistentStoreFromURL:sourceOptions:storeType:error:"
        }
      ],
      "role": "symbol",
      "title": "replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/replacepersistentstore(at:destinationoptions:withpersistentstorefrom:sourceoptions:oftype:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:)": {
      "abstract": [
        {
          "text": "Sets the metadata for a given store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMetadata"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "forPersistentStoreOfType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMetadata:forPersistentStoreOfType:URL:error:"
        }
      ],
      "role": "symbol",
      "title": "setMetadata(_:forPersistentStoreOfType:at:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/setmetadata(_:forpersistentstoreoftype:at:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:options:)": {
      "abstract": [
        {
          "text": "Updates the metadata of a specific type of persistent store at the provided location.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMetadata"
        },
        {
          "kind": "text",
          "text": "(["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?, "
        },
        {
          "kind": "externalParam",
          "text": "forPersistentStoreOfType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMetadata:forPersistentStoreOfType:URL:options:error:"
        }
      ],
      "role": "symbol",
      "title": "setMetadata(_:forPersistentStoreOfType:at:options:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/setmetadata(_:forpersistentstoreoftype:at:options:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/tryLock()": {
      "abstract": [
        {
          "text": "Attempts to acquire a lock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tryLock"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/tryLock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tryLock"
        }
      ],
      "role": "symbol",
      "title": "tryLock()",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/trylock()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/unlock()": {
      "abstract": [
        {
          "text": "Relinquishes a previously acquired lock.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unlock"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/unlock()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unlock"
        }
      ],
      "role": "symbol",
      "title": "unlock()",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/unlock()"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the coordinator posts after its registered stores change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoresdidchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator changes its registered stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoreswillchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDidImportUbiquitousContentChangesNotification": {
      "abstract": [
        {
          "text": "Posted after records are imported from the ubiquitous content store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDidImportUbiquitousContentChangesNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDidImportUbiquitousContentChangesNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreDidImportUbiquitousContentChangesNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoredidimportubiquitouscontentchangesnotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType": {
      "abstract": [
        {
          "text": "These constants are used as the value corresponding to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " in the user info dictionary of ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " and ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " notifications to identify the type of event leading to a change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionType"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionType"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousTransitionType",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontype"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionTypeKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousTransitionTypeKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitoustransitiontypekey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSXMLExternalRecordType": {
      "abstract": [
        {
          "text": "Specifies an XML file format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSXMLExternalRecordType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSXMLExternalRecordType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSXMLExternalRecordType"
        }
      ],
      "role": "symbol",
      "title": "NSXMLExternalRecordType",
      "type": "topic",
      "url": "/documentation/coredata/nsxmlexternalrecordtype"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468792-nspersistentstoredidimportubiqui": {
      "abstract": [
        {
          "text": "Posted after records are imported from the ubiquitous content store.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreDidImportUbiquitousContentChanges"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468792-nspersistentstoredidimportubiqui",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreDidImportUbiquitousContentChanges",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1468792-nspersistentstoredidimportubiqui"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSXMLExternalRecordType",
        "doc://com.apple.coredata/documentation/CoreData/NSBinaryExternalRecordType"
      ],
      "title": "Deprecated constants"
    },
    {
      "anchor": "Deprecated-enumerations",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType"
      ],
      "title": "Deprecated enumerations"
    },
    {
      "anchor": "Deprecated-type-properties",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468792-nspersistentstoredidimportubiqui"
      ],
      "title": "Deprecated type properties"
    },
    {
      "anchor": "Deprecated-type-methods",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/elementsDerived(fromExternalRecordAt:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(with:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:options:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/registerStoreClass(_:forStoreType:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/removeUbiquitousContentAndPersistentStore(at:options:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:options:)"
      ],
      "title": "Deprecated type methods"
    },
    {
      "anchor": "Deprecated-instance-methods",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/addPersistentStore(ofType:configurationName:at:options:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/destroyPersistentStore(at:ofType:options:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/lock()",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/migratePersistentStore(_:to:options:withType:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/tryLock()",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/unlock()",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/perform(_:)-7jqb",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/performAndWait(_:)-d3kq"
      ],
      "title": "Deprecated instance methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-constants",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSXMLExternalRecordType",
                "doc://com.apple.coredata/documentation/CoreData/NSBinaryExternalRecordType"
              ],
              "title": "Deprecated constants"
            },
            {
              "anchor": "Deprecated-enumerations",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousTransitionType"
              ],
              "title": "Deprecated enumerations"
            },
            {
              "anchor": "Deprecated-type-properties",
              "identifiers": [
                "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1468792-nspersistentstoredidimportubiqui",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreDidImportUbiquitousContentChangesNotification"
              ],
              "title": "Deprecated type properties"
            },
            {
              "anchor": "Deprecated-type-methods",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/elementsDerived(fromExternalRecordAt:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(with:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/metadataForPersistentStore(ofType:at:options:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/registerStoreClass(_:forStoreType:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/removeUbiquitousContentAndPersistentStore(at:options:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/setMetadata(_:forPersistentStoreOfType:at:options:)"
              ],
              "title": "Deprecated type methods"
            },
            {
              "anchor": "Deprecated-instance-methods",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/addPersistentStore(ofType:configurationName:at:options:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/destroyPersistentStore(at:ofType:options:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/lock()",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/migratePersistentStore(_:to:options:withType:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/tryLock()",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/unlock()",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/perform(_:)-7jqb",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/performAndWait(_:)-d3kq"
              ],
              "title": "Deprecated instance methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1tryLock()/title",
          "value": "tryLock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1tryLock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tryLock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)/title",
          "value": "importStoreWithIdentifier:fromExternalRecordsDirectory:toURL:options:withType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1importStore(withIdentifier:fromExternalRecordsDirectoryAt:to:options:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "importStoreWithIdentifier:fromExternalRecordsDirectory:toURL:options:withType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1registerStoreClass(_:forStoreType:)/title",
          "value": "registerStoreClass:forStoreType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1registerStoreClass(_:forStoreType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "registerStoreClass:forStoreType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(ofType:at:options:)/title",
          "value": "metadataForPersistentStoreOfType:URL:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(ofType:at:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "metadataForPersistentStoreOfType:URL:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1perform(_:)-7jqb/title",
          "value": "performBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1perform(_:)-7jqb/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1addPersistentStore(ofType:configurationName:at:options:)/title",
          "value": "addPersistentStoreWithType:configuration:URL:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1addPersistentStore(ofType:configurationName:at:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPersistentStoreWithType:configuration:URL:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1lock()/title",
          "value": "lock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1lock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBinaryExternalRecordType/title",
          "value": "NSBinaryExternalRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSBinaryExternalRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBinaryExternalRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSXMLExternalRecordType/title",
          "value": "NSXMLExternalRecordType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSXMLExternalRecordType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSXMLExternalRecordType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1destroyPersistentStore(at:ofType:options:)/title",
          "value": "destroyPersistentStoreAtURL:withType:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1destroyPersistentStore(at:ofType:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "destroyPersistentStoreAtURL:withType:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1setMetadata(_:forPersistentStoreOfType:at:)/title",
          "value": "setMetadata:forPersistentStoreOfType:URL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1setMetadata(_:forPersistentStoreOfType:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setMetadata:forPersistentStoreOfType:URL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)/title",
          "value": "replacePersistentStoreAtURL:destinationOptions:withPersistentStoreFromURL:sourceOptions:storeType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1replacePersistentStore(at:destinationOptions:withPersistentStoreFrom:sourceOptions:ofType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replacePersistentStoreAtURL:destinationOptions:withPersistentStoreFromURL:sourceOptions:storeType:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1elementsDerived(fromExternalRecordAt:)/title",
          "value": "elementsDerivedFromExternalRecordURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1elementsDerived(fromExternalRecordAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "elementsDerivedFromExternalRecordURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(with:)/title",
          "value": "metadataForPersistentStoreWithURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "metadataForPersistentStoreWithURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1performAndWait(_:)-d3kq/title",
          "value": "performBlockAndWait:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1performAndWait(_:)-d3kq/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performBlockAndWait:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1removeUbiquitousContentAndPersistentStore(at:options:)/title",
          "value": "removeUbiquitousContentAndPersistentStoreAtURL:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1removeUbiquitousContentAndPersistentStore(at:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "removeUbiquitousContentAndPersistentStoreAtURL:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/title",
          "value": "NSPersistentStoreUbiquitousTransitionTypeKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionTypeKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionTypeKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/title",
          "value": "NSPersistentStoreUbiquitousTransitionType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousTransitionType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousTransitionType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1unlock()/title",
          "value": "unlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1unlock()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(ofType:at:)/title",
          "value": "metadataForPersistentStoreOfType:URL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1metadataForPersistentStore(ofType:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "metadataForPersistentStoreOfType:URL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1setMetadata(_:forPersistentStoreOfType:at:options:)/title",
          "value": "setMetadata:forPersistentStoreOfType:URL:options:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1setMetadata(_:forPersistentStoreOfType:at:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setMetadata:forPersistentStoreOfType:URL:options:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1migratePersistentStore(_:to:options:withType:)/title",
          "value": "migratePersistentStore:toURL:options:withType:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1migratePersistentStore(_:to:options:withType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "migratePersistentStore:toURL:options:withType:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstorecoordinator-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentstorecoordinator-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
