{
  "abstract": [
    {
      "text": "Key to represent the protection class for the persistent store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPersistentStoreFileProtectionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSPersistentStoreFileProtectionKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPersistentStoreFileProtectionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPersistentStoreFileProtectionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPersistentStoreFileProtectionKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Backward compatibility may preclude some features. The acceptable values are those defined for the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/fileattributekey/1616632-protectionkey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The default value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1616633-completeuntilfirstuserauthentica",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for all applications built on or after iOS v5.0. The default value for all older applications is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1617472-none",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey": {
      "abstract": [
        {
          "text": "Key to represent the protection class for the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreFileProtectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreFileProtectionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreFileProtectionKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorefileprotectionkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption": {
      "abstract": [
        {
          "text": "A flag that indicates the coordinator destroys the store file even if the operation might be unsafe, overriding locks, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreForceDestroyOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreForceDestroyOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreForceDestroyOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreforcedestroyoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption": {
      "abstract": [
        {
          "text": "Options key that specifies the connection timeout for Core Data stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreTimeoutOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreTimeoutOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreTimeoutOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoretimeoutoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption": {
      "abstract": [
        {
          "text": "A flag that indicates whether a store is treated as read-only or not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReadOnlyPersistentStoreOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReadOnlyPersistentStoreOption"
        }
      ],
      "role": "symbol",
      "title": "NSReadOnlyPersistentStoreOption",
      "type": "topic",
      "url": "/documentation/coredata/nsreadonlypersistentstoreoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption": {
      "abstract": [
        {
          "text": "Option key to run an analysis of the store data to optimize indices based on statistical information when the store is added to the coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLiteAnalyzeOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLiteAnalyzeOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLiteAnalyzeOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqliteanalyzeoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption": {
      "abstract": [
        {
          "text": "Option key to rebuild the store file, forcing a database wide defragmentation when the store is added to the coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLiteManualVacuumOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLiteManualVacuumOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLiteManualVacuumOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqlitemanualvacuumoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption": {
      "abstract": [
        {
          "text": "Options key for a dictionary of SQLite pragma settings with pragma values indexed by pragma names as keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLitePragmasOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLitePragmasOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLitePragmasOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqlitepragmasoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption": {
      "abstract": [
        {
          "text": "A flag that indicates whether an XML file should be validated with the DTD while opening.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSValidateXMLStoreOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValidateXMLStoreOption"
        }
      ],
      "role": "symbol",
      "title": "NSValidateXMLStoreOption",
      "type": "topic",
      "url": "/documentation/coredata/nsvalidatexmlstoreoption"
    },
    "doc://com.apple.documentation/documentation/foundation/fileattributekey/1616632-protectionkey": {
      "abstract": [
        {
          "text": "The key in a file attribute dictionary whose value identifies the protection level for this file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "protectionKey"
        },
        {
          "kind": "text",
          "text": ": FileAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/fileattributekey/1616632-protectionkey",
      "kind": "symbol",
      "role": "symbol",
      "title": "protectionKey",
      "type": "topic",
      "url": "/documentation/foundation/fileattributekey/1616632-protectionkey"
    },
    "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1616633-completeuntilfirstuserauthentica": {
      "abstract": [
        {
          "text": "The file is stored in an encrypted format on disk and cannot be accessed until after the device has booted.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "completeUntilFirstUserAuthentication"
        },
        {
          "kind": "text",
          "text": ": FileProtectionType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1616633-completeuntilfirstuserauthentica",
      "kind": "symbol",
      "role": "symbol",
      "title": "completeUntilFirstUserAuthentication",
      "type": "topic",
      "url": "/documentation/foundation/fileprotectiontype/1616633-completeuntilfirstuserauthentica"
    },
    "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1617472-none": {
      "abstract": [
        {
          "text": "The file has no special protections associated with it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": FileProtectionType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/fileprotectiontype/1617472-none",
      "kind": "symbol",
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/foundation/fileprotectiontype/1617472-none"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
        "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPersistentStoreFileProtectionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreFileProtectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
                "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPersistentStoreFileProtectionKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSReadOnlyPersistentStoreOption/title",
          "value": "NSReadOnlyPersistentStoreOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSReadOnlyPersistentStoreOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReadOnlyPersistentStoreOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteManualVacuumOption/title",
          "value": "NSSQLiteManualVacuumOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteManualVacuumOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLiteManualVacuumOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1fileprotectiontype~11616633-completeuntilfirstuserauthentica/title",
          "value": "NSFileProtectionCompleteUntilFirstUserAuthentication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreTimeoutOption/title",
          "value": "NSPersistentStoreTimeoutOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreTimeoutOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreTimeoutOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLitePragmasOption/title",
          "value": "NSSQLitePragmasOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLitePragmasOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLitePragmasOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreFileProtectionKey/title",
          "value": "NSPersistentStoreFileProtectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreFileProtectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreFileProtectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteAnalyzeOption/title",
          "value": "NSSQLiteAnalyzeOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteAnalyzeOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLiteAnalyzeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidateXMLStoreOption/title",
          "value": "NSValidateXMLStoreOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidateXMLStoreOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidateXMLStoreOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1fileprotectiontype~11617472-none/title",
          "value": "NSFileProtectionNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreForceDestroyOption/title",
          "value": "NSPersistentStoreForceDestroyOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreForceDestroyOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreForceDestroyOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1fileattributekey~11616632-protectionkey/title",
          "value": "NSFileProtectionKey"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstorefileprotectionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nspersistentstorefileprotectionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
