{
  "abstract": [
    {
      "text": "A notification that posts before a coordinator changes its registered stores.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSPersistentStoreCoordinatorStoresWillChangeNotification",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This notification’s ",
              "type": "text"
            },
            {
              "code": "object",
              "type": "codeVoice"
            },
            {
              "text": " is the store coordinator that’s about to change. The framework posts the notification to an internal thread. Move to a known thread before peforming any work.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary contains information about the added and removed persistent stores, which you access with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " keys. Don’t capture the dictionary’s contents.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey": {
      "abstract": [
        {
          "text": "Key for the array of stores that were added.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAddedPersistentStoresKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSAddedPersistentStoresKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSAddedPersistentStoresKey"
        }
      ],
      "role": "symbol",
      "title": "NSAddedPersistentStoresKey",
      "type": "topic",
      "url": "/documentation/coredata/nsaddedpersistentstoreskey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that the coordinator posts after its registered stores change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresDidChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresDidChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoresdidchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator changes its registered stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorStoresWillChangeNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorStoresWillChangeNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorstoreswillchangenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorWillRemoveStoreNotification": {
      "abstract": [
        {
          "text": "A notification that posts before a coordinator removes a store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinatorWillRemoveStoreNotification"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorWillRemoveStoreNotification",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPersistentStoreCoordinatorWillRemoveStoreNotification",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinatorwillremovestorenotification"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey": {
      "abstract": [
        {
          "text": "Key for the array of stores that were removed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRemovedPersistentStoresKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSRemovedPersistentStoresKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRemovedPersistentStoresKey"
        }
      ],
      "role": "symbol",
      "title": "NSRemovedPersistentStoresKey",
      "type": "topic",
      "url": "/documentation/coredata/nsremovedpersistentstoreskey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorStoresDidChangeNotification",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinatorWillRemoveStoreNotification"
      ],
      "title": "Notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAddedPersistentStoresKey/title",
          "value": "NSAddedPersistentStoresKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSAddedPersistentStoresKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSAddedPersistentStoresKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRemovedPersistentStoresKey/title",
          "value": "NSRemovedPersistentStoresKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSRemovedPersistentStoresKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRemovedPersistentStoresKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nspersistentstorecoordinatorstoreswillchangenotification"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
