{
  "abstract": [
    {
      "text": "Error code to denote an error containing multiple validation errors.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/NSValidationMultipleErrorsError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSManagedObjectValidationError@NSValidationMultipleErrorsError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSValidationMultipleErrorsError"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSValidationMultipleErrorsError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSValidationMultipleErrorsError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSValidationMultipleErrorsError"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSCoreDataError": {
      "abstract": [
        {
          "text": "An error code that indicates a nonspecific Core Data error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCoreDataError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSCoreDataError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCoreDataError"
        }
      ],
      "role": "symbol",
      "title": "NSCoreDataError",
      "type": "topic",
      "url": "/documentation/coredata/nscoredataerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicyError": {
      "abstract": [
        {
          "text": "An error code that indicates a migration failure during processing of an entity migration policy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicyError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicyError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSEntityMigrationPolicyError"
        }
      ],
      "role": "symbol",
      "title": "NSEntityMigrationPolicyError",
      "type": "topic",
      "url": "/documentation/coredata/nsentitymigrationpolicyerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordImportError": {
      "abstract": [
        {
          "text": "Error code to denote a general error encountered while importing external records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordImportError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordImportError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordImportError"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordImportError",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordimporterror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSInferredMappingModelError": {
      "abstract": [
        {
          "text": "Error code to denote a problem with the creation of an inferred mapping model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSInferredMappingModelError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSInferredMappingModelError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSInferredMappingModelError"
        }
      ],
      "role": "symbol",
      "title": "NSInferredMappingModelError",
      "type": "topic",
      "url": "/documentation/coredata/nsinferredmappingmodelerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintMergeError": {
      "abstract": [
        {
          "text": "Error code to denote a problem with the merging of instances of a managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectConstraintMergeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintMergeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectConstraintMergeError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectConstraintMergeError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectconstraintmergeerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintValidationError": {
      "abstract": [
        {
          "text": "Error code to denote a problem with the validation of a managed object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectConstraintValidationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintValidationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectConstraintValidationError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectConstraintValidationError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectconstraintvalidationerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextLockingError": {
      "abstract": [
        {
          "text": "Error code to denote an inability to acquire a lock in a managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextLockingError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextLockingError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectContextLockingError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectContextLockingError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectcontextlockingerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectExternalRelationshipError": {
      "abstract": [
        {
          "text": "Error code to denote that an object being saved has a relationship containing an object from another store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectExternalRelationshipError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectExternalRelationshipError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectExternalRelationshipError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectExternalRelationshipError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectexternalrelationshiperror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectMergeError": {
      "abstract": [
        {
          "text": "Error code to denote that a merge policy failed—Core Data is unable to complete merging.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectMergeError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectMergeError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectMergeError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectMergeError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectmergeerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModelReferenceNotFoundError": {
      "abstract": [
        {
          "text": "An error code that indicates Core Data isn’t able to find or instantiate the referenced object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectModelReferenceNotFoundError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModelReferenceNotFoundError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectModelReferenceNotFoundError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectModelReferenceNotFoundError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectmodelreferencenotfounderror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectReferentialIntegrityError": {
      "abstract": [
        {
          "text": "Error code to denote an attempt to fire a fault pointing to an object that does not exist.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectReferentialIntegrityError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectReferentialIntegrityError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectReferentialIntegrityError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectReferentialIntegrityError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectreferentialintegrityerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectValidationError": {
      "abstract": [
        {
          "text": "Error code to denote a generic validation error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagedObjectValidationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectValidationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSManagedObjectValidationError"
        }
      ],
      "role": "symbol",
      "title": "NSManagedObjectValidationError",
      "type": "topic",
      "url": "/documentation/coredata/nsmanagedobjectvalidationerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationCancelledError": {
      "abstract": [
        {
          "text": "Error code to denote that migration failed due to manual cancellation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationCancelledError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationCancelledError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationCancelledError"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationCancelledError",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationcancellederror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationConstraintViolationError": {
      "abstract": [
        {
          "text": "Error code to denote a problem with the validation of a managed object during a migration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationConstraintViolationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationConstraintViolationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationConstraintViolationError"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationConstraintViolationError",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationconstraintviolationerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSMigrationError": {
      "abstract": [
        {
          "text": "Error code to denote a general migration error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMigrationError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSMigrationError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSMigrationError"
        }
      ],
      "role": "symbol",
      "title": "NSMigrationError",
      "type": "topic",
      "url": "/documentation/coredata/nsmigrationerror"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSValidationMultipleErrorsError": {
      "abstract": [
        {
          "text": "Error code to denote an error containing multiple validation errors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSValidationMultipleErrorsError"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSValidationMultipleErrorsError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValidationMultipleErrorsError"
        }
      ],
      "role": "symbol",
      "title": "NSValidationMultipleErrorsError",
      "type": "topic",
      "url": "/documentation/coredata/nsvalidationmultipleerrorserror"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Error-codes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSCoreDataError",
        "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicyError",
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordImportError",
        "doc://com.apple.coredata/documentation/CoreData/NSInferredMappingModelError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintMergeError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintValidationError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextLockingError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectExternalRelationshipError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectMergeError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModelReferenceNotFoundError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectReferentialIntegrityError",
        "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectValidationError",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationCancelledError",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationConstraintViolationError",
        "doc://com.apple.coredata/documentation/CoreData/NSMigrationError"
      ],
      "title": "Error codes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSValidationMultipleErrorsError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidationMultipleErrorsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coredata/documentation/CoreData"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Error-codes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSCoreDataError",
                "doc://com.apple.coredata/documentation/CoreData/NSEntityMigrationPolicyError",
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordImportError",
                "doc://com.apple.coredata/documentation/CoreData/NSInferredMappingModelError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintMergeError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectConstraintValidationError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectContextLockingError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectExternalRelationshipError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectMergeError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectModelReferenceNotFoundError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectReferentialIntegrityError",
                "doc://com.apple.coredata/documentation/CoreData/NSManagedObjectValidationError",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationCancelledError",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationConstraintViolationError",
                "doc://com.apple.coredata/documentation/CoreData/NSMigrationError"
              ],
              "title": "Error codes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSValidationMultipleErrorsError"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectValidationError/title",
          "value": "NSManagedObjectValidationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectValidationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectValidationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectReferentialIntegrityError/title",
          "value": "NSManagedObjectReferentialIntegrityError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectReferentialIntegrityError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectReferentialIntegrityError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidationMultipleErrorsError/title",
          "value": "NSValidationMultipleErrorsError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidationMultipleErrorsError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidationMultipleErrorsError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationConstraintViolationError/title",
          "value": "NSMigrationConstraintViolationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationConstraintViolationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationConstraintViolationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordImportError/title",
          "value": "NSExternalRecordImportError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordImportError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordImportError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContextLockingError/title",
          "value": "NSManagedObjectContextLockingError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectContextLockingError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectContextLockingError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectMergeError/title",
          "value": "NSManagedObjectMergeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectMergeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectMergeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectConstraintValidationError/title",
          "value": "NSManagedObjectConstraintValidationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectConstraintValidationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectConstraintValidationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataError/title",
          "value": "NSCoreDataError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSCoreDataError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCoreDataError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectExternalRelationshipError/title",
          "value": "NSManagedObjectExternalRelationshipError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectExternalRelationshipError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectExternalRelationshipError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicyError/title",
          "value": "NSEntityMigrationPolicyError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSEntityMigrationPolicyError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSEntityMigrationPolicyError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInferredMappingModelError/title",
          "value": "NSInferredMappingModelError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSInferredMappingModelError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSInferredMappingModelError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectConstraintMergeError/title",
          "value": "NSManagedObjectConstraintMergeError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectConstraintMergeError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectConstraintMergeError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationCancelledError/title",
          "value": "NSMigrationCancelledError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationCancelledError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationCancelledError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationError/title",
          "value": "NSMigrationError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSMigrationError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSMigrationError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModelReferenceNotFoundError/title",
          "value": "NSManagedObjectModelReferenceNotFoundError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSManagedObjectModelReferenceNotFoundError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSManagedObjectModelReferenceNotFoundError"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/nsvalidationmultipleerrorserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/nsvalidationmultipleerrorserror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
