{
  "abstract": [
    {
      "text": "Use persistent history tracking to determine what changes have occurred in the store since the enabling of persistent history tracking.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/persistent-history"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Persistent history"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChange": {
      "abstract": [
        {
          "text": "A change representing the insertion, update, or deletion of a managed object in the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChange"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChange"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryChange",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychange"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest": {
      "abstract": [
        {
          "text": "A request to fetch or purge persistent history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChangeRequest"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryChangeRequest"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryChangeRequest",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorychangerequest"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult": {
      "abstract": [
        {
          "text": "The result of a request to fetch persistent history.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResult"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryResult"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryResult",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistoryresult"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryToken": {
      "abstract": [
        {
          "text": "A bookmark for keeping track the most recent history that you’ve processed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryToken"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryToken"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryToken",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorytoken"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryTransaction": {
      "abstract": [
        {
          "text": "A set of changes in the persistent history based on a context save or batch operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryTransaction"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentHistoryTransaction"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentHistoryTransaction",
      "type": "topic",
      "url": "/documentation/coredata/nspersistenthistorytransaction"
    },
    "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes": {
      "abstract": [
        {
          "text": "Guarantee that a context won’t see store changes until you tell it to look.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Accessing data when the store changes",
      "type": "topic",
      "url": "/documentation/coredata/accessing-data-when-the-store-changes"
    },
    "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes": {
      "abstract": [
        {
          "text": "Filter store transactions for changes relevant to the current view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes",
      "kind": "article",
      "role": "article",
      "title": "Consuming relevant store changes",
      "type": "topic",
      "url": "/documentation/coredata/consuming-relevant-store-changes"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Change-processing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
        "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes"
      ],
      "title": "Change processing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tracking-History",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryToken"
      ],
      "title": "Tracking History"
    },
    {
      "anchor": "Requesting-History",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult"
      ],
      "title": "Requesting History"
    },
    {
      "anchor": "Reading-History",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryTransaction",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChange"
      ],
      "title": "Reading History"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Tracking-History",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryToken"
              ],
              "title": "Tracking History"
            },
            {
              "anchor": "Requesting-History",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChangeRequest",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryResult"
              ],
              "title": "Requesting History"
            },
            {
              "anchor": "Reading-History",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryTransaction",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentHistoryChange"
              ],
              "title": "Reading History"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Change-processing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/accessing-data-when-the-store-changes",
                "doc://com.apple.coredata/documentation/CoreData/consuming-relevant-store-changes"
              ],
              "title": "Change processing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryTransaction/title",
          "value": "NSPersistentHistoryTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryTransaction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/title",
          "value": "NSPersistentHistoryResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryToken/title",
          "value": "NSPersistentHistoryToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChange/title",
          "value": "NSPersistentHistoryChange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/title",
          "value": "NSPersistentHistoryChangeRequest"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentHistoryChangeRequest/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentHistoryChangeRequest"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/persistent-history"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/persistent-history"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
