{
  "abstract": [
    {
      "text": "The options keys that configure the behavior and characteristics of a persistent store.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coredata/documentation/CoreData",
        "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coredata/documentation/CoreData/store-options"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Data"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Store options"
  },
  "references": {
    "doc://com.apple.coredata/documentation/CoreData": {
      "abstract": [
        {
          "text": "Persist or cache data on a single device, or sync data to multiple devices with CloudKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Data",
      "type": "topic",
      "url": "/documentation/coredata"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption": {
      "abstract": [
        {
          "text": "Option indicating the file extension to use for Spotlight external record files.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordExtensionOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordExtensionOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordExtensionOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordextensionoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption": {
      "abstract": [
        {
          "text": "Option indicating the directory where Spotlight external record files should be written to.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordsDirectoryOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordsDirectoryOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordsDirectoryOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordsdirectoryoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption": {
      "abstract": [
        {
          "text": "Option to specify the file format of a Spotlight external records.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExternalRecordsFileFormatOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSExternalRecordsFileFormatOption"
        }
      ],
      "role": "symbol",
      "title": "NSExternalRecordsFileFormatOption",
      "type": "topic",
      "url": "/documentation/coredata/nsexternalrecordsfileformatoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator": {
      "abstract": [
        {
          "text": "An object that enables an app’s contexts and the underlying persistent stores to work together.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreCoordinator"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreCoordinator",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)": {
      "abstract": [
        {
          "text": "Creates a persistent store coordinator with the specified managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "managedObjectModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithManagedObjectModel:"
        }
      ],
      "role": "symbol",
      "title": "init(managedObjectModel:)",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorecoordinator/init(managedobjectmodel:)"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey": {
      "abstract": [
        {
          "text": "Key to represent the protection class for the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreFileProtectionKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreFileProtectionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreFileProtectionKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorefileprotectionkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption": {
      "abstract": [
        {
          "text": "A flag that indicates the coordinator destroys the store file even if the operation might be unsafe, overriding locks, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreForceDestroyOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreForceDestroyOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreForceDestroyOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreforcedestroyoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing a boolean that indicates whether the receiver should erase the local store file and rebuild it from the iCloud data in Mobile Documents.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRebuildFromUbiquitousContentOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstorerebuildfromubiquitouscontentoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption": {
      "abstract": [
        {
          "text": "The corresponding value is an ",
          "type": "text"
        },
        {
          "code": "NSNumber",
          "type": "codeVoice"
        },
        {
          "text": " object representing a boolean that indicates whether the receiver should remove all associated ubiquity metadata from a persistent store. You typically use this option during migration or copying to disassociate a persistent store file from an iCloud account.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreRemoveUbiquitousMetadataOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreremoveubiquitousmetadataoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption": {
      "abstract": [
        {
          "text": "Options key that specifies the connection timeout for Core Data stores.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreTimeoutOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreTimeoutOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreTimeoutOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoretimeoutoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey": {
      "abstract": [
        {
          "text": "The a string specifying the iCloud container identifier.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContainerIdentifierKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontaineridentifierkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey": {
      "abstract": [
        {
          "text": "Option to specify that a persistent store has a given name in ubiquity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentNameKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContentNameKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontentnamekey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey": {
      "abstract": [
        {
          "text": "Option to specify the log path to use for ubiquitous content logs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentURLKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousContentURLKey"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousContentURLKey",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouscontenturlkey"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption": {
      "abstract": [
        {
          "text": "The corresponding value is an optionally specified string which will be mixed in to Core Data’s identifier for each iCloud peer. The value must be an alphanumeric string without any special characters, whitespace or punctuation. The primary use for this option is to allow multiple applications on the same peer (device) to share a Core Data store integrated with iCloud. Each application will require its own store file.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousPeerTokenOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPersistentStoreUbiquitousPeerTokenOption"
        }
      ],
      "role": "symbol",
      "title": "NSPersistentStoreUbiquitousPeerTokenOption",
      "type": "topic",
      "url": "/documentation/coredata/nspersistentstoreubiquitouspeertokenoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption": {
      "abstract": [
        {
          "text": "A flag that indicates whether a store is treated as read-only or not.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSReadOnlyPersistentStoreOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSReadOnlyPersistentStoreOption"
        }
      ],
      "role": "symbol",
      "title": "NSReadOnlyPersistentStoreOption",
      "type": "topic",
      "url": "/documentation/coredata/nsreadonlypersistentstoreoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption": {
      "abstract": [
        {
          "text": "Option key to run an analysis of the store data to optimize indices based on statistical information when the store is added to the coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLiteAnalyzeOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLiteAnalyzeOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLiteAnalyzeOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqliteanalyzeoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption": {
      "abstract": [
        {
          "text": "Option key to rebuild the store file, forcing a database wide defragmentation when the store is added to the coordinator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLiteManualVacuumOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLiteManualVacuumOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLiteManualVacuumOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqlitemanualvacuumoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption": {
      "abstract": [
        {
          "text": "Options key for a dictionary of SQLite pragma settings with pragma values indexed by pragma names as keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSQLitePragmasOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSQLitePragmasOption"
        }
      ],
      "role": "symbol",
      "title": "NSSQLitePragmasOption",
      "type": "topic",
      "url": "/documentation/coredata/nssqlitepragmasoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption": {
      "abstract": [
        {
          "text": "A flag that indicates whether an XML file should be validated with the DTD while opening.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSValidateXMLStoreOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSValidateXMLStoreOption"
        }
      ],
      "role": "symbol",
      "title": "NSValidateXMLStoreOption",
      "type": "topic",
      "url": "/documentation/coredata/nsvalidatexmlstoreoption"
    },
    "doc://com.apple.coredata/documentation/CoreData/core-data-stack": {
      "abstract": [
        {
          "text": "Manage and persist your app’s model layer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/core-data-stack",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Data stack",
      "type": "topic",
      "url": "/documentation/coredata/core-data-stack"
    },
    "doc://com.apple.coredata/documentation/CoreData/migration-options": {
      "abstract": [
        {
          "text": "The options keys that configure the migration behavior of a persistent store.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/migration-options",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Migration options",
      "type": "topic",
      "url": "/documentation/coredata/migration-options"
    },
    "doc://com.apple.coredata/documentation/CoreData/store-versions": {
      "abstract": [
        {
          "text": "The metadata keys you use when comparing store versions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coredata/documentation/CoreData/store-versions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Store versions",
      "type": "topic",
      "url": "/documentation/coredata/store-versions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-persistent-store-coordinator",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
        "doc://com.apple.coredata/documentation/CoreData/migration-options",
        "doc://com.apple.coredata/documentation/CoreData/store-versions"
      ],
      "title": "Creating a persistent store coordinator"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
        "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
        "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
        "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
        "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSReadOnlyPersistentStoreOption",
                "doc://com.apple.coredata/documentation/CoreData/NSValidateXMLStoreOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreTimeoutOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLitePragmasOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLiteAnalyzeOption",
                "doc://com.apple.coredata/documentation/CoreData/NSSQLiteManualVacuumOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreFileProtectionKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreForceDestroyOption"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsDirectoryOption",
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordExtensionOption",
                "doc://com.apple.coredata/documentation/CoreData/NSExternalRecordsFileFormatOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentNameKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContentURLKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousPeerTokenOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRemoveUbiquitousMetadataOption",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreUbiquitousContainerIdentifierKey",
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreRebuildFromUbiquitousContentOption"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-persistent-store-coordinator",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coredata/documentation/CoreData/NSPersistentStoreCoordinator/init(managedObjectModel:)",
                "doc://com.apple.coredata/documentation/CoreData/migration-options",
                "doc://com.apple.coredata/documentation/CoreData/store-versions"
              ],
              "title": "Creating a persistent store coordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1init(managedObjectModel:)/title",
          "value": "initWithManagedObjectModel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator~1init(managedObjectModel:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithManagedObjectModel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreFileProtectionKey/title",
          "value": "NSPersistentStoreFileProtectionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreFileProtectionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreFileProtectionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsDirectoryOption/title",
          "value": "NSExternalRecordsDirectoryOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsDirectoryOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordsDirectoryOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidateXMLStoreOption/title",
          "value": "NSValidateXMLStoreOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSValidateXMLStoreOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSValidateXMLStoreOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteAnalyzeOption/title",
          "value": "NSSQLiteAnalyzeOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteAnalyzeOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLiteAnalyzeOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteManualVacuumOption/title",
          "value": "NSSQLiteManualVacuumOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLiteManualVacuumOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLiteManualVacuumOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousPeerTokenOption/title",
          "value": "NSPersistentStoreUbiquitousPeerTokenOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousPeerTokenOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousPeerTokenOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContainerIdentifierKey/title",
          "value": "NSPersistentStoreUbiquitousContainerIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContainerIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContainerIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRebuildFromUbiquitousContentOption/title",
          "value": "NSPersistentStoreRebuildFromUbiquitousContentOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRebuildFromUbiquitousContentOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRebuildFromUbiquitousContentOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSReadOnlyPersistentStoreOption/title",
          "value": "NSReadOnlyPersistentStoreOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSReadOnlyPersistentStoreOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSReadOnlyPersistentStoreOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentNameKey/title",
          "value": "NSPersistentStoreUbiquitousContentNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContentNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLitePragmasOption/title",
          "value": "NSSQLitePragmasOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSSQLitePragmasOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSQLitePragmasOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/title",
          "value": "NSPersistentStoreCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentURLKey/title",
          "value": "NSPersistentStoreUbiquitousContentURLKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreUbiquitousContentURLKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreUbiquitousContentURLKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreForceDestroyOption/title",
          "value": "NSPersistentStoreForceDestroyOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreForceDestroyOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreForceDestroyOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreTimeoutOption/title",
          "value": "NSPersistentStoreTimeoutOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreTimeoutOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreTimeoutOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRemoveUbiquitousMetadataOption/title",
          "value": "NSPersistentStoreRemoveUbiquitousMetadataOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSPersistentStoreRemoveUbiquitousMetadataOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPersistentStoreRemoveUbiquitousMetadataOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordExtensionOption/title",
          "value": "NSExternalRecordExtensionOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordExtensionOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordExtensionOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsFileFormatOption/title",
          "value": "NSExternalRecordsFileFormatOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coredata~1documentation~1CoreData~1NSExternalRecordsFileFormatOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSExternalRecordsFileFormatOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coredata/store-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coredata/store-options"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
