{"abstract":[{"type":"text","text":"The default action-message selector associated with the control."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"Discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This property contains the action message selector of the receiver’s cell. Controls that support multiple cells (such as "},{"type":"codeVoice","code":"NSMatrix"},{"type":"text","text":" and "},{"type":"codeVoice","code":"NSForm"},{"type":"text","text":") must supply the appropriate action-message selector in this property. Specify "},{"type":"codeVoice","code":"NULL"},{"type":"text","text":" to prevent action messages from being sent to the receiver’s target."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want the action-message selector for a control that has multiple cells, it is better to get the selector directly from the cell’s own "},{"code":"action","type":"codeVoice"},{"type":"text","text":" property."}]}]}],"metadata":{"role":"symbol","modules":[{"name":"AppKit"}],"title":"action","navigatorTitle":[{"kind":"identifier","text":"action"}],"externalID":"c:objc(cs)NSControl(py)action","platforms":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV","text":"Selector"},{"kind":"text","text":"?"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSControl/action"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscontrol/action"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscontrol/action"]}],"seeAlsoSections":[{"title":"Implementing the Target-Action Mechanism","anchor":"Implementing-the-Target-Action-Mechanism","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControl/target","doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSControl/target":{"url":"/documentation/appkit/nscontrol/target","title":"target","abstract":[{"text":"The target object that receives action messages from the cell.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/target","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"target","kind":"identifier"},{"text":": AnyObject?","kind":"text"}],"navigatorTitle":[{"text":"target","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl/action":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"action","kind":"identifier"}],"role":"symbol","title":"action","type":"topic","kind":"symbol","url":"/documentation/appkit/nscontrol/action","abstract":[{"type":"text","text":"The default action-message selector associated with the control."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/action"},"doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContinuous","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nscontrol/iscontinuous","title":"isContinuous","navigatorTitle":[{"text":"continuous","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous","abstract":[{"type":"text","text":"A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking."}]},"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)":{"abstract":[{"type":"text","text":"Sets the conditions on which the receiver sends action messages to its target."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)","role":"symbol","title":"sendAction(on:)","kind":"symbol","url":"/documentation/appkit/nscontrol/sendaction(on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EventTypeMask","preciseIdentifier":"c:@E@NSEventMask"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"sendActionOn:"}]},"doc://com.externally.resolved.symbol/c:@T@SEL":{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","type":"topic","abstract":[{"type":"text","text":"Defines an opaque type that represents a method selector."}],"url":"/documentation/objectivec/sel","title":"SEL","kind":"symbol","role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)":{"type":"topic","abstract":[{"type":"text","text":"Causes the specified action to be sent to the target."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","url":"/documentation/appkit/nscontrol/sendaction(_:to:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"sendAction:to:"}],"title":"sendAction(_:to:)","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV":{"type":"topic","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"Selector"}],"url":"/documentation/objectivec/selector","title":"Selector","abstract":[{"type":"text","text":""}],"identifier":"doc://com.externally.resolved.symbol/s:10ObjectiveC8SelectorV","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"macOS","beta":false,"deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Instance Property"},{"op":"replace","path":"/metadata/title","value":"action"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"action"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControl/target","doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)"],"generated":true,"anchor":"Implementing-the-Target-Action-Mechanism","title":"Implementing the Target-Action Mechanism"}]},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@SEL","text":"SEL","preciseIdentifier":"c:@T@SEL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/title","value":"target"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/fragments","value":[{"kind":"identifier","text":"target"}]},{"value":"action","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/title"},{"value":[{"text":"action","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/fragments"},{"value":"continuous","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/title"},{"value":[{"kind":"identifier","text":"continuous"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/fragments"},{"value":"sendActionOn:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(on:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendActionOn:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(on:)/fragments"},{"value":"sendAction:to:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(_:to:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendAction:to:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(_:to:)/fragments"},{"value":"NSControl","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title"},{"value":[{"kind":"identifier","text":"NSControl"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments"},{"value":[{"text":"NSControl","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}