{
  "abstract": [
    {
      "text": "A constant for specifying a cell’s size.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSControl"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSControlSize",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ControlSize"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ControlSize"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSControl.ControlSize"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ControlSize"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These constants are used by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/Attribute": {
      "abstract": [
        {
          "text": "Constants for specifying how a button behaves when pressed and how it displays its state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/Attribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Attribute"
        }
      ],
      "role": "symbol",
      "title": "NSCell.Attribute",
      "type": "topic",
      "url": "/documentation/appkit/nscell/attribute"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/CellType": {
      "abstract": [
        {
          "text": "Constants for specifying how a cell represents its data (as text or as an image).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CellType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/CellType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CellType"
        }
      ],
      "role": "symbol",
      "title": "NSCell.CellType",
      "type": "topic",
      "url": "/documentation/appkit/nscell/celltype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/HitResult": {
      "abstract": [
        {
          "text": "Constants used by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/hitTest(for:in:of:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method to determine the effect of an event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HitResult"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/HitResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HitResult"
        }
      ],
      "role": "symbol",
      "title": "NSCell.HitResult",
      "type": "topic",
      "url": "/documentation/appkit/nscell/hitresult"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/StateValue": {
      "abstract": [
        {
          "text": "Constants for specifying a cell’s state and are used mostly for buttons.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StateValue"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/StateValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StateValue"
        }
      ],
      "role": "symbol",
      "title": "NSCell.StateValue",
      "type": "topic",
      "url": "/documentation/appkit/nscell/statevalue"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/StyleMask": {
      "abstract": [
        {
          "text": "Constants for specifying what happens when a button is pressed or is displaying its alternate state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/StyleMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "StyleMask"
        }
      ],
      "role": "symbol",
      "title": "NSCell.StyleMask",
      "type": "topic",
      "url": "/documentation/appkit/nscell/stylemask"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize": {
      "abstract": [
        {
          "text": "The size of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "controlSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSControl",
          "text": "NSControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSControlSize",
          "text": "ControlSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/controlSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "controlSize"
        }
      ],
      "role": "symbol",
      "title": "controlSize",
      "type": "topic",
      "url": "/documentation/appkit/nscell/controlsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCell/hitTest(for:in:of:)": {
      "abstract": [
        {
          "text": "Returns hit testing information for the receiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hitTest"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSEvent",
          "text": "NSEvent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCell",
          "text": "NSCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCellHitResult",
          "text": "HitResult"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCell/hitTest(for:in:of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hitTestForEvent:inRect:ofView:"
        }
      ],
      "role": "symbol",
      "title": "hitTest(for:in:of:)",
      "type": "topic",
      "url": "/documentation/appkit/nscell/hittest(for:in:of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl": {
      "abstract": [
        {
          "text": "A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControl"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControl"
        }
      ],
      "role": "symbol",
      "title": "NSControl",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum": {
      "abstract": [
        {
          "text": "A constant for specifying a cell’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ControlSize"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ControlSize",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/large": {
      "abstract": [
        {
          "text": "A size larger than the default control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlSizeLarge"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ControlSize.large",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum/large"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/mini": {
      "abstract": [
        {
          "text": "The smallest control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mini"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/mini",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlSizeMini"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ControlSize.mini",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum/mini"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/regular": {
      "abstract": [
        {
          "text": "The default control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "regular"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/regular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlSizeRegular"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ControlSize.regular",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum/regular"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/small": {
      "abstract": [
        {
          "text": "A size smaller than the default control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/small",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlSizeSmall"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ControlSize.small",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/controlsize-swift.enum/small"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControl/ImagePosition": {
      "abstract": [
        {
          "text": "A constant for specifying the position of a button’s image relative to its title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImagePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControl/ImagePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImagePosition"
        }
      ],
      "role": "symbol",
      "title": "NSControl.ImagePosition",
      "type": "topic",
      "url": "/documentation/appkit/nscontrol/imageposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSControlTint": {
      "abstract": [
        {
          "text": "Constants for specifying a cell’s tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlTint"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSControlTint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlTint"
        }
      ],
      "role": "symbol",
      "title": "NSControlTint",
      "type": "topic",
      "url": "/documentation/appkit/nscontroltint"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImageScaling": {
      "abstract": [
        {
          "text": "Constants that specify a cell’s image scaling behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImageScaling"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImageScaling",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSImageScaling"
        }
      ],
      "role": "symbol",
      "title": "NSImageScaling",
      "type": "topic",
      "url": "/documentation/appkit/nsimagescaling"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSMiniControlSize": {
      "abstract": [
        {
          "text": "The control has a smaller size than ",
          "type": "text"
        },
        {
          "code": "NSSmallControlSize",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSMiniControlSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSMiniControlSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMiniControlSize",
      "type": "topic",
      "url": "/documentation/appkit/nsminicontrolsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSRegularControlSize": {
      "abstract": [
        {
          "text": "The default control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSRegularControlSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSRegularControlSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRegularControlSize",
      "type": "topic",
      "url": "/documentation/appkit/nsregularcontrolsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSmallControlSize": {
      "abstract": [
        {
          "text": "A size that is smaller than the default control size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSmallControlSize"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSmallControlSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSmallControlSize",
      "type": "topic",
      "url": "/documentation/appkit/nssmallcontrolsize"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle": {
      "abstract": [
        {
          "text": "Background styles to apply to a view’s cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BackgroundStyle"
        }
      ],
      "role": "symbol",
      "title": "NSView.BackgroundStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsview/backgroundstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/data-entry-types": {
      "abstract": [
        {
          "text": "These constants specify how a cell formats numeric data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/data-entry-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Data Entry Types",
      "type": "topic",
      "url": "/documentation/appkit/data-entry-types"
    },
    "doc://com.apple.appkit/documentation/AppKit/deprecated-scaling-constants": {
      "abstract": [
        {
          "text": "These are deprecated scaling constants.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/deprecated-scaling-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated Scaling Constants",
      "type": "topic",
      "url": "/documentation/appkit/deprecated-scaling-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCell/CellType",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/Attribute",
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ImagePosition",
        "doc://com.apple.appkit/documentation/AppKit/NSImageScaling",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/StateValue",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/StyleMask",
        "doc://com.apple.appkit/documentation/AppKit/NSControlTint",
        "doc://com.apple.appkit/documentation/AppKit/NSCell/HitResult",
        "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle",
        "doc://com.apple.appkit/documentation/AppKit/deprecated-scaling-constants",
        "doc://com.apple.appkit/documentation/AppKit/data-entry-types"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Sizing-Controls",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/mini",
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/small",
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/regular",
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/large"
      ],
      "title": "Sizing Controls"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSControlSize"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Sizing-Controls",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/mini",
                "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/small",
                "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/regular",
                "doc://com.apple.appkit/documentation/AppKit/NSControl/ControlSize-swift.enum/large",
                "doc://com.apple.appkit/documentation/AppKit/NSRegularControlSize",
                "doc://com.apple.appkit/documentation/AppKit/NSSmallControlSize",
                "doc://com.apple.appkit/documentation/AppKit/NSMiniControlSize"
              ],
              "title": "Sizing Controls"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCell/CellType",
                "doc://com.apple.appkit/documentation/AppKit/NSCell/Attribute",
                "doc://com.apple.appkit/documentation/AppKit/NSControl/ImagePosition",
                "doc://com.apple.appkit/documentation/AppKit/NSImageScaling",
                "doc://com.apple.appkit/documentation/AppKit/NSCell/StateValue",
                "doc://com.apple.appkit/documentation/AppKit/NSCell/StyleMask",
                "doc://com.apple.appkit/documentation/AppKit/NSControlTint",
                "doc://com.apple.appkit/documentation/AppKit/NSCell/HitResult",
                "doc://com.apple.appkit/documentation/AppKit/NSView/BackgroundStyle",
                "doc://com.apple.appkit/documentation/AppKit/deprecated-scaling-constants",
                "doc://com.apple.appkit/documentation/AppKit/data-entry-types"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSControlSize"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StateValue/title",
          "value": "NSCellStateValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StateValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellStateValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StateValue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellStateValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/title",
          "value": "NSControlSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StyleMask/title",
          "value": "NSCellStyleMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StyleMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1StyleMask/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellStyleMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1regular/title",
          "value": "NSControlSizeRegular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1regular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSizeRegular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ImagePosition/title",
          "value": "NSCellImagePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ImagePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellImagePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ImagePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellImagePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1hitTest(for:in:of:)/title",
          "value": "hitTestForEvent:inRect:ofView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1hitTest(for:in:of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "hitTestForEvent:inRect:ofView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1HitResult/title",
          "value": "NSCellHitResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1HitResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellHitResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1HitResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellHitResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1small/title",
          "value": "NSControlSizeSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1small/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSizeSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1mini/title",
          "value": "NSControlSizeMini"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1mini/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSizeMini"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1CellType/title",
          "value": "NSCellType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1CellType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1CellType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title",
          "value": "NSControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/title",
          "value": "NSControlTint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControlTint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlTint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1large/title",
          "value": "NSControlSizeLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1ControlSize-swift.enum~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlSizeLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/title",
          "value": "NSBackgroundStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView~1BackgroundStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/title",
          "value": "controlSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1controlSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "controlSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1Attribute/title",
          "value": "NSCellAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1Attribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1Attribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCellAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/title",
          "value": "NSImageScaling"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaling"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImageScaling/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageScaling"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscontrol/controlsize-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscontrol/controlsize-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
