{"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)"},"metadata":{"platforms":[{"deprecated":false,"introducedAt":"10.7","beta":false,"name":"macOS","unavailable":false}],"title":"invalidateIntrinsicContentSize(for:)","externalID":"c:objc(cs)NSControl(im)invalidateIntrinsicContentSizeForCell:","modules":[{"name":"AppKit"}],"navigatorTitle":[{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCell","text":"NSCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","extendedModule":"AppKit","roleHeading":"Instance Method"},"variants":[{"paths":["/documentation/appkit/nscontrol/invalidateintrinsiccontentsize(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscontrol/invalidateintrinsiccontentsize(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateIntrinsicContentSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCell","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","text":"NSCell"},{"kind":"text","text":")"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The cell whose intrinsic content size has changed.","type":"text"}],"type":"paragraph"}],"name":"cell"}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"Controls determine their intrinsic content size based on the cell size for a given bounds returned by their cell. When the content of the cell changes in a way that would change the return value of "},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","isActive":true,"type":"reference"},{"type":"text","text":", the cell needs to call this method to notify its control that its intrinsic size is no longer valid."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Notifies the control that the intrinsic content size for its cell is no longer valid.","type":"text"}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCell":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","abstract":[{"type":"text","text":"A mechanism for displaying text or images in a view object without the overhead of a full "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView"},{"type":"text","text":" subclass."}],"role":"symbol","navigatorTitle":[{"text":"NSCell","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCell","kind":"identifier"}],"title":"NSCell","kind":"symbol","url":"/documentation/appkit/nscell","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)":{"url":"/documentation/appkit/nscontrol/invalidateintrinsiccontentsize(for:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/invalidateIntrinsicContentSize(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidateIntrinsicContentSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCell","text":"NSCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"invalidateIntrinsicContentSize(for:)","abstract":[{"text":"Notifies the control that the intrinsic content size for its cell is no longer valid.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSView":{"abstract":[{"text":"The infrastructure for drawing, printing, and handling events in an app.","type":"text"}],"url":"/documentation/appkit/nsview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSView"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSView","title":"NSView","navigatorTitle":[{"kind":"identifier","text":"NSView"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)":{"type":"topic","abstract":[{"type":"text","text":"Returns the minimum size needed to display the receiver, constraining it to the specified rectangle."}],"title":"cellSize(forBounds:)","url":"/documentation/appkit/nscell/cellsize(forbounds:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRect","preciseIdentifier":"c:@T@NSRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"NSSize","preciseIdentifier":"c:@T@NSSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cellSizeForBounds:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell/cellSize(forBounds:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"name":"macOS","introducedAt":"10.7","deprecated":false,"beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"invalidateIntrinsicContentSizeForCell:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"path":"/metadata/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateIntrinsicContentSizeForCell:"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]}},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCell","text":"NSCell","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCell","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"path":"/primaryContentSections/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The cell whose intrinsic content size has changed.","type":"text"}]}],"name":"cell"}],"kind":"parameters"},"op":"replace","path":"/primaryContentSections/1"},{"op":"replace","value":"NSCell","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/title"},{"op":"replace","value":[{"text":"NSCell","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCell"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell/navigatorTitle"},{"op":"replace","value":"invalidateIntrinsicContentSizeForCell:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1invalidateIntrinsicContentSize(for:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"invalidateIntrinsicContentSizeForCell:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1invalidateIntrinsicContentSize(for:)/fragments"},{"op":"replace","value":"NSControl","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title"},{"op":"replace","value":[{"text":"NSControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments"},{"op":"replace","value":[{"text":"NSControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle"},{"op":"replace","value":"NSView","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/title"},{"value":[{"kind":"identifier","text":"NSView"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/fragments"},{"value":[{"text":"NSView","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSView/navigatorTitle"},{"value":"cellSizeForBounds:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"cellSizeForBounds:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCell~1cellSize(forBounds:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}