{"abstract":[{"type":"text","text":"A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking."}],"metadata":{"modules":[{"name":"AppKit"}],"role":"symbol","navigatorTitle":[{"text":"continuous","kind":"identifier"}],"platforms":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContinuous","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isContinuous","externalID":"c:objc(cs)NSControl(py)continuous","roleHeading":"Instance Property"},"kind":"symbol","sections":[],"seeAlsoSections":[{"anchor":"Implementing-the-Target-Action-Mechanism","title":"Implementing the Target-Action Mechanism","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControl/action","doc://com.apple.appkit/documentation/AppKit/NSControl/target","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContinuous","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"Discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of this property is "},{"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference","isActive":true},{"type":"text","text":" if the action message is sent continuously; otherwise, "},{"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscontrol/iscontinuous"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscontrol/iscontinuous"]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)":{"abstract":[{"type":"text","text":"Sets the conditions on which the receiver sends action messages to its target."}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)","role":"symbol","title":"sendAction(on:)","kind":"symbol","url":"/documentation/appkit/nscontrol/sendaction(on:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"EventTypeMask","preciseIdentifier":"c:@E@NSEventMask"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"sendActionOn:"}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isContinuous","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nscontrol/iscontinuous","title":"isContinuous","navigatorTitle":[{"text":"continuous","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/isContinuous","abstract":[{"type":"text","text":"A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking."}]},"doc://com.apple.appkit/documentation/AppKit/NSControl/target":{"url":"/documentation/appkit/nscontrol/target","title":"target","abstract":[{"text":"The target object that receives action messages from the cell.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/target","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"target","kind":"identifier"},{"text":": AnyObject?","kind":"text"}],"navigatorTitle":[{"text":"target","kind":"identifier"}],"role":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSControl/action":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Selector","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"action","kind":"identifier"}],"role":"symbol","title":"action","type":"topic","kind":"symbol","url":"/documentation/appkit/nscontrol/action","abstract":[{"type":"text","text":"The default action-message selector associated with the control."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/action"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","type":"topic","role":"symbol","kind":"symbol"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSControl":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl","navigatorTitle":[{"kind":"identifier","text":"NSControl"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSControl"}],"title":"NSControl","role":"symbol","abstract":[{"text":"A specialized view, such as a button or text field, that notifies your app of relevant events using the target-action design pattern.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscontrol"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)":{"type":"topic","abstract":[{"type":"text","text":"Causes the specified action to be sent to the target."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","url":"/documentation/appkit/nscontrol/sendaction(_:to:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"sendAction:to:"}],"title":"sendAction(_:to:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"macOS","deprecated":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Instance Property","path":"/metadata/roleHeading","op":"replace"},{"value":"continuous","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"continuous"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSControl"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":[{"generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSControl/action","doc://com.apple.appkit/documentation/AppKit/NSControl/target","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(_:to:)","doc://com.apple.appkit/documentation/AppKit/NSControl/sendAction(on:)"],"anchor":"Implementing-the-Target-Action-Mechanism","title":"Implementing the Target-Action Mechanism"}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"getter"},{"kind":"text","text":"="},{"kind":"identifier","text":"isContinuous"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"continuous"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"sendActionOn:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(on:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendActionOn:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(on:)/fragments"},{"op":"replace","value":"continuous","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/title"},{"op":"replace","value":[{"kind":"identifier","text":"continuous"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1isContinuous/fragments"},{"op":"replace","value":"target","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/title"},{"op":"replace","value":[{"kind":"identifier","text":"target"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1target/fragments"},{"op":"replace","value":"action","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/title"},{"op":"replace","value":[{"kind":"identifier","text":"action"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1action/fragments"},{"op":"replace","value":"NSControl","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSControl"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSControl"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl/navigatorTitle"},{"op":"replace","value":"sendAction:to:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(_:to:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendAction:to:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSControl~1sendAction(_:to:)/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}