{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The button state when AirPlay is active.","type":"text"}],"seeAlsoSections":[{"anchor":"Button-States","identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"],"title":"Button States","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/avkit/avroutepickerview/buttonstate/active"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/avkit/avroutepickerview/buttonstate/active"]}],"identifier":{"url":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"active"}],"navigatorTitle":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateActive"}],"role":"symbol","symbolKind":"case","externalID":"c:@E@AVRoutePickerViewButtonState@AVRoutePickerViewButtonStateActive","title":"AVRoutePickerView.ButtonState.active","platforms":[{"beta":false,"unavailable":false,"introducedAt":"10.15","name":"macOS","deprecated":false}],"roleHeading":"Case","modules":[{"name":"AVKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"]]},"sections":[],"references":{"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active":{"role":"symbol","kind":"symbol","title":"AVRoutePickerView.ButtonState.active","type":"topic","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateActive","kind":"identifier"}],"abstract":[{"type":"text","text":"The button state when AirPlay is active."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active","url":"/documentation/avkit/avroutepickerview/buttonstate/active"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","title":"Technologies","role":"overview"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState":{"type":"topic","title":"AVRoutePickerView.ButtonState","url":"/documentation/avkit/avroutepickerview/buttonstate","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ButtonState"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ButtonState"}],"abstract":[{"type":"text","text":"Constants that describe the available button states."}]},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView":{"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView","title":"AVRoutePickerView","abstract":[{"type":"text","text":"A view that presents a list of nearby media receivers."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AVRoutePickerView","kind":"identifier"}],"url":"/documentation/avkit/avroutepickerview","navigatorTitle":[{"text":"AVRoutePickerView","kind":"identifier"}],"type":"topic"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted":{"abstract":[{"text":"The highlighted button state when AirPlay is active.","type":"text"}],"type":"topic","url":"/documentation/avkit/avroutepickerview/buttonstate/activehighlighted","title":"AVRoutePickerView.ButtonState.activeHighlighted","identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted","kind":"symbol","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateActiveHighlighted","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeHighlighted","kind":"identifier"}],"role":"symbol"},"doc://com.apple.avkit/documentation/AVKit":{"identifier":"doc://com.apple.avkit/documentation/AVKit","type":"topic","url":"/documentation/avkit","abstract":[{"type":"text","text":"Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions."}],"kind":"symbol","title":"AVKit","role":"collection"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted":{"role":"symbol","kind":"symbol","title":"AVRoutePickerView.ButtonState.normalHighlighted","type":"topic","navigatorTitle":[{"text":"AVRoutePickerViewButtonStateNormalHighlighted","kind":"identifier"}],"abstract":[{"type":"text","text":"The highlighted button state when a mouse-down event occurs inside the button."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalHighlighted"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","url":"/documentation/avkit/avroutepickerview/buttonstate/normalhighlighted"},"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal":{"type":"topic","kind":"symbol","title":"AVRoutePickerView.ButtonState.normal","role":"symbol","url":"/documentation/avkit/avroutepickerview/buttonstate/normal","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"normal","kind":"identifier"}],"identifier":"doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","abstract":[{"type":"text","text":"The normal, or default, button state."}],"navigatorTitle":[{"text":"AVRoutePickerViewButtonStateNormal","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":false,"introducedAt":"10.15","name":"macOS","beta":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration Case","op":"replace","path":"/metadata/roleHeading"},{"value":"AVRoutePickerViewButtonStateActive","op":"replace","path":"/metadata/title"},{"value":"case","op":"replace","path":"/metadata/symbolKind"},{"value":[{"text":"AVRoutePickerViewButtonStateActive","kind":"identifier"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.avkit/documentation/AVKit","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":[{"identifiers":["doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted","doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"],"anchor":"Button-States","generated":true,"title":"Button States"}],"op":"replace","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"tokens":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateActive"}],"languages":["occ"]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":"AVRoutePickerViewButtonStateActive","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/title","op":"replace"},{"value":[{"text":"AVRoutePickerViewButtonStateActive","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/fragments","op":"replace"},{"value":"AVRoutePickerViewButtonState","path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/title","op":"replace"},{"value":[{"kind":"identifier","text":"AVRoutePickerViewButtonState"}],"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/fragments","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/navigatorTitle","value":[{"text":"AVRoutePickerViewButtonState","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title","value":"AVRoutePickerView","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments","value":[{"kind":"identifier","text":"AVRoutePickerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle","value":[{"kind":"identifier","text":"AVRoutePickerView"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/title","value":"AVRoutePickerViewButtonStateActiveHighlighted","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/fragments","value":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateActiveHighlighted"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/title","value":"AVRoutePickerViewButtonStateNormalHighlighted","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/fragments","value":[{"text":"AVRoutePickerViewButtonStateNormalHighlighted","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/title","value":"AVRoutePickerViewButtonStateNormal","op":"replace"},{"path":"/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/fragments","value":[{"kind":"identifier","text":"AVRoutePickerViewButtonStateNormal"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}