{
  "abstract": [
    {
      "text": "The highlighted button state when a mouse-down event occurs inside the button.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.avkit/documentation/AVKit",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@AVRoutePickerViewButtonState@AVRoutePickerViewButtonStateNormalHighlighted",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "normalHighlighted"
      }
    ],
    "modules": [
      {
        "name": "AVKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AVRoutePickerViewButtonStateNormalHighlighted"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "AVRoutePickerView.ButtonState.normalHighlighted"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "normalHighlighted"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.avkit/documentation/AVKit": {
      "abstract": [
        {
          "text": "Create user interfaces for media playback, complete with transport controls, chapter navigation, picture-in-picture support, and display of subtitles and closed captions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AVKit",
      "type": "topic",
      "url": "/documentation/avkit"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView": {
      "abstract": [
        {
          "text": "A view that presents a list of nearby media receivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerView"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState": {
      "abstract": [
        {
          "text": "Constants that describe the available button states.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonState"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active": {
      "abstract": [
        {
          "text": "The button state when AirPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "active"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStateActive"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState.active",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate/active"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted": {
      "abstract": [
        {
          "text": "The highlighted button state when AirPlay is active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeHighlighted"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStateActiveHighlighted"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState.activeHighlighted",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate/activehighlighted"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal": {
      "abstract": [
        {
          "text": "The normal, or default, button state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStateNormal"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState.normal",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate/normal"
    },
    "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted": {
      "abstract": [
        {
          "text": "The highlighted button state when a mouse-down event occurs inside the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normalHighlighted"
        }
      ],
      "identifier": "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normalHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AVRoutePickerViewButtonStateNormalHighlighted"
        }
      ],
      "role": "symbol",
      "title": "AVRoutePickerView.ButtonState.normalHighlighted",
      "type": "topic",
      "url": "/documentation/avkit/avroutepickerview/buttonstate/normalhighlighted"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Button-States",
      "generated": true,
      "identifiers": [
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active",
        "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"
      ],
      "title": "Button States"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.15",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AVRoutePickerViewButtonStateNormalHighlighted"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStateNormalHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.avkit/documentation/AVKit",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Button-States",
              "generated": true,
              "identifiers": [
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/normal",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/active",
                "doc://com.apple.avkit/documentation/AVKit/AVRoutePickerView/ButtonState/activeHighlighted"
              ],
              "title": "Button States"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "AVRoutePickerViewButtonStateNormalHighlighted"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/title",
          "value": "AVRoutePickerViewButtonStateNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStateNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/title",
          "value": "AVRoutePickerViewButtonStateActive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1active/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStateActive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/title",
          "value": "AVRoutePickerViewButtonStateActiveHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1activeHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStateActiveHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/title",
          "value": "AVRoutePickerViewButtonStateNormalHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState~1normalHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonStateNormalHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/title",
          "value": "AVRoutePickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/title",
          "value": "AVRoutePickerViewButtonState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.avkit~1documentation~1AVKit~1AVRoutePickerView~1ButtonState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AVRoutePickerViewButtonState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/avkit/avroutepickerview/buttonstate/normalhighlighted"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/avkit/avroutepickerview/buttonstate/normalhighlighted"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
