{
  "abstract": [
    {
      "text": "A value indicating how the view’s contents blend with the surrounding content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/blendingMode-swift.property"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSVisualEffectView(py)blendingMode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "blendingMode"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSVisualEffectView",
        "text": "NSVisualEffectView"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@NSVisualEffectBlendingMode",
        "text": "BlendingMode"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "blendingMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "blendingMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "blendingMode"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSVisualEffectView",
              "text": "NSVisualEffectView"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSVisualEffectBlendingMode",
              "text": "BlendingMode"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the value of this property is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/behindWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (the default), the visual effect view blurs the content behind the window. When the value is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/withinWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", it blurs the content behind the view of the current window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the visual effect view’s material is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", set the blending mode to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/withinWindow",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView": {
      "abstract": [
        {
          "text": "A view that adds translucency and vibrancy effects to the views in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify whether the visual effect view blends with what’s either behind or within the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BlendingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BlendingMode"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.BlendingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/blendingmode-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/behindWindow": {
      "abstract": [
        {
          "text": "A mode that blends and blurs the visual effect view with the contents behind the window, such as the desktop or other windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behindWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/behindWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectBlendingModeBehindWindow"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.BlendingMode.behindWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/blendingmode-swift.enum/behindwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/withinWindow": {
      "abstract": [
        {
          "text": "A mode that blends and blurs the visual effect view with contents behind the view in the current window only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "withinWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum/withinWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectBlendingModeWithinWindow"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.BlendingMode.withinWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/blendingmode-swift.enum/withinwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar": {
      "abstract": [
        {
          "text": "The material for a window’s titlebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titlebar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialTitlebar"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.titlebar",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/titlebar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/blendingMode-swift.property": {
      "abstract": [
        {
          "text": "A value indicating how the view’s contents blend with the surrounding content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "blendingMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSVisualEffectView",
          "text": "NSVisualEffectView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSVisualEffectBlendingMode",
          "text": "BlendingMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/blendingMode-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "blendingMode"
        }
      ],
      "role": "symbol",
      "title": "blendingMode",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/blendingmode-swift.property"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/interiorBackgroundStyle": {
      "abstract": [
        {
          "text": "The view’s interior background style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interiorBackgroundStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSBackgroundStyle",
          "text": "BackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/interiorBackgroundStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interiorBackgroundStyle"
        }
      ],
      "role": "symbol",
      "title": "interiorBackgroundStyle",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/interiorbackgroundstyle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/isEmphasized": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether to emphasize the look of the material.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEmphasized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/isEmphasized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emphasized"
        }
      ],
      "role": "symbol",
      "title": "isEmphasized",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/isemphasized"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-Effect-Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/isEmphasized",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/interiorBackgroundStyle"
      ],
      "title": "Specifying the Effect Appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "blendingMode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blendingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-Effect-Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/isEmphasized",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/interiorBackgroundStyle"
              ],
              "title": "Specifying the Effect Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/BlendingMode-swift.enum",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@NSVisualEffectBlendingMode",
                    "text": "NSVisualEffectBlendingMode"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "blendingMode"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1blendingMode-swift.property/title",
          "value": "blendingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1blendingMode-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "blendingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum~1behindWindow/title",
          "value": "NSVisualEffectBlendingModeBehindWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum~1behindWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectBlendingModeBehindWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/title",
          "value": "NSVisualEffectMaterialTitlebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialTitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/title",
          "value": "NSVisualEffectView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1isEmphasized/title",
          "value": "emphasized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1isEmphasized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "emphasized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1interiorBackgroundStyle/title",
          "value": "interiorBackgroundStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1interiorBackgroundStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interiorBackgroundStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum/title",
          "value": "NSVisualEffectBlendingMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectBlendingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectBlendingMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum~1withinWindow/title",
          "value": "NSVisualEffectBlendingModeWithinWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1BlendingMode-swift.enum~1withinWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectBlendingModeWithinWindow"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/blendingmode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/blendingmode-swift.property"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
