{
  "abstract": [
    {
      "text": "Constants to specify the material shown by the visual effect view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSVisualEffectMaterial",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "Material"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "Material"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSVisualEffectView.Material"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "Material"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView": {
      "abstract": [
        {
          "text": "A view that adds translucency and vibrancy effects to the views in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectView"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum": {
      "abstract": [
        {
          "text": "Constants to specify the material shown by the visual effect view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Material"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/appearanceBased": {
      "abstract": [
        {
          "text": "A default material for the view’s effective appearance.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearanceBased"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/appearanceBased",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialAppearanceBased"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.appearanceBased",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/appearancebased"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground": {
      "abstract": [
        {
          "text": "The material for the background of opaque content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialContentBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.contentBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/contentbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/dark": {
      "abstract": [
        {
          "text": "A material with a dark effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dark"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/dark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialDark"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.dark",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/dark"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI": {
      "abstract": [
        {
          "text": "The material for the background of a full-screen modal interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullScreenUI"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialFullScreenUI"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.fullScreenUI",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/fullscreenui"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView": {
      "abstract": [
        {
          "text": "The material for in-line header or footer views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headerView"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialHeaderView"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.headerView",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/headerview"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow": {
      "abstract": [
        {
          "text": "The material for the background of heads-up display (HUD) windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hudWindow"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialHUDWindow"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.hudWindow",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/hudwindow"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/light": {
      "abstract": [
        {
          "text": "A material with a light effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "light"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/light",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialLight"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.light",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/light"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/mediumLight": {
      "abstract": [
        {
          "text": "A material with a medium-light effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mediumLight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/mediumLight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialMediumLight"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.mediumLight",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/mediumlight"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu": {
      "abstract": [
        {
          "text": "The material for menus.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menu"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialMenu"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.menu",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/menu"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover": {
      "abstract": [
        {
          "text": "The material for the background of popover windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popover"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialPopover"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.popover",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/popover"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection": {
      "abstract": [
        {
          "text": "The material used to indicate a selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSelection"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.selection",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/selection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet": {
      "abstract": [
        {
          "text": "The material for the background of sheet windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sheet"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSheet"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.sheet",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/sheet"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar": {
      "abstract": [
        {
          "text": "The material for the background of window sidebars.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialSidebar"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.sidebar",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/sidebar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar": {
      "abstract": [
        {
          "text": "The material for a window’s titlebar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titlebar"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialTitlebar"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.titlebar",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/titlebar"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip": {
      "abstract": [
        {
          "text": "The material for the background of a tool tip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialToolTip"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.toolTip",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/tooltip"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/ultraDark": {
      "abstract": [
        {
          "text": "A material with an ultra-dark effect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ultraDark"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/ultraDark",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialUltraDark"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.ultraDark",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/ultradark"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground": {
      "abstract": [
        {
          "text": "The material for the area behind the pages of a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underPageBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialUnderPageBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.underPageBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/underpagebackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground": {
      "abstract": [
        {
          "text": "The material to show under a window’s background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "underWindowBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialUnderWindowBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.underWindowBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/underwindowbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground": {
      "abstract": [
        {
          "text": "The material for the background of opaque windows.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windowBackground"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVisualEffectMaterialWindowBackground"
        }
      ],
      "role": "symbol",
      "title": "NSVisualEffectView.Material.windowBackground",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.enum/windowbackground"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/material-swift.property": {
      "abstract": [
        {
          "text": "The material shown by the visual effect view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "material"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSVisualEffectView",
          "text": "NSVisualEffectView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSVisualEffectMaterial",
          "text": "Material"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/material-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "material"
        }
      ],
      "role": "symbol",
      "title": "material",
      "type": "topic",
      "url": "/documentation/appkit/nsvisualeffectview/material-swift.property"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-the-Background-Material",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/material-swift.property"
      ],
      "title": "Specifying the Background Material"
    }
  ],
  "topicSections": [
    {
      "anchor": "Material-Types",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground"
      ],
      "title": "Material Types"
    },
    {
      "anchor": "Deprecated-Materials",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/appearanceBased",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/light",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/dark",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/mediumLight",
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/ultraDark"
      ],
      "title": "Deprecated Materials"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSVisualEffectMaterial"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Material-Types",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/titlebar",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/selection",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/menu",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/popover",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sidebar",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/headerView",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/sheet",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/windowBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/hudWindow",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/fullScreenUI",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/toolTip",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/contentBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underWindowBackground",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/underPageBackground"
              ],
              "title": "Material Types"
            },
            {
              "anchor": "Deprecated-Materials",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/appearanceBased",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/light",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/dark",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/mediumLight",
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/Material-swift.enum/ultraDark"
              ],
              "title": "Deprecated Materials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Specifying-the-Background-Material",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSVisualEffectView/material-swift.property"
              ],
              "title": "Specifying the Background Material"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSVisualEffectMaterial"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1mediumLight/title",
          "value": "NSVisualEffectMaterialMediumLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1mediumLight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialMediumLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1windowBackground/title",
          "value": "NSVisualEffectMaterialWindowBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1windowBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialWindowBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1menu/title",
          "value": "NSVisualEffectMaterialMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1menu/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1contentBackground/title",
          "value": "NSVisualEffectMaterialContentBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1contentBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialContentBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1light/title",
          "value": "NSVisualEffectMaterialLight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1light/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialLight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1ultraDark/title",
          "value": "NSVisualEffectMaterialUltraDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1ultraDark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUltraDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1selection/title",
          "value": "NSVisualEffectMaterialSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1selection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1toolTip/title",
          "value": "NSVisualEffectMaterialToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1popover/title",
          "value": "NSVisualEffectMaterialPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1popover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/title",
          "value": "NSVisualEffectMaterial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1fullScreenUI/title",
          "value": "NSVisualEffectMaterialFullScreenUI"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1fullScreenUI/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialFullScreenUI"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1appearanceBased/title",
          "value": "NSVisualEffectMaterialAppearanceBased"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1appearanceBased/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialAppearanceBased"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1dark/title",
          "value": "NSVisualEffectMaterialDark"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1dark/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialDark"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sidebar/title",
          "value": "NSVisualEffectMaterialSidebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sidebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSidebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underPageBackground/title",
          "value": "NSVisualEffectMaterialUnderPageBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underPageBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUnderPageBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/title",
          "value": "NSVisualEffectView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1hudWindow/title",
          "value": "NSVisualEffectMaterialHUDWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1hudWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialHUDWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underWindowBackground/title",
          "value": "NSVisualEffectMaterialUnderWindowBackground"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1underWindowBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialUnderWindowBackground"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1material-swift.property/title",
          "value": "material"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1material-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "material"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/title",
          "value": "NSVisualEffectMaterialTitlebar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1titlebar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialTitlebar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1headerView/title",
          "value": "NSVisualEffectMaterialHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1headerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sheet/title",
          "value": "NSVisualEffectMaterialSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSVisualEffectView~1Material-swift.enum~1sheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSVisualEffectMaterialSheet"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/material-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nsvisualeffectview/material-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
