{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes/init(address:name:serviceClassMajor:deviceClassMajor:deviceClassMinor:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So023IOBluetoothDeviceSearchB10AttributesV7address4name17serviceClassMajor06devicehI00jH5MinorABSo09BluetoothB7AddressV_s5UInt8V_A247Kts6UInt32VA2Mtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "address"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
        "text": "BluetoothDeviceAddress"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "name"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothDeviceName",
        "text": "BluetoothDeviceName"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "serviceClassMajor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothServiceClassMajor",
        "text": "BluetoothServiceClassMajor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "deviceClassMajor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothDeviceClassMajor",
        "text": "BluetoothDeviceClassMajor"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "deviceClassMinor"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothDeviceClassMinor",
        "text": "BluetoothDeviceClassMinor"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(address:name:serviceClassMajor:deviceClassMajor:deviceClassMinor:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "address"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
              "text": "BluetoothDeviceAddress"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothDeviceName",
              "text": "BluetoothDeviceName"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "serviceClassMajor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothServiceClassMajor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothServiceClassMajor",
              "text": "BluetoothServiceClassMajor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "deviceClassMajor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothDeviceClassMajor",
              "text": "BluetoothDeviceClassMajor"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "deviceClassMinor"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothDeviceClassMinor",
              "text": "BluetoothDeviceClassMinor"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceAddress"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceAddress",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceaddress"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceClassMinor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceClassMinor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceClassMinor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdeviceclassminor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothDeviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothDeviceName"
        }
      ],
      "role": "symbol",
      "title": "BluetoothDeviceName",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothdevicename"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothServiceClassMajor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothServiceClassMajor"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothServiceClassMajor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothServiceClassMajor"
        }
      ],
      "role": "symbol",
      "title": "BluetoothServiceClassMajor",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothserviceclassmajor"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes": {
      "abstract": [
        {
          "text": "Structure used to search for particular devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchDeviceAttributes"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "IOBluetoothDeviceSearchDeviceAttributes"
        }
      ],
      "role": "symbol",
      "title": "IOBluetoothDeviceSearchDeviceAttributes",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchdeviceattributes"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes/init(address:name:serviceClassMajor:deviceClassMajor:deviceClassMinor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "address"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@BluetoothDeviceAddress",
          "text": "BluetoothDeviceAddress"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothDeviceName",
          "text": "BluetoothDeviceName"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "serviceClassMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothServiceClassMajor",
          "text": "BluetoothServiceClassMajor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceClassMajor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothDeviceClassMajor",
          "text": "BluetoothDeviceClassMajor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "deviceClassMinor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothDeviceClassMinor",
          "text": "BluetoothDeviceClassMinor"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/IOBluetoothDeviceSearchDeviceAttributes/init(address:name:serviceClassMajor:deviceClassMajor:deviceClassMinor:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(address:name:serviceClassMajor:deviceClassMajor:deviceClassMinor:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/iobluetoothdevicesearchdeviceattributes/init(address:name:serviceclassmajor:deviceclassmajor:deviceclassminor:)"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/title",
          "value": "BluetoothDeviceAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceAddress/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothServiceClassMajor/title",
          "value": "BluetoothServiceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothServiceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothServiceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothServiceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothServiceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/title",
          "value": "BluetoothDeviceClassMinor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMinor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMinor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/title",
          "value": "BluetoothDeviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/title",
          "value": "IOBluetoothDeviceSearchDeviceAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchDeviceAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1IOBluetoothDeviceSearchDeviceAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "IOBluetoothDeviceSearchDeviceAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/title",
          "value": "BluetoothDeviceClassMajor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothDeviceClassMajor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothDeviceClassMajor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/iobluetoothdevicesearchdeviceattributes/init(address:name:serviceclassmajor:deviceclassmajor:deviceclassminor:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
