{
  "abstract": [
    {
      "text": "A Final Cut Pro timeline sequence.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@FCPXObjectType@kFCPXObjectType_Sequence",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sequence"
      }
    ],
    "modules": [
      {
        "name": "Professional Video Applications"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kFCPXObjectType_Sequence"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "1.0",
        "name": "ProVideo Workflow Extensions"
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "FCPXObjectType.sequence"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Unsupported OS: ProExtensionHost"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sequence"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications": {
      "abstract": [
        {
          "text": "Exchange data with Final Cut Pro, and create effects plug-ins for Final Cut Pro and Motion.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
      "kind": "symbol",
      "role": "collection",
      "title": "Professional Video Applications",
      "type": "topic",
      "url": "/documentation/professional_video_applications"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType": {
      "abstract": [
        {
          "text": "The Final Cut Pro timeline object types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FCPXObjectType"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FCPXObjectType"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "event"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Event"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.event",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/event"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline library.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "library"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Library"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.library",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/library"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline project.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "project"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Project"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.project",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/project"
    },
    "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence": {
      "abstract": [
        {
          "text": "A Final Cut Pro timeline sequence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sequence"
        }
      ],
      "identifier": "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/sequence",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kFCPXObjectType_Sequence"
        }
      ],
      "role": "symbol",
      "title": "FCPXObjectType.sequence",
      "type": "topic",
      "url": "/documentation/professional_video_applications/fcpxobjecttype/sequence"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Final-Cut-Pro-Timeline-Object-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
        "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project"
      ],
      "title": "Final Cut Pro Timeline Object Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": null
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kFCPXObjectType_Sequence"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Sequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Final-Cut-Pro-Timeline-Object-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/event",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/library",
                "doc://com.apple.professionalvideoapplications/documentation/professional_video_applications/FCPXObjectType/project"
              ],
              "title": "Final Cut Pro Timeline Object Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Unsupported OS: ProExtensionHost"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kFCPXObjectType_Sequence"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1sequence/title",
          "value": "kFCPXObjectType_Sequence"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1sequence/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Sequence"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/title",
          "value": "FCPXObjectType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FCPXObjectType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1event/title",
          "value": "kFCPXObjectType_Event"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1event/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Event"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1project/title",
          "value": "kFCPXObjectType_Project"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1project/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Project"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1library/title",
          "value": "kFCPXObjectType_Library"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.professionalvideoapplications~1documentation~1professional_video_applications~1FCPXObjectType~1library/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kFCPXObjectType_Library"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxobjecttype/sequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/professional_video_applications/fcpxobjecttype/sequence"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
