{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.corenfc/documentation/CoreNFC",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "CoreNFC",
    "externalID": "c:@E@NFCVASErrorCode",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ErrorCode"
      }
    ],
    "modules": [
      {
        "name": "Core NFC"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ErrorCode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NFCVASResponse.ErrorCode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ErrorCode"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.corenfc/documentation/CoreNFC": {
      "abstract": [
        {
          "text": "Detect NFC tags, read messages that contain NDEF data, and save data to writable tags.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC",
      "kind": "symbol",
      "role": "collection",
      "title": "Core NFC",
      "type": "topic",
      "url": "/documentation/corenfc"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaEncryptionId"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaEncryptionId"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaEncryptionId",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicaencryptionid"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingRequestCode"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingRequestCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingrequestcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingTimeSlot"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCFeliCaPollingTimeSlot"
        }
      ],
      "role": "symbol",
      "title": "NFCFeliCaPollingTimeSlot",
      "type": "topic",
      "url": "/documentation/corenfc/nfcfelicapollingtimeslot"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693RequestFlag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693RequestFlag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693RequestFlag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693requestflag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCISO15693ResponseFlag"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCISO15693ResponseFlag"
        }
      ],
      "role": "symbol",
      "title": "NFCISO15693ResponseFlag",
      "type": "topic",
      "url": "/documentation/corenfc/nfciso15693responseflag"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mode"
        }
      ],
      "role": "symbol",
      "title": "NFCVASCommandConfiguration.Mode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvascommandconfiguration/mode-swift.enum"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse": {
      "abstract": [
        {
          "text": "An object representing the response from a single ",
          "type": "text"
        },
        {
          "code": "GET VAS DATA",
          "type": "codeVoice"
        },
        {
          "text": " command.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NFCVASResponse"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASResponse"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ErrorCode"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated": {
      "abstract": [
        {
          "text": "A constant indicating that the data isn’t activated.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotActivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotActivated"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeDataNotActivated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodedatanotactivated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound": {
      "abstract": [
        {
          "text": "A constant indicating that data wasn’t found.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotFound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeDataNotFound"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeDataNotFound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodedatanotfound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData": {
      "abstract": [
        {
          "text": "A constant indicating that the data is incorrect.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeIncorrectData"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeIncorrectData"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeIncorrectData",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeincorrectdata"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess": {
      "abstract": [
        {
          "text": "A constant indicating that the ",
          "type": "text"
        },
        {
          "code": "GET VAS DATA",
          "type": "codeVoice"
        },
        {
          "text": " command was successful.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeSuccess"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeSuccess",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodesuccess"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion": {
      "abstract": [
        {
          "text": "A constant indicating an unsupported application version.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeUnsupportedApplicationVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeUnsupportedApplicationVersion"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeUnsupportedApplicationVersion",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeunsupportedapplicationversion"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention": {
      "abstract": [
        {
          "text": "A constant indicating that the tag requires user intervention.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeUserIntervention"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeUserIntervention"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeUserIntervention",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodeuserintervention"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField": {
      "abstract": [
        {
          "text": "A constant indicating that the value in the Length Count field is wrong.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongLCField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongLCField"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeWrongLCField",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodewronglcfield"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters": {
      "abstract": [
        {
          "text": "A constant indicating that VAS command parameters are wrong.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NFCVASResponse",
          "text": "NFCVASResponse"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NFCVASErrorCode",
          "text": "ErrorCode"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VASErrorCodeWrongParameters"
        }
      ],
      "role": "symbol",
      "title": "VASErrorCodeWrongParameters",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/vaserrorcodewrongparameters"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotActivated": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataNotActivated"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeDataNotActivated"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.dataNotActivated",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/datanotactivated"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotFound": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dataNotFound"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeDataNotFound"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.dataNotFound",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/datanotfound"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/incorrectData": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "incorrectData"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/incorrectData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeIncorrectData"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.incorrectData",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/incorrectdata"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/init(rawvalue:)"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/success": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeSuccess"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.success",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/success"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/unsupportedApplicationVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedApplicationVersion"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/unsupportedApplicationVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeUnsupportedApplicationVersion"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.unsupportedApplicationVersion",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/unsupportedapplicationversion"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/userIntervention": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userIntervention"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/userIntervention",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeUserIntervention"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.userIntervention",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/userintervention"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongLCField": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongLCField"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongLCField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeWrongLCField"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.wrongLCField",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/wronglcfield"
    },
    "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongParameters": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wrongParameters"
        }
      ],
      "identifier": "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NFCVASErrorCodeWrongParameters"
        }
      ],
      "role": "symbol",
      "title": "NFCVASResponse.ErrorCode.wrongParameters",
      "type": "topic",
      "url": "/documentation/corenfc/nfcvasresponse/errorcode/wrongparameters"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotActivated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotFound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/incorrectData",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/success",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/unsupportedApplicationVersion",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/userIntervention",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongLCField",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongParameters"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
        "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters"
      ],
      "title": "Type Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NFCVASErrorCode"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.corenfc/documentation/CoreNFC"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotActivated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeDataNotFound",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeIncorrectData",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeSuccess",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUnsupportedApplicationVersion",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeUserIntervention",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongLCField",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/VASErrorCodeWrongParameters",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotActivated",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/dataNotFound",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/incorrectData",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/success",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/unsupportedApplicationVersion",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/userIntervention",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongLCField",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASResponse/ErrorCode/wrongParameters"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaEncryptionId",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingRequestCode",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCFeliCaPollingTimeSlot",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693RequestFlag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCISO15693ResponseFlag",
                "doc://com.apple.corenfc/documentation/CoreNFC/NFCVASCommandConfiguration/Mode-swift.enum"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NFCVASErrorCode"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongLCField/title",
          "value": "VASErrorCodeWrongLCField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongLCField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeWrongLCField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1unsupportedApplicationVersion/title",
          "value": "NFCVASErrorCodeUnsupportedApplicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1unsupportedApplicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeUnsupportedApplicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/title",
          "value": "NFCISO15693RequestFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693RequestFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693RequestFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693RequestFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1userIntervention/title",
          "value": "NFCVASErrorCodeUserIntervention"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1userIntervention/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeUserIntervention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/title",
          "value": "NFCFeliCaPollingRequestCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingRequestCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingRequestCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/title",
          "value": "NFCISO15693ResponseFlag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ResponseFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCISO15693ResponseFlag/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCISO15693ResponseFlag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeIncorrectData/title",
          "value": "VASErrorCodeIncorrectData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeIncorrectData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeIncorrectData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/title",
          "value": "NFCVASErrorCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUserIntervention/title",
          "value": "VASErrorCodeUserIntervention"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUserIntervention/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeUserIntervention"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/title",
          "value": "NFCFeliCaEncryptionId"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaEncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaEncryptionId/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaEncryptionId"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeSuccess/title",
          "value": "VASErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeSuccess/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/title",
          "value": "NFCFeliCaPollingTimeSlot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCFeliCaPollingTimeSlot/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCFeliCaPollingTimeSlot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotFound/title",
          "value": "VASErrorCodeDataNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeDataNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/title",
          "value": "NFCVASResponse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASResponse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongParameters/title",
          "value": "VASErrorCodeWrongParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeWrongParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeWrongParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1wrongLCField/title",
          "value": "NFCVASErrorCodeWrongLCField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1wrongLCField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeWrongLCField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1wrongParameters/title",
          "value": "NFCVASErrorCodeWrongParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1wrongParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeWrongParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUnsupportedApplicationVersion/title",
          "value": "VASErrorCodeUnsupportedApplicationVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeUnsupportedApplicationVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeUnsupportedApplicationVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1dataNotActivated/title",
          "value": "NFCVASErrorCodeDataNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1dataNotActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeDataNotActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1incorrectData/title",
          "value": "NFCVASErrorCodeIncorrectData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1incorrectData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeIncorrectData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/title",
          "value": "NFCVASMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASCommandConfiguration~1Mode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1dataNotFound/title",
          "value": "NFCVASErrorCodeDataNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1dataNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeDataNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotActivated/title",
          "value": "VASErrorCodeDataNotActivated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1VASErrorCodeDataNotActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "VASErrorCodeDataNotActivated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1success/title",
          "value": "NFCVASErrorCodeSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.corenfc~1documentation~1CoreNFC~1NFCVASResponse~1ErrorCode~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NFCVASErrorCodeSuccess"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/corenfc/nfcvasresponse/errorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/corenfc/nfcvasresponse/errorcode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
