{
  "abstract": [
    {
      "text": "An option to prevent Writing Tools from modifying the text in the view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSWritingToolsBehavior@NSWritingToolsBehaviorNone",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "none"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSWritingToolsBehaviorNone"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "NSWritingToolsBehavior.none"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "none"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views"
      ]
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/complete": {
      "abstract": [
        {
          "text": "An option to provide the complete Writing Tools experience for the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "complete"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/complete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehaviorComplete"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior.complete",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior/complete"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/default": {
      "abstract": [
        {
          "text": "An option to let the system determine the best way to enable Writing Tools for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehaviorDefault"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior.default",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior/default"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/limited": {
      "abstract": [
        {
          "text": "An option to provide a limited, overlay-panel experience for the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "limited"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/limited",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehaviorLimited"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior.limited",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior/limited"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none": {
      "abstract": [
        {
          "text": "An option to prevent Writing Tools from modifying the text in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehaviorNone"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior.none",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior/none"
    },
    "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views": {
      "abstract": [
        {
          "text": "Modify the behavior of Writing Tools in standard macOS text views,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and adjust your app’s behavior while the feature is active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/customizing-writing-tools-behavior-for-system-views",
      "kind": "article",
      "role": "article",
      "title": "Customizing Writing Tools behavior for AppKit views",
      "type": "topic",
      "url": "/documentation/appkit/customizing-writing-tools-behavior-for-system-views"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Writing-Tools-behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/default",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/complete",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/limited"
      ],
      "title": "Getting the Writing Tools behaviors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSWritingToolsBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Writing-Tools-behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/default",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/complete",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior/limited"
              ],
              "title": "Getting the Writing Tools behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSWritingToolsBehaviorNone"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1limited/title",
          "value": "NSWritingToolsBehaviorLimited"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1limited/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorLimited"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1complete/title",
          "value": "NSWritingToolsBehaviorComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1complete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1default/title",
          "value": "NSWritingToolsBehaviorDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1none/title",
          "value": "NSWritingToolsBehaviorNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehaviorNone"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nswritingtoolsbehavior/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nswritingtoolsbehavior/none"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
