{
  "abstract": [
    {
      "text": "The device doesn’t support the suppression of automatic pass presentation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.passkit/documentation/PassKit",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@PKAutomaticPassPresentationSuppressionResult@PKAutomaticPassPresentationSuppressionResultNotSupported",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "notSupported"
      }
    ],
    "modules": [
      {
        "name": "PassKit (Apple Pay and Wallet)"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.2",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "PKAutomaticPassPresentationSuppressionResult.notSupported"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "notSupported"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.passkit/documentation/PassKit": {
      "abstract": [
        {
          "text": "Process Apple Pay payments in your app, and create and distribute passes for the Wallet app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit",
      "kind": "symbol",
      "role": "collection",
      "title": "PassKit (Apple Pay and Wallet)",
      "type": "topic",
      "url": "/documentation/passkit"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult": {
      "abstract": [
        {
          "text": "The result of an attempt to suppress automatic pass presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResult"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting": {
      "abstract": [
        {
          "text": "The device is already presenting passes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyPresenting"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.alreadyPresenting",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/alreadypresenting"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled": {
      "abstract": [
        {
          "text": "The system canceled the suppression before calling the response handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelled"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultCancelled"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.cancelled",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/cancelled"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied": {
      "abstract": [
        {
          "text": "The user prevented the suppression, or an internal error occurred.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "denied"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultDenied"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.denied",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/denied"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported": {
      "abstract": [
        {
          "text": "The device doesn’t support the suppression of automatic pass presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notSupported"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/notSupported",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.notSupported",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/notsupported"
    },
    "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success": {
      "abstract": [
        {
          "text": "Suppression of automatic presentation successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "success"
        }
      ],
      "identifier": "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PKAutomaticPassPresentationSuppressionResultSuccess"
        }
      ],
      "role": "symbol",
      "title": "PKAutomaticPassPresentationSuppressionResult.success",
      "type": "topic",
      "url": "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/success"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
        "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.2",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "PKAutomaticPassPresentationSuppressionResultNotSupported"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.passkit/documentation/PassKit",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/alreadyPresenting",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/denied",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/cancelled",
                "doc://com.apple.passkit/documentation/PassKit/PKAutomaticPassPresentationSuppressionResult/success"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1notSupported/title",
          "value": "PKAutomaticPassPresentationSuppressionResultNotSupported"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1notSupported/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultNotSupported"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1denied/title",
          "value": "PKAutomaticPassPresentationSuppressionResultDenied"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1denied/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultDenied"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1success/title",
          "value": "PKAutomaticPassPresentationSuppressionResultSuccess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1success/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultSuccess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1alreadyPresenting/title",
          "value": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1alreadyPresenting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultAlreadyPresenting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/title",
          "value": "PKAutomaticPassPresentationSuppressionResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1cancelled/title",
          "value": "PKAutomaticPassPresentationSuppressionResultCancelled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.passkit~1documentation~1PassKit~1PKAutomaticPassPresentationSuppressionResult~1cancelled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "PKAutomaticPassPresentationSuppressionResultCancelled"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/notsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/passkit/pkautomaticpasspresentationsuppressionresult/notsupported"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
