{"kind":"symbol","variants":[{"paths":["/documentation/metal/mtlindirectcommandbufferdescriptor/maxkernelthreadgroupmemorybindcount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/metal/mtlindirectcommandbufferdescriptor/maxkernelthreadgroupmemorybindcount"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxKernelThreadgroupMemoryBindCount","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/s:Si","text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"],"languages":["swift"]}]}],"identifier":{"url":"doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor/maxKernelThreadgroupMemoryBindCount","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor"]]},"metadata":{"externalID":"c:objc(cs)MTLIndirectCommandBufferDescriptor(py)maxKernelThreadgroupMemoryBindCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxKernelThreadgroupMemoryBindCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maxKernelThreadgroupMemoryBindCount","kind":"identifier"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"introducedAt":"14.0","deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false}],"symbolKind":"property","title":"maxKernelThreadgroupMemoryBindCount","modules":[{"name":"Metal"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.metal/documentation/Metal":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc://com.apple.metal/documentation/Metal","title":"Metal","abstract":[{"text":"Render advanced 3D graphics and compute data in parallel with graphics processors.","type":"text"}],"url":"/documentation/metal"},"doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor":{"abstract":[{"text":"A configuration you create to customize an indirect command buffer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MTLIndirectCommandBufferDescriptor"}],"identifier":"doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MTLIndirectCommandBufferDescriptor"}],"title":"MTLIndirectCommandBufferDescriptor","url":"/documentation/metal/mtlindirectcommandbufferdescriptor","type":"topic"},"doc://com.externally.resolved.symbol/s:Si":{"kind":"symbol","title":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","url":"/documentation/Swift/Int","abstract":[{"text":"A signed integer value type.","type":"text"}],"fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Int","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:@T@NSUInteger":{"title":"NSUInteger","abstract":[{"text":"Describes an unsigned integer.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger","role":"symbol","url":"/documentation/objectivec/nsuinteger"},"doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor/maxKernelThreadgroupMemoryBindCount":{"navigatorTitle":[{"kind":"identifier","text":"maxKernelThreadgroupMemoryBindCount"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxKernelThreadgroupMemoryBindCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"role":"symbol","title":"maxKernelThreadgroupMemoryBindCount","identifier":"doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor/maxKernelThreadgroupMemoryBindCount","type":"topic","url":"/documentation/metal/mtlindirectcommandbufferdescriptor/maxkernelthreadgroupmemorybindcount","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","kind":"technologies","type":"topic","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies","abstract":[{"text":"","type":"text"}],"url":"/documentation/technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"iPadOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"Mac Catalyst","unavailable":false},{"beta":false,"introducedAt":"14.0","deprecated":false,"name":"macOS","unavailable":false},{"beta":false,"introducedAt":"17.0","deprecated":false,"name":"tvOS","unavailable":false},{"beta":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS","unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Property","path":"/metadata/roleHeading"},{"op":"replace","value":"maxKernelThreadgroupMemoryBindCount","path":"/metadata/title"},{"op":"replace","value":"property","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"maxKernelThreadgroupMemoryBindCount"}],"path":"/metadata/fragments"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.metal/documentation/Metal","doc://com.apple.metal/documentation/Metal/MTLIndirectCommandBufferDescriptor"]]},"path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxKernelThreadgroupMemoryBindCount"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"value":"MTLIndirectCommandBufferDescriptor","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBufferDescriptor/title","op":"replace"},{"value":[{"text":"MTLIndirectCommandBufferDescriptor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBufferDescriptor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MTLIndirectCommandBufferDescriptor"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBufferDescriptor/navigatorTitle","op":"replace"},{"value":"maxKernelThreadgroupMemoryBindCount","path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBufferDescriptor~1maxKernelThreadgroupMemoryBindCount/title","op":"replace"},{"value":[{"text":"maxKernelThreadgroupMemoryBindCount","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLIndirectCommandBufferDescriptor~1maxKernelThreadgroupMemoryBindCount/fragments","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}