{
  "abstract": [
    {
      "text": "Four unsigned normalized 16-bit values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.metal/documentation/Metal",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ushort4Normalized"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MTLVertexFormat@MTLVertexFormatUShort4Normalized",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ushort4Normalized"
      }
    ],
    "modules": [
      {
        "name": "Metal"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MTLVertexFormatUShort4Normalized"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.11",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MTLVertexFormat.ushort4Normalized"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ushort4Normalized"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.metal/documentation/Metal": {
      "abstract": [
        {
          "text": "Render advanced 3D graphics and compute data in parallel with graphics processors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal",
      "kind": "symbol",
      "role": "collection",
      "title": "Metal",
      "type": "topic",
      "url": "/documentation/metal"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat": {
      "abstract": [
        {
          "text": "Values that specify the organization of function vertex data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLVertexFormat"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormat"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char": {
      "abstract": [
        {
          "text": "One signed 8-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatChar"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.char",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/char"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2": {
      "abstract": [
        {
          "text": "Two signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.char2",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/char2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2Normalized": {
      "abstract": [
        {
          "text": "Two signed normalized 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatChar2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.char2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/char2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char3": {
      "abstract": [
        {
          "text": "Three signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.char3",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/char3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char4": {
      "abstract": [
        {
          "text": "Four signed 8-bit two’s complement values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "char4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.char4",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/char4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/charNormalized": {
      "abstract": [
        {
          "text": "One signed normalized 8-bit two’s complement value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "charNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/charNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatCharNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.charNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/charnormalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/invalid": {
      "abstract": [
        {
          "text": "An invalid vertex format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatInvalid"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.invalid",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/invalid"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar": {
      "abstract": [
        {
          "text": "One unsigned 8-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2": {
      "abstract": [
        {
          "text": "Two unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar2"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar2"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar2",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar2"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2Normalized": {
      "abstract": [
        {
          "text": "Two unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar2Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar2Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar2Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar2normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3": {
      "abstract": [
        {
          "text": "Three unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar3"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar3"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar3",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar3"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3Normalized": {
      "abstract": [
        {
          "text": "Three unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar3Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar3Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar3Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar3normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4": {
      "abstract": [
        {
          "text": "Four unsigned 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar4"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar4"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar4",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar4"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4Normalized": {
      "abstract": [
        {
          "text": "Four unsigned normalized 8-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uchar4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUChar4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.uchar4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/uchar4normalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ucharNormalized": {
      "abstract": [
        {
          "text": "One unsigned normalized 8-bit value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ucharNormalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ucharNormalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUCharNormalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.ucharNormalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/ucharnormalized"
    },
    "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ushort4Normalized": {
      "abstract": [
        {
          "text": "Four unsigned normalized 16-bit values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ushort4Normalized"
        }
      ],
      "identifier": "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ushort4Normalized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MTLVertexFormatUShort4Normalized"
        }
      ],
      "role": "symbol",
      "title": "MTLVertexFormat.ushort4Normalized",
      "type": "topic",
      "url": "/documentation/metal/mtlvertexformat/ushort4normalized"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/invalid",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char3",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char4",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ucharNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4Normalized",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/charNormalized",
        "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2Normalized"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.11",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MTLVertexFormatUShort4Normalized"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUShort4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.metal/documentation/Metal",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/invalid",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char3",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char4",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/ucharNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar2Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar3Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/uchar4Normalized",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/charNormalized",
                "doc://com.apple.metal/documentation/Metal/MTLVertexFormat/char2Normalized"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MTLVertexFormatUShort4Normalized"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1ushort4Normalized/title",
          "value": "MTLVertexFormatUShort4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1ushort4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUShort4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar/title",
          "value": "MTLVertexFormatUChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar3/title",
          "value": "MTLVertexFormatUChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1ucharNormalized/title",
          "value": "MTLVertexFormatUCharNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1ucharNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUCharNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1invalid/title",
          "value": "MTLVertexFormatInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char2Normalized/title",
          "value": "MTLVertexFormatChar2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatChar2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char/title",
          "value": "MTLVertexFormatChar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatChar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar2/title",
          "value": "MTLVertexFormatUChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char2/title",
          "value": "MTLVertexFormatChar2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatChar2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1charNormalized/title",
          "value": "MTLVertexFormatCharNormalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1charNormalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatCharNormalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar2Normalized/title",
          "value": "MTLVertexFormatUChar2Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar2Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar2Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char4/title",
          "value": "MTLVertexFormatChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatChar4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char3/title",
          "value": "MTLVertexFormatChar3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatChar3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar3Normalized/title",
          "value": "MTLVertexFormatUChar3Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar3Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar3Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat/title",
          "value": "MTLVertexFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar4Normalized/title",
          "value": "MTLVertexFormatUChar4Normalized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar4Normalized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar4Normalized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar4/title",
          "value": "MTLVertexFormatUChar4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.metal~1documentation~1Metal~1MTLVertexFormat~1uchar4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLVertexFormatUChar4"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/metal/mtlvertexformat/ushort4normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/metal/mtlvertexformat/ushort4normalized"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
