{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/opendirectory/odrecordmap/native-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/opendirectory/odrecordmap/native-swift.property"]}],"identifier":{"url":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap/native-swift.property","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"native","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"Open Directory"}],"role":"symbol","platforms":[{"beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"name":"macOS","introducedAt":"10.9","deprecated":false,"unavailable":false}],"externalID":"c:objc(cs)ODRecordMap(py)native","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"title":"native"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"kind":"symbol","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}],"title":"NSString","url":"/documentation/foundation/nsstring","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},"doc://com.apple.opendirectory/documentation/OpenDirectory":{"title":"Open Directory","role":"collection","abstract":[{"type":"text","text":"Authenticate users, and search for contact information in Open Directory and LDAP directories."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory","url":"/documentation/opendirectory"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","kind":"technologies","title":"Technologies","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"role":"overview"},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap":{"navigatorTitle":[{"kind":"identifier","text":"ODRecordMap"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap","kind":"symbol","title":"ODRecordMap","role":"symbol","abstract":[],"url":"/documentation/opendirectory/odrecordmap","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ODRecordMap"}]},"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap/native-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"identifier":"doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap/native-swift.property","role":"symbol","abstract":[],"url":"/documentation/opendirectory/odrecordmap/native-swift.property","navigatorTitle":[{"text":"native","kind":"identifier"}],"kind":"symbol","type":"topic","title":"native"},"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"String"}],"title":"String","url":"/documentation/Swift/String","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}],"identifier":"doc://com.externally.resolved.symbol/s:SS"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"10.9","beta":false,"deprecated":false,"unavailable":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Property","op":"replace","path":"/metadata/roleHeading"},{"value":"native","op":"replace","path":"/metadata/title"},{"value":"property","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"native"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.opendirectory/documentation/OpenDirectory","doc://com.apple.opendirectory/documentation/OpenDirectory/ODRecordMap"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"value":null,"op":"add","path":"/relationshipsSections"},{"value":null,"op":"add","path":"/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"native","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"/primaryContentSections/0"},{"value":[{"text":"A static, plain-text Unicode string object.","type":"text"}],"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract"},{"value":"ODRecordMap","op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/title"},{"value":[{"text":"ODRecordMap","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/fragments"},{"value":[{"kind":"identifier","text":"ODRecordMap"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap/navigatorTitle"},{"value":"native","op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap~1native-swift.property/title"},{"value":[{"text":"native","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.opendirectory~1documentation~1OpenDirectory~1ODRecordMap~1native-swift.property/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}