{
  "abstract": [
    {
      "text": "The block that the output unit will call to get audio to send to the output.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/outputProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AudioToolbox",
    "externalID": "c:objc(cs)AUAudioUnit(py)outputProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outputProvider"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@AURenderPullInputBlock",
        "text": "AURenderPullInputBlock"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Audio Toolbox"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "outputProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "outputProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outputProvider"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@AURenderPullInputBlock",
              "text": "AURenderPullInputBlock"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This block must be set if output is enabled.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox": {
      "abstract": [
        {
          "text": "Record or play audio, convert formats, parse audio streams, and configure your audio session.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
      "kind": "symbol",
      "role": "collection",
      "title": "Audio Toolbox",
      "type": "topic",
      "url": "/documentation/audiotoolbox"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit": {
      "abstract": [
        {
          "text": "A class that defines a host’s interface to an audio unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AUAudioUnit"
        }
      ],
      "role": "symbol",
      "title": "AUAudioUnit",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformInput": {
      "abstract": [
        {
          "text": "Determines whether the I/O device can perform input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformInput"
        }
      ],
      "role": "symbol",
      "title": "canPerformInput",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/canperforminput"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformOutput": {
      "abstract": [
        {
          "text": "Determines whether the I/O device can perform output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformOutput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformOutput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformOutput"
        }
      ],
      "role": "symbol",
      "title": "canPerformOutput",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/canperformoutput"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceID": {
      "abstract": [
        {
          "text": "Gets the I/O hardware device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUAudioObjectID",
          "text": "AUAudioObjectID"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceID"
        }
      ],
      "role": "symbol",
      "title": "deviceID",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/deviceid"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceInputLatency": {
      "abstract": [
        {
          "text": "The audio device’s input latency, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceInputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceInputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceInputLatency"
        }
      ],
      "role": "symbol",
      "title": "deviceInputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/deviceinputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceOutputLatency": {
      "abstract": [
        {
          "text": "The audio devic’s output latency, in seconds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deviceOutputLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceOutputLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deviceOutputLatency"
        }
      ],
      "role": "symbol",
      "title": "deviceOutputLatency",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/deviceoutputlatency"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/inputHandler": {
      "abstract": [
        {
          "text": "The block that the output unit will call to notify when input is available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUInputHandler",
          "text": "AUInputHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/inputHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputHandler"
        }
      ],
      "role": "symbol",
      "title": "inputHandler",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/inputhandler"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isInputEnabled": {
      "abstract": [
        {
          "text": "A flag enabling audio input from the unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isInputEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isInputEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputEnabled"
        }
      ],
      "role": "symbol",
      "title": "isInputEnabled",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/isinputenabled"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isOutputEnabled": {
      "abstract": [
        {
          "text": "A flag enabling audio output from the unit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOutputEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isOutputEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputEnabled"
        }
      ],
      "role": "symbol",
      "title": "isOutputEnabled",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/isoutputenabled"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/outputProvider": {
      "abstract": [
        {
          "text": "The block that the output unit will call to get audio to send to the output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AURenderPullInputBlock",
          "text": "AURenderPullInputBlock"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/outputProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputProvider"
        }
      ],
      "role": "symbol",
      "title": "outputProvider",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/outputprovider"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/setDeviceID(_:)": {
      "abstract": [
        {
          "text": "Sets the I/O hardware device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDeviceID"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@AUAudioObjectID",
          "text": "AUAudioObjectID"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/setDeviceID(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDeviceID:error:"
        }
      ],
      "role": "symbol",
      "title": "setDeviceID(_:)",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/setdeviceid(_:)"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/startHardware()": {
      "abstract": [
        {
          "text": "Starts the audio hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startHardware"
        },
        {
          "kind": "text",
          "text": "() "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/startHardware()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startHardwareAndReturnError:"
        }
      ],
      "role": "symbol",
      "title": "startHardware()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/starthardware()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/stopHardware()": {
      "abstract": [
        {
          "text": "Stops the audio hardware.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stopHardware"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/stopHardware()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stopHardware"
        }
      ],
      "role": "symbol",
      "title": "stopHardware()",
      "type": "topic",
      "url": "/documentation/audiotoolbox/auaudiounit/stophardware()"
    },
    "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock": {
      "abstract": [
        {
          "text": "A block to supply audio input to a render block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AURenderPullInputBlock"
        }
      ],
      "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AURenderPullInputBlock"
        }
      ],
      "role": "symbol",
      "title": "AURenderPullInputBlock",
      "type": "topic",
      "url": "/documentation/audiotoolbox/aurenderpullinputblock"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-Device",
      "generated": true,
      "identifiers": [
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceID",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/setDeviceID(_:)",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformInput",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformOutput",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isInputEnabled",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isOutputEnabled",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/inputHandler",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceInputLatency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceOutputLatency",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/startHardware()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/stopHardware()",
        "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock"
      ],
      "title": "Configuring the Device"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "outputProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-Device",
              "generated": true,
              "identifiers": [
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceID",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/setDeviceID(_:)",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformInput",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/canPerformOutput",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isInputEnabled",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/isOutputEnabled",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/inputHandler",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceInputLatency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/deviceOutputLatency",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/startHardware()",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AUAudioUnit/stopHardware()",
                "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock"
              ],
              "title": "Configuring the Device"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.apple.audiotoolbox/documentation/AudioToolbox/AURenderPullInputBlock",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@AURenderPullInputBlock",
                    "text": "AURenderPullInputBlock"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "outputProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1startHardware()/title",
          "value": "startHardwareAndReturnError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1startHardware()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startHardwareAndReturnError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1inputHandler/title",
          "value": "inputHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1inputHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/title",
          "value": "AURenderPullInputBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AURenderPullInputBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AURenderPullInputBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1outputProvider/title",
          "value": "outputProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1outputProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1stopHardware()/title",
          "value": "stopHardware"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1stopHardware()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stopHardware"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceOutputLatency/title",
          "value": "deviceOutputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceOutputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceOutputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1canPerformOutput/title",
          "value": "canPerformOutput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1canPerformOutput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canPerformOutput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceInputLatency/title",
          "value": "deviceInputLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceInputLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceInputLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1canPerformInput/title",
          "value": "canPerformInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1canPerformInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canPerformInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1isInputEnabled/title",
          "value": "inputEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1isInputEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1isOutputEnabled/title",
          "value": "outputEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1isOutputEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/title",
          "value": "AUAudioUnit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AUAudioUnit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceID/title",
          "value": "deviceID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1deviceID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "deviceID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1setDeviceID(_:)/title",
          "value": "setDeviceID:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.audiotoolbox~1documentation~1AudioToolbox~1AUAudioUnit~1setDeviceID(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDeviceID:error:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/audiotoolbox/auaudiounit/outputprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/audiotoolbox/auaudiounit/outputprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
