{
  "abstract": [
    {
      "text": "The raw value that represents the threading model.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/rawValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So14BLAS_THREADINGV8rawValues6UInt32Vvp",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rawValue"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt32V",
        "text": "UInt32"
      }
    ],
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "rawValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rawValue"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt32V",
              "text": "UInt32"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING": {
      "abstract": [
        {
          "text": "Constants that describe the BLAS and LAPACK threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS_THREADING"
        }
      ],
      "role": "symbol",
      "title": "BLAS_THREADING",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(_:)": {
      "abstract": [
        {
          "text": "Creates a threading model constant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading/init(_:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a threading model constant with an unsigned-integer value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading/init(rawvalue:)"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/rawValue": {
      "abstract": [
        {
          "text": "The raw value that represents the threading model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/rawValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "rawValue",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading/rawvalue"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MAX_OPTIONS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_MAX_OPTIONS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BLAS_THREADING",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MAX_OPTIONS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_MAX_OPTIONS"
        }
      ],
      "role": "symbol",
      "title": "BLAS_THREADING_MAX_OPTIONS",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading_max_options"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MULTI_THREADED": {
      "abstract": [
        {
          "text": "A constant that specifies that the Accelerate framework decides whether BLAS and LAPACK execute on single or multiple threads.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_MULTI_THREADED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BLAS_THREADING",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MULTI_THREADED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_MULTI_THREADED"
        }
      ],
      "role": "symbol",
      "title": "BLAS_THREADING_MULTI_THREADED",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading_multi_threaded"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_SINGLE_THREADED": {
      "abstract": [
        {
          "text": "A constant that specifies BLAS and LAPACK execute on a single thread only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_SINGLE_THREADED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@BLAS_THREADING",
          "text": "BLAS_THREADING"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_SINGLE_THREADED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BLAS_THREADING_SINGLE_THREADED"
        }
      ],
      "role": "symbol",
      "title": "BLAS_THREADING_SINGLE_THREADED",
      "type": "topic",
      "url": "/documentation/accelerate/blas_threading_single_threaded"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt32V": {
      "abstract": [
        {
          "text": "A 32-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt32",
      "type": "topic",
      "url": "/documentation/Swift/UInt32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-threading-model",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(_:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING/init(rawValue:)",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MULTI_THREADED",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_SINGLE_THREADED",
        "doc://com.apple.accelerate/documentation/Accelerate/BLAS_THREADING_MAX_OPTIONS"
      ],
      "title": "Specifying a threading model"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_SINGLE_THREADED/title",
          "value": "BLAS_THREADING_SINGLE_THREADED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_SINGLE_THREADED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING_SINGLE_THREADED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/title",
          "value": "BLAS_THREADING"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_MULTI_THREADED/title",
          "value": "BLAS_THREADING_MULTI_THREADED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_MULTI_THREADED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING_MULTI_THREADED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_MAX_OPTIONS/title",
          "value": "BLAS_THREADING_MAX_OPTIONS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1Accelerate~1BLAS_THREADING_MAX_OPTIONS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BLAS_THREADING_MAX_OPTIONS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/accelerate/blas_threading/rawvalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
