{
  "abstract": [
    {
      "text": "Sent when the user taps Cancel.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.addressbookui/documentation/AddressBookUI",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)ABPeoplePickerNavigationControllerDelegate(im)peoplePickerNavigationControllerDidCancel:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "peoplePickerNavigationControllerDidCancel"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
        "text": "ABPeoplePickerNavigationController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Address Book UI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "peoplePickerNavigationControllerDidCancel:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "peoplePickerNavigationControllerDidCancel(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationControllerDidCancel"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "peoplePicker"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
              "text": "ABPeoplePickerNavigationController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The people-picker navigation controller with which the user interacted.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "peoplePicker"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the delegate does not implement this method, the people picker will dismiss itself when the user taps cancel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Special-Considerations",
          "level": 3,
          "text": "Special Considerations",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Prior to iOS 8, the delegate was responsible for dismissing the people picker and this method was required.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.addressbookui/documentation/AddressBookUI": {
      "abstract": [
        {
          "text": "Access users’ contacts and display them in a graphical interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Address Book UI",
      "type": "topic",
      "url": "/documentation/addressbookui"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABPeoplePickerNavigationController",
          "type": "codeVoice"
        },
        {
          "text": " class (whose instances are known as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "people-picker navigation controllers",
              "type": "text"
            }
          ],
          "type": "strong"
        },
        {
          "text": ") implements a view controller that manages a set of views that allow the user to select a contact or one of its contact-information items from an address book.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationController"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationController"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerNavigationController",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontroller"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate": {
      "abstract": [
        {
          "text": "The ",
          "type": "text"
        },
        {
          "code": "ABPeoplePickerNavigationControllerDelegate",
          "type": "codeVoice"
        },
        {
          "text": " protocol describes the interface ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegates must adopt to respond to people-picker user events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ABPeoplePickerNavigationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "ABPeoplePickerNavigationControllerDelegate",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)": {
      "abstract": [
        {
          "text": "Called after a person has been selected by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:didSelectPerson:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:didSelectPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:didselectperson:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)": {
      "abstract": [
        {
          "text": "Called after a property has been selected by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:didSelectPerson:property:identifier:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:didselectperson:property:identifier:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)": {
      "abstract": [
        {
          "text": "Sent when the user selects a contact.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldContinueAfterSelectingPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)": {
      "abstract": [
        {
          "text": "Sent when the user selects one of a person’s properties.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldContinueAfterSelectingPerson"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABRecordRef",
          "text": "ABRecord"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "property"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABPropertyID",
          "text": "ABPropertyID"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@ABMultiValueIdentifier",
          "text": "ABMultiValueIdentifier"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontroller(_:shouldcontinueafterselectingperson:property:identifier:)"
    },
    "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)": {
      "abstract": [
        {
          "text": "Sent when the user taps Cancel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationControllerDidCancel"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
          "text": "ABPeoplePickerNavigationController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationControllerDidCancel(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "peoplePickerNavigationControllerDidCancel:"
        }
      ],
      "role": "symbol",
      "title": "peoplePickerNavigationControllerDidCancel(_:)",
      "type": "topic",
      "url": "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontrollerdidcancel(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-User-Events",
      "generated": true,
      "identifiers": [
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
        "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)"
      ],
      "title": "Responding to User Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "peoplePickerNavigationControllerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationControllerDidCancel:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.addressbookui/documentation/AddressBookUI",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-User-Events",
              "generated": true,
              "identifiers": [
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:)",
                "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationControllerDelegate/peoplePickerNavigationController(_:didSelectPerson:property:identifier:)"
              ],
              "title": "Responding to User Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "peoplePickerNavigationControllerDidCancel:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.addressbookui/documentation/AddressBookUI/ABPeoplePickerNavigationController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)ABPeoplePickerNavigationController",
                    "text": "ABPeoplePickerNavigationController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "peoplePicker"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The people-picker navigation controller with which the user interacted.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "peoplePicker"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:)/title",
          "value": "peoplePickerNavigationController:didSelectPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:didSelectPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)/title",
          "value": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:property:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:property:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:property:identifier:)/title",
          "value": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:didSelectPerson:property:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:didSelectPerson:property:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/title",
          "value": "ABPeoplePickerNavigationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)/title",
          "value": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationController(_:shouldContinueAfterSelectingPerson:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationController:shouldContinueAfterSelectingPerson:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/title",
          "value": "ABPeoplePickerNavigationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ABPeoplePickerNavigationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationControllerDidCancel(_:)/title",
          "value": "peoplePickerNavigationControllerDidCancel:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.addressbookui~1documentation~1AddressBookUI~1ABPeoplePickerNavigationControllerDelegate~1peoplePickerNavigationControllerDidCancel(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "peoplePickerNavigationControllerDidCancel:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontrollerdidcancel(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/addressbookui/abpeoplepickernavigationcontrollerdelegate/peoplepickernavigationcontrollerdidcancel(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
